>Carnegiea_gigantea 1067 bp 
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------ccgcgccgggggcaacccccggcgccgcaacgaaaccccggcgcgaac
cgcgccaaggaacacgaactcatggcgtgcccgcccgcgcccgttccgccggcgcgcggg
ggcggcacctgcccctacttaa-aacgtaacgactctcggcaacggatatttcggctcat
g--gtagacg-agcacctcgcaaactgcgatacttggtgtgaattgcagaatcccgtgaa
ccatcgagtctttgaacgcaagttgcgcccgaagccttccggccgagggcacgtctgcct
gggcgtcacgcatcgcgcctcccgccccc-cgcccgccgggggggg-----aggatgatg
gcctcccgcgccccagccggggcgcggctggcctaaaacgggagcccgcggcgacgagct
gcggcggcgattggtggtggacg-aggcctcaagtggccgccgtttgcatcgcgccgcgc
acgcacgccgccgggaagggctcgtcggaccctgacgtg--tgctggaagcacagaaccg
ttgcgaccccaggtcaggcggggctacccgctgagtttaagcatatcaataagcggagga
aaagaaacttacaaggattcccctagtaacggcgagcgaaccgggaagagcccagcttta
aaatcgggcggcctcgccgtccgaattgtagtctggagaagcgtcctctgcggcggaccg
ggcccaagtcccctggaaaggggcgccggagagggtgagagccccgtcgtgcccggaccc
tgtcgcaccacgagcctgtcgc--------------
>Cephalocereus_senilis 1067 bp 
------------------------------------------------------------
------------------------------------------------------------
-----------------------------caaggtttcctaggtaaggatcattgtcgaa
a-ctgcccagcagaaagacc-gcgaacatgt-ttaccccaacatgcggggaggggtgcct
cg-gctccctccccgcgccgggggcaacccccggcgcagcaacgaaaccccggcgcgaac
cgcgccaaggaacacgaaatcatggcgtgcccgcccgcgcccggtccgccggcgcgcggg
ggcggcacctgtccctacttaa-aaagtaaagactctcggcaacggatatctcggctatt
gacatcgatgaagaaagtagcgaaatgcgataattggtgtgaattgcagaat-ccgtgaa
ccatcgagtttttgaaagcaagttgcgcccgaagccttccggccgagggcacgtctgcct
gggcgtcaagcatcgcgcctccccccc---cgcccgccgggggaggg----aggatgttg
gcctcccgcgcccctgtcggggcgcggctggcctaaaacgggagcccgcggcgacgagcg
gcggcggcgattggtggtggacg-aggcctcaagtggccgccgtttgcatcgcgccgcgc
ccgcgcgccgccgggtagggctcgtcggaccctgacgtg--tgcaggaagcacaaaaccg
ttgcgaccccaggtagg--ggggctacccgctaaat------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------
>Myrtillocactus_schenckii 1067 bp 
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------aggatcattgtcgaa
acctgcccagcagaaagacccgcgaacgtgttttgccccaacatgcggggaggggtgcct
cg-gccccctccccgagccgggggcagcccccggcgcagcaacgaaaccccggcgcgaac
cgcgccaaggaacacgaactcatggcgtgcccgcccgcgcccggtccgccggcgcgcggg
ggcggcacctgtccctacttaagaacgtaacgactctcggcaacggatatctcggctctc
g-catcgatgaagaacgtagcgaaatgcaatacttggtgtgaattgcagaatcccgtgaa
ccatcgagtctttgaacgcaagttgcgcccgaagccttccggccgagggcacgtctgcct
gggcgtcacgcatcgcgcct-ccccccc--cgcc-----gggggggga---aggatgatg
gcctcccgcgccccgggcggggcgcggctggcctaaaacgggagcccgcggcgacgagct
gcggcggcgactggtggtggacg-aggcctcgagcggccgccgtttgcatcgcgccgcgc
acgcacgccgccggggcgggctcgtcggaccctgacgtgcttgctgaaagcacagaaccg
ttgcgaccccaggtcaggcggggctacccgctgagtttaagcatatcaataagcggagga
aaagaaacttacaaggattcccctagtaacggcgagcgaaccgggaagagcccagcttta
aaatcgggcggcctcgccgtccgaattgtagtctggagaagcgtcctctgcggcggaccg
ggcccaagtcccctggaaaggggcgccagagagggtgagagccccgtcgtgcccggaccc
tgtcgcaccacgag----------------------
>Neobuxbaumia_euphorbioides 1067 bp 
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------gaaggatcattgtcgaa
a-ctgcccagcagaaagacc-gcgaacatgt-ttaccccaacatgcggggaggggtgcct
cg-gccccctccccgcgccgggggcaacccccggcgccgcaacgaaaccccggcgcgaac
cgcgccaaggaacacgaactcatggcgtgcccgcccgcgcccggtccgccggcgcgcggg
ggcggcacctgtccctacttaa-aacgtaacgactctcggcaacggatatctcggctctc
t-catcgatgaagaacgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtgaa
ccatcgagtctttgaacgcaagttgcgcccgaagccttccggccgagggcacgtctgcct
gggcgtcacgcatcgcgcctccccccccctcgcccgcc-ggggggg-----aggatgatg
gcctcccgcgccccagccggggcgcggctggcctaaaacgggagcccgcggcgacgagcg
gcggcggcgattggtggtggacg-aggcctcaagtggccgccgtttgcatcgcgccgcgc
acgcacgccgccgggtagggctcgtcggaccctgacgtg--tgcaggaagcacagaa-cg
ttgcgacccca-------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------
>Neobuxbaumia_mezcalaensis 1067 bp 
------------------------------------------------------------
------------------------------------------------------------
-----------------tcacaaatttaaatatgtttattgcggaaggatcattgtcgaa
a-ctgcccagcagaaagacc-gcgaacatgt-ttaccccaacatgcggggaggggtgcct
cg-gccccctccccgcgccgggggcaacccccggcgccgcaacgaaaccccggcgcgaac
cgcgccaaggaacacgaactcatggcgtgcccgcccgcgcccggcccgccggcgcgcggg
ggcggcacctgtccctacttaa-aacgtaacgactctcggcaacggatatctcggctctc
g-catcgatgaagaacgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtgaa
ccatcgagtctttgaacgcaagttgcgcccgaagccttccggccgagggcacgtctgcct
gggcgtcacgcatcgcgcctccccccc---tgcccgcc-ggggggg-----aggaggatg
gcctcccgcgcccctgccggggcgcggctggcctaaaacgggagcccgcggcgacgagcg
gcggcggcgattggtggtggacg-aggcctcaagtggccgccgtttgcatcgcgccgcgc
acgcgcgccgccgggtagggctcgtcggaccctgacgtg--tgcaggaagcacaaaa-cg
ttgcgaccccagtcaggcgggggctacccgctgaattt----------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------
>Neobuxbaumia_multiareolata 1067 bp 
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------gaaggatcattgtcgaa
a-ctgcccagcagaaagacc-gcgaacatgt-ttaccccaacatgcggggaggggtgccc
cg-gccccctccccgcgccgggggcaacccccggcgccgcaacgaaaccccggcgcgaac
cgcgccaaggaacacgaactcatggcgtgcccgcccgcgcccggtccgccggcgcgcggg
ggcggcacctgtccctacttaa-aacgtaacgactctcggcaacggatatctcggctctc
t-catcgatgaagaacgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtgaa
ccatcgagtctttgaacgcaagttgcgcccgaagccttccggccgagggcacgtctgcct
gggcgtcacgcatcgcgcctcccccccc--tgcccgccgggggggg-----aggatgatg
gcctcccgcgcccctgtcggggcgcggctggcctaaaacgggagcccgcggcgacgagcg
gcggcggcgattggtggtggacg-aggcctcaagtggccgccgtttgcatcgcgccgcgc
ccgcgcgccgccgggtagggctcgtcggaccctgacgtg--tgcaggaagcacaaaaccg
ttgcgaccccagtcaggcggggctacccctgaatttaagca-------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------
>Neobuxbaumia_polylopha 1067 bp 
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------ctgcggaaggatcattgtcgaa
a-ctgcccagcagaaagacc-gcgaacatgt-ttaccccaacatgcggggaggggtgcct
cg-gccccctccccgcgccgggggcaacccccggcgcagcaacgaaaccccggcgcgaac
cgcgccaaggaacacgaactcatggcgtgcccgcccgcgcccggtccgccggcgcgcggg
ggcggcacctgtccctacttaa-aacgtaacgactctcggcaacggatatctcggctctc
g-catcgatgaagaacgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtgaa
ccatcgagtctttgaacgcaagttgcgcccgaagccttccggccgagggcacgtctgcct
gggcgtcacgcatcgcgcctccccccct--cgcccgccgggggggg-----gagaggttg
gccctccgcgcccctgccggggcgcggctggcctaaaacgggagcccgcggcaacaagcg
gcggcggcaattggtggtggacg-aggcctcaaatggccgccgtttgcatcgcgccgcgc
acacacaccgccgggtagggctcgtcggaccctgatatg--tgcaggaaacacaaaaccg
ttgcaaccccagtcaggcgggggctacccgctgaatttaagcatat--------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------
>Neobuxbaumia_scoparia 1067 bp 
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------cggaaggatcattgtcgaa
a-ctgcccagcagaaagacc-gcgaactttt-ttaccccaacatgcggggaggggtgccc
cg-gccccctccccgcgccgggggcaacccccggcgccgcaacgaaaccccggcgcgaac
cgcgccaaggaacacgaactcatggcgtgcccgcccgcgcccggtccgccggcgcgcggg
ggcggcacctgtccctacttaa-aacgtaacgactctcggcaacggatatctcggctctc
g-catcgatgaagaacgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtgaa
ccatcgagtctttgaacgcaagttgcgcccgaagccttccggccgagggcacgtctgcct
gggcgtcacgcatcgcgcctcccccccc--tgcccgccgggggggg-----aggatgatg
gcctcccgcgcccctgccggggcgcggctggcctaaaacgggagcccgcggcggcgagcg
gcggcggcgattggtggtggacg-aggcctcaagtggccgccgtttgcatcgcgccgcgc
acgcgcgccgccgggtagggctcgtcggaccctgacgtg--tgcaggaagcacaaaa-cg
ttgcgaccccagtcag--------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------
>Neobuxbaumia_tetetzo 1067 bp 
------------------------------------------------------------
------------------------------------------------------------
----------------------------------catgggacggaaggatcattgtcgaa
a-ctgcccagcagaaagacc-gcgaacatgt-ttaccccaacatgcggggaggggtgccc
cg-gccccctgcccgcgccgggggcaacccccggcgccgcaacgaaaccccggcgcgaac
cgcgccaaggaacacgaactcatggcgtgcccgcccgcgcccggcccgccggcgcgcggg
ggcggcacctgtccctacttaa-aacgtaacgactctcggcaacggatatctcggctctc
g-catcgatgaagaacgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtgaa
ccatcgagtctttgaacgcaagttgcgcccgaagccttccggccgagggcacgtctgcct
gggcgtcacgcatcgcgcctc---ccccc-cgcccgccggggggg------aggaggatg
gcctcccgcgcccctgccggggcgcggctggcctaaaacgggagcccgcggcgacgagcg
gcggcggcgattggtggtggacg-aggcctcaagtggccgccgtttgcatcgcgccgcgc
acgcgcgccgccgggtagggctcgtcggaccctgatgtg--tgcaggaagcacaaaaccg
ttgcgaccccagtca-ggcggggctacccgctgagtttaagcatatcaataagcggagga
aaagaaacttacaaggattcccctagtaacggcgagcgaaccgggaagagcccagcttta
aaatcgggcggcctcgccgtccgaattgtagtctggagaagcgtcctctgcggcggaccg
ggcccaagtcccctggaaaggggcgccagagagggtgagagccccgtcgtgcccggaccc
tgtcgcaccacgagggctgtgcca------------
>Pachycereus_fulviceps 1067 bp 
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------ctgcggaaggatcattgtcgaa
a-ctgcccagcagaaagacc-gcgaacatgt-ttaccccaacatgcggggaggggtgcct
cg-gccccctccccaagccgggggcaacccccggcgccgcaacgaaaccccggcgcgaac
cgcgccaaggaacacgaactcatggcgtgcccgcccgcgcccggtccgccggcgcgcggg
ggcggcacctgtccctacttaa-aacgtaacgactctcggcaacggatatctcggctctc
g-catcgatgaagaacgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtgaa
ccatcgagtctttgaacgcaagttgcgcccgaagccttccggccgagggcacgtctgcct
gggcgtcacgcatcgcgcctc---ccccc-cgcccgccggggggga-----aggatgatg
gcctcccgcgcccctgtcggggcgcggctggcctaaaacgggagcccgcggcgacgagct
gcggcggcgattggtggtggacg-aggcctcaagtggccgccgtttgcatcgcgccgcgc
acgcgcgccgccggggagggctcgtcggaccctgacgtg--tgtgggaagcacaaaaccg
ttgcgaccccagtca-ggcggggccacccgctgagtttaagcatatcaataagcggagga
aaagaaacttacaaggattcccctagtaacggcgagcgaaccgggaagagcccagcttta
aaatcgggcggcctcgccgtccgaattgtagtctggagaagcgtcctctgcggcggaccg
ggcccaagtcccctggaaaggggcgccagagagggtgagagccccgtcgtgcccggaccc
tgtcgcaccacgagggctgt----------------
>Pachycereus_gatesii 1067 bp 
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------------tgtcgaa
acctgcccagcagaaagacc-gcgaacatgt-ttaccccaacatgcggggaggggtgcct
cg-gccccctccccgcgccgggggcaacccccggcgccgcaacgaaaccccggcgcgaac
cgcgccaaggaacacaaactcatggagtgcccgcccgcacccggtccgccggcgcgcggg
ggcggcacctgtccctactgaa-aacgtaacgactctcggcaacggatatctcggctctc
g-catcgatgaagaacgtagcgaaatgcgatacttggtgtgaattgcagaat-ccgtgaa
ccatcgagtctttgaacgcaagttgcgcccgaagccttcgggccgagggcacgtctgcct
gggcgtcacgcatcgcgcctccccccccc-cgcccgcgggggggga-----aggatgatg
gcctcccgcgccccggccggggcgcggctggcctaaaacgggagcccgcggcgacgagct
gcggcggcgattggtggtggacg-aggcctcaggtgggcgccgtttgcatcgcgccgcgc
acgcacgccgccgggaagggctcgtcggaccctgacgtg--tgctggaagcacaaaaccg
ttgcgaccccaggtcaggcggggctacccgctgagtttaagcatatcaataagcggagga
aaagaaacttaccaggattcccctagtagcggcgagcgaaccgggaagagcccagcttta
aaatcgggcggcctcgccgtccgaattgtagtctggagaagcgtcctctgcggcggaccg
ggcccaagtcccctggaaaggggcgccagagagggtgagagccccgtcgtgcccggaccc
tgtcgcaccacgaggcgctttccccattcgggtttt
>Pachycereus_gaumeri 1067 bp 
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------gcggaaggatcattgtcgaa
acctgcccagcagaaagacc-gcgaacatgt-ttaccccaacatgcggggaggggtgcct
cg-gccccctccccgcgccgggggcaacccccggcgccgcaacgaaaccccggcgcgaac
cgcgccaaggaacacgaactcatggagtgcccgcccgcgcccggtccgccggcgcgcggg
ggcggcacctgtccctactgaa-aacgtaacgactctcggcaacggatatctcggctctc
g-catcgatgaagaacgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtgaa
ccatcgagtctttgaacgcaagttgcgcccgaagccttccggccgagggcacgtctgcct
gggcgtcacgcatcgcgcctcc--ccccc-cgcccgccggggggggggggaaggatgatg
gcctcccgcgccccggccggggcgcggctggcctaaaacgggagcccgcggcgacgagtt
gcggcggcgattggtggtggacg-aggcctcaagtggccgccgtttgcatcgcgccgcgc
acgcacgccgccgggaagggctcgtcggaccctgacgtg--tgctggaagcacaaaa-cg
ttgcgaccccagtca-ggcggg--------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------
>Pachycereus_grandis 1067 bp 
----------------------tacgattgaatggtcc-ggtgaagtgttcggatcgcgg
cgacgtgggcggttcgccgccggcgacgtcgcgagaagtccactgaaccttatcatttag
aggaaggagaagtcgtaacaaggtttccgtaggtgaacctgcggaaggatcattgtcgaa
acctgcccagcagaaagacc-gcgaacatgt-ttaccccaacatgcggggaggggtgcct
cg-gccccctccccgcgccgggggcaacccccggcgccgcaacgaaaccccggcgcgaac
cgcgccaaggaacacgaactcatggcgtgcccgcccgcgcccggtccgccggcgcgcggg
ggcggcacctgtccctacttaa-aacgcaacgactctcggcaacggatatctcggctctc
g-catcgatgaagaacgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtgaa
ccatcgagtctttgaacgcaagttgcgcccgaagccttccggccgagggcacgtctgcct
gggcgtcacgcatcgcgcctcccgccccc-cgcccgccgggggggggg---aggatgatg
gcctcccgcgccccagccggggcgcggctggcctaaaacgggagcccgcggcgacgagct
gcggcggcgattggtggtggacg-aggcctcaagtggccgccgtttgcatcgcgccgcgc
acgcacgccgccgggaagggctcgtcggaccctgacgtg--tgctggaagcacagaaccg
ttgcgaccccagtcagggcgg---------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------
>Pachycereus_hollianus 1070 bp 
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------ctgcgg-aagatcattgtcgaa
a-ctgcccagcagaaaga-ccgcgaacatgttttgccccaacatgcggggaggggtgccy
cg-gccccctccccgagccgggggcagcccccggcgcagcaacgaaaccccggcgcgaac
cgcgccaaggaacacgaactcatggcgtgcccgcccgcgcccggtccgccggcgcgcggg
ggcggcacctgtccctacttaagaacgtaacgactctcggcaacggatatctcggctctc
g-catcgatgaagaacgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtgaa
ccatcgagtctttgaacgcaagttgcgcccgaagccttccggccgagggcacgtctgctt
gggcgtcacgcatcgcgcct-ccccccc--cgcccgcc--ggggggga---aggatgatg
gcctcccgcgccccggtcggggcgcggctggcccaaaacgggagcccgcggcgacgagct
gcggcggcgattggtggtggacg-aggcctcgagtggccgccgtttgcatcgcgccgcgc
acgcacgccgccggggcgggctcgtcggaccctgacgtgtttgctgaaagcacagaaccg
ttgcgaccccaggtcaggcggggctacccgctgagtttaagcatatcaataagcggagga
aaagaaacttacaaggattcccctagtaacggcgagcgaaccgggaagagcccagcttta
aaatcgggcggcctcgccgtccgaattgtagtctggagaagcgtcctctgcggcggaccg
ggcccaagtcccctggaaaggggcgccagagagggtgagagccccgtcgtgcccggaccc
tgtcgcaccacgag----------------------
>Pachycereus_lepidanthus 1067 bp 
----------------------accgattgaatggtcc-ggtgaagtgttcggatcgcgg
cgacgtgggcggttcgccgccggcgacgtcgcgagaagtccactgaaccttatcatttag
aggaaggagaactcgt-aacaggtttccgtatgtgaacctgcgg-aagatcattgtcgaa
a-ctgcccagcagaaaga-ccgcgaacatgtcttgccccaacatgcggggaggggtgcct
cgtgccccctccccgagccgggggcagcccccggcgcagcaacgaaaccccggcgcgaac
cgcgccaaggaacacgaactcatggcgtgcccgcccgcgcccggtccgccggcgcgcggg
ggcggcacccgtccctacttaaaaacgtaacgactctcggcaacggatatctcggctctc
g-catcgatgaagaacgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtgaa
ccatcgagtctttgaacgcaagttgcgcccgaagccttccggccgagggcacgtctgcct
gggcgtcacgcatcgcgcct--cccccc--cgcccgcc----ggggga---aggatgatg
gcctcccgcgccccggccggggcgcggctggcccaaaacgggagcccgcggcgacgagct
gcggcggcgattggtggtggacg-aggcctcgagtggccgccgtttgcatcgcgccgcgc
acgcacgccgccggggcgggctcgtcggaccctgacgtgtttgctgaaagcacagaaccg
ttgcgaccccaggtcaggcggggctacccgctgagtttaagcatatcaataagcggagga
aaagaaacttacaaggattcccctagtaacggcgagcgaaccgggaagagcccagcttta
aaatcgggcggcctcgccgtccgaattgtagtctggagaagcgtcct-tgcggcggaccg
ggcccaagtcccctggaaaggggcgccagagagggtgagagccccgtcgtgcccggaccc
tgtcgcaccacgagcgtgt-----------------
>Pachycereus_marginatus 1067 bp 
---------------------------ttgaatggtcc-ggtgaagtgttcggatcgcgg
cgacgtgggcggttcgccgccggcgacgtcgcgagaagtccactgaaccttatcatttag
aggaaggagaagtcgtaacaaggtttccgtaggtgaacctgcggaaggatcattgtcgaa
acctgcccagcagaaagacc-gcgaacatgt-tcaccccaacatgcgggaaggggtgcct
cg-gccccctccccgcgcccggggcaacccccggcgcagcaacgaaaccccggcgcgaac
cgcgccaaggaacacgaacgcatggcgtgcccgcccgcgcccggtccgccggcgcgcggg
ggcggcacctgtcccaactgaa-aacgtaacgactctcggcaacggatatctcggctctc
g-catcgatgaagaacgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtgaa
ccatcgagtctttgaacgcaagttgcgcccgaagccttccggccgagggcacgtctgcct
gggcgtcacgcatcgcgcctcc--ccccc-cgcccgccgggggggggggggaggatgatg
gcctcccgcgccccggccggggcgcggctggcctaaaacgggagcccgcggcgacgagct
gcgacggcgattggtggtggacg-aggcctcagatggccgccgtttgcatcgcgccgcgc
acgcacgccgccgggaagggctcgtcggacccggacgtg--tgctggaagcacaaaaccg
ttgcgaccccaggtcaggcggggctacccgctgagtttaagcatatcaataagcggagga
aaagaaacttacaaggattcccctagtaacggcgagcgaaccgggaagagcccagcttta
aaatcgggcggcctcgccgtccgaattgtagtctggagaagcgtcctctgcggcggaccg
ggcccaagtcccctggaaaggggcgccagagagggtgagagccccgtcgtgcccggaccc
tgtcgcaccacgaggcgctt----------------
>Pachycereus_militaris 1067 bp 
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------aaggatcattgtcgaa
acctgcccagcagaaagacc-gcgaacatgt-tttccccaacatgcggggaggggtgcct
cg-gccccctccccgcgccgggggcaacccccggcgccgcaacgaaaccccggcgcgaac
cgcgccaaggaacacgaactcatggcgtgcccgcccgcgcccggtccgccggcgcgcggg
ggcggcacctgtccctacttaa-aacgtaacgactctcggcaacggatatctcggctctc
g-catcgatgaagaacgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtgaa
ccatcgagtctttgaacgcaagttgcgcccgaagccttccggccgagggcacgtctgcct
gggcgtcacgcatcgcgcctcc--ccccc-cgcccgccggggggggggggaaggatgatg
gcctcccgcgccccggccggggcgcggctggcctaaaacgggagcccgcggcggcgagct
gcggcggcgattggtggtggacg-aggcctcgagtggccgccgtttgcatcgcgccgcgc
acgcacgccgccggggagggctcgtcggaccctgacgtg--tgctgaaagcacagaaccg
ttgcgaccccagtca-ggcggggctacccgctgagtttaagcatatcaataagcggagga
aaagaaacttacaaggattcccctagtaacggcgagcgaaccgggaagagcccagcttta
aaatcgggcggcctcgccgtccgaattgtagtctggagaagcgtcctctgcggcggaccg
ggcccaagtcccctggaaaggggcgccagagagggtgagagccccgtcgtgcccggaccc
tgtcgcaccacgaggcgcgt----------------
>Pachycereus_pringlei 1067 bp 
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------cggaaggatcattgtcgaa
acctgcccagcagaaagacc-gcgaacatgt-ttaccccaacatgcggggaggggtgcct
cg-gccccctccccgcgccgggggcaacccccggcgccgcaacgaaaccccggcgcgaac
cgcgccaaggaacacgaactcatggcgtgcccgcccgcgcccggtccgccggcgcgcggg
ggcggcacctgtccctacttaa-aacgtaacgactctcggcaacggatatctcggctctc
g-catcgatgaagaacgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtgaa
ccatcgagtctttgaacgcaagttgcgcccgaagccttccggccgagggcacgtctgcct
gggcgtcacgcatcgcgcctcccgccccc-cgcccgccggggggggg----aggatgatg
gcctcccgcgccccagccggggcgcggctggcctaaaacgggagcccgcggcggcgagct
gcggcggcgattggtggtggacg-aggcctcaagtggccgccgtttgcatcgcgccgcgc
acgcacgccgccgggaagggctcgtcggaccctgacgtg--tgctggaagcacagaaccg
ttgcgaccccagtcagggcggggctacccgctgagtttaagcatatcaataagcggagga
aaagaaacttacaaggattcccctagtaacggcgagcgaaccgggaagagcccagcttta
aaatcgggcggcctcgccgtccgaattgtagtctggagaagcgtcctctgcggcggaccg
ggcccaagtcccctggaaaggggcgccagagagggtgagagccccgtcgtgcccggaccc
tgtcgcaccacgaggcgct-----------------
>Pachycereus_schottii 1067 bp 
----------------------tacgattgaatggtcc-ggtgaagtgttcggatcgcgg
cgacgtgggcggttcgccgccggcgacgtcgcgagaagtccactgaaccttatcatttag
aggaaggagaagtcgtaacaaggtttccgtaggtgaacctctggaaggatcattgtcgaa
acctgcccagcagaaagaccggcgaacatgt-ttaccccaacatgcggggaggggtgcct
cg-gccccctccccgcgccgggggcaacccccggcgccgcaacgaaaccccggcgcgaac
cgcgccaaggaacacaaactcatggagtgcccgcccgcgcccggtccgccggcgcgcggg
ggcggcacctgtccctactgaa-aacgtaacgactctcggcaacggatatctcggctctc
g-catcgatgaagaacgtagcgaaatgcgatacttggtgtgaattgcagaat-ccgtgaa
ccatcgagtctttgaacgcaagttgcgcccgaagccttcgggccgagggcacgtctgcct
gggcgtcacgcatcgcgcctccccccccc-cgcccgcgggggggga-----aggatgatg
gcctcccgcgccccggccggggcgcggctggcctaaaacgggagcccgcggcgacgagct
gcggcggcgattggtggtggacg-aggcctcaggtgggcgccgtttgcatcgcgccgcgc
acgcacgccgccgggaagggctcgtcggaccctgacgtg--tgctggaagcacaaaaccg
ttgcgaccccaggtcaggcggggctacccgctgagtttaagcatatcaataagcggagga
aaagaaacttaccaggattcccctagtagcggcgagcgaaccgggaagagcccagcttta
aaatcgggcggcctcgccgtccgaattgtagtctggagaagcgtcctctgcggcggaccg
ggcccaagtcccctggaaaggggcgccagagagggtgagagccccgtcgtgcccggaccc
tgtcgcaccacgaggcgc------------------
>Pachycereus_tepamo 1067 bp 
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------tcattgtcgaa
acctgcccagcagaaagacc-gcgaacatgt-ttaccccaacatgcggggaggggtgcct
cg-gccccctccccgcgccgggggcaacccccggcgccgcaacgaaaccccggcgcgaac
cgcgccaaggaacacgaactcatggcgtgcccgcccgcgcccggtccgccggcgcgcggg
ggcggcacctgtccctacttaa-aacgcaacgactctcggcaacggatatctcggctctc
g-catcgatgaagaacgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtgaa
ccatcgagtctttgaacgcaagttgcgcccgaagccttccggccgagggcacgtctgcct
gggcgtcacgcatcgcgcctcccgccccc-cgcccgccggggggggg----aggatgatg
gcctcccgcgccccagccggggcgcggctggcctaaaacgggagcccgcggcgacgagct
gcggcggcgattggtggtggacg-aggcctcaagtggccgccgtttgcatcgcgccgcgc
acgcacgccgccgggaagggctcgtcggaccctgacgtg--tgctggaagcacagaaccg
ttgcgaccccagtca-ggcggggctacccgctgagtttaagcatatcaataagcggagga
aaagaaacttacaaggattcccctagtaacggcgagcgaaccgggaagagcccagcttta
aaatcgggcggcctcgccgtccgaattgtagtctggagaagcgtcctctgcggcggaccg
ggcccaagtcccctggaaaggggcgccagagagggtgagagccccgtcgtgcccggaccc
tgtcgcaccacgaggcg-------------------
>Pachycereus_weberi 1067 bp 
tgtacacactgcccgtcgctcctacgattgaatggtcc-ggtgaagtgttcggatcgcgg
cgacgtgggcggttcgccgccggcgacgtcgcgagaagtccactgaaccttatcatttag
aggaaggagaagtcgtaacaaggtttccgtaggtgaacctgcggaaggatcattgtcgaa
acctgcccagcagaaagacc-gcgaacatgt-ttaccccaacatggggggaggggtgccc
cg-gccccctccccgcgccgggggcaacccccggcgccgcaacgaaaccccggcgcgaac
cgcgccaaggaacacgaactcatggcgtgcccgcccgcgcccggtccgccggcgcgcggg
ggcggcacctgtccctacttaa-aacgcaacgactctcggcaacggatatctcggctctc
g-catcgatgaagaacgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtgaa
ccatcgagtctttgaacgcaagttgcgcccgaagccttccggccgagggcacgtctgcct
gggcgtcacgcatcgcgcctcccgccccc-cgcccgccgggggggggg---aggatgatg
gcctcccgcgccccagccggggcgcggctggcctaaaacgggagcccgcggcggcgagct
gcggcggcgattggtggtggacg-aggcctcgagtggccgccgtttgcatcgcgccgcgc
acgcacgccgccgggaagggctcgtcggaccctgacgtg--cgctggaagcacagaaccg
ttgcgaccccagtcaggcgg----------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------
>Stenocereus_aragonii 1067 bp 
------------------------------------------------------------
------------------------------------------------------------
---------------taacaaggtttccgtaggtgaacctgcggaaggatcattgtcgaa
acctgcccagcagaaagacc-gcgaacatgt-ttaccccaacatgcggggaggggcgcct
cg-gccccctgcccgcgccgggggcaacccccggcgcagcaacgaaaccccggcgcgaac
cgcgccaaggaacacgaactcatggcgtgcccgcccgcgcccggtccgccggcgcgcggg
ggcggcacctgtccctacttaa-aacgtaacgactctcggcaacggatatctcggctctc
g-catcgatgaagaacgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtgaa
ccatcgagtctttgaacgcaagttgcgcccgaagccttccggccgagggcacgtctgcct
gggcgtcacgcatcgcgcctcccgccccc-cgcccg-c-cgggggggg---aggatgatg
gcctcccgcgccccagccggggcgcggctggcctaaaacgggagcccgcggcgacgagct
gcggcggcgattggtggtggacgaaggcctcaagtggccgccgtttgcatcgcgccgcgc
acgcacgccgccggggagggctcgtcggaccctgacgtg--tgctggaagcacagaaccg
ttgcgaccccagtcagg-------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------
>Stenocereus_chrysocarpus 1067 bp 
---------------------------ttgaatggtccgggtgaagtgttcggatcgcgg
cgacgtgggcggttcgccgccggcgacgtcgcgagaagtccactgaaccttatcatttag
aggaaggagaagtcgtaacaaggtttccgtaggtgaacctgcggaaggatcattgtcgaa
acctgcccagcagaaagacccgcgaacatgttctgccccaacatgcggggaggggcgcct
cg-gccccctccccgagccgggggcagcccccggcgcagcaacgaaaccccggcgcgaac
cgcgccaaggaacacgaactcatggcgtgcccgcccgcgcccggtccgccggcgcgcggg
ggcggcacctgtccctacttaagaacgtaacgactctcggcaacggatatctcggctctc
g-catcgatgaagaacgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtgaa
ccatcgagtctttgaacgcaagttgcgcccgaagccttccggccgagggcacgtctgcct
gggcgtcacgcatcgcgcctccccccccgcccgcc----gggggggga---aggatgatg
gcctcccgcgccccggccggggcgcggctggcctaaaacgggagcccgcggcgacgagct
gcggcggcgactggtggtggacg-aggcctcgagcggccgccgtttgcatcgcgccgcgc
acgcacgccgccggggcgggctcgtcggaccctgacgtgtttgctgaaagcacagaaccg
ttgcgaccccagg-----------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------
>Stenocereus_eichlamii 1067 bp 
------------------------------------------------------------
------------------------------------------------------------
----------------aaaaaagtttccgtaggtgaacctgcggaaggatcattgtcgaa
acctgcccagcagaaagacc-gcgaacatgt-ttaccccaacatgcggggaggggcgcct
cg-gccccctgcccgcgccgggggcaacccccggcgcagcaacgaaaccccggcgcgaac
cgcgccaaggaacacgaactcatggcgtgcccgcccgcgcccggtccgccggcgcgcggg
ggcggcacctgtccctacttaa-aacgtaacgactctcggcaacggatatctcggctctc
g-catcgatgaagaacgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtgaa
ccatcgagtctttgaacgcaagttgcgcccgaagccttccggccgagggcacgtctgcct
gggcgtcacgcaccgcgcctcccgccccc-cgcccgcc-cgggggggg---aggatgatg
gcctcccgcgccccagccggggcgcggctggcctaaaacgggagcccgcggcgacgagct
gcggcggcgattggtggtggacgaaggcctcaagtggccgccgtttgcatcgcgccgcgc
acgcacgccgccggggagggctcgtcggaccctgacgtg--tgctggaagcacagaaccg
ttgcga-cccagtcaggcggggctaccc--------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------
>Stenocereus_fricci 1067 bp 
-----------------------acgattgaatggtcc-ggtgaagtgttcggatcgcgg
cgacgtgggcggttcgccgccggcgacgtcgcgagaagtccactgaaccttatcatttag
aggaaggagaagtcgtaacaaggtttccgtaggtgaacctgcggaaggatcattgtcgaa
acctgcccagcagaaagacccgcgaacgtgttttgccccaacatgcggggaggggcgcct
cg-gccccctccccgagccgggggcagcccccggcgcagcaacgaaaccccggcgcgaac
cgcgccaaggaacacgaactcatggcgtgcccgcccgcgcccggtccgccggcgcgcggg
ggcggcacctgtccctacttaagaacgtaacgactctcggcaacggatatctcggctctc
g-catcgatgaagaacgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtgaa
ccatcgagtctttgaacgcaagttgcgcccgaagccttccggccgagggcacgtctgcct
gggcgtcacgcatcgcgcctccccccccccgccccccgggggggggga---aggatgatg
gcctcccgcgccccggtcggggcgcggctggcctaaaacgggagcccgcggcgacgagct
gcggcggcgactggtggtggacg-aggcctcgagcggccgccgtttgcatcgcgccgcgc
acgcacgccgccggggcgggctcgtcggaccctgacgtgtttgctgaaagcacagaaccg
ttgcgaccccaggt----------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------
>Stenocereus_martinezii 1067 bp 
------------------------------------------------------------
------------------------------------------------------------
-gaaggagaagtcgta-acaaggtttccgtaggtgaacctgcggaaggatcattgtcgaa
acctgcccagcagaaagacccgcgaacatgttttgccccaacatgcggggaggggcgcct
cg-gccccctccccgagccgggggcagcccccggcgcagcaacgaaaccccggcgcgaac
cgcgccaaggaacacgaactcatggcgtgcccgcccgcgcccggtccgccggcgcgcggg
ggcggcacctgtccctacttaagaacgtaacgactctcggcaacggatatctcggctctc
g-catcgatgaagaacgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtgaa
ccatcgagtctttgaacgcaagttgcgcccgaagccttccggccgagggcacgtctgcct
gggcgtcacgcatcgcgcct-ccccccc--cgcccgccggggggggga---aggatgatg
gcctcccgcgccccggccggggcgcggctggcctaaaacgggagcccgcggcgacgagct
gcggcggcgactggtggtggacg-aggcctcgagcggccgccgtttgcatcgcgccgcgc
acgcacgccgccggggcgggctcgtcggaccctgacgtgtttgctgaaagcacagaaccg
ttgcgaccccaggtcaggcggggctacccgctgagtttaagcatatcaataagcggagga
aaagaaacttacaaggattcccctagtaacggcgagcgaaccgggaagagcccagcttta
aaatcgggcggcctcgccgtccgaattgtagtctggagaagcgtcctctgcggcggaccg
ggcccaagtcccctggaaaggggcgccagagagggtgagagccccgtcgtgcccggaccc
tgtcgcaccacgaggcg-------------------
>Stenocereus_stellatus 1067 bp 
------------------------------------------------------------
------------------------------------------------------------
-----------------acaaggtttccgtaggtgaacctgcggaaggatcattgtcgaa
acctgcccagcagaaagacccgcgaacgtgttttgccccaacatgcggggaggggcgcct
cg-gccccctccccgagccgggggcagcccccggcgcagcaacgaaaccccggcgcgaac
cgcgccaaggaacacgaactcatggcgtgcccgcccgcgcccggtccgccggcgcgcggg
ggcggcacctgtccctacttaagaacgtaacgactctcggcaacggatatctcggctctc
g-catcgatgaagaacgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtgaa
ccatcgagtctttgaacgcaagttgcgcccgaagccttccggccgagggcacgtctgcct
gggcgtcacgcatcgcgcctcccccccc--cgcccgccggggggggga---aggatgatg
gcctcccgcgccccggacggggcgcggctggcctaaaacgggagcccgcggcggcgagct
gcggcggcgactggtggtggacg-aggcctcgagcggccgccgtttgcatcgcgccgcgc
acgcacgccgccggggcgggctcgtcggaccctgacgtgtttgctgaaagcacagaaccg
ttgcgaccccaggtcaggcggggctacccgctgagtttaagcatatcaataagcggagga
aaagaaacttacaaggattcccctagtaacggcgagcgaaccgggaagagcccagcttta
aaatcgggcggcctcgccgtccgaattgtagtctggagaagcgtcctctgcggcggaccg
ggcccaagtcccctggaaaggggcgccagagagggtgagagccccgtcgtgcccggaccc
tgtcgcaccacgagg---------------------
