>Aspergillus_fumigatus_AY373851_1 Aspergillus_fumigatus_AY373851.1 803 bp 
----------------------------------------tccgtaggtg-aacctgcgg
------------------------------------------------------------
---------------aaggatcattaccgagtga-gggccctctggg-tcca--------
---------------------------acct--cccacccgtgtctatc-----------
-----gtaccttgttgcttcggcgggcccgccgtttcgacggccgccggggaggccttg-
-------cgcccccgggcccgcgcccgccgaagaccccaacatgaacgctgttct----g
aaagtatgcagtctgagttgatta------------------------------------
--tcgt--aatcagtt------------aaaactttcaacaacggatctcttggttccgg
catcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaattcagt-gaat
cat-cgagtctttg-aac-gcacattgcgccccct-gg------tattcc-ggggggcat
gcctg-tccgagcgtcattgctgcc-ctcaagcacgg-----------------------
----------cttgtgtgt---tgggc--ccccgtccccc-tctcccgggggacgggccc
g-aaaggcagcgg-----------------------------------------------
----------------------------------------------------cggcaccg
cgtccggtcctcgagcgtatggggctttgtcacctgctc-tgta---ggcccggccggcg
cc-agccga---------------------------------------------------
-----------c-acccaactttatttttctaaggttgacctcggatca-ggtagggata
cccgctgaa-ctt---aagcatatcaataagcggaggaaaagaaaccaacagggattgcc
tc---------------------------------------------------------
>Aspergillus_sp__AM176671_1_deep_sea_sediment Aspergillus_sp._AM176671.1_deep_sea_sediment 803 bp 
------------------------------------------------------------
------------------------------------------------------------
---------------aaggatcattaccgagtga-gggccctctggg-tcca--------
---------------------------acct--cccacccgtgtttatt-----------
-----ttaccttgttgcttcggcgggcccgcc--ttaactggccgccggg--gggctta-
-------cgcccccgggcccgcgcccgccgaagacacc--ctcgaactctgtct------
gaagattgtagtctgag-tgaaaa------------------------------------
--tata--aattattt------------aaaactttcaacaacggatctcttggttccgg
catcgatgaagaacgcagcgaaatgcgatacgtaatgtgaattgca-aattcagt-gaat
cat-cgagtctttg-aac-gcacattgcgccccct-gg------tattcc-ggggggcat
gcctg-tccgagcgtcattgctgcc-ctcaagcacgg-----------------------
----------cttgtgtgt---tggg---ccccgtcctccgat-cccgggggacgggccc
g-aaaggcagcgg-----------------------------------------------
----------------------------------------------------cggcaccg
cgtccggtcctcgagcgtatggggctttgtcacccgctc-tgta---ggcccggccggcg
ct-tgccga---------------------------------------------------
-----------tcaacccgaat--ttttatccaggttgacctcggatca-ggtagggata
cccgctgaa-ctt---aa------------------------------------------
-----------------------------------------------------------
>Aureobasidium_GI932_EU108769_3582m Aureobasidium_GI932_EU108769_3582m 803 bp 
gaattcgccctt----ggaagtaaaagtcgtaacaaggtttccgtaggtg-aacctgcgg
------------------------------------------------------------
--------------aa-ggatcattaaagagtaa-g-ggtgctcagcgcccg--------
---------------------------acctc---------caaccctt-----tgttgt
taaaactaccttgttgctttggcgggaccgctcggtctcgagccgctggg------gat-
-------tcgtcccaggcgagcgcccgccagagttaa---accaaactcttgtta----t
ttaaccggtcgtctgagttaaaat------------------------------------
--tttg--aataaatc------------aaaactttcaacaacggatctcttggttctcg
catcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaattcagt-gaat
cat-cgaatctttg-aac-gcacattgcgcccctt-gg------tattcc-gaggggcat
gcctg-ttcgagcgtca-ttacaccactcaagctatg-----------------------
----------cttggtatt---gggcg--tcgtccttagtt---------gggcgcacct
t-aaagacctcgg-----------------------------------------------
----------------------------------------------------cga--ggc
cactccggctttaggcgtagtagaatttattcgaacgtctgtcaaagga-----gaggaa
ctctgccga---------------------------------------------------
-----------ctgaaacc-ttt-atttttctaggttgacctcggatca-ggtagggata
cccgctgaa-ctt---aagcatatcaataagcggaggaaagggcgaattc----------
-----------------------------------------------------------
>Aureobasidium_pullulans_AF455533_1 Aureobasidium_pullulans_AF455533.1 803 bp 
----------tt----ggaagtaaaagtcgtaacaaggtttccgtaggtg-aacctgcgg
------------------------------------------------------------
--------------aa-ggatcattaaagagtaa-g-ggtgctcagcgcccg--------
---------------------------acctc---------caaccctt-----tgttgt
taaaactaccttgttgctttggcgggaccgctcggtctcgagccgctggg------gat-
-------tcgtcccaggcgagcgcccgccagagttaa---accaaactcttgtta----t
ttaaccggtcgtctgagttaaaat------------------------------------
--tttg--aataaatc------------aaaactttcaacaacggatctcttggttctcg
catcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaattcagt-gaat
cat-cgaatctttg-aac-gcacattgcgcccctt-gg------tattcc-gaggggcat
gcctg-ttcgagcgtca-ttacaccactcaagctatg-----------------------
----------cttggtatt---gggcg--tcgtccttagtt---------gggcgcgcct
t-aaagacctcgg-----------------------------------------------
----------------------------------------------------cga--ggc
cactccggctttaggcgtagtagaatttattcgaacgtctgtcaaagga-----gaggaa
ctctgccga---------------------------------------------------
-----------ctgaaacc-ttt-atttttctaggttgacctcggatca-ggtagggata
cccgctgaa-ctt---aagcatatcaataagcggagg-----------------------
-----------------------------------------------------------
>Candida_palmioleophila_AB016582_1 Candida_palmioleophila_AB016582.1 803 bp 
---------------------------ctgtattctaattgccagcgcttaattgcgcgg
------------------------------------------------------------
---------------------cgattaaaccttacacacaat---gtttttc--------
------------------------------------------------------tttatt
agaaactattgctttggcttggctaagaaattagtcgggccagaggt---ttacacaaa-
-------c---ttcaattttta------------------attgaattgttattt----a
atactttgtcaa-----------t------------------------------------
--ttgttgattaaattcaaacaatcttcaaaactttcaacaacggatctcttggttctcg
catcgatgaagaacgcagcgaaatgcgataagtaatatgaattgcagattttcgt-gaat
cat-cgaatctttg-aac-gcacattgcgccctct-gg------tattcc-agagggcat
gcctg-tttgagcgtcatttctctc--tcaaacccttggg--------------------
----------tttggtatt---gagtg---------------------------------
--atactcttag------------------------------------------------
------------------------------------------------------------
----------tcgaactaggcgtttgctt--------gaaatttattggcatgagtgacg
ctgagaagt------------------------------------------------gca
ttcaggaaatatcaatgtattaggtttatccaact-cgttgacaattcttggttgtgaat
tttgtgttagcttgcctaaaaaacacaaacaagt--------------------------
-----------------------------------------------------------
>Cerebella_androprogonis_AJ306620_1 Cerebella_androprogonis_AJ306620.1 803 bp 
------------------------------------------------------------
------------------------------------------------------------
-------------------atcatta----ccta-g-agtttgtagacttcg--------
---------------------------gtctg--------ctacctcttacccatgtctt
ttaagtaccttcgtttcctcggtgggtccgcccgccga----------------------
------------ctggacaa--------------cat---tcaaaccctttgcag----t
tgcaatcagcgtctgaaaaaacat------------------------------------
--aat-------agtt------------acaactttcaacaacggatctcttggttctgg
catcgatgaagaacgcagcgaaatgcgataagtagtgtgaattgcagaattcagt-gaat
cat-cgaatctttg-aac-gcacattgcgcccctt-gg------tattcc-atggggcat
gcctg-ttcgagcgtcatttgtacc-ttcaagctctg-----------------------
----------cttggtgtt---gggtg--ttttgtctcgcctctgcgtgtagactcgcct
t-aaaacaattgg-----------------------------------------------
----------------------------------------------------cagccggc
gtattgatttcggagcgcagtacatctcgcgctttgcactcataacg-------------
--acgacgt---------------------------------------------------
-----------ccaaaagtacaa--ttttacactcttgacctcggatca-ggtagggata
cccgctgaa-ctt---aagcatatcaataagcggagga----------------------
-----------------------------------------------------------
>Cladosporium_GI900_EU108743_3613m Cladosporium_GI900_EU108743_3613m 803 bp 
----------------ggaagtaaaagtcgtaacaaggtctccgtaggtg-aacctgcgg
------------------------------------------------------------
--------------gagggatcatta-----caa-gttgaccccggtctaac--------
---------------------------caccgggatgttcataaccctt-----tgttgt
c----cgactctgttgcctc--cggggcgaccctgcct----------------------
------------tcgggcgggggctccgggtggacac---ttcaaactcttgc------g
taactttgcagtctgagtaaactt------------------------------------
--aatt--aataaatt------------aaaacttttaacaacggatctcttggttctgg
catcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaattcagtggaat
cat-cgaatctttg-aac-gcacattgcgcccccc-tg------tattccgggggggcat
gcctg-ttcaagcgtca-tttcaccactcaagcctcg-----------------------
----------cttggtatt---gggca--acgcggtccgcc-----------gcgtgcct
c-aaatggggggg-----------------------------------------------
----------------------------------------------------ctg--ggt
cttctgtcccctaagcgttgtggaaactattc--------gctaaagggtgttcgggagg
ctacgccg----------------------------------------------------
------------taaaacaaccc-catttctaaggttgacctcggatca-ggtagggata
cccgctgaa-ctt---aagcatatcaataagcggagga----------------------
-----------------------------------------------------------
>Cladosporium_GI901_EU108744_3610m Cladosporium_GI901_EU108744_3610m 803 bp 
----gaattcgcccttggaagtaaaagtcgtaacaaggtctccgtaggtg-aacctgcgg
------------------------------------------------------------
--------------ag-ggatcatta-----caa-g-aacgcccgggctacg--------
---------------------------gcctg-gttattcataaccctt-----tgttgt
c----cgactctgttgcctc--cggggcgaccctgcct----------------------
------------tcgggcgggggctccgggtggacac---ttcaaactcttgc------g
taactttgcagtctgagtaaactt------------------------------------
--aatt--aataaatt------------aaaacttttaacaacggatctcttggttctgg
catcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaattcagt-gaat
cat-cgaatctttg-aac-gcacattgcgccccct-gg------tattcc-ggggggcat
gcctg-ttcgagcgtca-tttcaccactcaagcctcg-----------------------
----------cttggtatt---gggca--acgcggtccgcc-----------gcgtgcct
c-aaatcgtccgg-----------------------------------------------
----------------------------------------------------ctg--ggt
cttctgtcccctaagcgttgtggaaactattc--------gctaaagggtgttcgggagg
ctacgccg----------------------------------------------------
------------taaaacaaccc-catttctaaggttgacctcggatca-ggtagggata
cccgctgaa-ctt---aagcatatcaataagcggaggaaagggcgaattc----------
-----------------------------------------------------------
>Cladosporium_GI924_EU108761_3582m Cladosporium_GI924_EU108761_3582m 803 bp 
------------------------------------------------------------
------------------------------------------------------------
------------------------ta-----caa-g-aacgcccgggctacg--------
---------------------------gcctgagttattcataaccctt-----tgttgt
c----cgactctgttgcctc--cggggcgaccctgcct----------------------
------------tcgggcgggggctccgggtggacac---ttcaaactcttgc------g
taactttgcagtctgagtaaactt------------------------------------
--aatt--aataaatt------------aaaacttttaacaacggatctcttggttctgg
catcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaattcagt-gaat
cat-cgaatctttg-aac-gcacattgcgccccct-gg------tattcc-ggggggcat
gcctg-ttcgagcgtca-tttcaccactcaagcctcg-----------------------
----------cttggtatt---gggca--acgcggtccgcc-----------gcgtgcct
c-aaatcgtccgg-----------------------------------------------
----------------------------------------------------ctg--ggt
cttctgtcccctaagcgttgtggaaactattc--------gctaaagggtgttcgggagg
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------------------
>Cladosporium_cladosporioides_AY345352_1_Antarctica Cladosporium_cladosporioides_AY345352.1_Antarctica 803 bp 
---------------------------------------tccgtaaggtg-aacctgcgg
------------------------------------------------------------
--------------ag-ggatcatta-----caa-g-tgaccccggtttacc--------
---------------------------accgg-gatgttcataaccctt-----tgttgt
c----cgactctgttgcctc--cggggcgaccctgcct----------------------
------------tcgggcgggggctccgggtggacac---ttcaaactcttgc------g
taactttgcagtctgagtaaattt------------------------------------
--aatt--aataaatt------------aaaactttcaacaacggatctcttggttctgg
catcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaattcagt-gaat
cat-cgaatctttg-aac-gcacattgcgccccct-gg------tattcc-ggggggcat
gcctg-ttcgagcgtca-tttcaccactcaagcctcg-----------------------
----------cttggtatt---gggca--acgcggtccgcc-----------gcgtgcct
c-aaatcgaccgg-----------------------------------------------
----------------------------------------------------ctg--ggt
cttctgtcccctaagcgttgtggaaactattc--------gctaaaggtggttcgggagg
ctacgccg----------------------------------------------------
------------taaaacaaccc-catttctaaggttgacctcggatca-ggtagga---
------------------------------------------------------------
-----------------------------------------------------------
>Cladosporium_herbarum_AF177734_1_Greenland_glacial_ice Cladosporium_herbarum_AF177734.1_Greenland_glacial_ice 803 bp 
---------------------------------------ctccgtaggtg-aac-tgcgg
------------------------------------------------------------
--------------ag-ggatcatta-----caa-g-aacgcccgggcttcg--------
---------------------------gcctg-gttattcataaccctt-----tgttgt
c----cgactctgttgcctc--cggggcgaccctgcct----------------------
------------tcgggcgggggctccgggtggacac---ttcaaactcttgc------g
taactttgcagtctgagtaaactt------------------------------------
--aatt--aataaatt------------aaaacttttaacaacggatctcttggttctgg
catcgatgaaaaacgcagcgaaatgcgataagtaatgtgaattgcagaattcagt-gaat
catccaaatctttgaaac-gcacattgcgccccct-gg------tattcc-ggggggcat
gcctgtttcgaacgtcattttcaccactcaagcctcg-----------------------
----------ctttggttttgggggca--acgcggtccgcc-----------gcgtgcct
c-aaatcgtccgg-----------------------------------------------
----------------------------------------------------ctg--ggt
cttctgtcccctaagcgttgtggaaactattc--------gctaaagggtgttcgggagg
ctacgccg----------------------------------------------------
------------taaaacaaccc-catttctaaggttga-ctcggatca-ggtagggata
cccgctgaa-tt------------------------------------------------
-----------------------------------------------------------
>Cladosporium_sp__DQ317332_1_Ross_Sea_Antarctica Cladosporium_sp._DQ317332.1_Ross_Sea_Antarctica 803 bp 
------------------------------------------------------------
------------------------------------------------------------
-----------------ggatcatta-----caa-g-tgaccccggtcttac--------
---------------------------caccgggatgttcataaccctt-----tgttgt
c----cgactctgttgcctc--cggggcgaccctgcct----------------------
------------tcgggcgggggctccgggtggacac---ttcaaactcttgc------g
taactttgcagtctgagtaaactt------------------------------------
--aatt--aataaatt------------aaaacttttaacaacggatctcttggttctgg
catcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaattcagt-gaat
cat-cgaatctttg-aac-gcacattgcgccccct-gg------tattcc-ggggggcat
gcctg-ttcgagcgtca-tttcaccactcaagcctcg-----------------------
----------cttggtatt---gggca--acgcggtccgcc-----------gcgtgcct
c-aaatcgaccgg-----------------------------------------------
----------------------------------------------------ctg--ggt
cttctgtcccctaagcgttgtggaaactattc--------gctaaagggtgttcgggagg
ctacgccg----------------------------------------------------
------------taaaacaaccc-catttctaaggttgacctcggatca-ggtagggata
cccgctgaa-ctt---aagcatatcaataagcggagga----------------------
-----------------------------------------------------------
>Cladosporium_uncultured_soil_fungus_DQ421000_1 Cladosporium_uncultured_soil_fungus_DQ421000.1 803 bp 
--cttggtcatttagaggaagtaaaagtcgtaacaaggtctccgtaggtg-aacctgcgg
------------------------------------------------------------
--------------ag-ggatcatta-----caa-g-aacgcccgggctacg--------
---------------------------gcctg-gttattcataaccctt-----tgttgt
c----cgactctgttgcctc--cggggcgaccctgcct----------------------
------------tcgggcgggggctccgggtggacac---ttcaaactcttgc------g
taactttgcagtctgagtaaactt------------------------------------
--aatt--aataaatt------------aaaacttttaacaacggatctcttggttctgg
catcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaattcagt-gaat
cat-cgaatctttg-aac-gcacattgcgccccct-gg------tattcc-ggggggcat
gcctg-ttcgagcgtca-tttcaccactcaagcctcg-----------------------
----------cttggtatt---gggca--acgcggtccgcc-----------gcgtgcct
c-aaatcgtccgg-----------------------------------------------
----------------------------------------------------ctg--ggt
cttctgtcccctaagcgttgtggaaactattc--------gctaaagggtgttcgggagg
ctacgccg----------------------------------------------------
------------taaaacaaccc-catttctaaggttgacctcggatca-ggtagggata
cccgctgaa-ctt---aagcatatcaataagcggagga----------------------
-----------------------------------------------------------
>Cryptococcs_GI817_DQ191309_3619m Cryptococcs_GI817_DQ191309_3619m 803 bp 
--cttggtcatttagaggaagtaaaagtcgtaacaaggtttccgtaggtgaacc-tgcgg
------------------------------------------------------------
--------------aa-ggatcattaatgaattt-agat---------------------
tgaaccataggcgaaagccagtggttcttctttcatatccata-aca-c---------ct
gtgcactgttggatgcttgcat----------------------------------cca-
-------cttttaa--------------------------actaaacat-----------
-tattgtaacaaatgt---agtct------------------------------------
--tattataacataat------------aaaactttcaacaacggatctcttggctctcg
catcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaattcagt-gaat
cat-cgaatctttg-aac-gcaccttgcgctcctt-gg------tattcc-gaggagcat
gcctg-tttgagtgtcatgaaaccc--tcaaacccaagttttggatttcgatccatgctt
gag-------tttggattt---ggatg--tt--tgc---cggtgatgaaccgactcatct
t-aaaagtattagcttggatctgtctat--------------------------------
---------------------------------------------atgact--------g
gtttga--cttggcataataagtattttgct-gaggacatcttc--ggatgg-ccaggac
ctagactactgtctgctaactaaaccatcactttaagtgcatctttggatgttactcatt
gtgta------------------acttt--gacatctggcctcaaatca-agtaggacta
cccgctgaa-ctt---aagcatatcaataagcggagg-----------------------
-----------------------------------------------------------
>Cryptococcs_GI944_EU18779_3582m Cryptococcs_GI944_EU18779_3582m 803 bp 
----------------ggaagtaaaagtcgtaacaaggtttccgtaggtgaacc-tgcgg
------------------------------------------------------------
--------------aa-ggatcattaatgaattt-agat---------------------
tgaaccataggcgaaagccagtggttcttctttcatatccata-aca-c---------ct
gtgcactgttggatgcttgcat----------------------------------cca-
-------cttttaa--------------------------actaaacat-----------
-tattgtaacaaatgt---agtct------------------------------------
--tattataacataat------------aaaactttcaacaacggatctcttggctctcg
catcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaattcagt-gaat
cat-cgaatctttg-aac-gcaccttgcgctcctt-gg------tattcc-gaggagcat
gcctg-tttgagtgtcatgaaaccc--tcaaacccaagttttggatttcgatccacgctt
ggagt-----ttgggattt---ggatg--tt--tgc---cggtgatgaaccgactcatct
t-aaaagtattagcttggacctgtctat--------------------------------
---------------------------------------------atgact--------g
gtttga--cttggcataataagtattttgct-gaggacatcttc--ggatgg-ccaggac
ctagactactgtctgctaactaaaccatcactttaagtgcatctttggatgttactcatt
gtgta------------------acttt--gacatctggcctcaaatca-agtaggacta
cccgctgaa-ctt---aagcatatcaataagcggaggaaagggcgaattc----------
-----------------------------------------------------------
>Cryptococcs_magnus_AF190009_1 803 bp 
----------------------------------------tccgtaggtgaacc-tgcgg
------------------------------------------------------------
--------------aa-ggatcattaatgaattt-agat---------------------
tgaaccataggcgaaagccagtggttcttctttcatatccata-aca-c---------ct
gtgcactgttggatgcttgcat----------------------------------cca-
-------cttttaa--------------------------actaaacat-----------
-tattgtaacaaatgt---agtct------------------------------------
--tattataacataat------------aaaactttcaacaacggatctcttggctctcg
catcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaattcagt-gaat
cat-cgaatctttg-aac-gcaccttgcgctcctt-gg------tattcc-gaggagcat
gcctg-tttgagtgtcatgaaaccc--tcaaacccaagttttggatttcgatccatgctt
gag-------tttggattt---ggatg--tt--tgc---cggtgatgaaccgactcatct
t-aaaagtattagcttggatctgtctat--------------------------------
---------------------------------------------atgact--------g
gtttga--cttggcataataagtattttgct-gaggacatcttc--ggatgg-ccaggac
ctagactactgtctgctaactaaaccatcactttaagtgcatctttggatgttactcatt
gtgta------------------acttt--gacatctggcctcaaatca-agtaggacta
cccgctgaa-ctt---aagcatatcaataagcggagga----------------------
-----------------------------------------------------------
>Cryptococcus_niccombsii_AY029346_1_Antarctica Cryptococcus_niccombsii_AY029346.1_Antarctica 803 bp 
----------------------------------------tccgtaggtgaacc-tgcgg
------------------------------------------------------------
--------------aa-ggatcactagtga--tt-aaatcgagagcgtcttc--------
----------------attgacctctcacccttcacatccacatacacc---------ct
gtgaatcgtttggctttttcattaatagagcgcaagctcgacaagtgaaaaagtcatca-
---------tttat--------------------------ac-ataccc-----------
-cagtcttatgaatgtaacagttt------------------------------------
--taata-aacataat------------aaaacttttaacaacggatctcttggttctcg
catcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaattcagt-gaat
cat-cgaatctttg-aac-gcaccttgcgctcctt-gg------tattcc-gaggagcat
gcctg-tttgagtgtcatgaaactc--tcacccttcaact-----ttcttaatagtggtt
gcagg-----cgtggactt---gagcg--ctgctgg---ttttaattaaccggctcgctt
g-aaatgaattagc--agatcc-ttttt--------------------------------
---------------------------------------------gtaatc--------g
gttcca--ctcgacgtgataagtatttcgcc-gaggacatctttacggatgg-ccgagat
aaagaaagt----------------------cttagatccgcttctaattcttag-----
ccttacgcaagtaagctaaacccatttt--atgatctggcctcaaatca-ggtaggacta
cccgctgaa-ctt---aagcatatcaataagcggagga----------------------
-----------------------------------------------------------
>Cystofilobasidium_AF294943_1_psychrophile_from_glacier Cystofilobasidium_AF294943.1_psychrophile_from_glacier 803 bp 
------------------------------------------------------------
------------------------------------------------------------
--------------------------gtga--tt-aaatcgagagtgtcttc--------
----------------attgacctctcacccttcacatccacataca-c---------ct
gtgcaccgtttggctcttat----aaaagacgaaagtctgcaatg----agagtcatca-
-------attttat--------------------------ac-ataccc-----------
-cagtcttatgaatgtaacagttt------------------------------------
--taata-aacataat------------aaaacttttaacaacggatctcttggttctcg
catcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaattcagt-gaat
cat-cgaatctttg-aac-gcaccttgcgctcctt-gg------tattcc-gaggagcat
gcctg-tttgagtgtcatgaaactc--tcaaccttcaact-----tttttattaa-ggct
gaagg-----cttggactt---gagcg--ctgctgg---ttctcacgaaccggctcgctt
g-aaatgaattagc--agatcc-ttttt--------------------------------
---------------------------------------------gtaatc--------g
gttcca--ctcgacgtgataagtatttcgcc-gaggacatatgaaagtatgg-ccgagat
aaagaaagt----------------------tctagatccgcttctaattcttagataaa
gcttgctttactaaac----cccatttt--atga--------------------------
------------------------------------------------------------
-----------------------------------------------------------
>Cystofilobasidium_GI898_EU108742_3613m Cystofilobasidium_GI898_EU108742_3613m 803 bp 
-gaattcgccccttggaagtaaaagtcgtaaccacggtttcccgtaggtgtaacctgcgg
------------------------------------------------------------
--------------aaaggatcattaccgagtgaggggccctctgggttcca--------
---------------------------accttccccacccgtgtctatc-----------
-----gtaccttgttgcttcggcgggcccgccgtttcgacggccgccggggaggccttg-
-------cgcccccgggcccccgcccgccgaagaccccaacatgaacgctgttct----g
aaagtatgcagtctgagttgatta------------------------------------
--tcgt--aatcagtt------------aaaactttcaacaacggatctcttggttccgg
catcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaattcagt-gaat
cat-cgagtctttg-aac-gcacattgcgccccct-gg------tattcc-ggggggcat
gcctg-tccgagcgtcattgctgcc-ctcaagcacgg-----------------------
----------cttgtgtgt---tgggc--ccccgtccccc-tctcccgggggacgggccc
g-aaaggcagcgg-----------------------------------------------
----------------------------------------------------gggcaccg
cgtccggtcctcgagcgtatggggctttgtcacctgctc-tgta---ggcccggccggcg
cc-agccga---------------------------------------------------
-----------c-acccaactttatttttctaaggttgacctcggatca-ggtagggata
cccgctgaa-ctt---aagcatatcaataagcggaggaaagg--------gcgaattc--
-----------------------------------------------------------
>Cystofilobasidium_GI913_EU108753_3606m Cystofilobasidium_GI913_EU108753_3606m 803 bp 
-----------------------------------------------------cctgcgg
------------------------------------------------------------
--------------aa-ggatcactagagatttc-gccctccggggctctct--------
------------------------ttttcttcacacacccctgtgcact---------tt
ggctgccgcttcatt--------------------------------gcggtggtcttt-
-------tataatt--------------------------accataccc-atata----c
acaagtcattgaatgt---aaaat------------------------------------
--cgttataaactaat------------ataactttcaacaacggatctcttggttctcg
catcgatgaagaacgcagcgaattgcgataagtaatgtgaattgcagaattcagt-gaat
cat-cgaatctttg-aac-gcatcttgcgctcttt-gg------tattcc-gaagagcat
gcctg-tttgagtgtcatgaaactc--tcacctgcagcactc---ttttattagagggct
ggag------cgtggacgt---gagtg--ctgctggtgccctcgctgcatcggctcactt
g-aaatttattagctgaatc----ctct--------------------------------
---------------------------------------------agtgtt--------g
gttcta--ctcgacgtgataagatctccgtc-gaggacagtgctccttgtgggcgttggc
caccgctag---------------------ctgttgatacgctcctaattagcgcagac-
---------ttcgagtgctggcaac-tttgacaac-tggcctcaaattt-ag-agaatca
------------------------------------------------------------
-----------------------------------------------------------
>Cystofilobasidium_capitatum_AY052492_1_cold_adapted_yeast Cystofilobasidium_capitatum_AY052492.1_cold_adapted_yeast 803 bp 
------------------------------------------------------ctgcgg
------------------------------------------------------------
--------------aa-ggatcactaaagaattc-gcccttcggggctctc---------
-------------------------tttattcacacacccctgtgcact---------tt
ggccacctctttgtt--------------------------------gaggtgtgtctt-
-------tttaatt--------------------------accataccctataaa----c
acaagttattgaatgt---aaaat------------------------------------
--cgttataaactaat------------ataactttcaacaacggatctcttggttctcg
catcgatgaagaacgcagcgaattgcgataagtaatgtgaattgcagaattcagt-gaat
cat-cgaatctttg-aac-gcatcttgcgctcttt-gg------tattcc-gaagagcat
gcctg-tttgagtgtcatgaaactc--tcacctccaatcttt---tttaactagaaggtt
gggg------cgtggacgt---gagtg--ctgctggtgccctggttgcatcggctcactt
g-aaattcattagctgaatc----cttt--------------------------------
---------------------------------------------aaagta--------g
gttcta--ctcgacgtgataagatctccgtc-gaggacagtgcttc-----ggcattggc
caacgataa----------------------agttgatacgcttctaattagcgcagac-
---------ttcgagtgctggcaat-tttgacaacttggcctcaaatca-ggtaggacta
cccactgaa-ctt---aagcatatcaa---------------------------------
-----------------------------------------------------------
>Cystofilobasidium_infirmo_miniatum_AF444400_1 Cystofilobasidium_infirmo_miniatum_AF444400.1 803 bp 
-----------------------------------------tccgtaggtgaacctgcgg
------------------------------------------------------------
--------------aa-ggatcactagagatttc-gccctccggggctctct--------
------------------------ttttcttcacacacccctgtgcact---------tt
ggctgccgcttcatt--------------------------------gcggtggtcttt-
-------tataatt--------------------------accataccc-atata----c
acaagtcattgaatgt---aaaat------------------------------------
--cgttataaactaat------------ataactttcaacaacggatctcttggttctcg
catcgatgaagaacgcagcgaattgcgataagtaatgtgaattgcagaattcagt-gaat
cat-cgaatctttg-aac-gcatcttgcgctcttt-gg------tattcc-gaagagcat
gcctg-tttgagtgtcatgaaactc--tcacctgcagcactc---ttttattagagggct
ggag------cgtggacgt---gagtg--ctgctggtgccctcgctgcatcggctcactt
g-aaatttattagctgaatc----ctct--------------------------------
---------------------------------------------agtgtt--------g
gttcta--ctcgacgtgataagatctccgtc-gaggacagtgctccttgtgggcgttggc
caccgctag---------------------ctgttgatacgctcctaattagcgcagac-
---------ttcgagtgctggcaacttttgacaacttggcctcaaatca-ggtaggacta
cccactgaa-ctt---aagcatatcaataagcggagga----------------------
-----------------------------------------------------------
>Dothioraceae_sp__EF060638_1_marine Dothioraceae_sp._EF060638.1_marine 803 bp 
--ctccgtcatttagaggaagtaaaagtcgtaacaaggtttccgtaggtg-aacctgcgg
------------------------------------------------------------
--------------aa-ggatcattaaagagtaa-g-ggtgctcagcgcccg--------
---------------------------acctc---------caaccctt-----tgttgt
taaaactaccttgttgctttggcgggaccgctcggtctcgagccgctggg------gat-
-------tcgtcccaggcgagcgcccgccagagttaa---accaaactcttgtta----t
ttaaccggtcgtctgagttaaaat------------------------------------
--tttg--aataaatc------------aaaactttcaacaacggatctcttggttctcg
catcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaattcagt-gaat
cat-cgaatctttg-aac-gcacattgcgcccctt-gg------tattcc-gaggggcat
gcctg-ttcgagcgtca-ttacaccactcaagctatg-----------------------
----------cttggtatt---gggtg--ccgtccttagtt---------gggcgcgcct
t-aaagacctcgg-----------------------------------------------
----------------------------------------------------cga--ggc
ctcaccggctttaggcgtagtagaatttattcgaacgtctgtcaaagga-----gaggac
ttctgccga---------------------------------------------------
-----------ctgaaacctttt-atttttctaggttgacctcggatca-ggtagggata
cccgctgaa-ctt---aagcatatc-ataagcggaggaaaaaaaccaacagggattgccc
tattacggcgaatgaaccgcacgctcaaattgaaactggcctcggtcccattgtaattg
>Filobasidium_globisporum_AF444336_1 Filobasidium_globisporum_AF444336.1 803 bp 
----------------------------------------tccgtaggtgaacc-tgcgg
------------------------------------------------------------
--------------aa-ggatcattattgaattc-aaatcatctgtggcttcggcccgga
tgtgccaacaggtaacactgttggtaattc-----tatccata-aca-c---------ct
gtgaactgttggatgcttgcat----------------------------------cca-
-------cttttaa--------------------------actaaacat-----------
-tattgtaacaaatgt---agtct------------------------------------
--tattataacataat------------aaaacttttaacaacggatctcttggctctcg
catcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaattcagt-gaat
cat-cgaatctttg-aac-gcaccttgcgctcctt-gg------tattcc-gaggagcat
gcctg-tttgagtgtcatgaaactc--tcaaacccaagttttggatttcggtccatgctt
gag-------tttggattt---ggatg--tt--tgc---cggtgatgaaccgactcatct
t-aaaagtattagc-tagatctgtctct--------------------------------
---------------------------------------------atgact--------g
gtttga--cttggcataataagtattttgct-gaggacatctttcgggatgg-ccaggac
ctagactattgtctgctaactaaaccatcactttaagtgcatctttggatgttactcatt
gtgta------------------acttt--gacatctggcctcaaatca-ggtaggacta
cccgctgaa-ctt---aagcatatcaataagcggagga----------------------
-----------------------------------------------------------
>Mycosphaerella_macrospora_AF362049_1 Mycosphaerella_macrospora_AF362049.1 803 bp 
----------------------------------------tccgtaggta-acctcg---
------------------------------------------------------------
--------------ag-ggatcatta-----caa-g-aacgcccgggcttcg--------
---------------------------gcctg-gttattcataaccctt-----tgttgt
c----cgactctgttgcctc--cggggcgaccctgcct----------------------
------------tcgggcgggggctccgggtggacac---ttcaaactcttgc------g
taactttgcagtctgagtaaactt------------------------------------
--aatt--aataaatt------------aaaacttttaacaacggatctcttggttctgg
catcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaattcagt-gaat
cat-cgaatctttg-aac-gcacattgcgccccct-gg------tattcc-ggggggcat
gcctg-ttcgagcgtca-tttcaccactcaagcctcg-----------------------
----------cttggtatt---gggca--acgcggtccgcc-----------gcgtgcct
c-aaatcgtccgg-----------------------------------------------
----------------------------------------------------ctg--ggt
cttctgtcccctaagcgttgtggaaactattc--------gctaaagggtgttcgggagg
ctacgccg----------------------------------------------------
------------taaaacaaccc-catttctaaggttgacctcggatca-ggtagggata
------------------------------------------------------------
-----------------------------------------------------------
>Penicillium_GI920_EU108757_3585m Penicillium_GI920_EU108757_3585m 803 bp 
------------------------------------------------------------
------------------------------------------------------------
-----------------------ttaccgagtga-gggccctctggg-tcca--------
---------------------------acct--cccacccgtgtttatt-----------
-----ttaccttgttgcttcggcgggcccgcc--ttaactggccgccggg--gggctta-
-------cgcccccgggcccgcgcccgccgaagacacc--ctcgaactctgt-t------
gaagattgtagtc-gag-tgaaaa------------------------------------
--tata--aattattt------------aaaactttcaacaacggatctcttggttcc-g
catcgatgaagaacgcagcgaaatgcgatacgtaatgtgaattgca-aattcagt-gaat
cat-cgagtctttg-aac-gcacattgcgccccct-gg------tattcc-ggggggcat
gcctg-tccgagcgtcatttatgcc-ctcaagcacgg-----------------------
----------cttgtgtgt---tggg---ccccgtcctccgat-cccgggggacgggccc
g-aaaggcagcgg-----------------------------------------------
----------------------------------------------------cggcaccg
cgtccggtcctcgagcgtatggggctttgtcacccgctc-tgta---ggcccggccggcg
ct-tgccga---------------------------------------------------
-----------tcaacccaaat--ttttat------------------------------
------------------------------------------------------------
-----------------------------------------------------------
>Penicillium_chrysogenum_AM158209_1_deep_sea_sediment Penicillium_chrysogenum_AM158209.1_deep_sea_sediment 803 bp 
------------------------------------------------------------
------------------------------------------------------------
---------------aaggatcattaccgagtga-gggccctctggg-tcca--------
---------------------------acct--cccacccgtgtttatt-----------
-----ttaccttgttgcttcggcgggcccgcc--ttaactggccgccggg--gggctta-
-------cgcccccgggcccgcgcccgccgaagacacc--ctcgaactctgtct------
gaagattgtagtctgag-tgaaaa------------------------------------
--tata--aattattt------------aaaactttcaacaacggatctcttggttccgg
catcgatgaagaacgcagcgaaatgcgatacgtaatgtgaattgca-aattcagt-gaat
cat-cgagtctttg-aac-gcacattgcgccccct-gg------tattcc-ggggggcat
gcctg-tccgagcgtcatttctgcc-ctcaagcacgg-----------------------
----------cttgtgtgt---tggg---ccccgtcctccgat-cccgggggacgggccc
g-aaaggcagcgg-----------------------------------------------
----------------------------------------------------cggcaccg
cgtccggtcctcgagcgtatggggctttgtcacccgctc-tgta---ggcccggccggcg
ct-tgccga---------------------------------------------------
-----------tcaacccaaat--ttttatccaggttgacctcggatca-ggtagggata
cccgctgaa-ctt---aa------------------------------------------
-----------------------------------------------------------
>Penicillium_chrysogenum_AY373903_1 Penicillium_chrysogenum_AY373903.1 803 bp 
----------------------------------------tccgtaggtg-aacctgcgg
------------------------------------------------------------
---------------aaggatcattaccgagtga-gggccctctggg-tcca--------
---------------------------acct--cccacccgtgtttatt-----------
-----ttaccttgttgcttcggcgggcccgcc--ttaactggccgccggg--gggctta-
-------cgcccccgggcccgcgcccgccgaagacacc--ctcgaactctgtct------
gaagattgtagtctgag-tgaaaa------------------------------------
--tata--aattattt------------aaaactttcaacaacggatctcttggttccgg
catcgatgaagaacgcagcgaaatgcgatacgtaatgtgaattgca-aattcagt-gaat
cat-cgagtctttg-aac-gcacattgcgccccct-gg------tattcc-ggggggcat
gcctg-tccgagcgtcatttctgcc-ctcaagcacgg-----------------------
----------cttgtgtgt---tggg---ccccgtcctccgat-cccgggggacgggccc
g-aaaggcagcgg-----------------------------------------------
----------------------------------------------------cggcaccg
cgtccggtcctcgagcgtatggggctttgtcacccgctc-tgta---ggcccggccggcg
ct-tgccga---------------------------------------------------
-----------tcaacccaaat--ttttatccaggttgacctcggatca-ggtagggata
cccgctgaa-ctt---aagcatatcaataagcggaggaaaagaaaccaacagggattgcc
cc---------------------------------------------------------
>Penicillium_commune_AF236103_1_Antarctica Penicillium_commune_AF236103.1_Antarctica 806 bp 
-tctcggtcatttagaggaagtaaaagtcgtaacaaggtttccgtaggtg-aacctgcrg
------------------------------------------------------------
---------------aaggatcattaccgagtga-gggccctctggg-tcca--------
---------------------------acct--cccacccgtgtttatt-----------
-----ttaccttgttgcttcggcgggcccgcc--ttaactggccgccggg--gggctca-
-------cgcccccgggcccgcgcccgccgaagacacc--ctcgaactctgtct------
gaagattgaagtctgag-tgaaaa------------------------------------
--tata--aattattt------------aaaactttcaacaacggatctcttggttccgg
catcgatgaagaacgcagcgaaatgcgatacgtaatgtgaattgca-aattcagt-gaat
cat-cgagtctttg-aac-gcacattgcgccccct-gg------tattcc-ggggggcat
gcctg-tccgagcgtcattgctgcc-ctcaagcccgg-----------------------
----------cttgtgtgt---tggg---ccccgtcctccgatctccgggggacgggccc
g-aaaggcagcgg-----------------------------------------------
----------------------------------------------------cggcaccg
cgtccggtcctcgagcgtatggggctttgtcacccgctc-tgta---ggcccggccggcg
ct-tgccga---------------------------------------------------
-----------tcaacccaaat--ttttatccaggttgacctcggatca-ggtagggata
cccgctgaa-ctt---aagcatatcaataagcggagga----------------------
-----------------------------------------------------------
>Penicillium_corylophilum_AY345354_1_Antarctica Penicillium_corylophilum_AY345354.1_Antarctica 803 bp 
----------------------------------------tccgtaggtg-aacctgcgg
------------------------------------------------------------
---------------aaggatcattaccgagtga-gggccctctggg-tcca--------
---------------------------acct--cccacccatgtttatt-----------
-----gtaccttgttgcttcggcgggcccgcc--tca--cggccgccggg--gggcttc-
-------tgccctctggcccgcgcccgccgaagacacc--attgaacactgtct------
gaagattgcagtctgag-caatta------------------------------------
--gcta--aataagtt------------aaaactttcaacaacggatctcttggttccgg
catcgatgaagaacgcagcgaaatgcgatacgtaatgtgaattgcagaattcagt-gaat
cat-cgagtctttg-aac-gcacattgcgcccctt-gg------tattcc-ggggggcat
gcctg-tccgagcgtcattgctgcc-ctcaagcacgg-----------------------
----------cttgtgtgt---tggg---ccccgtcctcc--ttcccgggggacgggccc
g-aaaggcagcgg-----------------------------------------------
----------------------------------------------------cggcaccg
cgtccggtcctcgagcgtatggggctttgtcacccgctcttgta---ggcccggccggcg
ct-tgccga---------------------------------------------------
-----------caaccatcaat--cttttttcaggttgacctcggatca-ggta------
------------------------------------------------------------
-----------------------------------------------------------
>Penicillium_expansum_AF218786_1_Antarctica Penicillium_expansum_AF218786.1_Antarctica 806 bp 
-tctcggtcatttagaggaagtaaaagtcgtaacaaggtttccgtaggtg-aacctgcrg
------------------------------------------------------------
---------------aaggatcattaccgagtga-gggccctttggg-tcca--------
---------------------------acct--cccacccgtgttta-t-----------
-----ttacctcgttgcttcggcgggcccgcc--ttaactggccgccggg--gggctca-
-------cgcccccgggcccgcgcccgccgaagacacc--cccgaactctgcct------
gaagattgtcgtctgag-tgaaaa------------------------------------
--tata--aattattt------------aaaactttcaacaacggatctcttggttccgg
catcgatgaagaacgcagcgaaatgcgatacgtaatgtgaattgca-aattcagt-gaat
cat-cgagtctttg-aac-gcacattgcgccccct-gg------tattcc-ggggggcat
gcctg-tccgagcgtcattgctgcc-ctcaagcccgg-----------------------
----------cttgtgtgt---tggg---ccccgtcctccgat-tccgggggacgggccc
g-aaaggcagcgg-----------------------------------------------
----------------------------------------------------cggcaccg
cgtccggtcctcgagcgtatggggctttgtcacccgctc-tgta---ggcccggccggcg
ct-tgccga---------------------------------------------------
-----------tcaacccaaat--ttttatccaggttgacctcggatca-ggtagggata
cccgctgaa-ctt---aagcatatcaataagcggagga----------------------
-----------------------------------------------------------
>Penicillium_griseoroseum_GI737_DQ191308_1_glacial_ice Penicillium_griseoroseum_GI737_DQ191308.1_glacial_ice 803 bp 
-----------------------------------tccattgcggaggagga--------
------------------------------------------------------------
---------------aagaactttcactcagtga-gggaaataagggtttt---------
----------------------------cct--cccacccgtgttaatt-----------
-----ttaccttgttgcttcggcgggcccgcc--ttacctggccgccggg--gggctta-
-------cgcccccgggcccgcgcccgccgaagacacc--ctcgaactctgtct------
gaagattgaagtctgag-tgaaaa------------------------------------
--tata--aattattt------------aaaactttcaacaacggatctcttggttccgg
-atcgatgaagaacgcagcgaaatgcgatacgtaatgtgaattgca-aattcagt-gaat
cat-cgagtctttg-aac-gcacattgcgccccctggg------gattcc-ggggggcat
gcctg-tccgagcgtcattgctgcc-ctcaagcccgg-----------------------
----------cttgtgtgt---tggg---ccccgtcccccaatctccgggggacgggccc
acaaaggcagcggc----------------------------------------------
----------------------------------------------------cggcaccg
cgtccggtccttgagcgaatggggctttgtcacccgcttctgta---ggcccggccggcg
ccttgccta---------------------------------------------------
-----------tcaactccaaat-ttttatccaggatgacctcggatca-ggaaggggat
accgcagaacctt---aagcatatcaatagccggagtaaaatttttagagagcctaa---
-----------------------------------------------------------
>Penicillium_sp__AF177735_1_Greenland_glacial_ice Penicillium_sp._AF177735.1_Greenland_glacial_ice 803 bp 
---------------------------------------gttcgtaggtg-aac-tgcgg
------------------------------------------------------------
---------------gaggatcattaccgagtga-gggccctctggg-tcca--------
---------------------------acct--cccacccgtgtttatt-----------
-----ttaccttgttgcttcggcgtgcctgcc--ttt--tggctgccggg--ggtcgtc-
-------tgtccccgggtccgcgctcgccgaagacacc--ttagaactctgtct------
gaagattgtagtctgag-attaaa------------------------------------
--tata--aattattt------------aaaactttcaacaacggatctcttggttccgg
catcgatgaagaacgcagcgaaatgcgatacgtaatgtgaattgcagaattcagt-gaat
cat-cgagtctttg-aac-gcacattgcgccctct-gg------tattcc-ggagggcat
gcctg-tccgagcgtcattgctgcc-ctcaagcacgg-----------------------
----------cttgtgtgt---tggg---ctccgtcctcc---ttccgggggacgggccc
g-aaaggcagcgg-----------------------------------------------
----------------------------------------------------cggcaccg
cgtccggtcctcaagcgtatggggctttgtcacccgctt-tgta---ggactggccggcg
cc-tgccga---------------------------------------------------
-----------tcaac-caaac--ttttttccaggttgacctcggatca-ggtagggata
cccgctgaa-ctt---aagcatatcaat--------------------------------
-----------------------------------------------------------
>Penicillium_sp__AF177739_1_Greenland_glacial_ice Penicillium_sp._AF177739.1_Greenland_glacial_ice 803 bp 
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------gggccctctggg-tcca--------
---------------------------acct--cccacccgtgtttatt-----------
-----ttaccttgttgcttcggcgggcccgcc--ttaactggccgccggg--gggctca-
-------cgcccccgggcccgcgcccgccgaaaacacc--ctcgaactctgtct------
gaagattgaagtctgag-tgaaaa------------------------------------
--tata--aattattt------------aaaactttcaacaacggatctcttggttccgg
catcgatgaagaacgcagcgaaatgcgatacgtaatgtgaattgca-aattcagt-gaat
cat-cgagtctttg-aac-gcacattgcgccccct-gg------tattcc-ggggggcat
gcctg-tccgagcgtcattgctgcc-ctcaagcccgg-----------------------
----------cttgtgtgt---tggg---ccccgtcctccgatctccgggggacgggccc
g-aaaggcagcgg-----------------------------------------------
----------------------------------------------------cggcaccg
cgtccggacctcgagcgtatggggctttgtcacccg--c-tgta---ggcccggccggcg
ct-tgccga---------------------------------------------------
-----------acaacccaaat--tttta-ccaggttgacctcggatca-ggtaggg-ta
cccg-tgaa-tta---a-------------------------------------------
-----------------------------------------------------------
>Penicillium_sp__AF261663_1_Greenland_glacial_ice Penicillium_sp._AF261663.1_Greenland_glacial_ice 803 bp 
---------------------------gcgtaacaaggtttcgt--agtg-aacctgcgg
------------------------------------------------------------
---------------aaggatcattaccgagtga-gggccctctggg-tcca--------
---------------------------acct--cccacccgtgtttatt-----------
-----ttaccttgttgcttcggcgggcccg-c--ttaactgg-cgccggg--gggctta-
-------cg-ccccgggcccgcg-ccgccgaagacacc--ctcgaactctgtct------
gaagattgtagtctgag-tgaaaa------------------------------------
--tata--aattattt------------aaaactttcaacaacggatctcttggttccgg
catcgatgaagaacgcagcgaaatgcgatacgtaatgtgaattgca-aattcagt-gaat
cat-cgagtctttg-aac-gcacattgcgccccct-gg------tattcc-ggggggcat
gcctg-tccgagcgtcatttctgcc-ctcaagcacgg-----------------------
----------cttgtgtgt---tggg---ccccgtcctccgat-cccgggggacgggccc
g-aaaggcagcgg-----------------------------------------------
----------------------------------------------------cggcaccg
cgtccggtcctcgagcgtatggggctttgtcacccgctc-tgta---ggcccggccggcg
ct-tgccga---------------------------------------------------
-----------tcaacccaaat--ttttatccaggttgacctcggatca-ggtagggata
cccgctgaa-ctt---aagcatatcaataagcggaggacctgag----------------
-----------------------------------------------------------
>Penicillium_sp__AY391833_1_glacier Penicillium_sp._AY391833.1_glacier 803 bp 
------------------------------------------------------------
------------------------------------------------------------
---------------aagtatcattaccgagtga-gggccctctggg-tcca--------
---------------------------acct--cccacccgtgtttatt-----------
-----atacctagttgcttcggcgggcccgccgtc---atggccgccgggg-ggcaccc-
-------tgcccccgggcccgcgcccgccgaagccccc--cctgaacgctgtct------
gaagattgcagtctgag-cgatta------------------------------------
--gcta--aatcagtt------------aaaactttcaacaacggatctcttggttccgg
catcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaattcagt-gaat
cat-cgagtctttg-aac-gcacattgcgccccct-gg------tattcc-ggggggcat
gcctg-tccgagcgtcattgctgcc-ctcaagcacgg-----------------------
----------cttgtgtgt---tgggc--ccccgccccccggctcccggggggcgggccc
g-aaaggcagcgg-----------------------------------------------
----------------------------------------------------cggcaccg
cgtccggtcctcgagcgtatggggcttcgtcacccgctc-tgta---ggcccggccggcg
cc-cgccgg---------------------------------------------------
-----------cgacccccctcaatctttctcaggttgacctcggatca-ggtagggata
cccgctgaa-ctt---aa------------------------------------------
-----------------------------------------------------------
>Phoma_GI950_EU108785_3563m 803 bp 
--gcgaattcgcccttggaagtaaaagtcgtaacaaggtttccgtaggtg-aacctgcgg
------------------------------------------------------------
--------------aa-ggatcatta----ccta-g-agtttgtagacttcg--------
---------------------------gtctg--------ctacctcttacccatgtctt
ttgagtaccttcgtttcctcggcgggtccgcccgccga----------------------
------------ttggacaa--------------cat---tcaaaccctttgcag----t
tgcaatcagcgtctgaaaaaacat------------------------------------
--aat-------agtt------------acaactttcaacaacggatctcttggttctgg
catcgatgaagaacgcagcgaaatgcgataagtagtgtgaattgcagaattcagt-gaat
cat-cgaatctttg-aac-gcacattgcgcccctt-gg------tattcc-atggggcat
gcctg-ttcgagcgtcatttgtacc-ttcaagctctg-----------------------
----------cttggtgtt---gggtg---tttgtctcgcctctgcgtgtagactcgcct
t-aaaacaattgg-----------------------------------------------
----------------------------------------------------cagccggc
gtattgatttcggagcgcagtacatctcgcgctttgcactcataacg-------------
--acgacgt---------------------------------------------------
-----------ccaaaagtacat--ttttacactcttgacctcggatca-ggtagggata
cccgctgaa-ctt---aagcatatcaataagcggaggaaagggcgaattcgtttaaacct
gcaggactagtccgttagtgagggtaattctga--------------------------
>Phoma_glomerata_AY183371_1 803 bp 
--cttgggtcattagaggaagtaaaagtcgtaacaaggtttccgtaggtg-aacctgcgg
------------------------------------------------------------
--------------aa-ggatcatta----ccta-g-ag-ttgtaggcttt---------
---------------------------gcctg--------ctatctcttacccatgtctt
ttgagtaccttcgtttcctcggcgggtccgcccgccga----------------------
------------ttggaca----------------at---ttaaaccatttgcag----t
tgcaatcagcgtctgaaaaaactt------------------------------------
--aat-------agtt------------acaactttcaacaacggatctcttggttctgg
catcgatgaagaacgcagcgaaatgcgataagtagtgtgaattgcagaattcagt-gaat
cat-cgaatctttg-aac-gcacattgcgcccctt-gg------tattcc-atggggcat
gcctg-ttcgagcgtcatttgtacc-ttcaagctctg-----------------------
----------cttggtgtt---gggtg---tttgtctcgcctctgcgcgtagactcgcct
c-aaaacaattgg-----------------------------------------------
----------------------------------------------------cagccggc
gtattgatttcggagcgcagtacatctcgcgctttgcactcataacg-------------
--acgacgt---------------------------------------------------
-----------ccaaaagtacat--ttttacactcttgacctcggatca-ggtagggata
cccgctgaa-ctt---aagcatatcaatagccgggag-----------------------
-----------------------------------------------------------
>Phoma_uncultured_soil_fungus_DQ420965_1 Phoma_uncultured_soil_fungus_DQ420965.1 803 bp 
--cttggtcatttagaggaagtaaaagtcgtaacaaggtttccgtaggtg-aacctgcgg
------------------------------------------------------------
--------------aa-ggatcatta----ccta-g-agtttgtagacttcg--------
---------------------------gtctg--------ctacctcttacccatgtctt
ttgagtaccttcgtttcctcggcgggtccgcccgccga----------------------
------------ttggacaa--------------cat---tcaaaccctttgcag----t
tgcaatcagcgtctgaaaaaacat------------------------------------
--aat-------agtt------------acaactttcaacaacggatctcttggttctgg
catcgatgaagaacgcagcgaaatgcgataagtagtgtgaattgcagaattcagt-gaat
cat-cgaatctttg-aac-gcacattgcgcccctt-gg------tattcc-atggggcat
gcctg-ttcgagcgtcatttgtacc-ttcaagctctg-----------------------
----------cttggtgtt---gggtg---tttgtctcgcctctgcgtgtagactcgcct
t-aaaacaattgg-----------------------------------------------
----------------------------------------------------cagccggc
gtattgatttcggagcgcagtacatctcgcgctttgcactcataacg-------------
--acgacgt---------------------------------------------------
-----------ccaaaagtacat--ttttacactcttgacctcggatca-ggtagggata
cccgctgaa-ctt---aagcatatcaataagcggagga----------------------
-----------------------------------------------------------
>Pseudozyma_GI895_EU108740_3621m Pseudozyma_GI895_EU108740_3621m 803 bp 
-----------------------------------------------gtg-ggctcgcac
------------------------------------------------------------
------------------------------------------------------------
-------------------------------cctgtccaactaaacctgagctacctttt
ttatataacacggttgcatcggtccgtctgtcgaaaccagtagcgctcatagcgag----
-------cagcgtctggggaaagacgggtcggcgcttc-ttaccaacacttttga-acac
taggattggaa---ggacaaaaatcatttttttgatgatggaagcgactggtaatgcggt
cgtctaaattgaaaaa------------acaacttttggcaacggatctcttggttctcc
catcgatgaagaacgcagcgaattgcgataagtaatgtgaattgcagaagt-----gaat
cat-cgaatctttg-aacggcaccttgcgctccc--ggcagatttaatctgggggagcat
gcctg-tttgagggccgcgaattgt-ttcgaacgaacagc--------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------------------
>Pseudozyma_antarctica_AY641557_1_Antarctica Pseudozyma_antarctica_AY641557.1_Antarctica 803 bp 
tgaacctgcagatggatcatttcgatgaaaa--ccttttttcttgaggtgtggctcgca-
------------------------------------------------------------
------------------------------------------------------------
-------------------------------cctgtctaactaaatc-gagctaccacat
tt---taacacggttgcatcggttgg-ctgtcaaa-----cagtgcgcgcggcgaattca
ttttcgcccgcgctctgcgaga---cggtcgacactttaccaaaaacactgttgatacca
taggatttgaacgtagatgaaact--------------------cgactggtaatgcggt
cgtctaaaatctaaaa------------acaacttttggcaacggatctcttggttctcc
catcgatgaagaacgcagcgaattgcgataagtaatgtgaattgcagaagt-----gaat
cat-cgaatctttg-aac-gcaccttgcgctccc--ggcagatctaatct-ggggagcat
gcctg-tttgagggccgcgaattgt-ttcgaacg-acagctttcttatttagttgag--a
gagctggcggatcggtatt---gagggtcttgccat-----tttccacggtggctccctc
g-aaatgcattagcgcatccattcgata--ggcaagacggacgaaagctcgttatttcgc
ccacgtctttccctgccgggttttgataatatcaggacttcggagaggaaaggcgctggg
tcgaggagctggacgcgacg----ttttgctggttggagtgcttctgaaccccgcccatg
cctccttct---------------------------------------------------
----ccggaagaggaagggatttaatttcaattcatcggcctcaga-t--ggtaggacta
cccgctgaacta------------------------------------------------
-----------------------------------------------------------
>Pseudozyma_prolifica_AM160639_1 Pseudozyma_prolifica_AM160639.1 803 bp 
tgaacctgcagatggatcattttgatgaaaaaccttttttttctgaggtgtggctcgca-
------------------------------------------------------------
------------------------------------------------------------
-------------------------------cctgtccaactaaacctgagctacctttt
ttatataacacggttgcatcggtcggtctgtcgaaaccagtagcgctcatagcgag----
-------cagcgtctggggaaagacgggtcggcgcttc-ttaccaacacttttga-acac
taggattggaa---ggacaaaaatcatttttttgatgatggaagcgactggtaatgcggt
cgtctaaattgaaaaa------------acaacttttggcaacggatctcttggttctcc
catcgatgaagaacgcagcgaattgcgataagtaatgtgaattgcagaagt-----gaat
cat-cgaatctttg-aac-gcaccttgcgctccc--ggcagatttaatct-ggggagcat
gcctg-tttgagggccgcgaattgt-ttcgaacg-acagcttttttttcttgttgagaaa
gagctggcggatcggtagt---gagggtct--ctgc-----catttaccgtggctccctc
g-aaatgcattagcgcatccattggaaggcggaaagacggacgaaagctcgagttttttt
gccctcgcttccctgccgggttttgataatgtcaggacttcggaggcgaaga-----gag
ggcgggagctggacgcaacgacttttctgctgtttggcgtgcttctgaaccccgcccatg
cctctgctt---------------------------------------------------
-taaccacagaggaagggatttatttttcaattcatcggcctcagatt--ggtaggacta
cccgctgaacttaagcatatc---------------------------------------
-----------------------------------------------------------
>Rhodotorula_GI902_EU108745_3610m Rhodotorula_GI902_EU108745_3610m 803 bp 
----gaattcgcccttggaagtaaaagtcgtaacaaggtttccgtaggtgaacc-tgcgg
------------------------------------------------------------
--------------aa-ggatcattagtgaatat-aggacgtccaacttaac--------
----tt-ggag-----tccgaactctcactttctaaccctgtgcatttg---------tt
tgggatagt------------------------aactctcgcaagagggcgaactccta-
-------tt-cact--------------------------tataaacac-----------
-aaagtctatgaatgtattaaatt------------------------------------
--t--tataacaaaat------------aaaactttcaacaacggatctcttggctctcg
catcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaattcagt-gaat
cat-cgaatctttg-aac-gcaccttgcgctccat-gg------tattcc-gtggagcat
gcctg-tttgagtgtcatgaatact--tcaaccctcc--------tctttcttaatgatt
gaagaggtgtttggtttct---gagcg--ctgctgg---cctttagggtctagctcgttc
g-taatgcattagc----------atcc--------------------------------
---------------------------------------------gcaatc-gaacttcg
gattga--cttggcgtaatagactattcgct-gaggaattct-agtcttcgg-actagag
ccgggttgg-----------------------------------------gttaaaggaa
gcttctaa-tcagaatgt-ctacatttt--aagattagatctcaaatca-ggtaggacta
cccgctgaa-ctt---aagcatatcaataagcggaggaaagggcgaattc----------
-----------------------------------------------------------
>Rhodotorula_GI903_EU108746_3610m Rhodotorula_GI903_EU108746_3610m 803 bp 
---gaattcgccccttggaagtaaaagtcgtaacaaggtttccgtaggtgaacc-tgcgg
------------------------------------------------------------
--------------aa-ggatcattagtgaatat-aggacgtccaacttaac--------
----tt-ggag-----tccgaactctcactttctaaccctgtgcatttg---------tt
tgggatagt------------------------aactctcgcaagagggcgaactccta-
-------tt-cact--------------------------tataaacac-----------
-aaagtctatgaatgtattaaatt------------------------------------
--t--tataacaaaat------------aaaactttcaacaacggatctcttggctctcg
catcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaattcagt-gaat
cat-cgaatctttg-aac-gcaccttgcgctccat-gg------tattcc-gtggagcat
gcctg-tttgagtgtcatgaatact--tcaaccctcc--------tctttcttaatgatt
gaagaggtgtttggtttct---gagcg--ctgctgg---cctttagggtctagctcgttc
g-taatgcattagc----------atcc--------------------------------
---------------------------------------------gcaatc-gaacttcg
gattga--cttggcgtaatagactattcgct-gaggaattct-agtcttcgg-actagag
ccgggttgg-----------------------------------------gttaaaggaa
gcttctaa-tcagaatgt-ctacatttt--aagattagacctcaaatca-ggtaggacta
cccgctgaa-ctt---aagcatatcaataagcggaggaaagggcgaattc----------
-----------------------------------------------------------
>Rhodotorula_GI904_EU108747_3610m Rhodotorula_GI904_EU108747_3610m 803 bp 
----gaattcgcccttggaagtaaaagtcgtaacaaggtttccgtaggtgaacc-tgcgg
------------------------------------------------------------
--------------aa-ggatcattagtgaatat-aggacgtccaacttaac--------
----tt-ggag-----tccgaactctcactttctaaccctgtgcatttg---------tt
tgggatagt------------------------aactctcgcaagagggcgaactccta-
-------tt-cact--------------------------tataaacac-----------
-aaagtctatgaatgtattaaatt------------------------------------
--t--tataacaaaat------------aaaactttcaacaacggatctcttggctctcg
catcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaattcagt-gaat
cat-cgaatctttg-aac-gcaccttgcgctccat-gg------tattcc-gtggagcat
gcctg-tttgagtgtcatgaatact--tcaaccctcc--------tctttcttaatgatt
gaagaggtgtttggtttct---gagcg--ctgctgg---cctttagggtctagctcgttc
g-taatgcattagc----------atcc--------------------------------
---------------------------------------------gcaatc-gaacttcg
gattga--cttggcgtaatagactattcgct-gaggaattct-agtcttcgg-actagag
ccgggttgg-----------------------------------------gttaaaggaa
gcttctaa-tcagaatgt-ctacatttt--aagattagatctcaaatca-ggtaggactg
cccgctgaa-ctt---aagcatatcaataagcggaggaaagggcgaattc----------
-----------------------------------------------------------
>Rhodotorula_GI908_EU108748_3606m Rhodotorula_GI908_EU108748_3606m 803 bp 
------------------------------------------------------------
------------------------------------------------------------
-------------------atcattagtgaatat-aggacgtccaacttaac--------
----tt-ggag-----tccgaactctcactttctaaccctgtgcatttg---------tt
tgggatagt------------------------aactctcgcaagagggcgaactccta-
-------tt-cact--------------------------tataaacac-----------
-aaagtctatgaatgtattaaatt------------------------------------
--t--tataacaaaat------------aaaactttcaacaacggatctcttggctctcg
catcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaattcagt-gaat
cat-cgaatctttg-aac-gcaccttgcgctccat-gg------tattcc-gtggagcat
gcctg-tttgagtgtcatgaatact--tcaaccctcc--------tctttcttaatgatt
gaagaggtgtttggtttct---gagcg--ctgctgg---cctttagggtctagctcgttc
g-taatgcattagc----------atcc--------------------------------
---------------------------------------------gcaatcggaacttcg
gattga--cttggcgtaatagactattcgct-gaggaattct-agtcttcgg-actagag
ccgggttgg-----------------------------------------gtttaaaggg
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------------------
>Rhodotorula_GI909_EU108749_3606m Rhodotorula_GI909_EU108749_3606m 803 bp 
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------gacgtccaaacttca--------
----ctgtgaggagtcccggaactctcactttctaaccatgtgcatttg---------tt
tgggatagt------------------------aactctcgcaagagggcgaactccta-
-------tt-cact--------------------------tataaacac-----------
-aaagtctatgaatgtattaaatt------------------------------------
--t--t-taacaaact------------aaaactttcaacaacggatctcttggctct-g
catcgacgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaattcagt-gaat
cat-cgaatctttg-aac-gcaccttgcgctccat-gg------tattcc-gtggagcat
gcctg-tttgagtgtcatgaatact--tcaaccctcc--------tctttcttaatgatt
gaagaggtgtttggtttct---gagcg--ctgctgg---cctttagggtctagctcgttc
g-taatgcattagc----------atcc--------------------------------
---------------------------------------------gcaatc-gaacttcg
gattggacttgggcgtaatagactattcgcgtgaggaattctaagtcttcgg-actta--
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------------------
>Rhodotorula_GI910_EU108750_3606m Rhodotorula_GI910_EU108750_3606m 803 bp 
------------------------------------------------------------
------------------------------------------------------------
---------------------actcgaaatatat-aggacgtccaacttaac--------
----tt-ggag-----tccgaactctcactttctaaccctgtgcatttg---------tt
tgggatagt------------------------aactctcgcaagagggcgaactccta-
-------tt-cact--------------------------tataaacac-----------
-aaagtctatgaatgtattaaatt------------------------------------
--t--tataacaaaat------------aaaactttcaacaacggatctcttggctctcg
catcgatgaagaacgcagcgaaatgccataagtaatgtgaattgcagaattcagt-gaat
cat-cgaatctttg-aac-gcaccttgcgctccat-gg------tattcc-gtggagcat
gcctg-tttgagtgtcatgaatact--tcaaccctcc--------tctttcttaatgatt
gaagaggtgtttggtttct---gagcg--ctgctgg---cctttagggtctagctcgttc
g-taatgcattagc----------atcc--------------------------------
---------------------------------------------gcaatc-gaacttcg
gattga--cttggcgtaatagactattcgctggaggaattct-agtcttcgg-actagag
ccgggttgg-----------------------------------------gttaaaggaa
gcttctaa-tcagaatgt-ctacatttt--aagattagatctcaaatca-ggtaggacta
------------------------------------------------------------
-----------------------------------------------------------
>Rhodotorula_GI911_EU108751_3606m Rhodotorula_GI911_EU108751_3606m 803 bp 
------------------------------------------------------------
------------------------------------------------------------
-------------------atcattagtgaatat-aggacgtccaacttaac--------
----tt-ggag-----tccgaactctcactttctaaccctgtgcacttg---------tt
tgggatagt------------------------aactctcgcaagagagcgaactccta-
-------tt-cact--------------------------tataaacac-----------
-aaagtctatgaatgtattaaatt------------------------------------
--t--tataacaaaat------------aaaactttcaacaacggatctcttggctctcg
catcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaattcagt-gaat
cat-cgaatctttg-aac-gcaccttgcgctccat-gg------tattcc-gtggagcat
gcctg-tttgagtgtcatgaatact--tcaaccctcc--------tctttcttaatgatt
gaagaggtgtttggtttct---gagcg--ctgctgg---cctttacggtctagctcgttc
g-taatgcattagc----------atcc--------------------------------
---------------------------------------------gcaatc-gaacttcg
gattga--cttggcgtaatagactattcgct-gaggaattct-agtcttcgg-actagag
ccgggttgg-----------------------------------------gttaaaggaa
gcttc-------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------------------
>Rhodotorula_GI914_EU108754_3591m Rhodotorula_GI914_EU108754_3591m 803 bp 
------------------------------------------------------------
------------------------------------------------------------
---------------------------tgaatat-aggacgtccaacttaac--------
----tt-ggag-----tccgaactctcactttctaaccctgtgcatttg---------tt
tgggatagt------------------------aactctcgcaagagggcgaactccta-
-------tt-cact--------------------------tataaacac-----------
-aaagtctatgaatgtattaaatt------------------------------------
--t--tataacaaaat------------aaaactttcaacaacggatctcttggctctcg
catcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaattcagt-gaat
cat-cgaatctttg-aac-gcaccttgcgctccat-gg------tattcc-gtggagcat
gcctg-tttgagtgtcatgaatact--tcaaccctcc--------tctttcttaatgatt
gaagaggtgtttggtttct---gagcg--ctgctgg---cctttagggtctagctcgttc
g-taatgcattagc----------atcc--------------------------------
---------------------------------------------gcaatc-gaacttcg
gattga--cttggcgtaatagactattcgct-gaggaattct-agtcttcgg-actagag
ccgggttgg-----------------------------------------gttaaaggaa
gcttctaa-tcagaatgt-ctacatttt--aaga--------------------------
------------------------------------------------------------
-----------------------------------------------------------
>Rhodotorula_GI926_EU108763_3582m Rhodotorula_GI926_EU108763_3582m 803 bp 
----gaattcgcccttggaagtaaaagtcgtaacaaggtttccgtaggtgaacc-tgcgg
------------------------------------------------------------
--------------aa-ggatcattagtgaatat-aggacgtccaacttaac--------
----tt-ggag-----tccgaactctcactttctaaccctgtgcatttg---------tt
tgggatagt------------------------aactctcgcaagagggcgaactccta-
-------tt-cact--------------------------tataaacac-----------
-aaagtctatgaatgtattaaatt------------------------------------
--t--tataacaaaat------------aaaactttcaacaacggatctcttggctctcg
catcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaattcagt-gaat
cat-cgaatctttg-aac-gcaccttgcgctccat-gg------tattcc-gtggagcat
gcctg-tttgagtgtcatgaatact--tcaaccctcc--------tctttcttaatgatt
gaagaggtgtttggtttct---gagcg--ctgctgg---cctttagggtctagctcgttc
g-taatgcattagc----------atcc--------------------------------
---------------------------------------------gcaatc-gaacttcg
gattga--cttggcgtaatagactattcgct-gaggaattct-agtcttcgg-actagag
ccgggttgg-----------------------------------------gttaaaggaa
gcttctaa-tcagaatgt-ctacatttt--aagattagatctcaaatca-ggtaggacta
cccgctgaa-ctt---aagcatatcaataagcggaggaaagggcgaattc----------
-----------------------------------------------------------
>Rhodotorula_GI927_EU108764_3582m Rhodotorula_GI927_EU108764_3582m 803 bp 
----gaattcgcccttggaagtaaaagtcgtaacaaggtttccgtaggtgaacc-tgcgg
------------------------------------------------------------
--------------aa-ggatcattagtgaatat-aggacgtccaacttaac--------
----tt-ggag-----tccgaactctcactttctaaccctgtgcatttg---------tt
tgggatagt------------------------aactctcgcaagagggcgaactccta-
-------tt-cact--------------------------tataaacac-----------
-aaagtctatgaatgtattaaatt------------------------------------
--t--tataacaaaat------------aaaactttcaacaacggatctcttggctctcg
catcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaattcagt-gaat
cat-cgaatctttg-aac-gcaccttgcgctccat-gg------tattcc-gtggagcat
gcctg-tttgagtgtcatgaatact--tcaaccctcc--------tctttcttaatgatt
gaagaggtgtttggtttct---gagcg--ctgctgg---cctttagggtctagctcgttc
g-taatgcattagc----------atcc--------------------------------
---------------------------------------------gcaatc-gaacttcg
gattga--cttggcgtaatagactattcgct-gaggaattct-agtcttcgg-actagag
ccgggttgg-----------------------------------------gttaaaggaa
gcttctaa-tcagaatgt-ctacatttt--aagattagatctcaaatca-ggtaggacta
cccgctgaa-ctt---aagcatatcaataagcggaggaaagggcgaattc----------
-----------------------------------------------------------
>Rhodotorula_GI928_EU108765_3582m Rhodotorula_GI928_EU108765_3582m 803 bp 
----gaattcgcccttggaagtaaaagtcgtaacaaggtttccgtaggtgaacc-tgcgg
------------------------------------------------------------
--------------aa-ggatcattagtgaatat-aggacgtccaacttaac--------
----tt-ggag-----tccgaactctcactttctaaccctgtgcatttg---------tt
tgggatagt------------------------aactctcgcaagagggcgaactccta-
-------tt-cact--------------------------tataaacac-----------
-aaagtctatgaatgtattaaatt------------------------------------
--t--tataacaaaat------------aaaactttcaacaacggatctcttggctctcg
catcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaattcagt-gaat
cat-cgaatctttg-aac-gcaccttgcgctccat-gg------tattcc-gtggagcat
gcctg-tttgagtgtcatgaatact--tcaaccctcc--------tctttcttaatgatt
gaagaggtgtttggtttct---gagcg--ctgctgg---cctttagggtctagctcgttc
g-taatgcattagc----------atcc--------------------------------
---------------------------------------------gcaatc-gaacttcg
gattga--cttggcgtaatagactattcgct-gaggaattct-agtcttcgg-actagag
ccgggttgg-----------------------------------------gttaaaggaa
gcttctaa-tcagaatgt-ctacatttt--aagattagatctcaaatca-ggtaggacta
cccgctgaa-ctt---aagcatatcaataagcggaggaaagggcgaattc----------
-----------------------------------------------------------
>Rhodotorula_GI929_EU108766_3582m Rhodotorula_GI929_EU108766_3582m 803 bp 
----gaattcgcccttggaagtaaaagtcgtaacaaggtttccgtaggtgaaccttgcgg
------------------------------------------------------------
--------------aa-ggatcattagtgaatat-aggacgtccaacttaac--------
----tt-ggag-----tccgaactctcactttctaaccctgtgcatttg---------tt
tgggatagt------------------------aactctcgcaagagggcgaactccta-
-------tt-cact--------------------------tataaacac-----------
-aaagtctatgaatgtattaaatt------------------------------------
--t--tataacaaaat------------aaaactttcaacaacggatctcttggctctcg
catcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaattcagt-gaat
cat-cgaatctttg-aac-gcaccttgcgctccat-gg------tattcc-gtggagcat
gcctg-tttgagtgtcatgaatact--tcaaccctcc--------tctttcttaatgatt
gaagaggtgtttggtttct---gagcg--ctgctgg---cctttagggtctagctcgttc
g-taatgcattagc----------atcc--------------------------------
---------------------------------------------gcaatc-gaacttcg
gattga--cttggcgtaatagactattcgct-gaggaattct-agtcttcgg-actagag
ccgggttgg-----------------------------------------gttaaaggaa
gcttctaa-tcagaatgt-ctacatttt--aagattagatctcaaatca-ggtaggacta
cccgctgaa-ctt---aagcatatcaataagcggaggaaagggcgaattc----------
-----------------------------------------------------------
>Rhodotorula_GI931_EU108768_3582m Rhodotorula_GI931_EU108768_3582m 803 bp 
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------aaccctcc--------tctttcttaatgatt
gaagaggtgtttggtttct---gagcg--ctgctgg---cctttagggtctagctcgttc
g-taatgcattagc----------atcc--------------------------------
---------------------------------------------gcaatc-gaacttcg
gattga--cttggcgtaatagactattcgct-gaggaattct-agtcttcgg-actagag
ccgggttgg-----------------------------------------gttaaaggaa
gcttctaa-tcagaatgt-ctacatttt--aagattagatctcaaatca-ggtaggacta
cccgctgaa-ctt---aagcatatcaataagcggaggaaagggcgaattcgttt------
-----------------------------------------------------------
>Rhodotorula_GI933_EU108770_3582m Rhodotorula_GI933_EU108770_3582m 803 bp 
----gaattcgcccttggaagtaaaagtcgtaacaaggtttccgtaggtgaacc-tgcgg
------------------------------------------------------------
--------------aa-ggatcattagtgaatat-aggacgtccaacttaac--------
----tt-ggag-----tccgaactctcactttctaaccctgtgcatttg---------tt
tgggatagt------------------------aactctcgcaagagggcgaactccta-
-------tt-cact--------------------------tataaacac-----------
-aaagtctatgaatgtattaaatt------------------------------------
--t--tataacaaaat------------aaaactttcaacaacggatctcttggctctcg
catcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaattcagt-gaat
cat-cgaatctttg-aac-gcaccttgcgctccat-gg------tattcc-gtggagcat
gcctg-tttgagtgtcatgaatact--tcaaccctcc--------tctttcttaatgatt
gaagaggtgtttggtttct---gagcg--ctgctgg---cctttagggtctagctcgttc
g-taatgcattagc----------atcc--------------------------------
---------------------------------------------gcaatc-gaacttcg
gattga--cttggcgtaatagactattcgct-gaggaattct-agtcttcgg-actagag
ccgggttgg-----------------------------------------gttaaaggaa
gcttctaa-tcagaatgt-ctacatttt--aagattagatctcaaatca-ggtaggacta
cccgctgaa-ctt---aagcatatcaataagcggaggaaagggcgaattc----------
-----------------------------------------------------------
>Rhodotorula_GI939_EU108775_3582m Rhodotorula_GI939_EU108775_3582m 803 bp 
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------tccaacttaac--------
----tt-ggag-----tccgaactctcactttctaaccctgtgcatttg---------tt
tgggatagt------------------------aactctcgcaagagggcgaactccta-
-------tt-cact--------------------------tataaacac-----------
-aaagtctatgaatgtattaaatt------------------------------------
--t--tataacaaaat------------aaaactttcaacaacggatctcttggctctcg
catcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaattc-gt-gaat
cat-cgaatctttg-aac-gcaccttgcgctccat-gg------tattcc-gtggagcat
gcctg-tttgagtgtcatgaatact--tcaaccctcc--------tctttcttaatgatt
gaagaggtgtttggtttct---gagcg--ctgctgg---cctttagggtctagctcgttc
g-taatgcattcgc----------atcc--------------------------------
---------------------------------------------gcaatc-gaacttcg
gattga--cttggcgtaatagactattcgct-gaggaattct-agtcttcggaactagag
ccgggttgg-----------------------------------------gttaaaggaa
gcttctaa-tcagaatgt-ctacatttt--aagattagatctcaattta-----------
------------------------------------------------------------
-----------------------------------------------------------
>Rhodotorula_GI945_EU108780_3582m Rhodotorula_GI945_EU108780_3582m 803 bp 
---ggaattcgcccttggaagtaaaagtcgtaacaaggtttccgtaggtgaacc-tgcgg
------------------------------------------------------------
--------------aa-ggatcattagtgaatat-aggacgtccaacttaac--------
----tt-ggag-----tccgaactctcactttctaaccctgtgcatttg---------tt
tgggatagt------------------------aactctcgcaagagggcgaactccta-
-------tt-cact--------------------------tataaacac-----------
-aaagtctatgaatgtattaaatt------------------------------------
--t--tataacaaaat------------aaaactttcaacaacggatctcttggctctcg
catcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaattcagt-gaat
cat-cgaatctttg-aac-gcaccttgcgctccat-gg------tattcc-gtggagcat
gcctg-tttgagtgtcatgaatact--tcaaccctcc--------tctttcttaatgatt
gaagaggtgtttggtttct---gagcg--ctgctgg---cctttagggtctagctcgttc
g-taatgcattagc----------atcc--------------------------------
---------------------------------------------gcaatc-gaacttcg
gattga--cttggcgtaatagactattcgct-gaggaattct-agtcttcgg-actagag
ccgggttgg-----------------------------------------gttaaaggaa
gcttctaa-tcagaatgt-ctacatttt--aagattagatctcaaatcacggtaggacta
cccgctgca-acttacacgcatatcaataagcggaggaagggcgaattc-----------
-----------------------------------------------------------
>Rhodotorula_GI946_EU108781_3582m Rhodotorula_GI946_EU108781_3582m 803 bp 
----gaattcgcccttggaagtaaaagtcgtaacaaggtttccgtaggtgaacc-tgcgg
------------------------------------------------------------
--------------aa-ggatcattagtgaatat-aggacgtccaacttaac--------
----tt-ggag-----tccgaactctcactttctaaccctgtgcatttg---------tt
tgggatagt------------------------aactctcgcaagagggcgaactccta-
-------tt-cact--------------------------tataaacac-----------
-aaagtctatgaatgtattaaatt------------------------------------
--t--tataacaaaat------------aaaactttcaacaacggatctcttggctctcg
catcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaattcagt-gaat
cat-cgaatctttg-aac-gcaccttgcgctccat-gg------tattcc-gtggagcat
gcctg-tttgagtgtcatgaatact--tcaaccctcc--------tctttcttaatgatt
gaagaggtgtttggtttct---gagcg--ctgctgg---cctttagggtctagctcgttc
g-taatgcattagc----------atcc--------------------------------
---------------------------------------------gcaatc-gaacttcg
gattga--cttggcgtaatagactattcgct-gaggaattct-agtcttcgg-actagag
ccgggttgg-----------------------------------------gttaaaggaa
gcttctaa-tcagaatgt-ctacatttt--aagattagatctcaaatca-ggtaggacta
cccgctgaa-ctt---aagcatatcaataagcggaggaaagggcgaattc----------
-----------------------------------------------------------
>Rhodotorula_GI947_EU108782_3582m Rhodotorula_GI947_EU108782_3582m 803 bp 
----gaattcgcccttggaagtaaaagtcgtaacaaggtttccgtaggtgaacc-tgcgg
------------------------------------------------------------
--------------aa-ggatcattagtgaatat-aggacgtccaacttaac--------
----tt-ggag-----tccgaactctcactttctaaccctgtgcatttg---------tt
tgggatagt------------------------aactctcgcaagagggcgaactccta-
-------tt-cact--------------------------tataaacac-----------
-aaagtctatgaatgtattaaatt------------------------------------
--t--tataacaaaat------------aaaactttcaacaacggatctcttggctctcg
catcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaattcagt-gaat
cat-cgaatctttg-aac-gcaccttgcgctccat-gg------tattcc-gtggagcat
gcctg-tttgagtgtcatgaatact--tcaaccctcc--------tctttcttaatgatt
gaagaggtgtttggtttct---gagcg--ctgctgg---cctttagggtctagctcgttc
g-taatgcattagc----------atcc--------------------------------
---------------------------------------------gcaatc-gaacttcg
gattga--cttggcgtaatagactattcgct-gaggaattct-agtcttcgg-actagag
ccgggttgg-----------------------------------------gttaaaggaa
gcttctaa-tcagaatgt-ctacatttt--aagattagatctcaaatca-ggtaggacta
cccgctgaa-ctt---aagcatatcaataagcggaggaaagggcgaattc----------
-----------------------------------------------------------
>Rhodotorula_GI948_EU108783_3582m Rhodotorula_GI948_EU108783_3582m 803 bp 
----gaattcgcccttggaagtaaaagtcgtaacaaggtttccgtaggtgaacc-tgcgg
------------------------------------------------------------
--------------aa-ggatcattagtgaatat-aggacgtccaacttaac--------
----tt-ggag-----tccgaactctcactttctaaccctgtgcatttg---------tt
tgggatagt------------------------aactctcgcaagagggcgaactccta-
-------tt-cact--------------------------tataaacac-----------
-aaagtctatgaatgtattaaatt------------------------------------
--t--tataacaaaat------------aaaactttcaacaacggatctcttggctctcg
catcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaattcagt-gaat
cat-cgaatctttg-aac-gcaccttgcgctccat-gg------tattcc-gtggagcat
gcctg-tttgagtgtcatgaatact--tcaaccctcc--------tctttcttaatgatt
gaagaggtgtttggtttct---gagcg--ctgctgg---cctttagggtctagctcgttc
g-taatgcattagc----------atcc--------------------------------
---------------------------------------------gcaatc-gaacttcg
gattga--cttggcgtaatagactattcgct-gaggaattct-agtcttcgg-actagag
ccgggttgg-----------------------------------------gttaaaggaa
gcttctaa-tcagaatgt-ctacatttt--aagattagatctcaaatca-ggtaggacta
cccgctgaa-ctt---aagcatatcaataagcggaggaaagggcgaattc----------
-----------------------------------------------------------
>Rhodotorula_GI949_EU108784_3582m Rhodotorula_GI949_EU108784_3582m 803 bp 
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------aatt------------------------------------
--t--tataacaaaat------------aaaactttcaacaacggatctcttggctctcg
catcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaattcagt-gaat
cat-cgaatctttg-aac-gcaccttgcgctccat-gg------tattcc-gtggagcat
gcctg-tttgagtgtcatgaatact--tcaaccctcc--------tctttcttaatgatt
gaagaggtgtttggtttct---gagcg--ctgctgg---cctttagggtctagctcgttc
g-taatgcattagc----------atcc--------------------------------
---------------------------------------------gcaatc-g---ctcg
gattga--cttggcgtaatagactattcgct-gaggaattct-agtcttcgg-actagag
ccgggttgg-----------------------------------------gttaaaggaa
gcttctaa-tcagaatgt-ctacatttt--aagattagatctcaaatca-ggtaggacta
cccgctgaa-ctt---aagcatatcaat--------------------------------
-----------------------------------------------------------
>Rhodotorula_GI951_EU108786_3563m Rhodotorula_GI951_EU108786_3563m 803 bp 
--------------------------------------------taggtgaacc-tgcgg
------------------------------------------------------------
--------------aa-gga-cattagtgaatat-aggacgtccaacttaac--------
----tt-ggag-----tccgaactctcactttctaaccctgtgcatttg---------tt
tgggatagt------------------------aactctcgcaagagggcgaactccta-
-------tt-cact--------------------------tataaacac-----------
-aaagtctatgaatgtattaaatt------------------------------------
--t--tataacaaaat------------aaaactttcaacaacggatctcttggctctcg
catcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaattcagt-gaat
cat-cgaatctttg-aac-gcaccttgcgctccat-gg------tattcc-gtggagcat
gcctg-tttgagtgtcatgaatact--tcaaccctcc--------tctttcttaatgatt
gaagaggtgtttggtttct---gagcg--ctgctgg---cctttagggtctagctcgttc
g-taatgcattagc----------atcc--------------------------------
---------------------------------------------gcaatc-gaacttcg
gattga--cttggcgtaatagactattcgct-gaggaattct-agtcttcgg-actagag
ccgggttgg-----------------------------------------gttaaaggaa
gcttctaa-tcagaatgt-ctacatttt--aagattagatctcaaatca-ggtaggac--
------------------------------------------------------------
-----------------------------------------------------------
>Rhodotorula_GI952_EU108787_3563m Rhodotorula_GI952_EU108787_3563m 803 bp 
----------------------------------------------ggtgaacc-tgcgg
------------------------------------------------------------
--------------aa-ggatcattagtgaatat-aggacgtccaacttaac--------
----tt-ggag-----tccgaactctcactttctaaccctgtgcatttg---------tt
tgggatagt------------------------aactctcgcaagagggcgaactccta-
-------tt-cact--------------------------tataaacac-----------
-aaagtctatgaatgtattaaatt------------------------------------
--t--tataacaaaat------------aaaactttcaacaacggatctcttggctctcg
catcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaattcagt-gaat
cat-cgaatctttg-aac-gcaccttgcgctccat-gg------tattcc-gtggagcat
gcctg-tttgagtgtcatgaatact--tcaaccctcc--------tctttcttaatgatt
gaagaggtgtttggtttct---gagcg--ctgctgg---cctttagggtctagctcgttc
g-taatgcattagc----------atcc--------------------------------
---------------------------------------------gcaatc-gaacttcg
gattga--cttggcgtaatagactattcgct-gaggaattct-agtcttcgg-actagag
ccgggttgg-----------------------------------------gttaaaggaa
gcttctaa-tcagaatgt-ctacatttt--aagattagatctcaaatca-ggtaggacta
ccc---------------------------------------------------------
-----------------------------------------------------------
>Rhodotorula_GI959_EU108793_3501m Rhodotorula_GI959_EU108793_3501m 803 bp 
------------------------------------------------------------
------------------------------------------------------------
----------------------actctaagatat-aggacgtcc-acttaac--------
----ttggcag-----tccgaactctcactttctaaccctgtgcacttg---------tt
tgggatagt------------------------aactctcgcaagagagcgaactccta-
-------tt-cact--------------------------tataaacac-----------
-aaagtctatgaatgtattaaatt------------------------------------
--t--tataacaaaat------------aaaactttcaacaacggatctcttggctctcg
catcgatgaagaacgcagcgaaatgccataagtaatgtgaattgcagaattcagt-gaat
cat-cgaatctttg-aac-gcaccttgcgctccat-gg------tattcc-gtggagcat
gcctg-tttgagtgtcatgaatact--tcaaccctcc--------tctttcttaatgatt
gaagaggtgtttggtttct---gagcg--ctgctgg---cctttacggtctagctcgttc
g-taatgcattagc----------atcc--------------------------------
---------------------------------------------gcaatc-gaacttcg
gattga--cttggcgtaatagactattcgct-gaagaattct-agtcttcgg-actagag
ccgggttgg-----------------------------------------gttaaaggaa
gcttctaa-tcagaatgt-ctacatttt--aagattagatctcaatca--ggtaggacta
cccgctgaa-cttaagc-------------------------------------------
-----------------------------------------------------------
>Rhodotorula_GI962_EU108795_3501m Rhodotorula_GI962_EU108795_3501m 803 bp 
------------------------------------ggtttccgtaggtgaacc-tgcgg
------------------------------------------------------------
--------------aa-ggatcattagtgaatat-aggacgtccaacttaac--------
----tt-ggag-----tccgaactctcactttctaaccctgtgcatttg---------tt
tgggatagt------------------------aactctcgcaagagggcgaactccta-
-------tt-cact--------------------------tataaacac-----------
-aaagtctatgaatgtattaaatt------------------------------------
--t--tataacaaaat------------aaaactttcaacaacggatctcttggctctcg
catcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaattcagt-gaat
cat-cgaatctttg-aac-gcaccttgcgctccat-gg------tattcc-gtggagcat
gcctg-tttgagtgtcatgaatact--tcaaccctcc--------tctttcttaatgatt
gaagaggtgtttggtttct---gagcg--ctgctgg---cctttagggtctagctcgttc
g-taatgcattagc----------atcc--------------------------------
---------------------------------------------gcaatc-gaacttcg
gattga--cttggcgtaatagactattcgct-gaggaattct-agtcttcgg-actagag
ccgggttgg-----------------------------------------gttaaaggaa
gcttctaa-tcagaatgtgctacatttt--aagattagatctc-----------------
------------------------------------------------------------
-----------------------------------------------------------
>Rhodotorula_GI966_EU108797_3501m Rhodotorula_GI966_EU108797_3501m 803 bp 
---------------------------------------ttccgtaggtgaacc-tgcgg
------------------------------------------------------------
--------------aa-ggatcattagtgaatat-aggacgtccaacttaac--------
----ttgggag-----tccgaactctcactttctaaccctgtgcatttg---------tt
tgggatagt------------------------aactctcgcaagagggcgaactccta-
-------tt-cact--------------------------tataaacac-----------
-aaagtctatgaatgtattaaatt------------------------------------
--t--tataacaaaat------------aaaactttcaacaacggatctcttggctctcg
catcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaattcagt-gaat
cat-cgaatctttg-aac-gcaccttgcgctccat-gg------tattcc-gtggagcat
gcctg-tttgagtgtcatgaatact--tcaaccctcc--------tctttcttaatgatt
gaagaggtgtttggtttct---gagcg--ctgctgg---cctttagggtctagctcgttc
g-taatgcattagc----------atcc--------------------------------
---------------------------------------------gcaatc-gaacttcg
gattga--cttggcgtaatagactattcgct-gaggaattct-agtcttcgg-actagag
ccgggttgg-----------------------------------------gttaaaggaa
gcttctaattcagaatgtgctacattcttaagcattagatct------------------
------------------------------------------------------------
-----------------------------------------------------------
>Rhodotorula_glucinis_EF194846_1_marine Rhodotorula_glucinis_EF194846.1_marine 803 bp 
--------------tggaaggtaaaaatcgtaacaaggtttccgtaggtgaacc-tgcgg
------------------------------------------------------------
--------------aa-ggatcattagtgaacat-aggacgtccaacttaac--------
----tt-ggag-----tccgaactctcactttctaaccctgtgcatttg---------tt
tggggtagt------------------------agcctct----cggggcgaatcccta-
-------tt-cact--------------------------tataaacac-----------
-aaagtctatgaatgtatttaatt------------------------------------
--t--tataacaaaat------------aaaactttcaacaacggatctcttggctctcg
catcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaattcagt-gaat
cat-cgaatctttg-aac-gcaccttgcgctccat-gg------tattcc-gtggagcat
gcctg-tttgagtgtcatgaatact--tcaaccctcc--------tctttctttatgatc
gaagaggtgtttggattct---gagcgttttgctgg---cc-tcacggtcgagctcgctc
g-taatgcattagc----------atcc--------------------------------
---------------------------------------------gcaatc-gaacttcg
gattga--cttggcgtaatagactattcgct-gaggaattct-agtcttcgg-actagag
ccgggttgg-----------------------------------------attaaaggaa
gctcctaa-tcctaatgt---ctatttt--aagattagatctcaaatca-ggtaggacta
cccgctgaa-ctt---aagcatatcaataagcggaggaa---------------------
-----------------------------------------------------------
>Rhodotorula_mucilaginosa_AF444614_1 Rhodotorula_mucilaginosa_AF444614.1 803 bp 
----------------------------------------tccgtaggtgaacc-tgcgg
------------------------------------------------------------
--------------aa-ggatcattagtgaatat-aggacgtccaacttaac--------
----tt-ggag-----tccgaactctcactttctaaccctgtgcacttg---------tt
tgggatagt------------------------aactctcgcaagagagcgaactccta-
-------tt-cact--------------------------tataaacac-----------
-aaagtctatgaatgtattaaatt------------------------------------
--t--tataacaaaat------------aaaactttcaacaacggatctcttggctctcg
catcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaattcagt-gaat
cat-cgaatctttg-aac-gcaccttgcgctccat-gg------tattcc-gtggagcat
gcctg-tttgagtgtcatgaatact--tcaaccctcc--------tctttcttaatgatt
gaagaggtgtttggtttct---gagcg--ctgctgg---cctttacggtctagctcgttc
g-taatgcattagc----------atcc--------------------------------
---------------------------------------------gcaatc-gaacttcg
gattga--cttggcgtaatagactattcgct-gaggaattct-agtcttcgg-actagag
ccgggttgg-----------------------------------------gttaaaggaa
gcttctaa-tcagaatgt-ctacatttt--aagattagatctcaaatca-ggtaggacta
cccgctgaa-ctt---aagcatatcaataagcggaggaaaag------------------
-----------------------------------------------------------
>Rhodotorula_mucilaginosa_AM117824_1_deep_sea Rhodotorula_mucilaginosa_AM117824.1_deep_sea 803 bp 
------------------------------------------------------------
------------------------------------------------------------
--------------aa-ggatcattagtgaatat-aggacgtccaacttaac--------
----tt-ggag-----tccgaactctcgctttctaaccctgtgcacttg---------tt
tgggatagt------------------------aactctcgcaagagagcgaactccta-
-------tt-cact--------------------------tataaacac-----------
-aaagtctatgaatgtattaaatt------------------------------------
--t--tataacaaaat------------aaaactttcaacaacggatctcttggctctcg
catcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaattcagt-gaat
cat-cgaatctttg-aac-gcaccttgcgctccat-gg------tattcc-gtggagcat
gcctg-tttgagtgtcatgaatact--tcaaccctcc--------tctttcttaatgatt
gaagaggtgtttggtttct---gagcg--ctgctgg---cctttacggtctagctcgttc
g-taatgcattagc----------atcc--------------------------------
---------------------------------------------gcaatc-gaacttcg
gattga--cttggcgtaatagactattcgct-gaggaattct-agtcttcgg-actagag
ccgggttgg-----------------------------------------gttaaaggaa
gcttctaa-tcagaatgt-ctacatttt--aagattagatctcaaatca-ggtaggacta
cccgctgaa-ctt---aa------------------------------------------
-----------------------------------------------------------
>Rhodotorula_sp__DQ015695_1_Antarctic_sea_ice_psychrophile Rhodotorula_sp._DQ015695.1_Antarctic_sea_ice_psychrophile 803 bp 
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------tgtcgaactccat--------
----t--ggag-----tccgaactctcactttctaaccctgtgcacttg---------tt
tgggatagt------------------------aactctcgcaagagagcgaactccta-
-------tt-cact--------------------------tataaacac-----------
-aaagtctatgaatgtattaaatt------------------------------------
--t--tataacaaaat------------aaaactttcaacaacggatctcttggctctcg
catcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaattcagt-gaat
cat-cgaatctttg-aac-gcaccttgcgctccat-gg------tattcc-gtggagcat
gcctg-tttgagtgtcatgaatact--tcaaccctcc--------tctttcttaatgatt
gaagaggtgtttggtttct---gagcg--ctgctgg---cctttacggtctagctcgttc
g-taatgcattagc----------atcc--------------------------------
---------------------------------------------gccatc-gaacttcg
gattga--cttggcgtaatagactattcgct-gaggaattct-agtcttcgg-attagag
ccgggatgg-----------------------------------------gttaaaggaa
gcttctaa-tcagaatgt-ctacatttt--aagattagatctcaaatta-gg-aggacta
cccgctgaa-ctt---aagcatatcaataagcggaggaa---------------------
-----------------------------------------------------------
>Rhodotorula_sp__DQ643075_1_deep_sea Rhodotorula_sp._DQ643075.1_deep_sea 803 bp 
----------------------------------------tccgtaggtgaacc-tgcgg
------------------------------------------------------------
--------------aa-ggatcattagtgaatat-aggacgtccaacttaac--------
----tt-ggag-----tccgaactctcactttctaaccctgtgcacttg---------tt
tgggatagt------------------------aactctcgcaagagagcgaactccta-
-------ttccact--------------------------tataaacac-----------
-aaagtctatgaatgtattaaatt------------------------------------
--t--tataacaaaat------------aaaactttcaacaacggatctcttggctctcg
catcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaattcagt-gaat
cat-cgaatctttg-aac-gcaccttgcgctccat-gg------tattcc-gtggagcat
gcctg-tttgagtgtcatgaatact--tcaaccctcc--------tctttcttaatgatt
gaagaggtgtttggtttct---gagcg--ctgctgg---cctttacggtctagctcgttc
g-taatgcattagc----------atcc--------------------------------
---------------------------------------------gcaatc-gaacttcg
gattga--cttggcgtaatagactattcgct-gaggaattct-agtcttcgg-actagag
ccgggttgg-----------------------------------------gttaaaggaa
gcttctaa-tcagaatgt-ctacatttt--aagattagatctcaaatca-ggtaggacta
cccgctgaa-ctt---aagcatatcaataagcggaggaa---------------------
-----------------------------------------------------------
>Saccharomyces_cerevisiae_AM900396_1 Saccharomyces_cerevisiae_AM900396.1 803 bp 
-------------------------------------------tgcgcttaagtgcgcgg
tcttgctaggcttgtaagtttctttcttgctattccaaacggtgagagatttctgtgctt
ttgttataggacaattaaaaccgtttcaatacaacacactgtggagttttca--------
------------------------------------------------------tatctt
tgcaactttttctttgg-gcattcgagcaatcgg--ggcccagaggtaacaaacacaaa-
-------caattttatttattc------------------attaaatt------------
----tttgtcaaaaacaagaattt------------------------------------
--tcgtaactggaaattttaaaatattaaaaactttcaacaacggatctcttggttctcg
catcgatgaagaacgcagcgaaatgcgatacgtaatgtgaattgcagaattccgt-gaat
cat-cgaatctttg-aac-gcacattgcgcccctt-gg------tattcc-agggggcat
gcctg-tttgagcgtcatttccttc--tcaaacattc-tg--------------------
----------tttggtagt---gagtg---------------------------------
--atactctttggagttaacttgaaatt--------------------------------
---------------------------------------------gctggc---------
--------cttttcattggatgttttttttccaaagagaggtttctctgcgtgcttga--
--------g------------------------------------------------gta
taatgcaagtacggtcgttttaggttttaccaactgcggctaatcttttttatactgagc
gtattggaacgttatcgataagaagagagcgtctaggcgaacaatgttcttaaa------
-----------------------------------------------------------
>Sporidiobolales_sp__EF060587_1_marine Sporidiobolales_sp._EF060587.1_marine 803 bp 
-tcttggtcatttagaggaagtaaaagtcgtaacaaggtttccgtaggtgaacc-tgcgg
------------------------------------------------------------
--------------aa-ggatcattagtgaatat-aggacgtccaacttaac--------
----tt-ggag-----tccgaactctcactttctaaccctgtgcacttg---------tt
tgggatagt------------------------aactctcgcaagagagcgaactccta-
-------tt-cact--------------------------tataaacac-----------
-aaagtctatgaatgtattaaatt------------------------------------
--t--tataacaaaat------------aaaactttcaacaacggatctcttggctctcg
catcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaattcagt-gaat
cat-cgaatctttg-aac-gcaccttgcgctccat-gg------tattcc-gtggagcat
gcctg-tttgagtgtcatgaatact--tcaaccctcc--------tctttcttaatgatt
gaagaggtgtttggtttct---gagcg--ctgctgg---cctttacggtctagctcgttc
g-taatgcattagc----------atcc--------------------------------
---------------------------------------------gcaatc-gaacttcg
gattga--cttggcgtaatagactattcgct-gaggaa-tct-agtcttcgg-atta-aa
cccggttgg-----------------------------------------gttaaaggaa
gcttctaa-tcagaatgt-ctacatttt---aagatagatctcaaatca-gggaggactc
ccgctgaac-ttagcctatcattagcggaggaaaagaactaacagggtttc---------
-----------------------------------------------------------
