>Aegopogon_bryophilus 668 bp 
tcgtgaccctgaccaaaaaagaccgtgaatatgtcatccatgc-cgccgtt--tgatggg
-gcttgcacctgtctctcggtatggggcacat---accttt--ttctacaagggttgtg-
ctc--caaaaagaacccacggcgctgtatggcgtcaaggaaaactga-tat---tacttg
ttc-ggggcct----agttcggcttgccggactaa--ccccgggcagagat-gatatgct
a----atc-cacatgactctcggcaacggatatctcggctctcgcatcgatgaagaacgt
agcaaaatgcgatacctggtgtgaattgcagaatcccgtgaaccatcgagtttttgaacg
caagttgcgcccgaggccttctggttgagggcacgtctgcctgggcgtcacgccaaaaga
cactccccaacatgccctatgttg--gt------tgggacgtggtatttagcc-cctcgt
gcc--ttt-ggcgcggtgggcacaagttggggctgccggcagtgccgatcacagcacaag
gtggatgacgcaagttgttctcggtgctatgatatgtactgattaaggcgattctat-gg
--------cccattgga-cccacggatcgaagtgcacatcgttcgaaccgcga
>Aegopogon_cenchroides 668 bp 
tcgtgaccctgaccaaaaaagaccgtgaacatgtcatccatgc-cgccgtt--tgatggg
-gcttgcacccgtctctcggtatggggcacat---accttc--ttctagaagggaagtgc
ccc--caaaaagaacccacggcgctgtatggcgtcaaggaaaactga-tat---tgcttg
ttt-ggggcca----cgttcggcttgccggactaa--ccctaggcagtgat-gatatgct
a----atc-cacatgactctcggcaacggatatctcggctctcgcatcgatgaagaacgt
agcaaaatgcgatacctggtgtgaattgcagaatcccgtgaaccatcgagtttttgaacg
caagttgcgcccgaggccttctggttgagggcacgtctgcctgggcgtcacgccaaaaga
cactccccaacatgccctatgttg--gt------tgggacgtggtatttagcc-cctcgt
gcc-attg-ggcgcggtgggcacaagttggggctgccggcagtgccgatcacagcacaag
gtggatgacgcaagttgttctcggtgctatgaaacgtactgattaaggcgattctac-gg
--------cccattgtaccccacggatcgaagtgcacatcgttcgaaccgcga
>Bealia_mexicana 677 bp 
tcgtgaccctgaccaaaacagaccgtgaacatgtcatccatgc-cgccggt--tgatggg
-gsttgcacccgtctcccagcacggggcacaa---accttc---ttcaagaagagagtgc
ccc--aaaaaagaacccacggcgccgtatggcgtcaaggaaaactaataaa---tcctag
cty-cggggca----cgctcggcttgccggacgaa--ccccgagcagtgat-gctatgst
a----ata-cacatgactctcggcaacggatatctcggctctcgcatcgatgaagaacgt
agcaaaatgcgatacctggtgtgaattgcagaatcccgtgaaccattgagtttttgaacg
caagttgcgcctgaggccttttggttgagggcacgtctgcctgggcgtcacgccaaaaga
cactcctcac-----caaatcctg--gt------gtggacgtgatatttggcc-cctcgt
gcc-tttg--gcacggtgggcctaagtaggggctgccggcggtgccgatcacagcacaag
gtggatgacgcaagttgttctcggtgctacgatatgaaccgtttacggcataactataag
--------ccctttggaccca-gcgaccgatgcacacgtagctcggaccgcga
>Blepharidachne_kingii 668 bp 
tcgtgaccctgaccaaaacagaccgcgaacgtgtcatcaatgc-tgccggg--agacggg
-tcttgcactcgtctcttggttaggcgtgcca---accttc---ttcggaaggtagggac
cct----aaaagaacccacggcgccgtatggcgtcaaggaacactgaaatt---gccttg
cgc-gggacca----cgaccggcctgtcggacgta--ccccgtgcagggat-gatatgtt
a----atc-cacatgactctcggcaacggatatctcggctctcgcatcgatgaagaacgt
agcaaaatgcgatacctggtgtgaattgcagaatcccgtgaaccatcgagtttttgaacg
caagttgcgcctgaggccttatggccgagggcacgtctgcctgggcgtcacgccaaaaga
cactccaca------ccaatcctg--gt------gcggacgtggtattcggcc-cctcgt
gcc-att---gcgcggtgggcctaagtctgggctgccggcggtgccgatcacagcacaag
gtggatgacgcaagttgttctcggtgttgcgatttggaccgctttcagtgatgatac-gg
--------ccctcgagaccca-tagacccaagcacacgtcgcttggaccgcga
>Blepharoneuron_shepherdii 668 bp 
tcgtgaccctgaccaaaacagaccgtgaacatgtcatccatgcc-gccggg--tgatggg
-gcttgcacccatctcctggcacggggcacag---accttc--ttctagaagagaaatgc
ccc---aaaaagaacccacggcgccgtacggcgtcaaggaacactgataaa---tctttg
ctc-aggag-a----cgtccggcttgccggacgaa--ccttgtgcagcgat-gctattcg
a----ata-cacatgactctcggcaacggatatctcggctctcgcatcgatgaagaacgt
agcaaaatgcgatacctggtgtgaattgcagaatcccgtgaaccatcgagtttttgaacg
caagttgcgcccgaggccttttggttgagggcacgtctgcctgggcgtcacgccaaaaga
cactcccca------ccaatctcg--gt------gcggacgtggtatttggcc-tctcgt
gtc-tttg-tgcgcggtgggcacaagttggggctgccggcggtgccgatcacagcacaag
gtggatgacgctagttgttctcggtgctacgatacgatccgctcacggcaattgtac-gg
--------cccttttgaccca-ttgatcgaagcgcatgccgctcgaaccgcga
>Blepharoneuron_tricholepis 671 bp 
tcgtgaccctgaccaaaacagaccgtgaacatgtcatccatgcc-gctggt--tgatggg
-gcttgcacctgtcacccagcacggggcacag---accttc--ttctagaagtgaaatgt
ccc---aaaaagaacccacggcgccgtatggcgtcaaggaacactgataaa---tccttg
ctc-gggggca----cgtctggcttgccggacgaa--ccccgtgcagcggtagctatgtg
a----ata-cacatgactctcggcaacggatatctcggctctcgcatcgatgaagaacgt
agcaaaatgcgatacctggtgtgaattgcagaatcccgtgaaccatcgagtttttgaacg
caagttgcgcccgaggccttttggttgagggcacgtctgcctgggcgtcacgccaaaaga
cactcccca------ccaatccyg--gt------gcggacgtggtatttggcc-cctcgt
gcc-tttg-tgcgcggtgggcagaagttggggctgccggcggtgccggtcacagcacaag
gtggatgacgcaagttattctcggtgctacgacacggaccgcttacggcaat--cac-gg
--------cccttttgaccca-ttgaccgaagcgcatgccgctcggaccgcga
>Bouteloua_trifida 668 bp 
tcgtgaccctaaccaaaacagaccgtgaacatgttacccatgc-cgctggg--cgatggg
-tctcgcacccatctctcagaacagggtgccg---accttc---gttagaggggaggggc
cct----aaatgaacccacggcgccgtatggcgtcaaggaacacagatatt---gccttg
cgt-ggggtgt----ggactggcatgccagtcggac-ccccgtgcagcgat-catatgtt
a----ttt-cacatgactctcggcaacggatatctcggctctcgcatcgatgaagaacgt
agcaaaatgcgatacctggtgtgaattgcagaatcccgtgaaccatcgagtttttgaacg
caagttgcgcccgagaccttctggtcgagggcacgtctgcctgggcgtcatgccaaaaga
cacacccca------cccatcaag--ttgaggtggaggaagtggtatttggct-ctccgt
gca-tcta-ggtgcggtgggcctaagttggggctgccggcggtgccgatcacagcacaag
gtggatgacgcaagttgttctc-gtgctatgattcggactgttttcggtgacgctat-gg
--------ccctttgcaccca-tgtaccaaagcgcacaacgcttggaccacga
>Chaboissaea_decumbens 668 bp 
tcgtgaccctgaccaaaacagaccgtgaacatgtcatcgatgc-cactgat--tgacggg
-gcttgcacctgtctcttggtctggggcaaat---accttca-cttttgaagggaaagtg
ccc--caaaaagaacccacggcgccgtatggcgtcaaggaacacttg-tat---tgcttg
ccc-agggcca----cggtcggcttgccgaacggaa-ccctgtgcagtgat-gatatgct
a----atc-aacatgactctcggcaacggatatctcggctctcgcatcgatgaagaacgt
agcaaaatgcgatacctggtgtgaattgcagaatcccgtgaaccatcgagtttttgaacg
caagttgcgcccgaagccttctggttgagggcacgtctgcctgggcgtcacgccaaaaga
cactcccca------cccatccta--gt------ggggacgtggtttttggcc-cctcgt
gcc-ttt--ggcgcggtgagccaaagttggggctgctggcggtgccgatcacagcacaag
gtggatgacgcaagttgttctcggtgctatgatatgagccgcatatggcgatcctat-ag
--------ccctttggaccca-ttaatcgacacgcatgttgctcgaaccgcga
>Chaboissaea_ligulata 671 bp 
tcgtgaccctgaccaaaacagaccgtgaacatgttatccatgc-caccgat--tggcggg
-gcttgcacccrtctctcggcctgggacaaat---accttca-ttattgaggggaaaatg
ccc--caaaaagaacccacggcgccgtatggcgtcaaggatcacttg-tat---tgcttg
cca-aggccca----cggtcggcttgccgaacggaa-ccttgtgcagtgat-gatatgct
a----atc-aacatgactctcggcaacggatatctcggctctcgcatcgatgaagaacgt
agcaaaatgcgatacctggtgtgaattgcagaatcccgtgaaccatcgagtttttgaacg
caagttgcgcccgaagccttctggttgagggcacgtctgcctgggcgtcacgccaaaaga
cactcccca------cccatcata--gt------ggagacgtggtatttggcc-cctcgt
gcc-ttt--ggtgcggtgagcaaaagttggggctgccggcggtgccgatcacagcacaag
gtggatgacgcaagttgttctcggtgctatgatatgagccgcatacggcgatgctat-gg
--------ccctttggaccca-ttaatcgaagcgcgcgtcgctcgaaccgcga
>Distichlis_spicata 686 bp 
tcgtgaccctgaccaaaacagaccgtgaacgtgtcctccatgc-cgccggg--ttacagg
-tcyttcacctgtctctcggtacagggcgcca---accttc---ttyggargggaggggc
cct----aaaagaacccacggcgccgtatggcgtcaaggaacactgatatt---gcgtag
cac-ggggsca----cggtcggcttgccgggtgca--ccccgtgccgcgat-gatacatt
a----atc-cacatgactctcggcaacggatatctcggctctcgcatcgatgaagaacgt
agcaaaatgcgatacctggtgtgaattgcagaatcccgtgaaccatcgagtttttgaacg
caagttgcgcccgaggccttgyggtcgagggcacgtctgcctgggcgtcacgccaaaaga
cactccaca------cccgtcaag--gt------gcggatgtggtatctggcc-cctcgt
gcg-att---gtgcggtgggcctaagttggggctgccggcggtgccgaccacagcrcaag
gtggatgacgcaagttgttctcggcgctatgattcggaccgctttcggtgatgccac-gg
--------ccctctgtaccca-tcgaccgaagcgcacatcgctcggaccgcga
>Hilaria_cenchroides 686 bp 
tcgtgaccctgaccaaagcagaccgtgaatttgtcatccatgc-tgccgga--tgatggg
-tccwgtactcatcactcggcatacggacggttccawcctt--cttyggaagggaggtgt
ccg----aaaagaacccacggcgccggatggcgtcaaggaagacaatcatt---gctttg
tgc--ggtgcggatgtgtctggcatgccgggcactccctctgtgcggtgag-catgtttt
argagatt-cacacgactctcggcaacggatatctcggctcttgcatcgatgaagaacgt
agcaaaatgcgatacctggtgtgaattgcagaatcccgtgaaccatcaagtttttgaacg
caagttgcgcccgaggccatttggttgagggcacgtctgcctgggcgtcacgccaaaaga
cactcccca------tcaatcatg--tt------gtggatgtggtgtatggct-cctccc
acc----gcggcagggtgagctcaaagtygggctgtcggggctgccgatgacagcgcaag
gtggatgacgcaagttgttctatgtgctatgattcggctagctctcgacaatga----gg
atttggccctttttagaccca-tyatccaaagaacctgtatcttggaccacga
>Lycurus_phleoides 683 bp 
tcgtgaccctgaccaaaacagaccgtgaacatgtcatccatgc-caccggt--wgacggg
-gctcgcacccgtctctcggtctggggcamct---accttcattttttgatgggaaaktg
ccc--caaaaagaacccacggcgccgtatggcgtcaaggaacacttg-tat---tgcttg
ctc-ggggcta----cggtcggcttgccgaatggaa-ccccgtgcagtgat-gatatgct
a----atc-aacatgactctcggcaacggatatctcggctctcgcatcgatgaagaacgt
agcaaaatgcgatacctggtgtgaattgcagaatcccgtgaaccatcgagtttttgaacg
caagttgcgcccgaggccttctggttgagggcacgtctgcctgggcgtcacgccaaaaga
cactcccca------ccaatccta--gt------ggggacgtggtatttggcc-aatcgt
gcc-ttt--ggcrcggtgggcaaaagttggggctgccggcggtgccgatcacagcacaag
gtggatgacgcaagttgttctcggtgttatgatatgtaccgcaaacggcgatggtat-gg
--------ccctttggaccca-tcaatcgaagcgcgygtcgctcgaaccgcga
>Lycurus_setosus 686 bp 
tcgtgaccctgaccaaaacagaccgtgaacatgtcatccatgc-caccggt--wgacggg
-gctcgcacccgtctctcggtctggggcamct---accttcattttttgatgggaaaktg
ccc--caaaaagaacccacggcgccgtatggcgtcaaggaacacttg-tat---tgcttg
ctc-ggggcta----cggtcggcttgccgaatggaa-ccccgtgcagtgat-gatatgct
a----atc-aacatgactctcggcaacggatatctcggctctcgcatcgatgaagaacgt
agcaaaatgcgatacctggtgtgaattgcagaatcccgtgaaccatcgagtttttgaacg
caagttgcgcccgaggccttctggttgagggcacgtctgcctgggcgtcacgccaaaaga
cactcccca------ccaatccta--gt------ggggacgtggtatttggcc-aatcgt
gcc-ttt--ggcrcggtgggcaaaagttggggctgccggcggtgccgatcacagcacaag
gtggatgacgcaagttgttctcggtgttatgatatgtaccgcaaacggcratggtat-gg
--------ccctttggaccca-tcaatcgaagcgcgtytcgctcgaaccgcga
>Muhlenbergia_alamosae 695 bp 
tcgtgaccctkaccaaaacagaccgtgaacatgtcatccatgc-ygccgtc--tgacggg
-gcttgcacccgtctctcggtaaggggtacat---accttc--ttctagaagggaagtg-
ccc--caaaaagaacccacggcgcygtatggcgtcaaggaacactga-tat---tgcgtg
ttt-ggggcaa----tgttcggcmtgctggactag--ccccgggcagtgat-gatatgtt
a----atc-cacatgactctcggcaacggatatctcggctctcgcatcgatgaagaacgt
agcaaaatgcgatacctggtgtgaattgcagaatcccgtgaaccatcgagtttttgaacg
caagttgcgcccgaggccttctggttgagggcacgtctgcctgggcgtcacgccaaaaga
cactcccaa------ccaatctcg--gt------tgggacgtggtrtttggcc-cctcgt
gcc-ttttkggtgcggtgggcagaagttggggctgccggcggtgccgatcacagcacaag
gtggatggcgcaagttgttctcagtgctatgatacgaaccgcttayggcgttgctac-gg
--------cccttakgaccc-atggatcgaagcrcacatcgctcgaaccgcga
>Muhlenbergia_annua 668 bp 
tcgtgaccctgaccaaaacagaccgtgaacttgtcatccatgcc-gttggt--tgatggg
-gcttgcacccgtctcccagctaggggcacag---accttc--ttcgtgaagagaaatgc
ccc---aaaaagaacccacggcgccgtatggcgtcaaggatcactgaaaaa---tccttg
ctc-gggtgca----cgtctggcttgccggatgga--ccctgtgcagcgat-gctatgcg
a----aaatcacatgactctcggcaacggatatctcggctctcgcatcgatgaagaacgt
agcaaaatgcgatacctggtgtgaattgcagaatcccgtgaaccatcgagtttttgaacg
caagttgcgcccgaggcctttcggttgagggcacgtctgcctgggcgtcacgccaaaaga
cactcccca------ccaatctta--gt------gtggacgtggtatttggct-cctcgt
gcc-tttg-cgcgcggtgggcataagttggggctgccggcggtgccggtcacagcacaag
gtggatgacgcaagtttttctcggtgctatgatacggacccgtgatggcaattgtat-gg
--------cccgttcgaccca-atgaccgaagcgcatgccgctcggaccgcga
>Muhlenbergia_arenacea 674 bp 
tcgtgaccctgaccaaaacagaccgtgaacatgtcatccatgc-caccggt--tgacggg
-gcttgcacccgtctctcggtccggggcacat---accttca-ttttagaagggaaagtg
tcc--caaaaagaacccacggcgccgtatggcgtcaaggaacacttg-tat---tgcttg
ctcgggggcca----aggtcggcttgccgaacggaacccccgtgcagtgat-gatatgct
a----atc-aacatgactctcggcaacggatatctcggctctcgcatcgatgaagaacgt
agcaaaatgcgatacctggtgtgaattgcagaatcccgtgaaccatcgagtttttgaacg
caagttgcgcccgaggccttctggttgagggcacgtctgcctgggcgtcacgccaaaaga
cact-ccca------cacatccta--gt------ggggacgtggtatttggcc-cctcgt
gcc-tttg-tgcgcggtgggcaaaagttggggctgccggcggtgccgatcacagcacaag
gtggatgacgcaagttgttctcggtgytatgatacgagcygcatacggcgatgctat-gg
--------ccctttggaccca-tcaatcgaagcgcacgccgctcgaaccgcga
>Muhlenbergia_argentea 674 bp 
tcgtgaccctgaccaaaacagaccgtgaacatgtcatccatgct-gccggt--tgatggg
-gcttgcacccgtctcctagcacggggcatag---accttc--ctcgagaagagaaatgt
ccc---aaaaagaacccacggcgccgtatggcgtcaaggaacactgataaa---tctttg
ctc-gggggca----cgtctggcttgccggatgaa--ccccgcgcagcgat-gctatgcg
a----ata-tagatgactctcggcaacggatatctcggctctygcatcgatgaagaacgt
agcaaaatgcgatacctggtgtgaattgcagaatcccgtgaaccatcgagtttttgaacg
caagttgcgcccgaggccttttggtcgagggcacgtctgcctgggcgtcacgccaaaaga
cactccgca------ccaatccgg--tt------gtggacgtggtatttggcc-ccycgt
gca-tttg-tgcgcggtgggcagaagttggggctgccggcggtgccgatcacagcgcatg
gtggatgacacaagttgttctcggtgctatgatacgaactgctcacggcaattcaac-gc
--------tcctttggatcca-ttgaccgaagcgcacactgctcggaccgcga
>Muhlenbergia_arsenei 668 bp 
tcgtgaccctgaccaaaacagaccgtgaacatgtcatccatgc-cgccgtc--tgacggg
-gcttgcacccgtctctcggtctggggcacatttcttcttc--ttctagaagggaagcg-
ccc--caaaaagaacccacggcgccgtatggcgtcaaggaacactga-tat---tgcttg
ttt-ggggcca----cgttcggcttgccggactaa--cctcaggcagtgat-gatatgct
a----atc-cacatgactctcggcaacggatatctcggctctcgcatcgatgaagaacgt
agcaaaatgcgatacctggtgtgaattgcagaatcccgtgaaccatcgagtttttgaacg
caagttgcgcccgaggccttctggttgagggcacgtctgcctgggcgtcacgccaaaaga
cactcccca------cccatctcg--gt------tgggacgtggtatttggcc-cctcgt
gcc-tttg-ggcacggtgggcagaagttggggctgccggcggtgccgatcacagcacaag
gtggatggcgcaagttattctcggtgctgtgatacgaaccgcttacggcgatg-cac-ag
--------ccctttggaccc-atggatcgaagcgcatgtcgctcggaccgcga
>Muhlenbergia_brevis 668 bp 
tcgtgtccctgaccaaaacagaccgtgaatatgtcatccatgccagctggt--tgatggg
-gcttgcacccgtctcccagctcggggcacag---accttc--ttcttgaagagaaatgc
ccc---aaaaagaacccacggcgccgtatggcgtcaaggaacacagaaaaa---tccttg
ttc-gggtgca----cgtccggcttgccggatgga--ccccgtgcagtgat-gctatgcg
a----aaa-cacatgactctcggcaacggatatctcggctctcgcatcgatgaagaacgt
agcaaaatgcgatacctggtgtgaattgcagaatcccgtgaaccatcgagtttttgaacg
caagttgcgcccgaggccttttggttgagggcacgtctgcctgggcgtcacgccaaaaga
cactcccca------ccaatctta--gt------gtggatgtggtatttggct-cctcgt
accttttg-ggtgcggtgggcagaagttggggctgccggcggtgccgatcacagcacaag
gtggatgacgcaagttgttctcggtgctatgatacggactgcttatggcaattgcat-gg
--------ccctttgaaccca-atcaccgaagcgcatgccgctcggaccgcga
>Muhlenbergia_brevivaginata 677 bp 
tcgtgaccctgaccaaaayagaccgtgaacatgtcatcgaatc-cgccggt--tgacggg
tatttttacccgtctctcggtatggggcacgt---accttc--ttcatagaagcgaaggg
ccc--caaaaagaacccacggcgccgtatggcgtcaaggaaaactgg-tat---tgcttg
ctc-agggcaa----tgaacggcttgccgaacggaa-ccctgagcagcgat-gatattgt
a----tca--acatgactctcggcaacggatatctcggctctcgcatcgatgaagaacgt
agcaaaatgcgatacctggtgtgaattgcagaatcccgtgaaccatcgagtttttgaacg
caagttgcgcccgaggccttttggycgagggcacgtctgcctgggcgtcacgccaaaaga
cactcccca------cacatccta--gt------ggggacgtggtatttggcc-actcgt
gcc-tttg-cgcgcggtgggctaaagttggggctgccggcggtgccgatcacagcacaag
gtggatgacgcaagttgttctcggtgctacgatacgagccgcatacggtgatgttat-gg
--------ccctctggaccca-ttgatcgaagygcttgtcgctcgaaccgcga
>Muhlenbergia_capillipes 668 bp 
tcgtgaccctgaccaaaacagaccgtgaacatgtcatccatgcc-gctggt--tgatagg
-tcttgcacctgtctcctagcatggagcacgt---accttc--t---agaagggaaatgc
ccc----aaaagaacccacggcgccgtatggcgtcaaggaaaactga-aaa---tccttg
ctc-gggtgca----tgtccggcttgccggacgat--gcccttgcagcgat-gctatgcg
a----aaa-cacacgactctcggcaacggatatctcggctctcgcatcgatgaagaacgt
agcaaaatgcgatacctggtgtgaattgcagaatcccgtgaaccatcgagtttttgaacg
caagttgcgcccgaggccttttggttgagggcacgtctgcctgggcgtcacgctaaaagt
cactcccca------ccatccttg--gt------gaggatgtggtatttggct-cctcgt
gcc-tttg-tgcgcggtgggcagaagttggggctgccggcggtgccgatcacagcacaag
gtggatgacggaagttattctaggtgctacgatacgaaccgtacacggcaattgtat-gg
--------cccttttgaccca-acgaccgaagcgcacgttgctcggaccgcga
>Muhlenbergia_ciliata 668 bp 
tcgtgaccctgaccaaaacagaccgtgaacacgtcatccatgc-cgccgtc--tgatagg
-tcttgcacctatctatcggtacggggtacat---accttt--gtcttgaagggaagtg-
ccc--caaaaagaacccacggcgccgtatggcgtcaaggaaaactta-tat---tgcttc
ttt-ggggcca----tgttcggcttgccggacaaa--ccccgagcagcgat-gctatgga
a----atc-ca-atgactctcggcaacggatatctcggctctcgcatcgatgaagaacgt
agcaaaatgcgatacctggtgtgaattgcagaatcccgtgaaccatcgagtttttgaacg
caagttgcgcccgaggccttctggttgagggcacgtctgcctgggcgtcacgcaaaaaga
cactcccta------tccatcttg--gt------tgggacgtggcatttggcc-tctcgt
gcc-ttcg-ggtgcggtgggcagaagttggggctgccggcggtgccgatcacagcacaag
gtggatggcgcaagttgttctcggtgctatgatacgaaccgcttatggcaatgcaaa-gg
--------ccctttggaccc-atggatcgaagcgcacagcgctcggaccgcga
>Muhlenbergia_curtifolia 668 bp 
tcgtgaccctgaccaaaacagaccgtgaacatgtcatccatgc-cgccgtt--tgatggg
-gcttgcacccatctctcggtatggggcacgt---accttc--ttctagaagggaagtg-
ccc--caaaaagaacccacggcgccgtatggcgtcaaggaaaactga-tat---tgcttg
ttt-ggggcca----cgttcggcttgccggactaa--ccccgggcagtgat-gatatgct
a----atc-cacatgactctcggcaacggatatctcggctctcgcatcgatgaagaacgt
agcaaaatgcgatacctggtgtgaattgcagaatcccgtgaaccatcgagtttttgaacg
caagttgcgcccgaggccttctggttgagggcacgtctgcctaggcgtcacgccaaaaga
cactcccca------cccatctcg--gt------tgggacgtggtatttggcc-cctcgt
gcc-tttc-agcgcggtgggcagaagttggggctgccggcagtgccgatcacagcacaag
gtggatgacgcaagttgttctcggtgctatgatacgaactgcttacggcgatgctac-gg
--------cccatcggaccc-atggatcgaagcgcacatcgctcggaccgcga
>Muhlenbergia_diversiglumis 668 bp 
tcgtgaccctgaccaaaatagactgcgaacatgtcatccatgc-tgccgtt--tggtggg
-tctggcacccatctctcggtatgggttgcat---aacttc--ttctagaagggaagca-
tcc--caaaaagaacccacggcgccgtatggcgccaaggaaaactga-tat---tgcttg
ttt-ggggcca----tgttcggcttgccggactaa--ccctgggcagtgat-gatatgct
a----atc-cacatgactctcggcaacggatatctcggctctcgcatcgatgaagaacgt
agcgaaatgcgatacctggtgtgaattgcagaatcccgtgaaccatcgagtttttgaacg
caagttgcgcccgaagccttctggttgagggcacgtctgcctgggcgtcacgccaaaaga
cactcccca------cc-atctcg--gt------tgggacgtggtatttggcc-cctcgt
gcc-tttc-ggcacggtgggcagaagttggggctgccggcagtgccgatcacagcacaag
gtggatgacgcaagttgttctcggtgctatgatacgagctgcttacggcgatgctac-ag
--------ccctttggaccc-atggttgtaagcgaacatcgcttggaccgcga
>Muhlenbergia_dumosa 668 bp 
tcgtgaccctgaccaaaacagaccgtgaacatgtcatccatgctcgccgtt--tgacggg
-gcttgcacccgtctctcggcccggggcacat---accttc--ttttagaagggaaggg-
ccc--caaaaagaacccacggcgccgtatggcgtcaaggaacactga-tat---tgcttg
ctt-ggggcca----cgttcggcttgccggatgaa--ccccgggcagtgat-gatatgct
a----atc-cacatgactctcggcaacggatatctcggctctcgcatcgatgaagaacgt
agcaaaatgcgatacctggtgtgaattgcagaatcccgtgaaccatcgagtttttgaacg
caagttgcgcccgaggccttctggttgagggcacgtctgcctgggcgtcacgccaaaaga
cactcccca------cccatcttg--gt------agggacgtggtatttggtc-ccccgt
gcc-tttt-ggcgcggtgggcaaaagttggggctgccggcggtgccgatcacagcacaag
gtggatgacgcaagttgttctcggtgctacgatacgaactgcttacggcgatgctac-gg
--------ccctttggaccc-attgatcgaagcgcatgtcgctcggaccgcga
>Muhlenbergia_eludens 671 bp 
tcgtgaccctgaccaaaacagaccgtgaacatgtcatccatgcc-gctggw--cgatggg
-gcttgcacccgtctcccagcttggggcacgg---accttc--ttccggaagagaaatgc
ccc--aaaaaagaacccacggcgctgtatggcgtcaaggaacactaagaaa---tctttg
ctc-gggtgca----cgtctggcttgccggatgga--cctcgtgcagcgat-gatatgca
a----aaa-cacatgactctcggcaacggatatctcggctctcgcatcgatgaagaacgt
agcaaaatgcgatacctggtgtgaattgcagaatcccgtgaaccatcgagtttttgaacg
caagttgcgcccgagaccttttggttgagggcacgtctgcctgggcgtcacgccaaaaga
cactccaca------ccaaccttg--gt------gtggacgtggtatttggct-catcgt
gcc-cttg-tgcgcggtgggcagaagttggggctgccggcggtgccgatcacagcacaag
gtggatgacgcaagttgttctcggtgctaggatacggacccctgatggcaattgcac-gg
--------ccctatggaccca-tggaccggagtgcccgtcgctcggaccgcga
>Muhlenbergia_emersleyi 668 bp 
tcgtgaccctgaccaaaacagaccgtgaacatgtcatccatgcc-gccgga--tgacggg
-tcttgcacccgtctctcggcacggggcactt---accttc--ttctagaagggaagggc
ccc---aaaaagaacccacggcgccgtatggcgtcaaggaacactgataaa---tccttg
ctc-ggggctt----tggtcggcttgccggtcgaa--ccccttgcagcgat-gatatgcg
a----atc-cacatgactctcggcaacggatatctcggctctcgcatcgatgaagaacgt
agcaaaatgcgatacctggtgtgaattgcagaatcccgtgaaccatcgagtttttgaacg
caagttgcgcccgaggccttctggtcgagggcacgtctgcctgggcgtcacgccaaaaga
cactcccct------ccaatcccg--gt------gtggacgtggtatttggcc-cctcgt
gcc-ttag-cgtgcggtgggcagaagtttgggctgccggcggtgccgatcacagcacaag
gtggatgacgcaagttgttctcggtgctacgatacgaaccgcttacggcaatgctat-gg
--------ccctttggaccct-tcgaccgaagcgcatgccgctcggaccgcga
>Muhlenbergia_expansa 683 bp 
tcgtgaccctgaccaaaacagaccgtgaacatgtcatccatgcc-gccgga--agayggg
-tcytgcacccgtctctcggcacggggcacyt---accttc--tyctagaaggaaagggc
ccc---aaaaagaacccacggcgccgtatggcgtcaaggaacactgataaa---tccttg
ctc-ggggctt----yggtcggcttgccggtcgaa--ccccttgcagcgat-gatatgcg
a----atc-cacatgactctcggcaacggatatctcggctctcgcatcgatgaagaacgt
agcaaaatgcgatacctggtgtgaattgcagaatcccgtgaaccatcgagtttttgaacg
caagttgcgcccgaggccttctggtcgagggcacgtctgcctgggcgtcacgccaaaaga
cactcccca------ccaatcccg--gt------gtggacgtggtatttggcc-cctcgt
gcc-ttag-cgtgcggtgggcagaagtttgggctgccggcggtgccgatcacagcacaag
gtggatgacgcaagttgttctcggtgctacgatacgaaccgcttacggcaatgctat-gg
--------ccctttggaccct-tcgaccgaagcgcatgccgctcggaccgcga
>Muhlenbergia_flavida 668 bp 
tcgtgaccctgaccaaaacagattgtgaacatgtcatcgatgc-cgctggttgtgatggg
-gcttgcacctgtctcctagcacggggcacag---accttcctctcgaggagagaaatgc
cct--aaaaaagaacccacggcgccgtatggcgtcaaggaacactgataatcaatctttg
ctc-gagggac----tgtctggcttgccaggcgaa--ccccgtgcagcgat-gctatgcg
a----ata-cacatgactctcggcaacggatatcttggctctcacatcgatgaagaacgt
agcaaaatgcgatacctggtgtgaattgcagaatcccgtgaaccatcgagtttttgaacg
caagttgcgcccgaggccttttggttgagggcacgtctgcctgggcgtcacgccaaaaga
cactcccc-------ctaattcgg--gt------gtggatgtggta-ttggcc-cctcgt
gca-tttg-tgcgtggtgggcagaagttggggctgccggcagtgccgatcacagcacgtg
gtggatgacacaagttgttctcggtgctatgatatgagctgctcacggcaattcaac-gc
--------tcctttggaccca-ttgaacgaattgcaagctgctcggaccacga
>Muhlenbergia_flaviseta 671 bp 
tcgtgaccctgaccaaaacagaccgtgaacaagtcatccatgc-tgccaat--tgacagg
-gctcgcacctgtccattggtctcgggcacgt---accttc--tttttagaaggtaacgg
ccc--caaaaagaacccacggcgccgtatggcgtcaaggaaaactga-tat---tgcttg
cat-ggggcca----cgattggcttgctgaactgaa-ccccgtgcagcgat-gatatgct
a----atc-cacatgactctcggcaacggatatctcggctctcgcatcgatgaagaacgt
agcaaaatgcgatacctggtgtgaattgcagaatcccgtgaaccatcgagtttttgaacg
caagttgcgcccgaggccttttggttgagggcacgtctgcctgggcgtcacgctaaaaga
cactctcca------cctatctta--gt------ggggacgtggtatttggcc-cmtcgt
gcc-tttg-cgtgcgatgggcagaagttggggctgccggcggtgccgatcacagcacaag
gtggatgacgtaagttgttctcggtgctacgatacgaactgcgtatggcaaagatat-gg
--------ccctttggaccca-tcgatcgaggcgcgtgtcgctcgtaccgcga
>Muhlenbergia_fragilis 668 bp 
tcgtgaccctgaccaaaacagaccgcgaacatgtcatccatgcc-gctggg--tgatggg
-gcttgcacctgtctcctagcatggggcacag---accttc--c---agaagagaaatgc
ccc---aaaaagaacacacggcgccgtatggcgtcaaggaaaactgg-aat---tccttg
ctc-gggtgca----cgtctggcttgctggatgga--ccccgtgcagcgat-gatatgcg
a----aaa-cacatgactctcggcaacggatatctcggctctcgcatcgatgaagaacgt
agcaaaatgcgatacctggtgtgaattgcagaatcccgtgaaccatcgagtttttgaacg
caagttgcgcctgaggccttttggttgagggcacgtctgcctgggcgtcacgctaaaaga
cactcctca------ccaacctcg--gt------gtggatgtggtatttggct-cctcgt
gcc-cttg-tgtgcggtgggcagaagttggggctgctggcggtgcagatcacagcacaag
gtggatgacgcaagttattctcggtgctatgatatgaaccttactcggcaattgcac-gg
--------ccctttggaccca-atgatcgaagcgcacgacgctcggaccgcga
>Muhlenbergia_gigantea 671 bp 
tcgtgaccctgaccaaaacagaccgtgaacatgtcatccatgcc-gccgga--tgacggg
-tcttgcacccgtctctcggcacggggcactt---accttc--ttctagaagggaagggc
ccc---aaaaagaacccacggcgccgtatggcgtcaaggaacactgataaa---tccttg
ctc-ggggctt----tggtcggcttgccggtcgaa--ccccttgcagcgat-gatatgcg
a----atc-cacatgactctcggcaacggatatctcggctctcgcatcgatgaagaacgt
agcaaaatgcgatacctggtgtgaattgcagaatcccgtgaaccatcgagtttttgaacg
caagttgcgcccgaggccttctggtcgagggcacgtctgcctgggcgtcacgccaaaaga
cactcccca------ccaatcccg--gt------gtggacgtggtatttggcc-cctcgt
gcs-ttag-cgtgcggtgggcagaagtttgggctgccggcggtgccgatcacagcacaag
gtggatgacgcaagttgttctcggtgctacgatacgaaccgcttacggcaatgctat-gg
--------ccctttggaccct-tcgaccgaagcgcatgccgctcggaccgcga
>Muhlenbergia_himalayensis 668 bp 
tcgtgaccctgaccaaaacagaccgtgaacatgtcatccatgc-cgccgtt--tgatggg
-gcttgcacccgtctctcggtatggggcacat---accttc--ttctagaagggaagtg-
gcc--caaaaagaacccacggcgccgtatggcgtcaaggaaaactga-tat---tgcttg
ttt-cgggcca----cgtccggcttgccggactaa--ccccgggcagtgat-gatatgct
a----atc-cacatgactctcggcaacggatatctcggctctcgcatcgatgaagaacgt
agcaaaatgcgatacctggtgtgaattgcagaatcccgtgaaccatcgagtttttgaacg
caagttgcgcccgaggccttctggttgagggcacgtctgcctgggcgtcacgccaaaaga
cactcccca------cccatctcg--gt------tgggacgtggtatttggcc-cctcgt
gcc-tttc-ggcgcggtgggcagaagttggggctgccggcagtgccgatcacagcacaag
gtggatgacgcaagttgttctcggtgctatgatacgaactgcttacggcgatgctat-gg
--------cccattggaccc-atggatcgaagcgcacatcgctcggaccgcga
>Muhlenbergia_jonesii 668 bp 
tcgtgaccctgaccaaaacagaccgtgaacatgtcatccatgc-tgccaat--tgatggg
-cctcgcacccgtcaattggtctggggcacgt---a-cttc--tttttagaagggaacga
ccc--ctacaagaacccacggcgccgtatggcgtcaaggaatactga-tat---tgcttg
ctc-ggggcaa----cgatcggcttgctgaacgaaa-ccctgtgcagtgat-gatttgct
a----att-cacatgactctcggcaacggatatctcggctctcgcatcgatgaagaacgt
agcaaaatgcgatacctggtgtgaattgcagaatcccgtgaaccatcgagtttttgaacg
caagttgcgcccgagaccttctggtcaagggcacgtctgcctgggcgtcacgccaaaaga
cactcccca------ccagtatta--gt------ggggacgtggtatttggtc-cttcgt
gcc-tttg-cgcgcggtgggcaaaagttggggctgccggcggtgccgatcacagcacaag
gtggatgacgcaagttgttctcggtgctatgatacgaaccgcatacggcaatgctat-gg
--------ccctttggaccca-tcaatcgaagcgcgcgtcgctcgtaccgcga
>Muhlenbergia_lehmanniana 668 bp 
tcgtgaccctgaccaaaacagaccgtgaacatgtcatccatgcc-gccgga--tgacggg
-tcttgcacccgtctctcggcacggggcactt---accttc--ttctagaagggaagggc
ccc---aaaaagaacccacggcgccgtatggcgtcaaggaacactgataaa---tccttg
ctc-ggggctt----tggtcggcttgccggtcaaa--ccccttgcagcgat-gatatgcg
a----atc-cacatgactctcggcaacggatatctcggctctcgcatcgatgaagaacgt
agcaaaatgcgatacctggtgtgaattgcagaatcccgtgaaccatcgagtttttgaacg
caagttgcgcccgaggccttctggtcgagggcacgtctgcctgggcgtcacgccaaaaga
cactcccca------ccaatcccg--gt------gtggacgtggtatttggcc-cctcgt
gcc-ttag-cgtgcggtgggcagaagtttgggctgccggcggtgccgatcacagcacaag
gtggatgacgcaagttgttctcggtgctacgatacgaaccgcttacggcaatgctat-gg
--------ccctttggaccct-tcgaccgaagcgcatgccgctcggaccgcga
>Muhlenbergia_ligularis 668 bp 
tcgtgaccctgaccaaaacagaccgtgaacatgtcatccatgcc-gccggt--tgatggg
-gcttgcacccatctcccagcacggggcacgg---accttc--ttctagaagagaaatgc
ccc---aaaaagaacccacggcgccgtatggcgtcaaggaacactgataaa---tccttg
ctc-gggggca----cgtccggcttgccgaacgaa--ccccgtgcagcgat-gctatgca
a----ata-cacatgactctcggcaacggatatctcggctctcgcatcgatgaagaacgt
agcaaaatgcgatacctggtgtgaattgcagaatcccgtgaaccatcgagtttttgaacg
caagttgcgcccgaggccttttggtcgagggcacgtctgcctgggcgtcacgccaaaaga
cactcccca------ccaatcccg--gt------gcggacgtggtatttggcc-cctcgt
gcc-tttg-tgcgtggtgggcacaagttggggctgccggcagtgccgatcacagcacaag
gtggatgacgcaagttgttctcggtgctatgatacgaactgcttacggcaattatat-gg
--------ccctttggaccca-ttgaccgaagcgcacaccgctcggaccgcga
>Muhlenbergia_lucida 677 bp 
tcgtgaccctgaccaaaacagaccgtgaacatgtcatccatgcc-gccgga--tgacggg
-tcttgcacccgtctctcggcacggggcactt---accttc--ttctagaagggaagggc
ccc---aaaaagaacccacggcgccgtatggcgtcaaggaacactgataar---tccttg
ctc-ggggctt----tggtcggcttgccggtcgaa--ccccttgcagcgat-gatatgcg
a----atc-cacatgactctcggcaacggatatctcggctctcgcatcgatgaagaacgt
agcaaaatgcgatacctggtgtgaattgcagaatcccgtgaaccatcgagtttttgaacg
caagttgcgcccgaggccttctggtcgagggcacgtctgcctgggcgtcacgccaaaaga
cactccccw------ccaatcccg--gt------gtggacgtggtatttggcc-cctcgt
gcc-ttag-cgtgcggtgggcagaagtttgggctgccggcggtgccgatcacagcacaag
gtggatgacgcaagttgttctcggtgctacgatacgaaccgcttacggcaatgctat-gg
--------ccctttggaccct-tsgaccgaagcgcatgccgctcggaccgcga
>Muhlenbergia_microsperma 671 bp 
tcgtgaccctgaccaaaacagaccgtgaacatgtcatccatgcttcccgtt--tgacggg
-gcttgcacccgtctctcggtccggagcactt---accttc--ttatagaagggaaggg-
ccc--caaaaagaacccacggcgccgtatggcgtcaaggaacactaa-tat---ttcttg
ctt-ggggccg----cgttcggcttgccggatgaa--ccccgggcagtgat-gatatgct
a----atc-cacatgactctcggcaacggatatctcggctctcgcatcgatgaagaacgt
agcaaaatgcgatacctggtgtgaattgcagaatcccgtgaaccatcgagtttttgaacg
caagttgcgcccgaggccttctggttgagggcaygtctgcctgggcgtcacgcaaaaaga
cactcccca------cccatcttg--gt------ggagacgtggtatttggctaccccgt
gcc-ataa-ggcacggtgggcaaaagtttgggctgccggcggtgccgatcacagcacaag
gtggatgacgcaagttattctcggtgctacgatacgaaccgcttacggcgatgctat-gc
--------ccctttggaccc-attgatcgaagcgcccgtcgctcggaccgcga
>Muhlenbergia_minutissima 668 bp 
tcgtgaccctgaccaaaacagaccgtgaacatgtcatccatgcc-gctggt--agatggg
-gcttgcacccgtctcccagcttggggcacgg---accttc--ttccggaagagaaatgc
ccc--aaaaaagaacccacggcgctgtatggcgtcaaggaacactaagaaa---tctttg
ctc-gggtgca----cgtctggcttgccggatgga--cctcgtgcagcgat-gatatgca
a----aaa-cacatgactctcggcaacggatatctcggctctcgcatcgatgaagaacgt
agcaaaatgcgatacctggtgtgaattgcagaatcccgtgaaccatcgagtttttgaacg
caagttgcgcccgagaccttttggttgagggcacgtctgcctgggcgtcacgccaaaaga
cactccaca------ccaaccttg--gt------gtggacgtggtatttggct-catcgt
gcc-cttg-tgcgcggtgggcagaagttggggctgccggcggtgccgatcacagcacaag
gtggatgacgcaagttgttctcggtgctaggatacggacccctgatggcaatcgcac-gg
--------ccctatggaccca-tggaccggagtgcccgtcgctcggaccgcga
>Muhlenbergia_monandra 668 bp 
tcgtgaccctgaccaaaacagaccgtgaacatgtcatccattc-caccgat--tgacggg
-gcttgcacccgtctctcggactggggcaaat---accttca-ttcttgaagggaaagtg
ccc--caaaaagaacccacggcgccgtatggcgtcaaggaacacttg-tat---tgcttg
ccc-ggggcct----cggtcggcttgccgaactgaa-ccccgtgcagtgat-gatatact
a----atc-aacatgactctcggcaacggatatctcggctctcgcatcgatgaagaacgt
agcaaaatgcgatacctggtgtgaattgcagaatcccgtgaaccatcgagtttttgaacg
caagttgcgcccgaggccttctggttgagggcacgtctgcctgggcgtcacgtcaaaaga
cactcccca------cccatccta--gt------ggggatgtggtatttggcc-cctcgt
gcc-ttt--ggcgcggtgggcaaaagttggggctgccggcggtgccgatcacagcacaag
gtggatgacgcaagttgttctcggtgctaggatacgagccgcatacggcgatgctat-gg
--------ccctttggaccca-tcaatcgaagcgcgcgtcgctcgaaccgcga
>Muhlenbergia_montana 668 bp 
tcgtgaccctgaccaaaacagaccgtgaacatgtcatccatgc-tgccaat--tgacggg
-cctcgcacccgtcaattggtctggggcacgt---a-cttc--ttcttagaagggaacga
ccc--ctacaagaacccacggcgccgtatggcgtcaaggaatactga-tat---tgcttg
ctc-ggggcaa----cgatcggcttgccgaacgaaa-ccctgtgcagtgat-gatttgct
a----att-cacatgactctcggcaacggatatctcggctctcgcatcgatgaagaacgt
agcaaaatgcgatacctggtgtgaattgcagaatcccgtgaaccatcgagtttttgaacg
caagttgcgcccgagaccttctggtcaagggcacgtctgcctgggcgtcacgccaaaaga
cactcccca------ccagtatta--gt------ggggacgtggtatttggtc-cttcgt
gcc-tttg-cgcgcggtgggcaaaagttggggctgccggcggtgccgatcacagcacaag
gtggatgacgcaagttgttctcggtgctatgatacgaaccgcatacggcaatgctat-gg
--------ccctttggaccca-tcaatcgaagcgcgcgtcgctcgtaccgcga
>Muhlenbergia_nigra 671 bp 
tcgtgaccctgaccaaaacagaccgtgaacatgtcatccatgcc-gccggt--tgacggg
-tcttgcacccgtctctcggcacggggcactt---accttc--ttctagargggaagggc
ccc---aaaaagaacccacggcgccgtatggcgtcaaggaacactgataaa---tccttg
ctc-ggggctt----tggtcggcttgccggtcgaa--ccccttgcagcgat-gatatgcg
a----atc-cacatgactctcggcaacggatatctcggctctcgcatcgatgaagaacgt
agcaaaatgcgatacctggtgtgaattgcagaatcccgtgaaccatcgagtttttgaacg
caagttgcgcccgaggccttctggtcgagggcacgtctgcctgggcgtcacgccaaaaga
cactcccca------ccaatcccg--gt------gtggacgtggtatttggcc-cctcgt
gcc-ttag-cgtgcggtgggcagaagtttgggctgccggcggtgccgatcacagcacaag
gtggatgacgcaagttgttctcggtgctacgatacgaaccgcttacggcaatgctat-gg
--------ccctttggaccct-tcgaccgaagcgcatgccgctcggaccgcga
>Muhlenbergia_pauciflora 668 bp 
tcgtgaccctgaccaaaacagaccgtgaacatgtccctcatgc-tgccgtc--tgacggg
-gcttgcacccgtctctcggtctggggcaaat---accttc--ttctagaagggaatgg-
ccc--caaaaagaacccacggcgctgtatggcgtcaaggaacactga-tat---tgcttg
ttt-ggggcca----tgtccggcttgccggatgta--cctcgggcagtgat-gatatgct
a----atc-cacatgactctcggcaacggatatctcggctctcgcatcgatgaagaacgt
agcaaaatgcgatacctggtgtgaattgcagaatcccgtgaaccatcgagtttttgaacg
caagttgcgcccgaggccttctggttgagggcacgtctgcctgggcgtcacgccaaaaga
cactcccca------cccatcttg--gt------tgggatgtggtatttggcc-cctcgt
tcc-tttg-ggcgcggtggacagaagttggggctgccggcggtgccgatcacagcacaag
gtggatggcgcaagttgttctcggtgctacgatacgaaccgcttacggcgatgctac-ag
--------ccctttggacccaattgatcgatgcgaacatcgctcggaccgcga
>Muhlenbergia_peruviana 668 bp 
tcgtgaccctgaccaaaacagaccgtgaacatgtcatccatgc-tgccaat--tgacggg
-ccttgtacctgtcaattggt-tggggcacgt---a-cttc--ttttaagaatggaacga
ccc--ctacaagaacccacggcgccgtatggcgtcaaggaaaactga-tat---tgcttg
cac-agggcaa----cgatcggcttgctgaacggaa-ccctgtgcagtgat-gatttgct
a----act-cacatgactctcggcaacggatatctcggctctcgcatcgatgaagaacgt
agcaaaatgcgatacctggtgtgaattgcagaatcccgtgaaccatcgagtttttgaacg
caagttgcgcccgagaccttctggttgagggcacgtctgcctgggcgtcacgccaaaaga
cactcccca------caattctgt--gt------ggggatgtggtatttggtc-cctcgt
gcc-tttg-agcgcggtgggcaaaagttggggctgccggcggtgccgatcacagcacatg
gtggatgacgcatgttgttctcggtgctatgatacgaaccgcatacggcaatgatat-gg
--------cccattggaccca-tcgatcgaagcg---------cgaaccgcga
>Muhlenbergia_polycaulis 674 bp 
tcgtgaccctgaccaaaacagaccgtgaacatgtcatccatgc-cgccgtt--tgatggg
-gcttgcacccgtctctcggtatggggcacat---accttc--ttctagaagggaagtg-
ccc--caaaaagaacccacggcgccgtatggcgtcaaggaaaactga-tat---tgcttg
ttt-ggggcca----ygttcggcttgccggactaa--ccccgggcagtgat-gatatgct
a----atc-cacatgactctcggcaacggatatctcggctctcgcatcgatgaagaacgt
agcaaaatgcgatacctggtgtgaattgcagaatcccgtgaaccatcgagtttttgaacg
caagttgcgcccgaggccttctggttgagggcacgtctgcctgggcgtcacgccaaaaga
cactcccca------cccacctcg--gt------tgggacgtggtatttggcc-cctcgt
gcc-tttc-ggcgcggtgggcagaagttggggctgccggcagtgccgatcacagcacaag
gtggatgacgcaagttgttctcggtgctatgatacgaactgcttacggcgatgctac-gg
--------cccattggaccc-ayggatcgaagcgcacatcgctcggaccgcga
>Muhlenbergia_porteri 677 bp 
tcgtgaccctgaccaaaacagaccgtgaacatgtcatccatgcttgccgtt--tgacggg
-gcttgcacccgtctctcggtccggggcackt---accttc--ttstagaagggaaggg-
ccc--caaaaagaacccacggcgccgtatggcgtcaaggaacactga-tat---tgcttg
ctt-ggggcca----cgttcggcttgccggatgaa--ccccgggcagtgat-gatatgct
a----atc-cacatgactctcggcaacggatatctcggctctcgcatcgatgaagaacgt
agcaaaatgcgatacctggtgtgaattgcagaatcccgtgaaccatcgagtttttgaacg
caagttgcgcccgaggccttctggttgagggcacgtctgcctgggcgtcacgccaaaaga
cactcccca------ccaatcttg--gt------ggagacgtggtatttggct-ccccgt
gcc-ttat-ggcgcggtgggcaaaagtttgggctgccggcggtgccgatcacagcacaag
gtggatgacgcgagttgttctcggtgctgcgataccaactgcttacggcgatgctat-rg
--------ccctttggaccc-agtgatcgaagcgcacgtcgctcggaccgcga
>Muhlenbergia_pungens 671 bp 
tcgtgaccctgaccaaaacagaccgtgaacatgtcatccatgc-cgccggt--tgatggg
-gcttgcacccgtctctcggtatggggcacaa---accttct-ttttagaa-ggaaatgg
ccc--caaaaagaacccacggcgccgtatggcgtcaaggaacacttg-tat---tgcttg
ctc-ggggata----cgatcggctcgccgaacggaa-ccccgtgcagtgat-gatatgct
a----atc-aacatgactctcggcaacggatatctcggctctcgcatcgatgaagaacgt
agcaaaatgcgatacctggtgtgaattgcagaatcccgtgaaccatcgagtttttgaacg
caagttgcgcccgaggccttctggttgagggcacgtctgcctgggcgtcacgccaaaaga
cactcccca------cccatccta--gt------ggggacgtggtatttggcc-ccccgt
gcc-tttg-cgcgcggtgggcaaaagttggggctgccggcggtgccgatcacagcacaag
gtggatgacgcaagttgttctcgrtgctacgatacgagccgcatacggcgatgctat-gg
--------ccctttggaccca-tcgatcgaagcacgcgtcgctcgaaccgcga
>Muhlenbergia_ramosa 668 bp 
tcgtgaccctgaccaaaacagaccgtgaacatgtcatccatgc-cgccgtt--tgatggg
-gcttgcacctgtctctcggtatggggcacgt---accttc--ttctagaagggaagtg-
ccc--caaaaagaacccacggcgccgtatggcgtcaaggaaaactga-tat---tgcttg
ttt-cgggcca----cgtccggcttgccggacgaa--ccccgggcagtgat-gatatgct
a----atc-cacatgactctcggcaacggatatctcggctctcgcatcgatgaagaacgt
agcaaaatgcgatacctggtgtgaattgcagaatcccgtgaaccatcgagtttttgaacg
caagttgcgcccgaggccttctggttgagggcacgtctgcctgggcgtcacgccaaaaga
cactcccca------cccatctcg--gt------tgggacgtggtatttggcc-cctcgt
gcc-tttc-ggcgcggtgggcagaagttggggctgccggcagtgccgatcacagcacaag
gtggatgacgcaagttgttctcggtgctatgatacgaactgcttacggcgatgctac-gg
--------cccattggaccc-atggatcgaagcgcacatcgctcggaccgcga
>Muhlenbergia_ramulosa 668 bp 
tcgtgaccctgaccaaaacagaccgtgaacatgtcatccatgc-cgccgtt--tgatggg
-gcttgcacctgtctctcggtttgggacctgg---aacttc-----atgaagggaagggt
cccaaaaaaaagaacccacggcgccttatggcgtcaaggaaaacttaaatt---gccttg
ctc-ggggctt----cgaccggcgtgccggatgaa--ccccgtgcagcgat-gatatgct
a----atc-aacatgactctcggcaacggatatctcggctctcgcatcgatgaagaacgt
agcaaaatgcgatacctggtgtgaattgcagaatcccgtgaaccatcgagtttttgaacg
caagttgcgcccgagaccttctggtcgagggcacgtctgcctgggcgtcacgccaaaaga
cactcccca------ccaatcctg--gt------gtggacgtggtatttggcc-cctcgt
gcc-cttg-agcatggtgggcagaagttggggctgccggcggtgccggtcacagcacaag
gtggatgacgcaagttgttctcggtgctgtgtttcga-ccgcttacggcgct------tg
--------ccctttggaccca-tctaccgaagtgcatgtcgctcggactgcga
>Muhlenbergia_reederorum 689 bp 
tcgtgaccctgaccaaaacagaccgtgaacatgtcatccatgcc-gccgga--wgacggg
-tcytgcacccgtctctcggcacggggcamtt---accttc--ttctagaagggaagggc
ccc---aaaaagaacccacggcgccgtatggcgtcaaggaacactgataaa---tccttg
ctc-ggggctt----cggtcggcttgccggtcgaa--ccccttgcagcgat-gatatgcg
a----atc-cacatgactctcggcaacggatatctcggctctcgcatcgatgaagaacgt
agcaaaatgcgatacctggtgtgaattgcagaatcccgtgaaccatcgagtttttgaacg
caagttgcgcccgaggccttctggtcgagggcacgtctgcctgggcgtcaygccaaaaga
cactcccca------ccaatcccg--gt------gyggacgtggtatttggcc-cctcgt
gcc-ttag-cgygcggtgggcagaagtttgggctgccggcggtgccgatcacagcacaag
gtggatgacgcaagttgttctcggtgctgcgatacgaaccgcttacggcratgctat-gg
--------ccctttggaccct-tcgaccgaagcgcatgccgctcggaccgcga
>Muhlenbergia_reverchonii 668 bp 
tcgtgaccctgaccaaaacagaccgtgaacatgtcatccatgcc-gccgga--agatggg
-tcttgcacccgtctctcggcacggggcactt---gccttc--ttctagaaggaaagggc
ccc---aaaaagaacccacggcgccgtatggcgtcaaggaacactgataaa---tccttg
ctc-ggggctt----tggtcggcttgccggtcgaa--ccccttgcagcgat-gatatgcg
a----atc-cacatgactctcggcaacggatatctcggctctcgcatcgatgaagaacgt
agcaaaatgcgatacctggtgtgaattgcagaatcccgtgaaccatcgagtttttgaacg
caagttgcgcccgaggccttttggtcgagggcacgtctgcctgggcgtcacgccaaaaga
cactcccca------ccaatcccg--gt------gtggacgtggtatttggcc-cctcgt
gcc-ttag-cgtgcggtgggcagaagtttgggctgccggcggtgccgatcacagcacaag
gtggatgacgcaagttgttctcggtgctacgatacgaaccgcttacggcaatgctat-gg
--------ccctttggaccct-tcgaccgaagcgcatgccgctcggaccgcga
>Muhlenbergia_richardsonis 668 bp 
tcgtgaccctgaccaaaacagactgtgaacatgtcatccatgc-caccgat--tgacggg
-gcttgcacccgtctctcggtctggggcacat---taccttcatttttgaaggaaaagtg
gcc--caaaaagaacccacggcgccgtatggcgtcaaggaacacttg-tat---tgcttg
ctc-ggggcta----agatcggcttgccgaacggaa-ccccggacagtgat-gatatgct
a----atc-aacatgactctcggcaacggatatctcggctctcgcatcgatgaagaacgt
agcaaaatgcgatacctggtgtgaattgcagaatcccgtgaaccatcgagtttttgaacg
caagttgcgcccgagaccttctggttgagggcacgtctgcctgggcgtcacgccaaaaga
cactcccca------cccaaccta--gt------ggggacgtggtatttggct-cctcgt
gtc-gtta-tgcacggtgggcaaaagttggggctgccggcggtgccgatcacagcacaag
gtggatgacgcaagttgttctcggtgctacgatacaagccgtgtacggcgatgctat-gg
--------ccctttggacccatttaatcgaagcgcgcgtcgctcgaaccgcga
>Muhlenbergia_schreberi 668 bp 
tcgtgaccctgaccaaaacagaccgtgaacatgtcatccatgc-caccgtt--tgatggg
-acttgcacccgtctctcggtatggggcacgt---accttc--ttctagaagggaagtg-
ccc--caaaaagaacccacggcgccgtatggcgtcaaggaaaactga-tat---tgcttg
ttt-cgggcca----cgtccggcttgccggactaa--ccccgggcagtgat-gatatgct
a----atc-aacatgactctcggcaacggatatctcggctctcgcatcgatgaagaacgt
agcaaaatgcgatacctggtgtgaattgcagaatcccgtgaaccatcgagtttttgaacg
caagttgcgcccgaggccttctggttgagggcacgtctgcctgggcgtcacgccaaaaga
cactcccca------cccatctcg--gt------tgggacgtggtatttggcc-cctcgt
gcc-tttc-ggcgcggtgggcagaagttggggctgccggcagtgccgatcacagcacaag
gtggatgacgcaagttgttctcggtgctatgatacgaactgcttacggcgatgctac-gg
--------cccattggaccc-atggatcgaagcgcacatcgctcggaccgcga
>Muhlenbergia_seatonii 680 bp 
tcgtgaccctgaccaaaacagaccgtgaacatgtcatccatgc-caccggt--tgatggg
-gcttgcacccatctctcggtctggagcacgt---acctaca-tttttgtagggaatgtg
ccc--caaaaagaacccacggcgctgtatggcgtcaaggaacacttg-tat---tgcttg
ctc-ggagtca----cgttsggcttgccgaaaggaa-ccccgggcagtgat-gatatgat
a----atc-aacatgactctcggcaacggatatctcggctctcgcatcgatgaagaacgt
agcaaaatgcgatacctggtgtgaattgcagaatcccgtgaaccatcgagtttttgaacg
caagttgcgcccgaggccttctggttgagggcacgtctgcctgggcgtcacgycaaaaga
cactccccr------cctatctga--gt------agggatgtggtatttggcc-cctcgt
gcc-tttg-cgtgcggtgggcaaaagttggggctgccggcggagccgatcacagcacaag
gtggatgacgtaagttgttctcggtgctacgataygagccgcacacggcaatgctat-gg
--------ccctttggaccca-tcaatcgaagcgcgtgtcgctcgaaccgcga
>Muhlenbergia_setarioides 668 bp 
tcgtgaccctgaccaaaacagaccgtgaacatgtcatccatcc-cgccggt--tgatggg
-gcttgcacccgtctctcggtctggggcacat---atcttc--ttctagaagggatgggc
tcc--aaaaaagaacccacggcgccgtatggcgtcaaggtacactga-aat---tgcttg
ctt-ggggcaacgatcgatcggcttgccggttgaa--ccccgggcagtgat-gatatgct
a----atc-aatatgactctcggcaacggatatctcggctctcgcatcgatgaagaacgt
agcaaaatgcgatacctggtgtgaattgcagaatcccgtgaaccatcgagtttttgaacg
caagttgcgcccgagaccttctggttgagggcacgtctgcctgggcgtcacgccaaaaga
cactcccca------cccatcttg--gt------gtggatgtggtatttggcc-cctcgt
gcc-tttg-tgcacggtgggcaaaagatggggctgccggcggtgccgatcacagcacaag
gtggatgacggaagttgttctcggtgctatgatatgaaccgcttacggcgatgctat-gg
--------ccctttggaccc-atccatcgaagcgcatgtcgctcgaaccgcga
>Muhlenbergia_sinuosa 674 bp 
tcgtgtccctgaccaaaacagaccgtgaacatgtcatccatgct-gccggt--tgatggg
-gcttgcacccgtctcccagctcggggcacag---accttc--ttcttgaagagaaatgc
ccc---aaaaagaacccacggcgccgtatggcgtcaaggaaaacagaaaaa---tccttg
tat-gggtgca----cgtccggcwtgccggatgga--ccccatgcagtgat-gmtatgcg
a----aaa-cacatgactctcggcaacggatatctcggctctcgcatcgatgaagaacgt
agcaaaatgcgatacctggtgtgaattgcagaatcccgtgaaccatcgagtttttgaacg
caagttgcgcccgaggccttttggttgagggcacgtctgcctgggcgtcacgccaaaaga
cactcccca------caaatcttt--gt------gcggatgtggtatttggct-cctcgt
gcc-tttg-ggcgcggtgagcagaagttggggctgccggcggtgccgatcacagcacaag
gtggatgacgcaagttgttctcggtgctatggtacggactgctgacggcga--gcat-gg
--------ccctttggaccca-ttgaccgaagcgcacgccgctcggaccgcga
>Muhlenbergia_sobolifera 668 bp 
tcgtgaccctgaccaaaacagaccgtgaacatgtcatccatgc-cgccgtt--tgatggg
-gcttgcacccgtctctcggtatggggcacgt---accttc--ttctagaagggaaatg-
ccc--caaaaagaacccacggcgccgtatggcgtcaaggaaaactga-tat---tgcttg
ttt-cggggca----cgtccggcttgccggactaa--ccctgggcagtgat-gatatgct
a----ata-cacatgactctcggcaacggatatctcggctctcgcatcgatgaagaacgt
agcaaaatgcgatacctggtgtgaattgcagaatcccgtgaaccatcgagtttttgaacg
caagttgcgcccgaggccttctggttgagggcacgtctgcctgggcgtcacgccaaaaga
cactcccca------cccatctcg--gt------tgggacgtggtatttggcc-cctcgt
gcc-tttc-ggcgcggtgggcagaagttggggctgccggcagtgccgatcacagcacaag
gtggatgacgcaagttgttctcggtgctatgatacgaactgcttacggcgatgctat-gg
--------cccattggaccc-atggatcgaagcgcacatcgctcggaccgcga
>Muhlenbergia_stricta 680 bp 
tcgtgaccctgaccaaaacagaccgtgaacatgtcatccatgcc-gccgga--tgacggg
-tcttgcacccgtctcccggcacggggctctt---accttc--ttctagaagggaagggc
ctc---aaaaagaacccacggcgccgtatggcgtcaaggaacactgataaa---tccttg
cay-ggggctt----tggtcggcttgccgswcgaa--cyccttgcagcgat-gatatgcg
a----atc-cacatgactctcggcaacggatatctcggctctcgcatcgatgaagaacgt
agcaaaatgcgatacctggtgtgaattgcagaatcccgtgaaccatcgagtttttgaacg
caagttgcgcccgaggccttctggttgagggcacgtctgcctgggcgtcacgccaaaaga
cactcccca------ccaatctcg--gt------gtggacgtggtatttggcc-cctcgt
gcc-ttag-cgtgcggtgggcagaagtttgggctgccggcggtgccgatcacagcacaag
gtggatgacgcaagttgttctcggtgctacgatacgaaccgcttacggcaatgctat-gg
--------ccctttggaccct-tcgaccgaagcgcatgccgctcggaccgcga
>Muhlenbergia_tenuifolia 668 bp 
tcgtggccctgaccaaaacaaaccgtgaacatgtcatccatgcttgccgat--tgacggg
-gcttgcacccgtctctcggtctggggcgcag---accttg--tacc--aagggaaggg-
ccc--caaaaagaacccacggcgtcgtatgacgtcaaggaacactga-tat---tgcttg
ctt-ggggcca----cattcggcttgctggatgac--ccccgagcagtgat-gatatgct
a----atc-aacatgactctcggcaacggatatctcggctctcgcatcgatgaagaacgt
agcaaaatgcgatacctggtgtgaattgcagaatcccgtgaaccatcgagtttttgaacg
caagttgcgcccgaggccttttggttgagggcacgtctgcctgggcgtcacgccaaaaga
cactcccct------cccatcctg--gt------ggggacgtggtatttggcc-ccccgt
gcc-tttt-ggcacggtgggcaaaagttggggctgccggcggtgccgatcacagcacaag
gtggatgacgcaagttgttctcgatgctaggatacggacagcttatggcaatgatat-gg
--------ccctttggaccc-attgatcgaagtgcacgtcgctcggaccgcga
>Muhlenbergia_torreyi 668 bp 
tcgtgaccctgaccaaaacagaccgtgaacatgtcatccatgcc-gccggt--tgatggg
-gcttgcacccatctcccggcatggggca--g---accttc--ttacagaagagaactgc
ccc---aaaaagaacccacggcgccgtatggcgtcaaggaagactgaaaaa---tccttg
ctc-gggtgca----agttcggcttgccggacgga--ccccgtgcagcgat-gctatgcg
a----aaa-cacatgactctcggcaacggatatctcggctctcgcatcgatgaagaacgt
agcaaaatgcgatacctggtgtgaattgcagaatcccgtgaaccatcgagtttttgaacg
caagttgcgcccgaggccttttggttgagggcacgtctgcctgggcgtcacgccaaaaga
cactcccca------ccaatctcg--gt------gcggatgtggtatttggct-cctcgt
gcc-tttg-tgcgcggtgggcataagttggggctgccggcggtgccgatcacagcacaag
gtggatgacgcaagttgttctcggtgctacgatacgaaccgctcacggcaattgtac-gg
--------ccttttggaccca-ttgaccgaagcgcacgccgctcggaccgcga
>Muhlenbergia_utilis 668 bp 
tcgtgaccctgaccaaaacaaactgtgaacatgtcatccatgc-caccgat--tgacggg
-gcttgcacccgtctctcggtctggggcacat---tactttcatttttgaaggtaaagtg
gcc--caaaaagaacccacggcgccgtatggcgtcaaggaacacttg-tat---tgcttg
ctc-ggggcta----agatcggcttgccgaacggaa-ccccggacagcgat-gatatgct
a----atc-aacatgactctcggcaacggatatctcggctctcgcatcgatgaagaacgt
agcaaaatgcgatacctggtgtgaattgcagaatcccgtgaaccatcgagtttttgaacg
caagttgcgcccgagaccttctggttgagggcacgtctgcctgggcgtcacgccaaaaga
cactcccca------cccaatcta--gt------ggggacgtggtatttggcc-cctcgt
gcc-gttg-cgcacggtgggcaaaagttggggctgccggcggtgccgatcacagcacaag
gtggatgacgcaagttgttctcggtgctaagatacgagccgtgtacggcgatgctat-gg
--------ccctttggaccca-ttaatcgaagcgcgcgtcgctcgaaccgcga
>Muhlenbergia_vaginata 668 bp 
tcgtgaccctgaccaaaacagaccgtgaacatgtcatccatgcc-gccggt--tgatggg
-gcttgtacccgtctactagcacggggcacgg---aacttc--ttccggaagagaagtgc
ccc---aaaaagaacccacggcgccgtatggcgtcaaggaacactgataaa---tccttg
ctc-gaggaca----cgttcggcttgccggacgat--ccccgtgcagcgat-gctatgcg
a----ata-cacatgactctcggcaacggatatctcggctctcgcatcgatgaagaacgt
agcaaaatgcgatacctggtgtgaattgcagaatcccgtgaaccatcgagtttttgaacg
caagttgcgcccgaggccttttggttgagggcacgtctgcctgggcgtcacgccaaaaga
cactctcca------ccaatcctg--gt------gcggatgtggtatttggcc-cctcgt
gcg-tttg-tgcacggtgggcagaagttggggctgccggcggtgccgatcacagcacaag
gtggatgacgcaagttgttctcggtgctacgatagaaaccgcttacggcaattgtac-gg
--------ccctttggaccca-ttga-cgaagcgcacgccgctcggaccgcga
>Muhlenbergia_villiflora_var__villiflora Muhlenbergia_villiflora_var._villiflora 671 bp 
tcgtgaccctgaccaaaacagaccgtgaacttgtcatccatgc-caccgat--tgacggg
-gcttgcacccgtctctcggtctggggcaaat---accttca-tttcagaagggaaagtg
ccc--caaaaagaacccacggcgccgtatggcgtcaaggaacacttg-tat---tgcttg
ccc-ggggcca----cggtcggcttgccgaacggaa-ccccgtgcagtgat-gatatgct
a----atc-aacatgactctcggcaacggatatctcggctctcgcatcgatgaagaacgt
agcaaaatgcgatacctggtgtgaattgcagaatcccgtgaaccatcgagtttttgaacg
caagttgcgcccgaggccttctggttgagggcacgtctgcctgggcgtcacgccaaaaga
cactcccca------cccatccta--gt------ggggacgtggtatttggcc-cctcgt
gtc-tttg-ggcgcggtgggcamaagttggggctgccggcggtgccgatcacagcacaag
gtggatgacgcaagttgttctcgttgctacgatacgagccgcatacggcaatgctat-gg
--------ccctttggaccca-tcaatcgaagcgcgcgtcgctcgaactgcga
>Muhlenbergia_virescens 671 bp 
tcgtgaccctgaccaaaacagaccgtgaacatgtcatccatgc-tgccaat--tgacggg
-cctcgcacccgtcaattggtctggggcacgt---a-cttc--ttcttagaagggaacga
ccc--ctacaagaacccacggcgccgtatggcgtcaaggaatactga-tat---tgcttg
ctc-ggggcaa----cgatcagcttgctgaacgaaw-ccctgtgcagtgat-gatttgct
a----att-cacatgactctcggcaacggatatctcggctctcgcatcgatgaagaacgt
agcaaaatgcgatacctggtgtgaattgcagaatcccgtgaaccatcgagtttttgaacg
caagttgcgcccgagaccttctggtcaagggcacgtctgcctgggcgtcacgccaaaaga
cactcccca------ccattatta--gt------ggggacgtggtatttggtc-cttcgt
gcc-tttg-cgcgcggtgggcaaaagttggggctgccggcggtgccgatcacagcacaag
gtggatgacgcaagttgttctcggtgctatgatacgaaccgcatacggcaatgctat-gg
--------ccctttggaccca-tcaatcgaagcgcgcgtcgctcgtaccgcga
>Muhlenbergia_wrightii 686 bp 
tcgtgaccctgacmaaaacaraccgtgaacatgtcatccatgc-caccggt--tgacggg
-gcttgcacccgtctctcggtctggggcaaat---accttcg-ttttagaagggaaagtg
ccc--caaaaagaacccacggcgccgtatggcgtcaaggaacacttg-tat---tgcttg
ctc-rgggcca----cggtcggcttgccgaaygraa-ccccgtgcagtgat-gatatgct
a----atc-aacatgactctcggcaacggatatctcggctctcgcatcgatgaagaacgt
agcaaaatgcgatacctggtgtgaattgcagaatcccgtgaaccatcgagtttttgaacg
caagttgcgcccgaggccttctggttgagggcacgtctgcctgggcgtcacgccaaaaga
cactcccca------cccatccta--gt------ggggacgtggtatttggcc-cctcgt
gcc-ttt--ggcgcggtgggcaaaagttggggctgccggcggtgccgatcacagcacaag
gtggatgacgcaagttgttctcggtgctacgatacgagccgcatacggcgatgcyat-gg
--------ccctttggaccca-tcaatcgaagcgcgcgtcgctcgaaccgcga
>Pappophorum_vaginatum 668 bp 
tcgtgaccctgaacaaaacagactgtgaacatgtcgtccatgc-cgctggg--taacagg
-gcttgcacctgtcacctggtacagggaacct---actttc----ttgtaaagttagtgt
ccc---aaaaagaaccaacggcgccgtatggcgtcaaggaacaatgatatt---gccttg
ctt--ggttca----cgtttggcttgccggacgaa--cccaatgcaaagat-gagatgtt
a----atc-cacatgactctcggcaacggatatctcggctctcgcatcgatgaagaacgt
agcaaaatgcgatacctggtgtgaattgcagaatcccgtgaaccatcgagtttttgaacg
caagttgcgcccgaggccttttgactgagggcacgtctgcttgggcgtcactcctaaaga
cactcccca------cccatcctg--gt------gcggacgtggtgtttggcc-cctcgc
gcc-tttt-ggtgcggtgggcacaagttggggctgccggtgttgccgatcacagcataag
gtggataacaaatgttgttctcgaagctatgattcggaccacttctggtgatgcgat-gg
--------ccctttgcaccca-ttgacc-aagcgcacgttgcttggattgcga
>Pereilema_ciliatum 668 bp 
tcgtgaccctgaccaaaatagaccgtgaacatgtcatccatgc-tgccgtt--tgacggg
-gcttgcacccgcctctcggtctggggcacat---ccattc--ttctagaatggaagtg-
cac--caaaaagaacccacggcgccgtatggcgtcaaggaacactaa-tat---tgcttg
ttt-ggggcca----cgttccgcttgcgggactaa--ccctggacagtgat-gatatgct
a----atc-cacatgactctcggcaacggatatctcggctctcgcatcgatgaagaacgt
agcaaaatgcgatacctggtgtgaattgcagaatcccgtgaaccatcgagtttttgaacg
caagttgcgcccgaggtcttctggttgagggcacgtctgcctgggcgtcacgccaaaaga
cactcccca------cccatcttg--gt------tgggacgtggtatttggcc-cctcgt
gcc-tttc-ggcgcggtgggcacaagtttgggctgccggcggtgccgatcacagcacaag
gtggatggcgcaagttgttctcggtgctgtgatatgaaccgcttacggtgatgctat-ag
--------ccctttggaccc-atggatcgaagcgcacatcgctcggaccgcga
>Pereilema_crinitum 671 bp 
tcgtgaccctgaccaaaacagaccgtgaacatgtcatccatgt-cgccgtt--tgacggg
-gcttgcacccggctctcggtctggggcacat---ttcttc--ttccagaagggatgcg-
tcc--caaaaagaacccacggcgccgtatggcgtcaaggaacactga-tat---tgcttg
ttt-ggggcca----tgttcggcttgctggactwa--ccccgggcagtgat-gatatgct
a----atc-cacatgactctcggcaacggatatctcggctctcgcatcgatgaagaacgt
agcaaaatgcgatacctggtgtgaattgcagaatcccgtgaaccatcgagtttttgaacg
caagttgcgcccgaggccttctggttgagggcacgtctgcctgggcgtcacgccaaaaga
cactcccca------catatcttg--gt------tgggacgtggtatttggcc-cctcgt
gcc-tttg-ggcgcggtgggcagaagttggggctgccggcggtgccgatcacagcacaag
gtggatggcgcaagttgttctcggtgctgcgatacgaaccgcgtacggcgatgccac-gg
--------ccctttggaccc-atggatcgaagcgcatgtcgctcggaccgcga
>Redfieldia_flexuosa 668 bp 
tcgtgaccctgaccaaaacagaccgcgaacatgtcatccatgc-cgccggt--tgacggg
-gcttgcacccgtctctcggtatggggcacat---accttct-tttttgaagggaaaggg
ccc--caaaaagaacccacggcgccgtatggcgtcaaggaaaacttg-tat---tgcttg
ctc-ggggcta----tgatcggcttgccgaacggaa-ccccgtgcagtgat-gatatgct
a----atc-aacatgactctcggcaacggatatctcggctctcgcatcgatgaagaacgt
agcaaaatgcgatacctggtgtgaattgcagaatcccgtgaaccatcgagtttttgaacg
caagttgcgcccgaggccttctggttgagggcacgtctgcctgggcgtcacgccaaaaga
cactcccca------cccatcctagggt------agggacgtggtatttggcc-cctcgt
gcc-tttg-tgcgcggtgggcaaaagttggggctgccggcggtgccgatcacagcacaag
gtggatgacgcaagttgttctcggtgctacgatacgagccgcatacggcgatgctat-ag
--------ccctttggaccca-tggatcgaagcgcgcgtcgctcgaaccgcga
>Schaffnerella_gracilis 671 bp 
tcgtgaccctgaccaaaacagaccgtgaacatgtcatccatgc-caccggt--tgacggg
-g-tcgcacccgtctctcggtctggggcacct---accttcattttttgatgggaaagtg
ccc--caaaaagaacccacggcgccgtatggcgtcaaggaacacttg-tat---tgcttg
ctc-ggggcaa----cggtcggcttgccgaatggaa-ccccgtgcagtgat-gatatgct
a----atc-aacatgactctcggcaacggatatctcggctctcgcatcgatgaagaacgt
agcaaaatgcgatacctggtgtgaattgcagaatcccgtgaaccatcgagtttttgaacg
caagttgcgcccgaggccttctggttgagggcacgtctgcctgggcgtcacgccaaaaga
cactcccca------ccaatccta--gt------ggggacgtggtatttggcc-aatcgt
gcc-ttt--ggtgcggtgggcaaaagtgtgggctgccggcggtgccgatcacagcacaag
gtggatgacgcaagttgttctcggtgttatgatatgtaccgcaaacggtgatggtat-gg
--------ccctttggaccca-tgaatcgaagcgcgcgtcgytcgaaccgcga
