>Phytophthora_alticola_CMW19424_DQ988197 Phytophthora_alticola_CMW19424_DQ988197 895 bp 
ccacacct--aaaaactttccacgtgaaccgtatcaa-acttttagttgggggtcttttt
cggcgacggctgctggcttcattgctggcggctgctgttgaat-gagccctatcatggcg
agcg-tttaggcttc--ggtctgaactagtagc-----ttttttaaacccatt-ctttat
tactgattatactgtggggacgaaagtctctgcttttaactagatagcaactttcagcag
tggatgtctaggctcgcacatcgatgaagaacgctgcgaactgcgatacgtaatgcgaat
tgcaggattcagtgagtcatcgaaattttgaacgcatattgcacttccgggttagtcctg
ggagtatgcctgtatcagtgtccgtacatcaaacttggctttcttccttccgtgtagtcg
gtgga---agatgtgccagatgtgaagtgtcttgcggc--tggt----cttcgggtcgg-
-ctgtgagtcctttgaaatgtactgaactgtacttctctttgctcgaaaagcgtggc--g
ttgctgattgtggaggctgcctgcgtagccagtctggcgaccagtttgtctgctgtggcg
-ttaatggaggagtgttcgattcgcggtatggttggcttcggctgaacagac-gcttatt
gaatggtttttcctgctatggcg--gtacaggttggtgaaccgtagctatgtg-ggcttg
gcttttgaa--ttggctttgctgttgcgaagtagagtggcgg----------cttcagc-
-----------tgtcgagggtcgatcca-tttgggaag--tg-gtgggtactt
>Phytophthora_alticola_CMW19425_DQ988196 Phytophthora_alticola_CMW19425_DQ988196 895 bp 
ccacacct--aaaaactttccacgtgaaccgtatcaa-acttttagttgggggtcttttt
cggcgacggctgctggcttcattgctggcggctgctgttgaat-gagccctatcatggcg
agcg-tttaggcttc--ggtctgaactagtagc-----ttttttaaacccatt-ctttat
tactgattatactgtggggacgaaagtctctgcttttaactagatagcaactttcagcag
tggatgtctaggctcgcacatcgatgaagaacgctgcgaactgcgatacgtaatgcgaat
tgcaggattcagtgagtcatcgaaattttgaacgcatattgcacttccgggttagtcctg
ggagtatgcctgtatcagtgtccgtacatcaaacttggctttcttccttccgtgtagtcg
gtgga---agatgtgccagatgtgaagtgtcttgcggc--tggt----cttcgggtcgg-
-ctgtgagtcctttgaaatgtactgaactgtacttctctttgctcgaaaagcgtggc--g
ttgctgattgtggaggctgcctgcgtagccagtctggcgaccagtttgtctgctgtggcg
-ttaatggaggagtgttcgattcgcggtatggttggcttcggctgaacagac-gcttatt
gaatggtttttcctgctatggcg--gtacaggttggtgaaccgtagctatgtg-ggcttg
gcttttgaa--ttggctttgctgttgcgaagtagagtggcgg----------cttcagc-
-----------tgtcgagggtcgatcca-tttgggaag--tg-gtgggtactt
>Phytophthora_boehmeriae_DDS3884_EU301151 Phytophthora_boehmeriae_DDS3884_EU301151 895 bp 
ccacacct-aaaaaactttccacgtgaaccgttcaa--ccttttagttggggactcctcg
tc------ggcggctttcgggctgttggtgggtt----------gaggcctatcaaagcg
agtgatttgggccgcaaggtctgagttgcgagt--tttccttttaaacccattacttaaa
tactgattatactgtggggacgaaagtctctgcttttaactagatagcaactttcagcag
tggatgtctaggctcgcacatcgatgaagaacgctgcgaactgcgatacgtaatgcgaat
tgcaggattcagtgagtcatcgaaattttgaacgcatattgcacttccgggttatgcctg
ggagtatgcctgtatcagtgtccgtacatcaaccttggcttccttccttccgtgtagtcg
gtggat--gggaatgccagacgtgaagtgtcttgctgtagcggt----tttcggactgcg
gcggcgagtcctttgaaatgta-gatactgttcttctctttgctcgaaaagctgtgcaga
atgtatgttgtggaggctgccatcacggcatgtc-ggcgactgattt-cgtgctgaggcg
ttt--tggagaggggttcgattcgcggtagtgttggtttcggccgaacaatctgcttatt
gggttcttttccaggctttggcgtatgcggagtcggtgtaccgtagttgtgcgtggcttg
gcctttgaacgctcgttttg-cgtggcgaagtagagtggcgaagtgtttgttttcggacg
aatgcggctgccgaggaggcgataaatattttgggaaaatttagtgtgcgctt
>Phytophthora_capsici_CBS128_23_DQ464056 Phytophthora_capsici_CBS128.23_DQ464056 895 bp 
ccacacct-aaaaaactttccacgtgaaccgtatcaacccttttagttgggggtc-----
---------------------ttgt---------------------accctatcatggcg
aatg-tttggacttc--ggtccgggcgagtagc-tttttgttttaaacccatt-tcacaa
ttctgattatactgtggggacgaaagtctctgcttttaactagatagcaactttcagcag
tggatgtctaggctcgcacatcgatgaagaacgctgcgaactgcgatacgtaatgcgaat
tgcaggattcagtgagtcatcgaaattttgaacgcatattgcacttccgggttagtcctg
ggagtatgcctgtatcagtgtccgtacatcaaacttggctttcttccttccgtgtagtcg
gtgga---ggatgtgccagatgtgaagtgtcttgcgtg--ttgt---ccttcgggtcga-
-ctgcgagtccttttaaatgtactgaactgtacttctctttgctcgaaaagcgtggt--g
ttgctggttgtggaggctgcctgcgtggccagtc-ggcgaccggtttgtctgctgcggcg
tttaaaggaggagtgttcgattcgcggtatggttggcttcggctgaacaggc-gcttatt
gaat-gcttttcctgctgtggcg--tgatgggctggtgaaccgtagctgtgtttggcttg
gcttttgaa--tcggctttgctgttgcgaagtagagtggcgg----------cttcggc-
-----------tgtcgagggtcgatccattttgggaat-ttt-gtgtgcactc
>Phytophthora_capsici_IMI352321_AF266787 Phytophthora_capsici_IMI352321_AF266787 895 bp 
ccacacct-aaaaaactttccacgtgaaccgtatcaacccttttagttgggggtc-----
---------------------ttgt---------------------accctatcatggcg
aatg-tttggacttc--ggtccgggcgagtagc-tttttgttttaaacccatt-tcacaa
ttctgattatactgtggggacgaaagtctctgcttttaactagatagcaactttcagcag
tggatgtctaggctcgcacatcgatgaagaacgctgcgaactgcgatacgtaatgcgaat
tgcaggattcagtgagtcatcgaaattttgaacgcatattgcacttccgggttagtcctg
ggagtatgcctgtatcagtgtccgtacatcaaacttggctttcttccttccgtgtagtcg
gtgga---ggatgtgccagatgtgaagtgtcttgcgtg--ttgt---ccttcgggtcga-
-ctgcgagtccttttaaatgtactgaactgtacttctctttgctcgaaaagcgtggt--g
ttgctggttgtggaggctgcctgcgtggccagtc-ggcgaccggtttgtctgctgcggcg
tttaaaggaggagtgttcgattcgcggtatggttggcttcggctgaacaggc-gcttatt
gaat-gcttttcctgctgtggcg--tgatgggctggtgaaccgtagctgtgtttggcttg
gcttttgaa--tcggctttgctgttgcgaagtagggtggcgg----------cttcggc-
-----------tgtcgagggtcgatccattttgggaac-ttt-gtgtgcactt
>Phytophthora_citricola_CBS221_88_IMI021173_FJ237526 Phytophthora_citricola_CBS221.88_IMI021173_FJ237526 895 bp 
ccacacct-aaaaaactttccacgtgaaccgtatcaacccttttagttgggggtc-----
---------------------ttgcttt----ttttgc------gagccctatcatggcg
aatg-tttggacttc--ggtctgggctagtagc-tttttgttttaaacccatt-ctacaa
tactgattatactgtggggacgaaagtctctgcttttaactagatagcaactttcagcag
tggatgtctaggctcgcacatcgatgaagaacgctgcgaactgcgatacgtaatgcgaat
tgcaggattcagtgagtcatcgaaattttgaacgcatattgcacttccgggttagtcctg
ggagtatgcctgtatcagtgtccgtacatcaaacttggctttcttccttccgtgtagtcg
gtgga---ggatgtgccagatgtgaagtgtcttgcggg---tgt---ccttcgggtcgt-
-ctgcgagtcctttgaaatgtactgaactgtacttctctttgctcgaaaagcgtggt--g
ttgctggttgtggaggctgcctgcgtggccagtc-ggcgaccggtttgtctgctgcggcg
tttaatggaggagtgttcgattcgcggtatggttggcttcggctgaacaggc-gcttatt
gtat-gcttttcctgctgtggcg--tgatgggctggtgaaccgtagctgtgtgtggcttg
gcttttgaa--tcggctttgctgttgcgaagtagagtggcgg----------cttcggc-
-----------tgtcgagggtcgatcca-tttgggaac-ttt-gtgtgcacct
>Phytophthora_citricola_CBS295_29_FJ560913 Phytophthora_citricola_CBS295.29_FJ560913 895 bp 
ccacacct-aaaaaactttccacgtgaaccgtatcaacccttttagttgggggtc-----
---------------------ttgcttt----ttttgc------gagccctatcatggcg
aatg-tttggacttc--ggtctgggctagtagc-tttttgttttaaacccatt-ctacaa
tactgattatactgtggggacgaaagtctctgcttttaactagatagcaactttcagcag
tggatgtctaggctcgcacatcgatgaagaacgctgcgaactgcgatacgtaatgcgaat
tgcaggattcagtgagtcatcgaaattttgaacgcatattgcacttccgggttagtcctg
ggagtatgcctgtatcagtgtccgtacatcaaacttggctttcttccttccgtgtagtcg
gtgga---ggatgtgccagatgtgaagtgtcttgcggg---tgt---ccttcgggtcgt-
-ctgcgagtcctttgaaatgtactgaactgtacttctctttgctcgaaaagcgtggt--g
ttgctggttgtggaggctgcctgcgtggccagtc-ggcgaccggtttgtctgctgcggcg
tttaatggaggagtgttcgattcgcggtatggttggcttcggctgaacaggc-gcttatt
gtat-gcttttcctgctgtggcg--tgatgggctggtgaaccgtagctgtgtgtggcttg
gcttttgaa--tcggctttgctgttgcgaagtagagtggcgg----------cttcggc-
-----------tgtcgagggtcgatcca-tttgggaac-ttt-gtgtgcacct
>Phytophthora_citricola_CH98U121C_AB367378_Japan Phytophthora_citricola_CH98U121C_AB367378_Japan 895 bp 
ccacacct-aaaaaactttccacgtgaaccgtatcaacccttttagttgggggtc-----
---------------------ttgcttt----ttttgc------gagccctatcatggcg
aatg-tttggacttc--ggtctgggctagtagc-tttttgttttaaacccatt-ctacaa
tactgattatactgtggggacgaaagtctctgcttttaactagatagcaactttcagcag
tggatgtctaggctcgcacatcgatgaagaacgctgcgaactgcgatacgtaatgcgaat
tgcaggattcagtgagtcatcgaaattttgaacgcatattgcacttccgggttagtcctg
ggagtatgcctgtatcagtgtccgtacatcaaacttggctttcttccttccgtgtagtcg
gtgga---ggatgtgccagatgtgaagtgtcttgcggg---tgt---ccttcgggtcgt-
-ctgcgagtcctttgaaatgtactgaactgtacttctctttgctcgaaaagcgtggt--g
ttgctggttgtggaggctgcctgcgtggccagtc-ggcgaccggtttgtctgctgcggcg
tttaatggaggagtgttcgattcgcggtatggttggcttcggctgaacaggc-gcttatt
gtat-gcttttcctgctgtggcg--tgatgggctggtgaaccgtagctgtgtgtggcttg
gcttttgaa--tcggctttgctgttgcgaagtagagtggcgg----------cttcggc-
-----------tgtcgagggtcgatcca-tttgggaac-ttt-gtgtgcacct
>Phytophthora_citricola_E_112_EU263906 Phytophthora_citricola_E_112_EU263906 895 bp 
ccacacct-aaaaaacttttcacgtgaaccgtatcaacccttttagttgggggtc-----
---------------------ttgc-tt----ttttgc------gagccctatcatggcg
aatg-tttggacttc--ggtctgggctagtagc-tttttgttttaaacccatt-ctacaa
tactgattatactgtggggacgaaagtctctgcttttaactagatagcaactttcagcag
tggatgtctaggctcgcacatcgatgaagaacgctgcgaactgcgatacgtaatgcgaat
tgcaggattcagtgagtcatcgaaattttgaacgcatattgcacttccgggttagtcctg
ggagtatgcctgtatcagtgtccgtacatcaaacttggctttcttccttccgtgtagtcg
gtgga---ggatgtgccagatgtgaagtgtcttgcggg---tgt---ccttcgggtcgt-
-ctgcgagtcctttgaaatgtactgaactgtacttctctttgctcgaaaagcgtggt--g
ttgctggttgtggaggctgcctgcgtggccagtc-ggcgaccggtttgtctgctgcagcg
tttaatggaggagtgttcgattcgcggtatggttggcttcggctgaacaggc-gcttatt
gtat-gcttttcctgctgtggcg--tgatgggctggtgaaccgtagctatgtgtggcttg
gcttttgaa--tcggctttgctgttgcgaagtagagtggcgg----------cttcggc-
-----------tgtcgagggtcgatcca-tttgggaac-ttt-gtgtgcacct
>Phytophthora_citricola_E_IMI031372_AF266788 Phytophthora_citricola_E_IMI031372_AF266788 895 bp 
ccacacct-aaaaaacttttcacgtgaaccgtatcaacccttttagttgggggtc-----
---------------------ttgc-tt----ttttgc------gagccctatcatggcg
aatg-tttggacttc--ggtctgggctagtagc-tttttgttttaaacccatt-ctacaa
tactgattatactgtggggacgaaagtctctgcttttaactagatagcaactttcagcag
tggatgtctaggctcgcacatcgatgaagaacgctgcgaactgcgatacgtaatgcgaat
tgcaggattcagtgagtcatcgaaattttgaacgcatattgcacttccgggttagtcctg
ggagtatgcctgtatcagtgtccgtacatcaaacttggctttcttccttccgtgtagtcg
gtgga---ggatgtgccagatgtgaagtgtcttgcggg---tgt---ccttcgggtcgt-
-ctgcgagtcctttgaaatgtactgaactgtacttctctttgctcgaaaagcgtggt--g
ttgctggttgtggaggctgcctgcgtggccagtc-ggcgaccggtttgtctgctgcagcg
tttaatggaggagtgttcgattcgcggtatggttggcttcggctgaacaggc-gcttatt
gtat-gcttttcctgctgtggcg--tgatgggctggtgaaccgtagctatgtgtggcttg
gcttttgaa--tcggctttgctgttgcgaagtagagtggcgg----------cttcggc-
-----------tgtcgagggtcgatcca-tttgggaac-ttt-gtgtgcacct
>Phytophthora_citricola_I_22F3_FJ392321 Phytophthora_citricola_I_22F3_FJ392321 895 bp 
ccacacctaaaaaaacttttcacgtgaaccgtatcaacccttttagttgggggtc-----
---------------------ttgc-tt----ttttgc------gagccctatcatggcg
aatg-tttggacttc--ggtctgggctagtagc-tttttgttttaaacccatt-ctacaa
tactgattatactgtggggacgaaagtctctgcttttaactagatagcaactttcagcag
tggatgtctaggctcgcacatcgatgaagaacgctgcgaactgcgatacgtaatgcgaat
tgcaggattcagtgagtcatcgaaattttgaacgcatattgcacttccgggttagtcctg
ggagtatgcctgtatcagtgtccgtacatcaaacttggctttcttccttccgtgtagtcg
gtgga---ggatgtgccagatgtgaagtgtcttgcggg---tgt---ccttcgggtcgt-
-ctgcgagtcctttgaaatgtactgaactgtacttctctttgctcgaaaagcgtggt--g
ttgctggttgtggaggctgcctgcgtggccagtc-ggcgaccggtttgtctgctgcggcg
tttaatggaggagtgttcgattcgcggtatggttggcttcggctgaacaggc-gcttatt
gtat-gcttttcctgctgtggcg--tgatgggctggtgaaccgtagctgtgtgtggcttg
gcttttgaa--tcggctttgctgttgcgaagtagagtgacgg----------cttcggc-
-----------tgtcgagggtcgatcca-tttgggaac-ttt-gtgtgcacct
>Phytophthora_citricola_I_CBS181_25_FJ392322 Phytophthora_citricola_I_CBS181.25_FJ392322 895 bp 
ccacacctaaaaaaacttttcacgtgaaccgtatcaacccttttagttgggggtc-----
---------------------ttgc-tt----ttttgc------gagccctatcatggcg
aatg-tttggacttc--ggtctgggctagtagc-tttttgttttaaacccatt-ctacaa
tactgattatactgtggggacgaaagtctctgcttttaactagatagcaactttcagcag
tggatgtctaggctcgcacatcgatgaagaacgctgcgaactgcgatacgtaatgcgaat
tgcaggattcagtgagtcatcgaaattttgaacgcatattgcacttccgggttagtcctg
ggagtatgcctgtatcagtgtccgtacatcaaacttggctttcttccttccgtgtagtcg
gtgga---ggatgtgccagatgtgaagtgtcttgcggg---tgt---ccttcgggtcgt-
-ctgcgagtcctttgaaatgtactgaactgtacttctctttgctcgaaaagcgtggt--g
ttgctggttgtggaggctgcctgcgtggccagtc-ggcgaccggtttgtctgctgcggcg
tttaatggaggagtgttcgattcgcggtatggttggcttcggctgaacaggc-gcttatt
gtat-gcttttcctgctgtggcg--tgatgggctggtgaaccgtagctatgtgtggcttg
gcttttgaa--tcggctttgctgttgcgaagtagagtgacgg----------cttcggc-
-----------tgtcgagggtcgatcca-tttgggaac-ttt-gtgtgcacct
>Phytophthora_citricola_I_US1_FJ665234 Phytophthora_citricola_I_US1_FJ665234 895 bp 
ccacacctaaaaaaacttttcacgtgaaccgtatcaacccttttagttgggggtc-----
---------------------ttgc-tt----ttttgc------gagccctatcatggcg
aatg-tttggacttc--ggtctgggctagtagc-tttttgttttaaacccatt-ctacaa
tactgattatactgtggggacgaaagtctctgcttttaactagatagcaactttcagcag
tggatgtctaggctcgcacatcgatgaagaacgctgcgaactgcgatacgtaatgcgaat
tgcaggattcagtgagtcatcgaaattttgaacgcatattgcacttccgggttagtcctg
ggagtatgcctgtatcagtgtccgtacatcaaacttggctttcttccttccgtgtagtcg
gtgga---ggatgtgccagatgtgaagtgtcttgcggg---tgt---ccttcgggtcgt-
-ctgcgagtcctttgaaatgtactgaactgtacttctctttgctcgaaaagcgtggt--g
ttgctggttgtggaggctgcctgcgtggccagtc-ggcgaccggtttgtctgctgcggcg
tttaatggaggagtgttcgattcgcggtatggttggcttcggctgaacaggc-gcttatt
gtat-gcttttcctgctgtggcg--tgatgggctggtgaaccgtagctgtgtgtggcttg
gcttttgaa--tcggctttgctgttgcgaagtagagtgacgg----------cttcggc-
-----------tgtcgagggtcgatcca-tttgggaac-ttt-gtgtgcacct
>Phytophthora_citricola_I_US10_FJ665235 Phytophthora_citricola_I_US10_FJ665235 895 bp 
ccacacctaaaaaaacttttcacgtgaaccgtatcaacccttttagttgggggtc-----
---------------------ttgc-tt----ttttgc------gagccctatcatggcg
aatg-tttggacttc--ggtctgggctagtagc-tttttgttttaaacccatt-ctacaa
tactgattatactgtggggacgaaagtctctgcttttaactagatagcaactttcagcag
tggatgtctaggctcgcacatcgatgaagaacgctgcgaactgcgatacgtaatgcgaat
tgcaggattcagtgagtcatcgaaattttgaacgcatattgcacttccgggttagtcctg
ggagtatgcctgtatcagtgtccgtacatcaaacttggctttcttccttccgtgtagtcg
gtgga---ggatgtgccagatgtgaagtgtcttgcggg---tgt---ccttcgggtcgt-
-ctgcgagtcctttgaaatgtactgaactgtacttctctttgctcgaaaagcgtggt--g
ttgctggttgtggaggctgcctgcgtggccagtc-ggcgaccggtttgtctgctgcggcg
tttaatggaggagtgttcgattcgcggtatggttggcttcggctgaacaggc-gcttatt
gtat-gcttttcctgctgtggcg--tgatgggctggtgaaccgtagctgtgtgtggcttg
gcttttgaa--tcggctttgctgttgcgaagtagagtgacgg----------cttcggc-
-----------tgtcgagggtcgatcca-tttgggaac-ttt-gtgtgcacct
>Phytophthora_citricola_II_22F2_FJ392324 Phytophthora_citricola_II_22F2_FJ392324 895 bp 
ccacacct-aaaaaacttttcacgtgaaccgtatcaacccttttagttgggggtc-----
---------------------ttgcttt----ttttgc------gagccctatcatggcg
aatg-tttggacttc--ggtctgggctagtagc-tttttgttttaaacccatt-ctacaa
tactgattatactgcggggacgaaagtctctgcttttaactagatagcaactttcagcag
tggatgtctaggctcgcacatcgatgaagaacgctgcgaactgcgatacgtaatgcgaat
tgcaggattcagtgagtcatcgaaattttgaacgcatattgcacttccgggttagtcctg
ggagtatgcctgtatcagtgtccgtacatcaaacttggctttcttccttccgtgtagtcg
gtgga---ggatgtgccagacgtgaagtgtcttgcggg---tgt---ccttcgggtcgt-
-ctgcgagtcctttgaaatgtactgaactgtacttctctttgctcgaaaagcgtggt--g
ttgctggttgtggaggctgcctgcgtggccagtc-ggcgaccggtttgtctgctgcggcg
tttaatggaggagtgttcgattcgcggtatggttggcttcggctgaacaggc-gcttatt
gtat-gcttttcctgctgtggcg--tgatgggctggtgaaccgtagctgtgtgtggcttg
gcttttgaa--tcggctttgctgttgcgaagtagagtggcgg----------cttcggc-
-----------tgtcgagggtcgatcca-tttgggaac-ttt-gtgtgcacct
>Phytophthora_citricola_II_CBS379_61_FJ392325 Phytophthora_citricola_II_CBS379.61_FJ392325 895 bp 
ccacacct-aaaaaacttttcacgtgaaccgtatcaacccttttagttgggggtc-----
---------------------ttgcttt----ttttgc------gagccctatcatggcg
aatg-tttggacttc--ggtctgggctagtagc-tttttgttttaaacccatt-ctacaa
tactgattatactgcggggacgaaagtctctgcttttaactagatagcaactttcagcag
tggatgtctaggctcgcacatcgatgaagaacgctgcgaactgcgatacgtaatgcgaat
tgcaggattcagtgagtcatcgaaattttgaacgcatattgcacttccgggttagtcctg
ggagtatgcctgtatcagtgtccgtacatcaaacttggctttcttccttccgtgtagtcg
gtgga---ggatgtgccagacgtgaagtgtcttgcggg---tgt---ccttcgggtcgt-
-ctgcgagtcctttgaaatgtactgaactgtacttctctttgctcgaaaagcgtggt--g
ttgctggttgtggaggctgcctgcgtggccagtc-ggcgaccggtttgtctgctgcggcg
tttaatggaggagtgttcgattcgcggtatggttggcttcggctgaacaggc-gcttatt
gtat-gcttttcctgctgtggcg--tgatgggctggtgaaccgtagctgtgtgtggcttg
gcttttgaa--tcggctttgctgttgcgaagtagagtggcgg----------cttcggc-
-----------tgtcgagggtcgatcca-tttgggaac-ttt-gtgtgcacct
>Phytophthora_citricola_III_15C9_FJ392327 Phytophthora_citricola_III_15C9_FJ392327 895 bp 
ccacacct-aaaaaacttttcacgtgaaccgtatcaacccttttagttgggggtc-----
---------------------ttgc-tt----ttttgc------gagccctatcatggcg
aatg-tttggacttc--ggtctgggctagtagc-tttttgttttaaacccatt-ctacaa
tactgattatactgtggggacgaaagtctctgcttttaactagatagcaactttcagcag
tggatgtctaggctcgcacatcgatgaagaacgctgcgaactgcgatacgtaatgcgaat
tgcaggattcagtgagtcatcgaaattttgaacgcatattgcacttccgggttagtcctg
ggagtatgcctgtatcagtgtccgtacatcaaacttggctttcttccttccgtgtagtcg
gtgga---ggatgtgccagatgtgaagtgtcttgcggg---tgt---ccttcgggtcgt-
-ctgcgagtcctttgaaatgtactgaactgtacttctctttgctcgaaaagcgtggt--g
ttgctggttgtggaggctgcctgcgtggccagtc-ggcgaccggtttgtctgctgcggcg
tttaatggaggagtgttcgattcgcggtatggttggcttcggctgaacaggc-gcttatt
gtat-gcttttcctgctgtggcg--tgatgggctggtgaaccgtagctgtgtgtggcttg
gcttttgaa--tcggctttgctgttgcgaagtagagtgacgg----------cttcggc-
-----------tgtcgagggtcgatcca-tttgggaac-ttt-gtgtgcacct
>Phytophthora_citricola_III_1E1_FJ392326 Phytophthora_citricola_III_1E1_FJ392326 895 bp 
ccacacct-aaaaaacttttcacgtgaaccgtatcaacccttttagttgggggtc-----
---------------------ttgc--t----ttttgc------gagccctatcatggcg
aatg-tttggacttc--ggtctgggctagtagc-tttttgttttaaacccatt-ctacaa
tactgattatactgtggggacgaaagtctctgcttttaactagatagcaactttcagcag
tggatgtctaggctcgcacatcgatgaagaacgctgcgaactgcgatacgtaatgcgaat
tgcaggattcagtgagtcatcgaaattttgaacgcatattgcacttccgggttagtcctg
ggagtatgcctgtatcagtgtccgtacatcaaacttggctttcttccttccgtgtagtcg
gtgga---ggatgtgccagatgtgaagtgtcttgcggg---tgt---ccttcgggtcgt-
-ctgcgagtcctttgaaatgtactgaactgtacttctctttgctcgaaaagcgtggt--g
ttgctggttgtggaggctgcctgcgtggccagtc-ggcgaccggtttgtctgctgcggcg
tttaatggaggagtgttcgattcgcggtatggttggcttcggctgaacaggc-gcttatt
gtat-gcttttcctgctgtggcg--tgatgggctggtgaaccgtagctgtgtgtggcttg
gcttttgaa--tcggctttgctgttgcgaagtagagtgacgg----------cttcggc-
-----------tgtcgagggtcgatcca-tttgggaac-ttt-gtgtgcacct
>Phytophthora_citricola_III_EF032477 Phytophthora_citricola_III_EF032477 895 bp 
ccacacct-aaaaaacttttcacgtgaaccgtatcaacccttttagttgggggtc-----
---------------------ttgc-tt----ttttgc------gagccctatcatggcg
aatg-tttggacttc--ggtctgggctagtagc-tttttgttttaaacccatt-ctacaa
tactgattatactgtggggacgaaagtctctgcttttaactagatagcaactttcagcag
tggatgtctaggctcgcacatcgatgaagaacgctgcgaactgcgatacgtaatgcgaat
tgcaggattcagtgagtcatcgaaattttgaacgcatattgcacttccgggttagtcctg
ggagtatgcctgtatcagtgtccgtacatcaaacttggctttcttccttccgtgtagtcg
gtgga---ggatgtgccagatgtgaagtgtcttgcggg---tgt---ccttcgggtcgt-
-ctgcgagtcctttgaaatgtactgaactgtacttctctttgctcgaaaagcgtggt--g
ttgctggttgtggaggctgcctgcgtggccagtc-ggcgaccggtttgtctgctgcggcg
tttaatggaggagtgttcgattcgcggtatggttggcttcggctgaacaggc-gcttatt
gtat-gcttttcctgctgtggcg--tgatgggctggtgaaccgtagctgtgtgtggcttg
gcttttgaa--tcggctttgctgttgcgaagtagagtgacgg----------cttcggc-
-----------tgtcgagggtcgatcca-tttgggaac-ttt-gtgtgcacct
>Phytophthora_citricola_III_P11835_2_DQ648146 Phytophthora_citricola_III_P11835.2_DQ648146 895 bp 
ccacacct-aaaaaacttttcacgtgaaccgtatcaacccttttagttgggggtc-----
---------------------ttgc-tt----ttttgc------gagccctatcatggcg
aatg-tttggacttc--ggtctgggctagtagc-tttttgttttaaacccatt-ctacaa
tactgattatactgtggggacgaaagtctctgcttttaactagatagcaactttcagcag
tggatgtctaggctcgcacatcgatgaagaacgctgcgaactgcgatacgtaatgcgaat
tgcaggattcagtgagtcatcgaaattttgaacgcatattgcacttccgggttagtcctg
ggagtatgcctgtatcagtgtccgtacatcaaacttggctttcttccttccgtgtagtcg
gtgga---ggatgtgccagatgtgaagtgtcttgcggg---tgt---ccttcgggtcgt-
-ctgcgagtcctttgaaatgtactgaactgtacttctctttgctcgaaaagcgtggt--g
ttgctggttgtggaggctgcctgcgtggccagtc-ggcgaccggtttgtctgctgcggcg
tttaatggaggagtgttcgattcgcggtatggttggcttcggctgaacaggc-gcttatt
gtat-gcttttcctgctgtggcg--tgatgggctggtgaaccgtagctgtgtgtggcttg
gcttttgaa--tcggctttgctgttgcgaagtagagtgacgg----------cttcggc-
-----------tgtcgagggtcgatcca-tttgggaac-ttt-gtgtgcacct
>Phytophthora_citricola_IV_15C7_FJ392328 Phytophthora_citricola_IV_15C7_FJ392328 895 bp 
ccacacct-aaaaaactttccacgtgaaccgtatcaa-ac-tttagttgggggtcttttt
cggcgacggctgctggcttcattgctggcggctgctgttggat-gagccctatcatggcg
agcg-tttgggcttc--ggtctgaactagtagc-----ttttttaaacccatt-ctttat
tactgattatactgtggggacgaaagtctctgcttttaactagatagcaactttcagcag
tggatgtctaggctcgcacatcgatgaagaacgctgcgaactgcgatacgtaatgcgaat
tgcaggattcagtgagtcatcgaaattttgaacgcatattgcacttccgggttagtcctg
ggagtatgcctgtatcagtgtccgtacatcaaacttggctttcttccttccgtgtagtcg
gtgga---ggatgtgccagatgtgaagtgtcttgcggc--tggt----cttcgggtcgg-
-ctgtgagtcctttgaaatgtactgaactgtacttctctttgctcgaaaagcgtggc--g
ttgctgattgtggaggctgcctgcgtagccagtctggcgaccagtttgtctgctgtggcg
-ttaatggaggagtgttcgattcgcggtatggttggcttcggctgaacagac-gcttatt
gaat-gtttttcctgctgtggcg--gtacgggttggtgaaccgtagctatgtg-ggcttg
gcttttgaa--ttggctttgctgttgcgaagtagagtggcag----------cttcggc-
-----------tgtcgagggtcgatcca-tttgggaat--tt-gtgtgtactt
>Phytophthora_citricola_IV_15C8_FJ392329 Phytophthora_citricola_IV_15C8_FJ392329 895 bp 
ccacacct-aaaaaactttccacgtgaaccgtatcaa-ac-tttagttgggggtcttttt
cggcgacggctgctggcttcattgctggcggctgctgttggat-gagccctatcatggcg
agcg-tttgggcttc--ggtctgaactagtagc-----ttttttaaacccatt-ctttat
tactgattatactgtggggacgaaagtctctgcttttaactagatagcaactttcagcag
tggatgtctaggctcgcacatcgatgaagaacgctgcgaactgcgatacgtaatgcgaat
tgcaggattcagtgagtcatcgaaattttgaacgcatattgcacttccgggttagtcctg
ggagtatgcctgtatcagtgtccgtacatcaaacttggctttcttccttccgtgtagtcg
gtgga---ggatgtgccagatgtgaagtgtcttgcggc--tggt----cttcgggtcgg-
-ctgtgagtcctttgaaatgtactgaactgtacttctctttgctcgaaaagcgtggc--g
ttgctgattgtggaggctgcctgcgtagccagtctggcgaccagtttgtctgctgtggcg
-ttaatggaggagtgttcgattcgcggtatggttggcttcggctgaacagac-gcttatt
gaat-gtttttcctgctgtggcg--gtacgggttggtgaaccgtagctatgtg-ggcttg
gcttttgaa--ttggctttgctgttgcgaagtagagtggcag----------cttcggc-
-----------tgtcgagggtcgatcca-tttgggaat--tt-gtgtgtactt
>Phytophthora_citrophthora_CMW20198_DQ988188 Phytophthora_citrophthora_CMW20198_DQ988188 895 bp 
ccacacct-aaaaaactttccacgtgaaccgtatcaacccttttagttgggggtg-----
---------------------ttgcttggca-tttagctgagccgcgccctatcatggcg
aatg-tttggacttc--ggtctgggctagtagcttttttgttttaaa-ccatt-taacaa
tactgattatactgtggggacgaaagtctctgcttttaactagatagcaactttcagcag
tggatgtctaggctcgcacatcgatgaagaacgctgcgaactgcgatacgtaatgcgaat
tgcaggattcagtgagtcatcgaaattttgaacgcatattgcacttccgggttagtcctg
ggagtatgcctgtatcagtgtccgtacatcaaacttggctttcttccttccgtgtagtcg
gtgga---ggatgtgccagatgtgaagtgtcttgcggt--ttgtgtgccttcgggccgag
gctgcgagtcctttgaaatgtactgaactgtacttctctttgctcgaaaagcgtggt--g
ttgctggttgtggaggctgcctgcgtggccagtc-ggcgaccggtttgtctgctgcggcg
tttaatggaggagtgttcgattcgcggtatggttggcttcggctgaacaggc-gcttatt
gtat-gcttttcctgctgtggcg--tgatgggctggtgaaccgtagctgtgtgtggcttg
gcttttgaa--tcggctttgctgttgcgaagtagagtggcgg----------cttcggc-
-----------tgtcgagtgtcgatccattttgggaacgttt-gtgtgcgctt
>Phytophthora_citrophthora_IMI332632_AF266785 Phytophthora_citrophthora_IMI332632_AF266785 895 bp 
ccacacct-aaaaaactttccacgtgaaccgtatcaacccttttagttgggggtg-----
---------------------ttgcttggcgtttttgctgagccacgccctatcatggcg
aatg-tttggacttc--ggtctgggctagtagcttttttgttttaaacccatt-taacaa
tactgattatactgtggggacgaaagtctctgcttttaactagatagcaactttcagcag
tggatgtctaggctcgcacatcgatgaagaacgctgcgaactgcgatacgtaatgcgaat
tgcaggattcagtgagtcatcgaaattttgaacgcatattgcacttccgggttagtcctg
ggagtatgcctgtatcagtgtccgtacatcaaacttggctttcttccttccgtgtagtcg
gtgga---ggatgtgccagatgtgaagtgtcttgcggt--ttttgtgccttcgggccgtg
gctgcgagtcctttgaaatgtactgaactgtacttctctttgctcgaaaagcgtggt--g
ttgctggttgtggaggctgcctgcgtggccagtc-ggcgaccggtttgtctgctgcggcg
tttaatggaggagtgttcgattcgcggtatggttggcttcggctgaacaggc-gcttatt
gtat-gcttttcctgctgtggcg--tgatgggctggtgaaccgtagctgtgtgtggcttg
gcttttgaa--tcggctttgctgttgcgaagtagagtggcgg----------cttcggc-
-----------tgtcgagtgtcgatccattttgggaacgttt-gtgtgcgctt
>Phytophthora_colocasiae_9177_AY251657 Phytophthora_colocasiae_9177_AY251657 895 bp 
ccacacct-aaaaaactttccacgtgaaccgtatcaacccttttagttgggggtg-----
---------------------ttgcttggca-ttttgctgag--gcgccctatcatggcg
aatg-tttggacttc--ggtctgggctagtagc-tttttgttttaaa-ccctt-taacaa
tactgattatactgtggggacgaaagtctctgcttttaactagatagcaactttcagcag
tggatgtctaggctcgcacatcgatgaagaacgctgcgaactgcgatacgtaatgcgaat
tgcaggattcagtgagtcatcgaaattttgaacgcatattgcacttccgggttagtcctg
ggagtatgcctgtatcagtgtccgtacatcaaacttggctttcttccttccgtgtagtcg
gtgga---ggatgtgccagatgtgaagtgtcttgcggt--ttgtgtgccttcgggccgag
gctgcgagtcctttgaaatgtactgaactgtacttctctttgctcgaaaagcgtggt--g
atgctggttgtggaggctgcctgcgtggccagtc-ggcgaccggtttgtctgctgcggcg
tttaatggaggagtgttcgattcgcggtatggttggcttcggctgaacagac-gcttatt
gtat-gcttttcctgctgtggcg--tgatgggctggtgaaccgtagctgtgtgtggcttg
gcttttgaa--tcggttttgctgttgcgaagtagagtggcgg----------cttcggc-
-----------tgtcgagtgtcgatccattttgggaactttt-gtgtgcgctt
>Phytophthora_colocasiae_IMI368918_AF266786 Phytophthora_colocasiae_IMI368918_AF266786 895 bp 
ccacacct-aaaaaactttccacgtgaaccgtatcaacccttttagttgggggtg-----
---------------------ttgcttggca-ttttgctgag--gcgccctatcatggcg
aatg-tttggacttc--ggtctgggctagtagc-tttttgttttaaa-ccctt-taacaa
tactgattatactgtggggacgaaagtctctgcttttaactagatagcaactttcagcag
tggatgtctaggctcgcacatcgatgaagaacgctgcgaactgcgatacgtaatgcgaat
tgcaggattcagtgagtcatcgaaattttgaacgcatattgcacttccgggttagtcctg
ggagtatgcctgtatcagtgtccgtacatcaaacttggctttcttccttccgtgtagtcg
gtgga---ggatgtgccagatgtgaagtgtcttgcggt--ttgtgtgccttcgggccgag
gctgcgagtcctttgaaatgtactgaactgtacttctctttgctcgaaaagcgtggt--g
atgctggttgtggaggctgcctgcgtggccagtc-ggcgaccggtttgtctgctgcggcg
tttaatggaggagtgttcgattcgcggtatggttggcttcggctgaacagac-gcttatt
gtat-gcttttcctgctgtggcg--tgatgggctggtgaaccgtagctgtgtgtggcttg
gcttttgaa--tcggctttgctgttgcgaagtagagtggcgg----------cttcggc-
-----------tgtcgagtgtcgatccattttgggaactttt-gtgtgcgctt
>Phytophthora_cryptogea_CRP235_AY659443 Phytophthora_cryptogea_CRP235_AY659443 895 bp 
ccacacct-aaaaaactttccacgtgaaccgtatcaacctttttaaattgggggctcccg
tctggccggccggttttcggctggctgggtgg------------cggctctatcatggcg
accg-cttgggcctc--ggcctgggctagtagc--gtattttttaaacccatt-cctaat
tactgaatatactgtggggacgaaagtctctgcttttaactagatagcaactttcagcag
tggatgtctaggctcgcacatcgatgaagaacgctgcgaactgcgatacgtaatgcgaat
tgcaggattcagtgagtcatcgaaattttgaacgcatattgcacttccgggttagtcctg
ggagtatgcctgtatcagtgtccgtacactaaacttggctcccttccttccgtgtagtcg
gtggatggggacgcg-cagatgtgaagtgtcttgcggc--tggt----cttcggtccgg-
-ctgcgagtcctttgaaatgtactacactgtacttctctttgctcgaaaagcgtgac--g
ttgctggttgtggaggctgcctgtgtggcatgtc-ggcgaccggtttgtctgctgcggcg
tttaatggaggagtgttcgattcgcggtatgattggcttcggctgaacagac-gcttatt
gggt-gcttttcctgctgtggct--ggatggactggtgaaccgtagctgtgctaggcttg
gcgtttgaa--ccggcggtg-tggtgcgaagtagggtgtctg----------ttccggcg
caagctggggtggacgagggtcgatcca-tttgggaaacgtt-gtgtgcgctt
>Phytophthora_fallax_NZFS446_DQ297397 Phytophthora_fallax_NZFS446_DQ297397 895 bp 
ccacaccttaaaaaa--ttccacgtgaactgtattgtcaaccaaattcggggattccttg
ct----agcgtgccttcgggcgtgccggtaggtt----------gagacccatca-aacg
aaaa-catcggctgaaaggtcggagccagtagt--tacctttgtaaacccttt-actaaa
tactgaa-aaactgtggggacgaaagtccttgctttt-actagatagcaactttcagcag
tggatgtctaggctcgcacatcgatgaagaacgctgcgaactgcgatacgtaatgcgaat
tgcaggattcagtgagtcatcgaaattttgaacgcatattgcacttccgggttatgcctg
gaagtatgcctgtatcagtgtccgtatatcaaacttgccttccttccttccgtgtagtcg
gtggatgggaacgtg-cagatgtgaagtgtcttggcggcgtcgc------ttcggcggtg
ctggcgagtccttttaaatacaagatactgttcttctctttgctcgaaaagcgtgtg--g
gatgtggttgtggaggctgcctgcgtggccagtc-ggcgactgattt-cgtgctgagacg
----gtggggaggggcttgattcgcggtatggttggcttcggctgaacttct-gcttatt
gggc-ttctttcatgtcttggcgtatgcgatttcggtgtaccgtagctgtgtgtggcttg
gcttttgaa---ccgtgttctgtgtgcgaagtagagtgggca----tgtggttttcggac
tgcgtggccg-----aggggacgagaccttttgggaaattgt-gctgctactt
>Phytophthora_multivora_CBS124094_FJ237517 Phytophthora_multivora_CBS124094_FJ237517 895 bp 
ccacacctaaaaaaactttccacgtgaaccgtatcaaccctttcagttgggggcc-----
---------------------ttgc-tt----ttttgc------gagccctatcatggcg
aatg-tttggacttc--ggtctgggctagtagc-tttttgttttaaacccatt-ctacaa
tactgattatactgtggggacgaaagtctctgcttttaactagatagcaactttcagcag
tggatgtctaggctcgcacatcgatgaagaacgctgcgaactgcgatacgtaatgcgaat
tgcaggattcagtgagtcatcgaaattttgaacgcatattgcacttccgggttagtcctg
ggagtatgcctgtatcagtgtccgtacatcaaacttggctttcttccttccgtgtagtcg
gtgga---ggatgtgccagatgtgaagtgtcttgcagg---tgt---ccttcgggtcgt-
-ctgcgagtcctttgaaatgtactgaactgtacttctctttgctcgaaaagcgtggc--g
ttgctggttgtggaggctgcctgcgtggccagtc-ggcgaccggtttgtctgctgcggcg
tttaatggaggagtgttcgattcgcggtatggttggcttcggctgaacaggc-gcttatt
gtat-gcttttcctgctgtggcg--tgatggactggtgaaccgtagctgtgtgtggcttg
gcttttgaa--tcggctttgctgttgcgaagtagagtggcgg----------ctccggc-
-----------tgtcgagggtcgatcca-tttgggaac-ttt-gtgtgcacct
>Phytophthora_multivora_CBS124095_FJ237521 Phytophthora_multivora_CBS124095_FJ237521 895 bp 
ccacacctaaaaaaactttccacgtgaaccgtatcaaccctttcagttgggggcc-----
---------------------ttgc-tt----ttttgc------gagccctatcatggcg
aatg-tttggacttc--ggtctgggctagtagc-tttttgttttaaacccatt-ctacaa
tactgattatactgtggggacgaaagtctctgcttttaactagatagcaactttcagcag
tggatgtctaggctcgcacatcgatgaagaacgctgcgaactgcgatacgtaatgcgaat
tgcaggattcagtgagtcatcgaaattttgaacgcatattgcacttccgggttagtcctg
ggagtatgcctgtatcagtgtccgtacatcaaacttggctttcttccttccgtgtagtcg
gtgga---ggatgtgccagatgtgaagtgtcttgcagg---tgt---ccttcgggtcgt-
-ctgcgagtcctttgaaatgtactgaactgtacttctctttgctcgaaaagcgtggc--g
ttgctggttgtggaggctgcctgcgtggccagtc-ggcgaccggtttgtctgctgcggcg
tttaatggaggagtgttcgattcgcggtatggttggcttcggctgaacaggc-gcttatt
gtat-gcttttcctgctgtggcg--tgatggactggtgaaccgtagctgtgtgtggcttg
gcttttgaa--tcggctttgctgttgcgaagtagagtggcgg----------ctccggc-
-----------tgtcgagggtcgatcca-tttgggaac-ttt-gtgtgcacct
>Phytophthora_multivora_P1817_AB367494 Phytophthora_multivora_P1817_AB367494 895 bp 
ccacacct-aaaaaactttccacgtgaaccgtatcaaccctttcagttgggggcc-----
---------------------ttgc-tt----ttttgc------gagccctatcatggcg
aatg-tttggacttc--ggtctgggctagtagc-tttttgttttaaacccatt-ctacaa
tactgattatactgtggggacgaaagtctctgcttttaactagatagcaactttcagcag
tggatgtctaggctcgcacatcgatgaagaacgctgcgaactgcgatacgtaatgcgaat
tgcaggattcagtgagtcatcgaaattttgaacgcatattgcacttccgggttagtcctg
ggagtatgcctgtatcagtgtccgtacatcaaacttggctttcttccttccgtgtagtcg
gtgga---ggatgtgccagatgtgaagtgtcttgcagg---tgt---ccttcgggtcgt-
-ctgcgagtcctttgaaatgtactgaactgtacttctctttgctcgaaaagcgtggc--g
ttgctggttgtggaggctgcctgcgtggccagtc-ggcgaccggtttgtctgctgcggcg
tttaatggaggagtgttcgattcgcggtatggttggcttcggctgaacaggc-gcttatt
gtat-gcttttcctgctgtggcg--tgacggactggtgaaccgtagctgtgtgtggcttg
gcttttgaa--tcggctttgctgttgcgaagtagagtggcgg----------ctccggc-
-----------tgtcgagggtcgatcca-tttgggaac-ttt-gtgtgcacct
>Phytophthora_multivora_VHS16168_FJ237513 Phytophthora_multivora_VHS16168_FJ237513 895 bp 
ccacacct-aaaaaactttccacgtgaaccgtatcaaccctttcagttgggggcc-----
---------------------ttgc-tt----ttttgc------gagccctatcatggcg
aatg-tttggacttc--ggtctgggctagtagc-tttttgttttaaacccatt-ctacaa
tactgattatactgtggggacgaaagtctctgcttttaactagatagcaactttcagcag
tggatgtctaggctcgcacatcgatgaagaacgctgcgaactgcgatacgtaatgcgaat
tgcaggattcagtgagtcatcgaaattttgaacgcatattgcacttccgggttagtcctg
ggagtatgcctgtatcagtgtccgtacatcaaacttggctttcttccttccgtgtagtcg
gtgga---ggatgtgccagatgtgaagtgtcttgcagg---tgt---ccttcgggtcgt-
-ctgcgagtcctttgaaatgtactgaactgtacttctctttgctcgaaaagcgtggc--g
ttgctggttgtggaggctgcctgcgtggccagtc-ggcgaccggtttgtctgctgcggcg
tttaatggaggagtgttcgattcgcggtatggttggcttcggctgaacaggc-gcttatt
gtat-gcttttcctgctgtggcg--tgatggactggtgaaccgtagctgtgtgtggcttg
gcttttgaa--tcggctttgctgttgcgaagtagagtggcgg----------ctccggc-
-----------tgtcgagggtcgatcca-tttgggaac-ttt-gtgtgcacct
>Phytophthora_multivora_VHS16439_FJ237516 Phytophthora_multivora_VHS16439_FJ237516 895 bp 
ccacacctaaaaaaactttccacgtgaaccgtatcaaccctttcagttgggggcc-----
---------------------ttgc-tt----ttttgc------gagccctatcatggcg
aatg-tttggacttc--ggtctgggctagtagc-tttttgttttaaacccatt-ctacaa
tactgattatactgtggggacgaaagtctctgcttttaactagatagcaactttcagcag
tggatgtctaggctcgcacatcgatgaagaacgctgcgaactgcgatacgtaatgcgaat
tgcaggattcagtgagtcatcgaaattttgaacgcatattgcacttccgggttagtcctg
ggagtatgcctgtatcagtgtccgtacatcaaacttggctttcttccttccgtgtagtcg
gtgga---ggatgtgccagatgtgaagtgtcttgcagg---tgt---ccttcgggtcgt-
-ctgcgagtcctttgaaatgtactgaactgtacttctctttgctcgaaaagcgtggc--g
ttgctggttgtggaggctgcctgcgtggccagtc-ggcgaccggtttgtctgctgcggcg
tttaatggaggagtgttcgattcgcggtatggttggcttcggctgaacaggc-gcttatt
gtat-gcttttcctgctgtggcg--tgatggactggtgaaccgtagctgtgtgtggcttg
gcttttgaa--tcggctttgctgttgcgaagtagagtggcgg----------ctccggc-
-----------tgtcgagggtcgatcca-tttgggaac-ttt-gtgtgcacct
>Phytophthora_multivora_WAC13200_FJ237522 Phytophthora_multivora_WAC13200_FJ237522 895 bp 
ccacacctaaaaaaactttccacgtgaaccgtatcaaccctttcagttgggggcc-----
---------------------ttgc-tt----ttttgc------gagccctatcatggcg
aatg-tttggacttc--ggtctgggctagtagc-tttttgttttaaacccatt-ctacaa
tactgattatactgtggggacgaaagtctctgcttttaactagatagcaactttcagcag
tggatgtctaggctcgcacatcgatgaagaacgctgcgaactgcgatacgtaatgcgaat
tgcaggattcagtgagtcatcgaaattttgaacgcatattgcacttccgggttagtcctg
ggagtatgcctgtatcagtgtccgtacatcaaacttggctttcttccttccgtgtagtcg
gtgga---ggatgtgccagatgtgaagtgtcttgcagg---tgt---ccttcgggtcgt-
-ctgcgagtcctttgaaatgtactgaactgtacttctctttgctcgaaaagcgtggc--g
ttgctggttgtggaggctgcctgcgtggccagtc-ggcgaccggtttgtctgctgcggcg
tttaatggaggagtgttcgattcgcggtatggttggcttcggctgaacaggc-gcttatt
gtat-gcttttcctgctgtggcg--tgatggactggtgaaccgtagctgtgtgtggcttg
gcttttgaa--tcggctttgctgttgcgaagtagagtggcgg----------ctccggc-
-----------tgtcgagggtcgatcca-tttgggaac-ttt-gtgtgcacct
>Phytophthora_multivora_WAC13204_FJ237518 Phytophthora_multivora_WAC13204_FJ237518 895 bp 
ccacacctaaaaaaactttccacgtgaaccgtatcaaccctttcagttgggggcc-----
---------------------ttgc-tt----ttttgc------gagccctatcatggcg
aatg-tttggacttc--ggtctgggctagtagc-tttttgttttaaacccatt-ctacaa
tactgattatactgtggggacgaaagtctctgcttttaactagatagcaactttcagcag
tggatgtctaggctcgcacatcgatgaagaacgctgcgaactgcgatacgtaatgcgaat
tgcaggattcagtgagtcatcgaaattttgaacgcatattgcacttccgggttagtcctg
ggagtatgcctgtatcagtgtccgtacatcaaacttggctttcttccttccgtgtagtcg
gtgga---ggatgtgccagatgtgaagtgtcttgcagg---tgt---ccttcgggtcgt-
-ctgcgagtcctttgaaatgtactgaactgtacttctctttgctcgaaaagcgtggc--g
ttgctggttgtggaggctgcctgcgtggccagtc-ggcgaccggtttgtctgctgcggcg
tttaatggaggagtgttcgattcgcggtatggttggcttcggctgaacaggc-gcttatt
gtat-gcttttcctgctgtggcg--tgatggactggtgaaccgtagctgtgtgtggcttg
gcttttgaa--tcggctttgctgttgcgaagtagagtggcgg----------ctccggc-
-----------tgtcgagggtcgatcca-tttgggaac-ttt-gtgtgcacct
>Phytophthora_palmivora_TARS8_DQ987922 Phytophthora_palmivora_TARS8_DQ987922 895 bp 
ccacacct--aaaaactttccacgtgaaccgtatcaa-aa-cttagttgggggtctcttt
cggcggcggctgctggcttcattgctggcggctgctgttggga-gagctctatcatggcg
agcg-tttgggcttc--ggtctgaactagtagc-----ttttttaaacccatt-ctttat
aactgattatactgtagggacgaaagtctctgcttttaactagatagcaactttcagcag
tggatgtctaggctcgcacatcgatgaagaacgctgcgaactgcgatacgtaatgcgaat
tgcaggattcagtgagtcatcgaaattttgaacgcatattgcacttccgggttagtcctg
ggagtatgcctgtatcagtgtccgtacatcaaacttggttttcttccttccgtgtagtcg
gtggt---ggatgtgccagatgtgaagtgtcttgcggc--tggt----cttcggatcgg-
-ctgtgagtcctttgaaatgtactgaactgtacttctctttgctccaaaagcgtggc--g
ttgctgattgtggaggctgcttgcgtagccagtctggcgaccagtttgtctgctgtggcg
-ttaatggaggagtgttcgattcgcggtatggttggcttcggctgaacagac-gcttatt
gaat-atttcttcagctgtggtg--gtat-gattggtgaaccgtagctatgtg-agcttg
gcttttgaa--ttggctttgctgttgcgaagtagagtggcgg----------cttcggc-
-----------tgtcgagggtcgatcca-tttgggaac--tt-gtgtatgctt
>Phytophthora_palmivora_UQ1294_AF266780 Phytophthora_palmivora_UQ1294_AF266780 895 bp 
ccacacct-aaaaaactttccacgtgaaccgtatcaa-aa-cttatttgggggtctcttt
cggcggcggctgctggcttcattgctggcggctgctgttggga-gagctctatcatggcg
agcg-tttgggcttc--ggtctgaactagtagc-----ttttttaaacccatt-ctttat
aactgattatactgtagggacgaaagtctctgcttttaactagatagcaactttcagcag
tggatgtctaggctcgcacatcgatgaagaacgctgcgaactgcgatacgtaatgcgaat
tgcaggattcagtgagtcatcgaaattttgaacgcatattgcacttccgggttagtcctg
ggagtatgcctgtatcagtgtccgtacatcaaacttggttttcttccttccgtgtagtcg
gtggt---ggatgtgccagatgtgaagtgtcttgcggc--tggt----cttcggatcgg-
-ctgtgagtcctttgaaatgtactgaactgtacttctctttgctccaaaagcgtggc--g
ttgctgattgtggaggctgcttgcgtagccagtctggcgaccagtttgtctgctgtggcg
-ttaatggaggagtgttcgattcgcggtatggttggcttcggctgaacagac-gcttatt
gaat-atttcttcagctgtggtg--gtat-gattggtgaaccgtagctatgtg-agcttg
gcttttgaa--ttggctttgctgttgcgaagtagagtggcgg----------cttcggc-
-----------tgtcgagggtcgatcca-tttgggaac--tt-gtgtatgctt
>Phytophthora_plurivora_CBS124087_FJ665226 Phytophthora_plurivora_CBS124087_FJ665226 895 bp 
ccacacct-aaaaaacttttcacgtgaaccgtatcaacccttttagttgggggtc-----
---------------------ttgcttt----ttttgc------gagccctatcatggcg
aatg-tttggacttc--ggtctgggctagtagc-tttttgttttaaacccatt-ctacaa
tactgattatactgcggggacgaaagtctctgcttttaactagatagcaactttcagcag
tggatgtctaggctcgcacatcgatgaagaacgctgcgaactgcgatacgtaatgcgaat
tgcaggattcagtgagtcatcgaaattttgaacgcatattgcacttccgggttagtcctg
ggagtatgcctgtatcagtgtccgtacatcaaacttggctttcttccttccgtgtagtcg
gtgga---ggatgtgccagacgtgaagtgtcttgcggg---tgt---ccttcgggtcgt-
-ctgcgagtcctttgaaatgtactgaactgtacttctctttgctcgaaaagcgtggt--g
ttgctggttgtggaggctgcctgcgtggccagtc-ggcgaccggtttgtctgctgcggcg
tttaatggaggagtgttcgattcgcggtatggttggcttcggctgaacaggc-gcttatt
gtat-gcttttcctgctgtggcg--tgatgggctggtgaaccgtagctgtgtgtggcttg
gcttttgaa--tcggctttgctgttgcgaagtagagtggcgg----------cttcggc-
-----------tgtcgagggtcgatcca-tttgggaac-ttt-gtgtgcacct
>Phytophthora_plurivora_CBS124089_FJ665227 Phytophthora_plurivora_CBS124089_FJ665227 895 bp 
ccacacct-aaaaaacttttcacgtgaaccgtatcaacccttttagttgggggtc-----
---------------------ttgcttt----ttttgc------gagccctatcatggcg
aatg-tttggacttc--ggtctgggctagtagc-tttttgttttaaacccatt-ctacaa
tactgattatactgcggggacgaaagtctctgcttttaactagatagcaactttcagcag
tggatgtctaggctcgcacatcgatgaagaacgctgcgaactgcgatacgtaatgcgaat
tgcaggattcagtgagtcatcgaaattttgaacgcatattgcacttccgggttagtcctg
ggagtatgcctgtatcagtgtccgtacatcatacttggctttcttccttccgtgtagtcg
gtgga---ggatgtgccagacgtgaagtgtcttgcggg---tgt---ccttcgggtcgt-
-ctgcgagtcctttgaaatgtactgaactgtacttctctttgctcgaaaagcgtggt--g
ttgctggttgtggaggctgcctgcgtggccagtc-ggcgaccggtttgtctgctgcggcg
tttaatggaggagtgttcgattcgcggtatggttggcttcggctgaacaggc-gcttatt
gtat-gcttttcctgctgtggcg--tgatgggctggtgaaccgtagctgtgtgtggcttg
gcttttgaa--tcggctttgctgttgcgaagtagagtggcgg----------cttcggc-
-----------tgtcgagggtcgatcca-tttgggaac-ttt-gtgtgcacct
>Phytophthora_plurivora_CBS124091_FJ665229 Phytophthora_plurivora_CBS124091_FJ665229 895 bp 
ccacacct-aaaaaacttttcacgtgaaccgtatcaacccttttagttgggggtc-----
---------------------ttgcttt----ttttgc------gagccctatcatggcg
aatg-tttggacttc--ggtctgggctagtagc-tttttgttttaaacccatt-ctacaa
tactgattatactgcggggacgaaagtctctgcttttaactagatagcaactttcagcag
tggatgtctaggctcgcacatcgatgaagaacgctgcgaactgcgatacgtaatgcgaat
tgcaggattcagtgagtcatcgaaattttgaacgcatattgcacttccgggttagtcctg
ggagtatgcctgtatcagtgtccgtacatcaaacttggctttcttccttccgtgtagtcg
gtgga---ggatgtgccagacgtgaagtgtcttgcggg---tgt---ccttcgggtcgt-
-ctgcgagtcctttgaaatgtactgaactgtacttctctttgctcgaaaagcgtggt--g
ttgctggttgtggaggctgcctgcgtggccagtc-ggcgaccggtttgtctgctgcggcg
tttaatggaggagtgttcgattcgcggtatggttggcttcggctgaacaggc-gcttatt
gtat-gcttttcctgctgtggcg--tgatgggctggtgaaccgtagctgtgtgtggcttg
gcttttgaa--tcggctttgctgttgcgaagtagagtggcgg----------cttcggc-
-----------tgtcgagggtcgatcca-tttgggaac-ttt-gtgtgcacct
>Phytophthora_plurivora_CBS124092_FJ665233 Phytophthora_plurivora_CBS124092_FJ665233 895 bp 
ccacacct-aaaaaacttttcacgtgaaccgtatcaacccttttagttgggggtc-----
---------------------ttgcttt----ttttgc------gagccctatcatggcg
aatg-tttggacttc--ggtctgggctagtagc-tttttgttttaaacccatt-ctacaa
tactgattatactgcggggacgaaagtctctgcttttaactagatagcaactttcagcag
tggatgtctaggctcgcacatcgatgaagaacgctgcgaactgcgatacgtaatgcgaat
tgcaggattcagtgagtcatcgaaattttgaacgcatattgcacttccgggttagtcctg
ggagtatgcctgtatcagtgtccgtacatcaaacttggctttcttccttccgtgtagtcg
gtgga---ggatgtgccagacgtgaagtgtcttgcggg---tgt---ccttcgggtcgt-
-ctgcgagtcctttgaaatgtactgaactgtacttctctttgctcgaaaagcgtggt--g
ttgctggttgtggaggctgcctgcgtggccagtc-ggcgaccggtttgtctgctgcggcg
tttaatggaggagtgttcgattcgcggtatggttggcttcggctgaacaggc-gcttatt
gtat-gcttttcctgctgtggcg--tgatgggctggtgaaccgtagctgtgtgtggcttg
gcttttgaa--tcggctttgctgttgcgaagtagagtggcgg----------cttcggc-
-----------tgtcgagggtcgatcca-tttgggaac-ttt-gtgtgcacct
>Phytophthora_plurivora_CBS124093_FJ665225 Phytophthora_plurivora_CBS124093_FJ665225 895 bp 
ccacacct-aaaaaacttttcacgtgaaccgtatcaacccttttagttgggggtc-----
---------------------ttgcttt----ttttgc------gagccctatcatggcg
aatg-tttggacttc--ggtctgggctagtagc-tttttgttttaaacccatt-ctacaa
tactgattatactgcggggacgaaagtctctgcttttaactagatagcaactttcagcag
tggatgtctaggctcgcacatcgatgaagaacgctgcgaactgcgatacgtaatgcgaat
tgcaggattcagtgagtcatcgaaattttgaacgcatattgcacttccgggttagtcctg
ggagtatgcctgtatcagtgtccgtacatcaaacttggctttcttccttccgtgtagtcg
gtgga---ggatgtgccagacgtgaagtgtcttgcggg---tgt---ccttcgggtcgt-
-ctgcgagtcctttgaaatgtactgaactgtacttctctttgctcgaaaagcgtggt--g
ttgctggttgtggaggctgcctgcgtggccagtc-ggcgaccggtttgtctgctgcggcg
tttaatggaggagtgttcgattcgcggtatggttggcttcggctgaacaggc-gcttatt
gtat-gcttttcctgctgtggcg--tgatgggctggtgaaccgtagctgtgtgtggcttg
gcttttgaa--tcggctttgctgttgcgaagtagagtggcgg----------cttcggc-
-----------tgtcgagggtcgatcca-tttgggaac-ttt-gtgtgcacct
>Phytophthora_plurivora_IMI342898_AF266789 Phytophthora_plurivora_IMI342898_AF266789 895 bp 
ccacacct--aaaaacttttcacgtgaaccgtatcaacccttttagttgggggtc-----
---------------------ttgcttt----ttttgc------gagccctatcatggcg
aatg-tttggacttc--ggtctgggctagtagc-tttttgttttaaacccatt-ctacaa
tactgattatactgcggggacgaaagtctctgcttttaactagatagcaactttcagcag
tggatgtctaggctcgcacatcgatgaagaacgctgcgaactgcgatacgtaatgcgaat
tgcaggattcagtgagtcatcgaaattttgaacgcatattgcacttccgggttagtcctg
ggagtatgcctgtatcagtgtccgtacatcaaacttggctttcttccttccgtgtagtcg
gtgga---ggatgtgccagacgtgaagtgtcttgcggg---tgt---ccttcgggtcgt-
-ctgcgagtcctttgaaatgtactgaactgtacttctctttgctcgaaaagcgtggt--g
ttgctggttgtggaggctgcctgcgtggccagtc-ggcgaccggtttgtctgctgcggcg
tttaatggaggagtgttcgattcgcggtatggttggcttcggctgaacaggc-gcttatt
gtat-gcttttcctgctgtggcg--tgatgggctggtgaaccgtagctgtgtgtggcttg
gcttttgaa--tcggctttgctgttgcgaagtagagtggcgg----------cttcggc-
-----------tgtcgagggtcgatcca-tttgggaac-ttt-gtgtgcacct
>Phytophthora_plurivora_InfGaul_AY879291 Phytophthora_plurivora_InfGaul_AY879291 895 bp 
ccccacct-aaaaaacttttcacgtgaaccgtatcaacccttttagttgggggtc-----
---------------------ttgcttt----ttttgc------gagccctatcatggcg
aatg-tttggacttc--ggtctgggctagtagc-tttttgttttaaacccatt-ctacaa
tactgattatactgcggggacgaaagtctctgcttttaactagatagcaactttcagcag
tggatgtctaggctcgcacatcgatgaagaacgctgcgaactgcgatacgtaatgcgaat
tgcaggattcagtgagtcatcgaaattttgaacgcatattgcacttccgggttagtcctg
ggagtatgcctgtatcagtgtccgtacatcaaacttggctttcttccttccgtgtagtcg
gtgga---ggatgtgccagacgtgaagtgtcttgcggg---tgt---ccttcgggtcgt-
-ctgcgagtcctttgaaatgtactgaactgtacttctctttgctcgaaaagcgtggt--g
ttgctggttgtggaggctgcctgcgtggccagtc-ggcgaccggtttgtctgctgcggcg
tttaatggaggagtgttcgattcgcggtatggttggcttcggctgaacaggc-gcttatt
gtat-gcttttcctgctgtggcg--tgatgggctggtgaaccgtagctgtgtgtggcttg
gcttttgaa--tcggctttgctgttgcgaagtagagtggcgg----------cttcggc-
-----------tgtcgagggtcgatcca-tttgggaac-taa-gtgtgcacct
>Phytophthora_plurivora_MN21HH_DQ486661 Phytophthora_plurivora_MN21HH_DQ486661 895 bp 
ccacacct-aaaaaacttttcacgtgaaccgtatcaacccttttagttgggggtc-----
---------------------ttgcttt----ttttgc------gagccctatcatggcg
aatg-tttggacttc--ggtctgggctagtagc-tttttgttttaaacccatt-ctacaa
tactgattatactgcggggacgaaagtctctgcttttaactagatagcaactttcagcag
tggatgtctaggctcgcacatcgatgaagaacgctgcgaactgcgatacgtaatgcgaat
tgcaggattcagtgagtcatcgaaattttgaacgcatattgcacttccgggttagtcctg
ggagtatgcctgtatcagtgtccgtacatcaaacttggctttcttccttccgtgtagtcg
gtgga---ggatgtgccagacgtgaagtgtcttgcggg---tgt---ccttcgggtcgt-
-ctgcgagtcctttgaaatgtactgaactgtacttctctttgctcgaaaagcgtggt--g
ttgctggttgtggaggctgcctgcgtggccagtc-ggcgaccggtttgtctgctgcggcg
tttaatggaggagtgttcgattcgcggtatggttggcttcggctgaacaggc-gcttatt
gtat-gcttttcctgctgtggcg--tgatgggctggtgaaccgtagctgtgtgtggcttg
gcttttgaa--tcggctttgctgttgcgaagtagagtggcgg----------cttcggc-
-----------tgtcgagggtcgatcca-tttgggaac-ttt-gtgtgcacct
>Phytophthora_plurivora_PLU255_FJ665232 Phytophthora_plurivora_PLU255_FJ665232 895 bp 
ccacacct-aaaaaacttttcacgtgaaccgtatcaacccttttagttgggggtc-----
---------------------ttgcttt----ttttgc------gagccctatcatggcg
aatg-tttggacttc--ggtctgggctagtagc-tttttgttttaaacccatt-ctacaa
tactgattatactgcggggacgaaagtctctgcttttaactagatagcaactttcagcag
tggatgtctaggctcgcacatcgatgaagaacgctgcgaactgcgatacgtaatgcgaat
tgcaggattcagtgagtcatcgaaattttgaacgcatattgcacttccgggttagtcctg
ggagtatgcctgtatcagtgtccgtacatcaaacttggctttcttccttccgtgtagtcg
gtgga---ggatgtgccagacgtgaagtgtcttgcggg---tgt---ccttcgggtcgt-
-ctgcgagtcctttgaaatgtactgaactgtacttctctttgctcgaaaagcgtggt--g
ttgctggttgtggaggctgcctgcgtggccagtc-ggcgaccggtttgtctgctgcggcg
tttaatggaggagtgttcgattcgcggtatggttggcttcggctgaacaggc-gcttatt
gtat-gcttttcctgctgtggcg--tgatgggctggtgaaccgtagctgtgtgtggcttg
gcttttgaa--tcggctttgctgttgcgaagtagagtggcgg----------cttcggc-
-----------tgtcgagggtcgatcca-tttgggaac-ttt-gtgtgcacct
>Phytophthora_plurivora_PLU35_FJ237524 Phytophthora_plurivora_PLU35_FJ237524 895 bp 
ccacacct-aaaaaacttttcacgtgaaccgtatcaacccttttagttgggggtc-----
---------------------ttgcttt----ttttgc------gagccctatcatggcg
aatg-tttggacttc--ggtctgggctagtagc-tttttgttttaaacccatt-ctacaa
tactgattatactgcggggacgaaagtctctgcttttaactagatagcaactttcagcag
tggatgtctaggctcgcacatcgatgaagaacgctgcgaactgcgatacgtaatgcgaat
tgcaggattcagtgagtcatcgaaattttgaacgcatattgcacttccgggttagtcctg
ggagtatgcctgtatcagtgtccgtacatcaaacttggctttcttccttccgtgtagtcg
gtgga---ggatgtgccagacgtgaagtgtcttgcggg---tgt---ccttcgggtcgt-
-ctgcgagtcctttgaaatgtactgaactgtacttctctttgctcgaaaagcgtggt--g
ttgctggttgtggaggctgcctgcgtggccagtc-ggcgaccggtttgtctgctgcggcg
tttaatggaggagtgttcgattcgcggtatggttggcttcggctgaacaggc-gcttatt
gtat-gcttttcctgctgtggcg--tgatgggctggtgaaccgtagctgtgtgtggcttg
gcttttgaa--tcggctttgctgttgcgaagtagagtggcgg----------cttcggc-
-----------tgtcgagggtcgatcca-tttgggaac-ttt-gtgtgcacct
>Phytophthora_plurivora_PLU36_FJ665228 Phytophthora_plurivora_PLU36_FJ665228 895 bp 
ccacacct-aaaaaacttttcacgtgaaccgtatcaacccttttagttgggggtc-----
---------------------ttgcttt----ttttgc------gagccctatcatggcg
aatg-tttggacttc--ggtctgggctagtagc-tttttgttttaaacccatt-ctacaa
tactgattatactgcggggacgaaagtctctgcttttaactagatagcaactttcagcag
tggatgtctaggctcgcacatcgatgaagaacgctgcgaactgcgatacgtaatgcgaat
tgcaggattcagtgagtcatcgaaattttgaacgcatattgcacttccgggttagtcctg
ggagtatgcctgtatcagtgtccgtacatcaaacttggctttcttccttccgtgtagtcg
gtgga---ggatgtgccagacgtgaagtgtcttgcggg---tgt---ccttcgggtcgt-
-ctgcgagtcctttgaaatgtactgaactgtacttctctttgctcgaaaagcgtggt--g
ttgctggttgtggaggctgcctgcgtggccagtc-ggcgaccggtttgtctgctgcggcg
tttaatggaggagtgttcgattcgcggtatggttggcttcggctgaacaggc-gcttatt
gtat-gcttttcctgctgtggcg--tgatgggctggtgaaccgtagctgtgtgtggcttg
gcttttgaa--tcggctttgctgttgcgaagtagagtggcgg----------cttcggc-
-----------tgtcgagggtcgatcca-tttgggaac-ttt-gtgtgcacct
>Phytophthora_plurivora_PLU7_AJ007370 Phytophthora_plurivora_PLU7_AJ007370 895 bp 
ccacacct-aaaaaacttttcacgtgaaccgtatcaacccttttagttgggggtc-----
---------------------ttgcttt----ttttgc------gagccctatcatggcg
aatg-tttggacttc--ggtctgggctagtagc-tttttgttttaaacccatt-ctacaa
tactgattatactgcggggacgaaagtctctgcttttaactagatagcaactttcagcag
tggatgtctaggctcgcacatcgatgaagaacgctgcgaactgcgatacgtaatgcgaat
tgcaggattcagtgagtcatcgaaattttgaacgcatatcgcacttccgggttagtcctg
ggagtatgcctgtatcagtgtccgtacatcaaacttggctttcttccttccgtgtagtcg
gtgga---ggatgtgccagacgtgaagtgtcttgcggg---tgt---ccttcgggtcgt-
-ctgcgagtcctttgaaatgtactgaactgtacttctctttgctcgaaaagcgtggt--g
ttgctggttgtggaggctgcctgcgtggccagtc-ggcgaccggtttgtctgctgcggcg
tttaatggaggagtgttcgattcgcggtatggttggcttcggctgaacaggc-gcttatt
gtat-gcttttcctgctgtggcg--tgatgggctggtgaaccgtagctgtgtgtggcttg
gcttttgaa--tcggctttgctgttgcgaagtagagtggcgg----------cttcggc-
-----------tgtcgagggtcgatcca-tttgggaac-ttt-gtgtgcacct
>Phytophthora_plurivora_PLU77_FJ665230 Phytophthora_plurivora_PLU77_FJ665230 895 bp 
ccacacct-aaaaaacttttcacgtgaaccgtatcaacccttttagttgggggtc-----
---------------------ttgcttt----ttttgc------gagccctatcatggcg
aatg-tttggacttc--ggtctgggctagtagc-tttttgttttaaacccatt-ctacaa
tactgattatactgcggggacgaaagtctctgcttttaactagatagcaactttcagcag
tggatgtctaggctcgcacatcgatgaagaacgctgcgaactgcgatacgtaatgcgaat
tgcaggattcagtgagtcatcgaaattttgaacgcatattgcacttccgggttagtcctg
ggagtatgcctgtatcagtgtccgtacatcaaacttggctttcttccttccgtgtagtcg
gtgga---ggatgtgccagacgtgaagtgtcttgcggg---tgt---ccttcgggtcgt-
-ctgcgagtcctttgaaatgtactgaactgtacttctctttgctcgaaaagcgtggt--g
ttgctggttgtggaggctgcctgcgtggccagtc-ggcgaccggtttgtctgctgcggcg
tttaatggaggagtgttcgattcgcggtatggttggcttcggctgaacaggc-gcttatt
gtat-gcttttcctgctgtggcg--tgatgggctggtgaaccgtagctgtgtgtggcttg
gcttttgaa--tcggctttgctgttgcgaagtagagtggcgg----------cttcggc-
-----------tgtcgagggtcgatcca-tttgggaac-ttt-gtgtgcacct
>Phytophthora_plurivora_PLU9_FJ237523 Phytophthora_plurivora_PLU9_FJ237523 895 bp 
ccacacct-aaaaaacttttcacgtgaaccgtatcaacccttttagttgggggtc-----
---------------------ttgcttt----ttttgc------gagccctatcatggcg
aatg-tttggacttc--ggtctgggctagtagc-tttttgttttaaacccatt-ctacaa
tactgattatactgcggggacgaaagtctctgcttttaactagatagcaactttcagcag
tggatgtctaggctcgcacatcgatgaagaacgctgcgaactgcgatacgtaatgcgaat
tgcaggattcagtgagtcatcgaaattttgaacgcatattgcacttccgggttagtcctg
ggagtatgcctgtatcagtgtccgtacatcaaacttggctttcttccttccgtgtagtcg
gtgga---ggatgtgccagacgtgaagtgtcttgcggg---tgt---ccttcgggtcgt-
-ctgcgagtcctttgaaatgtactgaactgtacttctctttgctcgaaaagcgtggt--g
ttgctggttgtggaggctgcctgcgtggccagtc-ggcgaccggtttgtctgctgcggcg
tttaatggaggagtgttcgattcgcggtatggttggcttcggctgaacaggc-gcttatt
gtat-gcttttcctgctgtggcg--tgatgggctggtgaaccgtagctgtgtgtggcttg
gcttttgaa--tcggctttgctgttgcgaagtagagtggcgg----------cttcggc-
-----------tgtcgagggtcgatcca-tttgggaac-ttt-gtgtgcacct
>Phytophthora_plurivora_PLU92_FJ665231 Phytophthora_plurivora_PLU92_FJ665231 895 bp 
ccacacct-aaaaaacttttcacgtgaaccgtatcaacccttttagttgggggtc-----
---------------------ttgcttt----ttttgc------gagccctatcatggcg
aatg-tttggacttc--ggtctgggctagtagc-tttttgttttaaacccatt-ctacaa
tactgattatactgcggggacgaaagtctctgcttttaactagatagcaactttcagcag
tggatgtctaggctcgcacatcgatgaagaacgctgcgaactgcgatacgtaatgcgaat
tgcaggattcagtgagtcatcgaaattttgaacgcatattgcacttccgggttagtcctg
ggagtatgcctgtatcagtgtccgtacatcatacttggctttcttccttccgtgtagtcg
gtgga---ggatgtgccagacgtgaagtgtcttgcggg---tgt---ccttcgggtcgt-
-ctgcgagtcctttgaaatgtactgaactgtacttctctttgctcgaaaagcgtggt--g
ttgctggttgtggaggctgcctgcgtggccagtc-ggcgaccggtttgtctgctgcggcg
tttaatggaggagtgttcgattcgcggtatggttggcttcggctgaacaggc-gcttatt
gtat-gcttttcctgctgtggcg--tgatgggctggtgaaccgtagctgtgtgtggcttg
gcttttgaa--tcggctttgctgttgcgaagtagagtggcgg----------cttcggc-
-----------tgtcgagggtcgatcca-tttgggaac-ttt-gtgtgcacct
>Phytophthora_quercetorum_MND4_EF539180 Phytophthora_quercetorum_MND4_EF539180 895 bp 
ccacacct-aaaaaactttccacgtgaaccgtatcaa-ac-tttagttgggggtcttttt
cggcgacggctgctggcttcattgctggcggctgctgttggat-gagccctatcatggcg
agcg-tttgggcttc--ggtctgaactagtagc-----ttttttaaacccatt-ctttat
tactgattatactgtggggacgaaagtctctgcttttaactagatagcaactttcagcag
tggatgtctaggctcgcacatcgatgaagaacgctgcgaactgcgatacgtaatgcgaat
tgcaggattcagtgagtcatcgaaattttgaacgcatattgcacttccgggttagtcctg
ggagtatgcctgtatcagtgtccgtacatcaaacttggctttcttccttccgtgtagtcg
gtgga---ggatgtgccagatgtgaagtgtcttgcggc--tggt----cttcgggtcgg-
-ctgtgagtcctttgaaatgtactgaactgtacttctctttgctcgaaaagcgtggc--g
ttgctgattgtggaggctgcctgcgtagccagtctggcgaccagtttgtctgctgtggcg
-ttaatggaggagtgttcgattcgcggtatggttggcttcggctgaacagac-gcttatt
gaat-gtttttcctgctgtggcg--gtacgggttggtgaaccgtagctatgtg-ggcttg
gcttttgaa--ttggctttgctgttgcgaagtagagtggcag----------cttcggc-
-----------tgtcgagggtcgatcca-tttgggaat--tt-gtgtgtactt
>Phytophthora_quercetorum_WI111_EF539179 Phytophthora_quercetorum_WI111_EF539179 895 bp 
ccacacct-aaaaaactttccacgtgaaccgtatcaa-ac-tttagttgggggtcttttt
cggcgacggctgctggcttcattgctggcggctgctgttggat-gagccctatcatggcg
agcg-tttgggcttc--ggtctgaactagtagc-----ttttttaaacccatt-ctttat
tactgattatactgtggggacgaaagtctctgcttttaactagatagcaactttcagcag
tggatgtctaggctcgcacatcgatgaagaacgctgcgaactgcgatacgtaatgcgaat
tgcaggattcagtgagtcatcgaaattttgaacgcatattgcacttccgggttagtcctg
ggagtatgcctgtatcagtgtccgtacatcaaacttggctttcttccttccgtgtagtcg
gtgga---ggatgtgccagatgtgaagtgtcttgcggc--tggt----cttcgggtcgg-
-ctgtgagtcctttgaaatgtactgaactgtacttctctttgctcgaaaagcgtggc--g
ttgctgattgtggaggctgcctgcgtagccagtctggcgaccagtttgtctgctgtggcg
-ttaatggaggagtgttcgattcgcggtatggttggcttcggctgaacagac-gcttatt
gaat-gtttttcctgctgtggcg--gtacgggttggtgaaccgtagctatgtg-ggcttg
gcttttgaa--ttggctttgctgttgcgaagtagagtggcag----------cttcggc-
-----------tgtcgagggtcgatcca-tttgggaat--tt-gtgtgtactt
>Phytophthora_sp__1_DDS1221_EU593265 Phytophthora_sp._1_DDS1221_EU593265 895 bp 
ccacacct-aaaaaactttccacgtgaaccgtatcaa-ac-tttagttgggggtcttttt
cggcgacggctgctggcttcattgctggcggctgctgttgaat-gagccctatcatggcg
agcg-tttaggcttc--ggtctgaactagtagc-----ttttttaaacccatt-ctttat
tactgattatactgtggggacgaaagtctctgcttttaactagatagcaactttcagcag
tggatgtctaggctcgcacatcgatgaagaacgctgcgaactgcgatacgtaatgcgaat
tgcaggattcagtgagtcatcgaaattttgaacgcatattgcacttccgggttagtcctg
ggagtatgcctgtatcagtgtccgtacatcaaacttggctttcttccttccgtgtagtcg
gtgga---agatgtgccagatgtgaagtgtcttgcggc--tggt----cttcgggtcgg-
-ctgtgagtcctttgaaatgtactgaactgtacttctctttgctcgaaaagcgtggc--g
ttgctgattgtggaggctgcctgcgtagccagtctggcgaccagtttgtctgctgtggcg
-ttaatggaggagtgttcgattcgcggtatggttggctttggctgaacagac-gcttatt
gaat-gtttttcctgctatggcg--gtacgggttggtgaaccgtagctatgtg-ggcttg
gcttttgaa--ttggctttgctgttgcgaagtagagtggcgg----------cttcggc-
-----------tgtcgagggtcgatcca-tttgggaat--tt-gtgtgtactt
>Phytophthora_sp__1_VHS9861_EU301118 Phytophthora_sp._1_VHS9861_EU301118 895 bp 
ccacacct-aaaaaactttccacgtgaaccgtatcaa-ac-tttagttgggggtcttttt
cggcgacggctgctggcttcattgctggcggctgctgttgaat-gagccctatcatggcg
agcg-tttaggcttc--ggtctgaactagtagc-----ttttttaaacccatt-ctttat
tactgattatactgtggggacgaaagtctctgcttttaactagatagcaactttcagcag
tggatgtctaggctcgcacatcgatgaagaacgctgcgaactgcgatacgtaatgcgaat
tgcaggattcagtgagtcatcgaaattttgaacgcatattgcacttccgggttagtcctg
ggagtatgcctgtatcagtgtccgtacatcaaacttggctttcttccttccgtgtagtcg
gtgga---agatgtgccagatgtgaagtgtcttgcggc--tggt----cttcgggtcgg-
-ctgtgagtcctttgaaatgtactgaactgtacttctctttgctcgaaaagcgtggc--g
ttgctgattgtggaggctgcctgcgtagccagtctggcgaccagtttgtctgctgtggcg
-ttaatggaggagtgttcgattcgcggtatggttggctttggctgaacagac-gcttatt
gaat-gtttttcctgctatggcg--gtacgggttggtgaaccgtagctatgtg-ggcttg
gcttttgaa--ttggctttgctgttgcgaagtagagtggcgg----------cttcggc-
-----------tgtcgagggtcgatcca-tttgggaat--tt-gtgtgtactt
>Phytophthora_sp__DAR34210_L41375 Phytophthora_sp._DAR34210_L41375 895 bp 
ccacacct-aaaaaactttccacgtgaaccgtttcaaccctttcagttgggggcc-----
---------------------ttgc-tt----ttttgc------gagccctatcatggcg
aatg-tttggacttc--ggtctgggctagtagc-tttttgttttaaacccatt-ctacaa
tactgattatactgtggggacgaaagtctctgcttttaactagataacaactttcagcag
tggatgtctaggctcgcacatcgatgaagaacgctgcgaactgcgatacgtaatgcgaat
tgcaggattcagtgagtcatcgaaatttggaacgcatattgcactcccgggttagtcctg
ggagtatgcctgtatcagtgtccgtacatcaaacttggctttctccctcccgtgtagtcg
gtgga---ggatgtgccagatgtgaagtgtcttgcagg---tgt---ccttcgggtcgt-
-ctgcgagtcctttgaaatgtactgaactgtacttctctttgctcgaaaagcgtggc--g
ttgctggttgtggaggctgcctgcgtggccagtc-ggcgaccggtttgtctgctgcggcg
tttaatggaggagtgttcgattcgcggtatggttggcttcggctgaacaggc-gcttatt
gtat-gcttttcctgctgtggcg--tgatggactggtgaaccgtagctgtgtgtggcttg
gcttttgaa--tcggctttgctgttgcgaagtagagtggcgg----------ctccggc-
-----------tgtcgagggtcgatcca-tttgggaac-ttt-gtgtgcacct
>Phytophthora_sp__P4242_AY946259 Phytophthora_sp._P4242_AY946259 895 bp 
ccacacct-aaaaaactttccacgtgaaccgtttcaaccctttcagttgggggcc-----
---------------------ttgc-tt----ttttgc------gagccctatcatggcg
aatg-tttggacttc--ggtctgggctagtagc-tttttgttttaaacccatt-ctacaa
tactgattatactgtggggacgaaagtctctgcttttaactagataacaactttcagcag
tggatgtctaggctcgcacatcgatgaagaacgctgcgaactgcgatacgtaatgcgaat
tgcaggattcagtgagtcatcgaaatttggaacgcatattgcactcccgggttagtcctg
ggagtatgcctgtatcagtgtccgtacatcaaacttggctttctccctcccgtgtagtcg
gtgga---ggatgtgccagatgtgaagtgtcttgcagg---tgt---ccttcgggtcgt-
-ctgcgagtcctttgaaatgtactgaactgtacttctctttgctcgaaaagcgtggc--g
ttgctggttgtggaggctgcctgcgtggccagtc-ggcgaccggtttgtctgctgcggcg
tttaatggaggagtgttcgattcgcggtatggttggcttcggctgaacaggc-gcttatt
gtat-gcttttcctgctgtggcg--tgatggactggtgaaccgtagctgtgtgtggcttg
gcttttgaa--tcggctttgctgttgcgaagtagagtggcgg----------ctccggc-
-----------tgtcgagggtcgatcca-tttgggaac-ttt-gtgtgcacct
>Phytophthora_tropicalis_H213_AY207010 Phytophthora_tropicalis_H213_AY207010 895 bp 
ccacacct-aaaaaactttccacgtgaaccgtatcgacccttttagttgggggtc-----
---------------------ttgt---------------------accctatcatggcg
aatg-tttggacttc--ggtctgggcgagtagc-tttttgttttaaacccatt-tctcaa
tactgattatactgcggggacgaaagtctctgcttttaactagatagcaactttcagcag
tggatgtctaggctcgcacatcgatgaagaacgctgcgaactgcgatacgtaatgcgaat
tgcaggattcagtgagtcatcgaaattttgaacgcatattgcacttccgggttagtcctg
ggagtatgcctgtatcagtgtccgtacatcaaacttggctttcttccttccgtgtagtcg
gtgga---ggatgtgccagatgtgaagtgtcttgcggt--ttgt---ccttcgggtcgg-
-ctgcgagtccttttaaatgtactgaactgtacttctctttgctcgaaaagcgtggt--g
ttgctggttgtggaggctgcctgcgtggccagtc-ggcgaccggtttgtctgctgcggcg
tttaatggaggagtgttcgattcgcggtatggttggcttcggctgaacaggc-gcttatt
gtat-gcttttcctgctgtggcg--tgatgggctggtgaaccgtagctgtgtgtggcttg
gcttttgaa--tcggctttgctgttgcgaagtagagtggcgg----------cttcggc-
-----------tgtcgagggtcgatccattttgggaac-ttt-gtgtgcactt
>Phytophthora_tropicalis_P4742_AY946257 Phytophthora_tropicalis_P4742_AY946257 895 bp 
ccacacct-aaaaaactttccacgtgaaccgtatcgacccttttagttgggggtc-----
---------------------ttgt---------------------accctatcatggcg
aatg-tttggacttc--ggtctgggcgagtagc-tttttgttttaaacccatt-tctcaa
tactgattatactgcggggacgaaagtctctgcttttaactagatagcaactttcagcag
tggatgtctaggctcgcacatcgatgaagaacgctgcgaactgcgatacgtaatgcgaat
tgcaggattcagtgagtcatcgaaattttgaacgcatattgcacttccgggttagtcctg
ggagtatgcctgtatcagtgtccgtacatcaaacttggctttcttccttccgtgtagtcg
gtgga---ggatgtgccagatgtgaagtgtcttgcggt--ttgt---ccttcgggtcgg-
-ctgcgagtccttttaaatgtactgaactgtacttctctttgctcgaaaagcgtggt--g
ttgctggttgtggaggctgcctgcgtggccagtc-ggcgaccggtttgtctgctgcggcg
tttaatggaggagtgttcgattcgcggtatggttggcttcggctgaacaggc-gcttatt
gtat-gcttttcctgctgtggcg--tgatgggctggtgaaccgtagctgtgtgtggcttg
gcttttgaa--tcggctttgctgttgcgaagtagagtggcgg----------cttcggc-
-----------tgtcgagggtcgatccattttgggaac-ttt-gtgtgcactt
>END; 1 bp 
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------------n
>nameless_1 1 bp 
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------------n
>nameless_2 1 bp 
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------------n
>nameless_3 1 bp 
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------------n
