>Eteone_picta 1369 bp 
aggtttccgtaggtgaacctgcggaaggatcattatcgaaac------------------
--------------------------------------------gagaacgaaagttgca
aactttgaacgctaaatcctcg--------------tcccccgcgagccgctgcccctcc
acatcc----------------cgccctataacttcgcggcggg-tg---------cggt
tcgtgcgagcggacgaggtggccccggcccccct----taggcgctat------------
----------------------------------cgctgcgaggatcg------------
-----------------------ttcctctcactcacgactcgtggcggccggggatgtg
ttgccgg----------cgtccgtcaaaccccactc------------ttaccatgcg--
-------aagggggt-accgcgctcccgtcccctctccgggagatagctactgt---gcc
tcgaggtgaatcggtttaaagcggcgcgactgccctactactgtcgtcctctcccgtcgc
ccgccccgcttcgcatctgtgcctcctccatactgtcacg-----------agaacctta
cgaaacgccgctccccgtgcgaatgttgcccgcgcgtgcggacgtggctccaaaccaaag
tcggcgaaggaaccctctcggggacccgagtcgcga--caaactactctaagcggtggat
cactcggctcgtgcgtcgatgaagagcgcagccagctgcgtgaactaatgtgaattgcag
gacacattgaacatcgacatcttgaacgcatattgcggcatcggctcaaaccgttgccac
gcctgtctcagggtcggttcactagcaatcg-ctccgcgttcctcctcgcggca------
---------gcgccttgag--ccgtcgtagtccctccgccagggggggctccgtcgctcc
aagtgcagaccggttacgc------gtcctccgttcgtccccctac------ccgttcgg
aaaaagacgcggccggc----------------------ctctctcacg----tcccgct
cgcggtctcgcggcct----------ccggacggcggcttg------gcttcctctgctc
gcctccgg----------------------------------------------------
------------ttcccgctcgggacccaacc---------------------gtggact
cctcctatgaga------gagagcgcccggctaagccgaccaacccttcgtcgttcctcc
gaacg-------------------tcgaaaaaccactc---tgtcgacctgagatcagac
gagact
>Notophyllum_crypticum_spm_11 1372 bp 
aggtttccgtaggtgaacctgcggaaggatcattatcgaaactgac--------------
-------------------------ccagatggtttcagatgagagg-----aaagtccg
ag----gaaactcgatttctcggcggcggtgccag-tgcctcgggag-cgcagtctctcg
gcacgccagggcatcgtggcggcgtcccatggctcgggg-taggcta---------cgga
tcttagtgggagatccgccgaccccggttcgctcggaaggggcgccag------------
----------------------------------tgatctaaaaattgaaacagcagtgc
ggggtacctgtcctgggg--aaggccctcc---atattccccggggtgagcaccgttggc
gcgcgcc----------tgccc-ttactcggcgcga------------tcgtcgtgcgac
ggttcaaagaggcgg-accacagtcatc-tt-cctcacagtmgacctcatatgt---ggc
ggagggtg-atttatcccacccggcgagtccgccccgc-attgcga-cccct--------
-cgctt-gcgagggttttgttttccccacgaactgttacc-aattgtgtgaaccatatta
cgaagc----ttgcgcgtccgtccgttgcccgggcgt-----cgcaaggccaaactttat
tttccaaag----cctctacgaggtgagtacgaaaag-aaaactactctaagcggtggat
cactcggctcgtgtgtcgatgaagagcgcagccagctgcgtgaattaatgtgaattgcag
gacacattgaacatcgatatcttgaacgcatattgcggcatcggcttccaccgatgccac
gcctgtctcagggtcggtttactatctatcgcccccgcgctcctctcggtagcaatgcgg
a-ttcgtgggcgccttgggttttcacgcagcgcttc--------ggtgctccgcggccct
aagtgcagaccggtctccc-aaaaagttgattgttcg-----------------------
-----gggacggctcgtcccgatcgccagctctgtgtg-atttttctcgacgctcgccct
caagagctcgtggcacagcccgtg-gtcggacggtggctcg------gctt-ctttgctc
gcctccgcccgggttcctcgagt-ttataagccgtcgaaaaaacaaccagc--agcgagt
gcctcggac-tttttcgacttcggaccgaacc---------------------ggtgact
cggtttaaccaa------tagcacg-----------------------tgtcctcc----
gggat-------------------acgtgcgatcactc---tgtcgacctgagatcagac
gagact
>Notophyllum_crypticum_spm_12 1369 bp 
aggtttccgtaggtgaacctgcggaaggatcattatcgaaactgac--------------
-------------------------ccagatggtttcagatgagagg-----aaagtccg
ag----gaaactcgatttctcggcggcggtgccag-tgcctcgggag-cgcagtctctcg
gcacgccagggcatcgtggcggcgtcccatggctcgggg-taggcta---------cgga
tcttagtgggagatccgccgaccccggttcgctcggaaggggcgccag------------
----------------------------------tgatctaaaaattgaaacagcagtgc
ggggtacctgtcctgggg--aaggccctcc---atattccccggggtgagcaccgttggc
gcgcgcc----------tgccc-ttactcggcgcga------------tcgtcgtgcgac
ggttcaaagaggcgg-accacagtcatc-tt-cctcacagtcgacctcatatgt---ggc
ggagggtg-atttatcccacccggcgagtccgccccgc-attgcga-cccct--------
-cgctt-gcgagggttttgttttccccacgaactgttacc-aattgtgtgaaccatatta
cgaagc----ttgcgcgtccgtccgttgcccgggcgt-----cgcaaggccaaactttat
tttccaaag----cctctacgaggtgagtacgaaaag-aaaactactctaagcggtggat
cactcggctcgtgtgtcgatgaagagcgcagccagctgcgtgaattaatgtgaattgcag
gacacattgaacatcgatatcttgaacgcatattgcggcatcggcttccaccgatgccac
gcctgtctcagggtcggtttactatctatcgcccccgcgctcctctcggtagcaatgcgg
a-ttcgtgggcgccttgggttttcacgcagcgcttc--------ggtgctccgcggccct
aagtgcagaccggtctccc-aaaaagttgattgttcg-----------------------
-----gggacggctcgtcccgatcgccagctctgtgtg-atttttctcgacgctcgccct
caagagctcgtggcacagcccgtg-gtcggacggtggctcg------gctt-ctttgctc
gcctccgcccgggttcctcgagt-ttataagccgtcgaaaaaacaaccagc--agcgagt
gcctcggac-tttttcgacttcggaccgaacc---------------------ggtgact
cggtttaaccaa------tagcacg-----------------------tgtcctcc----
gggat-------------------acgtgcgatcactc---tgtcgacctgagatcagac
gagact
>Notophyllum_crypticum_spm_13 1369 bp 
aggtttccgtaggtgaacctgcggaaggatcattatcgaaactgac--------------
-------------------------ccagatggtttcagatgagagg-----aaagtccg
ag----gaaactcgatttctcggcggcggtgccag-tgcctcgggag-cgcagtctctcg
gcacgccagggcatcgtggcggcgtcccatggctcgggg-taggcta---------cgga
tcttagtgggagatccgccgaccccggttcgctcggaaggggcgccag------------
----------------------------------tgatctaaaaattgaaacagcagtgc
ggggtacctgtcctgggg--aaggccctcc---atattccccggggtgagcaccgttggc
gcgcgcc----------tgccc-ttactcggcgcga------------tcgtcgtgcgac
ggttcaaagaggcgg-accacagtcatc-tt-cctcacagtcgacctcatatgt---ggc
ggagggtg-atttatcccacccggcgagtccgccccgc-attgcgaccccct--------
-cgctt-gcgagggttttgttttccccacgaactgttacc-aattgtgtgaaccatatta
cgaagc----ttgcgcgtccgtccgttgcccgggcgt-----cgcaaggccaaactttat
tttccaaag----cctctacgaggtgagtacgaaaag-aaaactactctaagcggtggat
cactcggctcgtgtgtcgatgaagagcgcagccagctgcgtgaattaatgtgaattgcag
gacacattgaacatcgatatcttgaacgcatattgcggcatcggcttccaccgatgccac
gcctgtctcagggtcggtttactatctatcgcccccgcgctcctctcggtagcaatgcgg
a-ttcgtgggcgccttgggttttcacgcagcgcttc--------ggtgctccgcggccct
aagtgcagaccggtctccc-aaaaagttgattgttcg-----------------------
-----gggacggctcgtcccgatcgccagctctgtgtg-atttttctcgacgctcgccct
caagagctcgtggcacagcccgtg-gtcggacggtggctcg------gctt-ctttgctc
gcctccgcccgggttcctcgagt-ttataagccgtcgaaaaaacaaccagc--agcgagt
gcctcggac-tttttcgacttcggaccgaacc---------------------ggtgact
cggtttaaccaa------tagcacg-----------------------tgtcctcc----
gggat-------------------acgtgcgatcactc---tgtcgacctgagatcagac
gagact
>Notophyllum_crypticum_spm_14 1369 bp 
aggtttccgtaggtgaacctgcggaaggatcattatcgaaactgac--------------
-------------------------ccagatggtttcagatgagaggagtgaaaagtccg
ag----gaaactcgatttctcggcggcggtgccagttgcctcgggag-cgcagtctctcg
gcacgccagggcatcgtggcggcgtcccatggctcggggttaggcta---------cgga
tcttagtgggagatccgccgaccccggttcgctcggaaggggcgccag------------
----------------------------------tgatctaaaaattgaaacagcagtgc
ggggtacctgtcccgggg--aaggccctcga--taattccccggggtgagcaccgttggc
gcgcgcc----------tgccc-ttactcggcgcga------------tcgtcgtgcgac
ggttcaaagaggcgg-accacagtcccc-ttccctcacagcagacctcatatgt---ggc
ggagggtg-atttatcccacccggcgagtccgccccgc-attgcga-cccct--------
-cgctt-gcgagggttttgttttccccacgaactgttacc-aattgtgtgaaccatatta
cgaagc----ttgcgcgtccgtccgttgcccgggcgt-----cgcaaggccaaactttat
tttccaaag----cctctacgaggtgagtacgaaaag-aaaactactctaagcggtggat
cactcggctcgtgtgtcgatgaagagcgcagccagctgcgtgaattaatgtgaattgcag
gacacattgaacatcgatatcttgaacgcatattgcggcatcggcttccaccgatgccac
gcctgtctcagggtcggtttactatctatcgcccccgcgctcctctcggtagcaatgcgg
a-ttcgtgggcgccttgggttttcacgcagcgcttc--------ggtgctccgcggccct
aagtgcagaccggtctccc-aaaaagttgattgttcg-----------------------
-----gggacggctcgtcccgatcgccagctctgtgtg-atttttctcgacgctcgccct
caagagctcgtggcacagcccgtg-gtcggacggtggctcg------gctt-ctttgctc
gcctccgcccgggttcctcgagt-ttataagccgtcgaaaaaacaaccagc--agtgagt
gcctcggacttttttcgacttcggaccgaacc---------------------ggtgact
cggtttaaccaa------tagcacg-----------------------tgtcctcc----
gggat-------------------acgtgcgatcactc---tgtcgacctgagatcagac
gagact
>Notophyllum_crypticum_spm_15 1369 bp 
aggtttccgtaggtgaacctgcggaaggatcattatcgaaactgac--------------
-------------------------ccagatggtttcagatgagaggagtgaaaagtccg
ag----gaaactcgatttctcggcggcggtgccag-tgcctcgggag-cgcagtctctcg
gcacgccagggcatcgtggcggcgtcccatggctcggggttaggcta---------cgga
tcttagtgggagatccgccgaccccggttcgctcggaaggggcgccag------------
----------------------------------tgatctaaaaattgaaacagcagtgc
ggggtacctgtcccgggg--aaggccctcga--taattccccggggtgagcaccgttggc
gcgcgcc----------tgccc-ttactcggcgcga------------tcgtcgtgcgac
ggttcaaagaggcgg-accacagtcccc-ttccctcacagcagacctcatatgt---ggc
ggagggtg-atttatcccacccggcgagtccgccccgc-attgcga-cccct--------
-cgctt-gcgagggttttgttttccccacgaactgttacc-aattgtgtgaaccatatta
cgaagc----ttgcgcgtccgtccgttgcccgggcgt-----cgcaaggccaaactttat
tttccaaag----cctctacgaggtgagtacgaaaag-aaaactactctaagcggtggat
cactcggctcgtgtgtcgatgaagagcgcagccagctgcgtgaattaatgtgaattgcag
gacacattgaacatcgatatcttgaacgcatattgcggcatcggcttccaccgatgccac
gcctgtctcagggtcggtttactatctatcgcccccgcgctcctctaggtagcaatgcgg
a-ttcgtgggcgccttggg-tttcacgcagcgcttc--------ggtgctccgcggccct
aagtgcagaccggtctccc-aaaaagttgattgttcg-----------------------
-----gggacggctcgtcccgatcgccagctctgtgtgtttttttctcgacgctcgccct
caagagctcgtggcacagcccgtg-gtcggacggtggctcg------gctt-ctttgctc
gcctccgcccgggttcctcgagt---------cgtcagaaagaaatacaacggagtgagt
gcctcgaac-tttttcgacttcggaccgaacc---------------------ggtgact
cggtttaaccaa------tagcacg-----------------------tgtcctcc----
gggat-------------------acgtgcgatcactc---tgtcgacctgagatcagac
gagact
>Notophyllum_crypticum_spm_16 1369 bp 
aggtttccgtaggtgaacctgcggaaggatcattatcgaaactgac--------------
-------------------------ccagatggtttcagatgagaggagtgaaaagtccg
ag----gaaactcgatttctcggcggcggtgccag-tgcctcgggag-cgcagtctctcg
gcacgccagggcatcgtggcggcgtcccatggctcggggttaggcta---------cgga
tcttagtgggagatccgccgaccccggttcgctcggaaggggcgccag------------
----------------------------------tgatctaaaaattgaaacagcagtgc
ggggtacctgtcccgggg--aaggccctcga--taattccccggggtgagcaccgttggc
gcgcgcc----------tgccc-ttactcggcgcga------------tcgtcgtgcgac
ggttcaaagaggcgg-accacagtcccc-ttccctcacagcagacctcatatgt---ggc
ggagggtg-atttatcccacccggcgagtccgccccgc-attgcga-cccct--------
-cgctt-gcgagggttttgttttccccacgaactgttacc-aattgtgtgaaccatatta
cgaagc----ttgcgcgtccgtccgttgcccgggcgt-----cgcaaggccaaactttat
tttccaaag----cctctacgaggtgagtacgaaaag-aaaactactctaagcggtggat
cactcggctcgtgtgtcgatgaagagcgcagccagctgcgtgaattaatgtgaattgcag
gacacattgaacatcgatatcttgaacgcatattgcggcatcggcttccaccgatgccac
gcctgtctcagggtcggtttactatctatcgcccccgcgctcctctaggtagcaatgcgg
a-ttcgtgggcgccttggg-tttcacgcagcgcttc--------ggtgctccgcggccct
aagtgcagaccggtctccc-aaaaagttgattgttcg-----------------------
-----gggacggctcgtcccgatcgccagctctgtgtgtttttttctcgacgctcgccct
caagagctcgtggcacagcccgtg-gtcggacggtggctcg------gctt-ctttgctc
gcctccgcccgggttcctcgagt---------cgtcagaaagaaatacaacggagtgagt
gcctcgaac-tttttcgacttcggaccgaacc---------------------ggtgact
cggtttaaccaa------tagcacg-----------------------tgtcctcc----
gggat-------------------acgtgcgatcactc---tgtcgacctgagatcagac
gagact
>Notophyllum_crypticum_spm_17 1369 bp 
aggtttccgtaggtgaacctgcggaaggatcattatcgaaactgac--------------
-------------------------ccagatggtttcagatgagaggagtgaaaagtccg
ag----gaaactcgatttctcggcggcggtgccag-tgcctcgggag-cgcagtctctcg
gcacgccagggcatcgtggcggcgtcccatggctcggggttaggcta---------cgga
tcttagtgggagatccgccgaccccggttcgctcggaaggggcgccag------------
----------------------------------tgatctaaaaattgaaacagcagtgc
ggggtacctgtcccgggg--aaaggccctct--attttccccggggtgagcaccgttggc
gcgcgcc----------tgccc-ttactcggcgcga------------tcgtcgtgcgac
ggttcaaagaggcgg-accacagtcccc-ttccctcacagcagacctcatatgt---ggc
ggagggtt-atttatcccacccggcgagtccgccccgc-attgcga-cccct--------
-cgctt-gcgagggttttgttttccccacgaactgttacctaagtgtgtgaaccatatta
cgaagc----ttgcgcgtccgtccgttgcccgggcgt-----cgcaaggccaaactttat
tttccaaag----cctctccgaggtgagtacgaaaag-aaaactactctaagcggtggat
cactcggctcgtgtgtcgatgaagagcgcagccagctgcgtgaattaatgtgaattgcag
gacacattgaacatcgatatcttgaacgcatattgcggcatcggcttccaccgatgccac
gcctgtctcagggtcggtttactatctatcgcccccgcgctcctctcggtagcaatgcgg
a-ttcgtgggcgccttgggttttcacgcagcgcttc--------ggtgctccgcggccct
aagtgcagaccggtctccc-aaaaagttgattgttcg-----------------------
-----gggacggctcgtcccgatcgccagctctgtgtg-atttttctcgacgctcgccct
caagagctcgtggcacagcccgtg-gtcggacggtggctcg------gctt-ctttgctc
gcctccgcccgggttcctcgagt-ttataagccgtcgaaaaaacaaccagc--agtgagt
gcctcagac-tttttcgacttcggaccgaacc---------------------ggtgact
cggtttaaccaa------tagcacg-----------------------tgtcctcc----
gggat-------------------acgtgcgatcactc---tgtcgacctgagatcagac
gagact
>Notophyllum_foliosum_spm_1 1369 bp 
aggtttccgtaggtgaacctgcggaaggatcattatcgaaactgac--------------
-------------------------ccaaatggtttcaaatgtgtggaatg-aaagtccg
ag----gaaattcgcttcctcggcggcggtgccag-tgcctcgggag-cgcagtctcccg
gcacgccagggcatcgtggcggcgtcccatggctcggggtcaggcta---------cgga
tcttagtgggagattcgccgaccccggttcgctcggaaggggcgccag------------
----------------------------------tgatctaaaaattgaaacagcagtgc
ggggtacctgtcccggggaaaaggccctcta--tttttctccggggtgagcaccgttggc
gcgcgcc----------tgccctttactcggcgcga------------tcgtcgtgcgac
ggttcaaagaggcgg-accacagtcccccttccctcacggcagacctcagacgtggcggc
ggagggtg-atttatcccacccggcgagtccgccccgc-attgcga-cccct--------
-cgcttcgcgagggttttgttttccccacgaactgttaca-aagtgtgtgaaccatatta
cgaagc----ttgcgcgtccgtccgttgcccgggcgt-----cgcaaggccaaactttat
tttccaaag----cctcttcgaggtgagtacgaaaag-aaaactactctaagcggtggat
cactcggctcgtgtgtcgatgaagagcgcagccagctgcgtgaattaatgtgaattgcag
gacacattgaacatcgatatcttgaacgcatattgcggcatcggcttccaccgatgccac
gcctgtctcagggtcggtttactatctatcgcccccgcgctcctctcggtagcaatgcgg
atttcacgggcgccttggg-tttcacgcagcgcttc--------ggtgctccgcggccct
aagtgcagaccggtctcccaaaaaagttgattgttcg-----------------------
-----gggacggctcgt--------ccagctccgtgtg-ctttttctcgacgctcgccct
caaaagctcgtggcacagcccgtg-gtcggacggtggctcg------gctt-ctttgctc
gcctccggccgggttcctcgagatttataagtcgtcggaaataatac-aacggagtgagt
gcctcgaac-tgtttcgacttcggaccgaacc---------------------ggtgact
cggtttaaccaa------tagcacg-----------------------tgtcctcctccg
ggaag-------------------ccgtgcgatca-tc---tgtcgacctgagatcagac
gagact
>Notophyllum_foliosum_spm_10 1372 bp 
aggtttccgtaggtgaacctgcggaaggatcattatcgaaactgac--------------
-------------------------ccaaatggtttcaaatgtgtggaatg-aaagtccg
ag----gaaattcgcttcctcggcggcggtgccag-tgcctcgggag-cgcagtctctcg
gcacgccagggcatcgtggcggcgtcccatggctcggggtcaggcta---------cgga
tcttagtgggagattcgccgaccccggttcgctcggaaggggcgccag------------
----------------------------------tgatctaaaaattgaaacagcagtgc
ggggtacctgtcccggggaaaaggccctcta--tttttctccggggtgagcaccgttggc
gcgcgcc----------tgccctttacwcggcgcga------------tcgtcgtgcgac
ggttcaaagaggcgg-accacagtcccccttccctcacggcagacctcagacgtggcggc
ggagggtg-atttatcccacccggcgagtccgccccgc-attgcga-cccct--------
-cgcttcgcgagggttttgttttccccacgaactgttaca-aagtgtgtgaaccatatta
cgaagc----ttgcgcgtccgtccgttgcccgggcgt-----cgcaaggccaaactttat
tttccaaag----cctcttcgaggtgagtacgaaaag-aaaactactctaagcggtggat
cactcggctcgtgtgtcgatgaagagcgcagccagctgcgtgaattaatgtgaattgcag
gacacattgaacatcgatatcttgaacgcatattgcggcatcggcttccaccgatgccac
gcctgtctcagggtcggtttactatctatcgcccccgcgctcctctcggtagcaatgcgg
atttcacgggcgccttggg-tttcacgcagcgcttc--------ggtgctccgcggccct
aagtgcagaccggtctcccaaaaaagttgattgttcg-----------------------
-----gggacggctcgt--------ccagctctgtgtg-ctttttctcgacgctcgccct
cgaaagctcgtggcacagcccgtg-gtcggacggtggctcg------gctt-ctttgctc
gcctccggccgggttcctcgagatttataagtcgtcggaaataatac-aacggagtgagt
gcctcgaac-tttttcgacttcggaccgaacc---------------------ggtgact
cggtttaaccaa------tagcacg-----------------------tgtcctcctccg
ggaag-------------------ccgtgcgatcattc---tgtcgacctgagatcagac
gagact
>Notophyllum_foliosum_spm_2 1369 bp 
aggtttccgtaggtgaacctgcggaaggatcattatcgaaactgac--------------
-------------------------ccaaatggtttcaaatgtgtggaatg-gaagtccg
ag----gaaattcgcttcctcggcggcggtgccag-tgcctcgggag-cgcagtctctcg
gcacgccagggcatcgtggcggcgtcccatggctcggggtcaggcta---------cgga
tcttagtgggagattcgccgaccccggttcgctcggaaggggcgccag------------
----------------------------------tgatctaaaaattgaaacagcagtgc
ggggtacctgtcccgggg-aaaggccctcta--tttttctccggggtgagcaccgttggc
gcgcgcc----------tgccc-ttactcggcgcga------------tcgtcgtgcgac
ggttcaaagaggcgg-accacagtctcctttccctcacggcggacctcagacgt---ggc
ggagggtg-atttatcccacccggcgagtccgccccgc-attgcga-cccct--------
-cgcttcgcgagggttttgttttccccacgaactgttaca-aagtgtgtgaaccatatta
cgaagc----ttgcgcgtccgtccgttgcccgggcgt-----cgcaaggccaaactttat
tttccaaag----cctcttcgaggtgagtacgaaaag-aaaactactctaagcggtggat
cactcggctcgtgtgtcgatgaagagcgcagccagctgcgtgaattaatgtgaattgcag
gacacattgaacatcgatatcttgaacgcatattgcggcatcggcttccaccgatgccac
gcctgtctcagggtcggtttactatctatcgcccccgcgctcctctcggtagcaacgcgg
atttcacgggcgccttggg-tttcacgcagcgcttc--------ggtgctccgcggccct
aagtgcagaccggtctcccaaaaaagttgattgttcg-----------------------
-----gggacggctcgt--------ccagctccgtgtg-ctttttctcgacgctcgccct
caaaagctcgtggcacagcccgtg-gtcggacggtggctcg------gctt-ctttgctc
gcctccggccgggttcctcgaga-ttataagtcgtcggaaataacac-aacggagtgagt
gcctcgaac-tttttcgacttcggaccgaacc---------------------ggtgact
cggtttaaccaa------tagcacg-----------------------tgtcctcctccg
ggaag-------------------ccgtgcgatcattc---tgtcgacctgagatcagac
gagact
>Notophyllum_foliosum_spm_3 1378 bp 
aggtttccgtaggtgaacctgcggaaggatcattatcgaaactgac--------------
-------------------------ccaaatggtttcaaatgtgtggaatg-gaagtccg
ag----gaaattcgcttcctcggcggcggtgccag-tgcctcgggag-cgcagtctctcg
gcacgccagggcatcgtggcggcgtcccatggctcggggtcaggcta---------cgga
tcttagtgggagattcgccgaccccggttcgctcggaaggggcgccag------------
----------------------------------tgatctaaaaattgaaacagcagtgc
ggggtacctgtcccgggg-aaaggccctcta--tttttctccggggtgaacaccgttggc
gcgcgcc----------tgccc-ttactcggcgcga------------tcgtcgtgcgac
ggttcaaagaggcgg-accacagtcccctttccctcacggcagacctcagacgt---ggc
ggagggtg-atttatcccacccggcgagtccgccccgc-attgcga-cccct--------
-cgcttcgcgagggttttgttttccccacgaactgttaca-aagtgtgtgaaccatatta
cgaagc----ttgcgcgtccgtccgttgcccgggcgt-----cgcaaggccaaactttat
tttccaaag----cctcttcgaggtgagtacgaaaag-aaaactactctaagcggtggat
cactcggctcgtgtgtcgatgaagagcgcagccagctgcgtgaattaatgtgaattgcag
gacacattgaacatcgatatcttgaacgcatattgcggcatcggcttccaccgatgccac
gcctgtctcagggtcggtttactatctatcgcccccgcgctcctctcggtagcaaygcgg
atttcacgggcgccttggg-tttcacgcagcgcttc--------ggtgctccgcggccct
aagtgcagaccggtctcccaaaaaagttgattgttcg-----------------------
-----gggacggctcgt--------ccagctcygtgtg-ctttttctcgacgctcgccct
caaaagctcgtggcacagcccgtg-gtcggacggtggctcg------gctt-ctttgctc
gcctccggccgggttcctcgaga-ttataagtcgtcggaaataayac-aacggagtgagt
gcctcgaac-tttttcgacttcggaccgaacc---------------------ggtgact
cggtttaaccaa------tagcacg-----------------------tgtcctcctccg
ggaag-------------------ccgtgcgatcattc---tgtcgacctgagatcagac
gagact
>Notophyllum_foliosum_spm_4 1369 bp 
aggtttccgtaggtgaacctgcggaaggatcattatcgaaactgac--------------
-------------------------ccaaatggtttcaaatgtgtggaatg-aaagtccg
ag----gaaattcgcttcctcggcggcggtgccag-tgcctcgggag-cgcagtctctcg
gcacgccagggcatcgtggcggcgtcccatggctcggggtcaggcta---------cgga
tcttagtgggagattcgccgaccccggttcgctcggaaggggcgccag------------
----------------------------------tgatctaaaaattgaaacagcagtgc
ggggtacctgtcccggggaaaaggccctctatttttttctccggggtgagcaccgttggc
gcgcgcc----------tgccctttactcggcgcga------------tcgtcgtgcgac
ggttcaaagaggcgg-accacagtcccctttccctcacggcagacctcagacgt---ggc
ggagggtg-atttatcccacccggcgagtccgccccgc-attgcga-cccct--------
-cgcttcgcgagggttttgttttccccacgaactgttaca-aagtgtgtgaaccatatta
cgaagc----ttgcgcgtccgtccgttgcccgggcgt-----cgcaaggccaaactttat
tttccaaag----cctcttcgaggtgagtacgaaaag-aaaactactctaagcggtggat
cactcggctcgtgtgtcgatgaagagcgcagccagctgcgtgaattaatgtgaattgcag
gacacattgaacatcgatatcttgaacgcatattgcggcatcggcttccaccgatgccac
gcctgtctcagggtcggtttactatctatcgcccccgcgctcctctcggtagcaacgcgg
atttcatgggcgccttggg-tttcacgcagcgcttc--------ggtgctccgcggccct
aagtgcagaccggtctcccaaaaaagttgattgttcg-----------------------
-----gggacggctcgt--------ccagctccgtgtg-ctttttctcgacgctcgccct
caaaagctcgtggcacagcccgtg-gtcggacggtggctcg------gctt-ctttgctc
gcctccggccgggttcctcgaga-ttataagtcgtcggaaataatac-aacggagtgagt
gcctcgaac-tttttcgacttcggaccgaacc---------------------ggtgact
cggtttaaccaa------tagcacg-----------------------tgtcctcctccg
ggaag-------------------ccgtgcgatcattc---tgtcgacctgagatcagac
gagact
>Notophyllum_foliosum_spm_5 1372 bp 
aggtttccgtaggtgaacctgcggaaggatcattatcgaaactgac--------------
-------------------------ccaaatggtttcaaatgtgtggaatg-aaagtccg
ag----gaaattcgcttcctcggcggcggtgccag-tgcctcgggag-cgcagtctctcg
gcacgccagggcatcgtggcggcgtcccatggctcggggtcaggcta---------cgga
tcttagtgggagattcgccgaccccggttcgctcggaaggggcgccag------------
----------------------------------tgatctaaaaattgaaacagcagtgc
ggggtacctgtcccgggg-aaaggccctcta-ttttttctccggggtgagcaccgttggc
gcgcgcc----------tgccctttacwcggcgcga------------tcgtcgtgcgac
ggttcaaagaggcgg-accacagtcccctttccctcacggcagacctcagacgt---ggc
ggagggtg-atttatcccacccggcgagtccgccccgc-attgcga-cccct--------
-cgcttcgcgagggttttgttttccccacgaactgttaca-aagtgtgtgaaccatatta
cgaagc----ttgcgcgtccgtccgttgcccgggcgt-----cgcaaggccaaactttat
tttccaaag----cctcttcgaggtgagtacgaaaag-aaaactactctaagcggtggat
cactcggctcgtgtgtcgatgaagagcgcagccagctgcgtgaattaatgtgaattgcag
gacacattgaacatcgatatcttgaacgcatattgcggcatcggcttccaccgatgccac
gcctgtctcagggtcggtttactatctatcgcccccgcgctcctctcggtagcaacgcgg
atttcatgggcgccttggg-tttcacgcagcgcttc--------ggtgctccgcggccct
aagtgcagaccggtctcccaaaaaagttgattgttcg-----------------------
-----gggacggctcgt--------ccagctctgtgtg-ctttttctcgacgctcgccct
caaaagctcgtggcacagcccgtg-gtcggacggtggctcg------gctt-ctttgctc
gcctccggccgggttcctcgaga-ttataagtcgtcggaaataatac-aacggagtgagt
gcctcgaac-tttttcgacttcggaccgaacc---------------------ggtgact
cggtttaaccaa------tagcacg-----------------------tgtcctcctccg
ggaag-------------------ccgtgcgatcattc---tgtcgacctgagatcagac
gagact
>Notophyllum_foliosum_spm_6 1369 bp 
aggtttccgtaggtgaacctgcggaaggatcattatcgaaactgac--------------
-------------------------ccaaatggtttcaaatgtgtggaatg-aaagtccg
ag----gaaattcgcttcctcggcggcggtgccag-tgcctcgggag-cgcagtctctcg
gcacgccagggcatcgtggcggcgtcccatggctcggggtcaggcta---------cgga
tcttagtgggagattcgccgaccccggttcgctcggaaggggcgccag------------
----------------------------------tgatctaaaaattgaaacagcagtgc
ggggtacctgtcccggggaaaaggccctcta--tttttctccggggtgagcaccgttggc
gcgcgcc----------tgccctttactcggcgcga------------tcgtcgtgcgac
ggttcaaagaggcgg-accacagtcccccttccctcacggcagacctcagacgtggcggc
ggagggtg-atttatcccacccggcgagtccgccccgc-attgcga-cccct--------
-cgcttcgcgagggttttgttttccccacgaactgttaca-aagtgtgtgaaccatatta
cgaagc----ttgcgcgtccgtccgttgcccgggcgt-----cgcaaggccaaactttat
tttccaaag----cctcttcgaggtgagtacgaaaag-aaaactactctaagcggtggat
cactcggctcgtgtgtcgatgaagagcgcagccagctgcgtgaattaatgtgaattgcag
gacacattgaacatcgatatcttgaacgcatattgcggcatcggcttccaccgatgccac
gcctgtctcagggtcggtttactatctatcgcccccgcgctcctctcggtagcaatgcgg
atttcacgggcgccttggg-tttcacgcagcgcttc--------ggtgctccgcggccct
aagtgcagaccggtctcccaaaaaagttgattgttcg-----------------------
-----gggacggctcgt--------ccagctccgtgtg-ctttttctcgacgctcgccct
caaaagctcgtggcacagcccgtg-gtcggacggtggctcg------gctt-ctttgctc
gcctccggccgggttcctcgagatttataagtcgtcggaaataatacaaacggagtgagt
gcctcgaac-tttttcgacttcggaccgaacc---------------------ggtgact
cggtttaaccaa------tagcacg-----------------------tgtcctcctccg
ggaag-------------------ccgtgcgatcattc---tgtcgacctgagatcagac
gagact
>Notophyllum_foliosum_spm_7 1369 bp 
aggtttccgtaggtgaacctgcggaaggatcattatcgaaactgac--------------
-------------------------ccaaatggtttcaaatgtgtggaatg-aaagtccg
ag----gaaattcgcttcctcggcggcggtgccag-tgcctcgggag-cgcagtctctcg
gcacgccagggcatcgtggcggcgtcccatggctcggggtcaggcta---------cgga
tcttagtgggagattcgccgaccccggttcgctcggaaggggcgccag------------
----------------------------------tgatctaaaaattgaaacagcagtgc
ggggtacctgtcccggggaaaaggccctcta--tttttctccggggtgagcaccgttggc
gcgcgcc----------tgccctttactcggcgcga------------tcgtcgtgcgac
ggttcaaagaggcgg-accacagtcccccttccctcacggcagacctcagacgtggcggc
ggagggtg-atttatcccacccggcgagtccgccccgc-attgcga-cccct--------
-cgcttcgcgagggttttgttttccccacgaactgttaca-aagtgtgtgaaccatatta
cgaagc----ttgcgcgtccgtccgttgcccgggcgt-----cgcaaggccaaactttat
tttccaaag----cctcttcgaggtgagtacgaaaagaaaaactactctaagcggtggat
cactcggctcgtgtgtcgatgaagagcgcagccagctgcgtgaattaatgtgaattgcag
gacacattgaacatcgatatcttgaacgcatattgcggcatcggcttccaccgatgccac
gcctgtctcagggtcggtttactatctatcgcccccgcgctcctctcggtagcaatgcgg
atttcacgggcgccttggg-tttcacgcagcgcttc--------ggtgctccgcggccct
aagtgcagaccggtctcccaaaaaagttgattgttcg-----------------------
-----gggacggctcgt--------ccagctccgtgtg-ctttttctcgacgctcgccct
caaaagctcgtggcacagcccgtg-gtcggacggtggctcg------gctt-ctttgctc
gcctccggccgggttcctcgagatttataagtcgtcggaaataatac-aacggagtgagt
gcctcgaac-tttttcgacttcggaccgaacc---------------------ggtgact
cggtttaaccaa------tagcacg-----------------------tgtcctcctccg
ggaag-------------------ccgtgcgatcattc---tgtcgacctgagatcagac
gagact
>Notophyllum_foliosum_spm_8 1375 bp 
aggtttccgtaggtgaacctgcggaaggatcattatcgaaactgac--------------
-------------------------ccaaatggtttcaaatgtgtggaatg-aaagtccg
ag----gaaattcgcttcctcggcggcggtgccag-tgcctcgggag-cgcagtctctcg
gcacgccagggcatcgtggcggcgtcccatggctcggggtcaggcta---------cgga
tcttagtgggagattcgccgaccccggttcgctcggaaggggcgccag------------
----------------------------------tgatctaaaaattgaaacagcagtgc
ggggtacctgtcccggggaaaaggccctcta--tttttctccggggkgagcaccgttggc
gcgcgcc----------tgccctttactcggcgcga------------tcgtcgtgcgac
ggttcaaagaggcgg-accacagtcccccttccctcacggcagacctcagacgtggcggc
ggagggtg-atttatcccacccggcgagtccgccccgc-attgcga-cccct--------
-cgcttcgcgagggttttgttttccccacgaactgttaca-aagtgtgtgaaccatatta
cgaagc----ttgcgcgtccgtccgttgcccgggcgt-----cgcaaggccaaactttat
tttccaaag----cctcttcgaggtgagtacgaaaag-aaaactactctaagcggtggat
cactcggctcgtgtgtcgatgaagagcgcagccagctgcgtgaattaatgtgaattgcag
gacacattgaacatcgatatcttgaacgcatattgcggcatcggcttccaccgatgccac
gcctgtctcagggtcggtttactatctatcgcccccgcgctcctctcggtagcaatgcgg
atttcacgggcgccttggg-tttcacgcagcgcttc--------ggtgctccgcggccct
aagtgcagaccggtctcccaaaaaagttgattgttcg-----------------------
-----gggacggctcgt--------ccagctctgtgtg-ctttttctcgacgctcgccct
caaaagctcgtggcacagcccgtg-gtcggacggtggctcg------gctt-ctttgctc
gcctccggccgggttcctcgaga-ttataagtcgtcggaaatartac-aacggagtgagt
gcctcgaac-tttttcgacttcggaccgaacc---------------------ggtgact
cggtttaaccaa------tagcacg-----------------------tgtcctcctccg
ggaag-------------------ccgtgcgatcattc---tgtcgacctgagatcagac
gagact
>Notophyllum_foliosum_spm_9 1369 bp 
aggtttccgtaggtgaacctgcggaaggatcattatcgaaactgac--------------
-------------------------ccaaatggtttcaaatgtgtggaatg-aaagtccg
ag----gaaattcgcttcctcggcggcggtgccag-tgcctcgggag-cgcagtctctcg
gcacgccagggcatcgtggcggcgtcccatggctcggggtcaggcta---------cgga
tcttagtgggagattcgccgaccccggttcgctcggaaggggcgccag------------
----------------------------------tgatctaaaaattgaaacagcagtgc
ggggtacctgtcccgggg-aaaggccctcta--tttttctccggggtgagcaccgttggc
gcgcgcc----------tgccc-ttactcggcgcga------------tcgtcgtgcgac
ggttcaaagaggcgg-accacagtcccccttccctcacggcagacctcagacgt---ggc
ggagggtg-atttatcccacccggcgagtccgccccgc-attgcga-cccct--------
-cgcttcgcgagggttttgttttccccacgaactgttaca-aagtgtgtgaaccatatta
cgaagc----ttgcgcgtccgtccgttgcccgggcgt-----cgcaaggccaaactttat
tttccaaag----cctcttcgaggtgagtacgaaaag-aaaactactctaagcggtggat
cactcggctcgtgtgtcgatgaagagcgcagccagctgcgtgaattaatgtgaattgcag
gacacattgaacatcgatatcttgaacgcatattgcggcatcggcttccaccgatgccac
gcctgtctcagggtcggtttactatctatcgcccccgcgctcctctcggtagcaatgcgg
atttcacgggcgccttggg-tttcacgcagcgcttc--------ggtgctccgcggccct
aagtgcagaccggtctcccaaaaaagttgattgttcg-----------------------
-----gggacggctcgt--------ccagctctgtgtg-ctttttctcgacgctcgccct
caaaagctcgtggcacagcccgtg-gtcggacggtggctcg------gctt-ctttgctc
gcctccggccgggttcctcgagatttataagtcgtcggaaataatac-aacggagtgagt
gcctcgaac-tttttcgacttcggaccgaacc---------------------ggtgact
cggtttaaccaa------tagcacg-----------------------tgtcctcctccg
ggaag-------------------ccgtgcgatcattc---tgtcgacctgagatcagac
gagact
>Paranaitisi_katoi_EU431132 1369 bp 
aggtttccgtaggtgaacctgcggaaggatcattaccgaaactcgcaaactgccgagaca
cttgtaggtggttgctaagtcctctcctcatcgccttggggggaggcggccgggcgctcg
cg----agactttgcttgc-----------------tgcttcggcgacggctgcacccat
gattcc------------accccgccctcttgtcgctatcagggctgtggctgcatcgag
tctcacagtgggtacgaaagactcccatgagcccagtccaggggttggatgccggaaggg
tccgtaagccaatatttgattttacaccattgcctgatgtgaacaacg----atcgttgc
ggggtacctgactcgatcgggtacgccccgg----------aggggagagcaccgttggc
acacggccctttttttttgtcagtcgctcgacaagagagggccggaccgtgccgtgcgac
ggtttaaagagacgacgccgcagcctgctgacagtggcgg--attttcggattc---gcc
aaacgaggcagttccccacctggcttagtccgccccgc-atcgtttcgttgt--------
-----ttgcgaacacctttttttcccaacatactgttttc------tgtaccggttatca
aaaacaaggaccgcgcgtccgtccgttgcccgggcgtggcggtgc----cgaaacttttc
gttccccag-----------------cggacgagaaa-gaaattactctaagcggtggat
cactcggctcgtgtgtcgatgaagagcgcagccagctgcgtgaattaatgtgaattgcag
gacacattgaacatcgatatcttgaacgcatattgcggcatcggcccacaccgatgccac
gcctgtctcagggtcggtttactagcaatcgtttcggattttcc----------------
aattcgcaaacgccttgag-cctgtcgcagtttccc--tcgccggaaactccgtcgctct
aaatgcagaccggtctccc--------tcagcgcacatcacactgcgcctcgttttcctt
agcgggggacggctcgt----------------------cctctttctg----ccggttt
cgcggacaagcagaccagcggaaatctcggacggcggctcgatttgtactttttgtgctc
gcctccggatcacc--------------------------------------------gc
gacacttgctttttttgtccacgaactcgtccccgcatatttaaggagaggtttgcggtt
cgtgtcgctcgagcgacttagcaccgttgttggggtctctgcgtgttgttttctccactc
ggaaaaacaattttcgcgagactttcaaacaatatctcacttgtcgacctgagatcagac
gagact
