>Disciotis_venosa_AY544667 952 bp 
-------------------------taagcatatcaataagcggaggaa-----------
-----aagaaaccaacagggattgcctcagtaacggcgagtgaagcggcaacagctcaaa
ttttaaagctggcgtctttggcgtccgcattgtaatttggagaggcatcttc--------
-----------ggtttgggcgccagcctatgttccttggaacaggacgtcacagagggtg
agaatccc----------------------------------------------------
----------------gtgcttggccggctgtcccattccatgtgaagtgtcttcgacga
gtcgagttgtttgggaatgcagctcaaaatgggtggtaaatttcatctaaagctaaata-
------------ttggtgggag--------------accgatagcgcacaagtagagtga
tcgaaagatgaaaagcactttgaaaatagagttaaaaagtacgtgaaattgttgaaaggg
aagcgcttgagaccagactcggccggggatgatcagctgtccttctgggcagtgcacttg
tctctggtcgggccagcatcggttgagacggcgggacaaaggcttcgggaacgtggctcc
tttcggggagtgttatagcccgtcgcgtaatgccgccagcctcgaccgaggaccgcgc--
--------ttcggctaggatgctggcgtaatggtcttcagcgacccgtct----------
tgaaacacggaccaaggagtctaacatctatgcgagtgtttgggtgtcaa---acccccg
cgcgaaatgaaagtgaacggagg-------------------------------------
--------------------------------------------------------tggg
aacccgtaagggtg---------------------caccatcgaccggtcctgatgtctt
cgga---------tggatctgagtaggagcatagctgttgggacccgaaagatggtgaac
tatgcctgaatagggtgaagccagaggaaactctggtggaggctcgcagcggttctgacg
tgcaaatc----gatcgtcaaatttgggtataggggcgaaagacta--------------
-
>Morchella_angusticeps_AJ544203 952 bp 
--------tccg-----------------taggtgaacctgcggaa-ggatcattacc--
-----aagaaccatacagaaa---------------------------------------
----a----gggaggcattaggg---gaccgaccagggctagtagctt-tac--------
--------------------gttgttgaacgtcca-------------gtatggacccga
agcctccc---------------------------------------------------c
catctaaaccctctgcgtacctgtcccttcttgcttcccccgg-----------catctc
g-----------------------------------------------------------
------------tcggggggagg--taacaaccaaaactctctgtgaatcaaacagccgt
caga------------at------tataaaacaaacaaaaagttaaaactttcaacaacg
gatctcttg---------------------------------------------------
---------gttcccacatcgatgaagaacgcagcgaaatgcgataagtaatgtga----
-attgcagaattcagtgaatcatcgaat-----------ctttgaacgcacattgcgccc
cctggtattccggggggcatgcctgttcgagcgtcataaaaacctcctcccccttcgggt
tttgttactatcgttggggggttttggcctaatgggatagcgattggcaattcgtttccc
aatgtcctaaatagacgtagacccgcctccagatgcgacag-------------------
----------------------------------------caccgaggccatcaaccgtg
gagttatggga------------------------tataataggcttgcagtaaaatgct
cacctctc-----tccacacgccgat----------------ggcacgacagttgcag--
-ttgcgggcgtaaattggagcccttttc-----------------aggaccctcgtggcc
tagcatcc----accatacataatttgacctcggatcaggtagggatacccgctgaactt
a
>Morchella_conica_AJ544194 952 bp 
--------tccg-----------------taggtgaacctgcggaa-ggatcattacc--
-----aagaaccacacagaaa---------------------------------------
----a----gggcagc---cgag---gggccaccagggctagtagctt-tac--------
--------------------gttgttgaacgtcct-------------ggccggacccgg
agccgccc---------------------------------------------------c
catctaaaccctctgcgtacctgtcccgccttgcttcccccgg-----------ctaccc
g-----------------------------------------------------------
------------ctggggggaggaacaacaaccaaaactctttgtgaa-caagccgacgt
caga------------at------catagcaaaacaaaaaagttaaaactttcaacaacg
gatctcttg---------------------------------------------------
---------gttcccacatcgatgaagaacgcagcgaaatgcgataagtaatgtga----
-attgcagaattcagtgaatcatcgaat-----------ctttgaacgcacattgcgccc
cctggtattccggggggcatgcctgttcgagcgtcataaaaacctcctcccccatcgggt
ttgattactatcgttggggggttttggcctaatgggatagcgattggcaattagtttccc
aatgtcctaaatagacgtagacccgcctccagatgcgacag-------------------
----------------------------------------caccgaggccatcaaccgtg
gagttatggga------------------------tat-ataggcttgcagtaaaatgct
cacctttc-----tccatacgccgat----------------ggcacaccggtcgcag--
-ttgcgggcgtaaattggagcccttttc-----------------aggaccctcgtggcc
tagcatcc----accatacacaatttgacctcggatcaggtagggatacccgctgaactt
a
>Morchella_crassipes_AJ539480 952 bp 
atcaatgctctgcatacat-tcattcaattgaatg-tggtgcagagtaggttatttctgc
tgaagggggatcccccggcag---------------------------------------
----a-ggtggacggcacatgca---ggctccgaacgacggaagccaaccat--------
--------------------gtcgctgagtcccctggggctaggggcggtaaaagcccct
agccactc-cccgccgacggcgttgaccccatcgttctggcaccctctcgccactgtccc
aaccaaaaccctctgtgtacccttccc-tgttgcttcccccgggcaactggctccggcca
g-----------------------------------------------------------
------------ccggggggagaaacca-agcaaaaaccc--ttttcgcaaaacagacgt
ctga------------acgcaaaaaacaaaacaaaaaaaaagttaaaactttcaacaacg
gatctcttg---------------------------------------------------
---------gttcccacatcgatgaagaacgcagcgaaatgcgataagtaatgtga----
-attgcagaattcagtgaatcatcgaat-----------ctttgaacgcacattgcgccc
tctggtattccggagggcatgcctgttcgagcgtcataaataccgctccccctc---gga
ttgcttgcggtccctggggggttctggcaatgtg-------------------gattccc
cgtgctttgagggcatgcgaacgggctcccagtgctgaaagacataatgttcccagccga
aaccggtgattaatttcatcggcaggattcgtggcaggcagactgagggcgtcaaccgtg
gagtcatgagggtagaaacctccccctttgcaagtaacattgctctggcagttagatctg
caggcctg-----ccggtctggggatggacctcccactcgcaggcgtcacggccacga--
-tagcgggcgttaaacggaatccgatccg-cctcacgggtggttgaagatccttgtgggc
tagcaacc----cctaaacacattttgacctcggatcaggtagggatacccgctgaactt
a
>Morchella_elata_AJ544200 952 bp 
--------tccg-----------------taggtgaacctgcggaa-ggatcattacc--
-----aagaaccacacagaaa---------------------------------------
----a----gggaggca--aagg---ggccta-caggtctagtagcttatac--------
--------------------gttgttgaacgtcct-------------gcctggacccgg
agccgccc---------------------------------------------------c
catctaaaccctctgcgtacctgtcccttcttgcttcccccgg-----------catctc
g-----------------------------------------------------------
------------tcggggggagg--taacaaccaaaactctctgtgaatcaaacagccgt
caga------------at------tataaaacaaat-aaaagttaaaactttcaacaacg
gatctcttg---------------------------------------------------
---------gttcccacatcgatgaagaacgcagcgaaatgcgataagtaatgtga----
-attgcagaattcagtgaatcatcgaat-----------ctttgaacgcacattgcgccc
cctggtattccggggggcatgcctgttcgagcgtcataaaaacttcctcccccttcgggt
tttgttactatcgttggggggttttggcctaatgggatagcgattggcaattcgtttccc
aatgtcctgaatagacgtagacccgccaccagatgcgacag-------------------
----------------------------------------caccgaggccatcaaccgtg
gagttatggga------------------------tatgataggcttgcagtaaaatgct
cacctctc-----ttcacacgccgat----------------ggcacgacagttgcag--
-ttgcgggcgtaaattggagcccttttc-----------------aggacccttgtggcc
tagcatcc----accatacataatttgaccacggatcaggtagggatacccgctgaactt
a
>Morchella_esculenta_AJ623265 952 bp 
atcaatgctctgcatacat-tcattcaattgaatg-tggtgcagagtaggttatttctgc
tgaagggggatcccccggcag---------------------------------------
----a-ggtggacggcacatgca---ggctccgaacgacggaagccaaccat--------
--------------------gtcgctgagtcccctggggctaggggcggtaaaagcccct
agccactc-cccgccgacggcgttgaccccatcgttctggcaccctctcgccactgtccc
aaccaaaaccctctgtgtacccttccc-tgttgcttcccccgggcaactggctccggcca
g-----------------------------------------------------------
------------ccggggggagaaacca-agcaaaaaccc--ttttcgcaaaacagacgt
ctga------------acgcaaaaaacaaaac-aaaaaaaagttaaaactttcaacaacg
gatctcttg---------------------------------------------------
---------gttcccacatcgatgaagaacgcagcgaaatgcgataagtaatgtga----
-attgcagaattcagtgaatcatcgaat-----------ctttgaacgcacattgcgccc
tctggtattccggagggcatgcctgttcgagcgtcataaataccgctccccctc---gga
ttgcttgcggtccctggggggttctggcaatgtg-------------------gattccc
cgtgctttgagggcatgcgaacgggctcccagtgctgaaagacataatgttcccagccga
aaccggtgattaatttcatcggcaggattcgtggcaggcagactgagggcgtcaaccgtg
gagtcatgagggtagaaacctccccctttgcaagtaacattgctctggcagttagatctg
caggcctg-----ccggtctggggatggacctcccactcgcaggcgtcacggccacga--
-tagcgggcgttaaacggaatccgatccgccctcacgggtggttgaagatccttgtgggc
tagcaacc----cctaaacacattttgacctcggatcaggtagggatacccgctgaactt
a
>Morchella_rufobrunnea_ODonnell_DQ355922 Morchella_rufobrunnea_ODonnell_DQ355922 952 bp 
------------------------------------------------gatcattac---
-----aaaatccaaccaaaaa---------------------------------------
----gaggcgaggaccgcggccgcctggtctccccggttaagaggcacccaccctcagcc
cccatctgcgcgcggcgggggatgcggggcctcccgtact--------ggccgggccgcg
ggcccctc----------------------------------------------cgtctt
cacacaaaccctctgtgtaccttgtccccattgcttccctcggaacgagagcttctccgg
gctggtccgggtggcggcgccccgtggaacgggcggcgcaacccgattggccacgcctgg
ctcgctcctcgcccggggggaggaaaacccaaacaaaccctttgcgcgaaaaac-gacgt
ctga------------ac--agaaaagaaaacaaactaaaagttaaaactttcaacaacg
gatctcttg---------------------------------------------------
---------gttcccacatcgatgaagaacgcagcgaaatgcgataagtaatgtga----
-attgcagaattcagtgaatcatcgaat-----------ctttgaacgcacattgcgccc
tctggtattccggggggcatgcctgttcgagcgtcataaaaacctctccacccc---ggg
ttca-tgagatccggggcgggtattggcggtgcgg------------------atccctc
ccccctatacaacgggacggaggcgcccaccgctcaaagccatgaagataacccagccga
aagcg--------------------------------------ccagggcgtcaaccgtg
gagtcatgagg------------------------aaccacgccccgcgaggggtgcctc
ccactctgggcgaccggtgtatggaa-----------atgcgggcgtaaaagcacggg--
-aaatccgcgggaaccggcgccgtctctggctgcggccgtggatgatccccgtggggggc
tagatacccaatcacattcaagttttgacctcggatcaggtagggatacccgctgaactt
a
>Morchella_spongiola_AJ539476 952 bp 
ttaaacgctctgcacccatcccacgcagttgggtgaaggtgcagagcggatttctgtagc
taaaggaggtacccctggcaa---------------------------------------
----gtggctgacgacgcaagca---gggctgaaataa---acccctgccac--------
--------------------tgcggcgattcccctgtggctgtgggt-gtaaagacccac
agcgactcgcaccgcggcaggacaccactcttaggtttgtcaccccctcgccactgtccc
aaccaaaaccctctgtgtacccttccc-agttgcttcccccggggaactggctcctgcca
g-----------------------------------------------------------
------------ccggggggagaaacca-agcaaaaacccttttttcgcaaaacagacgt
ccga------------at-ttaaaaacaaaac----aaaaagttaaaactttcaacaacg
gatctcttg---------------------------------------------------
---------gttcccacatcgatgaagaacgcagcgaaatgcgataagtaatgtga----
-attgcagaattcagtgaatcatcgaat-----------ctttgaacgcacattgcgccc
tctggtattccggagggcatgcctgttcgagcgtcataaataccgctccccctc---gga
ttgattgcgatccctggggggttctggcaatgtg-------------------gtctccc
cgtgctttgagggcatgcgaacgggctcccagtgctgaaagacataacgttcccggccga
aaccggtgattaatttcaccggcaggattcgtggcaggcagactgagggcgtcaaccgtg
gagtcatgaggatagaaacctccccctttgcaagtaacattgctctggcagttagatctg
caggcctg-----ccggtctggggatggacctcccactcgcaggcgtcacggccacga--
-tagcgggcgttaaacggaatccgatccgccttcactggtggttgaagatccttgtgggc
tagcaacc----cctaaacatattttgacctcggatcaggtagggatacccgctgaactt
a
>Verpa_bohemica_FJ176853 952 bp 
------------------------------atatcaataagcggaggaa-----------
-----aagaaaccaacagggattgcctcagtaacggcgagtgaagcggcaacagctcaaa
ttttaaagctggcgtcttcgacgtccgcattgtaatttggagaggcatcttc--------
-----------ggattgggcgccagcctatgttccttggaacaggacgtcacagagggtg
agaatccc----------------------------------------------------
----------------gtgcttggctggctgtcccatttcatgtgaagtgtcttcgacga
gtcgagttgtttgggaatgcagctcaaaatgggtggtaaatttcatctaaagctaaata-
------------ttggtgggag--------------accgatagcgcacaagtagagtga
tcgaaagatgaaaagcactttgaaaatagagttaaaaagtacgtgaaattgttgaaaggg
aagcgcttgagaccagactcggctggtgatgatcagctgtccttttgggcagtgcacttg
tcgccggttgggccagcatcggttgagacggcgggataaaggttttgggaatgtggctcc
tctcggggagtgttatagcccagaatgcaatgccgccagcctcgaccgaggaccgcgc--
--------ttcggctaggatgctggcataatggtcttcagcgacccgtct----------
tgaaacacggaccaaggagtctaacatctatgcgagtgtttgggtgtcaa---acccttg
cgcgaaatgaaagtgaacggagg-------------------------------------
--------------------------------------------------------tggg
aacccgcaagggcg---------------------caccatcgaccggtcctgatgtctt
cgga---------tggatctgagtaggagcatagctgttgggacccgaaagatggtgaac
tatgcctgaatagggtgaagccagaggaaactctggtggaggctcgcagcggttctgacg
tgcaaatc----gatcgtcaaatttgggtataggggcgaaagacta--------------
-
