>Phytophthora_alticola_CMW19424_DQ988197 Phytophthora_alticola_CMW19424_DQ988197 909 bp 
ccacacct---aaaaactttccacgtgaaccgtatc-aaacttttagttgggggtctt--
tttcggcg-ac-ggctgctggcttcattgctggcggctgc-----tgttgaatgagccct
atc-------at-ggcgagcgtttaggcttc----------ggtctgaactagtag----
---cttttttaaacccatt-ctttattactgat-tatactgtggggacgaaagtctctgc
ttttaactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacg
ctgcgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaac
gcatattgcacttccgggttagtcctgggagtatgcctgtatcagtgtccgtacatcaaa
cttggctttcttccttccgtgtagtcggtgga-agatgtgccag-atgtgaagtgtcttg
cggctgg----tcttcgggtcgg--ctgtgagtcctttgaaatgtactgaactgtact-t
ctctttgctcgaaaagc-gt---g-gcgttgctgattgtggaggctgcc-tgcgtagcca
gtctggcgaccagtttgtctgctgtggcg--ttaatggaggagtgttcgattcgcggtat
ggttggcttcggctgaacag-acgcttattgaatggtttttcctgcta-tggcg---gta
caggttggtgaaccgtagctatgtg-ggcttggcttttgaattggctttgc-tgttgcga
agtagagtgg-------------------cggcttcagc------------tgtcga-gg
gtcgat---ccatttgggaagtg----gtgggtactt----------
>Phytophthora_alticola_CMW19425_DQ988196 Phytophthora_alticola_CMW19425_DQ988196 909 bp 
ccacacct---aaaaactttccacgtgaaccgtatc-aaacttttagttgggggtctt--
tttcggcg-ac-ggctgctggcttcattgctggcggctgc-----tgttgaatgagccct
atc-------at-ggcgagcgtttaggcttc----------ggtctgaactagtag----
---cttttttaaacccatt-ctttattactgat-tatactgtggggacgaaagtctctgc
ttttaactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacg
ctgcgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaac
gcatattgcacttccgggttagtcctgggagtatgcctgtatcagtgtccgtacatcaaa
cttggctttcttccttccgtgtagtcggtgga-agatgtgccag-atgtgaagtgtcttg
cggctgg----tcttcgggtcgg--ctgtgagtcctttgaaatgtactgaactgtact-t
ctctttgctcgaaaagc-gt---g-gcgttgctgattgtggaggctgcc-tgcgtagcca
gtctggcgaccagtttgtctgctgtggcg--ttaatggaggagtgttcgattcgcggtat
ggttggcttcggctgaacag-acgcttattgaatggtttttcctgcta-tggcg---gta
caggttggtgaaccgtagctatgtg-ggcttggcttttgaattggctttgc-tgttgcga
agtagagtgg-------------------cggcttcagc------------tgtcga-gg
gtcgat---ccatttgggaagtg----gtgggtactt----------
>Phytophthora_bisheria_Cg_2_3_3_AY241924 Phytophthora_bisheria_Cg.2.3.3_AY241924 909 bp 
ccacacctaaaaaaaactttccacgtgaaccgtatcaacccttttaattggggat-tt--
gcttggtgtgc-ggctagctggcctttattggctggcaggctgcgtgctgggcgagtcct
atc-------at-ggcaaacgtttgggcttc----------ggtctgagcaagtag--c-
-t---ttttttaaaccatt-tcttaatactgat-tatactgtggggacgaaagtctctgc
ttttaactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacg
ctgcgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaac
gcatattgcacttccgggttagtcctgggagtatgcctgtatcagtgtccgtacatcaaa
cttggttttcttccttccgtgtagtcggtgga-ggatatgccag-atgtgaagtgtcttg
cggctgg----ctttcgggtcggctgcgcgagtcctttgaaatgtactgaactgtact-t
ctctttgctcgaaaagt-ga---g-gcgttgctggttgtggaggctgcc-cgcgtggcca
gtc-ggcgaccggtttgtctgctgcggtgttttactggaggagtgttcgattcgcggtat
ggttggcttcggctgaacag-gcgcttattggac-gttttccctgctg-tggcg---tga
tgagctggtgaaccgtagctatgta-ggcttggcttttgaaccggtgatac-tattgcga
agtagagtgg-------------------cggcttcggc------------tgccgaggg
gtcgat---ccattttgggaaactt-tgtgtgtactt----------
>Phytophthora_bisheria_P_1_33_AF408625 Phytophthora_bisheria_P.1.33_AF408625 909 bp 
ccacacctaaaaaaaactttccacgtgaaccgtatcaacccttttaattggggat-tt--
gcttggtgtgc-ggctagctggcctttattggctggcaggctgcgtgctgggcgagtcct
atc-------at-ggcaaacgtttgggcttc----------ggtctgagcaagtag--c-
-t---ttttttaaaccatt-tcttaatactgat-tatactgtggggacgaaagtctctgc
ttttaactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacg
ctgcgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaac
gcatattgcacttccgggttagtcctgggagtatgcctgtatcagtgtccgtacatcaaa
cttggttttcttccttccgtgtagtcggtgga-ggatatgccag-atgtgaagtgtcttg
cggctgg----ctttcgggtcggctgcgcgagtcctttgaaatgtactgaactgtact-t
ctctttgctcgaaaagt-ga---g-gcgttgctggttgtggaggctgcc-cgcgtgacca
gtc-ggcgaccggtttgtctgctgcggtgttttactggaggagtgttcgattcgcggtat
ggttggcttcggctgaacag-gcgcttattggac-gttttccctgctg-tggcg---tga
tgagctggtgaaccgtagctatgta-ggcttggcttttgaaccggtgatac-tattgcga
agtagagtgg-------------------cggcttcggc------------tgccgaggg
gtcgat---ccattttgggaaactt-tgtgtgtactt----------
>Phytophthora_boehmeriae_CMW19441_DQ988207 Phytophthora_boehmeriae_CMW19441_DQ988207 909 bp 
ccccacct----aaaactttccacgtgaaccgttc--aaccttttagttggggactcc--
----------------------tcgtcggcggctttcgggctgttggtgggttgaggcct
atc-------aa-agcgagtgatttgggccg-------caaggtctgagttgcgag---t
ttttccttttaaacccattacttaaatactgat-tatactgtggggacgaaagtctctgc
ttttaactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacg
ctgcgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaac
gcatattgcacttccgggttatgcctgggagtatgcctgtatcagtgtccgtacatcaac
cttggcttccttccttccgtgtagtcggtggatgggaatgccag-acgtgaagtgtcttg
ctgtagcgg--ttttcggactgcggc-gcgagtcctttgaaatgta-gatactgttct-t
ctctttgctcgaaaagctgt---gcagaatgtatgttgtggaggctgcc-atcacggcat
gtc-ggcgactgattt-cgtgctgaggcg---ttttggagaggggttcgattcgcggtag
tgttggtttcggccgaacaatctgcttattgggt-tcttttccaggctttggcg-tatgc
ggagtcggtgtaccgtagttgtgcgtggcttggcctttgaacgctcgttttgcgtggcga
agtagagtggcgaagtgtttgttttcggacgaatgcggc------------tgccgagga
ggggataaaatattttgggaaaatttagtgtgcgctt----------
>Phytophthora_boehmeriae_DDS3884_EU301151 Phytophthora_boehmeriae_DDS3884_EU301151 909 bp 
ccacacct--aaaaaactttccacgtgaaccgttc--aaccttttagttggggactcc--
----------------------tcgtcggcggctttcgggctgttggtgggttgaggcct
atc-------aa-agcgagtgatttgggccg-------caaggtctgagttgcgag----
ttttccttttaaacccattacttaaatactgat-tatactgtggggacgaaagtctctgc
ttttaactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacg
ctgcgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaac
gcatattgcacttccgggttatgcctgggagtatgcctgtatcagtgtccgtacatcaac
cttggcttccttccttccgtgtagtcggtggatgggaatgccag-acgtgaagtgtcttg
ctgtagcgg--ttttcggactgcggcggcgagtcctttgaaatgta-gatactgttct-t
ctctttgctcgaaaagctgt---gcagaatgtatgttgtggaggctgcc-atcacggcat
gtc-ggcgactgattt-cgtgctgaggcg---ttttggagaggggttcgattcgcggtag
tgttggtttcggccgaacaatctgcttattgggt-tcttttccaggctttggcg-tatgc
ggagtcggtgtaccgtagttgtgcgtggcttggcctttgaacgctcgttttgcgtggcga
agtagagtggcgaagtgtttgttttcggacgaatgcggc------------tgccgagga
ggcgat-aaatattttgggaaaatttagtgtgcgctt----------
>Phytophthora_cactorum_IMI296524_AF266772 Phytophthora_cactorum_IMI296524_AF266772 909 bp 
ccacacct---aaaaactttccacgtgaaccgtttcaaaccaaatagttgggggtctt--
gtctggtg-gc-ggctgctggctttattgttggcggctgc-----tgctgggtgagccct
atc-------at-ggcgagcgtttgggcttc----------ggcctgagctagtag----
cttttcttttaaacccatt-ccttaatactgat-tatactgtggggacgaaagtccttgc
ttttaactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacg
ctgcgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaac
gcatattgcacttccgggttagtcctgggagtatgcctgtatcagtgtccgtacatcaaa
cttggctttcttccttccgtgtagtcggtgga-ggagatgccag-atgtgaagtgtcttg
cggctgg----ttttcggaccga--ctgcgagtccttttaaatgtactgaactgtact-t
ctctttgctcgaaaagc-gt---g-gcgttgctggttgtggaggctgct-attgtagcaa
gtt-ggcgaccggtttgtctgctgcggcg--ttaatggaagagtgttcgattcgcggtat
ggttagcttcggctgaacaatgcgcttattggat-gttttttctgctg-tggcg---tga
tggaccggtgaaccatagctcagtt--gcttggcttttgaatcggctttgc-tgttgcga
agtagagtgg-------------------cggcttcggc------------tgtcga-gg
gtcgat---ccatttgggaaatg---tgtgtgtactt----------
>Phytophthora_cactorum_P167_EU109566 Phytophthora_cactorum_P167_EU109566 909 bp 
ccacacct---aaaaactttccacgtgaaccgtttcaaaccaaatagttgggggtctt--
gtctggtg-gc-ggctgctggctttattgttggcggctgc-----tgctgggtgagccct
atc-------at-ggcgagcgtttgggcttc----------ggcctgagctagtag----
cttttcttttaaacccatt-ccttaatactgat-tatactgtggggacgaaagtccttgc
ttttaactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacg
ctgcgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaac
gcatattgcacttccgggttagtcctgggagtatgcctgtatcagtgtccgtacatcaaa
cttggctttcttccttccgtgtagtcggtgga-ggagatgccag-atgtgaagtgtcttg
cggctgg----ttttcggaccga--ctgcgagtccttttaaatgtactgaactgtact-t
ctctttgctcgaaaagc-gt---g-gcgttgctggttgtggaggctgct-attgtagcaa
gtt-ggcgaccggtttgtctgctgcggcg--ttaatggaagagtgttcgattcgcggtat
ggttagcttcggctgaacaatgcgcttattggat-gttttttctgctg-tggcg---tga
tggaccggtgaaccatagctcagtt--gcttggcttttgaatcggctttgc-tattgcga
agtagagtgg-------------------cggcttcggc------------tgtcga-gg
gtcgat---ccatttgggaaatg---tgtgtgtactt----------
>Phytophthora_captiosa_NZFS310_31_DQ297404 Phytophthora_captiosa_NZFS310.31_DQ297404 909 bp 
ccacacct-taaaaaat--tccacgtgaactgtattgtcaaccaaattcggggactcctt
gctagtgtgctttcgggcgtgcc----------------------ggtaggttgagaccc
atc-------aa--acgaaaacatcgactga--------aaggtcggagccagtag----
ttacctttgtaaacccttt-actaaatactgaa--aaactgtggggacgaaagtccttgc
tttt-actagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacg
ctgcgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaac
gcatattgcacttccgggttatgcctggaagtatgcctgtatcagtgtccgtatatcaaa
cttgccttccttccttccgtgtagtcggtggatgggaacgtgcagatgtgaagtgtcttg
gcggcgtc---gcttcgg-cggtgctggcgagtccttttaaatacaagatactgttct-t
ctctttgctcgaaaagc-gt---gtgggatg-tggttgtggaggctgcc-tgcgtggcca
gtc-ggcgactgattt-cgtgctgagacg-----gtggggaggggcttgattcgcggtat
ggttggcttcggctgaactt-ctgcttattgggcttctttc--atgtcttggcg-tatgc
gattttggtgtaccgtagctgtgtgtggcttggcttttgaaccgtgttc--tgtgtgcga
agtagagtgggcg----tgtggtttt---cggactgcgt------------ggccgaggg
gacgag--accttttgggaaattgtgctgctacttttgtggcggcat
>Phytophthora_captiosa_NZFS310_35_DQ297405 Phytophthora_captiosa_NZFS310.35_DQ297405 909 bp 
ccacacct-taaaaaat--tccacgtgaactgtattgtcaaccaaattcggggactcctt
gctagtgtgctttcgggcgtgcc----------------------ggtaggttgagaccc
atc-------aa--acgaaaacatcgactga--------aaggtcggagccagtag----
ttacctttgtaaacccttt-actaaatactgaa--aaactgtggggacgaaagtccttgc
tttt-actagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacg
ctgcgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaac
gcatattgcacttccgggttatgcctggaagtatgcctgtatcagtgtccgtatatcaaa
cttgccttccttccttccgtgtagtcggtggatgggaacgtgcagatgtgaagtgtcttg
gcggcgtc---gcttcgg-cggtgctggcgagtccttttaaatacaagatactgttct-t
ctctttgctcgaaaagc-gt---gtgggatg-tggttgtggaggctgcc-tgcgtggcca
gtc-ggcgactgattt-cgtgctgagacg-----gtggggaggggcttgattcgcggtat
ggttggcttcggctgaactt-ctgcttattgggcttctttc--atgtcttggcg-tatgc
gattttggtgtaccgtagctgtgtgtggcttggcttttgaaccgtgttc--tgtgtgcga
agtagagtgggcg----tgtggtttt---cggactgcgt------------ggccgaggg
gacgag--accttttgggaaattgtgctgctacttttgtggcggcat
>Phytophthora_cinnamomi_mc9_AY302153 Phytophthora_cinnamomi_mc9_AY302153 909 bp 
ccacacct--aaaaaactttccacgtgaaccgtatcaacccaattagttgggggcctg--
ctctgggcggc-ggctgtcgatgtcaaagtcgacggct-gctgc-tgcgtggcgggccct
atc-------ac-tggcgagcgtttgggtccctctcg-ggggaactgagctagtag----
cctctcttttaaacccatt-ctgtaatactgaa-catactgtggggacgaaagtctctgc
ttttaactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacg
ctgcgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaac
gcatattgcacttccgggttagtcctgggagtatgcctgtatcagtgtccgtacatcaaa
cttggctctcttccttccgtgtagtcggtggatggaggtgccag-acgtgaggtgtcttg
cgg-gcgg---tcttcggactgg--ctgtgagtcccttgaaatgtactgaactgtact-t
ctctttgctcgaaaagc-gt---g-acgttgctggttgtggaggctgcc-tgtatggcca
gtc-ggcgaccggtttgtctgctgcggcg-tttaatggaggagtgttcgattcgcggtat
ggttggcttcggctgaacaaagcgcttattggat-gttcttcctgctg-tggcg---gta
cggatcggtgaaccgtagctgtgctaggcttggcgtttgaaccggcggtgt-tgttgcga
agtagggtgg-------------------cggcttcggc------------tgtcga-gg
gtcgat---ccatttgggaactctg---tgtctctgcggcgcactt-
>Phytophthora_citricola_112_EU263906 Phytophthora_citricola_112_EU263906 909 bp 
ccacacct--aaaaaacttttcacgtgaaccgtatcaacccttttagttgggggtctt--
gc-ttttt------------------------------------------tgcgagccct
atc-------at-ggcgaatgtttggacttc----------ggtctgggctagtag--c-
tttttgttttaaacccatt-ctacaatactgat-tatactgtggggacgaaagtctctgc
ttttaactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacg
ctgcgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaac
gcatattgcacttccgggttagtcctgggagtatgcctgtatcagtgtccgtacatcaaa
cttggctttcttccttccgtgtagtcggtgga-ggatgtgccag-atgtgaagtgtcttg
cgg-gtgt---ccttcgggtcgt--ctgcgagtcctttgaaatgtactgaactgtact-t
ctctttgctcgaaaagc-gt---g-gtgttgctggttgtggaggctgcc-tgcgtggcca
gtc-ggcgaccggtttgtctgctgcagcg-tttaatggaggagtgttcgattcgcggtat
ggttggcttcggctgaacag-gcgcttattgtat-gcttttcctgctg-tggcg---tga
tgggctggtgaaccgtagctatgtgtggcttggcttttgaatcggctttgc-tgttgcga
agtagagtgg-------------------cggcttcggc------------tgtcga-gg
gtcgat---cca-tttgggaac-tt-tgtgtgcacct----------
>Phytophthora_citricola_77a_EU594606 Phytophthora_citricola_77a_EU594606 909 bp 
ccacacct--aaaaaactttccacgtgaaccgtatcaaccctttcagttgggggcctt--
gc-ttttt------------------------------------------tgcgagccct
atc-------at-ggcgaatgtttggacttc----------ggtctgggctagtag--c-
tttttgttttaaacccatt-ctacaatactgat-tatactgtggggacgaaagtctctgc
ttttaactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacg
ctgcgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaac
gcatattgcacttccgggttagtcctgggagtatgcctgtatcagtgtccgtacatcaaa
cttggctttcttccttccgtgtagtcggtgga-ggatgtgccag-atgtgaagtgtcttg
cag-gtgt---ccttcgggtcgt--ctgcgagtcctttgaaatgtactgaactgtact-t
ctctttgctcgaaaagc-gt---g-gcgttgctggttgtggaggctgcc-tgcgtggcca
gtc-ggcgaccggtttgtctgctgcggcg-tttaatggaggagtgttcgattcgcggtat
ggttggcttcggctgaacag-gcgcttattgtat-gcttttcctgctg-tggcg---tga
tggactggtgaaccgtagctgtgtgtggcttggcttttgaatcggctttgc-tgttgcga
agtagagtgg-------------------cggctccggc------------tgtcga-gg
gtcgat---cca-tttgggaac-tt-tgtgtgcacct----------
>Phytophthora_citricola_IMI021173 Phytophthora_citricola_IMI021173 909 bp 
ccacacct--aaaaaactttccacgtgaaccgtatcaacccttttagttgggggtctt--
gctttttt------------------------------------------tgcgagccct
atc-------at-ggcgaatgtttggacttc----------ggtctgggctagtag--c-
tttttgttttaaacccatt-ctacaatactgat-tatactgtggggacgaaagtctctgc
ttttaactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacg
ctgcgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaac
gcatattgcacttccgggttagtcctgggagtatgcctgtatcagtgtccgtacatcaaa
cttggctttcttccttccgtgtagtcggtgga-ggatgtgccag-atgtgaagtgtcttg
cgg-gtgt---ccttcgggtcgt--ctgcgagtcctttgaaatgtactgaactgtact-t
ctctttgctcgaaaagc-gt---g-gtgttgctggttgtggaggctgcc-tgcgtggcca
gtc-ggcgaccggtttgtctgctgcggcg-tttaatggaggagtgttcgattcgcggtat
ggttggcttcggctgaacag-gcgcttattgtat-gcttttcctgctg-tggcg---tga
tgggctggtgaaccgtagctgtgtgtggcttggcttttgaatcggctttgc-tgttgcga
agtagagtgg-------------------cggcttcggc------------tgtcga-gg
gtcgat---cca-tttgggaac-tt-tgtgtgcacct----------
>Phytophthora_citricola_IMI031372_AF266788 Phytophthora_citricola_IMI031372_AF266788 909 bp 
ccacacct--aaaaaacttttcacgtgaaccgtatcaacccttttagttgggggtctt--
gc-ttttt------------------------------------------tgcgagccct
atc-------at-ggcgaatgtttggacttc----------ggtctgggctagtag--c-
tttttgttttaaacccatt-ctacaatactgat-tatactgtggggacgaaagtctctgc
ttttaactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacg
ctgcgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaac
gcatattgcacttccgggttagtcctgggagtatgcctgtatcagtgtccgtacatcaaa
cttggctttcttccttccgtgtagtcggtgga-ggatgtgccag-atgtgaagtgtcttg
cgg-gtgt---ccttcgggtcgt--ctgcgagtcctttgaaatgtactgaactgtact-t
ctctttgctcgaaaagc-gt---g-gtgttgctggttgtggaggctgcc-tgcgtggcca
gtc-ggcgaccggtttgtctgctgcagcg-tttaatggaggagtgttcgattcgcggtat
ggttggcttcggctgaacag-gcgcttattgtat-gcttttcctgctg-tggcg---tga
tgggctggtgaaccgtagctatgtgtggcttggcttttgaatcggctttgc-tgttgcga
agtagagtgg-------------------cggcttcggc------------tgtcga-gg
gtcgat---cca-tttgggaac-tt-tgtgtgcacct----------
>Phytophthora_citricola_MN21HH_DQ486661 Phytophthora_citricola_MN21HH_DQ486661 909 bp 
ccacacct--aaaaaacttttcacgtgaaccgtatcaacccttttagttgggggtctt--
gctttttt------------------------------------------tgcgagccct
atc-------at-ggcgaatgtttggacttc----------ggtctgggctagtag--c-
tttttgttttaaacccatt-ctacaatactgat-tatactgcggggacgaaagtctctgc
ttttaactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacg
ctgcgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaac
gcatattgcacttccgggttagtcctgggagtatgcctgtatcagtgtccgtacatcaaa
cttggctttcttccttccgtgtagtcggtgga-ggatgtgccag-acgtgaagtgtcttg
cgg-gtgt---ccttcgggtcgt--ctgcgagtcctttgaaatgtactgaactgtact-t
ctctttgctcgaaaagc-gt---g-gtgttgctggttgtggaggctgcc-tgcgtggcca
gtc-ggcgaccggtttgtctgctgcggcg-tttaatggaggagtgttcgattcgcggtat
ggttggcttcggctgaacag-gcgcttattgtat-gcttttcctgctg-tggcg---tga
tgggctggtgaaccgtagctgtgtgtggcttggcttttgaatcggctttgc-tgttgcga
agtagagtgg-------------------cggcttcggc------------tgtcga-gg
gtcgat---cca-tttgggaac-tt-tgtgtgcacct----------
>Phytophthora_citricola_P15946_EU244846 Phytophthora_citricola_P15946_EU244846 909 bp 
ccacacct--aaaaaactttccacgtgaaccgtatcaaccctttcagttgggggcctt--
gc-ttttt------------------------------------------tgcgagccct
atc-------at-ggcgaatgtttggacttc----------ggtctgggctagtag--c-
tttttgttttaaacccatt-ctacaatactgat-tatactgtggggacgaaagtctctgc
ttttaactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacg
ctgcgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaac
gcatattgcacttccgggttagtcctgggagtatgcctgtatcagtgtccgtacatcaaa
cttggctttcttccttccgtgtagtcggtgga-ggatgtgccag-atgtgaagtgtcttg
cag-gtgt---ccttcgggtcgt--ctgcgagtcctttgaaatgtactgaactgtact-t
ctctttgctcgaaaagc-gt---g-gcgttgctggttgtggaggctgcc-tgcgtggcca
gtc-ggcgaccggtttgtctgctgcggcg-tttaatggaggagtgttcgattcgcggtat
ggttggcttcggctgaacag-gcgcttattgtat-gcttttcctgctg-tggcg---tga
tggactggtgaaccgtagctgtgtgtggcttggcttttgaatcggctttgc-tgttgcga
agtagagtgg-------------------cggctccggc------------tgtcga-gg
gtcgat---cca-tttgggaac-tt-tgtgtgcacct----------
>Phytophthora_citricola_P44_EF423556 Phytophthora_citricola_P44_EF423556 909 bp 
ccacacct--aaaaaacttttcacgtgaaccgtatcaacccttttagttgggggtctt--
gctttttt------------------------------------------tgcgagccct
atc-------at-ggcgaatgtttggacttc----------ggtctgggctagtag--c-
tttttgttttaaacccatt-ctacaatactgat-tatactgcggggacgaaagtctctgc
ttttaactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacg
ctgcgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaac
gcatattgcacttccgggttagtcctgggagtatgcctgtatcagtgtccgtacatcaaa
cttggctttcttccttccgtgtagtcggtgga-ggatgtgccag-acgtgaagtgtcttg
cgg-gtgt---ccttcgggtcgt--ctgcgagtcctttgaaatgtactgaactgtact-t
ctctttgctcgaaaagc-gt---g-gtgttgctggttgtggaggctgcc-tgcgtggcca
gtc-ggcgaccggtttgtctgctgcggcg-tttaatggaggagtgttcgattcgcggtat
ggttggcttcggctgaacag-gcgcttattgtat-gcttttcctgctg-tggcg---tga
tgggctggtgaaccgtagctgtgtgtggcttggcttttgaatcggctttgc-tgttgcga
agtagagtgg-------------------cggcttcggc------------tgtcga-gg
gtcgat---cca-tttgggaac-tt-tgtgtgcacct----------
>Phytophthora_citrophthora_CMW20198_DQ988188 Phytophthora_citrophthora_CMW20198_DQ988188 909 bp 
ccacacct--aaaaaactttccacgtgaaccgtatcaacccttttagttgggggtgtt--
gcttggca---------------------------------tttagctgagccgcgccct
atc-------at-ggcgaatgtttggacttc----------ggtctgggctagtag--ct
tttttgttttaaa-ccatt-taacaatactgat-tatactgtggggacgaaagtctctgc
ttttaactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacg
ctgcgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaac
gcatattgcacttccgggttagtcctgggagtatgcctgtatcagtgtccgtacatcaaa
cttggctttcttccttccgtgtagtcggtgga-ggatgtgccag-atgtgaagtgtcttg
cggtttgtgtgccttcgggccgaggctgcgagtcctttgaaatgtactgaactgtact-t
ctctttgctcgaaaagc-gt---g-gtgttgctggttgtggaggctgcc-tgcgtggcca
gtc-ggcgaccggtttgtctgctgcggcg-tttaatggaggagtgttcgattcgcggtat
ggttggcttcggctgaacag-gcgcttattgtat-gcttttcctgctg-tggcg---tga
tgggctggtgaaccgtagctgtgtgtggcttggcttttgaatcggctttgc-tgttgcga
agtagagtgg-------------------cggcttcggc------------tgtcga-gt
gtcgat---ccattttgggaacgtt-tgtgtgcgctt----------
>Phytophthora_citrophthora_IMI332632_AF266785 Phytophthora_citrophthora_IMI332632_AF266785 909 bp 
ccacacct--aaaaaactttccacgtgaaccgtatcaacccttttagttgggggtgtt--
gcttggcgt--------------------------------ttttgctgagccacgccct
atc-------at-ggcgaatgtttggacttc----------ggtctgggctagtag--ct
tttttgttttaaacccatt-taacaatactgat-tatactgtggggacgaaagtctctgc
ttttaactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacg
ctgcgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaac
gcatattgcacttccgggttagtcctgggagtatgcctgtatcagtgtccgtacatcaaa
cttggctttcttccttccgtgtagtcggtgga-ggatgtgccag-atgtgaagtgtcttg
cggtttttgtgccttcgggccgtggctgcgagtcctttgaaatgtactgaactgtact-t
ctctttgctcgaaaagc-gt---g-gtgttgctggttgtggaggctgcc-tgcgtggcca
gtc-ggcgaccggtttgtctgctgcggcg-tttaatggaggagtgttcgattcgcggtat
ggttggcttcggctgaacag-gcgcttattgtat-gcttttcctgctg-tggcg---tga
tgggctggtgaaccgtagctgtgtgtggcttggcttttgaatcggctttgc-tgttgcga
agtagagtgg-------------------cggcttcggc------------tgtcga-gt
gtcgat---ccattttgggaacgtt-tgtgtgcgctt----------
>Phytophthora_cryptogea_CRP235_AY659443 Phytophthora_cryptogea_CRP235_AY659443 909 bp 
ccacacct--aaaaaactttccacgtgaaccgtatcaacctttttaaattgggggctccc
gtctggccggccggttttcggctggctgggtggcggct--------------------ct
atc-------at-ggcgaccgcttgggcctc----------ggcctgggctagtag----
cgtattttttaaacccatt-cctaattactgaa-tatactgtggggacgaaagtctctgc
ttttaactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacg
ctgcgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaac
gcatattgcacttccgggttagtcctgggagtatgcctgtatcagtgtccgtacactaaa
cttggctcccttccttccgtgtagtcggtggatggggacgcgcagatgtgaagtgtcttg
cggctgg----tcttcggtccgg--ctgcgagtcctttgaaatgtactacactgtact-t
ctctttgctcgaaaagc-gt---g-acgttgctggttgtggaggctgcc-tgtgtggcat
gtc-ggcgaccggtttgtctgctgcggcg-tttaatggaggagtgttcgattcgcggtat
gattggcttcggctgaacag-acgcttattgggt-gcttttcctgctg-tggct---gga
tggactggtgaaccgtagctgtgctaggcttggcgtttgaaccggcggtgt-gg-tgcga
agtagggtgt-------------------ctgttccggcgcaagctggggtggacga-gg
gtcgat---ccatttgggaaacgttgtgtgcgctt------------
>Phytophthora_cryptogea_DDS3612_EU301139 Phytophthora_cryptogea_DDS3612_EU301139 909 bp 
ccacacct--aaaaaactttccacgtgaaccgtatcaacctttttaaattgggggctccc
gtctggccggccggttttcggctggctgggtggcggct--------------------ct
atc-------at-ggcgaccgcttgggcctc----------ggcctgggctagtag----
cgtattttttaaacccatt-cctaattactgaa-tatactgtggggacgaaagtctctgc
ttttaactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacg
ctgcgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaac
gcatattgcacttccgggttagtcctgggagtatgcctgtatcagtgtccgtacactaaa
cttggctcccttccttccgtgtagtcggtggatggggacgcgcagatgtgaagtgtcttg
cggctgg----tcttcggtccgg--ctgcgagtcctttgaaatgtactacactgtact-t
ctctttgctcgaaaagc-gt---g-acgttgctggttgtggaggctgcc-tgtgtggcat
gtc-ggcgaccggtttgtctgctgcggcg-tttaatggaggagtgttcgattcgcggtat
gattggcttcggctgaacag-acgcttattgggt-gcttttcctgctg-tggct---gga
tggactggtgaaccgtagctgtgctaggcttggcgtttgaaccggcggtgt-gg-tgcga
agtagggtgt-------------------ctgttccggcgcaagctggggtggacga-gg
gtcgat---ccatttgggaaacgttgtgtgcgctt------------
>Phytophthora_cryptogea_IMI045168_AF266796 Phytophthora_cryptogea_IMI045168_AF266796 909 bp 
ccacacct--aaaaaactttccacgtgaaccgtatcaacctttttaatttgggggcttcc
gtctggccggccggttttcggctggctgggtggcggct--------------------ct
atc-------at-ggcgaccgcttgggcctc----------ggcctgggctagtag----
cgtattttttaaacccatt-cctaattactgaa-tatactgtggggacgaaagtctctgc
ttttaactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacg
ctgcgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaac
gcatattgcacttccgggttagtcctgggagtatgcctgtatcagtgtccgtacactaaa
cttggctcccttccttccgtgtagtcggtggatggggacgcgcagatgtgaagtgtcttg
cggctgg----tcttcggtccgg--ctgcgagtcctttgaaatgtactacactgtact-t
ctctttgctcgaaaagc-gt---g-acgttgctggttgtggaggctgcc-tgtgtggcat
gtc-ggcgaccggtttgtctgctgcggcg-tttaatggaggagtgttcgattcgcggtat
ggttggcttcggctgaacag-acgcttattgggt-gcttttcctgctg-tggct---gga
tggactggtgaaccgtagctgtgctaggcttggcgtttgaaccggcggtgt-gg-tgcga
agtagggtgt-------------------ctgttctggcgtaagctggggtggacga-gg
gtcgat---ccatttgggaaacgttgtgtgcgctt------------
>Phytophthora_cryptogea_TCH010_EU301141 Phytophthora_cryptogea_TCH010_EU301141 909 bp 
ccacacct--aaaaaactttccacgtgaaccgtatcaacc-ttttaaattgggggctccc
gtctggccggccggttttcggctggctgggtggcggct--------------------ct
atc-------at-ggcgaccgcttgggcctc----------ggcctgggctagtag----
cgtattttttaaacccatt-cctaattactgaa-tatactgtggggacgaaagtctctgc
ttttaactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacg
ctgcgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaac
gcatattgcacttccgggttagtcctgggagtatgcctgtatcagtgtccgtacactaaa
cttggctcccttccttccgtgtagtcggtggatggggacgcgcagatgtgaagtgtcttg
cggctgg----tcttcggtccgg--ctgcgagtcctttgaaatgtactacactgtact-t
ctctttgctcgaaaagc-gt---g-acgttgctggttgtggaggctgcc-tgtgtggcat
gtc-ggcgaccggtttgtctgctgcggcg-tttaatggaggagtgttcgattcgcggtat
gattggcttcggctgaacag-acgcttattgggt-gcttttcctgctg-tggct---gga
tggactggtgaaccgtagctgtgctaggcttggcgtttgaaccggcggtgt-gg-tgcga
agtagggtgt-------------------ctgttccggcgcaagctggggtggacga-gg
gtcgat---ccatttgggaaacgttgtgtgcgctt------------
>Phytophthora_cryptogea_VHS14620_EU301142 Phytophthora_cryptogea_VHS14620_EU301142 909 bp 
ccacacct--aaaaaactttccacgtgaaccgtatcaacctttttaaattgggggctccc
gtctggccggccggttttcggctggctgggtggcggct--------------------ct
atc-------at-ggcgaccgcttgggcctc----------ggcctgggctagtag----
cgtattttttaaacccatt-cctaattactgaa-tatactgtggggacgaaagtctctgc
ttttaactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacg
ctgcgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaac
gcatattgcacttccgggttagtcctgggagtatgcctgtatcagtgtccgtacactaaa
cttggctcccttccttccgtgtagtcggtggatggggacgcgcagatgtgaagtgtcttg
cggctgg----tcttcggtccgg--ctgcgagtcctttgaaatgtactacactgtact-t
ctctttgctcgaaaagc-gt---g-acgttgctggttgtggaggctgcc-tgtgtggcat
gtc-ggcnaccggtttgtctgctgcggcg-tttaatggaggagtgttcgattcgcggtat
gattggcttcggctgaacag-acgcttattgggt-gcttttcctgctg-tggct---gga
tggactggtgaaccgtagctgtgctaggcttggcgtttgaaccggcggtgt-gg-tgcga
agtagggtgt-------------------ctgttccggcgcaagctggggtggacga-gg
gtcgat---ccatttgggaaacgttgtgtgcgctt------------
>Phytophthora_drechsleri_ATCC46742_AF266798 Phytophthora_drechsleri_ATCC46742_AF266798 909 bp 
ccacacct--aaaaaac-ttccacgtgaaccgtatcaacctttttaaattgggggcttcc
gtctggccggccggttctcggctggctgggtggcggct--------------------ct
atc-------at-ggcgaccgcctgggcctc----------ggcctgggttagtag----
cgtatttttt-aaaccatt-cctaattactgaa-aaaactgtggggacgaaagtctctgc
ttttaactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacg
ctgcgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaac
gcatattgcacttccgggttagtcctgggagtatgcctgtatcagtgtccgtacactaaa
cttggctcccttccttccgtgtagtcggtggatggggacgcgcagatgtgaagtgtcttg
cggctgg----tcttcggtccgg--ctgcgagtccttttaaatgtactacactgtact-t
ctctttgctcgaaaagc-gt---g-acgttgctggttgtggaggctgcc-tgtgtggcat
gtc-ggcgaccggtttgtctgctgcggcgttttaatggaggagtgttcgattcgcggtat
ggttggcttcggctgaacag-acgcttattgggt-gctttttctgctg-cggcg---gga
tggactggtgaaccgtagctgtgctaggcttggcgtttgaaccggcggtat-tg-tgcga
agtagggtgt-------------------ctgtctcggcgcaagctggggtgggcga-gg
gtcgat---ccatttgggaaacgttgtgtgcgctt------------
>Phytophthora_drechsleri_DSM62680_AY878548 Phytophthora_drechsleri_DSM62680_AY878548 909 bp 
ccacacct--aaaaaac-ttccacgtgaaccgtatcaacctttttaaattgggggcttcc
gtctggccggccggttctcggctggctgggtggcggct--------------------ct
atc-------at-ggcgaccgcctgggcctc----------ggcctgggttagtag----
cgtatttttt-aaaccatt-cctaattactgaa-aaaactgtggggacgaaagtctctgc
ttttaactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacg
ctgcgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaac
gcatattgcacttccgggttagtcctgggagtatgcctgtatcagtgtccgtacactaaa
cttggctcccttccttccgtgtagtcggtggatggggacgcgcagatgtgaagtgtcttg
cggctgg----tcttcggtccgg--ctgcgagtccttttaaatgtactacactgtact-t
ctctttgctcgaaaagc-gt---g-acgttgctggttgtggaggctgcc-tgtgtggcat
gtc-ggcgaccggtttgtctgctgcggcgttttaatggaggagtgttcgattcgcggtat
ggttggcttcggctgaacag-acgcttattgggt-gctttttctgctg-cggcg---gga
tggactggtgaaccgtagctgtgctaggcttggcgtttgaaccggcggtat-tg-tgcga
agtagggtgt-------------------ctgtctcggcgcaagctggggtgggcga-gg
gtcgat---ccatttgggaaacgttgtgtgcgctt------------
>Phytophthora_erythroseptica_ATCC36302_AF266797 Phytophthora_erythroseptica_ATCC36302_AF266797 909 bp 
ccacacct--aaaaaactttccacgtgaaccgtatcaacctttttaaattgggggcttcc
gtctggccggccggttttcggctggctgggtggcggct--------------------ct
atc-------at-ggcgaccgcttgggcctc----------ggcctgggctagtag----
cgtattttt--aaaccatt-cctaattactgaa-tatactgtggggacgaaagtctctgc
ttttaactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacg
ctgcgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaac
gcatattgcacttccgggttagtcctgggagtatgcctgtatcagtgtccgtacactaaa
cttggctcccttccttccgtgtagtcggtggatggggacgcgcagatgtgaagtgtcttg
cggctgg----tcttcggtccgg--ctgcgagtcctttgaaatgtactacactgtact-t
ctctttgctcgaaaagc-gt---g-acgttgctggttgtggaggctgcc-tgtgtggcat
gtc-ggcgaccggtttgtctgctgcggcg-tttaatggaggagtgttcgattcgcggtat
ggttggcttcggctgaacag-acgcttattgggt-gcttttcctgctg-tggct---gga
tggactggtgaaccgtagctgtgctaggcttggcgtttgaaccggcggtgt-gg-tgcga
agtagggtgt-------------------ctgttccggcgtaagctggggtggacga-gg
gtcgat---ccatttgggaaacgttgtgtgcgctt------------
>Phytophthora_fallax_NZFS446_DQ297397 Phytophthora_fallax_NZFS446_DQ297397 909 bp 
ccacacct-taaaaaat--tccacgtgaactgtattgtcaaccaaattcggggattcctt
gctagcgtgccttcgggcgtgcc----------------------ggtaggttgagaccc
atc-------aa--acgaaaacatcggctga--------aaggtcggagccagtag----
ttacctttgtaaacccttt-actaaatactgaa--aaactgtggggacgaaagtccttgc
tttt-actagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacg
ctgcgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaac
gcatattgcacttccgggttatgcctggaagtatgcctgtatcagtgtccgtatatcaaa
cttgccttccttccttccgtgtagtcggtggatgggaacgtgcagatgtgaagtgtcttg
gcggcgtc---gcttcgg-cggtgctggcgagtccttttaaatacaagatactgttct-t
ctctttgctcgaaaagc-gt---gtgggatg-tggttgtggaggctgcc-tgcgtggcca
gtc-ggcgactgattt-cgtgctgagacg-----gtggggaggggcttgattcgcggtat
ggttggcttcggctgaactt-ctgcttattgggcttctttc--atgtcttggcg-tatgc
gatttcggtgtaccgtagctgtgtgtggcttggcttttgaaccgtgttc--tgtgtgcga
agtagagtgggca----tgtggtttt---cggactgcgt------------ggccgaggg
gacgag--accttttgggaaattgtgctgctacttttgtggcggcat
>Phytophthora_fallax_NZFS448_DQ297398 Phytophthora_fallax_NZFS448_DQ297398 909 bp 
ccacacct-aaaaaaat--tccacgtgaactgtattgtcaaccaaattcggggattcctt
gctagcgtgccttcgggcgtgcc----------------------ggtaggttgagaccc
atc-------aa--acgaaaacatcggctga--------aaggtcggagccagtag----
ttacctttgtaaacccttt-actaaatactgaa--aaactgtggggacgaaagtccttgc
tttt-actagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacg
ctgcgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaac
gcatattgcacttccgggttatgcctggaagtatgcctgtatcagtgtccgtatatcaaa
cttgccttccttccttccgtgtagtcggtggatgggaacgtgcagatgtgaagtgtcttg
gcggcgtc---gcttcgg-cggtgctggcgagtccttttaaatacaagatactgttct-t
ctctttgctcgaaaagc-gt---gtgggatg-tggttgtggaggctgcc-tgcgtggcca
gtc-ggcgactgattt-cgtgctgagacg-----gtggggaggggcttgattcgcggtat
ggttggcttcggctgaactt-ctgcttattgggcttctttc--atgtcttggcg-tatgc
gatttcggtgtaccgtagctgtgtgtggcttggcttttgaaccgtgttc--tgtgtgcga
agtagagtgggca----tgtggtttt---cggactgcgt------------ggccgaggg
gacgag--accttttgggaaattgtgctgctacttttgtggcggcat
>Phytophthora_frigida_CMW19434_DQ988178 Phytophthora_frigida_CMW19434_DQ988178 909 bp 
ccacacctaaaaaaaactttccacgtgaaccgtatcaacccttttaattggggat-tt--
gcttggtgtgc-ggctagctggcc-ttattggctggcaggctgcgtgctaggcgagtcct
atc-------at-ggcaaacgtttggg-ttc----------ggcttgagctagtag--c-
-ttt-tttttaaaccattt-ctttaatactgat-tatactgtggggacgaaagtctctgc
ttttaactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacg
ctgcgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaac
gcatattgcacttccgggttagtcctggaagtatgcctgtatcagtgtccgtacatcaaa
attggctttcttccttccgtgtagtcggtgga-ggatgtgccagaatgtgaagtgtcttg
cggctgg----ccttcgggttgact--gcgagtccttttaaatgtactgaactgtatt-c
ctctttgctcgaaaagt-aa---g-gcgttgcttgttgtggaggctgcc-cgtgtggcca
gtc-ggcgactggtttgtctgctgcggtgttttactggaggagtgttcgattcgcggtat
ggttggcttcggctgaacag-acgcttattgggt-gtttttcctgctg-tggcg---tga
tggactggtgaaccgtagctatgta-ggcttggcttttgaaccggtgatac-tattgcga
agtagagtgg-------------------cggcttcggc------------tgccgaggg
gtcgat---ccattttgggaacttcatgtgtgtactt----------
>Phytophthora_frigida_CMW19435_DQ988177 Phytophthora_frigida_CMW19435_DQ988177 909 bp 
ccacacctaaaaaaaactttccacgtgaaccgtatcaacccttttaattggggat-tt--
gcttggtgtgc-ggctagctggcc-ttattggctggcaggctgcgtgctaggcgagtcct
atc-------at-ggcaaacgtttggg-ttc----------ggcttgagctagtag--c-
-ttt-tttttaaaccattt-ctttaatactgat-tatactgtggggacgaaagtctctgc
ttttaactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacg
ctgcgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaac
gcatattgcacttccgggttagtcctggaagtatgcctgtatcagtgtccgtacatcaaa
attggctttcttccttccgtgtagtcggtgga-ggatgtgccagaatgtgaagtgtcttg
cggctgg----ccttcgggttgact--gcgagtccttttaaatgtactgaactgtatt-c
ctctttgctcgaaaagt-aa---g-gcgttgcttgttgtggaggctgcc-cgtgtggcca
gtc-ggcgactggtttgtctgctgcggtgttttactggaggagtgttcgattcgcggtat
ggttggcttcggctgaacag-acgcttattgggt-gtttttcctgctg-tggcg---tga
tggactggtgaaccgtagctatgta-ggcttggcttttgaaccggtgatac-tattgcga
agtagagtgg-------------------cggcttcggc------------tgccgaggg
gtcgat---ccattttgggaacttcatgtgtgtactt----------
>Phytophthora_inflata_InfGaul_AY879291 Phytophthora_inflata_InfGaul_AY879291 909 bp 
ccccacct--aaaaaacttttcacgtgaaccgtatcaacccttttagttgggggtctt--
gctttttt------------------------------------------tgcgagccct
atc-------at-ggcgaatgtttggacttc----------ggtctgggctagtag--c-
tttttgttttaaacccatt-ctacaatactgat-tatactgcggggacgaaagtctctgc
ttttaactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacg
ctgcgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaac
gcatattgcacttccgggttagtcctgggagtatgcctgtatcagtgtccgtacatcaaa
cttggctttcttccttccgtgtagtcggtgga-ggatgtgccag-acgtgaagtgtcttg
cgg-gtgt---ccttcgggtcgt--ctgcgagtcctttgaaatgtactgaactgtact-t
ctctttgctcgaaaagc-gt---g-gtgttgctggttgtggaggctgcc-tgcgtggcca
gtc-ggcgaccggtttgtctgctgcggcg-tttaatggaggagtgttcgattcgcggtat
ggttggcttcggctgaacag-gcgcttattgtat-gcttttcctgctg-tggcg---tga
tgggctggtgaaccgtagctgtgtgtggcttggcttttgaatcggctttgc-tgttgcga
agtagagtgg-------------------cggcttcggc------------tgtcga-gg
gtcgat---cca-tttgggaac-ta-agtgtgcacct----------
>Phytophthora_inflata_InfRhod2_AY879293 Phytophthora_inflata_InfRhod2_AY879293 909 bp 
ccccacct--aaaaaacttttcacgtgaaccgtatcaacccttttagttgggggtctt--
gctttttt------------------------------------------tgcgagccct
atc-------at-ggcgaatgtttggacttc----------ggtctgggctagtag--c-
tttttgttttaaacccatt-ctacaatactgat-tatactgcggggacgaaagtctctgc
ttttaactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacg
ctgcgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaac
gcatattgcacttccgggttagtcctgggagtatgcctgtatcagtgtccgtacatcaaa
cttggctttcttccttccgtgtagtcggtgga-ggatgtgccag-acgtgaagtgtcttg
cgg-gtgt---ccttcgggtcgt--ctgcgagtcctttgaaatgtactgaactgtact-t
ctctttgctcgaaaagc-gt---g-gtgttgctggttgtggaggctgcc-tgcgtggcca
gtc-ggcgaccggtttgtctgctgcggcg-tttaatggaggagtgttcgattcgcggtat
ggttggcttcggctgaacag-gcgcttattgtat-gcttttcctgctg-tggcg---tga
tgggctggtgaaccgtagctgtgtgtggcttggcttttgaatcggctttgc-tgttgcga
agtagagtgg-------------------cggcttcggc------------tgtcga-gg
gtcgat---cca-tttgggaac-ta-agtgtgcacct----------
>Phytophthora_inundata_P1032_AF541914 Phytophthora_inundata_P1032_AF541914 909 bp 
ccacacct--aaaaaactttccacgtgaaccgtatcaaccccttaagattgggagctt--
gctcggcggcgtgcgtgctggcctgtaatgggtcggcgtgctgc-tgctgggcgggctct
atc-------atgggcgagcgtttgggcttc----------ggctcgagctagtag---c
tttttcttttaaacccctt-ctttaattactga-aatactgtggggacgaaagtctctgc
ttttaactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacg
ctgcgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaac
gcatattgcacttccgggttcgtcctggaagtatgcctgtatcagtgtccgtacatcaac
cttggttttcttccttccgtgtagtcggtgga-ggatatgccag-acgtgaagtgtcttg
ctagcggt---ctttcgagtctgc-cggcgagtcctttgaaatgtactgaactgtactct
ctctttgctcgaaaagc-gt---g-gcgttgctggttgtggaggctgcc-cgtatggcca
gtc-ggcgaccggtttgttagctgtagta-tatactggaggagtgttcgattcgcggtat
ggttggcttcggctgaacaatctgcttattgggt-gcttttcctgctattggcg---gta
caaactggtgaaccgtagctgtgtggagcttggcttttgaatcggctttgc---ttgcga
agtagagtgg-------------------cggcttcggc------------tgccgaggg
gtcgat---ccattttgggaaatta-tgtgtgtgcggctt-------
>Phytophthora_inundata_P246B_AF266791 Phytophthora_inundata_P246B_AF266791 909 bp 
ccacacct--aaaaaactttccacgtgaaccgtatcaaccccttaagattgggagctt--
gctcggcggcgtgcgtgctggcctgtaatgggtcggcgtgctgc-tgctgggcgggctct
atc-------atgggcgagcgtttgggcttc----------ggctcgagctagtag---c
tttttcttttaaacccctt-ctttaattactga-aatactgtggggacgaaagtctctgc
ttttaactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacg
ctgcgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaac
gcatattgcacttccgggttcgtcctggaagtatgcctgtatcagtgtccgtacatcaac
cttggttttcttccttccgtgtagtcggtgga-ggatatgccag-acgtgaagtgtcttg
ctagcggt---ctttcgagtctgc-cggcgagtcctttgaaatgtactgaactgtactct
ctctttgctcgaaaagc-gt---g-gcgttgctggttgtggaggctgcc-cgtatggcca
gtc-ggcgaccggtttgttagctgtagta-tatactggaggagtgttcgattcgcggtat
ggttggcttcggctgaacaatctgcttattgggt-gcttttcctgctattggcg---gta
caaactggtgaaccgtagctgtgtggagcttggcttttgaatcggctttgc---ttgcga
agtagagtgg-------------------cggcttcggc------------tgccgaggg
gtcgat---ccattttgggaaatta-tgtgtgtgcggctt-------
>Phytophthora_macrochlamydospora_T10455_L41373 Phytophthora_macrochlamydospora_T10455_L41373 909 bp 
ccacacct---aaaacttttccacgtgaaccgtatttttgacg----ttggggactcctg
gct------------------tc----------------------ggccggttgagacct
atc-------ac--gcgaccgctcgggctga--------aaagtcggggccagtag----
cctttttt-taaacccatt-ccgaactactgaaccatactgtggggacgaaagtccttgc
ttttaactagatagcaactttcagcagtggatgtctaggctcgcacatcgatggaggacc
ctgcgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaac
gcatattgcacttccgggttatgcctgggagtatgcctgtatcagtgtccgtacatgaaa
cttggctcccttccttccgtgtagtcggtggatggggacgcgcagacgtgaagtgtcttg
cggcggcg---gcttcggccggctgctgcgagtcctttgaaatgtaagac-ctgttct-t
ctctttgcccgaaaagc-gttgcgtgag-tg-tggttgtggaggctgccgtttgcggcat
gtc-ggcgactgattt-cgtgctgaggcg----tgtggggagaggctcgattcgcggtat
ggttggcttcggctgaactt-ctgcttattggtctttttttcgcggctttggcgttttgc
ggggtcggtgtaccgtagctgcgggtggcttggcctttgaaccgtgttcgtgcggagcga
agtaaggtgggcgtgactgtagtgtt---atggccg-------------------agggg
gacgca--accatttgggaaa-----gtaatgcttttctgccggctt
>Phytophthora_macrochlamydospora_T10456_L41372 Phytophthora_macrochlamydospora_T10456_L41372 909 bp 
ccacacct---aaaacttttccacgtgaaccgtatttttgacg----ttggggactcctg
gct------------------tc----------------------ggccggttgagacct
atc-------ac--gcgaccgctcgggctga--------aaagtcggggccagtag----
cctttttt-taaacccatt-ccgaactactgaaccatactgtggggacgaaagtccttgc
ttttaactagatagcaactttcagcagtggatgtctaggctcgcacatcgatggaggacc
ctgcgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaac
gcatattgcacttccgggttatgcctgggagtatgcctgtatcagtgtccgtacatgaaa
cttggctcccttccttccgtgtagtcggtggatggggacgcgcagacgtgaagtgtcttg
cggcggcg---gcttcggccggctgctgcgagtcctttgaaatgtaagac-ctgttct-t
ctctttgcccgaaaagc-gttgcgtgag-tg-tggttgtggaggctgccgtttgcggcat
gtc-ggcgactgattt-cgtgctgaggcg----tgtggggagaggctcgattcgcggtat
ggttggcttcggctgaactt-ctgcttattggtctttttttcgcggctttggcgttttgc
ggggtcggtgtaccgtagctgcgggtggcttggcctttgaaccgtgttcgtgcggagcga
agtaaggtgggcgtgactgtagtgtt---atggccg-------------------agggg
gacgca--accatttgggaaa-----gtaatgcttttctgccggctt
>Phytophthora_megakarya_IMI337104_AF266782 Phytophthora_megakarya_IMI337104_AF266782 909 bp 
ccacacct---aaaaactttccacgtgaaccgtatc-aacc-tttagttgggggtctt--
tttcggcg-gc-ggctgctggtttaattactggcggttgc-----tgctgggagagccct
atc-------at-ggcgagcgtttgggcttc----------ggtctgaactagtag----
---cttttttaaacccatt-cattattactgat-tatactgtggggacgaaagtctctgc
ttttaactagatagcaactttcagcagtggatgtctaggctcgcacctcgatgaagaacg
ctgcgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaac
gcatattgcacttccgggttagtcctggaagtatgcctgtatcagtgtccgtacatcaaa
cttggttttcttccttccgtgtagtcggtgga-ggatatgccag-atgtgaggtgtcttg
cggctgg----ccttcgggtcgg--ctgtgagtcccttgaaatgtactgaactgtact-t
ctctttgctcgaaaagt-aa---a-gc-ttgcttgttgtggaggctgct-tgtgtaacca
gtc-ggcgactagtttgtctgctgtggcg--ttaatggaggagtgttcgattcgcggtat
gattggcttcggctgaacag-aagcttattgggc-gtttttcctgcta-tggcg---gta
tgaagtagtgaaccgtagttatgtg-ggcttggcttttgaatgtgc-tcgc-tg-tgcga
agtagagtgg-------------------cgactttggt------------tgtcga-gg
gtcgat---ccatttgggaaatt----gtgtgtactt----------
>Phytophthora_megakarya_NS128_AJ517466 Phytophthora_megakarya_NS128_AJ517466 909 bp 
ccacacct---aaaaactttccacgtgaaccgtatc-aacc-tttagttgggggtctt--
tttcggcg-gc-ggctgctggtttaattactggcggttgc-----tgctgggagagccct
atc-------at-ggcgagcgtttgggcttc----------ggtctgaactagtag----
---cttttttaaacccatt-cattattactgat-tatactgtggggacgaaagtctctgc
ttttaactagatagcaactttcagcagtggatgtctaggctcgcacctcgatgaagaacg
ctgcgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaac
gcatattgcacttccgggttagtcctggaagtatgcctgtatcagtgtccgtacatcaaa
cttggttttcttccttccgtgtagtcggtgga-ggatatgccag-atgtgaggtgtcttg
cggctgg----ccttcgggtcgg--ctgtgagtcccttgaaatgtactgaactgtact-t
ctctttgctcgaaaagt-aa---a-gc-ttgcttgttgtggaggctgct-tgtgtaacca
gtc-ggcgactagtttgtctgctgtggcg--ttaatggaggagtgttcgattcgcggtat
gattggcttcggctgaacag-aagcttattgggc-gtttttcctgcta-tggcg---gta
tgaagtagtgaaccgtagttatgtg-ggcttggcttttgaatgtgc-tcgc-tg-tgcga
agtagagtgg-------------------cgactttggt------------tgtcga-gg
gtcgat---ccatttgggaaatt----gtgtgtactt----------
>Phytophthora_megasperma_IMI33317_AF266794 Phytophthora_megasperma_IMI33317_AF266794 909 bp 
ccacacct--aaaaaactttccacgtgaaccgtatcaaccccttaaatttgggggctt--
gctcggcggcgtgtgtgctggcctgtaatgggtcggcgtgctgc-tgctgggcgggctct
atc-------atgggcgagcgtttgggcttc----------ggctcgagctagtag---c
tatcaattttaaacccttt-cttaaatactgaa-catactgtggggacgaaagtctctgc
ttttaactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacg
ctgcgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaac
gcatattgcacttccgggttagtcctgggagtatgcctgtatcagtgtccgtacatcaac
cttggttttcttccttccgtgtagtcggtgga-ggatatgccag-atgtgaagtgtcttg
ctagcggt---ctttcgagtctgc-cggtgagtccttttaaatgtactgaactgtactct
ctctttgcgcgaaaagc-gt---g-gcgttgctggttgtggaggctgcc-cgtgtggcca
gtc-ggcgaccggtttgttagctgtggcg-t---ttggaggagtgttcgattcgcggtat
ggttggcttcggctaaacaatctgcttattgggt-gcttttcctgtca-tggcg---gta
tgaactggtgaaccgtagctgtgtggtgcttggcttttgaaccggctttgc-t-ttgcga
agtagtgtga-------------------cggcttcggc------------tgtcgaggg
gtcgat---ccattttgggaaactt-tgtgtgtgcagctt-------
>Phytophthora_megasperma_SCRP682_DQ116960 Phytophthora_megasperma_SCRP682_DQ116960 909 bp 
ccacacct---aaaaactttccacgtgaaccgtatcaaccccttaaatttgggggctt--
gctcggcggcgtgtgtgctggcctgtaatgggtcggcgtgctgc-tgctgggcgggctct
atc-------atgggcgagcgtttgggcttc----------ggctcgagctagtag---c
tatcaattttaaacccttt-cttaaatactgaa-catactgtggggacgaaagtctctgc
ttttaactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacg
ctgcgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaac
gcatattgcacttccgggttagtcctgggagtatgcctgtatcagtgtccgtacatcaac
cttggttttcttccttccgtgtagtcggtgga-ggatatgccag-atgtgaagtgtcttg
ctagcggt---ctttcgagtctgc-cggtgagtccttttaaatgtactgaactgtactct
ctctttgcgcgaaaagc-gt---g-gcgttgctggttgtggaggctgcc-cgtgtggcca
gtc-ggcgaccggtttgttagctgtggcg-t---ttggaggagtgttcgattcgcggtat
ggttggcttcggctaaacaatctgcttattgggt-gcttttcctgtca-tggcg---gta
tgaactggtgaaccgtagctgtgtggtgcttggcttttgaaccggctttgc-t-ttgcga
agtagtgtga-------------------cggcttcggc------------tgtcgaggg
gtcgat---ccattttgggaaactt-tgtgtgtgcggctt-------
>Phytophthora_melonis_IMI325917_AF266767 Phytophthora_melonis_IMI325917_AF266767 909 bp 
ccacacct--aaaaaactttccacgtgaaccgtatcaa--caagtagttgggggcctg--
ctctgtgtggctagctgtcgatgtcaaagtcggcgactggctgc-tatgtggcgggctct
atc-------at-ggcgattggtttgggtcctcctcgtggggaactggatcatgag----
cccaccttttaaacccatt-cttgattactgaa-tatactgtggggacgaaagtctctgc
ttttaactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacg
ctgcgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaac
gcatattgcacttccgggttagtcctgggagtatgcctgtatcagtgtccgtacatcaaa
cttggctctcttccttccgtgtagtcggtggatggagacgccag-acgtgaggtgtcttg
cggcgcgg---ccttcgggctgc--ctgcgagtcccttgaaatgtactgaactgtact-t
ctctttgctcgaaaagc-gt---g-acgttgttggttgtggaggctgcc-tgtatggcca
gtc-ggcgaccagtttgtctgctgcggcg-tttaatggaggagtgttcgattcgcggtat
ggttggcttcggctgaacaatgcgcttattggat-gcttttcctgctg-tggtg---gta
tgggctggtgaaccgtagttgtgcgaggcttggcttttgaaccggcggtgt-tgtagcga
agtagagtgg-------------------cggcttcggc------------tgtcga-gg
gtcgat---ccatttgggaactctgtgttgtctctgcggctt-----
>Phytophthora_melonis_P12_AY739021 Phytophthora_melonis_P12_AY739021 909 bp 
ccacacct--aaaaaactttccacgtgaaccgtatcaa--caagtagttgggggcctg--
ctctgtgtggctagctgtcgatgtcaaagtcggcgactggctgc-tatgtggcgggctct
atc-------at-ggcgattggtttgggtcctcctcgtggggaactggatcatgag----
ccca-cttttaaacccatt-cttgattactgaa-tatactgtggggacgaaagtctctgc
ttttaactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacg
ctgcgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaac
gcatattgcacttccgggttagtcctgggagtatgcctgtatcagtgtccgtacatcaaa
cttggctctcttccttccgtgtagtcggtggatggagacgccag-acgtgaggtgtcttg
cggcgcgg---ccttcgggctgc--ctgcgagtcccttgaaatgtactgaactgtact-t
ctctttgctcgaaaagc-gt---g-acgttgttggttgtggaggctgcc-tgtatggcca
gtc-ggcgaccagtttgtctgctgcggcg-tttaatggaggagtgttcgattcgcggtat
ggttggcttcggctgaacaatgcgcttattggat-gcttttcctgctg-tggtg---gta
tgggctggtgaaccgtagttgtgcgaggcttggcttttgaaccggcggtgt-tgtagcga
agtagagtgg-------------------cggcttcggc------------tgtcga-gg
gtcgat---ccatttgggaactctgtgttgtctctgcggctt-----
>Phytophthora_multivesiculata_CBS545_96_AF266790 Phytophthora_multivesiculata_CBS545.96_AF266790 909 bp 
ccacacct--aaaaaactttccacgtgaaccgtatcaacccctttagttgggggtctt--
gcttggcgtgc-ggct-gctggcctttattggttggctggctgcgtgctgggcgagccct
atc-------at-ggcgatcgtttggacctc----------ggtctgagctagtag--c-
-ttttgttttaaacccatt-ctttaatactgat-tatactgtggggacgaaagtctctgc
ttttaactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacg
ctgcgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaac
gcatattgcacttccgggttagtcctgggagtatgcctgtatcagtgtccgtacatcaaa
cttggctttcttccttccgtgtagtcggtgga-ggagacgtcag-atgtgaagtgtcttg
cggttgg----ccttcgggtcgt--ctgcgagtcctttgaaatgtactgaactgtactct
ctctttgctcgaaaagc-gt---g-gtattgttggttgtggagactgcc-tgtgtggcca
gtc-ggcgaccggtttgtctgctacggcg-tttaatggaggagtgttcgattcgcggtat
ggttggcttcggctgaacag-acgcttattggac-gtttttcctgctg-tggcg---tga
tgggctggtgaaccgtagctgtgtttggcttggtctttgaatcggctttgc-tgttgcga
agtagagcgg-------------------cggcttcggc------------tgtcgaggg
gtcgat---ccattttgggaag-tt-tgtgtgtactt----------
>Phytophthora_multivesiculata_CDL05_1_DQ835678 Phytophthora_multivesiculata_CDL05.1_DQ835678 909 bp 
ccacacct--aaaaaactttccacgtgaaccgtatcaacccctttagttgggggtctt--
gcttggcgtgc-ggct-gctggcctttattggttggctggctgcgtgctgggcgagccct
atc-------at-ggcgatcgtttggacctc----------ggtctgagctagtag--c-
-ttttgttttaaacccatt-ctttaatactgat-tatactgt-gggacgaaagtctctgc
ttttaactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacg
ctgcgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaac
gcatattgcacttccgggttagtcctgggagtatgcctgtatcagtgtccgtacatcaaa
cttggctttcttccttccgtgtagtcggtgga-ggagacgtcag-atgtgaagtgtcttg
cggttgg----ccttcgggtcgt--ctgcgagtcctttgaaatgtactgaactgtactct
ctctttgctcgaaaagc-gt---g-gtattgttggttgtggagactgcc-tgtgtggcca
gtc-ggcgaccggtttgtctgctacggcg-tttaatggaggagtgttcgattcgcggtat
ggttggcttcggctgaacag-acgcttattggac-gtttttcctgctg-tggcg---tga
tgggctggtgaaccgtagctgtgtttggcttggtctttgaatcggctttgc-tgttgcga
agtagagcgg-------------------cggcttcggc------------tgtcgaggg
gtcgat---ccattttgggaag-tt-tgtgtgtactt----------
>Phytophthora_nicotianae_DDS3453_EU301133 Phytophthora_nicotianae_DDS3453_EU301133 909 bp 
ccacacct--aaaaaactttccacgtgaaccgtttc-aacccaatagttgggggtctt--
atttggcg-gc-ggctgctggcttaattgttggcggctgc-----tgctgagtgagccct
atc-aaaaaaaa-ggcgaacgtttgggcttc----------ggcctgatttagtagtctt
tttttcttttaaacccatt-ccttaatactgaa-tatactgtggggacgaaagtctctgc
ttttaactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacg
ctgcgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaac
gcatattgcacttccgggttagtcctggaagtatgcctgtatcagtgtccgtacattaaa
cttgactttcttccttccgtgtagtcggtgga-ggagatgtcag-atgtgaagtgtcttg
cgattgg----tcttcggaccgg--ctgcgagtccttttaaatgtactaaactgaact-t
ctctttgctcgaaaagtggt---g-gcgttgctggttgtgaaggctgct-attgtggcaa
att-ggcgactggtttgtctgctgcggcg--ttaatggaagagtgttcgattcgtggtat
ggttggcttcggctgaacaatgcacttattggac-gtttttcctgctg-tggcg---tga
tggactggtgaaccatagctcggtg--gcttggcttttgaattggctttgc-tgttgcga
agtagggtgg-------------------cagcttcggt------------tgtcga-gg
gtcgat---ccatttgggaactt---aatgtgtactt----------
>Phytophthora_nicotianae_UQ848_AF266776 Phytophthora_nicotianae_UQ848_AF266776 909 bp 
ccacacct-aaaaaaactttccacgtgaaccgtttc-aacccaatagttgggggtctt--
atttggcg-gc-ggctgctggcttaattgttggcggctgc-----tgctgagtgagccct
atc-aaaaaaaa-ggcgaacgtttgggcttc----------ggcctgatttagtagtctt
tttttcttttaaacccatt-ccttaatactgaa-tatactgtggggacgaaagtctctgc
ttttaactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacg
ctgcgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaac
gcatattgcacttccgggttagtcctggaagtatgcctgtatcagtgtccgtacattaaa
cttgactttcttccttccgtgtagtcggtgga-ggagatgtcag-atgtgaagtgtcttg
cgattgg----tcttcggaccgg--ctgcgagtccttttaaatgtactaaactgaact-t
ctctttgctcgaaaagtggt---g-gcgttgctggttgtgaaggctgct-attgtggcaa
att-ggcgactggtttgtctgctgcggca--ttaatggaagagtgttcgattcgtggtat
ggttggcttcggctgaacaatgcacttattggac-gtttttcctgctg-tggcg---tga
tggactggtgaaccatagctcggtg--gcttggcttttgaattggctttgc-tgttgcga
agtagggtgg-------------------cagcttcggt------------tgtcga-gg
gtcgat---ccatttgggaactt---aatgtgtactt----------
>Phytophthora_nicotianae_VHS16097_EU301134 Phytophthora_nicotianae_VHS16097_EU301134 909 bp 
ccacacct--aaaaaactttccacgtgaaccgtttc-aacccaatagttgggggtctt--
atttggcg-gc-ggctgctggcttaattgttggcggctgc-----tgctgagtgagccct
atcaaaaaaaaa-ggcgaacgtttgggcttc----------ggcctgatttagtagtctt
tttttcttttaaacccatt-ccttaatactgaa-tatactgtggggacgaaagtctctgc
ttttaactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacg
ctgcgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaac
gcatattgcacttccgggttagtcctggaagtatgcctgtatcagtgtccgtacattaaa
cttgactttcttccttccgtgtagtcggtgga-ggagatgtcag-atgtgaagtgtcttg
cgattgg----tcttcggaccgg--ctgcgagtccttttaaatgtactaaactgaact-t
ctctttgctcgaaaagtggt---g-gcgttgctggttgtgaaggctgct-attgtggcaa
att-ggcgactggtttgtctgctgcggcg--ttaatggaagagtgttcgattcgtggtat
ggttggcttcggctgaacaatgcacttattggac-gtttttcctgctg-tggcg---tga
tggactggtgaaccatagctcggtg--gcttggcttttgaattggctttgc-tgttgcga
agtagggtgg-------------------cagcttcggt------------tgtcga-gg
gtcgat---ccatttgggaactt---aatgtgtactt----------
>Phytophthora_niederhauserii_P831_EF050511 Phytophthora_niederhauserii_P831_EF050511 909 bp 
ccacacct--aaaaaactttccacgtgaaccgtatcaa--caagtagttgggggcctg--
ctctgtgtggctggctgtcgatgtcaaagtcgacggctggctgc-tgtgtggcgggctct
atc-------at-ggcgattggtttgggtcctcctcgtggggaactggatcatgag----
cccactttttaaacccatt-cttaaatactgaa-tatactgtggggacgaaagtctctgc
ttttaactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacg
ctgcgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaac
gcatattgcacttccgggttagtcctgggagtatgcctgtatcagtgtccgtacatcaaa
cttggctctcttccttccgtgtagtcggtggatggagacgccag-acgtgaggtgtcttg
cggcgcgg---ccttcgggctgc--ctgcgagtcccttgaaatgtactgaactgtact-t
ctctttgctcgaaaagc-gt---g-acgttgttggttgtggaggctgcc-tgtatggcca
gtc-ggcgaccggtttgtctgctgcggcg-tttaatggaggagtgttcgattcgcggtat
ggttggcttcggctgaacaatgcgcttattggat-gcttttcctgctg-tggcg---gta
tgggctggtgaaccgtagctgtgcgaggcttggcttttgaaccggcggtgt-tgttgcga
agtagggtgg-------------------cggcttcggc------------tgtcga-gg
gtcgat---ccatttgggaactctgtgttgtctctgcggctt-----
>Phytophthora_niederhauserii_VHS17577_EU301137 Phytophthora_niederhauserii_VHS17577_EU301137 909 bp 
ccacacct--aaaaaactttccacgtgaaccgtatcaa--caagtagttgggggcctg--
ctctgtgtggctgtctgtcgatgtcaaagtcgacggctggctgc-tgtgtggcgggctct
atc-------at-ggcgattggtttgggtcctcctcgtggggaactggatcatgag----
cccactttttaaacccatt-cttaaatactgaa-tatactgtggggacgaaagtctctgc
ttttaactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacg
ctgcgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaac
gcatattgcacttccgggttagtcctgggagtatgcctgtatcagtgtccgtacatcaaa
cttggctctcttccttccgtgtagtcggtggatggagacgccag-acgtgaggtgtcttg
cggcgcgg---ccttcgggctgc--ctgcgagtcccttgaaatgtactgaactgtact-t
ctctttgctcgaaaagc-gt---g-acgttgttggttgtggaggctgcc-tgtatggcca
gtc-ggcgaccggtttgtctgctgcggcg-tttaatggaggagtgttcgattcgcggtat
ggttggcttcggctgaacaatgcgcttattggat-gcttttcctgctg-tggcg---gta
tgggctggtgaaccgtagctgtgcgaggcttggcttttgaaccggcggtgt-tgttgcga
agtagggtgg-------------------cggcttcggc------------tgtcga-gg
gtcgat---ccatttgggaactctgtgttgtctctgcggctt-----
>Phytophthora_palmivora_TARS8_DQ987922 Phytophthora_palmivora_TARS8_DQ987922 909 bp 
ccacacct---aaaaactttccacgtgaaccgtatc-aaaa-cttagttgggggtctc--
tttcggcg-gc-ggctgctggcttcattgctggcggctgc-----tgttgggagagctct
atc-------at-ggcgagcgtttgggcttc----------ggtctgaactagtag----
---cttttttaaacccatt-ctttataactgat-tatactgtagggacgaaagtctctgc
ttttaactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacg
ctgcgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaac
gcatattgcacttccgggttagtcctgggagtatgcctgtatcagtgtccgtacatcaaa
cttggttttcttccttccgtgtagtcggtggt-ggatgtgccag-atgtgaagtgtcttg
cggctgg----tcttcggatcgg--ctgtgagtcctttgaaatgtactgaactgtact-t
ctctttgctccaaaagc-gt---g-gcgttgctgattgtggaggctgct-tgcgtagcca
gtctggcgaccagtttgtctgctgtggcg--ttaatggaggagtgttcgattcgcggtat
ggttggcttcggctgaacag-acgcttattgaat-atttcttcagctg-tggtg---gta
t-gattggtgaaccgtagctatgtg-agcttggcttttgaattggctttgc-tgttgcga
agtagagtgg-------------------cggcttcggc------------tgtcga-gg
gtcgat---ccatttgggaactt----gtgtatgctt----------
>Phytophthora_palmivora_UQ1294_AF266780 Phytophthora_palmivora_UQ1294_AF266780 909 bp 
ccacacct--aaaaaactttccacgtgaaccgtatc-aaaa-cttatttgggggtctc--
tttcggcg-gc-ggctgctggcttcattgctggcggctgc-----tgttgggagagctct
atc-------at-ggcgagcgtttgggcttc----------ggtctgaactagtag----
---cttttttaaacccatt-ctttataactgat-tatactgtagggacgaaagtctctgc
ttttaactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacg
ctgcgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaac
gcatattgcacttccgggttagtcctgggagtatgcctgtatcagtgtccgtacatcaaa
cttggttttcttccttccgtgtagtcggtggt-ggatgtgccag-atgtgaagtgtcttg
cggctgg----tcttcggatcgg--ctgtgagtcctttgaaatgtactgaactgtact-t
ctctttgctccaaaagc-gt---g-gcgttgctgattgtggaggctgct-tgcgtagcca
gtctggcgaccagtttgtctgctgtggcg--ttaatggaggagtgttcgattcgcggtat
ggttggcttcggctgaacag-acgcttattgaat-atttcttcagctg-tggtg---gta
t-gattggtgaaccgtagctatgtg-agcttggcttttgaattggctttgc-tgttgcga
agtagagtgg-------------------cggcttcggc------------tgtcga-gg
gtcgat---ccatttgggaactt----gtgtatgctt----------
>Phytophthora_quercetorum_MND4_EF539180 Phytophthora_quercetorum_MND4_EF539180 909 bp 
ccacacct--aaaaaactttccacgtgaaccgtatc-aaac-tttagttgggggtctt--
tttcggcg-ac-ggctgctggcttcattgctggcggctgc-----tgttggatgagccct
atc-------at-ggcgagcgtttgggcttc----------ggtctgaactagtag----
---cttttttaaacccatt-ctttattactgat-tatactgtggggacgaaagtctctgc
ttttaactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacg
ctgcgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaac
gcatattgcacttccgggttagtcctgggagtatgcctgtatcagtgtccgtacatcaaa
cttggctttcttccttccgtgtagtcggtgga-ggatgtgccag-atgtgaagtgtcttg
cggctgg----tcttcgggtcgg--ctgtgagtcctttgaaatgtactgaactgtact-t
ctctttgctcgaaaagc-gt---g-gcgttgctgattgtggaggctgcc-tgcgtagcca
gtctggcgaccagtttgtctgctgtggcg--ttaatggaggagtgttcgattcgcggtat
ggttggcttcggctgaacag-acgcttattgaat-gtttttcctgctg-tggcg---gta
cgggttggtgaaccgtagctatgtg-ggcttggcttttgaattggctttgc-tgttgcga
agtagagtgg-------------------cagcttcggc------------tgtcga-gg
gtcgat---ccatttgggaattt----gtgtgtactt----------
>Phytophthora_quercetorum_WI111_EF539179 Phytophthora_quercetorum_WI111_EF539179 909 bp 
ccacacct--aaaaaactttccacgtgaaccgtatc-aaac-tttagttgggggtctt--
tttcggcg-ac-ggctgctggcttcattgctggcggctgc-----tgttggatgagccct
atc-------at-ggcgagcgtttgggcttc----------ggtctgaactagtag----
---cttttttaaacccatt-ctttattactgat-tatactgtggggacgaaagtctctgc
ttttaactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacg
ctgcgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaac
gcatattgcacttccgggttagtcctgggagtatgcctgtatcagtgtccgtacatcaaa
cttggctttcttccttccgtgtagtcggtgga-ggatgtgccag-atgtgaagtgtcttg
cggctgg----tcttcgggtcgg--ctgtgagtcctttgaaatgtactgaactgtact-t
ctctttgctcgaaaagc-gt---g-gcgttgctgattgtggaggctgcc-tgcgtagcca
gtctggcgaccagtttgtctgctgtggcg--ttaatggaggagtgttcgattcgcggtat
ggttggcttcggctgaacag-acgcttattgaat-gtttttcctgctg-tggcg---gta
cgggttggtgaaccgtagctatgtg-ggcttggcttttgaattggctttgc-tgttgcga
agtagagtgg-------------------cagcttcggc------------tgtcga-gg
gtcgat---ccatttgggaattt----gtgtgtactt----------
>Phytophthora_sp__1_DDS1221_EU593265 Phytophthora_sp._1_DDS1221_EU593265 909 bp 
ccacacct--aaaaaactttccacgtgaaccgtatc-aaac-tttagttgggggtctt--
tttcggcg-ac-ggctgctggcttcattgctggcggctgc-----tgttgaatgagccct
atc-------at-ggcgagcgtttaggcttc----------ggtctgaactagtag----
---cttttttaaacccatt-ctttattactgat-tatactgtggggacgaaagtctctgc
ttttaactagatagcaactttcagcagtggatgtctaggctcgcacatngatgaagaacg
ctgcgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaac
gcatattgcacttccgggttagtcctgggagtatgcctgtatcagtgtccgtacatcaaa
cttggctttcttccttccgtgtagtcggtgga-agatgtgccag-atgtgaagtgtcttg
cggctgg----tcttcgggtcgg--ctgtgagtcctttgaaatgtactgaactgtact-t
ctctttgctcgaaaagc-gt---g-gcgttgctgattgtggaggctgcc-tgcgtagcca
gtctggcgaccagtttgtctgctgtggcg--ttaatggaggagtgttcgattcgcggtat
ggttggctttggctgaacag-acgcttattgaat-gtttttcctgcta-tggcg---gta
cgggttggtgaaccgtagctatgtg-ggcttggcttttgaattggctttgc-tgttgcga
agtagagtgg-------------------cggcttcggc------------tgtcga-gg
gtcgat---ccatttgggaattt----gtgtgtactt----------
>Phytophthora_sp__1_VHS10154_EU301114 Phytophthora_sp._1_VHS10154_EU301114 909 bp 
ccacacct--aaaaaactttccacgtgaaccgtatc-aaac-tttagttgggggtctt--
tttcggcg-ac-ggctgctggcttcattgctggcggctgc-----tgttgaatgagccct
atc-------at-ggcgagcgtttaggcttc----------ggtctgaactagtag----
---cttttttaaacccatt-ctttattactgat-tatactgtagggacgaaagtctctgc
ttttaactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacg
ctgcgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaac
gcatattgcacttccgggttagtcctgggagtatgcctgtatcagtgtccgtacatcaaa
cttggctttcttccttccgtgtagtcggtgga-agatgtgccag-atgtgaagtgtcttg
cggctgg----tcttcgggtcgg--ctgtgagtcctttgaaatgtactgaactgtact-t
ttctttgctcg-aaagc-gt---g-gcgttgctgattgtggaggctgcc-tgcgtagcca
gtctggcgaccagtttgtctgctgtggcg--ttaatggaggagtgttcgattcgcggtat
ggttggctttggctgaacag-acgcttattgaat-gtttttcctgcta-tggcg---gta
cgggttggtgaaccgtagctatgtg-ggcttggcttttgaattggctttgc-tgttgcga
agtagagtgg-------------------cggcttcggc------------tgtcga-gg
gtcgat---ccatttgggaattt----gtgtgtactt----------
>Phytophthora_sp__1_VHS9861_EU301118 Phytophthora_sp._1_VHS9861_EU301118 909 bp 
ccacacct--aaaaaactttccacgtgaaccgtatc-aaac-tttagttgggggtctt--
tttcggcg-ac-ggctgctggcttcattgctggcggctgc-----tgttgaatgagccct
atc-------at-ggcgagcgtttaggcttc----------ggtctgaactagtag----
---cttttttaaacccatt-ctttattactgat-tatactgtggggacgaaagtctctgc
ttttaactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacg
ctgcgaactgcgatacgtaatgcgaattgcaggattcagtgagtnatcgaaattttgaac
gcatattgcacttccgggttagtcctgggagtatgcctgtatcagtgtccgtacatcaaa
cttggctttcttccttccgtgtagtcggtgga-agatgtgccag-atgtgaagtgtcttg
cggctgg----tcttcgggtcgg--ctgtgagtcctttgaaatgtactgaactgtact-t
ctctttgctcgaaaagc-gt---g-gcgttgctgattgtggaggctgcc-tgcgtagcca
gtctggcgaccagtttgtctgctgtggcg--ttaatggaggagtgttcgattcgcggtat
ggttggctttggctgaacag-acgcttattgaat-gtttttcctgcta-tggcg---gta
cgggttggtgaaccgtagctatgtg-ggcttggcttttgaattggctttgc-tgttgcga
agtagagtgg-------------------cggcttcggc------------tgtcga-gg
gtcgat---ccatttgggaattt----gtgtgtactt----------
>Phytophthora_sp__2_VHS13559_EU301121 Phytophthora_sp._2_VHS13559_EU301121 909 bp 
ccacacct-aaaaaaactttccacgtgaaccgtatcaaccctttaaattgggggtctt--
gcttggtgtgc-ggctggctggcctttattggctggcaggctgcgtgctgggcgagccct
atc-------at-ggcaaacgtttgggcttc----------ggtctgagctagtag--c-
-tttatttttaaacccatt-tcttaatactgat-tatactgtggggacgaaagtctctgc
ttttaactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacg
ctgcgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaac
gcatattgcacttccgggttagtcctgggagtatgcctgtatcagtgtccgtacatcaaa
cttggctttcttccttccgtgtagtcggtgga-ggagacgccag-atgtgaagtgtcttg
cggctgg----ctttcgggccgact--gcgagtcctttgaaatgtactgaactgtact-t
ctctttgctcgaaaagt-gt---g-gcgttgctggttgtggaggctgcc-cgcgtggcca
gtc-ggcgaccggtttgtctgctgcggcgttttactggaggagtgttcgattcgcggtat
ggttggcttcggctgaacag-gcgcttattggac-gtttttcctgctg-tggcg---tga
tgggctggtgaaccgtagctgtgtgtggcttggcttttgaatcggttttgc-tattgcga
agtagagtgg-------------------cggcttcggc------------tgtcgaggg
gtcgat---ccattttgggaaactt-tgtgtgtactt----------
>Phytophthora_sp__2_VHS13663_EU301123 Phytophthora_sp._2_VHS13663_EU301123 909 bp 
ccacacct-aaaaaaactttccacgtgaaccgtatcaaccctttaaattgggggtctt--
gcttggtgtgc-ggctggctggcctttattggctggcaggctgcgtgctgggcgagccct
atc-------at-ggcaaacgtttgggcttc----------ggtctgagctagtag--c-
-tttatttttaaacccatt-tcttaatactgat-tatactgtggggacgaaagtctctgc
ttttaactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacg
ctgcgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaac
gcatattgcacttccgggttagtcctgggagtatgcctgtatcagtgtccgtacatcaaa
cttggctttcttccttccgtgtagtcggtgga-ggagacgccag-atgtgaagtgtcttg
cggctgg----ctttcgggccgact--gcgagtcctttgaaatgtactgaactgtact-t
ctctttgctcgaaaagt-gt---g-gcgttgctggttgtggaggctgcc-cgcgtggcca
gtc-ggcgaccggtttgtctgctgcggcgttttactggaggagtgttcgattcgcggtat
ggttggcttcggctgaacag-gcgcttattggac-gtttttcctgctg-tggcg---tga
tgggctggtgaaccgtagctgtgtgtggcttggcttttgaatcggttttgc-tattgcga
agtagagtgg-------------------cggcttcggc------------tgtcgaggg
gtcgat---ccattttgggaaactt-tgtgtgtactt----------
>Phytophthora_sp__2_VHS16103_EU301125 Phytophthora_sp._2_VHS16103_EU301125 909 bp 
ccacacct-aaaaaaactttccacgtgaaccgtatcaaccctttaaattgggggtctt--
gcttggtgtgc-ggctggctggcctttattggctggcaggctgcgtgctgggcgagccct
atc-------at-ggcaaacgtttgggcttc----------ggtctgagctagtag--c-
-tttatttttaaacccatt-tcttaatactgat-tatactgtggggacgaaagtctctgc
ttttaactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacg
ctgcgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaac
gcatattgcacttccgggttagtcctgggagtatgcctgtatcagtgtccgtacatcaaa
cttggctttcttccttccgtgtagtcggtgga-ggagacgccag-atgtgaagtgtcttg
cggctgg----ctttcgggccgact--gcgagtcctttgaaatgtactgaactgtact-t
ctctttgctcgaaaagt-gt---g-gcgttgctggttgtggaggctgcc-cgcgtggcca
gtc-ggcgaccggtttgtctgctgcggcgttttactggaggagtgttcgattcgcggtat
ggttggcttcggctgaacag-gcgcttattggac-gtttttcctgctg-tggcg---tga
tgggctggtgaaccgtagctgtgtgtggcttggcttttgaatcggttttgc-tattgcga
agtagagtgg-------------------cggcttcggc------------tgtcgaggg
gtcgat---ccattttgggaaactt-tgtgtgtactt----------
>Phytophthora_sp__4_DDS3438_EU301128 Phytophthora_sp._4_DDS3438_EU301128 909 bp 
ccacacct--aaaaaactttccacgtgaaccgtatcaaccctttcagttgggggcctt--
gc-ttttt------------------------------------------tgcgagccct
atc-------at-ggcgaatgtttggacttc----------ggtctgggctagtag--c-
tttttgttttaaacccatt-ctacaatactgat-tatactgtggggacgaaagtctctgc
ttttaactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacg
ctgcgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaac
gcatattgcacttccgggttagtcctgggagtatgcctgtatcagtgtccgtacatcaaa
cttggctttcttccttccgtgtagtcggtgga-ggatgtgccag-atgtgaagtgtcttg
cag-gtgt---ccttcgggtcgt--ctgcgagtcctttgaaatgtactgaactgtact-t
ctctttgctcgaaaagc-gt---g-gcgttgctggttgtggaggctgcc-tgcgtggcca
gtc-ggcgaccggtttgtctgctgcggcg-tttaatggaggagtgttcgattcgcggtat
ggttggcttcggctgaacag-gcgcttattgtat-gcttttcctgctg-tggcg---tga
tggactggtgaaccgtagctgtgtgtggcttggcttttgaatcggctttgc-tgttgcga
agtagagtgg-------------------cggcttcggc------------tgtcga-gg
gtcgat---cca-tttgggaac-tt-tgtgtgcacct----------
>Phytophthora_sp__4_HSA1210_EU301130 Phytophthora_sp._4_HSA1210_EU301130 909 bp 
ccacacct--aaaaaactttccacgtgaaccgtatcaaccctttcagttgggggcctt--
gc-ttttt------------------------------------------tgcgagccct
atc-------at-ggcgaatgtttggacttc----------ggtctgggctagtag--c-
tttttgttttaaacccatt-ctacaatactgat-tatactgtggggacgaaagtctctgc
ttttaactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacg
ctgcgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaac
gcatattgcacttccgggttagtcctgggagtatgcctgtatcagtgtccgtacatcaaa
cttggctttcttccttccgtgtagtcggtgga-ggatgtgccag-atgtgaagtgtcttg
cag-gtgt---ccttcgggtcgt--ctgcgagtcctttgaaatgtactgaactgtact-t
ctctttgctcgaaaagc-gt---g-gcgttgctggttgtggaggctgcc-tgcgtggcca
gtc-ggcgaccggtttgtctgctgcggcg-tttaatggaggagtgttcgattcgcggtat
ggttggcttcggctgaacag-gcgcttattgtat-gcttttcctgctg-tggcg---tga
tggactggtgaaccgtagctgtgtgtggcttggcttttgaatcggctttgc-tgttgcga
agtagagtgg-------------------cggcttcggc------------tgtcga-gg
gtcgat---cca-tttgggaac-tt-tgtgtgcacct----------
>Phytophthora_sp__4_IMI133316_EU301126 Phytophthora_sp._4_IMI133316_EU301126 909 bp 
ccacacct--aaaaaactttccacgtgaaccgtatcaaccctttcagttgggggcctt--
gc-ttttt------------------------------------------tgcgagccct
atc-------at-ggcgaatgtttggacttc----------ggtctgggctagtag--c-
tttttgttttaaacccatt-ctacaatactgat-tatactgtggggacgaaagtctctgc
ttttaactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacg
ctgcgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaac
gcatattgcacttccgggttagtcctgggagtatgcctgtatcagtgtccgtacatcaaa
cttggctttcttccttccgtgtagtcggtgga-ggatgtgccag-atgtgaagtgtcttg
cag-gtgt---ccttcgggtcgt--ctgcgagtcctttgaaatgtactgaactgtact-t
ctctttgctcgaaaagc-gt---g-gcgttgctggttgtggaggctgcc-tgcgtggcca
gtc-ggcgaccggtttgtctgctgcggcg-tttaatggaggagtgttcgattcgcggtat
ggttggcttcggctgaacag-gcgcttattgtat-gcttttcctgctg-tggcg---tga
tggactggtgaaccgtagctgtgtgtggcttggcttttgaatcggctttgc-tgttgcga
agtagagtgg-------------------cggctccggc------------tgtcga-gg
gtcgat---cca-tttgggaac-tt-tgtgtgcacct----------
>Phytophthora_sp__4_IMI329674_EU301127 Phytophthora_sp._4_IMI329674_EU301127 909 bp 
ccacacct--aaaaaactttccacgtgaaccgtatcaaccctttcagttgggggcctt--
gc-ttttt------------------------------------------tgcgagccct
atc-------at-ggcgaatgtttggacttc----------ggtctgggctagtag--c-
tttttgttttaaacccatt-ctacaatactgat-tatactgtggggacgaaagtctctgc
ttttaactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacg
ctgcgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaac
gcatattgcacttccgggttagtcctgggagtatgcctgtatcagtgtccgtacatcaaa
cttggctttcttccttccgtgtagtcggtgga-ggatgtgccag-atgtgaagtgtcttg
cag-gtgt---ccttcgggtcgt--ctgcgagtcctttgaaatgtactgaactgtact-t
ctctttgctcgaaaagc-gt---g-gcgttgctggttgtggaggctgcc-tgcgtggcca
gtc-ggcgaccggtttgtctgctgcggcg-tttaatggaggagtgttcgattcgcggtat
ggttggcttcggctgaacag-gcgcttattgtat-gcttttcctgctg-tggcg---tga
tggactggtgaaccgtagctgtgtgtggcttggcttttgaatcggctttgc-tgttgcga
agtagagtgg-------------------cggctccggc------------tgtcga-gg
gtcgat---cca-tttgggaac-tt-tgtgtgcacct----------
>Phytophthora_sp__4_MJS278_EU301131 Phytophthora_sp._4_MJS278_EU301131 909 bp 
ccacacct--aaaaaactttccacgtgaaccgtatcaaccctttcagttgggggcctt--
gc-ttttt------------------------------------------tgcgagccct
atc-------at-ggcgaatgtttggacttc----------ggtctgggctagtag--c-
tttttgttttaaacccatt-ctacaatactgat-tatactgtggggacgaaagtctctgc
ttttaactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacg
ctgcgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaac
gcatattgcacttccgggttagtcctgggagtatgcctgtatcagtgtccgtacatcaaa
cttggctttcttccttccgtgtagtcggtgga-ggatgtgccag-atgtgaagtgtcttg
cag-gtgt---ccttcgggtcgt--ctgcgagtcctttgaaatgtactgaactgtact-t
ctctttgctcgaaaagc-gt---g-gcgttgctggttgtggaggctgcc-tgcgtggcca
gtc-ggcgaccggtttgtctgctgcggcg-tttaatggaggagtgttcgattcgcggtat
ggttggcttcggctgaacag-gcgcttattgtat-gcttttcctgctg-tggcg---tga
tggactggtgaaccgtagctgtgtgtggcttggcttttgaatcggctttgc-tgttgcga
agtagagtgg-------------------cggctccggc------------tgtcga-gg
gtcgat---cca-tttgggaac-tt-tgtgtgcacct----------
>Phytophthora_sp__9_MJS186_EU301148 Phytophthora_sp._9_MJS186_EU301148 909 bp 
ccacacct-taaaaaaccatccacgtgaaccgtattgtcaa-aacatttggggactcctt
gctagcgggctttcgggcttgcc----------------------ggtcggttgagacct
a---------ac--acgagagccttggctga--------aaagccggggtgagtag----
tttc-ttt-taaacccttt-actaaaaactgaa--aaactgtggggacgaaagtccttgc
tttt-actagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacg
ctgcgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaac
gcatattgcacttccgggttatgcctggaagtatgcctgtatcagtgtccgtatatcaaa
cttgccttccttccttccgtgtagtcggtggatgggaacgtgcagatgtgaagtgtcttg
gcggcgtc---gctttgg-cggtgctggcgagtccttttaaatacaagatactgttct-t
ctctttgctcgaaaagc-gt---gtgggatg-tggttgtggaggctgcc-tgcgtggcat
gtc-ggcgactgattt-cgtgctgaggcg-----ttggaggtgggcttgattcgcggtat
ggttggcttcggctgaactt-ctgcttattgggttctaatc--ttgctttggcg-tatgc
ggggtcggtgtaccgtagtcgtgtg-ggcttggcttttgaaccgtgttt--tgcgtgcga
agtagagtggccg----tgtggtttt---cggactgcgt------------ggccgaggg
aacgag--accttttgggaaattgtgctgctacttttgtggcggcat
>Phytophthora_sp__9_TCH003_EU301149 Phytophthora_sp._9_TCH003_EU301149 909 bp 
ccacacct-taaaaaaccatccacgtgaaccgtattgtcaa-aacatttggggactcctt
gctagcgggctttcgggcttgcc----------------------ggtcggttgagacct
a---------ac--acgagagccttggctga--------aaagccggggtgagtag----
tttc-ttt-taaacccttt-actaaaaactgaa--aaactgtggggacgaaagtccttgc
tttt-actagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacg
ctgcgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaac
gcatattgcacttccgggttatgcctggaagtatgcctgtatcagtgtccgtatatcaaa
cttgccttccttccttccgtgtagtcggtggatgggaacgtgcagatgtgaagtgtcttg
gcggcgtc---gctttgg-cggtgctggcgagtccttttaaatacaagatactgttct-t
ctctttgctcgaaaagc-gt---gtgggatg-tggttgtggaggctgcc-tgcgtggcat
gtc-ggcgactgattt-cgtgctgaggcg-----ttggaggtgggcttgattcgcggtat
ggttggcttcggctgaactt-ctgcttattgggttctaatc--ttgctttggcg-tatgc
ggggtcggtgtaccgtagtcgtgtg-ggcttggcttttgaaccgtgttt--tgcgtgcga
agtagagtggccg----tgtggtttt---cggactgcgt------------ggccgaggg
aacgag--accttttgggaaattgtgctgctacttttgtggcggcat
>Phytophthora_sp__9_VHS16234_EU301150 Phytophthora_sp._9_VHS16234_EU301150 909 bp 
ccacacct-taaaaaaccatccacgtgaaccgtattgtcaa-aacatttggggactcctt
gctagcgggctttcgggcttgcc----------------------ggtcggttgagacct
a---------ac--acgagagccttggctga--------aaagccggggtgagtag----
tttctttt-taaacccttt-actaaaaactgaa--aaactgtggggacgaaagtccttgc
tttt-actagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacg
ctgcgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaac
gcatattgcacttccgggttatgcctggaagtatgcctgtatcagtgtccgtatatcaaa
cttgccttccttccttccgtgtagtcggtggatgggaacgtgcagatgtgaagtgtcttg
gcggcgtc---gctttgg-cggtgctggcgagtccttttaaatacaagatactgttct-t
ctctttgctcgaaaagc-gt---gtgggatg-tggttgtggaggctgcc-tgcgtggcat
gtc-ggcgactgattt-cgtgctgaggcg-----ttggaggtgggcttgattcgcggtat
ggttggcttcggctgaactt-ctgcttattgggttctaatc--ttgctttggcg-tatgc
ggggtcggtgtaccgtagtcgtgtg-ggcttggcttttgaaccgtgttt--tgcgtgcga
agtagagtggccg----tgtggtttt---cggactgcgt------------ggccgaggg
aacgag--accttttgggaaattgtgctgctacttttgtggcggcat
>Phytophthora_tropicalis_H213_AY207010 Phytophthora_tropicalis_H213_AY207010 909 bp 
ccacacct--aaaaaactttccacgtgaaccgtatcgacccttttagttgggggtctt--
gt-----------------------------------------------------accct
atc-------at-ggcgaatgtttggacttc----------ggtctgggcgagtag--c-
tttttgttttaaacccatt-tctcaatactgat-tatactgcggggacgaaagtctctgc
ttttaactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacg
ctgcgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaac
gcatattgcacttccgggttagtcctgggagtatgcctgtatcagtgtccgtacatcaaa
cttggctttcttccttccgtgtagtcggtgga-ggatgtgccag-atgtgaagtgtcttg
cggtttgt---ccttcgggtcgg--ctgcgagtccttttaaatgtactgaactgtact-t
ctctttgctcgaaaagc-gt---g-gtgttgctggttgtggaggctgcc-tgcgtggcca
gtc-ggcgaccggtttgtctgctgcggcg-tttaatggaggagtgttcgattcgcggtat
ggttggcttcggctgaacag-gcgcttattgtat-gcttttcctgctg-tggcg---tga
tgggctggtgaaccgtagctgtgtgtggcttggcttttgaatcggctttgc-tgttgcga
agtagagtgg-------------------cggcttcggc------------tgtcga-gg
gtcgat---ccattttgggaac-tt-tgtgtgcactt----------
>Phytophthora_tropicalis_P4742_AY946257 Phytophthora_tropicalis_P4742_AY946257 909 bp 
ccacacct--aaaaaactttccacgtgaaccgtatcgacccttttagttgggggtctt--
gt-----------------------------------------------------accct
atc-------at-ggcgaatgtttggacttc----------ggtctgggcgagtag--c-
tttttgttttaaacccatt-tctcaatactgat-tatactgcggggacgaaagtctctgc
ttttaactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacg
ctgcgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaac
gcatattgcacttccgggttagtcctgggagtatgcctgtatcagtgtccgtacatcaaa
cttggctttcttccttccgtgtagtcggtgga-ggatgtgccag-atgtgaagtgtcttg
cggtttgt---ccttcgggtcgg--ctgcgagtccttttaaatgtactgaactgtact-t
ctctttgctcgaaaagc-gt---g-gtgttgctggttgtggaggctgcc-tgcgtggcca
gtc-ggcgaccggtttgtctgctgcggcg-tttaatggaggagtgttcgattcgcggtat
ggttggcttcggctgaacag-gcgcttattgtat-gcttttcctgctg-tggcg---tga
tgggctggtgaaccgtagctgtgtgtggcttggcttttgaatcggctttgc-tgttgcga
agtagagtgg-------------------cggcttcggc------------tgtcga-gg
gtcgat---ccattttgggaac-tt-tgtgtgcactt----------
>END; 1 bp 
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------n
