>Phytophthora_arecae 900 bp 
ccacacct--aaaaactttccacgtgaaccgtatcaaaact---tagttgggggtctct-
ttcggcg-g--cggctgctggcttcattgctggcggct----gctgttgggagagctcta
tc------a-tggcgagc-gtttgggctt---------cggtctgaactagtag------
-cttttttaaacccattc-tttataactgattatactgtagggacgaaagtctctgcttt
taactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacgctg
cgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaacgca
tattgcacttccgggttagtcctgggagtatgcctgtatcagtgtccgtacatcaaactt
ggttttcttccttccgtgtagtcggtggt-ggatgtgc-cagatgtgaagtgtcttgcgg
-ctggt----cttcggatcgg--ctgtgagtcctttgaaatgtactgaactgtact-tct
ctttgctccaaaagc-gtggcgttgctgattgtggaggctgcttgcgtagccagtctggc
gaccagtttgtctgctgtggcg--ttaatggaggagtgttcgattcgcggtatggttggc
ttcggctgaacag-acgcttattgaatatt-tcttcagctg-tggtggtatg-attggtg
aaccgtagctatgtg-agcttggcttttgaattggctttgct-gttgcgaagtagagtgg
cggct------------------tcggctgtcga-gggtcgatcc-atttgggaact---
-tgtgt------------------at---gcttcg---gc-atgcatctcaa
>Phytophthora_cactorum 900 bp 
ccacacct--aaaaactttccacgtgaaccgtttcaaaccaa-atagttgggggtcttg-
tctggtg-g--cggctgctggctttattgttggcggct----gctgctgggtgagcccta
tc------a-tggcgagc-gtttgggctt---------cggcctgagctagtag--cttt
tc--ttttaaacccattc-cttaatactgattatactgtggggacgaaagtccttgcttt
taactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacgctg
cgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaacgca
tattgcacttccgggttagtcctgggagtatgcctgtatcagtgtccgtacatcaaactt
ggctttcttccttccgtgtagtcggtgga-ggagatgc-cagatgtgaagtgtcttgcgg
-ctggt----tttcggaccga--ctgcgagtccttttaaatgtactgaactgtact-tct
ctttgctcgaaaagc-gtggcgttgctggttgtggaggctgctattgtagcaagtt-ggc
gaccggtttgtctgctgcggcg--ttaatggaagagtgttcgattcgcggtatggttagc
ttcggctgaacaatgcgcttattggatgtt-ttttctgctg-tggcgtgatggaccggtg
aaccatagc--tcagttgcttggcttttgaatcggctttgct-gttgcgaagtagagtgg
cggct------------------tcggctgtcga-gggtcgatcc-atttgggaaatg--
-tgtgt------------------gt---acttcg---gt-atgcatctcaa
>Phytophthora_capsici 900 bp 
ccacacct-aaaaaactttccacgtgaaccgtatcaaccctt-ttagttgggggtcttg-
-------------------------------------------t----------acccta
tc------a-tggcgaat-gtttggactt---------cggtccgggcgagtag---ctt
tttgttttaaacccattt-cacaattctgattatactgtggggacgaaagtctctgcttt
taactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacgctg
cgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaacgca
tattgcacttccgggttagtcctgggagtatgcctgtatcagtgtccgtacatcaaactt
ggctttcttccttccgtgtagtcggtgga-ggatgtgc-cagatgtgaagtgtcttgcgt
-gttgt---ccttcgggtcga--ctgcgagtccttttaaatgtactgaactgtact-tct
ctttgctcgaaaagc-gtggtgttgctggttgtggaggctgcctgcgtggccagtc-ggc
gaccggtttgtctgctgcggcg-tttaaaggaggagtgttcgattcgcggtatggttggc
ttcggctgaacag-gcgcttattgaatgct-tttcctgctg-tggcgtgatgggctggtg
aaccgtagctgtgtttggcttggcttttgaatcggctttgct-gttgcgaagtagggtgg
cggct------------------tcggctgtcga-gggtcgatcc-attttgggaact--
-t---t------------------gtgtgcacttcg--gt-gcgcatctcaa
>Phytophthora_cinnamomi 900 bp 
ccacacct-aaaaaactttccacgtgaaccgtttcaacccaa-ttagttgggggcctgc-
tctg-ggcg-gcggttgtcgatgtcaaagtcgacggtt-gctgttgcgtggggggcccta
tc------actggcgagc-gtttgggtccccctcg-ggggaactgagctagtag--cc--
tctcttttaaacccatcc-tgtaatactgaacatactgtggggacgaaagtctctgcttt
taactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacgctg
cgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaatttggaacgca
tattgcacttccgggttagtcctgggagtatgcctgtatcagtgtccgtacatcaaactt
ggctctcttccttccgtgtagtcggtggatggaggtgc-cagacgtgaggtgtcttgcgg
-gcggt----cttcggactgg--ctgtgagtcccttgaaatgtactgaactgtact-tct
ctttgctcgaaaagc-gtgacgttgctggttgtggaggctgcctgtatggccagtc-ggc
gaccggtttgtctgctgcggcg-tttaatggaggagtgtccgattcgcggtatggttggc
tccggctgaacaaagcgcttattggatgttcctccctgctg-tggcggtacggatcggtg
aaccgtagctgtgctaggcttggcgtttgaaccggcggtgtt-gttgcgaagtagggtgg
cggct------------------tcggctgtcga-gggtcgatcc-atttgggaactc--
-tgtgtc-tctccggcgcactt--gtgtgcttgtgg-----tggcatctcaa
>Phytophthora_citricola 900 bp 
ccacacct-aaaaaacttttcacgtgaaccgtatcaaccctt-ttagttgggggtcttg-
-------------------------------------------cttttttgcgagcccta
tc------a-tggcgaat-gtttggactt---------cggtctgggctagtag---ctt
tttgttttaaacccattc-tacaatactgattatactgtggggacgaaagtctctgcttt
taactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacgctg
cgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaacgca
tattgcacttccgggttagtcctgggagtatgcctgtatcagtgtccgtacatcaaactt
ggctttcttccttccgtgtagtcggtgga-ggatgtgc-cagatgtgaagtgtcttgcg-
-ggtgt---ccttcgggtcgt--ctgcgagtcctttgaaatgtactgaactgtact-tct
ctttgctcgaaaagc-gtggtgttgctggttgtggaggctgcctgcgtggccagtc-ggc
gaccggtttgtctgctgcagcg-tttaatggaggagtgttcgattcgcggtatggttggc
ttcggctgaacag-gcgcttattgtatgct-tttcctgctg-tggcgtgatgggctggtg
aaccgtagctatgtgtggcttggcttttgaatcggctttgct-gttgcgaagtagagtgg
cggct------------------tcggctgtcga-gggtcgatcc-a-tttgggaact--
-t---t------------------gtgtgcacctcg--gt-gcgcatctcaa
>Phytophthora_colocasiae 900 bp 
ccacacct-aaaaaactttccacgtgaaccgtatcaaccctt-ttagttgggggtgttg-
cttggca-----------------------------------ttttgctgaggcgcccta
tc------a-tggcgaat-gtttggactt---------cggtctgggctagtag---ctt
tttgttttaaaccc-ttt-aacaatactgattatactgtggggacgaaagtctctgcttt
taactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacgctg
cgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaacgca
tattgcacttccgggttagtcctgggagtatgcctgtatcagtgtccgtacatcaaactt
ggctttcttccttccgtgtagtcggtgga-ggatgtgc-cagatgtgaagtgtcttgcgg
-tttgtgtgccttcgggccgaggctgcgagtcctttgaaatgtactgaactgtact-tct
ctttgctcgaaaagc-gtggtgatgctggttgtggaggctgcctgcgtggccagtc-ggc
gaccggtttgtctgctgcggcg-tttaatggaggagtgttcgattcgcggtatggttggc
ttcggctgaacag-acgcttattgtatgct-tttcctgctg-tggcgtgatgggctggtg
aaccgtagctgtgtgtggcttggcttttgaatcggctttgct-gttgcgaagtagagtgg
cggct------------------tcggctgtcga-gtgtcgatcc-attttgggaact--
-tttgt------------------gtgcgctttcga--gt-gtgcatctcaa
>Phytophthora_cryptogea 900 bp 
ccacacct-aaaaaactttccacgtgaaccgtatcaacctttttaatttgggggcttccg
tctggccgg-ccggttttcggctggctgggtggcggct-------------------cta
tc------a-tggcgacc-gcttgggcct---------cggcctgggctagtag--c---
gtatttttaaacccattc-ctaattactgaatatactgtggggacgaaagtctctgcttt
taactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacgctg
cgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaacgca
tattgcacttccgggttagtcctgggagtatgcctgtatcagtgtccgtacactaaactt
ggctcccttccttccgtgtagtcggtggatggggacgcgcagatgtgaagtgtcttgcgg
-ctggt----cttcggtccgg--ctgcgagtcctttgaaatgtactacactgtact-tct
ctttgctcgaaaagc-gtgacgttgctggttgtggaggctgcctgtgtggcatgtc-ggc
gaccggtttgtctgctgcggcg-tttaatggaggagtgttcgattcgcggtatggttggc
ttcggctgaacag-acgcttattgggtgct-tttcctgctg-tggctggatggactggtg
aaccgtagctgtgctaggcttggcgtttgaaccggcggtgtg--gtgcgaagtagggtgt
ctgtt---ctggcgtaagctgg---ggtggacga-gggtcgatcc-atttgggaaacgtt
gtgtgc-----------------------gcttcggc----gcgcatctcaa
>Phytophthora_drechsleri 900 bp 
ccacacct-aaaaaac-ttccacgtgaaccgtatcaacctttttaaattgggggcttccg
tctggccgg-ccggttctcggctggctgggtggcggct-------------------cta
tc------a-tggcgacc-gcctgggcct---------cggcctgggttagtag--c---
gtattttttaaaccattc-ctaattactgaaaaaactgtggggacgaaagtctctgcttt
taactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacgctg
cgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaacgca
tattgcacttccgggttagtcctgggagtatgcctgtatcagtgtccgtacactaaactt
ggctcccttccttccgtgtagtcggtggatggggacgcgcagatgtgaagtgtcttgcgg
-ctggt----cttcggtccgg--ctgcgagtccttttaaatgtactacactgtact-tct
ctttgctcgaaaagc-gtgacgttgctggttgtggaggctgcctgtgtggcatgtc-ggc
gaccggtttgtctgctgcggcgttttaatggaggagtgttcgattcgcggtatggttggc
ttcggctgaacag-acgcttattgggtgct-ttttctgctg-cggcgggatggactggtg
aaccgtagctgtgctaggcttggcgtttgaaccggcggtatt--gtgcgaagtagggtgt
ctgtc---tcggcgcaagctgg---ggtgggcga-gggtcgatcc-atttgggaaacgtt
gtgtgc-----------------------gcttcggc----gtgcatctcaa
>Phytophthora_erythroseptica 900 bp 
ccacacct-aaaaaactttccacgtgaaccgtatcaacctttttaaattgggggcttccg
tctggccgg-ccggttttcggctggctgggtggcggct-------------------cta
tc------a-tggcgacc-gcttgggcct---------cggcctgggctagtag--c---
gtatttttaaa-ccattc-ctaattactgaatatactgtggggacgaaagtctctgcttt
taactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacgctg
cgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaacgca
tattgcacttccgggttagtcctgggagtatgcctgtatcagtgtccgtacactaaactt
ggctcccttccttccgtgtagtcggtggatggggacgcgcagatgtgaagtgtcttgcgg
-ctggt----cttcggtccgg--ctgcgagtcctttgaaatgtactacactgtact-tct
ctttgctcgaaaagc-gtgacgttgctggttgtggaggctgcctgtgtggcatgtc-ggc
gaccggtttgtctgctgcggcg-tttaatggaggagtgttcgattcgcggtatggttggc
ttcggctgaacag-acgcttattgggtgct-tttcctgctg-tggctggatggactggtg
aaccgtagctgtgctaggcttggcgtttgaaccggcggtgtg--gtgcgaagtagggtgt
ctgtt---ccggcgtaagctgg---ggtggacga-gggtcgatcc-atttgggaaacgtt
gtgtgc-----------------------gcttcggc----gcgcatctcaa
>Phytophthora_fragariae 900 bp 
ccacacct-aaaaaactttccacgtgaaccgtatcaacccac-ttagttgggggcctgt-
cctg-gcgg-ctggctgtcgatgtcaaagttgacggct-gctgctgtgtgtcgggcccta
tc------a-tggcgagc-gtttgggtccctctcg-ggggaactgagccagtag--ccct
tttcttttaaacccattc-ttgaatactgaatatactgtggggacgaaagtctctgcttt
taactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacgctg
cgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaacgca
tattgcacttccgggttagtcctgggagtatgcctgtatcagtgtccgtacatcaaactt
ggctctcttccttccgtgtagtcggtggatggggacgc-cagacgtgaggtgtcttgcgg
-gtggc----cttcgggctgc--ctgcgagtcccttgaaatgtactgaactgtact-tct
ctttgctcgaaaagc-gtgacgttgttggttgtggaggctgcctgtgtggccagtc-ggc
gaccggtttgtctgctgcggcg-tttaatggaggagtgttcgattcgcggtatggttggc
ttcggctgaacaatgcgcttattggacgtt-cttcctgctg-tggcggtacggatcggtg
aaccgtagctgtgcgaggcttggcctttgaaccggcggtgttggtcgcgaagtagggtgg
cggct------------------tcggctgtcgaggggtcgatcc-atttgggaact---
-tgtgtc-tctgcggcgcgcttcggtgtgctgcggg-----tggcatctcaa
>Phytophthora_fragariae_rubi 900 bp 
ccacacct-aaaaaactttccacgtgaaccgtatcaacccac-ttagttgggggcctgt-
cctg-gcgg-ctggctgtcgatgtcaaagttgacggct-gctgctgtgtgtcgggcccta
tc------a-tggcgagc-gtttgggtccctctcg-ggggaactgagccagtag--ccct
tttcttttaaacccattc-ttgaatactgaatatactgtggggacgaaagtctctgcttt
taactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacgctg
cgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaacgca
tattgcacttccgggttagtcctgggagtatgcctgtatcagtgtccgtacatcaaactt
ggctctcttccttccgtgtagtcggtggatggggacgc-cagacgtgaggtgtcttgcgg
-gtggc----cttcgggctgc--ctgcgagtcccttgaaatgtactgaactgtact-tct
ctttgctcgaaaagc-gtgacgttgttggttgtggaggctgcctgtgtggccagtc-ggc
gaccggtttgtctgctgcggcg-tttaatggaggagtgttcgattcgcggtatggttggc
ttcggctgaacaatgcgcttattggacgtt-cttcctgctg-tggcggtacggatcggtg
aaccgtagctgtgcgaggcttggcctttgaaccggcggtgttggtcgcgaagtagggtgg
cggct------------------tcggctgtcgaggggtcgatcc-atttgggaact---
-tgtgtcttctgcggcgcgcttcggtgtgctgcggg-----tggcatctcaa
>Phytophthora_gonapodyides 900 bp 
ccacacct-aaaaaac-ttccacgtgaaccgtatcaaccccttaaatttgggggcttgc-
tcggcggcg--tgcgtgctggcctgtaatgggtcggcgtgctgctgctgggcaggctcta
tc------atgggcgagc-gtttgggctt---------cggctcgaactagtag---cta
tcaattttaaaccctttctttaaatactgaacatactgtggggacgaaagtctctgcttt
taactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacgctg
cgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaacgca
tattgcacttccgggttagtcctgggagtatgcctgtatcagtgtccgtacatcaacctt
ggttttcttccttccgtgtagtcggtgga-ggatatgc-cagacgtgaagtgtcttgctg
-gcggt----ctttcgagtctgccggtgagtcctttgaaatgtactgaactgtactctct
ctttgctcgaaaagc-gtggcgttgctggttgtggagcctgcccgtgtggccagtc-ggc
gaccggtttgttagctgtggcg-tttaatggaggagtgttcgattcgcggtatggttggc
ttcggctgaacaatctgcttattgggtgct-tttcctgtcattggcggtacgaactggtg
aaccgtagctgtgtggtgcttggcttttgaaccggctttgct--ttgcgaagtagggtgg
cggct------------------tcggctgtcgaggggtcgatccattttgggaaactt-
-tgtgt------------------gtgcggcttcgtgctgcgcgcatctcaa
>Phytophthora_heveae 900 bp 
ccacacct--aaaaaatttccacgtgaaccgtaac-aaacca-atagttggggg-cgag-
tttggcg-------------------------gctact----gctgctggacgagctcta
tc------a-tggcgagc-gtttggactt---------cggtctgaactagtag----cc
cttcttttaaacccattc-ctaattactgattatactgtggggacgaaagtctctgcttt
taactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacgctg
cgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaacgca
tattgcacttccgggttagtcctgggagtatgcctgtatcagtgtccgtacaacaaactt
ggctttcttccttccgtgtagtcggtgga-ggagatgc-cagatgtgaagtgtcttgcgg
-ctggt----tctcgaactgg--ctgcgagtcctttgaaatgtactgaactgtact-tct
ctttgctcgaaaagc-atggcgttgctggttgtggaggctgcctgtgtggcatgtc-ggc
gaccggtctgtctgctgcagcg--ttaatggaggcgtgttcgattcgcggtatggttggc
ttcggctgaacaatgcgcttattgtatgtg-tttcctgttg-tggcggtaatggctggtg
taccgtagctatgtggtgcttggcttttgaatcggctttgct-gttgtgaagtagagtgg
cggct------------------tcggctgtcga-gggtcgatcc-atttgggaaatt--
-tgtgt------------------gt--gcctttattggc-gtgcatctcaa
>Phytophthora_hibernalis_Australia Phytophthora_hibernalis_Australia 900 bp 
ccacacct-aaaaaactttccacgtgaaccgtatcaaccctt-ttagttgggggc---t-
tctgttcgg-ctggcttttgctgg-ctgggcggcggct-------------------cta
tc------a-tggcgagc-gcctgggccttc-------gggtctgagctagtag--tc--
ttc-ttttaaaccctttc-ttaaatactgaatatactgtggggacgaaagtctctgcttt
taactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacgctg
cgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaacgca
tattgcacttccgggttagtcctgggagtatgcctgtatcagtgtccgtacatcaaactt
gcctcccttccttccgtgtagtcggtggatggggacgtgcagacgtgaagtgtcttgcga
-ttggt----cttcgggccgg--ctgcgagtccttttaaatgtacagaacggtact-tct
ctttgctcgaaaagc-ataatggaattggttgtggaagcttcccg-gtggcaagtc-ggc
gactggtttgtctgctacggcg-tttaatggaggaatgttcgattcgcggtatggttagc
ttcggctgaacaatgcgcttattggatgtt-tttcctgctg-tggtggtaatgactggtg
aaccgtagctatgcagggattggcctttgaactgaggatgtt--gtgtgaagtagagtgg
cggtt----tggcgcaagctg----ggctgtcga-gggtcgatcctatttgggaaatt--
-tgtgt------------------tggcggcttcggctgt-tggcatctcaa
>Phytophthora_hibernalis_New_Zealand Phytophthora_hibernalis_New_Zealand 900 bp 
ccacacct-aaaaaactttccacgtgaaccgtatcaaccctt-ttagttgggggc---t-
tctgttcgg-ctggcttttgctgg-ctgggcggcggct-------------------cta
tc------a-tggcgagc-gcctgggccttc-------gggtctgagctagtag--tc--
ttc-ttttaaaccctttc-ttaaatactgaatatactgtggggacgaaagtctctgcttt
taactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacgctg
cgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaacgca
tattgcacttccgggttagtcctgggagtatgcctgtatcagtgtccgtacatcaaactt
gcctcccttccttccgtgtagtcggtggatggggacgtgcagacgtgaagtgtcttgcga
-ttggt----cttcgggccgg--ctgcgagtccttttaaatgtacagaacggtact-tct
ctttgctcgaaaagc-ataatggaattggttgtggaagcttcccg-gtggcaagtc-ggc
gactggtttgtctgctacggcg-tttaatggaggaatgttcgattcgcggtatggttagc
ttcggctgaacaatgcgcttattggatgtt-tttcctgctg-tggtggtaatgactggtg
aaccgtagctatgcagggattggcccttgaactgaggatgtt--gtgtgaagtagagtgg
cggtt----tggcgcaagctg----ggctgtcga-gggtcgatcctatttgggaaatt--
-tgtgt------------------tggcggcttcggctgt-tggcatctcaa
>Phytophthora_hibernalis_Portugal Phytophthora_hibernalis_Portugal 900 bp 
ccacacct-aaaaaactttccacgtgaaccgtatcaaccctt-ttagttgggggc---t-
tctgttcgg-ctggcttttgctgg-ctgggcggcggct-------------------cta
tc------a-tggcgagc-gcctgggccttc-------gggtctgagctagtag--tc--
ttc-ttttaaaccctttc-ttaaatactgaatatactgtggggacgaaagtctctgcttt
taactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacgctg
cgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaacgca
tattgcacttccgggttagtcctgggagtatgcctgtatcagtgtccgtacatcaaactt
gcctcccttccttccgtgtagtcggtggatggggacgtgcagacgtgaagtgtcttgcga
-ttggt----cttcgggccgg--ctgcgagtccttttaaatgtacagaacggtact-tct
ctttgctcgaaaagc-ataatggaattggttgtggaagcttcccg-gtggcaagtc-ggc
gactggtttgtctgctacggcg-tttaatggaggaatgttcgattcgcggtatggttagc
ttcggctgaacaatgcgcttattggatgtt-tttcctgctg-tggtggtaatgactggtg
aaccgtagctatgcagggattggcctttgaactgaggatgtt--gtgtgaagtagagtgg
cggtt----tggcgcaagctg----ggctgtcga-gggtcgatcctatttgggaaatt--
-tgtgt------------------tggcggcttcggctgt-tggcatctcaa
>Phytophthora_ilicis 900 bp 
ccacacct-aaaaa--cttccacgtgaactgtatc-gaacaa-ctagttgggggtcttg-
tttggcgtg--cggctgct----------tcggtagct----gctgctaggcgagcccta
tc------a-cggcgagc-gtttggactt---------cggtctgagctagtag-----c
tattttttaaacccattc-tttaatactgattatactgtggggacgaaagtctctgcttt
taactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacgctg
cgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaacgca
tattgcacttccgggttagtcctgggagtatgcctgtatcagtgtccgtacatcaaactt
ggctttcttccttccgtgtagtcggtgga-ggagacgc-cagacgtgaagtgtcttgcgg
-cgaat----tttcgaatttg--ctgtgagtcctttgaaatgtactgaactgtact-tct
ctttgctcgaaaagc-gtggcgttgctggttgtggagcctgcccgcgtggccagtc-ggc
gaccggtttgtctgctgtggcg--ttaatggaggagtgttcgattcgcggtatggttagc
ttcggctgaacaa-gcgcttattggatgtt-cttcttgctg-tggcgtgatggactggtg
aaccgtagctatgtgtggcttggcttttgaatcggctttgct-gttgcgaagtagagtgg
cggct------------------tcggctgtcga-gggtcgatcc-atttgggaaatt--
-tgtgt------------------gtatgacttcggttgt-aagcatctcaa
>Phytophthora_infestans 900 bp 
ccacacct--aaaaactttccacgtgaaccgtttc-aaccca-atagttgggggtctta-
cttggcg-g--cggctgctggctttattgctggcggct----actgctgggcgagcccta
tc----aaa-aggcgagc-gtttggactt---------cggtctgagctagtag--cttt
tttattttaaacccttta-cttaatactgattatactgtggggacgaaagtctctgcttt
taactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacgctg
cgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaacgca
tattgcacttccgggttagtcctggaagtatgcctgtatcagtgtccgtacaacaaactt
ggctttctcccttccgtgtagtcggtgga-ggagatgc-cagatgtgaagtgtcttgcgg
-ttggt----ttccggaccga--ctgcgagtcctttgaaatgtactaaactgtact-tct
ctttgctccaaaagtggtggcattgctggttgtggacgctgctattgtagcgagtt-ggc
gaccggtttgtctgctgcggcg--ttaatggagaaatgctcgattcgtggtatggttgcc
ttcggctgaacaatgcgcttattgggtgat-tttcctgctg-tggcgtgatggactggtg
aaccatggc--tctttagcttggcatttgaatcggctttgct-gttgcgaagtagagtgg
cggct------------------tcggctgccga-gggtcgatcc-atttgggaaatg--
-t-tgt------------------gt---acttcg---gt-atgcatctcaa
>Phytophthora_lateralis 900 bp 
ccacacct-aaaaaac-ttccacgtgaaccgtatcaaaaccc-ttagttgggggc---t-
tctgttcgg-ctggcttcggctgg-ctgggcggcggct-------------------cta
tc------a-tggcgagc-gcatgggccttc-------gggtctgagctagtag--cc--
ctctttttaaacccattc-ctaaatactgaatatactgtggggacgaaagtctctgcttt
taactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacgctg
cgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaacgca
tattgcacttccgggttagtcctgggagtatgcctgtatcagtgtccgtacatcaaactt
gcctcccttccttccgtgtagtcggtggatggggacgtgcagacgtgaagtgtcttgcga
-ttggt----cttcgggccgg--ctgcgagtcctttgaaatgtacagaactgtact-tct
ctttgctcgaaaagc-atgacgttgttggttgtggaggctgtccgtgtggccagtc-ggc
gaccggtttgtctgctgcggcg-tttaatggaggagtgttcgattcgcggtatggttagc
ttcggctgaacaatgcgcttattggatgtt-ttttctgctg-tggcggtaatgactggtg
aaccgtagctatgcagggcttggcttttgaaccgacggtgtt--gtgcgaagtagagtgg
cggtt----tggcgcaagctg----ggctgtcga-gggtcgatcc-atttgggaaatt--
-tgtgt------------------tggcagcttcggctgt-tggcatctcaa
>Phytophthora_megakarya 900 bp 
ccacacct--aaaaactttccacgtgaaccgtatcaacctt---tagttgggggtcttt-
ttcggcg-g--cggctgctggtttaattactggcggtt----gctgctgggagagcccta
tc------a-tggcgagc-gtttgggctt---------cggtctgaactagtag------
-cttttttaaacccattc-attattactgattatactgtggggacgaaagtctctgcttt
taactagatagcaactttcagcagtggatgtctaggctcgcacctcgatgaagaacgctg
cgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaacgca
tattgcacttccgggttagtcctggaagtatgcctgtatcagtgtccgtacatcaaactt
ggttttcttccttccgtgtagtcggtgga-ggatatgc-cagatgtgaggtgtcttgcgg
-ctggc----cttcgggtcgg--ctgtgagtcccttgaaatgtactgaactgtact-tct
ctttgctcgaaaagt-aaagc-ttgcttgttgtggaggctgcttgtgtaaccagtc-ggc
gactagtttgtctgctgtggcg--ttaatggaggagtgttcgattcgcggtatgattggc
ttcggctgaacag-aagcttattgggcgtt-tttcctgcta-tggcggtatgaagtagtg
aaccgtagttatgtg-ggcttggcttttgaatgtgc-tcgct-g-tgcgaagtagagtgg
cgact------------------ttggttgtcga-gggtcgatcc-atttgggaaat---
-tgtgt------------------gt---acttcg---gt-atgcatctcaa
>Phytophthora_megasperma 900 bp 
ccacacct-aaaaaactttccacgtgaaccgtatcaaccccttaaatttgggggcttgc-
tcggcggcg--tgtgtgctggcctgtaatgggtcggcgtgctgctgctgggcgggctcta
tc------atgggcgagc-gtttgggctt---------cggctcgagctagtag---cta
tcaattttaaaccctttc-ttaaatactgaacatactgtggggacgaaagtctctgcttt
taactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacgctg
cgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaacgca
tattgcacttccgggttagtcctgggagtatgcctgtatcagtgtccgtacatcaacctt
ggttttcttccttccgtgtagtcggtgga-ggatatgc-cagatgtgaagtgtcttgcta
-gcggt----ctttcgagtctgccggtgagtccttttaaatgtactgaactgtactctct
ctttgcgcgaaaagc-gtggcgttgctggttgtggaggctgcccgtgtggccagtc-ggc
gaccggtttgttagctgtggcg-tt---tggaggagtgttcgattcgcggtatggttggc
ttcggctaaacaatctgcttattgggtgct-tttcctgtca-tggcggtatgaactggtg
aaccgtagctgtgtggtgcttggcttttgaaccggctttgct--ttgcgaagtagtgtga
cggct------------------tcggctgtcgaggggtcgatccattttgggaaactt-
-tgtgt------------------gtgcggcttcgtgctgcgcgcatctcaa
>Phytophthora_mirabilis 900 bp 
ccacacct--aaaaactttccacgtgaaccgtttc-aaccca-atagttgggggtctta-
cttggcg-g--cggctgctggctttattgctggcggct----act-ctgggcgagcccta
tc----aaa-aggcgagc-gtttggactt---------cggtctgagctagtag--cttt
tttattttaaacccttta-cttaatactgattatactgtggggacgaaagtctctgcttt
taactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacgctg
cgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaacgca
tattgcacttccgggttagtcctggaagtatgcctgtatcagtgtccgtacaacaaactt
ggctttcttccttccgtgtagtcggtgga-ggagatgc-cagatgtgaagtgtcttgcgg
-ttggt----tttcggaccga--ctgcgagtccttttaaatgtactaaactgtact-tct
ctttgctccaaaagtggtggcattgctggttgtggacgctgctattgtagcgagtt-ggc
gaccggtttgtctgctgcggcg--ttaatggagaaatgctcgattcgtggtatggttggc
ttcggctgaacaatgcgcttattgggtgat-tttcctgctg-tggcgtgatggactggtg
aaccatggc--tctttagcttggcatttgaatcggctttgct-gttgcgaagtagagtgg
cggct------------------tcggctgccga-gggtcgatcc-atttgggaaatg--
-t-tgt------------------gt---acttcg---gt-atgcatctcaa
>Phytophthora_nemorosa 900 bp 
ccacacct-aaaaaactttccacgtgaactgtatc-gaacaa-ctagttgggggtcttg-
tttggcgtg--cggctgct----------tcggtagct----gctgctaggcaagcccta
tc------a-cggcgagc-gtttggactt---------cggtctgagctagtag-----c
tattttttaaacccattc-tttaatactgattatactgtggggacgaaagtctctgcttt
taactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacgctg
cgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaacgca
tattgcacttccgggttagtcctgggagtatgcctgtatcagtgtccgtacatcaaactt
ggctttcttccttccgtgtagtcggtgga-ggagacgc-cagacgtgaagtgtcttgcgg
-cgaat----tttcgaatttg--ctgtgagtcctttgaaatgtactgaactgtact-tct
ctttgctcgaaaagc-gtggcgttgctggttgtggaggctgcccgcgtggccagtc-ggc
gaccggtttgtctgctgtagcg--ttaatggaggagtgttcgattcgcggtatggttagc
ttcggctgaacaa-gcgcttattggatgtt-cttcttgctg-tggcgtgatggactggtg
aaccgtagctatgtgtggcttggcttttgaatcggctttgct-gttgcgaagtagagtgg
cggct------------------tcggctgtcga-gggtcgatcc-atttgggaaatt--
-tgtgt------------------gtatgacttcggttgt-atgcatctcaa
>Phytophthora_nicotianae 900 bp 
ccacacctaaaaaaactttccacgtgaaccgtttc-aaccca-atagttgggggtctta-
tttggcg-g--cggctgctggcttaattgttggcggct----gctgctgagtgagcccta
tcaaaaaaa-aggcgaac-gtttgggctt---------cggcctgatttagtagtctttt
tttcttttaaacccattc-cttaatactgaatatactgtggggacgaaagtctctgcttt
taactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacgctg
cgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaacgca
tattgcacttccgggttagtcctggaagtatgcctgtatcagtgtccgtacattaaactt
gactttcttccttccgtgtagtcggtgga-ggagatgt-cagatgtgaagtgtcttgcga
-ttggt----cttcggaccgg--ctgcgagtccttttaaatgtactaaactgaact-tct
ctttgctcgaaaagtggtggcgttgctggttgtgaaggctgctattgtggcaaatt-ggc
gactggtttgtctgctgcggca--ttaatggaagagtgttcgattcgtggtatggttggc
ttcggctgaacaatgcacttattggacgtt-tttcctgctg-tggcgtgatggactggtg
aaccatagc--tcggtggcttggcttttgaattggctttgct-gttgcgaagtagggtgg
cagct------------------tcggttgtcga-gggtcgatcc-atttgggaactt--
-aatgt------------------gt---acttcg---gt-atgcatctcaa
>Phytophthora_palmivora 900 bp 
ccacacct-aaaaaactttccacgtgaaccgtatcaaaact---tatttgggggtctct-
ttcggcg-g--cggctgctggcttcattgctggcggct----gctgttgggagagctcta
tc------a-tggcgagc-gtttgggctt---------cggtctgaactagtag------
-cttttttaaacccattc-tttataactgattatactgtagggacgaaagtctctgcttt
taactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacgctg
cgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaacgca
tattgcacttccgggttagtcctgggagtatgcctgtatcagtgtccgtacatcaaactt
ggttttcttccttccgtgtagtcggtggt-ggatgtgc-cagatgtgaagtgtcttgcgg
-ctggt----cttcggatcgg--ctgtgagtcctttgaaatgtactgaactgtact-tct
ctttgctccaaaagc-gtggcgttgctgattgtggaggctgcttgcgtagccagtctggc
gaccagtttgtctgctgtggcg--ttaatggaggagtgttcgattcgcggtatggttggc
ttcggctgaacag-acgcttattgaatatt-tcttcagctg-tggtggtatg-attggtg
aaccgtagctatgtg-agcttggcttttgaattggctttgct-gttgcgaagtagagtgg
cggct------------------tcggctgtcga-gggtcgatcc-atttgggaact---
-tgtgt------------------at---gcttcg---gc-atgcatctcaa
>Phytophthora_phaseoli 900 bp 
ccacacct--aaaaactttccacgtgaaccgtttc-aaccca-atagttgggggtctta-
cttggcg-g--cggctgctggctttattgctggcggct----actgctgggcgagcccta
tc----aaa-aggcgagc-gtttgggctt---------cggtctgagctagtag--cttt
tttattttaaacccttta-cttaatactgattatactgtggggacgaaagtctctgcttt
taactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacgctg
cgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaacgca
tattgcacttccgggttagtcctggaagtatgcctgtatcagtgtccgtacaacaaactt
ggctttcttccttccgtgtagtcggtgga-ggagatgc-cagatgtgaagtgtcttgcgg
-ttggt----tttcggaccga--ctgcgagtccttttaaatgtactaaactgtact-tct
ctttgctccaaaagtggtggcattgctggttgtggacgctgctattgtagcgagtt-ggc
gaccggtttgtctgctgcggcg--ttaatggagaaatgctcgattcgtggtatggttggc
ttcggctgaacaatgcgcttattgggtgat-tttcctgctg-tggcgtgatggactggtg
aaccatggc--tctttagcttggcatttgaatcggctttgct-gttgcgaagtagagtgg
cggct------------------tcggctgccga-gggtcgatcc-atttgggaaatg--
-t-tgt------------------gt---acttcg---gt-atgcatctcaa
>Phytophthora_pseudosyringae_470 Phytophthora_pseudosyringae_470 900 bp 
ccacacct-aaaaaactttccacgtgaactgtatc-gaacaa-ctagttgggggtcttg-
tttggcgtg--cggctgct----------tcggtagct----gctgctaggcgagcccta
tc------a-cggcgagc-gtttggactt---------cggtctgagctagtag-----c
tattttttaaacccattc-tttaatactgattatactgtggggacgaaagtctctgcttt
taactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacgctg
cgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaacgca
tattgcacttccgggttagtcctgggagtatgcctgtatcagtgtccgtacatcaaactt
ggctttcttccttccgtgtagtcggtgga-ggagacgc-cagacgtgaagtgtcttgcgg
-cgaat----tttcgaatttg--ctgtgagtcctttgaaatgtactgaactgtact-tct
ctttgctcgaaaagc-gtggcgttgctggttgtggaggctgcccgcgtggcctgtc-ggc
gaccggtttgtctgctgtggcg--ttaatggaggagtgttcgattcgcggtatggttagc
ttcggctgaacaa-gcgcttattggatgtt-cttcttgctg-tggcgtgatggactggtg
aaccgtagctatgtgtggcttggcttttgaatcggctttgct-gttgcgaagtagagtgg
cggct------------------tcggctgtcga-gggtcgatcc-atttgggaaatt--
-tgtgt------------------gtatgacttcggttgt-atgcatctcaa
>Phytophthora_pseudosyringae_471 Phytophthora_pseudosyringae_471 900 bp 
ccacacct-aaaaaactttccacgtgaactgtatc-gaacaa-ctagttgggggtcttg-
tttggcgtg--cggctgct----------tcggtagct----gctgctaggcgagcccta
tc------a-cggcgagc-gtttggactt---------cggtctgagctagtag-----c
tattttttaaacccattc-tttaatactgattatactgtggggacgaaagtctctgcttt
taactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacgctg
cgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaacgca
tattgcacttccgggttagtcctgggagtatgcctgtatcagtgtccgtacatcaaactt
ggctttcttccttccgtgtagtcggtgga-ggagacgc-cagacgtgaagtgtcttgcgg
-cgaat----tttcgaatttg--ctgtgagtcctttgaaatgtactgaactgtact-tct
ctttgctcgaaaagc-gtggcgttgctggttgtggaggctgcccgcgtggcctgtc-ggc
gaccggtttgtctgctgtggcg--ttaatggaggagtgttcgattcgcggtatggttagc
ttcggctgaacaa-gcgcttattggatgtt-cttcttgctg-tggcgtgatggactggtg
aaccgtagctatgtgtggcttggcttttgaatcggctttgct-gttgcgaagtagagtgg
cggct------------------tcggctgtcga-gggtcgatcc-atttgggaaatt--
-tgtgt------------------gtatgacttcggttgt-atgcatctcaa
>Phytophthora_pseudosyringae_472 Phytophthora_pseudosyringae_472 900 bp 
ccacacct-aaaaaactttccacgtgaactgtatc-gaacaa-ctagttgggggtcttg-
tttggcgtg--cggctgct----------tcggtagct----gctgctaggcgagcccta
tc------a-cggcgagc-gtttggactt---------cggtctgagctagtag-----c
tattttttaaacccattc-tttaatactgattatactgtggggacgaaagtctctgcttt
taactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacgctg
cgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaacgca
tattgcacttccgggttagtcctgggagtatgcctgtatcagtgtccgtacatcaaactt
ggctttcttccttccgtgtagtcggtgga-ggagacgc-cagacgtgaagtgtcttgcgg
-cgaat----tttcgaatttg--ctgtgagtcctttgaaatgtactgaactgtact-tct
ctttgctcgaaaagc-gtggcgttgctggttgtggaggctgcccgcgtggcctgtc-ggc
gaccggtttgtctgctgtggcg--ttaatggaggagtgttcgattcgcggtatggttagc
ttcggctgaacaa-gcgcttattggatgtt-cttcttgctg-tggcgtgatggactggtg
aaccgtagctatgtgtggcttggcttttgaatcggctttgct-gttgcgaagtagagtgg
cggct------------------tcggctgtcga-gggtcgatcc-atttgggaaatt--
-tgtgt------------------gtatgacttcggttgt-atgcatctcaa
>Phytophthora_pseudosyringae_473 Phytophthora_pseudosyringae_473 900 bp 
ccacacct-aaaaaactttccacgtgaactgtatc-gaacaa-ctagttgggggtcttg-
tttggcgtg--cggctgct----------tcggtagct----gctgctaggcgagcccta
tc------a-cggcgagc-gtttggactt---------cggtctgagctagtag-----c
tattttttaaacccattc-tttaatactgattatactgtggggacgaaagtctctgcttt
taactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacgctg
cgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaacgca
tattgcacttccgggttagtcctgggagtatgcctgtatcagtgtccgtacatcaaactt
ggctttcttccttccgtgtagtcggtgga-ggagacgc-cagacgtgaagtgtcttgcgg
-cgaat----tttcgaatttg--ctgtgagtcctttgaaatgtactgaactgtact-tct
ctttgctcgaaaagc-gtggcgttgctggttgtggaggctgcccgcgtggcctgtc-ggc
gaccggtttgtctgctgtggcg--ttaatggaggagtgttcgattcgcggtatggttagc
ttcggctgaacaa-gcgcttattggatgtt-cttcttgctg-tggcgtgatggactggtg
aaccgtagctatgtgtggcttggcttttgaatcggctttgct-gttgcgaagtagagtgg
cggct------------------tcggctgtcga-gggtcgatcc-atttgggaaatt--
-tgtgt------------------gtatgacttcggttgt-atgcatctcaa
>Phytophthora_pseudosyringae_Germany_PSEU16 Phytophthora_pseudosyringae_Germany_PSEU16 900 bp 
ccacacct-aaaaaactttccacgtgaactgtatc-gaacaa-ctagttgggggtcttg-
tttggcgtg--cggctgct----------tcggtagct----gctgctaggcgagcccta
tc------a-cggcgagc-gtttggactt---------cggtctgagctagtag-----c
tattttttaaacccattc-tttaatactgattatactgtggggacgaaagtctctgcttt
taactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacgctg
cgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaacgca
tattgcacttccgggttagtcctgggagtatgcctgtatcagtgtccgtacatcaaactt
ggctttcttccttccgtgtagtcggtgga-ggagacgc-cagacgtgaagtgtcttgcgg
-cgaat----tttcgaatttg--ctgtgagtcctttgaaatgtactgaactgtact-tct
ctttgctcgaaaagc-gtggcgttgctggttgtggaggctgcccgcgtggcctgtc-ggc
gaccggtttgtctgctgtggcg--ttaatggaggagtgttcgattcgcggtatggttagc
ttcggctgaacaa-gcgcttattggatgtt-cttcttgctg-tggcgtgatggactggtg
aaccgtagctatgtgtggcttggcttttgaatcggctttgct-gttgcgaagtagagtgg
cggct------------------tcggctgtcga-gggtcgatcc-atttgggaaatt--
-tgtgt------------------gtatgacttcggttgt-atgcatctcaa
>Phytophthora_pseudotsugae 900 bp 
ccacacct--aaaaactttccacgtgaaccgtttcaaaccaa-atagttgggggtcttg-
tctggtg-g--cggctgctggctttgttgttggcggct----gctgctgggtgagcccta
tc------a-tggcgagc-gtttgggctt---------cggcctgagctagtag--cttt
tc--ttttaaacccattc-cttaatactgattatactgtggggacgaaagtccttgcttt
taactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacgctg
cgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaacgca
tattgcacttccgggttagtcctgggagtatgcctgtatcagtgtccgtacatcaaactt
ggctttcttccttccgtgtagtcggtgga-ggagatgc-cagatgtgaagtgtcttgcgg
-ctggt----tttcggaccga--ctgcgagtccttttaaatgtactgaactgtact-tct
ctttgctcgaaaagc-gtggcgttgctggttgtggaggctgctattgtagcaagtt-ggc
gaccggtttgtctgctgcggcg--ttaatggaagagtgttcgattcgcggtatggttggc
ttcggctgaacaatgcgcttattggatgat-ttttctgctg-tggcgtgatggaccggtg
aaccatagc--tcagtggcttggcttttgaatcggctttgct-gttgcgaagtagagtgg
cggct------------------tcggctgtcga-gggtcgattc-atttgggaaatg--
-tgtgt------------------gt---acttcg---gt-atgcatctcaa
>Phytophthora_ramorum 900 bp 
ccacacct-aaaaaactttccacgtgaaccgtatcaaaaccc-ttagttgggggc---t-
tctgttcgg-ctggcttcggctgg-ctgggcggcggct-------------------cta
tc------a-tggcgagc-gcttgagccttc-------gggtctgagctagtag--cc--
cactttttaaacccattc-ctaaatactgaatatactgtggggacgaaagtctctgcttt
taactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacgctg
cgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaacgca
tattgcacttccgggttagtcctgggagtatgcctgtatcagtgtccgtacatcaaactt
gcctcccttccttccgtgtagtcggtggatggggacgtgcagacgtgaagtgtcttgcga
-ttggt----cttcgggccgg--ctgcgagtcctttgaaatgtacagaactgtact-tct
ctttgctcgaaaagc-atgacgttgttggttgtggaggctgcccgtgtggccagtc-ggc
gaccggtttgtctgctgcggcg-tttaatggaggagtgttcgattcgcggtatggttagc
ttcggctgaacaatgcgcttattggatgct-ttttctgctg-tggcggtaatgactggtg
aaccgtagctgtgcagggcttggcttttgaatcgacggtgtt--gtgcgaagtagagtgg
cggtt----cggcgcaagctg----ggctgtcga-gggtcgatcc-atttgggaaact--
-tgtgt------------------tggcggcttcggctgc-tggcatctcaa
>Phytophthora_sojae 900 bp 
ccacacct-aagaaactttccacgtgaaccgtatcaa--caa-gtagttgggggcctgc-
tctgtgtgg-ctgtctgtcgatgtcaaagtcggcggctggctgctgtgtggcgggctcta
tc------a-tggcgattggtttgggtcctcctcgtggggaactggatcatgag--cc--
cactttttaaacccattc-ttaaatactgaatatactgtggggacgaaagtctctgcttt
taactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacgctg
cgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaacgca
tattgcacttccgggttagtcctgggagtatgcctgtatcagtgtccgtacatcaaactt
ggctctcttccttccgtgtagtcggtggatggagacgc-cagacgtgaggtgtcttgcgg
cgtggc----cttcgggctgc--ctgcgagtcccttgaaatgtactgaactgtact-tct
ctttgctcgaaaagc-gtgacgttgttggttgtggaggctgcctgtatggccagtc-ggc
gaccggtttgtctgctgcggcg-tttaatggaggagtgttcgattcgcggtatggttggc
ttcggctgaacaatgcgcttattggatgct-tttcctgctg-tggcggtatgggctggtg
aaccgtagctgtgtgaggcttggcttttgaaccggcggtgtt-gttgcgaagtagggtgg
cggct------------------tcggctgtcga-gggtcgatcc-atttgggaactc--
-tgtgttgtctctgcggc------ttgctgcggagg-----tggcatctcaa
>Phytophthora_syringae 900 bp 
ccacacct-aaaaaac-ttccacgtgaaccgtatcaaaacccttttattgggggc---t-
tctgtctggtctggcttcggctggattgggtggcggct-------------------cta
tc------a-tggcgacc-gctctgagcttc-------ggcctggagctagtag--cc--
cactttttaaacccattc-ttaattactgaacaaactgtggggacgaaagtctctgcttt
taactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacgctg
cgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaacgca
tattgcacttccgggttagtcctgggagtatgcctgtatcagtgtccgtacatcaaactt
ggctcccttccttccgtgtagtcggtggatggggatgcacagacgtgaagtgtcttgcga
-ctggg----cttcggctcgg--ctgcgagtccttttaaatgtacagaactgtact-tct
ctttgctcgaaaagc-gttatattactggttgtggaggctgcctgtgcggcaagtc-ggc
gaccggtttgttaactgcggcg-tttaatggaggagtgttcgattcgcggtatggatggc
ttcggctgaactg-acgcttattgagtact-tttcctgctg-tggtggtacgaactggtg
aaccgtagctgtgtttggcttggcttttgaactggcgatgtg--gtgcgaagtagagtga
cggttgttccggcgcaagctggagtgactgtcga-gggtcgatcc-atttgggaaatttt
gtgtct------------------gtgcgacttcggttgcgtggcatctcaa
