>Cryptosphaeria_ligniota_AJ302418 Cryptosphaeria_ligniota_AJ302418 610 bp 
gggatcattatagagtta------taaactcc-taaaacccatgtg-aacttacc--tat
gttgcctcggcgggaaa--------------------------gcctacccg---gtacc
tacctaccctgta----gacaccc-gggagcgagctaccctgtagcccgctgcag-----
-gcccacccgccggtggacagtt-gaactcttgtttttttttatgtggcattctgaa-tg
attatacttaataagttaaaactttcaacaacggatctcttggttctggcatcgatgaag
aacgcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaatcatcgaatcttt
gaacgcacattgcgcccattagtattctagtgggcatgcctgttcgagcgtcatttcaa-
-ccctcaagccctag----ctgcttggtgttgggagtttac---ctgcgg--------gt
aattcctgaaataaat-cggcggagtcgcggtg-accccaagcgtagtaa--tttttcct
cgctttaggt-gtgtcggtgctgacgttcggccgctaaaccc-cttat-tttct-agtgg
ttgacctcgg
>Cryptosphaeria_pullmanensis_AJ302419 Cryptosphaeria_pullmanensis_AJ302419 610 bp 
gggatcattatagagtgt------taaactcc-caaaacccatgtg-aacttacc--tat
gttgcctcggcgggaaa--------------------------gctgacccg---gatgg
taattaccctgta----gttaccc-gggagcgagctacctcgtagcccgctgcag-----
-gcccacccgccggtggacagtt-aaactcttgttttttttcatgtggca-tctgaa-tg
attatacgtaataagttaaaactttcaacaacggatctcttggttctggcatcgatgaag
aacgcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaatcatcgaatcttt
gaacgcacattgcgcccattagtattctagtgggcatgcctgttcgagcgtcatttcaa-
-ccctcaagccctag----ctgcttggtgttgggagtttac---ctgcgg--------gt
aattcctcaaatgcat-cggcggagtcgcggtg-accccaagcgtagtaa--tttttcct
cgctttcgga-gtgtcggcgctggcgttcggccgttaaaccc-cctat-tttct-agtgg
ttgacctcgg
>Cryptosphaeria_pullmanensis_UCD730SJ Cryptosphaeria_pullmanensis_UCD730SJ 610 bp 
gggatcattatagagtat------taaactcc-caaaacccatgtg-aacttacc--tat
gttgcctcggcgggaaa--------------------------gctgacccg---gatgg
taattaccctgta----gttaccc-gggagcgagctacctcgtagcccgctgcag-----
-gcccacccgccggtggacagtt-aaactcttgtttttttttatgtggca-tctgaa-tg
attatacgtaataagttaaaactttcaacaacggatctcttggttctggcatcgatgaag
aacgcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaatcatcgaatcttt
gaacgcacattgcgcccattagtattctagtgggcatgcctgttcgagcgtcatttcaa-
-ccctcaagccctag----ctgcttggtgttgggagtttac---ctgcgg--------gt
aattcctcaaatgcat-cggcggagtcgcggtg-accccaagcgtagtaa--ttcttcct
cgctttcgga-gtgtcggcgctggcgttcggccgttaaaccc-cttat-tttct-agtgg
ttgacctcgg
>Cryptosphaeria_subcutanea_AJ302420 Cryptosphaeria_subcutanea_AJ302420 610 bp 
gggatcattatagagtta------taaactcc-taaaacccatgtg-aacttacc--tat
gttgcctcggcggggaa--------------------------gcttacccg---g----
tacctaccctgta----gacaccc-gggagcgagctaccctgtagcccgctgcag-----
-gcccacccgccggtggacagtt-aaactcttg---ttttttatgtggcattctgaa-tg
attatacttaataagttaaaactttcaacaacggatctcttggttctggcatcgatgaag
aacgcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaatcatcgaatcttt
gaacgcacattgcgcccattagtattctagtgggcatgcctgttcgagcgtcatttcaa-
-ccctcaagccctag----ctgcttggtgttgggagtttac---ctgcgg--------gt
aattcctgaaataaat-cggcggagtcgcggtg-accccaagcgtagtaa--tttttcct
cgcttcaggt-gtgtcggtgctgacgttcggccgttaaaccc-cctat-tttct-agtgg
ttgacctcgg
>Cryptovalsa_ampelina_AY920391 610 bp 
gggatcattacagagtta------tctaactc-ccaaaaccatgtg-aacttacc--tat
gttgcctcggcggggaa--------------------------gctaacccg---g----
tacctacccagta----gttaccc-gggag-ggcctaccctgtag-ctaccctat-----
-agcgacccgccggtggactgct-aaactcttg----tttttaagtgatattctgag-tg
tttaaacttaattagttaaaactttcaacaacggatctcttggttctggcatcgatgaag
aacgcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaatcatcgaatcttt
gaacgcacattgcgcccattagtattctagtgggcatgcctgttcgagcgtcatttcaa-
-cccttaagccttag----ttgcttagtgttgggggctcgc-ctagctatagacgctggc
gaccccttaaaaatat-cggcggagtcgtgtcg-accctaagcgtagtaat-ttattcct
cgcttcaggc-ttgtaggcgctggcgtccggccgttaaaccc-cctat-ttttt-aatgg
ttgacctcgg
>Cryptovalsa_ampelina_DMO300 610 bp 
gggatcattacagagtta------tctaactc-ccaaaaccatgtg-aacttacc--tat
gttgcctcggcggggaa--------------------------gctaacccg---g----
tacctacccagta----gttaccc-gggag-ggcctaccctgtag-ctaccttat-----
-agcgacccgccggtggactgct-aaactcttg----tttttaagtgatattctgag-tg
tttaaacttaattagttaaaactttcaacaacggatctcttggttctggcatcgatgaag
aacgcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaatcatcgaatcttt
gaacgcacattgcgcccattagtattctagtgggcatgcctgttcgagcgtcatttcaa-
-cccttaagccttag----ttgcttagtgttgggggctcgc-ctagctatagacgctggc
gaccccttaaaaatat-cggcggagtcgtgtcg-accctaagcgtagtaat-ttattcct
cgcttcaggc-ttgtaggcgctggcgtccggccgttaaaccc-cctaa-ttttt-aatgg
ttgacctcgg
>Cryptovalsa_ampelina_RANCHO4 610 bp 
gggatcattacagagtta------tctaactc-ccaaaaccatgtg-aacttacc--tat
gttgcctcggcggggaa--------------------------gctaacccg---g----
tacctacccagta----gttaccc-gggag-ggcctaccctgtag-ctaccctat-----
-agcgacccgccggtggactgct-aaactcttg----tttttaagtgatattctgag-tg
tttaaacttaattagttaaaactttcaacaacggatctcttggttctggcatcgatgaag
aacgcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaatcatcgaatcttt
gaacgcacattgcgcccattagtattctagtgggcatgcctgttcgagcgtcatttcaa-
-cccttaagccttag----ttgcttagtgttgggggctcgc-ctagctatagacgctggc
gaccccttaaaaatat-cggcggagtcgtgtcg-accctaagcgtagtaat-ttattcct
cgcttcaggc-ttgtaggcgctggcgtccggccgttaaaccc-cctat-ttttt-aatgg
ttgacctcgg
>Daldinia_concentrica_AF201708 610 bp 
gggatcattaccgagtta------tctaaact-ccaaccctttgtgaaacttacc--gtc
gttgcctcggcgggctg-------------------------cgcttaccct---g----
tagctaccctgta----gctacccggtaggcgcgct------------------------
-ccaagcccgccggtggaccact-aaactctgt----tttaataccgaatctctgaa-tg
cttcaacttaataagttaaaactttcaacaacggatctcttggttctggcatcgatgaag
aacgcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaatcatcgaatcttt
gaacgcacattgcgcccattagtattctagtgggcatgcctattcgagcgtcatttcaa-
-cccttaagccttag----ttgcttagcgttgggagtctgcgctgtacttgttacggcgc
agttcctcaaagtgat-tggcggagttagggcatactctaagcgtagtaatatttcttct
cgcttctgtagttgtc----ctggcggcttgccgttaaaccc-ctata-ttttctagtgg
ttgacctcgg
>Diatrype_bullata_AJ302422 610 bp 
gggatcattacagagtta------ccttaact-ccaaacccatgtg-aacttacc--tat
gttgcctcggcggggaa--------------------------gcctacccg---g----
taattaccctgta----gttaccc-gggagcgagctaccctgtagcccgctgcag-----
-gcctacccgccggcggacactt-aaactcttg---ttttacagtgaaacttctgat-at
tttatacttaataagttaaaactttcaacaacggatctcttggttctggcatcgatgaag
aacgcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaatcatcgaatcttt
gaacgcacattgcgcccattagtattctagtgggcatgcctgttcgagcgtcatttcga-
-ccatcaagccccag----ttgcttggttttgggagcctat-ctttaggg--------at
agctccttaaatagag-tggcggagtcgtgctg-accccaagcgtagtaa--ttctttct
cgctttaggt---gccggtgccgacgtcctgccgttaaaccc-cctat-tttta-aaagg
ttgacctcgg
>Diatrype_disciformis_AJ302424 610 bp 
gggatcattacagagtta------cc-taact-ccaaacccatgtg-aacttacc--tat
gttgcctcggcggggaa--------------------------gcctacccg---g----
tacctaccctgta----gttaccc-gggagcgagctaccctgtagcccgctgcag-----
-gcctacccgccggtggacagtt-aaactcttg--tttttacagtgaaacttctgat-at
tttatacttaataagttaaaactttcaacaacggatctcttggttctggcatcgatgaag
aacgcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaatcatcgaatcttt
gaacgcacattgcgcccattagtattctagtgggcatgcctgttcgagcgtcatttcga-
-ccatcaagccccgg----ttgcttggttttgggagcctat-ctctaggg--------at
agctccttaaatagag-tggcggagtcgtgccg-accccaagcgtagtaa--tttcttct
cgcttcaggt---gccggtgctgacgtcctgccgttaaaccc-cctat-tttta-aaagg
ttgacctcgg
>Diatrype_flavovirens_AJ302430 610 bp 
gggatcattacagagtta------tctaactc-ccaaacccatgtg-aacttacc--tac
gttgcctcggcggggaa--------------------------gcctacccg---g----
tacctaccctgta----gttaccc-gggagcgagctaccctgtagcccgctgcag-----
-gcctacccgccggtggacatct-aaactcttg---ttttctagt-gattatctgag-tg
tttatacttaataagttaaaactttcaacaacggatctcttggttctggcatcgatgaag
aacgcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaatcatcgaatcttt
gaacgcacattgcgcccattagtattctagtgggcatgcctgttcgagcgtcatttcaa-
-ccctcaagccctag----ttgcttggtattgggagcttg---cctacgg--------gc
aactcctcaaaagcat-tggcggagtcgcggtg-accccaagcgtagtaa--ttctt-ct
cgctt-aggt-gtgtcaacgctgacgttcagccactaaaccc-cctat-tttct-agtgg
ttgacctcgg
>Diatrype_macowaniana_AJ302431 610 bp 
gggatcattacagagtta------tctaactc-cc-aacccatgtg-aacttacc--ttt
gttgcctcggcggggaa--------------------------gcctacccg---g----
tacctaccctgta----gttaccc-gggagcgagctaccctgtagcccgctgctg-----
-gccgacccgccggtggacagta-aaactcttg----tttttagtgaattatctgag-tg
tttatacttaataagttaaaactttcaacaacggatctcttggttctggcatcgatgaag
aacgcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaatcatcgaatcttt
gaacgcacattgcgcccattagtattctagtgggcatgcctgttcgagcgtcatttcaa-
-ccctcaagccccag----ttgcttggtgttgggagcttgc---ccctac--------gc
aactcctgaaagctat-tggcggagccgcattg-gccctaagcgtagtaa--tttttcct
cgcttcaggt-gtcccggtgctggcgtcctgccgtaaaaccc-ccaat-tttac-aatgg
ttgacctcgg
>Diatrype_oregonensis_DCA600 610 bp 
gggatcattacagagtta------cctaactc-cc-aacccatgtg-aacttacc--ttt
gttgcctcggcgggaga--------------------------gcctacccg---g----
tacctaccctgta----gttaccc-gggagcgagctaccctgtagcccgctgctg-----
-gccgacccgccggtggacagta-aaactcttg----ttttttagtgattatctgag-tg
tttatacttaataagttaaaactttcaacaacggatctcttggttctggcatcgatgaag
aacgcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaatcatcgaatcttt
gaacgcacattgcgcccattagtattctagtgggcatgcctgttcgagcgtcatttcaa-
-ccctcaagccccag----ttgcttggtgttgggagcctgc---cccccccgggga--gc
agctcctcaaagctat-tggcggagtcgtattg-gccctaagcgtagtaat-tttttcct
cgcttctagtggttccagtgctggcgtccagccgtaaaaccc-ctaat-tttct-agtgg
ttgacctcgg
>Diatrype_sp_DBEY700 610 bp 
gggatcattacagagtta------tctaactc-cc-aacccatgtg-aacttacc--tat
gttgcctcggcgggaaa--------------------------gcctacccg---g----
tacctaccctgta----gttaccc-gggagcgggctaccctgtagcccgctgctg-----
-gccgacccgccggtggacagta-aaactcttg----tttttagtgaattgtctgag-tg
tttatacttaataagttaaaactttcaacaacggatctcttggttctggcatcgatgaag
aacgcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaatcatcgaatcttt
gaacgcacattgcgcccattagtattctagtgggcatgcctgttcgagcgtcatttcaa-
-ccctcaagccccag----ttgcttggtattgggagcttgc---ctgcgg--------gc
aactcctcgaagctat-tggcggagccgcgtgg-gccctaagcgtagtaa--tcttttct
cgcttcaggt-gcttccgtgctggcgtccagccgtaaaaccc-ccaat-ttt-t-aatgg
ttgacctcgg
>Diatrype_spilomea_AJ302433 610 bp 
gggatcattacagagtta------cc-taact-ccaaacccatgtg-aacttacc--tat
gttgcctcggcggggaa--------------------------gcctacccg---g----
aacctaccctgta----gttaccc-gggagcgagctaccctgtagcccgctgcag-----
-gcctacccgccggcggacactt-aaactcttg---ttttacagtgaaacttctgat-at
tttatacttaataagttaaaactttcaacaacggatctcttggttctggcatcgatgaag
aacgcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaatcatcgaatcttt
gaacgcacattgcgcccattagtattctagtgggcatgcctgttcgagcgtcatttcga-
-ccatcaagccccag----ttgcttggttttgggagcctat-ctctaggg--------at
agctccttaaatagag-tggcggagtcgtgctg-accccaagcgtagtaa--ttttttct
cgctttaggt---gccggtgctgacgtcctgccgttaaaccc-cctat-tttta-aaagg
ttgacctcgg
>Diatrype_stigma_AJ302439 610 bp 
gggatcattacagagtta------tctaactc-ccaaacccatgtg-aacttacc--tat
gttgcctcggcggggaa--------------------------gcctacccg---g----
tacctaccctgta----gttaccc-gggagcgagctaccctgtagcccgctgcag-----
-gcctacccgccggtggacagtt-aaactcttg---ttttacagtgaaacttctgat-at
tttatacttaataagttaaaactttcaacaacggatctcttggttctggcatcgatgaag
aacgcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaatcatcgaatcttt
gaacgcacattgcgcccattagtattctagtgggcatgcctgttcgagcgtcatttcga-
-ccctcaagcctcag----ttgcttggttttgggagcctat--ctc-cgg--------at
agctcctcaaatagag-tggcggagtcgtgctg-accccaagcgtagtaa--ttttttct
cgctttaggt---gccggtgctgacgtcttgccgttaaaccc-cctat-tttt--aaagg
ttgacctcgg
>Diatrype_stigma_DCash200 610 bp 
gggatcattacagagtta------tctaactc-ccaaacccatgtg-aacttacc--tat
gttgcctcggcggggaa--------------------------gcctacccg---g----
tacctaccctgta----gttaccc-gggagcgagctaccctgtagcccgctgcag-----
-gcctacccgccggtggacagtt-aaactcttg---ttttacagtgaaacttctgat-at
tttatacttaataagttaaaactttcaacaacggatctcttggttctggcatcgatgaag
aacgcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaatcatcgaatcttt
gaacgcacattgcgcccattagtattctagtgggcatgcctgttcgagcgtcatttcga-
-ccctcaagcctcag----ttgcttggttttgggagcctat--ctc-cgg--------at
agctcctcaaatagag-tggcggagtcgtgctg-accccaagcgtagtaa--ttttttct
cgctttaggt---gccggtgctgacgtcttgccgttaaaccc-cctat-tttt--aaagg
ttgacctcgg
>Diatrype_undulata_AJ302436 610 bp 
gggatcattacagagtta------tctaactc-ccaaacccatgtg-aacttacc--tat
gttgcctcggcggggaa--------------------------gcctacccg---g----
tacctaccctgta----gttaccc-gggagcgagctaccctgtagcccgctgcag-----
-gcctacccgccggtggacagtt-aaactcttg---ttttacagtgaaacttctgat-at
tttatacttaataagttaaaactttcaacaacggatctcttggttctggcatcgatgaag
aacgcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaatcatcgaatcttt
gaacgcacattgcgcccattagtattctagtgggcatgcctgttcgagcgtcatttcga-
-ccttcaagcctcag----ttgcttggttttgggagcctat-cctt-cgg--------at
agctcctcaaatagagttggcggagtcgtgctg-accccaagcgtagtaa--tttcttct
cgcttcaggt---gccggtgctgacgtcttgccgttaaaccc-cctat-ttca--aatgg
ttgacctcgg
>Diatrype_whitmanensis_CDB011 610 bp 
gggatcattacagagtta------tttaactc-ccaaacccgtgtg-aacttacc--tac
gttgcctcggcggggaa--------------------------gcctacccggtag----
tatctaccctgta----gttaccc-gggagcgagctaccctgtagcccgctgcag-----
-gcctacccgccggtggactgct-aaactcttg--tttttttggtggattatctgag-tg
tttatacttaacgagttaaaactttcaacaacggatctcttggttctggcatcgatgaag
aacgcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaatcatcgaatcttt
gaacgcacattgcgcccattagcattctagtgggcatgcctgttcgagcgtcatttcaa-
-ccctcaagccctag----ttgcttggtgttgggagcttat-ctctctgg--------at
aactcctcgaaagcat-tggcggagtcgcggtg-accccgagcgtagtaa--ttctt-ct
cgctttaggt-gtgttagcgctgtcgtctagccgttaaacct-tctat-tttct-agtgg
ttgacctcgg
>Diatrypella_favacea_AJ302440 610 bp 
gggatcattacagagtta------tctaactc-ccaaaaccatgtg-aacttacc--tat
gttgcctcggcggggaa--------------------------gcctacccg---g----
tacctaccctgta----gttaccc-gggagcgagctaccctgtagcccgctgctg-----
-gcctacccgccggtggactgtt-aaactcttg---ttttttagt-gattatctgag-tg
tttatacttaataagttaaaactttcaacaacggatctcttggttctggcatcgatgaag
aacgcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaatcatcgaatcttt
gaacgcacattgcgcccattagtattctagtgggcatgcctgttcgagcgtcatttcaa-
-ccctcaagccctag----ttgcttggtgttgggagccta---tctccgg--------at
agctcctcaaaaccat-tggcggagtcgcgatg-gccccaagcgtagtaa--tttttatt
cgcttcaggt-gtgtcagcgctggcgttcagccgttaaaccc-cctat-tttct-agtgg
ttgacctcgg
>Diatrypella_frostii_AJ302441 610 bp 
gggatcattacagagtta------tctaactc-cc-aacccatgtg-aacttacc--ttt
gttgcctcggcgggaga--------------------------gcctacccg---g----
tacctaccctgta----gttaccc-gggagcgagctgccctgcagcccgctgctg-----
-gccgacccgccggtggacagta-aaactcttg----tttttagtggattatctgag-tg
tttatacttaataagttaaaactttcaacaacggatctcttggttctggcatcgatgaag
aacgcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaatcatcgaatcttt
gaacgcacattgcgcccattagtattctagtgggcatgcctgttcgagcgtcatttcaa-
-ccctcaagccccag----ttgcttggtgttgggagcctgc---ccccctagggga--gc
agctcctcaaagctat-tggcggagtcgtattg-gccctaagcgtagtaa--tttttcct
cgcttttagtggttccagtgctggcgtccagccgtaaaaccc-ctaat-tttct-agtgg
ttgacctcgg
>Diatrypella_prominens_AJ302442 610 bp 
gggatcattacagagtta------tccaactc-cc-aacccatgtg-aacttacc--ttt
gttgcctcggcgggagagcctacccggtacctaccctgtagttgcctacccg---g----
tacctaccctgta----gttaccc-gggagcgagctgccctgcagcccgctgctg-----
-gccgacccgccggtggacagta-aaactcttg---ttttttagtggattatctgag-tg
tttatacttaataagttaaaactttcaacaacggatctcttggttctggcatcgatgaag
aacgcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaatcatcgaatcttt
gaacgcacattgcgcccattagtattctagtgggcatgcctgttcgagcgtcatttcaa-
-ccctcaagcccccg----ttgcttggtgttgggagcctgc---cccccctagggggggc
agctcctcaaagctat-tggcggagccgtgctg-gccctaagcgtagtaa--tttgttct
cgcttctagtggttccagcgctggcgttcagccgtaaaaccc-ctaat-tttct-agtgg
ttgacctcgg
>Diatrypella_pulvinata_AJ302443 610 bp 
gggatcattacagagtta------tctaactc-ccaaaaccatgtg-aacttacc--tat
gttgcctcggcggggaa--------------------------gcctacccg---g----
tacctaccctgta----gttaccc-gggagcgagctaccctgtagcccgctgctg-----
-gccgacccgccggtggactgct-aaactcttg---ttttttcgt-gattatctgag-tg
tttatacttaataagttaaaactttcaacaacggatctcttggttctggcatcgatgaag
aacgcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaatcatcgaatcttt
gaacgcacattgcgcccattagtattctagtgggcatgcctgttcgagcgtcatttcaa-
-ccctcaagccctag----ttgcttggtgttgggagccta---tctccgg--------at
agctcctcaaaaccat-tggcggagtcgcgatg-gccccaagcgtagtaa--tttttatt
cgcttcaggt-gtgtcagcgctggcgtccagccgctaaaccc-cctat-ttttt-agtgg
ttgacctcgg
>Diatrypella_quercina_AJ302444 610 bp 
gggatcattacagagttc------cc-taact-ccaaacccatgtg-aacttacc--tat
gttgcctcggcgggaaa--------------------------acctacccg---g----
taattaccctgta----gttaccc-gggagcgagctacctggtagcccgctgcag-----
-gcctacccgccggtggacagtt-aaactcttg---ttttaccgtgaaacttctgat-at
tttatacttaataagttaaaactttcaacaacggatctcttggttctggcatcgatgaag
aacgcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaatcatcgaatcttt
gaacgcacattgcgcccattagtattctagtgggcatgcctgttcgagcgtcatttcga-
-ccatcaagccccag----ctgcttggttttgggagcctat-ctccaggg--------at
agctccttaaatagag-tggcggagtcgtgctg-a-cccaagcgtagtaa--ttt-ttct
cgcttctggt---gccggtgctgacgtcctgccgttaaaccc-cctat-ttttt-aaagg
ttgacctcgg
>Diatrypella_sp_CA008 610 bp 
gggatcattacagagtta------ataaactc-cc-aacccatgtg-aacttacc--tat
gttgcctcggcgggaga--------------------------gcctacccg---g----
tacctaccctgta----gttaccc-gggagcgagctaccctgtagcccgctgctg-----
-gccgacccgccggtggacagta-aaactcttg----tttttagtggattatctgag-tg
tttatacttaataagttaaaactttcaacaacggatctcttggttctggcatcgatgaag
aacgcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaatcatcgaatcttt
gaacgcacattgcgcccattagtattctagtgggcatgcctgttcgagcgtcatttcaa-
-ccctcaagccccag----ttgcttggtgttgggagcctgc-a-cccccccgggggctgc
agctcctcaaagctat-tggcggagtcgtattg-gccctaagcgtagtaat-tttttcct
cgcttctagtggttccagtgctggcgtccagccgtaaaaccc-ctaat-ctttt-agtgg
ttgacctcgg
>Diatrypella_sp_CA010 610 bp 
gggatcattacagagtta------ataaactc-cc-aacccatgtg-aacttacc--tat
gttgcctcggcgggaga--------------------------gcctacccg---g----
tacctaccctgta----gttaccc-gggagcgagctaccctgtagcccgctgctg-----
-gccgacccgccggtggacagta-aaactcttg----tttttagtggattatctgag-tg
tttatacttaataagttaaaactttcaacaacggatctcttggttctggcatcgatgaag
aacgcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaatcatcgaatcttt
gaacgcacattgcgcccattagtattctagtgggcatgcctgttcgagcgtcatttcaa-
-ccctcaagccccag----ttgcttggtgttgggagcctgc-a-cccccccgggggctgc
agctcctcaaagctat-tggcggagtcgtattg-gccctaagcgtagtaat-tttttcct
cgcttctagtggttccagtgctggcgtccagccgtaaaaccc-ctaat-cttct-agtgg
ttgacctcgg
>Diatrypella_sp_CA015 610 bp 
gggatcattacagagtta------ataaactc-cc-aacccatgtg-aacttacc--tat
gttgcctcggcgggaga--------------------------gcctacccg---g----
tacctaccctgta----gttaccc-ggaagcgagctaccctgtagcccgctgctg-----
-gccgacccgccggtggacagta-aaactcttg----tttttagtggattatctgag-tg
tttatacttaataagttaaaactttcaacaacggatctcttggttctggcatcgatgaag
aacgcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaatcatcgaatcttt
gaacgcacattgcgcccattagtattctagtgggcatgcctgttcgagcgtcatttcaa-
-ccctcaagccccag----ttgcttggtgttgggagcctgc-a-acccccaaggggctgc
agctcctcaaagctat-tggcggagtcgtattg-gccctaagcgtagtaat-tttttcct
cgcttctagtggttccagtgctggcgtccagccgtaaaaccc-ctaat-tttct-agtgg
ttgacctcgg
>Diatrypella_sp_CA149 610 bp 
gggatcattacagagtta------ataaactc-cc-aacccatgtg-aacttacc--tat
gttgcctcggcgggaga--------------------------gcctacccg---g----
tacctaccctgta----gttaccc-gggagcgagctaccctgtagcccgctgctg-----
-gccgacccgccggtggacagta-aaactcttg----tttttagtggattatctgag-tg
tttatacttaataagttaaaactttcaacaacggatctcttggttctggcatcgatgaag
aacgcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaatcatcgaatcttt
gaacgcacattgcgcccattagtattctagtgggcatgcctgttcgagcgtcatttcaa-
-ccctcaagccccag----ttgcttggtgttgggagcctgc-a-cccccccgggggctgc
agctcctcaaagctat-tggcggagtcgtattg-gccctaagcgtagtaat-tttttcct
cgcttctagtggttccagtgctggcgtccagccgtaaaaccc-ctaat-tttct-agtgg
ttgacctcgg
>Diatrypella_sp_CA7614 610 bp 
gggatcattacagagtta------ataaactc-cc-aacccatgtg-aacttacc--tat
gttgcctcggcgggaga--------------------------gcctacccg---g----
tacctaccctgta----gttaccc-gggagcgagctaccctgtagcccgctgctg-----
-gccgacccgccggtggacagta-aaactcttg----tttttagtggattatctgag-tg
tttatacttaataagttaaaactttcaacaacggatctcttggttctggcatcgatgaag
aacgcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaatcatcgaatcttt
gaacgcacattgcgcccattagtattctagtgggcatgcctgttcgagcgtcatttcaa-
-ccctcaagccccag----ttgcttggtgttgggagcctgc-a-acccccaaggggctgc
agctcctcaaagctat-tggcggagtcgtattg-gccctaagcgtagtaat-tttttcct
cgcttctagtggttccagtgctggcgtccagccgtaaaaccc-ctaat-tttct-agtgg
ttgacctcgg
>Diatrypella_sp_UCDCH2 610 bp 
gggatcattacagagtta------ataaactc-cc-aacccatgtg-aacttacc--tat
gttgcctcggcgggaga--------------------------gcctacccg---g----
tacctaccctgta----gttaccc-gggagcgagctaccctgtagcccgctgctg-----
-gccgacccgccggtggacagta-aaactcttg----tttttagtggattatctgag-tg
tttatacttaataagttaaaactttcaacaacggatctcttggttctggcatcgatgaag
aacgcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaatcatcgaatcttt
gaacgcacattgcgcccattagtattctagtgggcatgcctgttcgagcgtcatttcaa-
-ccctcaagccccag----ttgcttggtgttgggagcctgc-accccccccgggggctgc
agctcctcaaagctat-tggcggagtcgtattg-gccctaagcgtagtaat-tttttcct
cgcttctagtggttccagtgctggcgtccagccgtaaaaccc-ttaat-tttct-agtgg
ttgacctcgg
>Diatrypella_verrucaeformis_DHB500 Diatrypella_verrucaeformis_DHB500 610 bp 
gggatcattacagagtta------ataaactc-cc-aacccatgtg-aacttacc--tat
gttgcctcggggggaga--------------------------gcctacccg---g----
tacctaccctgta----gttaccc-gggagcgagctaccctgtagcccgctgctg-----
-gccgacccgccggtggacagta-aaactcttg----tttttagtggattatctgag-tg
tttatacttaataagttaaaactttcaacaacggatctcttggttctggcatcgatgaag
aacgcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaatcatcgaatcttt
gaacgcacattgcgcccattagtattctagtgggcatgcctgttcgagcgtcatttcaa-
-ccctcaagccccag----ttgcttggtgttgggagcctgc-a-cccccccgggggctgc
agctcctcaaagctat-tggcggagtcgtattg-gccctaagcgtagtaat-tttttcct
cgcttctagtggttccagtgctggcgtccagccgtaaaaccc-ctaat-tttct-agtgg
ttgacctcgg
>Eutypa_lata_AJ302450 610 bp 
gggatcattacagagtta------cctaact--ccaaacccatgtg-aacttacc--tat
gttgcctcggcggggaa--------------------------gcctacccg---g----
tacctaccctgta----gctaccc-gggagcgagctaccctgtagcccgctgcag-----
-gcctacccgccggtggacactt-aaactcttg---ttttttagt-gattatctgag-tg
tttatacttaataagttaaaactttcaacaacggatctcttggttctggcatcgatgaag
aacgcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaatcatcgaatcttt
gaacgcacattgcgcccattagtattctagtgggcatgcctgttcgagcgtcatttcga-
-ccttcaagccctag----ctgcttggtgttgggagccta---tctccgg--------at
agctcctcaaaagcat-tggcggagtcgcggtg-accccaagcgtagtaa--ttctt-ct
cgctttaggt-gtgtcacggctgacgtcttgccgttaaaccc-ccaat-tttttaaatgg
ttgacctcgg
>Eutypa_lata_DCA900 610 bp 
gggatcattacagagtta------cctaact--ccaaacccatgtg-aacttacc--tat
gttgcctcggcggggaa--------------------------gcctacccg---g----
tacctaccctgta----gctaccc-gggagcgagctaccctgtagcccgctgcag-----
-gcctacccgccggtggacactt-aaactcttg--tttttttagt-gattatctgag-tg
tttatacttaataagttaaaactttcaacaacggatctcttggttctggcatcgatgaag
aacgcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaatcatcgaatcttt
gaacgcacattgcgcccattagtattctagtgggcatgcctgttcgagcgtcatttcga-
-ccttcaagccctag----ctgcttggtgttgggagccta---tctccgg--------at
agctcctcaaaagcat-tggcggagtcgcggtg-accccaagcgtagtaa--ttctt-ct
cgctttaggt-gtgtcacggctgacgtcttgccgttaaaccc-ccaat-tttttaaatgg
ttgacctcgg
>Eutypa_leptoplaca_AY684237 610 bp 
gggatcattacagagtta------cccaactcaccaaacccatgtg-aacttacc--tat
gttgcctcggcggggaa--------------------------gcctacccg---g----
tacctaccctgta----gttaccc-gggagcgagctacgctgtagcccgctgcag-----
-gccaacccgccggtggactgtt-aaactcttg-----ttatagtggaacttctgat-tt
tttatacttaataagttaaaactttcaacaacggatctcttggttctggcatcgatgaag
aacgcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaatcatcgaatcttt
gaacgcacattgcgcccattagtattctagtgggcatgcctgttcgagcgtcatttcaa-
-ccctcaagccctag----ttgcttggtgttgggagtttac---ctgcgg--------gt
aattcctgaaaagcat-cggcggagtcgtgttg-gccccaagcgtagtaa--ttt-ttct
cgcttcaggtggttccagcgctggcgtccagccgctaaaccc-cctat-tctt-tagtgg
ttgacctcgg
>Eutypa_maura_AJ302454 610 bp 
gggatcattacagagtta------tctaactc-ccaaacccatgtg-aacttacc--tac
gttgcctcggcggggaa--------------------------gcctacccg---g----
taactaccctgta----cttaccc-gggagcgagctaccctgtagcccgctgcag-----
-gcctacccgccggtggactgtt-aaactctgg-----atatagtggaacttctgat-gt
tttatacttaataagttaaaactttcaacaacggatctcttggttctggcatcgatgaag
aacgcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaatcatcgaatcttt
gaacgcacattgcgcccattagtattctagtgggcatgcctgttcgagcgtcatttcaa-
-ccctcaagccccag----cggcttggtgttgggagtttat---ctgcgg--------at
aattcctgaaaagcat-cggcggagccgtgctg-gccccaagcgtagtaa--tctgctct
cgcttcaggtg--ctcagcgccggcgcctagccgctaaaccc-cctaa-ttttctagtgg
ttgacctcgg
>Eutypella_alsophila_AJ402367 610 bp 
gggatcattaatgagttt------tctaaactccaaaccctttgag-aaccttac--cta
gttgcctcggcg----g--------------------------acttgccct---gggac
gacctaccctgcagcgagttaccc-tgtaacgagttgccctgtagggacttgccc--tgt
agcctgcccgccggcggccaacctaaactctgt---ttttatcgtggcacttctgagga-
-ttattctaaatgaattaaaactttcaacaacggatctcttggttctggcatcgatgaag
aacgcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaatcatcgaatcttt
gaacgcacattgcgcccattagtattctagtgggcatgcctgttcgagcgtcatttcaa-
-ctatcaagccctgt----ttgcttggcgttgggagacttg-tag---gcccggcctgca
agctcctgaaatagat-cggcggagtcgtggcg-accctcagcgtagtaa---tctttct
cgcattaggt---gtcggcgccggcgtccggccgttaaaccc-cctat-ttattttagtc
ttgacctcgg
>Eutypella_caricae_AJ302460 610 bp 
gggatcattacagagtta------tctaactc-cc-aacccatgtg-aacttacc--ttt
gttgcctcggcggggga--------------------------gcctacccg---g----
tacctaccctgta----gttaccc-gggagcgagctaccctgtagcccgctgctg-----
-gccgacccgccggtggacagta-aaactcttg----tttttagtgaattatctgag-tg
tttatacttaataagttaaaactttcaacaacggatctcttggttctggcatcgatgaag
aacgcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaatcatcgaatcttt
gaacgcacattgcgcccattagtattctagtgggcatgcctgttcgagcgtcatttcaa-
-ccctcaagccccag----ttgcttggtgttgggagcttgc---ccctac--------gc
aactcctgaaagctat-tggcggagccgcattg-gccctaagcgtagtaa--tttttcct
cgcttcaggt-gtcccggtgctggcgtcctgccgtaaaaccc-ccaat-tttac-aatgg
ttgacctcgg
>Eutypella_cerviculata_AJ302461 610 bp 
gggatcattacagagtta-----ttttaactcctaaaccctatgtg-aacctacc--tat
gttgcctcggcggggaa--------------------------gcttaccct---g----
tacctactctgta----ggtactc--ggtgcgaactaccctgtagctagctgcta-----
-gctaacccgccgatggaccatttcaactcttg--ttttttctgtggcacatctgaactg
tttatacttaataagttaaaactttcaacaacggatctcttggttctggcatcgatgaag
aacgcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaatcatcgaatcttt
gaacgcacattgcgcccattagtattctagtgggcatgcctgttcgagcgtcatttcga-
-ccatcaagctttat----ttgcttggagttgggagtttgc-ct-tac----------gc
aattccttaaatctat-tggcggagttgcaata-accctaagcgtagtaa--ttattcct
cgctttaggt-gtgttagcgctgacgtttagccgttaaaccc-cctatatttacgtaggt
ttgacctcgg
>Eutypella_cerviculata_AJ302468 610 bp 
gggatcattacagagtta-----ttttaactcc--aaacctatgtg-aacttatt--ttt
gttgcctcggcgaggga--------------------------acttacctg---g----
tacttaccctgta----agaactcaggaggcgagctaccctgtagcatgccgctg-----
-gcaaactcgccgaaggactattcgaattcttg--tttt---agtggcacatctgaactg
tttatacttaataagttaaaactttcaacaacggatctcttggttctggcatcgatgaag
aacgcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaatcatcgaatcttt
gaacgcacattgcgcccattagtattctagtgggcatgcctgttcgagcgtcatttcga-
-ccatcaagctttat----ctgcttggagttgggaatttac-tcataa----------gt
aattccttaaatctat-cggcggagttgcgata-atcccaagcgtagtaa--ttatttct
cgctttaggt-gtgttagcgctgacatttagccgttaaaccc-tttatatttacgtaggt
ttgacctcgg
>Eutypella_kochiana_AJ302462 610 bp 
gggatcattacagagtta------tccaactccgaaaccctttgag-aacttacc--ttg
gttgcctcggcgggacg--------------------------acctaccct---ggaag
gacctaccctgtagcgcgctaccc-tgtagcaacctaccctgtaggccccgtcccggggc
ggcgcgcccgccgacggccagtcgaaactctgt---ttataccgtggcacttctgaggat
gttatacttaataagttaaaactttcaacaacggatctcttggttctggcatcgatgaag
aacgcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaatcatcgaatcttt
gaacgcacattgcgcccactagtattctagtgggcatgcctgttcgagcgtcatttaaaa
cccatcaagccctattttgttgcttggcgttgggagatttc-cgggccgccgcgccgggg
aactcctcaaatctat-cggcggagtcgtggcg-accccaagcgtagtaa---ttcttct
cgcctgaggt---gtcggcgccggcgtcctgccgctaaaccc-cctatatttttaaagtc
ttgacctcgg
>Eutypella_leprosa_AJ302463 610 bp 
gggatcattaaagagtag-tttttacaacaactccaaacccatgtg-aacttacc--tat
gttgcctcggcggggaa--------------------------gcctaccct---g----
tacctaccctgta----gttaccc-tgt-a------------------------g-----
-gtctacccgccagaggacttct-aaactctgt----ttttatatgaaacttctgag-tg
tttaaacttaat-agttaaaactttcaacaacggatctcttggttctggcatcgatgaag
aacgcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaatcatcgaatcttt
gaacgcacattgcgcccattagtattctagtgggcatgcctgttcgagcgtcatttcaa-
-ccatcaagccctat----ttgcttggcgttgggagcttac-cctgcacttgcggg--ac
aactccttaaatatat-tggcggagtcgcgaag-accccaagcgtagtaat-ttttttct
cgctttag---gtgtcgacgctggcatccagccactaaaccc-ccaa--ttttg-taggt
ttgacctcgg
>Eutypella_prunastri_AJ302464 610 bp 
gggatcattatagagtta------tctaactc-ccaaacccatgtg-aacttacc--tat
gttgcctcggcggggaa--------------------------gcctacccg---g----
tacctaccctgta----gttaccc-gggagcgagctaccctgtagcccgctgctg-----
-gcctacccgccggtggacagtt-aaactcttg-----atatagtggaacttctgat-at
tttatacttaataagttaaaactttcaacaacggatctcttggttctggcatcgatgaag
aacgcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaatcatcgaatcttt
gaacgcacattgcgcccattagtattctagtgggcatgcctgttcgagcgtcatttcaa-
-ccctcaagccctag----cggtttggtgttgggagtttat---ctacgg--------at
aattcctgaaaagcat-cggcggagccgtgctg-gccccaagcgtagtaa--ttttttct
cgcttcaggtg--tccggcgctggttttcagccgctaaaccc-cccaa-tttt-taatgg
ttgacctcgg
>Eutypella_scoparia_AJ302465 610 bp 
gggatcattaatgagttt------tctaaactccaaaccctt--ga-gaacatac--cta
gttgcctcggcg----g--------------------------acttgccct---gggac
gacctaccctgcagcgagttaccc-tgtaacgagttgccctgtagggacctgccc--tgt
agcctgctcgccggcggccaacctaaactctg----ttttattgtggcacttctgagga-
-ttattctaaatgaattaaaactttcaacaacggatctcttggttctggcatcgatgaag
aacgcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaatcatcgaatcttt
gaacgcacattgcgcccattagtattctagtgggcatgcctgttcgagcgtcatttcaa-
-ccatcaagccctat----ttgcttggcgttgggagacttg-tag---gtctggcctgca
agctcctgaaatagat-cggcggagtcgtggcg-accctcagcgtagtaa---ttcttct
cgctttaggt---gtcggcgctggcgtttagccgttaaaccc-cctat-ttcttttagtc
ttgacctcgg
>Eutypella_scoparia_DFMAL100 610 bp 
gggatcattaatgagttt------tctaaactccaaaccctt--ga-gaacatac--cta
gttgcctcggcg----g--------------------------acttgccct---gggac
gacctaccctgcagcgagttaccc-tgtaacgagttgccctgtagggacctgccc--tgt
agcctgctcgccggcggccaacctaaactctg----ttttattgtggcacttctgagga-
-ttattctaaatgaattaaaactttcaacaacggatctcttggttctggcatcgatgaag
aacgcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaatcatcgaatcttt
gaacgcacattgcgcccattagtattctagtgggcatgcctgttcgagcgtcatttcaa-
-ccatcaagccctat----ttgcttggcgttgggagacttg-tag---gtctggcctgca
agctcctgaaatagat-cggcggagtcgtggcg-accctcagcgtagtaa---ttcttct
cgctttaggt---gtcggcgctggcgtttagccgttaaaccc-cctat-ttcttttagtc
ttgacctcgg
>Eutypella_sp_DNEG200 610 bp 
gggatcattaaagagtag-ttattacaacaactccaaacccatgtg-aacttacc--tat
gttgcctcggcggggga--------------------------acctacccg---g----
tacttaccctgta-----------------------------------------------
-ggcgacccgccgatggaccatc-aaactctgt----ttat-tatgtaacttctgag-tg
tttaaacttaataagttaaaactttcaacaacggatctcttggttctggcatcgatgaag
aacgcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaatcatcgaatcttt
gaacgcacattgcgcccattagtattctagtgggcatgcctgttcgagcgtcatttcaa-
-ccatcaagccctat----ttgcttggcgttgggagcttaa-cctac-cctgtagg--at
aactcctcaaatatat-tggcggagtcgcgaag-accccaagcgtagtaa--ttttttct
cgcttcaggt-gtgtcggcgctggcatccagccactaaaccc-ctaa--ttttt-tagtc
ttgacctcgg
>Eutypella_sp_UCD2336Co 610 bp 
gggatcattaatgagttt------tctaaactccaaaccctt--ga-gaacatac--cta
gttgcctcggcg----g--------------------------acttgccct---gggac
gacctaccctgcagcgagttaccc-tgtaacgagttgccctgtagagacctgccc--tgt
agcctgcccgccggcggccaacctaaactctg----ttttattgtggcacttctgagga-
-ttattctaaatgaattaaaactttcaacaacggatctcttggttctggcatcgatgaag
aacgcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaatcatcgaatcttt
gaacgcacattgcgcccattagtattctagtgggcatgcctgttcgagcgtcatttcaa-
-ccatcaagccctat----ttgcttggcgttgggagacttg-tag---gcccggcctgca
agctcctgaaatagat-cggcggagtcgtggcg-accctcagcgtagtaa---ttcttct
cgctttaggt---gtcggcgctggcgtttagccgttaaaccc-cctat-tt-ttttagtc
ttgacctcgg
>Eutypella_sp_UCD2338Co 610 bp 
gggatcattaaagagtag-tttttacaacaactccaaacccatgtg-aacttacc--tat
gttgcctcggcggggga--------------------------acctacccg---g----
tacttaccctgta-----------------------------------------------
-ggcgacccgccgatggaccatc-aaactctgt----ttat-tatgtaacttctgag-tg
tttaaacttaataagttaaaactttcaacaacggatctcttggttctggcatcgatgaag
aacgcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaatcatcgaatcttt
gaacgcacattgcgcccattagtattctagtgggcatgcctgttcgagcgtcatttcaa-
-ccatcaagccctat----ttgcttggcgttgggagcttaa-cctac-cctgtagg--at
aactcctcaaatatat-tggcggagtcgcgaag-accccaagcgtagtaa--ttttttct
cgcttcaggt-gtgtcggcgctggcatccagccactaaaccc-ctaa--ttttt-tagtc
ttgacctcgg
>Eutypella_sp_UCD2342Co 610 bp 
gggatcattaaagagtagttttttacaacaactccaaacccatgtg-aacttacc--tat
gttgcctcggcggggag--------------------------acctacccg---g----
tagttaccctgta----gttaccc-tgt-a------------------------g-----
-agctacccgtcgacggaccatc-aaactctgt----ttttctatgaaacttctgag-tg
ttttaacttaataaattaaaactttcaacaacggatctcttggttctggcatcgatgaag
aacgcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaatcatcgaatcttt
gaacgcacattgcgcccattagtattctagtgggcatgcctgttcgagcgtcatttcga-
-ccatcaagccctat----ttgcttggcgttgggagcttac-cctgcagctgcggg--at
aactcctcaaatatat-tggcagagtcgcgaag-accctaagtgtagtaa---ttcttct
cgcttcagca-gtgttgacgctggcatctagccactaaaccc-ttaat-tttta-taggt
ttgacctcgg
>Eutypella_sp_UCD2353Co 610 bp 
gggatcattaaagagtagttttttacaacaactccaaacccatgtg-aacttacc--tat
gttgcctcggcggggag--------------------------acctacccg---g----
tagttaccctgta----gttaccc-tgt-a------------------------g-----
-agctacccgtcgacggaccatc-aaactctgt----ttttctatgaaacttctgag-tg
ttttaacttaataaattaaaactttcaacaacggatctcttggttctggcatcgatgaag
aacgcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaatcatcgaatcttt
gaacgcacattgcgcccattagtattctagtgggcatgcctgttcgagcgtcatttcga-
-ccatcaagccctat----ttgcttggcgttgggagtttac-cctgcagctgcggg--at
aactcctcaaatatat-tggcagagtcgcgaag-accctaagcgtagtaa---ttcttct
cgcttcagca-gtgttaacgctggcgtctagccactaaaccc-ctaat-tttta-taggt
ttgacctcgg
>Eutypella_sp_UCD3Co 610 bp 
gggatcattaaagagtag-tttttacaacaactccaaacccatgtg-aacttacc--tat
gttgcctcggcggggga--------------------------acctacccg---g----
tacttaccctgta-----------------------------------------------
-ggcgacccgccgatggaccatc-aaactctgt----ttat-tatgtaacttctgag-tg
tttaaacttaataagttaaaactttcaacaacggatctcttggttctggcatcgatgaag
aacgcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaatcatcgaatcttt
gaacgcacattgcgcccattagtattctagtgggcatgcctgttcgagcgtcatttcaa-
-ccatcaagccctat----ttgcttggcgttgggagcttaa-cctac-cctgtagg--at
aactcctcaaatatat-tggcggagtcgcgaag-accccaagcgtagtaa--ttttttct
cgcttcaggt-gtgtcggcgctggcatccagccactaaaccc-ctaa--ttttt-tagtc
ttgacctcgg
>Eutypella_sp_UCD713SJ 610 bp 
gggatcattaaagagtag-tttttacaacaactccaaacccatgtg-aacttacc--tat
gttgcctcggcggggaa--------------------------gcctaccct---g----
tacc---------------taccc-tgt-a------------------------g-----
-gcctacccgccagaggacttct-aaactctgt----ttttatatgaaacttctgag-tg
tttaaacttaat-agttaaaactttcaacaacggatctcttggttctggcatcgatgaag
aacgcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaatcatcgaatcttt
gaacgcacattgcgcccattagtattctagtgggcatgcctgttcgagcgtcatttcaa-
-ccatcaagccctat----ttgcttggcgttgggagcttac-cctgcacttgcggg--at
aactccttaaatatat-tggcggagtcgcggag-accccaagcgtagtaa--ttttttct
cgctttag---gtgtcgacgctggcatccagccactaaaccc-ccaa--tttta-taggt
ttgacctcgg
>Eutypella_vitis_AJ302466 610 bp 
gggatcattaaagagtag-tttttacaacaactccaaacccatgtg-aacttacc--tat
gttgcctcggcggggaa--------------------------a-ctacccg---g----
tagctaccctgta----gctaccc-tgtaa------------------------g-----
-gaatactcgtcgacggaccatt-aaactctgt----ttttctatgaaacttctgag-tg
ttttaacttaataaattaaaactttcaacaacggatctcttggttctggcatcgatgaag
aacgcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaatcatcgaatcttt
gaacgcacattgcgcccattagtattctagtgggcatgcctgttcgagcgtcatttcga-
-ccatcaagccctat----ttgcttggcgttgggagcttac-cctgcagttgcggg--at
aactcctcaaatatat-tggcggagtcgcggag-accctaagcgtagtaa---ttcttct
cgctttagta-gtgttaacgctggcatctggccactaaaccc-ctaat-tttta-taggt
ttgacctcgg
>Eutypella_vitis_AY462566 610 bp 
gggatcattaaagagtag-tttttacaacaactccaaacccatgtg-aacttacc--tat
gttgcctcggcggggaa--------------------------a-ctacccg---g----
tagctaccctgta----gttaccc-tgtaa------------------------g-----
-gactactcgtcgacggaccatt-aaactctgt----ttttctatgaaacttctgag-tg
ttttaacttaataaattaaaactttcaacaacggatctcttggttctggcatcgatgaag
aacgcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaatcatcgaatcttt
gaacgcacattgcgcccattagtattctagtgggcatgcctgttcgagcgtcatttcga-
-ccatcaagccctat----ttgcttggcgttgggagcttac-cctgcagttgcggg--at
aactcctcaaatatat-tggcggagtcgcggag-accctaagcgtagtaa---ttcttct
cgctttagta-gtgtcaacgctggcatctggccactaaaccc-ctaat-tttta-taggt
ttgacctcgg
>Eutypella_vitis_AY462568 610 bp 
gggatcattaaagagtag-tttttacaacaactccaaacccatgtg-aacttacc--tat
gttgcctcggcggggaa--------------------------a-ctacccg---g----
tagctaccctgta----gctaccc-tgtaa------------------------g-----
-gactactcgtcgacggaccatt-aaactctgt----ttttctatgaaacttctgag-tg
ttttaacttaataaattaaaactttcaacaacggatctcttggttctggcatcgatgaag
aacgcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaatcatcgaatcttt
gaacgcacattgcgcccattagtattctagtgggcatgcctgttcgagcgtcatttcga-
-ccatcaagccctat----ttgcttggcgttgggagcttac-cctgcagttgcggg--at
aactcctcaaatatat-tggcggagtcgcggag-accctaagcgtagtaa---ttcttct
cgctttagta-gtgtcaacgctggcatctggccactaaaccc-ctaat-tttta-taggt
ttgacctcgg
>Libertella_sp_DQ286281 610 bp 
-ggatcattaaagagtag-ttattacaacaactccaaacccatgtg-aacttacc--tat
gttgcctcggcggggga--------------------------acctacccg---g----
tacttaccctgta-----------------------------------------------
-ggcgacccgccgatggaccatc-aaactctgt----ttat-tatgtaacttctgag-tg
tttaaacttaataagttaaaactttcaacaacggatctcttggttctggcatcgatgaag
aacgcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaatcatcgaatcttt
gaacgcacattgcgcccattagtattctagtgggcatgcctgttcgagcgtcatttcaa-
-ccatcaagccctat----ttgcttggcgttgggagcttaa-cctac-cctgtagg--at
aactcctcaaatatat-tggcggagtcgcgaag-accccaagcgtagtaa--ttttttct
cgcttcaggt-gtgtcggcgctggcattcagccactaaaccc-ctaa--ttttt-tagtc
ttgacctcgg
>Whalleya_microplaca_AJ390420 610 bp 
gggatcattaatgagtta------aaaaactcctaaacccactgtg-aacataccatttt
gttgcctcggcaggttgtgtttgccctgtagctgctaccctggacctaccct---g----
gacctaccctgta----gctacct-ggtaacacgttt-----------------------
-aacggcctgccggtggtcttct-aaactcttg--ctatatattgcgaatttctgaacaa
gtaaaacttaataagttaaaactttcaacaacggatctcttggttctggcatcgatgaag
aacgcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaatcatcgaatcttt
gaacgcacattgcgcctactagtattctagtgggcatgcctgttcgagcgtcatttcga-
-cccttaagcctctg----ttgcttagtgttgggagcctacggttatagc--------gt
agctccttaaagttagttggcggagttagggtacactctcagcgtagtaaacatttttct
cgctgttgtagttgccttagctg-----ttgccattaaacctgtctattatttagtaagg
ttgacctc--
