>Callicarpa_giraldii 676 bp 
tcgagacccgcaaagtagaccgcgaacacgtg-tttaaccacattgggcccgcggcgcgg
ggggaagcctcccgtcgcgatcccatccccgccggcgtgcgcgagagcgttc-----cgt
cgtgcgggc-taacgaacccc-ggcgcggcatgcgccaaggaaaat-gaaac--gtagcg
tccgcct--cccgacgccccgttc-gcggggcgcgcgg-ggggacgggacg---------
---tctatcg---aatgtcaaaacgactctcggcaacggatatctcggctctcgcatcga
tgaagaacgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtgaaccatcgag
tctttgaacgcaagttgcgcccgaagccattaggccgagggcacgtctgcctgggcgtca
cgcatcgcgtcgcccccc--tccccgcgcaccgcgctcgcga--------ggggggcgga
gattggccccccgtgcgcgcttccgtcgcgtgcggtcggcccaaatgcgatccctcggcg
acgcacgtcacgactagtggtggttg-aacaacgctcaa---ctctcgtgctgtcgtgcg
gcaccgcgtcgtccgttcgggca------tcaaca-acgacccaa---------------
-------------actttcgacc
>Clinopodium_tomentosum 679 bp 
------cctgcaaagcagaccgcgaacacgt--actaacgccgc-gggtgc--ggcgcgg
gggcaaccccc-tgccgtgtcccgtctcctgccggcgtgctccctc-gggtc----acgc
tgtgcgggc-taacgaacccc-ggcgcggaatgcgccaaggaaaac-cgaac--gaagcg
tccgcc---cctggcatcccgttc-gcggagcgtgccg-cgggatcgggcg---------
---tctatca---aatgtcaaaacgactctcggcaacggatatctcggctctcgcatcga
tgaagaacgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtgaaccatcgag
tctttgaacgcaagttgcgcccgaagccattaggccgagggcacgtctgcctgggcgtca
cgcatcgcgtcgcccccca-cccccgcgcgcatcgccgggcg------gttgggggcgga
cactggcctcccgtgcg-----cctcggcgtgcggccggcccaaatgagatccccgggcg
actggcgtcacgacaagtggtggttg-aacat--ctcaat--ctctctcgtggtc--gtg
ccgccgtgtcgtcccgtacgggaa-----tcgaga-atgacccaacggtg---cacggcg
cgaacagcgtcycacctccgacc
>Coleus_xanthanthus 676 bp 
tcgaaacctgcaaagcagaccgcggac-cgtg-tttaacgccgacc--------------
-------------------------cccccgccgggacgcgcgccccagtgc-gcccccc
cgcgcgggc-taacaaacccc-ggcgcagtacgcgccaaggaaaac-agaaaaggatgca
gcgccgccgcggcgcgccccgtccggcgggacgcgcgc-cgtcgtccggcg---------
---tctgtct-tgaaagtcgaaacgactctcggcaacggatatctcggctctcgcatcga
tgaagaacgtagtgaaatgcgatacttggtgtgaattgcagaatcccgtgaaccatcgag
tctttgaacgcaagttgcgcccgaagccattaggccgagggcacgtctgcctgggcgtca
cgcatcgcgtcgccccccgcccgc-----------atcggga--------cgggggcgga
cactggcctcccgtgcg-----ccccggcgcgcggccggcccaaatgcgatcccccggcg
acccgcgtcgcggcaagtggtggttg-agcac--ctcaat------cgatccgcc--gcg
accccgggccgtccgcacgggcgt-----cgacca-ccaaccctacggca----------
------cgcgagtgcctccgacc
>Collinsonia_canadensis 676 bp 
tcgaaacctgcaaagcagaccgtgaacacgtg-tttaacatca--ccgggcacggtgt-g
gggagactcac---gccgtgtaccacccccgccg--gtgcgcgccctcgggc-gtcgaat
cgtgcgggc-taacgaacccc-ggcgcggcatgcgccaaggaaaac-aaaat--ttagcg
tctgcc---ctccgcatcccgttc-gcggggtgtgcggtg-ggagtggacg---------
---tctatcg---aatgtcataacgactctcggcaacggatatctcggctctcgcatcga
tgaagaacgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtgaaccatcgag
tctttgaacgcaagttgcgcccgaagccattaggccgagggcacgtctgcctgggcgtca
cgcatcgcgtcgcccctc--tccccgcgccgagcgctcgtga--------agggggcgga
tattggcctcccgtgcg-----ccccggcgtgcggctggcccaaatgagatccctcggcg
actcatgtcgcgactggtggtggttg-aataa--ctcaat--ctcgcgtcttgtc--gtg
ctactgcgtcgttcgtacgggcag-----cgaata-atgacccaacggtg-ctcgtgtgt
tacagcac--cgcaccttcgacc
>Elsholtzia_ciliata 676 bp 
tcgaaacctgcaaagtagaccgcgaacatgtg-tttaacatca--tcaggcgcggcgtgg
gggaaactccc---gtcgcgtcctgcccctgccg--gtgtacgctctcgggc-gctgcat
cgtgcgggc-taacgaacccc-ggcgcggcacgcgccaaggaaaac-gaaat--ttagca
tccgcc---ctccgcatcccgttc-gcggggcgtgcg--ggggagcggctg---------
---tctatcg---aacgtcataacgactctcggcaacggatatctcggctctcgcatcga
tgaagaacgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtgaaccatcgag
tctttgaacgcaagttgcgcccgaagccgtcaggccgagggcacgtctgcatgggcgtca
cgcatcgcgtcgcccccc--tccccgccctcagtgctcgtga--------gtggggtgga
tattggcctcccgtgcg-----cttcagcgtgcggctggcccaaatgtgatccctcggcg
actcgcatcgcgactagtggtggttg-aacag--ctcaat--ctcgcgtcgtgtcgtgtg
ttgcgttgttgtccgcgcgggcat-----cggatg-caaacccaacggtg-----gcggt
gctcgcac--cgcgccttcgacc
>Eriope_latifolia 676 bp 
tcgaaacctgcaaagcagaccgcgaacacgtg-taaaacgcat--c--------------
-------------------------tccccgccgtcgcgccccgcgc---------gcgt
cgtgcgggc-taacgaacccc-ggcgcggcacgcgccaaggaaaac-cgaac--caggcg
ccgtcct--ccccgcatcccgtcc-gcgggcagtgcgg-ggggcgtcgggc---------
---tccattga--aaagtcaaaacgactctcggcaacggatatctcggctctcgcatcga
tgaagaacgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtgaaccatcgag
tctttgaacgcaagttgcgcccgaagccatcaggccgagggcacgtctgcctgggcgtca
cgcat--cgtcgcccccc--tccccgcgctccgtgc---ggg------acggggggcgga
tattggcctcccgtgcg-----ccccggcgcgcggttggcccaaatgcgatccccatgcg
gcccgagtcgcgacaagtggtggttg-aaatc--ctcaat--ctctcgtctcgtc--gtg
catccgggccgtgcgtgcgggcat-----cggacatacgaccctacggcg---cggaggc
c------c--cgcgccctcgatc
>Hanceola_exserta 676 bp 
tcgaaacctgcgaggcagaccgcgaacacgtg-tttaacgcca--t--------------
-------------------------cccccgccgccgcgcgcgcacccgtgc-gccgcgt
cgcgcgggc-taacgaacccc-ggcgcggaacgcgccaaggaaaac-agaat--gtagcg
ccggccc--cc-cagcaccc-----------cgtgcgg-ggggagcgggcg---------
---tctatcg---aatgtcaaaacgactctcggcaacggatatctcggctctcgcatcga
tgaagaacgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtgaaccatcgag
tctttgaacgcaagttgcgcccgaagccgtcaggccgagggcacgtctgcctgggcgtca
cgcatcgcgtcgccccccc-tacccgcgcaccgcgctcgtgg------t-ggggggcgga
tattggcctcccgtgcg-----ccccggcgcgcggccggcccaaattcgatccctcggcg
accggcgtcgcgacaagtggtggttg-aactc--ctcaat--ctcgcgcctcgtc--gtg
ctgccggatcgtccgtacgggctt-----cgaaca-acgacccaacggcg---cgg--cc
tttgcggc--tgcgccttcgacc
>Hanceola_sinensis_1 676 bp 
tcgaaacctgcgaggcagaccgcgaacacgtg-tttaacgcca--t--------------
-------------------------cccccgccgccgcgcgcgcccccgtgc-gccgcgt
cgtgcgggc-taacgaacccc-ggcgcggaacgcgccaaggaaaac-agaat--gtagcg
ccggccc--cc-cgcatcccgtcc-gcggtgcgtgcgg-ggggatccggcg---------
---tctatcg---aatgtcaaaacgactctcggcaacggatatctcggctctcgcatcga
tgaagaacgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtgaaccatcgag
tctttgaacgcaagttgcgcccgaagccgtcaggccgagggcacgtctgcctgggcgtca
cgcatcgcgtcgccccccc-tccccgcgctccgcgctcgtgg------tgggggggcgga
tattggcctcccgtgcg-----ccccggcgcgcggccggcccaaatgcgatcccccggcg
acccgcgtcgcgacaagtggtggttg-aactc--ctcaat--ctcgcgcctcgtc--gtg
atgccgggtcgtccgtgcgggctt-----cgagca-acgacccaacggcg---cggc-cc
tctgcggc--cgcgccttcgacc
>Hanceola_sinensis_2 676 bp 
tcgagacctgcgaggcagaccgcgaacacgtg-tttaacgcca--t--------------
-------------------------cccccgccgccgcgcgcgc-cccgtgc-gccgcgt
cgtgcgggc-taacgaacccc-ggcgcggaacgcgccaaggaaaac--gaat--gtagcg
ccgg-cc--cc-cgcatcccgtcc-gcggtgcgtgcgg-ggggatccggcg---------
---tctatcg---aatgtcaaaacgactctcggcaacggatatctcggctctcgcatcga
tgaagaacgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtgaaccatcgag
tctttgaacgcaagttgcgcccgaagccgtcaggccgagggcacgtctgcctgggcgtca
cgcatcgcgtcgccccccc-tccccgcgcgccgcgctcgtgg------tgggggggcgga
tattggcctcccgtgcg-----ccccggcgcgcggccggcccaaatgcgatcccccggcg
acccgcgtcgcgacaagtggtggttg-aactc--ctcaat--ctcgcg-ctcgtc--gtg
atgccgggtcgtccgtgcgggctt-----cgagc--acgacccaacggcg---cggc-cc
tctgcggc--cgcgccttcgacc
>Hanceola_sinensis_3 676 bp 
-tcgaacctgcgaggcagaccgcgaacacgtg-tttaacgcca--t--------------
-------------------------cccccgccgccgcgcgcgcacccgtgc-gccgcgt
cgtgcgggc-taacgaacccc-ggcgcggaacgcgccaaggaaaac--gaat--gtagcg
ccggccc--cc-cgcatcccgtcc-gcgg-gcgtgcgg-ggggatccggcg---------
---tctatcg---aatgtcaaaacgactctcggcaacggatatctcggctctcgcatcga
tgaagaacgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtgaaccatcgag
tctttgaacgcaagttgcgcccgaagccgtcaggccgagggcacgtctgcctgggcgtca
cgcatcgcgtcgccccccc-tccccgcgcgccgcgctcgtgg------tgggggggcgga
tattggcctcccgtgcg-----ccccggcgcgcggccggcccaaatgcgatcccccggcg
acccgcgtcgcgacaagtggtggttg-aactc--ctcaat--ctcgcg-ctcgtc--gtg
atgccgggtcgtccgtgcgggctt-----cgagc--acgacccaacggcg---cggc-cc
tctgcggc--cgcgccttcgacc
>Hyptis_alata 676 bp 
tcgaaacctgcaaagcagaccgcgaacacgta-cctaaagcat--c--------------
-------------------------tcctcgccggcgcactcgt------------gtgt
cgtgcgggc-taacgaacccc-ggcgcggcatgcgccaaggaatac-cgaac--gtggca
ttggccc--ccaggcatcccgttc-gcgggtactgccg-gggaagtcgatg---------
---tctatcg---aatgtcaaaacgactctcggcaacggatatctcggctctcgcatcga
tgaagaacgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtgaaccatcgag
tctttgaacgcaagttgcgcccaaagccattaggccgagggcacgcctgcctgggcgtca
cgcatcgcgtcgcccccat---cccacgctg------cgtgg------aatgggggtgga
tactggcctcccgtgcg-----cccgtgcgtgcggccggcccaaatgcgatcccccggcg
acccgtgtcgcgacaagtggtggttg-aactc--ctcaat--ctcaagtctcgtc--gtg
cattcgaactgtccgtgcgggcat-----cattta-gcgacccaacggtg---cggtggc
cctgccgc--cgcactctcgacc
>Hyptis_brevipes 676 bp 
tcgaaacctgcaaagcagaccgcgaacacgtg-actaacgcat--c--------------
-------------------------tccccgccggcgcacccgt------------gcgt
cgtgcgggc-taacgaacccc-ggcgcggcatgcgccaaggaaaac-cgaac--gtggca
tcggccc--cc-cgcatcccgtcc-gcgggcagtgcag-gggcagtcgacg---------
---tctatcg---aatgtcaaaacgactctcggcaacggatatctcggctctcgcatcga
tgaagaacgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtgaaccatcgag
tctttgaacgcaagttgcgcccgaagccattaggccgagggcacgtctgcctgggcgtca
cgcatcgcgtcg--ccccc-tccccgcgctccg----cggga------acggggggcgga
tattggcctcccgtgag-----ccacggcgcgcggttggcccaaatgcgatcccccggcg
actcgcgtcgcgacaagtggtggttg-aactc--ctcaat--ctctcgtctcgtc--gcg
cattcgggttgtccgtgcgggcat-----cgaaca-tcgaccctacggcg---cggtggc
cccgctgc--cgcgctctcgacc
>Isodon_adenanthus 676 bp 
tcgaaacctgcaaagcagaccgcgaacacgtt-tctaacgcca--t--------------
-------------------------cccccgccgcagcgcgcgcactcgtgc-cgcactg
cgtgcgggc-taacgaacccc-ggcgcggaacgcgccaaggaaaacttaaat--ttagcg
tcggtcccgctccgcatcccgttc-gcgggtcgtgcggtgcggaacggacg---------
---tctatcg---aatgtcataacgactctcggcaacggatatctcggctctcgcatcga
tgaagaacgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtgaaccatcgag
tctttgaacgcaagttgcgcccgaagccattaggccgagggcacgtctgcctgggcgtca
cgcatcgcgtcgct-ccc--ccca--cccacg---ttggcga--------ggggggcgga
tattggcctcccgtgtg-----cctcggcgtgcggccggcccaaatgagatcccccggcg
actcgcgtcgcgacaagtggtggttg-aacat--ctcaat--ctcgcgtctcgtc--gtg
--gccgagccgtccgtggtgatc------cgaacg-atgacccaacggag-ct-------
----------tgctccttcgact
>Isodon_adenolomus 676 bp 
tcgaaacctgcaaagcagaccgcgaacacgtt-tctaacgcca--t--------------
-------------------------cccccgccgcagcgcgcgcactcgtgc-cgcgctg
cgtgcgggc-taacgaacccc-ggcgcggaacgcgccaaggaaaacttaaat--ttagcg
tcggtcccgccccgcatcccgttc-gcgggccgtgcggtgcggaacgggcg---------
---tctatcg---aatgtcataacgactctcggcaacggatatctcggctctcgcatcga
tgaagaacgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtgaaccatcgag
tctttgaacgcaagttgcgcccgaagccattaggccgagggcacgtctgcctgggcgtca
cgcatcgcgtcgct-ccc--cccc--accact---ctggcga-------gggggggcgga
tattggcctcccgtgcg-----cctcggcgtgcggccggcccaaatgcgatcccccggcg
actcgcgtcgcgacaagtggtggttg-aacat--ctcaat--ctcgcgtctcgtc--gtg
ccgccgagccgtccgtggtgatc------cgaacg-atgacccaacggag-ct-------
----------tgctccttcgacc
>Isodon_amethystoides 676 bp 
tcgaaacctgcaaagcagaccgcgaacacgtt-tctaacgcca--t--------------
-------------------------cccccgccgcagcgcgcgcactcgtgc-cgcgcgg
cgtgcgggc-taacgaacccc-ggcgcggaacgcgccaaggaaaacttaaat--ttagcg
tcggtcccgccccgcatcccgttc-gcgggccgtgcggtgcggaacgggcg---------
---tctatag---aatgtcataacgactctcggcaacggatatctcggctctcgcatcga
tgaagaacgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtgaaccatcgag
tctttgaacgcaagttgcgcccgaagccattaggccgagggcacgtctgcctgggcgtca
cgcatcgcgtcgct-ccc--cccc--accact---ctggcga--------ggggggcgga
tattggcctcccgtg-g-----cctcggcgtgcggccggcccaaatgcgatcccccggcg
actcgcgtcgcgacaagtggtggttg-aacat--ctcaat--ctcgcgtctcgtc--gtg
ccgccgagccgtccgtggtgatc------cgaacg-atgacccaacggag-ct-------
----------tgctccttcgacc
>Isodon_bulleyanus 676 bp 
tcgaaacctgcaaagcagactgcgaacacgtt-tctaacgcca--t--------------
-------------------------cccccgccgcagcgcgcgcactcgtgc-cgcgcgg
cgtgcgggc-taacgaacccc-ggcgcggaacgcgccaaggaaaacttaaat--ttagcg
tcggtcccgccccgcatcccgttc-gcgggcattgcggtgcggaacgggcg---------
---tctattg---aatgtcataacgactctcggcaacggatatctcggctctcgcatcga
tgaagaacgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtgaaccatcgag
tctttgaacgcaagttgcgcccgaagccattaggccgagggcacgtctgcctgggcgtca
cgcatcgcgtcgct-ccc--cccc--accaccacgctggcga-------gggggggcgga
tattggcctcccgtgcg-----cctcggcgtgcggccggcccaaatgcgatcccccggcg
actcgcgtcgcgacaagtggtggttg-aacat--ctcaat--ctcgcgtctcgtc--gtg
ccgccgagccgtccgtggcgatc------cgaacg-atgacccaacggag-ct-------
----------tgctccttcgacc
>Isodon_calcicolus 676 bp 
tcgaaacctgcaaagcagactgcgaacacgtt-tctaacgcca--t--------------
-------------------------cccccgccgcagcgcgcgcactcgtgc-cgcgcgg
cgtgcgggc-taacgaacccc-ggcgcggaacgcgccaaggaaaacttaaat--ttagcg
tcggtcccgccccgcatcccgttc-gcgggcattgcggtgcggaacgggcg---------
---tctattg---aatgtcataacgactctcggcaacggatatctcggctctcgcatcga
tgaagaacgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtgaaccatcgag
tctttgaacgcaagttgcgcccgaagccattaggccgagggcacgtctgcctgggcgtca
cgcatcgcgtcgct-ccc--cccc--accaccacgctggcga-------gggggggcgga
tattggcctcccgtgcg-----cctcggcgtgcggccggcccaaatgcgatcccccggcg
actcgcgtcgcgacaagtggtggttg-aacat--ctcaat--ctcgcgtctcgtc--gtg
ccgccgagccgtccgtggcgatc------cgaacg-atgacccaacggag-ct-------
----------tgctccttcgacc
>Isodon_coetsa 676 bp 
tcgaaacctgcaaagtagaccgcgaacatgtt-tctaatgcca--t--------------
-------------------------cccctgccgcagcgcgtgctctcgtgc-cgcgcgg
cgtgcgggc-taacgaacccc-ggcgcggaacgcgccaaggaaaacttaaat--ttagcg
tcggtcccaccccgcatcccgttc-gcgggccgtgcggtgtggaa-gggcg---------
---tctatcg---aatgtcataacgactctcggcaacggatatctcggctctcgcatcga
tgaagaacgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtgaaccatcgag
tctttgaacgcaagttgcgcccgaagccattaggccgagggcacgtctgcctgggcgtca
cgcatcgcgtcgctcccc--cccc--accacg---ctggcga--------ggggggcgga
tattggcctcccgtgcg-----cctcggcgtgcggctggcccaaatgcgatcccccggcg
actcgcgtcgcgacaagtggtggttg-aacat--ctcaat--ctcgcgtctcgtc--gtg
c--gcgagccgtccgtggtgatc------c-aacg-atgacccaacggag-ct-------
----------tgctccttcgacc
>Isodon_eriocalyx_1 676 bp 
tcgaaacctgcaaagcagaccgagaacacgtt-tctaacgcca--t--------------
-------------------------cccccgccgcggtgcgcgcactcgtgc-cgcgctg
cgtgcgggc-taacgaacccc-ggcgcggaaagcgccaaggaaaacttaaat--ttagcg
tcggtctcgccccgcatcccgttc-gcgggccgtgcggtgcggaacgggcg---------
---tctatcg---aatgtcataacgactctcggcaacggatatctcggctctcgcatcga
tgaagaacgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtgaaccatcgag
tctttgaacgcaagttgcgcccgaagccattaggccgagggcacgtctgcctgggcatca
cgcatcgcgtcgct-ccc--cccc--accact---ctggcga-------gggggggcgga
tattggcctcccgtgca-----cctcggcgtgcggccggcccaaatgcgatcccccggcg
actcgcgtcgcgacaagtggtggttg-aacat--ctcaat--ctcgcgtctcgtc--gtg
ccgccgagccgtccgtggtggtc------cgaacg-atgacccaacggag-ct-------
----------tgctccttcgacc
>Isodon_eriocalyx_2 676 bp 
tcgaaacctgcaaagcagaccgagaacacgtt-tctaacgcca--t--------------
-------------------------cccccgccgcggtgcgcgcactcgtgc-cgcgctg
cgtgcgggc-taacgaacccc-ggcgcggaaagcgccaaggaaaacttaaat--ttagcg
tcggtctcgccccgcatcccgttc-gcgggccgtgcggtgcggaacgggcg---------
---tctatcg---aatgtcaaaacgactctcggcaacggatatctcggctctcgcatcga
tgaagaacgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtgaaccatcgag
tctttgaacgcaagttgcgcccgaagccattaggccgagggcacgtctgcctgggcgtca
cgcatcgcgtcgct-ccc--cccc--accact---ctggcgaggggggggggggggcgga
tattggcctcccgtgcg-----cctcgtcgtgcggccggcccaaatgcgatcccccggcg
actcgcgtcgcgataagtggtggttg-aacat--ctcaat--cttgcgtctcgtc--gtg
ccgccgagccgtccgtggtgatc------cgaacg-atgacccaacggag-ct-------
----------tgctccttcgacc
>Isodon_eriocalyx_3 676 bp 
tcgaaacctgcaaagcagaccgagaacacgtt-tctaacgcca--t--------------
-------------------------cccccgccgcggtgcgcgcactcgtgc-cgcgctg
cgtgcgggc-taacgaacccc-ggcgcggaaagcgccaaggaaaacttaaat--ttagcg
tcggtcccgccccgcatcccgttc-gcgggccgtgcggtgcggaacgggcg---------
---tctatcg---aatgtcataacgactctcggcaacggatatctcggctctcgcatcga
tgaagaacgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtgaaccatcgag
tctttgaacgcaagttgcgcccgaagccattaggccgagggcacgtctgcctgggcgtca
cgcatcgcgtcgct-ccc--cccc--accact---ctggcga------ggggggggcgga
tattggcctcccgtgcg-----cctcggcgtgcggccggcccaaatgcgatcccccggcg
actcgcgtcgcgacaagtggtggttg-aacat--ctcaat--ctcgcgtctcgtc--gtg
ccgccgagccgtccgtggtgatc------cgaacg-atgacccaacggag-ct-------
----------tgctccttcgacc
>Isodon_eriocalyx_4 676 bp 
tcgaaacctgcaaagcagaccgagaacacgtt-tctaacgcca--t--------------
-------------------------cccccgccgcgg-gcgcgcactcgtgc-cgcgctg
cgtgcgggc-taacgaacccc-ggcgcggaaagcgccaaggaaaacttaaat--ttagcg
tcggtc-cgccccgcatcccgttc-gcgggccgtgcggtgcggaacgggcg---------
---tctatcg---aatgtcataacgactctcggcaacggatatctcggctctcgcatcga
tgaagaacgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtgaaccatcgag
tctttgaacgcaagttgcgcccgaagccattaggccgagggcacgtctgcctgggcgtca
cgcatcgcgtcgct-ccc--cccc--accact---ctggcga-------gggggggcgga
tattggcctcccgtgc------cctcggcgtgcggccggcccaaatgcgatcccccggcg
actcgcgtcgcgacaagtggtggttg-aacat--ctcaat--ctcgcgtctcgtc--gtg
ccgccgagccgtccgtggtgatc------cgaacg-atgacccaacggag-ct-------
----------tgctccttcgacc
>Isodon_flabelliformis 676 bp 
tcgaaacctgcaaagcagaccgcgaacacgtt-tctaacgcca--t--------------
-------------------------cccccaccgcagcgcgcgcactcgtgc-cgcgctg
cgtgcgggc-taacgaacccc-ggcgcggaacgcgccaaggaaaacttaaat--ttagcg
tcggtcccgccccgcatcccgtta-gcgggccgtgcggtgcggaacgggcg---------
---tctatcg---aatgtcataacgactctcggcaacggatatctcggctctcgcatcga
tgaagaacgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtgaaccatcgag
tctttgaacgcaagttgcgcccgaagccattaggccgagggcacgtctgcctgggcgtca
cgcatcgcgtcgctcccc--cccc--accaccatgctggcga-------gggggggcgga
tattggcctcccgtgcg-----cctcggtgtgcggccggcccaaatgctatccctcggcg
actcgcgtcgcgacaagtggtggttg-aacat--ctcaat--ctcgcgtctcgtc--gtg
ctgccgagccgtccgtggtgatc------cgaacg-atgacccaacggag-ct-------
----------tgctccttcgacc
>Isodon_flavidus 676 bp 
tcgaaacctgcaaagcagaccgcgaacacgtt-tctaacgcca--t--------------
-------------------------cccccgccgcagcgcgcgcactcgtgc-cgcgctg
cgtgcgggc-taacgaacccc-ggcgcggaacgcgccaaggaaaacttaaat--ttagcg
tcggtcccgccccgcatcccgttc-gcgggccgtgcggtgcggaacgggcg---------
---tctatcg---aatgtcataacgactctcggcaacggatatctcggctctcgcatcga
tgaagaacgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtgaaccatcgag
tctttgaacgcaagttgcgcccgaagccattaggccgagggcacgtctgcctgggcgtca
cgcatcgcgtcgct-ccc--cccc--accact---ttggcga-------gggggggcgga
tattggcctcccgtgca-----cctcggcgtgcggccggcccaaatgcgatcccccggcg
actcgcgtcgcgacaagtggtggttg-aacat--ctcaat--ctcgcgtctcgtc--gtg
ccgccgagccgtccgcggtgatc------cgaaca-atgacccaacggag-ct-------
----------tgctccttcgacc
>Isodon_flexicaulis 676 bp 
tcgaaacctgcaaagcagaccgcgaacacgtt-tctaacgcca--t--------------
-------------------------cccccgccgcagcgcgcgcactcgtgc-cgcgcgg
cgtgcgggc-taacgaacccc-ggcgcggaaagcgccaaggaaaacttaaat--ttagcg
tcggtcccgccccgcatcccgttc-gcgggccgtgcggtgcggaacgggcg---------
---tctatcg---aatgtcataacgactctcggcaacggatatctcggctctcgcatcga
tgaagaacgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtgaaccatcgag
tctttgaacgcaagttgcgcccgaagccattaggccgagggcacgtctgcctgggcgtca
cgcatcgcgtcgct-ccc--cccc--accact---ctggcga-------gggggggcgga
tattggcctcccgtgcg-----cctcggcgtgcggccggcccaaatgcgatcccccggcg
actcgcgtcgcgacaagtggtggttg-aacat--ctcaat--ctcgcgtctcgtc--gtg
ccgccgagccgtccgtggtgatc------cgaacg-atgacccaacggag-ct-------
----------tgctccttcgacc
>Isodon_forrestii 676 bp 
tcgaaacctgcaaagcagaccgcgaacacgtt-tctaacgcca--t--------------
-------------------------cccccgccgcagcgcgcgcactcgtgc-cgcgc-g
cgtgcgggc-taacgaacccc-ggcgcggaacgcgccaaggaaaacttaaat--ttagcg
tcggtcccgccccgcatcccgttc-gcgggccgtgcggtgcggaacgggcg---------
---tctatcg---aatgtcataacgactctcggcaacggatatctcggctctcgcatcga
tgaagaacgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtgaaccatcgag
tctttgaacgcaagttgcgcccgaagccattaggccgagggcacgtctgcctgggcgtca
cgcatcgcgtcgct-ccc--cccc--accact---ctggcga-------gggggggcgga
tattggcctcccgtgcg-----cctcggcgtgcggccggcccaaatgcgatcccccggcg
actcgcgtcgcgacaagtggtggttg-aacat--ctcaat--ctcgcgtctcgtc--gtg
ccgccgagccgtccgcggtgatc------cgaacg-atgacccaacggag-ct-------
----------tgctccttcgacc
>Isodon_gesneroides 676 bp 
tcgaaacctgcaaagcagaccgcgaacacgtt-tctaacgcca--t--------------
-------------------------cccccgccgcagcgcgcgcactcgtgc-cgcgcgg
cgtgcgggc-taacgaacccc-ggcgcggaacgcgccaaggaaaacttaaat--ttagcg
tcggtctcgccccgcatcccgttc-gcgggccgtgcggtgcggaacgggcg---------
---tctatag---aatgtcataacgactctcggcaacggatatctcggctctcgcatcga
tgaagaacgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtgaaccatcgag
tctttgaacgcaagttgcgcccgaagccattaggccgagggcacgtctgcctgggcgtca
cgcatcgcgtcgctcccc--cccc--accact---ctggcga-------gggggggcgga
tattggcctcccgtgcg-----cctcggcgtgcggccggcccaaatgcgatcccccggcg
actcgcgtcgcgacaagtggtggttg-aacat--ctcaat--ctcgcgtctcgtc--gtg
ccgccgagccgtccgtggtgatc------cgaacg-atgacccaacggag-ct-------
----------tgctccttcgacc
>Isodon_glutinosus 676 bp 
tcgaaacctgcaaagcagaccgcgaacaagtt-tctaacgcca--t--------------
-------------------------cccccgccgcagcgcgcgcactcgtgc-cgcgc-g
cgtgcgggc-taacgaacccc-ggcgcggaacgcgccaaggaaaacttaaat--ttagcg
tcggtcccgccccgcatcccgttc-gcgggccgtgcggtgcggaacgggcg---------
---tctatcg---aatgtcataacgactctcggcaacggatatctcggctctcgcatcga
tgaagaacgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtgaaccatcgag
tctttgaacgcaagttgcgcccgaagccattaggccgagggcacgtctgcctgggcgtca
cgcatcgcgtcgct-ccc--cccc--accact---ctggcga------ggggggggcgga
tattggccccccgtgcg-----cctcggcgtgcggccggcccaaatgcgatcccccggcg
attcgcgtcgcgacaagtggtggttg-aacat--ctcaat--ctcgcgtctcgtc--gtg
ccgccgagccgtccgtggtgatc------cgaacg-atgacccaacggag-ct-------
----------tgctccttcgacc
>Isodon_grandifolius_var_atuntz 676 bp 
tcgaaacctgcaaagcagaccgcgaacacgtt-tctaacgcca--t--------------
-------------------------cccccgccgcagcgcgcgcactcgtgc-cgctctg
cgtgcgggc-taacgaacccc-ggcgcggaaagcgccaaggaaaacttaaat--ttagcg
tcggtcccgccccgcatcccgttc-gcgggccgtgcggtgcggaacgggcg---------
---tctatcg---aatgtcataacgactctcggcaacggatatctcggctctcgcatcga
tgaagaacgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtgaaccatcgag
tctttgaacgcaagttgcgcccgaagccattaggccgagggcacgtctgcctgggcgtca
cgcatcgcgtcgct-ccc--cccc--accact---ctggcga-------gggggggcgga
tattggcctcccgtgcg-----cctcggcgtgcggccggcccaaatgcgatcccccggcg
actcgcgtcgcgacaagtggtggttg-aacat--ctcaat--ctcgcgtctcgtc--gtg
ccgccgagccgtccgtggtgatc------cgaacg-atgacccaacggag-ct-------
----------tgctccttcgacc
>Isodon_hispidus_1 676 bp 
tcgaaacctgcaaagcagaccgcgaacacgtt-aacaacgccgacc--------------
-------------------------cccccgccgccgcgcccgcacccgtgc-ggcgcgg
cgtgcgggc-taacgaacccc-ggcgcggcacgcgccaaggaaaacttgaat--ttagcg
tcggtccccc-cagcatcccgttc-gcgggccgtgcgg-ggggaacgggcg---------
---tctatcg---aatgtcgtaacgactctcggcaacggatatctcggctctcgcatcga
tgaagaacgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtgaaccatcgag
tctttgaacgcaagttgcgcccgaagccattaggccgagggcacgtctgcctgggcgtca
cgcatcgcgtcgcccccc--tccccgcgcaagtcgctcgaga--------ggggggcgga
tactggctccccgtgcg-----ccacggcgcgcggccggcccaaatgcgatcccccggcg
tcccgcgtcgcgacaagtggtggttg-aacat--ctcaatccctcgcgtcctgtc--gtg
ccgctgggccgtccgcagggttc------cgaacg-atgacccaacggag-ctcat----
-------c--ggctccctcgacc
>Isodon_hispidus_2 676 bp 
tcgaaacctgcaaagcagaccgcgaacacgttaaacaacgccaa-c--------------
-------------------------cccccgccgccgcgcgcgcacttgtgc-gacgcgg
cgtgcgggc-taacgaacccc-ggcgcggcacgcgccaaggaaaactgaaat--ttagcg
tcggtccccctcagcatcccgttc-gcgggccgtgcgg-ggggaacgggcg---------
---tctatcg---aatgtcataacgactctcggcaacggatatctcggctctcgcatcga
tgaagaacgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtgaaccatcgag
tctttgaacgcaagttgcgcccgaagccattaggccgagggcacgtctgcctgggcgtca
cgcatcgcgtcgcccccc--tccccgcgcacggcgctcgcga--------ggggggcgga
tactggctccccgtgcg-----cctcggcgcgcggccggcccaaatgcgatcccccggcg
acccgcgtcgcgacaagtggtggttg-aacat--ctcaat--ctcgcgtcctgtc--gtg
ccgctgggtcgtccgcagggttc------cgaacg-atgacccaacggag-ctcat----
-------c--tgctccctcgacc
>Isodon_irroratus 676 bp 
tcgaaacctgcaaagcagaccgcgaacacgtt-tctaacgcca--t--------------
-------------------------cccccgccgcagcgcgcgcactcgtgc-cgcgctg
cgtgcgggc-taacgaacccc-ggcgcggaacgcgccaaggaaaacttaaat--ttagcg
tcggtcccgccccgcatcccgttc-gcgggccgtgcggtgcggaacgggcg---------
---tctatcg---aatgtcataacgactctcggcaacggatatctcggctctcgcatcga
tgaagaacgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtgaaccatcgag
tctttgaacgcaagttgcgcccgaagccattaggccgagggcacgtctgcctgggcgtca
cgcatcgcgtcgct-ccc--cccc--accact---ctggcga-------gggggggcgga
tattggcctcccgtgcg-----cctcggcgtgcggccggcccaaatgcgatcccccggcg
actcgcgtcgcgacaagtggtggttg-aacat--ctcaat--ctcgcgtctcgtc--gtg
ccgccgagccgtccgtggtgatc------cgaacg-atgacccaacggag-ct-------
----------tgctccttcgacc
>Isodon_japonicus 676 bp 
tcgaaacctgcaaagcagaccgcgaacacgtt-tctaacgcca--t--------------
-------------------------cccccgccgcagcgcgcgcactcgtgc-cgcgcgg
cgtgcgggc-taacgaacccc-ggcgcggaacgcgccaaggaaaacttaaat--ttagcg
tcggtcccgccccgcatcccgttc-gcgggccgtgcggtgcggaacgggcg---------
---tctatag---aatgtcataacgactctcggcaacggatatctcggctctcgcatcga
tgaagaacgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtgaaccatcgag
tctttgaacgcaagttgcgcccgaagccattaggccgagggcacgtctgcctgggcgtca
cgcatcgcgtcgct-ccc--cccc--accact---ctggcga-------gggggggcgga
tattggcctcccgtgcg-----cctcggcgtgcggccggcccaaatgcgatcccccggcg
actcgcgtcgcgacaagtggtggttg-aacat--ctcaat--ctcgcgtctcgtc--gtg
ccgccgagccgtctgtggtgatc------cgaacg-atgacccaacggag-ct-------
----------tgctccttcgacc
>Isodon_japonicus_var_glaucocal 676 bp 
tcgaaacctgcaaagcagaccgcgaacacgtt-tctaacgcca--t--------------
-------------------------cccccgccgcagcgcgcgcactcgtgc-cgcgcgg
cgtgcgggc-taacgaacccc-ggcgcggaacgcgccaaggaaaacttaaat--ttagcg
tcggtcccgccccgcatcccgttc-gcgggccgtgcggtgcggaacgggcg---------
---tctatag---aatgtcataacgactctcggcaacggatatctcggctctcgcatcga
tgaagaacgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtgaaccatcgag
tctttgaacgcaagttgcgcccgaagccattaggccgagggcacgtctgcctgggcgtca
cgcatcgcgtcgct-ccc--cccc--accact---ctggcga-------gggggggcgga
tattggcctcccgtgtg-----cctcggcgtgcggccggcccaaatgcgatcccccggcg
actcgcgtcgcgacaagtggtggttg-aacat--ctcaat--ctcgcgtctcgtc--gtg
ccgccgagccgtccgtggtgatc------cgaacg-atgacccaacggag-ct-------
----------tgctccttcgacc
>Isodon_leucophyllus 676 bp 
tcgaaacctgcaaagcagaccgcgaacacgtt-tctaacgcca--t--------------
-------------------------cccccgccgcagcgcgcgcactcgtgc-cgctctg
cgtgcgggc-taacgaacccc-ggcgcggaaagcgccaaggaaaacttaaat--ttagcg
tcggtcccgccccgcatcccgttc-gcgggccgtgcggtgcggaacgggcg---------
---tctatcg---aatgtcataacgactctcggcaacggatatctcggctctcgcatcga
tgaagaacgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtgaaccatcgag
tctttgaacgcaagttgcgcccgaagccattaggccgagggcacgtctgcctgggcgtca
cgcatcgcgtcgct-ccc--cccc--accact---ctggcga-------gggggggcgga
tattggcctcccgtgcg-----cctcggcgtgcggccggcccaaatgcgatcccccggcg
actcgcgtcgcgacaagtggtggttg-aacat--ctcaat--ctcgcgtctcgtc--gtg
ccgccgagccgtccgtggtgatc------cgaacg-atgacccaacggag-ct-------
----------tgctccttcgacc
>Isodon_lophanthoides 676 bp 
tcgaaacctgcaaagcagaccgcgaacacgtt-aacaacgccga-c--------------
-------------------------cccccgccgccgcgcccgcacccgtgc-ggcgcag
cgtgcgggc-taacgaacccc-ggcgcggcacgcgccaaggaaaacttgaat--ttagcg
tcggtccccc-cagcatcccgttc-gcggggcgtgcgg-ggggaacgggcg---------
---tctatcg---aatgtcgtaacgactctcggcaacggatatctcggctctcgcatcga
tgaagaacgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtgaaccatcgag
tctttgaacgcaagttgcgcccgaagccattaggccgagggcacgtctgcctgggcgtca
cgcatcgcgtcgcccccc--tccccgcgcacggcgctggcga--------ggggggcgga
tactggctccccgtgcg-----ccacggcgcgcggccggcccaaatgcgatcccccggcg
tcccgcgtcgcgacgagtggtggttg-aacat--ctcaatctctcgcgtcctgtc--gtg
ccgctgggccgtccgcagggtgttccgaacgaacg-atgacccaacggag-ctcat----
-------c--cgctccctcgacc
>Isodon_lophanthoides_var_gerar 676 bp 
tcgaaacctgcaaagcagaccgcgaacacgtt-aacaacgccgacc--------------
-------------------------cccccgccgccgcgcccgcacccgtgc-ggcgcgg
cgtgcgggc-taacgaacccc-ggcgcggcacgcgccaaggaaaacttgaat--ttagcg
tcggtccccc-cagcatcccgttc-gcgggccgtgcgg-ggggaacgggcg---------
---tctatcg---aatgtcgtaacgactctcggcaacggatatctcggctctcgcatcga
tgaagaacgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtgaaccatcgag
tctttgaacgcaagttgcgcccgaagccattaggccgagggcacgtctgcctgggcgtca
cgcatcgcgtcgcccccc--tccccgcgcacggcgctggaga--------ggggggcgga
tactggctccccgtgcg-----ccacggcgcgcggccggcccaaatgcgatcccccggcg
tcccgcgtcgcgacgagtggtggttg-aacat--ctcaatctctcgcgtcctgtc--gtg
ccgctgggccgtccgcagggttc------cgaacg-atgacccaacggag-ctcat----
-------c--cgctccctcgacc
>Isodon_lophanthoides_var_micra 676 bp 
tcgaaacctgcaaagcagaccgcgaacacgtt-aacaacgccga-c--------------
-------------------------cccccgccgccgcgcccgcacccgtgc-ggcgcgg
cgtgcgggc-taacgaacccc-ggcgcggcacgcgccaaggaaaactt-aat--ttagcg
tcggtccccc-cagcatcccgttc-gcgggccgtgcgg-ggggaacgggcg---------
---tctatcg---aatgtcgtaacgactctcggcaacggatatctcggctctcgcatcga
tgaagaacgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtgaaccatcgag
tctttgaacgcaagttgcgcccgaagccattaggccgagggcacgtctgcctgggcgtca
cgcatcgcgtcgcccccc--tccccgcgcacggcgctggcga--------ggggggcgga
tactggctccccgtgcg-----ccacggcgcgcggccggcccaaatgcgatcccccggcg
tcccgcgtcgcgacaagtggtggttg-aacat--ctcaatctctcgcgtcctgtc--gtg
ccgctgggccgtccgcagggttc------cgaacg-atgacccaacggag-ctcat----
-------c--ggctccctcgacc
>Isodon_loxothyrsus 676 bp 
tcgaaacctgcaaagcagaccgcgaactcgtt-tctaacgcca--t--------------
-------------------------cccccgccgcagcgcgcgcactcgtgc-cgcgcgg
cgtgcgggc-taacgaacccc-ggcgcggaacgcgccaaggaaaacttaaat--ttagcg
tcggtcccgccccgcatcccgttc-gcgggccgtgcggtgcggaac-ggcg---------
---tctatcg---aatgtcataacgactctcggcaacggatatctcggctctcgcatcga
tgaagaacgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtgaaccatcgag
tctttgaacgcaagttgcgcccgaagccattaggccgagggcacgtctgcctgggcgtca
cgcatcgcgtcgct-ccc--cccc--accact---ctggcga-------gggggggcgga
tattggcctcccgtgcg-----cctcggcgtgcggccggcccaaatgcgatcccccggcg
actcgcgtcgcgacaagtggtggttg-aacat--ctcaat--ctcgcgtctcgtc--gtg
ccgccgagccgtccgtggtgatc------cgaacg-atgacccaacggag-ct-------
----------tgctccttcgacc
>Isodon_lungshengensis 676 bp 
tcgaaacctgcaaagcagaccgcgaacacgtt-tctaacgcca--t--------------
-------------------------cccccgccgcagcgcgcgcactcgtgc-cgcgctg
cgtgcgggc-taacgaacccc-ggcgcggaacgcgccaaggaaaacttaaat--ttagcg
tcggtcccgccccgcatcccgttc-gcgggccgtgcggtgcggaacgggcg---------
---tctatcg---aatgtcgtaacgactctcggcaacggatatctcggctctcgcatcga
tgaagaacgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtgaaccatcgag
tctttgaacgcaagttgcgcccgaagccattaggccgagggcacgtctgcctgggcgtca
cgcatcgcgtcgct-ccc--cccc--accact---ctggcga-------gggggggcgga
tattggcctcccgtgcg-----cctcggcgtgcggccggcccaaatgcgatcccccggcg
actcgcgtcgcgacaagtggtggttg-aacat--ctcaat--ctcgcgtctcgtc--gtg
ccgccgagccttccgcggtgatc------cgaacg-atgacccaacggag-ct-------
----------tgctccttcgacc
>Isodon_megathyrsus_1 676 bp 
tcgaaacctgcaaagcagaccgcgaacacttt-tctaacgcca--t--------------
-------------------------cccccgccgcagcgcgcgcactcgtgc-cgcgcgg
cgtgcgggc-taacgaacccc-ggcgcggaacgcgccaaggaaaacttaaat--ttagca
tcggtcccgccccgcatcccgttc-gcgggccgtgcggtgcggaacgggcg---------
---tctatcg---aatgtcataacgactctcggcaacggatatctcggctctcgcatcga
tgaagaacgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtgaaccatcgag
tctttgaacgcaagttgcgcccgaagccattaggccgagggcacgtctgcctgggcgtca
cgcatcgcgtcgct-ccc--ccca--cccacg---ttggcga--------ggggggcgga
tattggcctcccgtgcg-----cctcggcgtgcggccggcccaaatgcgatcccccggcg
actcgtgtcgcgacaagtggtggttg-aacat--ctcaat--ctcgcgtctcgtc--gtg
ccgccgagccgtccgtggtgatc------caaacg-atgacccaacggag-ct-------
----------tgctccttcgacc
>Isodon_megathyrsus_2 676 bp 
tcgaaacctgcaaagcagaccgcgaacacgtt-tctaacgcca--t--------------
-------------------------cccccgccgcagcgcgcgcactcgtgc-cgcgcgg
cgtgcgggc-taacgaacccc-ggcgcggaacgcgccaaggaaaacttaaat--ttagca
tcggtcccgccccgcatcccgttc-gcgggccgtgcggtgcggaacgggcg---------
---tctatcg---aatgtcataacgactctcggcaacggatatctcggctctcgcatcga
tgaagaacgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtgaaccatcgag
tctttgaacgcaagttgcgcccgaagccattaggccgagggcacgtctgcctgggcgtca
cgcatcgcgtcgct-ccc--ccca--cccacg---ttggcga--------ggggggcgga
tattggcctcccgtgcg-----cctcggcgtgcggccggcccaaatgcgatcccccggcg
actcgtgtcgcgacaagtggtggttg-aacat--ctcaat--ctcgcgtctcgtc--gtg
ccgccgagccgtccgtggtgatc------caaacg-atgacccaacggag-ct-------
----------tgctccttcgacc
>Isodon_melissoides 676 bp 
tcgaattctgcaaagcagaccgcgaactcgtt-tctaacgcca--a--------------
-------------------------cccccgccgcagcgcgcgcactcgtgc-cgcgc-g
cgtgcgggc-taacgaacccc-ggcgcggaacgcgccaaggaaaacttaaat--ttagcg
tcggtcccgccccgcatcccgttc-gcgggccgtgcggtgcggaacgggcg---------
---tctatcg---aatgtcataacgactctcggcaacggatatctcggctctcgcatcga
tgaagaacgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtgaaccatcgag
tctttgaacgcaagttgcgcccgaagccattaggccgagggcacgtctgcctgggcgtca
cgcatcgcgtcgct-ccc--cccc--accact---ctggcga-------gggggggcgga
tattggcctcccgtgcg-----cctcggcgtgcggccggcccaaatgcgatcccccggcg
actcgcgtcgcgacaagtggtggttg-aacat--ctcaat--ctcgcgtctcgtc--gtg
ccgccgagccgtccgtggtgatc------cgaacg-atgacccaacggag-ct-------
----------tgctccttcgacc
>Isodon_nervosus 676 bp 
tcgaaacctgcaaagcagaccgcgaacacgtt-tctaacgcca--t--------------
-------------------------cccccgccgcagcgcgcgcactcgtgc-cgcgcgg
cgtgcgggc-taacgaacccc-ggcgcggaacgcgccaaggaaaacttaaat--ttagcg
tcggtcccgccccgcatcccgttc-gcgggccgtgcggtgcggaacgggcg---------
---tctatcg---aatgtcataacgactctcggcaacggatatctcggctctcgcatcga
tgaagaacgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtgaaccatcgag
tctttgaacgcaagttgcgcccgaagccattaggccgagggcacgtctgcctgggcgtca
cgcatcgcgtcgct-ccc--cccc--accact---ctggcga-------gggggggcgga
tattggcctcccgtgcg-----cctcggcgtgcggccggcccaaatgcgatcccccggcg
actcgcgtcgcgacaagtggtggttg-aacat--ctcaat--ctcgcgtctcgtc--gtg
ccgccgagccgtccgtggtgatc------cgaacg-atgacccaacggagcct-------
----------tgctccttcgacc
>Isodon_phyllopodus 676 bp 
tcgaaacctgcaaagcagaccgcgaacacgtt-aacaacgccaa-c--------------
-------------------------cccccgccgccgcgcgcgcactcgtgc-gacgcgg
cgtgcgggc-taacgaacccc-ggcgcggcacgcgccaaggaaaactgaaat--ttagcg
tcggtccccctcagcatcccgttc-gcgggccgtgcgg-ggggaacgggcg---------
---tctatcg---aatgtcataacgactctcggcaacggatatctcggctctcgcatcga
tgaagaacgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtgaaccatcgag
tctttgaacgcaagttgcgcccgaagccattaggccgagggcacgtctgcctgggcgtca
cgcatcgcgtcgcccccc--tccccgcgcacggcgctcgtga--------ggggggcgga
tactggctccccgtgcg-----cctcggcgcgcggccggcccaaatgcgatcccccggcg
acccgcgtcgcgacaagtggtggttg-aacat--ctcaat--ctcgcgtcctgtc--gtg
ccgctgggtcgtccgcagggttc------cgaacg-atgacccaacggag-ctcat----
-------c--tgctccctcgacc
>Isodon_phyllostachys 676 bp 
tcgaaacctgtaaagcagaccgcgaacacgtt-tctaacgcca--t--------------
-------------------------cccccgccgcagcgcgcgcactcgtgc-cgcgcgg
cgtgtgggc-taacgaacccc-ggcgcggaatgcgccaaggaaaacttaaat--ttagcg
tcggtcctgccccgcatcccgttc-gcgggccgtgcggtgcggaacgggcg---------
---tctatcg---aatgtca-aacgactctcggcaacggatatctcggctctcgcatcga
tgaagaacgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtgaaccatcgag
tctttgaacgcaagttgcgcccgaagccattaggccgagggcacgtctgcctgggcgtca
cgcatcgcgtcgct-ccc--cccc--accact---ctggcga-------gggggtgcgga
tattggcctcccgtgcg-----cctcggcgtgcggccggcccaaatgcgatcccccggcg
actcgcgtcgcgacaagtggtggttg-aacat--ctcaat--ctcgcgtctcgtc--gtg
ccgccgagccgtccgcggtgatc------cgaacg-atgacccaacggag-ct-------
----------tgctccttcgacc
>Isodon_pleiophyllus 676 bp 
tcgaaacctgcaaagtagaccgcgaacatgtt-tctaatgcca--t--------------
-------------------------cccc-gccgcagcgcg-gctctcgtgc-cgcgcgg
cgtgcgggc-taacgaacccc-ggcgcggaacgcgccaaggaaaacttaaat--ttagcg
tcggtcccgccccgcatcccgttc-gcgggccgtgcggtgtggaa-gggcg---------
---tctatcg---aatgtcataacgactctcggcaacggatatctcggctctcgcatcga
tgaagaacgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtgaaccatcgag
tctttgaacgcaagttgcgcccgaagccattaggccgagggcacgtctgcctgggcgtca
cgcatcgcgtcgctcccc--cccc--accacg---ctggcga--------ggggggcgga
tattggcctcccgtgcg-----cctcggcgtgcggctggcccaaatgcgatcccccggcg
actcgcgtcgcgacaagtggtggttg-aacat--ctcaat--ctcgcgtctcgtc--gtg
c--gcgagccgtccgtggtgatc------g-aacg-atgacccaacggag-ct-------
----------tgctccttcgacc
>Isodon_rosthornii 676 bp 
tcgaaacctgcaaagcagaccgcgaacacgtt-tctaacgcca--t--------------
-------------------------cccccgccgcagcgcgcgcactcgtgc-cgcgcgg
cgtgcgggc-taacgaacccc-ggcgcggaacgcgccaaggaaaacttaaat--ttagcg
tcggtcccgccccgcatcccgttc-gcgggccgtgcggtgtggaacgggcg---------
---tctatag---aatgtcataacgactctcggcaacggatatctcggctctcgcatcga
tgaagaacgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtgaaccatcgag
tctttgaacgcaagttgcgcccgaagccattaggccgagggcacgtctgcctgggcgtca
cgcatcgcgtcgctcccc--ccca--ccaact---ctggcga--------ggggggcgga
-attggccccccgtgcg-----cctcggcgtgcggccggcccaaatgcgatcccccggcg
actcgcgtcgcgacaagtggtggttg-aacat--ctcaat--ctcgcgtctcgtc--gtg
ctgccgagccgtccgtggtgatc------cgaacg-atgacccaacggag-ct-------
----------tgctccttcgacc
>Isodon_rugosiformis 676 bp 
tcgaaacctgcaaagcagaccgcgaactcgtt-tctaacgcca--t--------------
-------------------------cccccgccgcagcgcgcgcactcgtgc-cgcgcgg
cgtgcgggc-taacgaacccc-ggcgcggaacgcgccaaggaaaacttaaat--ttagcg
tcggtcccgccccgcatcccgttc-gcgggccgtgcggtgcggaactggcg---------
---tctatcg---aatgtcataacgactctcggcaacggatatctcggctctcgcatcga
tgaagaacgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtgaaccatcgag
tctttgaacgcaagttgcgcccgaagccattaggccgagggcacgtctgcctgggcgtca
cgcatcgcgtcgct-ccc--cccc--accact---ctggaga-------gggggggcgga
tattggcctcccgtgcg-----cctcggcgtgcggccggcccaaatgcgatcccccggcg
actcgcgtcgcgacaagtggtggttg-aacat--ctcaat--ctcgcgtctcgtc--gtg
ccgccgagccgtccgtggtgatc------caaacg-atgacccaacggag-ct-------
----------tgctccttcgacc
>Isodon_scoparius 676 bp 
tcgaaacctgcaaagcagaccgcgaacacgtt-tctaacgcca--t--------------
-------------------------cccccgccgcagcgcgcgcactagtgc-cgcgcgg
cgtgcgggc-taacgaacccc-ggcgcggaacgcgccaaggaaaacttaaat--ttagcg
tcggtctcgccccgcatcccgttc-gcgggccgtgcggtgcggaacgggcg---------
---tctatcg---aatgtcataacgactctcggcaacggatatctcggctctcgcatcga
tgaagaacgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtgaaccatcgag
tctttgaacgcaagttgcgcccgaagccattaggccgagggcacgtctgcctgggcgtca
cgcatcgcgtcgct-ccc--cccc--accact---ctggcga-------ggaggggcgga
tattggcctcccgtgcg-----cctcggcgtgcggccggcccaaatgcgatcccccggcg
actcgcgtcgcgacaagtggtggttg-aacat--ctcaat--ctcgcgtctcgtc--gtg
ccgccgagccgtccgcggtgatc------cgaacg-atgacccaacggag-ct-------
----------tgctccttcgacc
>Isodon_sculponeatus 676 bp 
tcgaaacctgcaaagcagaccgcgaacacgtt-tttaacgcca--t--------------
-------------------------cccccgccacagcgcgcgcactcgtgc-cgcgctg
cgtgcgggc-taacgaacccc-ggcgcggaacgcgccaaggaaaacttaaat--ttagcg
tcggtcccgccccgcatcccgttc-gcgggccgtgcggtgcggaacgggcg---------
---tctatcg---aatgtcataacgactctcggcaacggatatctcggctctcgcatcga
tgaagaacgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtgaaccatcgag
tctttgaacgcaagttgcgcccgaagccattaggccgagggcacgtctgcctgggcgtca
cgcatcgcgtcgct-ccc--cccc--agcaca---ctggcga--------ggggggcgga
tattggcctcccgtgct-----cctcggcgtgcggccggcccaaatgcgatcccccggcg
actcgcgtcgcgacaagtggtggttg-aacat--ctcaat--ctcgcgtctcgtc--gtg
ctgccgagccgtccgtggtgatc------cgaacg-atgacccaacggag-ct-------
----------tgctccttcgacc
>Isodon_taliensis 676 bp 
tcgaaacctgcaaagcagaccgcgaacacgtt-tctaacgcca--t--------------
-------------------------cccccgccgcagcgcgtgcactcgtgc-cgcgcgg
cgtgcgggc-taacgaacccc-ggcgcggaacgcgccaaggaaaacttaaat--ttagcg
tcggtcccgccccgcatcccgttc-gcgggccgtgcggtgcggaacggacg---------
---tctatcg---aatgtcataacgactctcggcaacggatatctcggctctcgcatcga
tgaagaacgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtgaaccatcgag
tctttgaacgcaagttgcgcccgaagccattaggccgagggcacgtctgcctgggcgtca
cgcatcgcgtcgct--cc--cccc--accact---ctggcga------ggggggggcgga
tattggcctcccgtgcg-----cctcggcgtgcggccggcccaaatgcgatcccccggcg
actcgcgtcgcgacaagtggtggttg-aacat--ctcaat--ctcgcgtctcgtc--gtg
c-gccgagccgtccgtggtgatc------cgaacg-atgacccaacggagctt-------
----------tgctccttcgacc
>Isodon_ternifolius 676 bp 
tcgaaacctgcacagcagaccgcgaacacgtt-tctaaagcca--a--------------
-------------------------cccccgccgccgcgcgcgcactcgtgc-gccgcga
tgtgcgggc-taacgaacccc-ggcgcggcacgcgccaaggaaaactaaaat--ttagcg
ccggtcc--ccccgcaacccgttc-gcgggccgtgcggggcagcacgagcg---------
---tctattg---aatgtcataacgactctcggcaacggatatctcggctctcgcatcga
tgaagaacgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtgaaccatcgag
tctttgaacgcaagttgcgcccgaagccattaggccgagggcacgtctgcctgggcgtca
cgcatcgcgtcgcccccc--caccgcgcttcggcacggccga---------gggggtgga
tattggccccccgtgcg-----cctcggcgtgcggtcggcccaaatacgatcccctgtcg
actcgcgtcgcgacaagtggtggttg-aacat--ctcaat--ctcgcatctcgtc--gtg
gcaccgagccttccgcggtgatc------cgatag-atgacccaacggag-ctgct----
---tatgc--cgctccttcgacc
>Isodon_wikstroemioides 676 bp 
tcgaaacctgcaaagcagaccgcgaacacgtt-tctaacgcca--t--------------
-------------------------cccccgccgcagcgcgcgcactcgtgc-cgctctg
cgtgcgggc-taacgaacccc-ggcgcggaacgcgccaaggaaaacttaaat--ttagcg
tcggtcccgccccgcatcccgttc-gcgggccgtgcggtgcggaacaggcg---------
---tctatcg---aatgtcataacgactctcggcaacggatatctcggctctcgcatcga
tgaagaacgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtgaaccatcgag
tctttgaacgcaagttgcgcccgaagccattaggccgagggcacgtctgcctgggcgtca
cgcatcgcgtcgct-ccc--cccc--accact---ctggcga-------gggggggcgga
tattggcctcccgtgcg-----cctcggcgtgcggccggcccaaatgcgatcccccggcg
actcgcgtcgcgacaagtggtggttg-aacat--ctcaat--ctcgcgtctcgtc--gtg
ccgccgagtcgtccgcggtgatc------cgaacg-atgacccaacggag-ct-------
----------tgctccttcgacc
>Isodon_xerophilus 676 bp 
tcgaaacctgcaaagcagaccgcgaacacgtt-tctaacgcca--t--------------
-------------------------cccccgccgcagcgcgcgcactcgtgc-cgcgcgg
cgtgcgggc-taacgaacccc-ggcgcggaacgcgccaaggaaaacttaaat--ttagcg
tcggtcccgccccgcatcccgttc-gcgggccgtgcggtgcggaacgggcg---------
---tctatcg---aatgtcataacgactctcggcaacggatatctcggctctcgcatcga
tgaagaacgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtgaaccatcgag
tctttgaacgcaagttgcgcccgaagccattaggccgagggcacgtctgcctgggcgtca
cgcatcgcgtcgct-ccc--ccca--cccacg---ttggcga--------ggggggcgga
tattggcctcccgtgcg-----cctcggcgtgcggccggcccaaatgcgatcccccggcg
actcgtgtcgcgacaagtggtggttg-aacat--ctcaat--ctcgcgtctcgtc--gtg
ccgccgagccgtccgtggtgatc------cgaacg-atgacccaacggag-ct-------
----------tgctccttcgacc
>Isodon_yuennanensis 676 bp 
tcgaaacctgcaaagcagaccgcgaacacgttaaacaacgccaa-t--------------
-------------------------cccccgccgccgcccgtgcacttgtgcggacgcgg
cgtgcgggc-taacgaacccc-ggcgcggcacgcgccaaggaaaactgaaat--ttagcg
tcggtccccctcagcatcccgttc-gcgggtcgtgcgg-ggggaacgggcg---------
---tctatcg---aatgtcataacgactctcggcaacggatatctcggctctcgcatcga
tgaagaacgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtgaaccatcgag
tctttgaacgcaagttgcgcccgaagccattaggccgagggcacgtctgcctgggcgtca
cgcatcgcgtcgcccccc--tccccgcgcacggcgctcgcga--------ggggggcgga
tactggctccccgtgcg-----cctcggcgcgcggccggcccaaatgcgatcccccggcg
acccgcgtcgcgacaagtggtggttg-aacat--ctcaat--ctcgcgtcctgtc--gtg
ccgctgggtcgtccgtagggttc------cgaacg-atgacccaa-ggag-ctcat----
-------c--tgctccctcgacc
>Lavandula_angustifolia_1 676 bp 
-tcgaacctgcaaggcagaccgcgaacacgtg-tttaactccg----cgggaccgttgtg
cggcgcgagccccacgccgatcccgctcccgtcgttgcacgcgcacccgtgc-gccgcag
cgttcgggcttaactcacccc-ggcgcggaatgcgccaaggaaaac-aaaat--gaagcg
tcggcc---ctccgcatcccgttc-gcggggcgtgcgg-gggcagcgggcg---------
---tctatcg---aatgtcataacgactctcggcaacggatatctcggctctcgcatcga
tgaagaacgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtgaaccatcgag
tctttgaacgcaagttgcgcccgaggccattcggctgagggcacgtctgcctgggcgtca
cgcatcgcgtcgccccctc-cacccgcgcactgcgctcgtag--------agggggcgga
tattggccccccgtgtg-----ctccggcacgcggtcggcccaaatgcgatcccccggcg
actcatgtcgcggccagtggtggttg-aacat--atcaat--ctcgtgtcttgcc--gcg
tcgttgagccg-tcggacgggatct----cgt-ta-acgacccaacggtg-tgagcgcac
cccgtgcgcgcgcgccctcgacc
>Lavandula_angustifolia_2 676 bp 
tcgaaacctgcaaggcagaccgcgaacacgtg-tttaactccg----cgggaccgttgtg
cggcgcgagccccacgccgatcccgctcccgtcgttgcacgcgcacccgtgc-gccgcag
cgttcgggcttaactcacccc-ggcgcggaatgcgccaaggaaaac-aaaat--gaagcg
tcggcc---ctccgcatcccgttc-gcggggc-tgcgg-gggcagcgggcg---------
---tctatcg---aatgtcataacgactctcggcaacggatatctcggctctcgcatcga
tgaagaacgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtgaaccatcgag
tctttgaacgcaagttgcgcccgaggccattcggctgagggcacgtctgcctgggcgtca
cgcatcgcgtcgccccctc-cacccgcgcactgcgctcgtag--------agggggcgga
tattggccccccgtgtg-----ctccggcacgcggtcggcccaaatgcgatcccccggcg
actcatgtcgcggccagtggtggttg-aacat--atcaat--ctcgtgtcttgcc--gcg
tcgttgagccg-tcggacgtgatct----cgt-ta-acgacccaacggtg-tgagcgcac
cccgtgcgcgcgcgccctcgacc
>Lavandula_sp 676 bp 
tcgaaacctgcaaggcagaccgcgaacacgtg-tttaact--------------------
----------------------ccgttcccgccggtgtgcgcgcactcgtgc-gccgcat
cgtgcgggc-taactcacccc-ggcgcggaaagcgccaaggaatac-aaact--gaagcg
tcggcc---ctccgcatcccgttc-gcgggctgtgcgg-gggtagcgggcg---------
---tctatcg---aatgtcataacgactctcggcaacggatatctcggctctcgcatcga
tgaagaacgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtgaaccatcgag
tctttgaacgcaagttgcgcccgatgccatccggttgagggcacgtctgcctgggcgtca
cgcatcgcgtcgccccctc-cccgcgctcattgtgcaggtgg--------atggggcgga
taatggccccccgtgcg-----ccccggcgtgcggtcggcccaaatacgatcccccggcg
actcatgtcgcggccagtggtggttg-aacat--ctcaat--ctctctattcgtc--gtg
gcgttgagccgttcggatgcgatca----cgtatt-ctgacccaacggtg-tgggtgcac
tacatgcgctcgcactttcgacc
>Mentha_arvensis 676 bp 
tcgaaacctgcaaagcagaccgcgaactcgta-actaacgccgcggggcac--ggcacgg
gggagaccccc-tgccgcatcccgtctcctgccggcttgctccctcgggggc----acgc
cgtgcgggc-taacgaacccc-ggcgcggaacgcgccaaggaaaac-caaac--gaagcg
tccgcc---cccggcatcccgttc-gcggggcgtgccg-tgggatcgggcg---------
---tctatca---aatgtcaaaacgactctcggcaacggatatctcggctctcgcatcga
tgaagaacgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtgaaccatcgag
tctttgaacgcaagttgcgcccgaagccattaggccgagggcacgtctgcctgggcgtca
cgcatcgcgtcgcccccca-cccccgcgcgcatcgccgggca------gttgggggcgga
cactggcctcccgtgcg-----cctcggcgtgcggccggcccaaatgagatccccgggcg
actggcgtcgcgacaagtggtggttg-aacat--ctcaat--ctctctcgtggtc--gtg
ccgccgtgtcgtcccgtacgggaa-----tcgaaa-acgacccaacggtg---ctaggcg
cgaacagcgtctcaccttcgacc
>Mentha_sp 676 bp 
tcgaaacctgcaaagcagaccgcgaactcgta-actaacgccgcggggcac--ggcacgg
gggagaccccc-tgccgcatcccgtctcctgccggcttgctccctcgggggc----acgc
cgtgcgggc-taacgaacccc-ggcgcggaacgcgccaaggaaaac-caaac--gaagcg
tccgcc---cccggcatcccgttc-gcggggcgtgccg-tgggatcgggcg---------
---tctatca---aatgtcaaaacgactctcggcaacggatatctcggctctcgcatcga
tgaagaacgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtgaaccatcgag
tctttgaacgcaagttgcgcccgaagccattaggccgagggcacgtctgcctgggcgtca
cgcatcgcgtcgcccccca-cccccgcgcgcatcgccgggcg------gttgggggcgga
cactggcctcccgtgcg-----cctcggcgtgcggccggcccaaatgagatccccgggcg
actggcgtcgcgacaagtggtggttg-aacat--ctcaat--ctctctcgtggtc--gtg
ccgccgtgtcgtcccgtacgggaa-----tcgaaa-acgacccaacggtg---ctaggcg
cgaacagcgtctcaccttcgacc
>Ocimum_basilicum 676 bp 
tcgagacctgcaaagcagaccgcgaacacgtg-tttaactcat-----------------
-----------------------gaatcccgccgccggccccgg------------tcgg
cgcgcgggc-taacgaacccc-ggcgcggaacgcgccaaggaaaactcaaaacgtcggcg
ccggcc---ccccccaccccgtcc-gcgggtcgtgcgg-ggggcgcgggcg---------
---tccatcgacgaatgtcaaaacgactctcggcaacggatatctcggctctcgcatcga
tgaagaacgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtgaaccatcgag
tctttgaacgcaagttgcgcccgaagccatcaggccgagggcacgtctgcctgggcgtca
cgcatcgcgtcgcccccccatccccgcgcaatgcgctcggct------tgggggggcgga
tactggcctcccgtgcg-----ccccgccgcgcggccggcccaaatg-gatcccccggcg
acccgcgtcgcgacaagtggtggttg-aactc--atcaatt-tccccgtcgcgcc-----
---ccgggtcgtccgcgcggatcccttagtaaaa--agaacccaa---------------
---------------cctcgacc
>Ocimum_gratissimum_var_suave 676 bp 
tcgaaacctgcaaagcagaccgcgaacacgtg-tttaactcat-----------------
-------------------------cccccgccgccga------------------tcgg
cgtgcgggc-taacgaaccccgggcgcggaaagcgccaaggaaaac-tgtac--gtagcg
tcggtcc--cc-c-catcccgttc-gcgggtcgtgcgg-gggatgcggacg---------
---tctatcg---aat-tcaaaacgactctcggcaacggatatctcggctctcgcatcga
tgaagaacgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtgaaccatcgag
tctttgaacgcaagttgcgcccgaagccattaggccgagggcacgtctgcctgggcgtca
cgcatcgcgtcgcccccccttccccgcgcaccgcgctcggga------cggggggacgga
tattggcctcccgtgcg-----ccccggtgcgcggccggcccaaatgcgatcccccggcg
acccgcgtcgcgacaagtggtggttgaaacat--ctcaat--ctcgcgtctcgtc--gcg
cttccgggtcgtccgagcgggctc-----caaa-a-ataacccaatggtg---cggccgt
t---acgc--cgcgccctcgacc
>Orthosiphon_aristatus_1 676 bp 
tcgaaacctgcaaagcagaccgcgaacacgtt-tctaactcac--t--------------
-------------------------ctcccgccggcgcgggcgcacccgtgc-cttgcgt
cgtgcgggc-taacgaacccc-ggcgcggaatgcgccaaggaaaac-cgaac--gtagcg
tcggccc--cc-ctcgccccgttc-gcgggtcgtgcgg-ggggcgcggacg---------
---tctatcg---aatgtcaaaacgactctcggcaacggatatctcggctctcgcatcga
tgaagaacgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtgaaccatcgag
tctttgaacgcaagttgcgcccgaagccattaggccgagggcacgtctgcctgggcgtca
cgcatcgcgtcg-cccccc-tccccgcgctctgcgctcggga------c-gggggacgga
tattggcctcccgtgcg-----ccccgtcgtgcggccggcccaaatgcgatcccccggcg
actcgcgtcgcgacaagtggtggttg-aacat--ctcaat--ctcgcgtctcgtc--gcg
ccgccgaatcgtccgtacgggcat-----cgaa-a-ttgacccaaaggcg---tggc-cc
cc--gagc--cacgctctcgacc
>Orthosiphon_aristatus_2 676 bp 
tcgaaacctgcaaagcagaccgcgaacacgtt-tctaactcac-----------------
-------------------------ctcccgccggcgcgggcgcacccgtgc-ct-gcgt
cgtgcgggc-taacgaacccc-ggcgcggaatgcgccaaggaaaac-cgaac---tagcg
tcggccc--cc-cttgccccgttc-gcgggtcgtgcgg-ggggcgcggacg---------
---tctatcg---aatgtcaaaacgactctcggcaacggatatctcggctctcgcatcga
tgaagaacgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtgaaccatcgag
tctttgaacgcaagttgcgcccgaagccattaggccgagggcacgtctgcctgggcgtca
cgcatcgcgtcg-cccccc-t-cccgcgc-ctgcgctcggga------c-gggggacgga
tattggcctcccgtg-g-----ccccgtcgtgcggccggcccaaatgcgatcccccggcg
actcgcgtcgcgacaagtggtggttg-aacat--ctcaat--ctcgcgtctcgtc--gcg
ccgccgaatcgtccgt-cgggcat-----cgaa-a-tcgacccaaaggcg---tggc-cc
cc--gagc--c-cgctctcgacc
>Orthosiphon_wulfenioides 676 bp 
tcgaaacctgcaaagcagaccgcgaacacgtt-tctaactcac--t--------------
-------------------------ctcccgccggcgcgcgcgctcgcgtgc-gtcgcgt
cgtgcgggc-taacgaacccc-ggcgcggaatgcgccaaggaaaac-tgaaa--gtagcg
ccggccc--cc-ctctccccgttc-gcgggtcgtgcgg-ggggcgcgggcg---------
---tctatcg---aatgtcaaaacgactctcggcaacggatatctcggctctcgcatcga
tgaagaacgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtgaaccatcgag
tctttgaacgcaagttgcgcccgaagccattaggccgagggcacgtctgcctgggcgtca
cgcatcgcgtcg-cccccc-tccccgcgctccgcgctcgggg------t-ggggggcgga
tattggcctcccgtgcg-----ccccgtcgtgcggccggcccaaatgcgatcccccggcg
actcgcgtcgcgacaagtggtggttg-aacat--ctcaat--ctcgcgtctcgtc--gcg
ccgccgaatcgtccggacgggcat-----cgaaca-gtgacccaacggcg---tgg--cc
tt--gagc--cgcgctctcgacc
>Perilla_frutescens 676 bp 
tcgaaacctgcaaagcagaccgcgaacacgtg-tttaacatca--tcggacacggcgtgg
gggagactccc---gtcgtgcaccgctcccgccg--gagtgcgccctcgggc-gtcgcac
cgtgcgggc-taacgaacccc-ggcgcggcaagcgccaaggaaaac-aaaat--ttagcg
cccgcc---ttccgcatcccgttc-gcggggtgtgcgggg-ggaatggacg---------
---tctatcg---aatgtcataacgactctcggcaacggatatctcggctctcgcatcga
tgaagaacgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtgaaccatcgag
tctttgaacgcaagttgcgcccgaagccattaggccgagggcacgtctgcctgggcgtca
cgcatcgcgtcgcccccc--tccccgcgctgagcgctcgtga--------ggggggcgga
tattggccccccgtgcg-----ccctggcgtgcggtcggcccaaatgcgatccctcgacg
actcgtgtcgcgactagtggtggttg-aatag--ctcaat--ctcgtgtcttgtc--gtg
ctaccgcgtcgtccgaatgggaat-----cgaaca-acgacccaacggtg-ttcgtgcgt
taccgcac--cgcaccttcgacc
>Plectranthus_strigosus 676 bp 
------------------------------------------------------------
---------------------------------------------------------cgc
cgcgcgggc-taacgaacccc-ggcgcggaaagcgccaaggaaaactgaa----------
---------------------------------------gagaaagaggcgccgccggcg
tcttctatcg---aatgtcaaaacgactctcggcaacggatatctcggctctcgcatcga
tgaagaacgtagcgaaatgcgatacttggtgtgaattgca-aatcccgtgaaccatcgag
tctttgaacgcaagttgcgcccgaagccattaggccgagggcacgtctgcctgggcgtca
cgcatcgcgtcgcccccc---------------cgatcgcacggcgatcgagggggcgga
gattggcctcccgtgcg-----ccccggcgcgcggccggcccaaatgcgatcccccggcg
acccgcgtcgcggcgagtggtggttg-aac-t--ctcaat--ctcgcgtaccgcc--gcg
cccccgggccgtccgagcgggcat-----cgagcacagacccgaacggcg----------
-----------------------
>Salvia_evansiana 676 bp 
acgaaacctgcaaagcagaccgcgaacacgtg-tttaacacagtcgggtgcgcggcgt-g
gggtgacccccgtctcgtactcgatcccccgtcgtcgcgcgtcctc-ggacc----gcgt
cgttcgggc-taacgaacccc-ggcgcggaatgcgccaaggaaaac-taatc--gaagcg
tccgcc---ccccgtgccccgttc-gcggtgcgtgctg-ggggaccggatg---------
---tctatca---aatgtcaaaacgactctcggcaacggatatctcggctctcgcatcga
tgaagaacgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtgaaccatcgag
tctttgaacgcaagttgcgcccgaagccattaggccgagggcacgtctgcctgggcgtca
cgcatcgcgtcgccccctc-tccccgcgcacagcgcggtttg--------cgggggcgga
aactggcctcccgtgcg-----ccccggcgtgcggttggcccaaatgcgatccctcggcg
actcgtatcgcgacaagtggtggttg-aacaa--ctcact--ttcat-----gtc--gtg
cttctgcgtcgttggtatgggcat-----ccgtaa-acgacccaacggtg---tcggcgt
cgcacgacgccccaccttcgacc
>Salvia_miltiorrhiza 676 bp 
tcgaaacctgcaaagcagaccgcgaacacgtg-tttaacaatgccgggtgcgtggcgtgg
gggcaacccccgtcatgtactcggtcccccgccggcgcgcgtcctc-gggca----gtgt
cgtgcgggc-taacgaacccc-ggcgcggaatgcgccaaggaaaac-taatc--gaagcg
tccgcc---cctcgtgccccgttc-gcggtgcgcgcgg-ggggattggatg---------
---tctatca---aatgtcaaaacgactctcggcaacggatatctcggctctcgcatcga
tgaagaacgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtgaaccatcgag
tctttgaacgcaagttgcgcccgaagccattaggccgagggcacgtctgcctgggcgtca
cgcatcgcgtcgccccc-c-tccccgcgcatagcgtgggctg--------cgggggcgga
aactggcctcccgtgcg-----ccccggcgcgcggctggcccaaatgcgatccctcggcg
actcgtgtcgcgacaagtggtggttg-aacaa--ctcact--ttcat-----gtc--gtg
attctgcgtcgtcggtatgggcat-----ccgtaa-acgacccaacggtg---taggcgc
cacacggcgcccaaccttcgacc
>Siphocranion_macranthum_1 676 bp 
tcgaaacctgcaaagcagaccgcgaacacgtg-tttaacatcg--tcgggcacggcctcg
tcgtgatccgg--------------ctctcgccgccgcgtagccatttgtgc-tttgcgt
cgtgcgggc-taacgaacccc-ggcgcggaatgcgccaaggaaaac-ttaat--gaagcg
tcggccc--cctcgcaccccgttt-gcggtgcgtgcgg-ggggagcggatg---------
---tctatcg---aatgtcaaaacgactctcggcaacggatatctcggctctcgcatcga
tgaagaacgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtgaaccatcgag
tctttgaacgcaagttgcgcccgaagccattaggccgagggcacgtctgcctgggcgtca
cgcatcgcgtcgccccctc-tcctcgtgccaaacacgcttgg----gatgggggggcgga
tattggcctcccgtgca-----cctcggtgcgtggttggcccaaatgtgatccctcggcg
actcttgtcacgacctgtggtggttg-aaaat--ctcaat--ctcgcttcgtgtc--gtg
ctttcgagtcgtccgtaagggctt-----cgaata-acgacccaatggcg-tcggcgcga
tatcgtgctgtgcgc-ttcgacc
>Siphocranion_macranthum_2 676 bp 
tcgaaacctgcaaagcagaccgcgaacacgtg-tttaatatcg--tcgggcacggcctcg
tcgtgatccgg--------------ctctcgccgccgcgtagcc-tttgtgc-ttcgcgt
cgtgcgggc-taacgaacccc-ggcgcggaatgcgccaaggaaaac-ttaat--gaagcg
tcggccc--cctcgcaccccgttt-gcggtgcgtgcgg-ggggagcggatg---------
---tctatcg---aatgtcaaaacgactctcggcaacggatatctcggctctcgcatcga
tgaagaacgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtgaaccatcgag
tctttgaacgcaagttgcgcccgaagccattaggccgagggcacgtctgcctgggcgtca
cgcatcgcgtcgccccctc-tccccgtgccaaaaacgctcgg----gat-ggggggtgga
tattggcctcccgtgca-----cctcggtgcgtggttggcccaaatgtgatccctcggcg
actcttgtcacgacctgtggtggttg-aaaat--ctcaat--ctcgcttcgtgtc--gtg
ctttcgagtcgtccgtaagggatt-----cgaata-acgacccaatggcg-tcggcgcga
tatcgcgctgtgcgc-ttcgacc
>Siphocranion_nudipes 676 bp 
tcgtaacctgcaaagcagaccgcgaacacgtg-tttaacaccg--tcgggcacggcctcg
tcgtgatccgg--------------ctctcgccgccgcgcagcc-tttgtgc-ttcgcgt
cgtgcgggc-taacgaacccc-ggcgcggaatgcgccaaggaaaac-ttaat--gaagcg
tcggccc--cctcgcaccccgttt-gcggtgcgtgcgg-ggggagcggatg---------
---tctatcg---aatgtcaaaacgactctcggcaacggatatctcggctctcgcatcga
tgaagaacgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtgaaccatcgag
tctttgaacgcaagttgcgcccgaagccattaggccgagggcacgtctgcctgggcgtca
cgcatcgcgtcgccccctc-tcctcgtgccaaacacgcttgg----gatggggggacgga
tattggcctcccgtgca-----ccccggtgcgtggttggcccaaatgcgatccctcgacg
actcttgtcacgacctgtggtggttg-aaaat--ctcaat--ctcgcttcgtgtc--gtg
ctttcgagtcgttcgtaagggctt-----cgaata-acgacccaatggcg-tcggtgcga
tatcgcgctgtgcgctttcgacc
