>Ceratocystiopsis_collifera_CBS126_89 Ceratocystiopsis_collifera_CBS126.89 714 bp 
-cagagttt--tctaaactcccaacccttgcgaaccat---acccatactgtt-------
---------ctcgttgcttccggcgggg--gatgcccctcccc-----------------
----------------------tcccgcgcc-gggggcggcgg-----------------
-----gccctatgaaccttt-acatctcaaccacaagaaaac-----cgtctgagctaaa
a--aacaaataatcaaaactttc-aacaacggatctcttggctctggcatcgatgaagaa
cgcagcgaaatgcgatacgtaatgtgaattgcagaattcagcgaaccatcgaatctttga
acgcacattgcgcccgccagtattct-ggcgggcatgcctgtccgagcgtcatttccccc
ctcacgcgccccgcgc------tggtgtt-ggggct----------------cctccgcc
tggcgga---------------------gggcccctaaagcgagtggcgggcccgtctgg
c--ggctccgagcgcagtaccgaacgc-aagttctcccctcgcccggac----gccccgt
-cggcgccttgccagcccaaatcgcgcatgacgtgcaactcttcttac----------
>Ceratocystis_deltoideospora_WIN_M_41 Ceratocystis_deltoideospora_WIN.M.41 714 bp 
-gcgagcgcgtcagcgactcccaacccgtgcgaacgct---acctttcttg---------
---------tctgttgctttc-ggcggg-cggccctcccccca-----------------
--------cggggggcggcggcccgcaggcctggtgccacgcc---caggcgcccgccgg
agcgacccaaccaaacctttgattctcttctccgcgtctcgcgcgcacgtctgagcacaa
ctgacacaatcgtcaaaactttc-aacaacggatctcttggttctggcatcgatgaagaa
cgcagcgaactgcgatacgtaatgtgaattgcagaattcagtgaaccatcgaatctttga
acgcacattgcgcctgccagcactct-ggcaggcacgcctgtccgagcgtcatttccacc
cctcaggcgcttgcc-------tggcgtt-ggggcccctccgccac--------------
cggcgg----------------------aggccccgaaagcgagtggcgggccggcctgg
cg-ggctccgagcgcagtagttacgca----agtcattgccgctccgga-cgcccccggc
gaggcgcccag---ccgagggacgcgcgcgcgccgcgcgccccgcccccccttctcaa
>Grosmannia_aurea_CBS438_69 714 bp 
-gcgagttca-cagtgactcccaacccgtgcaaacctta--ccgcatcctttct--gaga
gagagcg--cccgttgcttcctgccggg-cggcgtgccctcct-cccctccctctgc--g
ggggggggttggac--gggcgcccgcccgcc-gggggtgcggc---gcgg-ccgctccct
ctc----gccgcgaaccttc-ttt-----gcagtataattgtat---cgtctgag-caaa
accacagaatcgttaaaactttc-aacaacggatctcttggttctggcatcgatgaagaa
cgcagcgaactgcgataagtaatgcgaattgcagaattcagcgagccatcgaatctttga
acgcacattgcgcccgccagcattct-ggcgggcatgcctgtccgagcgtcatttcctcc
ctcacgcagcgcgcctgcg---tggtgtt-ggggtg-ttctgcggc--caggcctgcgcc
cagcgcaggccgccg-c-----------agcccccgaaagccagtggcgggccggcagcg
---ggctccgagcgcagtaagcatcac--------gccctcgctctgga-cg-ctcccgc
-ctgcgccctg---ccccacag--accggcagacgcgagtct--gcctccttctc---
>Grosmannia_cucullata_C1216 714 bp 
-gcgagttcacaagtgactcccaacccgtgccaactta---ccgcgccctggtctccagg
gcgc-----accgttgcctcctggcggg-cgccgtcggcacct-----------------
---------tgcggtgcggg-cgtgcctgcc-gggggcgcacc-----------------
------------gaaccttc-tttgccgtattatac-----------cgtctgag-aaaa
accacagaatcgtaaaaactttc-aacaacggatctcttggttctggcatcgatgaagaa
cgcagcgaactgcgataagtaatgcgaattgcagaattcagcgagccatcgaatctttga
acgcacattgcgcccgccagtattct-ggcgggcatgcctgtccgagcgtcatttcctcc
ctcacgcggc-ctttcgcg---tggtgtt-ggggcg-atctgcgac--cggtcgctgcag
cgatgcggcg-tccggcgc---------agcccctcaaagcaagtggcgggccggcagcg
---gtctccgagcgcagtaagcatttt------tgcctctcgccctgga-cg-atgctgc
-ctgcgccctg----cccccaa-----tgcagacgcaagtctatctca----------
>Grosmannia_davidsonii_WIN_M_1132 Grosmannia_davidsonii_WIN.M.1132 714 bp 
-gcgagttcacaagtgactcccaacccgtgccaactta---ccgcgccctggtctccagg
gcgc-----accgttgcctcctggcggg-cgccgtcggcacct-----------------
---------tgcggtgcggg-cgtgcctgcc-gggggcgcacc-----------------
------------gaaccttcttttgcagtattatac-----------cgtctgag-aaaa
accacagaatcgtaaaaactttc-aacaacggatctcttggttctggcatcgatgaagaa
cgcagcgaactgcgataagtaatgcgaattgcagaattcagcgagccatcgaatctttga
acgcacattgcgcccgccagtattct-ggcgggcatgcctgtccgagcgtcatttcctcc
ctcacgcggc-ctttcgcg---tggtgtt-ggggcg-atctgcgac--cggtcgctgcag
cgatgcggcg-tccggcgc---------agcccctcaaagcaagtggcgggccggcagcg
---gtctccgagcgcagtaagcatttt------tgcctctcgctctgga-cg-atgctgc
-ctgcgccctg----cccccaa-----tgcagacgcaagtctatctca----------
>Grosmannia_davidsonii_WIN_M_1494 Grosmannia_davidsonii_WIN.M.1494 714 bp 
-gcgagttcacaagtgactcccaacccgtgccaactta---ccgcgccctggtctccagg
gcgc-----accgttgcctcctggcggg-cgccgtcggcacct-----------------
---------tgcggtgcggg-cgtgcctgcc-gggggcgcacc-----------------
------------gaaccttc-tttgcagtattatac-----------cgtctgag-aaaa
accacagaatcgtaaaaactttc-aacaacggatctcttggttctggcatcgatgaagaa
cgcagcgaactgcgataagtaatgcgaattgcagaattcagcgagccatcgaatctttga
acgcacattgcgcccgccagtattct-ggcgggcatgcctgtccgagcgtcatttcctcc
ctcacgcggc-ctttcgcg---tggtgtt-ggggcg-atctgcgac--cggtcgctgcag
cgatgcggcg-tccggcgc---------agcccctcaaagcaagtggcgggccggcagcg
---gtctccgagcgcagtaagcatttt------tgcctctcgctctgga-cg-atgctgc
-ctgcgccctg----cccccaa-----tgcagacgcaagtctatctca----------
>Grosmannia_davidsonii_WIN_M_1495 Grosmannia_davidsonii_WIN.M.1495 714 bp 
-ctgagttc--cagcaactcccaacccgtgcaaacata---ccgcatcttcc--------
---agcg--cccgttgcctcccggcggg-cggcgccctccctc-----------------
-------------tgggggggaccgcccgcc-gggggctgcgc-----------------
------------ggccgttc-cagaacgcattgcagtctttagtgcctgtctgag--cag
accacagaatcgttaaaactttc-aacaacggatctcttggttctggcatcgatgaagaa
cgcagcgaactgcgataagtaatgtgaattgcagaattcagcgaaccatcgaatctttga
acgcacattgcgcccgccagcattct-ggcgggcatgcctgtccgagcgtcatttccacc
ctcacgcgccccggc-gcg---tggtgtt-ggggca-tgctgcggc--------------
ggccgcgaggccccg-c-----------aggcccctaaaaccagtggcgggccggcagcg
---ggctccgagcgcagtaagcagcaa-------cgccctcgctctgga-cg-cccccgc
-cggctccc-----gcctacag-------cggaagctgacccccatcgc---------
>Grosmannia_davidsonii_WIN_M_60B Grosmannia_davidsonii_WIN.M.60B 714 bp 
-gcgagttcacaagtgactcccaacccgtgccaactta---ccgcgccctggtctccagg
gcgc-----accgttgcctcctggcggg-cgccgtcggcacct-----------------
---------tgcggtgcggg-cgtgcctgcc-gggggcgcacc-----------------
------------gaaccttcttttgcagtattatac-----------cgtctgag-aaaa
accacagaatcgtaaaaactttc-aacaacggatctcttggttctggcatcgatgaagaa
cgcagcgaactgcgataagtaatgcgaattgcagaattcagcgagccatcgaatctttga
acgcacattgcgcccgccagtattct-ggcgggcatgcctgtccgagcgtcatttcctcc
ctcacgcggc-ctttcgcg---tggtgtt-ggggcg-atctgcgac--cggtcgctgcag
cgatgcggcg-tccggcgc---------agcctctcaaagcaagtggcgggccggcagcg
---gtctccgagcgcagtaagcatttt------tgcctctcgctctgga-cg-atgctgc
-ctgcgccctg----cccccaa-----tgcagacgcaagtctatctca----------
>Grosmannia_dryocoetis_CBS376_66 Grosmannia_dryocoetis_CBS376.66 714 bp 
cgagagttac--atcaactcccaacccgtgcatacatc---ccgcattcttgccc-----
---------ccgttcgcctccctgcggg-cggcgcgcgcctccagctc-c----------
----------ggctggcggcgcccgcccgccggggggcccaac-----gg-ccgc-----
-------gcttcgaacttct-gagtatactgagc-------------agtctgag-caaa
accat-gaatcgttaaaactttc-aacaacggatctcttggttctggcatcgatgaagaa
cgcagcgaactgcgataagtaatgtgaattgcagaattcagtgaaccatcgaatctttga
acgcacattgcgcccgccagcattct-ggcgggcatgcctgtccgagcgtcatttccacc
ctcacgcgcccctttagtgcg-tggtgtt-ggggcg-t-ctgcggc--------------
ggccgcgaggccccg-c-----------aggccccgaaacccagtggcgggccggcagaa
---ggctccgagcgcagtaagcatca---------gccctcgctctgga-cg-cccctgc
-tggcagctcg---ccctgcgg-----cggaaacgcttgcagcaaccatattc-----
>Grosmannia_europhioides_CBS229_83 Grosmannia_europhioides_CBS229.83 714 bp 
-gcgagttca-cagtgactcccaacccgtgcaaacctta--ccgcatactttccgagaga
gagagcg--cctgttgcctcctgtcggg-cggcgtg-ccctc--ccctccttccgactac
ggagggggtgggac--gggcacccgcccgcc-gggggcgcggc---gtggcccgctccct
ctc----gtcttgaaccttc-ttt-----acagtatacctataa---tgtctgag-taaa
accacagaatcgttaaaactttc-aacaacggatctcttggttctggcatcgatgaagaa
cgcagcgaactgcgataagtaatgcgaattgcagaattcagcgagccatcgaatctttga
acgcacattgcgcccgccagcattct-ggcgggcatgcctgtccgagcgtcatttcctcc
ctcacgcagcacgcctgcg---tggtgtt-ggggcg-ttctgcggc--ccggcttgcgcc
tagcgtatgccgccg-c-----------agcccccgaaagccagtggcgggccggcagcg
---ggctccgagcgcagtaagcagcag-------tgccctcgctttgga-cg-cccccgc
-ctgcgccctg----cccttat--tttggcagacgtaagtct--gcctccttctc---
>Grosmannia_europhioides_MUCL18355 Grosmannia_europhioides_MUCL18355 714 bp 
-gcgagttca-cagtgactcccaacccgtgcaaacctta--ccgcatactttcc--gaga
gagagcg--cctgttgcctcctgtcggg-cggcgtg-ccttc--ccctccttccgactac
ggaaggggtgggac--gggcacccgcccgcc-gggggcgcggc---atggcccgctccct
ctc----gtcttgaaccttc-ttt-----acagtatacctataa---tgtctgag-taaa
accacagaatcgttaaaactttc-aacaacggatctcttggttctggcatcgatgaagaa
cgcagcgaactgcgataagtaatgcgaattgcagaattcagcgagccatcgaatctttga
acgcacattgcgcccgccagcattct-ggcgggcatgcctgtccgagcgtcatttcctcc
ctcacgcagcacgcctgcg---tggtgtt-ggggcg-ttctgcggc--ccggcttgcgcc
tagcgtatgccgccg-c-----------agcccccgaaagccagtggcgggccggcagcg
---ggctccgagcgcagtaagcagcag-------tgccctcgctttgga-cg-cccccgc
-ctgcgccctg----cccctat--tctggcagacgtaagtct--gcctccttctc---
>Grosmannia_europhioides_NFRI80_67_22 Grosmannia_europhioides_NFRI80.67.22 714 bp 
-gcgagttca-cagtgactcccaacccgtgcaaacctta--ccgcatactttccgagaga
gagagcg--cctgttgcctcctgtcggg-cggcgtg-ccctc--ccctccttccgactac
ggagggggtgggac--gggcacccgcccgcc-gggggcgcggc---gtggcccgctccct
ctc----gtcttgaaccttc-ttt-----acagtatacctataa---tgtctgag-taaa
accacagaatcgttaaaactttc-aacaacggatctcttggttctggcatcgatgaagaa
cgcagcgaactgcgataagtaatgcgaattgcagaattcagcgagccatcgaatctttga
acgcacattgcgcccgccagcattct-ggcgggcatgcctgtccgagcgtcatttcctcc
ctcacgcagcacgcctgcg---tggtgtt-ggggcg-ttctgcggc--ccggcttgcgcc
tagcgtatgccgccg-c-----------agcccccgaaagccagtggcgggccggcagcg
---ggctccgagcgcagtaagcagcag-------tgccctcgctttgga-cg-cccccgc
-ctgcgccctg----cccttat--tttggcagacgtaagtct--gcctcctctc----
>Grosmannia_francke_grosmanniae_ATCC22061 Grosmannia_francke_grosmanniae_ATCC22061 714 bp 
-gcgagttca-acataactcccaacccgtgccaactta---ccgcgccctggtctccagg
gtgc-----accgttgcctcctggcgga-tgcggcc-ccacct-----------------
---------cgcggtgcgggccgtgcctgcc-gggggcgcacc-----------------
------------gaaccttc-tttgcagtacagtac-----------cgtctgag-acaa
accacagaatcgtaaaaactttt-aacaacggatctcttggttctggcatcgatgaagaa
cgcagcgaactgcgataagtaatgcgaattgcagaattcagcgagccatcgaatctttga
acgcacattgcgcccgccagcattct-ggcgggcatgcctgtccgagcgtcatttcctcc
ctcatgcggc-ctttcgcg---tggtgtt-ggggcg-atctgcggc--cggtctctgcag
cgatgcagggccccggcgc---------agcccccgaaagcgagtggcgggccggcagtg
---gtctccgagcgcagtaagcatctt------tgcctctcgctctgga-cg-aagctgc
-ctgcgccctg----cct---a-----tgcagacgcaagtctatctca----------
>Grosmannia_galeiformis_C1101 714 bp 
-gcgagttca-cagcgactcccaacccgtgcataccta---ccgcgccctcc--------
-ggggcg--cccgttgcctcctggcgggccgccgcgcccagc------------------
----------------gcgcgcgcgcccgcc-gggggc----------------------
-------tctccgaacctca-gcagtaacagta--------------cgtctgag-caaa
accactgaatcgttaaaactttc-aacaacggatctcttggttctggcatcgatgaagaa
cgcagcgaactgcgataagtaatgcgaattgcagaattcagcgagccatcgaatctttga
acgcacattgcgcccgccagcattct-ggcgggcatgcctgtccgagcgtcatttcctcc
ctcacgcggcccccccgcg---tggtgtt-ggggcg-ttctgcggc---ggcctcgcggc
cggcgc----------------------agcccccgaaagccagtggcgggccggcggc-
---ggctccgagcgcagtaagcaccag-------tgccctcgctccgga-cgaccaccgc
-ctgcgccctg----cccagaa-----cgcggacgcgagtctcgcacctcac------
>Grosmannia_galeiformis_CECT20482 Grosmannia_galeiformis_CECT20482 714 bp 
--ggagttca-cagcgactcccaacccgtgcataccta---ccgcgccctcc--------
-ggggcg--cccgttgcctcctggcgggccgccgcgcccagc------------------
----------------gcgcgcgcgcccgcc-gggggc----------------------
-------tctccgaacctca-gcagtaacagta--------------cgtctgag-caaa
accactgaatcgttaaaactttc-aacaacggatctcttggttctggcatcgatgaagaa
cgcagcgaactgcgataagtaatgcgaattgcagaattcagcgagccatcgaatctttga
acgcacattgcgcccgccagcattct-ggcgggcatgcctgtccgagcgtcatttcctcc
ctcacgcggcccccccgcg---tggtgtt-ggggcg-ttctgcggc---ggcctcccggc
cggcgc----------------------agcccccgaaagccagtggcgggccggcggc-
---ggctccgagcgcagtaagcaccag-------tgccctcgctccgga-cgaccaccgc
-ctgcgccctg----cccagaa-----cgcggacgcgagtctcgcacctcac------
>Grosmannia_huntii_WIN_M_492 714 bp 
-gcgagttca-ctgcgactcccaacccgtgcaaacctta--ccgcatcctttct--gaga
gagagcg--cccgttgcctcctgccggg-cggcgtgcccc----tccccccctttgc---
---tgggggcggatgggggtgcccgcccgcc-gggggcgcggc---gcgg-ccgctccct
ctc----gccgcgaaccttc-ttt-----gcagtatatttgtat---cgtctgag-caaa
accacagaatcgttaaaactttc-aacaacggatctcttggttctggcatcgatgaagaa
cgcagcgaactgcgataagtaatgcgaattgcagaattcagcgagccatcgaatctttga
acgcacattgcgcccgccagcattct-ggcgggcatgcctgtccgagcgtcatttcctcc
ctcacgcagcgcgcctgcg---tggtgtt-ggggcg-ttctgcggc--caggcctgcgcc
cagcgcaggcttccg-c-----------agcccccgaaagccagtggcgggccggcagcg
---ggctccgagcgcagtaagcatcac--------gccctcgctctgga-cg-cccccgc
-ctgcgccctg----cccccag--accggcagacgcgagtct--gcctccttctc---
>Grosmannia_laricis_CBS636_94 714 bp 
-gcgagttca-cagtgactcccaacccgtgcaaacctta--ccgcatactttcc--gaga
gagagcg--cctgttgcctcctgtcggg-cggagtgcccctt--ccctccttccggctac
ggagggggtggaac--gggcacccgcccgcc-gggggcgcggc---gtggcccgctccct
ctc----gtcttgaaccttc-ttt-----acagtatacctataa---tgtctgag-taaa
accacagaatcgttaaaactttc-aacaacggatctcttggttctggcatcgatgaagaa
cgcagcgaactgcgataagtaatgcgaattgcagaattcagcgagccatcgaatctttga
acgcacattgcgcccgccagcattct-ggcgggcatgcctgtccgagcgtcatttcctcc
ctcacgcagcacgcctgcg---tggtgtt-ggggcg-ttctgcggc--ccggcttgcgcc
tagcgtatgccgccg-c-----------agcccccgaaagccagtggcgggccggcagcg
---ggctccgagcgcagtaagcagcag-------tgccctcgctttgga-cg-cccccgc
-ctgcgccttg----cccccat--tttggcagacgtaagtct--gcctccttctc---
>Grosmannia_penicillata_NFRI60_21 Grosmannia_penicillata_NFRI60.21 714 bp 
-gcgagttca--agcaactcccaacccgtgcatacata---ccgcatttcttgcg-----
---------cccgttgccttccggcggg-cggcgcgcgcctccagcttcc----------
----------ggctggcggcgcccgcccgcc-ggaggaccagc-----gg-ccgc-----
-------actctgaacctct-tcgtatactgagc-------------agtctgag-aaaa
accat-gaatcgttaaaactttc-aacaacggatctcttggttctggcatcgatgaagaa
cgcagcgaactgcgataagtaatgtgaattgcagaattcagtgaaccatcgaatctttga
acgcacattgcgcccgccagcattct-ggcgggcatgcctgtccgagcgtcatttccacc
ctcacgcgcccctttagtgcg-tggtgtt-ggggca-tactgcggc--------------
tgccgcgaggcaccg-c-----------aggccctgaaacccagtggcgggccggcagaa
---ggctccgagcgcagtaagcatcac--------gccctcgctccgga-cg-cccctgc
-tggcagctcg---ccctgcgg-----cggaaacgcttgcagcaaccatctta-----
>Grosmannia_penicillata_WIN_M_131 Grosmannia_penicillata_WIN.M.131 714 bp 
-gcgagttta--aacaactcccaacccgtgcatacata---ccgcatttcttgcg-----
---------cccgttgcctcctggcggg-cggcgcgcgcctccagctc-c----------
----------ggctggcggcgcccgcccgcc-gggggaccagc-----gg-tcgc-----
-------actttgaacctct-gcgtacactgagc-------------agtctgag-caaa
accat-gaatcgttaaaactttc-aacaacggatctcttggttctggcatcgatgaagaa
cgcagcgaactgcgataagtaatgtgaattgcagaattcagtgaaccatcgaatctttga
acgcacattgcgcccgccagcattct-ggcgggcatgcctgtccgagcgtcatttccacc
ctcacgcgcccctttagtgcg-tggtgtt-ggggca-tactgcggc--------------
tgccgcaaggcaccg-c-----------aggccctgaaacccagtggcgggccggcagaa
---ggctccgagcgcagtaagcatcac--------gccctcgctctgga-cg-cccctgc
-tggcagctcg---ccctgcgg-----cggaaacgcttgcagcaaccatttct-----
>Grosmannia_piceaperda_WIN_M_1380 Grosmannia_piceaperda_WIN.M.1380 714 bp 
-gcgagttca-ctgcgactcccaacccgtgcaaacctta--ccgcatcctttct--gaga
gagagcg--cccgttgcctcctgccggg-cggcgtgcgcccc--tccccccctttgc---
---tgggggcggac--gggtgcccgcccgcc-ggggacgcggccgggcgg-ccgctccct
ctcgggggccgcgaaccttc-tttaacacgccgtatatctgtatgagcgtctgagtcaaa
accacagaatcgttaaaactttc-aacaacggatctcttggttctggcatcgatgaagaa
cgcagcgaactgcgataagtaatgcgaattgcagaattcagcgagccatcgaatctttga
acgcacattgcgcccgccagcattct-ggcgggcatgcctgtccgagcgtcatttcctcc
ctcacgcagcgcgcctgcgcgctggtgttggggacg-ttctgcggccgcaggcctgcgcc
cagcgcagggcccggccgccgggcggggagcccccgaaagccagtggcgggccggcagcg
atcggctccgagcgcagtaagcatcacctgtttatgccctcgctctgga-cgccccccgc
-ctgcgccctgccgcccccccg--accggcagacgcgagtct--gtctccttctc---
>Grosmannia_piceaperda_WIN_M_980 Grosmannia_piceaperda_WIN.M.980 714 bp 
-gcgagttca-ctgcgactcccaacccgtgcaaacctta--ccgcatcctttct--gaga
gagagcg--cccgttgcctcctgccggg-cggcgtgcccc----tccccccctttgc---
---tgggggcggac--gggtgcccgcccgcc-ggggacgcggc---gcgg-ccgctccct
ctc----gccgcgaaccttc-ttt-----gccgtatatctgtat---cgtctgag-caaa
accacagaatcgttaaaactttc-aacaacggatctcttggttctggcatcgatgaagaa
cgcagcgaactgcgataagtaatgcgaattgcagaattcagcgagccatcgaatctttga
acgcacattgcgcccgccagcattct-ggcgggcatgcctgtccgagcgtcatttcctcc
ctcacgcagcgcgcctgcg---tggtgtt-ggggcg-ttctgcggc--caggcctgcgcc
cagcgcaggccgccg-c-----------agcccccgaaagccagtggcgggccggcagcg
---ggctccgagcgcagtaagcatcac--------gccctcgctctgga-cgccccccgc
-ctgcgccctgcc-cccccccg--accggcagacgcgagtct--gtctccttctc---
>Grosmannia_pseudoeurophioides_WIN_M_42 Grosmannia_pseudoeurophioides_WIN.M.42 714 bp 
-gcgagttca--agcaactcccaacccgtgcatacata---ccgcatttcttgcg-----
---------cccgttgcctcctggcggg-cggcgcgcgcctctagctt-c----------
----------ggctggcggcgcccgcccgcc-gggggcccagc-----gg-ccgc-----
-------actctgaacctct-gcgtacactgagc-------------agtctgag-caaa
accat-gaatcgttaaaactttc-aacaacggatctcttggttctggcatcgatgaagaa
cgcagcgaactgcgataagtaatgtgaattgcagaattcagtgaaccatcgaatctttga
acgcacattgcgcccgccagcattct-ggcgggcatgcctgtccgagcgtcatttccacc
ctcacgcgccccttcagtgcg-tggtgtt-ggggca-tactgcggc--------------
ggccgcgaggcaccg-c-----------aggccctgaaacccagtggcgggccggcagaa
---ggctccgagcgcagtaagcatcac--------gccctcgctccgga-cg-cccctgc
-tggcagctcg---ccctgcgg-----cggaaacgcttgcagcaaccattttct----
>Grosmannia_wageneri_ATCC58579 714 bp 
-gcgagttca-cagcgactcccaacccgtgcaaacctta--ccgcatccttctg------
-agagcg--cccgttgcctcctggcggg-cggcgcgacccccc-----cccttccct---
----gggg--agggggctgcgaccgcccgcc-gggggcgcggc---gcgg-ccgctctct
ccc--------cgaaccttc-ttt------acagttaccatgac---cgtctgag-caaa
accactgaatcgttaaaactttc-aacaacggatctcttggttctggcatcgatgaagaa
cgcagcgaactgcgataagtaatgcgaattgcagaattcagcgagccatcgaatctttga
acgcacattgcgcccgccagcattct-ggcgggcatgcctgtccgagcgtcatttcctcc
ctcacgcagcgcgcctgcg---tggtgtt-ggggcg-ttctgcggc--caggcctgcgcc
tagc--aggccgccg-c-----------agcccccgaaagccagtggcgggccggcagcg
---ggctccgagcgcagtaagcagcag-------tgccctcgctctgga-cg-cccccgc
-ctgcgccctg----ccccaaa--gacggcagacgcgagtct--ccctccttctc---
>Hyalopesotum_pini_WIN_M_82_89 714 bp 
-gcgagttca-cagcgactcccaacccgtgcataccta---ccgcgccctcc--------
-ggggcg--cccgttgcctcctggcgggccgccgcgcccagc------------------
----------------gcgcgcgcgcccgcc-gggggc----------------------
-------tctccgaacctca-gcagtaacagta--------------cgtctgag-caaa
accactgaatcgttaaaactttc-aacaacggatctcttggttctggcatcgatgaagaa
cgcagcgaactgcgataagtaatgcgaattgcagaattcagcgagccatcgaatctttga
acgcacattgcgcccgccagcattct-ggcgggcatgcctgtccgagcgtcatttcctcc
ctcacgcggcccccccgcg---tggtgtt-ggggcg-ttctgcggc---ggcctcccggc
cggcgc----------------------agcccccgaaagccagtggcgggccggcggc-
---ggctccgagcgcagtaagcaccag-------tgccctcgctccgga-cgaccaccgc
-ctgcgccctg----cccagaa-----cgcggacgcgagtctcgcacctcac------
>Leptographium_americanum_WIN_M_1456 Leptographium_americanum_WIN.M.1456 714 bp 
-gcgagttca--agcaactcccaacccgtgcatacata---ccgcatttcttgcg-----
---------cccgttgcctcctggcggg-cggcgcgcgcctccagcct-c----------
----------ggctggcggcgcccgcccgcc-gggggcccagc-----gg-ccgc-----
-------actctgaacctct-gcgtacactgagc-------------agtctgag-caaa
accat-gaatcgttaaaactttc-aacaacggatctcttggttctggcatcgatgaagaa
cgcagcgaactgcgataagtaatgtgaattgcagaattcagtgaaccatcgaatctttga
acgcacattgcgcccgccagcattct-ggcgggcatgcctgtccgagcgtcatttccacc
ctcacgcgccccttcagtgcg-tggtgtt-ggggca-tactgcggc--------------
tgccgcaaggcaccg-c-----------aggccctaaaacccagtggcgggccggcagaa
---ggctccgagcgcagtaagcattac--------gccctcgctccgga-cg-cccctgc
-tggcagctcg---ccctgcgg-----cggaaacgcttgcagcaaccaattttt----
>Leptographium_lundbergii_CBS352_29 Leptographium_lundbergii_CBS352.29 714 bp 
-gcgagttca-cagcgactcccaacccgtgcaaacctta--ccgcatcctttct--gaga
gagagcg--cccgttgcctcctgccggg-cggcgtgccctcca-cccccccctctgc---
--gggggggcggac--gggcgcccgcccgcc-gggggcgcggc---gcgg-ccgctcccc
ctc----gccgcgaaccttc-ttt-----gcagtataattgtat---cgtctgag-caaa
accacagaatcgttaaaactttc-aacaacggatctcttggttctggcatcgatgaagaa
cgcagcgaactgcgataagtaatgcgaattgcagaattcagcgagccatcgaatctttga
acgcacattgcgcccgccagcattct-ggcgggcatgcctgtccgagcgtcatttcctcc
ctcacgcagcgcgcctgcg---tggtgtt-ggggcg-ttctgcggc--caggcctgcgcc
cagcgcaggccgccg-c-----------agcccccgaaagccagtggcgggccggcagcg
---ggctccgagcgcagtaagcatcac--------gccctcgctctgga-cg-cccccgc
-ctgcgccctg----cccccat--accggcagacgcgagtct--gcctccttctc---
>Leptographium_lundbergii_DAOM64746 Leptographium_lundbergii_DAOM64746 714 bp 
-gcgagttca-cagcgactcccaacccgtgcaaacctta--ccgcatcctttct--gaga
gagagcg--cccgttgcctcctgccggg-cggcgtgccctcca-tcccctcctctgcgcg
ggggggggttggac--gggtgcccgcccgcc-ggggacgtgac---gcgg-ctgctcccc
ctc----gccgcgaaccttc-ttt-----acagtataattgtat---cgtctgag-caaa
accacagaatcgttaaaactttc-aacaacggatctcttggttctggcatcgatgaagaa
cgcagcgaactgcgataagtaatgcgaattgcagaattcagcgagccatcgaatctttga
acgcacattgcgcccgccagcattct-ggcgggcatgcctgtccgagcgtcatttcctcc
ctcacgcagcgcgcctgcg---tggtgtt-ggggcg-ttctgcggc--caggcctgcgcc
cagcgcaggccgccg-c-----------agcccccgaaagccagtggcgggccggcagcg
---ggctccgagcgcagtaagcatcac--------gccctcgctttgga-cg-cccccgc
-ctgcgccctg---tcccccat--accggcagacgcgagtct--gcctccttctc---
>Leptographium_lundbergii_DSMZ5010 Leptographium_lundbergii_DSMZ5010 714 bp 
-gcgagttca-cagcgactcccaacccgtgcaaacctta--ccgcatcctttct--gaga
gagagcg--cccgttgcctcctgccggg-cggcgtgccctcca-cccccccctctgc---
--gggggggcggac--gggcgcccgcccgcc-gggggcgcggc---gcgg-ccgctcccc
ctc----gccgcgaaccttc-ttt-----gcagtataattgtat---cgtctgag-caaa
accacagaatcgttaaaactttc-aacaacggatctcttggttctggcatcgatgaagaa
cgcagcgaactgcgataagtaatgcgaattgcagaattcagcgagccatcgaatctttga
acgcacattgcgcccgccagcattct-ggcgggcatgcctgtccgagcgtcatttcctcc
ctcacgcagcgcgcctgcg---tggtgtt-ggggcg-ttctgcggc--caggcctgcgcc
cagc-caggccgccg-c-----------agcccccgaaagccagtggcgggccggcagcg
---ggctccgagcgcagtaagcatcac--------gccctcgctctgga-cg-cccccgc
-ctgcgccctg----cccccat--accggcagacgcgagtct--gcctccttctc---
>Leptographium_lundbergii_NFRI60_25 Leptographium_lundbergii_NFRI60.25 714 bp 
-gcgagttca-cagcgactcccaacccgtgcaaacctta--ccgca-cctttct--gaga
gagagcg--cccgttgcctcctgccggg-cggcgtgccctcca-cccccccctctgc---
--gggggggcggac--gggcgcccgcccgcc-gggggcgcggc---gcgg-ccgctcccc
ctc----gccgcgaaccttc-ttt-----gcagtataattgtat---cgtctgag-caaa
accacagaatcgttaaaactttc-aacaacggatctcttggttctggcatcgatgaagaa
cgcagcgaactgcgataagtaatgcgaattgcagaattcagcgagccatcgaatctttga
acgcacattgcgcccgccagcattct-ggcgggcatgcctgtccgagcgtcatttcctcc
ctcacgcagcgcgcctgcg---tggtgtt-ggggcg-ttctgcggc--caggcctgcgcc
cagcgcaggccgccg-c-----------agcccccgaaagccagtggcgggccggcagcg
---ggctccgagcgcagtaagcatcac--------gccctcgctctgga-cg-cccccgc
-ctgcgccctg----cccccat--accggcagacgcgagtct--gcctccttctc---
>Leptographium_lundbergii_NFRI69_148 Leptographium_lundbergii_NFRI69.148 714 bp 
-gcgagttca-cagcgactcccaacccgtgcaaacctta--ccgcatcctttct--gaga
gagagcg--cccgttgcctcctgccggg-cggcgtgccctcca-cccccccctctgc---
--gggggggcggac--gggcgcccgcccgcc-gggggcgcggc---gcgg-ccgctcccc
ctc----gccgcgaaccttc-ttt-----gcagtataattgtat---cgtctgag-caaa
accacagaatcgttaaaactttc-aacaacggatctcttggttctggcatcgatgaaaaa
cgcagcgaactgcgataagtaatgcgaattgcagaattcagcgagccatcgaatctttga
acgcacattgcgcccgccagcattct-ggcgggcatgcctgtccgagcgtcatttcctcc
ctcacgcaacgcgcctgcg---tggtgttgggggcg-ttcttgcgc--caggcctgcgcc
cagcgcaggccgccg-c-----------agcccccgaaagccagtggcgggccggcagcg
---ggctccgagcgcagtaagcatcac--------gccctcgctctgga-cg-cccccgc
-ctgcgccctg----cccccat--accggcagacgcgagtct--gcctccttctc---
>Leptographium_lundbergii_NFRI89_1040_1_3 Leptographium_lundbergii_NFRI89.1040.1.3 714 bp 
-gcgagttca-cagcgactcccaacccgtgcaaacctta--ccgcatcctttct--gaga
gagagcg--cccgttgcctcctgccggg-cggcgtgccctcca-cccccccctctgc---
--gggggggcggac--gggcgcccgcccgcc-gggggcgcggc---gcgg-ccgctcccc
ctc----gccgcgaaccttc-ttt-----gcagtataattgtat---cgtctgag-caaa
accacagaatcgttaaaactttc-aacaacggatctcttggttctggcatcgatgaagaa
cgcagcgaactgcgataagtaatgcgaattgcagaattcagcgagccatcgaatctttga
acgcacattgcgcccgccagcattct-ggcgggcatgcctgtccgagcgtcatttcctcc
ctcacgcagcgcgcctgcg---tggtgtt-ggggcg-ttctgcgga--caggcctgcgcc
cagcgcaggccgccg-c-----------agcccccgaaagccagtggcgggccggcagcg
---ggctccgagcgcagtaagcatcac--------gccctcgctctgga-cg-cccccgc
-ctgcgccctg----cccccat--accggcagacgcgagtct--gcctccttctc---
>Leptographium_procerum_DAOM33940 Leptographium_procerum_DAOM33940 714 bp 
---gagttca-cagcgactcccaacccgtgcataccta---ccgcgccctcc--------
-ggggcg--cccgttgcctcctggcgggccgccgcgcccagc------------------
----------------gcgcgcgcgcccgcc-gggggc----------------------
-------tctccgaacctca-gcagtaacagta--------------cgtctgag-caaa
accactgaatcgttaaaactttc-aacaacggatctcttggttctggcatcgatgaagaa
cgcagcgaactgcgataagtaatgcgaattgcagaattcagcgagccatcgaatctttga
acgcacattgcgcccgccagcattct-ggcgggcatgcctgtccgagcgtcatttcctcc
ctcacgcggcccccccgcg---tggtgtt-ggggcg-ttctgcggc---ggcctcccggc
cggcgc----------------------agcccccgaaagccagtggcgggccggcggc-
---ggctccgagcgcagtaagcaccag-------tgccctcgctccgga-cgaccaccgc
-ctgcgccctg----cccagaa-----cgcggacgcgagtctcgcacctcac------
>Leptographium_procerum_NFRI59_84_2 Leptographium_procerum_NFRI59.84.2 714 bp 
-gcgagttca-cagcgactcccaacccgtgcatacctta--ccgcat-cttctg------
-agagcg--cccgttgcctcctggcggg-cggcgcgccctccc-taagcccctctgc---
----gggg------------------------gcggggggggc---gcgg-ccgctctcc
cac--------cgaaccttc-tat------tagtatacctttac---cgtctgag-caaa
accactgaatcgttaaaactttc-aacaacggatctcttggttctggcatcgatgaagaa
cgcagcgaactgcgataagtaatgcgaattgcagaattcagcgagccatcgaatctttga
acgcacattgcgcccgccagcattct-ggcgggcatgcctgtccgagcgtcatttcctcc
ctcacgcagcgcgcctgcg---tggtgtt-ggggcgtttctgcggc--caggcctgcgcc
tagc--aggcctccg-c-----------agcccccgaaagccagtggcgggccggcagcg
---ggctccgagcgcagtaagcagcag-------tgccctcgctctgga-cg-cctccgc
-ctgcgccctg----ccccaaatgaccggcagacgcaagtctgcccctccttctc---
>Leptographium_procerum_TOM73_12 Leptographium_procerum_TOM73.12 714 bp 
-gcgagttca-cagcgactcccaacccgtgcatacctta--ccgcat-cttctg------
-agagcg--cccgttgcctcctggcggg-cggcgcgccctccc-taagcccctctgc---
----ggggtgcggggggggcgcccgcccgcc-gggggcgcggc---gcgg-ccgctctcc
cac--------cgaaccttc-tat------tagtatacctttac---cgtctgag-caaa
accactgaatcgttaaaactttc-aacaacggatctcttggttctggcatcgatgaagaa
cgcagcgaactgcgataagtaatgcgaattgcagaattcagcgagccatcgaatctttga
acgcacattgcgcccgccagcattct-ggcgggcatgcctgtccgagcgtcatttcctcc
ctcacgcagcgcgcctgcg---tggtgtt-ggggcgtttctgcggc--caggcctgcgcc
tagc--aggcctccg-c-----------agcccccgaaagccagtggcgggccggcagcg
---ggctccgagcgcagtaagcagcag-------tgccctcgctctgga-cg-cctccgc
-ctgcgccctg----ccccaaatgaccggcagacgcaagtctgcccctccttctc---
>Leptographium_procerum_TOM76_8 714 bp 
-gcgagttca-cgacgactcccaacccgtgcatacctta--ccgcat-cttctg------
-agagcg--cccgttgcctcctggcggg-cggcgcgccctccc-taagcccctctgc---
----ggggtgcggggggggcgcccgcccgcc-gggggcgcggc---gcgg-ccgctctcc
cac--------cgaaccttc-tat------tagtatacctttac---cgtctgag-caaa
accactgaatcgttaaaactttc-aacaacggatctcttggttctggcatcgatgaagaa
cgcagcgaactgcgataagtaatgcgaattgcagaattcagcgagccatcgaatctttga
acgcacattgcgcccgccagcattct-ggcgggcatgcctgtccgagcgtcatttcctcc
ctcacgcagcgcgcctgcg---tggtgtt-ggggcgtttctgcggc--caggcctgcgcc
tagc--aggcctccg-c-----------agcccccgaaagccagtggcgggccggcagcg
---ggctccgagcgcagtaagcagcag-------tgccctcgctctgga-cg-cctccgc
-ctgcgccctg----ccccaaatgaccggcagacgcaagtctgcccctccttctc---
>Leptographium_procerum_WIN_M_1264 Leptographium_procerum_WIN.M.1264 714 bp 
-gcgagttca-cagcgactcccaacccgtgcatacctta--ccgcat-cttctg------
-agagcg--cccgttgcctcctggcggg-cggcgcgccctccc-taagcccctctgc---
----ggggtgcggggggggcgcccgcccgcc-gggggggcggc---gcgg-ccgctctcc
cac--------cgaaccttc-tat------tagtatacctttac---cgtctgag-caaa
accactgaatcgttaaaactttc-aacaacggatctcttggttctggcatcgatgaagaa
cgcagcgaactgcgataagtaatgcgaattgcagaattcagcgagccatcgaatctttga
acgcacattgcgcccgccagcattct-ggcgggcatgcctgtccgagcgtcatttcctcc
ctcacgcagcgcgcctgcg---tggtgtt-ggggcgtttctgcggc--caggcctgcgcc
tagc--aggcctccg-c-----------agcccccgaaagccagtggcgggccggcagcg
---ggctccgagcgcagtaagcagcag-------tgccctcgctctgga-cg-cctccgc
-ctgcgccctg----ccccaaatgaccggcagacgcaagtctgcccctccttctc---
>Leptographium_sp_J_R_88_194A 714 bp 
-gcgagttta--aacaactcccaacccgtgcatacata---ccgcatttctt--------
----gcg--cccgttgcctcctggcggg-cggcgcgcgcctccagctcc-----------
----------ggctggcggcgcccgcccgcc-gggggaccagc-----gg-tcgc-----
-------actttgaacctct-gcgtacactgagc-------------agtctgag-caaa
accat-gaatcgttaaaactttc-aacaacggatctcttggttctggcatcgatgaagaa
cgcagcgaactgcgataagtaatgcgaattgcagaattcagcgagccatcgaatctttga
acgcacattgcgcccgccagcattct-ggcgggcatgcctgtccgagcgtcatttcctcc
ctcacgcagcgcgcctgcg---tggtgtt-ggggcg-ttctgcggt--caggcctgcgcc
cagcgcaggccgccg-c-----------agcccccgaaagccagtggcgggccggcagcg
---ggctccgagcgcagtaagcatcac-------gcccttcgctctgga-cg-cccccgc
-ctgcgccctg---ccccccag--accggcagacgcgagtct--gcccccttctc---
>Leptographium_sp_WIN_M_1106 714 bp 
-gcgagttca-cagcgactcccaacccgtgagaacctta--ccgcatcctttct--gaga
gagagcg--cccgttgcctcctgccggg-cggcgtgccctccc-cccccccccctct---
gcggggggcgggac--gggcgcccgcccgcc-gggggcgcggc---gcgg-ccgctccct
ccc----accgcgaaccttc-ttt-----gcagtatatttgtat---cgtctgag-c-aa
accacagaatcgttaaaactttc-aacaacggatctcttggttctggcatcgatgaagaa
cgcagcgaactgcgataagtaatgcgaattgcagaattcagcgagccatcgaatctttga
acgcacattgcgcccgccagcattct-ggcgggcatgcctgtccgagcgtcatttcctcc
ctcacgcagcgcgcctgcg---tggtgtt-ggggcg-ttctgcggt--caggcctgcgcc
cagcgtaggccgccg-c-----------agcccccgaaagccagtggcgggccggcagcg
---ggctccgagcgcagtaagcatcac--------gccctcgctctgga-cg-cccccgc
-ctgcgccctg---ccccccat--accggcagacgcgagtct--gcccccttctc---
>Leptographium_sp_WIN_M_1247 714 bp 
-gcgagttca-cagcgactcccaacccgtgagaacctta--ccgcatcctttct--gaga
gagagcg--cccgttgcctcctgccggg-cggcgtgccct-----cccccccccttt---
gcggggggcgggac--gggcgcccgcccgcc-gggggcgcggc---gcgg-ccgctccct
ccc----accgcgaaccttc-ttt-----gcagtatatttgtat---cgtctgag-c-aa
accacagaatcgttaaaactttc-aacaacggatctcttggttctggcatcgatgaagaa
cgcagcgaactgcgataagtaatgcgaattgcagaattcagcgagccatcgaatctttga
acgcacattgcgcccgccagcattct-ggcgggcatgcctgtccgagcgtcatttcctcc
ctcacgcagcgcgcctgcg---tggtgtt-ggggcg-ttctgcggt--caggcctgcgcc
cagcgtaggccgccg-c-----------agcccccgaaagccagtggcgggccggcagcg
---ggctccgagcgcagtaagcatcac--------gccctcgctctgga-cg-cccccgc
-ctgcgccctg---ccccccat--accggcagacgcgagtct--gcccccttctc---
>Leptographium_sp_WIN_M_1269 714 bp 
-gcgagttca-cagggactcccaacccgtgagaacctta--ccgcatccttttt--ggga
gagagcg--cccgttgcctcctgccggg-cggcgtgccctccc-cccccccccctct---
gcggggggcgggac--gggcgcccgcccgcc-gggggcgcggc---gcgg-ccgctccct
ccc----accgcgaaccttc-ttt-----gcagtatatttgtat---cgtctgag-c-aa
accacagaatcgttaaaactttc-aacaacggatctcttggttctggcatcgatgaagaa
cgcagcgaactgcgataagtaatgcgaattgcagaattcagcgagccatcgaatctttga
acgcacattgcgcccgccagcattct-ggcgggcatgcctgtccgagcgtcatttcctcc
ctcacgcagcgcgcctgcg---tggtgtt-ggggcg-ttctgcggt--caggcctgcgcc
cagcgtaggccgccg-c-----------agcccccgaaagccagtggcgggccggcagcg
---ggctccgagcgcagtaagcatcac--------gccctcgctctgga-cg-cccccgc
-ctgcgccctg---ccccccat--accggcagacgcgagtct--gcccccttctc---
>Leptographium_sp_WIN_M_528 714 bp 
-gcgagttca--agcaactcccaacccgtgcatacata---ccgcatttcttgcg-----
---------cccgttgcctcctggcggg-cggcgcgcgcctccagctt-c----------
----------ggctggcggcgcccgcccgcc-gggggcccagc-----gg-ccgc-----
-------actctgaacctct-gcgtacactgagc-------------agtctgag-caaa
accat-gaatcgttaaaactttc-aacaacggatctcttggttctggcatcgatgaagaa
cgcagcgaactgcgataagtaatgtgaattgcagaattcagtgaaccatcgaatctttga
acgcacattgcgcccgccagcattct-ggcgggcatgcctgtccgagcgtcatttccacc
ctcacgcgcccctttagtgcg-tggtgtt-ggggca-tactgcagc--------------
tgccgcaaggcaccg-c-----------aggccctaaaacccagtggcgggccggcagaa
---ggctccgagcgcagtaagcattac--------gccctcgctccgga-cg-cccctgc
-tggcagctcg---ccctgcgg-----cggaaacgcttgcagcaaccaatttt-----
>Leptographium_sp_WIN_M_984 714 bp 
-gcgagttca-cagcaactcccaacccgtgcaaaccta---ccgcatcctgccc------
--gagcg--cccgttgcctcctggcggg-cggcgcgtcagccc---------------cc
tgtaaaacgggagctgatgccgccgcccgac-gggggcgcggc---gtgg-ccgctc---
-------accgtgaaccttc-tgtatcgtatcttga-----------cgtctgagcagaa
accactgaatcgttaaaactttc-aacaacggatctcttggttctggcatcgatgaagaa
cgcagcaaactgcgataagtaatgcgaattgcagaattcagcgagtcatcgaatctttga
acgcacattgcgcccgccagcactct-ggcgggcatgcctgtccgagcgtcatttcctcc
ctcacgcagcacgcctgcg---tggtgtt-ggggcg-atctgcggc---ggtcgcgtccc
ctcagaagggcgcgcacgcaccgc----agccccctaaagccagtggcgggccggcggcg
---ggctccgagcgcagtaagcagcat-------tgccctcgctctggattgcccccagc
-ctgcgccctg---ccctagac-----agcagacgcaagtctaccctttttttac---
>Leptographium_sp_WIN_M_985 714 bp 
-gcgagttca-cagcaactcccaacccgtgcaaaccta---ccgcatcctgccc------
--gagcg--cccgttgcctcctggcggg-cggcgcgtcagccc---------------cc
tgtaaaacgggagctgatgccgccgcccgac-gggggcgcggc---gtgg-ccgctc---
-------accgtgaaccttc-tgtatcgtatcttga-----------cgtctgagcagaa
accactgaatcgttaaaactttc-aacaacggatctcttggttctggcatcgatgaagaa
cgcagcaaactgcgataagtaatgcgaattgcagaattcagcgagtcatcgaatctttga
acgcacattgcgcccgccagcactct-ggcgggcatgcctgtccgagcgtcatttcctcc
ctcacgcagcacgcctgcg---tggtgtt-ggggcg-atctgcggc---ggtcgcgtccc
ctcagaagggcgcgcacgcaccgc----agccccctaaagccagtggcgggccggcggcg
---ggctccgagcgcagtaagcagcat-------tgccctcgctctggattgcccccagc
-ctgcgccctg---ccctagac-----agcagacgcaagtctacccttttttttac--
>Leptographium_terebrantis_CBS298_85 Leptographium_terebrantis_CBS298.85 714 bp 
-gcgagttca-cagtgactcccaacccgtgcaaaccttagcacgcatcctttct--gaga
gagagcgcccccgttgctttctgccggg-cggcgtgccctcctccctccccctctgca-g
ggggggggttggac--gggcgcccgcccgcc-gggggcgcggc---gcgg-ccgctccct
ctc----gccgcgaaccttc-ttt-----gcagtataattgtat---cgtctgag-caaa
accacagaatcgttaaaactttc-aacaacggatctcttggttctggcatcgatgaagaa
cgcagcgaactgcgataagtaatgcgaattgcagaattcagcgagccatcgaatctttga
acgcacattgcgcccgccagcattct-ggcgggcatgcctgtccgagcgtcatttcctcc
ctcacgcagcgcgcctgcg---tggtgtt-ggggcg-ttctgcggc--caggcctgcgcc
cagcgcaggccgccg-c-----------agcccccgaaagccagtggcgggccggcagcg
---ggctccgagcgcagtaagcatcac--------gccctcgctctgga-cg-ctcccgc
-ctgcgccctg---tcccacag--accggcagacgcgagtct--gcctccttctc---
>Leptographium_terebrantis_CBS337_70 Leptographium_terebrantis_CBS337.70 714 bp 
-gcgagttca-cagtgactcccaacccgtgcaaacctta--ccgcatcctttct--gaga
gagagcgcccccgttgctttctgccggg-cggcgtgccctcctccctccccctctgcagg
ggggggggttggac--gggcgcccgcccgcc-gggggcgcggc---gcgg-ccgctccct
ctc----gccgcgaaccttc-ttt-----gcagtataattgtat---cgtctgag-caaa
accacagaatcgttaaaactttc-aacaacggatctcttggttctggcatcgatgaagaa
cgcagcgaactgcgataagtaatgcgaattgcagaattcagcgagccatcgaatctttga
acgcacattgcgcccgccagcattct-ggcgggcatgcctgtccgagcgtcatttcctcc
ctcacgcagcgcgcctgcg---tggtgtt-ggggcg-ttctgcggc--caggcctgcgcc
cagcgcaggccgccg-c-----------agcccccgaaagccagtggcgggccggcagcg
---ggctccgagcgcagtaagcatcac--------gccctcgctctgga-cg-ctcccgc
-ctgcgccctg---tcccacag--accggcagacgcgagtct--gcctccttctc---
>Leptographium_terebrantis_CBS408_61 Leptographium_terebrantis_CBS408.61 714 bp 
-gcgagttca-cagtgactcccaacccgtgcaaacctta--ccgcatccttttt--gaga
gagagcg--cccgttgcttcctgccggg-cggcgtgccctcct-cccctccctctgc---
ggggggggttggac--gggcgcccgcccgcc-gggggtgcggc---gcgg-ccgctccct
ctc----gccgcgaaccttc-ttt-----gcagtataattgtat---cgtctgag-caaa
accacagaatcgttaaaactttc-aacaacggatctcttggttctggcatcgatgaagaa
cgcagcgaactgcgataagtaatgcgaattgcagaattcagcgagccatcgaatctttga
acgcacattgcgcccgccagcattct-ggcgggcatgcctgtccgagcgtcatttcctcc
ctcacgcagcgcgcctgcg---tggtgtt-ggggtg-ttctgcggc--caggcctgcgcc
cagcgcaggccgccg-c-----------agcccccgaaagccagtggcgggccggcagcg
---ggctccgagcgcagtaagcatcac--------gccctcgctctgga-cg-ctcccgc
-ctgcgccctg---ccccacag--accggcagacgcgagtct--gcctccttctc---
>Leptographium_terebrantis_UAMH9690 Leptographium_terebrantis_UAMH9690 714 bp 
-gcgagttca-cagtgactcccaacccgtgcaaacctta--ccgcatcctttct--gaga
gagagcg--cccgttgcttcctgccggg-cggcgtgccctcctccccccccctctgc--a
ggggggggttggac--gggcgcccgcccgcc-gggggtgcggc---gcgg-ccgctccct
ctc----gccgcgaaccttc-ttt-----gcagtataattgtat---cgtctgag-caaa
accacagaatcgttaaaactttc-aacaacggatctcttggttctggcatcgatgaagaa
cgcagcgaactgcgataagtaatgcgaattgcagaattcagcgagccatcgaatctttga
acgcacattgcgcccgccagcattct-ggcgggcatgcctgtccgagcgtcatttcctcc
ctcacgcagcgcgcctgcg---tggtgtt-ggggcg-ttctgcggc--caggcctgcgcc
cagcgcaggccgccg-c-----------agcccccgaaagccagtggcgggccggcagcg
---ggctccgagcgcagtaagcatcac--------gccctcgctctgga-cg-ctcccgc
-ctgcgccctg---ccccacag--accggcagacgcgagtct--gcctccttctc---
>Leptographium_terebrantis_UAMH9722 Leptographium_terebrantis_UAMH9722 714 bp 
-gcgagttca-cagtgactcccaacccgtgcaaacctta--ccgcatcctttct--gaga
gagagcg--cccgttgcttcctgccggg-cggcgtgccctcct-cccctccctctgc--g
ggggggggttggac--gggcgcccgcccgcc-gggggtgcggc---gcgg-ccgctccct
ctc----gccgcgaaccttc-ttt-----gcagtataattgtat---cgtctgag-caaa
accacagaatcgttaaaactttc-aacaacggatctcttggttctggcatcgatgaagaa
cgcagcgaactgcgataagtaatgcgaattgcagaattcagcgagccatcgaatctttga
acgcacattgcgcccgccagcattct-ggcgggcatgcctgtccgagcgtcatttcctcc
ctcacg-agcgcgcctgcg---tggtgtt-ggggtg-ttctgcggc--caggcctgcgcc
cagcgcaggccgccgca-----------agcccccgaaagccagtggcgggccggcagcg
---ggctccgagcgcagtaagcatcac--------gccctcgctctgga-cg-ctcccgc
-ctgcgccctg---ccccacag--accggcagacgcgagtct--gcctccttctc---
>Leptographium_truncatum_CBS929_85 Leptographium_truncatum_CBS929.85 714 bp 
-gcgagttca-cagcgactcccaacccgtgagaacctta--ccgcatcctttcc--gaga
gagagcg--cccgttgcctcctgccggg-cggcgtgccct------ccccccccctc---
tgcggggggcggac--gggcgcccgcccgcc-gggggcgcggc---gcgg-ccgctccct
ccc----gccgcgaaccttc-ttt-----gcagtatatttgtat---cgtctgag-c-aa
accacagaatcgttaaaactttc-aacaacggatctcttggttctggcatcgatgaagaa
cgcagcgaactgcgataagtaatgcgaattgcagaattcagcgagccatcgaatctttga
acgcacattgcgcccgccagcattct-ggcgggcatgcctgtccgagcgtcatttcctcc
ctcacgcagcgcgcctgcg---tggtgtt-ggggcg-ttctgcggt--caggcctgcgcc
cagcgcaggccgccg-c-----------agcccccgaaagccagtggcgggccggcagcg
---ggctccgagcgcagtaagcatcac--------gccctcgctctgga-cg-cccccgc
-ctgcgccctg---ccccccag--accggcagacgcgagtct--gcccccttctc---
>Leptographium_truncatum_NFRI1813_1 Leptographium_truncatum_NFRI1813.1 714 bp 
-gcgagttca-cagcgactcccaacccgtgagaacctta--ccgcatcctttcc--gaga
gagagcg--cccgttgcctcctgccggg-cggcgtgccct-----cccccccccctc---
tgcggggggcggac--gggcgcccgcccgcc-gggggcgcggc---gcgg-ccgctccct
ccc----gccgcgaaccttc-ttt-----gcagtatatttgtat---cgtctgag-c-aa
accacagaatcgttaaaactttc-aacaacggatctcttggttctggcatcgatgaagaa
cgcagcgaactgcgataagtaatgcgaattgcagaattcagcgagccatcgaatctttga
acgcacattgcgcccgccagcattct-ggcgggcatgcctgtccgagcgtcatttcctcc
ctcacgcagcgcgcctgcg---tggtgtt-ggggcg-ttctgcggt--caggcctgcgcc
cagcgcaggccgccg-c-----------agcccccgaaagccagtggcgggccggcagcg
---ggctccgagcgcagtaagcatcac--------gccctcgctctgga-cg-cccccgc
-ctgcgccctg---ccccccag--accggcagacgcgagtct--gcccccttctc---
>Leptographium_truncatum_TOM74_29 Leptographium_truncatum_TOM74.29 714 bp 
-gcgagttca-cagcgactcccaacccgtgagaacctta--ccgcatcctttcc--gaga
gagagcg--cccgttgcctcctgccggg-cggcgtgccct-----ccccccccctct---
gccggggggcggac--gggcgcccgcccgcc-gggggcgcggc---gcgg-ccgctccct
ccc----gccgcgaaccttc-ttt-----gcagtatatttgtat---cgtctgag-c-aa
accacagaatcgttaaaactttc-aacaacggatctcttggttctggcatcgatgaagaa
cgcagcgaactgcgataagtaatgcgaattgcagaattcagcgagccatcgaatctttga
acgcacattgcgcccgccagcattct-ggcgggcatgcctgtccgagcgtcatttcctcc
ctcacgcagcgcgcctgcg---tggtgtt-ggggcg-ttctgcggt--caggcctgcgcc
cagcgcaggccgccg-c-----------agcccccgaaagccagtggcgggccggcagcg
---ggctccgagcgcagtaagcatcac--------gccctcgctctgga-cg-cccccgc
-ctgcgccctg---ccccccag--accggcagacgcgagtct--gcccccttctc---
>Leptographium_truncatum_TOM86_30 Leptographium_truncatum_TOM86.30 714 bp 
-gcgagttca-cagcgactcccaacccgtgagaacctta--ccgcatcctttct--gaga
gagagcg--cccgttgcctcctgccggg-cggcgtgccct-----ccccccccctct---
gcggggggcgggac--gggcgcccgcccgcc-gggggcgcggc---gcgg-ccgctccct
ccc----accgcgaaccttc-ttt-----gcagtatatttgtat---cgtctgag-c-aa
accacagaatcgttaaaactttc-aacaacggatctcttggttctggcatcgatgaagaa
cgcagcgaactgcgataagtaatgcgaattgcagaattcagcgagccatcgaatctttga
acgcacattgcgcccgccagcattct-ggcgggcatgcctgtccgagcgtcatttcctcc
ctcacgcagcgcgcctgcg---tggtgtt-ggggcg-ttctgcggt--caggcctgcgcc
cagcgtaggccgccg-c-----------agcccccgaaagccagtggcgggccggcagcg
---ggctccgagcgcagtaagcatcac--------gccctcgctctgga-cg-cccccgc
-ctgcgccctg---ccccccat--accggcagacgcgagtct--gcccccttctc---
>Leptographium_wingfieldii_CBS645_89 Leptographium_wingfieldii_CBS645.89 714 bp 
-gcgagttca-cagtgactcccaacccgtgcaaacctta--ccgcatcctttct--gaga
gagagcg--cccgttgcttcctgccggg-cggcgtgccctcct-cccctccctctgc---
ggggggggttggac--gggcgcccgcccgcc-gggggtgcggc---gcgg-ccgctccct
ctc----gccgcgaaccttc-ttt-----gcagtataattgtat---cgtctgag-caaa
accacagaatcgttaaaactttc-aacaacggatctcttggttctggcatcgatgaagaa
cgcagcgaactgcgataagtaatgcgaattgcagaattcagcgagccatcgaatctttga
acgcacattgcgcccgccagcattct-ggcgggcatgcctgtccgagcgtcatttcctcc
ctcacgcagcgcgcctgcg---tggtgtt-ggggtg-ttctgcggc--caggcctgcgcc
cagcgcaggccgccg-c-----------agcccccgaaagccagtggcgggccggcagcg
---ggctccgagcgcagtaagcatcac--------gccctcgctctgga-cg-ctcccgc
-ctgcgccctg---ccccacag--accggcagacgcgagtct--gcctccttctc---
>Leptographium_wingfieldii_CBS648_89 Leptographium_wingfieldii_CBS648.89 714 bp 
-gcgagttca-cagtgactcccaacccgtgcaaacctta--ccgcatcctttct--gaga
gagagcg--cccgttgcttcctgccggg-cggcgtgccctcct-cccctccctctgc---
ggggggggttggac--gggcgcccgcccgcc-gggggtgcggc---gcgg-ccgctccct
ctc----gccgcgaaccttc-ttt-----gcagtataattgtat---cgtctgag-caaa
accacagaatcgttaaaactttc-aacaacggatctcttggttctggcatcgatgaagaa
cgcagcgaactgcgataagtaatgcgaattgcagaattcagcgagccatcgaatctttga
acgcacattgcgcccgccagcattctgggcgggcatgcctgtccgagcgtcatttcctcc
ctcacgcagcgcgcctgcg---tggtgtt-ggggtg-ttctgcggc--caggcctgcgcc
cagcgcaggccgccgcc-----------agcccccgaaagccagtggcgggccggcagcg
---ggctccgagcgcagtaagcatcac--------gccctcgctctgga-cg-ctcccgc
-ctgcgccctg---ccccacag--accggcagacgcgagtct--gcctccttctc---
>Leptographium_wingfieldii_MCC125 Leptographium_wingfieldii_MCC125 714 bp 
-gcgagttca-cagtgactcccaacccgtgcaaacctta--ccgcatcctttct--gaga
gagagcg--cccgttgcttcctgccggg-cggcgtgccctcctccccccccctctgcggg
ggggggggttggac--gggcgcccgcccgcc-gggggtgcggc---gcgg-ccgctccct
ctc----gccgcgaaccttc-ttt-----gcagtataattgtat---cgtctgag-caaa
accacagaatcgttaaaactttc-aacaacggatctcttggttctggcatcgatgaagaa
cgcagcgaactgcgataagtaatgcgaattgcagaattcagcgagccatcgaatctttga
acgcacattgcgcccgccagcattct-ggcgggcatgcctgtccgagcgtcatttcctcc
ctcacgcagcgcgcctgcg---tggtgtt-ggggcg-ttctgcggc--caggcctgcgcc
cagcgcaggccgccg-c-----------agcccccgaaagccagtggcgggccggcagcg
---ggctccgagcgcagtaagcatcac--------gccctcgctctgga-cg-ctcccgc
-ctgcgccctg---ccccacag--accggcagacgcgagtct--gcctccttctc---
>Leptographium_wingfieldii_MCC130 Leptographium_wingfieldii_MCC130 714 bp 
-gcgagttca-cagtgactcccaacccgtgcaaacctta--ccgcatcctttct--gaga
gagagcg--cccgttgcttcctgccggg-cggcgtgccctcct-cccccccccctctgcg
ggggggggttggac--gggcgcccgcccgcc-gggggtgcggc---gcgg-ccgctccct
ctc----gccgcgaaccttc-ttt-----gcagtataattgtat---cgtctgaa-caaa
accacagaatcgttaaaactttc-aacaacggatctcttggttctggcatcaatgaaaaa
cgcagcgaactgcgataagtaatgcgaattgcaaaattcagcgagccatcgaatctttga
acgcacattgcgcccgccagcattct-ggcgggcatgcctgtccgagcgtcatttcctcc
ctcacgcagcgcgcctgcg---tggtgtt-ggggtg-ttctgcggc--caggcctgcgcc
cagcgcaggccgccg-c-----------agcccccgaaagccagtggcgggccggcagcg
---ggctccgagcgcagtaagcatcac--------gccctcgctctgga-cg-ctcccgc
-ctgcgccctg---ccccacag--accggcagacgcgagtct--gcctccttctc---
>Leptographium_wingfieldii_MCC349 Leptographium_wingfieldii_MCC349 714 bp 
-gcgagttca-cagtgactcccaacccgtgcaaacctta--ccgcatcctttct--gaga
gagagcg--cccgttgcttcctgccggg-cggcgtgccctcct-cccctccctctgc---
ggggggggttggac--gggcgcccgcccgcc-gggggtgcggc---gcgg-ccgctccct
ctc----gccgcgaaccttc-ttt-----gcagtataattgtat---cgtctgag-caaa
accacagaatcgttaaaactttcaaacaacggatctcttggttct-gcatcgatgaagaa
cgcagcgaactgcgataagt-atgcgaattgcagaattcagcgagccatcgaatctttga
acgcacattgcgcccgccagcattct-ggc--gcatgcctgtccgagcgtcatttcctcc
ctcacgcagcgcgcctgcg---tggtgtt-ggggtg-ttctgcggc--caggcctgcgcc
cagcgcaggccgccg-c-----------agcccccgaaagccagtggcgggccggcagcg
---ggctccgagcgcagtaagcatcac--------gccctcgctctgga-cg-ctcccgc
-ctgcgccctg---ccccacag--accggcagacgcgagtct--gcctccttctc---
>Leptographium_wingfieldii_TOM10_2 Leptographium_wingfieldii_TOM10.2 714 bp 
-gcgagttca-cagtgactcccaacccgtgcaaacctta--ccgcatcctttct--gaga
gagagcg--cccgttgcttcctgccggg-cggcgtgccctcct-cccctccctctgc---
---gggggttggac--gggcgcccgcccgcc-gggggtgcggc---gcgg-ccgctccct
ctc----gccgcgaaccttc-ttt-----gcagtataattgtat---cgtctgag-caaa
accacagaatcgttaaaactttc-aacaacggatctcttggttctggcatcgatgaagaa
cgcagcgaactgcgataagtaatgcgaattgcagaattcagcgagccatcgaatctttga
acgcacattgcgcccgccagcattct-ggcgggcatgcctgtccgagcgtcatttcctcc
ctcacgcagcgcgcctgcg---tggtgtt-ggggtg-ttctgcggc--caggcctgcgcc
cagcgcaggccgccg-c-----------agcccccgaaagccagtggcgggccggcagcg
---ggctccgagcgcagtaagcatcac--------gccctcgctctgga-cg-ctcccgc
-ctgcgccctg---ccccacag--accggcagacgcgagtct--gcctccttctc---
>Leptographium_wingfieldii_TOM11_5 Leptographium_wingfieldii_TOM11.5 714 bp 
-gcgagttca-cagtgactcccaacccgtgcaaacctta--ccgcatcctttct--gaga
gagagcg--cccgttgcttcctgccggg-cggcgtgccctcct-cccctccctctgc---
---gggggttggac--gggcgcccgcccgcc-gggggtgcggc---gcgg-ccgctccct
ctc----gccgcgaaccttc-ttt-----gcagtataattgtat---cgtctgag-caaa
accacagaatcgttaaaactttc-aacaacggatctcttggttctggcatcgatgaagaa
cgcagcgaactgcgataagtaatgcgaattgcagaattcagcgagccatcgaatctttga
acgcacattgcgcccgccagcattct-ggcgggcatgcctgtccgagcgtcatttcctcc
ctcacgcagcgcgcctgcg---tggtgtt-ggggtg-ttctgcggc--caggcctgcgcc
cagcgcaggccgccg-c-----------cacccccgaaagccagtggcgggccggcagcg
---ggctccgagcgcagtaagcatcac--------gccctcgctctgga-cg-ctcccgc
-ctgcgccctg---ccccacag--accggcagacgcgagtct--gcctccttctc---
>Leptographium_wingfieldii_TOM59_21 Leptographium_wingfieldii_TOM59.21 714 bp 
-gcgagttca-cagtgactcccaacccgtgcaaacctta--ccgcatcctttct--gaga
gagagcg--cccgttgcttcctgccggg-cggcgtgccctcct-cccctccctctgc---
---gggggttggac--gggcgcccgcccgcc-gggggtgcggc---gcgg-ccgctccct
ctc----gccgcgaaccttc-ttt-----gcagtataattgtat---cgtctgag-caaa
accacagaatcgttaaaactttc-aacaacggatctcttggttctggcatcgatgaagaa
cgcagcgaactgcgataagtaatgcgaattgcagaattcagcgagccatcgaatctttga
acgcacattgcgcccgccagcattct-ggcgggcatgcctgtccgagcgtcatttcctcc
ctcacgcagcgcgcctgcg---tggtgtt-ggggtg-ttctgcggc--caggcctgcgcc
cagcgcaggccgccg-c-----------aacccccgaaagccagtggcgggccggcagcg
---ggctccgagcgcagtaagcatcac--------gccctcgctctgga-cg-ctcccgc
-ctgcgccctg---ccccacag--accggcagacgcgagtct--gcctccttctc---
>Leptographium_wingfieldii_WIN_M_1218 Leptographium_wingfieldii_WIN.M.1218 714 bp 
-gcgagttca-cagtgactcccaacccgtgcaaacctta--ccgcatcctttct--gaga
gagagcgcccccgttgctttctgccggg-cggcgtgccctcctccctccccctctgca-g
ggggggggttggac--gggcgcccgcccgcc-gggggcgcggc---gcgg-ccgctccct
ctc----gccgcgaaccttc-ttt-----gcagtataattgtat---cgtctgag-caaa
accacagaatcgttaaaactttc-aacaacggatctcttggttctggcatcgatgaagaa
cgcagcgaactgcgataagtaatgcgaattgcagaattcagcgagccatcgaatctttga
acgcacattgcgcccgccagcattct-ggcgggcatgcctgtccgagcgtcatttcctcc
ctcacgcagcgcgcctgcg---tggtgtt-ggggcg-ttctgcggc--caggcctgcgcc
cagcgcaggccgccg-c-----------agcccccgaaagccagtggcgggccggcagcg
---ggctccgagcgcagtaagcatcac--------gccctcgctctgga-cg-ctcccgc
-ctgcgccctg---tcccacag--accggcagacgcgagtct--gcctccttctc---
>Leptographium_wingfieldii_WIN_M_1322 Leptographium_wingfieldii_WIN.M.1322 714 bp 
-gcgagttca-cagtgactcccaacccgtgcaaacctta--ccgcatcctttct--gaga
gagagcg--cccgttgcttcctgccggg-cggcgtgccctcctccccccccctctgc-gg
ggggggggttggac--gggcgcccgcccgcc-gggggtgcggc---gcgg-ccgctccct
ctc----gccgcgaaccttc-ttt-----gcagtataattgtat---cgtctgag-caaa
accacagaatcgttaaaactttc-aacaacggatctcttggttctggcatcgatgaagaa
cgcagcgaactgcgataagtaatgcgaattgcagaattcagcgagccatcgaatctttga
acgcacattgcgcccgccagcattct-ggcgggcatgcctgtccgagcgtcatttcctcc
ctcacgcagcgcgcctgcg---tggtgtt-ggggtg-ttctgcggc--caggcctgcgcc
cagcgcaggccgccg-c-----------agcccccgaaagccagtggcgggccggcagcg
---ggctccgagcgcagtaagcatcac--------gccctcgctctgga-cg-ctcccgc
-ctgcgccctg---ccccacag--accggcagacgcgagtct--gcctccttctt---
>Leptographium_wingfieldii_WIN_M_1382 Leptographium_wingfieldii_WIN.M.1382 714 bp 
-gcgagttca-cagtgactcccaacccgtgcaaacctta--ccgcatcctttct--gaga
gagagcg--cccgttgcttcctgccggg-cggcgtgccctcctccccccccctctgc--g
ggggggggttggac--aggcgcccgcccgcc-gggggtgcggc---gcgg-ccgctccct
ctc----gccgcgaaccttc-ttt-----gcagtataattgtat---cgtctgag-caaa
accacagaatcgttaaaactttc-aacaacggatctcttggttctggcatcgatgaagaa
cgcagcgaactgcgataagtaatgcgaattgcagaattcagcgagccatcgaatctttga
acgcacattgcgcccgccagcattct-ggcgggcatgcctgtccgagcgtcatttcctcc
ctcacgcagcgcgcctgcg---tggtgtt-ggggcg-ttctgcggc--caggcctgcgcc
cagcgcaggccgccg-c-----------agcccccgaaagccagtggcgggccggcagcg
---ggctccgagcgcagtaagcatcac--------gccctcgctctgga-cg-ctcccgc
-ctgcgccctg---ccccacag--accggcagacgcgagtct--gcctccttctc---
>Leptographium_wingfieldii_WIN_M_1482 Leptographium_wingfieldii_WIN.M.1482 714 bp 
-gcgagttca-cagtgactcccaacccgtgcaaacctta--ccgcatcctttct--gaga
gagagcg--cccgttgcttcctgccggg-cggcgtgccctcct-cccctccctctgc-gg
ggggggggttggac--gggcgcccgcccgcc-gggggtgcggc---gcgg-ccgctccct
ctc----gccgcgaaccttc-ttt-----gcagtataattgtat---cgtctgag-caaa
accacagaatcgttaaaactttc-aacaacggatctcttggttctggcatcgatgaagaa
cgcagcgaactgcgataagtaatgcgaattgcagaattcagcgagccatcgaatctttga
acgcacattgcgcccgccagcattct-ggcgggcatgcctgtccgagcgtcatttcctcc
ctcacgcagcgcgcctgcg---tggtgtt-ggggtg-ttctgcggc--caggcctgcgcc
cagcgcaggccgccg-c-----------agcccccgaaagccagtggcgggccggcagcg
---ggctccgagcgcagtaagcatcac--------gccctcgctctgga-cg-ctcccgc
-ctgcgccctg---ccccacag--accggcagacgcgagtct--gcctccttctc---
>Ophiostoma_brevicolle_CBS159_78 Ophiostoma_brevicolle_CBS159.78 714 bp 
-gcgagttca-aagtgactcccaacccgtgccaactta---ccgcgccctggtctccagg
gcgc-----attgttgcctcctggcagg-cgctgccggcacct-----------------
---------tgc-gtgctag-aaggcttgcc-gggggcgcact-----------------
------------gaaccttc-tttgtagtatagtac-----------cgtctgag--aca
accacagaatcgtaaaaactttc-aacaacggatctcttggttctggcatcgatgaagaa
cgcagcgaactgcgataagtaatgcgaattgcagaattcagcgagccatcgaatctttga
acgcacattgcgcccgccagcattct-ggcgggcatgcctgtccgagcgtcatttcctcc
ctcatgcggc-ctttcgcg---tggtgtt-ggggcg-atctgcaac--caggccctacag
cgatgtaggg-cccggcgc---------agcccctgaaagcgagtggcgggccggcagtg
---gtctccgagcgcagtaagcatctt------tgcctctcgctctgga-ta-acgctgc
-ctgcgccctg----cctt--a-----tgcagacgcaagtctatctca----------
>Pesotum_sp_WIN_M_1423 714 bp 
-gcgagttcacaagtgactcccaacccgtgccaactta---ccgcgccctggtctccagg
gcgc-----actgttgcctcctggcggg-cgccgtcggcacct-----------------
---------tgcggtgcggg-cgtgcctgcc-gggggcgcacc-----------------
------------gaaccttc-tttgcagtattatac-----------cgtctgag-aaaa
accacagaatcgtaaaaactttc-aacaacggatctcttggttctggcatcgatgaagaa
cgcagcgaactgcgataagtaatgcgaattgcagaattcagcgagccatcgaatctttga
acgcacattgcgcccgccagtattct-ggcgggcatgcctgtccgagcgtcatttcctcc
ctcacgcggc-ctctcgcg---tggtgtt-ggggcg-atctgcgac--cggtcgctgcag
cgatgcggcg-tccggcgc---------agcccctcaaagcaagtggcgggccggcagcg
---gtctccgagcgcagtaagcatttt------tgcctctcgctctgga-cg-atgctgc
-ctgcgccctg----cccccaa-----tgcagacgcaagtctatctca----------
>Pesotum_sp_WIN_M_1428 714 bp 
-gcgagttcacaagtgactcccaacccgtgccaactta---ccgcgccctggtctccagg
gcgc-----actgttgcctcctggcggg-cgccgtcggcacct-----------------
---------tgcggtgcggg-cgtgcctgcc-gggggcgcacc-----------------
------------gaaccttc-tttgcagtattgtac-----------cgtctgag-aaaa
accacagaatcgtaaaaactttc-aacaacggatctcttggttctggcatcgatgaagaa
cgcagcgaactgcgataagtaatgcgaattgcagaattcagcgagccatcgaatctttga
acgcacattgcgcccgccagtattct-ggcgggcatgcctgtccgagcgtcatttcctcc
ctcacgcggc-ctttcgcg---tggtgtt-ggggcg-atctgcgac--cggtcgctgcag
cgatgcggcg-tccggcgc---------agcccctcaaagcaagtggcgggccggcagcg
---gtctccgagcgcagtaagcatttt------tgcctctcgctctgga-cg-atgctgc
-ctgcgccctg----cccccaa-----tgcagacgcaagtctatctca----------
>Pesotum_sp_WIN_M_478 714 bp 
-gcgagttcacaagtgactcccaacccgtgccaactta---ccgcgccctggtctccagg
gcgc-----actgttgcctcctggcggg-cgccgtcggcacct-----------------
---------tgcggtgcggg-cgtgcctgcc-gggggcgcacc-----------------
------------gaaccttc-tttgcagtattatac-----------cgtctgag-aaaa
accacagaatcgtaaaaactttc-aacaacggatctcttggttctggcatcgatgaagaa
cgcagcgaactgcgataagtaatgcgaattgcagaattcagcgagccatcgaatctttga
acgcacattgcgcccgccagtattct-ggcgggcatgcctgtccgagcgtcatttcctcc
ctcacgcggc-ctttcgcg---tggtgtt-ggggcg-atctgcgac--cggtcgctgcag
cgatgcggcg-tccggcgc---------agcccctcaaagcaagtggcgggccggcagcg
---gtctccgagcgcagtaagcatttt------tgcctctcgctctgga-cg-atgctgc
-ctgcgccctg----cccccaa-----tgcagacgcaagtctatctca----------
>Pesotum_sp_WIN_M_481 714 bp 
-ctgagttc--cagcaactcccaacccgtgcaaacata---ccgcatcttcc--------
---agcg--cccgttgcctcccggcggg-cggcgccctccctc-----------------
-------------tgggggggaccgcccgcc-gggggctgcgc-----------------
------------ggccgttc-cagaacgcattgcagtctttagtgcctgtctgag--cag
accacagaatcgttaaaactttc-aacaacggatctcttggttctggcatcgatgaagaa
cgcagcgaactgcgataagtaatgtgaattgcagaattcagcgaaccatcgaatctttga
acgcacattgcgcccgccagcattct-ggcgggcatgcctgtccgagcgtcatttccacc
ctcacgcgccccggc-gcg---tggtgtt-ggggca-tgctgcggc--------------
ggccgcgaggccccg-c-----------aggcccctaaagccagtggcgggccggcagcg
---ggctccgagcgcagtaagcagaaa-------cgccctcgctctgga-cg-cccccgc
-cggctccc-----gcctacag-------cggaagctgacccccatcgc---------
