>Batcheloromyces_eucalypti 700 bp 
------------------------------------------------------------
--------------------------------------------------------tcca
taaggtgaacctgcgaagggatcataaca-aaatga--gggg-gta--agccc-------
ga---cctcaaaccctttgtgtc-ccaac---catgttgcctcaggggtaaacaggcc-c
a-------gagccg-gggcccccggtggacccc------caactttatatct--ttgc-g
tctgagc----aacggaaaaccaatcaatcaaaactttcaacaacggatctcttggttct
ggcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaa
tcatcgaatctttgaacgcatattgcgccctctggcattccggagggcatgcctgttcga
gcgtcatttcaccactccagc-cccgctggg-tcttgggcg-ctgcg----gcct-----
gcc---cgcgcgcctcaaagtct-c--cggccgagccg-accgtctcca-agcgttgtga
ccataacgggttcgcttccgggaccaggtccggcgccgcgccgtgaaaaccttc--cgca
aaaggttaacatcggatcaggtagggata---------------------
>Cladosporium_sphaerospermum 700 bp 
------------------------------------------------------------
------------------------------------------------------------
----------------agggatcattac--aagtga-------cccccggctccggccgg
ggatgttcataaccctttgttgt-ccgac---tctgttgcctccggggcgaccctgcctt
t----tcacgggcgggggccccgggtggac--acatcaaaactcttgcgtaactttgcag
tctgagt-----aaatttaattaataaattaaaactttcaacaacggatctcttggttct
ggcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaa
tcatcgaatctttgaacgcacattgcgccccctggtattccggggggcatgcctgttcga
gcgtcatttcaccactcaagc-ctcgcttgg-tattgggcg-acgcg-------------
gtccgccgcgcgcctcaaatcga-c--cggctgggtct-tctgtcccctcagcgttgtgg
----aaactattcgctaaagggtgc-cacgggaggccacgccgaaaaacaaacccatttc
taaggttgacctcggatcaggtagg-------------------------
>Mycosphaerella_ellipsoidea 700 bp 
------------------------------------------------------------
------------------------------------------------------------
------gaacctgcggagggatcattact-gagtga--gggc-tca--cgccc-------
ga---cctccaaccctttgtgaa-ccaac---tctgttgcttcgggggcgaccccgccgt
t---tcggcgac--ggcgcccccggagg----tcatc--aaacactgcatct--ttgc-g
tcggagtc---ttaaagtaaat--ttaaacaaaactttcaacaacggatctcttggttct
ggcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaa
tcatcgaatctttgaacgcacattgcgccccgtggtattccgcggggcatgcctgttcga
gcgtcatttcaccactcaagc-ctagcttgg-tattgggcg-tcgcg----g--------
ttc---cgcgcgccttaaagtct-c--cggctgagcag-ttcgtctcta-agcgttgtgg
--cata-tatttcgctgaagagtt--cggacggcttttggccgttaaatctttc--tt--
-aaggttgacctcggatcaggtagggata---------------------
>Mycosphaerella_gracilis_DQ302960 Mycosphaerella_gracilis_DQ302960 700 bp 
------------------------------------------------------------
------------------------------------------------------------
---ggtgaacctgcggagggatcattact-gagtga--gggc-tca--cgccc-------
ga---cctccaaccctttgtgaa-cacat---cttgttgcttcgggggcgaccctgccgg
c-actacgtcgccgggcgcccccggagg----tctcc--aaacactgcatct--ttgc-g
tcggagt----tt-aaacaaat--taaac-aaaactttcaacaacggatctcttggttct
ggcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaa
tcatcgaatctttgaacgcacattgcgccctttggtattccgaagggcatgcctgttcga
gcgtcatttcaccactcaagc-ctggcttgg-tattgggcg-tcgcg----g--------
ctc---cgcgcgccttaaagtct-c--cggctgagcca-ttcgtctcta-agcgttgtgg
attttc-taattcgcttcggagtg--cgggtggc-cgcggccgttaaatcttt---attg
aaaggttgacctcggatcaggtagg-------------------------
>Mycosphaerella_heimii_AF309606 700 bp 
------------------------------------------------------------
---------------------------------------------------------tcc
gtaggtgaacctgcggagggatcattact-gagtga--gggc-ta---ggtcc-------
ga---cctccaaccctttgtgaa-cc-aa--acttgttgcttcgggggcgaccctgccgc
t---tgggcggtgcggcgcccccggagg----ccatt--aaacactgcatca--ttgc-g
tcggagt----aa-aagtaaat--taaac-aaaactttcaacaacggatctcttggttcc
agcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaa
tcatcgaatctttgaacgcacattgcgccctctggtattccggggggcatgcctgttcga
gcgtcatttcaccactcaagc-ctggcttgg-tattgggcg-tcgcg----g--------
ctc---cgcgcgccttaaagtcttc--cggctgagctg-tccgtctcta-agcgttgtgg
---caa-ctattcgcttcggaggt--cgggtggc-cgcggccgttaaatctttc--ac--
-aaggttgacctcggatcaggtagggata---------------------
>Mycosphaerella_heimii_TH004C 700 bp 
--------------gtgaggccttcggactggcccagggaggtcggcaacgaccacccag
ggccggaaagttggtcaaactcggtcatttagaggaagtaaaagtcgtaacaaggtctcc
gtaggtgaacctgcggagggatcattact-gagtga--gggc-tac--ggtcc-------
ga---cctccaaccctttgtgaa-ccaaa--acttgttgcttcgggggcgaccctgccgc
t---tcggcggtgcggcgcccccggagg----ccatt--aaacactgcatca--ttgc-g
tcggagt----aa-aagtaaat--taaac-aaaactttcaacaacggatctcttggttcc
agcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaa
tcatcgaatctttgaacgcacattgcgccctctggtattccggggggcatgcctgttcga
gcgtcatttcaccactcaagc-ctggcttgg-tattgggcg-tcgcg----g--------
ctc---cgcgcgccttaaagtcttc--cggctgagctg-tccgtctcta-agcgttgtgg
---caa-ctattcgcttcggaggt--cgggtggc-cgcggccgttaaatctttc--ac--
-aaggttgacctcggatcaggtagggatacccgctgaacttaagcatatc
>Mycosphaerella_heimii_TH004D 700 bp 
gattgaatggctcagtgaggccttcggactggcccagggaggtcggcaacgaccacccag
ggccggaaagttggtcaaactcggtcatttagaggaagtaaaagtcgtaacaaggtctcc
gtaggtgaacctgcggagggatcattact-gagtga--gggc-tac--ggtcc-------
ga---cctccaaccctttgtgaa-cc--a--acttgttgcttcgggggcgaccctgccgc
t---tcggcggtgcggcgcccccggagg----ccatt--aaacactgcatca--ttgc-g
tcggagt----aa-aagtaaat--taaac-aaaactttcaacaacggatctcttggttcc
agcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaa
tcatcgaatctttgaacgcacattgcgccctctggtattccggggggcatgcctgttcga
gcgtcatttcaccactcaagc-ctggcttgg-tattgggcg-tcgcg----g--------
ctc---cgcgcgccttaaagtcttc--cggctgagctg-tccgtctcta-agcgttgtgg
---caa-ctattcgcttcggaggt--cgggtggc-cgcggccgttaaatctttc--ac--
-aaggttgacctcggatcaggtagggatacccgctgaacttaagcatatc
>Mycosphaerella_heimii_TH089 700 bp 
gattgaatggctcagtgaggccttcggactggcccagggaggtcggcaacgaccacccag
ggccggaaagttggtcaaactcggtcatttagaggaagtaaaagtcgtaacaaggtctcc
gtaggtgaacctgcggagggatcattact-gagtga--gggc-tac--ggtcc-------
ga---cctccaaccctttgtgaa-cc-aa--acttgttgcttcgggggcgaccctgccgc
t---tcggcggtgcggcgcccccggagg----ccatt--aaacactgcatca--ttgc-g
tcggagt----aa-aagtaaat--taaac-aaaactttcaacaacggatctcttggttcc
agcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaa
tcatcgaatctttgaacgcacattgcgccctctggtattccggggggcatgcctgttcga
gcgtcatttcaccactcaagc-ctggcttgg-tattgggcg-tcgcg----g--------
ctc---cgcgcgccttaaagtcttc--cggctgagctg-tccgtctcta-agcgttgtgg
---caa-ctattcgcttcggaggt--cgggtggc-cgcggccgttaaatctttc--ac--
-aaggttgacctcggatcaggtagggatacccgctgaacttaagcatatc
>Mycosphaerella_irregulari_TH003 Mycosphaerella_irregulari_TH003 700 bp 
gattgaatggctcagtgaggccttcggactggcccagggaggtcggcaacgaccacccag
ggccggaaagttggtcaaactcggtcatttagaggaagtaaaagtcgtaacaaggtctcc
gtaggtgaacctgcggagggatcattacc-gagtga--gggc--ccccggccc-------
ga---cctccaaccctttgtgaactcaca--tctcgttgcttcgggggcgaccctgccgt
t---cgcggc-cgcggcgcccccggggg----atact--taacactgcatca--ttgc-g
tcggagtct--tttatgtaaatcatgaac-aaaactttcaacaacggatctcttggttct
ggcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaa
tcatcgaatctttgaacgcacattgcgccccgtggtattccgcggggcatgcctgttcga
gcgtcatttcaccactcgagt-ctgactcgg-tattgggcg-ccgcg----cact-----
gcc----gcgcgcctcaaagttt-c--cggctgggcggacccgtccccg-agcgttgtgg
catcacagttctcgcctgggagtcgcgggttggcttgcggccgttaaacacacc--catc
aaaggttgacctcggatcaggtagggatacccgctgaacttaagcatatc
>Mycosphaerella_irregulari_TH003_2 Mycosphaerella_irregulari_TH003.2 700 bp 
gattgaatggctcagtgaggccttcggactggcccagggaggtcggcaacgaccacccag
ggccggaaagttggtcaaactcggtcatttagaggaagtaaaagtcgtaacaaggtctcc
gtaggtgaacctgcggagggatcattacc-gagtga--gggc--ccccggccc-------
ga---cctccaaccctttgtgaactcaca--tctcgttgcttcgggggcgaccctgccgt
t---cgcggc-cgcggcgcccccggggg----atact--taacactgcatca--ttgc-g
tcggagtct--tttatgtaaatcatgaac-aaaactttcaacaacggatctcttggttct
ggcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaa
tcatcgaatctttgaacgcacattgcgccccgtggtattccgcggggcatgcctgttcga
gcgtcatttcaccactcgagt-ctgactcgg-tattgggcg-ccgcg----cact-----
gcc----gcgcgcctcaaagttt-c--cggctgggcggacccgtccccg-agcgttgtgg
catcacagttctcgcctgggagtcgcgggttggcttgcggccgttaaacacacc--catc
aaaggttgacctcggatcaggtagggatacccgctgaacttaagcatatc
>Mycosphaerella_irregulari_TH003_3 Mycosphaerella_irregulari_TH003.3 700 bp 
gattgaatggctcagtgaggccttcggactggcccagggaggtcggcaacgaccacccag
ggccggaaagttggtcaaactcggtcatttagaggaagtaaaagtcgtaacaaggtctcc
gtaggtgaacctgcggagggatcattacc-gagtga--gggc--ccccggccc-------
ga---cctccaaccctttgtgaactcaca--tctcgttgcttcgggggcgaccctgccgt
t---cgcggc-cgcggcgcccccggggg----atact--taacactgcatca--ttgc-g
tcggagtct--tttatgtaaatcatgaac-aaaactttcaacaacggatctcttggttct
ggcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaa
tcatcgaatctttgaacgcacattgcgccccgtggtattccgcggggcatgcctgttcga
gcgtcatttcaccactcgagt-ctgactcgg-tattgggcg-ccgcg----cact-----
gcc----gcgcgcctcaaagttt-c--cggctgggcggacccgtccccg-agcgttgtgg
catcacagttctcgcctgggagtcgcgggttggcttgcggccgttaaacacacc--catc
aaaggttgacctcggatcaggtaggg------------------------
>Mycosphaerella_irregulari_TH004A Mycosphaerella_irregulari_TH004A 700 bp 
gattgaatggctcagtgaggccttcggactggcccagggaggtcggcaacgaccacccag
ggccggaaagttggtcaaactcggtcatttagaggaagtaaaagtcgtaacaaggtctcc
gtaggtgaacctgcggagggatcattacc-gagtga--gggc--ccccggccc-------
ga---cctccaaccctttgtgaactcaca--tctcgttgcttcgggggcgaccctgccgt
t---cgcggcacgcggcgcccccggggg----atact--taacactgcatca--ttgc-g
tcggagtct--tttatgtaaatcataaac-aaaactttcaacaacggatctcttggttct
ggcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaa
tcatcgaatctttgaacgcacattgcgccccgtggtattccgcggggcatgcctgttcga
gcgtcatttcaccactcgagt-ctgactcgg-tattgggcg-tcgcg----cacc-----
gcc----gcgcgcctcaaagttt-c--cggctgggcggacccgtccccg-agcgttgtgg
catcacagttctcgcctgggagtcgcgggttggcttgcggccgttaaacacacc--catc
aaaggttgacctcggatcaggtagggatacccgctgaacttaagcatatc
>Mycosphaerella_irregulari_TH019 Mycosphaerella_irregulari_TH019 700 bp 
gattgaatggctcagtgaggccttcggactggcccagggaggtcggcaacgaccacccag
ggccggaaagttggtcaaactcggtcatttagaggaagtaaaagtcgtaacaaggtctcc
gtaggtgaacctgcggagggatcattacc-gagtga--gggc--ccccggccc-------
ga---cctccaaccctttgtgaa-tcaca--tctcgttgcttcgggggcgaccctgccgt
t---cgcggcacgcggcgcccccggggg----atact--caacactgcatca--ttgc-g
tcggagtc---tttatgtaaatcataaac-aaaactttcaacaacggatctcttggttct
ggcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaa
tcatcgaatctttgaacgcacattgcgccccgtggtattccgcggggcatgcctgttcga
gcgtcatttcaccactcgagt-ctgactcgg-tattgggcg-ccgcg----cacc-----
gcc----gcgcgcctcaaagttt-c--cggctgggcggacccgtccccg-agcgttgtgg
catcacagttctcgcctgggagtcgcgggttggcttgcggccgttaaacacccc--catc
aaaggttgacctcggatcaggtagggatacccgctgaacttaagcatatc
>Mycosphaerella_konae 700 bp 
-----------------------tcggactggcccagggaggtcggcaacgaccacccag
ggccggaaagttggtcaaactcggtcatttagaggaagtaaaagtcgtaacaaggtctcc
gtaggtgaacctgcggagggatcattact-gagtga--gggc-tac--ggtcc-------
ga---cctccaaccctttgtgaa-cc-ga--acttgttgcttcgggggcgaccctgccgc
t---tcggcggtgcggcgcccccggagg----ccatt--aaacactgcatca--ttgc-g
tcggagt----aa-aagtaaat--taaac-aaaactttcaacaacggatctcttggttcc
agcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaa
tcatcgaatctttgaacgcacattgcgccctctggtattccggggggcatgcctgttcga
gcgtcatttcaccactcaagc-ctggcttgg-tattgggcg-tcgcg----g--------
ctc---cgcgcgccttaaagtcttc--cggctgagctg-tccgtctcta-agcgttgtgg
---caa-ctattcgcttcggaggt--cgggtggc-cgcggccgttaaatctttc--ac--
-aaggttgacctcggatcaggtagggata---------------------
>Mycosphaerella_marksii_CPC_13273 Mycosphaerella_marksii_CPC_13273 700 bp 
-attgaatggctcagtgaggccttcggactggcccagggaggtcggcaacgaccacccag
ggccggaaagttggtcaaactcggtcatttagaggaagtaaaagtcgtaacaaggtctcc
gtaggtgaacctgcggagggatcattacc-gagtga--gggt-ttcg--gccc-------
ga---cctccaaccctttgtgaa-tca-a--acctgttgcttcgggggcgaccctgccgt
t---cgcggc-gcg-gcgcccccggggg----agacc--aaacactgcgtcaatttgt-g
tcggagta-----cttgttaa---taaac-aaaactttcaacaacggatctcttggttct
ggcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaa
tcatcgaatctttgaacgcacattgcgccccgtggtattccgcggggcatgcctgttcga
gcgtcatttcaccactcgagt-ctgactcgg-tattgggcg-ccgcg----tttc-----
gat----gcgcgccttaaagttt-c--cggctggaccg-tccgtctccg-agcgttgtgg
catc---tgtctcgctagggagtcgcggagggcgtt--ggccgttaaacac-cc--catc
aaaggttgacctcggatcaggtagggatacccgctgaacttaagcatatc
>Mycosphaerella_marksii_CPC_13724 Mycosphaerella_marksii_CPC_13724 700 bp 
------atggctcagtgaggccttcggactggcccagggaggtcggcaacgaccacccag
ggccggaaagttggtcaaactcggtcatttagaggaagtaaaagtcgtaacaaggtctcc
gtaggtgaacctgcggagggatcattacc-gagtga--gggc-ttcg--gccc-------
ga---cctccaaccctctgtgaa-tca-a--acctgttgcttcgggggcgaccctgccgt
t---cgcggc-gcg-gcgcccccggggg----aaatc--aaacactgcgtcaatttgt-g
tcggagta-----cttgttaa---taaac-aaaactttcaacaacggatctcttggttct
ggcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaa
tcatcgaatctttgaacgcacattgcgccccgtggtattccgcggggcatgcctgttcga
gcgtcatttcaccactctagt-ctgactcgg-tattgggcg-tcgcg----tttc-----
gat----gcgcgccttaaagttt-c--cggctggaccg-tccgtctccg-agcgttgtgg
catc---tgtctcgctagggagccgcggagggcgtt--ggccgttaaacac-cc--catc
aaaggttgacctcggatcaggtagggatacccgctgaacttaagcatatc
>Mycosphaerella_marksii_DQ267587 Mycosphaerella_marksii_DQ267587 700 bp 
------------------------------------------------------------
---------------------------------------------------------tcc
gtaggtgaacctgcggagggatcattacc-gagtga--gggt-ttcg--gccc-------
ga---cctccaaccctttgtgaa-tca-a--acctgttgcttcgggggcgaccctgccgt
t---cgcggc-gcg-gcgcccccggggg----aaatc--aaacactgcgtcaatttgt-g
tcggagta-----cttgttaa---taaac-aaaactttcaacaacggatctcttggttct
ggcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaa
tcatcgaatctttgaacgcacattgcgccccgtggtattccgcggggcatgcctgttcga
gcgtcatttcaccactcgagt-ctgactcgg-tattgggcg-tcgcg----tttc-----
gat----gcgcgccttaaagttt-c--cggctggaccg-tccgtctccg-agcgttgtgg
catc---tgtctcgctagggagccgcggagggcgtt--ggccgttaaacac-cc--catc
aaaggttgacctcggatcaggtagggata---------------------
>Mycosphaerella_parkii_AF173311 700 bp 
------------------------------------------------------------
---------------------------------------------------------tcc
gtaggtgaacctgcggagggatcattact-gagtga--gggt-ttcaccgccc-------
ga---cctccaaccctttgtgaa-ccaca--acttgttgcttcgggggcgaccctgccgt
t---cgcggc-atc-gcgcccccggagg----atact--taaccctgcatca--ttgc-g
tcggagta---attttattaa---tacat-aaaactttcaacaacggatctcttggttct
ggcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaa
tcatcgaatctttgaacgcacattgcgccccgtggtattccgcggggcatgcctgttcga
gcgtcatttcaccactcgagt-ctgactcgg-tattgggcg-tcgcg----gctt-----
--ccgccgcgcgcctcaaagtct-c--cggctgggcag-cccgtctccg-agcgttgtgg
catcacagttctcgctagggagtcgcggacggcgtc--ggccgttaaatac-cc--catc
aaaggttgacctcggatcaggtagggata---------------------
>Mycosphaerella_parkii_AY626979 700 bp 
------------------------------------------------------------
------------------------------------------------------------
gtaggtgaacctgcggagggatcattact-gagtga--gggt-ttcaccgccc-------
ga---cctccaaccctttgtgaa-ccaca--acttgttgcttcgggggcgaccctgccgt
t---cgcggc-atc-gcgcccccggagg----atact--taaccctgcatca--ttgc-g
tcggagta---attttattaa---tacat-aaaactttcaacaacggatctcttggttct
ggcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaa
tcatcgaatctttgaacgcacattgcgccccgtggtattccgcggggcatgcctgttcga
gcgtcatttcaccactcgagt-ctgactcgg-tattgggcg-tcgcg----gctt-----
aaccgccgcgcgcctcaaagtct-c--cggctgggcag-cccgtctccg-agcgttgtgg
catcacagttctcgctagggagtcgcgggcggcgtc--ggccgttaaatac-cc--catc
aaaggttgacctcggatcaggtagggatacccgctgaacttaagc-----
>Mycosphaerella_pseudoendophytica_AF173303 Mycosphaerella_pseudoendophytica_AF173303 700 bp 
------------------------------------------------------------
---------------------------------------------------------tcc
gtaggtgaacctgaggagggatcattact-gagtga--gggc-tca--cgccc-------
a-----ttctaaccctttgtgaactacaa--ctctgttgcttcgggggcgaccccgccgt
c-----tcggcggtggcgctcccggtggccaattatt--aaactctgcatct-cctgc-g
tcggagt----cttaaagaaatt-taaac-aaaactttcaacaacggatctcttggttct
ggcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaa
tcatcgaatctttgaacgcacattgcgccccgtggtattccgcggggcatgcctgttcga
gcgtcatttcaccactcaagc-ctagcttgg-tattgggcg-tcgcg----a--c-----
ttcggtcgcgcgccttaaagtct-c--cggctgagcag-tgtgtctccg-agcgttgtga
tac----atattcgctagggatga--caggtctgtcgcggccgttaaatcttt----ata
acaggttgacctcggatcaggtagggata---------------------
>Mycosphaerella_pseudoendophytica_AF468874 Mycosphaerella_pseudoendophytica_AF468874 700 bp 
------------------------------------------------------------
---------------------------------------------------------tcc
cgtagtgaacctgaggagggatcattact-gagtga--gggc-tca--cgccc-------
a-----ttctaaccctttgtgaactacaa--ctctgttgcttcgggggcgaccccgccgt
c-----tcggcggtggcgctcccggtggccaattatt--aaactctgcatct-cttgc-g
tcggagt----cttaaagaaatt-taaac-aaaactttcaacaacggatctcttggttct
ggcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaa
tcatcgaatctttgaacgcacattgcgccccgtggtattccgcggggcatgcctgttcga
gcgtcatttcaccactcaagc-ctagcttgg-tattgggcg-tcgcg----a--c-----
ttcggtcgcgcgccttaaagtct-c--cggctgagcag-tctgtctccg-agcgttgtga
tac----atattcgctagggatga--caggtctgtcgcggccgttaaatcttt----ata
acaggttgacctcggatcaggtagggata---------------------
>Mycosphaerella_pseudomarksii_TH126 Mycosphaerella_pseudomarksii_TH126 700 bp 
gattgaatggctcagtgaggccttcggactggcccagggaggtcggcaacgaccacccag
ggccggaaagttggtcaaactcggtcatttagaggaagtaaaagtcgtaacaaggtctcc
gtaggtgaacctgcggagggatcattacc-gagtga--gggcctctccggccc-------
ga---cctccaaccctttgtgaa--ccag--tcttgttgcttcgggggcgaccctgccgt
t---cgcggttgccggcgcccccggagg----atacg--taacactgcatca--ttgc-g
tcggagtctagattttgtaaatcataaac-aaaactttcaacaacggatctcttggttct
ggcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaa
tcatcgaatctttgaacgcacattgcgccccgtggtattccgcggggcatgcctgttcga
gcgtcatttcaccactcgagt-ctgactcgg-tattgggcg-tcgcg----cact-----
gcc----gcgcgcctcaaagtct-c--cggctgggcggatccgtccccg-agcgttgtgg
cattacacttctcgctagggagtcgcgggttggcttgcggccgttaaacacacc--catc
aaaggttgacctcggatcaggtagggatacccgctgaacttaagcatatc
>Mycosphaerella_pseudomarksii_TH126_1 Mycosphaerella_pseudomarksii_TH126.1 700 bp 
gattgaatggctcagtgaggccttcggactggcccagggaggtcggcaacgaccacccag
ggccggaaagttggtcaaactcggtcatttagaggaagtaaaagtcgtaacaaggtctcc
gtaggtgaacctgcggagggatcattacc-gagtga--gggcctctccggccc-------
ga---cctccaaccctttgtgaa--ccag--tcttgttgcttcgggggcgaccctgccgt
t---cgcggttgccggcgcccccggagg----atacg--taacactgcatca--ttgc-g
tcggagtctagattttgtaaatcataaac-aaaactttcaacaacggatctcttggttct
ggcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaa
tcatcgaatctttgaacgcacattgcgccccgtggtattccgcggggcatgcctgttcga
gcgtcatttcaccactcgagt-ctgactcgg-tattgggcg-tcgcg----cact-----
gcc----gcgcgcctcaaagtct-c--cggctgggcggatccgtccccg-agcgttgtgg
cattacacttctcgctagggagtcgcgggttggcttgcggccgttaaacacacc--catc
aaaggttgacctcggatcaggtagggatacccgctgaacttaagcatatc
>Mycosphaerella_pseudomarksii_TH126_3 Mycosphaerella_pseudomarksii_TH126.3 700 bp 
gattgaatggctcagtgaggccttcggactggcccagggaggtcggcaacgaccacccag
ggccggaaagttggtcaaactcggtcatttagaggaagtaaaagtcgtaacaaggtctcc
gtaggtgaacctgcggagggatcattacc-gagtga--gggcctctccggccc-------
ga---cctccaaccctttgtgaa--ccag--tcttgttgcttcgggggcgaccctgccgt
t---cgcggttgccggcgcccccggagg----atacg--taacactgcatca--ttgc-g
tcggagtctagattttgtaaatcataaac-aaaactttcaacaacggatctcttggttct
ggcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaa
tcatcgaatctttgaacgcacattgcgccccgtggtattccgcggggcatgcctgttcga
gcgtcatttcaccactcgagt-ctgactcgg-tattgggcg-tcgcg----cact-----
gcc----gcgcgcctcaaagtct-c--cggctgggcggatccgtccccg-agcgttgtgg
cattacacttctcgctagggagtcgcgggttggcttgcggccgttaaacacacc--catc
aaaggttgacctcggatcaggtagggatacccgctgaacttaagcatatc
>Mycosphaerella_punctiformis 700 bp 
------------------------------------------------------------
------------------------------------------------------------
----------------agggatcattact-gagtga--gggc-ttcc-ggccc-------
ga---cctccaaccctttgtgaa-cacat---cttgttgcttcgggggcgaccctgccgt
t------cgcggcattc-cccccggagg----tcatca-aaacactgcattc--ttac-g
tcggagt----aaaaagttaat--ttaat-aaaactttcaacaacggatctcttggttct
ggcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaa
tcatcgaatctttgaacgcacattgcgccccctggtattccggggggcatgcctgttcga
gcgtcatttcaccactcaagc-ctcgcttgg-tattgggcg-tcgcg----agtc-----
tct---cgcgcgcctcaaagtct-c--cggctgtgcgg-ttcgtctccc-agcgttgtgg
--caac-tatttcgcagtggagtt--cgagtcgt-cgtggccgttaaatct-t-----tc
aaaggttgacctcggatcagg-----------------------------
>Mycosphaerella_quasiparkii_TH016A Mycosphaerella_quasiparkii_TH016A 700 bp 
gattgaatggctcagtgaggccttcggactggcccagggaggtcggcaacgaccacccag
ggccggaaagttggtcaaactcggtcatttagaggaagtaaaagtcgtaacaaggtctcc
gtaggtgaacctgcggagggatcattact-gagtga--gggc-tca--cgccc-------
ga---cctccaaccctttgtgaa-ccaaa--ctttgttgcttcgggggcgaccctgccat
cga-------gttgggcgcccccggagg----tcatc--aaactctgcatct--ttgc-g
tcggagt----acaagtt-aat--taaac-aaaactttcaacaacggatctcttggttct
ggcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaa
tcatcgaatctttgaacgcacattgcgccctttggtattccgaagggcatgcctgttcga
gcgtcatttcaccactcaagc-ctcgcttgg-tattgggcg-tcgcg----g--------
ttc---cgcgcgccttaaagtct-c--cggctgagctg-tccgtctcta-agcgttgtga
---tac-atattcgcttcggagtg--cgggcggt-cgcggccgttaaacttct----ttc
aaaggttgacctcggatcaggtagggatacccgctgaacttaagcatatc
>Mycosphaerella_quasiparkii_TH016A_2 Mycosphaerella_quasiparkii_TH016A.2 700 bp 
gattgaatggctcagtgaggccttcggactggcccagggaggtcggcaacgaccacccag
ggccggaaagttggtcaaactcggtcatttagaggaagtaaaagtcgtaacaaggtctcc
gtaggtgaacctgcggagggatcattact-gagtga--gggc-tca--cgccc-------
ga---cctccaaccctttgtgaa-ccaaa--ctttgttgcttcgggggcgaccctgccat
cga-------gttgggcgcccccggagg----tcatc--aaactctgcatct--ttgc-g
tcggagt----acaagtt-aat--taaac-aaaactttcaacaacggatctcttggttct
ggcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaa
tcatcgaatctttgaacgcacattgcgccctttggtattccgaagggcatgcctgttcga
gcgtcatttcaccactcaagc-ctcgcttgg-tattgggcg-tcgcg----g--------
ttc---cgcgcgccttaaagtct-c--cggctgagctg-tccgtctcta-agcgttgtga
---tac-atattcgcttcggagtg--cgggcggt-cgcggccgttaaacttct----ttc
aaaggttgacctcggatcaggtagggatacccgctgaacttaagcatatc
>Mycosphaerella_quasiparkii_TH016A_3 Mycosphaerella_quasiparkii_TH016A.3 700 bp 
gattgaatggctcagtgaggccttcggactggcccagggaggtcggcaacgaccacccag
ggccggaaagttggtcaaactcggtcatttagaggaagtaaaagtcgtaacaaggtctcc
gtaggtgaacctgcggagggatcattact-gagtga--gggc-tca--cgccc-------
ga---cctccaaccctttgtgaa-ccaaa--ctttgttgcttcgggggcgaccctgccat
cga-------gttgggcgcccccggagg----tcatc--aaactctgcatct--ttgc-g
tcggagt----acaagtt-aat--taaac-aaaactttcaacaacggatctcttggttct
ggcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaa
tcatcgaatctttgaacgcacattgcgccctttggtattccgaagggcatgcctgttcga
gcgtcatttcaccactcaagc-ctcgcttgg-tattgggcg-tcgcg----g--------
ttc---cgcgcgccttaaagtct-c--cggctgagctg-tccgtctcta-agcgttgtga
---tac-atattcgcttcggagtg--cgggcggt-cgcggccgttaaacttct----ttc
aaaggttgacctcggatcaggtagggatacccgctgaacttaagcatatc
>Mycosphaerella_quasiparkii_TH091A Mycosphaerella_quasiparkii_TH091A 700 bp 
gattgaatggctcagtgaggccttcggactggcccagggaggtcggcaacgaccacccag
ggccggaaagttggtcaaactcggtcatttagaggaagtaaaagtcgtaacaaggtctcc
gtaggtgaacctgcggagggatcattact-gagtga--gggc-tca--cgccc-------
ga---cctccaaccctttgtgaa-ctaaa--ctttgttgcttcgggggcgaccctgccat
cga-------gttgggcgcccccggagg----tcatc--aaactctgcatct--ttgc-g
tcggagt----acaagtt-aat--taaac-aaaactttcaacaacggatctcttggttct
ggcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaa
tcatcgaatctttgaacgcacattgcgccctttggtattccgaagggcatgcctgttcga
gcgtcatttcaccactcaagc-ctagcttgg-tattgggcg-tcgcg----a--------
ttc---cgcgcgccttaaagtct-c--cggctgagctg-tccgtctcta-agcgttgtga
---tac-atattcgcttcggagtg--cgggcggt-cgcggccgttaaacttct----ttc
aaaggttgacctcggatcaggtagggatacccgctgaacttaagcatatc
>Mycosphaerella_rosigena 700 bp 
------------------------------------------------------------
-gccggaaagttggtcaaactcggtcatttagaggaagtaaaagtcgtaacaaggtctcc
gtaggtgaacctgcggagggatcattaaa-gagtga--gggc-ccc-cggtcc-------
ga---cctccaaccctttgtgaa-ctaca--acccgttgcttcgggggcgaccctgccgt
t---cgcggc-gtcggcgcccccggagg----atcat--taacactgcatca--atgc-g
tcggagta---aatcagttaatc-tgaac-aaaactttcaacaacggatctcttggttct
ggcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaa
tcatcgaatctttgaacgcacattgcgccccgtggtattccgcggggcatgcctgttcga
gcgtcatttcaccactcgagt-ctgactcgg-tattgggcg-tcgcg----catt-----
gcc----gcgcgccttaaagtct-c--cggctgggcgg-cccgtctccg-agcgttgtga
catcac-agtttcgctagggagtcgcgggcggcgtt--ggccgttaaatac-cc--catc
aaaggttgacctcggatcaggtagggatacccgctgaacttaagcatatc
>Mycosphaerella_thailandica_AY752156_T Mycosphaerella_thailandica_AY752156_T 700 bp 
------------------------------------------------------------
------------------------------------------------------------
------------------ggatcattact-gagtga--gggc-ctccgggtcc-------
ga---cctccaaccctttgtgaa-cc-aa--tcttgttgcttcgggggcgaccctgccgc
t---tcggcggtgcggcgcccccggagg----ccatc--aaacactgcatca--ttgc-g
tcggagt----aa-aagtaaat--gaaac-aaaactttcaacaacggatctcttggttcc
agcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaa
tcatcgaatctttgaacgcacattgcgccctctggtattccggggggcatgcctgttcga
gcgtcatttcaccactcaagc-ctggcttgg-tattgggcg-tcgcg----g--------
tgc---cgcgcgccttaaagtcttc--cggctgagctg-tccgtctcta-agcgttgtgg
---caa-ctattcgcttcggaggc--cgggcggc-cgcggccgttaaatctttc--ac--
-aaggttgacctcggatcaggtagggata---------------------
>Mycosphaerella_thailandica_EF394848 Mycosphaerella_thailandica_EF394848 700 bp 
-attgaatggctcagtgaggccttcggactggcccagggaggtcggcaacgaccacccag
ggccggaaagttggtcaaactcggtcatttagaggaagtaaaagtcgtaacaaggtctcc
gtaggtgaacctgcggagggatcattact-gagtga--gggc-ctccgggtcc-------
ga---cctccaaccctttgtgaa-cc-aa--tcttgttgcttcgggggcgaccctgccgc
t---tcggcggtgcggcgcccccggagg----ccatc--aaacactgcatca--ttgc-g
tcggagt----aa-aagtaaat--gaaac-aaaactttcaacaacggatctcttggttcc
agcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaa
tcatcgaatctttgaacgcacattgcgccctctggtattccggggggcatgcctgttcga
gcgtcatttcaccactcaagc-ctggcttgg-tattgggcg-tcgcg----g--------
tgc---cgcgcgccttaaagtcttc--cggctgagctg-tccgtctcta-agcgttgtgg
---caa-ctattcgcttcggaggc--cgggcggc-cgcggccgttaaatctttc--ac--
-aaggttgacctcggatcaggtagggata---------------------
>Mycosphaerella_thailandica_TH004B Mycosphaerella_thailandica_TH004B 700 bp 
-attgaatggctcagtgaggccttcggactggcccagggaggtcggcaacgaccacccag
ggccggaaagttggtcaaactcggtcatttagaggaagtaaaagtcgtaacaaggtctcc
gtaggtgaacctgcggagggatcattact-gagtga--gggc-ctccgggtcc-------
ga---cctccaaccctttgtgaa-cc-aa--tcttgttgcttcgggggcgaccctgccgc
t---tcggcggtgcggcgcccccggagg----ccatc--aaacactgcatca--ttgc-g
tcggagt----aa-aagtaaat--gaaac-aaaactttcaacaacggatctcttggttcc
agcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaa
tcatcgaatctttgaacgcacattgcgccctctggtattccggggggcatgcctgttcga
gcgtcatttcaccactcaagc-ctggcttgg-tattgggcg-tcgcg----g--------
tgc---cgcgcgccttaaagtcttc--cggctgagctg-tccgtctcta-agcgttgtgg
---caa-ctattcgcttcggaggc--cgggcggc-cgcggccgttaaatctttc--ac--
-aaggttgacctcggatcaggtagggatacccgctgaacttaagcatatc
>Mycosphaerella_thailandica_TH011 Mycosphaerella_thailandica_TH011 700 bp 
gattgaatggctcagtgaggccttcggactggcccagggaggtcggcaacgaccacccag
ggccggaaagttggtcaaactcggtcatttagaggaagtaaaagtcgtaacaaggtctcc
gtaggtgaacctgcggagggatcattact-gagtga--gggc-ctccgggtcc-------
ga---cctccaaccctttgtgaa-cc-aa--tcttgttgcttcgggggcgaccctgccgc
t---tcggcggtgcggcgcccccggagg----ccatc--aaacactgcatca--ttgc-g
tcggagt----aa-aagtaaat--gaaac-aaaactttcaacaacggatctcttggttcc
agcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaa
tcatcgaatctttgaacgcacattgcgccctctggtattccggggggcatgcctgttcga
gcgtcatttcaccactcaagc-ctggcttgg-tattgggcg-tcgcg----g--------
tgc---cgcgcgccttaaagtcttc--cggctgagctg-tccgtctcta-agcgttgtgg
---caa-ctattcgcttcggaggc--cgggcggc-cgcggccgttaaatctttc--ac--
-aaggttgacctcggatcaggtagggatacccgctgaacttaagcatatc
>Mycosphaerella_thailandica_TH026A Mycosphaerella_thailandica_TH026A 700 bp 
gattgaatggctcagtgaggccttcggactggcccagggaggtcggcaacgaccacccag
ggccggaaagttggtcaaactcggtcatttagaggaagtaaaagtcgtaacaaggtctcc
gtaggtgaacctgcggagggatcattact-gagtga--gggc-ctccgggtcc-------
ga---cctccaaccctttgtgaa-cc-aa--tcttgttgcttcgggggcgaccctgccgc
t---tcggcggtgcggcgcccccggagg----ccatc--aaacactgcatca--ttgc-g
tcggagt----aa-aagtaaat--gaaac-aaaactttcaacaacggatctcttggttcc
agcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaa
tcatcgaatctttgaacgcacattgcgccctctggtattccggggggcatgcctgttcga
gcgtcatttcaccactcaagc-ctggcttgg-tattgggcg-tcgcg----g--------
tgc---cgcgcgccttaaagtcttc--cggctgagctg-cccgtctcta-agcgttgtgg
---caa-ctattcgcttcggaggc--cgggcggc-cgcggccgttaaatctttc--ac--
-aaggttgacctcggatcaggtagggatacccgctgaacttaagcatatc
>Mycosphaerella_thailandica_TH026B Mycosphaerella_thailandica_TH026B 700 bp 
gattgaatggctcagtgaggccttcggactggcccagggaggtcggcaacgaccacccag
ggccggaaagttggtcaaactcggtcatttagaggaagtaaaagtcgtaacaaggtctcc
gtaggtgaacctgcggagggatcattact-gagtga--gggc-ctccgggtcc-------
ga---cctccaaccctttgtgaa-cc-aa--tcttgttgcttcgggggcgaccctgccgc
t---tcggcggtgcggcgcccccggagg----ccatc--aaacactgcatca--ttgc-g
tcggagt----aa-aagtaaat--gaaac-aaaactttcaacaacggatctcttggttcc
agcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaa
tcatcgaatctttgaacgcacattgcgccctctggtattccggggggcatgcctgttcga
gcgtcatttcaccactcaagc-ctggcttgg-tattgggcg-tcgcg----g--------
tgc---cgcgcgccttaaagtcttc--cggctgagctg-tccgtctcta-agcgttgtgg
---caa-ctattcgcttcggaggc--cgggcggc-cgcggccgttaaatctttc--ac--
-aaggttgacctcggatcaggtagggatacccgctgaacttaagcatatc
>Mycosphaerella_thailandica_TH091B Mycosphaerella_thailandica_TH091B 700 bp 
gattgaatggctcagtgaggccttcggactggcccagggaggtcggcaacgaccacccag
ggccggaaagttggtcaaactcggtcatttagaggaagtaaaagtcgtaacaaggtctcc
gtaggtgaacctgcggagggatcattact-gagtga--gggc-ctccgggtcc-------
ga---cctccaaccctttgtgaa-cc-aa--tcttgttgcttcgggggcgaccctgccgc
t---tcggcggtgcggcgcccccggagg----ccatc--aaacactgcatca--ttgc-g
tcggagt----aa-aagtaaat--gaaac-aaaactttcaacaacggatctcttggttcc
agcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaa
tcatcgaatctttgaacgcacattgcgccctctggtattccggggggcatgcctgttcga
gcgtcatttcaccactcaagc-ctggcttgg-tattgggcg-tcgcg----g--------
tgc---cgcgcgccttaaagtcttc--cggctgagctg-tccgtctcta-agcgttgtgg
---caa-ctattcgcttcggaggc--cgggcggc-cgcggccgttaaatctttc--ac--
-aaggttgacctcggatcaggtagggatacccgctgaacttaagcatatc
>Mycosphaerella_tumulosa 700 bp 
------------------------------------------------------------
---------------------------------------------------------tcc
gtaggtgaacctgcggagggatcattact-gagtga--gggc-tca--cgccc-------
ga---cctccaaccctctgtgaa-ccaaa---cttgttgcttcgggggcgaccctgccgg
caaactcgtcgccgggcgcccccggagg----tctcctcaaacactgcatct--ttgc-g
tcggagt----tt-aaacaaat--taaacaaaaactttcaacaacggatctcttggttct
ggcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaa
tcatcgaatctttgaacgcacattgcgccctttggtattccaaagggcatgcctgttcga
gcgtcatttcaccactcaagc-ctagcttgg-tattgggcg-tcgcg----gtct-----
ccc---cgcgcgccttgaa-tcttc--cggctgagccg-tccgtctcta-agcgttgtgg
attttt-caattcgctttggagtg--cgggtggc-tgcggccgttaaatctttc--actt
aaaggttgacctcggatcaggtagggata---------------------
>Mycosphaerella_vietnamensis_DQ632675 Mycosphaerella_vietnamensis_DQ632675 700 bp 
------------------------------------------------------------
---------------------------------------------------------tcc
gtaggtgaacctgcggagggatcattact-gagtga--gggt-ttcaccgccc-------
ga---cctccaaccctttgtgaa-ccaca--acttgttgcttcgggggcgaccctgccgt
t---cgcggc-atc-gcgcccccggagg----atact--taaccctgcatca--ttgc-g
tcggagta---tttttattaa---taaat-aaaactttcaacaacggatctcttggttct
ggcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaa
tcatcgaatctttgaacgcacattgcgccccgtggtattccgcggggcatgcctgttcga
gcgtcatttcaccactcgagt-ctgactcgg-tattgggcg-ccgcg----gttt-----
aatcgccgcgcgcctcaaagtct-c--cggctgggcag-cccgtctccg-agcgttgtgg
catcacagttctcgctagggagtcgcgggcggcgtc--ggccgttaaacac-cc--catc
aaaggttgacctcggatcaggtagggata---------------------
>Mycosphaerella_vietnamensis_DQ632678 Mycosphaerella_vietnamensis_DQ632678 700 bp 
------------------------------------------------------------
---------------------------------------------------------tcc
gtaggtgaacctgcggagggatcattact-gagtga--gggt-ttcaccgccc-------
ga---cctccaaccctttgtgaa-ccaca--acttgttgcttcgggggcgaccctgccgt
t---cgcggc-atc-gcgcccccggagg----atact--taaccctgcatca--ttgc-g
tcggagta---tttttattaa---taaat-aaaactttcaacaacggatctcttggttct
ggcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaa
tcatcgaatctttgaacgcacattgcgccccgtggtattccgcggggcatgcctgttcga
gcgtcatttcaccactcgagt-ctgactcgg-tattgggcg-ccgcg----gttt-----
aatcgccgcgcgcctcaaagtct-c--cggctgggcag-cccgtctccg-agcgttgtgg
catcacagttctcgctagggagtcgcgggcggcgtc--ggccgttaaacac-cc--catc
aaaggttgacctcggatcaggtagggata---------------------
>Mycosphaerella_vietnamensis_TH009B Mycosphaerella_vietnamensis_TH009B 700 bp 
gattgaatggctcagtgaggccttcggactggcccagggaggtcggcaacgaccacccag
ggccggaaagttggtcaaactcggtcatttagaggaagtaaaagtcgtaacaaggtctcc
gtaggtgaacctgcggagggatcattact-gagtga--gggt-ttcaccgccc-------
ga---cctccaaccctttgtgaa-ccaca--acttgttgcttcgggggcgaccctgccgt
t---cgcggc-atc-gcgcccccggagg----atact--taaccctgcatca--ttgc-g
tcggagta---tttttattaa---taaat-aaaactttcaacaacggatctcttggttct
ggcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaa
tcatcgaatctttgaacgcacattgcgccccgtggtattccgcggggcatgcctgttcga
gcgtcatttcaccactcgagt-ctgactcggttattgggcg-ccgcg----gttt-----
aatcgccgcgcgcctcaaagtct-c--cggctgggcag-cccgtctccg-agcgttgtgg
catcacagttctcgctagggagtcgcgggcggcgtc--ggccgttaaacac-cc--catc
aaaggttgacctcggatcaggtagggatacccgctgaacttaagcatatc
>Mycosphaerella_vietnamensis_TH010B Mycosphaerella_vietnamensis_TH010B 700 bp 
gattgaatggctcagtgaggccttcggactggcccagggaggtcggcaacgaccacccag
ggccggaaagttggtcaaactcggtcatttagaggaagtaaaagtcgtaacaaggtctcc
gtaggtgaacctgcggagggatcattact-gagtga--gggt-ttcaccgccc-------
ga---cctccaaccctttgtgaa-ccaca--acttgttgcttcgggggcgaccctgccgt
t---cgcggc-atc-gcgcccccggagg----atact--taaccctgcatca--ttgc-g
tcggagta---tttttattaa---taaat-aaaactttcaacaacggatctcttggttct
ggcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaa
tcatcgaatctttgaacgcacattgcgccccgtggtattccgcggggcatgcctgttcga
gcgtcatttcaccactcgagt-ctgactcggttattgggcg-ccgcg----gttt-----
aatcgccgcgcgcctcaaagtct-c--cggctgggcag-cccgtctccg-agcgttgtgg
catcacagttctcgctagggagtcgcgggcggcgtc--ggccgttaaacac-cc--catc
aaaggttgacctcggatcaggtagggatacccgctgaacttaagcatatc
>Mycosphaerella_vietnamensis_TH093 Mycosphaerella_vietnamensis_TH093 700 bp 
gattgaatggctcagtgaggccttcggactggcccagggaggtcggcaacgaccacccag
ggccggaaagttggtcaaactcggtcatttagaggaagtaaaagtcgtaacaaggtctcc
gtaggtgaacctgcggagggatcattact-gagtga--gggt-ttcaccgccc-------
ga---cctccaaccctttgtgaa-ccaca--acttgttgcttcgggggcgaccctgccgt
t---cgcggc-atc-gcgcccccggagg----atact--taaccctgcatca--ttgc-g
tcggagta---tttttattaa---taaat-aaaactttcaacaacggatctcttggttct
ggcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaa
tcatcgaatctttgaacgcacattgcgccccgtggtattccgcggggcatgcctgttcga
gcgtcatttcaccactcgagt-ctgactcggttattgggcg-ccgcg----gttt-----
aatcgccgcgcgcctcaaagtct-c--cggctgggcag-cccgtctccg-agcgttgtgg
catcacagttctcgctagggagtcgcgggcggcgtc--ggccgttaaacac-cc--catc
aaaggttgacctcggatcaggtagggatacccgctgaacttaagcatatc
>Mycosphaerella_vietnamensis_TH099A Mycosphaerella_vietnamensis_TH099A 700 bp 
gattgaatggctcagtgaggccttcggactggcccagggaggtcggcaacgaccacccag
ggccggaaagttggtcaaactcggtcatttagaggaagtaaaagtcgtaacaaggtctcc
gtaggtgaacctgcggagggatcattact-gagtga--gggt-ttcaccgccc-------
ga---cctccaaccctttgtgaa-ccaca--acttgttgcttcgggggcgaccctgccgt
t---cgcggc-atc-gcgcccccggagg----atact--taaccctgcatca--ttgc-g
tcggagta---tttttattaa---taaat-aaaactttcaacaacggatctcttggttct
ggcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaa
tcatcgaatctttgaacgcacattgcgccccgtggtattccgcggggcatgcctgttcga
gcgtcatttcaccactcgagt-ctgactcggttattgggcg-ccgcg----gttt-----
aatcgccgcgcgcctcaaagtct-c--cggctgggcag-cccgtctccg-agcgttgtgg
catcacagttctcgctagggagtcgcgggcggcgtc--ggccgttaaacac-cc--catc
aaaggttgacctcggatcaggtagggatacccgctgaacttaagcatatc
>Mycosphaerella_yunnanensis_DQ632686 Mycosphaerella_yunnanensis_DQ632686 700 bp 
------------------------------------------------------------
---------------------------------------------------------tcc
gtaggtgaacctgcggagggatcattact-gagtga--gggc-ctcc-ggtcc-------
ga---cctccaaccctttgtgaa-ccaac---actgttgcttcgggggcgaccctgcctt
t------cgggcagtgcgcccccggagg----atatca-aaacgctgcatct--ttgc-g
tcggagt----atcaatcaaat--tgaac-aaaactttcaacaacggatctcttggttct
ggcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaa
tcatcgaatctttgaacgcacattgcgccccgtggtattccgcggggcatgcctgttcga
gcgtcatttcaccactcaagc-ctggcttgg-tattgggcg-tcgcg----agt------
--c---cgcgcgcctcaaagtct-c--cggctgagctg-tccgtctccc-agcgttgtga
---atc-tcattcgctacggagtct-cgggcagc-cgcggccgttaaacttat-----ct
aaaggttgacctcggatcaggtagggata---------------------
>Mycosphaerella_yunnanensis_DQ632687 Mycosphaerella_yunnanensis_DQ632687 700 bp 
------------------------------------------------------------
---------------------------------------------------------tcc
gtaggtgaacctgcggagggatcattact-gagcga--gggc-ctcc-ggtcc-------
ga---cctcctaccctttgtgaa-ccaac---actgttgcttcgggggcgaccctgcctt
t------cgggcagtgcgcccccggagg----gaatca-aaacgctgcatct--ttgc-g
tcggagt----atcaatcaaat--tgaac-aaaactttcaacaacggatctcttggttct
ggcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaa
tcatcgaatctttgaacgcacattgcgccccgtggtattccgcggggcatgcctgttcga
gcgtcatttcaccactcaagc-ctggcttgg-tattgggcg-tcgcg----agt------
--t---cgcgcgcctcaaagtct-c--cggctgagctg-tccgtctccc-agcgttgtga
---atc-tcattcgctacggagtttacgagcagc-cgcggccgttaaacttat-----ct
aaaggttgacctcggatcaggtagggata---------------------
>Penidiella_eucalypti_TH064 700 bp 
gattgaatggctcagtgaggcgttcggactggcccagggaggtcggcaacgaccacccag
ggccggaaagttcgtcaaacttggtcatttagaggaagtaaaagtcgtaacaaggtctcc
gtaggtgaacctgcggagggatcattacc-gagtga--gggc-ccccg-gccc-------
ga---cctccaaccccatgtttt-ccaac--ctctgttgcctcgggggcgacccggcccc
g------g----ccggggccccccgcggacctcaacc--aaaccctgcatat-ctg-c-g
tctgagtc---aattgataaat--tcaatcaaaactttcaacaacggatctcttggttct
ggcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaa
tcatcgaatctttgaacgcacattgcgcccggtggcattccgccgggcatgcctgttcga
gcgtcattacaccactccagc-ctggctggg-tattgggcg-tcgcg----gggt-----
ccc---cgcgcgcctcgaagtct-c--cggccgagccg-tccgtctcataagcgttgtga
tc-tat-caagccgcttgcgagctc-ggggggccgtcgcgccgttaaacgacc---atct
caaggttgacctcggatcaggtagggatacccgctgaacttaagcatatc
>Penidiella_eucalypti_TH064_1 700 bp 
gattgaatggctcagtgaggcgttcggactggcccagggaggtcggcaacgaccacccag
ggccggaaagttcgtcaaacttggtcatttagaggaagtaaaagtcgtaacaaggtctcc
gtaggtgaacctgcggagggatcattacc-gagtga--gggc-ccccg-gccc-------
ga---cctccaaccccatgtttt-ccaac--ctctgttgcctcgggggcgacccggcccc
g------g----ccggggccccccgc-gacctcaacc--aaaccctgcatat-ctg-c-g
tctgagtc---aattgataaat--tcaatcaaaactttcaacaacggatctcttggttct
ggcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaa
tcatcgaatctttgaacgcacattgcgcccggtggcattccgccgggcatgcctgttcga
gcgtcattacaccactccagc-ctggctggg-tattgggcg-tcgcg----gggt-----
ccc---cgcgcgcctcgaagtct-c--cggccgagccg-tccgtctcataagcgttgtga
tc-tat-caagccgcttgcgagctc-ggggggccgtcgcgccgttaaacgacc---atct
caaggttgacctcggatcaggtagggatacccgctgaacttaagcatatc
>Penidiella_eucalypti_TH133 700 bp 
gattgaatggctcagtgaggcgttcggactggcccagggaggtcggcaacgaccacccag
ggccggaaagttcgtcaaacttggtcatttagaggaagtaaaagtcgtaacaaggtctcc
gtaggtgaacctgcggagggatcattacc-gagtga--gggc-ccccg-gccc-------
ga---cctccaaccccatgtttt-ccaac--ctctgttgcctcgggggcgacccggcccc
g------g----ccggggccccccgcggacctcaacc--aaaccctgcatat-ctg-c-g
tctgagtc---aattgataaat--tcaatcaaaactttcaacaacggatctcttggttct
ggcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaa
tcatcgaatctttgaacgcacattgcgcccggtggcattccgccgggcatgcctgttcga
gcgtcattacaccactccagc-ctggctggg-tattgggcg-tcgcg----gggt-----
ccc---cgcgcgcctcgaagtct-c--cggccgagccg-tccgtctcataagcgttgtga
tc-tat-caagccgcttgcgagctc-ggggggccgtcgcgccgttaaacgacc---atct
caaggttgacctcggatcaggtagggatacccgctgaacttaagcatatc
>Penidiella_kurandae 700 bp 
-----gatggctcagtgaggcctccggactggcccagggaggtcggcaacgaccacccag
ggccggaaagctggtcaaacttggtcatttagaggaagtaaaagtcgtaacaaggtctcc
gtaggtgaacctgcggagggatcattacc-gagtgc--gggc---tgcggccc-------
ga---cctcccaccccgtgtgtcccc-----ccccgttgcctcgggggcgacccggccgc
t-------cgcgccggggcccccggtggacccgcccaactcggttttcggtg--ctgc-g
tctgagtg---acaggtttaa---tgaagcaaaactttcaacaacggatctcttggttcc
ggcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaa
tcatcgaatctttgaacgcacattgcgccccttggcactccgaggggcatgcctgttcga
gcgtcatttcacccatcaagc-ctggcttgg-cgttgggcg-ccgcg-------------
-gcctccgcgcgcctcaaagttcccgtcggccgagccg-tccgcccccgtagcgttgtgg
tttccgttcgctcaccgggg------gaagggcggcggcgccgttcaaaaagtct-ccac
aaagtttgacctcggatcaggcagggatacccgctgaacttaagcatatc
>Penidiella_rigidophora 700 bp 
------------------------------------------------------------
------------------------------------------------------------
----------------agggatcattact-gagtga--cggc-cctcgggctc-------
ga---cctccaaccctttgt-aa-tccga--ccatgttgcctcgggggcgacccggcctt
c------gggcgtcggggcccccggtggacccc--tc---aacactgcat-c-tttgc-g
tctgagtt---tgatattgaa---tcaatcaaaactttcaacaacggatctcttggttct
ggcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaa
tcatcgaatctttgaacgcacattgcgccccttggtattccggggggcatgcctgttcga
gcgtcattacacccctccagc-ctcgctggt-tgttgggcgtccgcggatgcata-----
gtc---tgcgcgcctcaatgtcg-c--cggccggaccg-accgtctcta-agcgttgtgg
---taa-cagttcgcttgcg-ggca-cgggagggacgtcgccgttaaaccttttcattcc
--aggttgacctcggatcaggtagggatacccgctgaacttaagcatatc
>Penidiella_strumelloidea 700 bp 
------------------------------------------------------------
------------------------------------------------------------
----------------agggatcattact-gagtga--gggc-ctctgcgccc-------
ga---cctcccaacccttctgtcgtctccgaccgcgttgcctcgggggatccgccgtccg
c------------ggcggcccccggaggaccaca-----taactctgcgtaa-ccgtc-g
tccgagt-----ctaaacaaaaattgaaacacaactttcaacaacggatctcttggctct
ggcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaattccgtgaa
tcatcgaatctttgaacgcacattgcgcccctcggtattccggggggcatgcctgttcga
gcgtcattacacccctcaagctccggcttgg-tcttgggcg-tcgcg-----------gt
cccccccgcgtgcctcaatgtcg-c--cggctggtgcg-tccgtctccg-agcgtcgtga
cttca--ttgttcgcttctggagg--ccggacgcgccgcgccgtcaaccccccat-atct
acaggttgacctcggatcaggtagggatacccgctgaacttaagcatatc
>Penidiella_venezuelensis 700 bp 
------------------------------------------------------------
------------------------------------------------------------
----------------agggatcattaccagagtggaccggc-cctcgtggct-------
ggaacctcccaaccccatgtcgt-ttcga--ctctgttgcctcgggggcgacccggcctt
c------gggcgtcggggcccccggcggacccc--tc--aaactctgcatgc-tttgc-g
tctgagta---cagatataaa---tcaatcaaaactttcaacaacggatctcttggttct
ggcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaa
tcatcgaatctttgaacgcacattgcgccccctggcattccggggggcatgcctgttcga
gcgtcattacaccactcaagc-ctggcttgg-tattgggcggccgcg---gtcct-----
ccc---cgcgcgccctaatgtct-c--cggctgagccg-tccgtctcta-agcgttgtgg
ca-cac-cagttcgcttgcgaggcc-cgggcggttcgacgccgttaaaccccttcttctc
aaaggttgacctcggatcaggtagggatacccgctgaacttaagcatatc
>Phaeoramularia_calotropidis 700 bp 
------------------------------------------------------------
---------------------------------------------------------tcc
gtaggtgaacctgcggagggatcattact-gagtga--gggc-tca--cgccc-------
ga---cctccaaccctttgtgaa-cgaa----catgttgcttcgggggcgaccctgccat
tga-------gccgggcgcccccggagg----tcatc--aaactctgcatct--ttgc-g
tcggagt----acaagttaaat--caaac-aaaactttcaacaacggatctcttggttct
ggcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaa
tcatcgaatctttgaacgcacattgcgccctttggtattccgaagggcatgcctgttcga
gcgtcatttcaccactcaagc-ctcgcttgg-tattgggcg-tcgcg----g--------
ttc---cgcgcgccttaaagtct-c--cggctgagctg-tccgtctcta-agcgttgtga
---tac-atattcgcttcggggcg--cgggcggt-cacggccgttaaacttcc----ttc
acaggttgacctcggatcaggtagggata---------------------
>Pseudocercospora_assamensis 700 bp 
------------------------------------------------------------
---------------------------------------------------------tcc
gtaggtgaacctgcggagggatcattact-gagtga--gggc-tca--cgccc-------
ga---cctccaaccctttgtgaa-ccaaa---cttgttgcttcgggggcgaccctgccga
cgacttcgtcgccgggcgcccccggagg----tcttct-aaacactgcatct--ttgc-g
tcggagt----tt-aaacaaat--taaac-aaaactttcaacaacggatctcttggttct
ggcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaa
tcatcgaatctttgaacgcacattgcgccctttggtattccgaagggcatgcctgttcga
gcgtcatttcaccactcaagc-ctggcttgg-tattgggcg-tcgcg----gtgt-----
ttc---cgcgcgccttaaagtcttc--cggctgagctg-tccgtctcta-agcgttgtgg
attttt-caattcgcttcggagtg--cgggcggc-cgcggccgttaaatcttt---attc
aaaggttgacctcggatcaggtagggata---------------------
>Pseudocercospora_basiramifera 700 bp 
------------------------------------------------------------
---------------------------------------------------------tcc
gtaggtgaacctgcggagggatcattact-gagtga--gggc-tca--cgccc-------
ga---cctccaaccctttgtgaa-ccaaa---cttgttgcttcgggggcgaccctgccga
cgacttggtcgccgggcgcccccggagg----tcttct-aaacactgcatct--ttgc-g
tcggagt----tt-aaacaaat--taaac-aaaactttcaacaacggatctcttggttct
ggcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaa
tcatcgaatctttgaacgcacattgcgccctttggtattccgaagggcatgcctgttcga
gcgtcatttcaccactcaagc-ctggcttgg-tattgggcg-tcgcg----gtg------
ttc---cgcgcgccttaaagtcttc--cggctgagctg-tccgtctcta-agcgttgtgg
attttt-caattcgcttcggagtg--cggatggc-cgcggccgttaaatcttt---attc
aaaggttgacctcggatcaggtagggata---------------------
>Pseudocercospora_chiangmaiensis_TH094_1 Pseudocercospora_chiangmaiensis_TH094.1 700 bp 
-attgaatggctcagtgaggccttcggactggcccagggaggtcggcaacgaccacccag
ggccggaaagttggtcaaactcggtcatttagaggaagtaaaagtcgtaacaaggtctcc
gtaggtgaacctgcggagggatcattact-gagtga--gggc-tca--cgccc-------
ga---cctccaaccctttgtgaa-ccaaa---cttgttgcttcgggggcgaccctgccga
cgacttcgtcgccgggcgcccccggagg----tctcct-aaacactgcatct--ttgc-g
tcggagt----tt-aaacaaat--taaac-aaaactttcaacaacggatctcttggttct
ggcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaa
tcatcgaatctttgaacgcacattgcgccctttggtattccgaagggcatgcctgttcga
gcgtcatttcaccactcaagc-ctggcttgg-tattgggcg-tcgcg----gtgt-----
ttc---cgcgcgccttaaagtcttc--cggctgagctg-tccgtctcta-agcgttgtgg
attttt-caattcgcttcggagtg--cgggcggc-cgcggccgttaaatcttt---attc
aaaggttgacctcggatcaggtagggatacccgctgaacttaagcatatc
>Pseudocercospora_chiangmaiensis_TH094_2 Pseudocercospora_chiangmaiensis_TH094.2 700 bp 
-attgaatggctcagtgaggccttcggactggcccagggaggtcggcaacgaccacccag
ggccggaaagttggtcaaactcggtcatttagaggaagtaaaagtcgtaacaaggtctcc
gtaggtgaacctgcggagggatcattact-gagtga--gggc-tca--cgccc-------
ga---cctccaaccctttgtgaa-ccaaa---cttgttgcttcgggggcgaccctgccga
cgacttcgtcgccgggcgcccccggagg----tctcct-aaacactgcatct--ttgc-g
tcggagt----tt-aaacaaat--taaac-aaaactttcaacaacggatctcttggttct
ggcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaa
tcatcgaatctttgaacgcacattgcgccctttggtattccgaagggcatgcctgttcga
gcgtcatttcaccactcaagc-ctggcttgg-tattgggcg-tcgcg----gtgt-----
ttc---cgcgcgccttaaagtcttc--cggctgagctg-tccgtctcta-agcgttgtgg
attttt-caattcgcttcggagtg--cgggcggc-cgcggccgttaaatcttt---attc
aaaggttgacctcggatcaggtagggatacccgctgaacttaagcatatc
>Pseudocercospora_chiangmaiensis_TH094_3 Pseudocercospora_chiangmaiensis_TH094.3 700 bp 
-attgaatggctcagtgaggccttcggactggcccagggaggtcggcaacgaccacccag
ggccggaaagttggtcaaactcggtcatttagaggaagtaaaagtcgtaacaaggtctcc
gtaggtgaacctgcggagggatcattact-gagtga--gggc-tca--cgccc-------
ga---cctccaaccctttgtgaa-ccaaa---cttgttgcttcgggggcgaccctgccga
cgacttcgtcgccgggcgcccccggagg----tctcct-aaacactgcatct--ttgc-g
tcggagt----tt-aaacaaat--taaac-aaaactttcaacaacggatctcttggttct
ggcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaa
tcatcgaatctttgaacgcacattgcgccctttggtattccgaagggcatgcctgttcga
gcgtcatttcaccactcaagc-ctggcttgg-tattgggcg-tcgcg----gtgt-----
ttc---cgcgcgccttaaagtcttc--cggctgagctg-tccgtctcta-agcgttgtgg
attttt-caattcgcttcggagtg--cgggcggc-cgcggccgttaaatcttt---attc
aaaggttgacctcggatcaggtagggatacccgctgaacttaagcatatc
>Pseudocercospora_epispermogonia Pseudocercospora_epispermogonia 700 bp 
------------------------------------------------------------
---------------------------------------------------------tcc
gtaggtgaacctgcggagggatcattacc-gagtga--gggt-ttcg--gccc-------
ga---cctccaaccctttgtgaa-tca-a--acctgttgcttcgggggcgaccctgccgt
t---cgcggc-gcg-gcgcccccggggg----aaatc--aaacactgcgtcaatttgt-g
tcggagta-----cttgttaa---taaac-aaaactttcaacaacggatctcttggttct
ggcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaa
tcatcgaatctttgaacgcacattgcgccccgtggtattccgcggggcatgcctgttcga
gcgtcatttcaccactcgagt-ctgactcgg-tattgggcg-tcgcg----tttc-----
gat----gcgcgccttaaagttt-c--cggctggaccg-tccgtctccg-agcgttgtgg
catc---tgtctcgctagggagccgcggagggcgtt--ggccgttaaacac-cc--catc
aaaggttgacctcggatcaggtagggata---------------------
>Pseudocercospora_longispora 700 bp 
------------------------------------------------------------
---------------------------------------------------------tcc
gtaggtgaacctgcggagggatcattacc-gagtga--gggc-cca--cgccc-------
ga---cctccaaccctttgtgaa-ccaca---cctgttgcttcgggggcgaccctgccgg
cgaactcgtcgccgggcgcccccggagg----tctcct-aaacactgcatct--ttgc-g
tcggagt----ccgaaacaaat--cgaac-aaaactttcaacaacggatctcttggttct
ggcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaa
tcatcgaatctttgaacgcacattgcgccctttggtattccgaagggcatgcctgttcga
gcgtcatttcaccactcaagc-ctagcttgg-tattgggcg-ccgcg----gtg------
ttc---cgcgcgccttaaagtctcc--cggctgagccg-tccgtctcga-agcgttgtgg
attttt-caattcgcttcggagtg--cgggcggc-cgcggccgttaaatc-------ttc
caaggttgacctcggatcaggtagggata---------------------
>Pseudocercospora_paraguayensis 700 bp 
------------------------------------------------------------
---------------------------------------------------------tcc
gtaggtgaacctgcggagggatcattact-gagtga--gggc-tca--cgccc-------
ga---cctccaaccctttgtgaa-ccaaa---cttgttgcttcgggggcgaccctgccga
cgactccgtcgccgggcgcccccggagg----tcttct-aaacactgcatct--ttgc-g
tcggagt----tt-aaacaaat--taaac-aaaactttcaacaacggatctcttggttct
ggcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaa
tcatcgaatctttgaacgcacattgcgccctttggtattccgaagggcatgcctgttcga
gcgtcatttcaccactcaagc-ctggcttgg-tattgggcg-tcgcg----gtg------
ttc---cgcgcgccttaaagtcttc--cggctgagctg-tccgtctcta-agcgttgtgg
attttt-caattcgcttcggagtg--cggatggc-cgcggccgttaaatcttt---attc
aaaggttgacctcggatcaggtagggata---------------------
>Pseudocercospora_pseudoeucalyptorum Pseudocercospora_pseudoeucalyptorum 700 bp 
------------------------------------------------------------
------------------------------------------------------------
----------------agggatcattact-gagtga--gggc-tca--cgccc-------
ga---cctccaaccctttgtgaa-cacat---cttgttgcttcgggggcgaccctgccgg
c-actacgtcgccgggcgcccccggagg----tctcc--aaacactgcatct--ttgc-g
tcggagt----tt-aaacaaat--taaac-aaaactttcaacaacggatctcttggttct
ggcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaa
tcatcgaatctttgaacgcacattgcgccctttggtattccgaagggcatgcctgttcga
gcgtcatttcaccactcaagc-ctagcttgg-tattgggcg-tcgcg----g--------
ctc---cgcgcgccttaaagtct-c--cggctgagcca-ttcgtctcta-agcgttgtgg
attttc-taattcgcttcggagtg--cgggtggc-cgcggccgttaaatcttt---attc
aaaggttgacctcggatcaggtagg-------------------------
>Pseudocercospora_subulata 700 bp 
------------------------------------------------------------
------------------------------------------------------------
----------------agggatcattact-gagtga--gggc-tca--cgccc-------
ga---cctccaaccctttgtgaa-cacat---cttgttgcttcgggggcgaccctgccgg
c-actacgtcgccgggcgcccccgaagg----tctcc--aaacactgcatct--ttgc-g
tcggagt----ttaaaacaaat--taaac-aaaactttcaacaacggatctcttggttct
ggcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaa
tcatcgaatctttgaacgcacattgcgccctttggtattccgaagggcatgcctgttcga
gcgtcatttcaccactcaagc-ctggcttgg-tattgggcg-tcgcg----g--------
ctc---cgcgcgccttaaagtct-c--cggctgagcca-ttcgtctcta-agcgttgtgg
attttc-taattcgcttcggagtg--cgggtggc-cgcggccgttaaatcttt---attc
aaaggttgacctcggatcaggtagggata---------------------
>Readeriella_eucalypti 700 bp 
------------------------------------------------------------
------------------------------------------------------------
----------------agggatcattact-gagtga--gggc-cttcgggtcc-------
ga---cctccaaccccatgttgt-ccgac---tctgttgcctcgggggcgacccggccgt
a-------cggccgcgggcccccggtggactact-----caactctgcatct--tagc-g
tctgagt----tta--attataaatcaattaaaactttcaacaacggatctcttggttct
ggcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaa
tcatcgaatctttgaacgcacattgcgccccttggtattccgaggggcatgcctgttcga
gcgtcattacaccaatcaagc-ctggcttgg-tattgggcg-ccgtg----gttcttcgg
agc---cgcgcgccctaatgtcc-t--cggctgggccg-tccgcctcga-agcgttgtga
-taatacaga-tcgcttgtgggtgtgga--cggtcgcgcgccgtaaaacctttt--ttc-
--aagttgacctcggatcaggtagggata---------------------
>Teratosphaeria_cryptica 700 bp 
------------------------------------------------------------
--------------------------------------------------------tccg
t-aggtgaacctgcgtagggatcattacc-gagtga--gggc-ctccgggtcc-------
ga---cctccaaccctttgtgaa-cgcat---cccgttgcgtcggggccgaccctgccgc
c-------gtgccg-gggcccccggcggacccct-----caactctgcatct--ttgc-g
tctgagt----gat--aacgaaaatcaatcaaaactttcaacaacggatctcttggttct
ggcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaa
tcatcgaatctttgaacgcacattgcgccccctggtattccggagggcatgcctgttcga
gcgtcattacaccactccagc-ctcgctggg-tattgggcg-tctcg----g-ct-----
--c---cgcgcgcctcaatgtct-c--cggccgagccg-accgtctcta-agcgttgtgg
-cacaactgtttcgct-tccgggaccggtctggcgtcgcgccgtcaaccccctc--tctc
acaggttgacctcggatcaggtagggata---------------------
>Teratosphaeria_nubilosa 700 bp 
------------------------------------------------------------
--------------------------------------------------------tccg
t-aggtgaacctgcggagggatcattact-gagtgc--gggc-gcc--agccc-------
ga---cctcctaccccatgtttt-cccac---cacgttgcctcgggggcgacccggcccc
c-------gcgccg-gggccctcgcaggacccct-----caacgctgcatct--gtgc-g
tcggagt----aat--acaaccaatcaattaaaactttcaacaacggatctcttggttct
ggcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaa
tcatcgaatctttgaacgcacattgcgccctctggtattccggagggcatgcctgttcga
gcgtcatttcaccactccagc-cccgctggg-tcttgggcg-ccgcg----gcct-----
--c---cgcgcgcctcaatgtct-c--cggccgagccg-accgtctctc-agcgttgtgg
-cactactgtttcgctgacggggaccggtctggcggcgcgccgttaaacccttt--cacc
aaaggttgacctcggatcaggtagggata---------------------
>Teratosphaeria_parva_DQ303003 700 bp 
------------------------------------------------------------
------------------------------------------------------------
----------------agggatcattacc-gagtga--gggc-ctccgggctc-------
ga---cctccaaccccattgtat-tccgacctcttgttgcctcgggggcgacccggcctt
c------gggcgtcggggcccccggtggaccat--ca---aactctgcatct-ttgac-g
tctgagt----aaatattgaa---tcaatcaaaacttttaacaacggatctcttggttct
ggcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaa
tcatcgaatctttgaacgcacattgcgccccttggtattccgaggggcatgcctgttcga
gcgtcatttcaccactcaagc-ctggcttgg-tattgggcg-ccgcg-----gtt-----
tgc---cgcgcgcctcaaagtct-c--cggctgagcca-actgtctcta-agcgttgtgg
tt-taa-tcatccgcttgtg-agat-cgaaggcgacg--gccgttaa--actt---attc
aaaggttgacctcggatcaggtagggata---------------------
>Teratosphaeria_parva_DQ303005 700 bp 
------------------------------------------------------------
------------------------------------------------------------
--------------ggagggatcattacc-gagtga--gggc-ctccgggctc-------
ga---cctccaaccccattgtat-tccgacctcttgttgcctcgggggcgacccggcctt
c------gggcgtcggggcccccggtggaccat--ca---aactctgcatct-ttgac-g
tctgagt----aaatattgaa---tcaatcaaaacttttaacaacggatctcttggttct
ggcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaa
tcatcgaatctttgaacgcacattgcgccccttggtattccgaggggcatgcctgttcga
gcgtcatttcaccactcaagc-ctggcttgg-tattgggcg-ccgcg-----gtt-----
tgc---cgcgcgcctcaaagtct-c--cggctgagcca-actgtctcta-agcgttgtgg
tt-taa-tcatccgcttgtg-agat-cgaaggcgacg--gccgttaa--actt---attc
aaaggttgacctcggatcaggtagggata---------------------
>Teratosphaeria_sp_ 700 bp 
------------------------------------------------------------
---------------------------------------------------------tcc
gtaggtgaacctgcggagggatcattacc-gagtga--gggc-ccccg-gccc-------
ga---cctccaaccccatgtttt-ccaac--ctctgttgcctcgggggcgacccggcccc
g------g----ccggggccccccgcggacctcaacc--aaaccctgcatat-ctg-c-g
tctgagtc---aattgataaat--tcaatcaaaactttcaacaacggatctcttggttct
ggcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaa
tcatcgaatctttgaacgcacattgcgcccggtggcattccgccgggcatgcctgttcga
gcgtcattacaccactccagc-ctggctggg-tattgggcg-tcgcg----gggt-----
ccc---cgcgcgcctcgaagtct-c--cggccgagccg-tccgtctc-taagcgttgtga
tc-tat-caagccgcttgcgagctc-ggggggccgtcgcgccgttaaacgacc---atct
caaggttgacctcggatcaggtagggata---------------------
>Teratosphaeria_suberosa_AY725579 Teratosphaeria_suberosa_AY725579 700 bp 
------------------------------------------------------------
---------------------------------------------------------tcc
gtaggtgaacctgcggagggatcattacc-gagtga--gcgc-ctccgggcgc-------
ga---cctccaaccccatgtt-t-ccaa---ccatgttgcctcgggggcgacccggccgt
c------cggc-cgatcgcccccggtggacccc--tc---aactctgcatct-ttg-c-g
tcggagtc---taatgataaa---tcaatcaaaactttcaacaacggatctcttggttct
ggcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaa
tcatcgaatctttgaacgcacattgcgccccttggtattccgaggggcatgcctgttcga
gcgtcatttcaccactcaagc-ctcgcttgg-tattgggcg-ccgcg-----gtc-----
cgc---cgcgcgccccaatgt-t-c--cggctcagccc-aacgtcctcg-agcgatttga
ttacaa-tc--ccgctagca-ggca-cggagggcgcgacgccgctaaacaccc---catc
acaggttgacctcggatcaggta---------------------------
>Teratosphaeria_suberosa_DQ303046 Teratosphaeria_suberosa_DQ303046 700 bp 
------------------------------------------------------------
------------------------------------------------------------
----------------agggatcattacc-gagtga--gcgc-ctccgggcgc-------
ga---cctccaaccccatgttat-ccaa---ccatgttgcctcgggggcgacccggccgt
c------cggc-cgatcgcccccggtggacccc--tc---aactctgcatct-ttg-c-g
tcggagtc---taatgataaa---tcaatcaaaactttcaacaacggatctcttggttct
ggcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaa
tcatcgaatctttgaacgcacattgcgccccttggtattccgaggggcatgcctgttcga
gcgtcatttcaccactcaagc-ctcgcttgg-tattgggcg-ccgcg-----gtc-----
cgc---cgcgcgccccaatgtct-c--cggctcagccc-aacgtcctcgaagcgatttga
ttacaa-tc--ccgctagca-ggca-cggagggcgcgacgccgctaaacaccc---catc
acaggttgacctcggatcaggta---------------------------
