>SEQ0
atctactggagccgggcgagacacatggcatccgacttagtcaattcaaactgatcttcc
gtagtaaacgcattaccggctcttcacggatcagtgcatacgttcatagaacatagcagc
cgatgctggactcagcgcccttggtcccagtagccctggtttactgggcatcccaagcaa
ctctaacgcccttcttccatcgccttggctagaataggtaccacagagctaacgaaagag
gagggcttcaccggctctatcagatcatattaaatcagctggtgttagctaagggttctg
tagcaagctaagaagttaggtgagttccattcagggattatagattacctttaccactag
tgctactttggattgcatgctagataaagagagtatcttgttgtttggctgtctctggcg
tagcttcgcgagcatagctttccataggaacactcttcctgtaccccggggttggagtaa
ggttgacaacgaatgtaccattactgtttgggccgcgtaacacaaaaacataatcgcgtg
cgtggtgggaacacggggaagaaagtagctccagtaaaagtttgggtcatcatcggggcg
tgggtctggaccactggcgaggagggctattcagtaaaaaagcagtacgcaatttgccat
gacgcgtaaggaacaccgttgatctagtattacgtttagacatagctggacgcttgaacg
tttgctatcgacagctagagttccaatagagcatta--ccgagatggcacgaatcgcaag
tacgctcattcggtcagttaggcgacggcccggatgcacggcgaacctacggcatgacca
tttcgatgaatcccctccgttttcgagtacatggatcgcggagtggaacctatagctaca
atgacgaccgataaaccatcctgccgaatcccactgaaatgtgttatagcaaacttcgag
atagagtgcagagtcaactaaggaaatttaggaaagcacaaatgatggttctctctgcag
agtagaggcagttctagtagctcacaaactaaatcgaccctcttggacctcagtggtgct
agttcgacatgacatgtattac
>SEQ1
ttcttctggagccgggcgacacacaaggcatccgacttagtcaattcacactgatctgcc
gtagtaagcgcatttccggctctacacggatcagtgcttacgttcatataacatagcagc
cgatgctggactcagcgcccttggtcccagttgtcctggtttactgtgccgcccaagcaa
ttttaacgcccttctcccaacgccttggctagaataggtaccacagagctaacgaaagag
cagggcttcacgggctctatcagagcatattaaatcagctggtgttagctaagggttctg
taggaagctcaaaagttaggtgagttccgttcagggattatagattacctttaccactag
tgctgctttagattgcatgctagctaaagagagtatcttgttgtttggctgtctctggcg
tatcttagcgagcatagctttccataggaacattcttcctgaaccccggggttagagcaa
ggttgacaacgaatgt----ttactgtttgggccgcgtaacacaaaaacataatcgcgtg
cgtggtgggaacacggggaagaaagtagctccagtaaaagtttgggtcagcatcggggcg
tgggtctcgatcactggcgtggagggctattcagtaaaaaaacagtccgcaatttgccat
gacgcgtaaggaacagcgtagatttagtattacgtttagacgt-----------------
-----------cagctagagttccagtagagcatta--ccgagatggcgcgaatcgcaag
tacgctcattcggtcagttaggcgacggcccggatgcacggcgaacctacggcatgacca
tttcgatgaatcccctccgttttcgagtacatggatcgcggagtggaacctatagcgaca
atgacgacagatataccatccaggcgaatcgcattgaaatgtgttatagcaagattcgag
atagagtgca-------------------tggaaaacaccaatgatggttctctctgcag
agtagaggaagttctagtagctcacaaactaaatcgaccctcttggacgtcagtggtgct
tgttcgacatgacaagtatgcc
>SEQ2
atctactggagccgggcgagatacctggcagccgcctaattcaattctcattgatcttcc
gtagtagacgcataacctgctgttctcggatcagtgcatacgttcatagaccatagcaga
ccatgctggactcagcgcccttcgtcccagtagccccggtttactgggcatcccaagcaa
ctctaacgcccttcttccatcgccttggctagaataggtaccacagagctaacgaaagag
gagggcttcaccggcactatcagatcatattaaatcagctggtgttagctaagggttctg
taggaagctcaaaagataggggagttccgttgagggattattgataacctttaccactag
tgcaggttcaccttgcatgctagctaatgagagtatcgtgttaatcggctgtatccggcg
tatctaagcgagcatagcttttcataggaacattcttcctgaaccccggggttagagcaa
ggttgacaatgaatgg----ttactgtttgggccgcgtaacacaaaaacataatcgcgtg
cgtggtgggaacacggggaagaaagtagctccagtaaaagtttgggtcagcatcggggcg
tgggtctcgttcactgacgtggagggctattcagta---------------------cat
gacgcataaggaacag--------------------------------------------
-----------cagctagagttccactagagcatta--ccgacatggcgggaatcgc---
-----------------ttaggcgacggcccggatgcacggcgaacctacggcatgacca
tttcgatgaatcccctccgttttcgagtacatggatcgcggagtggaacctatagcgaca
atgacgagcgataaaccatcctgccgaatcccactgaaatgtgtaatagcaaacttcgag
atagagtgcagagtcaactatgg--------------------gatggttctctctgcag
agtagaggcagtt-----------------------------------------------
-----------acctgttttag
>SEQ3
atctactggagccgcgcgagatacctgtcagccgcctagtt------------atcttcc
gtagacgacgcataacctgctgttctcagatcagtgcatacgttcatagaccacataaga
cgatgctggactcagcccccttcgt-----------------------------------
ctctaacgcccttcttccatcgccttggctagaataggtaccacagagctaacgaaagag
gagagcttcaccggcactgtcagaccatattaaatcagctggtgttagctaagggttctg
taagaagatcaaaagttaggtga-------------attatcgattacctttacca----
----------------atgcaaggtaaagagagtatcttgttgcttgtctgtctctggcg
tatcttagcgagcatagctttccataggaacattcttcctgaaccccggggttagagcaa
ggttgacaccgaatgt----ttactgtttgggccgcgtaacacaaaaacataatcgcgtg
cgtggtgggaacacggggaagaaagtagctccagtaaaagtttgggtcatcatcggggcg
tgggtctcgttcactcacatggagagctattcagta---------------------aat
gacgcataacgaac----------------------------------------------
-----------cacctagagttccactagtgcatta--ccgacacagcg-----------
----------------gttaggcgacggcccggatgcacggcgaacctacggcatgacca
tttcgatgaatcccctccgttttcgagtacatggatcgcggagtggaacctatagctaca
atgacgacagaaatagcatccagccggttcgcattgaaatgtgttgtagcaagatccgag
atagagtgca-------------------tggataacaccaatgacggctctccctgcag
agtagaggaagttttattagctcacaaacttaatcgaccctcttggacgtcagtggtgct
tgttagacatgacaagtatgcc
>SEQ4
ttctactggagacgggcgagatccctggaagc-------------------------tcc
gtggtagacgcataacctgctgttctcgg-------------------------agcaga
ccatgctggactcagcgcccttcgtcccagtagccccggtttactgggcaacgcaagcaa
ctctaacgaccttcctccatcgccttggctagaataggtacctcagagctaacgaaagag
cagggcttcacgggctctatcagagcatattaaatcagctggtgttagctaagggttctg
taagaagatcaaaaat--------------------attagcaatgacctttacca----
----------------atgtaaggtaa-------------------gtctgtctctggcg
tgtcttagcgagcatagctttccataggaaaattcttcctgaacccgggggttagagcaa
ggttgacaccgaatcc----ttactgtttgggccgcgtaacacaaaaacataatcgcgtg
cgtggtgggaacacggggaagaaagtagctccagtaaaagtttgggtcagcatcggtgcg
tgggtctcgattactggcgtagagggctattcagtaaaaaaacagtccccaatttgccat
gaccggtaaggaacagtccagatttggacttacgtttacatgt-----------------
-----------ccgctacagttccagtagagcatta--ctgagatggcgagacccgca--
----------------agtacgcgacgtcccggatgcacggagaacctacggcatgacca
tttcgatgaatcccctccgttttcgagtacatggatcgcggagtggaacctatagctaca
atgtcgaccgataaaccaacctaccgaatcccactgaaatgtgttatagcaaacttcggg
atagagtgcagagtcaactaaggaaatttaggaaagcacaaatgatggtgctctctgcag
agtagaggcggttctagtagctcacaaactaaatcgacccacttggacctcagtggtgct
agttcgacatgacatgtattac
>SEQ5
atctcctggagccgggagagatacctgtgagc-------------------------cgc
ctagtagacgcataacgtgccgttctcggatgagttcatacgttcataggcgataggaga
ccatgctggactcagcgcgcttcgtcccagtagccccggtttactgggcattccaagcaa
ctcttacgcccttcttccatcgccttggctagaataggtacctcagagctaacgaaagag
cagggcttcacgggcactatcagagcatattaaatcagctggtgttagctaagggttctg
tagcacgctaagaagttatgtgagttccattcagggattatagattaacttcaccactag
tgctactttgaattgcatgctagataaagagtgaaacttgttg-----------ttggct
tagcttcgcgagcatacctttccatagtaacactcttcctgtaccccggggttggaataa
ggttgacaacgaatgtaccattactgtttgggccgcgtaacacaaaaacataatcgcgtg
cgtggtgggaacacggggaagaaagtagctccagtaaaagtttgggtcagcatcggtgcg
tgggt---------------------ctattcaataaaacaacagtccccaatttgccat
gacgcgtaaggaacagcgtacgtttag---------------------------------
-----------caactagagtgccagtagaggatta--ctgagaaggcgctagtcgca--
----------------actacgcgacgtcccggatgcacggagaacctacggcatgacca
tttcgatgaatcccctccattttcgagtacatggatcgcggagtggaacctatagctaca
atgacgag------------------------gctgaaatgtgtaatagcaaacttcgag
atagagtgcagagtcaactatgg--------------------gatgattctctctgcac
cgtggaggcagtttt---------------------------------------------
----------------ttttag
>SEQ6
atcgactggacccgggcgagatacctagcagccgcctaattctattctcattgatattcc
gtagtagacgcatagcctgctgttctcggatcagtacatacgttcatagaccttagaaga
ccatg-------------------------------------------------------
-------------catccatcgcgttggctagaataggtaccacagagctaacgaaagag
gagggcttcaccggctctatcagatcatattaaatcagctggtgttagctaagggttctg
taggacgcgctaaagatagttaagttccgttgcgggattattgataacctttaccactag
tgcaggttcagcttgcatgccagctaatgagaggatcgtgttaatcggctgtatccggcg
tatctaggcgagcgtagcttttcataggaacattcttccggccccccggggttacagcaa
ggttgagaatgaatgg----ttactgtttgggccgcgtaacacaaaaacataatcgcgtg
cgtggtgggaacacggggaagaaagtagctccagtaaaagtttgggtcagcatcggggcg
tg------------------------ctattcagtaaacaaacagtccgcgatttgccat
------------------------------------------------------------
---------------tagtattacgtttagacatcagcccgagatggcgcgaatcgcaag
tacgctcattcggtccgttaggcgacgtcccggatgcacggagaacctacggcatgacca
tttcgatgaatcccctccattttcgagtacatggatcgcggagtggaacctatagctaca
atgacggg------------------------gctgaaatgtgtaatagcaaacttcgag
gtagagtgcagagtcaactat----------------------gatgattatctctgcac
cgtggaggcagtctt---------------------------------------------
----------------tattag
>SEQ7
atctcctagacccgggagagatacctgtaaga-------------------------cgc
ctagtagacgcataacgtgcggtactcggatgagtccatacatacataggcgataggaga
ccatgctgggctcagcgcgcttcgtcccagtagccacggtttactggggattccaagcaa
ctcttacgcccatcttccatcgccttggctagaataggtacctcagagctaacgaaagag
cagggcttcaccggctctatcagagcatattaaatcagctggtgttagctaagggttctg
taggacgcgctacacatagttaagttcggttgcgggattattgataacctttaccactag
tgcaggttcagcttgcatgtcagttaataagaggatcgtgttaatcggcgctatccgggg
tttctaggcgagc-------------------ttattccggcccgccgcggtcatagcaa
ggttgacaatgactgg----ttactgtttgggccgcgtaacacaaaaacataatcgcgtg
cgtggtgggaacacggggaagaaagtagctccagtaaaagtttgggtcatcatcggggcg
tgggtctcgttcactcacatggagagctgttcggtg------------------------
-acgcataatgaac----------------------------------------------
-----------cacctagagtttcactagtgcatta--ccgacacagcg-----------
----------------gttaggcgacggcccggatgcacggcggacctacggcatgacca
tttcgatgagtcccctccgttctcgagtacatggatcgcggagtggaacctatagcgaca
atgacgagcgataaaccatcctgccgaatcccactgaaatgtgtaatagcaatcttcgag
ataaagcgcagaatgatctatgg--------------------------------tgcag
agtagaggcagtt-----------------------------------------------
-----------aactgttttag
>SEQ8
tcctactggaatcggccgagatccctggaaac-------------------------tcc
gtggtagacgcaaaacctgttgttctaga-------------------------agcaga
tcatgctcaactcagcgcccttcgtaccagtagccccggtgtactaggcaacgcaagcaa
gtctaacgaccttcctccctcgccttggctagaataggtaccaccgagctaacgaaagag
gagggcttcaccggctctatcagatcatattaaatcagctggtgttagctaagggttctg
taca--------------------------------------------------------
------------------------------------cttgttgcttgtctgtctctggcg
aatcttagcgagcatagctttgcataggaacgttctggctgaaccccggggttagagcga
ggttgacaccgaatgt----ttactgtttgggccgcgtaacacaaaaacataatcgcgtg
cgtggtgggaacacggggaagaaagtagctccagtaaaagtttgggtcatcatcggggcg
tgggtctcgttctctgtcttagagggctaatcagta---------------------cat
gacgcatacggta-----------------------------------------------
-----------cagctagggttcccctagagcataa--ccgacatggcgggaatcgc---
-----------------ttaggcgacgtcccggatgcacggagaacctacggcatgacca
tttcgatgaatcccctccattttcgagtacatggatcgcggagcggaacctatagctaca
atgacgacag-----------------------ttgaaatgtgtta--------------
----agtgca-------------------tggaaaacaccaatgatggtt----------
--------aagttctagtagctcacaaactaaatcggccctcttggacgtcagtggtgct
agttcgacatgacaagtatgcc
>SEQ9
ttctactggaggcgggcgagatcactggaagc-------------------------tcc
gtggtagacgcact----------------------------------------------
-------------------------------------------------------tgttt
actagacaacctttatccatcgccttggctagaataggtaccacagagctaacgaaagag
gacagcttcaccggcactgtcagaccatattaaatcagctggtgttagctaagggttctg
taggacgcgctacacattgttaatttcggtggcgggattatagctaacctttaccactag
t-------------------cagttaataagaggatcgtgttaatcggcgctgtccgg--
------------------------------------------------------gagcaa
ggtagacaatgactgg----ttactgtttgggccgcgtaacacaaaaacataatcgcgtg
cgtggtgcgaacacggggaagaaagtagctccagtaaaagtttgggtcagcatcggggcg
-------------gtcacatggagagctgttcgttg------------------------
-acgcaaaatgaac----------------------------------------------
-----------cacctagagttacactagtgcatta--ccaacacagcg-----------
----------------gttaggcgacgtcccggatgcacggagaacctacggcatgacca
tttcgatgaatcccctccattttcgagtacatggatcgcggagtggaacctatagctaca
atgacgag------------------------gctgaattgtgtaatatctaacttagag
atagcgcgcagagtcaaccatgg--------------------gatgattctctct----
------------------------------------------------------------
------------tttttttcag
>SEQ10
ttctactgcaggcgggcgagatcataggaagc-------------------------ttc
gtggtagacgcat-----------------------------------------------
--------------------------------------------------------gttt
atttgagaacctttatccatcgccttggctagaataggtaccacagagctaacgaaagag
gagagcttcaccggcactgtcagaccatattaaatcagctggtgttagctaagggttctt
taggaaactcaaaagaaaggggagttccgttgaggtattatggatcagctttaccactag
tggaggttcacctagcatgctaggtattgagagtatcgtgttaatcggctgtttccggcg
tatct----------------------------------------------ttacagaaa
tgttgacactgaatgg----ttactgcttgggccgcgtaacacaaaaacataatcgcgtg
cgtggtgggaacacggggaagaaagtagctccagtaaaagtttgggtcatcatcggggcg
tg------------------------ctattcagtaaacaaacagtccccgctttgccag
------------------------------------------------------------
---------------tcgtattacgtttacacat------gagatggcgcgaatcgcaac
tacgctcattcggtgggttaggcgacggcccggatgcacggcgaacctacggcatgacca
tttcgatgaatcccctccgttttcgagtacatggatcgcggagtggaacctatagctaca
atggcgacag-----------------------tttaaacgtgtta--------------
----agtgca-------------------tggaacaaaccactgatagc-----------
---------------------tcacaacctaaatcggcccttttgggcggcagtggtgct
agttcgacaggacaagtatgcc
>SEQ11
ttcttttagagccgggcgacacacaaggcaaccgatttagtca-----------------
--agtaagcgctttaccggctctacacggatcag------------------atagcagc
cgatgctggact---------------cagttgtcctggttggctgtgccgccgaagcaa
atttacagcccttttcccaacgccttggctagaataggtaccacagagataacgaaagag
gagagcttcaccggcactgtcagaccatattaaatcagctggtgttagctaagggttctg
ttagaagatcgaaagttcggt-------------gaattatcgattatctttaccat---
-----------------tgcaaggtaaagagattatcttgttgcttgtctgtctctggcg
tatcttagcgaggatagctttccac------------------ccccggggttagatcaa
ggttgacaccgactga----ttactgtttgggccgcgtaacacaaaaacataatcgcgtg
cgtggtgggaacacggggaagaaagtagctccagtaaaagtttgggtcatcatcggggca
tgggtctcgaccactggcg-------------------------gtccgcaacttgccat
gacgcgtaaggaacaacgtagatttagtattacgtttagacat-----------------
-----------aatctagagttcctgttgagcatta--ccgagatggctcgaatcgcaag
tgcgctcattcggtcagttcggcgacgtcccggatgcacggagaacctacggcatgacca
tttcgatgaatccgctccattgtcgagtacagggatcgcggagtggaacctatagctaca
atgacaagcgataatccatcctgccgaatccaactgaaacgtgtaatcgcacacttcgag
ttagagcgcacagtcaactatgg--------------------aatggttctctctgcag
tgtggaggcagtt-----------------------------------------------
-----------acctgttttag
>SEQ12
tcctaccggaatcggccgagagcccttgaaac-------------------------tcc
gtggtaaacgcaaaacttgttgctctaga-------------------------agcaga
tcatgctcaactccgcgccattcgtaccagtagccccggtgtactagacaacgcaagcgt
gtctaacgaccttcctccctcgccttggctagaataggtacctcagagctaacgaaagag
cagggcttcaagggctctatcagagcatattaaatcagctggtgttagctaagggttctg
tagcaagctacgaagtttcgtgcgttccattcagggattatcgattaacttcaacactag
tgctactttgaattgcata---------------------------acttgttgttggct
tagcatcgcgaacatacctgtcaatagtaacactctt-------------------gtaa
ggttg---------------ttactgtttgggccgcgtaacacaaaaacataatcgcgtg
cgtggtgggaacacggggaagaaagtagctccagtaaaagtttgggtcagcatcggggcg
tg------------------------cttttcagtaaacaaacagtccgcgatatgccat
------------------------------------------------------------
---------------aagtattacgtttagacatcagcccgagaaggcacgaatcgcaag
tacgctcattcggtccgttaggcgacggcccggatgcacggcgaacctacggcatgacca
tttcgatgaatcccctccgttttcgagtacatggatcgcggagtggaacctatagctaca
atgaccacag-----------------------ttgaaatttgtta--------------
----agtgca-------------------tcgaaaacaccaatgacggt-----------
----------------gtagctcacaaagtaaatcggccctcttggacgtcagtggtgct
agtttgatatgacaagtatgcc
>SEQ13
gtcttttagagacgggcgatacacatggcaaccgatttaatcaagtcagcggatccgata
gcagcagatgc-------------------------------------------------
---------------------tggactcatttgacctggttggctgtgccgccgaagtaa
attta-----------cagccgccttggctagaataggtaccacagagctaacgaaagag
gagagcttcaccggcactgtcagaccatattaaatcagctggtgttagctaagggttctt
tgggacgcgctacacatagttaagttcggttgcgggatgatttagaacctttaccactag
tgcaggttcaatc-------------ataagaggatcatgataatcggcgctatacgggg
tatctaggcgagc-------------------ttattccggccggccgcggtca------
--------------------ttactgtttgggccgcgtaacacaaaaacataatcgcgtg
cgtggtgggaacacggggaagaaagtagctccagtaaaagtttgggtcatcatcggggct
tggggctcgttcacta-----------------------------------------cat
gacgcataaggaacca--------------------------------------------
-----------cagcttaagttccattagaacatta--ccgaaatggcgggaatcg----
----------------attaggcgacgtcccggatgcacggagaacctacggcatgacca
tttcgatgaatcccctccattttcgagtacatggatcgcggagtggaacctatagctaca
atgacgag------------------------gctgaatcgtgtaacatctaacttagag
atagtttgat--------------------------------------------------
------------------------------------------------------------
-----tctatgtttgttttcag
>SEQ14
atcgcctagacccgggagagatacccgtaata-------------------------cgc
ctagtagacgcacaacctgcggtactcggatgagtccttccatacataggc---------
--------ggctcaccgcgcttcgtcccagtagccacggtttattggggattccaagcaa
ctattacgcccattttccatcgccttggctagaataggtacctcagagctaacgaaagtg
cagggcttcacgggctctatcagagcacattaaatcagctggtgttagctaagggttctg
t-----------------------------------------------------------
------------------------------------cgtgttgcttgtctgtctctggcg
aaccc-------------------------------------------------------
--------cggggtgt----ttactgtttgggccgcgtaacacaaaaacataatcgcgtg
cgtggtgggaacacggggaagaaagtagctccagtaaaagtttgggtcatcatcggggca
tgg------------------------tattcagtaaacaaatagtgcgcgatttgctat
------------------------------------------------------------
---------------tagtattacgtttagacatcagacgcagatggcgcgaa-------
------caatcggtccgttaggcgacgtcccggatgcacggagaacctacggcatgacca
tttcgatgaatcccctccattttcgagtacatgcatcgcggagcggaacctatagctaca
atgccgagag-----------------------tttaagcgtgtta--------------
----agtgca---------------------------------aatgat-----------
--------------------------------atcggcccttttttgcggccgttgtgc-
----------------------
>SEQ15
atctactggagccgctcagccgactagtaatc------------------------ttcc
gtagacggcggataacctgccgttctcagatcagtgcatacgttcatagaccacataaga
cgaagctggactc------------------------------------------agccc
ctctaaagcccctctt------ccatcgctagaataggtacctcagagctaacgaaagtg
cagggcttcacgggctctatcagagcacattaaatcagctggtgttagctaagggttctg
tagcaagcta------------------attcagggattatcgactaacttcaacactag
tgctactttgaattgaata---------------------------acttgttgttggtt
tagcatcgcgagtaacacactt----------------------------------gtaa
ggttg---------------ttactgtttggggcgcgtaacacaaaaacataatcgcgtg
cctggtgggaacacggggaagaaagtagctccagtaaaagtttgggtcagcatcggggcg
tgggtctcgtgcacttacgtgcggggctatttagta---------------------cat
gacgcataatgaatag--------------------------------------------
-------------------gttcctcgcgggaatcc------------------------
----------------cttaggcgacggcccggatgcacggcgaacctacggcatgacca
tttcgatgaatcccctccgtttgcgagtacatggatcgcggagtggaacctatagctaca
atggcgagtg-----------------------tttaagcgtgttt--------------
----agtgca---------------------------------tatgat-----------
--------------------------------atcaggccttttttgcggccggtgtgg-
----------------------
>SEQ16
ttatactgcaggcgggcgagatcataggaagc-------------------------tcg
gtggta------------------------------------------------------
-------------------------------------------------------tgttt
atttcggaacctttatccatcgccttggctagaataggtaccacagagctaacgaaagag
cagggcttcacgggctctatcagagcatattaaatcagctggtgttagctaagggttctg
tagcaagctacgaagtg-------------tcatggattatcgatcaatttcaacactag
tgcgcatac--------------------------------------cttgttgttgact
tagcatctcgaacatacctgtcaattgaaacactctt-------------------gtaa
ggttg---------------ttactgtttggggcgcgtaacacaaaaacataatcgcgtg
cctggtgtgaccacggggaagaaagtagctccagtaaaagtttgggtcagcatcggggcg
tg------------------------ctatgcagtaaacaagcggtccccgctttgacag
------------------------------------------------------------
---------------tcgtatttcgtt------------------ggcgcgaatcgcaac
ttcgctgattcggtgggttaggcgacgtcccggatgcacggagaacctacggcatgacca
tttcgatgaatccgctccattgtcgagtacagggatcgtggagtggaacctatagctaca
atgccaaccgataaaccaacctaccgaatcccaatgaaatctgtt---------------
--------cagagtcaactaaagaaattgaggaaggcacaaatgaaggtgatctctgcag
actagagggggttctagtagttcacaa-----------------------cagtggtgct
agttcgacatgaactgtattac
>SEQ17
ttcttctggagccgggcgacacacagggcatccgacttagtcaattcagactgatctgcc
gtagtaagcgcatttgcggctctacacggagcagtacttacgttcatatgatatagcagc
cgctgt--------------------------gtcttggtttattgtgccgcccaagcta
ttttaacgcccttctcccaacgccttggctagaataggtacctcagagctaacgaaagag
cagggcttcacgggcactatcagagcatattaaatcagctggtgttagctaagggttcta
tagcaagctaagaagtaaggtgagttccattcagggattatagattacctctacctctag
agctactttggatcgcatgctagataaagagagtatcttgttgtttggctgtctctggcg
tagcttcgcgagcatagctttccataggaacactcttcctgcaccctggggttggagtaa
ggttgacaaggaatgtaccattactgtttgggccgcgtaacacaaaaacataatcgcgtg
cgtggtgggaacacggggaagaaagtagctccagtaaaagtttgggtcagcatcggtgcg
tgg---------------------------tcggtaaacaatccgtcgccgctatgccag
------------------------------------------------------------
----------------------------------------gagatggagcaaatcgcaac
tacgctcattcggggggttaggcgacgtcccggatgcacggagaacctacggcatgacca
tttcgatgaatccccgccattttcgagtacatggatcgcggagtggaacctatagctaca
atgtcgagcgatgaacca------------------aaaagtgttatagcaaacttcggg
atagagtgcagaact----------------------------gatggtgccctctgaag
agtagaggcggttctagtagctcatacactaaatcgacccacttgggcctcagtggtgct
agttcaacatgacaggtattac
>SEQ18
atcggctagacccgggagagataactgaaata----------------------------
ctagttgacgcacaacctgcggta------------------------------------
----aggcggctcaccgcgcttcgtcccagtagca-------------------------
-----------------catcgccttggctagaataggtaccacagagctaacgaaaggg
gagggctttaccggctctatcagatcatattaaatcagctggtgttagctaagggttctg
taggacgcgctaaag-------------gttgccggatttttgataacctctaccgctag
tgcaggtacagcttgcatgccagctaacgagaggatcgtgttgatcggctgtatccggcg
tatctaggcgagcgtagcttttcatcggaacattcttccggccccgcggggttacagcaa
ggttgggaatgaattg----ttactgtttgggccgcgtaacacaaaaacataatcgcgtg
cgtggtgggaacacggggaagaaagtagctccagtaaaagtttgggtcatcatcggggc-
------------------------tgctgttcgttg------------------------
-acgcaaaacgaac----------------------------------------------
-----------caccgagagttacactcgtgcatta--acaacacagcg-----------
----------------gttaggcgacggcccggatgcacggcgaacctacggcatgacca
tttcgatgaatcccctccgttttcgagtacatggatcgcggagtggaacctataactaca
atgaaggg------------------------gctgaaatgagtaata------------
-------gcagagtcaactct----------------------gaggattatctatgctc
cgtggagggtgtcta---------------------------------------------
----------------tactag
>SEQ19
ttctactggaggcgggcgagatcactggaagc-------------------------tcc
gtggtagacacac-----------------------------------------------
------------------------------------------------------------
--------tccttcatccatcgccttggctagaataggtaccacagagctaacgaaagag
cagggcttcacgggctctttcagagcatattaaatcagctggtgttagctaagggttctg
tagcatgcta------------------attcagggattatcctttaacttcgacactag
tggtactttgaattgaata---------------------------aattgttcttggtt
tagcatcgcgagtaatacactt----------------------------------gtca
ggttg---------------ttactgtttgggccgcgtatcacaaaaacataatcgcgtg
cgtggtgggaacacggggaagaaagtagctccagtaaaagtttgggtcatcatcggggca
tgggtctcgattactggcgtagagggctattcagtaaaaaaacattccgcaatttgccat
gaccggtaaggaacagtccagatttgga--------------------------------
-----------ccgctacagttccagtagagcattt--ctgagatggcgggacccgca--
----------------agtacgcgacgtcccggatgcacggagaacctacggcatgacca
tttcgatgaatcccctccattttcgagtacatgcatcgcggagcggaacctatagctaca
atgctgagagacataccgtccaggctaatcgcattcaaatgtgttatcgcaagtttcgag
atagagtgca-------------------------------atgatggctctctctgcag
agtagaggaagtg---------------------cgaccctcttggacgtcagtggtgct
tgttccacattacaagtatgcc
