>SEQ0
ttaggataaactaacgtccgtcagctccatgcgaataccgcgtcttggcatacctgggct
caatcaccttacgtaaattactcggactctctctagcaaaaatcgcctgctacaaaagtt
ctactcacgagttcgagcgcagtgatctccatctcaatgctcccaggagcacccaaatgc
tattcgggtgtgaggtgcagtccttctgaatacaaacttcttcagtgatcatccgctcga
gcggatccagacctatctatgcgccctacttaagtatttaatgtgcgccctcccacgata
gtgcagaccacataccggccgacttgccaggctttcagaattccgacgatccgatgtcta
ggtggtgccaagaccacgtgcacaaaataagcaaacgatggcgcatgtacgtcgctctct
ctgttgtagtgtattgcaggattacgcggctactttcagagaccagactgtcctgcagat
cgtttatacaggagttgtggtgcccgttatccggctcgtaattgtggacggacctgagta
attgtcttgccgaaactgcctgaaaagccgcgtattgcaagagtgggttgcataagagta
tcagctgggccgaccccggagtcctatttaatctgacgcatacgttgatgcgggttatct
ggcctaagccatactaaactagttaaccgctactaaagtccgtcactacccgaagaatag
ttggactaatctctaaactaagcccgaaaccaaacctcgattcgttgcttgattttctag
tcttgaccgccggttgccgcctgtggcgttcacctctcgtagccagcccaaatttgctag
cgttgtccgatcgctgcgtgtttgctaccgttcgactgccgggagggatatcgctttgaa
tccaccccaaacgtctgtaaggaccattcggatcagcacagctttgcttttgtggacgct
agataggtaacacctcgcagcaccccagtccctgaagaccattcagtagatccttccggt
ttattcaaactagtatatcctcttgacacggagtgggtcagataggcagctaattcttgc
atccatggttgtcagtggac
>SEQ1
ttaagataaactaacgtccgtcagctccatgcgaataccgcgtcttggcataactgggct
caatcaccttacgtaaattactcggactctctctagccaaaatggcctgctcaaaaagtt
ctactcacgagtttgatcgcagtgatgtccatctcaatggtcc-----------------
--------tgtgagctgcagtccttctgaatacaaacttcttcagtgatcatccgctcga
gcggatccagacctatctatgcgccctacttaagtatttaatgtgcgccctcccacgata
gtgcagaccacataccggccgacttgctaggctttcagaattctgac-------------
------gccaagaccaccttcacaaaatatgcaaacgatggcacatgtacttcgctatct
ctgttgtagtgaattgcgggattacgcggttac---------------------------
----------ggagttgtggtgcccgttatccggctcgtaattgtggacggacctgagta
attgtcttgccgaaactgcctgaaaagccgcgtattgcaagagtgggttgcataagagta
tcagctgggccgaccccggcgttcgatttaatc------------------------ttt
ggcctaagccatactaaactagttaaccgctaataaagtccgtcactacccaaagaatag
ttggactactttctaaacaaagccccaaaccaagccacgattccttgcttgaaggtctag
tcttgaccaccggttgccgcctgtggcgttcacctctcgtagccagcccaaatttgctag
cgttgtccgatcgctgcgtgtttgctaccgttcgactgccgggagggatatcgctttgaa
tccaccccaaacgtctttaaggaccattcggatccgcacagctttggttttgtg------
--------------tcgcagcaccccagtccctgaagcccattaattagatccttccggt
ttattcaagctagtatatcctcttgagatggagtgggtcagataggcagctaattcttgc
atctatggttgtcatagg--
>SEQ2
ttaagattacgtaacgtccgtcacctccatgcgaataccgcgtctttgcataactgggcc
caatcaccttacgtaagttacacggactcgctctagccaaaatggcctgctcaaaaagtt
ctactcacgagtttgatcg-----------------------------------------
---------atggtcgtcagtccttctgaatacaaacttcttcggtgatcatccgctcga
gcggatccagacctatctatgcgccctacttaagtatttaatgtgcgccctcccacgata
gtgcagaccacataccggcctacttgctaggctttcagaattctgac-------------
------gccaagaccaccttcacaa-----------------ccatgtgtttcgctatct
ctgttgtagtgaattgcgggattaccccgttac---------------------------
----------ggagtcggggtgcccgttatccggctcgtaattgtggacggacctgagta
attgtcttgccgaaactgcctgaaaagccgcgtattgcaagagtgggttgcatacgagta
tcagctggaccgacgccggcgtttgacttaatc------------------------ttt
ggcctaagccatactaaactggttaaccgctaataaaaaccgtcactaccctaagaactg
ttggtctactgtcttaacaaag-----------------------------------tag
tcttgaccaccggatgccacctgtggcgttcacctctcgtagccagcccaaatttgctag
cgttgtccgatcgctgcgtgtttgctaccgttcgactgccgggagggatatcgctttgaa
tccaccccaaacgtctgtagggaccagtcggatcagcacagatttgcttatgtggacgct
agacaggtaacacctcgcagcaccccagtccctgaagaccattcagtagatccttccggt
ttattcaaactagtagatcccctccacacggagtgggtcagataggtagctaattcttgc
atccatggttgtcagtggag
>SEQ3
--------------tttacataaactaactgcgaataccgcctcttggcataactgggcg
caatcaccttacgtaaattactcggactctctctaggcaaaatggccggctcaaaaagtt
ctactcaggagtttgatcgcagtgattgccatcgcaatggtgt-----------------
--------tgtgacctgcagtccttctgaatacaaacttcttcagtgatcatccgctcga
gcggatccagacctatctatgcgccctacttaagtatttaatgtgcgccctcccacgata
gtgcagaccacttaccggcccacttgccaggcttacagacttccggc-------------
--------caaggccatgtgcacaaaa----------------------------tatta
tcacagatcgtatataca------------------------------------------
----------ggagtagtcgtgcccgttatccgactcgtaattgtggacggacctgagaa
attgtcttgccgaaactgcctgaaaagccgcgtattgcaagagtgggttgcatacgagta
tcagctggttcgacgcctgcttatgactaaatc------------------------ttt
ggcctaagcca------------tagccggtaataaaaatcgtaactaccctaagaactg
ttggtctactgtcttaacgatg-----------------------------------tag
tcttgaccaccggatgccacctgtggcgttcacctctcgtagccagcccaaatttgctag
cgttgtccgatcgctgcgtgtttgctaccgttcgactgccgggagggatatcgctttgaa
tccacccccagcgtctgtaagga-----------------gctttggttttgtg------
--------------tcgcagcaccccagtccctgaactcgattaattagatcctatcggt
ttattcaagctagtatatcctcttgagatggagtgggtcacataggcagctacttcttgc
atctatggttgtcatagg--
>SEQ4
ttaggctaaactaacgtgcgtcagctccatgcgaataccgcggcttggcatacctggtct
caatcaccgtgcataaattactcggactgtctctagcaaaaatcgcctactataaaagat
ctactcacgagttcgagcgcagtcaactccatctcaatgctcccaggagcgcccaaatgc
tatgcg-----ggtgtgaggtccttctgaacacaaacttcttcactgatcatccgctcga
gcggatccagacctatctatgcgccctacttaagtatttactgtgcgccctcccacgata
gggcagaccacttaccggccgagttgctaggctttcaggattctgat-------------
------accaagagcaccttctcaaaatatgcaaacgatggcacatgtacttcgctatct
cggttgtgctgaattgcgggcttacgcggtgcc---------------------------
----------ggacttttggtgcccgttatccgactcgtaattgtggacggacctgagaa
attgtcttgccgaaactgcctgaaaagccgcgtattgcaagagggggttgcatacgagta
tcagctgattcgacgcctgcttatgactaaaac------------------------ttc
ggcctaagcca------------tagccgttaataaaaatcgtaactaccctaagaactg
ttcgtcaacagtcttaacga-------------------------------------tag
tcttgaccaccggatgccacctgtggcgttcacctctcgtagccagccccaatttgctag
cgttgtccgatcgctgcgtgtttgctaccgttcgactgccgggagggatatcgctttgaa
tacgccacaaacgtctgtaaggcccattcggatcagcacagctttgcttttgtgaacggt
agataggtaacacctcgcagcaccccagtccctgaagacctttcagtagatccttccggt
ttattcaaactagtatagcctcccgacaccgagtgtctcagaaaggcatctaattcttgc
atccatggttgtcagtggac
>SEQ5
ttaggctaaactaaagtgcgtcagctccatgcgaatacggcggcttggcatacctggact
caatcaccgtgcataaattactcgga----------------------------------
--------gagttccagcgcagtcaactccgtctcaaa----------------------
---------gcggtgtgaggtccttctgaatacgaacttcttcagtgatcatccgctcga
gcggatccagacctatctatgcgccctacttaactatttaatgtgcgccctcccacgata
gtgcagacgacataccggcctacttgctatgctttcagaattctgac-------------
------gaca--------------------------------------gtttcgctatct
ctgttgtagtgaattgcg------------------------------------------
----------ggagtcggggtgcccgttatccgactcgtaattgtggacggacctgagaa
attgtcttgccgaaactgcctgaaaagccgcgtattgcaagagggggttgcatacgagta
tcacctggttcgactcctgcttatgcctaaatc-------------------------tt
agccgaagcca------------tagccggtcataaaaatcctaactactctaagaactg
ttggtctactgtcttaacgatg-----------------------------------tag
tcttaactactgcatgccacctgtggcgttctcctctcgtagccagcccaaatttgctag
cgttgtccgatcgttgcgtgtttgctaccgttcgactgccgggagggatatcgctttgaa
tccacccctaacgtctgtagggaccagtcggatcaacgcagatttgcttaagtggacgct
agataggtaacacttcgcagcaccccagtccctgaacacaatgcagtagatcatgccggt
ttattcagactagtagaccccacccacacggagtgggtcagagtggtagctaattcttgc
atccatggttggcagtggac
>SEQ6
ttaggctaaact------------------------------------catgcctggact
caatcaccgtgcataaattcctcgga----------------------------------
------------tccggcgcattcaactccggcccaaa----------------------
---------gcggtgtgtggtccttctgaatacaaacttcttcagtgatcatccgcccga
gcggatccagacctatctatgcgccctacttaagtatttaatgtgcgccctcccacgata
gggcagaacacctacagcccgacttgctaggctttcagaattctgag-------------
------gcca------------caagatatgcaaacgatggcacatgtacttcgct----
----------------cggcattacgcggttac---------------------------
----------ggagttgtggtgcccgttatccggctcgtaattgtggacggacctgagta
attgtcttgccgaaactgcctgaaaagccgcgtattgcaagagtgggttgcatacgaata
tcagctgggtcgaccccggcgttcgatttcatc------------------------ttt
ggcctaagccataataaactagttaaccgcgaataaag---------------------g
ctggactactttctaaacaaagccccaaacc--------------------------tag
tcatgaccgccggttgccgactgtggcgttcacctctcgtagctagcccaaatttgctag
cgttgtccgatcgctgcgtgtttgctaccgttcgactgccgggagggatatcgctttgaa
tccgc---------------------------tcatcacagctttacttttgtgaacggt
agatagttaacacctcgcagcaccccagtccctgaagacctttcagtagatccttccggt
ttattcaaactagtatagcctcccgacaccgagtgtctccgagaggcttctaattcttgc
atcgatggtggtcaatggac
>SEQ7
ttagcctaaact------------------------------------catgcctggact
caa---------------------------------------------------------
------------tccggcacattcaactccggcccaaa----------------------
---------acggtgtgtggtccttctgaatacaaacttgttcagtgatcatccgctcga
gcggatccagacctatctatgcgccttacttaagtatttaatgtgcgccctcccacgata
gtgcagacgacatatcggcctacttgctaagcttacataattctgac-------------
------gaca--------------------------------------gtttcgctatcc
ctgttgtagtgacctgcg------------------------------------------
----------ggagtcggggtgcccgttatccggctcgtaattgtggacggacctgagta
attgtcttgccgaaactgcctgaaaagccgcgtattgcaagagtgggttgcatacgagta
tcagctggaccgacgccggcgtttggcttaatc---------------------------
-----tagtcatactaa-----------------aaataccgtcactagcctaagaactg
ttggtctactgtcttaacaaag--------------------------------------
--ttgaccaccggat-----ctgtggcgttcacctctcgtagccagcccaaatttgctag
cgttgtccgatcgctgcgtgtttgctaccgttcgactgccgggagggataccgctttgaa
tccaccccaaaagtctgtagggaccagtcggatcagcacaggtttgcttaagtggacgct
ggacaggtaactcctcgcagcacgacagtccctgaagaccactcagtagatccttccggt
ttaatcatacgagtagatcccctccacacggcgtgggtcagataggtagctaattcttgc
atcaatggttgtcagttaag
>SEQ8
ttaggataaactaccgtccgtcatctccatgagaataccgcgtgttgccatatatgg---
-------------------actcggactctctctagcattaatcgcctgctacacaagtt
cttgtcacaagttcgagcgcagtgtggtccatctcaatgctcccaggagcacccaaatgc
tattcgggtgtgaggtgcagtccttctgaatacaaacttcttcagtgatcatccgctcga
gcggatccggacctatctatgcgccctacttaagtatttaatgtgcgccctcccacgata
gggcagacgccatgccgaccgagttgctagggtctcaggtttctgat-------------
------accaagag----------------gcaaacgatggtacatgtacttcgctctct
cggttg------------------------------------------------------
----------ggacttttggtgcccgttatccggctcgtaattgtggacggacctgagta
attgtcttgccgaaactgcctgaaaagccgagtattgcaagagtgggttgcatacgagta
tcagctgtgtcttccccggcggtcgatttcatc---------------------------
-----------------------------------------tctagtccataataaacta
gtggactactttctaaacaaagccccgatcc--------------------------tag
tcatgaccgccggttgccgactgtggcgttcacctctcgtagctagcccaaatttgctag
cgttgtccgatcgctgcgtgtttgctaccgttcgactgccgggagggatatcgctttgaa
tccaccccaaacgtctttaaggaccattcgtatccgcacagctttggttttgtg------
--------------tcggagcaccccagtccctga---------------------cggt
ttattaaagctagtagatccaattgagatggagtgggtcacataggcagctaattctttc
atctagggttgtcat--agg
>SEQ9
--------------tttacataaactaactgcgaatgccgcctcttggcatgactgggcg
caatcaccttacgtaaattactcggcctctctctaggcaaaatggccggctcaaaaagtt
ctac------------------tgattgccatcgcaatggtct-----------------
--------tgtgacctgcagtccttctgaatacaaacttcttcggtgatcatccgctcga
gcggatccagacctatctatgcgccctacttaagtatttaatgtgcgccctcccacgata
gtgcagaccacttaccggcccacttgccaggcttacagacttccgaa-------------
-----------ggccatgtgcacaaaatcttatcac------------------------
------------------------------------------------------------
----------agatcgtagatgcccgttatccggctcgtaattgtggacggacctgagta
attgtcttgccgaaacggcctgaaaagccgcgtattccaagagtgggttgcataagagta
tcaggcggaccgacgccggcgtttgacttaatt------------------------ttt
ggt--------------------tagccgctaataaaaaccgtcgctaccctaaaa----
---------------------------------------------------------tag
tcttgacctccggatgccacctgtggcgttctcctctcgtagccagcccaaatttgctag
cgttgtccgaacgttgcgtgtttgctaccgttcgactgccgggagggatatcgctttgaa
cccacacctaacgtctgtagggaccagtcggatcaatacaaacctgctaaagtggaccct
acacagggaacacttcgcagcaccccagtccctgaacacaatgcagtagatcatgccggt
ttattcatacgagtagaccccacccacacggagtgggtgagagtggtagctacttcttgc
gcccatggttggcagtggag
>SEQ10
ttaagataaacttacat--------------cgaatgccgccgcttggcatgactgggcg
caatcaccttacataaattactcggcctctctctaggtaaaatggccggctcaaaaagtt
ctac------------------tgattgccatcacaatggtct-----------------
-------------------ttccttctgaatacaaacttcttcagtgatcatccgcccga
gcggatccagacctatctatgcgccctacttaagtatttaatgtgcgccctcccacgata
gggcagccgccatgccgaccgagttgctatggtctcgggtttctgat-------------
------accaagac----------------gcaaacgaa---------------------
------------------------------------------------------------
----------gggacagggatgcccgttatccgactcgtaattgtggacggacctgagaa
attgtcttgccgaaactgcctgaaaagccgcgtattgcaagagggggttgcatacgagta
tcagctgtttt-------------------------------------------------
------------------------------------------ctagtccataatcaactg
gtggactacttcctaaacaaagccccgagcc--------------------------tag
tcatgacagccggttgccgactgtggcgttctcctctcgtagccagcccaaatttgctag
cgttgtccgatcgttgcgtgtttgctaccgttcgactgccgggagggatatcgctttgaa
tccaccccaaacgtctggaaggaccattcggatcagcacagctttggttatgttgacgtt
agataggtagcaccttgcagcacctcagtccctgaag-------------------cggt
ttatacaaactcgtatattctcttgacacggagtaggtcggataggcagctaattctttc
atgcatggttgtcagtcgac
>SEQ11
ttaggctaaactaaagtgcgtcagctccctgcgaatacggcggcttggcatagctggact
caatcaccgtgcacaaattagtcgga----------------------------------
--------gagctccagcgtagtcaactccgtctcaaa----------------------
---------gcggtgtaaggtccttctgaatacaaacttgttcagtgatcatccgctcga
gcggatccagacctatctatgcgccttacttaagtatttaatgtgcgccctcccacgata
gtgcatacaacacaccggcctacttgctaggctttcagaattctgac-------------
-----------------------------------caagaccaccttcacaactctatgt
tggtt-------------------------------------------------------
----------acggagtcggtgcccgttatccgactcgtaattgtggacggacctgagaa
attgtcttgccgaaactgcctgaaaagccgcgtactgcaagagggggttgcatacgagta
tctcctgggtcctccccggcgttcgatttcaac------------------------ttt
ggcataagccataacaaactagttaacggcgtagaaag---------------------g
ctgcactattttctaagctaagccccaaacc--------------------------ttg
tcatgaccgcgggttgccgactgtggcgttcacctctcgtagccagcccaaatttgctag
cgttgtccgatcgctgcgtgtttgctaccgttcgactgccgggagggatatcgctttgaa
c----------------tagggactgct--------------------------------
----aaagtacacttcgcagcaccccaggcccca-------------------tgccggt
ttcttcataagaggagacccctcccacacggggtgcgtgagagtggtagctacgtcttgc
gcccatgcttggcagtggag
>SEQ12
ttagcctaaactcgcacgc-----------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------acatggtgtgctccttctgaatacaaacttcttcagtgatcatccgcccga
gcggatccagacctatctatgagccctacttaagtatttaatgtgcgccctcccacgaaa
gggcagcccccatgcca-------------------aagccgcaaac-------------
------------------------------------------------------------
------------------------------------------------------------
----------gaagggacagtgcccgttatccggctcgtaattgtggacggacctgagta
attgtcttgccgaaacagcctgaaaagccgcgtattgcaatagtgggttgcatacgaata
tcagctgggctgcccgggccgttggattgaa-----------------------------
------agccctactaaactagttaaccgctaataaagtccgtcactacgcaaggaatag
tcg---------------------ccactccaagccccgatacctggcatgaaggtctag
tcttgaccaccggttgccgcctgtggcgttctcctctcgtagccagcccaaatttgctag
cgttgtccgaacgttgcgtgtttgctaccgttcgactgccgggagggatatcgctttgaa
tcccccccaaaagtctgtagggaccagacggatcagtacaggtgtgcttaagcggtcgcc
agacaagaaactcctcgaagcactacagtccctgaagaccactcagtatatccatctggt
ttaatcgtacgcgtagatcccctccacacggcgggggtcagataggtaggtgattcttgc
atcaatggttgtcacttaag
>SEQ13
ttaggataaactaccgtccgagatctccatgagtataccgc-------------------
-------------------actcggactctctctagcgtaattcggctgctacacaagtt
cttgtcaaaagttcgagcgccgtgttgtgcatctcaatgctccgaggagcaaccaaatgc
t-------------------tcctactgaatacaaacttcttcagtgatcatccgctcga
gcggatccagacctatctatgcgccctacttaagtatttaatgtgcgccctcccacgata
gtgcagacgacataccggcctgcttgctatactttcagaattctgac-------------
------gacg--------------------------------------gtttcgtgatct
ctgttagagtgaacc---------------------------------------------
----------ggggtcggggtgcccgtaatccggctcgtaattgtggacggacctgagta
attgtcttgccgaaacggcctgaaaagccgcgtattccaagagtgggttgcataagagta
tcagctggaccgacaccggcgtttgacttaatc---------------------------
--------------------------------tcatgaaccgtcactaccctaagaactg
taggtctaatgtcttaacaaag-----------------------------------tag
tctcgatcaccgactgccacctgtggcgttctcctctcgtagccagcccaaatttgctag
cgttgtccgaacgttgcgtgtttgctaccgttcgactgccgggagggatatcgctttgaa
tccacccccaacatctttaaggagcattcgtatccgcacagctttggttttgtg------
--------------tcggagcatcccagtccctga---------------------cagt
atattaaagctagtagttccaattgagatgcagtgggtcacataggcagctaattcttt-
-----------------agg
>SEQ14
ttaggctaaactaatgtgcgtcagctacctccgaatacggcgggttggca----------
-----------cacacattagtcgga----------------------------------
----------gctccagcgtagacaactccgtctc-------------------------
----------------gtggtccttctgaacacaaacttcttcactgatcatccgctcga
gcggatccagacctatctatgcgccctacttaagtatttactgtgcgccctcccacgata
gtgcagaccatacaccggccgacttgccgggcttacagagtaccgacgatccggtgtcta
ggtggtgcgaataccatgtgcataaaaaaagcacacgatggcgcaggtacctcggtgtcc
ctgctgtagtgtattacaggattacgcggctacattcggagaccagactgtcctgcagat
cgtttatacaggagttgtggtgcccgttatccggctcgtaattgtggacggacctgagta
attgtcttgccgaaactgcctgaaaagccgcgtattgcaagagtgggttgcatacgagta
tcagctgggctgcccgggccgttggattgaa-----------------------------
------agccctactaaactagttaaccgctaataaagtccggcacttcgcaaagaatag
tgg---------------------ccactccaaaccccgatacctggcaagattgtctag
tcttgaccaccggatgccgcctgtggcgttcacctctcgtagccagccccaatttgctag
cgttgtccgatcgctgcgtgtttgctaccgttcgactgccgggagggatatcgctttgaa
cccacacctaacgtctgccggtacaagtcggaccaatgcaaacctgctagagtggaccct
acacagggaacacttcgcagcaccacaggcgctgaacacaatgcagtagatcaggcccgg
ttctccatacgagtagcgccc---------------------------------------
----atggtaggcagtggag
>SEQ15
--------------ttttcataatctaactgcgaataccgcctctcggcacaactgggcg
caatcacctcacataaattactcggactctctctaggcaaaatggccggctcaaaaagtt
ctactcaggagtttgatcgcagtgattgccatcgcaatggtgt-----------------
--------tgtgacctgcagtccttctgaatataatcttcttcagtgatcatccgctcga
gcggatccagacctatctatgcgccctacttaagtatttaatgtgcgcccttccacgata
gagcagacggcatgccgaccgacttgc---------------------------------
----------------------------gcgcaaacgaaggtacaggtacatcgctctct
cggttg------------------------------------------------------
----------gggcttttggtgcccgttatccgactcgtaattgtggacggacctgagaa
attgtcttgccgaaactgcctgaaaagccgcgtattgcaagagggggttgcatacgagta
tt----------------------------------------------------------
--------------taaactagttaacggctaataaaaaccgtcactaccctaagaactg
ttggtctactgtcttaacaaag-----------------------------------tag
tcctgactaccggatgccatctgtggcgttcacctctcgtagccagcccaaatttgctag
cgttgtccgatcgctgcgtgtttgctaccgttcgactgccgggagggatatcgctttgaa
cccacacctaacttctgtagggaccagtcgg-----------------------------
--------aacactgcgcagcactccagtccctgcacacaatgcagtagaacatgccggt
ttattcatacgtatagaccccacccacacggagtgggtgagagaggtagctgcttctggc
acccatggttggcagtggag
>SEQ16
ttagcctaaactgca---------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------cgcaggtgtgctccttctgaatacaaacttcttcagtgatcatccgctcga
gcggatccagacctatctatgcgccctacttaagtatttaatatgcgccctcccacgata
gtgcagacgacatatcggcctatttccgcagcttacataatactgac-------------
-----------------------------------------------ggtttcgctatcc
ctgttgtagtgccctgcg------------------------------------------
----------ggagtcggggtgcccgttatccgactcgtaattgtggacggacctgagaa
attgtcttgccgaaactgcctgaaaagccgcgtattgcaagagggggttgcatacgagta
tcagctctgtcttccccggcggtcca----------------------------------
--------------------------------------------agtccataagatacta
gtggactactttctaaacaacgccccgatcc--------------------------tag
tcatgaccgccggttgccgactgtggcgttcacctctcgtagccagcccaaatttgctag
cgttgtccgatcgctgcgtgtttgctaccgttcgactgccgggagggatatcgctttgaa
aatacccccaacgtatgttaggaccttt--------------------------------
----------gctctcgcagcaccccattccctgaaga------------------cact
ttggtcaaactagtttgtcctcttgacacggagtgggtcagataggcagctaattcttgc
atccttggttgccagtcgac
>SEQ17
tcaggctaaactaaagtgcgtcagctccctgtgagcccggcggctgggcatagttggact
cagtcacgtggcacaaatgagtgtca----------------------------------
------------------------------------------------------------
---------aagctgtaaggtccttctgaatacaaacttcttcagtgatcatccgctcga
gcggatccagacctatctatgcgccctacttaagtatttaatgtgcgccctcccacgata
gggcagaactccaacaggacgacttgctaggcttacagaattgtgag-------------
------gccacaag----------------------------------------------
---------agttgcacggcattacgcggttac---------------------------
----------ggagttgtggtgcccgttatccggctcgtaattgtggacggacctgagta
attgtcttgccgaaacagcctgaaaagccgcgtattgcaatagtgggttgcatacgaata
tcagctggaccgacgccggcgtttgacttaatc------------------------ttt
ggcctaagccattctaaactggttaaccgctaataaaaaccgtcactgccctaagaactg
ttggtatactgtcttaacgaag--------------------------------------
------ccacgggatgccacctgtggcgttcacctctcgtagccagcccaaatttgctag
cgttgtccgatcgctgcgtgtttgctaccgttcgactgccgggagggatatcgctttgaa
cccacacctcacttctgtagggacgcgtcggaacagtg----------------------
---------------cgcagcactacagtacctgcacataa-------------------
-tgttcatacgtatagaccccacccacacggagtgggtgggaga--------------tc
acccatggttggcagtggag
>SEQ18
ttagtctacacttatgtgcgtcagctacctgcgaatacggcgggttggca----------
-----------cacagattactccga----------------------------------
----------gctccagcgtagacaacgtcgtctc-------------------------
----------------gtggtccttctgaacacaaacttcttcactgatcatccgctcga
gcggatccagacctatctatgcgccctacttaagtatttactgtgcgccctcccacgata
gggcagccgccatgccgaacgagttgctttggtctcgggtttctgat-------------
------------------------------------------------------------
------------------------------------------------------------
-----------agacagggatgcccgttatccggctcgtaattgtggacggacctgagta
attgtcttgccgaaacagcctgaaaagccgcgtattgcaatagtgggttgcatacgaata
tcagcagggtcgaccccggcgttcgatgtcatc------------------------ttt
ggcataagccataataaactacttaaccgagaataaag---------------------g
ctggactactt-------------caaggcc--------------------------tag
tcatgaccgccggttgccgactgtggcgatcacctctcgtagctagcccaaatttgctag
cgttgtccgatcgctgcgtgtttgctaccgttcgactgccgggagggatatcgctttgaa
tccacccacaaagtctgtagggaccagtcgga---------------------ggacgct
ggacaggtaactcctcgcagcacgacagtccctaaagaccagtcagtagatccttccagt
ttaatcatacgagtacatcccctccacacagcgtgggtctgataggtaactaattcttgc
atcaatggttgacagttaag
>SEQ19
ttaagaaaaactaacgtccgtcagccccatgcgaatgccgcgtcttggcataactgggct
caatcaccttacgtacattagtcggattctctctagcgaaaatggcctgctcaaataatt
ctactcacgagtttgattgcagtgatatccatcgcaatgggcc-----------------
--------tgtgagccgcagtccttctgaatacaaacttcttcagtgatcatccgctcga
gcggatccagacctatctatgcgccctacttaagtatttaatgtgcgccctcccacgata
gtgctgacgacatatgggccgacttgctaagcttagataattctgac-------------
------gaca--------------------------------------gtttcggtatcc
ctgttgtaatgacctg--------------------------------------------
----------ggagtcggggtgcccgttatccgactcgtaattgtggacggacctgagaa
attgtcttgccgaaactgcctgaaaagccgcgtattgcaagagggggttgcatacgagta
tcagctggaccgtcaccggcgtttgacttaacc---------------------------
------------------------------------taaccttcactaccctaataactg
taggtctaatgtcttaacaaag-----------------------------------tag
---------------gccgcctgtggcgttcacctctcgtagctagcccaaatttgctag
cgttgtccgatcgctgcgggtttgctaccgttcgactgcagagagggatatcgctttgaa
aatacgac----------------------------------------------------
------------cctcgcagcacccaattccctgagg-----------------------
----tcaaactagtttggcctcttgacacggagtaagtcagataggcacctaattcttgc
atccttggtggccattcggc
