>SEQ0
tgtcacaggtataggcaaacttacaccggtctcggcaagttaccgcattgcgggtagagt
ggcagtggcgaagccgccattctagtcggcgataactagattacttttcaacctgccagc
cgaatattggtgcggtccgaggcaaaaatgggcgatacgatcatcatcgcgcctcgtaaa
atacatcaatgatttaaaacccgccagctccttatcagagacgttcaactctaagacccc
attccttcagatcgtgagccagcggtacccgcgagtcatcaatcatgattatatggaaat
aataccaaccggcagtattacactccgcctaacggaactgtaagaccaactgcattgtgg
cgtcgacagtcgttagagtatgggttgttatacggactatgtctctcattgagattttac
gtttaagagtgacattcttatgcaccttaccgctcatctggcgtttaccacaccatcaca
gaccgcccgctacgatcctcgatgcttcactgggccgttgttggatttgctcagcgaaga
cacagaagatagcaatgccactaccccgacactaaaagttcatacatcggcctaagatgc
ggggggcacaaagtgcacaatcctatatatttgtctcacgtctggaagtgataagactct
ctttcctctgttccatcagtgcctttgcgagatgggtatctaggagctcgcagtaaataa
cgcctccctagaaaatgaacatactgtacgagtgcgagaagagtcacagcagatcgaggg
ttgcgttcccctcaggcactcccactcccttccgctagtattgctggacgtctgtccgtc
atcttcacggtgagttcaacgtgccctgtacgcgtcttgctggcatctccacttaccctc
tgagcaatgctgaaggttgctggccgtagttgtgcccacttccggccccctagaaatcgg
ggatacccgccggaacggcgagattcccgaactgatgaaaaatgaagagggctttacggt
cacgggataccaccggattagagtgctgttgactcaaaatgacaagggggaggacggcga
ctcgttgtgacgacggcctg
>SEQ1
tgtcccaggtat--------------cggcctcggcaagtgacctcgtt-----------
-------------tcgccattctaggcggcgataacaagattactttt------------
--aatattggtgcggtcc---------------------ctcatcattgcgcctcgtaaa
atacatcaatcatttaaaacccgccagctccttatcagagacgttcaactctaagacccc
attccttcagatcgtgaaccagaggtacccgcgagtcatcaatcatgattatatggaaat
cataccaaccggcagtatt-----------------------------actgcattgtgg
aatcgacagtcgttagagtatgggttgttatacggact----------------------
-tttaacactgaccttcttatgcacctaaccgctcatctggagtttaccacaccaacaca
gatcgcccgctacgagcctcgatgcttcactgggccgttgttggatttgctcagcgaaga
cacagaagatagcaatgccactaccccgacactaaaagttcatacatcggcctaagatgc
ggggggcacaaagtgcacattcctatatgtttgtct------------------------
---------------tcagtgcctttgcgagatgggtatc--------------------
-------ctagaaaatgaacatactgtaagagtgcgagaagagtca--------------
--------cactcaggcactcccactcccttccgctagtattgctggacgtctgtccgtc
atcttcacggtgagttcaacgtggcctgtacgcgtcttgctggcatctccacttaccctc
-----------------------ccgtagttttgcccacttcccgccccctagaaatctg
ggatacctaccggaacggcgagattcccgaactgataaaaaatgaagagggctttacggt
cacgtgattccaccggattagagtgctgttgactcaaaatgacaagggggaggacggcga
ctcgttgtgacgacggcctg
>SEQ2
tgtcccaggtag--------------cggcctcggcaagtggactcgtt-----------
-------------tcgccattctaggcggcaataccaagattactttt------------
--aatatctgtgccgtcc------------------------------------------
ctacatcaatcatttaa---ccgccagctccttatcagtgacgttcaactctaagacccc
attccttcagatcgtgagccagcggtacccgcgagtcatcaatcatgattatatggaaat
aataccaaccggcagaattacactccgcctaacggatctgaaagaccaactgcattgtgg
cgtcgacagttgttagagtatgggttgttttacg--------------------------
-tttaagggtgacattcttacgcagcttaccgcccatctggcgtttatcacaccatcaga
gaccgcccgccactatcctcgatgcttcactgggccgttgttggatttgctcagcgaaga
caaagaagatagcaatgccactaccccgacactaaaagttcatacatcgacctaagatgc
ggagggca--------------------------ctcacgtctggaagtgataagactct
ctttcctctcttccatcagtgcctttgctagatgggtatc--------------------
-----ccctataaactgaacatactgtacgagagcgagaagagtcacagcagatcgaggg
ctgctttcccatcaggcactcccactcccttccgctagtattgctggacgtctgtccgtc
atcttcacggtgagttcaacgtgccctgtacgcgtcttgctggcatctccacttaccctc
----------------------------------cccactccccgcccactagaattctt
ggatacctaacggcacggcgagattcacgaaatggtaaaaaatgaagaggcctttacgct
cacgtgattccaccggattagagtgctgttgactcaaaatgacaagggggaggac-----
---------ataacggcctg
>SEQ3
tgtcacaggtatagggaaccttacaccggtctcgaaaagttaccgcatt-----------
----gcggggaaggcgccattctagtcggcgataactagattacttttcaacgtgccagc
cgaatattcgtgcggtccgaggcaaaaatgtgcgatacgatcaccttcgcgcctcgtaaa
atacaacaaagatttaaaacccgccagctccttatcagagacgttcaactctaagacccc
attccttcagatcgtgaaccagaggtacccgcgagtcatcaatcatgattatatggaaat
cgtaccaaccggcagtatt-----------------------------tctgcattgggg
aatcgacagtcgctaaagtatgggttgatatacggac-----------------------
----gacactgaccttcttatgcacctaacagcacatctggagttcaccacaccaacaca
gatcgcccgctacgaccctcgatgcttcactgggccgttgttggatttgctcagcgatga
caaagaagatagcaatgccactaccccgacactaaaagttcatacatcgacctaagatgc
ggggggca--------------------atttgtctcacgtctgaaagtgataaaac---
-----------------agttgctttgtgagataggtatctaggagctcgcattaaataa
cgcctccctagaa-------------------------aacatacaccgcagatcgatgg
ttaggttccccccaggcactcccactcccttccgctagtattgctggacgtctgtccgtc
accttcacggtgagttcaacgtgccctgtacgcgtcttgctggcatctccacttaccctc
tgatcaatgctgaatgttgctggccgtagttgtgcccacttccggtcccctaggaatccg
gtatacccgccggaacggcta----------------------gaagagggctttacggt
cacgggataacaccgg--------------------aaatgacaagaggaaggacgggga
ctggttgtgccgacggcttg
>SEQ4
tgccgcaggtag--------------cggcttcggcaagtggacccatt-----------
-------------tcgccatactaggcggcaataccaagattactttt------------
--aatatctgtgccgtcc------------------------------------------
-------------------cccgccagctccttatcagagacgttcaactctaagacccc
attccttcagatcgtgagccagcggtacccgcgagtcatcaatcatgattatatggaaat
cgtaccaaccggcagtact-----------------------------tctgcattgcgg
catcgacagtcgctaaagtatgggttgat-------------------------------
----aacactgaccttcttatgcacctaacagcacatctggagttctccacaccaacaga
gatcgtccgctacgaccctcgatgcttcactgggccgttgttggatttgctcagcgaaga
cacagaagatagcaatgccactaccccgacactaaaagttcatacatcggcctaagatgc
ggggggcacaaagtgcacaatcctatatatttgtctcacgtccggaagtgataagactct
ctttcctctgttccaaaagtgcctgtgcgagatgggtatctaggagctcgcagtaaata-
--------------------------------------aagagtcactgcagatcgaggg
ttgcgttcccctcaggtactcccactcccttccgctagtattgctgtacgtctgtccgtc
accttcacggtgagttcaacgtgccctgtacgcgtcttgctggcatctccacttaccctc
-----------------------ccatagttttgcccacttccggccccctagatgtctg
ggatgcgtaacgg---------------gaattgataaaaaatgaacagggctttacggt
cacgtgattccaacggatcagagtgctgtggactcaaaatgacaaggggggggccggcgt
ctcgttggcacgacggcctg
>SEQ5
cgtcacaggcatatgcaaacttacaccgttctcggcaaatttccgcatt-----------
----------------gcgggtggagtggcagtact-agattacttttaaacctggcagc
cgaatattggtgcggtccgaggtaaaaatgggcgctacgatg------------------
----accattcatttaaaacccgccagctccttatcagagacgttcaactctcagacccc
attccttcagatcgtgagccagcggtacccgcgagtcatcaatcatgattatatggaaat
tataccaatcggcagcatt-----------------------------actgcattgtga
attcgacagtggttagagtatgggttgttagacggact----------------------
-tttaacactgaccttcgtatgcacctagccgctcatctggagtttaccgcaccaacaca
gatcgcccgctacgagcctcgatgcttcactgggccgttgttggatttgcacagcgaaga
cacagaagatagcaatgccactaccccgacactaaaagttcatacatcggcctaagatgc
ggagggca--------------------------ctcaagtctggaagtgataagactct
ctttcctctcttccatcagtgcctttgctagttgggtatc--------------------
-----ccctatagactgaacatagtgtacgagagcgagaagagtcaaagcagatcgaggg
cggctttc------------cccactcccttcggctagtattgctggacgtctgtccgtc
accttcacggtgagttcaacgtgccctgtacgcgtcttgctggcatctccacttaccctc
-----------------------ccatagttttgcccacttccggccccctagttgtctg
agatgcgtaacg------------------------aaaaaaggaaaagggctttacggt
cacgtcattccaacggatcagagtgctgtggactcaaaaagacaagcgaggggccggcgt
ctcgttggcacgacggcctg
>SEQ6
tgtcccaggtat--------------cggcctcggtaagtgaccgcgtt-----------
-------------------tcttagtcggcgatatcaagattacttta------------
--aatattagtgcggtcg---------------------ctcctcattgcgcctcataaa
atacatcaatcatttaaaacccgccagctccttatcagagacgttcaactctcagacccc
attccttcagatcgtgagccagcggtacccgcgagtcaacaatcatgattatatggaaat
cgtaccaaccggcagtatt-----------------------------tctgcattgggg
aatcgacagtcgctaaagtatgggttgatatactgac-----------------------
----gagactgaccttcttatgcacgtaacagcacatctggagttcgccacaccaacaca
gattgcccgctacgaccctcgatgcttcactgggccgttgttggatttgctcagcgatga
caaagaagatagcaatgccactaccccgacactaaaagttcatacatcgacctaagatgc
gggggtcc--------------------------ctcaagtctggaagtggtaagaccct
ctttcctctcttctatcagtgcctttgctagttgggtatc--------------------
-----ccttatagacttaacgtagagttcgagagcgagaagattaaacgcagaccgaggg
cggctttc------------cccactcccttccgctagtattgctggacgtctgtccgtc
atcttcacggtgagttcaacgtggcctgtacgcgtcttgctggcatctccacttaccctc
ccaccaacg--------------gcacaaattt---------------------------
------------------------------------------------------------
---------------------agaggtgttgactcatgatgacaaggggaaggac-----
---------ataacggcctg
>SEQ7
tgtcccaggtag-----------------------caagtggactcgtt-----------
-------------tcgccattctaggcggaaatacgaagactac----------------
----tatgtgtgccgtcc------------------------------------------
-------ctacatcaataatccgccagctccttatcagagacgttcaactctaagacccc
attccttcagatcgtgaaccagaggtacccgcgagtcatcaatcatgattatatggaaat
cgtaccaaccgggagtact------------------------------ttgcattgcgg
catcgacagtcactcaagtatggcttg---------------------------------
---------------------gtaacaaacagctcatcaggagctcaccacaccaacaga
tatcgtccgctacgaccctcgatgcttcactgggccgttgttggatttgctcagggaaga
cacagaagatagcaatgccactaccccgacactaaaagttcatacatcggcctaagatgc
ggggggcacaaggtgc-------------------------------gtaataagactct
ctttcctctgttcctaaagtgcctgtgtgagaagggtatgtaggagctcgctgt------
---------------------------------------------aattcagaccgtggg
ttgctttcccctcaggtactcccactcccttccgctagtattgctgtacgtctgtccgtc
accttcacggtgagttcaacgtgccctgtacgcgtcttgcttgcatctccacttaccctc
-----------------------tggtagttttgccctcttcccgccccctagaa-----
---------------cggcgagattcccgaaccgataaaatatgaagagggctgtacgat
ccggtaattccaccggattagagtgctgttgactcgaaatgattagggggaggacggcga
gtcgttgtgacg--------
>SEQ8
tgtcccaggtag--------------cggcctcggcaagaggactcgtt-----------
-------------tcgccattccaggcggcaaaacaaagattacttat------------
--catatctatgccgtcc------------------------------------------
ctacatcaatcatttaa---ctgccagctccttatcagagacgttcaactctaagacccc
attccttcagatcgtgaaccagaggtacccgcgagtcatcaatgatgattatatggaaat
aataccaaccggcagtattacactccgcctatcgga------------actgtaagacca
agtcgacagtcgttagagtatgggttgttatacggactatgtct----------------
-ctcattaagattattctcctgcaccttagcgctcatctggcgtgttacacaccatcaga
taccgcccgctacgatcctcgatgcttcagtgggccgttgttggatttgctcagggaaga
cacagaagatagcaatgccactaccccgacactaaaagttcatacatcggcctaagatgc
ggggggcacaatgtgc-------------------------------gtaataagactct
cgttccgctgttcca------------------gggtatgtacgagctcgctgt------
---------------------------------------------atttcagaccgtggg
ctgctttcccctcagatactcccactcccttccgctagtattgctggacgtctgtccgtc
accttcacggcgagttcaacgtgccctgtacgcgtcttgctggcatctccacttaccctc
taatgaatgatgaatgttgcaggccgtagttgtgccctcttccagtcgcctaggaatccg
gtatacccgccggagcggctagaa------------------------------------
-----------------------------agattaccaatgacaagaggaaggacgggta
ctggttgtgccgaaggcttg
>SEQ9
tgtccctggtga-------------------------------ctcgtt-----------
-------------tcggcagtctacgcgg-------------------------------
----tatgtgtgccatcc------------------------------------------
-------ctacatcagtaatccgccagctccttatcagagacgttcaactctaagacccc
attccttcagatcgtgaaccagaggtacccgcgagtcatcaatcatgattatatggaaat
cgtaccaagcggtagtatt-----------------------------tccgtg------
------------------------------------------------------------
----aagacagtccttcttatacacgtaccagcccatgtggagttccacacagcaacaca
gattgcccgctatgacccacgatgcttcactgggccgttgttggatttgctcagcgatga
caaagaagatagcaatgccactaccccgacactaaaagttcatacatcgacctaagatgc
gaagggca---------------------------tcaagtctggaagtgataagactct
ctttcctcccttccatcagtgcctttgctagttgggtagc--------------------
-----tactatagactgaacatagtgtacgagagcgagaagagtcaaagcagatcgaggg
cgg---------------ctcccactccctgccgctagtattgctggacgtctgtccgtc
atcttcacggtgagttcaacgtggcctgtacgcgtcttgctggcatctccacttaccctc
-----------------------ccgtagttttgcccacttcccgccccctagaaatctg
ggatacctgccggaacggcgagattctcgaa--------------------ctttacggt
cacgtgattccac----------------agactcaaaattagaagggggaggacggcga
cgcgttgtgacgacggcctg
>SEQ10
tgtc---------------------------tcagcaggtgacctcgtc-----------
-------------ccgccattctatgcggcgataacaagtttaatttt------------
-tgatcattgcgcctcgc------------------------------------------
---------atatttaaaacccgccagctccttatcagtgacgttcaactctaagacccc
attccttcagaccgtgagccagcggtacccgcgagtcatcaatcatgattatatggaaat
cgtaccaagcggcagtagt-----------------------------tctg--------
------------------------------------------------------------
----aagacagtccttctaatacacgtaccagcccatgtggagttccacacagcaacaca
ggttgcccgctattacccacgatgcttcagtgggccgttgttggatttgctcagggaaga
cacagaagatagcaatgccactaccccgacactaaaagttcatacatcggcctaagatgc
ggagggca--------------------------ctcaagtctggaagttttaagactct
ctttcctctcctccatcaaagcctttgctagttgggtatc--------------------
-----ccttttagcctgaacatagtctacgagagcgagaatagtcaaagcagatcgacgg
aggctttc------------cccactcccttccgctagtattgctggacgtctgtccgtc
accttcacgccgagttcaacgtgccctgtacgcgtcttgctggcatctccacttaccctc
-----------------------ccgtagttttgcccacttcctgccccctagaaacctg
ggttacctgccggaaaggcgagattctcgca-----------------------------
cacgtgtttccac----------------agactcaaaat--------------------
---------tcgacggcctg
>SEQ11
tgccgcaggtag--------------atgcatcggcaattggacccatt-----------
--------------------------------tcgcaagattagtttt------------
--attatctgtgccgtgc------------------------------------------
-------------------accgccagctccttatcagagacgttcaactctaagacccc
atgccttcagatcgtgaaccagaggtagccgcgagtcatcaatcatgattatatggaaat
tatacaaatcggcagcatt----------------------------------actgtga
attcgacagtggttagagtatgggttgttagacggact----------------------
-attaacactgaccttcgtatgcacctagacgctcttctggagtttacagcaccaacaca
gatcgcccgctacgagcctggatgcttcactgggccgttgttggatttgctcagcgaaga
cacagaagatagcaatgccactaccccgacactaaaagttcatacatcggcctaagatgc
gg----------------------------------------tgaaagtgataaaac---
-----------------agttgctttgtgggataggaaccttgcagctcgcatgaaataa
cgcatcccgagataccta--------------------------caccgcagatcgatgg
------------------ttcccactcccttccgctagtattgctggacgtctgtccgtc
accttcacggcgagttcaacgtgccctgtacgcgtcttgctggcatctccacttaccctc
------------------------------------------ccgccacctagaaatc--
--------------acggcgagattcccgaactgataaaaactgaagaggcctttacggt
cacgtga------------------------------------aagggggaggatggcgt
cgcgttgt------------
>SEQ12
tgccgccggtag--------------gggcttcgataagcggat----------------
-------------ccaccatactaggaggcaagagcaagattactttt------------
--aatatctgtgccgtcc------------------------------------------
-------------------cccgccagctccttatcagagacgttcaactctaagacccc
attccttcagatcgtgaaccagaggtacccgcgagtaatcaatcatgattatatggaaat
tatcccaatcggcatcatt-----------------------------actgcttggtga
aatcgacactggttagagcatgggttgata------------------------------
-tttaacactgacctttagatgcacctagcccctcatctggagtttaccgcaccaacacg
gatcgcccgctacaagcctcgatgcttcactgggccgttgttggatttgctcagcgaaga
cacagaagattgcaatgccactaccccgacactaaaagttcatacatcggcctaagatgc
ggggggcacaaagtgcacaatcctatatatttatctcaagtctgtaagtgataagactct
ttttcttctgttccataagtgcctttgcgagatggttatctaggagctcgcagtaactaa
cgcctccctagaacatgagcattctgtacgagtgcgtgatgagtcacagcagatcgaggg
ttgcgttacccgcaggcactcccactcccttcggctagtattgctggacatctgtccgtc
accttcacggtgagttcaacgtgccctgtacgcgtcttgctggcatctccacttaccctc
--------------------------------------cctcccgcccacgaaaaatcag
ggctacctgccggaacggcgagattctcaaa--------------------atttacggt
cacgtgattccacagaat----------------------------ggggaggacggcga
cgcgttgggacgacggcctg
>SEQ13
tg----------------------------------------------------------
-------------tccccattctaggccgcgataccaagattactttt------------
--aattttggtgcggtcc---------------------cgcatcattgcgcctcgtaaa
atacatcaatcatttaaaacccgccagctccttatcagtgacgttcaactctaagacccc
attccttcagaccgtgagccagcggtacccgcgagtcatcaatcatgattatatggaaat
tatcccaatcggcatcatt-----------------------------tctgctaggcga
catcgacactggttcgagcat---------------------------------------
-------------------ttatccctagcccatcatctggaggttaccgcaccaacacg
gatcgcctgctacaagcctcgatgcttcactgggccgttctgggatttgctcagcgaaga
cacagaagatagcaatgccactaccccgacactaaaagttcatacatcggcctaagatgc
gggggtcc------------------------------------------------ccct
ccttcctctcttgaatctgtgccttttttagttggatatc--------------------
----------------------agagttcgagagcgagcagattaaacgcagaccgaggg
cggctttc------------cccactcccttccgctagtattgctggacgtctgtccgtc
accttcacggtgacttcaacgtgccctgtacgcgtcttgctggcatctccacttaccctc
-----------------------ccgtagttttgcccacttcgcgcccccgagatgtctg
ggatgtg------------------------------------gaattgggctttacggt
cacgtgattgtaacggatcagagggctgtggactcaaaatgacatggggggggccgtcgt
cacattggcacgacggtctg
>SEQ14
tgtgccaggtag--------------cggcttcggcaagaggactcgtt-----------
---------------tgaattccaagcggcaaaacaaagattacttat------------
--catatctatcccgtcc------------------------------------------
ctacatcaatcatttta---ccgccagctccttatcagtgacgttcaactctaagacccc
attccttcagatcgtgagccagcggtacccgcgagtcatcaatcatgattatatggaaat
tatcccaatcggcatcaaa-----------------------------actgcttggtga
actcgacactgggtagagcacgggttgata------------------------------
-tttaacactgacctttagatgcacctagcccctcatctggagcttaccgcaccaacgcg
gatcgcccg-----------gatgcttcactgggccgttgttggatttgctcagcgatga
caaagaagatagcaatgccactaccccgacactaaaagttcatacatcgacctaagatgc
ggggggcacaaagtgcacaatcctatatatttgtgtcacgtccggaagcgataagactct
cgttcctctgttccaatactgcct------------------ggagctcgcagtaaata-
--------------------------------------aagagtcactgcagatcgattg
atgcgttcccctccggtactcccactcccttccgctagtattgctggacgtctgtccgtc
atcttcacggtgagttcaacgtgccctgtacgcgtcttgctagcatctccacttaccctc
-----------------------ccgtggttttgcccgcttcgcgcccccgagatgtacg
tgaagtg------------------------------------gaattgggctttacggt
aacgtgatggtaac--------------------ccaaatgacaagcggggggccgtcgt
aacattggcacgacggtctg
>SEQ15
tg----------------------------------------------------------
-------------ccgccattcaatgccgcgataccaagtttacttgt------------
--------------------------------aaatttgggcagcattgcgcctcgtaaa
atacat--------------ccgccagctccttatcagagacgttcaactctaagacccc
attccttcagatcgtgagccagcggtacccgcgagtcatcaatcatgattatatggaaat
cttaccaagcggtagtatt-----------------------------tccgagcaa---
------------------------------------------------------------
-------------------------------gtccttcttatgcacgtcagagcaacaca
gatcgcccgctattacccacgatgcttcagtgggccgttgttggattagctcagggaaga
cacagaagatagcaatgccaataccccgatactaaaagttcatacatcggcctaagatgc
ggggggcacaaagtgctcaatcctatatatttgtctcacgtctggaagtgataagactca
ctttcctctgttccatcagtgcctttgcgagatgggtatcaaggagct------------
--------tagaaaatgaacatactgtacgagtgagataagagtcacagcagatcgaggg
ttgcgttccc--------ctcccactcccttccgctagtattgctgtacgtctgtccgtc
accttcacggtgcgttcaacgtgccctgtacgcgtcttgctgccatctccacttaccctc
tgatcagttctgaatgttg--------------------ttccggtcccctaggaatccg
gtatacccgccggaacggcta----------------------gaagagggctttacggt
cacgggataacaccgg--------------------aagtgacaagaggaaggac-----
--------------ggcttg
>SEQ16
tgtcgcaggtag--------------cggcctcggtaacaggactcgtt-----------
-------------tcgccattcaaggctgcaaaataaagattactgat------------
--catttcaatgccgtcc------------------------------------------
ctacatcaattatttaa---ccgccagctccttatcagagacgttcaactctaagacccc
attccttcagatcgtgaaccagaggtacccgcgagccatcaatcatgattatatggaaat
tgtactaa----------------------------------------------------
----------------agtatgggttaat-------------------------------
----gtcactgaccttcctatgcacctaacagcacatctggagctctccacaccaacaga
gatcatccgctacgaccctcgatgcttcactgggccgttgttggatttgctcagcgaaga
cacagaagatagcaatgccactaccccgacactaaaagttcatacatcggcctaagatgc
ggggggcaaaaagggcacattcctataagtttgtct------------------------
---------------tcagtgcctttgcgaga----------------------------
------cctagaaaatgaacata-------------------------------------
ctgtatcacactcaggcactcccactcccttccgctagtattgctggacgtctgtccgtc
atcttcatggtgagttcaacgtggcctgtacgcgtcttgctggcatctccacttaccctc
tgatcaatcctg-------------------------actgtcggtcccctaggaatccg
gcta---------------------------------------gaagatggcttgacgca
cacgggata--------------------agacccgaaacgacaagaggaaggacgggga
ctggttg-------------
>SEQ17
tgccgcaggtac---------------------ggccattggacccatt-----------
--------------------------------tcgcaagattagtttg------------
--agtagctgtgccg---------------------------------------------
--------------------ccgccagctccctatcagagacgttcaactctaagacccc
attccttgagatcgtgaaccagaggtacccgctagtcatcaatcatgattatatggaaat
tgagctaa----------------------------------------------------
----------------agtataggtta---------------------------------
--------------------------tcactgaccttctggagctctccacacctacaga
gatcatccactacgacccgcgatgcttcactgggccgttgttggatttgctcagcgaaga
cacagaagattgcaatgccactaccccgacactaaaagttcatacatcggcctaagatgc
gc---------------------------------------------gtaataagactct
cgtttcgccgttcga------------------gggtatgtacgagctcgctgt------
---------------------------------------------atttcagaccgtggg
ccgctttcccctcagacactcccactcccttccgctagtattgctggacgtctgtccgtc
accttcacggcgagttcaacgtgccctgtacgcgtcttgcaggcatctccacttaccctc
tgatcaatcct-------------------------------cggtcccctaggaatccc
gcta---------------------------------------gaagatggcttgacgta
cacgggataagacccg---------------------------aagaggaaggacgggga
cttgttg-------------
>SEQ18
tg----------------------------------------------------------
-------------ccgccattcta------------aagtttgcttgt------------
--------------------------------aaatttgggcagcactgcgcctcttaaa
atatat--------------ccgccagctccttatcagagacgttcaactctaagacccc
attcgttcagatcgtgagccagcggtacccgcgagtcatcaatcatgattatatggaagt
aataccaaccggcagtgttatactccgcctaacggaactgaaagaccaactgcattgtgg
cgtcgacagtcgttagtgtatcggttgtta-----------tctctcaatgagattttac
gtttaagagtgacattctaatgcaccttaccgctcatcctgcgtt--------------g
aaccgtccgctacgaccctcgatgcttcactgggtcgttgtaggatttgctcagcgaaga
cacagaagatagcaatgccactaccccgacactaaaagttcatacatcggcctaagatgc
ggggg-------------------------------------------------------
--ttccgctgttcca------------------gggtatgtacgagctcgctgtattt--
----------------------------------------------------accgtggg
ctgcttgcccctcagacaatcccactcccttccgctagtattgctggacgtctgtccgtc
atcttcagggtgagttcaacgtgtcctgtacgcgtcttgctggcgtctccacttaccctc
-----------------------ccgtagttttgcccacttcgcgcccccgagatgtccg
ggatgtg-----------------------------------------------tgcggt
cacgtgcttgcaacggatcagagcgctgtgcacttaaaataccatagggggggctgtctt
caccttggcacggcggtctg
>SEQ19
tatgccacgtag--------------cggcttcggcaagaggactcgtt-----------
---------------tgaattccaagcggcaaaactaagattacgtat------------
------------------------------------------------------------
-tacatcaatcatttta---ccgccagctccttatcagtgacgttcaactctaagacccc
attccttcagaccgtgagccagcggtacccgcgagtcatcaatcatgattatatggaaat
tataccaatcggcagcatt-----------------------------actgcattgtga
attcaacagtggagacaggatgagttgttagacggact----------------------
-tttaacactgaccttcgtgtgcgcctagccactcatctggagtttaccggaccaacaca
gatcgtccgctacgagcttcgatgcttcactgggccgttgttggatttgctcagcgaaga
cacagaagattgcaatgccactaccccgacactaaaagttcatacatcggcctaagatgc
ggggggcacagactgcacaatcctatatatttgactcacgtgcggaag------------
----------ttccaaaagtgcctgtgcgtggtgggtaactacgagctcgcagcaaata-
--------------------------------------aggagtccctgcagatcgagga
ttaagttcgcctcaggtactcccacacccttccgctagtattgctggacgtctgtccgtc
atcttcacggtgagttcaacgtgccctgtacgcgtcttgctggcatctccacttaccctc
----------------------------------cccactccccgcccactagaattctt
gtatacctaagggcgcggcgagattcacgaaatggtaaaaattgaagaggcctttacgct
caggtgattccaccggattagagagctgctgacttaagatggcaagcgcgaggac-----
---------ataacggcctg
