>SEQ0
gactaacggggggcgatcggtgagttgcacatagaaacacgcacgagttctagacctcgg
cgattatcattgcgcgcgtcacagctccctcattaacgcactattaccatgcattcggcg
gactacggtccactgcatatgcttttgtcgttcaaacgggaactttactttcccgcgctc
acattcctatttcgcgtggaaacaattgaggcatacctgttgtaaaatctctctcttacc
cggccactgtagtgggagagaaattaatcgcaatgtaagcagtgtactgtcccgttacgg
taaatacgatcttgggacctactaacaggaatagagagaaacaggactcgcatgagcact
tgactccgagtgcggaccgtatcttcaacaactactcttcccagcggctgagtcgataga
ccacatgtgcaaccagctagacagccactcgtcgaatcggcgcgcgcctctgctgatcgt
aacgagtcacctccctggctgcactctgcatacatggagtaaacatgccatgatatagac
ctcgtgcccggtcatatagacgatgcttaaagtcatgaatgtgcccttgccgagatggat
tatttaatttcgaaattttagatttctcaacctggagcggtcggacggaaggaaggcccg
ataacccctgtattataactcctgaaagtcaacgccccctgtccctaacaccaattacat
tgcatgaacggtatgctggcactttaaaaggtatcgaagtcaactggaattgacaagaat
ggcgaaaacatcctggttgagtccgcaaaccgaaagtggtgtacggggagatccggcgtc
atctgagtggcaactatgtgactaataacctatcagttttcttccccaacaaagagccaa
ggtcatcagcattgccgttgcgtaatgtacgtgggtttggtgtattccaaggcgaaatta
tcttacaagtgactgccaccgacattctgcttctaacagcctgcgtacccgcgtctacca
taccctatgccaggctgctaaggagcacagctgctccgggcaaaggtctgacggcccaat
aaactcgcgatgtcgcaccc
>SEQ1
gactatcggggagcgatcggtgagttgcacatagaaacactcacaagttctagacctcgg
c----------------------gctccctcattcacgaactattaccatgcattcggcg
gactacggtccactgcatacgcttttg-----------------ttactttcctgcgctc
acattcttatgtcgcgtggaaacaattgaggcatacctgttgtaaaatctccctcttacc
cggccactgtagtgggagagaaattactcgcaatgtaagcagtgtactgtcccgttacgg
taaata------------------------------agaaacaggactgtcatgagcagt
tgacgccgagggccgaccgtatcatcaacaactactcttcccagcggctgagtcgatatc
acacatgtgcaaccagctagacagccactcgtcgaatcggcgcgcgcctctgatgatcgt
aacgagtcacgtccctggctgcactctgcatacatggagtaaacatgccatgatatagac
ctcgtgcccggtcatatagacgatgcttaaagtcatgaatgtgcccttgccgagatggag
tatttaatttcg-------------------cttgagcggtcggacggaaggaaggcgcg
gtaacccctgtattataactcc--------------------------caccagttacat
tgcataagaggtatgctggcactttaaaag---------------------gacaagaat
ggcga--------------agtccgcaaaccgaaagtggtgtacggggagatccggcgtc
atctgagtggcaactatgtgactaataacctatcagttttcttccccaacatagagccaa
ggtcatcggcattgccgttgggtaatttatgttagtttggtgtattccaaggggaaatta
tcttacaagtgactgccaccgacatgctgattctaacatcctgcgtatc-----------
--------------------------------------------------------caat
aagctctcgatgtcgcacgc
>SEQ2
gactaacggggggcgatcgttgagtcacacatagacacacgcacgagatctagacctcgg
cgattatcattgcgcgcgtcacggctctctcattttcgtactattacaatgctt------
------------------atgcttttgtcgttcaatcgggaactttattttcccgggctc
acattcctatttcg------aacaattgaggcatacctgttgtaaaatctctctcttacc
cggccactgtagtgggagagaaattaatcgcaatgtaagcagtgtactgtcccgttacgg
taaata------------------------------agaaacaggactgtcatagg----
-----------gccgaccgtatcatcaacaactactcttcccagctgctgatttgatatc
acacatgtgcaaccagctagtcagccactcgtcgatacggcgcgcgcctctgctgatcgt
aacgagtcacttccctggctgcactctgcatacatggagtaaacatgccatgatatagac
ctcgtgcccggtcatatagacgatgcttaaagtcatgaatgtgcccttgccgagatggag
tatttaatttcg---------------------------gtcggacggattgaaggcgcg
gtaacccctgaactataactcc--------------------------caccagttacat
ggcataagaggtatgctggaactttaaaag---------------------aaaaagaat
ggcga--------------agtccgcaaaccgaaagtggtgtacggggagatccggcgtc
ctctgagtggcaactatgttactaataacctaccagttttcttccccaacaaagagccaa
ggtcatcggtatttccaaggggaaatc--------------------------------a
tcgtacaagtgactgacaccgacatggtgattctaac-----------------------
--------------------------------------------------------caat
aagctctcgatgtcgcacgc
>SEQ3
gactaacggggggcgttcgttgagtcacacatagacacacgcacgagatctaggcctcgg
cgaatatcattgcgcgcgtcacggctctctcattttcgtacgattacaatgctt------
------------------atgcgtttgtcgtacaatcgggaactgtattgtcccgggctc
acattcctaggtcg------aacaattgaggcatacctgttgtaaaatctccctcttacc
cggccactgtagtgggagagaaattactcgcaaggtaagcagtgtactgtcccgttacgg
caaata------------------------------agaagcaggactgtcatgagcagt
tgacgc-------------------caaggtctactcttcccagcggctgagttgatatg
gcacat-------------------cactcgttgaattggcgagcccctctggt------
--------------ctggcagcactctgcatacatggagtaaacatgccatgatatagac
ctcgtgcccggtcatatagacgatgcttaaagtcatgaatgtgcccttgccgagatggag
tatttaattttg---------------------------gtcggacggattaaaggtgcg
gtaacccatgaactataactgc--------------------------caccag------
-----------------ggaactataaaag---------------------aaaacgaat
tgcg---------------agtccgcaaaccgaaagtggtgtacggggagatccggcgtc
ctctgagtggcaactatgttattgataacctaccagttttcttccccaacaaagagccaa
ggtcaacggcattgccgttggctaatttatgttagtttggtgtagtcaaaggggaaatta
tcttacaagctaacatccccaata------------------------------------
------------------------------------------------------------
-accgctcgatgtcgcgggc
>SEQ4
ggctatcggggagcgagcggtgagttgcacatagaaacactcacaatttctagaactcgg
c----------------------gcttcctcactaacgaactattacaatgcattcggcg
gactccggtccactacaaacgcttttgttac-----------------------------
-----------tttcgttgaaacaattgaggcatacctgttgtaaaatctctctcttacc
cggccactgtagtgggagagaaattaatcgcaatgtaagcagtgtactgtcccgttacgg
taaata------------------------------agtaacaggactgtcatgtgcagt
tgacgccgtgggccgaccctaccatcaacaactattcgtcccagcggctgagtcgatatc
tcacatgtgcaaccagctagacagccactcgtcgaat-----------------------
---------cgtccctggctgcactctgcatacatgcagtaaacatgccatgatatagac
ctcgtgcccggtcatatagacgatgcttaaagtcatgaatgtgcccttgccgagatggat
tatttaatttcggacatttagatatctcatcctggagcggtcggacggaaggaagctccg
ataacccctaa-------------------------------------caccaattacat
tgcataaacgctatgctggcacttttaaaggtatcgaagtcaactgggattgacaagaat
ggcgaaaacatcctggttgagtccgcaaaccgaaagtggtgtacggggagatccggcgtc
ctctgagtggcaactatgttattgataacctaccagttttcttccccaacaaagagccaa
gctcaacggcagtgccgttggccaatttatgttactttggtgtact--------------
------------------------------------------------------------
------------------------------------------------------------
--------aacatccccaat
>SEQ5
gaataacggggggcgttcgttgaatcacacatagacacacg--------------ctcgg
cgaatatcattgcgcgcgtcaccgctctctcagtttagttcgattacaatgctt------
------------------atgcgtttgtcgtacaatcgggaactgtattgtccccggctc
acattcctaggtcg------aacaattgaggcatacctgttgtaaaatctctctcttacc
cggccactgtagtgggagtgaaattaatcgcaatgtaagcagtgtactgtcccgttacgg
taaatacgctattgggaactactaccaagaacagacagaaacaggactcgcatgtac---
---------------------------------actctgcccaacggctgagtcgat---
--------------agctagacagccactcgtcaaaacggcgcgcgcctctgctgatcgt
aacgaggcaccacccaggctgcactctgcatacatggagtaaacatgccatgatatagaa
ctcgtgcccggtcatatagacgatgcttaaagtcatgaatgtgcccttgccgagatggag
tattcttgagcg---------------------------gtcggacggaaggaaggctc-
------------------------------------------------------------
--------------cctgtcacttaaaaag---------------------cacaagaat
ggcga--------------agtccgcaaaccgaaagtggtgtacggggagatccggcgtc
ctctgagtggcaactatgttactaataacctaccagttttcttccccaacaaagagccaa
ggtcatctgcattgccgttgcgtcatgtacgtgggtttggtgtattccagggagaaagta
tcttacatgtgcctgctaccgacattctgctttcaacagcctgagtacccgcgtctacca
taccctatgccacgctgctacggaggacagctgctccgggcaa-----------------
--------aatgtcgcaacc
>SEQ6
gaataacggggggcgctcgttga---------------------------------tcgg
cgaatttcattgcaca--------------------------------------------
-----------------------------atgcaattgggaactggattatccccggctc
acattccgaggtcg------aacaattgaggcatacctgttgtaaaatctccctcttacc
cggccactgcagtgggagagaaattactcgcaatgtaagcagtgtactgtcccgttacgg
taaata------------------------------agtaacaggcctgtcatgtgc---
---------------agcctaccatcaacaactattcgtcccagcggctgagtcgatatc
tcacatgtgcaatcaactagacagccactcgtcgaat-----------------------
---------cgcccctggccgcactctgcatacatggagtaaacatgccatgatatagac
ctcgtgcccggtcatatagacgatgcttaaagtcatgaatgtgcccttgccgagatggag
ta-----------------------------------------gacggattgaaggcgcg
gtaatccctctactatcactcc--------------------------taccagttacgt
ggcataataggtaaactggaactttaaaag---------------------aaacagaat
ggcga--------------agtccgcaaaccgaaagtggtgtacggggagatccggcgtc
ctctgagtggcaactatgttactaataacctaccagttttcttccccaacaaagagccaa
gctcaacggcagtgacgttggccaatttatgttactttggtgtact--------------
------------------------------------------------------------
------------------------------------------------------------
--------aatatccccaat
>SEQ7
gactaatggggggcgatcggtgagtt--------------------gttctaaacctcgg
cgataatcattgcgcgcggcacaactccctcatgaacgcacta-----------------
-----cggtccactgtatatgcttttgtcgttcaaaggggaactttagttttccccggtc
acattccattttcgtgtgtaaacaattgaggcatacctgttgtaaaatctctctcttacc
cggccactgtagtgggagagaaattaatcgcaatgtaagcagtgtactgtcccgttacgg
taatca------------------------------agaaaaagcactgtcatgagcagt
tgacccctagcg------------------------------------------------
--------gctgccagctagacagacactcgtcgaatcggcgcgcgcctctgatgatcgt
aacgagtcacgtccctagctgcactctgcatacatggagtaaacatgccatgatatagac
ctcgtgcccggtcatatagacgatgcttaaagtcatgaatgtgcccttgccgagatggag
ga-----------------------------------------gaaggaatggaggcgcg
ataatccctcttctatcactcc--------------------------taccagttacgt
ggcataataggtaaacttgaacattaaaag---------------------aaacagaat
ggcga--------------aggccgcaaaccgaaactgctggacggggagatccggcgtc
ctctgagtggcaactatgttactaataacctaccagttttcttccccaacaaagagccaa
gtttatcggtattacaagggactga-----------------------------------
----------------caccgacatggtgattcta-------------------------
------------------------------------------------------------
----------------aacc
>SEQ8
gactatcggggagcgaacggtgagttgcacatagaaacactcgcgagttcttgacctcgg
c----------------------gctacctcattcacgaactattaccatgcattcggtg
tactacggtccactgcatacggttttg-----------------ttacgttcctgcgctc
acaatcgtatgtggcgtggaaacaattgaggcatacctgttgtaaaatctctctcttacc
cggccactggagtgggagtgaaattaatcgcaatgtaagcagtgtactgtcccgttacgg
taaatg--------------------------------------------cttgagcagt
cgaagccaagggccgaccgtatcaccaacaactactcttcccagcggccgagtcgatatc
acacatgtgcaaccagc-----------------------cgcgcgcctctgatgatcct
aacgagtcacgtccctggctgcactctgcatacatggagtaaacatgctatgatatagac
ctcgtgcccggtcatatagatgatgcttaaagtcataaatgtgcccttgccgagatggag
tattggaagg--------------------------------------------------
------------------------------------------------------------
---------------------------------------------------aaggctacc
cac----------------agtccgcaaaccgaaagtggtgtacggggagatccggcgtc
ctctgagtggcaactatgttattaataacctaccagttttcttccccaacaaagagccaa
gctcagcggcagtgccgttggccactccatgttactttggtgtact--------------
------------------------------------------------------------
------------------------------------------------------------
--------aacatcgccaat
>SEQ9
gactaacggcggacgttcaatgagtaacacatagacacgcccaccagaactaggcctcgg
cgaatattattgcgcgcgtcaccgctctctcattttcgtacgattgcaa-----------
-----------------------------atacaatcgggaactgtatagtcccggggtc
cgattcctaggtcg------aacaattgaggcatacctgttgtaaaatctctctcttacc
cggccactgtcgtgggagagaaattaatcgcaatgtaagcagtgtactgtcccgttacgg
taagta------------------------------agaaagaggactgtca--------
---------------accgtatcataaacaactactcttcccaggggttgagtcgatatc
acccatgtgcaaccatctagacacccactcgtcgaatcag--------------gatcgt
aacgag-------------tgcactctgcatacatggagtaaacatgcgatgatatagac
ctcgtgcccggtcatatagacgatgcttaaagtcatgaatgtgcccttgccgagatgtag
tattggaagg--------------------------------------------------
------------------------------------------------------------
---------------------------------------------------aaggctacc
cac----------------aggccgcaaaccgaaactgctggacggggagatccggcgtc
ctctgagtggcaactatgttactaataacctaccagttttcttccccaacaaagagccaa
gctcaatagcagtgccgttgggcaatttatgtttccttggtgtact--------------
------------------------------------------------------------
------------------------------------------------------------
--------tatatccccaat
>SEQ10
ggctatcgggcagcgagcgttgagttgcacatagaaacactcacaatttcttgaagtcag
c----------------------gcttcctcactaacgaactattacaatgctctttggt
tacttt------------------------------------------------------
--------------------aacaattacggcatacctgttgtaaaatctctctcttacc
cggccactgtagtgggagagaaattaatcgcaatgtaagcagtgtacagtcccgttacgg
taaata------------------------------agtaacaggcctgtcatgtgc---
---------------acgctaccatcaacaactattattcccagcggttgaatcgatacc
taacatgtgcaatcaactagacagccactcgt----------------------------
----------gcccctgggcgcactctgcatacatgcagtaaacatgccatgatatagac
ctcgtgcccggtcatatagacgatgcttaaagtcatgaatgtgcccttgccgagatggat
tcttaaggctc-------------------------------------------------
------------------------------------------------------------
--------------cctgtcacttaaa------------------------cacacgaat
ggc----------------gggccgcaaaccgaaactgctggacggggagagccggcgtc
ctctgagtggcaactatgttactaataacgtaccagttttcttccccaacaaagagccaa
gctcaagggcagtgcctttggccaatttatgtgacttaggtgtacc--------------
------------------------------------------------------------
------------------------------------------------------------
-----------------aat
>SEQ11
gactaatggggggcgatcgttgagtt--------------------gttctaaacctcgg
cgataatcattgcgcgcggcacaactccctcatgaacgcacta-----------------
---------------------------cggtccgaaggggaactttaattttcaccggtc
acattccatcttcgtgtttcaacaattacggcatacctgttgtaaaatctctctcttacc
cggccactgtagtgggagagaaattaatcgcaatgtaagcagtgtacagtcccgttacgg
taaata--------------------------------------gagtgtcatagac---
-----------------------------------acttcccagctgctgatttgatctc
acacatgtgcacccagctagtcagccactcgtcgataccgtgcgcgcctctgctgatcgt
gacgatttacttccctggctgcactctgcatacatggagtaaacatgccatgatatagac
ctcgtgcccggtcatatagacgatgcctaaagtcatgaatgtgcccttgccgagattgag
tctttaggctc-------------------------------------------------
------------------------------------------------------------
--------------cctgtgacttaaa------------------------aacacgaat
gcc----------------ggtccgcaaaccgaaagtggtgtacggggagatccggcgtc
ctctgagtggcaactatgttactaataacctaccagttttcttccccaacaaagagccaa
agtcatcagcattgccgttgcgtaatgtacgtgggtttggtgtattccaaggcgaaaata
tcttacgagc---------------------tctagcagcctgcgtacccgcgtctacca
taccctgtgccaggctgctaggtcagacggcc------------------------caat
aaactcgcgatg--------
>SEQ12
gactaatggggggcgatcgttgagct--------------------gttctaaacctcgg
cgatactcattgcgcgcggcacgattccctcatgaacgcacta-----------------
---------------------------cgggccgatggggaactttaattttcaccggtc
acattccatcctcgagtatcaacaattgaggcatacctgttgtaaaatctccctcttacc
cggccactgtagtgggagagaaattactcgcaatgtaagcagtgtactgtcccgttacgg
taaata--------------------------------------gactgtcatacag---
------------------------------------------------------------
-------------tacccagctcaagattcgatagtcagcgattcgtccctaccgacctt
------ttacttccatggctgcactctgcatacatggagtaaacatgccatgatatagac
ctcgtgcccggtcatatagacgatgcttaaagtcatgaatgtgcccttgccgagatggat
tatttaatttcg---------------------------gtcggacggattgaaggcgcg
gttacccctgaactataactcc--------------------------caccagttacct
ggcataacaggtatgctgcaactttaaaag---------------------aagaagaat
ggtga--------------agtctgcaaactgaaagtgctgtacggggagatccggcgtc
ctctgagtggcaactatgttactaataacctaccagttttcttccccaacaaagagccaa
cctcaatagcattgccgttgggcaatttatttttccttggtttacc--------------
------------------------------------------------------------
------------------------------------------------------------
-----------------aat
>SEQ13
gactaactgggggcgatcggtgagttgcacataggaacacgcacgagttttagacctcgg
cgattctcatggctaccaggtcgtctt---------------------------------
---------------aatatgtattcgtcgttcaaacggg---------------cgctc
acattcttattt--------aacaattgaggcatacctgttgtaaaatctctctcttacc
cggccgctgtcgtgggagagaaattaatcgcaatgtaagcagtgtactgtcccgttacgg
taaata--------------------------------------gactggcatacag---
------------------------------------------------------------
-------------gacccagctcaagatccgatactcagcgatgcgtccctaccgacctt
------ttacttccatgg--gcactctgcatacatgcagtaaacatgccatgatatagac
ctcgtgcccggtcatatagacgatgcttaaagtcatgaatgtgccctcgcagagatggat
tcttaaggttc-------------------------------------------------
------------------------------------------------------------
---------------ctgtcacttaaagg-------------------------------
-------------------ggtccgcaaaccgaaagtggtgtacggggagatccggcgtc
ctctgagtggcaactatgttattaataacctaccagttttcttccccaacaaagagccaa
gctcaacggcagtgacggtggccaatttatgttactttggagtatccc------------
------------------------------------------------------------
------------------------------------------------------------
----------------caat
>SEQ14
gacta------------------------catagaaacacgcacgagttctagccctcgg
cgattatcaatgcgcgcgtcacagctccctcttttagccacta----------ttcggcg
gactacggtccaatgcatatgcttttgtcgttccgacgggaaattta-------------
-----cttatttcgggtggaaacgattgagccatacctgttgtaaaatctctctcttacc
cggccactggagtgggagtgaaattaatcgcaatgtaagcagtgtactgtcccgttaccg
taatca------------------------------agaaacagcacggtcatgagcagt
agacccct----------------------------------------------------
----------------------------------aacggctgcgcgcctctgatgatcgt
aacgagtcacgtctcaagctgcactctgcatacatggagtaaacatgccatgatatagac
ctcgtgcccggtcatatagacgatgcttaaagtcatgaatgtgcccttgccgagatggat
ttaaggc-----------------------------------------------------
------------------------------------------------------------
--------------actgtcacttaaa------------------------ctcaagaat
tgc----------------ggtccgcaaaccgaaagtggtgtaaggggagatccggcgtc
atctgagtggcaactatgtgactaataacctatcagttttcttccccaacaaagagccaa
agtc-----------------cgaatttatgttagtttggtgtattccag----------
-----------actgccaccgacatgctgattctatcattctgcgtat------------
------------------------------------------------------------
--------------------
>SEQ15
gaataacgggggtcgctcgttgagca----------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------caatgcaaacaattgaggcatacctgttgtaaaatctctctcttacc
cggccgctgtcgtgggagagaaattaatcgcaatgtaagcagtgtactgtcccgttacgg
taaaga----------------------------------------ctgtcatacag---
------------------------------------------------------------
-------------cacctagctcaagattcggtagtcagcgatacgtccctactgacctt
------ttgcttccatccctgcactctgcatacatgcagtaaacatgccatgatatagac
ctcgtgcccggtcatatagacgatgcttaaagtcatgaatgtgcccttgccgagatggat
tcttaaggctc-------------------------------------------------
------------------------------------------------------------
--------------cctgtcaattaa----------------------------------
-------------------cgtccgcaaaccgaaagtggtgtaaggagagatccggcgtc
atctgagtggcaactatgtgactaataacctatcagttttcttccccaacaaagagccaa
agtc-----------------cgaatttatgttagtttggtgtattccag----------
-----------attgccaccgacatgctgattctacc-----------------------
------------------------------------------------------------
---------ataatgcggat
>SEQ16
gacgaattgggt----------------------------------gttctaaccctcgg
cgataatcattgcgcgcggcacaactccctcatgaacgcacta-----------------
-----cggtgcactgtatatgcttttgtcgttcaaagggggactttcatt----------
--------------------aacaattgaggcatacctgttgtaaaatctccctcttacc
cggccactgtagtgggagagaaattactcgcaaggtaagcagtgtactgtcccgttacgg
taaata------------------------------ataaacgggactgtcatgagcagt
tgatgccgagggccgaccgtatcatcaacaactactcttcccaccggcggagtcggtctg
acacatgttcaaccagctagaca---------cgaatcggcgcgcgcctctgatgatcgt
aaccag-------------tgcactctgcatacatggagtaaacatgccatgatatagac
ctcgtgcccggtcatatagacgatgcttaaagtcatgaatgtgcccttgccgagatggag
tatggaag----------------------------------------------------
------------------------------------------------------------
---------------------------------------------------gaacgttac
cac----------------agtccgcaaaccgaaagtggtgtaaggggagatccggcgtc
atctgagtggcaactatgtgactaatcacctatcagttttcttccccaacaaagagccaa
agtcatcagcattgctgttgcgtaatgtacgtgcgtgtggtgtattctaaggcgacaata
tcttacgtgc---------------------tctagcagcctgcttacccgggtctacca
tactctgtgccaggatgctaggtcagacggcc------------------------caat
aaactcgtgatg--------
>SEQ17
gaataacggggggcgctcattga---------------------------------tcgg
cgaatttcattgc-----------------------------------------------
------------------------------cgcaattgggaactggattagccccggctc
acattaccaggtcg------aacgattgagccagacctgttgtaaaatctctctcttacc
cggccactggagtgggagtgaaattaatcgcaatgtaagcagtgtactgtcccgttaccg
taaaca------------------------------agtaacaggcctgtcatctgc---
---------------acgctaccatcaacaagtattattcacagcggttgaatcgattcc
taacatgtgcattcaactagatagccattcg-----------------------------
-------------------tgcactctgcatacatgcagtaaacatgccatgatatagac
ctcgtgcccggtcatatagacgatgcttaaagtcatgaatgtgcccttgccgagatggat
tctttaggcgc-------------------------------------------------
------------------------------------------------------------
--------------cctgtgactt---------------------------aaaacgaat
gcc----------------ggtccgcaaaccgaaagtggtgtaaggagagatccggcgtc
atctgagtggcaactatgtgactaataacctatcagttttcttccccaacatagagccaa
ctttatcggtattacaagggactgatt---------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------gcaaac
>SEQ18
gactcatgttgcgcgatta------------------------------ctaagcctcgg
ccatactcactgcgcgcggcacctttccatcatgaacgcacta-----------------
-------------------------------------cgcaactttaattttcaccggtc
acattccatcttcgagtatcaacgattgagccatacatgttgtaaaatctctctcttacc
cggccactggagtgggagtgaaattaatcgcaatgtaagcagtgtactgtcccgttaccg
taagta------------------------------acaaagaggactgtca--------
-------------------------aaacaacttctcttcccagtggtcgattggatatc
ccccatgagcaaccatccagccacctactcatcgaatcag--------------gctcgt
aacgag-------------tgcactctgcatacatggagtatacatgcgatgatatagac
ctcgcgcccggtcatatagacgatgcttaaagtcatgaatgtgcccttgccgagatgtag
tatttgatttcg---------------------------gtcggacggattgaaggcgtg
ttaaacccggaactata-------------------------------------------
-----------catgctggaaccttaaaag---------------------aaaaacaat
gacga--------------agtccgcaaaccgaaagtggtgtaaggggagatccggcgtc
atctgagtggcaactatgtgactaataacctatcagttttcttccccaacaaagagccaa
ctttataggtattataagggacggatt---------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------gctaac
>SEQ19
gactaacggggggcgattgttga-----------------------gatctagacctcgg
ctattatcattgcgcgcgtcaccgctctctcattttcgtactattactatgctt------
------------------atgtttttgttgttcaatcgggaccttgatattcccgggctc
acattcctacttcg------aacaattgaggcatacctgttgtaaaatctctctcttacc
cggccactgtagtgggagagaaattaatcgcaatgtaagcagtgtactgtcccgttacgg
taaata------------------------------agaaccaggaatgttatgagcagt
ttacgccgaaggccgaccgtagcatcaacaactattcttcccacccgctgactcgatatc
acacatgtgcaaccagctagacagcgactcgtcgaatcggcgcgcgcctctgatgatcgt
aacgagtcacgtccatggctgcactctgcatacatggagtaaacatgccatgatatagac
ctcgtgcccggtcatatagacggtgcttaaagtcatgaatgtgcccttgccgagatggat
tatttaatttcgaaattttagatgtctcaacctgg-------------------------
---acccctgtattataactcctgcaagtcaacggcccctgtccctaacaccaattacat
tgcatgaacggtatgccggcactttaaaaggtat-----------------cgaagccat
ggcgaaaacatcctggttgaggccgcaaaccgaaactgctggacggggggatccggcgtc
ctctgagtggcaactatgttactaataaccttccagttttcttccccaacaaagagccaa
ggtcatcaacagtgccgttccgtaatgtacgtaggtttggtgtattccaaggcgaaatta
tcttacaattgagtgacaccgccattctgcgtctacc----------------------a
tactctatgccaggctgctaaggagcacagctgctccgggcaaaggtctgacggcccaat
aaactcacgatgtcccacca
