>SEQ0
gcgttatccaagatcattgtgccctacagtgccatatctatgcggtatagattgcggacg
agtcagggattgtttcaaatcacgacactcaggccagtaccatactagctatcacacatc
ggtcaagggcggaggcggggactagaactgtggttaattgaagtggtcgcagcatacaac
cgctagcgtcacacgaggcattaaagtggggcaatggtactgtgggactaaacatgctag
ggagccgttccaccctaagcgtgacgtcagaggatatctacgtaagtgtcgaccggcgct
tcctatgacgatttcgagtgcgcgttgtgatacacgtctgtgaacgaaactgaatttgaa
tcttcaggttccgggcgggccttttagtatgggttgacgttggggaattagcggaccaag
acgttgtgctctggaatcagcacaggaaatgccatgctagatacactataaggtagacc-
---acttattagttacccacctagctgttctctctgcccaacattcccaacaacatcgca
tcagtgaagagtcgttttggctttcaggggacgaagggcccaagcacgaattttcatggg
cggcgacatactttttgagaccccgaaagtggtcaagatcggttgtgccggtaccagaca
acaattgtgtttggggggcttcgcacagttagattcagcaaccctttaatgtagcggatg
catttcgcaccaagtatgctggggtagcagcatacgcagccgagaaacacattggaaact
ttaccgttccacccgaacccatttgttcctgaagcttatctcaaccgcaactccagtaca
gtggaggaacatgtcgctgatcgagcggaatctgagagcaaatggtgggtcggcaggccc
acgacgtaaggggatgagcagtaaagttttatatgccttttaagcgcgatttatataact
tgtcttagcatcctcacgatcgaggagcgattgacataaggaaaccaacatcttcgttta
ttttgacccgcttcagccacaaagctgatgaagagtgtaatggggggtcaacgtggcgac
cagtcaggccgcccgttgtggaaa
>SEQ1
gcgttagccaagagcgttgcgccctccagtgccatatctatgcggtatggattgcggacg
agtcagggattttttaaaatcacgacactcagggcagtaccatactagctctcacgcatc
--------------------actagaagtgtggttaattgaagcggtcgcagcatacaac
cggtagagtcacacgaggcattaaagtggggcaatggtactgtgggactaaacatgctag
ggagccgttcc-------gcgtgacgtcagaggatatctacgtaagtgtcgaccggcgct
tcctatgacgatttcgagtgcacgttgtgatacaagtctgtgaacgaaactgtatttgaa
t--------------cgggccttttagtatgggttgacgttggggaattagcgtaccaag
actttgtgctatggaatcagcacaggaaatgcgatgctcgctacactttaaggtagacc-
---acttattagttacccacctagctgttctctctgcccaacattcccaacaacatcgca
tcagtgaagagtcgttttggctttcaggggacgaagggcccaagcacgaattttcatggg
cggcaacatactttaagagcccccgaaagtgttcaagatcggttgtgccggtaccagaca
gcaattgtgtttgggtggcttcgcccagtta---------------------agcggatg
catttctcgacaagtgtgctggggtagcagcatacgcaaccgagaaacacggtgg-----
-----------------cccatttgttcctgaagcttatctcaaccgcaactccagtaca
gtggaggaacatgtcgctgatcgagcggaatctgagagcaaatggtgggtcggcaggccc
acgacgtaaggggatgagcagtaaagttttatattccttttaagcgccattgatataact
ggtcttagcatccgcacgatcgagacgcgcttgacataaggttaccaacatcttcgttta
ttttgacccgcttcagccacaaagctgatgaagagtgtaatggggggtcaccgt------
------------------tgttga
>SEQ2
gcgttatccaagatcattgtgcattat--------------------tagattgcggacg
ag--------------------------tcaggcgagtactatactagctatcacacatc
agtcaagggcggaggtggagactagaactgtggttaatggaagagatcgccacatacaac
cgctagcgtcacacgaggcattaaagtggggcaatggtactgtgggactaaacatgctag
ggagccgttccaccctaagcgtgacgtcataggatatctacgtaagtgtcgaccggcgct
tcctatgacgatttcgagcgcgcgttgtgaaacacgtttgtgaccgaaactgaatttgaa
tcttcaggttccgggcgggcgttttagtatgggttgaccttgggtaattagaggaccaag
acgttgtgctctggaatcagcaaacgaaatgcaatgctagatacactttaaggtagacc-
---acttattagttacccacatagctattctctctgcccaacattcccaacaacatcgca
tcagtgaagagtcgtattggctttcaggggacgaagggcccaagcacgaattttcatggg
cggcgacatactttttgagac---------------------ttgtgccggtacgagaca
acaattgtgtttgggggggtccgcacagttagattcagcaaccctttaatgtagcggatg
catttcgcacctagtatgctggggtagcagcatacgcagccgagaaacacattggaaact
ttgccgttccacccgaacccatttgttcctgaagcttatctcaaccgcaactccagtaca
gtggaggaacatgtcgctgatcgagcggaatctgagagcaaatggtgggtcgggaggccc
acgacgtaatgggatgagcggtaaagttttatattccttttaagcgccattgagataact
ggtcttggcaaccgcacgatcgagacgcgcttgacatgagcttaccaacatcttcgttaa
ttttgatccgcttcagccacaacgcttataaagagtgtaatggggggtcaccgt------
------------------tgttga
>SEQ3
gcgttatcaaagatccttgtgcattat--------------------tagattgcggacg
ag--------------------------tcaggcgagtactatactagctatcacacaaa
agtcaacggcggaggtggagacaggatgtgtggttaacggaagggatcgccacatacaac
cgc-----------------ttaaagtggggcaatggtactgtgggactaaacatgctag
ggagccgttcc-------gcgtgacgtcagaggatatctacgtaagtgtcgaccggcgct
gcctatgacgatttcgagtgcacgttgtgatacaagtctgtgaacgaaactgtatttgaa
t--------------cgggccttttagtatgggttgacgttggtgaa-------------
--------------aatcagcacaggaaatgcgatgctcgctacgctctaaggtagacc-
---acttattaggtacccacctagctgttctctctgcccaacattcccaacaacatcgca
tcagtgaagagtcgttctggctttcaggggacgaagggcccaagcacgaattttcatggg
cggcgacaaactttttgagaccccgaaagt-------------------ggtcccagaca
acaattgtgtttggggtgcttcgcatagttagtttcagcaacact---------------
----------caagtatccgggggtagcagcatatgcagccgagaaagacattggaaact
ttaccgttccacccgaacccatctgttcctgaagcttatctcaaccgcaactccagtaca
gtggaggaacatgtcgctgatcgagcggaatctgagagcaaatggtgggtcggcaggccc
acgacgtaatgggatgacaggtaaagttttattttccgtttaagcgccgttgcgataact
ggtctgggcaaccgcacaatcgagacgcgctcgagatgagcttaccaacttcttcgttaa
ttttgatccgctgccgccacaagacttacaaagagtccggtgttga--------------
------------------------
>SEQ4
ccgttagccgagagcgttgcgccggctagttacatatctatgcggtatgcattgcggacg
agtcagggattttttaaattcacgacactcagggcagtaccatactagctctcacgcatc
--------------------actggaagtgtggttaattgaagcagtcccagcatacaac
cagtagagtcaaacgaggcattaaagtggggcaatggtactgtgggactaaacatgctag
ggagccgttcc-------gcgtgacgtcagaggatatctacgtaagtgtcgaccggcgct
tcctaggacgttttcgagcgcgcgttgtgaatgacgtttgtgaccggaactgaatttgag
tcttcaggttccggccgggcgatttagtatgggttcaccttgggtaattagatgaccacg
atgttgtgaacttgaatcagcaaacgaaatgcaacgctagatacacttaagggtagacc-
---acttattcgttacccacagagctgttctctatgcccaacattcccaacaacatcgca
tcagtgaagagtcgttctggctttcaggggacgaagggcccaagcacgaattttcatggg
cggcgtcatactttttgagac---------------------tagtgccggtacgagaca
acaattgtgtgcgggtggttccgcacagttagattcagtaaccctt--------------
--------------tatgctggggtagcagcttacggagccgagaaacccattggaaact
tttccgttccacccgaacccctttgttcctgaagcttatctcaaccgcaactccagtaca
gtggaggaacatgtcgctgatcgagcggaatctgagagcaaatggtgggtcggcaggccc
acgacgtaatgggatga--------attttatgttccttttaagcaccattgaaataact
ggtcttagcatccgcacgatcgagacgccctttacgtaacgttaccaacatcttctttta
tggtagagtgccgttgttga----------------------------------------
------------------------
>SEQ5
ccgttagctgagagcgttgcgcctgct---------------------------------
---tgtgacttttttgaatccacgacactaagggcagtaccatacttgcgctcacgcatc
--------------------actcgaattgtggttaattatagcagtcccagcatgcgcc
cagtagggtcaaacgaggcataaaagtggggcaatggtactgtgggactaaacatgctag
ggagccgttccaccctaagcgtgacgtcagaggatatctacgtaagtgtcgaccggcgct
tcctgggacgcttgcgaccgcgcgatgagaatgacgtttgtgaccggaactgaatttgag
tcttcaggctccggccgggcgcttaagaatgggttaaccttgggtaattagatgaccccg
atgttgtgaacttgaatcagcaaacgaaatgcaaccctgtatacacttaagggtaaacc-
------------------acagagctgttctctctgcccgacattcccaacaacatcgca
tcagtgaagagtcgttttggctttcaggggacgaagggcccaagcacgaattttcatggg
cggcgacatactgtttgagac---------------------ttgtgccagtacaagcca
acaattgtgtttgggggcgtccgcacagtaagattcattagccctttaatgtagc-----
---------------------------cctagtttgctgccgggaaac------------
------ttccacccgaacccatttgttcctgaagcttatctcaaccgcaactccagtaca
gtggaggaacatgtcgctgatcgagcggaatctgagagcaaatggtgggtcgggaggccc
acgaggtaacgggatgacaggttaagttttcttttccgtttaagcgccgttgcgaaaaca
ggtcggcgcaaccgcacaatcgagacgcgctcgagatgagctcaccaacttcatcgttaa
ttttgatccactgccgccacaagaattacaaagagtccggtgttgt--------------
------------------------
>SEQ6
gagttatcaaagataattgtgcattat--------------------tagattgcggacg
agtcagg-------------------------------------ctagctatcacacaaa
agacaacggccgaggtggagacaggaggt-------------------------------
-------------caaccgcttaaagtggggcaatggtactgtgggactaaacatgctag
ggagccgttcc-------gcgtgacgtcagaggatatctacgtaagtgtcgaccggcgct
tcctgggtcgcctgcgaccgcgcgatgagaatgatgtttgtgaccggacctgaat-----
---------------cgggcgcttaagattgggttaaccttgggtaattagatgacaccg
atgttgtgaacttgaatcagcaaacgaaatggaaccctgtatacactt------------
--------------------agagctgttctctctgcccaacattcccaacaacatcgca
tcagtgaagagtcgttttggctttcaggggacgaagggcccaagcacgaattttcatggg
cggcaagatactttaagatcccccgaaagtgttcatgatcggtcgtgccggtgcctgaca
gaagtagtgttagggtggcttcgcccagttaagccgatacatttctcga-----------
----------caagtttgctggggtagcagcatacgcaagcgaggaac------------
----------acgctggcccagttgttcctgaagcttatctcaaccgcaactccagtaca
gtggaggaacatgtcgctgatcgagcggaatctgagagcaaatggtgggtcggcaggccc
acgacgtaatgagatga----------------------------------ataagtact
ggtcttagcatccgcacgatcgagacgccctttacataacgtaaccaacatcttctttta
cgtgccgttgttga----------------------------------------------
------------------------
>SEQ7
gcgttatcaaagataactgtgcattat--------------------tagattgcggacg
agtcagg--------------------------------------------------aaa
agacaacggccgaggtggtgac--------------------------------------
-------------ctaccgcttaaagtggggcaatggtactgtgggactaaacatgctag
ggagccgttcc-------gcgtgacgtcagaggatatctacgtaagtgtcgaccggcgct
tcctttgaccacttc----------------------------ccgaagctgaatttgat
tgatcaggttacgggcgggcgttttagtgtgggttgaacttggctaaatagaggaac---
--------------gatacgcaaacgaaat-----------------------tagacc-
---acttattggttacccacatagctattctctctgcccgacattcccaacaacatcgca
tcagtgaagagtcgtattggctttcaggggacgaagggcccaagcacgaattttcatggg
cggcaagatactttaagatcccccgaaagtgtatatgatcggtcgtgccggtgcctgaca
gaagtagtg-----------------agttattctcga----------------------
----------caagtttgctgggctagcagcatacgcaagcgagtaac------------
----------acgatggccgagttgttcctgaagcttatctcaaccgcaactccagtaca
gtggaggaacatgtcgctgatcgagcggaatctgagagcaaatggtgggtcggcaggccc
acgacgttatgagatga----------------------------------ataagtact
ggtcttagcatccgcacgatcgagacgccctttacatcacgtaaccaacatcttccgtgg
ttga--------------------------------------------------------
------------------------
>SEQ8
gcattatccaagatcattgtgccctgcagggccatatctatgcggtatagaatgccgacg
agtcagggattgtctcaaatcacgacactcaggccaataccataatagctatcacc----
--------------------actagaacagtggttaattgacgtggtcgcggcatacgac
cgctagcgtcacgcgtggcataaaagtggggccatggtactgtgggactaaacatgctag
ggagccgttccaccctaagcgtgacgtcagaggatatctacgtaagtgtcgaccggcgct
tcctaggacatttgcgagcgaacg-----------------gaccggtactgaatttgag
tcttcagtttccggccgggcgatttagaatgcgttcgcctggggtaattggatgaccacg
acgttgtgaacgtgaatcaacaaacgaaaagcaacgcaagatacacttaagggtagacc-
---acttattcgttacccactgagctattctctctgcccgacattcccaacaacatcgca
tcagtgaagagtcgtattggctttcaggggacgaagggcccaagcacgaattttcatggg
cggcgacatactgtttcagac---------------------ttgtgccagtccaagcca
acaatt-------------------cagtaagattcattagccctttaatgtagc-----
--------------------------------------gccgggaaac------------
------ttccacccgaacccatttgttcctgaagcttatctcaaccgcaactccagtaca
gtggaggaacatgtcgctgatcgagcggaatctgagagcaaatggtgggtcggcaggccc
acgacgtaatggg---------------------tccgtttaagcgccggggcaataatt
ggcctgggcaaccgcacaatcgaggggcgctcgagatgggcttaccaacttcctcgttaa
tattgagccgctgccgccacaagactaacaaagagtccggtgatga--------------
------------------------
>SEQ9
gcgttagccaagagggttgcgccctccagtgccgcatcgatgtggtatggatcgcggaca
agttagggatttcttaaaaccccgacactcagggcagtgccatactagttctcacgcatc
--------------------actagaagtgtggttaattgaagcggtcgcagcatacaac
cggtagagtc----------ttaaagtggggcaatggtactgtgggactaaaaatgctag
ggagctgttcc-------gcgtgacgtcagaggatatctacgtaagtgtcgaccggcgct
tcctaggacatttgagagcgaacgggccagtttccg------------------------
---------------------------------------------gattggttgaccact
acgttgtgaacgtgaatcaataaacgaaaagcaacgcaagatacacttaaggggagacc-
---acttaatcgttacccactgatctgttctctctgcccaacattcccaacaacatcgca
tcagtgaagagtcgttttggctttcaggggacgaagggcccaagcacgaattttcatggg
cggcgacaagcttattgagaccccaaaagtggtcccgg----------------------
------------agggtgcttcgcatagttagtttcagcaaccct---------------
----------caaggatccgggggtagcagcacatga-----------------------
----------------------tcgttcctgaagcttatctcaaccgcaactccagtaca
gtggaggaacatgtcgctgatcgagcggaatctgagagcaaatggtgggtcggcaggccc
acgacgtaatgggatgacaggtaaagttttattttccgtttaagcgccgttgtgataact
ggtctgggcatccgctgaatcgagacacgctcgagatgagcttaccaacttcttcgttaa
ttttgatacgctgccgcgaccggtgttga-------------------------------
------------------------
>SEQ10
ccgttagccgagagcgttgagccggctattttcctaaccatgcggtacgcatcgcggacg
agtcagggattttttaaattcacgacactctgggcagtacaatactagctctcacgcatc
--------------------actggaagtgtggttaattgaagcagtcccagcatacaac
cagtagagtcaaactaggcataaaagtggggcaatggtactgtgggactaaacatgctag
ggagccgttccaccctaagcgtgacgtcagaggatatctacgtaagtttcgaccggctct
gcctatgccgatttcgagtgcacgttgtgatacaagtctgtgaacaaaactgtaattgaa
t------------------------agtatcggtttacgttggtgaa-------------
--------------aatcagcacaggaaatgcgatgctcgttaagctctaaggt------
----------------------agctgttctctccgcccaacattcccaacaacatcgca
tcagtgaagagtcgttctgggtttcaggggacgaagggcccaagcacgaattttcatggg
cggcgacgtactgtttgagac---------------------tcgtgccggaacaagcca
ataattttgtctgggggagtccgcacagtaagattcattagccctttaatatcgc-----
---------------------------cctagtttgctgccgagaaac------------
------atctacctgaacccatttgttcctgaagcttatctcaaccgcaactccagtaca
gtggaggaacatgtcgctgatcgaccggaatctgagagcaaatggtgggtcggcaggccc
acgacgtaatgtgatga--------attttatgttccttttaggcaccattgaaataact
ggtcttagcaacgtaaccaacagtgtac--------------------------------
-------------------------------------cggtgttga--------------
------------------------
>SEQ11
gcgttatccaagatcattgtgcattat--------------------tagattgcagacg
agtcagg-----------------------------------------------cacatc
cctcaagggcggaggtggagtttagaactgtggttaatcgaagagatcgccacatacaac
cgctagcgtcacgcgaggcattaaagtggggcaatggtactgtgggactaaacatgctag
ggagccgttcc-------gcgtgacgtcagaggatatctacgtaagtgtcgaccggcgct
tcctaggacattttcgagtgcgcgttgttactgacgtttttcggccggg-----------
----------------------------------------agaattattagatgacgtcg
gtgttgtgaacttgaatgagcgaacgcaatgcaacgctagatgcacttaagggtagacc-
---acttattcgttaccc------ctgttctctctgcccaacattcccaacaacatcgca
tcagtgaagagtcgttttggctttcaggggacgaagggcccaagcacgaattttcatggg
cggcgacatagtgtttgagacttt------------------------------------
-caattgtgtttgggggcgcctttaatgtaaccctagtttgct-----------------
------------------------------------------------------------
------ttccacccgaacccatgtgttcctgaagcttatctcaaccgcaactccagtaca
gtggaggaacatgtcactgatcgagcagaatctgagagcaaatggtgggtcggcaggccc
atgacgtaatgggatgacgggtaaagttttattttcctttcaagcgccgttgcggtaact
ggtct-----------------------gttcgcggtaagtttaccaacttcttcgttaa
ttttgatccgctgccgccactccggtgttga-----------------------------
------------------------
>SEQ12
gccttatctaagg-----------------gccatatctgtgcggtatagaatgccgacg
a--------------------acgacgcgcaggccaataccataatagctatcacc----
--------------------actagaacagtgggtaatggacgtggtcgcggc-------
-------gtcacgcgttgcattaaagtggggcaatggtactgtgggactaaacatgctag
ggggccgttcc-------gcgtgacgtcagaggatatctacgtaagtgtcgaccggcgct
tcctaggacgttttcgcgcgagggttgtgaatgacgtttgtggtcggaactggatttgaa
ttt-----------------------gtatgggtccaccttgggtaactagatgaccatg
atagggtgaacttgaatcggcgcacgaaattaatcgttagatacacttaagggtagtcc-
---actaattcgttacgcacagagctgttctctctgcccaacattcccaacaacatcgca
tcagtgaagagtcgttttggctttcaggtgacgaagggcccaagcacgaattttcatggg
cggcgacaaactttctgagacaccgaaagt-------------------cgtcccagaca
acaattgtgtttgggatgcttcgcctatttagtttcaacaacaat---------------
----------caactatgcgggggtagtagcatatgcggccgagaaagacattggaaact
ttaccg-----------------tgttcctgaagcttatctcaaccgcaactccagtaca
gtggaggaacatgtcgctgatcgagcggaatctgagagcaaatggtgggtcggcaggccc
acgacgtaatgggatgacatgtaaagttttattttgcgtttaagcgccgttgtgataact
ggtctgggcatccgctgaatcgagacacgctcttgatgagcttaccaacttcttcgtta-
------------------------------------------------------------
------------------------
>SEQ13
gcgttcctaaagagggttgcgacctccagtgccgcatccaagtggtatggatcgcggaca
agttagggatttctgaaaaccccgacactcagggtagtgccatactagttctcacacaac
--------------------actagaagtgcggttaattgaagcggtcgcagcatacaac
c----------cgtagagcctaaaagtggggcaatggtactgtgggactaaacatgctag
ggagccgttccaccctaagcgtgacgtcagaggatatctacgtaagtttcgaccggctct
tcctgggacgcttgccaccgcgcgatgagaacgacgtttgtgaacggaactgac------
---------------ccagtgcttacgaatgggttaaccctgggtaa-------------
----------cttgaatcagcaaacggaatgcaaccctctatacacttaagggtaaacc-
------------------ccagagctgttctctctgcccaacattcccaacaacatcgca
tcagtgaagagtcgttgtggctttcaggggacgaagggcccaagcacgacttttcatggg
cggcaacgtactgtttgggaccccgaaagcggtcaagaccggttgtgccggtaccagaaa
actgtagcg-----------------------------------------------gatg
catttcgcaccaagtatgctgg-----------------------aacacattggaaact
ctaccgttccacccgaacccattcgttcctgaagcttatctcaagcgcaactccagtaca
gtggaggaacatgtcgctgatcgagcggaatctgagagcaaatggtgggtcgggaggccc
acgacgtaatgagatcc----------------------------------ataagtact
ggtcttagcatccgcacgatcgagacgctgtctacccaaagtac----------------
------------------------------------------------------------
------------------------
>SEQ14
g------------------------acagtgccatatctatgcggtatagattgcggacg
agtcagggattgtttcaaaccacgac-----------------actagctatcacacatc
ggtcaagggcggaggcggggactagaactgtggttaattgaagtggtcgcagcatacaac
cgcta------------gcgttaaagtggggcaatggtactgtgggactaaacatgctag
ggagccgttcc-------gcgtgacgtcagaggatatctacgtaagtgtcgaccggcgct
gcctgtgccgatttcgagtgcacgttgtgatacaagtctgtgaacaaaactgtaattgga
t------------------------agtataggtttacgtaggtgaa-------------
--------------aatcagcacaggaaatgcgatgctccttaagctctaaagt------
----------------------agctgttctctctgcccaacattcccaacaacatcgca
tcagtgaagagtcgttttggatttcaggggacgaagggcccaagcacgaattttcatggg
cggcgccgtccagtttgagac---------------------tcgtgcgggaacaatcca
ataatattatctgggggagtccgcacagtaagattaattagccctttaatctcga-----
---------------------------cctagttttctgcctagaaac------------
------atctacctgaacccatttgttcctgaagcttatctcaaccgcaactccagtact
gtggaggaacatgtcgctgatcgagcggaatctgagagcaaatggtgggtcggcaggccc
acgacgtaatggggtaa-------------------------------------------
-----------ccgcacaatcgagcgtcgctcgggatgggcttaccaacttcctcgttat
tattgagccgctgccgccacagggcttacaaagggtccggtgctca--------------
------------------------
>SEQ15
ccgttagctgagagcgttgagccggctattttcctacccatggggtaagcatcgcggacg
agtgagggattttttaaactcattacactctgggcaggacaatactagctctcac-----
--------------------actggaagtggggttaattgaagcagtccca---------
----------aaacgaggccttaaagtggggcaatggtactgtgggactaaacatgctag
gaagccgttcc-------gcgtgacgtcagaggatatctacgtaagtgtcgaccggcgct
tcctgggtcg-----------------------acgtttgtgaccgcaccagagt-----
---------------tgggcgattaagattgggttaacctggggtaattagatgaccccg
atgtt-------------------------------------------------------
---gtctatttgatacacttagagctgttctctctgcccaacattcccaacaacatcgca
tcagtgaagagtcgttttggatttcaggggacgaagggcccaagcacgaattttcatggg
cggcgacatactgtttcagac---------------------ttgtgccagtccaagcca
acaatt-------------------cagtaagattcattagccc----------------
--------------------------------------gccgggaaac------------
------ttccacccgaacccatttgttcctgaagcttatctcaaccgcaactccagtaca
gtggaggtacatgtcgctgatcgagcggaatctgagagcaaatggtgggtcggcaggccc
acgacgtatagggatgacgggtaaagttttatttaccttacaagcgccgatgtggtaact
ggact-----------------------gttcgcggtaagtttagatcctctggcgccac
tccggcgctga-------------------------------------------------
------------------------
>SEQ16
gcattatacaagatcattgtgccctgcagggccatatctatgcggtatagaatgcccaag
agtcagggattgtctcaaatcacgacactcagt---------------------------
--------------------------------atcacctgacgtggtcgcggcatacgac
cgcgagtgtcacgcctggcattaaagtggggcaatcgtactgtgggactaaacatgctag
ggagccgttccaccctaagcgtgacgtcagaggatatctacgtaagtgtcgaccggcgct
tcctaggacgttttccagagcacgttgtggatgacgtttgtgaccggaactgaatttgag
tcttcaggttccggccgggcgacttagcatgggttcatgctgggaaattagatgaccatg
atgtttttaacttaaatcggcaaacgaaatgcatcgagagatacacttaagggtagacc-
---aattaatcgttacgcacagagctgttctctctgcccaccattcccaacaccatcgca
tcagtgaagagtcgttttggaattcaggggacgaagggcccaagcacgaattttcatggg
cggcgacaaactttctgtgac--------------------------------ccagacc
acaactgaatatggggtgcttcgcctagttagtttcaacaataat---------------
----------caactatgcgggggttgaggcata--------------------------
--------------gaaactttacgttcctgaagcttatctcaaccgcaactccagtaca
gtggaggaccatgtcgctgatcgagcggaatctgagagcaaatggtgggtcggcaggccc
acgatgttatgagatga----------------------------------ataagttct
actcttagcatccgcacgatcgagacgccctttccatcacgtaaccgtggttga------
------------------------------------------------------------
------------------------
>SEQ17
ccgt----------------------------------cacgcggtactcatcgcggacg
cgtcagggattttttaaattcacgacactccgagcagtacaatactagcactcacgcatc
--------------------actggaagtgtgcttaattgaagcagtcccagcatagaac
caatagattcaaactaggcataaaagtggggcaatggtactgtgggactaaacatgctag
ggagccgttccaccctaagcgtgacgtcagaggatatctacgtaagtttcgaccggctct
tcctgggtcgact-----------------------------------------------
------------------------------------------------------------
-----------------------------------gttgtccccgctccagagtagttgg
ttaacctggtgtctatttgtagagctattctctctgcccaacattcccaacaacatcgca
tcagtgaagagtcgtattggctttcaggagacgaagggcccaagcacgaattttcatggg
cggcaagatactttatgatcccccgaaagtgtatatcatcggtcgtgccggtgcctgaca
gaagttgtg-----------------agttattctcga----------------------
----------caagtttgctgggcgagcagcatacgcaagcgagtaacacg---------
--------------------atgggttcctgaagcttatctcaaccgcaactccagtaca
gtggaggaacatgtcgctgatcgagcggaatctgagagcaaatggtgggtcggcaggccc
acgacgtaaggggatga---------------gcattttttaagcgcgatggaaatcact
-------------------------------------aaggaaaccaatagctgcgttta
ttttgacccgcatcagtggaaa--------------------------------------
------------------------
>SEQ18
gccatatcta--------------------------------------------------
-----------ttcgagggattcgaca-------------------------cacacctg
ggtcatgggcggaagcggggaccagaactgtggttaattgaagtggt-------------
--------------------taaaagtggggccatggtactgtgggactaaacatgctag
tgagccgttccaccctaagcgtgacctcagaggatatctacgtaagtgtcgaccggcgct
t-------------------------gggatccaagtctgtgtttgaat-----------
---------------cgggccttttagtatgggttgacgttggtgaa-------------
--------------aatcagcacacgaaatgcgatgctggctacgctctaaggtagacc-
---actaattagctacccaccaagctgttctctccgcccaacattcccaacaacatcgca
tcagtgaagagtcgttctgggtttcaggggacgaagggcccaagcacgaatcttcatggg
cggcgacatactgtttcagac---------------------------------------
---------------------aattcagtaagattcattagcc-----------------
--------------------------------------gccgggacac------------
------ctccacccaaacccattagttcctgaagcttatctcaaccgcaactccactaca
gtggaggaacatgtctctgatcgagcggaatctgagagcaaatggtgggtcggcaggccc
acgacgtaatgagatcc----------------------------------ataagtact
ggtcttagcatccgcacgatcgagacgctgtctacccaaag-------------------
------------------------------------------------------------
------------------------
>SEQ19
gc---------------------------------------acgttatagaatgacgacg
ggtcagggattgtctcgaatcacgacgctcgggcctatgccacaatagctatcacc----
--------------------actagaacagtggttaattgacttggtcgctgcac-----
--------tcccgcgtggcattaaagtggggcaatggtactgtgggactaaaaatgctag
ggagccgttcc-------gcgtgacgtcagaggatatctacgtaagtgtcgaccggcgct
t-------------------------aagatccaagtctgtgtttgaat-----------
---------------cgggccgtttagtatgggttgacgttggtgaa-------------
---------------------------------------------ctgtaatgcgaacc-
---actaattagctacccaccgaactgttctctccgcccaacattcccaacaacatcgca
tcagtgaagagtcgttctgggtttcagggcacgaagggcccaagcacgaatcttcatggg
cggcaagatactttatgatcccccgaaagtgtatatcatcggtcgtgccggtggctgaca
gaagttgtcatcgcga--------------------------------------------
----------aaagtttgctgggcgagcagcatacgcaagcacgtaac------------
-----------------acgatgtgttcctgaagcttatctcaaccgcaactccagtact
gtggaggaacatgtcgctgatcgagcggaatctgagagcaaatggtgggtcggcaggccc
acgacgtaaggggatgagaagtaaagttttatgttcctattaagggccattgatagaact
ggtctcagcctccccacgatcgagacccgcttgacataaggttaacaacatcttggcca-
-------------------caaagctgatgaagactgcgatggggggtcacccttgttga
------------------------
