>SEQ0
gaccaggaatatctcgaaacgcagatacttccgtgacgccctacttctaagcgtgttggg
ttcgcctctcgactcatcgacaggcgtgatctagaggagagcgccat--cgcgcgcagag
gaatgaggacgttggtgttaacatgccctgtcggtccgtatagatcacgggtcaaacgtg
aactgcgagatgtgacaggccggcacaaggataattggatgaggaccctggtccaccaaa
cgtacttaactgttattttctaccccaaaagagctactttgcggccggccgccactccca
acaatcgaagggctgtgaatggtctctagtcacattctgaacgtcacaccccacattggt
ccccctttcttctacatagacttgagttaggtttatatgtgcggctgcgtcctgctgggc
actctctcaccgcaaacggcgagataccctacacgtgccacgtcacaaaggggtttgtgc
ggacttccggcttaagcaagagctatttgcccatcgccacatttcggagtcgctgaaaag
gcagtgcttcaccgttaagaagacccataaatctaattagcggagaatgtagtctgcaca
agtatcttatccctaatggtcataacgccggaagtttagcatatatatgggaccgccgtg
aggttgtgtttgtagttctaactctcattaccccggcaggacaattcaacgatatttgac
gaacaacgtatctgccttccccaaaagtacggggttgggctaactactggatgtagatga
atagggtattacctcctaaaaggttgcctgttaagtgtctcgtgccggaagcactcctcc
agcagaaagcggggtgtgataaaagtacatgaatacgtctatcaggtctaatggactttc
atgttagcaccgttggtgtcgttaacttcaacccgtcgccgataagtcaggggcgctttt
ctatcgagagccgaatcgaagactcctttcgcaattaatacgcattccggggtggcctaa
accagtacttacctgccacatattagcatctgattgtaattccacgctgtatgttacttc
ggaagtaggaaccccgtaagcg
>SEQ1
gaccaggaatatttcggaacgcagatacttccgtgacgccctacttctaagcgtgttggg
ttcgcctcgcgactcagcgacaggcgtcatgtagagtagagcgccgt--cgcgcccagag
gaatcaggacgttggtgttaacatgccctgtcggtccgtacatatcacggatcaaacggg
aactgcgagat-----------gcacaaggataattggatgaggaccctggtccaccaga
cgtacttaactgttattttctaccccaaaagagctactttgcggccggccgccactccca
acaatcgaa---------------tctagtcacattctgaacgtcacaccccacattgat
ccccctttcttctacataaacttgagttaggtttatatttgcgcctgcgtcctgcttggc
actctctcaccgcaaacggcgagataccttacaagggccacgtcacaaaggggtttgtgc
ggacttccggc-----------ctatttgcccatcgccacatttcggagtcgctgaaaag
gcagtgcttcaccgttaagaagacccataaatctaattagcggagaatgtagtctgcaca
agtatcttatccccaatggtcataactccggaagtttagcatatatatgggg--------
----------------------tctctttcctccgacaggacaattcaacggtatatgac
gaacaacgtatctgc---------------------gggctaactactggatgtagatga
ataggg----------taaaaggttgcctgttaagtgtctcgtgccggaagcactcctcc
agcagaaagcggggtgtgataaaagtacatgaatacgtctatcaggtctaatggactttc
attttagcgccgttggcgtcgtaaccttcaacccgtcggcgatgagtcaggggcgctttt
ctgtcgagagatgaatcgatgacccctttcgcaaataatatgcattccggggtggcctaa
accagtacttacctgccacatattagcatctgattgtaattccccgcagtaagttgcttc
ggacgaaggaaccccgtaagcg
>SEQ2
gaccacgaatattgcggaacgcagatacttccgtgacgccctacttcaaagagtgttggg
ttcgcctcgcgactcagcgacaggcctcaggtaga--------------------cagag
gcatcaggacgttggtgttaacgtgcgctgtcggt-----------------caaacggg
aactgcgatat-----------gcacaaggataattggatgaggaccctggtccaccaaa
cgtacttaactgttattttctaccccaaaagagctactttgcggccggccgccactccca
acaatcgaa---------------tctagtcacattctgaacctcacaccccacattgag
ccccctttcttgtacataaacttgagttaggtttatatttgcgcctgcgacctgcgtggc
actctcactccgcaaacggcgagctaccttacaacggccacgtcagaaagggatgtgtgc
ggacttccggc-----------ctatttgcccatcgccacatttcgcagtcgctgacaag
gcagtgcttcaccgttaagaagacccataaatctaatcagcggagaatggagtctgcaca
agtgtcttttccccgatgggcatatcgcgggaagtttagcatttataagggaccgccgtg
aggttgtgtttgtagttctaactctcat-----------------------gtatatgac
gaacaacctatgtgccttccccaaaagtacggggttgggctaactactgtatttagatga
atatggtattacctcctaataggttgcctgttaagtgtctcgtgccggaagcactcctcc
agcagaaagcggggtgtgataaaagtacatggatacgtctatcaggtctaatggactttc
atgttagcaccgttggtatcgttaacttcaacccgtcgccgatatgtcaggggcgctttt
ctatcgaaagcccaatcgaagactcctttcgtaatcaatacgcat---------------
------actcacctgccacatattagcatctgattgtaaatccacgctgggtgttacttc
ggaagtaggaaccccgtaagcg
>SEQ3
gaccaggaatatttcgggccgcagatacttccgcgatgccctacttttaagtgtgttggg
ttcgcctcgagactcagcgacacgcatcatgtagagtagagcgccgt--cgggcccagac
gaatcaggacgttggtgttaacatgccatgtcggt-------------------------
acctgcgtgat-----------gcacaaggataattggatgaggaccctggtccaccaga
cgtacttaactgttattttctaccccaaaagagctactttgcggccggccgccactccca
aaaatcgaa---------------tgtagtcaca-----------acaccccacattgat
ccgcctttcttctacataaacttgagttaggattatatctgcgcctgcgtcctggttggc
actctctcacggcaaacggcgatatgccttacaagtgccacgcctcaacggggtttgtgc
gaacttccggc-----------ctatttgcccatcgccacatttcggagtcgctgaaaag
gcagtgcttcaccgttaagaagacccataaatctaattagcggagaatgtagtctgcaca
agtatctcatccccaatggtcataactccgaaagtttagcatat----------------
----------------------tctctttcctccaaccggacaatgcaatggtatatgag
gaacaacgaatctga---------------------gggccaactactggaggtggatga
atcggg----------taaaaggttgcctgttaagtgtctcgtgccggaagcactcctcc
agcagaaagcggggtgtgataaaagtacatgaatacgtctatcaggcctaatggactttc
attttaacgccgttgtcgtcgtaaccttcaacccgtcggcgatgagtcaggggcgcttta
ctgtcgagagatgaatcgatgacccctttcgcaaataatttgcattccggggtgggc---
--------------gccacatattagcatctgatg-------------------------
----------------------
>SEQ4
gggcaggaatatttcggaacgcaaatactt------------------------------
---------------------------------------------------------gag
gaatccggacgttggtgttaacattacatatca--------------cggatcaaacggg
aactgcgagat-----------gcacaaggataattggatgaggaccctggtccaccaaa
cgtacttaactgttattttctaccccaaaagagctactttgcggccggccgccactccca
acaatcgaa---------------tatagacaca-----------acaccccacattgat
ccgcctttcttctacataaactcgagttacgattatatctctgcctgc------------
---------cggcaagcagcgatatgccttagaactgccacgcctcaacggggtttgtgc
ggacg-----------------ctatttgcccatcgccacatttcggagtcgctgaaaag
gcagtgcttaaccgttaagaagacccataaatctaattagcggagaatgtagtctgcaca
aggatcatacccccaatggtcatagctccggaagttttgcatatatatggggactc----
--------------------------------------------ttcaacggtatatgac
gcataacgtatttgc---------------------gggctaactacaggaactcgatca
ttacgg----------------gttgcctgttaagtgtctcgtgccggaagcactcctcc
agcagaaagcggggtgtgataaaagtacatggatacgtctatcaggtctaatggactttc
attttaacaccgttgtcgat---------------------atgagtcaggggcccttta
ctgtcgagagatgaatcgataacccctttcgcaaataatatgcatgccgag---------
--------------gccacgtattagcatctgacg-------------------------
----------------------
>SEQ5
gaccaggaaaatcgcgatacgcagatacctccgtgatgcactacttcta-----------
----------gactcaccgaccggcgtgatctagaggagagcgccat--cgcgggcagag
gaattaggacgttggtgttaacatgccctgtcggtgcttatagctcacgggtcaaacgtg
cactgcgagatgtgacaggctagcacaaggataattggatgaggaccctggtccaccaaa
cgtacttaactgttattttctaccccaaaagagctactttgcggccggccgccactccca
acaatcgaa----------------------------------caacaccccacattgat
cctcatgtcttctaaataaacttgagtt---------------------------tgggc
actctatcacggcaaacggcggtatgccttacaagtgccacgcctcaacggggtttgtga
gaact-----------------ctatttgcccatcgccacatttcgcagtcgctgacaag
gcagtgcttcaccgttaagaagacccataaatctaatcagcggagaatggagtctgcaca
aggatcatccccccaatgggcatagctccggatgttttgcatatataaggggtctc----
--------------------------------------------ttcaacggtatatgac
gcataaggtatttg----------------------ggcttaactac-------------
----------------------gttgcctgttaagtctctcgtgccggaagcactcctcc
agcagaaagcggggtgtgataaaagtacatggatacgtctatcaggtctaatggactttc
atgttagcaccgttgatatcgttaactttaacccgtcgccgataagtctggggagcatat
ctatcgagagccaaatagtagactcctttcgcaattaatacggattc-------------
----gtacttaccagccacatataagcatcggattgtaattccacgctgtctcttacttc
ggaagtaggaaccccgtaagcg
>SEQ6
gaccatgacaatcgggatacgcagatacctccgtgatgcactacttcta-----------
----------gactcaccgaccggcgttatctagaggagagcgccat--cgcggggagag
gaattaggacgttggtgtaaacatgccctgtcggtgctgata------------------
------gagatgtgacaggctagcacaaggataattggatgaggaccctgttccaccaga
cgtacttaactgttattttctaccccaaaagagctactttgcggccggccgccactccca
acaatcgaa---------------tatagtcaca-----------acaccatacattgat
acgcctatcttctacataaatttgggttaggattatatctccggctccatcctggttggc
actctctcacgccatacaa-------------------------------------gtgc
gaacttccggc-----------ctatttgcccatcgccacatttcgcagtcgctgacaag
gcagtgcttcaccgttaagaagacccataaatataatcagcggagaatggagtctgcaca
agtaccttatccctaatagtcacaacgtcggaagtttagcatatatattggaccccggag
ag---------------------ctcattaccccggcgggacaactcaacaatatttgac
gtacaacgtatctgccttccccaaaactacggggtagggctaactactggtggtagatga
atagggtattacctcctaaaaggttgcctgttaagtgtctcgtgccggaagcactcctcc
agcagaaagcggggtgtgataaaagtacatgaatacgtctatcaggtctaatggactttc
atgttaacgccgtagacctcgtaaccttcaacccgtgggggatgagtcgggggcgtttta
ccgtcgagagataaatcgatgacccctttcgcaaataagtttaattccggggtgggc---
--------------cccaaagaatagcatctgat--------------------------
----------------------
>SEQ7
gaccaagacaatcgggatacgtagatacctccgtgatggactacttcta-----------
--------------------------ttatctagtggagcgcgccat--cggggagtgag
gatttaggacgttggtgtaaacatgccctgtccgtgctgcta------------------
------gagatgtgacaggctagcacaaggataattggatgaggaccctggtccaccaaa
cgtacttaactgttattttctaccccaaaagagctactttgcggccggccgccactccca
acaagcgaagggctgtgcatggtctctagtcagattctgaacgtcacaccccacatcggt
ccccttttcttctacatagacttgagttaggtttacatgtgcggctgcgtctt-------
----------------------gatacgctacacgtgccacgtcgcaaagaggtatgtgc
gaacttccggcttaagcaagagctatttgcccatcgccacatttcggagtcgctgaaaag
gcagtgcttcaccgttaagaagacccataaatctaataagcggagaatggagtctggaca
agtgtcttttccccgatgggcatatcgcgggaaatttagcatttataagggaccgcctgg
aggttgtttttgtagttctaactctcat------------------------tataggac
gaacaacctatgtgccttacctaaaagtacggggttgggctaactactctttttagatca
atatgggattacctccaaattggttgcctgttaagtgtctagtgccggaagcactcctcc
agcagaaagcggggtgtgataaaagtacatgaatacatctatcagttctaatggactttc
attttaac---------------------------------atggggcaggcgcccgtta
ctgtcgagagatgaatcgataacccctttcgcaaaaaatatgcacgccgag---------
--------------tccacgttttagcatctgacg-------------------------
----------------------
>SEQ8
gaccaggaaaatcgcaatacgcaga-----------------------------------
----------------------tctagactcttgaggccagcgccat--ctcgggcacag
gaactaggatgttggtgttaacatgccctgtaggtgcttaga------------------
------tctcacggacacgctagcacaaggataattggatgaggaccctggtccaccaga
cgtacttaactgttattttctaccccaaaagagctactttgcggccggccgccactccca
acaatagtg---------------------------------gtcgccactaacattcgt
ccccctttcttctacacagacttgagttaggtttatatattcggctgcgtcccggagagc
agtctttgaccgcacacggcgaggaaccctacacgtgctacgtcacagaggggtttgtgc
ggccttccgacttaagcaagccctatttgcccctcgccacatttcggagtcgctgaaaag
gcagtgcttaaccgttaagaagacccataaatctaattagcggagaatgtagtctgcata
aggatcaaacccccaatggtcatagatccggaagttttgcatacatatggggactt----
--------------------------------------------ttcaacggtatatgac
gcataacgtatttgcatc------------------------------------------
----------------------gttgcctgttaagtgtctcgtgccgaaagcactcctcc
agcagaaagcggggtgtgataaaagtacatgaatacgtctatcaggtctaatggactttc
attttaac-------------------------------------------cgcccgtta
ctatcgagagatgagtcgataacccctttcgcaaaaaatttgcacgcctag---------
--------------tccacgttttagcatctgacg-------------------------
----------------------
>SEQ9
gatttagac---------------------------------------------------
-----------------------------tcttgagtccagctccat--atcgggcatag
gaactaggatgttggtgctaacatgccctgtaggttccgaaa------------------
--------------gcacacgggcacaaggataattggatgaggaccctggtccaccaga
cgtacttaactgttattttctaccccaaaagagctactttgcggccggccgccactccca
aaaatcgaa------------------------------------acaccccacattgat
ctgcctttcttccgaataagcttaagttaggattatatctgcgcctgcgtcctggctggc
actctctaacggcaaccggcgagatgccttacaagcaccacgcctcaacggggtttgtgc
gaacttacggc-----------ctatttgcccatcgccacatttcggagtcgctgaaaag
gcagtgcttcaccgttaagaagacccataaatctaataagccgagaatggagtctggaca
agcatcttatccataatggtcataacgccggaagtttagcatatatatggggccgcggtg
aggttgtgtttgtagttctaact-------------------------------------
----------tctgtcttccccaaaagtacggtgtagggctaactactggaagtagatga
atagggta--------------gttgcctgttaagtgtctagtgccggaagcactcctcc
agcagaaagcggggtgtgattaaagtacatgaatacatctatgagttctaatggactttc
atgttagcagccttggtgtcgttaacttcaacccggcgc---------------------
----cgtgggccgaagcgaagacccctttcgcaattaatacgcattccaggg--------
------acttacctgccacatattagcatctgattgtaatccctcgctgtatgttacttc
ggaagtaggaaccccgtaagcg
>SEQ10
gaccaagacaatctggaggcgtagatacctgcgtgatggactacttcta-----------
--------------------------ttatctagtggagcgcgccat--cggggagtgag
gattcaggacgttggtgtagacgtgccctgtccgtgctgcta------------------
---------------------ggcacaaggataataggatgaggaccctggtctaccaaa
cgtacttaactgttattttctaccccaaaagagctactttgcggccggccgccactccca
acgagatcc---------------------------------------------------
-------------------------------------------------tcatgttgggc
actcgatcacggcaaacggcgggatgcctgacaagtggcacgcctcaacgggctttgtga
gaact-----------------ctatttgcccatcgccacatttcgcagtcgctgacaag
gcagtgcttcaccgttaagaagacccataaatctaatcagcggagaatggagtctgcaca
agtaccttatccctaatagtcacaacgtcggaagtttagcatatat--------------
-----------------------ctcattaacccggctggacaactcaagaatatttgac
gtacaacataactgccgtccccaaaactacgaggtagggctaactcctggtggtag----
----------acctcataaaagattgcctgttaagtgtctcgtgccggaagcactcctcg
agcagaaagcggggtgtggtaaaagtacatggatacgtctatcaggtctaatggactttc
atgttagcaccgttggtgtcgttaatttcaacccgtcgccgataagtcaggggcgcttt-
------------------aagagtcctttcgcactgaatatgcattccggagtggcctaa
aacagtacttacctgccacaattccccgc-------------------------------
-----tggtaaccccgtaagca
>SEQ11
gaccaggaaaagcgcaatacgtaga-----------------------------------
----------------------tctagactcttgaggcgagcgccat--ctcgggcagag
taactagtatgttggtgttaacatgccctgtaggtgcctcga------------------
------tcacacggacacgctggcacaaggataattggatgaggaccctggtccaccaaa
cgtacttaactgttattttctaccccaaaagagctactttgcggccggccgccactccca
acagtcgaa--------------------------------------accccacattgat
ccacacgtcttctgaataaatttgagtt----------------------------ggtc
actctattacgggaaacggcggtatgccttagaagtgccacgcctcaacggggtttgtga
caact-----------------ctattagcccatcgccacatttcggagtcgctgaaaag
gcagtgcttgaccgttaagaagacccataaatctaattagcggagaatgtagtctgcaca
agtaccttatccctaatagtcattggacc-------------------------------
---------------ccggacagctcattaccccggccggacaact--------------
---caacatatctgccttccccaaacctacgggatagggctgactaccggtggtagagga
atagggtattacctcctaaaaggttgcctgttaagtgtctcgtgccgaaagcactcctcc
agcagaaagcggggtgtgataaaagtacatgaatacgtctatcaggtctaatggactttc
atgttggcaccgttggtgtcgtcaatttcaacccgtcgccgttaagtcaggggcgctt--
------------------------------------gaagagtattccgtagtggcctaa
tacagtccttacctgccacaattccccgctgca---------------------------
----------------------
>SEQ12
gaccaggaaaatcgcaatacgatga-----------------------------------
------------------------tcttctcttgacgccag------------------g
gatctaggatgttggtgttaacacgccctgtagatgcttgga------------------
------gctcacggtcacgctagcacaaggataattggatgaggaccctggtccaccaga
cgtacttaactgttattttctaccccaaaagagctactttgcggcaggccgccactccca
acaatagtg---------------------------------gtcgcctctaacattcgt
ccccctttcttctacacagactttagttacgtttatatattcggctgcgtgccggagagc
agtctttgaccgcacacggcgaggaaccctacacgtgctacgtcagagaggggtttttgc
gtgcttccgactcaagcaacccctatttgcccatcgccacatttcgcagtcgctgacaag
gcagtgcttcaccgttaagaagacccataaatataatcagcggagaatggagtctgcaca
aggatcttatccctaaaggtcatgacgccgga------------------cgccgccgtg
aggttgtgtttgcagttctaagtctcattaccccggcaggtacgttcaacggtatttgac
gaacaacgtatctgccttccccaaacgtacggggtggggctaactactggatgtagatca
atagggtat-------------gttgcctgttaagtgtctcgtgccggaagcactcctcc
agcagaaagcggggtgtgataaaagtacatgaatacgtctatcaggtctaatggactttc
att--------------------------------------atgggtcacgcgcccgtta
ctgtcgacagttgattcgattacccct---------------------------------
----------------cacgttgtagcatctaacg-------------------------
----------------------
>SEQ13
gaccaggtatatttcggaacgcaga-----------------------------------
-----------------------gcgtgtctcagcgaccggcgtcatgcagcgtccagag
gaatcaggac---------------ccctgtcggtccgtacacaccacgcatcaaac---
----------------------gcacaaggataattggatgaggaccctggtccaccaaa
cgtacttaactgttattttctaccccaaaagagctactttgcggccggccgccactccca
acaatcgaa---------------tctagtcacattgtgaacgtcacaccccacattgat
ccccctttcttctacataaacttgagttagggctatat----------------------
-ctctctcaccgcaaac--------------caagggccacgtcaccaagggctttgtgc
ggacctccggc-----------ctatttgcccatcgccacatttcgcagtcgctgacaag
gcagtgcttcaccgttaagaagacccataaatctaatcagcggagaatggagtctgcaca
agtgtcttttccc------------------aagtttagcatttttaaggggccgccgtg
agtatgtgtttgtagttcgaactctcat--------------------------tatgac
gaacaacctatgtg-------------tacggggttgggctaactactg-----------
------------tttttctaatgttgcctgttaagtgtctcgtgccggaagcactcctcc
agcagaaagcggggtgtgataaaagtacatggatacgtctatcaggtctaatggactttc
attttaac---------------------------------ttggggcaggcgcccgtta
ctgtcgggagatgaatcggtaacccctttcgcaaaaaataggcacgccgag---------
--------------tccaggttctagcatctgacg-------------------------
----------------------
>SEQ14
gaccaggaatatttcgggccgcagatacttccgcgaacccctacttttgagtgtgtcggg
ttcgcctcgatactcagcgacacgcataatgtaaagtggagcgccgt--cgggccccgac
gaatcaggacgttggtgttaacatgccatgtcgg-------------------------g
aactgcgcgat-----------gcacaaggataattggatgaggaccctggtccaccaga
cgtacttaactgttattttctaccccaaaagagctactttgcggccggccgccactccca
acaatcgaa------------------------------------acacaccacattgat
actcatgtcttctaaataaacttgagtt---------------------------tgggc
actctagtacggcaaacggcggtatcccttacaggtgccacgcctcaacgg---------
----------------------ctatttgcccatcgccacatttcggagtcgctgaaaag
gcagtgcttcaccgttaagaagacccataaatctaattagcggagaatgtagtctgcaca
agtatcttaaccctaatggtcttaacgccggaagtttagcatatatatgggaccgccgtg
aggtcgtgtttgtagttctatctgtcatcagcccggcaggacaattccacgatatatgac
gatcaacgtatctgccttgcccaaaagtaccgggttgggctaactactggttgtagatgc
atagggtattacttcctaagaggttgcctgtttagtgtctcgtgccggaagcactccgcc
agcagaaagcggggtgtgataaaagtacatgaatacggctatcaggcctaatggactttc
atgttagcaccgttgatatcgctaacttaaacccgtcgccgataagtctggggagcgtat
ctatcgggagacaaatactagactcctttcgcaattaatacggctta-------------
----gtacttaccagccacatat--------------------acgctgtctcttacttc
ggaagtagcaaccccggtagcg
>SEQ15
gaccaggaaaaccgcgatacgcaga-----------------------------------
----------------------tcttgaatcttgaggccagcgccat--ctcgggcacag
gaactaggatgttggtgttaagatgccctgtaggtgcttaga------------------
--------cctctcggacgctagcacaaggataattggatgaggaccctggtccaccaga
cgtacttaactgttattttctaccccaaaagagctactttgcggccggccgccactccca
acaatagcaggtctgtgaatggtctctagtcacattccgaacgtcacaccccacattga-
-----------------agacttgagttaggtttatatgtgcggctgagtcctggtcggc
actctcttaccgcaaacggcgagataccctacacg-----------------------gc
ggacttccggcttaagcaagacctatttgcccatcgccacatttcgcagtcgctgacaag
gcagtgcttcaccgttaagaagacccataaatataatcagcggagaatggagtctgcaca
agtatcttaaccctattggtcttaacgccggaagattaggatatatatgggacagccgtg
aggtcgtgtttgtagttccaaaccc-----------------------acgatatagtac
gatcatcgta-----------------taccgagttggtctaacta--------------
---------taattcctaagaggttgcctgttaagtgtctagtgccggaagcactcctcc
agcagaaagcggggtgtgacaaaagtacatgaatacatctatcagttctaatggactttc
atgtaa------------------------------------------cggggcactttt
gtatcgaaagcccaatcgaagactcctttcttaatcaatacgcat---------------
------actcacctgccacatat---------------aatctacgctgggtgttacttc
ggaagtaggaacccggtaagcg
>SEQ16
ggtatagac---------------------------------------------------
-----------------------------tcgggagtcccgttccat--atcgggcacag
gtactaggatgttggtgctaacatgccctgt-----------------------------
----------------------gcacaaggataattggatgaggaccctggtccaccaaa
cgtacttaactgttattttctaccccaaaagagctactttgcggccggccgccactccca
acaaaccaa---------------tatagacaca-----------acaccccacactgat
ccgcctttcttctacataaactcgagttacgtttatatctgtgactgc------------
-----------------------------------cggcaaccctcgacggggtttgtgc
ggacg-----------------ctatttgcccatcgccacatttcgcagtcgctgacaag
gcagtgcttcaccgttaagaagacccataaatataatcagcggagaatggagtctgcaca
agcatcgtatccc----------------ggaaggttagcatataaaggggatcgccgtt
aggtagtgtttgtagttctacctctcattaccccggcaagacacttcgacgatatttgac
gaacaagagatctggcttccccaaaagtacggggttgggctaactactcaacgtagatga
atagggtatcacctcctaaaaagttgcctgttaagtctctcgtgcccgaagcactcctcc
agcagaaagcggggtgtgataaaagtacatggatacgtctatcaggtctaatggactttc
atgctagcaccgttgatatcgttaactttaacctctcacggataagtctggggagcatat
ctatcgagagcaaaatagaagactccattcgcaattaatacggattc-------------
----gtgcgtaccagccacatataagcatcggattttaattccacgctgtctcttagttt
ggtggtaggaaccccgtaagcg
>SEQ17
gaccaagacaatcggtaaacgcagatacctccgtcatgcactacttcta-----------
-----------acgaaccgacgggcgctattaagaggagggcgccat--cgcgggtagag
gaattaggacgttggagtaaacatgccctgtcggccctgata------------------
------gagatgggacaggctagcacaaggataataggatgaggaccgtggtctaccaaa
cgtacttatctgttattttctaccccaaaagagctactttgcggcgggccgccactccca
acaatcgaa---------------tcttgtcacattctgaacgtaacacccgacattgag
cctcctttcttgtgcataaacttgagttaggtttatatttgcgcctgcgacctgcgtcgc
cctctcactccgcaaacggcgagctaccttacaacggccacgtcagacagggatgtgtgc
ggacttccggc-----------ctatttgcccatcgccacatttcgcagtcgctgacaag
gcagtgcttcaccgttaagaagacccataaatataatcagcggagaatggagtctgcaca
ag-----------------tcatagctccggaagttttgcatatatatggggactcttc-
------------------------------------------------------------
-----acgtatttgc---------------------ggcctatctacaggaactcg----
----------------------gttgcctgttaaatctctcgtgccggaagcactcctcc
agcagaaagcggggtgtgataaaagtacatggatacgtctatcaggtctaatgaactttc
attttaacgccgttggtgtcgttagcttcaacccgtcggctttgggtcaggggcgcacta
ctgtcgaaagatgaatcgctgg--------------------------------------
------gggtgggcgccacatattcgcatctgat--------------------------
----------------------
>SEQ18
gaccaagacaaccggga-------------------tggtctacttcta-----------
--------------------------ttatctagtggagcgcgccgc--cggggagtgag
gatttaggacgttggtgtaaacatgccctgtccgtgctggta------------------
------gagatgtgacagggtagcacaaggataattggatgaggaccctgttccaccaga
cgtacttaactgttattttctaccccaaaagagctactttgcggccggccgccactcgca
acaatagtg---------------------------------------------------
-------------------------cgtaggtttatctattcagctgcgtcccggagagc
agtcttgaaccgc--------------------------aggtcacagagggggttgtgc
ggccttcctacggaagtaagccctatttgcccatcgccacatttcgcagtcgctgccaag
gcagtgcttcaccgttaagaagacccataaatataatcagcggagaatgcagtctgcaca
agcatcgtatcattagt-----------------------atatcaaggggatcgccgtt
atgtagtgtttgtagttctacctctcattaccccggcaagacacttcgacgatatttgaa
gaagaagtgatctggcttccccaaaagcccgggcttgggctaactactcaacgtagatga
atagggtatcacctcctaaaaagttgcctgttaagtctctcgtgcccgaagcactcctcc
agcagaaagcggggtgtgataaaagtacatggatacgtctattaggtctaatggactttc
attttaacaccg--------------------------------agtcaggggcccttta
ctgtcgagagatgaatcgataacccctttcacaaataatatgca----------------
--------------gcctcgtattagcatctgac--------------------------
----------------------
>SEQ19
gaccaagacaatcggtaaacgccta------------------cctcta-----------
-----------acgaaccgacaggtgctattaagaggagggcgccat--cgcgggtagag
gaattaggacgttcg---------gccctgtta---------------------------
------gagatgggacaggctagcacaaggataattggatgaggaccctggtccaccaga
cgtacttaactgttattttctaccccaaaagagctactttgcggccggccgccactccca
acacaagtg---------------------------------------------------
-------------------------------cgtatcaattcagctgcgtcccggagagc
agtcttgaaccgca-------------------------------------------tgc
ggccttcctacggaaataagccctatttgcccatcgccacatttcggagtcgctgaaaag
gcagtgcttcaccgttaagaagacccataaatctaattcgcggagaatgtcgtctgcaca
aggatcttatccctaaaggtcatgacgcaggacg------------------ccgccctg
aggttgtgttggcagttcta----------------caggtacgttcaacggtatttgac
gaacaacgtatctgccttccccaaacgtacggggtggggctaactactcgatgtagataa
atagggtat-------------gttgcctgttaaatctctcgtgccggaagcactcctcc
agcagaaagcggggtgtgataaaagtacatggatacgtctatcgggtctaatgaactttc
atttgaacaccg--------------------------------agtcaggggcccttta
ctgtcgagaggtgaatcaataacccctatcacaaataatatgcac---------------
------------------------------------------------------------
----------------------
