>SEQ0
ataagttgccgggagatgtagcataatcgaattgcgcatgccccttaatcctaattgaga
gttcggtcaagggctaagtacatgactactcacgcggctagctacttcgttccataatta
aatgcgttttgaggggtccggcttaaccgggaggtatccggtggtgtacagtgtgcgtct
tgtgttgaacttcagcacttcccctaatgcggcacgcatgccttccagccctggggttca
aatgacataattttactttgcttttctcgcccgtgtaacgtcttcagacgtagtcgagtt
cagaaagcaggagcacgaatagcgactactttcgcaaagtacgaacgcaaatggaactag
gcaggctaactctaagcgcagagggcagagtgtgagaggacccccccgatacgcgttagt
gactgtcattattatcgtcggcgagttcctctatggtgctttcttcctgaacaagcagta
tggtaatgagtcccatgttaatgatccagcgtatacgtttggcagcgtttgtgtggtggt
ccaggctgatctgcaagggaagcaactgtcctagccaagaagggacccctcttttcttct
atggcctcccgaacaacacttccgttaggcgagacacgccccaagtccgtagggaatggg
tctggatccagcggaccgacgatacgcttggtactccttcctttttaaaaggaccctcgg
cgagaatggtacccgtaaccggtacggcgctattgttaaagccatacctggtacgttcca
aacacgtgagtttaggtctggaatttcctatcgggaaggaggctcccttagatttcacga
acaattgcaggcttttactatcggtgacacaggtgtcacgtcggtaacgtctgtttcgct
acctcgttacctgagccgccgtggaagagacaagagtatcactcgaggctaattcgatga
atttcccatcgacactcgatattacctcttcgccccgaggcgatcttccaagccgttgcg
tggaagatcactcaacaatcattatgtcttcattctcgcactggccagatggggcacgat
gagttggttggccagcagca
>SEQ1
ataagtagccgggagatgtaggataatcgaattgttcatgccccttaatcctaa------
---------------------------------gttgctagctacttcgatccataatta
aatgcgttttgtagggtacggcttaaccgggaagtatccggtggtgtatagtgggcgttt
tgttttgatctccagtcattcccctaatgcggcacgcatgccttccagccctggggttca
aatgacataattttactttgcttttctcgcccatgtaacgtcttcagacgtagtcgagtt
cacaaagcaggagcacgaatagctactactttcgcaagatccggacgcaaattgaactag
gcaggctaactctaagcgcagagggcagggtgtgagtggacccacccgatacgcgttagt
gactgtcat-------------------ctccatggtgcgtactccctgaacaagcagta
tggtaatcagtcccatgttaatgatccagcgtatacgtttggcagcgtttgtgtggtggt
ccaggctgatctgcaagggaagcaactgtcctagccaagaagggacccctcttttcttct
acggc----------------ccgtaaggcgagacacgccccaagtccgtaggcaatggg
tttggatccagtagaccgacg-----------------tcctttttacaaggaccctcgg
caagaatggtacccctaaccggtatggcgctcttgttcacgccatatctggtaccgtcca
aacacgtgcgcttagctctggaatctcctatcgggaaggaggctcccttagatttcacga
acaattgcaggcttttactatcggtgacacaggtgtcacgtcggtaacgtctgtttcgct
acctcgtgacatgagccgccgtggaagagaccagagtatgactcgaggctaattagatga
atttcccatctatactcgatatta---------------------ttcgaagccgttgcg
tggaagatcactcaacaatcattatgtcttcattctagcactgtgcagatggggcacgat
gagttggttggccggcagca
>SEQ2
atcatttgcagggtgataaagcataatcgaattgcgcatggcccttaatcctaatggaga
gttcggtcaagggctaagtacattactactcacgcggctagctacttcgttccataatta
attgcgtttgtaggggtctggcctaaccgcgaggtatccggtggcgaaccgtgtaagtct
tgtgttgaacttcagcacttcccctaatgcggcacgcatgccttccagccctggggttca
aatgacataattttactttgcttttctcgcccgtgtaacgtcttcagacgtagtcgagtt
cacaaagcaggagcacgaatagctactactttcgcaagatccggacgcaaattgaactag
gcaagccagctctaagcgcatagggcagggcgtgagtggacccacccgatacgcgtttgc
gactgtcat-------------------ctccatggtgcgtactccctgaacaaacagta
tggtaatcagtcccatgttaatgatccagcgtatacgttgggcagcgtttgtgtggtggt
ccaggctgatctgcaagggaagcaactgtcctagccaagaagggacccctcttttcttct
atggcctcccgaacgacacttcagttagtcgagacacgccccaagtcgctagggaatggg
tctggatccagcggccccacgatg---------------------tagaaggaccctcgg
ctagaatcgtacccgtaaccggtacggcgctatttttaaagccttacctggtacgttcca
aacacgtga-----------gaatttcctatcgagaaggaggctcccttagatttcacga
acaattgcaggcttttactatcggtgacacaggtgtcacgtcggtaacgtctgtttcgct
ccctcgtgatatgagccgccgtcgaagagaccagagtatgactcgaggcgaatgatatga
atttcccatctatactcgatatta---------------------ttcgaagccgttgcg
tgcaagatccctcaata--------------------gcaccgtgcagatggggcacgat
gggttggttggcctgcagca
>SEQ3
ttcttttgcagggtgataaagca-----------------gcagttaatccaaatggaga
gtgcggtcaagggctaagtacattactac----------------------tcataatta
atcgggtttgaaggggtatggcctatccgcgaggtatccggtggtgagccgtgtaagtct
tgcgttgaactatagcacttcccctgatgcggcacgcatgccttccagccctggggttca
aatgacataattttaatatgcttttctcgcccgtgtaacgtcttcagacgtattcgagtt
cagaaagcaggagcacgaatagccactactttcgcaaagtacgaacgcatatggaactag
gcagcttagctctaagcgaagaggtcagggtctgattggacccccccgatacccg-----
------------tatcgtcggcgattccctctatggtgctttcttcctgcacaactagta
tggtaatgagtcgcatgttaatgatccagcgtatacgtttggcagcgtttgtgtggtggt
ccaggctgatctgcaagggaagcaactgtcctagccaagaagggacccctcttttcttct
acggc----------------ccgtaaggcgagacacgccccacctccgtaggcaatggg
tttggatccagtagaccgacg-----------------tcctttttacaaggaccttcgg
cgagatcggtacccttaaccggtatggcactcttgtccacgccatatctggtaccgtccg
aaaacgtgcgcatagctctggaatttcctatcgagaaggaggctcccttagatttcacaa
acaattgcaggcttttactatcggtgacacaggtgtcacgtcggtaacgtctgtttcgct
ccctcgtgacatgagccgcggtggaagagtccagagtatgactccaggataatttg----
-------------actcgatttta---------------------ttcgaagccgttggg
tggaagatcactcaacaaacattatgtcttcagtcaagcactgtgcagatggggcacgat
gagttggtgggccggc----
>SEQ4
ataatttgccgggagatgtag----------------------cttaatcctaattgaga
gttcggtcaagggctaagtacatgactactcacgcggctagctactccgttcaacaat--
----------------tacggcttaaccgggaggtatccggtggtggacagcgtgcgtct
tgtgttgaaattcagcacttcccctaatgcggcacgcatgccttccagccctggggttca
aatgacataattttactttgcttttctcgcccgtgtaacgtcttcagacgtagtcgagtt
cacaaagctggagcacgaatagctactactttcgcaagatccggacgcaacttgcactag
gcaagctaactttaagcgcagaaggcagggtgtgagtggagccaccgaatacgct-----
--------------------------------------------------ccatgcagca
tggtaatcag----------atgatccagcgtatacgtttggcagcgattgtgtggtggt
ccaggctgatctgcaagggaagcaactgtcctagccaagaagggacccctcttttcttct
atggcctcccgaaaaacactcccgttgggcgagacacgccccaagtccgtaggga-----
-----------cggaccgacgataagcttggtactcgttcct------------------
----------------------tagcacgctattgataaagccatacctggtacgttcca
tacacgtgagt---------gaatttcctatcgagaaggaggctcccttagatttcacaa
acaattgcaggcttttactatcggtgacacaggtgtcacgtcggtaacgtctgtttcgct
cccgcaggata-------------------------------------------------
---------------------------------------------atttgaaccgttggg
tggaagatcactgaacaaagattatgtcttcagtcaaggactgag---------------
--gttggtgggccggc----
>SEQ5
aaaatttgccgggagatgtag----------------------cttaatccaaattgaga
gttcggtcaagggctaagtagatgtcagc-------------------------------
-------------aattacggcttaaccggga------------------gcttgtgtct
tgtgttgaaattcagcacttcccctgatgcggcacgcatgcctcccagccctggggttca
aatgatataattttaatatgcttttctcgcccgtgtaacgtcttcagacgtattcgagtt
cacaaagccggagcacgaata--------------aagatccggacgcaaattgcactag
gccagccagctctacgcgaatagggtagggcgtgagtggacccccacgatacgcgttagg
gactgtcat-------------------ctccagggtgcgtactccctgaacaaacagta
tggtaatcaatcccatgttaatgatccaacgtatacgtttggcagcgattgtgtgggggt
ccaggctgatctgcaagggaagcaactgtcctagccaagaagggacccctcttttcttct
atgaccgcccgatcaacacttccgttcagcgcgacacgccccaagtccgtaggtaatggg
tctggatccagcgcccggtccattcgcttggtactcattcctttttaagaggtccctcgg
cgagaatggtacacgtaaccggtacggcgctatcgttacagccatacctggttcgttcta
aacatgtgagtttacgtctggaatttcctatcgagaaggaggctcccttagatttcacga
acaattgcaggcttttactatcggtgacacaggtgtcacgtcggtaacgtctgtttcgct
accttgttacctgagccgccgtggaagagacaagattatcactcgaggctaattcgatgc
atttcccatagacactcgatataacctcttcgccccgaggcgatcttccaagccgttgcg
tggaagatcactcaacactcattaagtcttgattctggcactggccagcttgggaaggat
gagttggttgtcgagcagca
>SEQ6
agcatttgcagggtgatagagcatgatcgtattgcgcatggcccttaatcctaatggaga
gttcggtcaattgctaagcacattactac-----------------tcgttccttaatta
tttgccttcgtaagtgtctggactaaccgcgaggtatccggtggcgaaccgtgtaagtct
tgtgttgaacttcagcacttcccctaatgcggcacgcatgccttccagccctggggttca
aatgacataattttactttgcttttctcgcccgtgtaacgtcttcagacgtagtcgagtt
cataaagcaggagcaggaatagcgactactttcatagg----------------------
-------------------------caagtccggagtggacccacccgatatgcgcttgc
gccagtcat------------------------------------cttgaacaaacagta
tggtaatcagtcccattctaatgatccagcgtacacgtttggcagcgattgtgtggtggt
ccaggctgatctgcaagggaagcaactgtcctagccaagaagggacccctcttttcttct
atggcctc-----------------------agacatgccccatgtccataggga-----
-----------cggaccgccgatatgcctggtacttgttcct------------------
----------------------tagcacgctattgataaaggcatatctggtaagtccca
tacacgtgagt---------gaatctcctatcgggaaggaggctcccttagatttcacga
acaattgcaggcttttactatcggtgacacaggtgtcacgtcggtaacgtctgtttcgct
accgc--------------cgtggaagagataagagtaacacacgaggctcattggatgt
attacccatcgacactcgatattacctattcggccc--------------------tgcg
tggaagatcagtcaacaatcactctgtcttctttaaggcacaggccagatggggcacgat
gagttggttggccagcagca
>SEQ7
ataacttgccgggagatgtagcatagtcgaattgcatgtgtcccttaatcctatttgaga
gttcggtcaagggctaggtact------------------------ttgttccataatta
aatgcgttttgaggggtccggcttgaccggtaggtatccggtgctgtacagtatgcctct
tcagttgaacg-------tccccctaatgcggca-------cttccagccctggggttca
aatgacataattttactttgcttttctcgcccgtgtaacgtcttcagacgtagtcgagtt
cacaaagcagaaacacgaatagttactactttcgcaagatctgggcgcaaattgaactag
gcaggctcactctatgcgc-------------------------cccggtacgccttaat
gactggc--------------------------tggtacgtactccctgaacaagcagt-
--------------------atgatccagcgtatacgtttggcagcgtttgtgtggtggt
ccaggctgatctgcaagggaagcaactgtcctagccaagaagggacccctcttttcttct
agggcctc-----------------------agacatgccccatgtctatagggag----
------------ggaccgccgatatgccaggtaattgttcct------------------
----------------------tagcacgaggttgataaaggcatatctggtaagtccca
ttcacgtgagt---------gaatttcctatcgagaaggaggctcccttagatttcacaa
acaattgcaggcttttactatcggtgacacaggtgtcacgtcggtaacgtctgtttcgct
tccgcaggacaataacggttgggtggaagtc-----------------------------
------------------------------------------------------------
------------------------------------------------------------
--atcagtggtccggc----
>SEQ8
agcattaacagggtgatagagcatgatagtattgtgtatggcccttaatcctaattgaga
gttcggtcaattgc---------------------------------cgtcccttaatta
tttgccttcgtaagtgtcttgacaaaccgcgaggtctccggtggcgcagcgtgtaagtct
tgtgttggacttcagcacttcccctaatgcggcacgcatgccttccagccctggggttca
aatgacataattttactttgcttttctcgcccgtgtaacgtcttcagacgtagtcgagtt
cacaaagctggagcacgaatagctactactttcgcaagatccggacgcaacttccacttg
gcaagctaactttaagcgcagaaggctgggagtgagtggagccaccgaatacgct-----
--------------------------------------------------acatgcacca
tggtaatcat----------atgatccagcgtatacgtttggcagcgtttgtgtggtggt
ccaggctgatctgcaagggaagcaactgtcctagccaagaagggacccctcttttcttct
atgacctcccgaacgacacttcagttagtcgagacacaccccaagtcgctaggaaatggg
tctggatccagcggccccaggat----------------------tagtaggaccctcgg
ctagaatcgtacccctaaccggtacggcgctatttttaaaaccttacctgg---------
------------------cggaatttcctatcgagaaggaggctcccttagatttcacaa
acaattgcaggcttttactatcggtgacacaggtgtcacgtcgttaacgtctgtttcgct
acctcgttacctgagccgccgtggaagagacaagagtatcactcgaggctaattcgatga
atttcccatcgacactcgatattacctcttcgccccgaggcgatcttccaacct------
---------------caatcattatgtcttcattgtcacactggccagatggcgcacgat
tagttggttggcca------
>SEQ9
ataagttgccgggagatgtaccataatcgaattccgcatgccccttaagcctaattgaga
gcttg-------------------------------------------------------
-----------aggggtctggcttaaccgggaggaatccggtggtgtacagtgtgcgtct
tatgttgatcttcagcacttcccctgatgcggcacgcatgccttccagccctggggttca
aatgacataattttaatatgcttttctcgcccgtgtaacatcttcagacgtattcgagtt
cagaaaggaggagcacgaatagcgtctactttcgtaaagtacgatcgcaaatggaactag
gctagctaactctaagcgcagagggcagagtgtgtagtgactgtcattattctgg-----
-----------------tcggccagctccttttgggtgctttcttcctgaacaagcagt-
-----------------ctgatgatccagcgtatacgtttggcagcgtttgtgtggtggt
ccaggctgatctgcaagggaagcaactgtcctagccaagaagggacccctcttttcttct
acggc----------------ccgtaaggcgagacacgc------------ggcaatggg
tttggatccagtagaccgacg-----------------tcccttttacaaggaccctcgc
caagaatggtacctct-----------------------cggcatatttggtacggtcca
aacacgtgctcttagctctggaatttcctatcgagaaggaggctcccttagatttcacga
acaattgcaggcttttactatcggtgacacaggtgtcacgtcggtaacgtctgtttcgct
cccgcagaata-------------------------------------------------
---------------------------------------------atttgaatcgttggg
tggaatatcactgaacaaagatgctgtcttcagtcaaggactgagcggc-----------
--------------------
>SEQ10
ttcttttg----------------------------------------------------
------------gctaagtacattactactc-----------------------------
----------------tatggcctatacgcta------------------------gtct
tgcgttgaactatagcacttcccctaatgcggcacgcatgccttccagccctggggttca
aatgacataattttactttgcttttctcgcccgtgtaacgtcttcagacgtagtcgagtt
c----------------------------tttcata------------------------
-----------------------ggcaagttcggagtggacccacccgacatgcgcttgc
gccagtcaa--------------------------------------tggacaaacagaa
tggtaaacagtcccattctaatgatccagcgtatacgtttggcagcgattgtgtggtggt
ccaggctgatctgcaagggaagcaactgtcctacccaagaagggacccctcttttcttct
atgaccgcccgatcaacccttccgttcagcgctacacgccccaagtccgtaggcaatggg
tctggatccagcgcgcggtccattcgctttgtactcattcctttttaagaggtccctcgg
cga------------------------------------cggcatacctggttcgtccta
aaagtgtgagtttacgtctggaatttcctatcgagaaggaggctcccttagatttcacga
acaattgcaggcttttactatcggtgacacaggtgtcacgtcggtaacgtccgtttcgct
acctcgttacctgagccgccgtggaagcgacaagagcatcactcgaggctaattcg----
----------------------tacctcttcgccccgaggcgaagttccaacct------
---------------cagtcat-----------------acgggccagagggcgcatgat
tagttggtagacca------
>SEQ11
agcatgttcagggtgatggagcatgatcgtattgcgcctgacccttaaacctaatggaga
gttcagtcaattgctaaccacattactac-----------------tcgttccttaatta
tttgtcttcgtaagtgtctggactaaccgcgagatatccggtggcgcaccgtataagtct
tgggttgaacttcagcacttcccctaatgcggcacgcatgccttccagccctggggttca
aatgacataattttacgttgcttttctcgcccatgtaacgtcttcagacgtagtcgagtt
cgcaaggctggagcacgaatagctactacttccgcaagatccggacgcaactcgcactag
gcaagctacctttaagggcagaaggcagtgtgtgggtagagtcagcgatgaccct-----
--------------------------------------------------ccatgcagca
tgt-----------------atgatccagcgtatacgttgggcagcgtttgtgtggtggt
ccaggctgatctgcaagcgaagcaactgtcctagccaagaagggacccctcttttcttct
atggcctccagaacaacacttccgttaagcgagacacgctcctagtccgtagggaatggg
tttggatccagcggaccgacgatacgcttggtactccttcctttttaaaaggaccctcgg
ctaga-------------------------------------------------ggtcca
accacgtgtgtttagggctgtaatttcctatcgagaaggaggctcccttagatttcacaa
acaattgcaggcttttactatcggtgacacaggtgtcacgtcggtaacgtctgtttcgct
acctcgttacctgatccgccgtggatg------------cactcgaggctaattcg----
----------------------tacctcttcgccccgaggcgactttccaacct------
---------------cattcat-----------------acgggccagagggcgcatgat
tagttggtagacca------
>SEQ12
ataatttgcagggagatgtag----------------------cttaagcctaattgaga
gttcggtcaagggctaagtacctgacaactcacgcggctagctactccggtcaacaat--
----------------tacggcttaaccgggaggtatccggtggtggacagcgtgcgtct
tgcgttgaaattcggcacttcccctgatgcggcacgcatgccttccagccctggggttca
aatgacataattttaatatgcttttctcgcccgtgtaacgtcttcagacgtattcgagtt
cacaaagcagaaacgcgaatactcgcttctctcgcaagatatgggcgcaaattgaactag
gcaggatcactctatgcgctgtgg-------------------------tacgccttaat
gactggc--------------------------tggcacgtaccccgtgaacaagcagt-
--------------------atgatccagcgcatacgtttggcagcgtttgtgtggtggt
ccaggctgatctgcaagggaagcaactgtcctagccaagaagggacccctcttttcttct
acggc----------------ccgtaaggcgagacacgccccaagtccggacggaatggg
tatggatccagtagaccga---------------------------------------ga
caagaatggtacccctaacctgtatggcgctcttattcacgccatatcaggtaccgtcca
aacacgtgcgcgtagctccgtaatttcctatcgagaaggaggctcccttagatttcacaa
acaattgcaggcttttaatatcggtgacacaggtgtcacgtgggtaacgtctgtttcgct
tccgcaggacactaacggttgggtggaagcc-----------------------------
------------------------------------------------------------
------------------------------------------------------------
--atcagtgcttcggt----
>SEQ13
ttcttttgcatggtg-------------------------------------------ca
gagcggtcaacggctaagtacattacgac----------------------tcataatta
atcgcgattgaaggggtgtggcctatccggaaggtatccggtggtgagccgtgtaactct
tgcgtttctctacagcacttcccctgatgcggcacgcatgcctcccagccctggggttca
aatgatataattttaatatgcttttctcgccggtgtaacgtcttcagacgtattcgagtt
cacaaagccggagcacgaata--------------aaggaccggacgtaaattgaactag
gccagccagctctccgcgattagggtagggcgtgagtggaccctcacgatacgcgttacg
gactgtcag-----------------------------------ctccaggctgcgatta
tggtaatcaatctcatgttaatgatccagcgtatacgtttggcagcgtttgtgtggtggt
ccaggctgatctgcaagggaagcaactgtcctagccaagaagggacccctcttttcttct
atgactgcccgatcaaccgttccgtgcagcgcgacacgccccacgtccgtaggcaatggg
tctggatcactcattcc------------------------------------------t
ttagaatggtacacgtaaccggtacggcgctttcgttccatccatacatggttcgttcta
aacatgtgagtttacgtctggaatttcctatcgagaaggaggctcccctagatttcacga
acaattccaggcttttactatcggtgacacaggtgtcacgtcggtaacgtctgtttcgct
acctcgttccctgagccgccttg---------------tcactcgaggctgattcg----
----------------------tagctcttcgcccctaggacaagttccaacct------
---------------cagtcat-----------------------------gcgcatgat
t-------------------
>SEQ14
agcatgttcatggtaagggagtctaatcgtattgcgcctgaaccttaaacctaatggaaa
tttcaatcatttgctacccactttactac-----------------tcgttccttaatca
tttgtcctcgtaagcgtctggactaaccgcgagatatccggtggcgcaccg---------
----------tctagcacttcccttaatgcggcacgcatgccttccagccctggggttcc
aatgacataattttactttgcttttctcgcccatgtaacgtcttcagacgtagtcgagtt
cacaaagcagaaacgcgaatactcgcttctctaacaagttacgggcagaaattgaactac
gcaggaacatcatatgcgcaatga------------------------------------
----------------------------ctggctggcacgtaccccgtgaaccagcagt-
--------------------atgatccagcgtatacgtttggcagcgtttgtgtggtggt
ccaggctgatctgcaagggaagcaactgtcctagccaagaagggacccctcttttcttct
atgaccgccctatta--------------------atgccccaattccgtaggcaatggg
tccggctccagcgctcggtccattcgctttgtactcattcctttttaaggggttcctcgg
caa------------------------------------cggcatacctacttcgaccta
taaatg-------------ggaagttcctatcgggaaggaggctcccttagttttcacga
acaattaaaggcttttactatcggtgacacaggtgtcacgtcggtaacgtctgtttcgct
acctcgggacatgagccgccctggaagaaaccacagtatgactcgaggctaattagatga
atttcctatctatactcgatatta---------------------ttcgaagccgttccg
tggaagatcactcaa------------------tcttgcactgcgcagatggagcacgat
gagctggttggccggc----
>SEQ15
gtaagtagccgggacatgtaggataatcgaattgttcatccgccttaatcctaat-----
------------------------------------gctaggtgcttcgatgcataatta
attgcgttttgtagggtacggcttaac-----------------------------gttt
tgttttgatctccagagtttcccctgatgcggcacgcatgccttccagccctggggttca
aatgacataattttaatatgcttttctcgcccgtgtaacgtcttcagacgtattcgagtt
cacaaacctggcgcactaatagctactactttcgcaagatccggacgcaacttccacttg
ggaagctaac--------------------------------------------------
---------------------------------------------------catgcacca
tggaaatgat----------atgatccagcgtatacgtttggcagcgtttgtgtggtggt
ccaggctgatctgcaagggaagcaactgtcctagccaagaagggacccctcttttcttct
atggcctccagaacaacacttccgttaagcgagactcgctcctagtccgtaggtaatggg
tttggatccagcgcaacgacgatacgcttcggacgccttcctttgtaaaaggaccctcgg
ctaggac-----------------------------------------------------
--caagcgtgtatatggctgtaatttcctatcgagaaggaggctcccttagatttcacaa
acaattgcaggcttttactatcggtgacacaggtgtcacgtcggtaacgtctgcttcgct
tcctcgtgacatgagccgcggtggaagagtccagagtataactccatg------------
-----------atactcgatttta---------------------ttcgaagccgttggg
tgg------------------------------tcaagcactgtgcagatggggcacgat
gagtgggtgggcctgc----
>SEQ16
atatgtagccgcgggttgtaggataatcgaatagttcataccccctaaacctaa------
---------------------------------gttgctagctacttcgatacataat--
--------------------------------------------tgcatagtgggctttt
tgttttgatatccagtcattcccctaatgcggcacccatgccttccagccctggggttca
aatgacataattttactttgcttttctcgcccgtgtaacgtctgcagacgtagtcgagtt
cacaaagctggagcacgaatcgctactactttcgcaagatccagacgcaactagcactag
gcaagctaactttaagcgacaaaaacacgttgtgagtggagccaccgactttgct-----
--------------------------------------------------ccatgcagca
tggtaatcag----------atgatccagcgtatacgtttggcagcgattgtgtggtggt
ccaggctgatctgcaagggaagcaactgtcctagccaagaagggacccctcttttcttct
atgaccacc-------------------------cttgcccgaattcctttggcaatggg
cccggatccagcgctcggtc-------------------------caaggggttcctcgg
caacggtact--------------------------------------------------
--------------------gaatttcctatcgagaaggaggctcccttagatttcgcga
acaattgcaggcttttactatcggtgacacaggtgtcacgtcggtaacgtctgtttcgct
tcctcgtgaggtggg---------------------tatgactcgaggctaattagatga
atttcccatctatactcgatatga---------------------ttcgaagccgtggcg
tggaataacactcaacaatcctgatgacttcattcttgcgctgtgcagatggggcacgat
cagagggttggccggcagca
>SEQ17
ttattttggctaata---------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
tggagtatacgctagcacttcccctaatgcggcacgcatgccttccagccctggggttca
aatcacataattttacgttgcttttctcgcccatgtaacgtcttcagacgtagtcgagtt
cagtgagcaggatcacgaatagcgactactttcgcaaagtgagaacgcaaatggaaccag
gcaggctaactctaagcgccgagggcagagtgtgagaggacccccccgatacgcgttagt
gactgttattattatcctcggcgagttcctctacggt-------------acaagcagta
tggtaatgagtccgatgttaatgatccagcgtatacgttgggcagcgtttgtgtggtggt
ccaggcggatctgcaagcgaagcaactgtcctagccaagaagggacccgtcttttcttct
actgc----------------acgtaaggcggcacacgcacca-----------------
----------gtgcaccga---------------------------------------ga
caagattggtacccctaacctgtatgacgctcttattcacgccatatcagttaccgtcca
aacacgtgcgcgtagcaccggaatttcctatcgagtaggaggctcccttagatttcacaa
acaattgcaggcttttactatcggtgacacaggtgtcacgtcgttaacgtctgtttcgct
acctcgtgacatgagcccccgtggaagagaccagagtatgactcgaggctaattagatga
atttcccatctatactccctatta---------------------ttcgaagccgtcgcg
tggaagatcactcaacaatcattatgtcttcatc-------------------acacgat
gagttgtttggccggcagca
>SEQ18
atcatttgcagggtgatagagcattatcgtattgcgcatggcccctaatcctaatggaga
cttcggtcaattgctaagcacattac---------------------cgttacgtattca
tttgccttcgtaagtgtctggacaaaccgcgtggtatccggtggcgaaccgtgtaagtct
tgtgttggacttcagcac-tcccctaatgcggcacgcatgccttccagccctggggttca
aatgacataattttactttgcttttctcgcccgtgtaacgtcttcagacgtagtcgagtt
cacaaagcaggagcactaatagctactgcgttggcaagatccggacgcaaattgtactag
gcaggctaactctaagcgcagagggcagggtgtcagtggacccacccgatacgcgttcgt
gac-------------------------ctccatggtgcgtactccctgaacaagcagta
tggttatccggcccatcttaatgatccagcgtatacgtttggcagcgtttgtgtggtgtt
ccaggctgatctgcaagggaagcaactgtcctagccaagaagggacccctcttttcttct
atgacctcccgaacgacacttcagttattcgagacacaccccaactcgctaggaaatggt
gctggaaccagcggccccaggat----------------------tagtaggaccctcgg
ctagaatcgtaac-----------------------taaaaccttacacgg---------
------------------cggaagttcctatcgggaaggaggctcccttagttttcacga
acaattaaaggcttttactatcggtgacacaggtgtcacgtcggtaacgtctgtttcgct
acctcattacctgagccgccgtggaagagacaggattat------------------tga
aattcccatctacactcgatattacctctcct----------------------------
---------------caatcattatggcttcattgtcacactggccagatggcgcacgat
tagttggttggcga------
>SEQ19
ttgttttg----------------------------------------------------
------------------------------------------------------------
---------------------------------------gccaatatggcctataggcta
ggcgttgaactatagcacttcccctaatgcggcacgcatgccttccagccctggggttca
aatgacataattttactttgctttcctcgcccgtgtaacgtcttcagacgtagtcgagtt
cagaaagggggagcacgaatagcgtcttctttcgtaaagtacgatcgcaagtggagctag
ac---------------------ggcagagtgtgtagtgactgtcattattcagg-----
-----------------tcggccagccccttatggatgctttctacctcaacaagcaga-
-----------------ctgatgatccagcgtatacgttgggcagcgtttgtgtggtggt
ccaggctgatctgcaagggaagcaactgtcctagccaagaagggacccctcttttcttct
acggg----------------ccgaaaggcgagacacgccccaagtccggacggaagggg
tatggatcgagtagaccga---------------------------------------gg
caagaatggtacccctagcctgtatggagctctaatgcaggcgatatcagataccgtgca
aaaacg------------tggaatctcctatcgggaaggaggctcccttagatttcacca
acaattgcaggcttttactatcggtgacacaggtgtcacgtcggtaacgtctgtttcgct
gtcac-------------------------------------tcgaggctgattcg----
----------------------tagctcttcgccgcct----------------------
---------------cagtcat-----------------------------gcgcgtgat
t-------------------
