>SEQ0
agctggaatggacagggtcttcctccaactacttggctgtcccattgacattagtccctc
ttgcgtgttggcctcctcgccgtgaaatacataagccgtagtgcgccggagccacagtcc
agtttcaaaggtaatcccttacgcatcgtgttatactgtttaaaagtcacgacgacaata
tgggttgcgactgtagctagcgtagtgattaggtaaagcttcataccgcggtgcataggc
aagtagaacatgtccgttttggatctccccccgaggtctgcttcggccaactaccacaca
agttctagccccgttggaagcaggacgaagccccggaattatcccgcttggagcgcagag
cctattctgtcggcatggtgctacgccactgtaagttgggttggttagtgtttctctaca
atcctgaacatccaatactgttaggataagtgtgaattaaatttgttataataggtcagc
cacaagccgccgctctgatcacggccacagtaggtcggtgtaaaccatttcagtagttag
ccacactggggcaccgtccctgtgttgaaatagtcagcgccgttacagggaatcatgctc
agatggcccgaggcctactcgcaagtgatcctggaaatgcgttagccttatgcggtattt
cgtgcagtatgggaatataggcagtatggagaacctatcatatacgatatccaggtggat
ctatgccaatttatgagtgcaccaaacacttctacaacgtatctttcagccaaagtttcc
ggcaaacgttttcccgttggtccatcgaaaaaagggctgacccagttttgtaagatacaa
tatcgtcgtaaacaaaggacgtttgccaaaccgacaacggtaccgggttcgtgcacggaa
aaatcgttccgtatacttaatctggtctagactcccccgcacaactgcgtgcgtggggac
atttgcaaccagcaggacacgggcgggatgtgctgggtaatcattccagtcttcgggcga
gaaaggaaccacgcttcgtcatatgtaattgaccacacatcacgcaaagtgatgtatttt
gctagagggatggtcctcac
>SEQ1
agctggaatcgacagggtcttcctccaactacgtggctgtcccattgacattagtccctc
ttgcgtgttggcctcctcgcggtgaaatacaga-------------------------cc
agtttcaaaggtaatcccttacgcatcgtgtaatactgct---------------caata
tggcttagtaccgtagctagcgtagtgattaggcaaagcttcataccgcggtgcataggc
aagtcgaacatgtccgttttggatctccccccgaggtctgcttcggccaactaccacaca
agttctagccccgttggaagcgagacgaagcgcaggaattaacccgctttgagcacagag
cctgttctg-------------acggcactgtaagttgggttggttagtgtttctctaca
atcaagatcattccatactagtaggctaagtgtgaattaaatttgttctaataggtcagc
cacaagccgccgctttgatcacggccacagtaggtcggtgtaaaccatttcagtagttag
ccacactggggcaccgtccctgtgttgaaatagtcagcgccgttacagggaatcatgctc
agctggcccgaggcctgcccgcaattgatcctggatatgcgttagcctttggggaagatc
c---------------------------------------------------aggtggat
ctatgccaatttacgagtgcacaaaacacttctacatcgtatctttcagccaaattttcc
ggggaa---------gtttttccatcgaaaaaagggttcacccagttttgtaagatacaa
tatcgtcgtaaacaaaggacgtttgccaaaccgacaacggtaccgggttcgtgcacggaa
aaatcgttccgtatacttaatctggtctagactccaccgcacaaccgcgtgcgtggagac
atttgcaaccagcaggacacgggcgggatgtactgggtaatcattcgattcttcgggcga
gaaaggaa-----------------------------------gtaatttcatgtatttt
--------------------
>SEQ2
ggctggcatggacagggtcttcatccaactacgtggctctcccattgacattagtgcctc
ttgcgtgttgg-----------------------------------------------cc
agtttca-----------------ctcgtgtcatgctgct---------------caata
tggcttagtaccgtagctagcgtagtgattaggtaaagcttcataccgcggtgcataggc
aagtagaacatgtccgttttggatctccccccgaggtctgcttcggccaactaccacaca
agttctcgccccgttggaagcgagacgaagcgaaggaattaccacgatttgagcacagag
cctgttctg-------------acggcactgtaagtta----------------------
-----gatcattccatactagtaggctaagtgtcaattacatttgttctaataggtcagc
cacgaggcgccgctttgatcacggccacagtaggtcggtgtaaaccatttcagtagttag
ccacactggggcaccgtccctgtgttgaaatagtcagcgccgttacagggaatcatgctc
agctcgcccaaggcctgcccgcaattgatcctggatgggcgttagtctttggggaagatc
c---------------------------------------------------atgtggat
ctatgccaatttacgagtgcaaaaaacacttcgacttcgtatctttccgccaag------
-------------------ttccatcgaaaaaagggctgacccagttttgtaagatacaa
tatcgtcgtaaacaaagaacgtttgccaaaccgacaacggtaccgggttcgtgcacggaa
aaatcgttccgtatactt---------------cctccgcacaaccgcgtgcggggatac
atctgcaaccaacagga------------------gttaatcattcgattcttcggtcga
gaaaggaa-----------------------------------gtaatttcctgtattta
--------------------
>SEQ3
agctggaatgtccggggttttcctcccactactcggctgtcccattgacactagtccctc
ttccgtgttagactcctcgccgtgaaatacataagccgtagtgcgccggagccacagtcc
agtttgaaaggtaagcccttacgcatcgcgtgatactgattaaaagtcacgacgagaata
tgggttgcgagtgttggtagcgtagtgattaggtaaagcttcataccgcggtgcataggc
aagtagaacatgtccgttttggatctccccccgaggtctgcttcggccaactaccacaca
agttgtagcaccgttgga----------------------atcccgcttggagcgcagag
cctatactgtcggcatggtgctgcgccactgtaagttgggtcggttagtgtttctctaca
atcctaaacatccaatacggttaggataagtgtgacttagacttgatataagaggcgagc
cagaagccgctgctctgatcacggccacagtaggtcggtgtaaaccatttcagtagttag
ccacactggggcaccgtccctgtgttgaaatagtcagcgccgttacagggaatcatgctc
agatggctcgaggcctcctcgcaagtgatcctggaaaagcgtcagccttatgcggtattc
cgtgcagtgagggaatata-----------------------------------------
------------atgagtgcaccaaacacttccacaaggtatctgtgagcgaaagtttcc
cgcaaacgttatcccgtttgtccatcgaaaaaagggctgacccagttttgtaagatacag
tatcgtcgtaaacaaagaacgtttgccaaaccgacaacggtaccgggttcgtgcacggaa
taatcgttccgtatacttaatctggtctagacggcaccgcacaaccgcgtgcgtgcagac
attcgcaaccagtaggacgt-----------------taatcatacgattcttggggcga
gaaaggaa-----------------------------------gtaatttcatgtatttt
--------------------
>SEQ4
ggctggcatggacagggtcgtcacccaactacgtggctctcccattggcattagtgcctc
ttgtatcttg------------------------------------------------ct
agtttca-----------------gtcgtgtcatgctgct---------------caata
tcgcttaataccgtaactagcgtagtgagtaggtaaagcttcataccgcggtgcataggc
aagtagaacatgtccgttttggatctccccccgaggtctgcttcggccaactaccacaca
agttcttgccccgttgaaagcagggcgaagcaccggaatcatcgcgcttggagcgcag--
----------cggcatggtgctacgccactgtaa----------------gttctctaca
atcctgaacatccaatactgttaggttaag------------------tcataggtccgt
cacaagcccccgttctgatcacggccacagtaggtcggtgtaaaccatttcagtagttag
ccacactggggctccgtccctgtgttgaaatagtcagcgccgttacagggaatcatgctc
agatggctcgaggcctcctcgaaa--------------gcgtcagccttatgcggtactc
catgcagtgaggaaat--------------------------------------------
------------gtaagtgcaccaaacccttccacaaggtatctgtgagcgaaagtttcc
cgcaaacgt----------ttccatcgaaaaaagggctgacccaggtttgtaagatacaa
tatcgtcgtaaacaaaggacgtttgccaaaccgacaacggtaccgggttcgtgcacggaa
aaatcgttccgtatacttaatctggtctagactcccccgcgcaactgcgtgcgtggggac
atttgcaaccatcaggacacgggcgggatgtgctgggtaataattagaatcttcgggcga
gaaaggaa------------------ccattactaaacatcacgcaaagtgatgtatttt
gctagaggggtggtccccac
>SEQ5
agcaggaatcgacagggtcttcttcaaactacgtggctgtcccattgacattagtccctc
ttgcgcgtgggcccccccgcggtg----------------------------------cc
agttttaaaggtaatccctaacgcatcgtgtaatactgtt---------------gaata
tggcttagtaccgtagctagcgtagtgagtaggtaaagcttcataccgcggtgcataggc
aagtagaacatgtccgttttggatctgcccccgaggtctgcttcggccaactaccacaca
agttgtagcaccgctgg----------------------catcccgcttggagagcagac
cctatactgtcggcatggtgctgcgccactgtaagttcggtcggttagtctttcgctaca
agcctagacatccattacggttaggaaaagtgtgacttagacttgatacaagaggcgagc
cagaagcctgtgctcgtatcacggccacagtaggtcggtgtaaaccatttcagtagttcg
ccacactggggctccgtccctgtgttgaaatagtcagcgacgttacagggaatcatgctc
agctcccccaaggcat-----------------------tgttagtctttggggaagatc
c---------------------------------------------------atggggat
ctatgacaatttacgcgtgcaaaaaacccttc----------------------------
------------------gttccatcgaaaaaagggctgacccagttttgtaagatacaa
tatcgtcgtaaacaaaggacgtttgccaaaccgacaacggtaccgggttcgtgcacggaa
caattg-------------------tctatacggcaccgcacaaccgcgtgcgtgcagac
attcgaaaccagtaggacgt-----------------taatcaaacgcttcttggggcga
gaaacgaa-----------------------------------gtaatttcaggtatttt
--------------------
>SEQ6
agctggaatcgacaggctcatcctccaactacgtgactgtcccattgacatcactccctc
ttgcgtgttggcctcctcgcggtgaaatacaga-------------------------cc
agtttcatatgtaatccat------------------------------------caaga
tgccatagtaccgtagctagcgtagtgattaggtcaagcttcataccgcggtgcataggc
aagtagaacatgtccgttttggatctccccccgaggtctgcttcggccaactaccacaca
agttctcgccccgtgggaagcgagacgaagcgaaagaattaccacg--------------
-----------------------------------------------agacggcactgta
agttagatcattccatactagtaggcaaagtgttaactacatttg---------------
-------ttctaatttgaacacggccacagtaggtcggtgtaaaccatttcagtagttag
ccacactggggcaccgtccctgtgttgaaatagtcagcgccgttacagggaatgatgctc
aggtggcccaaggccggcccgcaattgaccctgtatgggccttagtagg-----------
------------------------------------------------------------
----------------------------------------------------------tc
catgtatctttccgcaaacttccatcgaaaaaagggctgacccagttttgtaagatacag
tatcgtcgtaaacaaagaacgtttgccaaaccgacaacggtaccgggttcgtgcacggaa
caattg-------------------tcgatacgacaccgcacatccgcgagcgtgcagcc
attcgaaaccagtatggcgt-----------------taatcaaactctacttggggcga
gaaacgaa-----------------------------------gtaatttcaggtatttt
--------------------
>SEQ7
agctggaatcgacaggctcattctccaactacgtgactgtcccagtg-------------
---------------------gtgaaatacaga-------------------------cc
agtttcatatgtgatccat------------------------------------taaga
tgccatattaccgtagctagcgtagtgattaggtcaagcttcataccgcggtgcataggc
aagtagaacatgtccgttttggatctccccccgaggtctgcttcggccaactaccacaca
cgttcttgccccgttgaaatcagggcgaagtaccggaatcatcgcgcttggagcgcag--
----------cggcatggtgctacgccacggtca----------------tttctctacg
aatctgaacatccaatagtgttaggttaag------------------ccataggtccgt
tacaagcccccgttctgatcacggccacagtaggtcggtgtaaaccatttcagtagttag
ccacactggggctccgtccctgtgttgaaatagtcagcgccgttacagggaatcatgctc
tgatggcccgaggcctcgccgccagtgatcctggacaagcgtcagccttatgcggtattc
cgtgcagtgagggtatata-----------------------------------------
------------atgagtgcaccaaacacttccacaaggtatctgtgagcgaaagtttcc
gtcaaacattatcccgtttgtccatcgaaaaaagggctgacgcaggtttgtaagatacaa
tatcgtcgtaaacaaaggacgtttgccaaaccgacaacggtaccgggttcgtgcacggaa
atatcgttccgtatacctaatctggtatagac---------------------tagggac
atttgccaccaacaggacacgggcgggatgtgctgtgtaaactttccagtctttagtcag
atgtaatt----------------------gaccacacatcaagcaaagtgatgtatttt
gttagagggatggtcctcac
>SEQ8
agctggaatcgtca-------------------tggctgtcccaatgacattagtaagtc
tcgcgtgttggcctcctcgcggtgaaatacaga-------------------------ac
agtttcaaaggtaatcccttacgcatcgtgtaatactgct---------------caata
tacctttgtaccgtagctagcgtagtgattaggtcaagcttcataccgcggtgcataggc
aagtagaacatgtccgttttggatctccccccgaggtctgcttcggccaactaccacaca
cgttcttgccccgttgaaatcagggcgaagt-----------------------------
----------cgacatggtgctacgccacgg---------------------tctctacg
aatctgaacatccaatagtgttaggttagg------------------ccaggggtccgt
tacaagcccccgttctgatcacggcgacagtaggtcggtgtaaaccatttcagtagttag
ccacactggggcaccgtccctgtgttgaaatagtcagcgccgttacagggaatgatgctc
agatggtccgaggcctactct-----------------gcgttagccttatgcggtattt
cgtgcagtatgggaatataggcagtaaggagaacatatcataaacggtatccaggtggat
ctatgccagtttatgagtgca----------------------------ccaatgtttcc
gacaaacgttttcccggtgctccatcgaaaaaagggctgacccacttttgtaagatacag
tatcgtcgtaaacaaagaacgtttgccaaaccgacaacggtaccgggttcgtgcacggaa
caattg-------------------tctatacggcaccatacaaccgcgtgcgtgcacac
attcgaaaccagtaggacgt-----------------taatcaaccgcttcttagcgcga
gaaacgga-----------------------------------gtaatttcaggtaattg
--------------------
>SEQ9
ggctggcatggactgggtcgtcacccaactacggggcgctcccataggcattattgcctc
ttttatcttg------------------------------------------------ct
agtttca-----------------gtcgtgtcatgctgct---------------caata
tcgcttaatcgcgtaactagcgtagtgagtaggttaagcttcataccgcggtgcataggc
aagtagaacatgtccgttttggatctcaccccgaggtctgcttcggccaactaccacaca
agtttttac---------------------------------------------------
----------------------------------------------aagtccgcactgta
agttagatcattcgatacttgtaggcaaagtgtgaactacatttg---------------
-------ttctaatttgatcacggccacagtacgtcggtgtaaaccatttcagtagttag
ccacactggggcaccgtccctgtgttgaaatagtcagcgccgttacagggaatcacgctc
agctggcccgaggccggct-------------------gccttagcctt-----------
----------------------------------------------agatccaggtggat
ctatgccaatttacgacttcagaaaacacttctacatcgtatctttccgcccaattttcc
--------------------tccatcgaaaaaagggttcacccagttttgtaagatacaa
tatcgtcgtaaacaaaggacgtttgccaaaccgacaacggtaccgggttcgggcacggaa
caattg---------------------------------cacaaccgcgtgcgtgcagac
atgcgaaaccagtaggacgt-----------------taatcaaacgcttctttgcgcga
gaaacgaa-----------------------------------gcaattgtttttt----
--------------------
>SEQ10
ggctggcatggagaaggtcgtcaccaaactacgtggctctcac-----------------
------------------------------------------------------------
-------------------------tgatagtatcatgct---------------ctata
tctctgaagaccgtaactagcgtagtgattaggtcaagcttcatcccgcggtgcataggc
aagtagaacatgtccgttttggatctccccccgaggtctgcttcggccaactaccacaca
cgttcttgccccgttgaaatctgggcgaagtaccggaatcatcgcgcttggagcgctg--
----------cggcatggtgctacgccacggtca----------------tttctctacg
aatctgaacctacaacagtgctaggttcag------------------gcatatgtccgt
tacaagcccccgttctgatcacggccacagtaggtcggtggaaaccatttcagtagttcg
ccacactggggctccggccctgtgttgaaatagtcagcgacgttacagggaatcatgctc
agatggctcgaggcctcctcgcaagtgatcctggaaaagcgtcagtcttattcggtatcc
cgtgcag-----------------------------------------------------
------------atgagtgtaccaaacccttccacaaggtagctctgagcgaaagtttca
tgcaaaggttatcccgtttgtccatcgaaaaaagggctgacccagttttgtaagatacaa
tatcgtcgtaaacaaagaacgtttgccaaaccgacaacggtaccgggttcgtgcacggaa
aaatcgttccgtatactt---------------cctccgcacaaccgggggcggggatac
atctgcaaccaacagta------------------gttaaccattcgatacttcggtcga
gaaaagaa-----------------------------------gtaagtt----------
--------------------
>SEQ11
agctggaatgcccgaggttttcctcccactactaggcggtccgatcg-------------
----gtgtcaaacttctcgccgtgaaacacataagtcgtagtgcgccggaatcacagtcc
agtttgaaaggtaagcccttacgcatcgcgtgttaccgattaaaaagcacgacgagaata
tgggttgcgagtgtaggtagcgtagtgattaggtcaagcttcataccgcggtgcataggc
aagtagaacatgtccgttttggatctccccccgaggtctgcttcggccaacaaccacaca
agttctagcccggttgggagcagcaagaagccccggaattattccgcgtggagaacagag
cgtattctgtcggcatggtgctacgccactgtgagatgggttggttag------------
--------------ataagtgacgattaa-------------------------------
-ataaacccccgctcttatcacgtcgacagtaggtcggtgtaaaccatttcagtagttag
ccacactggggcaccgtccctgtgttgaaatagtcagcgccgttacagggaatgatgctc
tgattgcccaaggtctcgccgccagagagcctggaca---------------cggtcttc
cgtgcagttagggtatata-----------------------------------------
------------gtcagtgcaccaaacacttccacaaggtatctttaagcgaaagtttcc
ctcgaacattatcacgttagtccatcgaaaaaagggctgacgcaggtttgtaagatacaa
tatcgtcgtaaacaaaggacgtttgccaaaccgacaacggtaccgggttcgtgcacggaa
gtatcgttccgtaaacctaatctggtatagac---------------------tagggac
atttgccaccaacaggacaggggcgggatgtgctgtctaaactttccagtctttagtcag
at-----------------------------------------gtgattgtccacatttg
-ttagagggatggtcctcag
>SEQ12
agcagcaatcgacagggtcttcttcaaactacgtgggg--------------atttcctc
ttgcgcgtgggcgccccctcggtg------------------------------------
---------------ccctaacgcatcgtgtaacattgta---------------gaata
tggcttagtaccgaagctagcgtagtgattaggtaaagcttcataccgcggtgcataggc
aagtagaacatgtccgttttggatctccccccgaggtctgcttcggcctactaccacaca
cg----------------------------------------------------------
----------cgacatggtg---------------------------------ctctacg
aatctgaacttccaatggtgttaggttagg------------------------------
--------------ccagggacggccacagtaggtcggtgtaaaccatttcagtagttag
ccacactggggcaccgtccctgtgttgaaatagtcagcgccgttacagggaatcatgctc
aaatggctcgaggcctcctcgaaa--------------gcgtgagccttaggcggtacac
catgcagtgatgaaat--------------------------------------------
------------gtaggggcaccaaacccttccacaagatatctgtgagcgaaagtttcc
cccaaacgt----------gtccatcgaaaaaagggttcacccagttttgtaagatacaa
tatcgtcgtaaacaaaggacgtttgccaaaccgacaacggtaccgggttcgggcacggaa
caatag---------------------------------cacaaccgggtgcgtgcagag
atgctcaacctttaggacgt-----------------taatcaaacgcttctttgcgcga
gaaacgag-----------------------------------gcaattgtttttt----
--------------------
>SEQ13
---------------------------------------tcccattgacattagtccctc
ttgtgtgttggcctacgcgccgtgaaatacataagcccaagt------------------
-gcttcaaaggtaatcccttgcgcaacgagttatagtgtttcaaagtcacgacgacaata
tgggttgtgactgtagctagcgtagtgattaggcaaagcttcataccgcggtgcataggc
aaatcgaacatgtccgttttggatctccccccgaggtctgcttcggccaactaccacaca
cgttcttagcccgttgaaataagggcgcttc-----------------------------
----------gagcgtggtgctacgccacggtca----------------tttctgtacg
aatctgaacatccaatagtgttaggttaag------------------ccataggtccgt
gacaagcccccgttctgatcacggccacagtaggtcggtgtaaaccatttcagtagttag
ccacactggggctccgtccctgtgttgaaatagtcagcgccgttacagggaatcatgctc
aggtggcccaaggccggcccgcaattgacacagtaaggaggtc-----------------
------------------------------------------------------------
------------------------------------------------------------
-----atctttccgcaaacttccatcgaaaaaagggttcacccagttttgtaagatacaa
tatcgtcgtaaacaaaggacgtttgccaaaccgacaacggtaccgggttcgggcacggaa
aaatcgttccggacagttaatctggtctagactcccgcgcgcaactgcttgcgtggggat
atttgcaa-----------------ggatgtgctaggtaatcttaagaagcttcgggcga
gagaggaa-----------------------------------gcattgtcatgtgtttt
gttagaggggtggtcccgac
>SEQ14
atgtggtatggacagggtcgt---------------------------------------
----------gtctcctcgccgtgaaatacctaagctgtagtgcgccggagacacagtcc
agtttcaaacgcaatcgcttacacatcgtgttatactgtttaaaaatcacgacgacaata
tgggtcgcgactgtagctagcgtggtgatttggaaaagcttcataccgcggtgcataggc
aagtagaacatgtccgttttggatctcccccccaggtctgcttcggccaactaccacaca
agttctagccctgatggaaccaggactaagccacggaattatcccgcttggagcgtagag
cctgttctgtcggcatggtgctacgccactgtaatttgggttggttagtgcttctctaca
atcctgaacctccaatactattaggataagtgtgaattatatttgatataataggtcagc
cacaagccaccggtctgatcacggccacagtaggtcggtgtaaaccatttcagtagttcg
ccacactggggctccgtccttgtgttgaaatagtcagcgacgttacagggaatcatgctc
ggagggcacgaggcctcctcgcaagag-------------------------------tc
cgtgcagtgaggggaaata-----------------------------------------
------------atgagtgcaccatacacttccacaaggtatctgtgggcgaaagtttcc
cgcaaacgttatcccatttgtccatcgaaagaagggttcacccagttttgtaagatacaa
tatcgtcgtaaacaaaggacgtttgccaaaccgacaacggtaccgggttcgggcacggaa
caattg---------------------------------cacaaccgcgtgcgtgccgaa
atgcaaaaccagtaggacgt-----------------taatctaacgcttcttttcgcga
gaaacgaa-----------------------------------attgtttttt-------
--------------------
>SEQ15
agcaggaaccaacagggtcttcttcaaactacgtggctgacccattgacattagaacctc
ttgcgcgtgggcgcccccccggtg----------------------------------cc
agtttaaaaggtaatccctaacgcatcgtgtaatact-----------------------
--------ttccgtagcaagcgtagtgattaggcaaagcttcataccgcggtgcataggc
aagtcgaacatgtccgttttggatctccccccgaggtctgcttcggccaactaccacaca
cgttcttg------------------gaagt-----------------------------
----------cgacatggtgctacgcaacgg---------------------tctctacg
aatctgaacatccaatagtgttaggttagg------------------ccaggggcccgc
taccaggccccgtactgatcacggccacagtaggtcggtgtaaaccatttcagtagttcg
ccacactggggctccgtccctgtgttgaaatagtcagcgacgttacagggaatcatgctc
agctcccccaaggcat-----------------------tgttagtcttgt---------
----------------------------------------------agatccatggggat
ctatgacaatttacgcgtggcaaaagaccctc----------------------------
------------------gttccatcgaaaaaagggctgacccagttttgtaagatacaa
tatcgtcgtaaacaaagaacgtttgccaaaccgacaaccgtaccgggttcgtgcacggaa
atctgg-------------------tcttgtctcccgcgcgcaactgcttgcgtggtgaa
agttgcaa-----------------ggaggttctaggtatgcttaagaagcttggggcga
gcgaggaa-----------------------------------gcagt--catgtgattt
gttagaggggtggtcccgat
>SEQ16
ggttcgcattgaccgggtcgtcacccaa---------------------------gcctc
ttttatcttg------------------------------------------------ca
agtttca-----------------gtcgtgtcatgctgct--------------------
--------------gcgtgacgtagtgattaggcaaagcttcataccgcggtgcataggc
aagtcgaacatgtccgttttggacctccccccgaggtctgcttcggccaactaccacaca
agtcc--------------------agaagccccgcaattattctacgtggagaacagag
agactcctgtaggcatggtgctacgccaccgtgagatgggttggttag------------
--------------ataattgtcgattaa-------------------------------
-atagacccccgctcttatcacggccacagtaggtcggtgtaaaccatttcagtagttag
ccacactggggcaccgtccctgtgttgaaatagtcagcgccgttacagggaatcatgctc
aggttgcccaaggccggcccgcagttgaccctgtttggaggtccattt------------
------------------------------------------------------------
------------------------------------------------------------
-----atcattccgcaagcttccatcgaaaaaagggctgacccagttttgtaagatacag
tatcgtcgtaaacaaagaacgtttgccaaaccgacaacggtaccgggttcgtgcacggaa
gaattg-------------------tctatacggcaccgcacaaccgc------------
------------------------------------------------ttcttggggtga
gaaactaa-----------------------------------gtaattggtagttt---
--------------------
>SEQ17
agcagcaatcgacagggt-------------------------------gggatttcctc
tagcgcgtcgtctcccccgcggtg------------------------------------
---------------ccctaactcatcttgtaacattgta---------------aaata
tggcttagtaacgcagctagcgtagtgattaggcaaagcttcataccgcggtgcataggc
aagtcgaacatgtccgttttggagctccccccgaggtctgcttcggccaactaccacaca
agtacttgccacgttgaaagcatggcgaagcaccggaatcatcacgcttggagcccag--
----------cggtatggtgctgcgccactgt----------------------------
--------------acactgttaggttaag------------------tcataggtccgt
cacaagccccgtt-----tcacggccacagtaggtcggtggaaaccatttcagtagttcg
ccacactggggctccggccctgtgttgaaatagtcagcgacgttacagggaatcatgctc
agctggccagaggcctgccagcaattgatcctggttatgggttagccttgga--------
----------------------------------------------agatccaggtggat
cgatgccatttta-------------------cacatcggatatttcagccaaattttcc
ggggaa---------gtttttccatcgaaaaaagggctgacccagttttgtaagatacag
tatcgtcgtaaacaaagaacgtttgccaaaccgacaacggtaccgggttcgtgcacggaa
caattg---------------------------------cacaaccgcctgcgttgagtc
atgcggaaccagtaggacgt-----------------taatcatacgcttcttggcgcga
gaaacgaa-----------------------------------gcaattgtttttt----
--------------------
>SEQ18
agctagaacgtcaggggttttc------------------tccattgacactagggcttc
ttccgtgttagacttctcgccgtgaaatatataagccgtagaccgccggagccacagtcc
cgattgaaagataagcccttacgcatagcgtgatacagat------------------ta
caagtcacgtctgttggtagcgtagtgat---gcaaagcttcataccgcggtgcataggc
aaatcgaacatgtccgttttggatctccccccgaggtctgcttcggccaactaccacaca
agttccagccccgtaggaagcgacacgaagcgcaggaattaacccgctttgag-------
----------------------acgccactgtaagtcgggttgattagtgtttctctaca
-------------------------------gtgaattaaatttgttctactaggtcagc
cacaagccgccgctttgatcacggccacagtaggtcggtgtaaaccatttcagtagttcg
ccacactggggctccgtccctgtgttgaaatagtcagcgacgttacagggaatcatgctc
aactgggccgaggcctgcccgcaagtgaccctggatatacgttagccgttggggaagatc
c---------------------------------------------------aggtggat
ctatgccaat------------aaaacagttcttcatcgtatctttcaaccaaattttcc
ggggaa---------gtttttccatcgaaaaaagggctgacccagttttgtaagatacaa
tatcgtcgtaaacaatcgacgtttgccaaaccgacaacggtaccgggttcgtgcacggaa
gtatcgttccgtaaacctaatct------------------------------tggggac
atttgccactaccaggacagggacgggatgtgctatctaaactttacagtctttagtgac
gt-----------------------------------------gtgattgtccacatttg
-ttagagggatggtactcag
>SEQ19
agctag-----------------------------------tcattgacactacggcttc
ttccgtgttagacttctcgccgtgaattatataagccgtaggt---------------ca
cgattgaaaggtaagcccttacgcatagcgtcgtg-------------------------
-----------ggtaggtagcgtagtgattaggtaaagcttcataccgcggtgcataggc
aagtagaacatgtccgttttggatctccccccgaggtctgcttcggccaactaccacaca
cgttcttgccccgttgaaattcgcgtt---------------------------------
----------tgtcgcgctgcta-------------------------------tctacg
aatctgagcctacaacagtgctaagttcag------------------gcatatgtccgt
tacaagcccccgttttgatcacggccacagtaggtcggtgtaaaccatttcagtagttcg
ccacactggggctccgtccctgtgttgaaatagtcagcgacgttacagggaatcatgctc
tggtggtccttagtaggtcca---------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--tgtatctttccgcaaacttccatcgaaaaaagggctgacccagttttgtaagatacag
tatcgtcgtaaacaaagaacgtttgccaaaccgacaacggtaccgggttcgtgcacggaa
caatta---------------------gatacgacgccgcacatccgcgagtgtgcagcc
attcgaaaccagtatgtctt-----------------taatcaaactctccgtgggggga
gcaacgaa-----------------------------------gtaatttgaggaatttt
--------------------
