>SEQ0
acggttaaccaatggatgccgcagcttgaggttgatacgtctaaaaaaagactacctgtt
accttggagcggcgacggttggtgtggcggcccctgtctaccagcaagacccgcttggtt
ttgtaaccacacgggggttcctggaaccatgccatcgcgtaacaagagaatccccttctg
gaggaggtccgcgatcagaccaccggatcccacaaggtttaggaagccctcatcagccgc
tcggtaaaacgcgtgagcatatcgtcaatatgtaccgagtcctgtgagcttagcgtttct
ggatttgtatccggacattatggagggagtttgtcaaatgttaccgcgaacgctagatac
ttgttcataggttaactggcgcgctgaaatctcttacgcgagctgtaaaattttgggcca
gggagatgtagcggtcaaaagaaccttgccctactttccctctgagccctcaatagagcc
cgtcaataaaggatatttcgttaacccgcgctggaaccgtagcgaattgcgccggatcta
cggacaatccgggcttgcgatgcccccagacggtacataggattctcccgcatggctcgg
tcaggcaatactgtcttatgaaagaggaccgcaagtttgctcatcgctaactgcccctag
ccctaattatcactatctcaagtattcccaaattaagaggtggcttatacctgatccggt
ataccgtca-----tactacccgtaccacttcggcgtgtgacaaccgtcatgagttccgg
gtatcaccctaggaatcttcc----------cgatgatgaccacagccgagattactttc
ttggacggtgacactatctcggtcagggtgaagcgtctcagtgctcaagaccacatttca
ttgcattctggagcgtcactttatttaagcgaggttacttccgcaaagtaacatgttagc
tgggtctgtcatcagtacagattttcgtgcctagagatgctacgggacccacttcgatac
cttaaaataatcaatctctggaccttgtacgttagcttaagccataacggtaagagaccc
gtttacctattggcaacactgaggagacagataac
>SEQ1
atggttatcgaatggatgccgcagcttgaggttgatacatcgaaaaatagactacctgta
accttggagcgccgacggttggtgtggcggcccttgtctaccaccacacgggggttcgt-
----------------------ggaaccatgccatcgcgtaacaagagtatccccttctg
gacgaggtccgcgatcagaccaccggatcccaaaaggtttaggaagccctcatcagccgc
tcggtaaaacgcgtgagcatatcgtcaatatgtaacgagtcctgtgagcttagcgtttct
ggatttgaatccgtacattatgaagggtgtttgtgaattgtttccgcaaacgctagatac
ttgtccataggttaactggcgcgccgaagtctctta------------------------
-----------------acagaaccttgcggttcttttcctctgagaccacaatagagcc
cctcaatttaggatttttcgttaacccgcgctggaaccgtagcgaattgcgccggatcta
cgcacaatccgggcttgcgatgcccccagacggtacataggattctcccgcatggctcgg
tcaggcactagagcctta---------------attttgctcatcgctaactgccactag
ccctaattttcactatctcaagtattcccaaattat------------------tccggt
ataccgtta-----cg-actttgcatgagtttctggtt----------------------
---tcaccctaggaaacttcc----------caaggatgaccacagccgagattactttc
ttggacggtgacactatctcggtcagggtgaagcgtctcagtgctcaagaccacatttca
ttgcattctggagcgtcactttatttaagcgaggttacttccgcagagtactagat----
------------------------------------------------------------
---aaagtaatcaatctctggaccatgtacgttagctccagacataacggtacgaga---
---------------------aggagacagataac
>SEQ2
acggcaaaccaatggatgccgcagcttgaggttgatacgtctaaaaaaagactacctgtt
accttggagtggcgactgt--------------------------atgaccggattggtt
tt------------------gtggaaccatgccaacgcgaaa------------------
gaggagggcagcgatcagaccaccggatcccaaaaggtttaggaagccctcatcagccgc
tcggtaaaacgcgtgagcatatcgtcaatatgtaacgagtcctgtgagcttagcgtttct
ggatttgaatccgtacattatgaaaggtgtttgtgaattgttaccgcaaac---------
-----------ttaactcgcgcaccgaagtttctta------------------------
-----------------acagcacctggcggatcttttactctgagaccacaatagagcc
cctcaatttaggatt-----ttaacccgcgctggaaccgtagcgaattgcgccggatcta
cgcacaatccgggcttgcgatgcccccagacggtacataggattctcccgcatggctcgg
tcacgcaatactgtcttatgaaagaggacggcaagttagcgcac----------------
------------------------ttcccaaattaagatgtggcttatacctgatccggt
ataccgcca-----tactccccgtacca--------------------------------
----------------cttctatcacccgaggaatgatgaccacagccgagattacgttc
taggacggtgacactatctcggtcagggtgaagcgtctcagtgctcaagatcacatttca
ttgcattctggagcgtcactttattgaagcgaggttacttccgcagagtactagat----
------------------------------------------------------------
---aaactaatcaatctttggaccatgtactac---------------------------
-----------------------------------
>SEQ3
acgggtaacaagtggat--------------------cgtctaagataagactacctgtt
accttggagcggcgacgtttggtgtgtcggcccctgtctatcagcaagacacgcttggtt
tt----------------------gaccatgccatcgcgtaacaagagaatccccttctg
gaggaggtacgcgctcagaccaccggatcccaaaaggtttaggaagccctcatcagccgc
tcggtaaaacgcgtgagcatatcgtcaatatgtaacgagtcctgtgagcttagcgtttct
ggattcgtatccggacattatggaggtagtttgtcaaaagttaccgcgaacgttagctac
ttgttcatatgttaactgtagcgctgaaatctcttacgcgatctgtaaaattttgg----
------------ggtcaaaagaaccttgccctactttccctctgagccatcaatagaggc
cgtcaatataggatatttcgctaacccgcgctggaaccgtagcgaattgcgccggatcta
cgcacaatccgggcttgcgatgcccccagacggtacataggattctcccgcatggctcgg
tcacgcaagcacg-----------------------------------------------
-------------------------tcccaaattaagaggaggttaatacctgattcggc
ataccgcca-----tcctccccgttcca--------------------------------
----------------cttctatagcgcgaggaatgatgaccacagccgagattactttc
ttggacggtgacactatctcggtcagggtgaagcgtctcagtgctcaagaccacatttca
ttgcattctggagcgtcactgtattgaggagaggttacttccgcatagtactagataagt
aatac-------------------------------------------------------
------------------------------------------------------------
-----------------------------------
>SEQ4
acgggtaacacgtggat--------------------tgtctaggataagacgtcctgtt
accttggagcggcgacgtttggtgtgtccgcccctgtctaacagcaagacacgcttggtc
tt----------------------------------------------------------
---gaattacgcgctcagaccaccggatcccaaaaggtttaggaagccctcatcagccgc
tcggtaaaacgcgtgagcatatcgtcaatatgtcacgagtcctgtgagcttagcgtttct
agatttgaatgtgtatgttaggaaaggtgtgggggaattgttaccgcaaac---------
-----------ctaactcgcgcaacgaagt------------------------------
-----------------aaagcgcctggcggatctgttattctgacccctc---------
--------------------ttaacccgcgctggagccgtagcgaattgcgccggatcta
cgcacaatccgggcttgcgatgcccccagacggtacataggattctcccgcatggctcgg
tcgggcactagagccttatggctaggtgc-------------------------------
---------------tctcaggtattcccaaattat------------------tccggt
ataccgtcaggagtttctggttacaccc--------------------------------
---------------------------taggaaaagatgaccacagccgagattactttc
ttggacggtgacactatctcggtcagggtgaagcgtctcagtgctcaagaccacatttca
ttgcattctggagcgtcactgtctggaggagaggttacttcctagataagtaattc----
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------
>SEQ5
acgggtaacaagtggat--------------------cgtctaggataagactacctgtt
acattagagcggcgacgtttggtgtgtcggcgcctgactatcagcaagacacgcttggtt
tt----------------------gaccatgccatcgcgtaacaagagaatccccttctc
gggaaggtacgcgctcagaccaccggatcccaaaaggtttaggaggccctcatcagccgc
tcggtaaaacgcgtgaccatatcgtcaatatgtaacgagtcctgtgagcttagcgtttct
ggatttgtatccggacattatggagtgcctttgtcaatt---------------------
-----cataggttaactggc-----------------------tgtagaaagttgggcca
gggagatgtagcggtcaaaagaaccttgccc-----------------------------
-------aaatgctatttggttaacccgcgctggaaccgtagcgaattgcgccggatcta
cgtacaatccgggcttgcgatgcccccagacggtacataggattctcccgcatggctcgg
tcaggcaatactgtcttatgaaagtggaccgcaagtttgcccatcgctaactactcctag
ccctaaatatcactttctcaagtcttgccaaattaacaggtggcttataccttaaccggt
atatcgtca-----aactacccgtaccacttcggcgtg----------------------
---tcacgctcggaaccttcc----------cgatgatgaccacagccgagattactttc
ttggactgtgacactatctcggtcagggtgaagcatctcagtgctcaagaccacatttca
ttgcattctggagcgtcactttattgaagcgtggttagttccgcagagtactagacttac
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------
>SEQ6
acggcaaaccaatggaagccgcagcttgaagttgatacgtcgaaaaaaagagctcctgat
accttggagtg----------------------------------atgacccgcttggtt
tt------------------gtggaaccatgccaacgcgaaa------------------
gaggagggcagcgatcagtccaccggatcccaaaaggtttaggaggccctcatcagccgc
tcggtaaaacgcgtgaccatatcgtcaatatgtaacgagtcctgtgagcttagcgtttct
ggatttgtatcccgacattatggagtgcgtttgtcaata---------------------
-----cataggttaagttgc----------------------------------gggcca
gggagatctgacggtcaaaagaaccttgccc-----------------------------
-------aaatgctaattggttaacccgcgctggaaccgtagcgaattgcgccggatcta
cgcacaatccgggcttgcgatgcccccagacggtacataggattctcccgcatggctcgg
tcacgccagcacg-----------------------------------------------
-------------------------tcccaacttaag-----------------------
--------------ccctccaccttcca--------------------------------
----------------cttcaatagcgagaggaatgatgagcacagccgagattactttc
ttggactgtgactctatctcggtcagggtgaagcatctcagttctcaagaccacatttca
ttgcattctggggcgtcactttattgaagcgaggttacttcatcagagtattagg-----
------------------------------------------------------------
---------atcgatctttagaccacgtactac---------------------------
-----------------------------------
>SEQ7
acgggtaacaagtgggt--------------------cgtctgggataatactacctgtt
acattagaacggcgacgttttgtgtgtcggcgcctcactatcagcaagacccgcttggtt
tt----------------------gatcatgccatcgcgtaacaaaagaatacccttctc
gggcaggta-----------caccggatcgcaaaaggtttaggaggccctcatcagccgc
tcggtaaaacgcgtgaccatatcgtcaatatgtaacgagtcctgtgagcttagcgtttct
gtagttgaatccgtatattatgaaaggtgtttgtgaattgtttccgcaaacgctagatac
ttgcccataggttaattgacgctccgaagtctctta------------------------
-----------------acagaaccttgc---------------ggttcacaatagagcc
cctcaagttaggttttttcgttaacccgcgctggatccgtagcgaattgcgccggatcta
cgcacaatccgggcttgcgatgcccccagccggtacataggattctcccgcatggctcgg
tcaggcaatactgtcttataaaag------------ttgcccatcgctaactactcctag
cccgttataccactttctcaagtctcgccaaattaacaggtggcttataccctaaccggt
atatcgtct-----aactacccgtaccacttcagcgtg----------------------
---ttacgctcggaaccttcc----------cgatgatgaccacagccgagattactttc
ttggacggtgacactatctcggtcagggtgaagcgtctcagtgctcaagaccacatttca
ttgcattctggaacgtcgccttatgtaagtgaggttacttccgcaaagtaacatgttagc
tgggtctgtcatcagtac------------------atgctacgggacccacttcgatac
cttaaaatagtgtatgtcgggaccttgtcccctagcgtaagccataacggtaagagaccc
gtttacctattggcaacactgaggagacagataac
>SEQ8
acggccaaccaatggaagcggcagcttgaagttgatacgacgaaaaaaagagctcctgat
accttggagtaatgac--------------------------------------------
-------------------------------ccggtccgaaa------------------
gaggaggg-------cagcgcaccggatcccaaaaggtttaggaggccctcatcagccgc
tcggtaaaacgcgtgaccatatcgtcaatatgtaacgagtcctgtgagcttagcgtttct
ggatttgtatccggacatca----------------aatgttaccgcgaacgctagatac
ttgttcataggttacctggcccgctgaaatctcttaccccagctgtaaatttttgggcca
gtgag-----------------------------------------------atggagcc
cgtcaataaaggatatttcgttaacccgcgctggatccgtagcgaattgcgccggatcta
cgcacaatccgggcttgcgatgcccccagccggtacataggattctcccgcatggctcgg
tcaggcaatactgtcttatgaaagtggtccgcatgtttgcccatcgcgaactactcttag
ccctgaatattactttctcaagtcttaccaagttaacaggttgcttttaccttaaccgct
atatcgtaa-----aactacccgtaccccttcggcgtg----------------------
-------------------------------tcacgatgaccacagccgagattactttc
ttggacggtgacactatctcggtcagggtgaagcgtctcagtgctcaagaccacatttca
ttgcattctggagcgtgactttatttaggcgaggttacttccgctgagtactacat----
------------------------------------------------------------
---gaagttatcaatctgtggaccatgtctgttacctccagacataacgggacgagaatc
ac---------------------------------
>SEQ9
-------------------------------------tgtcgaggataagacgtcctgtt
acattgtgtcg------------------------------------------cttggtc
tt----------------------------------------------------------
---gaattaccggctcagaccgccggatcgcaaaaggtttaggaggccctcatcagccgc
tcggtaaaacgcgtgaccatatcgtcaatatgtaacgagtcctgtgagcttagcgtttct
ggatttttctcccgacattagggagggagtttgtcaaatgttacctcgaacgctagatat
ttgttcagaggttaactggcgcgctgaaatctcttacgcgagctgtaaaattttgggcca
ggaagatgtagcggtcaaaagaaccttgccctactttccctgtgagccctaaatagagcg
cgtcaataaaggacatttcgctaacccgcgctggaaccgtagcgaattgcgccggatcta
cgcacaatccgggcttgcgatgcccccagacggtacataggattctcccgcatggctcgg
tcaggcaatactgtcatatgaaagtgaaccgcaagttt-------------------tag
ccgtaaatatcactttctcaagtcttgccaaattaacaggtcgcttatgccttatccggt
atatcgtca-----aacaagcagtaccg--------------------------------
----------------cttcc----------cgatgatggccacagccgagattactttc
ttggacgttgacactatctcggtcagggtgaagcgtctcagtgctcaagaccacatttca
ttgcattctggagcgtcactttaattacgcgaggttacttccgcaacgtaacatgttagc
tgggtctgtaatcagtaaatattttcgtgcttagagatattacgggacccactttgatac
cataaaatagtcaacccattgaccttctacgttagcttcagccataacggtaaaagaccc
gtatacctattggcaacactgagga----------
>SEQ10
atggttatagaatgcgtgctgcagcttgaggttgatacatccagaaataggctacctgtc
------------------------cggcggtccttgtctaccacgacac-----------
-------------------------------ccatcgcgtaacaagattaggccctcctg
gacgaggcccgcgatcagaccaccggatcccaaaaggtttaggaggccctcatcagccgc
tcggtaaaacgcgtgacgatatcgtcaatatgtaacgagtcctgtgagcttagcgtttct
ggacttgaatccgtacattataaaaccggtttgtggattgttaccgcaaac---------
-----------ttaactcgcccaccgaggtttctta------------------------
-----------------acagcacctggcggatcttttactctgagaccacaatagagcc
ccagaatttaggatt-----ttaacccgcgctggatccgtagcgaattgcgccggatcta
cgcacaatccggtcttgcgatgcccccagccggtacataggattctcccgcatggctcgg
tcgcgcaagcacg-----------------------------------------------
--------------------------cccaaattaagaggtggttaattcctgattcggc
ataccgcca-----tcctacccgttcca--------------------------------
----------------cttctatagcgtgaggaatgatgaccacacccgagattactttc
ttggacggtgacactatctcggtcagggtgaagcgtctcagtgctcaagaccacatttca
ttgcattctggagcgtcactttattgtactagactac-----------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------
>SEQ11
atggttacagaaggcgtgctgcaggttgaggttgataca---------------------
------------------------cggcggtccttgtctaccacgacac-----------
-------------------------------ccatcgcgtaacaa-----------catg
gacgaggcccgcggtctgaccaccggatcccaaaaggtttaggaagccctcatcagccgc
tcggtaaaacgcgtgagcatatcgtcaatatgtaacgagtcctgtgagcttagcgtttct
gtagttgaatccgtatattatgaaaggtgtttgtgaattgtttccgcacacgctagataa
ttgcccataggttaattgacgctccgaagtctctgc------------------------
--------------------------------------------ggtttacaatagagtc
cttcaagttatgttttttcgttaacccgcgctggatccgtagtcaattgcgccggatcta
cgcacaatccgggcttgcgatgcccccagccggtacataggattctcccgcatggctcgg
tcaggcaattctgtctaatcaaggaggaccgcaagtttgcacat----------------
-cctaattatcactatgtcaagtattcccaaatgaataggtggcttatacctgaaccggt
ataccgtca-----tactccgtgcgaca--------------------------------
-----accgtcggaatcttcc----------cgatgatggccacaggcgagattactttc
tcggacgttgacactatctcggtcagggtgaagcgtctcagtgctcaagaccacatttca
ttgcattctggagcgtcgctttattgaagccag---------------------------
------------------------------------------------------------
----tattaatcgagctttagaccaagtac------------------------------
-----------------------------------
>SEQ12
gtggttacaggaggcgtgctgcaggttgaggttgataca---------------------
--------------------------gcggtccttgtctaacacgacaccaa--------
--------------------------------------------------------catg
gacgaggcccgcggtctg--caccggatcccaaaaggtttaggaggccctcatcagccgc
tcggtaaatcgcgggacgatatcgtcaatatgtaacgaggcctgtgagcttagcgtttct
agatttgaatgtgtatgttaggaaaggggtcggggaactgttaccgcaaac---------
-----------ataattcgcgcaacgaagt------------------------------
aatgcgcccgttggctgacagctc------------------------------------
--------------------ttaacccgcgctggatccgtagcgaattgcgccggatcta
cgcacaatccggtcttgcgatgcccccagccggtacataggattctcccgcatggctcgg
tcatgccatactgtcttatgacagtggaccgcaagtttccgtgtagctaactgcccctag
gcctaattatcactatctcaagta-----------------ggctgatacctgatccggt
attcggcgt---------------------------------------------------
---tcacgctaggaatctgcc----------cattgatgaccacagccgagattactttc
ttggacggtgacactatctcggtcagggtgaagcgtctcagtgctcaagaccacatttca
ttgcattctggagagtccctttaattacgcggggttacttcagtgca-------------
------------------------------------tattttcggaaacaactttgatac
cataatatagtcaacccattgaccttttacgatagctctagccttaacggtaaatggccc
gtatacctattggcaccactgagga----------
>SEQ13
acgggtaacacg-------------------------tgtctaggataagacgtcctttt
acgttggagcgacgacgtttggtgtgtccgccccagtctaacaggaagacacgcttggtc
tt----------------------------------------------------------
----------------gaatcaccggatcccaaaaggtttaggaagccctcatcagccgc
tcggtaaaacgcgtgagcatatcgtcaatatttaacgagtcctgtgagcttagcgtttct
ggattcgtatccggacattatggaagtagtttgtcaaacgttaccgcgcacgttagatac
ttgttcatatgttgactgtaccgctgaaatctcttacgcggtc-----------------
-----------------------------------atctctctgtgccatcaatagagga
cctcaatatagggtattgcgttaacccgcgctggaaccgtagcgaattgcgccggatcta
cgcacaatccgggcttgcgatgcccccagacggtacaaaggattctcccgcatggctcgg
tcaggcaatactgtcttatgaaagtggtccgcatgtttgcaaat----------------
------------ctttctcaagtcttaccaagtgaactggttgcggttaccttaac----
---------------------ggtaccccttcggcgtg----------------------
-------------------------------tcaagatgaccacagccgagattactttc
ttggacggtgacactatctcggtcagggtgaagcgtctcagtgctcaagaccacatttca
ttgcattctggagcgtcactttattagacttac---------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------
>SEQ14
atggttatcgaatggctgccgcaccttgaggttgatacatcgaaaaatacactacctgta
accttagagtggcgacggttggtgtggcggcccgtgtctaccaccagacgggggttcgt-
----------------------ggaaccatgccatcgcgtaacaagtgtatccccttttg
gattaggtctgcgatcagaccaccggatcccaaaaggtttaggaggccctcatcagccgc
tcggtaaaacgcgtgaccatatcgtcaatatgtaacgagtcctgtgagcttagcgtttct
ggctttgtatccggccattatggagtgccttt----------------------------
-----cataggttaactagc-----------------------tgtagaaagttgggcga
gatagatgtagcggtcaaaggaaccttgccc-----------------------------
-------aaatgctatttacctaacccgcgctggaaccgtagcgaattgcgccggatcta
cgcacaatccgggcttgcgatgcccccagacggtacataggattctcccgcatggctcgg
tcaggaaatacggtcttatgaaataggacggcaatttagcgcac----------------
------------------------ttcccaaattaagatgtggctcatacctgatccggt
atacggcca-----tactccccgtaccg--------------------------------
----------------cttctatcacacgagtcatgatgaccacagccgagattacgttc
taggacggtgacactatctcggtcagggtgaagcgtctcagtgctcaagatcacatttca
ttgcattctggagcggcactgtctggaggcgaggttacttcctagataagtaatcc----
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------
>SEQ15
--------------------------------------gtcgaggataagccgtcccgtt
acatggtgtcgctttatcttga--------------------------------------
------------------------------------------------------------
----------------ataccaccggatcccaaaaggtttaggaggccctcatcagccgc
tcggtaaaacgcgtgaccatatcgtcaatatgtaacgagtcctgtgagcttagcgtttct
ggattcgtacccggcc------------------------------cgaacgttagatac
ttttt-------------------tgaaatctcttacgggatctgtaaaattttg-----
-----------tggtcaatagatccttgc------------------catcaatagaggc
cgtcaata------------ctaacccgcgctggaaccgtagcgaattgcgccggatcta
cgcacaatccgggcttgcgatgcccccagacggtacataggattctgccgcatggctcgg
tcgcgcaagcacg-----------------------------------------------
--------------------------cccaaattaagaggcggttaattcctgacccggc
ataccgcca-----tcctacatatagcg--------------------------------
---------------------------tgaggaatgatggccacaggcgagattactttc
tcggacgttgacactatctcggtcagggtgaagcgtctcagtgctcaagaccacatttca
ttgcattctggagcgtcactttattgaagcgcggtgacttacggatagtaa---------
------------------------------------------------------------
---acactcaacaatctttgcaccatgtactac---------------------------
-----------------------------------
>SEQ16
acgagtaacaagtgggt--------------------tgtctgggataatcctacctgtt
acattatagcggcgacggtttgtgtgtcgacgcctcactatcagcaagacccgcttggtt
gt----------------------gatcatgccatcgcgtaacaaaagaaaacccttatc
gcgcaggtg-----------cgcctgatcgcaaaaggtttaggaggccctcatcagccgc
tcggtaaaacgcgtgaccatatcgtcaatatgtaacgagtcctgtgagcttagcgtttct
ggcttagtatccggccattatggagtgcctttcatatgt---------------------
------------------------------------------------------------
----------------------------------------------------agaaagtt
gggcgctaaatgctatttacttaacccgcgctggatccgtagcgaattgcgccggatcta
cgcacaatccggtcttgcgatgcccccagccggtacataggattctcccgcatggctcgg
tcatgccatactgtcttatgacagtggaccgcaagtttccgtgtagctaactgcccctag
gccttatcatcgctatctcaagtatcggcgt-----------------------------
------------------------------------------------------------
---gcacgctaggaatctggc----------gattgatgaccacagccgagattactttc
ttggacggtgacactatctcggtcagggtgaagcgtctcagtgctcaagaccacatttca
ttgcattctggagcgtcactttattagact------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------
>SEQ17
acggcaaaccgatggatgccgcagcttgaggttgatacgtctaataaaagactacctgtt
accttggagtggctacggt--------------------------atgaccagattggtt
tt------------------gtggaaccatgccaacgcgaaa------------------
caggtaggtaccgatcacaccaccggatcccaaaaggtttaggaagccctcatcagccgc
tcggtaaaacgcgtgagcatatcgtcaatatgtaacgagtcctgtgagcttagcgtttct
agatttgaaggcgtatgtgagcaagggggtcgaa--------------------------
-------------aattagcgcaacgaagt------------------------------
-----gcgcgttggctgacagctc------------------------------------
--------------------ttaacccgcgctggaaccgtagcgaattgcgccggatcta
cgcacaatccgggcttgcgatgcccccggacggtacataggattctcccgcatggctcgg
tcacgccagcacgccaa-------------------------------------------
------------------------------------------------------------
--------------ccctccaccttcca--------------------------------
----------------cttcaatagcgagagcaatgatgagcacagccgagattactttc
ttggactgtgactctatctcggtcagggtgaagcatctcagttctcaagaccacatttca
ttgcattctggggcgtcaattgattagact------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------
>SEQ18
acggcaaac-----------------ccaggttgatacgtctaatataagactacctgtt
accc--------------------------------------------------------
-----------------------gaaccatgccaacgcgata------------------
cccgaacgtaccgatcccaccaccggatcccaaaaggtttaggaagccctcatcagccgc
tcggtaaaacgcgtgagcatatcgtcaatatgtaacgagtcctgtgagcttagcgtttct
ggatttttgtcccgacattagggaaggactttgtcaaatgctacctcgaacgctagatct
ttgatcagtggttaagtggcgcgccgaaaactcttacgcgagctgtaaaattt-------
--------------tcaaaaccaccttgccctactttccctgtaagccctaaatagagcg
cgtcaataaaggacatttcgttaacccgcgctggatccgtagcgaattgcgccggatcta
cggacaatccggtcttgcgatgcccccagccggtacataggattctcccgcatggctcgg
tcgcgcaagcaag-----------------------------------------------
--------------------------cccaaattgataggcggttaattcctgtcccggc
ataccgcca-----tcctacatatagcg--------------------------------
---------------------------tgaggactgatgaccacagccgagattactttc
ttggacggtgacactatctcggtcagggtgaagcgtctcagtgctcaagaccacatatca
ttgcattctggagcgtcactgtattgtggagatgttacttccgcatagtactatagtaat
ac----------------------------------------------------------
------------------------------------------------------------
-----------------------------------
>SEQ19
acgggtaacaagtggat--------------------cgtctaagataagactacctttg
accttggaccggcgacgtt----------------gtatatcagcaagacatgcttggtt
tt----------------------gagcacgccatagcgtaa------------------
---caggtacgcgctcagaccaccggatcccaaaaggtttaggaggccctcatcagccgc
tcggtcaatcgcgggacgatatcgtcaatatgtaacgaggcctgtgagcttagcgtttct
ggacctttgtcctgacattagggaagcactttgttaatagctacctcgaacgctagatct
ttgatca--------------ctccgaaaactcttacgcgagctgtaaaattt-------
--------------ccaaaaccactttacccta-----------------aaatggagag
cgtcagtaaaggacatttcgttaacccgcgctggaaccgtagcgaattgcgccggatcta
cgcacaatccgggcttgcgatgcccccagacgctacaaaggattctcccgcatggctcgg
tcagcacgtcccaactta------------------------------------------
------------------------------------------------------------
--------a-----gccctctaccttcg--------------------------------
----------------acttcatagcgagaggaatgatggccacagccgagattactttc
ttggacgttgacactatctcggtcagggtgaagcgtctcagtgctcaagaccacatttca
ttgcattctggagcgtcactttattgaagcgtggttagttccgcagagtatag-------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------
