>SEQ0
tgtcgcgcgcaactcgacagtaccgactttgccgtcctccatttacaatggtgatgctct
cgtctaggaaaacaggagtaattcatggtttcaggtcagcgtagcgctatgatccatccg
ggctgggtgtacatcgtccgcaaggaatgtccgtctcatcctcagattttagcaaaatct
aatctgagaacaaggggttatctcgagcccattaaacgaaataccatgcgtcggtgtcct
cggttttccgtagggcttccgattgatacgtaaaatatacttttaagcacgcccgcctac
attgccagactcaataaaagagtaggtaatctacgaggcggccatggtagagcgaa--gt
tggcggtagcggatcccctgaaatcgtctcaattattaggccgagagtaggccgcaatca
taaatctaacagggccttggccgggacgatcgcttagccccgcactacctgtctctggca
atatcgactcgatttacccgctgcgaaaaccggttgtatggtatgagcctcgtcgttaag
ctagtaagaagtaccttacgcccaatatatgggacggtaattagcagggttcgaacttcc
cttacgaatcattaaaggggtcggagcgtgtcagggtggggctaggagctcgtgaggcta
gattcatttcgagagatagtatgtaacgactcatcgagg--tagacaagtaggtactaac
aattcttgcttatcgaatctattaatggtacttccgctgtcggataacacaaccgacgcg
tacctcaacccatgcaagtctcgcgcacgccccgcatgatttatgccataccaacgcttg
tttgcacaccgcaaggaaggttagctcgagccccaacaaggcaaatggcgctcatcgcca
gaccgcaaacgggtagccttcataatgacatgagcgggaaaactttcatgcctagctaac
aatagatccaccgataatggttgcacaccctggcctttagggatagcggaggaacggcgg
agctcttcgggctcagcttacagagtgacgttatttactcgacggttcatctcgtatcgc
ggattagggtggtcgtcagagtag
>SEQ1
ggtcgggcgcacctcgaaagtaccgactttgcagtcctccatttacaatggggatgctct
cgtctaggaaaacacgtgtcattcttggtttcag-------------------ccagccg
ggctggatgtacatggtccgaaaggaaagtccgtctaatcctcagattttagcaaaatgt
aatctgagaacaaggagttatctcgagcccattaaacgaaataccatgcttcggtgtcct
cggttttccgtagggcttccgattgatacgtaaaatatacttttaagcacgcccgcctac
attgctagacttgacaaaa-------------------cagccatcgtagaacgaa--gt
tggctgtagcggatcctctgaaatcgtctcaactattaggacgagagtaggccgcaatca
taaatctaacagggccttggactggacgatcgcttagcctaggactacctgtttctggca
a----------------tatctgcgaaaaccggttgtatggtatgagcctcgtcgttaag
ctagtaagaagtaccttacgcccaatatatgggacggtaattagcagggttcgaacttcc
cttacgaattattaaaggcgtcggagcgtgtcagggttgggctaggagctcgtgaggcta
gattcaattcgagagatagtatgtaacgactcatcgagg--cagactaataggtactaac
aattctagcttaccgaacctattaatggtacttcagctgtcggataacacaacctacgcg
tacctcaacccatgcaagtcgcgcgcacgccccgcatgatttatgccataccaacgcttg
tttgcacaccgcaaggaaggttagctcgagccccaacaaggcaaatggcgctcatcgcca
gaccgcaaacgggtagccttcataacgagatgagcgggaaaacgttcatgcctagtgaac
aatagatccaccgataatggttgcacaccctggcctttagtgatagcggaggaacggcgg
agctgttagggctcacattcccgagtgccgttatata---------------------gc
ggataggggtggtcgtcagagtag
>SEQ2
cgtcgggcgcacctcaaaagtaccaactttgcagtcctccttttacaatgggcatgctct
cgtcttggaaaacacgtgccatacttggtctcac-------------------ccagccg
ggctggatgtacatggtccgacagggaagtccttctaatcctcagacgtt----------
------------aggagttttctcgagcccattaaacgaaataccatgcgtcggtgtcct
cggttttccgtagggcttccgattgatacgtaaaatatacttttaagcacgcccgcctac
attgccagactcaataaca-------------------aagtaggtattctacggg----
-gcgtgtagcgcatgccctgacaacgcctcaagtattaggccgagactaggccgcaatca
taaatctaacagg---------------------tagccccgcactacctctatctggca
atatcgactcgatctacccgctgcgaaaaccggttgtatggtatgaccctcgtcgttaag
ctagtaagaagtaccttacgcccaatataagggacggtaattagcagggttcgaacttcc
cttacgaatcattcaaggggccggatcgtgtcaaagtggggctaggggctcgtgaggcta
gattcatttcgggagatagtatgttatgactgatcgcgg--tagacaagtaggtactaac
aattcttgcttttggaatctattaatggtacctccgctgtcggagaatataaccgacgcc
ta----------------------gcacgccccgcatgatttatgccataccaacgcttg
tttgcacaccgcaaggaaggttagctcgagccccaacaaggcaaatggcgctcatcgcca
gaccggaaacgggctagt--------------------------------------gaac
aatagagccgcttacaatggatgcacaccctggcctttagtgatagcggaggatcggcgg
ggctgttagcgctcacattcccgagtgccgttattta---------------------gc
ggatagggttggtcgtcagagtag
>SEQ3
cgtc------------------ctaactttgaagtcctccttttacaatgggcctgctct
cgtcttggaaaacacgtgcccttcttggtc-----------------------ccagccg
ggctggatgtacatgttccgacagggaagcccttctaatcctcagacgtt----------
------------aggagttttctcgagcccattaaacgaaataacatgcgtcggtgtcct
cggttttccgtagggcttccgattgatacgtaaaatatacttttaagtacgcccgcctac
atgaccagactctataaaa-------------------gggtagataatctaggaggcgc
ccatggtagagcgtccccagaaaccgtctcaattattaggccgagagttgtccgctagca
taaatctatcatggccttggccggggcgat------------------------------
--------tcgatttacccgctgcgaaaaccgggtgtatggtatgagcctcgtcgttaag
ctagtaagaagtaccttacgcccaatatatgggacggtaattagcagggttcgaacttcc
ctgacgaattattaaaggcgtcccaac----------------------tcgtgagacca
ggttcaattcgagagatagtatgcaacgactcatcgagg--cagactaataggtactaat
aattctagcctagggaacccattaatggtaattcagctgtcgga----------------
----tcagcccatgcaagtcgcgtgcacgccccgcatgatttatgccataccaacgcttg
tttgcaccccgcaaggaaggttagctcgagccccaacaaggcaaatggcgctcatcgcca
gaccggaaacgggctact------------------------------------------
---------gcacacaatggatgcacaccatggcctttagtgttagcggaggatcgccgg
ggctgttagcgcccaccttcccgagtgccgttattta---------------------gc
ggctagagttggtcgtcagactag
>SEQ4
agtc---------------------gctcttccctcctccatttacaatggtgatgctct
cgtct-------------------------tcaggtcaccgtagcgctatgagcgattcg
agcggggtgtacatcatgcgcaaggcatgtccgtctcaacctcagattttagcaaaatct
aatctgagaacaacgggttatctcgagcccattaaacgaaataccatgcgtcggtgtcct
cggttttccgtagggcttccgattgatacgtaaaatatacttttaagcacgcccgcctac
attgctagacttgacaaaa-------------------cagccatcgttgaacgaa--gt
tggctgtaccgtttcctctgaattcgtctcaactattacgacgagagcaggccgcattca
ta------------------actacacgatcgcatagcctaggactacctgtttctagca
a----------------tatctgcgaaaaccgggtgtatggtatgagcctcgtcgttaag
ctagtaagaagtaccttacgcccaatatatgggacggtaattagcagggttcgaacttcc
cttacgaattattaaaggtgtcagaacgtgtcagggt-----------------------
---------------------tgtcacatcgaatatcgagccagactaagaggtgctaac
aattcttgc----------------tggtacttccgctgtcggataacacaaccctcg--
-------------------cgaacgcacgccccgcatgatttatgccataccaacgcttg
tttgcacaccgcaaggaaggttagctcgagccccaacaaggcaaatggcgctcatcgcca
gaccggaaacgggctagc------------------------------------------
--------cgcttacaatggatgcacatcgtggcccttagtgatagcggaggatcggcgg
ggctgttaacgctcacagtcccgagtgccctcattta---------------------gc
ggatagggttcgtcgtcagagaag
>SEQ5
tgtcgcgcgccagtcgacagaaccgacttagccgtcctccatttacaatggtgatgctca
cttctaggaaaactggagtaattcatggtttcaggtcagcgtagcgctatgatc------
----------------tccgcaaggaatgtccgtatcatcctcagattttagcaaaatct
aatgtgagaacaagggg--ttctcgagcccattaaacgaaataccatgcgtcgctgtcct
cggttttccgtagggcttccgattgatacgtaaaatatacttttaagcacgcccgcctac
atggctagtcttgacaaaa----------------------------caaaacgaa--gt
tggctgtaccgtttcctctaaattcgcaggccgctacggga-------------------
------------------------------------------------------------
-----------------cctctgcgaaaaccggttgtatggtatgagcctcgtcgttaag
ctagtaagaagtaccttacgcccaatatatgggacggtaattagcagggttcgaacttcc
cttacgaatcattaaaggggtcggagcgtgtcagggtggggctaggagcacgtgaggcta
gattcatatcgagtgataatatgtaacgacgcatcgagc--tacacaagaaggtactaac
aattcttgcttatctaatctattaatggcacttccgctg---------------------
---cttaacccatgctagtctcgcgcacgccccgcatgatttatgccataccaacgcttg
tttgcacaccgcaaggaaggttagctcgagccccaacaaggcaaatggcgctcatcgcca
gaccggaaaccgcttaca------------------------------------------
----------------atggatccacatcgtggcccttagtcatagcggggtatcggcgg
ggctgttaacgctcatagtcccgactgccctcatttc---------------------ac
cgatagggttcctcgtcagagaag
>SEQ6
tgtggcgcgccagtcgacagaaccgacatagccgtcctccatttacgatgggggttctca
cttctaagaaaactggagtaattcatggttgcaggccagcgtagcgctatgatc------
----------------tcagcaaggaatggccgtagcatcctctgattttaaccaaatct
actttgagaacatggcg--ttctcgagcccattaaacgaaataccatgcgtcggtgtcct
cggttttccgtagggcttccgattgatacgtaaaatatacttttaagcacgcccgcctac
atcgttagacttgccaaaa-------------------------------cacgaa--gt
tggctgtagcggattctctgcaatcgtctcaactattaggacgaaagtacgccgcaatca
taaatctaacagggccttgaactggacgatcgcttagcctagcactacgtgtttctggca
a----------------tccctgcgaaaaccggtcgtatggtatgagcctcgtcgttaag
ctagtaagaagtaccttacgcccaatatatgggacggtaattagcagggttcgaacttcc
cttacgagtcatcaaaggggttggagcgtgtcagggtggggctaggagcccgtgaggcta
gattcatatcgagtgataatatgtaacgacgcatcgaca--ttcacaagaaggtactaac
aattcttggttatctagtctattaatggcacctccgctg---------------------
---cttaacccatgctagtctcgcgcacgccccgcatgatttatgccataccaacgcttg
tttgcacaccgcaagggaggttagctcgagccccaacaaggcaaatggcgctcatcgcca
gaccggaaacggggtacc------------------------------------------
--------------------------------gcacttagtgttagcggatgatcgcagg
ggttgttagcacccaacttcccgagtgccgtta---------------------------
-------------cggcagacgag
>SEQ7
cgtcga--------------------------attcctcattttacgattggcctgctct
cgttttggaaaacagg-------------------------------------ccagccg
ggctggatgtata----------------------------------------------a
gttccgaccgttaggagttttctcgagcccattaaacgaaataccatgcgtcggtgtcct
cggttttccgtagggcttccgattgatacgtaaaatatacttttaagcacgcccgcctac
atggctagtcattacaaag-----------------------------------ca--gt
tgtctgtaccgtttcctctaaattcacaggccgctacggg--------------------
------------------------------------------------------------
-----------------acctcgcgaaaaccggttgtatggtatgagcctcgtcgttaag
ctggtaagaagtaccttacgcccaatatatgggacggtaattagcagggttcgaacttcc
cttatgagtcatccaaggggttcgagcgtgtcaggctagggctagaagtccgtgaggcta
gatacatatggagtgataatatgtaacgacgcatggaca--ttcacaagaatgtactcac
aattcttggttatcgagtctattaatggcacctccgctg---------------------
---cttaatccatgcttgtctcgcgcacgccccgcatgatttatgccataccaacgcttg
tttgcacaccgcaaggaaggttagctcgagccccaacaaggcaaatggcgctcatcgcca
gaccgctaacgggtcgcctacatcatgacatgatc-------------------------
------tccaccggcaatggctgcacaccctggccttaagggatagcggaggaacggcgg
agctcttcgggctcagcttacagagtgacgttactta-----------------------
--ctcgaggtggtcgtcagaatag
>SEQ8
tgtcgggcgcaattcgacactaccggctttgccgtcctccatttacaatggtgatgctct
cgtctaggaaaacaggagtaatgcatggtttcaggtcagcaaagcgctatgatccatccg
ggctgggtgtacatcgtcctcgaggaatg-------------------------aagact
aatctgagaacaaggggatatctcgagcccattaaacgaaataccatgcgttgctgtcct
cggttttccgtagggcttccgattgatacgtaaaatatactttcaagcacgcccgcctac
ttcgttagacttgccaaaa-------------------------------cacgaa--gt
tggctgtagcggattctctgcaatggtctcaactattaggacgaaaatacgccgcaatca
taaatctaacagggccttgaactgaacgatcgcttggcttagcactaagtgtttgtggca
a----------------tccctgcgaaaaccgggtgtatggtatgagcctcgtcgttaag
ctagtaagcagtaccttacgcccaatatatgggacgataattagcagggttcgaacttcc
cttaagagtcatccagggggttcgagcgtgtcaggctagggct-----------------
-----------cgtgataatatgtaaccacgcatgcaca--ttcccaagaatgtactcac
aattcttggttatcgagtctattcatggcacctccgctg---------------------
---cttaagccatgcttgtctagcgcacgccccgcatgatttatgccataccaaagcttg
tttgcacaccgcaaggaaggttagctcgagccccaacaaggcaaatggcgctcatcgcca
gaccgctaacgggtcgcgtacatcatgacct-----------------------------
-------------------gatctccacactggccttaagggataacggaggaacgacgg
agctcctcgcgcgt----------------------------------------------
---------------------tac
>SEQ9
cgcagg----------------ccagct--------------------------------
-----------------------------------------------------ccagccg
ggctggatgtaca----------------------------------------------a
gttccgaccgttaggagttttctcgagcccattaaacgaaataccatgcgtcggtgtcct
cggttttccgtagggcttccgattgatacgtaaaatatacttttaagcactcccgcctac
attggtagacttgacaaac-------------------cagacatcggtcgacgaa--gt
tggctgtagcgtttcctttgaattcgtctcaactattaggacgagagcaggccggattca
ta------------------------------------------tctacactttctagca
a----------------tatctgcgaaaaccgggtggatggtatgagcctcgtcgttaag
ctagtaagcagtaccttacgcccaatatatgggacgataattagcagggttcgaacttcc
cttacgaatcattcaaggggccggatcgtgtaaaa-------------------aggcta
gat------------------tgttaggactgttggcgg--tagacaagtaggaactaac
aattcttgcttttggaatctcttaatggaatat---------------------------
------------taccgacgtcaagcacgccccgcatgatttatgccataccaacgcttg
tttgcacaccgcaaggaaggttagctcgagccccaacaaggcaaatggcgctcatcggca
gacccgaaactggccact------------------------------------------
------------tacaatgaatccacatcgtggcccttcgtgatagctgaggatcggcgg
ggctgttaccgctcacagtcccgagttccctcatcta---------------------gc
ggatcggtttcgtcgta-------
>SEQ10
ta----------------agtacggactttgccgtcctccatttacaatgatgatgcccc
cgtttaggaaaaccggagtaatgcatggtttcaggtcagcgtagcgctatcatccatccg
ggctgggtgtacttc-------------gtccgtctcatcctcagattttagcaaactct
aatctgagaacaaggagttatctcgagcccattaaacgaaataccatgcgttgctgtcct
cggttttccgtagggcttccgattgatacgtaaaatatactttcaagcacgcccgcctac
ttcgttagtttagccaaaa-------------------------------cacaaa--gt
tgtctgtagcgggttctctgcaatggtcgcaacttttaggaagaaaatacgccgcaatga
taaatctaacaggaccttgaactgaccgatcgcttggcttagcattaagtgttt------
--------------------gtgcgaaaaccggttgtatggtatgagcctcgtcgttaag
ctagtaagaagtaccttacgcccaatatatgggacggtaattagcagggttcgaacttcc
cttacgaatcattaaagggttcggagcgtgtcagggtggggctaggaggtcgtgagccta
gattcatttcgagagataatatgtaatgactcaacaagg--taggcaagtatggactaac
aattcttg-----------------------tacttccg---------------------
---ctcaacccatgcaagtctcgcgcacgccccgcatgatttatgccataccaacgcttg
tttgcacaccgcaaggaaggttagctcgagccccaacaaggcaaatggcgctcatcgcca
gaccacaaacggccagccttcataacgagatgagggggaaaac-----------------
---agatcgaccgatcatggttgcacaccctgg---------------------------
----gttagggctcacattctata----------------------------------gc
agataggggtggtcgttagagtag
>SEQ11
agtc---------------------gctcttccctcctcaatttatactggtgatgcact
agtct-------------------------tcaggtcaccgtagcgctatgagcgattcg
agctgagtgtacataatgcgtaatgcatgtccgtctcaacctcagattttggcaaaatct
aatcggagaacaacgggttatctcgagcccattaaacgaaataacatgcgtcggtgtcct
cggttttccgtagggcttccgattgatacgtaaaatatacttttaagtacgcccgcctac
attggtagacttgataaac-------------------cagacatcggtagactaa--gt
tgactgtagcgtttcctttgaattcgtctcaactatcga---------------------
--------------------------------------ttcctatctacactttctagca
a-----------------tatcgcgaaaaccgggtggatggtatgagcctcgtcgttaag
cgagtaagcagtaccttacgcccaatatatgggacgat--ttagcagggttcgaacttcc
cttacgaatcattaaagtgctcggagcgtgtcaggttggggctaggagctcgtgcgggta
aattcctttcatgcaatagtatctaacgactcatccacg---------------------
---------------aatctattaatggtacttcccctgtcggataacacaaccgacgcg
taccacaatccatgcaaggctcgcgcacgccccgcatgatttatgccataccaacgcttg
tttgcacaccgcaaggaaggttagctcgagccccaacaaggcaaatggagctcatcgcca
gaccgctaacgcgtcttc------------------------------------------
---------accggcaatggttgcacaccctggccttaaggcatagtggacgaacgccgg
agctcttcgggcta--------------------------------------------ct
tactcgaggtggtcgtcagaatag
>SEQ12
cgcagg----------------ccagct--------------------------------
-----------------------------------------------------ccagccg
ggctggatgtgta----------------------------------------------a
gtaccgagcgttaggagttttctcgagcccattaaacgaaataacatgcgtcggtgtcct
cggttttccgtagggcttccgattgatacgtaaaatatacttttaagcacgcccgcctac
atggctagtcttggcaaaa----------------------------caagacgaa--gt
tggctgtaccgtttcctgtaaattcgcacgccgctacggga-------------------
------------------------------------------------------------
-----------------cctcagcgaaaaccggttgtatggtatgagcctcgtcgttaag
ctagtaagaagtaccttacgcccaatatatgggacggtaattagcagggttcgaaattcc
cttgcgaactattaaaggcgttggagcgtgtcagggttgggctagtagcgcgtgaggcta
----------------------------------tgagg--cggacgaataggtactaac
aattctagattaccgaacctattaatggtacttcagctgtcggataacacaaagtacgcg
tacctcaacccatgcaagtcgcgcgcacgccccgcatgatttatgccataccaacgcttg
tttgcacaccgcaaggaaggttagctcgagccccaacaaggcaaatggagctcatcgcca
gacccaaaactgagtact------------------------------------------
---------------------cccacatcgtggcccttcgtgatagctgaggatcggcgg
ggctgtttccgatcacagtcccgagttcta----------------------------ga
ggatcggtttcgtagta-------
>SEQ13
tgtctggcgcaattcgacactaccggtt------------------agtgctgatgctct
cgtctaggaaaacaggggtaatgcatggtatcaggtcagcaaagcgctataatccatccg
ggctgggtgtacatcgtcctcgaggaatg-------------------------aagacg
aatctgagaacaagtggatatctcgagcccattaaacgaaataccatgcgtcggtgtcct
gggttttccgtagggctaccgattgatacgtaaaatatacttttaagcacgcccgcctac
attgctagacttgcca----------------------------tcgttgcacgaa--gt
cggctgtacagtttcctctgaattcgtctcaactatcccgacgagagcagaccgcattca
ta------------------actacacgagcgcataccctaggcctagctatttctatca
a----------------tatctgcgaaaaccgggtgtatggtatgagcctcgtcgttaag
ctagtaagaagtaccttacgcccaatatatgggacggtaattagcagggttcgaacttcc
cttacgaatctttaaagggttcggagcgtattagggtcgggctagcaggtcgtgagccta
gattcatttcgagagataatatgtaatgactcaacatgg--aaggcaagtatggattaac
aatcct------------------------------------------------------
------------tgcaagtcgcgcgcacgcccggcatgatttatgccatacctacgcttg
tttgcaccccgcaaggaaggttagctcgagccccaacaaggcaaatggcgctcatcgcca
gaccgggaacggggtacc------------------------------------------
--------------------------------gcacttcgtgttagcgggtgatcgcagg
gcttgtcgg---------------------------------------------------
----------------cagacggg
>SEQ14
tgtggctcgcgagtcgacagaacagacatagacgtcgtccctttacgatgggggatctca
cttcgaaaaaaactagactaattcatggttgcaggccaacgcagcgctatgatc------
----------------tcagcaaggaatggccgtagcatcctctgattttaacaaaattt
actttgagaacatggcg--ttctcgagcccattaaacgaaataccatgcgttgctgtcct
cggttttccgtagggcttccaattgatacgtaaaatatactttcaagcacgcccgcttac
atcgttagactagccaaaa-----------------------------------------
----catagcggattctgt----------------------------------gcaatca
taaatctaagagggccttgcactggacgattgcttagcgtaacactacgtgtttctggca
a----------------tccctgcgaaaaccggttgtatggtatgagcctcgtcgttaag
ctagtaagaagtaccttacgcccaatatatgggacggtaattagcagggttcgaacttcc
cttacgtattattaaaggcgtcggagcgtcccagggttgggctaggagctcgtgcggcta
gattcaattcgagagatcgtatgtaaagactcatcgagg--cagactaatcgggagtaac
aattctaacttacccaacctattaatggtatttcagcagtcggatcacacaacctacgcc
tacctcaacttatgcaagtcgcgcgcacgccccgcatgatttatgccataccaacgcttg
tttgcacaccgcaaggaaggttagctcgagccccaacaaggcaaatggcgctcatcgcca
gaccgtaaacggggtacc------------------------------------------
--------------------------------gcgctttgtgttagcggatgatcgcagg
ggtttttaccaaccaacgtcccaagttccgtta---------------------------
----------------cggcagac
>SEQ15
tgtctcgcgccagtcgacagaaccgactaaaccgtcctccatttacaatggtgatgctcg
cttctaggaaaactggagtaattcatggt---------------cgctatgatc------
----------------tcagcaaagaa------------------------gcaaaatct
aatgtgtgaaaaagtgg--ttctcgagcccattaaacgaaataccatgcgtcggtgtcct
cggttttccgtagggcttccggttgatacgtaaaatatacttttaagcacgcccgcctac
attgccagactcagtagca-----------------------------------aa----
-------------------gtgttgccctgaagtattaggccgaggctaggcctctatca
taaatctaagtga---------------------tagcccctcaccacctctatctggcg
atatcgactcgatctacccgctgcgaaaaccggttgtatggtatgagcctcgtcgttaag
ctggtaagaagtaccttacgcccaatctatgggacggtaattagcagggttcgaacttcc
ctcccgcatcattaaagtcctcagaacgtgtcaggttggggctaggaactcgtgcgggta
aattctttt---------------------------------------------------
--------gctgccgaatctattaatggaacattccctgtctgataacccaaccgacgca
taccacaatccatgcaaggctcgcgcacgccccgcatgatttatgccataccaacgcttg
tttgcacaccgcaaggaaggttagctcgagccccaacaaggcaaatggagctcatcgcca
gaccggaaacgggctagc------------------------------------------
--------cgcttacaatggatgcacatagtggccctaa--------------------g
ggctgttaacgcacacagtcccgagtggcgtcattta---------------------gc
tgacagagttcgtcctcacagaag
>SEQ16
agtctggcgcaattcgacactaccgatt------------------agtgctgatgcatt
cgtctaggagaacaggggtaatgcatgatatca---------------------------
--------atccatcctcctcgaggaatg-------------------------aaggcg
aatctgagaacaagtggatatctcgagcccattaaacgaaataacatgcgtcggtgtcct
cggttttccgtagggcttccgattgatacgtaaaatatacttttaactacgcccgcctac
actggaagacttgacaaac-------------------cagtcatcggacgacgaa--gg
ttgctgtagcgtttcctttgcattcgtctcaaatattaggacgagagcaggccg------
-----------------------------------------------gcactttcttgca
a----------------tatctgcgaaaaccgggtggatggtatgagcctcgtcgttaag
cgagtaagcagtaccttacgcccaatatatgggacgat--ttagcagggttcgaacttcc
cttacgaattattaaaggtgccgcagcgt-------------------ctcgtgaggcta
gatgcaattcgagagatagtatgtagcgactcatcgagg--catactaatcggaacttac
aat-----------------attaatggtacttcagatgtcggataagacaacctacacg
tacctcaacccattcaagtcgcgcgcacgccccgcatgatttatgccataccaacgcttg
tttgcacaccgcaaggaaggttagctcgagccccaacaaggcaaatggcgctcatcgcca
gaccgctaacgggtggcggacatcatgacct-----------------------------
-------------------gatctccccactggccttgagggattacggaggaacgacgg
agctcctcgcgcgt----------------------------------------------
---------------------tac
>SEQ17
agtctggcgcaattctacacaaccgatt------------------aggggtgatgcatt
cgtctaggagaacatgggtaatgcatgatataa---------------------------
----------------tcctcgaggaa---------------------------------
-----ggaaccatgtggatatctcgagcccattaaacgaaataccatgcgtcggtgtcct
gggttttccgtagggctaccgattgatacgtaaaatatacttttaagcacgcccgcctac
actggaagacttgacaaac-------------------cagtcatcggacgacgaa--gg
atgctgtagcgttgcatttggattcgtctcagatattaggacgagcgcaggccggaa---
--------------------------------------------------ctttcttgca
a----------------aatgtgcgaaaaccggtcgtatggtatgagcctcgtcgttaag
ctagtaagaagtaccttacgcccaatatatgggacggtaattagcagggttcgaacttcc
cttccgaatcagtaaagggttcggag-----------------aggaggtcgtgagccta
gattcatttcgagagataatatgtaatgactcaacaagg--taggcaagtatggactaac
aattcttg-----------------------tacgaacg---------------------
---ctcaacgcctgcaagtctcgcgcacgccccgcgtgatttatgccataccaacgcttg
tttgcaccccgcaaggaaggttagctcgagccccaacaaggcaaatggcgctcatcgcca
gaccgtaaacgggttacc------------------------------------------
--------------------------------gcgctttgtgttagcggttgatcgc---
-----------------gtcccaagttccgtta---------------------------
----------------cggcagac
>SEQ18
agtctg----------------------------------------aggggtgatgcatt
cgtctcggagaaaatgggtaatgcatgaattaa---------------------------
----------------tcctcgagaaa---------------------------------
-----ggaacaatgaggatatctcgagcccattaaacgaaataccatgcgttgctgtcct
cggttttccgtagggcttccgattgatacgtaaaatatactttcaagcacgcccgcctac
attggaagacttgataaac-------------------cagacttcggtagactaa--gt
tgactgtagcgtatccttgattcctatct-------------------------------
-----------------------------------------------acactttctaaca
a-----------------tatcgcgaaaaccggtcgtatggtatgagcctcgtcgttacg
ctagtaagaagtaccttacgcccaatatatgggacggtaattagcagggttcgaacttcc
cttacgaattattaaaggtgtcagaacgagtcagggt-----------------------
---------------------tgtcacatcggatatcgacccacactaaggggtgctaac
aattcttg-------------------------ctgctgtcggataacacaaccctcg--
-------------------cgaacgcacgccccgcatgatttatgccataccaacgcttg
tttgcacaccgcaaggaaggttcgctcgagccccaacaaggcaaatggcgctcatcggca
gaccgctaacgggtggcggacatcatgacct-----------------------------
-------------------gattgccccactggccttgagggattacggaggaactt---
------------------------------------------------------------
---------------------tac
>SEQ19
cgtagggcgcacctcaaaagtaccaactgtgcattcctccttttacaatgggca------
-------------acgtgccatgcttggtctcac-------------------ctagccg
ggctggatgtagttggtccgacaaggaagtcctt--------------------------
--------------gagttttctcgagcccattaaacgaaataccatgcgtcggtgtctt
cggttttccgtagggcttccgattgatacgtaaaatatacttttaagcacgcccgcctac
atggctagtgttggcaaaa----------------------------caagacgtg--gg
tgcctgtgccgtttcctc-------------accttcggg--------------------
------------------------------------------------------------
-----------------accacgcgaaaaccgggtgtatggtatgagcctcgtcgttaag
ctagtaagaagtaccttacgcccaatatatgggacggtaattagcagggttcgaacttcc
cttacgattcattcaagtgaccggagcgtgtcaggttggggctaggagctcgtgcgggaa
aattcctttcatgcaatagtatctaacgactaatccacg---------------------
---------------aatctataaagggtacttcccctgtcggataacccaaccgacgcg
taccacaatccatgcaaggctcacgcacgccccgcatgatttatgccataccaacgcttg
tttgcacaccgcaaggaaggttagctcgagccccaacaaggcaaatggcgctcatcggca
gacccaaaactgagtact------------------------------------------
---------------------cccacatcgtggcccttcgtgatagctgaggatgagcgg
ggctttttccgatcacagtcccgagttcta----------------------------gt
ggatcggtttcgtagta-------
