>SEQ0
cagcggagcgcttagtactcaatctgcaacaccacccttacttgattaacagtgctttga
cctcgagtcggcaccacatagtccgaactaattgtgggagcatggtatcttacggtgagt
cgcgaaaggccagatcaccggtccaattcactcctgagcacgagcctcaaaacattatgt
agtcggccgacatcttagagtactggactcatgagtagccaatgttcaatccggcgatcc
ggttttgcacgatacgttccttggcggtctcgtcttgcttctcattgttggtacgtagcc
ctatctagcgctggggatgaccatcaggatgcgtatcccaatttgtcttgaccagtcccg
gtcgtacttattacgaacgcagtaatttggagcaaccgaaggtcaggcgatatacaaaaa
aacgcgaactacgcctacatattgaacggttgccttaatattacgaggtgtggaaccaac
tcaccttaccccctctaacattggtcatctggcatcacgccctcgggacgatcgcacctt
ataacaaggcttgctaacagggcttaggatggtagtacaagtgcaagtctacacgtaggt
ttccggtacgtcttactgcccacgcacgggagcaaaatcataggaaaaaagtctgctagt
ctcttcttctctccagattagtcctaaagccgaaaacgacagacgtgttggataccaccc
actatctgctgttgcctccatgaccgtactctactgacaggccacagagcgagtactacg
tatcgcttcagtatcccagctcactctcgaggtgccgttagtattgtgaagttcgtgtaa
aatagatcgccccgaaagttatcaatctgcttcataagcgctctacttgaggcatgtcga
cgtgcagcgccaggccccagatcacgtaaatcgattatattaaaccgtgcggcccaaagg
gctgcacagaccagatgcctgggcatgtaggttattcctggaatctgcgtgataggcttg
agactgtttgaattatctccctttggttcctcaatgtgtagtaattggatatttataacg
tgacgacagcaccagcgtaa
>SEQ1
caggggagcgcttagtactcaatctgcaacaccacccttacttgaactacagtgctttga
cctcgagtcggcaccacatagtccgaggtaattgtgggagcatggtagcttacggtgagt
cgcgaaaggccagatcacgggtccaattcacacctgggctcgcgcc--------------
------------tcttggagtactggactcatgagtagccaatgttcaatccggcgatcc
ggttttgcacgatacgttccttggcggtctcgtcttgcttctcattgttggtacgtagcc
ctatcaagcgctggagatgaccatgaggatgcgtatcccaatttgtcttgaccagtcccg
gtggtacttattacgagcgcagtaatttggagcaaccgaaggtcaggcgatatacaaaaa
aatgcgtactgca---------------------ttaatgttacgaggtgtggaaccaac
tcacgttaccccctcagacattggtcatctggcatcacgccctcgggacgatcgcacctt
ataacaaggcttgctaacagggcttaggatggtagtacaagtgcaagtctacacgtaggt
ttccggaacgtctcactgcccacgcgcgcgagcaaaatcaaaggaaaaaagtctgctagt
ctcgtcttctctccagattagtcctaaagcagaaaacgacagacgtgttagataccgccc
actatctgctgttgcctc---------------------ggtcacagagcgagta-----
-------------------ctcactctcgaggtgccgttagtattgtgaagttcgtgtaa
aatagatcgccccgaaagttatcaatctgcttcataagcgctctacttgaggcatgtcga
cgtgcatcgccaggccacagaccacgtcaatcgattatattaaaccgtgcggcccaaagg
gctgcacagaccagatgcctgtgcatgtacgttattcctggaatctgcgtggtaggctag
agactgttcgaattatctccattt------------------------------ataacg
tgacgacagcaccagcgtaa
>SEQ2
cagggg---------------------agcaccaccattacttgaactacagtgctttga
cctcgtgtcggcaccacgtggtccgaggtaattgtgggagcctggtagcttacggtgagt
cgctaaaggccagatcacgggtcccactcacccctgggctcgcgcc--------------
------------tcaaggagtactggactcatgagtagccaatgttcaatccggcgatcc
ggttttgcacgatacgttccttggcggtctcgtgttgcttctcattgttggtacgtagcc
ctatcaagcgctggaaatgaccatgaggatgcgtatgccacgttgtcttcaccagtgccg
gtggtacttattacgagcgcagtaat---------------gtcaggcgaaatacaaaaa
actgcgtactgca---------------------ttaatgctacg---------------
------taccccctcagtcattggtcatctggcatcacgccctcgggacgatcgcacctt
ataacaaggcttgctaacagggcttaggatggtagtacaagtgcaagtctacacgtaggt
ttccggtacgtcttactgccctagcacgggagcaaaatcataggaaagaaggctgctagt
ctctt----------------------acccgaaaacgacagacgtactggataccaccc
actatctgctgttgcctc-------------tacttacaggccacagagcgagtactccg
tatcgcttcagtatcccagctcactctcgaggtgccgttagtattgtgaagttcgtgtaa
aatagatcgacccgaaagttatcaatctgcttcataagcgctctacttgaggcatgtcga
cgtgcatcggccggctacagaccacgtcaatcgtttatattggtgcacagaccagag---
------------------------tggtaggctaatttagaaagtg--------------
------------------------------------------------------------
--acgacagcaccagcgtaa
>SEQ3
caaggg---------------------agcaccaccgttagttgaactacagtgccttga
cctcgtgtcggcacgacgttgtccgaggtaattgtgggagcctggtagcttacagtgagt
cgctaaaggccaggtta----------------------tcgcgcc--------------
------------tcaagaagtactggactcatgagtagccaatgttcaatccggcgatca
ggttttgcacgatacgttccttggcgttctcgtcttgcttctcattgttggtacgtagcc
ctatctagccctggggatgaccatcaggccgcgtatcccagtttgtcttgaccattcccg
gtcgtacttattatgaacgcaataatttggagcaaccgacggtcaggcgatatacaaaaa
aactcgaacaacgcctacatattgaaaggttgcctaaatattacgaggtgtggaaccaac
ccaccttaccccctcgacaatttgtcatctggcatcgcgccctcgggacgatcgcacctt
ataacaaggcttgctaacagggcttaggatggaagtacaagtgcaagtctacacgtaggt
ttccggtacgtctgaccgccctagcacgagagcaaaatcataggaaagaaggctgatagt
ctctt----------------------------------------aactggataccactc
agtatctgatgttgcctc-------------tacttacaggccacagagcgagtaatccc
tatcgctctactatcccagctcactctcgaggtgccgttagtattgtgaagttcgtgtaa
aatagatcgccccgaaagttatcaatctgcttcataagcgctctacttgaggcatgtcga
cgtgcagcgccataccccagatcacgtaaatcgattatattaaaccgtgcggcccaaagg
gcttcacagaccagatgcctgggcatgtaggttactcctggaatctgcgtgataggcttg
agactgtttgaattatctcgctttggatcctcaatgtgtt--------------------
--acggcatctcc-------
>SEQ4
cagggg---------------------agcaccaccattatttgaacttcagtgctttga
cgtcgtgtcggcaccacgtgggccgaggtatttgtgagagc-------------ctgagt
cgctaaaggccatatcacgggtccc-----------------------------------
------------acaaggagtactggactcatgagtagccaatgttcaatccggcgatcc
ggttttgcacgatacgttccttggcggtctcgtcttgcttctcattgttggtacgtagcc
ctatcaagcgttggagacgaccatgtggatgcgtatcccaatttgtcatgaccagtccca
gagatacttattacgagcgcaggaatttggagaaaccgaaggtcaggcgaaatacaaaaa
aaggcgtaccgca---------------------ttattgttacgtggtgtggaaccaac
tc------------------tttgtcatctggcatcgcgccctcgggacgatcgcacctt
ataacaaggcttgctaacagggcttaggatggaagtacaagtgcaagtctacacgtaggt
ttccggtacg--------------cacgggagcaaaatcataggaaacaagtttgatggt
ctcttcttctcaccagatcagtcctaa------------------cgccgaaaaccaccc
accatctgctgtcgcctcgatgaccgtactcaactgacaggccacagagcgagaactacg
tatcgcttcagtatcccggctcactctcgaggtgccgttagtattgtgaagttcgtgtaa
aatagatcgccccgaaagttatcaatctgcttcataagcgctctacttgaggcatgtcga
cgtgccgcgccataccccagatcacgtaaatcgattatattaaaccgtgtggcccaaagg
gc----------------------atgtaggttactcctggaatctctgggatagtcttc
agactgtttgaattagctcgctttgaatcctcaatgtgtt--------------------
--acggcatctc--------
>SEQ5
caaggg-----------------------------ccttagttgaactat----------
--------------------gtccgaggtaattttgg-------------------gaga
ctctaaatgccaggttaccc----------------------------------------
------------acaagaagtactggactcatgagtagccaatgttcaatccggcgatca
ggttttgcacgatacgttccttggcgttctcgtcttgcttctcattgttggtacgtagcc
ctatgaagcgttggggacgacgatg---------------atttgtcatgtccagtccca
gagatccttattacgagtgcaggaatgtggggaaacctaaggtcaggcgaaatacaaaaa
aaggcgtaccgct------------------------------------gtggtaccaac
tc------------------ttggtcatctggcatcacgccctcgggacgatcgcacctt
ataacaaggcttgctaacagggcttaggatggtagtacaagtgcaagtctacacgtaggt
tttcggtacggctccctgcccacgcgcgcgaacaaaatcaaaggaaaaaagtctgctagt
ctcgtcttct----------------aagcagaaaaggacagacgtgttagacaccggcc
actatgtgctgttgcctc---------------------ggtcacagatcgagta-----
-------------------ctcactctcgaggtgccgttagtattgtgaagttcgtgtaa
aatagatcgccccgaaagttatcaatctgcttcataagcgctctacttgaggcatgtcga
cgtgc--------------gagaacgtccatcaactatataaaaacgtgcggcccgaagg
gcttctatgaccagatgcgtgttcttgtacgttattcccggaatcggcgtggtaggctag
agactgctcgaattatctccattt------------------------------ataatg
tgacgacagcaccagcgtaa
>SEQ6
cagaat------------------------------------------------------
----------------------------------------------------ttgtgagt
cgcgaaaggccatatcgcgggtccc-----------------------------------
------------acaaggagtactggactcatgagtagccaatgttcaatccggcgatcc
ggttttacacgatacgttccttggcggtctcgtcttgcttctcattgttggtacgtagcc
ctatcaagctctggagatgaccatgaggatgcgtatcccaatttgtcttgaccaggcccg
gtggtactt-------------------ggaggaaccgaaggtcaggcggtatacaaaaa
aatgcgtactgca---------------------ttaatgttacgaggtgtggtctcaac
tc-----------------attggtcatctggcatcacgccctcgggacgatcgcacctt
ataacaaggcttgctaacagggcttaggatggtagtacaagtgcaagtctacacgtaggt
ttccgggacgtc--------------------caaaatcataggaaagatggcggatagt
ctctt----------------------------------------aactggataccactc
-------------------------------tacttacaggacacagagcgactaatccc
tatcgctctactatcccagctcactctcgaggtgccgttagtattgtgaagttcgtgtaa
aatagatcgccccgaaagttatcaatctgcttcataagcgctctacttgaggcatgtcga
cgtgcagcgccgggccccagatcacgtaaatcgattatattaaaccgtggggcgaaaagg
gctgcagagaccagctgcctgggcatgcaggtttttcctgaaatctgcgtgataggcttg
agactatttgaattttctccctttggttcctcaattattt--------------ataccg
tgacgacagcaccagcgtca
>SEQ7
cagtac------------------------------------------------------
----------------------------------------------------ttgtgcgt
cgagacaggccatatcgcaggtcc------------------------------------
------------ccacggagtactggactcatgagtagccaatgttcaatccggcgatca
ggttttgcacgatacgttccttggcgttctcgtcttgcttctcattgttggtacgtagcc
ctatcaagcgctggagatgaccatggggatgcgtatcccaatttgtcttgagctgttccg
gtggtacttattacgagctcagtaatttcgagcaatcgaaggtcaggcgatatacaaaaa
aatgagtactgca---------------------ttaatgttacgaggtgtagaaccaac
tcacgttaccccctcagacatttgtcatctggcatcgcgccctcgggacgatcgcacctt
ataacaaggcttgctaacagggcttaggatggaagtgcaagtgcaagtctacacgtaggt
ttttggtagcgctccctgcccacgcgcgcgaaaagcggttaagga---------------
------------------------------------------------------------
----------------tc---------------------gggcacagatcgagta-----
-------------------ctcactgtcgaggtgccgttagtattgtgaagttcgtgtaa
aatagatcgccccgaaagttatcaatcttcttcataagcgctctacttgaggcatgtcga
cgtgccgcgc------------------aatcgattagattaaaccgtgtggcccaaagg
gc----------------------atgtaggttacacctggaatctctgggatagtcttc
agactgtttgaatcctcaat----------------------------------------
--gcggcatctc--------
>SEQ8
cagggc---------------------agcaccaccattacttgaactacagtgctttga
cctcttgttg----------------ggtaattgtgggagcctggtagcttacggtgggt
cgctaaaagccagatcatgggc-----------------tctcgcc--------------
------------gcaaggagtactggactcatgagtagccaatgttcaatccggcaattc
ggttttgcacgatacgttccttggcggtctcgtcttgcctctcattgttggtacgtagcc
ccatcaagcgctggaaatgaccttgaggttgcgtatgccacgttggtttcaacagtgccg
gtggtactcattacgagcgcagtaat--------------------gcgaaatacaaaaa
actgcgttgtgca---------------------ttaatgctacc---------------
------taccccctcagtcattggtcatctggcatcgcgccctcgggacgatcgcacctt
ataacaaggcttgctaacagggcttaggatggtagtacaagtgcaagtctacacgtaggt
ttccgtaacgtctcactgccaccccgcgagagcaaaatcaaaggaaaaaagtttgataag
gattt---------------gtcctaaagcagacaacgacagacgtgtttgatacctcct
actatttggtgttgcctc---------------------gctcacagagcgagta-----
-------------------ctcactgtcgaggtgccgttagtattgtgaagttcgtgtaa
aatagatcgccccgaaagttatcaatcttcttcataagcgctctacttgaggcatgtcga
cgtgctggcccaaa----------------------------------------------
--------------------ggacatgtaggttactcctggaatctctgggatagccttc
aa-----------------gctttgaatcctcaatgtgtt--------------------
--accgcgtgtc--------
>SEQ9
catggg---------------------aggaccaccattatttgcacttcagtgctttga
cgtcgtgtcggcaccgcgtgggcccaggtttttgtgagagc-------------ctgagt
cg----------------------------------------------------------
------------ctatggagtactggactcatgagtagccaatgttcaatccggcaattc
ggttttgcacgatacgttccttggcggtctcgtcttgcctctcaatgttggtacgtagcc
ctatcaagcgtttgagacgaccatgtggacgcgtatgccaatgtgtcctgaccagtcaca
gagatacttattac---------------gagtaaccgaaggtcaggcgaaatacaaaaa
caggcgtatcgca---------------------ttattgttacgtggtgttgaaccaac
tc------------------tttgtcatctggcatcgcgccctcgggacgatcgcacctt
ataacaaggcttgctaacagggcttaggatggaagtacaagtgcaagtctacacgtaggt
ttccggtacgtctaactgcactcgcacgggagcaaaatcataggagaaaagtctgctagt
ctcttcttccctccagattaatcctaaggccgataacgaaagacgtgttggattccaccc
actatctgctgctgcctccatgaaagt------------acccacagagcgaagagtacg
tatcgcttgagtgtccaag-tcactctcgaggtgccgttagtattgtgaagttcgtgtaa
aatagatcgccccgaaagttatcaatctgcttcataagcgctctacttgaggcatgtcga
cgtgccgctccataccccagatcacgtaaatcgattat----------------caaagg
gc----------------------atgtaggttacgtct---------------------
-----------------tcagattgaatgctcaatgtgtt--------------------
--acggcaactc--------
>SEQ10
cagaat------------------------------------------------------
----------------------------------------------------tcctgagt
cgcgtaagggtctaacgcgggtccc-----------------------------------
------------tcaaggagtactggaatcatgagtagccaatgttcaatccggcaattc
ggttttgcacgatccgttccttggcggtctcgtcttgcctctcattgttggtacgtagcc
ctatcaagcgctggagatgaccatgaggatgcgtagcccaatttgtcttgacccgtcccg
gtggtacttattacgagcgcagtattttggagcaaccgaaggtcaggcgatatacaaaaa
aatgcgtactgca---------------------ttattgttacgagatgtggaactaac
tcacatgaccccctcagacattggtcatctggcatcacgccctcgggacgatcgcacctt
ataacaaggctggctaacagggcttaggatggtagtacaagtgcaagtctacacgtaggt
ttccgttacgtcttactgccctagcac-------------------agaaggctgcttgt
ctctt----------------------accccatgacgacagacgtactggataccaccc
actatctgctgtcgcctc-------------tgcttacaggccaaagagcgagtattccg
tatcgattaagtatcccggctcactctcgaggtgccgttagtattgtgaagttcgtgtaa
aatagatcgccccgaaagttatcaatctgcttcataagcgctctacttgaggcacgtcga
cgtactggcccaaa----------------------------------------------
------------------------atgtaggttgctcctcgaatctcta-----------
-------------------gctttgaatccacaatgtgtt--------------------
--accgcgtgtc--------
>SEQ11
cagggg---------------------------agcggtcactgctcaacagggctttga
cctcgagtcgtcaacacatagtctgaggtaattgtgggagcatgatagcttacggtgagt
cgcgaaaagccagatcacgggtgcaattcacacctgcgctcgagca--------------
------------tcttggagtactggactcatgagtagccaatgttcaatccgtcgatca
ggttttgcacgatacgttccttggcgttctcgtcttgcttctcattgttggtacgtagcc
ctatcaag-------------cataagcatgcgtatgccaagttgtcttcaccagcgccg
gtggtacttattacgaccgcagtatt---------------gtcaggcgaaatacaagaa
actgcgtactgaa---------------------ttagtgctacg---------------
------taccccct------ttggtcatctggcatcacgcgctcgggacgatcgcacctt
ataacaaggcttgctaacagggcttaggatggtagtacaagtgcaagtctacacgtaggt
ttccggtgcgtctcactgcactcgcacgaaa-----------------------------
-----cttccctacaaattaatcctccggccgataacgagagacgtgttggattccaccc
actatctgctgctgccgt---------------------cgcttgagtgtcaaag-----
--------------------tcactctcgaggtgccgttagtattgtgaagttcgtgtaa
aatagatcgccccgaaagttatcaatctgcttcataagcgctctacttgaggcacgtcga
cgttctgccccaca----------------------------------------------
------------------------atgtaggttgctcctcgaatctctc-----------
------------------------------------------------------------
--acaatgtgtgtc------
>SEQ12
cagaat------------------------------------------------------
------------------------------------------------------------
-------------tcccggggtccc-----------------------------------
------------acaaggagtactggactcatgagtagccaatgttcaatccggcgatcc
ggttttgcacgatacgttccttggcggtctcgtgttgcttctcattgttggtacgtagcc
caagcaagcgctggaaaggaccttgacgttgcgtgtgccaagttggttttaatcgtgccg
gtggtactcattaccagcgcagaaat--------------------gcaagatacaaaaa
actgt------------------------------------------------cattaat
gcaacctaccccctcagtcatttgtcatctggcatcgcgccctcgggacgatcgcacctt
ataacaaggcttgctagcagggcttaggatggaagtacaagtgcaagtctacacgtaggt
ttccgttacgccttagtgccctcgc-------------------taagaaggctgcttgt
ctctt----------------------attccatgacgacagacgtactggataccagcc
gctatctgctgttgccac-------------tgcttacaggccacagagcgagtattccg
tatggattaagtatcccgcctcactctcgaggtgccgttagtattgtgaagttcgtgtaa
aatagatcgccccgaaagttatcaatctgcttcataagcgctctacttgaggcatgtcga
cgtgcatcggacggctacagtacacgtcgatc----------------------------
------------------------gtggtggccagtacagaagtg---------------
------------------------------------------------------------
--acgacagtaccagcgtaa
>SEQ13
caggggggcggttagtactcaatctgcaacacctccctttcttgaactacagtgctaaga
cctcgagacggcaccacatagtccgaggtaattgtgggagcatgctagcttacggtgagt
ggcgaaaggccaaatcacgggtccaattcatacctgcgctcgcgcc--------------
------------ccttcgagtactggactcatgagtagccaatgttcaatccggcgatca
ggttttgcacgatacgttccttggcgttctcgtcttgcttctcattgttggtacgtagcc
ctatcaagcgctggagatgaccatgatgatgcgtatcccaatttgtcttgaccagtccgg
ctggtacttgttacgagcgcagtaatttggagcaaccgaaggtcaggcaatatccaaaat
aatgcgtagagca---------------------ttagtgttacgaggtgttgaaccagc
tcacgttaccccctcagaaattggtcatctggcatcacgccctcgggacgatcgcacctt
ataacaaggcttgctaacagggcttagcatggtagtacaagtgcaagtctacacgtaggt
tttcggtaggtgttactgccctagcacaggagaaaaatgataggaa--------------
---------------------------agccgaaaacgacagacgtacttgataccaccc
actagcttctgttgcctc-------------tacttacaggccaaagagcgagtactcgg
tatctcatcagaatcccagctctctctcgaggtgccgtgagtattgtgaagttcgtgtaa
aatagatcgccccgaaagttatcaatctgcttcataagcgctctacttgaggcatgtcga
cgtgccgcgccataccccagatcgcgtaaatcgtttatattaaacagtgtcgaccaaagg
gc----------------------atgtaggttactgctggtatctccgggatattcttc
-------------------------------caatgtgat--------------------
--acggcatctc--------
>SEQ14
caaggg---------------------tgcaccaccgttagttgaactacagtg------
---------------acgttgtccgcggtaattgtaggcgcctgctagcttacagcgagc
cgctaaaggccaggttacgcgcctc-----------------------------------
--------------------tactggactcatgagtagccaatgttcaatccggcgatcc
ggtttagcacgatacgttccttggcggtctcgtcttgcttctcattgttggtacgtagcc
ctatccagcgctggggatgtccatcagggtgcgtatcccaatttgtcttgaccagtcccg
gtcctacttattacgaacgcagtaatttggagtaaccgaaggtcacgcgatatacaaaaa
aa---------------------------------caatactacgaggtgtggaaccaac
tcaccttaccccctctaacattggtcatctggcatcacgccctcgggacgatcgcacctt
ataacaaggctggctaacagggcttaggatggtagtacaagtgcaagtctacacctaggt
ttccgttacgtctcagtgccacacagcgagagcaaaatcaaaggaaaaaggttggataat
cct------------------------------------------tgtttgataccacct
acttttaggtgtttcctc---------------------gctcacagagcgggta-----
--------------------tcactctggaggtgccgttagtattgtgaagttcgtgtaa
aatagatcgccccgaaagttatgaatctgcttcataagcgctctacttgaggcatgtcga
cctgccgctccatactccagatcacgtaaatcgcgaac----------------------
---------------------ggcatgtaggatac-------------------------
-----------------------cgaatgctcaatgtgta--------------------
--acgg--------------
>SEQ15
gagatt------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------cccgggggtactggactcatgagtagccaatgttcaatccggcgatcc
ggttttgcacgatacgttccttggcggtctcgtgttgcttctcattgttggtacgtcgcc
ctatcaagcgcaggaggtaattaacatgatgcgtatcccaatttttcttgaccagtccgg
ctcgtactagttacaagcgcagtcatttggagcaaccgaatgtcaggcaatatccaatat
aatgcgta---------------------------------------gagttgaaccagc
tcacgttaccccatcagaaattggtcatctggcatcacgccctcgggacgatcgcacctt
ataacaaggctggctaacagggcttaggatggtaggacaagtgcaagtctacacctaggt
ttcgggtgcgtctggaaactaccctacaaat-----------------------------
---------------------------------------tagaggtgttggactccaccc
actatctgctgctgcagg---------------------------agtgcta--------
-----------------aactcactctcgaggtgccgttagtattgtgaagttcgtgtaa
aatagatcgccccgaaagttatcaatctgcttcataagcgctctacttgaggcatgtcga
cgtgcatcgggcggctacagaccacgtcaat-----------------------------
---------gtgcacagaccagagtggtaggctaatttagaaagtt--------------
------------------------------------------------------------
--acgacgggaccag-----
>SEQ16
cagatt------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------cctgggggtactggactcatgagtagccaatgttcaatccggcgatca
ggttttgcacgatacgttccttggcgttctcgtcttgcttctcattgttggtacgtagcc
ctacccagcgttggagacgaccatgtggatgcgtatcccaattagtcatgaccagtccca
gag-------------------------------cgcagaggtcaggcgaaatacaaaaa
aaggcgtaccgtg----------------------------------gtgtggaaccaac
tc------------------ttggtcatctggcatcgcgccctcgggacgatcgcacctt
ataacaaggcttgctaacagggcttaggatggtagtacaagtgcaagtctacacgtaggt
ttccgttacgtgtcagtgcaacacagcgagagctaaataaaacgaaaaagcttggataat
c----------------------------------------------cttgataccacct
acttttagatgtttcctc---------------------gctcacagagcgggca-----
--------------------tcactgtccaggtgccgttagtattgtgaagttcgtataa
aatagatcgccccgaaagttatcaatcttcttcataagcgctctacttgaggcatgtcga
cgtgcatggggcggctacagaccacgtcaatg----------------------------
------------------------tggttggctaattcagaaagtt--------------
------------------------------------------------------------
--acaacggg----------
>SEQ17
cagact------------------------------------------------------
-----------------------------------------------------tgtgcgt
cgagacaggccatatcgcaggtcc------------------------------------
------------ccacggagtactggactcatgagtagccaatgttcaatccggcgatcc
ggttttgcacgatacgttctttggcggtctcgtcttgcttctcgttgttggtacgtagcc
cgatcaagcactggagatgaccatgatgatgcgtatcccaatttgccttgaccagtccgg
ctggta------------------------------------------aatatcccaaat
aacgcgtagagca---------------------ttagtgttacgaggtgttgacccagc
tcacgtaaccccctcagagattgctcatctggcatcacgccctcgggacgatcgcacctt
ataacaaggcttgctaacagggcttagcatggtagtacaagtgcaagtctacacgtaggt
ttccgttacgccttagtgccctcac-------------------taagtaggcagcttgt
ctctt---------------------------------------attctggattccagcc
gctatctgct------------------------ttacaggcctcagaccgagtattccg
tatggattaagtatcccgcctcactctcgaggtgccgttagtattgtgaagttcgtgtaa
aatagatcgccccgaaagttatcaatctgcttcataagcgctctacttgaggcatgtcga
ca--------------------------aatcgattagattaatccgtg-----------
-------agaccagatacctgggcatgtaggttattcctggaatctgcgcgaaaggcttg
agactgtttgagttatttccctttggttgctcaatgtgtagtcattggacctttatgacg
tgacgagagcaccagcgtaa
>SEQ18
caggggggccgttagtactcaatttgcaacacccccctttcttgaactgcagtgctaaga
cctcgagacaggatcagataatccgaggtaattgtcggagcatgctagcttacggagggt
cgcgaaaggccaaatcacgggttcaatacatacctgcgctcgcgcc--------------
------------cctacgagtactggactcatgagtagccaatgttcaatccggcgatcg
ggttttgcacgatacgttccttggcggtctcgtgttgcttctcattgttggtacgtcgcc
ctatctagcgatgtgcatgaccatcagcatgcgtatcccaatttgtcttgtccagtcccg
gttgtacttattacgaacgcagttattgggagcaacagaaggttaggctatttacaaaaa
aacgcgaactacgcctacatattgaacggttgcctaaatatttcgaggtgtggaaccaac
tcatcttaccccctctaacattggtcatctggcatcacgccctcgggacgatcgcacctt
ataacaaggctggctaacagggcttaggatggtaggacaagtgcaagtctacacctaggt
tgccggaacgtctcactgcccccgcgcgcgagcaaaatcaaaggaaataagtctgctagt
ctcctcttctctcc--------------------atcgacagacgtgttagataccgccc
attatctgcagttgcctc---------------------ggtcacagagcgagta-----
-------------------ctcactctcgaggtgccgttagtattgtgaagttcgtgtaa
aatagatcgccccgaaagttatcaatctgcttcataagcgctctacttgaggcatgtcga
cctcc-------------------------------------------------------
------------------------atgtaagtta--------------------------
-------------------gctttgaatccacactgcgtt--------------------
--accgcgtgtc--------
>SEQ19
cagggg---------------------agcaccaccattatttgaacatcagtgcttt--
------------------------gaggtatttgtgagacc-------------ctgaga
cgctaaagggcatatcacggg---------------------------------------
------------ccccacaatactggactcatgagtagccaatgttcaatccggcgatca
ggttttgcacgatacgttccttggcgttctcgtcttgcttctcattgttggtacgtagcc
ctatacagcgttggggacgacgatg---------------atttgtcatgtccagtccaa
ga-----------------------------------------caggcgaaatacaaaaa
aaggcgta----------------------------------------------------
--------------caggtattggtcatctggcatcacgccctcgggacgatcgcacctt
ataacaaggcttgctaacagggcttaggatggtagtacaagtgcaagtctacacgtaggt
tttcggtaggagataagg------------------------------------------
-------------------------aaaaccgaaaacgacagaagt--------------
-----------ttgcctt-----------------------------tacgagtactcgg
tatctcatcagaataccagctcactctcgaggtgctgttagtattgtgaagttcgtttaa
aatagatcgccccgaaagttatcaatctgcttcataagcgctctacttgaggcatgtcga
cgtgggtggccagtacagatg---------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--acgacactgccagcgtaa
