>SEQ0
taccctcctgtccagtacgacggtagggcatcccatgttggtctgaatcgcctctattac
tcagggcctcaatgcgacgcaggggaataatacagtacggggcatcccacctccccttgg
ggcgaattgaccattgggcggaaacccttgccattttcagcattaccgcagggtagagac
ttcggtcagctcataccggtgcggaacaccgtccgatccagtattttagttaacgaactt
ccgtctcaagaacacaaggatgtgggtagatcgatactcgaacgtacaggaacgcagtgt
agggctctcggggttccagcgccgcgttgatccctggacgcgcctgggttggtaaaaaca
cgcttatcactaagtaccaaattaggtctaggtatagacgatacccgatggtatcaccgg
gtagagtatctccgcacgtcgtcttattctgccgaatgtaccccgagtgtgattcataaa
tcccacttccctgcattttatacctacgaccaccaggtgatccctgctgcggatgaaaag
aatggagacaacaaggctttctgtaagccagaaagtggagggagaccgcctgtgattgcg
acccttttggaacttgtaaaaagggacagcagaagtctttggctcaacattcttagtgat
gatcgtcataagacttatgcgccgtttcacagaattggtcataaggtatattccgtcccc
tgtcatatggatgggggaacggaaagggacaaaagcactcagctcgtcgcagagtgcgcc
gaagaataaaaatcgcttactaccgtccaggtgcgcaggtcagggctgctcgcggtttag
cataccccatgacactgtacaggctggggaatgcatgacgatatagattaagtactagtc
tgcaggcagctgtttgatccagtgtgtgctttcgacctaaggcaaggagtggcgtgaaga
agactgtatcctgtcacggtgtcgcggattcccgcagctttttactccggccgctcatgg
cagcgtctttacctattgaggcattgcttgagagcacagttagaatgatagcttgtggat
gtttcattgcttttcagtcc
>SEQ1
tacactccagtcaagtacggcggtagggaattgcatgatggtctgtatcgactctattac
tcaggacctcgatgtgatgtatgggaataatccagtacgcgtcatcccacctccccttgg
ggagaatagaacattcggcggaaaccctt-----------------------gcagagac
ttcgatcagctcataccggtgcggaacaccgtccgatccagtattttagttaacgaactt
ccgtctcaagaacacaaggatgtgggtagatcgatactcgaacgtacaggaacgcagtgt
atggctctcggggttccagcgccgcattgatcgctggatgcgcccgggttagtaaaaaca
cgcttatcactaagtacctaattagggctaggtatagacgatacccgatggtatcaccgg
gtagagtatctgcgcacgtcgtctttttctgccgaatgtaccccgactgtgatccataaa
tcccacttccgagcattttatacctacgaccaccaggtgatccctgctgcggatgaaaag
aatggagacaacaaggctttctgtaagccagaaagtggagggagaccgcctgtgattgcg
accctttagtagtctttag-----------------------ctccacattcctagtgat
gatcgtcataagacttatgcgccgattctcagaattagacataaggtatattccgtcgcc
tgtcatatggatgggggaacggaa-------------------tcgtcgcagagtgcgcc
gaagaataaataccccgtactaccgtccaggtgcgcacgtcagggctgctcgcggtttag
cataccccatgacactgtacaggctggggaatgcatgacgatatagattaagtactagtc
tgcaagcagccgtttaatccagtatgt-------------------------ggtgaaca
aaactgtacactgtcacggtatcgcggattcc---------------------ctcatgg
cagcgtctttacctatagtgccattgcttgagagaacagttagaattgcagcttgtggat
gtttcattgcctttcagacc
>SEQ2
tatcctcctgtccagtacgac--------------------------tcgcctc------
------cctgaatgcgacgcaggggaataatacagtaggtggcat---------------
----------ccattgggcggaaacctgtcctattttcagcattaccgcaggg-------
--------------accgctgcggaacaccgtccgatccagtattttagttaacgaactt
ccgtctcaagaacacaaggatgt-------tcgatactcgaacgtacaggaacgcagtgt
atggttctcggggttccagcgccgcattggtcgccggatgcg------------------
---gtatcgctaagtacctaattagggctaggtttagacgatacccgatggtatgaccgg
gtacagtatctgcgcacgtcgtctttttctgccgaatgtaccctgactgtgatccataaa
taccacttccgagcattttctacctacgaccaccaggtgatccctgctgcggatgaaaag
aatggagacaacaaggctttctgtaagccagaaagtggaggaagaccgcctgtgattgcg
aaccttttggaacttgtaaaaaagtagagcagaagtcttt--------------------
-------ataagacttatgcgtcgtttcacagaattggtcatagggtatattccgtgccc
tgtcataaggatgggggaactgcaagggagactagcactcatctcgacgcaaagtgcgcc
taagaataaaaatcgcttagtaccgtccaggtgcgcaggtcagggctgctcggggtttag
cataccccatgacactgtacaggctggggaatgcatgacgatatagattaagtactagtc
tgcaggccgcagtttgtcc------------------------------------gacct
aagctgtatcgtgtcacggtgtcgcggattcccgcagctttttactccggccgctcatgt
cagc-----------------------------gcacagttaaaatgatagcttgtggat
gttttattgcttttcagtcc
>SEQ3
taccctc------------------------------ttggtctggatcgcctataatac
tgagggcggttagg----------------------------------------------
----------------------------------------------cgcggggtagaaaa
ttcggtcagctca-------gcggaacaccgtccgatccagtattttagttaacgaactt
ccgtctcaagaacacaaggatgc-------tcgatactcgaacgtacaggaacgcagtgt
atggttctcgggtcgccggatccg------------------------------------
---gggacactaagtacctaattagggctaggtttagacgatacccgatggtatggccgg
gtccagtatctgcgcacgtcgtctttttctgccgaatgtaccctgactgtgatcgataaa
taccacttccgagcattttctacctacgaccaccaggtgatccctgctgcggatgaaaag
aatggagacaacaaggctttctgtaagccagaaagtggaggaagaccgcttgtggttgcg
accctttagtagtctttag-----------------------ctccacatccctagtaat
gatcg---------------------tctcagaattagacataaggtatattctgtcgcc
tgacatatggattggggaacggaa-------------------tcgtcgcagagtgcgcc
gaagaataaata--------taccgtccaggtgcgcaggtcagggctgctcggggtttag
cataccccgtgaaactgtacaggctggggaatgcatgacgatatagattaagtactagtc
ttcatgcatccgtttaatccagtttgt--------------------------gtgaaca
aaactgtaaactttcacggtatcgcggattcc---------------------ctcatgg
cagcgtcttcacctatcgtgccattgcatgagagaacagttagaattgctgcttttggat
ctttcattgcctttcagacc
>SEQ4
taccctcctgttcagtacgacggtagggcaccccatgttggtctgaatcgcctctattac
tcagggcctcaatgcgatgcaggggaataatacagtacggggcatcccacgtcccctcgg
ggcgaattgaccattggactgagacccctgccattttcagc-------------------
------cagctcatacaggtgcggaacaccgtccgatccagtattttagttaacgaactt
ccgtctcaagaacacaaggatgtgggtagatcgatactcgaacgtacaggaacgcagtgt
atggttctcgtgg-----------------------------------------------
-------cagtgagtacctaattagggctaggtttagacgatacccgatcgtatggccgg
ttccagtatctgcgcaggtcgtcattttctgccgaatgtaccctgattgtgatcgataaa
taacacttcggagcattttctacctacgaccaccaggtgatccctgctgcggatgaaaag
aatggagacaacaaggctttctgtaagccagaaagtggggggacaccgcctgtgattgcg
aaacttttggaccatgtaaaaaagtagagcagaagtcgtt--------------------
-------ataagactgatggttcgtttcacagaattggtcatagggtatattccgtgccc
cgccataaggattggggaacttcaagggag--------------------gaagtgcgcc
taagaataaaaatcgcatagtaccgtccaggtgcgcaggtcagggctgctcggggtttag
cataccccatgacactgtacaggctggggaatgcatgacgatatagattaagtactagtc
tgcaggcagcta---------------------------aggccaggagtggcgtgcaca
agactgtatcctgtcacggggtcgcggattcccgaagctttttactcctggcgctcatgg
caccatctttacctattgcccactt-------------------------------agaa
tgttcattgcttttcagtcg
>SEQ5
tactctccggtccagtacgactgtagggcatcccattttggtctgaatctcctctagaac
tcagggcctcaatgcgacgcaggggaataatacagtacggggcatgccacctccccttgg
ggcgcattgaccattgggcggaaacccttgacattttcagcattaccgcagggtagagac
ttcggtcagctcctaccggtgcggaacaccgtccgatccagtattttagttaacgaactt
ccgtctcaagaacacaaggatgtgggtagatcgatactcgaacgtacaggaacgaagtgt
atggttcgcggggttccagcgccgcattgattgccggatgcg------------------
---gtatcgctaagtacctaattagggttaggtctaggcgatacacgagggtatgaccgg
ggacactatctgcgcacgtcgttgttttctgccgtatttaccctgactgtgatccataaa
tacctcttccgagcattttctacctacgaccaccaggtgatccctgctgcggatgaaaag
aatggagacaacaaggctttctgtaagccagaaagtggagggagaccgcctgtgattgcg
aaccttttggaacttgtcaaaagggacagctgaagtctatggctcaacattcttagtgat
gatcgtcgtaagac-----------------gaattggtcataaggtatagtctgtcccc
tgtcatatggatggaggaacggaaagggacaaaaccactcaggtcgtcgcagagtggccc
gaagaatataaatcacttactaccgtccaggtgcgcaggtcaggggtgctcgcggtttag
cattccccatgacactgtacaggctggggaatgcatgacgatatagattaagtactagtc
ttcacgcatccgtttaaaccagtttgt--------------------------gtgaaca
aaactcc----------------------------------------------ctcatgg
cagcctcttcacctatcgtgccattgcatgagag------------------ttttggat
ctttcattgcctttcagacc
>SEQ6
tactctccggtccagtacga-----------------------tgaatc-----------
------------tgcgacgcaggtgaataatacagtacgggggatgccacctgcccttgg
agcgcatagacccttgggcggaaacccttgacattttcagcattaccgcagggtagagac
ttcggtcagcacctaccg--gcggaacaccgtccgatccagtattttagttaacgaactt
ccgtctcaagaacacaaggatgtgggtagatcgatactcgaacgtacaggaacgcagtgt
atggttctcgggtcgccggatctg------------------------------------
---gggacactaagtacctaattaaggctaggtttagacgatacccgatggtaaggctgg
gtccagtatctgcgcccgtcgtctttttccgcggaatgtaccctgactgtgatcgataaa
aaccacttccgagcattttctacctacgaccaccaggtgatccctgctgcggatgaaaag
aatggagacgacaaggctttctgtaagccagaaagtcgagggagaccgcctgtgattgcg
aaccttttggaactagagaaaaggcttagtgatgatcgtc--------------------
---------------------------------gtaatacataaggtatagtctgtcccc
tcgaatatggatggaggaaaggaaaagaacaaaaccactctggtcgtcgaagagcggccc
gtagaatataaatctcttactaccgtccaggtgcgcaggtcagggctgctcggggtttag
cataccccatgacactgtacaggctggggaatacatgacgatatagattaagtactagtc
taaggccag-------------------------------------gagtggcgggcaca
agactgtatcctgccacgg------------------cttattactcctggggctcatgg
caccatctttacctattgcccactt-------------------------------tgaa
tgttcactgcttttcagtcg
>SEQ7
taccctcctgtccattacgacggtggggcatcccatgttggtctgaatcgcctctactac
tcagggcc-----------------aataatacagcacggggcatcccacctccccttgg
ggccaattgaccattggccggaaacccttgccattttcagcattaccgcagggtagagac
ttcggacagcctataccggtgcggaacaccgtccgatccagaattttagttaacgaactt
ccgtctcaagaacacaaggatgtgggtagatcgatactcgaacgtacaggaaagcagtgt
atggctctcagggtttag----------------------------------taaaaacg
ggcatatcactaagtacct----------------------tacccgatggtttcatc--
------------cgcacgtgatctttttctgccgaatgtacc-----------ccataaa
tcccgcttacgagcattttatacctacgaccaccaggtgatccctgctgcggatgaaaag
aatggagacaacaaggctttctgtaagccagaaagtggagggagaccgcctgtgattgcg
aaact-------------------------------------------------------
agtctctgtacgacttatgcgtcctttcacagaattggtcatagtgtatactccgtgccc
tgtcataaggatggtggaactgcaagggagaccagcactcatctggacgcaaagagcgct
taagaata------------taccgtccaggtgcgcaggtcagggctgctcgcggtttag
cataccccatgacactgtacaggctggggaatgcatgacgatatagattaagtacgagtc
tgcaggcagcta---------------------------agcccaggggtggcgtgctcc
agcctgttgcctgtcacggggtcgcggatacccgatgctttttactcctggcgctcatgg
caccctctttacctagtgccca--------------------------------------
--ttcattgcttctcagtcg
>SEQ8
taccctcctaaccattacgacggcgggacatcccatgttggtctgactcgcctctactac
tcagggtc-----------------aataatacaccacggggcatcccacctccccttgg
tgccaattgaccattggccggaaacccttgccattttcagcattaccgcagggtcgagac
ttcggacagcatataccggtgcggaacaccgtccgatccagtattttagttaacgaactt
ccgtctcaagaacacaaggatgc-------tcgatactcgaacgtacaggaacgcagtgt
ttggttctcgcgtcgccggatctg------------------------------------
---gggaccctaagtacctaattaaggctaggtctagacgatacccgatggtaaggccgg
gaccagtatctgtgcccgtcgtctttttacgagtaatgaaccctgactgtgatctttaaa
aaccacatccgggcattttctacctacgaccaccaggtgatccctgctgcggatgaaaag
aatggagacaacaaggctttctgtaagccagaaagtggagggagaccgcctgtgattgcg
tccctttagtagtctttagctccac-----------------------------------
------------------------attcctagtaatgattatgccccgattctcatcgcc
tgtcatatggatgggggaacggaa-------------------tcgtcgcagagtgcgcc
gatgaataaataccccgtactaccgtccaggtgcgcaggtcagggctgctcggggtttag
cataccccgtgaaactgtacaggctggggaatgcatgacgatatagattaagtactagtc
ttcacgcaaccgtttaagccagtttgt--------------------------tggaaca
aaac--------------------------------------------------------
--gcctcttcacctatcgtgccattgcaagagag------------------ttttagat
ctttcattgactttcagacc
>SEQ9
taccctc------------------------------atggtctggatcgcctctaatac
tgaaggccgttagg----------------------------------------------
----------------------------------------------cgcggggtagaaaa
ttcggtcaactca-------gcggaacaccgtccgatccagtattttagttaacgaactt
ccgtctcaagaacacaaggatgtgggtagatcgatactcgaacgtacaggaacgcagtgt
agggctctcggtattccagcgccgcgttggtccctggacgcgcctgggttggtaaaaaca
cgcttatcaataagtaccaaattagggctaggtatagacgatacacgacggcatcaccgg
gcagagtatc-----------------tctaccgaatgtaccccaagtgtgattcata--
--------------attttatacctacgaccaccaggtgatccctgctgcggatgaaaag
aatggagacaacaaggctttctgtaagccagaaagtggagggagaccgcctgtgattgcg
acccttttccag------------------------------------atccctaggcat
gatcg---------------------tctcagaattagacataaggcatattccgtcgcc
tgacatatggattggggaacggaa-------------------tcgtcgcagagtgcg--
--------------------taccgtccaggtgcgcaggtcagggctgctcggggtttag
cataccccatgacactgtacaggctggggaatacatgacgatatagattaagtactagtc
tgcaggcggcagtttgtcc------------------------------------gtcct
aagcagtatcgtgtcgcggtgtcgcggattcccgcagctttttactccggccgct-----
---------------------------------gcacagttcaaatgacagcttgttgat
cttttattg-----------
>SEQ10
taccctcctgtccagtacgacggcgggccatcccatgttggtctgaatcgcctatactac
tcagggcc-----------------aataataccgcccggggcatcccacctcctcttgg
ggccaattgaccattggccgcaaacccttgccatattcagcattaccgcagggtactgac
ttaggacgg------cctatgcggaacaccgtccgatccagtattttagttaacgaactt
ccgtctcaagaacacaaggatgtgggtagatcgatactcgaacgtacaggaacgcagtgt
atggttcgcggggctccaccgtcacgttggtcggcggaggcg------------------
------------ggtacctagttagggctaggtttagacgataccctatggta-------
----------tgcgcacgtggtctttttatgccgaatgtaccctgactgttatccataaa
tacctcttccaagcattttctacctacgaccaccaggtgatccctgctgcggatgaaaag
aatggagacaacaaggctttgtgtaagccagaaagtggagggaaaccgcctgtgattgcg
acccttgtacag------------------------------------atccatgggcat
gatca---------------------tcaccgaattaggcttaaggcatattccgtcgcc
tgacatatggattggggaacggaa-------------------tcgtcgcagagtgcg--
--------------------taccgtccaggtgcgcaggtcagggctgctcgcggtttag
cacaccccatgacactgtccaggctggggaatgcatgacgatatagattaagtactagtc
tgcaagcagccgcttaatccagtatgt-------------------------cgtgatca
aaactggacactgtcacggtatcgcggatacc----------------------------
-----------gccatagtgccattgcttgtgagaaca----------------------
---tcattgccttccagacc
>SEQ11
taatctccggtcaagtacga----------------------------------------
------------tgcgacgcaggtgaataatacagtacgggggaggccacctgcccttgg
agcgcatagacccttggacggaactctttgatattttctgcaataccgcagggtaaagac
gtcggtcagcacctacc--tgcggaacaccgtccgatccagtattttagttaacgaactt
ccgtctcaagaacacaaggatgtgggtagatcgatactcgatcgtacaggaacgcagtgt
atagttctcgggtcgccggatctg------------------------------------
---gtgacacgaagtacctaattacggccaggtgtagacgatacccgatggtaagactgg
gtccagtatctgcgcccgacgtcgttttacgcggaacctacc------------------
-----cttccgagcattttctacctacgaccaccaggtgatccctgctgcggatgaaaag
aatggagacaacaaggctttctgtaagccagaaagtggaggaagaccgcctgggtttgcg
acccttttggaacttgtaaaatggcagagcagaagtcttg--------------------
-------------cttatgcgccgtttcacaga----------------------ccccc
tatcatatggctgggggtacggaaggggacataagcactcagctcgtcggaaagtgcgcc
gaagaataaaaatcgcttattaccgtccaggtgctcaggtcagggctgctcgcggtttag
cacaccccatgacactgtacaggctggggaatgcatgacgatatagattaagtactagtc
tggaggccgcactttgtcc------------------------------------gacct
aagt-------------------------atcgtcggcctattactccggccgctcaggt
cagc-----------------------------gcacagttaaaattatagcttgtggat
gttttattgcttttcagtcc
>SEQ12
tcatctccggacaagtacga----------------------------------------
------------tgcgacgcaggtgaataatacggtacggggtaggccacctgcgctcgg
------------------------------------------------------atggac
gtctgtctgcgcctacc--tgcggaacaccgtccgatccagtattttagttaacgaactt
ccgtcccaagaacacaaggatgc-------tcgatactagaacgtacaggaacgcagtgt
atggctctcgtgg-----------------------------------------------
-------ccgttagtacctaattagggctagtttt--------------------gccgg
ttccatgatctgcgcaggtcgtcattttctgccgcat-----------------------
------------gcatattctacctacgaccaccaggtgatccctgctgcggatgaaaag
aatggagacaacaaggctttctgtaagccagaaagtggtgggagaccgcctgtgattgag
agccttttgaaacttagaag--------------------------------------tt
gatcgtcataagacttatgcgtcgtttcgctgaattggtcataaggtatgtcacgtcccc
tgtcaaatggatgggggagcggaaagggacaaaagcactaagatcgtcgcagagtccgcc
caagaataacaatcgcttactaccgtccaggtgcgcacgtcagggctgctcgcggtttag
cataccccatgacactgtacaggctggggaatgcatgacgatgtagattaagtactagtc
tccatgcagacgcttaatccagtatgt-------------------------cttgatca
aaactggacacagtaacgatatcacggaaaac----------------------------
-----------gccatagtgcaattgcttgtgaggaca----------------------
---tcaatgccttccagacc
>SEQ13
tcagctccagaca-----------------------------------------------
--------------------aggtgattaatacggtacggggtaggccacctccgctcgg
----------------------------------------------------------tc
gtctgcctgcgcctacc--tgcggaacaccgtccgatccagtattttagttaacgaactt
ccgtctcaagaacacaaggatgt-------ttgatactcgaacgtacaggaacgcagtgt
atggttctcgtgg-----------------------------------------------
-------cagtcagtacctaactagggctggttt---------------------ggcgg
ttccatgatccgcgtcggtcgtgattttctgccgcatg----------------------
--------------------tacctacgaccaccaggtgatccctgctgcggatgaaaag
aatggaaacaacaaggctttctgtaagccagaaagtggagggagaccgcctgtgattgcg
acccttttggaacttgtaaa----------------------------------------
----------------------------------------------------gttccccc
tatcatatgcctgggggtacggacggggccgtaagcactcagct----------------
----aataaaagtcgcctattaccgtccaggtgcgcaggtcagggctgctcgtggtttag
cataccccatgacactgtacaggctggggaatacatgacgatatagattaagtactagtc
ttca--------------------------------------------------------
----------ctggaacagcctc-------------------------------------
---------------------cattgcaagagag------------------tttttgat
ctttcgctgactttcagacc
>SEQ14
taatctccggtcgtgtacga----------------------------------------
------------tgcgacgcaggtgaataatacagtacggg----------------tgg
agcgcatagagc-----------------gatagtttctgaggcaccgcagggtaaagga
cc-----------------tgcggaacaccgtccgatccagtattttagttaacgaactt
ccgtctcaagaacacaaggatgtgggtagatcgatactcgaacgtacaggaacgcagtgt
atggttctcgggtagccgg-----------------------------------------
---aggacgcgaagtacctaatttgggctacgtttagacgattgccgatggtatggccga
ctcgagtatccgcgcaagtcgtctgttgctggcgaaagtacc------------------
----acttgcgagcactttctacctacgaccaccaggtgatcgctgctgcggatgaaaag
aatggagacaacaaggctttgtgtaagccagaaagtggagggaaaccgcctgtgtttgcg
aaccttttggaacttgtaaaaaagtagagcagaagtcttt--------------------
------------------------attcacagagttggtcatagggtatattccgtgccc
tgtcataaggatgggggaaccgcaag----------------------------------
--------------acgcactaccgtccaggtgcgcaggtcagggctgctcggggtttag
cataccccatgacactgtacaggctggggaatacatgacgatatagatttagtactagtc
tggaggccgcactttctcc------------------------------------gacca
aagtattggcgtattactcc----------------------------------------
---------------------------------ggccgctcaaaattatagcttatgtgt
gttttattactattcagttt
>SEQ15
tcagctccagaca-----------------------------------------------
--------------------aggtgattaatacggtacggggtaggccccctgcgctcgg
----------------------------------------------------------tc
gtctgcctgcgcctacca--gcggaacaccatccgatccagtattttagttaacgaactt
ccgtctcaagaacacaaggatgtgggtagatcgatactcgaacgtacaggaacgcagtgt
agggctctaggtattccagcgccgcgttggtccctggacgcgcctgggttggtaaaaaca
cgcttatcaataagtaccaaattacggctaggtatagacgatacacgacggcatcaccgg
gcagagtatctg-----------------taccgtatgtaaaccaagtgtgatt------
-----------aataatttttacatacgaccaacaggtgatccctgctccggatgaaaag
aatggagacaacaaggctttctgtaagccagaaagtggagggagaccgcctgtgattgcg
acctttgtacag------------------------------------atccatgggcat
gatca---------------------ccaccgaattagccttaag---------------
---catgtggattggggaacggaa-------------------tcgtagcagagtgcg--
--------------------taccgtccaggtgcgcaggtcagggctgctcgcggtttag
cataccccatgacactgtacaggctggggaatgcatggcgatatagattaagtactagtc
tgcaagcagccgcttaatccagtatgt-------------------------cgtgatca
aaactgga----------gtatcgtgtagacc----------------------------
-----------gccatagtgccattgctagtgagacca----------------------
---tcattgcctaccagacc
>SEQ16
tactcttcggtccagtacga----------------------ctgaatctcc--------
----------------------------------------ggcatgccgcctctccttgg
ggcgcattgaccgttgggcggaaacccttgacattttcagcattaccgcagggtagagag
ttcggtgagctcctacccgtgcggaacaccgtccgatccagaattttagttaacgaactt
ccgtctcaagaacacaaggatgtgggtagatcgatactcgaacgtacaggaaagcagtgt
atagttctcgggtcgccggatctg------------------------------------
---cctacacgaagtacctaattacggccaggtgtagacgatacccaa------------
--ccagtatctgcgcccgacgtcgttttacgcagaacctacc------------------
-----cttccgagcattttctacctacgaccaccagctgatccctgctgcggatgaaaag
aatggaaacaacaaggctttctgtaagccagaaagtggaggaagaccgcctgtgattgcg
accctttagtagtctttagcaccac-----------------------------------
----------aaacttatgcgccgattctcagagttagacataaggtatattccgtcgcc
tgtcatatggatgggggaacgg---------------------tcgtcgcagaggccgcc
gaggaatatataccccgtactaccgtccaggtgcgcaggtcagggctgctcggggtttag
cataccccatgacactgtacaggctggggaatacatgacgatatagattaagtactcgtc
tgctagcagccgcttaatccagtatgt-------------------------cgtgatca
aatctggacactgtaacggtatcgcggagacc----------------------------
-----------gccatattgccattgcttgtgagaaca----------------------
--------------------
>SEQ17
taccctcctattcagtacgacggtagggctccctatgttggtgtgaatcgcctctattac
tcagggactcaatgcgatgcaggggattaatacagtacagggcatcccacgtcccctcgg
cgcgaattgagcataatactcagacccctgccattttcagca------------------
-------------tacaggtgcggaacaccgtccgatccagtattttagttaacgaactt
ccgtcccaagaacacaaggatgc-------tcgatactagaacgtacaggaacgcagtgt
atggctctcagcgtttcg----------------------------------taaaaaca
tacagatcactaagtagct-----------------------------------------
----------tccgcgcgtgatctctgtctgccgaatgtacc-----------ccatgaa
tcccgcttacaagcattttatacctacgaccaccaggtgatccctgctacggatgaaaag
aatggagacgacaaggctttctgtaagccagaaagccgagggagaccgcctgtgattgcg
acatttgcaga--------------------------------------tccatgggcat
gatca---------------------ccaccgaattagccttaag---------------
---catgtggtttggggaacggta------------------------------------
----------------tctttaccgtccaggtgcgcaggtcagggctgctcgcggtttag
cataccccatgacactgtacaggctggggaatgcatgacgatatagattaagtacgagtc
tgcgagcggccgcttaatccagtatgt-------------------------cgtgatca
aaactggacactgtcacggtatcgcggatacc----------------------------
-----------gccatagtgcctttgcttgtgagaaca----------------------
---acattgccttccagacc
>SEQ18
tactcttcggtccagtacga----------------------ctgaatcgcc--------
----------------------------------------ggcatgccgtctctccttgg
ggcgcattgcccgtagggcggaaacccttgatattttcaacattaccgcgggatagagag
ttcggtgagctcctaccagtgcggaacaccgtccgatccagtattttagttaacgaactt
ccgtcccaagaacacaaggatgc-------tcgatactagaacgtacaggaacgcagtgt
ttggttctcgcgtcgccggatctg------------------------------------
---gggaccctaagtacctaatgaaggctaggtctagacgatacccgatggtaaggccgg
gacca---------------------------ctaatgaaccctgactgtgatctttgaa
aaccacatccggcaatttgctacctacgaccaccaggtgatccctgctgcggatgaaaag
aatggagacaacaaggctttctgtaagccagaaagtgggggaacaccgcctgtgattgcg
tgcctttagtagtctttagctccac-----------------------------------
------------------------attcctagtattgatcatgccccgattctcatcgcc
tctcatatggatgggggaacggaa-------------------tagttgctgagtgcgcc
ggtgaataaataccccatactaccgtccaggtgcgcacgtcagggctcctcgcggtttag
catactccatgacactgtacaggctggggaatgcgtgacgatatagattaagtactagtc
ggcaggcaccta---------------------------agcgcaggggtggcgtgctcc
agcctgttgcctttcacgggttcacggatacccgatgctttttccttctggcg-------
----atctttacctagtgccca--------------------------------------
--ttcattgctgctcagtcg
>SEQ19
tactcttcgg--------------------------------------------------
--------------------------------------gaggcatgccgcctctccttgg
ggcgcattgaccgttgggcggaaaccat-------------------------------g
ttcggtgagcgcctacccgtgcggaacaccgtccgatccagtattttagttaacgaacgt
ccgtctcaagaacacaaggatgtgggtagatcgatactcgaacgtacaggaacgcagtgt
gtcgttctcaggtagccga-----------------------------------------
---aggacgcgaagtacctaatt----------------------tgatggaatgaccga
ctcgagtatccgggcaagtcgtctgtttctggcgaatgtacc------------------
----acttgcgagcagtttctacctacgaccac-----gatccctgctgcggatgaaaag
aatggaaacaacaaggctttctgtaagccagaaagtggaggaagaccgcctgtcattgcg
acccccttggaacttgtaaa----------------------------------------
----------------------------------------------------gttcttcc
tatcatatgcctgggggtaccgagggggccgtaagcactcagct----------------
----aatataagtcgcctattaccgtccaggtgcgcacgtcagggctcctcgcggtttag
catactccatgacactgtacaggctggggaatgcgtgacgatatagattaagtactagtc
tccaagcagccgtttaatccagtatgt-------------------------ggtgaaca
aaactgtacattgtcacggtatcgcggattgc---------------------ctcctgg
cagcgtctttcctccttgtgccatttcttgagagaacagttagaattgcag---------
----------ctttcagacc
