>SEQ0
ggcttgcactgcaatctttcttacctctgaccgcggagagcggacctcctctcgtaatct
gtcaagcgctcttgtgattcgaccccaatcgtggtggaactcaactctcttaggctagag
gaatagactattatggatacgacggacgcgttttcaacggtggtagattcgtgacgtgac
tggatctatggagtataaattagtgtgatgttggccgacgagcagtagcacccggtactc
gccactccctcggaaatccacatctagatgtcgctactagtttatactacgagcgtcacg
ggacgcggaacgctaaaaccctcaaacctaacgggctccctgcagtaacacctatcacgg
ctactccgggaggctggggtactgaaatcgcaagaatggctgctttcatttaaagttaat
cggcggttgaatcatgtgtcttttaaaaagacggacgactagggtagcagcgccacgata
ttaccgccggagggcggtagcagaaccgatcaagctgcagggatcaaacagatttcctga
ttccagcggatccgccctctagaggcttttactttcgccaacccatcttcccttcgatgg
gattttacttcaaagaacctggcagctacaagcccatttaccatgaggggtgtttcatag
gtccctcctccaggcccaggcgaactctggaggtgccgtagcctggctatatgccttaat
ccgttattcggcgaaagtggaccgtgtggttttgatgttctgccgggacaggggtcaacg
gtaaagtatcccggcgagtgaaatacctacggggcggctcctaatctgctcgagacgaca
cagcaccaatcggatggaaaccccacatgctttcgggacctcccgaacccacaaggttct
tcagacgtgaaactccgggttccgtaactttcgatgatctgcgcagctcggtatggtcca
cgggcagataggccgtacggcctcaaagtctctcaacttcttagatcaagataagtcttc
gcgttctactatcgcaattccgtgcggacgtgagtcctgtacccttttcgcagagacata
gtcccagccgcggccagtca
>SEQ1
ggcttgcactgcaatatttcttacctctgaccgcggagagc-------------------
--caagcgctcttttgattcgaccccaatcgttttggaactaaactctcttaggctagag
gaagtgactattattgatacgacggatgcgttttcaacgggggtagattcgtgacgtggc
tggatctatggagtataaattagtgtgatgttggccgacgagcagtagcacccggtactc
gccactccctcggaaatccacatctagatgtcgctactagtttatactacgagcgtcacg
gg-----------------------------------ccctgcagtaacacctatcacgg
gtactccgggaggctggggaacggacatcgcaagaatggctgattccatttaaatttaat
cggcggttgaatcatgt-------------------------ggcaggagcgccacgata
ttaccggcggagggcggtagcagaaccgatcatgctgcagggatcaaacagatttcctga
ttccagcggatccgccctctagaggcttttactatcgccaacccatcttcccttcgatgg
gaatttacttcaaagtactgggcagct---------------------ggtgtttcatag
gttcctcctccaggccca---------------tgccgtagcctggctatatgccttaat
ccgttattcggccaa-----------------------------------------agtg
gcaaagtatcctggcgagtgaaatacctacggggccgctcctaatctgctcgagacgaca
cagcaccaatcggatggataccccacatgctttcgggacctcccgaacccacaaggttct
tcagaagtgaaactcggaggtccgtaactttcattgatctgcgcatc-------------
----------ggccgta-----------------------------------aagtcttc
gcgttctactatcggaattgcgagcggacgtgggtcctgtacccttttcgcagagacata
gtccaagctaaggccagtca
>SEQ2
gcct---------------------cctgaccgcggagagg-------------------
--caagcgctcttttgattcgagcataatcgttttggaact------------------g
gaagtgacttttattgatacgacggacgcgttttcaatgggggtagattcgttacgtggc
tggatctatcgagtattaattagtgtgatgttggccgacgagcagtagcacccggtactc
gccactccctcggaaatccacatctagatgtcgctactagtttatactacgagcgtcacg
gg--------------------------------------------------------cg
gtactccggggggctggggaacggacaacgcaagaatggctgattccatttaaattaaat
cggcggttgaatcttgt-------------------------ggcgagagcgccaccata
ttaccggcggagcgcggtagcagaaccgatcaagctgcagggatcaaacagatttcctga
ttccagcggacccgccctctagaggcttttactttcgccaacccatcttcccttcgatgg
gaatttacttcaaagtgctggggagct---------------------ggtgttgcatag
gttcctcctccaggccca---------------tgccgtagcctggctataagccttaat
ccgtaattcggccta-----------------------------------------agtg
gcaaagtatcctcgcgagtgaaatacctacggggccgctcctaatctgctcgagacgaca
cagcaccaatcggatggataccccacatgctttcgggacctcccgaacccacaaggttct
---------------------------------------tgcgcatc-------------
----------ggctgta-----------------------------------aagtctta
gcgttctactatcggaattgcgagcggacgtgggttctggacccttttcgtagagacata
gtccaagctaaggccagcca
>SEQ3
cgattgcactgcaatatttcttacctctgatcgcggagagc-------------------
--caagcgctcttttgattcg-----------------------------------cgag
gaagtaactattattgatacgacggatgcgtcttcaatgggggtagattcgttacgtagg
tggatctatggagtataaattagtgtgatgttggccgacgagcagtagcacccggtactc
gccactccctcggaaatccacatctagatgtcgctactagtttatactacgagcgtcacg
gg-----------------------------------ccctgcagtaacacctatcaagg
gtaccccgggaggatggggaacggacatcgcaagaatggctgatcccacttaaatt----
---------aatcatgt-------------------------ggcaggagcgccacgcta
ttaccggcggagggcggtagcagaaccgatcaagcttcagggatcaaacagatttcctga
gtccagcggacccgccctctagaggcttttactttcgccaaaccatcttcccttcgatgg
gattttacttcaaagaacctggcagttacaagcctatttaccatgaggggtgtttcatag
gtccctccgccgggccccggaaaactctggaggtgccgtggactggctaaatgcc-----
------------------ggaccgtgtggttttgatgttctggcgggacaggggtcaacg
gtaaagtatcccggcgagtgaaatacctacggggcggctcctaatctgctcgagacgaca
cagcaccaatcggatgcaaaccccacatgctttcgggacctcccgaacccacaaggttct
gcagacctgaaactccgggttccttaactttcgatgatcagcgcacctcggtatggtcca
cgagcagataggccgttcagcctcaaagtcactcaacttctaagatcaagataagtctac
gcgttctactatcgcaaatccgtgcggacgtgagtcctgt--------------------
-tcacagccgcggccagtca
>SEQ4
ggctcgcactccagg---------------------------------------------
-------------------cgccctcaatcgtttcggaactaaactctcttaggctagag
gaagtgactatta------------------ttgcaacggaggtagatttgtgacgtggc
tggatctatggcgtataaattagtgtgattttggccgacgagcagtagcacccggtactc
gccactccctcggaaatccacatctagatgtcgctactagtttatactacgagcgtcacg
gg-----------------------------------ccatacagtaacacctatcacgg
gtactccgggaggc--------------------aatggctgattccattcacatttaat
cgaccgttgaatcatgt-------------------------------------------
--gcgggcggagggcggttgcagaaccgttcatgctgcagggatcaaacagatttcctga
ttccagcggatccgccctctagaggcttttactatcgccaacccatcttcccttcgatgg
gagtttacttcaaagtgctggggagct---------------------ggttttgcaatg
gttcctcctccaggccca---------------tgccgtagcctgacagccta-------
------------------------------------------------------------
-------------------aaaatacctacggggccgctcctaatctgctcgagacgaca
cagcaccaatcggatggataccccacatgctttcgggacctcccgaacccacaaggttct
gcagacctgaccctccgaggtccttaactttcgatgaacagcgcacctc-----------
---gcagataggccgttccgcctcaca---------------------------------
---------------------------------------------------------atg
ttcacagccgcggccattca
>SEQ5
agcttgcact--------------------------------------------------
-------------------cgacctcaatcgtttaggaactaaacgctcttaggctagag
gaagtgactattattgcaac----------------------------------------
-ggagctatggcgtatcaattagtgtgattttggccgacgagcagtagcacccggttctc
gccactccctcggaaatccacatctagatgtcgctactagtttatactacgagcgtcacg
gg--------------------------------------tacaatgacacctatcacgc
gtactccgggaggc--------------------catggctcattcgattcacatttaat
cggctgttgaatcatgt-------------------------------------------
--gctggcggagggcggttgcagaaccgatcaagctgcagggatcaaacagatttcctga
ttccagcggacccgccctctagaggcttttactttcgccaacccatcttcccttcgatgg
gaatttacttcaaagtactgggcagtt-----------------------tgtttcatag
gttcctcctcctggctca---------------tgccgtagcctggctatatgccttaat
ccgttattcgaccaa-----------------------------------------agtg
gcaaagtatcctggcgagtgaaatacctacggggcggctcctaatctgctcgagacgaca
cagcaccaatcggatgcaaaccccacatgctttcgggacctcccgaatccacaaggttct
tcagacgtgaaactccgggttccgtaactttcgatgatctgcgctgctcggtatagtcca
cgggcagataggccgtacggcctcaaagtctctcaacttcctagatcaagataagtcttc
gcgttctactatcacaatcccgtgcggccgtg-----------------------ccata
gtctcaaccgcggcca---a
>SEQ6
ggcttgcactgcaatctttcttacgtcagaccggggagagcggacctcctctcgtagtct
gtcaagcgctcttgtgattcgaccccaatcgtggtggaactcaactatcttaggc-----
-----------------gacgacggacgcgttttcaacggtggtcgattcgtgacgtgac
tggatctatggaatgtaaattagtgtgattttggccgacgagcagtagcacccggtactc
gccactccctcggaaatccacatctagatgtcgctactagtttatactacgagcgtcact
gg-----------------------------------cccctcagccacacctaacacgg
gtactcacgca-------------------------------------------------
---cggttgaatcatgt-------------------------ggcaggagcgtcac----
------------gatattagcagaaccgatcaagctgcagggatcaaacagatttcctga
ttccagcggatccgccctctagaggcttttactttcgccaacccatcttcccttcgatgg
gaatttaccgcaaagtgctgaggagct------------------------gttgcatag
gttcctcctccaggccca---------------------------------------aat
ccgtaattc--------------------------------------------------g
ccaatgtatcttcgcgagtgaaatacctacggggcggctcctaatctgctcgagacgaca
cagcaccaatcggatggaaaccccacatgctttcgggacctcccgaagccacaaggttct
gcagacctgaccctccaaggtccttaactgtcgttgaacagcgcagctc-----------
------------------------------------------------------------
-------------------------------------------------------gcaga
tacaatgtcgcggccattca
>SEQ7
ggctcgcactc-------------------------------------------------
--caggcgccctc---------------------------------ctcttaggctagaa
gaagtcactatta------------------ttgcaacggaggtagatttgtgaagtgga
tcgatct-----------attagtgtgattttggccgacgagcagtagcacccggttctc
gccactccctcggaaatccacatctagatgtcgctactagtttatactacgagcgtcacg
gg-----------------------------------acgctaacgggctccctgcagaa
tc--------aggctggggtactgaaatcgcaggaatggctgctttcaattaaagttaat
cgcctgttgaatcatgtgtctttcaaaaagacggacgactagggtagcagcgccac----
------------gatattaccagaaccgttcatgctgcagggatcaaacagatttcctga
ttccagcggatccgccctctagaggcttttactatcgccaacccatcttcccttagatgg
gaatttacttcaaagtactggggagct---------------------ggtggtgcatac
gttcctagtacaggccca---------------tcccgtagcctggctataagccttaat
ccgtacttcggccta-----------------------------------------agag
gcaaagtgtcc---------aaatacctacggggcgggtcctaatctgctcgagacgaca
cagcaccaatcggatgcaaaccccacatgctttcgggacctcccgaatccacaaggttct
---------------------------------------agcgca---------------
------------------------------------------------------------
------taagatcggaattgcgagcggacgtgggttcttgcccattttcgtagagacata
gtccaagctaaggccagcta
>SEQ8
ggcttgcactgtaatctttattacgtcagaccggggagagcggacctcctctcgtagtct
gtcaagctttcttgtgattcgaccccaatggtggtggaactcaactatcttaggc-----
-----------------gacgacggacgcgttttcaacggtggtcgatccgcgacgtgac
tgaatctatggaatgtaaagtagtgtgattttggccgacgagcagtagcacccggttctc
gccactccctcggaaatccacatctagatgtcgctactagtttatactaccagcgtcacg
gg-----------------------------------ccctgc-----------------
-------gggacgatggggaacggacatcgcgggcttggctgatcccacttaaatt----
---------aatcgtgt-------------------------ggcaggagcgccacgcta
ttaccggcggaggacgttagcagaaccgatcatgctgcagggatcaaacagatttcctga
ttccagcggatccgccctctagaggcttttactatcgccaacccatcttcccttcgatgg
gaatttatttcaaactagggg---------------------------cctgtttcatag
gttcctcctcgtggctca---------------tcccgtagtctggctatatgccttaat
ccgttatccgaccaa-----------------------------------------agtg
gcaaagattcctggcgagtgaaataccttcggggcggctgctaatctgctcgagacgaca
cagcaccaatcggatgcaaaccccacatgcttgcgggacctcccgaatccacaaggttct
gcagacctgacccc---------------ttcgatgaacagcacacctc-----------
---gcggataggcagcctagca--------------------------------------
---------------------------------------------------------ata
ttcacacacgcggccataca
>SEQ9
ggcttgcactgcaatctttcttacctc---------------------------taatct
gtcaagcggtcttgtgattggaccccaatcgtggtgtaactca----------ggcagag
gaatagactattttggacaggacggacgcgttttcaacggtggtagattcgtgacgtgac
-------------------ttagtgtgtttttggccgacgagcagtagcacccggtactc
gccactccctcggaaatccacatctacatgtcgctactagtttatactacgagcgtcact
gg-----------------------------------accctgagtcacacctaacacgg
gtactcacgcaag-----------------------------------------------
-----gttgaatcgtgt-------------------------------------------
-----------ggcagggggcagaaccgatcaagctgcagggatcaaacagatttcctga
ttccagcggatccgccctctagaggcttttactttcgcccacccatcttcccttcgatgg
gaatttacttcaaagtactga--------------------------------ttcatag
gtaccacctcctgggaca---------------tgacgcagcctggctgtatgccttaat
cctttattcgaccaaagtggc---------------------------------------
--------------------aaatacctacggggcggctcctaatctgctcgagacgaca
cagcaccaatcggatggaaaccccacatgctttcgggacctcgcgaacccacaaggttct
gccgacatgaccgtccgaggtccttaacgttcgatgaacagcgcacctc-----------
---gcagattggccgtgccgaatcaca---------------------------------
---------------------------------------------------------atg
ttcacagccgcagccattcg
>SEQ10
cgattgcacttcaatatttcttacctctgatcgcggagagc-------------------
--caagcgctcttttgcttcg-----------------------------------cgag
gaaggaactatttttgatacgacggatgcgtcttcaatgggggtggattcgttacgtagg
aggatctatggagtctaagctagtgtgatgttggccgacgagcagtagcacccggtactc
gtcactccctcggaaatccacatctagatgtcgctactagtttatactacgagcgtcacg
gcgcgcggaacgctaaacccctcaaaccttacgggttccctgcagtaacacctatcgcgg
ctactccgggaggctggcgtactaagatcccaagaagggttgct----------------
-ggcgctcgaatcatgt----------------------------------------gtc
ttttcaaaagacggacgactcagaaccgatcaagctgcagggatcaaacagatttcctga
ttccagcggacccgccctctagaggcttttactttcgccaacccatcttcccttcgatgg
gattagacttcaaaaggcca----------------tttaccatgaggggtgtttcatag
gtccctcctccaggcccaggcgaactctggaggtgccgtagcctcgctttatgccttaat
ccgttattcggcgaatgtggaccgtgtggttttgacgttctgccgggacaggggtcatcg
gt------------------aaatacctacggggcgggtcctaatctgctcgagacgaca
cagcaccaatcggatgcaaaccccacatgctttcgggacctcccgaatccacaaggttct
tcagacgtgaaactccgggtttcgtaactttcgatcatctgcgcc---------------
-------ataggctgtccggcctcaaagtcgctctacttcttaaaacaagataagtcgta
gcgttc-------------ccgtgcggacgtgagtcctgtaccctcttcgcagagacata
gtgccagccgcggccagtca
>SEQ11
ggcttgcactgcaat---------------------------------------tattct
gtcaagcggtcttgtgagtggaccccaatcgtggtgtaactca----------ggcagag
gaatagattattttggacaggccggacgcgttttcaagggtagcagattcgtgacgtgcc
-------------------ttagtttgatgttggccgacgagcagtagcacccggtactc
gccactccctcggaaatccacatctagatgtcgctactagtttatactacgagcgtcacg
gg--------------------------------------tacaatgacacctaggacgt
atactccgcgagcc--------------------gatggctcattcgattcacaattaat
gggctgttgaataatgt-------------------------------------------
--------------gcttgccagaaccgatcgagctgcagggatcaaacagatttcctga
ttccagcggacccgccctctagaggcttttactttcgccaacccatcttcccttcgatgg
gaacttgcttcaaactgctggggagca---------------------ggtgttgcatag
g------------------------------------gtaacctggctataagccttaac
ccgtaattcggccta-----------------------------------------agtt
gcaaagtgtcctcgcgagtgaaataccttcggggcggctgctaatctgctcgagacgaca
cagcaccaatcggatgcaaaccccacatgcttgcgggacctcccgaatccacaaggttct
gcagacccgacccc---------------ttcgataaacagcgcacctc-----------
---gcggataggcagcctagc---------------------------------------
-----------------------------------------------------------a
atcacacacgcgaccataca
>SEQ12
-------------------------cctgaccgcggagagg-------------------
--caagcgctctttttattcgagcatactcgttgtggaact------------------g
gaagtgacttttattgatacgacggacgcgttttcaatggggg----------------c
tggatctatcgagtattaattagtgtgatgttggccgacgagcagtatcacccggtactc
gccactccctcggaaatccacatctagatgtcgctactagtttatactacgagcgtcacg
gg--------------------------------------tacaatgacacctatcacgc
gtactccgggaggc--------------------catggctcgatcgattcacatt----
-----------tcatgt-------------------------------------------
--gctggcggatgacggttgcagaaccgatcatgctgcagggatcaaacagatttcctga
ttccagcggatccgccctctagaggcttttactatcgccaacccatcttcccttcgatgg
gagtttatttcaaattgctggcgaact---------------------ggtttttcaatg
gttctacctccaggccca---------------ttccgtaccctgac-------------
------------------------------------------------------------
--------------------aaatacctacggggcgggtcctaatctgctcgagacgaca
cagcaccaatcggatgcaaaccccacatgctttcgggacctcccgaatccacaaggttct
---------------------------------------agcgca---------------
------------------------------------------------------------
---------tatcgaaattgcgagc---------------------------gagacata
gtccaagctaaggccagcca
>SEQ13
cgattgcagtgcaatatttcttacctctgatcgcggagagc-------------------
--caagcgctctcttgaatcg-----------------------------------cgcg
gaagtaactgttattaatacgacggatgccttttcaatgagggcagattcgttacgta--
-------------------atagtgtgattttggccgacgagcagtagcacccggtactc
gccactccctcggaaatccacatctagatgtcgctactagtttatactacgagcgtcacg
gg-----------------------------------acgctaacgggctccctgcagca
tc--------gtgcaggggtactgatatcgaaggaatagctgcttgcaattaaagttaat
agcctgttgaatcacgt----------gttattcttgactagggtagcagcgcctc----
------------aatagtaccagaacggatcgagctgcagggatcaaacagatttcctga
ttccagcggacccgccctctagaggcttttactttcgccaacccatcttcccttcgatgg
gaaattaattcaaagtaccga--------------------------------ttcatag
gtaccaccacttgcgaca---------------tggcgcattctaccatagtggc-----
------------------------------------------------------------
--------------------aaatacctacggggccgctcctaatctgctcgagacgaca
cagcaccaatcggatggataccccacatgatttcgggacctcccgaacccacaaggttct
gcagacc--------------------ccttcgataaacagcacacatc-----------
---gcggctaggcagcctagca--------------------------------------
---------------------------------------------------------ata
ttcgcacacgctcccataca
>SEQ14
ggcctgcaccgtaat---------------------------------------tattct
gtcaagcagtcttctgagtggaccccaatcgtggcataactca----------ggcagag
gaatagattattttggataggccagacgcgttttcaagggtagcagattcgtgacgggcc
-------------------ttagtgtgatgttggccgacgagcagtatcacccggtacac
gccactccctcggagatccacatctagatgtcgctactagtttatactacgagcgtcacg
gg-----------------------------------accctaacgggctccctgcagaa
tc--------agaagggggtactgaaatcgcacgaatggctgctttcaattatagttaat
cgccaa--------------------aaagacggacgactagggtagcagcgttac----
------------gatattaccagaaccgatcaagctgcagggatcaaacagatttcctga
ttccagcggatccgccctctagaggcttttactttcgcccacccatcttcccttcgatgg
gattgtacttcaaagaagctggcagcttcaagcccatttaccatgaggtgtgtttcatag
gtccctcctccaggcacaggcgaactctggaggtgccgtagcctggctatatggcttcaa
ctgt---------------------gtggttttaatgttctggcgggaaaggggtcaacg
gtaaagtatcccggcgagtgaaataccttcggggcggctgctaatctgctcgagacgaca
cagcaccaatcggatgcaaaccccacatgcttgcgggacctcccgaatccacaaggttct
---------------------------------------tgcgcatc-------------
----------ggctgta--------------------------------------tctta
gcgttctactatcggaattgcgagcgcacgtgggttctggacccttttcgtagagacata
gtccaagttaaggcaagcca
>SEQ15
gccttgcacggtcatctttattacgtcagaccggggagagcggacctcctctcgtagtct
gtcaagctttcttgtgattcgacccctat-------------------------------
----------------gaacgacggaggcggtttcaacggtgatcgatccgcgacgtgcc
tgaatctaatgaatgtaaagtagtgtgatgttggccgacgagcagtatcacccggtacac
gccactccctcggagatccacatctagatgtcgctactagtttatactacgagcgtcacg
gg-----------------------------------ccccgcagtttcacctatcacgt
gtactcggggaggctggggaacgggcatcgcaagattggctgattccatttaaatttaat
cggcggtt-----------------------------------gcaggagcgccacgata
ttaccggcgcagggcggtagcagaacggatcgagctgcagggatcaaacagatttcctga
ttccagcggacccgccctctagaggcttttactttcgccaacccatcttcccttcgatgg
gattttacttcaaagaacctgg-----------------accatgagtgaggtttcatag
gtccctcctccaggcccaggcgaactctggaggtgccgaagcctggctatgtgccttaat
ctgttattcggcgaaagtggaccctgtggttttgatgttctgccgggacagaggtcaacg
gtaaagta----------tgaaatacctacggggccgctcctaatctgcacgagacgaca
cagcaccaatcggatggataccccacatgctttcgggacctcccgaacccacaaggttct
gcagacccgagact----------------------------------------------
------------------------------------------------------------
----------------------------------------------------aggacata
ttcgcacactctcccataca
>SEQ16
ggctcgcagt--------------------------------------------------
---------------------------------------ccaggcgcccttaggttagag
gaagtgacta------------------caatcccaacgaaggtagatgtgtgacgtggc
tgaatgtatggcgtatacattagtgtgatgttggccgacgagcagtagcacccggtactc
gccactccctcggaaatccacatctcgatgtcgctactagtttatagtacgagcgtcacg
gg-----------------------------------ccatgcagtaacacctatcaagg
gtaccccgcgaggatggggaacggacatcgc-----------------------------
---------attcaggt-------------------------ggcaggaggaccacgcta
ttatcgatggacggcggtagcagaaccgatcaagctgcagggatcaaacagatttcctga
ttccagcggacccgccctctagaggcttttactttcgccaacccatcttcccttcgatgg
gaatttacttcaatgtactgggcagct---------------------ggtgtttcata-
---------------------------------tcccgtagccggagtatatgccttaat
ccgttattcggccaaagtgg----------------------------------------
------------------caaaatacctacggggcggctcctaatctgctcgagacgaca
cagcaccaatcggatgcaaaccccacatgctttcgggacctcccgaatccacaaggttct
---------------------------------------cgcgcaac-------------
----------ggctgtg-----------------------------------aagtctta
gagttctacta---------------------------ggacccgtctcgtagagacata
gtccaagctaaggccaggga
>SEQ17
gtcctgcaccgtaat---------------------------------------cattct
gtcaagcagtcctctgagtggaccccaatcgtggcataactga----------ggcaggg
gaatagattattttagataggccggacgcgtttgcaagggttgaagattcgtgacgggcc
-------------------ttagtgtgattttggccgacgagaagtagcacccggtactc
gccactccctcggaaatccacatctagatgtcgctactagtttatactacgagcgtcact
gcgcatggaacgctaaggccctgaaacctttcgggttccctgcagtaacacctag-----
--------------------actaagatcccaagaagggttgct----------------
-ggcgctcgaatcatgt----------------------------------------gtc
ttttcaaaagacggccgactcagaaccgatcaagctgcagggatcaaacagatttcctga
ttccagcggacccgccctctagaggcttttactttcgccaacccatcttcccttcgatgg
gaattttctt----------------------------------------tgcttcatag
gttcctcctcctggctca---------------tgcagtctcctggcaagaagtggcaa-
------------------------------------------------------------
----------------agtaaaatacctacggggcggctcctaatctgctcgagacgaca
cagcaccaatcggatgcaaacaccacatgctttcgggaccacccgaacccacaaggttct
tcagacgtgaaactccgggttccgtaactttcgatgatctgcgcagcttggtaagctcca
cgggcagataggccgtacggcctcaaagtctttcaacgtcttag----------------
----------atcgcaattctgtgctgacgtgagtcctgtaccctgttaggtgagacata
gacccag-------------
>SEQ18
ggcttgcactgcaatctttcttacctct--------------------------------
--caagcgatcttgtgattggaccccaaacgtggtgtaactca----------ggcagag
-------------------------------------ccgtggtagattggtgacgtg--
-----------------aattagtgtgattttggccgacgagcagtagcacccggttctc
gccactccctcggaaatccacatctagatgtcgctactagtttatactaccagcgtcacg
gg-----------------------------------cccctaacgggctccctgcagga
tc--------agaagggtgtactgcaatcgcacgaatgactgctttcaattatagttaat
cgccaa--------------------aaagacggacgactagggtagcagcgttac----
------------gatattaccagaaccgatcaagctgcagggatcaaacagatttcctga
ttccagcggatccgccctctagaggcttttactttcgccaacccatcttcccttcgatgg
gacttaacttcaaagtactaggcagat---------------------ggtgtttcgtcg
gttcctactcc---------------------------taggctggctatattccttaat
ccgttattcggccatagtgg----------------------------------------
------cttcctgtcgagtgaaatacctacgggaccgctcctaatctgctcgagacgaca
cagcaccaatcggatggataccacacatgatttcgggacctcccgaacccacaaggttct
tcagacgtgaaactcg--------------------------gctgctgggtatagtcca
cgggcagataggccgtacggccagaaagtctctcaacttcctagatcaagagaggtcttc
gcgttctactatcacaatcccttgcggccgtg-----------------------ccata
gtctcaaccgcggcca---a
>SEQ19
gcct---------------------cctcaccgcggagaag-------------------
--caatcgctcttgtgattcgagcctaatcgttttggaaccggagct-------------
-----------------gacttcggacgcgttttcaatgggcgtagattcgttacgaggc
tgtatctctcgagtattaattagtgtgatgttggccgacgagcagtagcacccggtactc
gccactccctcggaaatccacatctagatgtcgctactagtttatactacgagcgtcacg
gcggccggaacgc------------------------tcaaccagtaacacctatcgcgg
ctacacctggaggctggcgtactaagatcccaagaagggatgct----------------
-ggcgctcgaatcatgt----------------------------------------gta
ttttcaaaagacggacgaatcagaaccgatcaagctgcagggatcaaacagatttcctga
ttccagcggatccgccctctagaggcttttactttcgcccacccatcttcccttcgatgg
gattttacttcaaagaacctggcagctactagcccatgtaccatgaggggtgtttcataa
gtccatcctcctggcct------------------------ccggcctatatcccttaat
ccgttattcggcgaagggggacagtgaggttttcctgtactgccgggacaggggtcagca
gttaaatatccaggcgagggaaatacctacggggcggctcctaatctgctcgagacgaca
cagcaccaatcggatggaaaccccacatgctttcgggacctcccgaacccacaaggttct
tcagaagtgaaactcggaggtccgtaacttgcattgatcggcgcatc-------------
------------------------------------------------------------
----------ggctgtattgcgagccaacgtgggtcctgtaccttttccgcattgagata
gtccaagctaaggccagtca
