>SEQ0
ctaataaaacaagcgtctggatttggagagagagtgcaatgtccgataggggagaagacg
atccgctgaggtgtcagacatgggcagtggtcgagctcggccattgtggcttaattacct
gcagtaatctttgaacacgagagagatattcggggtgtacctgacacactgataaatgtt
tggaaccttgtttactggcttggggactttccggctggcttatttgataccgatataccc
ttgttatgggcctcaagggaggaaaaattcggcttcttcccactacttgcacaccaaaag
caatcgacaatgcttagacgctgttcttatattaagctgctatgatgatacttgatcacc
cctcgcgcctcatctgatttataactcccgtggagcggagttatccacgacagccccata
tccggatggtagaggtccctgtcggatacccttggagtgtaacagttgaacatttctgaa
gataacgtcggcaaggacggcaagtggataggttgcacccaggcacagttgaagtcaatc
cttattaatcgcttaagggcgctacggtagcagataggatccttgtatgccacaaatttg
acttactatccctagattttacgcgtacatgtcaaggatgtctcgctgcgatcctttgct
aaggggatggtccctttctttgatgtagtatctatatataatttcaacggacgatgtaac
tttggaacccggttcttaacacgattacgtgaaacgtagtccgcgaatccccgcaccagg
tttatattgtccactcttcggcaggcggatacatgttatgtgccaaaaagctcccatcac
tagcgtgctcgcaccaggagtgtccctctaacgcgacgaaaaaacaaattgttagctgtc
acgccatgggtcttttgacatacagtcgacggcactaatgttgccggtaagaggtctgca
gtagcaatatttaagatcctgtttttcgtgtcccccactctgtagttgctctgaaatcaa
caactgagtgaatatttacccattacaagggcctcgctttgccgctgggtctgtgtagga
ggcggcatcttgtctcgcgc
>SEQ1
ctaatgaaacaagcttatggattgtgagagagagtgcaacgtccgataggggagaagacg
atccgctgaggtgtcagacatggccagtggtcgatctctaccattgtgggctaattacct
gctgtaatctttgaacacgagacagatattcggggtgtacctgacacactggtaaatgtt
tggaaccttgtttagcggcttggggactttccggctggcttatttgataccgatataccc
ttgttatgggcctcaagggaggaaaaattcggcttgttcccactacttgcacaccaaaag
caatcgacaatgcttagaggctgttcttatattaagctgttacgatgatacttgatcacc
cctcgcgcctcacctgatttaaaactcccgtggagcggagttatccccggcagccccata
tccggatggtagaggtccctgtaggataccattgcagtctaacagttgatcatttctgaa
gataacgtcggcaaggacggcaagtggataggttgcacccaggcacagttgaagtcaatc
cttattaatcgcttaagggcgctacggtagcagataggatccttgtatgccacaaatttg
acttactatccctagattttacgcgtacatgtgaaggat---------------------
--ggggatggtccctctctttaatgtattagctatatataatttaaacggatgttgtaac
tttcgaacccggttataaacacgatgaggtgatacgtagtccgggaatgcccgcaccagg
ttcaaattgtccactcttcggcaggcggatacatgttatgtgccaaaaagctcccatcac
taacgtgctcgcaccaggagtgtccctctaacgcgacgaaaaaacaaattgttagcggtc
acgccatgggtcttttgacttacactcgacggcactaatgttg-----------------
----gaatatttaagatcct--------------------tgtagttgctctgcagtcaa
caactgatggaatctttacccattacaagggcgtcgctttgccgctgggtct--------
----------tgtctcgc--
>SEQ2
ctaatgagacaagcttaaggcttgtgagggagtgtgcaacttccgaaagggaagaagacg
agccggagaggtgtcagacatggccagtggtcgatctctacaggtgttggctattcacct
gctgtaatctttgaacacgagagagagaatcgcg--------------------------
-ggcactttgtttagcgccttggggactttccggctggcttatttgataccgatataccc
ttgttatgggcctcaagggaggaaaaattcggcttgttcccactacttgcagaccaaaag
caatcgacaatgcttagaaggtgttcttatattaagctgctatgatgatacttgatcacc
cct------------------------ccgtggagcggaggtatgcccgacagctccata
tccggatggtagagcttcctgtcggatacactgggagtgtaacagttgtacatt------
------------aagaacggcaagtggataggttgcacccaggcacagttgaagtcaatc
cttattaatcgcttaagggcgctacggtagcagataggatccttgtatgccacaaatttg
acttactatccctagactttacgcgtacatgtgaggggg---------------------
--ggcgatggtccatctctttaatgtattagctgtatatcatttttacggacgttgtatc
tttcgaacccgattataaacacgatgaggtgatacgtagt--------------------
-tcaaattgttcac------gcaggcggatacatgttatgtgccaaaaagctcccatcac
taacgtgctcgcaccaggagtgtccctctaacgcgacgaaaaaacaaattgttagcggtc
tcgccatgggtcttttgacctacagtcgacggcacttatgttgccggtaagcggtctgca
ctagcaatacttaagatcctgtttttcgtttgccccactctgtagttgcactgagctcaa
caactgagtcaatatttacccaatataagggcctcgttttgccgctgggtctgtgtagga
ggcggaatcgtgtctcgagg
>SEQ3
ctaatgagacaagct------------------------------------gcgaagacg
agccggagtggtgtcaga------------------tctacaggtgttggctattcacct
gctgtaatgtttgaacacgagagagagaatcgag--------------------------
-gtcactttgtttaatcccgtggggactttccggctggcttatttgataccgatataccc
ttgttatgggcctcaagggaggaaaaattcggcttgttcccactacttgcacaccaaaag
caatcgacacagctt-------------------------tatgttgttatttgatcac-
---------------------------ccgtggagcggaggtatgcccgacagctccatc
tccggatggtagagcttcctgtcggatacactgggagagtaacaattgaacatt------
------------aagcagggcaagtggataggttgcacacaggcacagttgaagtctatc
cttattaatcgcttaagggcgctacggtagcagataggatccttgtatgccacaaatttg
cctgactatccctagattttacccgtacatgtcacggct---------------------
--ggggatggtccctctctttaatgtattagctatatataatttaaacgaatgttgtaac
tttcgaacccggttgtaaacacgatgaggggatatgtagtccgggaatgcccgca-----
---------accactcttcggcaggcggatacatgttatgtgccaaaaagctcccatcac
taacgtgctcgcaccaggagtgtccctctaacgcgacgaaaaaacaaattgttagcggtc
aggccatgagtcttttgacttacactcgacggtactaaagttgcct--------------
----------------------------------------tgtagtttctctgcagtc--
------------------------acaagggcgtcgcttcgccgctgggtct--------
--------------------
>SEQ4
ctagtgaaacacgtttctggattgtgagataaagtgcaacgtccgataggggaggagacg
atccgctgaggtgtcagacatggccagtgttccttctctaccagtgtggg----------
---gcaatcgttgaacacgagacagatattcggagtgtacctgacatactggtaaatgtt
tggtcccttgtttaggggcttggggactttccggctggcttatttgataccgatataccc
ttgttatgggcctcaagggaggaaaaattcggcttgttcccactacttgcagaccaaaag
caatccacaatgcttagaaggtgttcttatatgaagctgctatgatgatactttatcacc
cct------------------------ccttggagcggagctatgcccgacagctccata
tccggatggtagagcttcctgtcggatacactgggagtgg--------------------
------------gagaacggcaagtggataggttgcacacaggcacagttgaagtctatc
cttattaatcgcttaagggcgctacggtagcagataggatccttgtatgccacaaatttg
tcttactatccctagattttacgcgttcatgtcagggatgtctcgctgcgatcctttgct
aaggggatggtcccttactttgatgtagaatctatgtataatttcaaaagacgctgtaac
tatggaacccggttcttaacacgattacgtgaaacgtagtccttgaatccgcgcaccagg
gttttattgtccactcttcggcaggcggatacatgttatgtgccaaaaagctcccatcac
taacgtgctcgcaccaggagtgtccctctaacgcgacgaaaaaacaaattgttagcggtc
tcgccatgggtctcttgacctacagtcgacagcacttatgtcgccggtaagcggtctgcg
ctagcaatacttatgacctagtttttcgattgccccactctgttcttgcacagatctcag
caactgagtcaatagttccccactataagggcctcgttatgccgctgagtcagtatacga
g-------------------
>SEQ5
ctaatgag---------------------------------------------------t
gcccggagtggtgccaga------------------------------------------
------------------------------------------------tctacaggtgtt
ggtcactttgtttgatctcgtggggactttccggctggcttatttgataccgatataccc
ttgttatgggcctcaagggaggaaaaattcggcttcttcccactacttgcacaccaaaag
caatcgacacagctt-------------------------tatcttgtaatttgatcac-
---------------------------ccgtggggcggaggtatggccgacagctccatc
cccggatggaagagcatcctgtcgga-------------------ttgcacatt------
------------aagtagggcaagtggataggttgcacacaggcacagttgaagtctatc
cttattaatcgcttaagggcgctacggtagcagataggatccttgtatgccacaaatttg
atttactatccctagactttacgcgtacatgtgaggg-----------------------
------------------------ggattagctgtatatcatttttacggacgttgtatc
attcgaaccccattataaagacgatgaggtg---------------------------cg
ttccaatggttcac------gcaggcggatacatgttatgtgccaaaaagctcccatcac
taacgtgctcgcaccaggagtgtccctctaacgcgacgaaaaaacaaattgttagcggtc
acgccatgggtcttttgacttagactcgacggcactaatgtcg-----------------
----gaatatttaagttgct--------------------tgtagttgctctgcagtgaa
caactgatggaatctttaccaattacatgggcgtcgtattgccgctgggtct--------
----------tgtctcgc--
>SEQ6
ataatgagacaagcttaaggctggtgagggagtgtgcaacttccgaaagggaagaagccg
agccggaaaggtgtcagtcatggccagtggtcgatctccacaggtgttggctattcacct
gccgaaatgtttgaacacgatagagagt--------------------------------
--gcaatttgtttaattcgttggggactttccggctggcttatttgataccgatataccc
ttgttatgggcctcaagggaggaaaaattcggcttcttcccactacttgcacaccaaaag
caatcgacactactt------------------------------tgtaattttatctc-
---------------------------ccgtggggcggaggtatggccgacagctccacc
cccggatggaagagcatcctgccgga-------------------ttgcacatt------
--------------------caagtggataggttgcacccaggcaccgttgaagtcaatc
cttattaattgcttaagggcgctacggtagcagataggatcgttgtatgccacaaatttg
tcttactatccctagattttacgggttcatggaagggaagtctcgctgcgatcctttgct
aagtgcatggtcccttactttgatgtcgaatctatgaataatttcaaaaggcgctgaaac
tatgtaacccggttccttacacgattacgtgtaacgtagtccttgaatccgcgcaccagg
gttttattgtctactcttctgcaggcggatacatgttatgtgccaaaaagctcccatcac
taacgtgctcgcaccaggagtgtccctctaacgcgaccaaaaaacaaattgttagcggtc
tcgccatgggtctcttgacctacagtcgacagcacttatgccgccggtaagcggtctgcg
ctaggaatacatatgacctactttttcgcttgcccca---------------gatctcag
caactgagtcaatagttccccactataaggggcgctttatcccgg---------------
--------------------
>SEQ7
ctaataaaacaaggatctggcgttgcagagagagagaaatgtccgataggggagaagccg
atccgctgaggtgtcagtcatcggcagaggtcgagcccg---------------------
---gtaatcttagtacacgagagtgatattcggggtgtacctgacacggtcataaatgtt
tggaaccttgtttactggcttggggactttccggctggcttatttgataccgatataccc
ttgttatgggcctcaagggaggaaaaattcggcttcttcccactacttgcacaccaaaag
aaatccgcacagctt-------------------------tatgttgttatttgatcac-
---------------------------ccgtgtagcggaggtatgcccgacatctccatc
tccggatggtatagcttcctgtcggatacactgggagagtaacaattgaacatt------
------------aagcacggcaactggataggttgcacccaggcacagttgaagtcaatc
cttattaatcgcttaagggcgctacggtagcagataggatccttgtatgccacaaattgg
aattactatccttagatcttacgcgtacatttaaggg-----------------------
------------------------ggattagttgtacatgattt----------tgtatg
attcgaaccccattataaagaccatgaggtg-----------------------------
--tcaatggttcac------gcaggcggatacatgttatgtgccaaaaatttcccatcac
taacgtgctcgcaccaggagtgtccctctaacgcgacgaaaaaagaaattgtaagcggtc
acgccatggggcttttgacttacacccgacggcacgattgttg-----------------
----gaatatttaagtacct--------------------tgtagttgct----------
---------------ttacccagtacaagggcgtctctgtctcgc---------------
--------------------
>SEQ8
ctaatgag---------------------------------------------------t
gcccggagtggtgccaga------------------------------------------
------------------------------------------------cctacaggtgtt
ggtcactttgtttgatctcgtggggacttaccggctggcttatttgataccgatataccc
ttgttatgggcctcaagggaggaaaaattcggcttcttcccactacttgcacaccaaaag
caaccgacaatgcgtagacgctgttcttatattaagctcctatgatgatgctcgagcacc
cctcgcgcctcatctgattgataactcccgtggagcggagttatccacgacagcctcata
tctggatggtagaggtccttatcggataccctttgaat----------------------
------------ggatcctgcaagtggatcggttgcacccaggcaccgttgaagtcaatc
cttattaattgcttaagggcgctacggtagcagataggatcgttgtatgccacaaatttg
cccgactatccctagattttacccgcacttgtcacggct---------------------
--ggggatggtccctctctctaatgtagtagctatatattgcttaaacgaatgttgtaac
tttcgcacccggtggtaaacacgatgaggggctatgtagtccgggactgcccgca-----
---------accactctttggcaggcggatacatgttatgtgccaaaaagctcccatcac
taacgtgctcgcaccaggagtgtccctctaacgcgacgaaaaaacaaattgttagcggtc
-----------------acttacactcgccggcactaatgttg-----------------
----gaatatttaagat-----------------------tgtagatgctctgcagtgaa
caacag------------------ataggggcgtcgctttgccgcggggtct--------
----------tgtctcgc--
>SEQ9
ctaataaaacaaggatctggcgttgcagagagagagaaatgtccgataggggagaaaccg
ttccgctgacttgtaagtcatcggcagaggtcgagcccg---------------------
---gtaatcttagtacacgacaatgatattcggggtgtacctgacacggtcttaaatgat
tggaaccttgtctactggcttggggactttccggctggcttatttgataccgatataccc
ttgttatgggcctcaagggaggaaaaattcggcttgttccgactacttgcagaccaaaag
aaatccgcacagc------------------------------------atttgataac-
-------------------------------------------tgcccaacagctccatc
tccggatggtatagcttcctgtcggatacactgggagagtaacaattgaacact------
------------aaccacggcaagtggataggttgcacacagccacagttgaagtctatc
cttattaatcgcttaagggcgctacggtagcagataggatccttgtatgccacaaatttg
acttactatccctagatttcatgcgtacatgtcaaggctgtctccctgcgatcctttgct
aaggggctgatccctttcattgatgtagtatctatatatgatttcaacggatgatgtaaa
tttagaatc-------------------gtgaaacgtagtccgcgaatctccgcacccgg
tttatattgtccactcttgggcaggcggatacatgttatgtgccaaaaatttcccatcac
taacgtgctcgcaccaggagtgtccctctaacgcgacgaaaaaagaaattgtaagcggtc
tcgccatgggtcttttgacctacagtcgacggcacttatgttgccggtaagcggtctgca
ctagcgatacttaggatcctgtttttcgtttgccccactctgtagttgca----------
---------------tgacccaatttaagggccgcgttttaccgctgggtctgtgtaggt
ggcggcatcatgtctcgagg
>SEQ10
ctaatgag----------------------------------------------------
--ccggagtgctgccaga------------------------------------------
------------------------------------------------cctacaggtctt
ggtcactttgtttgatctcttggggattttccggctgacttatttgataccgatataccc
ttgttatgggcctcaagggaggaaaaattcggcttgttccgactacttgcagaccaaaag
ctatcgacaatgcttacacgctgttcttatcttcagctgctatgatgatatttgaacacc
cctcgcccctcatctgatttataactcccgtggagcggacttcttcagcacacccccata
tccggatgttag--------------------------gtaacagttgaacatttctgaa
ggtaacgtcgacatggacgccaagtggataggttgcacccaggcacagttgaagtcaatc
cttattcatcgcttaagggcgctacggtagcagataggatccttgtatgccacaaatttg
aaataatatccttagatatcacgcgtacatgcaatgg-----------------------
------------------------ggattagttctacatgattt----------tgtatg
attcgaaccccgttataagcaccatgaggtg-----------------------------
--tcaatgtttcac------gcaggcggatacatgttatgtgccaaaaatttcccatcac
taacgtgctcgcaccaggagtgtccctctaacgcgacgaaaaaagaaattgtaagcggtc
acgccatggggcttttggattg--------------------------------------
---------------------------------ttgagcatgtagttg------------
-------------atttacccagtacaagggcgtctgtgtctcga---------------
--------------------
>SEQ11
ccaatgag----------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------tgcatcgactcagtggggattttccggctgacttatttgataccgatataccc
ttgttatgggcctcaagggaggaaaaattcggcttgttccgactacttgcagaccaaaag
aaatccgcacagctt-------------------------tatgttgttatctgatcac-
---------------------------ccgtgtagcggaggtaggcccgacatctc----
--------------------------tacactggtagcgtaacaattgatcatt------
------------acgctcggcaactggataggttgcacccaggcacagttgaagtcaatc
cttattaatcgcttaagggcgctacggtagc----aggatccttgtatgccacaaattgg
tcttactatcccaagattttacgagttcatggcagggaagtctcgct-------------
------gcgatcctttgctttgatctcggatctttgaataatgtcaaatggcgcttaaac
tatgtagcccggttccttaaacgattacgtgtaacgtagtccttgaatccgcgcagcagg
gttttattg-----------gcaggcggatacatgttatgtgccaaaaagctcccatcac
taacgtgctcgcaccaggagtgtccctctaacgcgaccaaaaaacaaattgttagcggtc
gagccatgggtcttttgacctacagtcgacggcacttatgtcgcctgtatgcggactgca
ctagcattacttaagatcctgtttgtcgttt------------------------gtcaa
caactgagtcaatatttacacaatagaagggcctcgatttgccgctgggtctgtggag--
--------------------
>SEQ12
ctaatgagac--------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--ctacaagtattggtcacttggggacttaccggctggcttatttgataccgatataccc
ttgttatgggcctcaagggaggaaaaattcggcttcttcccactacttacacaccaaaag
caatcgacacagcat-------------------------tatcttgtaatttgatcac-
---------------------------ccgtggcgcggaggtatgggcgagagctccatc
cccggatggaaaagcat---------------------------attgaacatt------
------------aagtagggcaagtggataggttgcacccaggcaccgttgaagtcaatc
cttattaattgcttaagggcgctacggtagcagatgggatcgttgtatgccacaaatttg
acttactttccct-------------------caagggtgtctcgctgcgatccatttct
aaacggatggtccctttctttgatgtagtatctatatataatttcaacggacgatgtaac
tttggaacccggctcttaacacgattacgtgaaacgtagtccgcgaatccccgcgaccgg
tttatattatccactcttcggcaggcggatacatgttatgtggcaaaaagctcccatcac
tagcgtgctcgcaccaggagtgtccctctaacgcgacgaaaaaacaaattgttagctgtc
ccgacaccggtctcttgacctacagtcgacagcacttatgtcgccggtaaggggtctgcg
ctagcaatgctta-----------------------------------------------
-----gagtcaatagattcccactataagggcctcgttatgccgctgagtcagtatacga
g-------------------
>SEQ13
ataatgagactagcttaaggctcgtgacgaagtgtgcaacttccgaaagggaagaacccg
agccggaaaggtggcagtcatggccagtggtcgatctccaccggtgttggctattcacct
gccgaaatgttt------------------------------------------------
-------------------ttggggattttccggctgacttatttgataccgatataccc
ttgttatgggcctcaagggaggaaaaattcggcttgttccgactacttgcagaccaaaag
caatcgacaacgcttagacgctcttcttatattaagcct-cgcgcctcaactgagttac-
---------------------------------------------cacgacagccccatc
tccgga----------------------------gagtgtaacatttgaacattgctgaa
gataacttctgcaaggacggcaactggataggttgcacccaggcacagttgaagtcaatc
cttattaatcgcttaagggcgctacggtagcagatgggatccttgtatgccacaaattgg
tcttacag---------------cgttcatctcagggatgtctcgc--------------
-------tggtcccttactttgatgaagaatctatgtataatttcaaaagacgctgtaac
tatggaacccggttcttaacacgattacttgaaacgtagtccctgatgccgcgcaccatg
gttttattgtccactcttcggcaggcggatacatgttatgtgccaaaaagctcccatcac
taacgtgctcgcaccaggagtgtccctctaacgcgaccaaaaaacaaattgttagcggtc
ag------------------tacgctcgatggtactaaagttg-----------------
----------------------------------------tgtagtttcactgcagtc--
------------------------acaagggcgtcgcttcgccgctgggtct--------
--------------------
>SEQ14
ctaacaagacaagc---------------------------------------gaagacg
agccggagtggtttcaga-----------------------------------ttcaact
gctgtaatgtttgaac--------------------------------------------
--tcactttgtttaattccgtggggattttccggctgacttatttgataccgatataccc
ttgttatgggcctcaagggaggaaaaattcggcttgtaccgactacttgcagaccaaaag
caatctacaatgcttcgaaggtgttgttatattaagatgctatgatggtacttgatcac-
-----------------------------------------------cgctagctccata
tccggatggtagagcttcctgtcaggtactctggga------------------------
------------tagaacggcaactggataggttgcacccaggcacagttgaagtcaatc
cttattaatcgcttaagggcgctacggtagcagataggatccttgtatgccacaaattgg
acttactctcgctaggtctcgct-------------------------------------
------gcgatcgtttgccaaggggtagtatctatatataatttcaaaggacgatgtaac
tttggaaccgggtacctaacacgattacgtgaaaagtaggccgcgaatccccgcaccagg
tatatattgtcgactcttcggcaggcggatacatgttatgtgccaaaaagctcccatcac
taacgtgctcgcaccaggagtgtccctctaatgcgacggaaaaacaaattgttagcggtc
tcgccatgggtgttatgacctacagtcgtaagcggt------------------------
----ctgcacctaagatcctgtttttcgtttgccccactctgtagttgcactgagctcaa
caa--------------------------------------------ggtctgtgaagga
ggcagaatcgtgtctcgagg
>SEQ15
ctaatggg----------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------tatcggtcacttggggactttccggctggcttatttgataccgatataccc
ttgttatgggcctcaagggaggaaaaattcggcttcttcccactacttgcacaccaaaag
aaatccgcacagttt-------------------------tatgtggatatttgatcac-
--------------------------------------------gcccgacttctccatc
tcaggatgg-----------------tacgcagggagagtaacaattggacgtt------
------------aagcacgggaagtggataggttgcacccaggcacagttgaagtcaatc
cttattaatcgcttaagggcgctacggtagcagataggatccttgtatgccacaaatttg
acttactcacgctaggtctcgct-------------------------------------
------gcgatcgtttgccaaggggtagtatctatatataatttcaaagtacgatgtatc
tttggaaccgggtacctaacacgattacgtgaaaagtaggccgcgaatctccgcaccagg
tatataatgtcgactcttcggcagacggatacaagttatgtgccaaaaagctcccatcac
taacgtgttcgcaccaggagtgtccctctaacgcgacgaaaaaacaaattgttagcgctc
acgccatgggtattttgacttagactcaacggcactaatgtcg-----------------
----gaatatttaagttgct--------------------tgtagttgctgtgcagtgaa
catctgatggaatccttaccacttacatgggcgtcgtattgccgctgggtct--------
----------tgtctcgc--
>SEQ16
ctaatcagac--------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--ctacacgtattggtcacatggggactttccggctggcttatttgataccgatataccc
ttgttatgggcctcaagggaggaaaaattcggcttgttcccactacttgcacaccaaaag
agatccgcacagc------------------------------------atttgataac-
-------------------------------------------tgcacaacagctccatc
tccggatgg------------------------ggagagtaacagttta-----------
------------aaccacggcaactggataggttgcacccaggcacagttgaagtcaatc
cttattaatcgcttaagggcgctacggtagc----aggatccttgtatgccacaaattgg
cctgacgatccctagatt--------------cacggct---------------------
--ggggatgatccctctctttaatgtattcgctatatataatttaaacgaatgttgtatc
tttcgaacc--------------------------gaagtccgggaatgcccgca-----
------------accactctgcagacggatacaagttatgtgccaaaaagctcacatcac
taacgtgttcgcaccaggagtgtccctctaacgcgacgaaaaaacaaattgttagcgctc
aagccatgggtcctttaacttacacgcgacggcaccaatgttg-----------------
----gcatatttaggagcct--------------------tgtagttgctctgcagtcaa
caactgatggtatctttacccattttaagggcgtccctttgccgctggatct--------
----------ggtctcgc--
>SEQ17
caaacaagacaagc---------------------------------------gacgatg
acacggagtggtttcaga-----------------------------------ttcaact
gctgtaatttttgaac--------------------------------------------
-------tcactttgtttaatggggattttccggctgacttatttgataccgatataccc
ttgttatgggcctcaagggaggaaaaattcggcttgttccgactacttgcagaccaaaag
caatctacaatgcttcgaaggtgttgttatatttctatgctatgatgctactggatcac-
-----------------------------------------------cattagatccata
tcgggatggtagagcttcctggcaggtactctggga------------------------
------------tagtacggcaagtggataggttgcacccaggcaccgttgaagtcaatc
cttattaattgcttaagggcgctacggtagcagataggatcgttgtatgccacaaatttg
cttgactagccctaaattttacc-------------------------------------
--ggggaaggtccctttctttaatgtattagctatatataatttaaacgaatcttgtaac
tttccaaccctgttgtaaacacgatgacgggatatgtagtccggggatgcccgcaac---
--------------------gcaggcggatacatgttatgtgccaaaaatttcccatcac
taacgtgctcgcaccaggagtgtccctctaacgcgacgaaaaaagaaattgtaagcggtc
acgcaatggggcttttgataaacagtcgacggcactaatgtgtgcgttaaggggtctgca
gtagcaatatttaagatcctgtttttcgtgccgcccactatgtagttggtctgaaatcaa
caactgactgaatatgtaccccttacaagggccttgctttgccgctgggtctgtttagga
ggcgtcatcttgcctcgggc
>SEQ18
ctaatgag---------------------------------------------------t
gtccggagtggtcccaga------------------------------------------
------------------------------------------------------------
-------------------gtggggactttccggctggcttatttgataccgatataccc
ttgttatgggcctcaagggaggaaaaattcggcttcttcccactacttgcacaccaaaag
caatcttaaaatc--------------------aagatgctatgatggtacttgaaca--
---------------------------------------------------agttccata
tccgaatggtagagcttcctctcaggttctctggg-------------------------
------------aataacggcaagtggataggttgcacccaggcacagttgaagtcaatc
cttattaatagcttaagggcgctacggtagcagataggatccttgtatgccacaaatttg
cgtcacggct--------------------------------------------------
--ggggattgtccggctctttaatgtattagctat-------------------tgtaac
tttcgaacacggt---------------------cgtagtccgggaatgcccgcaac---
-------------cactcttgcagacggatacaagttatgtgccaaaaagctcacatcac
taacgtgttcgcaccaggagtgtccctctaacgcgacgaaaaaacaaattgttagcgctc
acgccatgggtcttttgacttagactcgccg-----------------------------
-----aatatttaagttgct--------------------tgtagttgctctgcagtgaa
caactgatggaatctttaccaattgcatgggcgtcgtattgccgctgggtct--------
----------tgtctcgc--
>SEQ19
ctaat------------------------------------------------------t
gtcatgagtggtgccaga------------------------------------------
------------------------------------------------cctacaagtggt
ggtcactttgtttgatctcgtggggactttccggctggcttatttgataccgatatatcc
ttgttatgggcctcaagggaggaaaaattcggcttgttcccactacttgcagaccaaaag
caatccacaatgctt-------------------agctgctatgatgatactttatcacc
cct------------------------ccttggagcggagctat----------------
----gatggtagtacttcctgtcgtatacactgggagtgg--------------------
------------gagaacggcaagtggatcggttgcacccaggcaccgttgaagtcaatc
cttattaattgcttaagggcgctacggtagcagataggatcgttgtatgccacaaatttg
acttaaca--------------------------agggtgtcccgctgcgatccatttct
aaacggatggtccctttctttaatgtattctcgatatataatttcaacggacgaagtaac
tttgtaagccggctcttaac-------------------tccgcgaatccc---------
-------------ctcttcggcagacgtatacaagttatgtgccaaaaagctcccatcac
taacgtgttcgcaccaggagtgtccctctaacgcgacgaaaaaacaaattgtcagcgctc
acgccatggggcttttg-------------------------------------------
------------------------------------------------------------
-cattgttgagcaatttacccagtataaggttgtctgctcga------------------
--------------------
