>SEQ0
tacataagctctctatgtgtcaaaacgcacttgaagggggctagaactgcggtcagcatc
accacgaacgcgggtatatgaagttttgtcccaaagactagcagggtgattcgctctcta
tgtgcagaaactcttcacccttggtcgttctggtgatcgcactgcagagcagaccgttgc
ttcctctggaactccccacaagtgtaggggacggtgtccactcatcgccttgtagttaat
tataacccactgactcccttagaaatttcttataaattttcggttatcctgaatttctgc
cgttccctcaactctatcgtaaaccggatctggctgatgaggtgttgggaaggtgtggtc
ttctaatgcgaggtgcaattcttgatagattcgctctaacaattcaaagtctacctcaca
gcgcatttgtcgctgaagttaggggcctccaaaggataccctactattttgctggggacc
gggttcaacttaaagcccgagatagtatgtaaccagtcaaagtttgcacttagctgggtg
gaacgtgacggagttccggaatcctgagggcctgaagttggcgtatatcaaataagcgct
tctactgtgctaaagccttccgatgcttcgggggcttcgatacacttaaggtggtcaaga
agctgcggaagtttcgatgtggaacaagggatgccgtagttcgttcttgtgccgtctcag
tgaagcaccgcaggaaggatcccgtgctttaggtaagaacagtaacggcgggcgaacagc
cctggaatcgatcatggctcgttgtattgtctgagacactaggtcgagtgaggctaggct
tactcactatgacacttaatagtgactgattcttcttgctttctgaagattgccctctgg
gggggcaaagtgttaatagatgagctagtaagggtgcttaatgaggagttaagaacgttg
taaacacgaaaattaagccaacataattctttgtcggagccttcgaatgcaacggtacca
ccggttagtcccaggaaccctgacgcatggaggccttaagtctcagcttcacacacagga
gtgcccaagccgcggcgtag
>SEQ1
-----------------------tacatgcttgaagggggctagagctgcggtcagcatc
agcacgaacgcgggtatatgaagtttt--------------------------ctctcta
tgtgcagaaacactttacccttagtcgttctggtgatcgcactgcagagcagaccgttgc
ttccgctggaactctccaccagtgtaggggacggtgtccactcatcgccttgtagttaat
tataacccactgactcccttagaaatttcttataaattttcggttatcctgaatttctgc
ggttccctcaactctatggtaaatcggatctggctgatgaggtgctgggaaggtgtggtc
tactaacgcgagctgcaattcttgatagattcgctctaacaattgaaagtcgacctcacg
gcgc-----------------------tccaaacgataccgtactattttgctggggacc
gggttccacttacagcccgagatagtatgtaaccagtcaaagtttgcacttagctgggtg
gaacgtgacggagttccggaatcctgagggcctgtagttggcgtatatcaaataagcgct
tctactgagctaaggccttgcgatgcttcgggggcttcgatacccttaggggggtcaaga
agctgcgtaagtttcgacgtaggacaagggatgccttagttagttcttatgccgcctcag
tgaagcaccgcaggaaggattccctgcttaagctaagcacagtaacggtgggcgaacagc
cctggaatcgatcatggttcgttgtattgtctgagacactaggtcgagtgaggctaggct
tgctcactatgacacttaatagtgactgattcttcttgctttctgaagattgccctctgg
gggggcaaactgttgatagatgagctagtaagggtgcttaatgaggagttaggaacgttc
taaacacgaaaaagaagccaacataattcttagtcggagccttggaa-------------
--------tcccaggaaccctgacgcatgtaggccttaactctcaacttcacacacagga
gtgcccaagccgcggcgtag
>SEQ2
-----------------------tacatgcttgaatggg---------------------
--cacaaccgcaaatatatgaag------------------------------------a
tttgcagaaacactttacccttagtcgttctggtg-------------------------
ctccgctggaactcaccaccagtgtaggggacggtgtccactcatcgccttgtagttaat
tataacccactgactcccttagaaatttcttataaattttcggttatcctgaatttctgc
ccttccctcaattcgatcgtaacccgaatctggctgatgaggtgttgggaaggagtgggc
ttctaatgcgagtttcaactcttgatagattcgccctaacgattcaaagtctagctcaca
gcgcatttgtcgctgaagttaggggcctccaaaggataccctactattttgctggggacc
gggtccaacttaaagcccgagatagtatgtaaccagtcaaagtttgcacttagctgggtg
gaacgtgacggagttccggaatcctgagggcctgaagttggcgtatatcaaataagcgct
tctactgagctaatgccttgcgatgctttgggggcttcgttactccttgcggggtcaaga
agctgcgtaagtttcgtcgtaggacaagggatgccttacttagttcttatgccgcctcag
tgaagcaccgcaggatggattccctgcttaagcttagcacagtaacgtagggagaacggc
cgtgcaagcgatcatagttcgttgtattgtctgagacactaggtcgagtgaggctcgggt
tactcactatgacacttaatagtgactgattcttcttgctttctgaagattgccctctgg
aggggcacagtgttaatagctgag-----------------------gtgaagagcgttg
taaacaagaaaattaagccaacatatttctttgtcagggccttccca-------------
-----tagtcgcaggaaccctgtcgcaaggaggccgtaaggctcagcttcacacacagga
gtgccctagccgcggcgtag
>SEQ3
-----------------------taaatgcttgaagggg---------------------
--cacaacggcaaatatgtgaag-------------------------------------
attgaataaacactttacccttagtcgttctggtg-------------------------
ctccgctggaactcaccacaagtgtaggggacggtgtccactcatcgccttgtagttaat
tataaccgactgactcccttagaaatctcttataaattttcggttatcctgaatttctgc
cgctccctcaactctaccgtaaaccggatctggcttatgaggtgttgggaatgtgtagtc
ttctaatgcgaggtgaaatactttatagat-------------------tctacctcaca
gcacatttgtcgc------------------tgagatagcctactattttgctggggacc
gggttcacctta-------agatagtatgtaaccagtcaaagtttgcacttagctgggtg
gaacgtgacggagttccggaatcctgagggcctgtagttggcgtatatcaaataagcgct
tctactgagctaagtccctgcgatgcttcgggggcttcgatacccttaggggggtcaaga
agctgcgtaagtttccacgtag----------------------------gcagcctcag
tgaagcaccgcaggatggattccctgcttaggctaa----------------------gc
cttggaatcgagcatggttcgttgtattgtctgagacactaggtcgactgaggctaggct
tactcactatgacacttaatagtgactgattcttcttgctttctgaagattgccctctgg
ggaggcaaacggtcgatagatgagctagtaagggtgcttaatgaggggtaagg-------
------------------------------------gagcctcggaa-------------
--------ttccaggaactctgacgcatgtaggccttaactctgaacttcacacacagga
gtgaccaatccgggc-----
>SEQ4
-----------------------taaatgcttgaaggcg---------------------
--cagaacggcaaatgaataa---------------------------------------
------------------------------------------------------------
-tccgctggaactcaccacgagtgtaggggacggtgtccactcatcgccttgtagttaat
tataacccactgactcccttagaaatttcttataaattttcggttatcctgaatttctgc
cctgccatcaattcgaacgtaacccgaatctggctgatgaggtgttgggaaggagtgggc
t--------------------ttgatagattcgatataacgattcaaagtctagctcaca
gcgcattt---------------------caatggataccccactattttactggggacc
gggtccaacttaaagcccgagatagtatgtaaccagtcaaagtttgcacttagctgggtg
gaacgtgacggagttccggaatcctgagggcctgaagttggcgtatatcaaataagcgct
tctaccgagctaaggccttgcga---------------gatacccttaggggggtcaaga
agctccgtaagtttcaacgtaggcgtagggatgcgttagctagttcttatgccgcctcag
tgaagctccgcaggtaggattccctgcttaagctaagcacagtaacgttgggcgcacagc
cttggaatccatcatgggtcgttgtattgtctgagacactaggtcgagtgaggctcgggt
tactcactatgacacttaatagtgactgattcttcttgctttctgaagattgccctctgg
aggggcacagtgttaatatctgag-----------------------gtgaagagcgatg
taaacaagaaaattaagcctacatatttctttgtcagggccttacca-------------
-----tagtcgcaggagccctgtcgcaaggaggccgtaaggctcaacttcacacacagca
gtgccgtagccgcggcgtag
>SEQ5
-----------------------tacatgtttgaagggggctagtgctgcggtcagcatc
agcacgaacgcgggtatatga---------------------------------------
---------------ctctctatgtgcttctggtgttcgcactgctgagcagactgttac
ttccgctggaactc----tcagtgtaggggacggtgtccactcatcgccttgtagttaat
tataaccgactgactcccttagaaatctcttataaattttcggttatcctgaatttctgc
caatccatcaactctaccgtaaaccggatctggcttatgaggtggtgggaatgtttagtc
ttctaatgcgaggtgaaatactttatagat-------------------tctacctcaga
gcacttctgtcgc------------------ttagatagcctactattttgctggggacc
gggttcatctta-------agatagtatgtaaccagtcaaagtttgcacttagctgggtg
gaacgtgacggagttccggaatcctgagggcctgaagttggcgtatatcaaataagcgct
tctaatcacctggtgccttgcgaagcattgggggcttcgttactcattgcggggtcaaga
agctgcgtaagtttcgtcgaaggacaagggatgcattaattagttcttatgccggctcag
tgaagtaccgcaggatggattccgttcctaaaattaggacagtaacgtaggcagaaccgc
cg------------------gttgtattgtctgagacactaggtcgagtgaggctaggct
tactcactatgacacttaatagtgactgattcttcttgctttctgaagattgccctctgg
atgggcacagtgataatagctgag------------------------------gccttc
taaagaagaa--------------atttctttgtcagggacttccca-------------
----------------tccctgtcgcaaggaggccctaaggctcagctgcacgcacagga
gtgccctaggcgcggcgtag
>SEQ6
-----------------------tacatgcttgaatggg---------------------
--cacaaccgaaaatttatgaag------------------------------------a
tatgcagaaacacttttccct---------------------------------------
-tgcgctggaacttacaatcagtgtaggggccggtgtccactcatcgccttgtagttaat
tataacccactgactcccttagaaatttcttataaattttcggttatcctgaatttctgc
cctgccatcaattcgaacgttacccgaatctggctgatgaggtcttcggaaggagtgggc
c--------------------ttgatagactcaatataacgattcaaggtctagctcaca
gcgcattt---------------------caatggataccccactattttactg------
---------------cccgagatagtatgtaaccagtcaaagtttgcacttagctgggtg
gaacgtgacggagttccggaatcctgcgggcctgaagttggcgtatatcaaataagcgct
tctactgagctaatgccttgcgatgct---------------ctccttgcggggtaaaga
agctgcataagtttcgtcgtaggacaagggatgccttacttagtgcttatgccgcctcag
tgaagcaccgccggatggattccctgcttaagcttagcacagaaacgtagggagaactgc
cgtggaaccgatcatagttcgttgtattgtctgagacactaggtcgagtgaggctcgggt
tactcactatgacacttaatagtgactgattcttcttgctttctgaagattgccctctgg
aggggcatag-------------------------------------gtgaagagcgatg
taaacaagaagattaagcctacatatttcat-----------------------------
----------------------tcgcaggagggccgtaaggctcaacttcacacgcagca
gtgccgtagccgtggcgtag
>SEQ7
-----------------------ttaatgcttgaaggcg---------------------
--tagaaccggaaattaataa---------------------------------------
------------------------------------------------------------
-gccgccggaa--------cagtgtaggggacggtgtccactcatcgccttgtagttaat
tataacccactgactcccttagaaatttcttataaattttcggttatcctgaatttctgc
tattccatcaactctaccgtaacccgcatctggcttatgaggtggtgggaatgtatagtc
ttctaatgcgatgtgaaagactcgataggt-------------------tcgacctcaga
gcagttctgtcgc------------------atagatagcctactattttgctggggacc
gggttcatctta-------agatagtatgtaaccagtcaaagtttgcacttagctgggtg
gaacgtgacggagttccggaatcctgcgggcctgaagttggcgtatatcaaataagcgct
ccgactgtgctaaagcctcccgatgcttcaggggattcgataaactaaaggtggtcaata
agctgaggaagtttcgacgtggaacaagggatgccgtagcttgttattgtgccgtcccag
tgaagcaacgcaggtagg-----------------agcacagtaacggcgggccaacagc
cctgggat------------gttgtattgtctgagacactaggtcgagtgaggctaggct
tgctcactatgacacttaatagtgactgattcttcttgctttctgaagattgccctctgg
cagggcaaggtgtaaatagatgagctagtgaggctgcctcatgaggagttaagaacgttg
taaacacgaaaattaagccaccataattctatgtcggagccttcgaatgcaacggtacca
ccggttagtcccaggaaccctgacgcgtggaggccttaagtctcagcttcacacagagga
gtgcccaagccgcggcgttg
>SEQ8
-----------------------tgcctgattgaagggggctagagctgcggt-------
-----------------------------------------------------ctctcta
tgtgcagaaacactttacccttaggcgttctggtcatcgcactacagagcagactgttgc
ttccgctcgaactctccaccagtgtaggggacggtgtccactcatcgccttgtagttaat
tataacccactgactcccttagaaatttcttataaaatttcggttatcctgaatttctgc
cctgccatacattcgaacgtaacccgaatctggctgattagctgtggtgcaggagtgggc
t--------------------ttgatagattggatataaccattcaaagtctagctcgca
gcgcattt---------------------caatggagaccccactattttaccggggacc
gggtccaacttaaagcgcgagatagtatgtaaccagtcaaagtttgcacttagctgggtg
gaacgtgacggagttccggaatcctgcgggcctgaagttggcgtatatcaaataagcgct
t-----------------------acttcgggggcttcgatacagttaaggtggtcaaga
agctgcggaagtttcggtgtggagcaagggattccgtagttcgctcttttgccgtctcag
tgaagcaccgcaggaaggatcccgtgctttaggtaagcacagtaacggcgggcgaacagc
cctgcgctcgatcatggctcgttgtattgtctgagacactaggtcgagtgagtctcgggt
tactcactatgtcacctaatagtgactgattcttcttgctttctgaagattgccctctgg
ctgggtacagtgataatagctgag------------------------------gccttc
taaagaagag--------------atttctttgtcagggacttccca-------------
----------------tccctgtcgcaatcaggccctaaggctcagctgcacgcacagaa
gtgccctaggcgcggcgtag
>SEQ9
-----------------------taaatgg------------------------------
--cacaacggcaaatgaataa---------------------------------------
---------atactttaccct---------------------------------------
-tcctctggaattcaacacaagtgtaggggccggtgtccactcatcgtcttgtagttaat
tataacccactgactcccttagaaatttcttataaattttcggttatcctgaatttctgc
cctgccatcaattcgaacgcaacccgaatctagctgatgatgtgttgggaaggagtgggc
t--------------------ttggtagactcgatatagctattcaa-------------
-----------------------------caatggataccccactattgtactggggacc
gggtc---------------gatagtatgtaaccagtcaaagtttgcacttagctgggtg
gaacgtgacggagttccggaatcctgagggcctgaagttggcgtatatcaaataagcgct
tctactgagctaagtccctgcaatgcttcgggagcggcgataccttgcgtggggtcagga
agctgcgtaagtttccacgtag----------------------------ccagcctcag
tgaagcaccgccgaatggattccttgcttaggcta-------------------------
--------cgaggatggttcgttgtattgtctgagaccctaggtcgagtgaggctcgggt
tactcactatgacacttaatagtgactgatttttcttgctttctgaagattgccctctgg
aggggca----------------------------------------gtgattggcgttg
tacacaggaagaataagccaacatatttctgtgtcagggccttccca-------------
-----tagtcgcaggaaccctgtcgcaaggaggccgtaaggctcagcttcacacacagga
gtgtcctagccgcggcgtag
>SEQ10
-----------------------tcaatg---gaaggcg---------------------
--cagaccggcaaatgaataa---------------------------------------
------------------------------------------------------------
-tccgcaggaattcatcacgagtgtaggggacgttgtccactcatcgccttgtagttaat
tataactcactgactcccttagaaatttcttataaattttcggttatcctgaatttctgc
cctgccatacattcgattcgctgtcgtgcggga---------------------------
--------------------------------gatataaccatccaaagtctcgcacaca
gcgcattt---------------------caatggagaccccgctattttaccggggacc
gggtccaacttaaagcg--cgatagtatgtaaccagtcatagtttgcatttagctgggtg
gaacgtgacggagttccggaatcctgagggcctgaagttggcgtatatcaaataagcgct
tctactgcgctaaggccttgcgatgcttcgggggtttcgatacccttaggtggctcaaga
agctgcgtaagttccgacgtaggacaggggatgccttagttagttcttatgcagcctcag
tgaagtaccgcaggaaggatttcctgcttaagctaagcacaggaacggtagacgaacagc
catggaatccttcatgggtcgttgtattgtctgagacactaggtcgagtgagtctcgggt
tactcactatgtcacctaatagtgactgattcttcttgctttctgaagattgccctctgg
ctggggacagtgatactag-----------------------------------gccttc
taaagaagag--------------agttctttgtcagggacttccga-------------
----------------tccctgtcgcaatcaggccc------------------------
------------cggcgtag
>SEQ11
-----------------------taaatgcttgaaggcg---------------------
--cagaccggcaaat---------------------------------------------
------------------------------------------------------------
-tccgctgcaactcaccacgagtgtaggggccggtgtccactcatcgccttgtagttaat
tataacccactgactcccttagaaatttcttataaattttcggttatcctgaatttctgc
cgttccgtcaactctatcgtaact------------------------------gtggtc
ttctaatgcgaggtgcaattcttgatagattcgctctaacaattcaaagactacctcaca
gcgcatttgtcgctgaagtaaggggcctccaaagaataccctactattttcctggggacc
gggttcatccaaaagcccgagctagtatgtaaccagtcaaagtttgcacttagctgggtg
gaacgtgacggagttccggaatcctgagggcctgaagttggcgtatatcaaataagcgct
tctac-----------------------------------------------------gg
agctccgtaagttacaacttaggagtcgggatgcgctagctagttctattgccgcctcag
tgaagctcc--------------------aagctaagcacagtaaagttgggcgaacagc
cttggaatccatcatggcttgttgtattatctgagacactaggtcgagtgaggctcgggt
tactcactatgacacttaatagtgactgattcttcttgctttctgaagattgccctctgg
atgggcacagtgataatagctgag------------------------------gccttc
taaagaagga--------------atttctttgtcaggcacttccca-------------
----------------tccctgtcgaaaagaggacctaaggctcagctgcacgcacagga
gtcccctaggcgcggcgtag
>SEQ12
-----------------------taaatgg------------------------------
--cacaacggcaaatgaataa---------------------------------------
------------------------------------------------------------
--------atactttaccctagtgtaggggccggtgtccactcatcgtcttgtagttaat
tataacccactgactcccttagaaatttcttataaattttcggttatcctgaatttctgc
agctccctcaactctaccgtaaaccggatct-----------------------------
ttctaatacgaggtaaaattctttatagat-------------------tcgacctcaca
gcacatttgtag----------------------------ctgatattttgccggggacc
tggttcacctca-------agatagtatgtaaccagtcaaagtttgcacttagctgggcg
gaacgtgacggagttccggaatcctgagggcctgtagttggcgtatatcaaataagcgct
tccaattcg-------------------------------------------ggggcaga
agcggcataagcctccacgtag----------------------------gcagccttag
-------------------------------------------------------aaagc
cttggaatcgagcatggttcgttgtattgtctgaggcactaggtcgagtgaggctaggct
tgctcactatgacacttaatagtgactgattcttcttgctttctgaagattgccctctgg
ggaggcaaagtgttaatagatgagctagtaagggtgcttaatgaggaggtaagaacgttt
taaacacgag-----------------------------ccttcgtatgcaacggtaccg
ccgcttagtcccaggaaccctgacgcatggaggccttaagtctcagcttccctcactgga
gtgcccaagcgcccgcgtag
>SEQ13
-----------------------tacatgcttgaagggggctagagcggcggtcatcagc
agca-------------------------------------------------ctctgga
tgtgctgagacactttaccgttagtcgttctggcgatcgcactgccgagcagaccgtagc
ttccgccggaactctccaccagtgtaggggacggtgtccactcatcgccttgtagttaat
tataacccactgactcccttagaaatttcttataaattttcggttatcctgaatttctgc
agctccctcaactctaccggcatccgcagct-----------------------------
-------------taaaattc----------------------------tcgacctcaca
gcacatttgtag----------------------------ctgatattttgccggggacc
gtgttcacctca-------agatagtatgtaaccagtcaaagtttccacgtagctgggtg
gaacgtgacggagttccggaatcctgagggcctgaagttggcgtatatcaaataagcgct
tctactggct--------------------------------ctcattgcggggtaaaga
agccgcaaaagtttcgtggtaggacaaggtatgcctgacttagttcagatgccgccccag
tgaagcaccgccggagggattccctgcttaagcttagcacagaaatgtagggagaactgt
cgtggaaccgatcatacttcgttgtattgtctgagacactaggtcgagtgaggctaggct
tactcactatgacacttaatagtgactgattcttcttgctttctgaagattgcccgctgg
ctgggtacagtgataatagctgag------------------------------gccttc
aaaagaagag--------------gtatctttatcagggaattccca-------------
----------------tccctgtcgcaatcaggccctaaggctgagctgcgcgcacagaa
a-----------------ag
>SEQ14
-----------------------tacatgttggaaggggacgagtgctgcggtcagcatc
agcacgaacgcggctgtatga---------------------------------------
--------------------------ctctatacctgcgcattgctgtgcagactgttac
tttcgctggaactc----tcagtgtaggggacggtgtccactcatcgccttgtagctaat
tataacccactgactcccgtagaaatttcttataaattttcggttatcctgaatttctgc
cgctcccttaactctacctttaaccggatctgg----------------------aagtc
ttctaaagcgaggtgaaataccgtatagat-------------------tctacctctca
gcacatttgtcgc------------------tgagttagcctactattttcctggggacc
gggttcaccgta-------agatactatgtaaccagtcaaagtttgcacttagctgggtg
gaacgtgacggagttccggaatcctgagggcctgaagttggcgtatatcaaataagcgct
tctactgagctaatgccttgggatgct---------------------------------
--------------ctcagtaggacaagggat-----------cccttttgccgcctcag
cgaaacacggccggatggattctctgcttaagcttagcacagaaacgtcgggagaactgc
cgtggaaccaatcatagttcgttgtattgtctgagacactaggtcgactgaggctaggct
tactcacgatgacacttaatagtgactgattcttcttgctttctgaagattgccctctgg
ggaggcaaacggtcgatagatgag------------------------------------
-----------------------------------ggagcctcggaa-------------
--------ttccagcgactctgacgcatgtaggccttaactctgaacttcacacacagga
gttaccaatccg-------g
>SEQ15
tacataagctctccatgtgtcaaaacgcacttcaagggggctagaactgaggtaagcatc
accatgaacgtgggtataggaagtcttgtcccaaagactagcagggtgattcgctctcta
tgtgcagaaa----------------ctcttccccatcgcactgcagagcagaccgttgc
ttcctgtggaactcccctcaagtgaaggggacggtgtccactcatcgccttgtagttaat
tataaccgactgactcccttagggatctcttataaattttcggttatcctgaatttctgc
tactc-----------------------------------gttggtgggaacgtatagtc
ttctaatgcgatgagaaagactcgataggt-------------------tcgacctcagt
gcagttctgtcgc------------------atcgatagcctactattttgctggggacc
gggttcatctta-------agatagtatgtaaccagtcaaagtttgcacttagctgggtg
gaacgtgacggagttccggaatcctgagggcctgaagttggcgtatatcaaataagcgct
tctactt---------------------------------------------gctaaaga
agacccaaaagtttcgtggtaggacaaggtatggctgacttagttgagatgccgccccag
tgaagcaccgccggggggattccctgcttaagtttaacacagtaatgtagggagaactgt
cgtggaatcgatcatacttcgttgtattatctgagacactaggtcgagtgaggctcgggt
tactcactatgacacttaatagtgactgattcttcttgctttctgaagattgccctctgt
agaggcatagtgaaga--------------------------------------gcgatg
taaataaaaagagtaatcctacctatttcat-----------------------------
----------------------ttgcaggagggccgtaaggctcaacttgacatgcagca
gtgtcgtaccggtggcgtag
>SEQ16
-----------------------tacatctttgaagggg---------------------
---actagtgcgggtatatga---------------------------------------
---------------ctctctatgtgcttctggtgttcgcactgcagagcagactgttac
ttccactggaactc----tcagtgtaggggacgttgtccactcatcgccttgtagttaat
tataattcactgactcccttagaaatttcttataaattttcggttatcctgaatttctgc
tattccattgactctaccgtaacccgcatctggcttatgagatggtgggaatgtatagtc
atctaatgcgatgtgaaaaactcggtaggt-------------------tcgacctcaga
gcagttttgtcgc------------------atagatagcctacgagtttgctggg----
-------------------ggatagtatgtaaccagtcaaagtttgcacttagctgggtg
gaacgtgacggagttccggaatcctgagggcctgaagttggcgtatatcaaataagcgct
tc---------------------------agaggattcgataaactaaaggtgctgaacc
agctggggaagtttcgacgtggcacaagggatgccgtagcttgttattgtgccctcccaa
tgaagcaacgcaggtag-----------------aagcgcagtaaaggcgggcccaaagc
cctgggat------------gttgtattgtctgagacactaggtcgagtgaggctaggct
tgctcactatgacacttaatagtgactgattcttcttgctttctgaagattgccctctgg
ctgggtacagtggtaatagctgag------------------------------tccttt
ttga--------------------------ttgtcagggacttccct-------------
----------------tccctgtcgcattcacgccctaaggctcagctgcacgcacagaa
gtgcgctaggcgcggcgtag
>SEQ17
-----------------------ttaatgcttgagggcg---------------------
--tagaaccggaaagtaataa---------------------------------------
------------------------------------------------------------
-gccgccggaa--------aagtgaaggggacggtgtccactcatcgccttgtagttaat
tataaccgactgactcccttagggatctcttaaaaattttcggttatcctgaatttctgc
cctaccctcaagtcgatcgtcacccgaatctggctgatggggtgtggggaaggagagggc
ttctaatgcgagtttcaactcttcatagattcgtcctcacgattcaaagtctagctcaca
----------------------------------------ctactattttactgggaacc
gggtccaacttaaagcccgagatactatgtaaccagtcaaagtttgcacttagctgggtg
gaacgtgacggagttccggaatcctgagggcctgaagttggcgtatatcaaataagcgct
tctaatcacctggtgccttgcgaagcattggggg---------------------caaga
agctacgtaagttgcgtcgaa--------------ttatttacttcttatgtcggctcag
tgaagtacc-------------------tgaagttaagacagtaacgtag----------
--------tcagcaccgccggttgtattgtctgagacactaggtcgagtgaggctaggct
tgctcactatgacacttaatagtgactgattcttcttgctttctgaagattgccctctgg
attggcacagtgataatggcttag------------------------------gccttc
taa--------------------------tttgccaggcacttccca-------------
----------------tccctgtcgaa------------------actacacgcacagga
gtcccctaggcgcggcgtag
>SEQ18
-----------------------------tttggaaggc---------------------
---------gcggctgtatga---------------------------------------
--------------------------ctctatacctgcgcattgctgtgcagactgttgc
tttcgctggaactc----tcagtgtaggggacggtgtccactcatcgccttgtagttaat
tataacccactgactcccttagaaatttcttataaattttcggttatcctgaatttctgc
tcttctctcaattcgatcgtaacccaaatctggctgatgaggtgttgggaaggagtgggc
ttctattgcgagtttcaactcttgatagattctccctaacgattcaaagtctagctcaca
gcgcatatgtcgc---------------------------tgaagattttgctggggacg
gggaccaacttacagcccgagatactatgtaaccagtcaaagtttgcacttagctgggtg
gaacgtgacggagttccggaatcctgagggcctgaagttggcgtatatcaaataagcgct
tccaattcgc-------------------------------------------gggaaga
agcggcataagccgc---------------------------------------------
------------------------------------------------------agcagc
tttggaatcgagcagggtgccttgtattgtctgagacactaggtcgagtgaggctcgggt
tactcactatgacacttaatagtgactgattcttcttgctttctgaagattgccctctgg
atggacacagtgataatagctgag------------------------------gccttc
tatagaacga--------------atttctttgtcaggcacttccc--------------
-----------------ccctgtcgaaaagaggacagaaggctcagctgcacgcacagga
gtcccctaggcgcggcgtag
>SEQ19
-----------------------taaatgcttgaaggcg---------------------
--cagaaaggcaaatgaataa---------------------------------------
------------------------------------------------------------
-tccgctggaactcaccaagagtgtaggggccggtgtccactcatcgtcgtgtagttaat
tataacccactgactcccttagaaatttcttataaattttcggttatcctgaatttctgc
cgctcccttaactctacctttaaccgcatctgg----------------------aagtc
ttctaaagccaggtgaaataccgtagaaat-------------------tctacttctca
gcac-----------------------------------cctactattttcctggggacc
gggttcactgta-------agatagtatgtaaccagtcatagtttgcatttagctgggtg
gaacgtgacggagttccggaatcctgagggcctgaagttggcgtatatcaaataagcgct
tcgactgagctaagcccttgcgattcc-----------------tttaggggggtcaaga
agctgcctcagtttcgacgtaggacaagggacgccttagttagttcgtatggcgcctcaa
tgaag---------------tccctgcttaagctaagcacagtatcggtaggcaaccagc
c-----------------ctgttgtattgtctgagaccctaggtcgagtgaggctcgaga
tactcactatgacacttaatagtgactgatttttcttgctttctgaagattgccctctgg
ggaggcaaacggccgatagatgag------------------------------------
-----------------------------------ggagcctcggaa-------------
--------tttcagcgactcttacgcatggaggccctgactctgaacttaacacacagta
gttaccaatccg-------g
