>SEQ0
actgtttctcgggacgatgctagatatcggaccgctgctacacaaagacagcagacaggg
cggagaccaggaccctgattcattggggcgggcttgcggcgggatagccagggcagggtg
gcatacggagcggaccgataaaatatttccgtagcgcgtaccgcttctttagcaagtacc
tttgacatatttgtaccaacattcacacaccgggtaacggagataaaaacaaacgcgagc
gcttagtttagtcgttcgtctactaacgaaacctcactggtatgaattcagagcacctac
taattatatcctgaagatagcccgtggcagcaacgaggaacgaagacccttgccgttatc
aacatctctcgatcctatgaccctaatgtatttctactcattcataagtgcgtttagagg
ttgttatccaacaatagccgtcaattccaacaaccatggctcccgaggccggctaacagg
gttctccggcgaggctttcacgagaaaccgcttagggttcgtggcgatccgtgagcccgt
tattggaatcgttattattggaaatcgaagcgttaatataggcactcatagtgactggtg
ttgggatttacctagcaagccacaatggacggaacggctgacgaagtttgcgacaaggct
gcaactaactcccggtcagcgtaaatttgtcgtctcaaccttagaaataaggtctccatt
cttttattaatgggtttaggccatgatctgttcgggatgcaaagctttttgagtacgagt
actgctctaatatgactctagctatatatctgggcttacattattcgaacactaatacat
gatctctcgtatgctcactcaccgctttaatccagtgcggaaaactcactgtgcaacctt
atccagagcaggacttgccttcagccttgagcgaatcttaattaagattaaagttggaat
gtaaacgagatttctcccatgtgcaacagaaatgccgcggcccacgttcggctatagacg
cgtggagaccacaagacttgttgggtcaacgtcccagcaattgccttgcgttcttatttc
ccggggaccatcacaagtga
>SEQ1
actgattctagggaccatgctagatatcgggccgcttctacacaaagacagcagacagag
cggagaccaggaccctgatt------------------gcgggatagccagggcagggtg
gcat----------------aaatatttccgtagcgcgtaccgcttctttcg--------
----------------caacattcacacagcgggtaacggagataaaaacaaacgcgagc
gcttagtttagtcgttcgtctactaacgaaacctcactggtatgaattcagagcacctac
taattatatcctaatgatagcccgtggcatcaacgaggagcgaagacccttgc-------
--------tcgaacctatgaccctaatgtatttcaactcgttcataagcgcatttagagg
ttgttaaccgacagtagccatcaattccaaaaaccatggctccccaggcaggctaacagg
gttctccggcgaggctctcacgagaaaccgcttagggttcgtggcgatccgtgagcccgt
tattggaatcgttattattggaaatcgaagcgttaatataggcactcatagtgactggtg
ttgggatttacctagcaagccacaatgtacggaacggatgacgaggtttgcgataaggct
gcaactaactcccggtcagcgtaaatttgtcgtctcaacctcagaaataaggtttccatt
ctttta---------------------ctcttaggaatgcaaagctctatgaggacgact
actgctctaatataactctagctatatatctgggcttacattattcgaacactaatacat
gatctctcgtatgctcactcaccgctttaatccagtgcggaaaactcactgtgcaacctt
atccagagcaggacttgccttcagccttgcgcgaatcttatttaagattaaagctgcaat
gtaaacgagagttctccc------------------------------------------
------------atgtgtggttgggtcaacgtcccagcaatagctttgggttcttatttc
ccggggaccatcacacgtta
>SEQ2
actgattctagggaccatgctagatatcggtccgcttctacacaaaggaccctga-----
------------------------------------------------ttgggcagggtg
gcat----------------aaatacttccgtagcgcgtaccgcttc-------------
----------------caacattcacacagcgggtaacggagataaaaacaaacgcgagc
gcttagtttagtcgttcgtctactaacgaaacctcactggtatgaattcagagcacgtac
aa--------------------------------gggaaacgcagacccctgcccatatc
aacgtctctcgatccgatgaccctaat------------attcattagtgcggttagagg
ttgttatc---------------------------atggctcccgaggccggctaagag-
--------------------cgagaaaccgcttagggttcgtggcgatccgtgagcccgt
tattggaatcgttattattggaaatcgaagcgttaatatagccactcatagtgactggtg
ttgggatttacctagcaagccacaatgtacgcaacggatgaagaggttagcgatgaggct
-----------------------------tcgtctcaacctcagaaacatggtttccatt
attata---------------------ctcttaggaatgcaaagctctatgaggacgact
actgctctaatataactctagctatatatctgggcttaccttattcgaacactaatacat
gatctctcgtatgctcactcaccgctttactccagtgcggaaaactcactgtgcaacctt
atcccgagcagcacgtgccttcagccttgcgcgaatcttgtttaagattaaagct-----
------------------------------------------------------------
--------gcccacgtgtggttaggtcaaggtccgatcaatagcattgggttcttatttc
ccggggaccatcacacgtta
>SEQ3
ggtgattctagggaccatgctagatatcgggccgcttctacacaaagactgcagt-----
------------tcctgatt------------------gcgggctagccag---------
--------------------gaatatttccgtagcgcgtgccgcttctttcg--------
----------------caacattcacacaccgggtaacggagacaaaaacaaacgcgagc
gcttagtttagtcgttcgtctactaacgaaacctcactggtatgaattcagagcacctac
taattatatcgtaaggatagcccgtggcatcaacgaggagcgaagaccgttgc-------
--------------------------tgtatttcaactcgttcacaagcgcatttagagg
ctgttaaccgacagtagccatcaagttcaaaaactatggctcccgaggcatgctaacagg
tttctccggcgaggctctgacgagaaaccgcttagggttcgtggcgatccgtgagcccgt
tattggaatcgttattaatggaaatcgaagcgttaatataggcactcatagtgactggtg
ttgggatttacctagcctgccactatgtacgcaacgagtgaagcgtttagcgatgaggct
-----------------------------tcgactcaacctcagaaacaaggtttccatg
attata----------------------------gaatgcaaagctctatgaggacgact
actgctctaatataactctagctatatatctgggcttacattattcgaacactaatacat
gatctctcgtatgctcactcaccgctttaatccagtgcggaaaactcactgtgcaacctt
atccacggcaggacttgccttcagccttgagcgaatcataattaagattagagttggaat
gtaaacgagatttctctc-----------------cgcggcccccgctcgactatagacc
cttggaggccacaaggcttgttgggtcaacgtcccagcaattgccttgcgttcttgtttc
ccggg---------------
>SEQ4
gctgtttctcgggacgatgctagatatcggaccgctgatacacaaaggcagcagtcaggg
cgggg-----------------------ctagcttgcggcgggatagccagggcggggtg
gcatacggagcggaccgacaaaatccttctgtagcgcctacctcttctttagcaggtacc
tttgacatatttg---taccattcacacagcgggtaacggagataaaaacaaacgcgagc
gcttagtttagtcgttcgtctactaacgaaacctcactggtgtgaattcagagcacgtac
ta--------------------------------gggaaacgcacactcccgccaatatc
cacgtctctcgatccgatgaccctaat------------attcattagtgcgcttagagg
tttttatc---------------------------atgggtcccgaggccggctaagag-
--------------------cgagaaaccgcttagggttcgtggcgatccgtgagcccgt
tattggaatcgttattattggaaatcgaagcgttaatataggcactcatagtgacgggtg
tttggatttacctagcaagccacaatgtacgcaccggatgaaga----------------
-----------------------------------tgacctcggaaacagggcttccatt
atta-----------------------ctcttaggaatgcaaagctctatggggacgact
gctgctctaatataactctagctatatatctgggcttacattattcgaacactaatacat
gatctctcgtatgctcactcaccgctttaatccagtgcggaaaactcactgtgcaacctt
atccacggcagca-------------------agttcataattaagattagagttggaat
ttacacgagatttctctc-----------------cgcggcccccgctcgactatatact
cttggaggccgcaaggcttgttggttcaacgtccccgcaagtgccttgcgttcttggttc
tcggg---------------
>SEQ5
actgattcaaggtacaatgctagagagcgg------------------------------
---agaccagtaccctga--------------------gcgggatagccaacgcagggtg
gcat----------------aaatatttccgttgcgcgtaccgcttctttcg--------
----------------caacattcacacaccgggtaacggagataaaaacaaacgcgagc
gcttagtttagtcgttcgtctactaacgaaacctcactggtatgaattcagagcacctac
ag--------------------------------tggaaacgcagacccctgcccatatc
aacgtctctcgatccgaggaccctaat------------attctttagcgcggttagagg
ttgttatc---------------------------atggctcccgaggccggctaagag-
--------------------cgagaaaccgcttagggttcgtggcgatccgtgagcccgt
tattggaatcgttattattggaaatcgaagcgttaatatagccactcatagtgactggtg
ttgggatttacctagcatgtcccaatggaaggaacgactgccgaagattgcaacaaggct
gcaactaacgccaggtctgcgt---------------accttagaaataaggtctccact
cttttattaatgggtttaggccatgatctgttcgggatacacagctttttgagtacgagt
actgctcaaatatgactctagctatatatctgggcttacattattcgaacactaatacat
gatttctcgtatgcttactcaccgctttaatccagtgcggaaaactcactgtgcaacctt
atccagagcaggagttgcctacagccttgagcgaatcttaattaaaattaaagttggaag
gtcaacgagatttctccc--------------------atgtgaaacagagctaaagacg
cgtggagaccacatgacttcttggctca------------------------------tc
ccggggaccaccacaagtga
>SEQ6
ggtgattcta-----------------------gcttctacacaaagactgccgt-----
------------------------------------------------------------
-------------------------------tcgcgattgccgcttctttcg--------
----------------caacattcacacagcgggtaacggagataaaaacaatcgcgagc
gcttagtttagtcgttcgtctactaacgaaacctcactggtatgaattcagagcacgtac
taactatatcgtaaggatagcccgtggcatcaacgaggagcga-----------------
----------------------------------tactcgtccacaaacgcatttagagg
ctgttaaccgacagtagccatcaagttcaaaaactatggctcccggggcatgctaacagg
tttctgcggcaaggctctggcgagaaaccgcttagggttcgtggcgatccgtgagcccgt
tattggaatcgttattaatggaaatcaaagcgttaatataggcactcatagtgactggtg
atggaatttacctagcaagccacaatgtacggaacggatgacgaggtttgcgataaggct
gcaactaactcccggtcagcgtaaatttttcgtctcaccctcagaaataaggtttccatt
gtttca---------------------ctcttaggaatgcaaagct--------------
-----tctaatatcactctagctatatatctgggcttacattattcgaacactaatacat
gatctctcgtatgctcactcaccgctttaatccagtgcggaaaactcactgtgcaacctt
atccacggtagca-------------------agctcataattaagatcagagttggaat
ttacaacagatttctctc-----------------cgcggcccccgctcgactatatact
ctttgtgggcgcaaggcttgttggttcaacgtccccgcaagtcatttgcgttcttggttc
tccgg---------------
>SEQ7
gctgtttctcgggacgatgatagatatcggacagctgctacacaaaggcagcagtcaggg
cgggg-----------------------cgagcttgcggcgggatagccagggcggggtg
gcatcccgtgcggaccgacaaaatccttctgtagcgcctacctctcccttagttg-----
----------------taccattcacacagcgggtaacggagataaaaacaatcgcgagc
gcttagtttagtcgttcgtctactaacgaaacctcactggtatgaattcagagcacgtac
aa----------------------------------------------------------
-gggtctctcgaaccgatgaccctaat------------attcactattgcggttagagg
ttggtatc---------------------------atgactcgcgaggccggctaagag-
--------------------ccagaaaccgcttagggttcgtggcgatccgtgagcccgt
tattggaatcgttattattggaaaccgaagcgttaatataggcactcacagtgactggtg
tggcgatttgcctagaaagccacaatggactgaacg-------------gcgacaagggt
gcaactaactcccggtctg----------------caaccttagaaacaaggtccccagt
cttttattaatgggtttaggccatgatctgttcg------------------ggacgagt
actgctctaatattactctagctatatatctgggcttacattattcgaacactaatacat
gatctctcgtacgctcactcaccgctttaatccagtgcggaaaactcactgtgcaacctt
acccacggtagca-------------------agctcaaaattaagatcaaagttggaat
ttacaaaagctttctctc-----------------agcggcccccgct------------
--------gaacaaggcttgttggttcaacgt-----------------------ggttc
tccgg---------------
>SEQ8
ggtgattcta--------------------------------------------------
------------------------------------------------------------
-----------------------------------gctcgccgcttctttcg--------
----------------ctacattcacagagcgggtaacggagataaaaacaatcgcgagc
gcttagtttagtcgttcgtctactaacgaaacctcactggtatgaattcagagcacgtac
aaactatatcttaaggatagcccgtgg---------------------------------
----------------------------------tactcgtccacacacgcatttcgagg
ctgttaacctacagtcgccatcaaggtcaaaaactatgactcccggggcatgctaacagg
ttcctgcggcaaggctattgcgagaaaccgcctagggttcgtggcgatccgtgagcccgt
tattggaatcgttattaatggaaatcaaagcgttaatataggcactcatagtgactggtg
atg-------------------------------------acgaggtttgcgataaggct
gcaactaagtccc----------------tcgtctccccgtttgaaataaggtttatatt
gtttca---------------------ctcttaggaatgcaaag----------------
-----------------ctagctatatatctgggcttacattattcgaacactaatacat
gatctctcgtatgctcgctcaccgctttaatccagtgcggaagactcactgtgcaacctt
acccacggtagca-------------------agctcaaaattaaggtcagagttggaat
ttacaaaagctttctctc-----------------agcggaccccgct------------
--------gaacaaggcttgttggttcaacgt-----------------------ggctc
tccga---------------
>SEQ9
actgattcaaggtacaatgcgagagag---------------------------------
--------------------------------------gcgggataaccaacgcagggtg
gcat--------------------------------actactgcttctgtcg--------
----------------caaaattcacacagcgggtaacggagataaaaacaaacgcgagc
gcttagtttagtcgttcgtctactaacgaaacctcactggtatgaattcagagcacgtac
taatgatatcctaatgagagcccgtggtatcaacgaggagcgaagacccttgc-------
--------tcgaaactatgaccctaatgtatttcacctcgttgataatcgcatttagagg
ttgttaaccgacagaagccatcaattccaaaaaccgtggctccccaggcaggctatcagg
gttctccggcgaggctctcacgagaaaccgcttagggttcgtggcgatccgtgagcccgt
tattggaatcgttattattggaaatcgaagcgttaatataggcactcatagtgacgggtg
tttggatttacctacgaagacacaatgtacgcaccggctg--------------------
-------------------------------------acctcggaaacagagcttccatt
atta-----------------------ctcttaggaatgctaagctctatggggacgatt
gctgctctaatataactctagctatatatctgggcttaccttattcgagcactaatacat
gatatctcgtatgctcactcaccgctttactccagtgcggaaaactcactgtgcaacctt
ctccacggtagca-----------------------aataattaaggtcagagttggaat
ttacgacagagttttctc-----------------cgcggcccaagctcgaccatacact
ctttgtgggcgcaaggcttgttggtacaacgtcgccgcaagtcatttgcgtttttggttc
tccgg---------------
>SEQ10
actgattcaaggtacaatgctagagagcgg------------------------------
---agaccagtaccctga--------------------gcgggattgccagcgcagggtg
gcat----------------aaacatttccgttgcgcgtaccgcttatttgg--------
----------------caacattcacacaccgggtaacggagataaaaacaaacgcgagc
gcttagtttagtcgttcgtctactaacgaaacctcactggtatgaattcagagcacctac
taactatatcgtagggatagcacgtggcatcaacgaggagcgaagaccgttgc-------
--------------------------tgtaattctactcgatcacaagtgcattcagagg
ctgttaaccgtca----------------------gtggctcccgaggcatgctaacagg
tttctccggcgaggctctgacgagaaaccgcttaggtttcgtggcgatccgtgagcccgt
tattggaatcgttattaatgcaaatcgaagcgttaatataggcactcatagtgactggtg
ttgggatttacctagcatgtcccaatggaaggaacgactgcctaagattgcaacaagcct
gcaactaacgccaggtccgcgt---------------accttagaaataaggtgtccact
ctgtaattaatgggtttaggccatgatctgttcgggatacactgcttgttgaatacgagt
tctgctcacctatgactctagctatatatctgggcttacattattcgaacactaagacat
gatttctcgtatgcttactcaccgctttaatccagtgcggaaaacgcactgtgcaacctt
atccagagcaggacttggcaccagcattacgcgaatctaatttaagattaaagctccaat
ctaaacgagagtt-----------------------------------------------
-----------------tggttgggtcaacgtcccagcaatagcttcgggttcttatttc
cagggggccatcacacgtta
>SEQ11
actgattttagggaccatg------------------------aaagacagcagacagag
cggagaccaggaccctgact------------------gcgggatagccagggcggggtg
gcat-------------------------agtagcgcgtaccgc----------------
----------------caacattcacacagcgggtaacggagataaaaacaaacgcgagc
gcttagtttagttgttcgtctactaacgaaacctcactggtatgaattcagagcacgtac
ag--------------------------------tggaagcgcagacccctgcccatatc
gacgactcacgatccgaggaccctaat------------attcttcagcgcggttagagg
gttgtatc---------------------------atggctcccgaggccggctatgag-
--------------------cgagaaaccgcttagggttcgtggcgatccgtgagcccgt
tattggaatcgttattattggaaatcgaagcgttaatatagccactcatagtgactggtg
ttgggatgtacctagcaagt--------------------acgaagtttgtgccaaggct
gcaagtaactgctcgtcagcaaaaatttgtcttctcaaccttagaaaaaatttctgcatt
ccactattaatgggattaggacatgatctgttcggaatgcaaaggtttttgagtacgagt
actgctctaatatgactctagctatatatctgggcttacattattcgaacactaatacat
gatctctcgtatgctcactcaccgctttaatccagtgcggaaaactcactgtgcaacctt
acccacggtagca-------------------agctcggaattaaggtcagagttggaat
ttacaaaagctttctctc-----------------agcggaacccgca------------
--------gaacaaggcttgttggttcaacgt-----------------------ggctc
tccga---------------
>SEQ12
actgattcaacgtggaatgctgg-------------------------------------
---agaccagtaccctgg--------------------gcgggaaatccaacgcatggtg
gcat----------------aaaggtttgctttgcgtgtaccgcttctttcg--------
----------------caacattcacacagcgggtaacggagataaaaacacacgcgagc
gcttagtttagtcgttcgtctactaacgaaacctcactggtatgaattcagagcacctac
aa----------------------------------------------------------
----------------------------------------------------tctcgaac
cgagtgac---------------------------atgactcgcgaggacggctaagag-
--------------------cgagaaaccgcctagggttcgtggcgatccgtgagcccgt
tattggaatcgttattaatggaaatcaaagcgttaatataggcactcatagtgactggtg
atgggatttacctaggaagccacaatgtgaagct--------------------------
--------------------------------------------aaacatggtttccatt
attata---------------------cttttaggaatgcaaatctctatgaggacgact
actgctctaatataactctagctatatatctgggcttacattattcgaacactaagacat
gatttctcgtatgcttactcaccgctttaatccagtgcggaaaacgcactgtgcaacctt
acccacggtagca-------------------agctcggaaataaggtcagagttggaat
ttacaaaagctttctccc-----------------agcggaacccgca------------
--------gaaaaaggcttgttggat-----------------------------ggctc
tccga---------------
>SEQ13
actgattcaaggtacaatgctagtgagcac------------------------------
---agaccagcaccctga--------------------tcggtattgccagcgcagggtg
gcgt----------------aaacatttccgtggggcgtaccgcttatttgg--------
----------------caacattcacacagcgggtaacggagataaaaacaaacgcgagc
gcttagtttagttgttcgtctactaacgaaacct--------tgaattcagagcacgtac
aa--------------------------------gggaaacg------------------
---------------------cctaat------------attcattagtgcggttagagg
ttgttatc---------------------------atggctcccgaggccggctaagtg-
--------------------cgagaaaccgcctagggttcgtggcgacccgtgagcccgt
tattggaatcgttattaatggaaatcaaagcgttaatataggcactcatagtgactggtg
tggcgattttcctagaaagccaaaatggactgaacg-------------gcgacaagggt
tcaactaactcccggtctg----------------caaccttagaaacaaggactccagt
cagttgttgatgggtttatgccgtgctctgtgcg------------------ggacgtgt
actgctctaatattactctagctatatatctgggcttaccttattcgaacactaatacat
gatctctcgtatgctcactcaccgctttactccagtgcggaaaactcactctgcaacctt
ctccacggtacca-----------------------aataaaaaaagtcagggttggaat
ttccgacagatttttctc-----------------cgcgtcccaagctcgaccatagact
ctttgtgggcgccaggcttgttcgtacaa------------------gcgtttttggttc
tccgg---------------
>SEQ14
acagattctagggaccatgctagatatcagtccgcttcttcacaaaggaccctgtttggg
ca----------------------------------------------------------
--------------------------------tacgcgtaccacttc-------------
----------------caacattcacacagcgggtaacggagataaaaacaaacgcgagc
gcttagtttagttgttcgtctactaacgaaacctcactggtatgaattcagagcacgtac
taatt---------------------gcatcaacgaggagcgaaggccgttgc-------
--------------------------tgtattttaactcgttcgcaagcgcatgtagagg
ctcttaacagacagtagccatcaagttcaaaaactatggctcccgaggcatgctaccagg
tttctcctacgaggctctgacgagaaaccgcctagggttcgtggcgacccgtgagcccgt
tattggaatcgttattaatggaaatcaaagcattaatataggcactcatagtgactggtg
a----------------------aacgttcgcaccggatgaaga----------------
-----------------------------------taaccttatta--------------
---------------------------ctcttaagaatgccaagctctctggggacgact
gctgctctaatataactctagctatatatctgggcttacattattcgaacactaatacat
gatctctcgtatgctcactcaccgctttaatccagtgcggaaaactcactgtgcaacctt
ctccacgttacca-----------------------aataaaaaaagtcaaggttggaat
ttccgacagatttgtcta----------------------------------------gt
ctttgtgggcgccaggcttgttcctacaa------------------gcgtttttggttc
tccgg---------------
>SEQ15
cgtgattcta-----------------------gcttctacacaaagactgccgc-----
------------------------------------------------------------
-------------------------------tcgcgattcccgcttctttcg--------
----------------caacattcacacagcgggtaacggagataaaaacaaacgcgagc
gcttagtttagtcgttcgtctactaacgaaacctcactggtatgaattcagagcacctac
tacctataccgtacggatagaacgtggcatcaacgaggaggga-----------------
----------------------------------tcctcgtccagaaaagcatttagagg
ctgttaaccgacagtagccatcaagttcaaaaactatgactcccggggcatgctaacagg
tttctgcggtaaggctctagcgagaaaccgcttagggttcgtggcgatccgtgagcccgt
tattggaatcgttattattggaaatcgaagcgttaatataggcactcatagtgactggtg
atg-------------------------------------acgaggtttgagataaggct
gcacctaagtcac----------------gcgtctctccgtgagaaataaggtttatatt
gtttca---------------------ctcttaggaatgcagag----------------
-------------------agctatatatctgggcttacattattcgaacactaatacat
gatctctcgtatgctcactcaccgctttaatccagtgcggaaaactcactgtgcaacctt
atccacggcaggacttgccttcagccatgagcgaatcataattaagattagcgttggcat
gtgaacgagatttctgcc------------------------------------------
--------ccgcatggttttttgggtcaacgtcccagcaatagccttgcgttcttgtttc
ccggc---------------
>SEQ16
actaattttagagaccatg------------------------aaagacagcagacagag
cggagacccggacccttcct------------------gcgggatagccagggcg-----
------------------------------gtagcgcgtaccgc----------------
----------------caacatccacacagcgggtaacgcagataaaaacaatcgcgagc
gcttagtttagtcgttcgtctactaacgaaacctcactggtatgaattcagagcacgtac
aa--------------------------------gggaaacgcagacccctgcccatatc
atcgtctctcgatccgaagaccctaac------------actcgttagtgcggttagagg
ttcttatc---------------------------atggctcccgaggccggcagggag-
--------------------cgagaaaccgcttagggttcgtggcgatccgtgagcccgt
tattggaatcgttattattggaaatcgaagcgttaatctaggcactcatagtgactggtg
ttgggatttacctagcctgtcccaatggaaggaacgactgccgaagtttgcagcaaggct
gcaactaacgc------------------------cagtcttagaaataaggtctccact
cctctgttaatgggtttaggccatgatctgttcggg------------------------
actgctcaaatatgactc--gctatatatctgggcttacattattcgaacactaatacat
gatgtctcgtatgcttactcaccgctttaatccagtgcggaaaactcactgtgcaacctt
acccacggtagca-------------------agctcaaaattaaggtaagagttgggat
taacaatagctttctgtc-----------------agcggaccccgct------------
--------gtacaaggcttgttgattcaacgt-----------------------ggctc
tcct----------------
>SEQ17
gctgtttctcgggatgatgctagatatcggaccgcggatacacaaaggcagcagtcaggg
agg-------------------------ctagcttgcggcgggatagccagtgcggcgtg
gtatacggagcggaccgacacaatccttctctagcgccaatctcttcttgagcaggtacc
tttgacctttttg---taccattcacacagcgggtaacggagataaaaacaatcgcgagc
gcttagtttagtcgttcgtctactaacgaaacctcactggtatgaattcagagcacgtac
aacttat-----------------------------------------------------
---------------------------------------actccttaatgcggttagaag
ttgttatc---------------------------aaggctcccgaggtccgctaagtg-
--------------------cgagaaaccgcttagggttcgtggcgatcggtgagcccgt
tattggaatcgttattattggaaatcgaagcgttaatataggcactcatagtgacgggtg
ttggcagtcaccttgcaagccacaatgtacggaacggttgacgagttttgcggtag----
-----------ccggtccgagtaaatttgtcgtctcaacctcagaaataagatttccgtt
ctttt----------------------ctcttaggattgcaaagctctatgaggacgaca
actgctc-------------gctatatatctgggcttacattattcgaacactaatacaa
gatctctcgtatgctcactcaccgctttaatccagtgcggaaaagtcactgtgcaacctt
acccccggtagca-------------------aggtcaaaattaagatcaaagtccgaat
attcaaaagctttctctc-----------------agcgccccccgct------------
--------gaacaaggcttgtgggttcaacgt-----------------------cgttc
tcccg---------------
>SEQ18
actgcttgaaggtacactgctagagaacggaaacca------------------------
--------------------------------------gcgggattgccagcgc------
---------------------cacatttccgttgcgcgtaccgcttatttgg--------
----------------catcattcacacaccgggtaacggagataaaaacaaacgcgagc
gcttagtttagtcgttcgtctactaacgaaacctcactggtatgaattcagagcacctac
aa----------------------------------------------------------
----------------------------------------------------gctcgaac
cgagtgac---------------------------aggactcgcgaggacggctaagat-
--------------------cgacaaaccgcttagggttcgtggcgatccgtgagcccgt
tattggaatcgttattattggaaatcgaagcgttaatataggcactcatagtgactggtg
atg-------------------------------------acgaggttcgagaaaaggct
gcacctaagtcac----------------gcgtctctccgtgagaaataagg--------
------------------------------------------------------------
-----tttataatgcttcaagctatatatctgggcttacattattcgaacactaatacat
gatctctcgtatgctcactcaccgctttaatccagtgcggaaaacccactgtgcaacctt
ctccacggtacca-----------------------aagaagaaaagtcagggttggcat
tgccgacaaatttttcat-------------------------------------agact
ctttgtgggcgccaggctttttcgtacaa------------------gcgtttatggttc
tacgg---------------
>SEQ19
ggtgatcctagcttctacaccaag------------------------------------
------------------------------------------------------------
------------------------------actgcccctgccgcttctttcg--------
-------------------cattcacacagcgggtaacggagataaaaacaaacgcgagc
gcttagtttagtcgttcgtctactaacgaaacctcaatggtgtgaattcagagcacgtac
caatgatatcgtaatgacatcccgtggtatcaacgaggagcgaagacccttgc-------
--------tcgaaactttgaccctaatgaatttcacctcgttgataatcgcattcagagg
ttgttaactgacagaagccatcgtttccaaaaaccttggctccccaggcaggctatcagg
tttctccggcgaggctctcacgagaaaccgcttagggttcgtggcgatccgtgagcccgt
tattggaatcgttattattggaaatcgaagcgttaatatagccactcatagtgactggtg
ttgggatagacctagcatgtcccaatggaaggcacgactgccgaaaatctcaacaaggct
gt-----------------------------------accttagaaataaggtctccact
cttttattaatgggtttaggccattaaccgttcgggatacacagctttttcagtacgagt
actgctcaaatatgac----gctatatatctgggcttacattattcgaacactaagacat
gatttctcgtatgcttactcaccgctttaatccagtgcggaaaacgcactgtgcaacctt
acccacggtagca-------------------agctcaaaattaatatcaaatttgtatt
ttacaaaagctttcactc-----------------agcggcccccgat------------
--------gaacaaggcttgttggttcaacgtccag------------------------
--------------------
