>SEQ0
tgatgtacttgccacgatgttgcgtctgtgtgaaggtcgtcgggcaggacaagcgggtat
attcttgaacatgcaatgttgttatccggtaaacactttcataccgctcccataagaatg
ctcgccctctctagcaaaacgtgtgtaataaataggattattcaggaccaggtcccctaa
ctcgatcctgaccttttcgctcccctatgatttgatcctgcactccacaactttaggaag
tccacgacatccttccaccccctagacgtttgtccaagtccattgccacctagtgctaag
ggactgagaccccgaaaacagtgggcccgtaaattttcggctcggacgaacagtctcatc
ctttgctcatcagatcggctacgcatcaatgattactagctctcccggtccaagcacgtc
ggaaacgaacttttccaaattatgctaaaaaagaactacgggtgcgttctcgctgaaggg
ttgagctatcgatggatcccgacgcgggcgtcccggaatccccccctagggagcaacaag
ataactatacattaatttcgcccaagctggcatggcgatgcctccgtcaatgacgtcttt
aagcaccattaccatgagcgacggagataattaggctctgggagctccaatagtcgtgtt
ctacataaggggtaccccggatagactcccgggcaccacggtgtgctacgactttctgcc
cgggtgttctggtctaaacaagctgaattgattgcaccttttgctgtagcgtcactaacc
gattggaaggttaaggtgtgaaaagacgtggcgcacccattcgaaactcaaccggcgcca
atcgtgccccatgaaggcgcttcggaagtctatcttgacgaatctccgggatactgtatc
atagtccgatcttccccgttaggggccgccttagagtgattccttgtcatgcgtaagagg
gggctggtacacagtaaatccggtcttggctggaggaggagcggattcggcaagtgacgt
gtagatacaaccaattgtgcttaacctttcacttcaaatagttaggtagaaaaccagcga
ttgtatagataaattgagtg
>SEQ1
gaatgtacttgccacgatgttgtgtctgtgtgaaggtcgtcgggcaggacgagagggtat
attcttgaaaatgcaaggttggta------------------------cacataagaatg
ctcgcccactatagcaaaaggtgtgtaataaacatgattattcagcaccaggtctcctaa
ctcgatcctgaccttttcgctcccctatgatttgatcctgcactccacaactttaggaag
tccacgacatccttccaccccctagacgtttgtccaagtccattgccacctagtgctaag
ggactgagaccccgaa-------------------ttcggctcggacgaacagtctcatc
acttgctcaccacgtcggctacgcatcaatgattactagcgcacccggtccaagcgcgtc
ggaaacgaacttttccagattaggctaa----------------------cgctgaaggc
ttgaactatcgatggatcccgacgcgggcgtcccggaatccccccctcgggagcaacaag
ataactatacattaatttcgcccaagctggcatggcgatgcctccgtcaatgacgtcttt
acgcaccattaccatgagcgacggagataatcaggctttgggagctccaatagtcgtgtt
ctacataagggatagcccggatggactcgcgggcagcacggtctgctactaatttctggt
cgggtgttctgatctacacaagctgaattgattgcacctttcgctttagcgtcactaact
cattggaaggttaaggtgtgaaaagacgtggcgcacccattcgaaactcaaccggcgcca
atcgtgccccatgaaggcgcttcggaagtctatcttgacgaatctccgggatactgtatc
atagtccgatctgccccgttaggggccggcttagagtgattccttgtcaagcgtaagagg
gggctgttacacagtcaacccggtcttggcgggaggagggacggattcggcaagtgacgt
gtaaatacaaccaggtgtgcttaacctttcacttcacat--------------------a
ttgtatagataaatcgagtg
>SEQ2
---------------------------tggtgtaggtcgtcgggcaggacaagcgggtgt
attcttgaacatgcattgttgttatccggtaaacactttcataccgctcccaaaggaatg
cacgccatctctagcaaaacgtctgtaataaatagtattatttaggtccaggtcccctaa
ctcgatcctgtccttttcgctcccctatgatttgatcctgcactccacaactttaggaag
tccacgacatccttccaccccctagacgtttgtccaagtccattgccacctagtgctaag
ggactgtgaccccgaa----------------------------------cagtctcatc
ccttgctaatca-------------------------agcgcacccggtccaagcgagtg
gtaaatgaacttttccaggtgaggctaa----------------------cgctgaaggc
ttgaactatcgatggatcccgacgcgggcgtcccggaatccccccctcgggagcaacaag
ataactatacattaatttcgcccaagctggcatggcgatgcctccgtcaatgacgtcttt
acgcaccattaccgtgagcgaccgagataatcaggccttgggagctccaatagacgtgta
ctacataacggatagcccggatggactcgtgggcagcacggtcggctactaatttctggt
cgggtgtcctgatc----------------attgcacatatcgctttagcgtcactaact
cattggtaggttaaggtgtgaaaagacgtggcgcacccattcgaaactcaaccggcgcca
atcgtgccccatgaaggcgcttcggaagtctatcttgacgaatctccgggatactgtatc
agagtccgatcttccccgtcaggtgccgc-------------------------------
gggctggtacacagtaaatccggtcttggctggaggcggagcggtttcggcaagtgaagt
gtaaatacaaccatttgtgcttgacctttcacttcaaatagttaggtagaaaaccagcga
ttatatagataaattgagtg
>SEQ3
--------------tgatgtgcttgcctcgtgaaggtcgtcgagcaggacatgcgggaat
attcttgaacatgcaatgttgttatccggtaa----------------------------
ctcgctctctctagcaaaacgtgtgtaataaattggattattcaggatcaggtcccctaa
ctcgatcctgaccttttcgctcccctatgatttgatcctgcactccacaactttaggaag
tccacgacatccttccaccccctagacgtttgtccaagtccattgccacctagtgctaag
ggactgtgaccgcga--------------------------------------------c
ccttgctaattg-------------------------agcgcacccggtccaagcgagtg
gtaaattaacttttcccggtgaggctaa----------------------cgatgaaggc
ttgacctatcgctgaatcccgacgcgggcgtcccggaatccccccctagggagcaacaag
ataactatacattaatttcgcccaagctggcatggcgacgcctccgtcaatgacgtgttt
aagcaccattaccatgagcgacggagataactaggctctgggagctccaatagtcgtgtt
ctaccgaaggggtacccctgatagactcccgggcaccacggtgtgctacggctttctgcc
cgggtgctgtagtctaaagaagctgaattgggtgcacatttggctgtagcggcacgaacc
gattggaagggtaaggtgtgaaaagacgtggcgcacccattcgaaactcaaccggcgcca
atcgtgccccatgaaggcgcttcggaagtctatcttgacgaatctccgggatactgtatc
gtagtccgatcgcccccgttagggacagccctagagtgattccttgtcatgcgtaagatg
gggctggtacacagtaaatccggtcttggctcgaggaggagcggattcggaaagttacgt
gtagatacgaccttttgcgcttatcctctcacttcaaatagttaggtggaa---------
-------------ttgactg
>SEQ4
---------------------------------------------tggtcaagcgggcgt
attcttgaacatgcattgttcttatccggtaaacactttcctaccgcacccaaacgaatg
tacgccatctcgagcaaaacgtcggtaataaatagcagtatttacgtccaggtcccctaa
ttcgatcctgtccttttcgctcccctatgatttgatcctgcactccacaactttaggaag
tccacgacatccttccaccccctagacgtttgtccaagtccgttgccacctagtgctaag
ggactgagcccccggaaacagtgggcccgtaaattttcggctctgacggacagtcttatc
ctttgctcatcagatcggcaacgcaccagtgattattagctctcctggtccatgcacgtc
ggaaacgtccttttcccaat------------------------------tatcgcaaaa
aaggactacgggtgga--gcgacgcgggcgtcccggaatccccccctcgggagcaaaaag
ataactatacattaatttcgcccaagctggcatggcgatgcctccgtcaatgacgtcttt
aagctccataaccatgagcgagggagct------------------ccaatattcgcgtt
ccacatacgtggtacccaggacagac------------------------------tgcc
cgggtgttctggtctaaacaagctgaattgattgcacctttggctgtagc----------
-----------------gtgaaaagacgtggcgcacccattcgaaactcaaccggcgcca
atcgtgccccatgaaggcgcttcggaagtctatcttgacgaatctccgggatactgtatc
gtagtccgatcggccccactagggacagccctagaatgattgcttgtcatgcgtaagatg
gggctggtac----------------------taggaggagcggattcggaaagttacgt
gtatatacgacgttttgcgcttatcctctcactt--------------------------
-------------ttgtctg
>SEQ5
---------------------------------------------tggtcgagcgggcgt
atttttgaacatgcattgttcgtatgcggtaaacactttcctaccgcacccaaacgaatg
taggccatctcccgcaaaacgtcggtaataagtagcagtatttacgtccaggtcacctaa
ttcgatcctgcccttttcgctcccctatgatttgatcctgcactccacaactttaggaag
tccacgacatccttccaccccctagacgtttgtccaagtccattgccacctcgtgctaag
ggacaatgaccgtta--------------------------------------------c
ccttgctaattg----------------------------------------agcgagtg
gtaaattaacttttcccggtgaggctaa----------------------cgatgaagtc
ttgacctatccctgagaaccgacgcgggcgtcccggaatccccccctagggagcaacaag
ataactatacattaatttcgcccaagctggcatggcgatgcctccgtcaatgacgtcttt
acgcaccattaccatgagcgacggagataatcaggctttgggagtaacggtcagcacgat
ct----------------------------------------------------------
----tgttctgatctacacaagctgaattgatcgcccctttcgctttagcgtcactaact
cattggaaggttaaggggtgaaaagacgtggcgcacccattcgaaactcaaccggcgcca
atcgtgccccatgaaggcgcttcggaagtctatcttgacgaatctccgggatactgtatc
atagtccgacctgcctctttaggggccggcttagactgattccttgtcaagcgtaaga--
------------ggtcaacccggtcttggcgggaggagggacggatccggcaagtgtcta
ttaaatacaaccaggagtgcttaacctgtcactttacat--------------------a
ctgtatagacaaatcgagcg
>SEQ6
-----------------------------------------tggcaggacaagctggtgt
attctttaacaagcattgttctgatccgataaacactttcataacgctcccaaaggaatg
aacgccatctctcgca-------------------tattatttagatccaggtaccctaa
ctcgatcctgtccttttcgctcccctatgatttgatcctgcacaccacaactttaggaag
tccacgacatccttccaccccctagacgtttgtccaagtccattgccacctagtgctaag
tgattttcggctcgga--------------------------------------------
---cgaacagtctatcgtctacgcatcaatgattactagctctccccgtctaagcacgtc
gtaaacgaacttgtccaaattatgctaa------------------------aaaagtac
caggggtgcgtatgtttcccgacgcgggcgtcccggaatccccccctagggagcaacaag
ataactatacattaatttcgcccaagctggcatggcgatgcctccgtcaatgacgtcttt
aagctccataaccatgagcgaaggagct------------------ctaatattcgcgtt
ccacata-------------------------------------------------tgac
cgggagttctggtcaaaacaagatgaatttattgctcctttggctgtagc----------
-----------------atgaaaagacgtggcgcacccattcgaaactcaaccggcgcca
atcgtgccccatgaaggcgcttcggaagtctatcttgacgaatctccgggatactgtatc
atagtccgaccgccctctttaggggccggcttagactgattccttgtcaagcgtaaga--
------------ggtcaacccggt-----------------cgtaaccggcaagtgtcaa
ttaaatacaaccaggattgcttatcctgtcactttagat---------------------
-----------aatcgagcg
>SEQ7
--------------cgatgtgcttgcctcgtgaaggtggtcgagcaggatatgcaggtat
attcttgaacacgtaacattgttatccggga----------------------------g
cacgctctctctagcaaaacgtgtgtaataagttggagtattcagcatcagg--------
--------------tttcgatcccctatgatttgatcctgcactccacaactttaggaag
tccacgacatccttccaccccctagacgtttgtccaagtccattgccacctagtgctaag
g----------------------------------------------------------c
ccttgctaattg----------------------------------------accgagtg
gtaaattaacta--------------------------------------cgatgaactc
ttgacctatccctgagaaccgacgcgggcgtcccggaatccccccctagggagcaacaag
ataactatacattaatttcgcccaagctggaatggcgatgcctccgtcaatgacgtcttt
tagctcgataaccatgagcgaaggagat------------------ctgatattcgcgtt
ctacata-------------------------------------------------tgac
cgggagatgtgatcaaaacaacatgagttta-----------------------------
-----------------atgaaaagacgtggcgcacccattcgaaactcaaccggcgcca
atcgtgccccatgaaggcgcttcggaagtctatcttgacgaatctccgggatactgtatc
atagtccgacctgtctctttaggggccggcttagactgattccttgtca-----------
------------agccaacccggtcttggcgggaggagggacggatccggcaagtgtcta
ttaaatacaaccgggagtgcttaacctgtcacgttacat--------------------a
ctctacagacagatggagcg
>SEQ8
------------------------------------------------------------
--------tgaagtactattctgatccgacaaacactt----------------------
-----tatctatcgca-----------------------------------------tat
tattatcctatccttttcgctcccctatgatttgatcctgcactccacaactttaggaag
tccacgacatccttccaccccctagacgtttgtccaagtccgttgccacctagtgctaag
ggactctgcccctgga------------------------------------attttagg
ctctgacgatcg-----gcaacgcaccagtaattataagctcgccggggccatgcacgtt
--------------------------------------------------gatcacaaaa
aaggactgcggttgga--gcgacgcgggcgtcccggaatccccccctagggagcaacaag
ataactatacattaatttcgcccaagctggcatggcgacgcctccgtcaatgacgtgttt
aaccactattaccatgagagacggggataattaggctccgggaggtccaatagtcgtgtt
ctacgtaaggggtacccctcatagactcccaggcagcaccgtgtgtc------------c
cgggttttctggtctaaaaaagctgaattgattgcagcttttgctttagcctcactaacc
gataggaaggttaaagtgtgaaaagacgtggcgcacccattcgaaactcaaccggcgcca
atcgtgccccatgaaggcgcttcggaagtctatcttgacgagtctccgggatactgtatc
gtagatcgatcgcccccgttggggacagccctagattgatt------------------g
gggctggttcacagtaaatcgggccttggctcgaggaggagcggaatcggaaagttaagt
gtggatactaccttgtgcgcttatccactcacttcaaatagttaggtggaa---------
-------------ttgactg
>SEQ9
---------------------------tggtgtaggtcctcgggcaggacaatcgggtgt
attcttaatcaagcattgttgttatccggtaaacactttcataccgctcccaaaggaatg
caagccatctctagcgaaacgtatgtaataaata-----------------gtcccttaa
ctcgatcctgtccttttcgctcccctatgatttgatcctgcacaccacaactttaggaag
tccacgacatccttccaccccctagacgtttgtccaagtccattgccacctagtgctaag
ggactgtgaccccgat----------------------------------cagtctcatc
ccttgctaatca-------------------------agcgcccccggtccaagcgcgtg
gtaaatgaacttttccgagtgaggctaa----------------------cgctgcagga
ttgaactatggatggagcccgacgcgggcgtcccggtatccccccctcgggagcaaaaag
ataactatacattaatttcgcccaagctggcatggcgatgcctccgtcaatgacgtcttt
tagctcgctaaccatgagcgaaggagat------------------ctgatattcacgtc
ctatata-------------------------------------------------tgat
cg----------------------------------------------------------
---------------ttatgaaaagacgtggcgcagccattcgaaactcaaccggcgcca
atcgtgccccatgaaagcgcttcggaagtctctcttgacgaatctcccggatactgtatc
gtaggtggatcgctcccgttcgcgacagccctagattgatt------------------g
gggctggttcacagtaaatc--------------gggggggcggaatcggaaagttaagt
gtggttactaccttatgcacgtatcccctcacttcaaatagttaggtggaaa--------
--------------tggctg
>SEQ10
gaatgtacttgccacgttgatgtgtcggtgtgaaggtcgtcgggcagggcgtgagggtat
attcttgcaaatgcaaggttg------------------------gttcccagaagaatg
ctggcccactatagcaaaagggctgtaataa----------------cccggtctcctaa
ctcgatcctgatcttttcgctcccctatgatttgatcctgcactccacaactttaggaag
tccacgacatccttccaccccctagacgtttgtccaagtccgtttccacctagtgctaag
ggactgaggcccgcaa--------------------------------------ttcggc
tcggacgaaccacgtcgcatacgcatcaatgatcactcgcccacccggtccaagttcgtc
ggaaacggacttttccagattaggctaa----------------------cgctgaaggc
ttcaacaatcgatggatcccgacgcgggcgtcccggtatccccccctcgggagcaaaaag
ataactatacattaatttcgcccaagctggcatggcgatgcctccgtcaatgacgtcttt
tagctcgataaccatgagcgaaggagata------------------tgatattcacgtt
ctacata-------------------------------------------------tgac
cgggatatgggatcaaaacatcat------------------------------------
-----------------atgaaaagacgtggcgcacccattcgaaactcaaccggcgcca
atcgtgccccatgaaggcgcttcggaagtctatcttgacgaatctccgggatactgtatc
atagtccgacctgtctctttaggggccggcttagacttattccttgtca-----------
------------aggcaacctggtctgggcgggaggagggacgcagccggcacgtgtcta
ttaaat--------------------tgtcacgttacat--------------------c
ctctacagacagatggagag
>SEQ11
------------------------------------------------------------
------------------------------------------------------------
--------tgatacgacaacctctgta----------------------------tctat
tattatcctaacgttttcgctcccctatgatttgatcctgcactccacaactttaggaag
tccaccacatccttccaccccctatacgtttgtccaagtccgttgccacctagtgctaag
a----------------------------------------------------------t
ccttgctaattg----------------------------------------acctaggg
gttaattaa-----------------------------------------ggttgcaccc
aggacctatccctgagaaccgacgcgggcgtcccggtatccccccctcgggagcaaaaag
ataactatacattaatttcgcccaagctggcatggcgatgcctccgtcaatgacgtcttt
gcgcaccattaccctgagcggccgagataatcaggtcttgggagatccaatacacgt---
----------------cccgatggactcttgggcagcacggtctgcgactaatttctggt
cgggtgtcctgatc----------------attgcacatatcggtttagcggctgtaa--
--------------------aaaagacgtggcgcacccattcgaaactcaaccggcgcca
atcgtgccccatgaaggcgcttcggaagtctatcttgacgaatctccgggatactgtatc
ggaggtggatcgctgccgttcgcgacagccctatattgatt------------------g
gggctggttcacagtcagtc--------------ggaggggcgaattcggaaatttacgt
gaggttactaccttatgcgcgtatcccctcacttcaaatagttaggtgaaaa--------
--------------tggctg
>SEQ12
--------------tgatgcgcttggctcgtgaaaggcgtctggtaggacatgcgggaac
atatttgaccatgca---------------------------------------------
ctggctctcgctagcaaaacgtgtgtaataaattggattagtcaggatcaggtcccccaa
ctcg----------------tcccctatgatttgatcctgcactccacaactttaggaag
tccacgacatccttccaccccctagacgtttgtccaagtccgttgccacctagtgctaag
g----------------------------------------------------------t
ccttgttaattg----------------------------------------atctaggg
gtgaatcaa-----------------------------------------ggttgcaccc
agggcccatccctgag--aagacgcgggcgtcccggaatccccccctcgggagcaacaag
agaactatacattaatttcgcccaagctggcatggcgatgcctccgtcaatgaggtcttt
gcgcatcattat------------------------------------------------
----------acacgtcccgatggagtcttgggcagcacggtctgcaaataatttctgct
aggctgtcctgagc----------------attgcac-----------------------
-----------------atcaaaagacgtggcgcacccattcgaaactcaaccggcgcca
atcgtgccccatgaaggcgctttggaagtctatcttgacgaatctccgggatactgtatc
ctagtccgatcttccccgttaggggccgccttagagtgattccttgtcatgcgtaagagg
g--------------------------ggctggaagaggagcggcttcggcaagtgacgt
gtagattcaacctatt----------------------tagttaggtagaaaaccagcgg
ttgtatcggtaaatggagtg
>SEQ13
---------------------------tggtgtaggtcgtcggacaggacacgcgggtgg
at------------------------------------taataccggtcacaaaggaatg
cacgccatctctagcaaaacgtctgtaatacatagtattatttaggtccaggtcccctaa
ctcgatcctgtccttttacctcccctatgatttgatcctgcactccacaactttaggaag
tccacgacatccttccaccccccagacgtttgtccaagtccgttgccacctagtgctaag
g----------------------------------------------------------t
ccttgttaattt----------------------------------------atctaagg
gtcaatcaa---------------------------------------------------
----------gattga--acgacgcgggcgtcccggaatccccccctagggagcaacaag
ataactatacattaatttcgcccaagctggaatggcgatgcctccgtcaatgacgtcttt
aagcaccaaaaccatgagcgacggagataactaggctctgggagctctagtagtcgtgtt
ttaccgaaggggtatccctgatagcctcccgggcacc-----------------------
--ggtagtgtattctaaagaagctgaattggatgcacatttggctgtagcggcacgaacc
gattggaagggtaatgtgtgaaaagacgtggcgcacccattcgaaactcaaccggcgcca
atcgtgccccatgaaggcgcttcggaagtctatcttgacgaatctccgggatactgtatc
ggaggtggatcgctgccggtcgcgacagccctataatgact------------------g
gggctggcccacaatctgtc--------------ggagggtcgaattcgcaaatttatgt
gaggttactacgttatgcgcgta-------------------------------------
-------------tgtgaaa
>SEQ14
--------------tgaagcgctaggctcgttaaaggcgtctggtaggacatgcgggaac
at----------------------------------------------------------
ctggctctcgctagcaaaacgtgtgtactaaattggtttagtca----------------
--------------------tcccctatgatttgatcctgcactccacaactttaggaag
tccacgacatccttccaccccctagacgtttgtccaagtccattgccacctagtgctaag
ggactgaggcccgaaa--------------------------------------ttcggc
tcggacaaaccacgtcgcatacgcaccaatgatcattcgcacacccggtccaagttcgtc
tgaaacggccttttccagattaggctaa--------------------------------
-------attgacggatcccgacgcgggcgtcccggaatccccccctagggagcaacaag
ataactatacattaatgtcgcccaagctggcatggcgatgcctccgtcaatgacgtcttt
atacac------------------------------------------------------
------------------------gttcttgggcaggacg-------------------t
aggctgtcctgagc----------------accgcac-----------------------
-----------------atcaaaagacgtggcgcacccattcgaaactcaaacagcgcca
atcgtgccccatgaaggctcttcggaagtctatcttgacgaatctccgggatactgtatc
gtaggtggatcgctcgcgttcgcgacagcactagattgatt-------------------
-------------------------gtggctggtgaaagggcggaatcggaaagttaagt
gtggttactgccttatgtacttaa------------------------------------
--------------tggctg
>SEQ15
---------------------------------------tctggtaggacatgcgggaac
ttttttgaccatgca---------------------------------------------
cgggctctcactagcaaaacgagtgtaataatctggattagtcaggatcaggtcccccaa
ctcg----------------tcccctatgatttgatcctgcactccacaactttaggaag
tcctcgacatccttccaccccccagacgtttgtccaagtgcgttgccacctagtgctaag
ggactgtgtccgata--------------------------------------------c
cccttctaattg------------------------------------------agcgtg
gtaaagtaactttccccggtgaggctaa-----------------------------tgc
ttgacctatcgcttaatcccgacgcgggcgtcccggaatccccccctagggagcaactag
ataactatacattaatttcgcccaagctggcatggcgacgcctccgtcaatgccgtgttt
aaccaatattaccctgagagccgggaataattaggctccgggaggtccaatagtcgtgtt
ctacgtaaggggtactcctc----------------------------------------
---------------------gctgaattgattgcagctttcgctttagcctcactaacc
gatgggaagggtaaagtatgaaaagacgtggcgcacccattcgaaactcaaccggcgcca
atcgtgccccatgaaggcgcttcggaagtctatcttgacgaatctccgggatactgtatc
agagtccgatcctccccgtcagg-------------------------------------
--------------taaatccggtcttggctggaggcgaagcggtttctacaagtgaagt
gtaaatacaaccatttgtgcttgacctttcacttcaaatagttcggtagaaaaccagcga
ttatgtggatacattgagtg
>SEQ16
gaatgtacttgctacgatgttgtgtctgtgtgaaggtcgtcgggctggacgagagcgtat
attcttgaaa--------------------------------------cacataagagtg
ctcgcccactatagcaaaaggtgtctgat-----------------------ccacttaa
ctcgatgctgacctatgcgctcccctatgatttgatcctgcactccacaactttaggaag
tccacgacatccttccaccccccagacgtttgtccaagtccgttgccacctagtgctaag
ggattgggaccccgta----------------------------------cagtctcatc
tcttggtaatca-------------------------agtgcacccggtccaagcgagtg
gtaaatgagcttttccaggt------------------------------tgctgaaggc
ttgaactatcgatggatcccgacgcgggcgtcccggtatccccccctcgggagcaaaaag
ataactatacattaatttcgcccaagctggcatggcgatgcttccgtcaatgacgtcttt
acgcaccattaccatgagcgacggagataatcaggctttgggagtatcggtcagcacgag
ct----------------------------------------------------------
----tgttctaatctacacaagctgaatttatcgcccctttcgctttagc----------
-----------------gtcaaaagacgtggcgcacccattcgaaactcaaccggcgcca
atcgtgccccatgaaggcgcttcggaagtctatcttgacgaatctccgggatactgtatc
atagtccgacctgtttctttagggtccggcttagaattatg-------------------
---------------caacgtggcctgtgcgggaggagggacgcagccggcacgtttcta
ttaaat--------------------tctcacggtacat--------------------c
ctctacaaacagatggtgag
>SEQ17
---------------------------------------tggtgtaggacga--------
----------------------------------------atacgggtcacaaagcaatg
cacgccatctctaactaaacgtctgtaatacatagtattttttaggtccaggtcccctac
ctcgatcctgtccttttacctcccctatgatttgatcctgcactccacaactttaggaag
tccacgacatccttccaccccctagacgtttgtccaagtccattgccacctagtgctaag
g----------------------------------------------------------t
ccttggtaattt------------------------------------------------
------------------------------------------------------------
---atcttacggtcaatcaagacgcgggcgtcccggaatccccccctagggagcaacagg
ataactatacattaatttcgcccaagctggaatggcgatgcctccgtcaatgacgtcttt
acgcacctttaccgtgagcgaccgagatacttaggccatgcgatctccaatagacgtgta
cttcataacggatagcccggacggactcgtgggcagcacg--------------------
------------------------------attgcacataccgctttcgcgtcactcact
cattggtagggtaaggtgtgaaaagacgtggcgcagccattcgaaactcaaccggcgcca
atcgtgccccatgaaagcgcttcggaagtctctcttgacgaatctcccggatactgtatc
atagtccgacctgtttctttagggtccggc------------------------------
----------------aacgtggcctgtgcgggaggagagaagcagccggcacgtttcta
ttaaatgc--------------------tcacggtacat--------------------c
ctctacaaacagatggagag
>SEQ18
------------------------------------------------------------
--------tgaagtattattctgatccgacaaacactt----------------------
-----tatctatcgcatattat--------------------------------------
-------ttatactcttcgctcccctatgatttgatcctgcactccacaactttatgaag
tccacgacatccttccaccccctagacgtttgtccaagtccattgccacctagtgctaag
ggactctgcccctgga------------------------------------attttagg
ctctgaggatcg-----gcaacgcagcagtaagtataagctcgccggggccatccccctt
--------------------------------------------------gatcacacga
aaggactgcagttgga--gcgacgcgggcgtcccggaatccccccctagggagcaacaag
ataactatacattaatttcgcccaagctggcatggcgacgcctccgtcaatgacgtgttt
aagtaccaaaaccacga-------------------------------------------
-------------agccctgatagcctcccgggctcc-----------------------
---------------------ggtaaattggatgcacatttggctctagctgcacgaacc
gattggaagg-------gtaaaaagacgtggcgcacccattcgaaactcaaccggcgcca
atcgtgccccatgaaggcgcttcggaagtctatcttgacgaatctccgggatactgtatc
gtggtccgatcggccccactagggacagccctagaatgatcgcttgtcatgcgtaagagg
gg----------------------tctggtactaggtcgagcggatttagaaagttacgt
gtatacacgacgttttgcgcttatcctctcaatt--------------------------
-------------ttgtcag
>SEQ19
gaatgtacttgccacgttgatgtgtcggtatgaaggtcgtcgggcagggcgggaaggtat
atgcttgcaaatgcaaggtta------------------------gttcccagaagaatg
ctggcccactatagcaaaagggctgtaataa-----------------------------
--------------------tcccctatgatttgatcctgcactccacaactttaggaag
tccacgacatccttccaccccctagacgtttgttcaagtccattgccacctagtgctaag
gcactgtgtccgc----------------------------------------------t
accttccaattg------------------------------------------------
----------agaccccggtgaggctaa-----------------------------agc
gtgacctatcgcttaatccggacgcgggcgtcccggaatccccccctagggagcaacaag
ataactataccttaatgtcgcccaagctggcatggcgatgcctccgtcaatgacgtcttt
acggatcataaccatgagcgacggagataatcaggctttgggagtaacggt---------
------------------------------------------------------------
----tgttctggtctccacaagctggattgatcgcccctgtcgcgttagcgtcactaaca
cattggaaggttaaggggtgaaaagacgtggcgcacccattcgaaactcaaccggcgcca
atcgtgccccatgaaggggcttcggaagtctatcttgacgaatctccgggatactgtatc
agaatccgatcttccccatccgctgccgc-------------------------------
gggctagtacccagt-------------------aaaggagcggtttgggcaagtgaagt
gtaaatacaaccatttgtgcttgaccttagacttcaaatacttaggtagaaa--------
--------------------
