>SEQ0
tcgttttcaaccaattagaaaacacaggacaggaacgctcaaggaggctgcaatcgtcag
gggcgacccggcagttgcgttggagagtgatagctagcaaaatataaatacaaaggaggt
taacaggagccgggtcggtgcacaagtcttgaacgaggggaaagtattgggttctgtgcc
aaactttatctagcggaatgacacagaaggtctccttatactatgcacgaccacagtaca
tgttactgtgctcgtcgccgtccggtggccggatggcctccgcaagtacgccgtctccac
ccgtaggtctggggggcgggtttggggtggtgacattcgagttcagacatcccagaaagc
atcgctgctaccgagcgtgatactccacgacctaggttaggtctacataatcgtggccgt
ggccatgacttggtcgctatcgtcgatgtcatcaaataacggacatccacccgacggaca
gctggtgaccttgagctgcaccatggtctggaacacgtcctctcccggcgtggtcaatgg
ttagagcgtttactatgtccattaggaactcggctctccgtagtgacatgtctacctata
cccaattatacctacagacgcgctagtgggacctaacaaaaaggtagaatcacttccgcg
ctctcgacggaaaccatcgagattctagctcggccggcgcgtaaggctacaattcctgag
ttatggagcaacaaaacacagcccggcaataaattatgcttgatgtagcgacagcacgtt
gccctcttgagtagccgcacagctcttacagtctacttactatttgcccaccatctaaat
tttgtggttgtattatggctcatatattgactcttggctcatctgacttctgatctcaga
aggtcagtcgctcttactagaaggtccgtggcgattaggtcgcttacggaccgtgaagaa
atagcgaggacgtctaaacaaagttcctggacttcccctcgacctcgcacggccctgagg
gggattactcagagctccttcgattaaaggccatagccccggaacccaagacggagatcc
gagaccagagtattgactat
>SEQ1
tcgtttgcaaccaattagaaatcacaggacaggaacgctcaagggggctgcaatcgtcag
gggcgacccgccagttgcgttggagagtgatagctagcaaaatataaataccaagtaggg
taacaggagccgggtcggtgcacaagtcttgaacgaggggaaagtattgggttctgtccc
aaactatatctagcggaatcacacagaaggtctccttatactatgcacgaccacagtaca
tgttactgtgctcgtcgccgtccggtggccggatggcctccgcaagtacgccgtctccac
ccgtaggtctgggtggaggtcttggggtggtgacgttcgagtccagacatccctgaatgc
atcgccgcta---------------caaaacctaggttaggtctacataatcgtggccgt
ggtcatgagttggtcgctatcgtcgacgtcatcaaataactgacatccatcccacggaca
gcttgtgaccttgagctgcaccatggtctggaacacgtcctctcccggcgtggtcaatgg
ttagggcgtttactatgtccattaggaactcggctctccgtagtgacatgtctacctata
cccagttatccctacagacgcgctagtgggacctaacaaaaaggtcggatcacttgcgcg
cactcgacggaa----------------ctccgccggcccgtaaagctacaattcctgaa
ttatgg------------------------aaattatgcttgaggtagcgacagctcgtt
ggcctcttgactagcctcagagctcttacagtctagttactatttgaccaccatctaaat
tttgtggttgtattatggctcatatattgactcttggctcatctgacttctgatctcaga
aggtcagtcgctgttactcgaaggtccgtggctattaggtcgcttactgaccgtaaagaa
atcgcgaggacgtct---------------------cctcgacctcgcacggccctgagt
gggattactcagagctccttcgattaaaggccaaaggcccggaacccaagacggagatcc
gagaccagagtaatgactat
>SEQ2
tcgttatcaaccga---------------caggaacactcaaagagg-------------
--------------------------gtcatagctagcaaattataaatacaagggaggt
taataggagcc------------------tgaacgaggggaaaggattcggttctgtgcc
aaact-------------ttacacagaaggtctccttatactatgcacgaccacagtaca
tgttactgtgctcgtcgccgtccggtggccggatggcctccgcaagtacgccgtctccac
cggtaggtctgggtggaggtcgtggggtggtgacgtcccagtccaaacatcc--------
-----------------------------------attaggtctacctaatcgtggccgt
ggtcatgagttggtcgctatagtcgacgtcatcaaataactgacatcagtcccccggaaa
g----------------gcaccatggtctggaacacgtcctctcccggcgtggtcaatgg
ttagggcgtttactatgtccattaggaactcggctctccgtagtgacatgtctacctata
cccaattatatctacagacg--------------------------gcatcacttccgcg
ctatcgacggataccaacgagattctagctcggccggcgcgtaaggctacaattcctaag
ttatggagcaacaaaacacagcccggcaataaatgatgcttgatgaagcgaaagcacgtt
gccctcttgagtagccgtacagctcttacagtctacttactatttgcccaccatctaaat
tttgtggttgtattatggctcatatattcactcttggctcatctgacttctgatctcaga
aggtcagtttctcctactagaaggtccgggaccttta-------------------agaa
atagcgaggacggctaaacaaagttcctggacttacccaga-------------------
----------------------------------------ggaaccctagccggagatcc
gag-----------------
>SEQ3
tggtgttcaaccaatgagaaa------------------caaggaggctgtaatcgtcag
gggcgacccggca-------------gtgatagctaaaa---------------------
-------------------ggccaagtcttgaccgaggggatagt---------------
------tatctagcggaatgacacagaaggtctccttatactatgcacgaccacagtaca
tgttactgtgctcgtcgccgtccggtggccggatggcctccgcaagtaagccgtctccac
cggtaggtctgggtggatgtcgtggggtggtgacgtcccaggccaaacatcc--------
-----------------------------------tttaggtctacctaatcggggccg-
---------------ggtatagtcgacgtcatcaaataactgacatcagtcccccggaca
g----------------gcaccatggtctggaacacgtcctctcccggcgtggtcaatgg
ttatggcgtttactatgtccattaggaactcggctctccgtagtgacatgtctacctata
cccagttat-----------------------------------------------ggga
cctacgactgaa----------------ctccgccggcgcggaaagctacaattc-----
------------------------------------agcttaaggtggcgacagctcgtt
ggcctcttgactagcctcagagctcttacagtctagttactatttgaccaccatctaaat
tttgtggttgtattaaggctcatatattgactcttggctcatctgacttctgatctcaga
agttcagtcgcggttactcaaagg-----------taggggggtttctgaccgtagagaa
atcgcgaggacgtct---------------------cctcgacgtcgcacgcccctgagt
gggatcactcagagatcctacgacttaaggccaaaggtccggaacccaagccggagatcc
--------------------
>SEQ4
tcgtttgcacccaattagaaatcacaggacaggaacgcacaaggggggtggaatcgtcag
gggcgaccggccagttgctttggagagtgataacca-----------------attaggg
tgacacgagcctggtcggtgcccaagtcttgtacgaggggaaggtattgggttctgtccc
caactagagctagcggaatcacacagaaggtctacttatactatgcacgaccacagtaca
tgttactgtactcgtcgccgtccggttgccggatggcctccgcaagtacgccgtctccac
cggtgggtctgggtggaggtcgtggggtggtgacgtcgcagtccaaacatcc--------
----------------------------------------------------gtggccgt
ggtgatgagtgggtcgctat---------------------aacatcag-----------
-----------------gcaccatggtctggaacacgtcctctccctgcgtggtcaatgg
taagagcgtttactatgtccattagcaactcggctctccgtagtgacatgtctacctata
cccagttgtccctacagacgcgctagtgggacctttctaaa-------------------
----------------------------ttccgccggcccggaaagctagagttgcggaa
gtagga------------------------aaattctgcttgaggtagcgacagcccgtt
ggtctctcgactagcctcagagctcttacagtctagttactatttgaccaccatctaaat
tttgtggttgtattaaggctcatatattgactcttggctcagctgacttctgatctcaga
aggtcagtcgctgt-----------------ctattaggtcgcttactgaccgaaaagaa
atcgcgaggacgtct---------------------actcgaccctgcacggccct----
---------------tccttcgattaaaggccaaaggcccggaacccaagacggagatcc
gagaccagagtaatgac---
>SEQ5
tggcttgcgcccaattacaaatcacaggccaggaacgcacaaggggggtggaatcgtcag
gggcgacctgccagttgctttggagagtgacatcca------------------------
-------------ttctctgcccaactcttgtacgaggggaagg----------------
--------tctagctgaatcactcagaaggtctacttatactatgcacgaccacagtaca
tgttactgtactcgtcgccgtccggttgccggatggcctccgcaagtacgccgtctccac
cggtaggtctgggtcgaggtcgtggtgtgttgacgtcccagtccccacatcc--------
--------------------------------------------------atgtgggcgt
ggtcatgagttgttcgctatagtcgacgtcatcaaataactgacatcagtcccccggaaa
g----------------gcaccatggtctggaacacgtcctctcccggcgtggtcaatgg
ttagggcgtttactatgtccattaggaactcggctctccgtagtgacatgtctacctata
cacgaatag---------------------------------------------------
----------------------------cttggccggcgcgtaaggctacaattcctaag
ttagggagcaagaaaacagagcccggcaataaatgatgcttgatgaa-------------
----tcttgagtagccgtacagctcttacagtctacttactatttgcccaccatctaaat
tttgtggttgtattatgactcatatattgactcttggctcatctgacttctgatctcaga
agttcagtcgcggttactcaaggg-----------taggggggtttctgaccgtagagag
atcgcgaggccgtct---------------------gttcgacgtcgcacgcccccgagt
gggatcaattagtgatcctccgacttaaggccagaggtctggaacccaagccttagatcc
--------------------
>SEQ6
tcgtttgcaaccgagtagaaatcacagaacagggacgctcaagggggtcccaatcgtcag
gggcgacccgccagtttcgtcggagagtgaaagctagcaaaatttaaatactcaatag--
-------------------ggacaagtcttgaacgaggggaaagta--------------
------tatctagcggtatcacacagaaggtctccttatactatgcacgaccacagtaca
tgttactgtgctcgtcgccgtccggtggccggatggcctccgcaagtaagccgtctccac
cggtagatctggac----------------------------------------------
----------------------------------------------attcatgtgggcgt
cgtcatgagttgtacgctatagtcgacgtcatcaaataactgatatcagtcccccggaaa
g----------------gcaccatggtctggaacacgtcctctcccggcgtggtcaatgg
ttatggcgtttactttgtccattaggaactcggctctccgtagtgacatgtctacctata
catcc-------------------------------------------------------
----------------------------cttggccggcgcgtaaggctataattcccaag
ttaggg----------------------------------------agcgaga-------
-------aaacaagaatcttagctcttacagtctacttactatttgcccaccatctaaat
tttggggttgtattatgactcatatattgactcttggctcatctgacttctgatctcaga
aggtcagtcgctat-----------------cgattaggtcgctttctgaccgaaaagaa
atcgctaggacgt-----------------------------------------------
------------acttccttcgattaaatgcccaaggcccggaacctaagacggagaacc
gagaccagagtaatgac---
>SEQ7
tggtgttcaaccaatgaga--------------------caaggaggctgtaatcgtcag
gggcggcccggcagggaaa-----------------------------------------
-------------------ggccaagtcttgaccgaggggatagt---------------
------tatctaacggaatgactcagaaggtctccttatactatgcacgaccacagtaca
tgttactgtgctcgtcgccgtccggtggccggatggcctccgcaagtaagccgtctccac
ccataggtccgggtcggggtcttggcacatccaaaacctag-------------------
-----------------------------------gttaggtctacagaatcg-------
------------------------------atcaaataactgacatccatcgcacggaca
g-------------------caatggtcgggaacacgtcctctccctgcgtggtcaatgg
taagagcgtttactatgtccattagcaactcggctctccgtagtgacatgtctacctata
cccagttgtccctacagacgcgctaaa---------------------------------
----------------------------ttccgcaggcccgggaagctagagttgcggaa
gtagga------------------------aaattctgcttgaggtagcgagagcctgtt
cgtctagcgactagcttcagagctcttacagtctagttactatttgaccaccatctaaat
tttgttgttgtattaaggctcatatattgactcttggctcagctgacttctgatctcaga
aggtcagtcgctggtactcgaaggtccgtggctattgggtcgct----------------
---gtgaggacgtct---------------------cctcgtcctcgcacggccctgcgt
gggcttactcgcagctccttcgattaagaggc------------cccaggacggagtaat
--------------------
>SEQ8
tggtgttcgacaaatgagaaa------------------caagaaggctgtaatcgtcag
gggcgacccgcca-------------ttgatagcta------------------------
---------------------------------------gaaggt---------------
------tatctagcggaatgacacagaaggtcgacttatactatgcacgaccacagtaca
tgttactgtactcgtcgccgtccggttgccggatggcctccgcaagtacgccgtctccac
cagtaggtcggggtcgcggtcgtggagtattaacgtcccagtccccacatcc--------
------------------------------------------------------------
---------------atgttagtcgatgtcatcaaataatgg------------------
-----------------gcaccatggtctggaacacgtcctctccctgcgtggtcaatgg
taagagcgtttactatgtccattagcaactcggctctccgtagtgacatgtctacctata
cccagttatccctacagacggtctagttagccctaacaaaaaggtaggatcgcctgcgcg
ctctcgacgaaa----------------ttccgccggcccgtaaagctacaattactaaa
ttatgg------------------------gaattttgcttgaggtagcgacagctcgtt
tgcctcttaacgagcctcagagctcttacagtctacttactatttgcccaccatctaaat
tttgtggttgtattatggctcatatattgactcttggctcatctgacttctgatctcaga
aggtcagtcgctgttactcgatggtccgtggcttttaggtcgcttactcaccgtaaagaa
atcgcgaggacgt-------------------------------------ggcactgagt
gggattactcggacctccttcgattcaaggcctaaggcccggaaccgaagacggagatcc
gaga----------------
>SEQ9
tcgttttcaacaaattagaaa-------------acgctcaaggaggatgctatcgtta-
------------agttgcgttggtgagtgatagccaacacaatataaatataaaggaggt
taacagcaaccgggtcggtggacaagtcttgaacgaggggaatgtattggcttctgtgcc
aaactttatctagcggaatgacacagaaggtctccttatactatgcacgaccacagtaca
tgttactgtgctcgtcgccgtccggtggccggatggcctccgcaagtaagccgtctccac
tggtgggtctgagtgtaagtcgtcgggtggtgacgtcgcagtctacagatcc--------
----------------------------------------------------gtggccgt
ggtgatgagcgcgtcgctat---------------------agtatcag-----------
-----------------gcaccatggtctggaacacgtcctctcccggcgaggtcaatgg
ttatggcgtttactatgtccattaggaactcgcctctccgtagtgacatgtctacctata
accagttctccgtacacacgcgctaca---------------------------------
----------------------------atccgcaggcccgggaagctagagttgcggaa
------------------------------gaattctccttgaggtagcgagagcctgtt
cgtctagcgactagcttcagagctcttacagtctacttactatttgcccaccatctaaat
tttgtggttgtattatggctcatatattgactcttggctcatctgacttctgacctcaga
aggtcaatcgctgt-----------------caattaggtcgcttactgaccgaaaagaa
atcgcgaggccgtct---------------------actcgacgctgctcggccct----
---------------tccttcgcttataggccaaaggccaggaacccaagacagaggtcc
gac-----------------
>SEQ10
tcgtttgcaagtga-------------------------ctagggggtcccaatagt---
-----------------------agagtgaaagctagcg---------------------
-------------------ggacgagtcttgaacgaggggaaagta--------------
------tacctagcggtatcactcagaaggtctacttatactatgcacgaccacagtaca
tgttactgtactcgtcgccgtccggttgccggatggcctccgcaggtacgccgtctccac
ccgtaggtctggttggagggcttgaggtggtgacgttcgagtcgag--------------
----------------------------cacctacgttaggtcttcataatcgtggccgt
ggtcatgagttggtc-----------------caaataactggcctccatcccacggaaa
gcttgcggccttgagcagcaccatggtctggaacacgtcctctccctgcgtggtcaatgg
taagagcgtttactatgtccattagcaactcggctctccgtagtgacatgtctacctata
cctagttatccctacagacgcgctactgggacctaacaaaaaggtcggatctcttgcgcg
cactcgacggaa----------------ctccgccgccccgtaaagccacaattcctgaa
ttacgg-------------------------------------agtagcgacagctcgtt
ggcctcttgacaagctgcagagcacttacagtctacttactatttgcccaccatctaaat
tttgtggttgtattatggctcatatattcactcttggctcatctgacttctgatctcaga
atgtcaatcgc----------------------atgaggtcgcttactgaccgtatagaa
atcgcgaggcggtct---------------------actcgacgctgctcggccct----
---------------tccttcgtttataggccaaaggccaggaacccaagagagaggtcc
gac-----------------
>SEQ11
tcgttttcaacaaattagaaa-------------acggtcaagaaggatgcgatcgttaa
gt-------------------------------------------------------tgc
gaacagcaacggggtcggtggacaagagttggacgaaaggaatgcattggcttctgtgcc
aaactttatctagcggaatgacacagaaggtctccttatactatgcacgaccacagtaca
tgttactgtgctcgtcgccgtccggtggccggatggcctccgcaagtacgccgtctccac
cggtgggt------------------aaggtgacttcgcagtccaaacatcg--------
------------------------------------------------------------
---------gtggtcgctat---------------------aacaccag-----------
-----------------gcaccatggtctggaacacgtcctctcccggcgtggtcaatgg
ttagagcgtttactatgtccattaggaactcggctctccgtagtgacatgtctacctata
catac-------------------------------------------------------
----------------------------cttggccggcgcgtaaggctataattcccaag
ttaggg----------------------------------------agcgtga-------
-------aaaccagaatcttatctcttacagtctagttactatttgaccaccatctaaat
tttgtggttgtattaaggctcatatattgactcttggctcatctgacttctgatctcaga
aggtcaatcgatgt-----------------caattaggtcgcttactgaccgaaaagaa
atcgcgaggccgtct---------------------actcgacgctgctcggtgct----
---------------tccttcgcttataggcccaaggccccgac----------------
--------------------
>SEQ12
ttgtgtccaaccaaggata--------------------caaggaggatgcaatcgtcag
gggcggcccggcaggggaa-----------------------------------------
-------------------ggccaagtcttgaccgaggggacggt---------------
------tctctatcggaaagacacagaaggtctccttatactatgcacgaccacagtaca
tgttactgtgctcgtcgccgtccggtggcaggatggcctccgcaagtaagccgtctccac
cggtaggtctgggttaaacatctattaggtcgac--------------------------
----------------------------------------------ctaatcgtggccgt
ggtgatgagttgggcgctatagtggacgtaatcatataactgacatcagtcccccggaaa
g----------------gcaccatggtctggaacacgtcctctccctgcgtggtcaatgg
taagagcgtttactatgtccattagcaactcggctctccgtagtgacatgtctacctata
cctagttattcctacag-------------------caaaaaggtcggatctcttgcgcg
cactcgatggga----------------ctcagccgccccgtaaagcctcaattcttcaa
ttacgg-------------------------------------agtggcgacagctcgtt
-------------------gagctcttacagtctacttactatttgcccaccatctaaat
tttgtggttgtattatggctcatatattgactcttggctcatctgacttctgacctcaga
aggtcattcgaggg---------------------------------------tcgcgaa
atcgctaggacgt-----------------------------------------------
---------------tgctgcgattaaatgccaaagggccggaacctaagacggagaccc
gagaccagagtattgac---
>SEQ13
tcgtttgaaaccaaatagtgatcacaggacaggaacgctcaaggtggctgcaatcttcag
ga---------------cgttggagagtgatagctagcaaaatataaataccaagtaggg
taacaggagccgggtcagtgcgcaagtcttgaacgaggggaaagtactggggtctgtccc
aaactatatccagcggaatcactcagaaggtctgcttatactatgcacgaccacagtaca
tgttactgtactcgtcgccgtccggttgccggatggcctccgcaagtacgccgtctccac
cggtaggtctgtattaaacatctatagaggtgat--------------------------
------------------------------------------------------------
------gagttgggcgctatagtggacgtaatcatatcactctcatcagttccccggaaa
g-------------------ccatggtctggaacacgtcctctcccggcgaggtcaatgt
ttatggcgtttactgtgtccaataggaactcgcctctccgtagtgacatgtctgcctata
tatcc-------------------------------------------------------
----------------------------cttggccggcgcgtaacg--------------
------------------------------------------------------------
----------aaaagaccttagctcttacagtctagttactattcgaccaccatctaaat
tttgtggttgtattaaggctcctatattgactcttggctcagctgacttctgatctcaga
aggtcagtcgctggtactcttgggt----------------------------------a
gctgtgagcacgtct---------------------cgtcgtcctcgcccggcccagcgt
gggcttactcgcacagccttcgattaagaggc------------cccaggagggagtaat
--------------------
>SEQ14
tcgtttgaacccaaatagtgatcacaggacaggaacgctctgggtggctgcaatc-----
-----------------cgttggagagtgatacctagcaaaaaataaatatcaagtagtg
taacaggagccgggtcagtgcgcaagactcgaacgcggggagagtactggggtctctccc
aaactatatctagcggaatcacacagaaggtctgcttatactatgcacgaccacagtaca
tgttactgtgctcgtcgccgtccggaggccggatggcctccgcaagtaagccgtctccac
ccgtaggtctggggggcgggtgcggcgtggtgacatttgagttcggacatcc--------
-------------------ttactccacgacctaggttaggtctacataatagtggccgt
gtccaggacatggtcggtatcgtcgatgtcatcaaataacggacatcaacccgatgagct
-----------------gcaccatggtctggaacacgtcctctccctgcgtggtcaatgg
taagagcgtttactatgtccattagcaactcgggtctccgtagtgacatgtctacctata
catccct-----------------------------------------------------
-------------------------------------------------tgactcccaga
ctaggg----------------------------------------agcgaga-------
-------aaacaagaatcttagcacttacagtctacttactatttgcccaccatctaaat
tttgtggttgtattatggctcatatattcactcttggctcatctgacttctgatctcaga
aggtcaatcgatgt-----------------caattaggccgcttactgaccaaacaaaa
atcgcgaggccgtct---------------------cctctacgctgctcagtccgac--
------------------------------------------------------------
--------------------
>SEQ15
tagtttgcaacagattagaaatcacagaagagggacgctcacggaga-------------
--------------------------gtaaaagctagcaacatttaaatacacaatag--
-------------------ggacaagtcttgaaa--------------------------
------tatctagcggtatcacacagaaggtctccttatactatgcacgaccacagtaca
tgttacagtgctcgtcgccgtccggtggccggatggcctccgcaagtacgccgtctccac
cggtaggtctgtattaagcatcta------------------------------------
------------------------------------------------------------
--------------------------------tagatcactctcatccgttccccggaaa
g-------------------ccatggtctggaacacgtcctctcccggcgtggtcaatgg
ttagggcgtttactatgtccattaggaactcggctctccgtagtgacatgtctacctata
cccagttatctctacagacgcgctagtgagacctaacaaaaaggtcggatcacttgcgcg
cactcgacggaa----------------ctccgccggcccgtaaacctataattcgtgaa
ttattg---------------------------------------------aagctcgtt
ggccgcttgactagcctcaaagctcttacagtctagttactatttgaccaccatctaaat
tttgttgttgtattaaggctcatatattgactcttggctcagctgacttctgatctcaga
agggcagtcgcggtaactcgatggtccgtggcttttaggtcgcatactcaccgtaaagaa
atcgctaagacgt-------------------------------------ggcactgagt
gggattacccggacctc-----------------aggcccggaaccgaatacggagatct
gaga----------------
>SEQ16
tcgttcgcaccaaattagaagtcacagcacaggaacgcccaaggggggtgcagttg----
-----------------ctttggagagtgataacca-----------------attaggg
tgacacgtgcctggtcggggcccaaggcttgcaagaggggagggtattgggtactgttcc
caactggagctagcggaattacacagaaggtctccttatactatgcacgaccacagtaca
tgttactgtgctcgtcgccgtccgatggccggatggcctccgcaagtaagccgtctccac
acatacgtccgggtcggggtcttggcacatccac--------------------------
------------------------------------------------------------
--------------ctaggttgggtctacaatcaaataactgacatccatcgcacggaca
g-------------------ccatggtctggaacacgtcctctccctgcgtggtcaatgg
taagagcgtttactatgtccattagcaactcgggtctccgtagtgacatgtctacctata
catcc-------------------------------------------------------
----------------------------cttggccggcgcgtagggctataattcctaag
ttaggt----------------------------------------agcgaga-------
----------acacaagaacagctcttacagtctagttactattcgaccaccatctaaat
tttgtggttgtattaaggctcctatattgactcttggctcagctgacttctgatctcaga
aggtcagtctctggtactcgaaggtccgtggcaattgggtcgct----------------
---gtgaggacgt----------------------------------------------t
gggcttactcccagcttcttcgattgagaggc------------cccaggacggagtaat
--------------------
>SEQ17
cagtgtccaaccaaggata--------------------cttggaggatgcgatcgtcaa
ggggaa------------------------------------------------------
-------------------ggccaactcttgaccgaggggacgg----------------
---------ctatcggaaagactcagaaggtctccttatactatgcacgaccacagtaca
tgttactgtgctcgtcgccgtccggtggccggatggcctccgcaagtaagccctctccac
cggtgagt------------------aaggtgacttcgcagtgttcg-------------
------------------------------------------------------------
------------------------------------------------------------
-----------------gcaccatggtctggaacacgtcctctcccggcgtggtcaatgg
ttagggcgtttactatgtccattaggaactcggctctccgtagtgacatgtctacctatg
cccagttatatctacagccgcgctagtgagacctagtaaaaaggtcggatcacttgcgcg
cactcgacggag----------------cttcgcgggcccgtaaacctttaattcgtgag
ttattg---------------------------------------------aaggtcgtt
ggacgcttgaatagccccaaagctcttacagtctacttactatttgcccaccatctaaat
tttgtggttgtattatggctcatatattcactcttggctcatctgacttctgatctcaga
agctggtccgagg------------------cttttaggtcgtatactcaccgtaaagaa
atcgctaagacgt-------------------------------------ggctctgagt
gggattacccggacctc-----------------aagctcggaaccgaatatggagaact
gaga----------------
>SEQ18
tcggtttc----------------caggacaggaacggtc--------------------
-----------------ctctggatagtgatagctagcaaaatataaatacaaaggaggt
taacaggagcggggtcg-------------------ggggaaagtattgggttctgtgct
aaactttatctagcggaatgacccagaaggtctccttatactatgcacgacaacagtaca
tgttactgtgctcgtcgccgtccggtggccggatggcctccgcaagtaagccgtctccac
cggtaggtctgggtcgaggtcgtggtgtgttgacgtcccagtcccgatatcg--------
--------------------------------------------------ttgtgggcgt
gttcatgagttgttcgctatagtcgacgtcttcaaataactgacatcagtcccccggaaa
g----------------gcaccatggtctggaacacgtcctctccctgcgtggtcaatgg
taagagcgtttactatgtccattagcaactcgggtctccgtagtgacatgtctacctata
ccctattatacctaccgacgcgttagtgggacctagaaaaaaggtagaatcacttccgcg
ctctcgacggaa------------------------accattaaggcttcaattcctgag
ttatggagcagcaatacacagcccggcaataaactatgcatgatttagcgacagcacgt-
----------------tcacagctcttacagtctagttactatttgaccaccatctaaat
tttgtggttgtattatggctcatatattgactcttggctcatctgacttctgatctcaga
aggtcagtttctcctgctagaaggtccgggaccttta-------------------agaa
atagcgaggacggctaaacaaagcacct--------------------------------
-----------------------------------ggactggaaccctagccagagatcc
gag-----------------
>SEQ19
tcgttttcaacaaattagaaa-------------------------------atcgtta-
------------agttgcgaagttgagtgatagccaagacaatataaatataaaggaggt
taacagcaacccggtccgtggagaagtcttgaacgaggggaagatagtggcttctgtgcc
aaccgttatcaagcgtaatgacacagaaggtctccttatactatgcacgaccacagtaca
tgttactgtgctcgtcgccgtccggtggtcggatggcctccgcaagtaagccgtctccac
ccgtatgtctcgggggcgggtttggggtggtgacattcgtgttccgacataccagaaagc
atcgcgtctactgagcgtgatactccacgacctacgttaggtctacataagtgtg-----
------------------atcgtctatgtcatcaaataacggacatccacccgat-----
-----------------gcaccatggtctggaacacgtcctctcccggcgtggtcaatgg
ttagggcgtttactatgtccattaggaactcggctctccgtagtgacatgtctagctata
tatccct-----------------------------------------------------
-------------------------------------------------tgactcccaga
cgagga----------------------------------------agcgagc-------
-------aaacaagaatcttagctcttacagtctagttactatttgaccaccatctaaat
tttgtggttgtattaaggctcatatattgactcttggctcagctgacctctgatctcaga
agggtagtcgcggtaactcgatgctccgtggcttttaggtcgcatactcaccgtaaagca
atcgctaagacgt-------------------------------------ggcacttagt
gggattac----------------------cctcagacccggaaccgaagacggagatct
gaga----------------
