>SEQ0
atggagcgacaaacccctcaggtcctacatgtactaacagttgcgctcacgtagtagccg
ctggcaccagcaagaacgaagctagccccatatgctgccggctaatgctcatgacgctcg
ctgagctctgagtgcggttccttgtcgcgccccgcaacagattcgaaaatgaggtccaac
gcctgttcctgtttcctgctaacttttaccaatgtcttatatcaccagcccatagtcttt
ccgacggtcaccgtaccgaaacgttagtggcccaaacggctagctgttatcttctactgg
aacctgaccggtgagtgcacatatagacacatgcggatgctgggcttcagttttcacgta
cctatgagtcgagaagagtactgtctcaagcagactgtcagtttgcggttcttcaaaagt
ttttggagcgacgttattcgggttaagctcatacagctgatgagcgtaacctttcgcggg
cacttaaagaacgaagagaacagttagcggaaagttactgatttgaaccgcataatccgg
ctctgctactccataatcgactgatgaaatggtttatgattcgcctatgcccgagtcgtg
gctgtggtctagtgcaccccctgcgtacgctagtatgttctcttgcggggggggatatgg
gaacttaagtcgtcctccatgcccaatatagactcgccagcgcgagacgccttgacgggt
gtctactccaaccatgcccgggactgatttcatccatctgatgagagcataatagggtct
ctggttacggagattgtctgaagagcgctggggcgggattggcaggcgtgccgagcatag
gtagtaactaggtcccaggctggtcttgttcgggctatagactagaatttctgctctccc
tgtgtcgctaggccgttttgcccatgcgatacaaaggctattgaaccaggggtttcctta
accatgagacacaaatcccgctaagcagcgttaaacttacaggcatgatactggtgccgc
tccgtatcgctcaagcaaggactttacctcgctcaacccgactgaaagttttcacaatcc
ccacctagagaaacaacgtt
>SEQ1
atggagcgctaaacccctcaggtcctacatgtactaacagttgtgccc------------
----------------------------catatgctggcggttaatgctcatgacgctcg
ctgagctctgagtgcggttcctagtcgcgcccctcaacaaattctaatatgaggtcca--
-----------acccatgttcacttttaccaatgtcttatatcaccagcccatagtcttt
ccgacggtcaccgtaccgaaacgttagtggcccaaacggctagctgttatcttctactgg
caccggaacagtcagtgcacatatagacacatgcggatgctcggcttcagttttcacgta
cctttgagtcgataggagtactgtctcaagcagactgtcagttcgcggttcttcaaaagt
ttttgcagcgacgttattcgggttaa-------------------gtaacctttcgaggg
cacttaa---------aaaacagttagcggaaagttactgatttgaaccgcataatccgg
ctctgctactccataatcgactgatgaaatggtttatgattcgcctatgcccgagtcgtg
gctgtcgtctag----------------gctagtatgttctcttgcgggggtggatatgg
gaactaaagtcgtcc--------------------gccagcgcgagacgccttgacgggt
gtctactacaataatgcccgtgactgatttcatccatctgatgagagcataatagggc--
------------------tgaagagcgctggggcgggattggcaggcgtgccgagcatag
gtagtaactaggtcccaggctggtcttgttcgggctatagactagaatttctgctctccc
tgtctcgctcggccgttttacccatgcgatacaaaggctattgaaccagtggtttcctta
accaagagacacaaac--------------------ttacagggatgatactggggccgc
tccatatcgctcaagcaaggactttacctcgatcgagcaacaagatt-------------
--------------------
>SEQ2
atggagcgacaaacccctcaggtcctacatgtactaacagttgcgctcacgtagcagccg
ctggcaccagcaagaaggaagctagccccatattctgccggcaaatgctcatgccgctcg
ctgcgctctcagtgcggttccttgtcgctcccggcgacagattcgaaaatga--------
-----------tttcctgctcacttttaccaatgtcttatatcaccaacccttagtcttt
ccgacggtcaccgtaccgaaacgttagtggcccaaacggctagctgttatcttctactgg
cacccgaacagtcagtacacatatagaaacatgcggat----------------------
-------------------tctgtctcacgcagactgtcagttcgcggttattcaaaagt
ttctgcagcgacgttattcgggtcaa-------------------gtaaactttcgatgt
cagttaa---------aaaacagttagcggaaagttactgatttgaaccgcataatccgg
ctctgctactccataatcgactgatgaaatggtttatgattcgcctatgcccgagtcgtg
gctgtgatatagtgcacccccttcgtacgctagtatgttctcttgcggggggggatatgg
gaacttaattcgtcctccatgcccaatctagactagccagggcgagacgcgttgacgggt
gtctactccaaccatgcccggcactgttttcattcatctgatgagagcataataggagct
ctggttacggagatcgtctgaagagcgctggggcgggattggcaggcgtgccgagcatag
gtagtaactaggtcccaggctggtcttgttcgggctatagactagaatttctgctctccc
tctg-----------------------gatacaaaggcttttgaaccaggggtttgctta
accatgagacacaaatcccggtaaggagcgttaaacttacagtcatg-------------
------------aagcgaggactttccctcgctcaatccgactgaaagttttcacaaacc
acacct--------------
>SEQ3
atgcagcgacaaacccctcaggtcctacgtgtactaacatttgcgctcacgtagtagccg
ctggcaccagcaagaa-----------------------cgctaatgctcatgacgctcg
ctgagctccgagtgcggttccttgtcgcgccccgca------------------tccagc
gcctgttcctgttccctgctcacttttaccaatgtcttatatcaccaacccttagtcttt
ccgacggtcaccgtaccgaaacgttagtggcccaaacggctagctgttatcttctactgg
taccccaacggtcaacatgcggat------------------------------------
-------------------tctgtatcacgtagactgtcagttcgcggttattcaaaaat
-------------ttagtcgggacaa-------------------gtaaactttcgattt
cagttaa---------aaaacagttagcggaaagttactgatttgaaccgcataatccgg
ctctgctactccataatcgactgatgaaatggtttatgattcgcctatgcccgagtcgtg
gctgtggtctagtgcaccccctgcgtacgctagtatgttcacttgcggggggggatatgg
gaacttaagtcgtcctccatgcccatta---------------------cattgacgggt
gtctactccaaccatgcccgggactcatttcatccatctgatgagggcataagagggtct
ctg---------------tgaagagcgctggggcgggattggcaggcgtgccgagcatag
gtagtaactaagtcccaggctggtcttgttcgggctatagactagtatttctgctctccc
tctg-----------------------gatacataggcttttgaaccaggggtttgctta
accatgagacacaaatcccggtcaggagcgttaaacttacagtcacg-------------
------------aagcgaggactttcccacgctctatccgactgtaagttttcacaaacc
acacca--------------
>SEQ4
acgcagcgataatcccc-----------------------------tcacgtaggagcgg
ctggcaccagcgagaa-----------------------cgctaatgctcatgacgctcg
ctg-------------------------------------------------ggtccaac
gcctgttcctgtgccctgctaacatttaccaatgtcttatatcatcagcccatagtcttt
ccgacggtcaccgtaccgaaacgttagtggcccaaacggctagctgttatcttctactgg
aacctgaacggttag-----------acacatgcagatgatgggcttcagtcttcacgta
cctttgagtcgagaagagtactgtctcaagca------------------tttcaaaagt
ttttggagcgacgttattcgggttaagctca--------------tacagctgatgagcg
tacgaag---------agaacagttagcggaaagttactgatttgaaccgcataatccgg
ctctgctactccataatcgactgatgaaatggtttatgattcgcctatgcccgagtcgtg
gctatcgtctag----------------gctagtatgttcccttgcgggggtggatatga
gaacaaaagtcgtcc--------------------gccagcgagagacgccttgacgggt
gtcttctagaatcatgccggtgactcaatt------------------ataataggga--
------------------tgaagagcgctggggcgggattggcaggcgtgccgagcatag
gtagtaactaggtcccaggctggtcttgttcgggctatagactagaatttctgctctccc
tctg-----------------------gatacaaaggcttttgaaccaggggtttgctta
accatgatacacaaatcccgggaaggagcgttacacttacagttatg-------------
----------------------tttccctcgctcactccgactgacagctttcacatacc
actcct--------------
>SEQ5
atggagcgacaaacccctcaggtcctacatgtactaacagttgcgctcaggtagcagccg
ctggcaccag-----------------------------------tgctcatgccgctcg
ctgcgctctcagtgcggttccttgtcgctccgggccaccgattcgaatatga--------
-----------tttcctgctcacttttaccaatctcttatatcaccagcccatagtcttt
ccgacggtcaccgtaccgaaacgttagtggcccaaacggctagctgttatcttctactgg
caccggaacagtcagggcacttatagacacatgcg----------------------gta
ccgttcagtcgataggagtattgtctcaagcagactatcagttcgcggttcttcaaaagt
tttcgcagccacgttattcgggttaa-------------------gtaaactttggaggg
cacttaa---------aaaacagttagcggaaagttactgatttgaaccgcataatccgg
ctctgctactccataatcgactgatgaaatggtttatgattcgcctatgcccgagtcgtg
gctgtggtctagtgcaccccctgcgtacattagaatgttcgcttgctggaggggatatgg
gaacttaagtcgtcctccatgcccaacatagact--------------------------
------------ccttgacgtgactgatttcttcgatctgatgagaggataatggggtct
ctggtgacggagattgtctcaagagcgctggggcgggattggcaggcgtgccgagcatag
gtagtagctaggtcccaggctggtcttgttcgggctatagactagaatttctgctctccc
tctg-----------------------gatacaaaggcttctgaaccaggggtttgctta
accatgatacacaaatcccgggaaggagcgttagacttccagttatccgactggcacc--
-------------------------------------------------tttcacatacg
actcct--------------
>SEQ6
atgcagcgataatcccc-----------------------------tcacgtaggagcgg
ttggcaccagcgagaa---------------------------------cgtgacgct--
------------------------------------------------------tccatc
gcgtgttccggtgccctgctaacatttaccaatgtcttatatcataagcccatagtcttt
ccgacggtcaccgtaccgaaacgttagtggcccaaacggctagctgttatcttatactgg
cagccggacagtaagtacacatatagaaacttg---------------------------
--------------------ctgtctcacgcagattgtcagttcgcggttattaaaaagt
ctctgcatcgacgttattcgggtcaa-------------------gtaaactttagatgt
cagttaa---------aaaacagttagcggaaagttactgatttgaaccgcataatccgg
ctctgctattccataatcgactgatgaattggtttatgattcgcctatgcccgagtcgtg
gctgtggtctagagcgccggctgcgtacgcgagtttgttcactagcctggtgggaaatag
gaaattaagtc--------------------------------------caatgacgggt
gtctactccaaccatgccttggactcctttcacccatctgatgagggcacaagagggtct
atg---------------tgaagagcgctggggcgggattggcaggcgtgccgagcatag
gtagtagctaggtcccaggctggtcttgttcgggctatagactagaatttctgctctccc
tgtctcgctcggcctttttatccatgcggttaggaggctattgaacccgtagtttgctta
accac-------------------------------ttacagggatgatactggggccgc
tcgatatcgctcaagcaaggactttacctcgatcgagcaacaagatt-------------
--------------------
>SEQ7
atggagctacaatcgcctcaggtcctacatgtcctaacagttgggatcacgtagcagccg
ctggcacccgaaagaaggaagctagcg------------------ccctcatgccgttcg
ctgcgctctcagtgcggatccttgttgctgccggctacagtttcgaaaatga--------
-----------tttcatgctcacttttaccaatctcttatatcaccagcccatagtcttt
ccgacggtcaccgtaccgaaacgttagtggcccaaacggcaagctgttatcttctactgg
aacctgaccggtgaatggacaaatagaaacatgcggatgcagggctactgttttcacgta
cctatgagtcgagaaaagtactgtctctagcagactgtcagtttgcggttctgcaaaagt
ttttggagcgacgttaatcgggttaagctcatacagctgatgagcgtaacctttcgcggg
cacttaaagaacgaagataacagttagcggaaagttactgatttgaaccgcataatccgg
ctctgctactccataatcgactgatgaaatggtttatgattcgcctatgcccgagtcgtg
gctgtggtctagtgcaccccctgcctacgctattaagtcgtccg----------------
-------------------------------------cgatgcccattacattgacgggt
gtctactccaaccatgcccgggac---------------------agcattagaggggct
ctg---------------tgaagagcgctggggcgggattggcaggcgtgccgagcatag
gtagtagctaggtcccaggctggtcttgttcgggctatagactagaatttctgctgtccc
tctctcgctcgggctttttatccatgcggttaggaggccattgatcccgtagtttgctta
accac-------------------------------tgccagggatgatactggggccac
tcgatttcgctcaagaaaggactttacctcgatcgagctgcaagatt-------------
--------------------
>SEQ8
acgtagcgatcacccc--------------------------------------------
--gaagccagcgagaa-----------------------cgctaatgctcatgacgctca
ctg-------------------------------------------------gggtcgta
gcctgttcctgtgccctgctcacttttaccaatgtcttatatcaccaacccttagtcttt
ccgacggttaccgtaccgaaacgttagtggcccaaacggctagctgttatcttctactgg
cagccggacagtaagtggacatat------------------------------------
--------------------ctgtctca----------------------cttaaaaagt
ctctgcatcgaagttattcgggtcaa-------------------gtaaactttagatgt
cagttaa---------aaaacagttagcggaaagttactgatttgaaccgcataatccgg
ctctgctactccataatcgactaatgaaatggtttatgattcgcctatgcccgagtcgtg
gctatcgtctag----------------gctagtgtgttcccttgcggagtcg-------
--------------------------------tccgccagcgagagacgcgttgactg--
------------------------------------------------------------
-----------gattatatgaagagcgctggggcgggattggcaggcgtgccgagcatag
gtagtaactaggtcccaggctggtcttgttcgggctatagactagaatttctgctctccc
tgtggcgctaggccgttttacccatgcgagacaaaggctat-------------------
-----gagacacaaatcgc----------------------gctatgatactggtgccgc
tccgtctctcatcacaatccccac------------------------------------
--------------------
>SEQ9
gtgcagcgataatcccc-----------------------------tcatgtaggagctg
ttggcaccagtaagaa---------------------------------cgtgacgct--
------------------------------------------------------tccatg
gcgtgaaccggtgccctgctcacttttaccaatgtcttatatcaccaacccttagtcttt
ccgacggtcaccgtaccgaaacgttagtggcccaaacggctagctgttatcttctactgg
cagccgtacagcatgtcgacggtctca---------------------------------
--------------------------------------------------cttaaaaagt
ctctgcatcgaagttattcgggtaaa-------------------gtgaaccttagatgt
cagttaa---------agaacagtcagcggaaagttactgatttgaaccgcataatccgg
ctctgctactccataatcgactaatgaaatggtttatgattcgcctatgcccgagtcgtg
gctgtgctctactgcaccccctgcatacattagagtgttcttaagtc-------------
---------------------------------------------------------ggc
ctccatgcacaacatagacgtgactgatttcttcaaactgataagaggataatggggtcc
ctggtgacggagattgtctcaagaccgctggggcgggattggcaggcgtgccgagcatag
gtagtaactaggtcccaggctggtcttgttcgggctatagactagaatttctgctctccc
tctg-----------------------gatacatattcttttga----------------
--------acacaaatcgcggtcaggagccttaaacttacagtcacgaggc---------
---------------------ctctcccacgctctatccgactgtatgttttcacaaacc
acccca--------------
>SEQ10
ctggagctacactcgcttcaggtcatacatgtcctaacagttgggatcatctagcagccg
ctggcacccgaaagaaggaagatagcg------------------ccttcatgccgttcg
ctg----------------ctctgttgccgccggctacagtttcgaaaatga--------
-----------ttgcatgctaacttttaccaatgtcttatatcaccagcccatagtcttt
ccgacggtcaccgtaccgaaacgttagtggcccaaacggctagctgttatcttctactgg
agcttgaccggttaatggacaaatagacacatgcggaggcaggggtactgttttcacgta
cctatgtgtcgagaaaagtactgtctttagcagactgtcagtttgcggctctgcaaaag-
----------------atcggattaagctcatacagctgatgagcggaacctttcgcg--
----------------gtaacagttagcggaaagttactgatttgaaccgcataatccgg
ctctgctactccataatctactgatgaaatggtttatgattcgcctatgcccgagtcgtg
gctgtgctccactgctaccctac-------------------------------------
------------------------------------------------------------
----------aacatagacgtgactgatttcttcaaactgataagaggataatggggtcc
ctggtgacggagattgtctcaagagcgctggggcgggattggcaggcgtgccgagcatag
gtagtaactaggtcccaggctagtcttgttcgggctatagactagattttctgctctccc
tctg----------------------------------------------------ctta
accatgagacacaaatcccggtcagcagcgttaaacttacagtcttttcacaaaccacac
ca----------------------------------------------------------
--------------------
>SEQ11
ctgcagcgacaaacccctccggtcctacgtgaactaacatctgcgctc------------
---------------------------------------------ccgctagaacgctcg
ctgacctctaagtgcggttccttgtcgcggcccg------------------gatccggc
ggcgggccctgttccctgctcacttttaccaatgtcttatatcaccaacccttagtcttt
ccgtcggtcaccgtaccgaaacgttagtggcccaaacggctagctgttatcttctactgg
tatcccaacggtcaacatgcggat------------------------------------
-------------------tctgcaccccgtagactgtaagttcgctgtta---------
------------------cgggacaa-------------------ctaaactttcgattt
tagtcga---------aagacagttagcggaaagttactgatttgaaccgcataatccgg
ctctgctactccataatcgactgatgaaatggtttatgattcgcctatgcccgagtcgtg
gctgtggactagagcgccggcagggtacgtgagtgtgttcactagcctggtgggaaatag
gaaattaagtc--------------------------------------caatgccgggc
gtctactccaaccatgccttggactcctttcacccatctgatgagggcacaagagggtct
att---------------gcaagagcgctggggcgggattggcaggcgtgccgagcatag
gtagtaactaggtcccaggctggtcttgttcgggctatagactagaatttctgctctccc
tgtggcgctaggccgttttacccatgcgagacaaagactaatcgc---------------
-----------------------------------------gctagcatactggtgccgc
tccttctcaagtcacagtctacac------------------------------------
--------------------
>SEQ12
atggagcgctaaacccctcaggtcctacatg-----------------------------
-------------------------ccccatatgctggcggttaatgctcatgacgctcg
ctgacctatgagtttggttcctagtcgcgcccctcaacaaattctaatattaggtcca--
-----------acccatgttaacttttaccaatgtcttatatcaccagcccctagtcttt
ccgacggtcaccataccgaaacgttagtggcccaaacggctagctgttatcttctactgg
cagttggacagtaagtggaccttt------------------------------------
--------------------ctgtctc-----------------------attaataagt
ctctgaatggaaattattcgggtcaa-------------------ggaaattgtagatgt
cagtaaa---------aaagcagttagcggaaagttactgatttgaaccgcataatccgg
ctctgctactccataatcgactgatgaaatggtttatggttcgcctatgcccgagtcgtg
gccgtggtccagagcgccggctgcgtacgcgagtttgttcactagcctggtgggaaatac
gaacttatgtc--------------------------------------caatgacaggt
ttctacaccaagtatgccttggactcctttcacccatctgatgagggcacaacagggtct
atg---------------cgaagagcgcttgggcgggattggcaggcgtgccgagcatag
gtagtaactaggtcccaggctggtcttgttcgggctatagactagaatttctgctctccc
tgtctcgctcggccgttttaccca-----------------tgaaccaatggtttcctca
accaagaggcagaaac--------------------ttacagggatgatactggggccgc
tctatatcgctcaagcaaggactttacctcacaagatt----------------------
--------------------
>SEQ13
acgtagagatcacccc--------------------------------------------
----agccagcgagaa----------------------------------------cgca
ctg-------------------------------------------------gggtcgta
gcctgttcctgtggtctgctaacttttaccaatgtcttatatcaccagcccctagtcttt
ccgacggtcaccataccgaaacgttagtggcccaaacggctagctgttatcttctactgg
cagcccgacagcaagtacacacaaagaaatttg---------------------------
--------------------ttgtcacacgcagattgtcagttcgcggttataaaaaagt
ctctgaatcgaccttattcgggtc------------------------------------
------------------aacagttagcggaaagttactgatttgaaccgcataatccgg
ctctgctactccataatcgactgatgaaatggtttatgattcgcctatgcccgagtcgtg
ccggtggtctagtgcaccccctgccctc-tgaggtcgt----------------------
-------------------------------------------------cattgacgggt
gtctactccaaccatgcccgggac---------------------agcattagaggggct
ctg---------------tgaagagcgctggggcgggattggcaggcgtgccgagcataa
gtagtaactaggtcccaggctggtcttgttcgggctatagactagaatttctgctctccc
cctctcgctcgggctttttatccatgcggttaggaggccattgatcccgtagtttgttta
accac-------------------------------tgccagggatgatactggggccac
tcgatttcgctcaagaaaggactttacctcgatcgagctgcaagatt-------------
--------------------
>SEQ14
atggagcgacaaaccccaggggtcctacttgtactaacagttgcgctcacgtagcagccg
ctggcaccagcaagaagcaagatagccccatattctgccggcaaatgctcatgccgctcg
ctgcgcactcagtgcggttccttgtcgatcccggcgacagattcgaaaatga--------
--------------------cacttttaccaatctcttatatcaccagcccatagtcttt
ccgacggtcaccgtaccgaaacgttagtggcccaaacggcaagctgttatcttctactgg
taccccaacgatgcggatgtcgta------------------------------------
------------------------------------------------------------
--------tcaatttagtggggacaa-------------------ctaaactgtcgattg
caggtaa---------aaaacagttagcggaaagttactcatttgaaccgcataatccgg
ctctgctactccataatcgactgatgaaatggtttatgattcgcctatgcccgagtcgtg
gttgtgctccactgctacccac--------------------------------------
------------------------------------------------------------
----------aacataggcgtgactgatttcgtgtaactgataagaagataatggtgtcg
ctg---------------gtaagagcgctggggcgggattggcaggcgcgccgagcatag
gtagtagctaggtcccaggctggtcttgttcgggcgatagactagaatttctgctctcgc
actg-----------------------gatacatttttttttga----------------
--------acacaattcgcgggcaggagccttaatcttacagttacgag-----------
------------------------------------------------------------
--------------------
>SEQ15
atggagctacaatctcctcaggtcctacatgtcctaacatttggtatcacgtagcagccg
ctggcacccgaaagaaggaatctagcg------------------cgctcatgccgttcg
ctgcgctcgcagtgcggatccttgctgctgccggctacagtttcgaaaagga--------
-----------tttcatgccaacttttaccaatgtcttatatcaccagcccctagtcttt
ccgacggtcaccataccgaaacgttagtggcccaaacggctagctgttatcttctactgg
agcttgaccggttaatggacaaatagacacatgcggaggcaggggtactgttttcacgta
cccaagtgtcgagaaaagtactgtcattagcagactgtcagtttgcggctctgca-----
----------------------ttaagctcatacagatgat-------------------
----------------gtaacagttagcggaaagttactgatttgaaccgcataatccgg
ctctgctactccataatcgactgatgaaatggtttatgattcgcctatgcccgagtcgtg
ccgttggtctactgcacccccagaggtcgt------------------------------
-------------------------------------------------cattgacgggt
gtctactccaaccatgcccgagat---------------------agctttagaggggct
ctg---------------tgaagagcgcttgggcgggattggcaggcgtgccgagcatag
gtagtaactaggccccaggctggtcttgttcgggctatagactagaatttctgctctccc
tctctcgctcgagctttt----------------aggccattgatcccgtagtttgctta
accac-------------------------------tgccagggttgatact--------
------tcgctaaagataggaccttacctcgatcgagcttct------------------
--------------------
>SEQ16
ctgcagggacaaacccctccggtcctacgtgaaataacatctgcgctc------------
---------------------------------------------ccgctagaatgctcg
ctgacctctaagtggggttccttgtcgcggcccg------------------gctccggt
ggcggg-------ccctgttaacttttaccaatgtcttatatcaccagcccctagtcttt
ccgacggtcaccataccgaaacgttagtggcccaaacggctagctgttatcttttacagg
cagccggacagtaagtg-------------------------------------------
---------------------------------attggtatttcgccgttattaaaaggt
ccctgcatcgacgttatttgggtcga-------------------gtaaacttt------
-------------------acagtcagcggaaagttactgatttgaaccgcataatccgg
ctctgctactccataatcgactaatgaaatggtttatgattcgcctatgcccgagtcgtg
gctgtggactagagggccggcagggtacgtgagtgtgtccactagcctggtgggagatag
gaaattaagtc--------------------------------------cagtgccgggc
ctctagtccaaccacgccttggactcctttcaaccatctgatggagggacaagagggtcc
aat---------------gcaagagcgctggggcgggattggcaggcgtgccgagcatag
gtagtagctaggtcccagcctggtcttgttcgggctatagactagaatttctgctctccc
tgtgggcccaggcagtctgacccatgcgagacaaagactagc------------------
-----------------------------------------------atactggtgccgc
tccttctcaag-------------------------------------------------
--------------------
>SEQ17
ctgcagcgacgaacctctccggtcctacgtgaaccaacttccgc----------------
---------------------------------------------ccgctagaacgctcg
ctgacctataagggcggttacttgtcttggcccg------------------gatccgga
ggcgggccctgttccctgctaacttttaccaatgtcttatatcaccagcccctagtcttt
ccgacggtcaccataccgaaacgttagtggcccaaacggctagctgttatcttctactgg
aacctgagcggtgaatggacaaatagaaacatgcggatgcaaggttactgttttaacgta
cctataagtcgagaaaag---------------------agtatgcggttctgcaatagt
ttttggtgcgactttaatcgtgttaagctcatacagctgatgagcgtaacctttcgcggg
cgctt-----------aaggcagttagcggaaagttactgatttgaaccgcataatccgg
ctctgctactccataatcgactgatgaaatggtttatggttcgtctatgcccgagtcgtg
gctgtgc-----------------------------------------------gtatgg
gaacttaaggcgcgc---------------------------------------------
-tccatgcccattacatccgggcctcatttcatccatctgctg----------------t
ccg---------------tgaagagcgcttgggcgggattggcaggcgtgccgagcatag
gtagtaactaggccccaggctggtcttgttcgggctatagactagaatttctgctatccc
tgtgggcccaggcagtctgacccatgcgagacaaagactaac------------------
-----------------------------------------------atactggtgccac
tccctctcacg-------------------------------------------------
--------------------
>SEQ18
acggagcgacagaccccgacggtcctacttgtactaacagtggcgctcacgaagcagccg
ctggcaccagcaagaatcaagatagccccatattctgcggccacatgctcatgccgctcg
ctgcgcccttagtgcggttccttctcgatcacggcgacagattcgaaaatga--------
--------------------caattttaccaatctcttatatcaccagcccatagtcttt
ccgacggtcaccgtaccgaaacgttagtggcccaaacggcaagctgttatcttctactgg
aacct---------------------acacttgcaggagctggacttcagtcttcacgct
ccattaagctgagaagagtactgtctcaagta------------------ttttagaaat
ttttggagcgacgtaattcgggttaagctct--------------tacagctgatgagcg
tacggag---------agaacagttagcggaaagttactgatttgatccgcataatccgg
ctctgctattccataatcgactgatgaattggtttatgattcgcctatgcccgagtcgtg
gctgagctccactgctaccctac-------------------------------------
------------------------------------------------------------
----------aacatatacgtgactgatttcttcaaactattaagaggttaatggggtcc
ctggtgacggcgattgtctcaagagcgctggggcgggattggcaggcgcgccgagcatag
gtagtagctaggtcccaggctggtcttgttcgggcgatagacgagaatttctgctctcgc
tgtggcgctaggggctat------------------------------------------
-----gagacacaaatcgc----------------------gctatgatactggtgccgc
tccgtctctcatcacaatccccac------------------------------------
--------------------
>SEQ19
caccatggacaaacccctatggtccgacgt------------------------------
---------------------------------------------ccgctagaatgctcg
ctgacccctaagtgggggtcctggtcgcggcccg------------------gctccggt
ggcggg-------cccagtacacttttaccaatctcttatatcaccagcccatagtcttt
ccgacggtcaccgtaccgaaacgttagtggcccaaacggctagctgttatcttctactgg
cagccggacagcaagtg-------------------------------------------
---------------------------------attgttatttcgccgttattaaaaggt
ccctgcatccacgttatttgggcaga-------------------cttaactttc-----
--------------------cagttagcggaaagttactgatttgaaccgcataatccgg
ctctgctactccacaatcgactgatgaaatggtttatgattcgcctatgcccgagtcgtg
gttgtgctccactgcgacacaac-------------------------------------
------------------------------------------------------------
------------------------------------atcggtaagaagacaatggtgtcg
ctg---------------gtaagagcgctggggcgggattggcaggcgtgccgagcatag
gtagtagcgaggtcccaggctggtcttgttcgggctatagactagaatttctgctctccc
tctctcgatcgagctttt----------------aggccaatgatcccgtagtttgctta
accac-------------------------------agccggagttgatact--------
------tcgttaaagataggaccttacctcgatcgagctact------------------
--------------------
