>SEQ0
ttacctgggaaatagccataaaccaaacatctgcccgtccatggcacacgagacatcatg
cgtagtcgagattacggtatcaccatagcactctggtcaaggagtcaccacctacaaccg
tatatcccggtgaacctacactcaagtgcgtaaggcaaatgacatcctatcgttaactca
atcgttatctttagctttgccaaccaagatataatagaagagcgttgagatcatcgtggg
ccctatagtggcgtctagtttgactgcctatactctgaggcacagtaccattggccctct
aagatgagcttccctaggagggattacaccggactcgttccgactgtggagtcaggtacg
gactttcgacctcatctaagcttgtttaatctcgccccggtccgcatgccatcgaagtgc
ttcagctcttctgtgtatggctcaagttcactgtcggtctgctgtgcggactcagcctgt
cttcatacttttttttcacaggaacatcatcaaagtcctggcctcagcacccgcagtcta
tgcaactaacgattccggcgagtgccgatcgttttcgaagatgcccaccgactattagga
ccctacttagacaaaataaaggttgtaatctaagtagaatgatagacggagccggtatca
ctaactcttcgtagaaaagcacttgtcgtggggagaaattgcgattatcatgatggacca
a-cagccgctgggcgtgactccgattcgacggttatgctcgacagtgggtctgtaccacg
aggttcgagccgggaaacgtaccatattataacgacacgattcagtggtctaaatagacg
agctctttaaccacgagcgcatctttaggaccgtaacagcgcggagagaatctgcctgat
atccatagagtactagacgcgcaaagcgccgtccgctaccctcgccttggaactgcctaa
ccggtcagtgcgggtatggtggtgcccgatcatgaagaacacgagcctccgagcccgccc
ttggcttacgggtagtgtgagagccttctcattaaaacggtaacttgagcgataccgatg
ccgacttgtacacgtagcgta
>SEQ1
gtacctgtgaaatagccaaaaacctaacagctgcccgtccgtggcacacgagacataatg
agtagtcgaaattacggcatcaccatagcacattggtcaaggcgtcaccacctacatccg
t-----------------------agggcgtaaggcaaaggagataatatcgttaactcg
agcgttatcttgagctttgccaaccaagatataatagaagagcgttgagatcatcgtggg
ccctatagtggcgtctagtttgactgcctatactctgaggcacagtaccattggccctct
aagatgagcttccctaggagggattacaccggact--------------agtcaagtacg
gactttcgacctcatctccgcttgtttaatatcgccccggtccgcatgacaccgaa----
---------tctgtgtatggctaaggttcactgtcggtctgctgtgcggactcagcctgt
cttcatacttttttttcacaggaacatcatcaaagtcctggcctcagcacccgcagtcta
tgcaactaacgatttcggcgagtgccgatcgttttcgaagatgcccaccgactattagga
ccctacttaga-----------------------tagaatgacagacggagcaggtatca
ctaactcttcgaagaaaagcactggtggtggggagaagttgcgattataatcatagacca
a-cacccgctgtgcgtgactctgattcgactgttatgctcgacagtggatctgtaccccg
aggttcgagccgggaaacgtaccatattataacgacacgattcagtggtctaaatagacg
agctctttaaccacgagcgcatctttaggaccgtaacagcgcggagagaatctgcctgat
atccagagagtcgtagtcccgcaaagcgccgtccgctacactcgccttggaactgcctaa
ccggtcagtgcgagtatggtggtgcccgatcatgaaggacacgtgcctccgagcccgccc
ttggcttacgggttgtctgagagccttctcattaaaccggtaacgtgagcgacaccg---
--------tacgcgtaacgta
>SEQ2
gtacctctgaaatagccaaaaacccaacagctgcccgtccgtggcacacgagacagaatg
agtagtcgaaagtacggcatcaccatagcacattgatcaaggcctcaccacctacatccg
t---------------------------------------------------ataactcg
agcgttatcttaagctttgccaaccaagatataatagaagagcgttgagatcatcgtggg
ccctatagtggcgtctagtttgactgcctatactctgaggcacagtaccattggccctc-
---------ttccccagtagggactacaccggact--------------agtcatgtacg
gactttcgatctcatctccgcttgtttaatatcgccccggtc------------------
------------------------------------------actgcggactcagcctgt
cttcatactttcttttcccaggaacatcatcaaagtcctggcctcagcacccgcagtcta
tgcaactaacgatttcggcgagtgccgatcgttttcgaagatgcccaccgactgttagga
ccctacttaga-----------------------tagaatg-------------------
-------------------------taatggggagacgttgcgaatataagcatagacca
a-cacccgctgtgcgtcgctctgattcgactgttatgctcgacagtcgat----------
--------gtcgggaaacgtaccatattataacgacacgattcagtggtctaaatagacg
agctctttaaccacgagcgcatctttaggaccgtaacagcgcggagagaatctgcctgat
atccagaaagtcgtagtcccgcaaggcgccgtccgctacactcgccttggagctgcctaa
ccggtcagatcgagtatggtgttggccggtcatgaaggacacgtgcctccgagccaggca
ttggcttacgggttgtgtgagtaccttctaattaaaccggtaacgtgagcgacaccg---
--------tacgcgtaacgta
>SEQ3
gtacctcaaaaatagccaaatacccaacagcaccccgtccgtggcacacgcaccttcctc
aacgcctcacaacgtg--------------------------------------------
-----------------------------------------------catccgtaaatcg
agcgttatc----------tcaaccaagatataatagaagagcgttgagatcatcgtggg
ccgtatagtggcgtctagtttgactgcctatactctgaggcacagtaccattggccgtct
aagatgagattccctaggagggattacaccggact-------------------------
-------cgttccgacactggtagttcaataacgccccggtccgcatgccatcgaagtgt
ttcagctcttctgtgtatggctcaagttaactatcggtctgctgtgaggactcagcctgt
cttcatactatcttttcacaggaacatcatcaaagtcctggcctcagcacccgcagtcta
tgcaactaacgattccggcgagtgccgatcgttttcgaagatgcccaccgactattagga
gcatacttaga-----------------------tagaatgacagtcggagcaggtatct
ctaactcttcgaagataagcacttgtgctggggagaagttgcgattataaccatagaaca
a-cacccgctgtgcgtgcctcggattcgactgttatgctagacagtggatcggtaccccg
aggttctacccgggaaacgtcccatattataacgacacgattcaatggtctaaatagacg
agctctttaaccacgagcgcatctttaggaccgtaacagcgcggagagaatctgcctgat
atccatacagtgcgattcgcgcaa-------------accctcgccttgaatctgcctaa
cccgccagtgcgggtatggtggtgcccgatctcgaagaacacgagcctccgagcccgccc
ttggtttacgggtagtgtgagagccatgtcattaaaacggtaacttgagcgagaccgatg
cgcacttgtacacgtagcgta
>SEQ4
gtacctgtgaaatagccaaaaacctaacagctgcccgtccgtggcacacgagacataatg
agtagtcgaaattacggcatcaccgtatcacattggtcaaggcgtcagcacctacatccg
g-------------------------------------------aaatatcgttaactcg
agcgttatcttgagctttgtcaaccaagatataatagaagagcgttgagatcatcgtggg
ccctatagtggcgtctagtttgactgcctatactctgaggcacagtaccattggccctct
aacatgagattccataggagggattacaccggact-------------------------
-------cgttccaacactgggagttcaataccgccccggtccgaatgccaacgaggtgt
ttcagcgcttctgtggatgactcaagttaactatcagtctgctgttaggactcagccggt
cttcatactatcttttcacaggaacatcatcaaagtcctggcctcagcacccgcagtcta
tgcaactaacgattccggcgagtgccgatcgttttcgaagatgcccaccgactattagga
ccctacttatacaaaataaaggttggaatctaagtggaatgatagacggagccggtatca
ctacctcatcgtagaaaagcacttgtagtggggagaaattgcgattatcatgagggacca
a-cacccgctgggcgtgactccgagtcgacggttatgctcgataatagttctgtaccacg
aagttcgagcagggaaac---ccatattataacgacacgattcagtggtctaaatagacg
agctctttaaccacgagcgcatctttaggaccgttacggcgcggagagaatctgcctgat
atccagagacttgtagt----------------------acgcgccttggaactgcctaa
ccggtcagtgcgagtatggtggtgcacgatcatgtaggacacgtgcctccgagc------
--------cgggttgtcggagagcctactcatttaaccggtaaagtgagcgtcaccg---
--------tacgcgtaacgta
>SEQ5
gtatctgtgaaatagccaaaaaccgaacagctgcccgcccgtggctcacgagtcacattc
cgga--------------------------------------------------------
---------------------------------------------aatatcgttaactcg
agcgttatcttgagctttgtcaaccaagatataatagaagagcgttgagatcatcgtggg
ccctatattggcgtctagtttgactgcctatactctgaggcacagtaccattggccctct
aagatgagcgtccctaggagggattgcaccggactcgttcagactgtggagtcagatacg
gactttcga-----------------cgatctcgccccggcctgcatgctgtcgaagtgc
ttcagctcttc----------------------tcgatctgctgtgcggactcagcctgt
cttcatacttttttttcacaggaacatcatcaaagtcctggcctcagcacccgcagtcta
tgcaactaacgattccggcgagtgccgatcgttttcgaagatgcccaccgactattagga
cccgacttaga-----------------------tagaata-------------------
-------------------------taatgtggaaaggttgcgaatatcagcatagac--
-----------------------attcgcctgttgtgctcgacag---------------
----------cgggaaacgtaccatattataacgacacgattcagtggtctaaatagacg
agctctttaaccacgagcgcatctttaggaccgtaacagcgcggagagaatctgcctgat
atacatagagtccta------------------------cctcgccttggaactccgtat
ccggtcagtgcggctatggtggtgcccgatcatgaagaacacgagcctccgagcctgccc
ttggcttacgggtagtgtcagagccttctcattgaaatggtgacttgagcga--------
--------tacacgtagcgta
>SEQ6
gtatctgcgaaatagccgaaaaccgaacagccg---------------------------
------------------------------------------------------------
------------------------------------------------------------
--gattatcttgaactttgtcaaccaagatataatagaagagcgttgagatcatcgtggg
ccctatagtggcgtctagtttgactgcctatactctgaggcacagtaccattggccctct
aggatgagattccctaggagggattacaccgggct-------------------------
-------cattcagacactggtagttcaataagg----------------atcgcagtgt
ttcagctcttctgtgtatggctcaagttaactatcggtctg-------------------
---------atcttttcacaggaacatcatcaaagtcctggcctcatcacccgcagtcta
tgcaactaacgattccggcgagcgccgatcgttttcgaagatgcccaccgactattagga
ccctacttaaa-----------------------tagcatg-------------------
-------------------------taatggggagacgttgcgaatatgagcatagacca
a-cacccgctgtgcgtcgctctgacac----tcgatgtccg-------------------
------------------gtaccatattataacgacacgattcagtggtctaaatagacg
agctctttaaccacgagcgcatctttaggaccgtaacagcgcggagagaatctgcctgat
atccacagattcgtagtcactcatggcgccgtccgctacactcgccttggaactgcctaa
ccggtcagtgcgagtacggtggtgcccgatcatgacggacacgtgcctcccagcccgccc
ttcgcttacgggtggtctgagaaccatctcattaatccggtaacgggagtgacaccg---
--------tacgcgtaacgta
>SEQ7
gtacctttgaaatagccaaaaacctaacagctgcccgtccgtggcacatgagacataatg
agtagtcaaaattacggaatcaccatagcacattggtcaaggtgtcaccacctgggc---
----------------------------------------------------gtaaggca
aacgttatctgcagctttgccaaccaagatataatagaagagcgttgagatcatcgtggg
ccctatagtggcgtctagtttgactgcctatactctgaggcacagtaccattggccctct
aagatgagatgtcctcggcgggattccaccggcct-------------------------
-------cgttccgtcactgattgttcaaaaacaccccggtccgcttgccatcgaatagt
--------------------------------------------ggcggactcagccagc
cttcatactatcttttcacaggaacatcatcaaagtcctggcctcagcacccgcagtcta
tgcaactaacgatttcggcgagtgccgatcgttttcgaagatgcccaccgactgttagga
gca-------------------------------tagcatgacagtcggagcaagtagct
ctaactcttcgaagaaacgcgcttgtcctggggagaagttgtgaatataaccatag----
------------gcgtgcctcggactcgactgttatgctaaacagtggatcgggccaccg
agtttgtacacgggaaatgtcccatattataacgacacgattcagtggtctaaatagacg
agctctttaaccacgagcgcatctttaggaccgtaacagcgcggagagaatctgcctgat
attcagagaattgtagt------------------------------------------a
ccggtctgtgcgagtatgggggtgcacgatcatgtag-----------------------
--------cgggttgtcagagagcctactcatttaa------------------------
---------------------
>SEQ8
gtacctttgcaaaagccaaaaacctaaccgctgcccgtccgtggcacatgagacataatg
agtagtcaagctcaaggtgtcaccacctgggc----------------------------
----------------------------------------------------gtaaggga
tacgttatctgcaactttg-caaccaagatataatagaagagcgttgagatcatcgtggg
ccgtatagtggcgtctagtttgactgcctatactctgaggcacagtaccattggccgtct
acgacgagcttccctaggagggattaaaccggact--------------agtccaatacg
gactttcgatctcatctccgcttgtttaatatcgccccggtccgcatgaaaccgaa----
---------tctgtggacggctaaggtgcactgtcggtctgctgtccggactcagcctgt
cttcatacttttttttcacaggaacatcatcaaagtcctggcctcatcacccgcagtcta
tgcaactaacgattccggcgagcgccgatcgttttcgaagatgcccaccgactattagga
cccgagtgggg-----------------------tagaata-------------------
-------------------------taatgtggaaaggtagcgaatctcaccatagacc-
------------------------ttcgcctgttgtgctctacag---------------
---------------------ccatattataacgacacgattcagtggtctaaatagacg
agctctttaaccacgagcgcagctttaggaccgttacggcgcggagagaatctgcctgat
atccagagagtaatagttccgcaaag-------------------------actgcctaa
ccag---------------------------atgaaggac-------------cccgccc
ttggcttgcgggttgtctgagagccttctcattaaaccggtaa-----------------
--------aacgggtaacgta
>SEQ9
gcatc-------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------agccggatcaaccaagatataatagaagagcgttgagatcatcgtggg
ccctatagtggcgtctagtttgactgcctatactctgaggcacagtaccattggccctct
aagatgagattccttaggagggattacaccggact-------------------------
-------cgttccgacgctggttgttcaataacgccccggtccgcttgccattgaagtgt
ttcagctcttccgtgtatggcccaagttaactatggttctggtgtgaggactcagcctgt
ttttatacaatcttgtcaaaggaacatcatcaaagtcctggcctcagcacccgcagtcta
tgcaactaacgattccggcgagtgccgatcgttttcgaagatgcccagcgactattagga
ccctgctaa---------------------------------------------------
----------------------------tggggagacgttgcgaatatgagaatagacca
aacactcgatgcccg---------------------------------------------
------------------gtaccatattataacgacacgattcagtggtctaaatagacg
agctctttaaccacgagcgcatctttaggaccgtaacagcgcggagagaatttgcctgat
aaacacag-------------------------------tctcggcttggagctccgtat
caggtcagtgcggctatggtggtacccgatcgtgaagaacacgagccaccaagcc-----
----------------gtcagagccttctcattgaaatgctgacttgatcgc--------
--------tacacgtaacgta
>SEQ10
ggtcctttgaaatagccaaaaacctaacagatgcccg--------------------atg
aatagacaaaattacggaatcaccatagcacattggtcaaggtgtcaccacctc------
----------------------------------------------------gtaaggca
aacgtcatctgcagctttgccaaccaagatataatagaagagcgttgagatcatcgtggg
ccctatagtggcgtctagtttgactgcctatattctgaggcacagtaccattggccctct
aagatgaaattccctaggacggattacacctgact-------------------------
-------cgttccgccactggtagctcaataacgccccggtctgcatgccatcgaagtgt
ttcatctcttc---------------------atcggtctgctatgaggactcagccggt
cttcatactatcttctcacaggaacatcatcaaagtcctggcctcagcacccgcagtcta
tgcaactaacgatttcggcgagtgccgatcgttttcgaagatgcccaccgactgttagga
cccgagtgggg-----------------------tagaata-------------------
----------------------------ggcggaaaggtagcgaatctcaccatagacc-
------------------------ttcgctagtcgtgctctacag---------------
---------------------ccatattataacgacacgattcagtggtctaaatagacg
agctctttaaccacgagcgcatctttaggaccgtaacagcgcggagagaatctgcctgat
atccatagagtactagacgcgcaaagcgccgtccgctaccctcgccttggaactgcctat
cgggtgagtgcgggtatggtggtggccgatcatgaagaacacgagcctccgagcccgccc
ttggcttacgggtagtgtgagagccttctcattaaaccggtaacttgagggataccgatg
ccgacttgtacacgtagcgta
>SEQ11
ggatctgtgaaatagccgaaaaccggatagccc---------------------------
------------------------------------------------------------
------------------------------------------------------------
--gattatcttgaactttgtcaaccaagatataatagaagagcgttgagatcatcgtggg
ccctatagtggcgtctagtttgactgcctatactctgaggcacagtaccattggccctct
aacatgagcttccctaggagggattacaacggactcgttccgactgtggtgtcaggtgcg
gacttccgacctcaactaagcttgttgaatttcgccc-----------------------
-------cttctgtgtatggctcaagttcactgtcggtctgctgtgcggactcagcctgt
cttcatcctttattttcacaggaacctcatcaaagtcctggcctcagcacccgcagtcta
tgcaactaacgattccggcgagtgccgatcgttttcgaagatgcccaccgactattagga
ccctacttatcctcaataaaggttgaaatcaaagtggaatgatagat-------------
-------------gaacagcacttgtagtggggagaaattgggattatcatgagggagca
a-cacccgctgggcgtga--------------------tcgttaatagttctttaccacg
aagttcgagcagggaaac---ccatattataacgacacgattcagtggtctaaatagacg
agctctttaaccacgagcgcatctttaggaccgtaacagcgcggagagaatctgcctgat
atccagagagtaatagttccccaagg-------------------------actgcctaa
ccag---------------------------atgaaggacacg-------------gccc
ttggcttgcgggttgtctgagagccctctcattaaaccggtac-----------------
--------aacgggttacgta
>SEQ12
gtacctttgcaaaagccaaaaacctaacggctgcccgactgtggcacatgagacataata
ggtagtcaagctcaaggtgtcaccacctggac----------------------------
----------------------------------------------------gtaagtga
tacgttagctgcaactgtg-caaccaagatataatagaagagcgttgagatcatcgtggg
ccgtatagtggcgtctagtttgactgcctatactctgaggcacagtaccattggccgtct
aggatgagattccctaggagggattacaccgggct-------------------------
-------cattcacacactggtagttcgataaagatc-----------------------
------------gcgtatggctcaagttaaatatcgg-----------------------
-------------tctgacaggaacatcatcaaagtcctggcctcatcacccgcagtcta
tgcaactaacgattccggcgagcgccgatcgttttcgaagatgcccaccgactattagga
cccgagtgggg-----------------------tagaata-------------------
----------------------------ggcgaaaaggtagcgtatctcgccatagaac-
-----------------------------------ttcgctacag---------------
---------------------ccatattataacgacacgattcaatggtctaaatagacg
agctctttaaccacgagcgcatctttaggaccgtaacagcgcggagagaatctgcctgat
acacatagagtccta------------------------cctcgccttggaactccgtat
cagt--------------------------------gcacactagcctccgagcctgccc
ttggctttcgggtagtgtcggagccttctcattgaaatggta------------------
----------cacgtggcgta
>SEQ13
gcatctttgaaatagccaaaaaccgaacagctgcccgcccgtggctcacgagtcacattc
cgcag-------------------------------------------------------
------------------------------------------------------------
--cgttatcttgaactt---caaccaagatataatagaagagcgttgagatcatcgtggg
ccctatagtggcgtgtagtttgactgcctatactctgaggcacagtactattggccctct
aacataagattccctagga------------------------ctgtcgtgtcaggtgcg
gacttccgacgtcaactaagcttgttgaatttcgccc-----------------------
-------cttctgtgtatggctccagttcac-----------------------------
-----tccttgattttcacaggaacctcatcaaagtcctggcctcagcacccgcagtcta
tgcaactaacgattc-----agtgccgatcgttttcgaagatgcccaccgactattagga
ccctacttagacaaaataaaggttgttatttaagtagaatgatagacggagccggtgaca
ctaactcttcgcggaaaagcacttgtcgtgggcagacattgcgattatcatgatggacca
a-cagccgctgggcgtgactccgattcggctgt---------------------accacg
aggttcgagccgggaaa----ccatattataacgacacgattcagtggtctaaatagacg
agctctttaaccacgagcgcatctttaggaccgtaacagcgcggagagaatctgcctgat
attcagagaattgtagatgatgtgg-----------------------------------
------------------------------------------------------------
--------------gtcagagagccgacttatttaa------------------------
---------------------
>SEQ14
ggatctgtgaaatagccgaaaaccggatagcc----------------------------
------------------------------------------------------------
------------------------------------------------------------
-------cgagaaacattgtaaaccaagatataataaaagagcgttgagatcatcgtggg
ccctatagtggcgtctagtttgactgcctatactctgaggcacagtaccattggccctct
acgacgagcttccctaggagggattaaagcggact--------------agtccaatacg
gactttcgatctcatctccgcttgtttaatatcgccgtggtccgcatgaaaccgta----
-------------------------------tgtcgttctgctgtgcgaactcagagtgt
cttcatacatttttttcacaggaacatcatcaaagtcctggcctcagcacccgcagtcta
tgcaactaacgattccggcgagtgccgatcgttttcgaagatgcccaccgactattagga
ccctagttaga-----------------------tagaatg-------------------
-------------------------tagtggggaaacgttgcgaatctaagcatagacct
a-cacccggtgtccgtcgctctgatacgacttcaatgctcgaccg---------------
--------------------gccatattataacgacacgattcagtggtctaaatagacg
agctctttaaccacgagcgcatctttaggaccgtaacagcgcggagagaatctgcctgat
aacgagaaagtcgtcgtcccggaaggtgccgtccgctacactcgccttggagctgactaa
ccggtcaggtcgagtatggtgttggccggtcatgaaggacacgtgcctccgagctaggta
ttggcttacgggttgtgtgtg-------------------taacgggagcgaaaccg---
--------tacgcgaaacata
>SEQ15
gtacctgtcaaatagccaaaaacctaacagctgcccgtccgtggcatacgagacacaatg
agtagtcgaaattacaggggtcaccacctaaatccgt-----------------------
------------------------agggcgtaaggcaaaggagataatatcgttaactcg
agcgttatcttgagctttaccaaccaagatataatagaagagcgttgagatcatcgtggg
ccgtatagtggggtctagtttgactgcctatactctgaggcacagtccccttggccgtct
aatctgagatgtcctcagtgggaatccaccggcct-------------------------
-------cgtgccgtcactgattgttcaaaaacaccccaa--------------------
-----------------------------------------cagtgttgactcacctagc
cttcatact--------atcggaacatcatcaaagtcctggcctcagcacccgcagtcta
tgcaactaacgattccggcgagtgccgatcgttttcgaagatgcccaccgactattagga
cccgtgtgggg-----------------------tagaata-------------------
-----------------------------gcgaaatggtagcgtatctcgcgatcgatct
t-ca--------------------------------------------------------
---------------------ccatattataacgacacgattcagtggtctaaatagacg
agctctttaaccacgagcgcatctttaggaccgtaacagcgcggagagaatcggcctgat
atg--------------------------------------tcggcttggtgctccgtat
caggtcagtgcggctatggtggtagccgagcgtgaaaaacacgagccaactagcctgact
tgatcgc-----------------------------------------------------
--------tacacgtcacgaa
>SEQ16
ttacctcaaaaatagccaaagtcccaacagcaccccgtccgtggcac-------------
------------------------------------------------------------
------------------------------------------------------------
----caatcgagcaatatctcaaccaagatataatagaagagcgttgagatcatcgtggg
ccctatagtggcgtctagtttgactgcctatactctgaggcacagtaccattggccctct
aacctaagattccctagcagg-----------------------------------ttcg
gacttccgaagtcaactacgcttgttgaagttcgccc-----------------------
-------cttctgtgtatggctccagtttac-----------------------------
-----tccttgattttcccaggaacatcatcaaagtcctggcctcatcaccctcagtcta
tgcaactaacgattccggcgagcgccgatcgttttcgaagatgcccaccgactattagga
cacgtgtggga-------------------------------------------------
-----------------------------gcgaaagggtagcgtatctcgcgatcgatct
a-ca--------------------------------------------------------
---------------------ccatattataacgacacgattcaatggtctaaatagacg
agctctttaaccacgagcgcatctttaggaccgtaacagcgcggagagaatctgcctgat
atacaaacggtccta------------------------cctcgccttggaactccgtat
ccggtcagtgcggctatggtggtgcccgatcattaag----------------cctgtcc
ttggcctacgggtagtgtcagtgactt---------------------------------
--gagcgatacacgtagggta
>SEQ17
gtacctttgcaaaagccaaaaacctaaccacttcccgtccgtggtacatgagacataatg
agtagtcaagctcaaggtgtc---------------------------------------
-----------------------------------------------------taaggga
tagattatctgcaactttg-caaccaagatataatagaagagcgttgagatcatcgtggg
ccctatagtggcgtctagtttgactgcctatactctgaggcacagtaccattggccctct
aatctgagatgtcctctgtgggaat-----------------------------------
---------------cactgattgttcaaaaacactccaa--------------------
-----------------------------------------cagtgttgactcacgtaga
cttcata--------ttatcggaacatcatcaaagtcctggcctcatcacccgcagtcta
tgcaactcacgattccggcgagcgccgatcgttttcgaagatgcccaccgactattagga
ccctacttatatgaaataaaggtggtaatctaagtggaatgatagacggcgccggtagca
ctacctcatcgtagaaaagcacttgtagtggggagaaattgcgattaccatgagggacca
a-gacccgctgggcgtgactccgagtcaacggttatgctcgataatagttctgtacctcg
gagt-----------------ccatattataacgacacgattcagtggtctaaatagacg
agctctttaaccacgagcgcatctttaggaccgtaacagcgcggagagaatctgcctgat
atccatagagtacgagacgcgcaaagcgccgtccactacactcgcactggacctgcctaa
accgtcagtgcgggtctggtggtgcccgatcgtgaag--------------------ccc
ttggcttacgggtagtgtgagagccttctcattaaaacggtaacttgttcgataccgatg
ccgacttgtacacgtagcgta
>SEQ18
gaatctttgaaatagccaaaagccgaacagctgtccgcacgtggctcacgagtca-----
------------------------------------------------------------
------------------------------------------------------------
----ctttccgcagcattgtcaaccaagatataatagaagagcgttgagatcatcgtggg
ccctatagtggcgtctagtttgactgcctatactctgaggcacagtaccattggccctct
aggatgagattccctaggagggaatactccgtgct-------------------------
-------cattcacacactggtagttcgataaaaatc-----------------------
------------------------------------------------------------
-----------gccaagacaggaacatcatcaaagtcctggcctcatcacccgcagtcta
tgcaactaacgattccggcgagcgccgatcgttttcgaagatgcccaccgactattagga
ccctacttatcctcaataagagat------------------------------------
-------------gaacagaacttctagtggggagaaa----------------------
-------------------------------agcaacatcgtttatagttatttaccacg
aagtacgagcagggaaac---ccatattataacgacacgattcagtggtctaaatagacg
agctctttaaccacgagcgcatctttaagaccgtaacagcgaggagagaatctgcctgat
atccagaaagtcgtagtcccgcaaggcgccgtccgctacactccccatgcagctgcctaa
ccggtccgatcgagtatggtgttggccggtcatgaaggacccgtgcctccgagccag---
-----ttacgggttgagtgagcaccttcaaattaaaccggtaacgtgagcgaaaccg---
--------gacgcgtaacgt-
>SEQ19
ggatctgtcaaatagtcgaaacccggatagctc---------------------------
------------------------------------------------------------
------------------------------------------------------------
--gattatcgtgaactttgtcaaccaagatataatagaagaacgttgagatcatcgtggg
ccctatagtggcgtctagtttgactgcctatactctgaggcacagtaccattggccctct
acgacgagcttccctatgagggattaaaccggaca--------------agtgcaatagg
gactttcgatctcatctccgcttgtttaatatcgccccggtccgtatg------------
-------catctgtggacggctaatgtgcactgtccgtctgctgtccggactcaggctgt
cttcatactttttttgcacaggaacatcatcaaagtcctggcctcagcacccgcagtcta
tgcaactaacgatttcggcgagtgccgatcgtgttcgaagatgcccaccgactattagga
cccgacttaga-----------------------tagaata-------------------
------------------------------------------------------------
-----------------------------tgatcctgctcgacag---------------
----------cgggaaatataccatattataacgacacgattcagtggtctaaatagacg
agctctttaaccacgagcgcatctttaggaccgtaacagcgcggagagaatctgcctgat
atccagaaggtcgttgtcacgcaaggcgccatccgctacactcgccatggagctgcctaa
ccggtcagatcgattgttctgttggccggtcattaaggacacgcgcctcagagccaggca
ttggcttacgggttgtgtgagtaccttctaattaaaccggtaacgtgagcgacaccg---
---------------------
