>SEQ0
cgcttcgtagccccgctttgtgcag--acgtcccgcatactgatagaagcaaatcatgaa
atcgtcctaaacacccaacttctagcaatcccagggacctagactcaggatgtccggggc
ttcaaaactgctgccggctgagtgaccccacaaccattataaagcctaggagggcgc---
-------acgtgctccaggt---ctcccaccctagggttgcgataatggcgtacgcgcgg
aagtttaaggcgatatctgccccccatcgttggcatccttggagaatagtaatcacaccg
catgcactcattctctgcagttcaatgctttgttcttgaccgaggactgaaacaggttac
agaggaccaaggagaatgtctacgcggtgtcctggagaatgatttaaatagacttcgaaa
ccctatgtggaacgtcccgctagtcaggctttgaaaaaacag-agcttgtcatgtcggtt
agggaatccccatgatatcggtcgcggcctgccaaattgagccctgcagtgttggtcgtc
atgtggagatgtttcccgtgtgtaggtgtccagcaatgaccacgacttggtgagctattg
gtccaaagggacccccccgaacctgatcccaggcaggggcctgcccactgggagtgatcc
aatgaggtcgccgtgacaccttctaaccaccactttaaccgccctcgcccatttcatccc
tcatgacatataacgactagggtgttcacggcagggaggggctacactttctactcgccg
cacgaatatgaacgttcgatggggcgagccgcgaaaaatggtcggagaagatagcctacg
gcacttacatatatagggaagatgcggtgggcgggctacagatcactcggtggaaaacac
taccgcaaacatcttatgaaggagctattatacaattattcgctgagtaagtagtcaagg
tgacgcccgacagtcgcttccacaacacagtccggagaatcgaataagttcatttgtaac
gtcccctgggggtgtcctactgaacaacttagccctaatgtcaagagtgctatcgtagca
cccatcgacatcggacttactactgagcctgtgttc
>SEQ1
cgcttcgtatccccgctttttgcag--acgtcccgcatactgatagtagctaatcatga-
-----tctagcaatcaca----------------------------------------gg
gtctaaactgctgccggctgagtgaccccacaatcattataaagcctaggaggccgc---
-------acgtgctccaggt---ctccaaccatacggttgcgataatggcgtacgcgcgg
aagtttaaggcgatatctgccccccatcgttggcatccttggagaatagtaatcacaccg
catgcactcattctctgcagttcaatgctttgttcttgaccgaggaccgaaacagggtac
agaggaccaaggagaatgtctacgcggtgtcctggagaatgatttaaatagtcttcgaaa
ccctatgtggaacgtcccgctagtaaggctttgaaaaaacag-aacttatcatgtcggtt
agggaatccccatgatatcggtcgcggcctgccaaattgagccctgcagtgttggtcgtc
atgtggagatgtttcccgtgtgtaggtgtccagcaatgaccacgacttggtgagctattg
gtccaaagggaccccctggaacctgatcccaggcaggggcctgcacactggga-------
---------gccgtgacactttctaaccacctctttaaccccccgcgcccatttcatccc
tcatgacaaaaaacgactagagtgttcacggcagggaggggcaacactttctactcgccg
cacgaatatgaac-----------------------aatggtcggagaagatagcctacg
gcacttacatatatagggaagatgcggtgggcgggctacagatcactcggtggaaaacac
taccgcaaacatcttatgaaggagctattatacaaatattcgctgagtaggtagtcagag
tgtcgcccgagagtcggttctataacacagtccggagaatcgaggaagttcatttgtaac
gtcccccgggggtgtcctactgcacaacttagccctaatgtcaagagtgctatcgtggca
cccatcgacatcggactcactactaaggctgtgttc
>SEQ2
agcttcgtagccccgcttcgtgcag--acgtccagcatactgttagaagcaaatcatgaa
atcgttctagcaatccca----------------------------------------gc
ttccaaactgctgccg-----------------------------ctaggagggcgc---
-------acgtgctccaggt---ctaccaccctagggttgcgataatggcgtacgcgcgg
aagtttaaggcgatatctgccccccatcgttggcatccttggagaatagtaatcacaccg
catgcactcattctctgcagtt--------------------------------ggttac
agaggcccaaggagaatgtctacgcggtgtcctggagaatgatttaaatagtcctcgaaa
ccctatgtggaaagtcccgctggtaaggctttgaaaaaacgg-aacttaccatgtcagtt
agtgaatccctatgatatcggtggcgacatgccaaattgagccctgcagtgttggtcgtc
atgtggagatgtttcccgtgtgtaggtgtccagcaatgaccacgacttggtgagctattg
gtccaaagggaccccct-----------------gggggcctgcacactgggaa------
------------------------aaccacctctttatccccccgcgtccatttcatccc
tcatg-----------------------cggcatggaagggcaacagtttctactcgccg
cacgaagatgaac-----------------------aatggtcggagaagatagcctacg
gcacttacatatatagggaagatgcggtgggcgggctacagatcactcggtggaaaacac
taccgcaaacatcttatgaagcagctattatacaatgattggctgagtaagtagtcaagc
tggccccccaaagtcgcttccacaacacagtccggagaatcgaataagttcatttgtacc
gtcccctgggggtgccctactgaacaacttagccctaatgtcaagtgtgatatcgtagca
---------------------actgagcctgtgtgc
>SEQ3
agcttcgtagccccgcttcgcgcag--acgtccagtatactgttagaagccaatcatgaa
atcgttctagcaacccca----------------------------------------gc
ttccaaactgctgccg-----------------------------gtaggagggcgc---
-------acgtgccccaggt---cttccaccctagggttgcgataatggcgtacgcgcgg
aagtttaaggcgatatctgccccccatcgttggcatccttggagaatagtaatcacaccg
catgcactcattctctgcag----------------------------------ggttac
agaggcccaagtagaatgtctacgcagcgtcctggcgaagtatctaaatg----------
-------------gtcccgctggtaaggctttgaaaaaacgg-aacttaccatgtcagtt
agtgaatcccgatgatatccgtatcgacatgcc--attgagccctgcagtgttggacgtc
atgtggagatgtttcccgtgtgtatgtgtccagcaatgaccacgacttggtgagctattg
gtccaaagggaccccctgcaacctgatcccaggcaggggcccg-----------------
------------gtgacactttctaaccacctctttaatcccccgcgcccttatcatccc
tcatgacataggacgactagagtgtttacggcacggaggggcaatactttctactcgccg
cacgaatatgaac-----------------------aatggtcggagaagatagcctacg
gcacttacatatatagggaagatgcggtgggcgggctacagatcactcggtggaaaacac
taccgcaaacatcttatgaa----------------------------aagtatacaagc
cggcccccca-----------------------ggagaatagaataagttcatttgtacc
gtcccatgggggtgccctactgaacaacttagccctaatgacaagtgtgatatcatagca
---------------------actgagcctgtgtgc
>SEQ4
agcttcgtagccccgcttcgtgcag--acctccagcatactggttgaagcaaatcatgac
atcgttctagcaatccca----------------------------------------gc
ttccaatctgctgcca-----------------------------ctaggaaggccc---
-------acgtgctccagct---ttaccaccctggggttgcgataatggcgtacgcgcgg
aagtttaaggcgatatctgccccccatcgttggcatccttggagaatagtaatcacaccg
catgcgctcattctctccttta--------------------------------ggttac
agaggcccaaggataa--------------------gtatgctttaattagtcctcgaaa
ccatatgtggaaagtcccgctgataaggctttgaaaagacgg-aacttaccatgtcagtt
agtgaaaccctatgatatcggtggagacatgccaaattgagccctgcagtgttggtcgtc
atgtggagatgtttcccgtgtgtaggtgtccagcaatgaccacgacttggtgagctattg
gtcccaagggaccccct----------------caggggcctgcacactggga-------
---------gccgtgacactttctaaccccccctttaaccccccgcgcccatttcatccc
gcatgacaaaaaacgactagagtgttcacggcagggagg---------------------
------tatgaac-----------------------aatggtcggagaagatagcctacg
gcacttacatatatagggaagatgcggtgggcgggctacagatcactcggtggaaaacac
taccgcaaacatcttatgaggcagctattatacaatgattggatgattaagtagtcaagc
tggccccccaaagtcgcttgcacaacacagtccggagattcga-----------------
--cccctgggggtgccctactaaacaacttggccctaatgtcaagcgggatatcgtaaca
a-----------------------------------
>SEQ5
accttcgtagccccgcttcgggcag--acgcacagcatactgttggaagcatatcatgaa
atcgttctagcaatccca----------------------------------------gc
ttccaaactgcggccg-----------------------------ctaagtgggcgc---
-------acgtgctccaggt---ctaccaccctcgggttgcgataatggcgtacgcgcgg
aagtttaaggcgatatctgccccccatcgttggcatcgttggagaatagtaatcacaccg
catgcactcattctct-----------ctctgttcttgagcgaggaccgaaaaagggtac
agaggaacaaggaaaatgtttacgcggtgtcctgg-------------------------
-------------------------------------------aacgtatcatgtcggtt
agggaatccccagtatatcgggcgcggc-------cttgagccctgcagtgttggacgtc
atgtggagatgtttcccgtgtgtatgtgtccagcaatgaccacgacttggtgagctattg
gtccaaagggaccccctagaacataatcccaggtaggggcctgcacacttgga-------
---------gccatgacact-------------tttaaccccccgcgccgatatcatccc
tcatgaaaataaacgactagagtgt-----------------------------------
------------------------------------aatggtcggagaagatagcctacg
gcacttacatatatagggaagatgcggtgggcgggctacagatcactcggtggaaaacac
taccgcaaacatcttacgacgcg--------------attgattgattaagtagtcaaac
tagcccccgcaagtagcttgcacaacacagtccggagattcga-----------------
--cccctgggggtgcactactaaacaactccgccctaatgtcaagcgggatatcgtaaaa
a-----------------------------------
>SEQ6
agcttcgtagcaccgcttcgcggag--acgtccagcatactgttagaagcgaatcatgaa
atcattctagc-----------------------------------------------ac
ttccaaactgctgccg-----------------------------gtaggagaccgc---
-------gcgtgccccaggc---catccacccttgggttgcaataatggcgtacgcgcgg
aagtttaaggcgatatctgccccccatcgttggcatcgttggagaatagtaatcacaccg
catgcactcattctctgcagttcaatgcttggttcgtgacctaggactgagacaggttac
agag-----------------------tatcctggagaatgatttaaataaact------
---------gagcgtcccggcagtcaggctttgaacaaacag-agcttatcatgt-----
-------------------------ggcctgccaaattgagccctgcagtgttggtcgtc
atgtggagatgtttcccgtgtgtaggtgtccagcaatgaccacgacttggtgagctattg
gtccaaagggaccccct-----------------ggcggcctgcacactgggaa------
------------------------aaccacctcttaattcccccgcgtccatttcatccc
tgttg------------------------------------------cttctactcgccg
cacg--------------------------------aatggtcggagaagatagcctacg
gcacttacatatatagggaagatgcggtgggcgggctacagatcactcggtggaaaacac
taccgcaaagatcttatgaaggag------------------------------------
-------------------------------------aatagaataagttggtctgtacc
gtcccatgggggt-------------------------tgacaagtgtgatatcatagta
---------------------actgagcctgtgtgc
>SEQ7
agcttcgtggcaccgcttcccggag--atgtccatcataccgttagaatcgaatcatgaa
atcattcaaaa-----------------------------------------------ac
ctccaaaatgctcccg-----------------------------gtaggagaccgc---
-------gcgtgcctcaggc---catccaccattgggttgcgataatggcgtacgcgcgg
aagtttaaggcgatatctgccccccatcgttggcatccttggagaatagtaatcacaccg
catgcactcattctatgcag----------------------------------cgttac
agaggcgcaagtagaatctcttcggagcgtcctggcgaag--------------------
-----------------------------tttgaaaaaacggcgacttccc---------
-----------------------------------attgagccctgcagtgttggacgtc
atgtggagatgtttcccgtgtgtatgtgtccagcaatgaccacgacttggtgagctattg
gtccaaagggaccccctgcaaccggatcccaggcaggggcccg-----------------
------------gtgacactttcgaaccacctctttaatcccccgcgcgcttatcatccc
ttt-------------------------cggcacggaggggcaatactttctactcgccg
cacgaatatg--------------------------aatggatggagaagatagcctacg
gcacttacatatatagggaagatgcggtgggcgggctacagatcactcggtggaaaacac
taccgcaaacatcttatgaggcagctattatacgatgattggatgattaagtagtcaagc
atcactcccaaagtcgcttgcacaacaccgtccggggattcga-----------------
--cccctg----------------caacttggccgtaatgtcaagtgggatatcataaca
a-----------------------------------
>SEQ8
agcttcgtagccccgcttcgcgcag--acgtccagtatactgtttgaagccaatcattaa
atcgttctagcaacccca----------------------------------------gg
ttccgaattgctgcca-----------------------------gta------------
-------------cccaggt---cgtccaccctagggttgcgataatggcgtacgcgcgg
aagtttaaggcgatatctgccccccatcgttggcatccttggagaatagtaatcacaccg
catgcactcattctctgcag----------------------------------cgttac
agaggcgcaagtagaagctcttcggcacgtcctggcgtag--------------------
-----------------------------tttgaaaaaacggcgacttccc---------
-----------------------------------attgagccctgcagtgttggacgtc
atgtggagatgtttcccgtgtgtatctgtccagcaatgaccacgacttggtgagctattg
gtccaaagggacccccccgaacctgaacccagtcaggcgcctgcccactcgtagtg----
-------------------cttctaaccaccacttaaaccgccctcgcccatttcatccc
tcatgacatataaagtatagggtgttgacggcagggaggggctacactttctactccccg
cactaatctgaacgttcgatggggcgtgccgcggacaatggtcggagaagatagcctacg
gcacttacatatatagggaagatgcggtgggcgggctacagatcactcggtggaaaacac
taccgcaaacatcttatgagtcagctattatacgatgattggatgattaagtagtcgagc
atcactcccaaagccgcttgcacaacaccgtccggggattcga-----------------
--cccctg----------------------------------caacttggcctcataaca
a-----------------------------------
>SEQ9
agcttcgttacaccgcttcccggag--atgtccatcataccgttagaaacgaatcctgga
atcattcaaaa-----------------------------------------------ac
ctccaaaatgctcccg-----------------------------gtaggagagcgc---
-------gcgtgcctcaggt---catccaccattgggttgcgataatggcgtacgcgcgg
aagtttaaggcgatatctgccccccatcgttggcaaccttggagactagtaatcacaccg
gatgcactcattctctgccgaccga---------------------ccgaaccagagtac
agaggaccaaggagaacgtctacgcagtgtcctggagaatgatttaaatagtcttcgcaa
ccctatgtggaacgtcccgctaggcaggctttgaaaacacag-aacttatcaga------
-------------------------aaccccctaatttgagccctgcagtgttggacgtc
atgtggagatgtttcccgtgtgtatctgtccagcaatgaccacgacttggtgagctattg
gtccaaagggaccccctggga---------------------------------------
------------acaccacctgttacttcctgttt-------------------------
--------------------------------------------------ctactcggcg
cacg--------------------------------aatggtcggagaagatagcctacg
gcacttacatatatagggaagatgcggtgggcgggctacagatcactcggtggaaaacac
taccgcaaatatcttatgagagcatcact-------------------------------
------cccaaaaccgattgcacaacaccgtccggggattcga-----------------
--cccctgaa--------------------------------------------------
------------------------------------
>SEQ10
agcttcgtagccccgcttcgcgcag--accaccagcatactgagtgaagcaaatcatgac
atcgt--taacaatccca----------------------------------------gc
ttccaatctgctgcca-----------------------------cgaggaaggccc---
-------acgtgctccagct---ttaccactctggggttgcgataatggcgtacgcgcgg
aagtttaaggcgatatctgccccccatcgttggcatccttggagaatagtaatcacaccg
catgcactcattctctgcagttcaatgcttggttcgtaacctaggactgagacaggtt--
-----------------------------tccagctgaatgatttaaataaact------
---------gagcgtcccggcagtcaggctttgaacaagcag-agcttatcatg------
-----------------------------------tttgagccctgcagtgttggtcgtc
atgtggagatgtttcccgtgtgtaggtgtccagcaatgaccacgacttggtgagctattg
gtccaaagggacccccccaaacctgataccaggcaggcgcctgcccactcggagtgatcc
tatgaggtcgccgtgacaccttctagccaccactttaa-----------cattacatccc
tcatgacatacaacgactagggtgttcacggcagggagcagctacactttctactcgccg
cacgagtatgtacgttcgatgg--------------aatggtcggagaagatagcctacg
gcacttacatatatagggaagatgcggtgggcgggctacagatcactcggtggaaaacac
taccgcaaacatcttatgaaggaactattatacaaatatttgctgaggaggtagtggcag
tgtcgctcgagagtcagttcaagaagacagtccggagaatcgaggacgttcatttgtaac
gtcacccgggggtgtcctactgcata-------------------tgtgctatcgtggca
cccatcgacatcggactcactactaaggctgtgttc
>SEQ11
agcttcgtagccccggttcccgcag--acc-------------------caaagcacgat
atcgt-------------------------------------------------------
-----atctgatgcca-----------------------------cgaggaacgcca---
-------acgtgatccagct---ttaccactctggggttgcgataatggcgtacgcgcgg
aagtttaaggcgatatctgccccccatcgttggcatccttggagaatagtaatcacaccg
catgcactcattctctgcag----------------------------------cgttac
agagg-----------------------gtcctggcgcag--------------------
-----------------------------tttgaaaaagcgc-gactttcc---------
-----------------------------------attgagccctgcagtgttggtcgtc
atgtggagatgtttcccgtgtgtaggtgtccagcaatgaccacgacttggtgagctattg
gtccaaagggacccccccaaacctgataacaggcaggcgcctggccaatcggagtgatca
tatggggtcgccgtgacaccttctagccacaagtttaa----------------------
----------------------------cagttagggag---------------tcgccg
caccagtatgtaggttcgaagg--------------aatggtcggagaagatagcctacg
gcacttacatatatagggaagatgcggtgggcgggctacagatcactcggtggaaaacac
taccgcaaagatcttatgaagaagctattatacaaatattcgctgagaaggtagtcaggg
tggcgcccgagggtcggttctataacacagtccggagaatcg------------------
--cccccgggggtgtcctac----------------------aagagtgctaccgtggca
cccatcgacataagactcagtactaacgctgtgttc
>SEQ12
cgcctcgtatccccgctttttgcag--acgtcccgcacaccgatagaagctaaccatga-
-----tctagcaataaca----------------------------------------gg
gtctaaactgctgccg-----------------------------gctaagtgaccccac
aatcagtataaagcctagga---ggccggcgatacggttgccataatggcgtacgcgcgg
aagtttaaggcgatatctgccccccatcgttggcatccttggagaatagtaatcacaccg
catgcactcattctctgcag----------------------------------------
----------------------------gtcctgccgcag--------------------
-----------------------------cttgaaaaagcgc-gactttcc---------
-----------------------------------attgagccctgcagtgttggacgtc
atgtggagatatttcccgtgtgtatgtgtccagcaatgaccacgacttggtgagctattg
gtccaaagggacccccc-------------aggcaggcgcctgcccactcgga-------
----------ccgtgacaccttctagccaccactttaa-----------cattacatccc
tcatgacatacaacgactagg------------------------actttcttctcgccg
cacgagtatgtacgttcgatgg--------------aatggtcggagaagatagcctacg
gcacttacatatatagggaagatgcggtgggcgggctacagatcactcggtggaaaacac
taccgcaaagatcttatgaa----------------------------aagtatacaagc
aggcacccca-----------------------ggagaatagtataagttcatttgtacc
gtcccatgggggtgccctactgaacaacatagccctaatgacaagtgtgatatcatagca
---------------------agtgagcctgtttgc
>SEQ13
cgcctcgtatccccgctttttgcagcagcttctagcgt----------------------
----------------------------------------------------------aa
atgtaaactgctgccg-----------------------------gctaaggtac-----
-----------------------cccacactatacggttgcgataatggcgtacgcgcgg
aagtttaaggcgatatctgccccccatcgttggcatccttggagaatagtaatcacaccg
catgcactcattctctgcagttcaatgcttggttggtaacctaggcctgagagaggtt--
------------------------------------------------------------
----------tgcagctgatcagtcagggccggaacaagcag------------------
------------------------------------ttgagccctgcagtgttggtcgtc
atgaggagatgtttcccgtgtgtaggtgtccagcaatgaccacgacttggtgagctattg
gtccaaagggaccccct----------------cgggggcctgcacaatggga-------
---------gccgtgacactttctaacccccactttaaccccccgcgcccaattcatccg
tgatcacggcagggaggtgaac--------------------------------------
------------------------------------aatggtcggagaagatagcctacg
gcacttacatatatagggaagatgcggtgggcgggctacagatcactcggtggaaaacac
taccgcaaacatcttatgaagaagctattatataactatt--------------------
--gcgccccagggtcggttctataacacagtccggagaatcg------------------
--cccccgggggtgtcctac----------------------aagagcagtactaaagc-
-----------------------------tgtgttc
>SEQ14
agcttcgtagccccggttcccgcag-----------------------------------
------------------------------------------------------------
-acctatcaaattcca-----------------------------cgaggaacgcca---
-------acgtgatccagct---ttacaactatggggttgcgataatggcgtacgcgcgg
aagttcaaggcgatatctgccccccatcgttggcatccttggagaatattaatcacaccg
catgcactcattctctgcagtttaattctgggtaggtatcctaggcctgagagaggtt--
------------------------------------------------------------
----------tgcacctgatcagtcagggccggaacaagc--------------------
-----------------------------------attgagccctgcagtgtaggacgtc
atgtggagatgtttcccgtgtgtatctgtccagcaatgaccacgacttggtgagctattg
gtccaaagggaccccctagaacgtaatcccaggtaggggccagcacacttgga-------
---------gccatgccactttttaccc-------------ccggcgccgatataagccc
tcattaaaataaacgactagagtgc-----------------------------------
------------------------------------aatggtcggagaagatagcctacg
gcacttacatatatagggaagatgcggtgggcgggctacagatcactcggtggaaaacac
taccgcaaacatcttatgacgcaccc----------------------------------
-------------------------------caggagaatagtataagttcatttgtacc
gtcccatggggct-----------------------------------aacaacatagaa
gtg---------------------------------
>SEQ15
cgcctcgtatccccgctctatgcag-----------------------------------
------------------------------------------------------------
-------cagcttcta-----------------------------gcgtaaatggaa---
-------actgcttccggctaaggtaccccactacggttgcgataatggcgtacgcgcgg
aagtttaaggcgatatctgccccccatcgttggcaaccttggagacgagtaatcacaccg
gatgcactcattctctgcag----------------------------------tgttac
atagg-----------------------gtcctggcgcag--------------------
-----------------------------tataaaaaagggg-gactgtcc---------
-----------------------------------attgagccctgcagtgttggacgtc
atgtggagatatttcccgtgtgtatgtgtccagcaatgaccacgacttggtgagctattg
gtccaaagggaccccccca---------------aggcgcatggccaatcggagtgatca
tatggggtctccgtgacaccttctagccacaagtttac----------------------
----------------------------cagtaagggag---------------tcaccg
caccagtacgtaggttcgaagg--------------aatggtcggagaagatagcctacg
gtacttacatatatagggaagatgcggtgggcgggctacagatcactcggtggaaaacac
tacctcaaacatcttacgaagaagctattatacaattattcgctgtgaaggtagtcaggg
tggcgcctgagtgtcggttctataac----------------------------------
---------------cctac----------------------aagagtgctaccgtggca
cccatcgacataagactca-----------------
>SEQ16
atctacgtagccccgcttagcgcag--accaccagcatacttagtgtagcaattcatgac
atcgt--tagcaatacca------------------------------------------
-tccaatctgctgcca-----------------------------cgaggaaggccc---
-------acgtgctacagtt---ttacctctctggggttgcgataatggcgtacgcgcgg
aagtttaaggcgatatctgccgcccatcgttggcatccttggagaatagtaatcacaccg
catgcactcattcgctgccgcccg------------------------gaaccagagtac
ataggaccaaggagaacgtctacgaagtgtcctgcagaatgatttaaatagtcttcgcaa
ccatatatagaacgtcccgctaggcaggctttgaaaacacag-aacttatcggaaaccc-
-----------------------------------cttgagccctgcagtgttggtcgtc
atgtggagatgtttcccgtgtgtaggtgtccagcaatgaccacgacttggtgagctattg
gtccaaggggacccccccaaccctgaaaccaggcaggcgcccacccactcggagtgatcc
tatgagctcgcggtgacagcttctagccaccactttaa-----------cattgcgtccc
tcatgaggca--------------------------------------------------
---------gggagctcgatgg--------------aatggtcggagaagatagcctacg
gcacttacatatatagggaagctgcggtgggcgggctacagatcactcggtggaaaacac
taccgcaaacatcttatgaaggagctattatacaattattcgctgagtaagtagtcaagg
taacgttcca------------cagcacagt----------------gttcatttgtacc
gtcccctggcggtgtcctactgaacaacttagacctaatgtaaagtgggctatcatagca
cccatcgacatcggtc--------------------
>SEQ17
agcttcgtaaccgcgcttcgcgcaa--acgtccagtttactgtttgaaggcaatcactaa
atcgttctagcaacccca----------------------------------------gg
ttccgaattcctgcca-----------------------------gta------------
-------------cccaggt---cgtccaccctagagttgcgataatggcgtacgcgcgg
aagtttaaggcgatatctgccccccatcgttggcatccttggagaatagtaatcacaccg
catgcactcattctctgccgttcaatgtatggttcgtgacctaggaatgagacaggctac
a-----------------------ccctatcctagagaatgaattaaataaact------
---------cagcgtcccggcagtcagtctttgatcaatcag-agcttatcatgt-----
-------------------------ggcctgccaaattgagccctgcagtgttggacgtc
atgtggagatgtttcccgcgtgtatgtgtccagcaatgaccacgacttggtgagctattg
gtccaaagggaccctcccaaa--------------------tggccaatcggagtgatca
tacgcggtcgccgtgacaccttctaaccacaagtttat----------------------
----------------------------cagtgag-------------------tcgccg
caccagtatgtaggttcgcaga--------------aatggtcggagaagatagcctacg
gcacttacatatatagggaagatgcggtgggcgggctacagatcactcggtggaaaacac
taccgcaaacatcttatgaagaagctattatacaaatattcgctgagaaggttgtcaggt
tgtcgcccgagggtcggttgtgtaacaaagtccggagaatca------------------
--cccccgggggtgtccta-----------------------aagagtgctaccgtggca
cccatcgacataagactcagtagtaacgctgtctcc
>SEQ18
cgtttcgtagccccgcttcgggcag--accaccggcatagt-------------------
-------taacatgccca----------------------------------------gc
ttccaatctgccgcca-----------------------------acaggaaggccc---
------------------ct---tttccactctggggttgcgataatggcgtacgcgcgg
aagtctaaggcgatatctgccgcccatcgttggcatccttggagaatagtaatcacaccg
catgcactcattcgctgcagttcaatgttttgtgctttaccgaggaccgaactagggtac
agaggaccaagaagaatgttaacgcggtgtcctggagaatgatcca--------------
-----tctcgaacgtctcgctagt-------------------aaggtatcatgactgtt
agggtatccccatgatatcggtctcggcctgccaaattgagccctgcagtgtaggacgtc
atgtggagatgtttcccgtgtgtatctgtccagcaatgaccacgacttggtgagctattg
gtccaaagggacccccccaaacctgataccaggcaggcgcctgcgcagtcggagtgatcc
tatgaggtcgccgtgacaccttctagccaccactttaa-----------cattagatcgc
tcatggcatacaacgactagggttttcctaca----------------------------
------------------------------------aatggtcggagaagatagcctacg
gcacttacatatatagggaagatgcggtgggcgggctacagatcactcggtggaaaacac
taccgcaaagatcttaggcagcagctattatacaatgattggctgagtaagaagtcaagc
tggccccccaaagtcatttcgacaacacagtccggagaatcgcgtaagttcctttgtacc
gtcccctgggcgtgcgttactggacaacttaggcctaatgccaagtgtaatctcgtagca
---------------------acagagcctgtgtgc
>SEQ19
agcttcgtagcgccgcttcgtgcat--ccctgctgcgtactggttgaagcaaatcatgac
acctttctagctatcccg----------------------------------------gc
ttcc-----------------------------------------ctagaaaggcac---
-------acgcgatccagct---ttaccaccctgtggttgcgataatggcgaacgcgcgg
aagttcaaggcgatatctgccccccatcgttggcatccttggagaatattaatcacaccg
catgcactcattctctgcagtttaagtctgggtaggtatcctagtcctgagaaaggtt--
------------------------------------------------------------
-------------------------------------------ggcacctg---------
-----------------------------------attgagccctgcagtgttggtcgtc
atgtggagatgtttcccgtgtgtatgtgtccagcaatgaccacgacttggtgagctattg
gtccaaagggacccccttcac---------------------------------------
----------------cacctgttacttcctgtttctact--------------------
------------------------------------------------------------
------------------------------------aatggtcggagaagatagcctacg
gcacttacatatatagggaagatccggtgggcgggctacagatcactcggtggaaaacac
taccgcaaacatcttatgaagaagctattatacaaatattcgctgagaaggtagtcaggg
tggcgcccgagggtcgggtctataacacagtccggagaatcg------------------
--cccccggcgttgtactac----------------------aagagtgcttccgtggca
cccatcgacatgagactcagtact------------
