>SEQ0
ccctgttggctccgagaacttttaaggtctgatcacccttggccacccggatcgaggaga
tgttgacaccgaaaggcgtggatggcagcagcatctgttgcgtcatgaattttatgaggc
ccgcggagattacaagaagtcatgcctatgggatgccacaccccgacggcgcagtatctc
cgagccttttataatccctattacaggtgtatacatcaccctcgatatttatcggcgcat
acgagctcgtaccgacccggaggtcttgtccccgtaaaatgtaaatggtggtgttttcaa
ccctaggctcagacgatggctagtggtaactagggaggcccacatgaacactatgggact
ttatcgctagtatgccctttacttctgctagcccgttgtcatacccgatgactgccctga
ataaaatggggttctatggacgatctgagcagat--ctcagttagaagtgtatacgtact
gccccattaacagcaatcggctctagcacagtgagagaaatcccatctatccctaggcgt
agagggagtgggatctttttggcctctgcactggaattgagtcctccttcacaggcaata
agggactgaagtactaccagtcatgaaatcaagttcgtcgtcctcatccaaagtcggatg
gacaacaggggtggccacgtccatggcgtgtgcccttgaagagcccgcaaccaatccttg
cctctttgtggctgtaaggcatcgcacgcttgcgcagacctaattggctctaacgaccta
aacattgagcaatatcaggtcccaccttgcagcacatcgtcttgacggcatgcgtctact
cgagttcagtacgtccatcaggcactcgtatacactgtaatcttcagcccgaacatgtca
gaggagagttacctgtcaatgggcggtgattccacgcggatgagaactagcagaccgtct
aatggcgcgtgtttagaaggcaatgatgtagcgttggtcaggtacctattgagcgacgta
tcccctaggcgccgctcggcacactcatcctaatgggcgcaatggaacgctatcccggtt
gtggtcgtaaccacacgcgcca
>SEQ1
ccctgttggctccgagaacttttaagatctgagcacccatggccaccaggatcgaggaga
tgttgtaaccgaaagccatggatgacagcagcaactgttgcctcattaattttatgaggc
ccgcggagattacatgaagacatgcgtatgggatgccacagcccgactgcgcagtatcta
cgagcct-------------ttacaggtgtatacatcaccctcgatatttatcggcgcat
acgagctcgtaccgacccggaggtcttgtccccgtaaaatgtaaatggtggtgttttcaa
ccctaagctcagacgatggcaagtgctaactagggaggccttcaagaacaataggggact
ttattactt--------------------------------------ctgactgccctga
ataaaatagggttctatagccgatctgagcagat--ctcagttagaaatgtatacgtact
gccccattaacagtaatcggctctagcacagtgagagaaatcccatctatccctaggcgt
agagggagtgggatctttttggcctctgcactggaattgagtcctccttcacaggcaata
agggactgaagtactaccagtcatgaaatcaaattcgtcgtcctcatccaaagtaagatg
gacaacagggctggccacgtccgtggcgtgtgcccttctcgagcccgcaaccaatccttg
cctctttgtggctgtaaggcatcgcacgcgtgc----------------ctaacgaccta
aacactgagcaaaatcaggtcccaccttgcagcacatcgtcttgacggcatgcgtctact
cgagttcagtacgtccatcaggcactcgtatacactgtaatcttcagcccgaacatgtca
gaggcgagttacctgtcaatgggcgttgcttccacgcggatgagcaat------------
---------cgtttagaaggtaatgaagtagcgttggttaggtacccattgagcgacgta
tcccctaagccccgctcggcacactcatcctaatggaggcaatggaactctatcccggtc
ggggt-----------------
>SEQ2
ccctgttggctccgagaatttgtaagatctgagcacccatggc-----------------
tgttgtaactcaaacccgtgcatgacagtagcaactgatgcc------------------
----------------------------tgagtagccacagcccgactgcgcaatatcta
agagccc-------------ttacaggtgtatacatcaccctcgatatttatcggcgcat
acgagctagtaccgacccggaggtcttgtccccgtaaaatgtaaatggtggtgttttcaa
ccctaggctcagacgatggctagtgttaattagggaggcccacatgaacacgataggact
ttatcgctagtatgccc-----------------------------------------ac
ctgttatcataccctatggacgatctgagcaggt--ttcagttagaagtgtataggtact
ggcccaataacagcaatcggctctagcaaagtgagagaaatcccatctatccctaggcgt
agagggagtgggatctttttggcctctgcactggaattgagtcctccttcacaggcaata
agggactgaagtacgaccagtcatgacatcaagttcgtcgtcctcgtccaaagtcggatg
gacaacaggggtggcgacgtccatggcgtgcgcccttgaagagcccgcaaccaatccttg
cctctttgtggctgtaag------------------gaactaaattgctctaacgacgta
aacattg--------------ccaccttgcagcacatcgtcttgacggcatgcgtctact
cgagttcagtacgtccatcaggcactcgtatacactgtaatcttcagcccgaacatgtca
gaggcgagttatctgtcaatcggcgttgcttccgcgaggatgagcaat------------
---------cgtttagatggaaatgaagtagcgttggttaggtaccccttcagcgacgta
tcccctaagccccgctcggcacactcatcctaacggaggcattgaaactctatcccggtc
gg--------------------
>SEQ3
ccctgatggctgcgtgaacttttaagatctgagcacccatggctagcaggatcgaggaga
tgttgtaaccgaaagccatggatgtcagcagcgactgttgcctcattaattttatgaggc
ccccggagattacatgaagacatgcgtatgggatgccacagcccgactgcggagtctcta
cgagcca-------------ttacaggtgtatacatcaccctcgatatttatcggcgcat
acgagctagtaccgacccggaggtcttgtccccgtaaaatgtaaatggtggtgttttcaa
ccctaggctcagacgatggcaagtgttaattagggaggcccacatgaacacgataggact
ttagcgcta---------------------------------------------------
----tatcataccctatgcacgatctgagcaggt--tacagttagaagtgtatagccact
gtcccaataacagcaatcggctctagcacagtgagagaaatcccatctatccctaggcgt
agagggagtgggatcttttcggcctctgcactggaattgagtcgtccttcacaggcaata
agtgactgaagtactaccagtcatgaaatccagttcgtcgtcctcatccaaactgagatg
gacaacaggggtggccacctactgtgcgtctgcccttgaagagcccgcaaccaatccttg
cctctttgtggctgtaagacattgcacgcttgcgcagacctaattgtctctaacgacctc
aacattgagcaatatgaggtcccaccttgcagcacatcgtcttgacggcatgcgtctact
cgagttcagtacgtccatcaggcactcgtttacactgtaatcttcagcccgaacatgtca
gaggcgagttacctgttattgggcgttgcttccacgcgtatgggaaat------------
---------cgtttagaagttaatgaagtagcttgggttaggtactctttgagcgaggta
tccccttagctcctcccg---------------------------------------ttc
ggggt-----------------
>SEQ4
ccctgtcg---------------------------------gctaccaggatcgaggaga
tgttga-----------------gacaggcgcaactgtttcctcattaattttatgaggc
gcgcggagattgcattaagacatacgtatgggatgcaacagcccgacggcgcagtatcta
cgag----------------ttacaggtgtatacatcaccctcgatatttatcggcgcat
acgagctagtaccgacccggaggacttgtccccgtaaaatgtaaattgtggtgttttcaa
ccctaggctcagacgatggctagtggtaactagggaggccctcatgaacactatgggact
ttaccgctagtgtgccc-------------------------------------------
--gttgtggggttctatggacgatctgagcagat--ctcagttagaagtgt---------
---------ccatcaatcggccctagcaaagtgagagaaatcccatctatccctaggcgt
agagggagtgggatctttttggcctctgcactggaattgagtccgccttcacaggcaata
agggactgaagtgcta--------------------gtcgtcctcatccaaagtaagatg
gagaagagggctggccacgtccgtggagcgtgcccttctggagtccgcaaccaatccgtg
cctctttgtggctgtaag------------------------------------------
-------agctaaatcaggttccaccttgcagcacatcgtcttgacggcatgcgtctact
cgagttcagtacgtccatcaggcactcgtatacactgtaatcttcagcccgaacatgtca
gaggcgagttatctgtcaaacggcgtggt-------------------------------
---------------aatgtagacgaagtagcgttggttaggtacccctgccgtgacgta
tccccttagccccgctcggcacactcatcctaacggaggcaatgaaactctatcccggtc
gc--------------------
>SEQ5
ccctgttgtttccgagtacttttaaggtctgatcaccctcggccactcggatcgaggaga
tgttgacaccgaaaggcggcgatggcagcagcatccgttgc-------------------
-----------gcaagaaatcatgcctataggatgccacatgcccacggcgcagtctctc
cgatccttttataatccctattacaggtgtacacatcaccctccatatttatcggcgcat
acgagctcgtaccgacccggaggtcttgtccccgtaaaatgtaaatggtggtgttttcaa
cccgaggctcagacgatggctagtggtaactagggaggccttcatgaacgatatgggact
taaccgctagtgtgccc-------------------------------------------
--gttttggggtttaatggacgatctgagcagat--ctcggttagaagtgt---------
---------ccctcaatcggccctagcacagtgagagaaatcccatctatccctaggcgt
agagggagtgggatcttttcggcctctgcactggaattgagtcgtccttcacaggcaata
agtcagtcaactactaccagtcatgaaatccagtttatcgtcctcatccaaactgagatg
gacaacgggggtggcctcctactgtgcgtctgcccttgaagaggccaccaccaatccttg
cctctttttggctgtaagacattgcacgcttgcgcagacctaatggtctctaacgacctc
aacattgaacaatatgcggtcccaccttgcagcacatcgtcttgacggcatgcgtctact
cgagttcactacgtccatcaggcactcgtatacactgtattcttcagcccgaacatgtca
gaggcgagttctctttcaaacggcatggt-------------------------------
---------------aatgtagacgaattagcgttggctaggtacccctgccgtgtcgta
tcccgttatccccgctcggcacactcatcgtaacggaggcaatgaaactctatcccggt-
----------------------
>SEQ6
-----------------------------------------ccctttaggctcgatgaga
tgttga-----------------ggcaggcgcaactgtttcctcattaattgtatgaggc
gcgcggagattgcattcagacattcgtatgggacgcaacagcccga--------------
--------------------ttacaggtgtatacatcaccctcgatatttatcggcgcat
gcgagctagtaccgacccggaggtcttgtccccgtaaaatgtaaatggtggtgttttcaa
ccctaggcacagaggatggctattgttacttagggaggcccacctgtaaaagatacggct
ttatcgctagtatgccc-----------------------------------------ac
ctggtatcatacccaatggccgatctgagcaggt--ttcagttagaagtgtataggtact
ggtccaataacagcaatcggctctagcaaagtgagagaaatcccatctatccctaggcgt
agagggagtgggatctttttggcctctgcactggaattgagtcctccttcacaggcaata
agggactgaagtactaccagtcatgaaatcaagttcgtcgtcctcttccaaagtcggatg
gtcaacaggggagaccacgtccatggcgagtgcccttgaag-------------------
-------------gtaaggcatcgcacacttgcgcagacctaattcgctctaacgaacta
aacattgagcaatatcaggtctcaccttgcagcacatcgtcttgacggcatgcgtctact
cgagttcagtacgtccatcaggcactcgtatacactgtaatcttcagcccgaacatgtca
gaggagagttatctgtccatgatcggtgattccacgctgatg------------------
-----------------------agaactagca-------gacagtctaatggtagcgta
--------------gtcggcacactcatcctaatgcgcgcaatggaaggctcgcgcca--
----------------------
>SEQ7
-----------------------------------------ccctttaggctcgatgaga
tgttga-----------------ggcaggcgcgaatgtttccagatgaattgtctgaggc
attcgtaga---------------------------------------------------
--------------------ttacaggtgtatacatcaccctcgatatttatcggcgcat
acgagctcgtaccgacccggaggtcttgtccccgtaaaatgtaaatggtggtgttttcaa
ccctagggtcagacgatggctagtcttaactaggaaggcccacaagaacactatagggct
ttgccgattgtatgccctttacttgttctggcccgttgtcatacccgttgactgccctga
ataaaatggggttctatggacgatctgagcagat--atcagttagaagtgtatacgtcct
gccccattaacag---------ctagcacagtgagagaaatcccatctatccctaggcgt
agagggagtgggatctttttggcctctgcactggaattgagtcctccttcacaggcaata
agggactgaagtactaccagtcatgaaatcgagttcgtcgtcctcctccaaagtcggg--
------------------------------------------------------------
---------------accacgtggagcacttgcgcagacctaattcgctctaacgaacta
aacattgagaaata------tccaccttgcagcacatcgtcttgacggcatgcgtctact
cgagttcagtacgtccatcaggcactcgtatacactgtaatcttcagcccgaacatgtca
gaggagtgttatctgtccatgatcggtgcttcgacgctgaag------------------
-----------------------cgatctagca-------gacagtctaatggtagcgta
--------------gtcggcacactcatcctaatgcgcgcaaagcacggctcgc------
----------------------
>SEQ8
ccctgttggctccaagaacttttgagatctgtg--------gccaccaggatcgaggaga
tgttgtaaccga-----------------------tcttggctcattaattttctgaggc
ccgcggaaattgaatgaagacaggcgtatgggatcccacaccccgactacgcagtattta
cgagcct-------------ttacaggtgtatacatcaccctcgatatttatcggcgcat
acgagctagtaccgacccggcggtcttgtccccgtaaaatgtaaatggtggtgttttcaa
gcctaggctcagacgatgggtagtgttaattaggggggcccacatgaacacgctaggact
ttatcgctaggacgccc-------------------------------------------
--------------gatccacgatctgagcaggt--ttcagttagaagtgtttaggtact
ggcccactgatagcaatcggcgctagcacagtgagagaaatcccatctatccctaggcgt
agagggagtgggatctttttggcctctgcactggaattgagtcctccttcacaggcaata
aggg---------------ctcatgaaatcaaattcattgtcctcatccaaagtaagatg
gacaacggggctggtcacgtcagttgcgtgtgcccttctcgagcccgcaaccaatccttg
cctctttgtggcagtaagacct--------------------------------------
------------------atcccaccttgcagcacatcgtcttgacggcatgcgtctact
cgagttcagtacgtccatcaggcactcgtttacactgtaatcttcagcccgaacatgtca
aaggatagttccacgcggatgggatctagcagactgtctaatggcgcg------------
---------tgtctagaaggcaaagatgtagcgttggtcaggtgtctattaagcgacgta
ttccctaggcgccgctcggcacactcatcctaatgggcgcaatggaacgctatccagctt
gtggtagcaacaaca-------
>SEQ9
ccctatcg---------------------------------gctaccaggatcgaggaga
tgttga-----------------gacaggtgcaactgtttcctcattcattttatgaggc
gcgtggagatcgcattaagacatacgtatgggatgcaacagcccgacggcgcagtatcta
ggac----------------ttacaggtgtatacatcaccctcgatatttatcggcgcat
acgagctcgtaccgacccggaggtcttgtccccgtaaaatgtaaatggtggtgttttcaa
gcctagtctcagacgatgggtagtgttaattaggggggtccacatgaacacgctaagact
ttatcgctaggacgccc-------------------------------------------
--------------gatacacgatctgagcacga--ttca--------------------
-------------caatcggcgctagcaaagtgagagaaatcccatctatccctaggcga
agagggagtgggatctttttggcctctgcactggaattgagtcctccctcacaggcaata
agggtctgaagtactaccagtcatgaaatcaaattggtcgtccacatccaaagtaa----
----------------ccgtccgtggcgtgtgcccgtctcgagcccgcaaccaatccttg
caac--------------------------------------------------------
--gggtgcataccgagctaaaccaccttgcagcacatcgtcttgacggcatgcgtctact
cgagttcagtacgtccatcaggcactcgtatacactgtaatcttcagcccgaacatgtca
gaggtgagttatctgtcaatcggcgttgcttacgcgatgatgagcaat------------
-------------------------------------cgaggcaccccttgagcgacgta
tcccctaagccccgctcggaaaactcttcctaacggaggcattgaaactcttatccggtt
gg--------------------
>SEQ10
-----------------------------------------ccctttaggct--------
ttttga-----------------ggcaggcgcaactgtttcctcaagaattgtatgaggc
gcgcggagattgcattaagacattcgtatgggacgcaacagccc----------------
--------------------ttacaggtgtatacatcaccctcgatatttatcggcgcat
acgagctagttccgacccggaggtcttgtccccgtaaaatgtaaatggtggtgttttcaa
ccctaggctcagacgatgtctagtggtaactagggaggc-------------atggggct
ttatcgctagtatgacctatacttatgtta----------------------------gc
ctgttgtcatacccgatgacggccctgaataagatgctcagttagcagtgtataagtact
gccccattaacagcaattggctctagcacagtgagagaaatcccatctatccctaggcgt
agagggagtgggatctttttggcctctgcactggaattgagtcctccttcacaggcaata
agggaatgaagtactaccagccatgaagtcaagtgcgtcgtcctcatagaaagtcggatg
cacaacaggggtggccacgtccatggcgt-------------------aaccaatcatag
cctctttaaagctgtaaggcatcccatgcttgcgcggacctaattggatctaacgaccta
aacatcga--------------caccttgcagcacatcgtcttgacggcatgcgtctact
cgagttcagtacgtccatcaggcactcgtatacactgtaatcttcagcccgaacatgtca
gatgagtgttttctttccatgatcggtgcttagatgcggacg------------------
-----------------------tgacctagca-------gacagtcttatgctagcgta
--------------gtaggcacacacatcctaatgcgcgcaaagcatggcacac------
----------------------
>SEQ11
-----------------------------------------cactttaggctccaggaga
tgtgga-----------------ggcaggcgcaacagtttcctcattaat----------
--------attgcattcagacatacgtatgggacgcaacatcccga--------------
--------------------ttacaggtgtatacatcaccctcgatatttatcggcgcat
gcgagctagtaccgacccggaggtcttgtccccgtaaaatgtaaatggtggtgttttcaa
ccctaggctcagacgatggctagtggtaactagggaggcccaaatgcagactatgggact
tt-ctgctaccatgact------------------------------------gccccga
acaaaatggggttctatggacgatctgaacatat--ctcagttagaagtgtatacatact
ggctcataaacagcaatcggctctagcacagtgagagaaatcccaactatccctaggcgt
agagggagtgggatctttttggcctctgcactggaattgagtcctccttcacaggcaata
agtcagtcaaatactaccagtcatgaaatccagtttatcgtcctcatcgaaactgagatg
gacaacggggttgccctcctactgtgcgtctgcccttgaagaggacaccaccagtccttg
catctttttggctgtaagacattgcacgcttgcgcagacttaatggtctctagcgacctc
gacattgaacaatatgcggtcccaccttgcagcacatcgtcttgacggcatgcgtctact
cgagttcagtacgtccatcaggcactcgtatacactgtaatcttcagcccgaacatgtca
gaggcgagttctctttcaaacggcatggt-------------------------------
---------------aatgtagacgaactagggtcgtctaggtacccctgccgtgtccta
tccc--------------gttcactcatcgtaacggaggcaaagaaactctatcccggt-
----------------------
>SEQ12
ctctgttgtttccgagtacatttaaggtctgatcaccctcggccactcgtagcgagggac
-----------------------gatagcagcatccgttgc-------------------
-----------gcaagaaatcatgcctataggatgccacatgcccacggcgcagtctctc
cgatccctttacaatccctattacagttgtatacatcaccctcgatatttatcggcgcat
acgtgctcgtaccgacccggaggtcttgtccccgtaaaatgtaaatggtggtgttttcaa
ccctaagctcgaacgatggcaagtgctaacta----------------------------
-----------------------------------------ttacttctgactgccctga
ataaaattgggatctataggcgatctgagcagat--ctcagttcgaaatg----------
----gcttaacagtaatcggtactagcacattgagagaaatcccatctatccctaggcgt
agagggagtgggatctttttggcctctgctctggaattgagtcctctttcacaggcaata
aggaactgaagtacgaccagtcatgacatcacgttcgtcgtcctcgtccaaagtc-----
-------------------tccatgacgtgcgcccttgaagagcccgcctcgactccttg
cctcttattggctgtaagga----------------------------------------
----------actaaattgctccaccttgcagcacatcgtcttgacggcatgcgtctact
cgagttcagtacgtccatcaggcactcgtatacactgtaatcttcagcccgaacatgtca
gaggtgagttttctctcaaacggcatggt-------------------------------
----------------agttagacgaactagggtcgtctaggtacccgt-----------
---------------------------------tggaggcaaagaaactttatcacggt-
----------------------
>SEQ13
-----------------------------------------cccttgaggcttgatgaga
tgttca-----------------ggcaggcgcgaatgtttccagctgaattgtctgaggc
attcataga---------------------------------------------------
--------------------ttacaggtgtatacatcaccctcgatatttatcggcgcat
acgagctagtaccgacccggaggtcttgtccccgtaaaatgtaaatggtggtgttttcaa
ccctaagctcagaagatggcaaagaagaacagggga------------------------
------------------------------------------ctttactgactgccctga
ataaaatcggattctatagccgatctgagcagat--ctca--------------------
---ccattaaaagcaatcggctctagcaaagtgagagaaatcccatctatccctaggcgt
agagggagtgggatctttttggcctctgcactggaattgagtcctccttcacaggcaata
aggaactgatgtacgaccactcatgacatcacgttcgacgtcctgttcgaaatcc-----
-------------------tccttgacgtgcgcccttgacgagtccgcctcgactccttg
ccccttattggccgtaagg-----------------------------------------
----------actaaattgctccaccttgcagcacatcgtcttgacggcatgcgtctact
cgagttcagtacgtccatcaggcactcgtttacactgtaatcttcagcccgaacatgtca
gaggcgagttgtctgtcagtcggcctttctcccgcggggatgagctat------------
-----------cgtagatggaaatgaagtagcgatggttaggtaccccttcagcgacgta
tcccctatgtcccgcacggcacactcatcctaacggaggcgttcacactctctcccggtc
gg--------------------
>SEQ14
-----------------------------------------cactttaggct-------a
tgttga----------------------------------------------ggtgaggc
gcgcggagattgcattcagacgttcgtatggaacgccacaacccga--------------
--------------------tgtcaggtgtacacatcaccctctatatttatcggcgcat
acgtgctcgtaccgacccggaggtcttgtccccgtataatgtaaatggtggtgttttcaa
ccctaagcactaacgagcgcaagtgctaacta----------------------------
------------------------------------------------tgactgccctga
ataaacttgggatctataagcgatctgagcagat--ctcaattcgaaatg----------
----gtgtaacggtaaccggtactagcaaagtgagagaagtcccatctatccctaggcgt
agagggagtgggatctttttggcctctgcactggaattgagtcctccttcgcaggcaata
aggaactgatggtcgagcactcatgccatcacattcgaagtcctgtactaaatcc-----
-------------------tccttgaagtgcgccgtagacgagtccgcctcgactccttg
ccccttagtagctgtaagg-----------------------------------------
----------actatattgctccaccttgcagcacatcgtcttgacggcatgcgtctact
cgagttcagtacgtccatcaggcactcgtatacactgtaatcttcagcccgaacatgtca
gaggcgagttaactgtcaatgggcggtgctt-----------------------------
-----------------------------------------------tttagaaggcgta
tcccctaagccccgctcggcacactcatcctaatggaggcaatggaactctatcccggtc
gggtt-----------------
>SEQ15
-----------------------------------------cactttaggctccagggat
tgtgga----------------------------cagtttcctcattaat----------
---------ttgtattcagacatacggatgggacgaaacatcccga--------------
--------------------ttacaggtgtatacatcaccctcgatatttatcggcgcat
acgagctcgtaccgacccggaggtcttgtccccgtaaaatgtaaatggtggtgttttcaa
ccctaggatcagacgatggctagtgttaattaggtagatccccattaacacaataggact
ttatccctagtatgccc-----------------------------------------ac
cttttctcataccctatggacgatctgagcagct-----------------------acc
ggcccaataacagcaatcggctctagcacagtgagagaaatcccatctatccctaggcgt
agagggagtgggatctttttggcctctgcactggaattgagtcctccttcacaggcaata
aggg---------------ctcatgaaatcagatccaatgtcctcatccaaagtcagatg
gacaacgggactggtcctgtcagttgcgtgtgcccttctccagcccgcaaccaatccttg
cgtctttgtggcagt---------------------------------------------
-------------------ctacaccttgcagcacatcgtcttgacggcatgcgtctact
cgagttcagtacgtccatcaggcactcgtatacactgtaatcttcagcccgaacatgtca
gaggcgagttggatgagctatggta-----------------------------------
---------------gacggaaatgaagtagcgatggtacggtaccccttcagagacgta
tcccctatgtcccacgcggcacactcatcctaacggaggcgttcacactctctcccgatc
gg--------------------
>SEQ16
-----------------------------------------cactttaggat--------
-----------------------ggcaggtgcaggcgtttcctcattaat----------
--------attgcattcagacatacgtatgggacgcgacatcccga--------------
--------------------ttacaggtgtatacatcaccctcgatatttatcggcgcat
acgagctcgtaccgacccggaggtattgtccccgtaaaatgtaaatggtggtgttttcaa
ccctaagctcagacgaaggcaagtgcaaactagggaggccttcaggtactttaggggact
ttattactt--------------------------------------ctgactgccctga
ataaaagagggttctatagcagatctgggcagat--ctcagttagaaatg----------
gcccgattaacagtaatcggctctagcaaagggagagaagtcccatctatccctaggcgt
agagggagtgggatctttttggcctctgcactggaattgagtcctccttcgcaggccata
agggacttaagtactaccagtcatgaaatcgagttcgtcgtcctcctacaaagtccgg--
------------------------------------------------------------
---------------accacgtggagcacttgcgcaga----------------------
-------------aaaaacatccaccttgcagcacatcgtcttgacggcatgcgtctact
cgagttcagtacgtccatcaggcactcgtatacactgtaatcttcagcccgaacatgtca
gaggagtgttatatgtccatgatcggtgattccacactgatg------------------
-----------------------agaactagca---------------aacagtagcgta
--------------gccggcacactcctcctaatgcgcgcaatggaaggcccgcgcca--
----------------------
>SEQ17
tcctgttggctccgagaatt--------------------------------------gc
tgttgtaactccatcccgtgcatgacagtagcaccagatgccttagta------------
----------------------------------gccaaagcgcgactgcagaatattta
agagccc-------------ttacaggtgtacacatcaccctacatatttatcggcgcat
acgagctcgtaccgacccggaggtcttgtccccgtaaaatgtaaatggtggtgttttcaa
ccctaggctcagacgatggcaagtgttaattcggaaagcccacgggaacacgattagact
ttagcgcta---------------------------------------------------
----tatcataccctatgcgcggtctgcgcaggt--ttcagttagacgtgtatagccact
gtcccaataacagcaatcggctctagcaaagtgagagaaatcccatctatccctaggcgt
agagggagtgggatctttttggcctctgcactggaattgagtcctccttcacaggcaaaa
aggg---------------ctcatgaaatcagatccaatgtccttatccaaagtcagatg
gacaacgggactggtcgtgtcagttggctgtgccc-------------------tccatg
cgactttgtggcagt---------------------------------------------
----------------------caccttgcagcacatcgtcttgacggcatgcgtctact
cgagttcagtacgtccatcaggcactcgtatacactgtaatcttcagcccgaacatgtca
gaggcgagttggat----------------------------------------------
----------------aagctatggaagtagcgatggtagagtaccccttcattgacgta
tcccctatgtcacacgcggcgcactcatcctaacggaggcgttcacagtctctcccgatc
gg--------------------
>SEQ18
-----------------------------------------ccctttaggacga------
-----------------------ggcagccgcgaatgtttccagatggttcgtaga----
------------------------------------------------------------
--------------------ttacaggtgtatacatcaccctcgatatttatcggcgcat
acgagctcgtaccgacccggaggtcttgtccccgtaaaatgtaattggtggtgttttcaa
ccctaggatcagacgatggctattgtt------------------taacacaatgggact
ttatccctaacct-----------------------------------------------
----------tttctatggacgatctgagcagct-----------------------acc
ggcccaataacagcaatcggctctagcaaagtgagagaaatcccatctatccctaggcga
agagggagtgggatctttttggcctctgcactggaattgggtcctccctcacaggcaata
agtcagtcaactactactagtcatgaaacccagttcatcgtcctcatccaaactgacagg
cacaacgggggtg--------------------ccttgaagaggccaccaccaatccttg
cctctttatggctataagacattgcacgcttgcgcagacctaatggtctctaacgacctc
agccttgaacaatattcggtactacctcgcagcacatcgtcttgacggcatgcgtctact
cgagttcagtacgtccatcaggcactcgtttacactgtaatcttcagcccgaacatgtca
gaggagtgttagctgtccatgatcggtgctttgtcgctgaag------------------
---------------------------------------------------cgaagcgta
--------------gtcggcacactcatcctaatcggcgcaaagcacggctcgc------
----------------------
>SEQ19
cgctg-----------------------------------------------cgatgaca
tgttga-----------------ggcaggcgcaactgtttcctcattaattgtatgaggc
gcgcggagattgcattcagacattcgtatgggacgccacagcccga--------------
--------------------ttacaggtgtatacatcaccctcgatagttatcggcgcat
acgagctagtaccgacccggaggtcttgtccccgtaaaatgtaaatggtggtgttttcaa
ccctaggcacagaggttggctattgttacttagggaggcctacctgtaaaagatacggct
ttatcgttagtatgccc-----------------------------------------ac
ctggtatcataccc---------tctgagcaggt--ttcagttagaaggatataggtact
ggtctaataacagcaatcggctctagcaaagtgagagaaatcccatctatccctaggcgt
agagggagtgggatctttttggcctctgcactggaattgagtcctccttcacaggcaata
agggactgaagtgcta--------------------gtcggcctcatccaaa--------
-------gggctggccacgtccgtggaccgtgcccttc----------------------
cctctttgtggctgtaag------------------------------------------
-------agctaaatcaggttccaccttgcagcacatcgtcttgacggcatgcgtctact
cgagttcagtacgtccatcaggcactcgtatacactgtaatcttcagcccgaacatgtca
gaggcgagttaccagtcaatgttta-----------------------------------
---------------gaaggtcttgaagtagcattggttcggtacccatagagcgacgta
tcccctaagccccgctcggcacactca------------------aaccctatcccggtc
agggt-----------------
