>SEQ0
gcaataacgctgtcgtgacatcaggcgccgaaccggaagcgtcgaacggtccgggtcccc
tcactgtccagaataaaatgtatcccataatccccctttcttgtgtactatgtcgcgaga
cgtcagtcgttagcgtcgctaataaacacttccaccacctgcaaggttccgtagcgtaat
tttactgcttgctccctaaaagacgctcgctacacgcctgggtgtttttagcaacacaca
gacttggctggcgttgttgatagtcgaaatgtagctgcggacaacagtttcttgcactaa
cggctaaggctgtgtttaatatgcttgacaaccattaagtgattaaattggcttttgaca
agtaagtccatataagctgctacataatgtctccgtcttgcgagcgaaggcagtctacgt
cgagaactaggcggccatacaacaataccctatcgggaagaagtaatatctcctgacatt
gagtccgagaaaaggaagggaactaagaagtgtggacgcagggaccagccctagaatacg
caacgaacaatcgactccacccaacggaaagtccctcatttgatttagtcattcgtgaag
taaaccacgtaaggaaatgcaagcgcctgttcgaaggagcgaggtgctccattaacctcg
attagtatgagctccgaagctctaccaagggcccacgacttcgcggtcttactctatacc
aaaccccgagcgtttttcgccggctcacaaagccagcacaaaggcagcatacgcattcat
cgtatcgattctcccgctcacggtgcacctactgtgtgatggcgttgcagctatggggta
gtggctcattcgagagcacctactgtgcactggctacgtagggcctatctgaagtctgct
tccttataacgctgggcggaagcaaccgagtctcggcttttttaggttcatgtgggccac
cggtgcaatagtgcatagaaccctcccgtagtgccgcgtgggattaggggtttcacatca
cattccttgggagtgcttgatactttggcttctgcgtctggtatttcgtacttatgagtc
aagcagttccaacaaataaa
>SEQ1
gcaataacgttgtcgtgacatcaggtgccgtacccgaagcgtcgaacg------------
----tgtccagaataaaatgtatcccatagtccccctgtcttgtgtactatggcgcgaga
cgtcagtcgttagcgtcgctaataaaaacttccaccccctgcaaggttacgtagcgcaat
tttattgcttgttccctaaaagacgctcgctacacgcctgggtgtttttagcaacacaca
gacttggctggcgttgttgattgtcgaaatgtagctgcggacaacagtttcttgcactaa
cggctaaggctgtgtttaatatgcttgacaacca------------------------ca
agtaagtccatctaagctgctacataatgtctccgtcttgcgagcgaaagca--------
-------------gccatacaacactaccctatcgggaagaagtaatatctcctgacatt
gagtcctagacaagttagggaacaaagaagtgtggacgcagggaccagccctagaatacg
caacgaacaatcgactccacccaacggaaagtccctcatttgatttagtcattcgtgaag
tcaaccacgcagggaaatgcaagctccaattccgaggagcgaggccctccattaacctcg
attag-------------------acaaggtcccccgacttcgcggtcttactctatacc
aaaccccgagcgtttatcgccggctcacaaagccagcccaaaggcagcagacgcattcat
cgtgacgattctgccgcccacggtgcacctactgtgtgatggcgttgcagctatggggta
gtggctcattcgagagcacctactgtgcactggctacgtagggcctatctgaagtctgct
tgcttataacgctgggcggaagcaaccgagtctcggcttctttgggttcaggtgggcccc
cggtgcaatagagcagagaaccc--------------------ttaggggtttcacttca
cagtccttgggagtgcttgatactttggcttctgcgtctggtctttcgtacttatgagtc
aagcacttaccataaataaa
>SEQ2
gcaataacgctgtccagacatcaggcggcgaacc-------------------ggtcccc
tcactgtccagaataaaatgtattccataatccgcatctcttgtgtactatgtcgcgaga
t--------------------------acttccaccacctgcaaggttccgtagattaat
tttactactagctccct-aaagacgctcgcaacacgcctgggtgtttttagcaacacaca
gacttggctggcgttgttgatagtcgaaatgtagctgcggacaacagtttcttgcactaa
cggctaaggctgtgttttgtatgcttgacaaccattaggtgattaaaatggcttttgaca
agtaagtcca-----------------------caacttgcgagcaaaggcagtctacgt
agagaactaggcgatcatac----------------------------tctcccgacttt
gagtccgagaaa--------aacaaagaagtgtggacgcagggaccagccctagaatacg
caacgaacaatcgactccacccaacggaaagtcccccatttgatttagtcattcgtgaag
taaactacgtaagtaaatgcaagcgcctgttcgaaggagcgatatgctccattaacctcg
attagtatgtgctcctaagctctacaaagggcccacgacatcgcggacctacactatacc
caacccccagcgttttacgccggctgacaaagccagcacaaaggcagcatatgcatt---
---------------gctcacggtgcacctactgtgtgatggcgttgcagctatggggta
gtggctcattcgagagcacctactgtgcactggctacctagggcctatctgaagtctgct
tccttataacactgagcggaggcaacctagtctcggcttttttaggttcatgtgggccac
ggttgcaatagtgcatagaaccctcccgtagtgccgtgtgggattaggggtttcacatca
cattccttgggagtacttgatactttggcttccgcgtctagtctttcgtacatatgagtc
aagcagttccaccaaataaa
>SEQ3
gcaagaacgctgt-----------------------------------------------
--------ccgggtaaaatgtatgccataagcccccttacttgtgtaccatgtcgcgaga
cgtcagtcgttagcgtcgctattaaacacttccaccacctgcaaggttccgtagcg----
----------gctccctaaaagacgctcgcaacacgcctgggtgtttttagcaacacaca
gacttggctggcgttgttgatagtcgaaatgtagctgcggacaacagtttcttgcactaa
cggctaaggcggtgttttgtatgcttgacaaccattaggtgattaaaatcgcttttgaca
agtaagtcga-----------------------caacttgcgatcaaaggcagtctacgt
agcaaactaggcgatcatac----------------------------tttcccgacttt
gactccgagaaa--------aacaaagaagtgtggacgcagggaccagccctagaatacg
caacgaacaatcgactccagccaacggaaagtcccccatttgatttagtcattcgtgaag
tcaaccacgcagggaaatgcacgctccaactccgaggagcgaggccctcctttaccctcg
attaa-------------------acaaggtcctccgacttcgcgttcttactctat---
----------cgtttatcgccggctcacaaaatcagcccaaaggcagcagacgcattcat
cgtgacgattctgccgcccacggtgcacctactgtgtgatggcgttgcagctatggggta
gtggctcattcgagagcacctactgtgcactggctacgtagggcctatctgaagtctgct
tgcttataacgcttggccgaagcaaccgagtctcggcgtctttgggttcaggtgagcccc
cggtgcaatagagcagagaaccc-------------------------------------
-----ttgaggtgtgctagatactttggcatctgcgtctggactttcgtacaagtgagtc
acgcacttaccataaataaa
>SEQ4
gatata-----------------------gtacccaaagcggccaaag------------
----tgtccagaagaaaatgtttcccatagtccccctgtgttgtgtactatggcgcgcga
cgtcacccgt-----------------------------tgcaaggttacgtagcgcaat
tttgttgcttgttcc-----agacgctcgcaacacgcctgggtgtttttagcaaaacaca
gacttggctggcgttgttgatagtcgaaatgtagctgcggacaacagtttcttgcactaa
cggataaggcggtgttttgtatgcttgacaaccataaggtgattaaaatcgcttttgaca
agtacgtcga-----------------------caacttgcgatcaaaggcagtctacgt
agcaaacta---------------------------------------tttccctacttt
aactccgagaaa--------aactaagaagtgtggacgcagggtccagccctagaatacg
caacgaacaatcgactccacccaacggaaagtccctcatttgatttagtcattcgtgaag
tagactacgtaagtaaatgcaagcgcctatttgaaggagcgatatgctccattaacctcg
atcagtatgtgctcctaaagtctacaaagggcccacgacatcgcggccctacgctatacc
taacccccagcgttttacgccggctgactaagccagcacaaaggcagcatattcatt---
---------------gctcccggtgcacctactgtgtgatggcgttgcagctatggggta
gtggctcattcgagagcacctactgtgcactggctacgtagggcctatctgaagtctgct
tgcttattacgcaggtcggaagcaaccgagtcc--------------------------c
cggtgcactagagcagagaaccc--------------------ttaggggtttcacttca
cagtcattgggagtgcttgatactttggcttctgcgtctggtctgtcgta----------
---cacttaccataaataaa
>SEQ5
gtaataaagct---------tcaggggccgaaccggaagcgtcgaacggtccgcgtccac
tcactgtccagaatagaatgtatgccgtaatcccccttgcttgtgtgctatgtcgcgaca
cgtcagtcgttagcgtcgctaataaacacttccaccacctgcaaggttccgtagcgtaat
tctactgcttctttcctaaaagacgctcgaaacacgcctgggtgttcttagcaacacaca
gacttggctggcgttgttgatagtcgaaatgtagctgcggacaacagtttcttgcactaa
cggctacggcggtgtttaatatgctttacgaccattaagtgattaaattggcttttgaga
agtaagtccatataagctgctacattatgtctcagtcttgcgagcgaag-----------
------ctaggcggccatacaacaataccctatcgggaagacgtaatatctcatgacatt
gagtcagacaagaggaagggaacaaagaagtgtggacgcagggaccagccctagaatacg
caacgaacaatcgactccagccaacggaaagtcgcccatttgatttagtcattcgtgaag
tcaaccacgcaggcaaatgcacgcgcccactccgaggagcgaggcccttctttaccc---
------------------------agtaggtcctccgacacta-----------------
-------aaccgtttatcgccggctcacaaaagcagctccatggcagcagtcgcattcat
cgttacgattgtgccgcccacggtgcacctactgtgtgatggcgttgcagctatgcggta
gtggctcat--gagagcacctactgtgcactggctacgtagggcctatctgaagtctgct
tggctttaacgctgggcggaaacagccgag---------------------gtcggaccc
cggtggaatagagcagagaactc--------------------ttaggggtttcacttca
cagtccttgggagtgctaggttcttagac----------------tcgtacttatgtgac
aagcacttaccagaaataaa
>SEQ6
gtaataaagcttcaaggg------------------------------------------
--------ccgaaccggaagtatgccgtaatcccccttgcttgtgtgctatgtcgcgaca
cgtcagtcgtg----------------acttccaccacctg-------------------
---------------ctaaaagacgatcgaaacacgcctgggtgttcttagcaacacaca
gacttggctggcgttgttgatagtcgaaatgtagctgcggacaacagtttcttgcactaa
cggctaaggctg-------------------------gctgattaaaattgcttttgaca
agtaagtcca-----------------------catcctgcgaggaaaggcattctacgt
agagaactgggcgatcatac----------------------------tctcccgacttt
gagtccgagaaa--------aacaaagaagtgtggacgcagggaccagccctagaatacg
caacgaacaatcgactccagccaacggaaagtcccccatttgatttagtcattcgtgaag
tcaaatacgtaagtcaatgcaagcgcgtgttctaaggagcga------------------
-----tatgtgctgcgctaatctagaaagggcccacgac---------------------
-aacccccagcgttttacgctggctgacaaagccagcacaaaggccgcagatgcatt---
--------------------cggtgcacctactgggtgatggcgttgcagctatggggta
gtggctcattcgagagcacctactgtgcactggctacgtagggcctatctgaagtctgct
tccttgttacactgggcggaggcaacctagtctcggcttttttaggttcatgtgggacac
ggtggcaatagtgcatagcaccctcccgtatggccgtgtgggattaggggtttcacataa
cattccttgggagtacttgatactttggcttccgcgtctagtcttacgtacatatgagtc
aagcagtcccactaaataaa
>SEQ7
acaataacggtgtcgtgacatcagctgccgtacccgaagcgtcgaa--------------
--------ctgaaaaaaatgtatcccagagtccccctgtcttgtgtactatggcgagaga
cgtcagtccttagcgtcgctaataataacttccaccgcctgcaaggttacattgcggaat
tttatcgcctgttccctaaaagacgctcgcaacacgcctgggtgtttttagcaaaacaca
gacttggctggcgttgttgatagtcgaaatgtagctgcggacaacagtttcttgcactaa
cggctaaggctg-------------------------gctgataaaaattgcttttgaca
agtaagtaca-----------------------catcctgcgaagaaaggcattctacgt
agagaagcgggcgatcatac----------------------------tttcccgactgt
gaatccgagaag--------aacaaagaagtgtggacgcagggaccagccctagaatacg
caacgaacaatcgactccacccaacggaaagtcccccatttgatttagtcattcgtgaag
taaaccacgtaaggaaatgcaagcgcctcttcgaaggagcgaggtgctccattaacctcg
attagtatgagctccgaagctctaccaagggcccacgacatcgcggtcttgcactatccc
aaac-------------------------aagccagcactacggcagcatacgcattcat
cgta---------------tcggtgcacctactgtgtgatggcgttgcagctatggggta
gtggctcattcgagagcacctactgtgcactggctacctagggcctatctgaagtctgct
tcgttataccggtcggcggaagcgaccgagtctcggcttttctagggtcatgtgtgccac
cggtacaagtgtgtattgaaccctcccgtagtgccgcgtgggattaggggtgtcacagca
tattccttggtagtgcttgatattttggcttctgcgtctggtatttcgtacttataagtc
aagcagttcctacaaataaa
>SEQ8
tcaataacgttgtcgcgacatcaggcgccgtaccggcagcgtcgaacggtccgggtcccc
tcactgtctagtataaaatgtttcccataatcccactttgttaagtacta----------
-----------------------------------cacctacaaggtttcgcagcgtaat
ttcactgctggctcactaaaagacgatcgaaacacgcctgggtgttcttagcaacacaca
gacttggctggcgttgttgatagtcgaaatctagctgcggacaacagtttcttgcactaa
cggcgaaggttg-------------------------gctgataaaaattgctt------
----------------------------------gtcctacgaagaaagggattctacgt
agagaatctaggttccc-------------------------------------------
--------------------aactaagaagtgtggacgcagggaccagccctagaatacg
caacgaacaatcgactccacccaacggaaagtccctcatttgatttagtcattcgtgaag
tcaaccacgcagggaaatgcaagctccaattccgaggagcggggccctccattaacctcg
aatag-------------------acaaggtcccccgacttcgcggtctt----------
-----------gtttaacgccggaacacaaagtaagcccaaaggcagcagacgcattaat
cttgacgattctgccccccacggtgcacctactgtgtgatggcgttgcaactatggggta
gtggctcattcgagagcacctactgtgcactggctacgtagggcctatctgaagtctgct
tcctta----------------------ggtttaggcggctttgggttccggtggggccc
cggtgcaatagagcagagaaccc--------------------tttgggggttcacttta
tagtccttgggagtgcttgatactttggcttttgcctctggtctatcgtatttatgactc
aagcacttaccataaataaa
>SEQ9
gcaataatgttgtcgtgacatcaggtgccg------------------------------
----tgaccagaataaaatgaatcccatagtccgcctgacttgtctcctatggcgcgaga
cgtcagtagttggcgtcgctaataa-----------------aaggttgcgtagagcaat
tttattgcttgttccctaacagacgatcgaaacacgcctgggtgttcttagaaacacaca
gacttggctggcgttgttgatagtcgaaatgtagctgcggacaacagtttcttgcactaa
cggctacggctgggtttaatatgctttacgaccattaagtgattaaattggcttttgaga
agtaagtccatataagctgctacattatgtctcagtc-----------------------
------ctaggcggccatagaacactcccctatcgcgaagacgtaatatctcatgacatt
gagtcagacaagaggaagggaacaaagaagtgtggacgcagggaccagccctagaatacg
caacgaacaatcgactccacccaacggcaagtcccccatttgatttagtcattcgtgaag
tgaaccacgcaggccagtgcacgcgcccactccgaagagcgaggcccttcattaccc---
------------------------agtagggcctcccacacca-----------------
-------aaccgttaatagccggctcacaaaagcgggtcgatggcagcagtcgcaataat
cgttacgattgtgccccccacggtgctcctactgtttgatggcgttgcagctatggggta
gtgcctcattcgagagcacctactttgcactggctacgtagggcctatctgaagtctgct
gggctttaacgctgcgcggaaacagccgag---------------------gtcggaccc
cgttgggatagagcggagatctc--------------------ttaggggtttctcttca
cagtccttgggagtgctaggttcttagac----------------tcgtacttatgagac
aagcacttactagaaa----
>SEQ10
gtaattaa----------------------------------------------------
-------------------gtatcccgtaatccccattgc--------------------
cgtcagtcgtg----------------actgccacgacctg-------------------
---------------ctaaaagacgctcgcaacacgcctgggtgtttttagcaaaacaca
gacttggctggcgttgttgatagtcgaaatgtagctgcggacaacagtttcttgcactaa
cggctaaggcgctgttttgtatgcttgacaaccattaggtgattaaaatcgcttttgact
agtaagtcga-----------------------caacttgcggtcaaaggc---------
------------------------------------------------------------
---tacaagtaa--------aacaaagaagtgtggacgcagggaccagccctagaatacg
caacgaacaatcgactccacccaacggcaagtcccccatttgatttagtcattcgtgaag
taaaccacgtaaggaaatgcaagcgc--------------------ctccattgacctcg
ataagtatgagctcggaagctcta------------------gcggtcttactctg----
--------------------cggctcacaaagccagcccaaaggcatcatacccattcat
cgt----------------acggtgcacctactgtgtgatggcgttgcagctatggggta
gtggctcattcgagagcacctactgtgcactggctacgtagggcctatctgaagtctgct
tccttgttacaatgggcggaggcaacctagtctcggcttttttaggttcatgtgggacac
ggtggcggccgtgaggg-------------------------------------------
----------------ctgatagtttggctcccgcgtctagtcttacgtaaacttgagtc
aagcagtgccactaaataaa
>SEQ11
acaataacggtgttgtgacatcagctgccgaaccagaagcgtcgaa--------------
--------ctgaaaaaaatgtatcccagagtccccctgtcttgtgtactatggcgggaga
cgtcagtccttagcgtcgataataataggttccaccgcgtgcaaggttgcattccggatt
tttatcgccttttccctaaaagacgctcgcaacacgcctgggtgtttttagcaacacaca
gacttggctggcgttgttgatagtcgaaatgtagctgcggacaacagtttcttgcactaa
cggctacgccggtgattaatatgctttacgatcattaggtgattaaattggctctt----
-----------attagctgctatattatgtctcagtctcgcgagcgaat-----------
------caagccggccatacaacaataccctatcgggagcaggtaat-------------
--gtcacacgagaggaagggaactaagaagtgtggacgcagggaccagccctagaattcg
caacgaacaatcgactccacccaacggaaagtccctcatttgatttagtcagtcgtgaag
tgaaccacgtaatgaaatgcaagcgcctcttcggaggagggaggcgcgcga---------
---------agctccgaagctcgacccactatcccaaac---------------------
-----------------------------aagcccgcactacagcagcatacccattcat
cgta---------------tcggtgcacctactgtgtgatggcgttgcagctatggggta
gtggctcattcgagagcacctactgtgcactggctacctagggcctatctgaagtctgct
tgcttataacgcttgtccggagcaacggagtctcggggtctttgggttcaggtgagcccc
cggtgtagtagcgcagagaaccc-------------------------------------
-----ttgaggtctgctagatactt----------------tctttcgtacaagtgagtc
aggcacttacaataactaa-
>SEQ12
gtaataaagcttc-----------------------------------------------
--------------aagggctatgccgtaatcccccatgcttgttcgctatgtagcgaca
cgtcaggcgtg----------------acttccaccacctg-------------------
--------------------agacgatcgaaacacgcctgggtgttcttagcaacaaaca
gacttggctggcgttgttgatagtcgaaatgtagctgcggacaacagtttcttgcactaa
cggctaaggcgctcttttgtatgcttgacaaccattagttgattaagttgac--------
----------------------------------aacttgcggtca--------------
------------------------------------------------------------
---tacaagtaa--------aacaaagaagtgtggacgcagggaccagccctagaatacg
caacgaacaatcgactccagccaacggaaagtcccccatttgatttagtcattcgtgaag
gaacctacggaagtaaatacaagcgcctgttcgaaggagcgttatacccaattaacctcg
attagtatgtgctcctaagcgctacaaagggaccacgacatcgcgagcctacactatacc
aattccccagtgttttccgccggctgacaaagcaagcacaaaggcagcatatgcatt---
---------------gctcacggtgcacctactgtgtgatggcgttgcagctatggggta
gtggctcattcgagagcacctactgtgcactggctacgtagggcctatctgaagtctgct
tcctta----------------------ggtttaggcggctttgggatccggtggagccc
cggtgcaacagagctgtgaacac--------------------tttggaggttcacttta
tactccttgggagtgcttgatactttggcttttg--------------------------
--------------------
>SEQ13
acaataacggtgttgtga------------------------------------------
----------------------------------cctgtcttgtgtactatggcgggaga
cgtcagtccttagcgtcgatataaataggttccaccgcgtgcaaggttgcattccggagt
tttatctcatattccctaaaagacgctcgcaacacgcctgggtgtttttagcaacacaca
gacttggctggcgttgttgatagtcgaaatgtagctgcggacaacagtttcttgcactaa
cggctacgcaggtaactaatatgctttatgatcattaggtgattaaacttgctctt----
-----------attagctgctatgttatgccttagtctcgcgagcgaat-----------
------cacggcggccatacaacatt----------------------------------
--gtcacacgagaggaagggaacaaagaagtgtgaacgcagggaccagccctagaatacg
caacgaacaatcgactccagccaacggaaagtcccccatttgatttagtcattcgtgaag
tgcgtgctctaaggagcgatatgtgc----------------------------------
------------tgcgctaatctagaaagggcccacgacatc------------------
----ccccaccgttttacgatggctgacaaagcccgcacaaaggccgcaggt--------
-------------------gcggtgcacctactgggtgatggcgttgcagctatggggta
gtggctcattcgagagcacctactgtgcactggctacgtaaggcctatctgaagtctgct
tctttaaaacactgagcggaggcaacctagtcccggccttttttggtccacgtgggccac
ggttgca----------------ttctgtagtgccgtgtgggattaggggtcgcacatca
cattcctttggagtacttgatacttaggcgtacgggtctagtttttcgtacatatgaatc
aagcagttccaccaaataaa
>SEQ14
gcaataacgctgtccagacatcaggcggcgaacc--------------------------
-------------------ggtcccctcaatccgcatctcttgtgtactatgtcgggaga
t--------------------------------------------actccgtagattaat
tttactact----------aagacgctcgcaacacgcctgggtgtttttagcaacacaca
gacttggctggcgttgttgatagtcgaaatgtagctgcggacaacagtttcttgcactaa
cggcgaaggctg--------------------------ctgataaaaattgcct------
----------------------------------gtgttacgaagaaagggaggcttggt
tccc--------------------------------------------------------
--------------------aacaaagaagtgtggacgcagggaccagccctagaatacg
caacgaacaatcgactccagccaacggaaagtcgcccatttgatttagtcattcgtgaag
tcaaccatgcagggaaatgcaagctccaactc-----------------cattaacctcg
aatag-------------------acaaggtcccccgacttcgcggtctt----------
------------------------------agtaagcccaaaggctgcagccgca-----
-----------------ccacggtgcacctactgtgtgatggcgttgcagctatgcggta
gtggctcat--gagagcacctactgtgcactggctacgtagggcctatctgaagtctgct
--------------ggcggtagcaaccgagtctcggcttttttaggtacatgttggccac
cggtgcaatagtgcat----------------------------------tttcacttca
caatccttgggagtgcttgatactt-----------------------tgcttatgagtc
aagcagt-------------
>SEQ15
gtaatagt----------------------------------------------------
----------------------cccttcaatccccatctcttgtgtactatgttgggaga
tact--------------------------------------------------------
--------------------agacgatcgaaacacgactgggtgttcttagcaacaaaca
gacttggctggcgttgttgatagtcgaaatgtagctgcggacaacagtttcttgcactaa
cggctacggcggtgtttgaaatactttacgaccattaagtgagtacgttggcttttgaga
agtaagtccatataagctgctacattatgtctcagtcttgcgagcaaag-----------
------cgaggcggccatacaacaatacccgatcgggtagacgtaatatctcatgacatt
--------------------aacaaagaagtgtggacgcagggaccagccctagaatacg
caacgaacaatcgactccacccaacggaaagtccctcatttgatttagtcattcgtgaag
tcaaccacgcagggaaatgcacgctccaactccgaggagcgaggt---------------
---------------------tgaataaggtcctccgactacgcgttcttact-------
-----------------------ctaacaaaatcagccctaaggcatcagacgcattcat
cgcgactatgctgtcggccacggtgcacctactgtgtgatggcgttgcagctatgcggta
gtggctcat--gagagcacctactgtgcactggctacgtagggcctatctgaagtctgct
tcctta----------------------ggtttaggcggcttccggttcgtagag-----
-------------------------------------------cttgggggttcacttta
tcgtccttggcagtgcttgagactt-----------------ctctcatatttctgactc
aagcacttaccatgaaaaaa
>SEQ16
acaataacggtgttgtaa------------------------------------------
----------------------------------cctgtattgtgtactatggcgggaga
catcagacctcagcgtggatataaagaggttccacagtgtggaaggtttcatt-------
---------------ccggaagacgatcgaaacacgcctgggtgttcttagcaacacaca
gacttggctggcgttgttgatagtcgaaatgtagctgcggacaacagtttcttgcactaa
ctgataaggcggtgttttgtatgcttgacaaccataaggtgact----------------
------------------------------------tctacgtagaaat-----------
---------------------------------------------ctattaccctacttt
aactccgataaa--------aacaaagaagtgtggacgcagggaccagccctagaatacg
caacgaacaatcgactccacccaacggcaagtcccccatttgatttagtcattcgtgaag
taaaccacgtaaggaaatgcaagcgcctcttcgaagaagcgaggttctccattaagc---
-------------------ctctaccaagggcccacgtcattgcggtcttgcactatccc
aa----------------------------------------------------------
---------------accatcggtgcaccaactgtgtgatggcgttgcagctatggggta
gtggctcattcgagagcacctactgtgcactggctacgtagggcctatctgaagtctgct
tgcttataagactaagcggagtcaacctagtctcgccttttttaggttcgtgtgggccac
ggttggaatggtgcgtagaaccctcccgtagtgccgtgtgggcttaggggtttcac----
---------------------actttggcttccg-----------------ataagagtc
aagcagttccacagaataaa
>SEQ17
gcaagaacgctgt-----------------------------------------------
--------ccggctaaaatgtatgccataggcccccttatttgtgtacaatgtcgcgaga
cgtcagtcgttagcgtcgctatgtaacacttccaccacctgcaaggttccgtagcg----
----------gctcccaaaaagacgatcgaaacacgactgggtgttcttagcaataaaca
gacttggctggcgttgttgatagtcgaaatgtagctgcggacaacagtttcttgcactaa
cggctactgcggtttttaatatgctttacga-----------------tggcttttgata
agtaattccatataagctgcaacattatgtctcagtcttgcgagcgagg-----------
------ctaggcggcaatacaacaataccctatcgggaagacgtaatatctcatgacgtt
gagtgagacaagaggaaaggaacaaagaagtgtggacgcagggaccagccctagaatacg
caacgaacaatcgactccagccaacggaaagtcgcccatttgatttagtcattcgtgaag
gcacctgttcgaaggagggtta----------------------tacccaattaagctca
tttagtatgtgatcctaagcgctacaaaggaaccgcgacaacgcgcgcgtacactata--
---------------------------------------gaaggcagcatattcagt---
---------------gctcacggtgcaactactgtgtgatggcgttgcaactatggggta
gtggctcattcgagagcacctactgtgcactggctacgtagggcctatctgaagtctgct
tgatgataacgctg--------------agtctcggcttgtttgggttcggatgggcccc
cggtggagtagagcagacaacac--------------------ttaggggtttcacttca
cagtccttggcagtacttgatact----------------gtctttcgtacttatgagtc
aagcacttaccataaataaa
>SEQ18
-------------------------gatagtacccaaagcggccaaag------------
----tgtccagaagaaaatgaatcccatagtcctcctgtgttgtgtgctatggcgcgcga
cttcg---------------------------------ttgcaaggttacgtagcgcaat
tt------------------------acgaaacacgactgggtgttcttagcaataaaca
gacttggctggcgttgttgatagtcgaaatgtagctgcggacaacagtttcttgcactaa
cggatacgactgggttt---------------------------agattggcttttgaga
agtaagtccgtataagctgctacattatgtcccagtc-----------------------
------ctaggcggctaaaggacactcccctattgcgaagacgtgatatctcatgacatt
gagtttgacaagaggaagggaacaaagaagtgtggacgcagggaccagccctagaatacg
caacgaacaatcgactccacccaacggcaagtcccccatttgatttagtcattcgtgaag
taaaccacataaggaaatgcaaccgc--------------------ctccattgacctcg
ataagtatgagctcggaagcgc--------------------------------------
--------ggtgttgcactgcggctcacacagccagcccagaggcatcattcccattcat
cgt----------------acggtgcacctactgtgtgatggcgttgcagctatggggta
gtggctcattcgggagcacctactgtgcactggctacgtagggcctatctgaagtctgct
tgggtttaatg---------------------------------------ggtccgaccc
cggtggaatagagcagagatctc--------------------ttcggggtttcacttca
cagtccttgggagtgctaggttcctagac----------------tcgtacttatgtgac
aagcacgttcctgaagtaaa
>SEQ19
gcaacaacgctgtccagacatcaggcggcgaacc--------------------------
------------------------------------------gtattcaatgtcgcgagg
t--------------------------actgccaccggccgaaaggttccgtagattaat
tttattactagctc-cataaagacgctcgcaacacgcctgggtgtttttagcaacacaca
gacttggctggcgttgttgatagtcgaaatgtagctgcggacaacagtttcttgcactaa
cggcgaaggcgg--------------------------ctggtaaaaatttcct------
----------------------------------gtgttacgaagaaagggaggcttggt
tccc--------------------------------------------------------
--------------------aacaaagaagtgtggacgcagggaccagccctagaatacg
caacgaacaatcgactccacccaacggaaagtcccccatttgatttagtcattcgtgaag
tcaaccacgcgggtaaatacacgctcctattccgaggagcagggccctcca---------
------------------------acaagctcccccgacttcgcggtcttgtttaacggc
gc--------------------------------------------gcagacgcattcat
cttgtcgattctg--ccccccggtgcacctactgtgtgatggcgttgcagctatggggta
gtggctcattcgggagcacctactgtgcactggctacgtagggcctatctgaagtctgct
tgttgataacgctg--------------agtcccggcttgttt---------------cc
gggtggagtagaccagacaacgc-------------------------------tcttca
cagtccttcgcagtacttgacgctt----------------tttttcgtacttatgagtc
tagcacttaccataaatata
