>SEQ0
tgtcacaggtataggcaaacttacaccggtctcggcaagttaccgcattgcgggtagagt
ggcagtggcgaagccgccattctagtcggcgataa----ctagattacttttcaacctgc
cagccgaatattggtgcggtccgaggcaaaaatgggcgatacgatcatcatcgcgcctcg
taaaatacatcaatgatttaaaacccgccagctccttatcagagacgttcaactctaaga
ccccattccttcagatcgtgagccagcggtacccgcgagtcatcaatcatgattatatgg
aaataataccaaccggcagtattacactccgcctaacggaactgtaagaccaactgcatt
gtggcgtcgacagtcgttagagtatgggttgttatacggactatgtctctcattgagatt
ttacgtttaagagtgacattcttatgcaccttaccgctcatctggcgtttaccacaccat
cacagaccgcccgctacgatcctcgatgcttcactgggccgttgttggatttgctcagcg
aagacacagaagatagcaatgccactaccccgacactaaaagttcatacatcggcctaag
atgcggggggcacaaagtgcacaatcctatatatttgtctcacgtctggaagtgataaga
ctctctttcctctgttccatcagtgcctttgcgagatgggtatctaggagctcgcagtaa
ataacgcctccctagaaaatgaacatactgtacgagtgcgagaagagtcacagcagatcg
agggttgcgttcccctcaggcactcccactcccttccgctagtattgctggacgtctgtc
cgtcatcttcacggtgagttcaacgtgccctgtacgcgtcttgctggcatctccacttac
cctctgagcaatgctgaaggttgctggccgtagttgtgcccacttccggccccctagaaa
tcggggatacccgccggaacggcgagattcccgaactgatgaaaaatgaagagggcttta
cggtcacgggataccaccggattagagtgctgttgactcaaaatgacaagggggaggacg
gcgactcgttgtgacgacggcctg
>SEQ1
tgtcccaggtat--------------cggcctcggcaagtgacctcgtt-----------
-------------tcgccattctaggcggcgataa----caagattactttt--------
------aatattggtgcggtcc---------------------ctcatcattgcgcctcg
taaaatacatcaatcatttaaaacccgccagctccttatcagagacgttcaactctaaga
ccccattccttcagatcgtgaaccagaggtacccgcgagtcatcaatcatgattatatgg
aaatcataccaaccggcagtatt-----------------------------actgcatt
gtggaatcgacagtcgttagagtatgggttgttatacggact------------------
-----tttaacactgaccttcttatgcacctaaccgctcatctggagtttaccacaccaa
cacagatcgcccgctacgagcctcgatgcttcactgggccgttgttggatttgctcagcg
aagacacagaagatagcaatgccactaccccgacactaaaagttcatacatcggcctaag
atgcggggggcacaaagtgcacattcctatatgtttgtct--------------------
-------------------tcagtgcctttgcgagatgggtat-----------------
----------cctagaaaatgaacatactgtaagagtgcgagaagagtcaca--------
--------------ctcaggcactcccactcccttccgctagtattgctggacgtctgtc
cgtcatcttcacggtgagttcaacgtggcctgtacgcgtcttgctggcatctccacttac
cctc-----------------------ccgtagttttgcccacttcccgccccctagaaa
tctgggatacctaccggaacggcgagattcccgaactgataaaaaatgaagagggcttta
cggtcacgtgattccaccggattagagtgctgttgactcaaaatgacaagggggaggacg
gcgactcgttgtgacgacggcctg
>SEQ2
tgtcccaggtag--------------cggcctcggcaagtggactcgtt-----------
-------------tcgccattctaggcggcaatac----caagattactttt--------
------aatatctgtgccgtcc--------------------------------------
----ctacatcaatcatttaa---ccgccagctccttatcagtgacgttcaactctaaga
ccccattccttcagatcgtgagccagcggtacccgcgagtcatcaatcatgattatatgg
aaataataccaaccggcagaattacactccgcctaacggatctgaaagaccaactgcatt
gtggcgtcgacagttgttagagtatgggttgttttacg----------------------
-----tttaagggtgacattcttacgcagcttaccgcccatctggcgtttatcacaccat
cagagaccgcccgccactatcctcgatgcttcactgggccgttgttggatttgctcagcg
aagacaaagaagatagcaatgccactaccccgacactaaaagttcatacatcgacctaag
atgcggagggca--------------------------ctcacgtctggaagtgataaga
ctctctttcctctcttccatcagtgcctttgctagatgggtat-----------------
--------cccctataaactgaacatactgtacgagagcgagaagagtcacagcagatcg
agggctgctttcccatcaggcactcccactcccttccgctagtattgctggacgtctgtc
cgtcatcttcacggtgagttcaacgtgccctgtacgcgtcttgctggcatctccacttac
cctc----------------------------------cccactccccgcccactagaat
tcttggatacctaacggcacggcgagattcacgaaatggtaaaaaatgaagaggccttta
cgctcacgtgattccaccggattagagtgctgttgactcaaaatgacaagggggaggac-
-------------ataacggcctg
>SEQ3
tgtcacaggtatagggaaccttacaccggtctcgaaaagttaccgcattgcggg------
---------gaaggcgccattctagtcggcgataa----ctagattacttttcaacgtgc
cagccgaatattcgtgcggtccgaggcaaaaatgtgcgatacgatcaccttcgcgcctcg
taaaatacaacaaagatttaaaacccgccagctccttatcagagacgttcaactctaaga
ccccattccttcagatcgtgaaccagaggtacccgcgagtcatcaatcatgattatatgg
aaatcgtaccaaccggcagtatt-----------------------------tctgcatt
ggggaatcgacagtcgctaaagtatgggttgatatacggacg------------------
---------acactgaccttcttatgcacctaacagcacatctggagttcaccacaccaa
cacagatcgcccgctacgaccctcgatgcttcactgggccgttgttggatttgctcagcg
atgacaaagaagatagcaatgccactaccccgacactaaaagttcatacatcgacctaag
atgcggggggca--------------------atttgtctcacgtctgaaagtgataaa-
-------------------acagttgctttgtgagataggtatctaggagctcgcattaa
ataacgcctccctagaaaacata-------------------------caccgcagatcg
atggttaggttccccccaggcactcccactcccttccgctagtattgctggacgtctgtc
cgtcaccttcacggtgagttcaacgtgccctgtacgcgtcttgctggcatctccacttac
cctctgatcaatgctgaatgttgctggccgtagttgtgcccacttccggtcccctaggaa
tccggtatacccgccggaacggcta----------------------gaagagggcttta
cggtcacgggataacaccgg--------------------aaatgacaagaggaaggacg
gggactggttgtgccgacggcttg
>SEQ4
tgccgcaggtag--------------cggcttcggcaagtggacccatt-----------
-------------tcgccatactaggcggcaatac----caagattactttt--------
------aatatctgtgccgtcc--------------------------------------
-----------------------cccgccagctccttatcagagacgttcaactctaaga
ccccattccttcagatcgtgagccagcggtacccgcgagtcatcaatcatgattatatgg
aaatcgtaccaaccggcagtact-----------------------------tctgcatt
gcggcatcgacagtcgctaaagtatgggttgata--------------------------
---------acactgaccttcttatgcacctaacagcacatctggagttctccacaccaa
cagagatcgtccgctacgaccctcgatgcttcactgggccgttgttggatttgctcagcg
aagacacagaagatagcaatgccactaccccgacactaaaagttcatacatcggcctaag
atgcggggggcacaaagtgcacaatcctatatatttgtctcacgtccggaagtgataaga
ctctctttcctctgttccaaaagtgcctgtgcgagatgggtatctaggagctcgcagtaa
ata---------------------------------------aagagtcactgcagatcg
agggttgcgttcccctcaggtactcccactcccttccgctagtattgctgtacgtctgtc
cgtcaccttcacggtgagttcaacgtgccctgtacgcgtcttgctggcatctccacttac
cctc-----------------------ccatagttttgcccacttccggccccctagatg
tctgggatgcgtaacgg---------------gaattgataaaaaatgaacagggcttta
cggtcacgtgattccaacggatcagagtgctgtggactcaaaatgacaaggggggggccg
gcgtctcgttggcacgacggcctg
>SEQ5
cgtcacaggcatatgcaaacttacaccgttctcggcaaatt-------------------
-------------tccgcattgcgggtggagtggcagtactagattacttttaaacctgg
cagccgaatattggtgcggtcc---------------------gaggtaaaaatgggcgc
tacgatg-accattcatttaaaacccgccagctccttatcagagacgttcaactctcaga
ccccattccttcagatcgtgagccagcggtacccgcgagtcatcaatcatgattatatgg
aaattataccaatcggcagcatt-----------------------------actgcatt
gtgaattcgacagtggttagagtatgggttgttagacggact------------------
-----tttaacactgaccttcgtatgcacctagccgctcatctggagtttaccgcaccaa
cacagatcgcccgctacgagcctcgatgcttcactgggccgttgttggatttgcacagcg
aagacacagaagatagcaatgccactaccccgacactaaaagttcatacatcggcctaag
atgcggagggca--------------------------ctcaagtctggaagtgataaga
ctctctttcctctcttccatcagtgcctttgctagttgggtat-----------------
--------cccctatagactgaacatagtgtacgagagcgagaagagtcaaagcagatcg
agggcggctttccc------------cactcccttcggctagtattgctggacgtctgtc
cgtcaccttcacggtgagttcaacgtgccctgtacgcgtcttgctggcatctccacttac
cctc-----------------------ccatagttttgcccacttccggccccctagttg
tctgagatgcgtaacga------------------------aaaaaggaaaagggcttta
cggtcacgtcattccaacggatcagagtgctgtggactcaaaaagacaagcgaggggccg
gcgtctcgttggcacgacggcctg
>SEQ6
tgtcccaggtat--------------cggcctcggtaagtgaccgcgtt-----------
-------------------tcttagtcggcgatat----caagattacttta--------
------aatattagtgcggtcg---------------------ctcctcattgcgcctca
taaaatacatcaatcatttaaaacccgccagctccttatcagagacgttcaactctcaga
ccccattccttcagatcgtgagccagcggtacccgcgagtcaacaatcatgattatatgg
aaatcgtaccaaccggcagtatt-----------------------------tctgcatt
ggggaatcgacagtcgctaaagtatgggttgatatactgacg------------------
---------agactgaccttcttatgcacgtaacagcacatctggagttcgccacaccaa
cacagattgcccgctacgaccctcgatgcttcactgggccgttgttggatttgctcagcg
atgacaaagaagatagcaatgccactaccccgacactaaaagttcatacatcgacctaag
atgcgggggtcc--------------------------ctcaagtctggaagtggtaaga
ccctctttcctctcttctatcagtgcctttgctagttgggtat-----------------
--------cccttatagacttaacgtagagttcgagagcgagaagattaaacgcagaccg
agggcggctttccc------------cactcccttccgctagtattgctggacgtctgtc
cgtcatcttcacggtgagttcaacgtggcctgtacgcgtcttgctggcatctccacttac
cctc-----------------------------------ccaccaacggcac--------
------------------------------------------------------------
-------------------aaatttagaggtgttgactcatgatgacaaggggaaggac-
-------------ataacggcctg
>SEQ7
tgtcccaggtag-----------------------caagtggactcgtt-----------
-------------tcgccattctaggcggaaatac----gaagactact-----------
---------atgtgtgccgtcc--------------------------------------
----ctacatcaataa-------tccgccagctccttatcagagacgttcaactctaaga
ccccattccttcagatcgtgaaccagaggtacccgcgagtcatcaatcatgattatatgg
aaatcgtaccaaccgggagtact------------------------------ttgcatt
gcggcatcgacagtcactcaagtatggcttg-----------------------------
-------------------------gtaacaaacagctcatcaggagctcaccacaccaa
cagatatcgtccgctacgaccctcgatgcttcactgggccgttgttggatttgctcaggg
aagacacagaagatagcaatgccactaccccgacactaaaagttcatacatcggcctaag
atgcggggggcacaaggtgc-------------------------------gtaataaga
ctctctttcctctgttcctaaagtgcctgtgtgagaagggtatgtaggagctcgctgtaa
tt---------------------------------------------------cagaccg
tgggttgctttcccctcaggtactcccactcccttccgctagtattgctgtacgtctgtc
cgtcaccttcacggtgagttcaacgtgccctgtacgcgtcttgcttgcatctccacttac
cctc-----------------------tggtagttttgccctcttcccgcccccta----
----------------gaacggcgagattcccgaaccgataaaatatgaagagggctgta
cgatccggtaattccaccggattagagtgctgttgactcgaaatgattagggggaggacg
gcgagtcgttgtgacg--------
>SEQ8
tgtcccaggtag--------------cggcctcggcaagaggactcgtt-----------
-------------tcgccattccaggcggcaaaac----aaagattacttat--------
------catatctatgccgtcc--------------------------------------
----ctacatcaatcatttaa---ctgccagctccttatcagagacgttcaactctaaga
ccccattccttcagatcgtgaaccagaggtacccgcgagtcatcaatgatgattatatgg
aaataataccaaccggcagtattacactccgcctatcgga------------actgtaag
accaagtcgacagtcgttagagtatgggttgttatacggactatgtct------------
-----ctcattaagattattctcctgcaccttagcgctcatctggcgtgttacacaccat
cagataccgcccgctacgatcctcgatgcttcagtgggccgttgttggatttgctcaggg
aagacacagaagatagcaatgccactaccccgacactaaaagttcatacatcggcctaag
atgcggggggcacaatgtgc-------------------------------gtaataaga
ctctcgttccgctgttcca------------------gggtatgtacgagctcgctgt--
-------------------------------------------------atttcagaccg
tgggctgctttcccctcagatactcccactcccttccgctagtattgctggacgtctgtc
cgtcaccttcacggcgagttcaacgtgccctgtacgcgtcttgctggcatctccacttac
cctctaatgaatgatgaatgttgcaggccgtagttgtgccctcttccagtcgcctaggaa
tccggtatacccgccggagcggctagaaa-------------------------------
----------------------------------gattaccaatgacaagaggaaggacg
ggtactggttgtgccgaaggcttg
>SEQ9
---------------------------tgtccctggtga----ctcgtt-----------
-------------tcggcagtctacgcggt------------------------------
---------atgtgtgccatcc--------------------------------------
-----------ctacatcagtaatccgccagctccttatcagagacgttcaactctaaga
ccccattccttcagatcgtgaaccagaggtacccgcgagtcatcaatcatgattatatgg
aaatcgtaccaagcggtagtatt-------------------------------------
------------------------------------------------------------
--tccgtgaagacagtccttcttatacacgtaccagcccatgtggagttccacacagcaa
cacagattgcccgctatgacccacgatgcttcactgggccgttgttggatttgctcagcg
atgacaaagaagatagcaatgccactaccccgacactaaaagttcatacatcgacctaag
atgcgaagggca---------------------------tcaagtctggaagtgataaga
ctctctttcctcccttccatcagtgcctttgctagttgggtag-----------------
--------ctactatagactgaacatagtgtacgagagcgagaagagtcaaagcagatcg
agggcggct---cc------------cactccctgccgctagtattgctggacgtctgtc
cgtcatcttcacggtgagttcaacgtggcctgtacgcgtcttgctggcatctccacttac
cctc-----------------------ccgtagttttgcccacttcccgccccctagaaa
tctgggatacctgccggaacggcgagattctcgaa--------------------cttta
cggtcacgtgattccaca----------------gactcaaaattagaagggggaggacg
gcgacgcgttgtgacgacggcctg
>SEQ10
---------------------------tgtctcagcaggtgacctcgtc-----------
-------------ccgccattctatgcggcgataa----caagtttaatttt--------
-------tgatcattgcgcctc--------------------------------------
-----------gcatatttaaaacccgccagctccttatcagtgacgttcaactctaaga
ccccattccttcagaccgtgagccagcggtacccgcgagtcatcaatcatgattatatgg
aaatcgtaccaagcggcagtagt-------------------------------------
------------------------------------------------------------
--tc--tgaagacagtccttctaatacacgtaccagcccatgtggagttccacacagcaa
cacaggttgcccgctattacccacgatgcttcagtgggccgttgttggatttgctcaggg
aagacacagaagatagcaatgccactaccccgacactaaaagttcatacatcggcctaag
atgcggagggca--------------------------ctcaagtctggaagttttaaga
ctctctttcctctcctccatcaaagcctttgctagttgggtat-----------------
--------cccttttagcctgaacatagtctacgagagcgagaatagtcaaagcagatcg
acggaggctttccc------------cactcccttccgctagtattgctggacgtctgtc
cgtcaccttcacgccgagttcaacgtgccctgtacgcgtcttgctggcatctccacttac
cctc-----------------------ccgtagttttgcccacttcctgccccctagaaa
cctgggttacctgccggaaaggcgagattctcgca-------------------------
----cacgtgtttccaca----------------gactcaaaatt---------------
--------------cgacggcctg
>SEQ11
tgccgcaggtag--------------atgcatcggcaattggacccatttcg--------
---------------------------------------caagattagtttt--------
------attatctgtgccgtgc--------------------------------------
-----------------------accgccagctccttatcagagacgttcaactctaaga
ccccatgccttcagatcgtgaaccagaggtagccgcgagtcatcaatcatgattatatgg
aaattatacaaatcggcagcatt----------------------------------act
gtgaattcgacagtggttagagtatgggttgttagacggact------------------
-----attaacactgaccttcgtatgcacctagacgctcttctggagtttacagcaccaa
cacagatcgcccgctacgagcctggatgcttcactgggccgttgttggatttgctcagcg
aagacacagaagatagcaatgccactaccccgacactaaaagttcatacatcggcctaag
atgcgg----------------------------------------tgaaagtgataaaa
c--------------------agttgctttgtgggataggaaccttgcagctcgcatgaa
ataacgcatcccgagataccta--------------------------caccgcagatcg
atggt------------------tcccactcccttccgctagtattgctggacgtctgtc
cgtcaccttcacggcgagttcaacgtgccctgtacgcgtcttgctggcatctccacttac
cctc------------------------------------------ccgccacctagaaa
tc----------------acggcgagattcccgaactgataaaaactgaagaggccttta
cggtcacgtga------------------------------------aagggggaggatg
gcgtcgcgttgt------------
>SEQ12
tgccgccggtag--------------gggcttcgataagcggat----------------
-------------ccaccatactaggaggcaagag----caagattactttt--------
------aatatctgtgccgtcc--------------------------------------
-----------------------cccgccagctccttatcagagacgttcaactctaaga
ccccattccttcagatcgtgaaccagaggtacccgcgagtaatcaatcatgattatatgg
aaattatcccaatcggcatcatt-----------------------------actgcttg
gtgaaatcgacactggttagagcatgggttgata--------------------------
-----tttaacactgacctttagatgcacctagcccctcatctggagtttaccgcaccaa
cacggatcgcccgctacaagcctcgatgcttcactgggccgttgttggatttgctcagcg
aagacacagaagattgcaatgccactaccccgacactaaaagttcatacatcggcctaag
atgcggggggcacaaagtgcacaatcctatatatttatctcaagtctgtaagtgataaga
ctctttttcttctgttccataagtgcctttgcgagatggttatctaggagctcgcagtaa
ctaacgcctccctagaacatgagcattctgtacgagtgcgtgatgagtcacagcagatcg
agggttgcgttacccgcaggcactcccactcccttcggctagtattgctggacatctgtc
cgtcaccttcacggtgagttcaacgtgccctgtacgcgtcttgctggcatctccacttac
cctc--------------------------------------cctcccgcccacgaaaaa
tcagggctacctgccggaacggcgagattctcaaaa--------------------ttta
cggtcacgtgattccacagaat----------------------------ggggaggacg
gcgacgcgttgggacgacggcctg
>SEQ13
---------------------------------------tg-------------------
-------------tccccattctaggccgcgatac----caagattactttt--------
------aattttggtgcggtcc---------------------cgcatcattgcgcctcg
taaaatacatcaatcatttaaaacccgccagctccttatcagtgacgttcaactctaaga
ccccattccttcagaccgtgagccagcggtacccgcgagtcatcaatcatgattatatgg
aaattatcccaatcggcatcatt-----------------------------tctgctag
gcgacatcgacactggttcgag--------------------------------------
--------------------catttatccctagcccatcatctggaggttaccgcaccaa
cacggatcgcctgctacaagcctcgatgcttcactgggccgttctgggatttgctcagcg
aagacacagaagatagcaatgccactaccccgacactaaaagttcatacatcggcctaag
atgcgggggtc------------------------------------------------c
ccctccttcctctcttgaatctgtgccttttttagttggatat-----------------
--------c-----------------agagttcgagagcgagcagattaaacgcagaccg
agggcggctttccc------------cactcccttccgctagtattgctggacgtctgtc
cgtcaccttcacggtgacttcaacgtgccctgtacgcgtcttgctggcatctccacttac
cctc-----------------------ccgtagttttgcccacttcgcgcccccgagatg
tctgggatgt------------------------------------ggaattgggcttta
cggtcacgtgattgtaacggatcagagggctgtggactcaaaatgacatggggggggccg
tcgtcacattggcacgacggtctg
>SEQ14
tgtgccaggtag--------------cggcttcggcaagaggactcgtttga--------
------------------attccaagcggcaaaac----aaagattacttat--------
------catatctatcccgtcc--------------------------------------
----ctacatcaatcatttta---ccgccagctccttatcagtgacgttcaactctaaga
ccccattccttcagatcgtgagccagcggtacccgcgagtcatcaatcatgattatatgg
aaattatcccaatcggcatcaaa-----------------------------actgcttg
gtgaactcgacactgggtagagcacgggttgata--------------------------
-----tttaacactgacctttagatgcacctagcccctcatctggagcttaccgcaccaa
cgcggatcgcccg-----------gatgcttcactgggccgttgttggatttgctcagcg
atgacaaagaagatagcaatgccactaccccgacactaaaagttcatacatcgacctaag
atgcggggggcacaaagtgcacaatcctatatatttgtgtcacgtccggaagcgataaga
ctctcgttcctctgttccaatactgcct------------------ggagctcgcagtaa
ata---------------------------------------aagagtcactgcagatcg
attgatgcgttcccctccggtactcccactcccttccgctagtattgctggacgtctgtc
cgtcatcttcacggtgagttcaacgtgccctgtacgcgtcttgctagcatctccacttac
cctc-----------------------ccgtggttttgcccgcttcgcgcccccgagatg
tacgtgaagt------------------------------------ggaattgggcttta
cggtaacgtgatggtaac--------------------ccaaatgacaagcggggggccg
tcgtaacattggcacgacggtctg
>SEQ15
------------------------------------------------------------
-----------tgccgccattcaatgccgcgatac----caagtttacttgt--------
-------aaatttgggcagcat-----------------------------tgcgcctcg
taaaataca--------------tccgccagctccttatcagagacgttcaactctaaga
ccccattccttcagatcgtgagccagcggtacccgcgagtcatcaatcatgattatatgg
aaatcttaccaagcggtagtatt-------------------------------------
------------------------------------------------------------
-----tccgagcaagtccttcttatgcac---------------------gtcagagcaa
cacagatcgcccgctattacccacgatgcttcagtgggccgttgttggattagctcaggg
aagacacagaagatagcaatgccaataccccgatactaaaagttcatacatcggcctaag
atgcggggggcacaaagtgctcaatcctatatatttgtctcacgtctggaagtgataaga
ctcactttcctctgttccatcagtgcctttgcgagatgggtatcaaggagct--------
------------tagaaaatgaacatactgtacgagtgagataagagtcacagcagatcg
agggttgcgttccc--------ctcccactcccttccgctagtattgctgtacgtctgtc
cgtcaccttcacggtgcgttcaacgtgccctgtacgcgtcttgctgccatctccacttac
cctctgatcagttctgaatgttg--------------------ttccggtcccctaggaa
tccggtatacccgccggaacggcta----------------------gaagagggcttta
cggtcacgggataacaccgg--------------------aagtgacaagaggaaggac-
------------------ggcttg
>SEQ16
tgtcgcaggtag--------------cggcctcggtaacaggactcgtt-----------
-------------tcgccattcaaggctgcaaaat----aaagattactgat--------
------catttcaatgccgtcc--------------------------------------
----ctacatcaattatttaa---ccgccagctccttatcagagacgttcaactctaaga
ccccattccttcagatcgtgaaccagaggtacccgcgagccatcaatcatgattatatgg
aaattgtactaa------------------------------------------------
--------------------agtatgggttaatg--------------------------
---------tcactgaccttcctatgcacctaacagcacatctggagctctccacaccaa
cagagatcatccgctacgaccctcgatgcttcactgggccgttgttggatttgctcagcg
aagacacagaagatagcaatgccactaccccgacactaaaagttcatacatcggcctaag
atgcggggggcaaaaagggcacattcctataagtttgtct--------------------
-------------------tcagtgcctttgcgaga------------------------
----------cctagaaaatgaacatactgt------------------atcaca-----
--------------ctcaggcactcccactcccttccgctagtattgctggacgtctgtc
cgtcatcttcatggtgagttcaacgtggcctgtacgcgtcttgctggcatctccacttac
cctctgatcaatc-------------------------ctgactgtcggtcccctaggaa
tccggct---------------------------------------agaagatggcttga
cgcacacgggataa--------------------gacccgaaacgacaagaggaaggacg
gggactggttg-------------
>SEQ17
tgccgcaggta---------------------cggccattggacccatt-----------
-------------tcgc-----------------------aagattagt-----------
------------------------------------------------------------
-----ttgagtagctgtgccg---ccgccagctccctatcagagacgttcaactctaaga
ccccattccttgagatcgtgaaccagaggtacccgctagtcatcaatcatgattatatgg
aaattgagctaa------------------------------------------------
--------------------agtataggtta-----------------------------
---------tcactgacct---------------------tctggagctctccacaccta
cagagatcatccactacgacccgcgatgcttcactgggccgttgttggatttgctcagcg
aagacacagaagattgcaatgccactaccccgacactaaaagttcatacatcggcctaag
atgcgcgtaataaga-----------ctctcgtttcgccg--------------------
-------------------ttcgagggtatgt----------------------------
------------------acgagctcgctgt------------------atttcagaccg
tgggccgctttcccctcagacactcccactcccttccgctagtattgctggacgtctgtc
cgtcaccttcacggcgagttcaacgtgccctgtacgcgtcttgcaggcatctccacttac
cctctgatcaatc-------------------------c------tcggtcccctaggaa
tcccgct---------------------------------------agaagatggcttga
cgtacacgggataa--------------------gacccg-------aagaggaaggacg
gggacttgttg-------------
>SEQ18
------------------------------------------------------------
-----------tgccgccattct----------------aaagtttgcttgt--------
-------aaatttgggcagcac--------------------------------------
-----tgcgcctcttaaaatatatccgccagctccttatcagagacgttcaactctaaga
ccccattcgttcagatcgtgagccagcggtacccgcgagtcatcaatcatgattatatgg
aagtaataccaaccggcagtgttatactccgcctaacggaactgaaagaccaactgcatt
gtggcgtcgacagtcgttagtgtatcggttgtta-----------tctctcaatgagatt
ttacgtttaagagtgacattctaatgcaccttaccgctcatcctgcgtt-----------
---gaaccgtccgctacgaccctcgatgcttcactgggtcgttgtaggatttgctcagcg
aagacacagaagatagcaatgccactaccccgacactaaaagttcatacatcggcctaag
atgcggggg---------------------------------------------------
------ttccgctgttcca------------------gggtatgtacgagctcgctgtat
tt------------------------------------------------------accg
tgggctgcttgcccctcagacaatcccactcccttccgctagtattgctggacgtctgtc
cgtcatcttcagggtgagttcaacgtgtcctgtacgcgtcttgctggcgtctccacttac
cctc-----------------------ccgtagttttgcccacttcgcgcccccgagatg
tccgggatg-----------------------------------------------tgtg
cggtcacgtgcttgcaacggatcagagcgctgtgcacttaaaataccatagggggggctg
tcttcaccttggcacggcggtctg
>SEQ19
tatgccacgtag--------------cggcttcggcaagaggactcgtttga--------
------------------attccaagcggcaaaac----taagattacgtat--------
------------------------------------------------------------
-----tacatcaatcatttta---ccgccagctccttatcagtgacgttcaactctaaga
ccccattccttcagaccgtgagccagcggtacccgcgagtcatcaatcatgattatatgg
aaattataccaatcggcagcatt-----------------------------actgcatt
gtgaattcaacagtggagacaggatgagttgttagacggact------------------
-----tttaacactgaccttcgtgtgcgcctagccactcatctggagtttaccggaccaa
cacagatcgtccgctacgagcttcgatgcttcactgggccgttgttggatttgctcagcg
aagacacagaagattgcaatgccactaccccgacactaaaagttcatacatcggcctaag
atgcggggggcacagactgcacaatcctatatatttgactcacgtgcggaag--------
--------------ttccaaaagtgcctgtgcgtggtgggtaactacgagctcgcagcaa
ata---------------------------------------aggagtccctgcagatcg
aggattaagttcgcctcaggtactcccacacccttccgctagtattgctggacgtctgtc
cgtcatcttcacggtgagttcaacgtgccctgtacgcgtcttgctggcatctccacttac
cctc----------------------------------cccactccccgcccactagaat
tcttgtatacctaagggcgcggcgagattcacgaaatggtaaaaattgaagaggccttta
cgctcaggtgattccaccggattagagagctgctgacttaagatggcaagcgcgaggac-
-------------ataacggcctg
