>SEQ0
--------------gagagatgtagcaactgtgcagtacgcgcaacggtggctagagttg
ttcccatgtttgcacgcaacattgtccaatacttagagtccagctcatgaaattagtggg
atgtataagccgcactataggcatgctaggggccactagaggcccacatcttcatctcct
ccgcttccga-atccatgccagatagtcctttatgtccgaagctaggcattagttgcctg
ttcttgaatctctagcaggcggaagttattctcagttcgccagataacgagaagactcgc
atgcatccggtctatctttattgcaatttaggagggctcaacgggtgaagaatccggttt
ccaaaaccggctacacatatcctgcaccaactattaagctgcgtaagaaggtccgacctg
actacaccattgaaatcactaccgcgtttccatagggctagacacgaaccggtgccgtgt
aagagtgacaggtaccatgatgttactctaaatgtagacagaatgttaaatgtattattt
caagaactagtcttatccaacctccgcgttgccaaatcgtctccagaatcatttaaacct
gaacgtcgctgtggggatggccagcagcctattcaaaggggggaggctcagagttgtcgc
agtcctggctatccgggacgcttcaggagcaacatgcaaagtgtccggaccgtcgatcgg
acgtcttgacattcgcgaacttcccctgcttgcgggatcgg----------tctagagta
atatttggtgaactacgccgttccgactacatcaggggcagaaaattggtcacgcacact
ctcagataccgtttgcaccaaacgatcgcgaattttgtcggcacctcacatcctttacgg
gggatcctctcactgcgacaagggtgggacacggcttcccgtcgtgaaccacccgcaaag
aaatcggaggtgccaattccctagtcgcgataacccgtaattatatgacgacgccgctgg
acctgcgagtc----gacagtagttgtagctagtaaccgaactcgatgagg---ggtaaa
gcagctgtaaagtgaaccacggcactggtataatagctgtcgatgccccgcg
>SEQ1
--------------gagagatggagcagctgagcagcacgcgcaacgctggctagagttg
atc------------------tagtccaatacttagtgtccagctcatgaaatta-----
----------cttgctataggcat-------------------ccacatcttcatctctt
ccgcttccga-atccatgccatata---------atccgaagctaggcattagttgcctg
ttcttgaatctctagcaggcgggagttattctcagttcgccagataaccagaagactcgc
atgcatccggtctatc------------------ggctcaacgggtggg-----------
---------------------ctacactaagca---------------------------
-----------gaaatcactaccgcgtctccat---------------ccggtgcggtgt
aagagtgacaggtacaatgatgttactataaatgtagacagaatgttaaatgtattattt
caagaaatagtcttatccaacctccgcgttgccaaatcgtctccagaatcatttaaacct
gaacgtcgctgtggggatggccagcagtcta--------------attctgagtt-----
----------------gacgcttcaggagcaacatgcaaagtgtccggaccgtcgagggc
acgtcttgacattcgcgcact----------------tcgg----------ccta-----
-------------tacgcaattccgactacatcaggggcataaaattggtcacgcacact
ctcagataccgtttgcaccaaacgatcgcgaattttgtcggcacctcacatcctttacgg
gggatcctctcactgcgacaagggtgggacacggcttcc-------------------ac
aaataggaggtgccaact----------------ccgtaattatatgacgacgccgttgg
atctgcgagtc----gacagtagttgtagctactaaccgaacgcgatgcgg---ggttaa
gcagctgtgaagtgaaccacggcactggtataatagctgacgatgccccgct
>SEQ2
--------------gagagatggggcagctgagca-------------------------
--------------------------------------cctagctcctgaaatca-----
----------cttgctatagg-------------------------------catctctt
cctcttccga-ttctatgcc--------------atccgaagctaggcattagttgcctg
ttcttgaatctctagcaggcgggagttattctcagttcgccagatgaccagaagactcgc
atgcatccggtctatc------------------ggctcaacgggtgtg-----------
---------------------caacactaatca---------------------------
-----------------actaccgcgtctccat---------------ccggagcggtgt
aagagtgacaggtacaatgatgtta---------tagacagaatgttaaatgtattattt
caagaactagtcttatccaacctccgcgttgccaaatcgtctccagaatcatttagacct
gaacgtcgctgtggggatggcc-------------------------tatgagtt-----
----------------tacgcttgaggagcaacatgcaaagtgtccggaccggcgagagc
acgtctagacattcgcgcact----------------tcgg----------ccta-----
-------------tacgcaattccgactacttcaggggcatagaattggtcacgcacgct
ctcagataccgtttgcaccaaacgatcgcgaattttgtcggcacctcacatcctttacgg
gggatcctctcactgcgacaagggtgggacacggctt----------------------g
agatcggaggtgctaattccctagtggcgataacccgtaatgatatgacaac--------
----------c----gacagtagtagtagctagtaaccgaactcgatgcgg---ggtaaa
gcagctgtaaagtgaaccacggcactggtataatagcagtcgataccccgcg
>SEQ3
--------------aagagatgtagcaa---------acgcgcaacggtgactagagttg
ttcccatgtttgccccaaacattgtccaatacttagagtctcgctc--------------
--------------ctataggcatgcgagtggccactagaggcccacatgttcatctcct
ccgcttccga-atccatgccatattgttctttatgtccgaagctaggcattagttgccgg
ttcttgaatctctagcatgcgggagttattctcagttcgccagataaccagaagactcgc
atgcatccggtctatc------------------tgcgtaacgggtgta-----------
---------------------caacactaagca---------------------------
-----------------actacggcgtttccag---------------ccggagcggtgt
aagagtgacaggtacaatgatgatt---------tagacagaatgttaaatgtattattt
caggaactagtcttatccaacctccgcgttgccaaatcgtctcgagaatcatttaaacct
gaacgtcgctgtggggatggcca-------------------------------------
----------------tacgcttaaggagcagcatgaaaagtgtccggaccggcgagagc
acgtctagaaattcgcgcact----------------tcgg----------cgtg-----
-------------tactcaattccgactactaaaggggcgtagaattggtcacgcacact
ctcagataccgtttgcaccaaacgatcgcgaattttgtcggcacctcacatcctttacgg
gggatcctctcactgcgacaagggtgggacacggctt----------------------g
agatcggaggtgctaattccctagtggcgataacccgtaacgatcagacttc--------
----------c----gacagtcgtagtagctagtagccgaactcgatgcgg---ggtaaa
gcagctgtaatgtgatccacggcactggtataagaggagtcgataccccgcg
>SEQ4
--------------cagagatgtcgcaactttgcagtacgcgcaacgatggctagagttg
ttcccatgtttgcacgcaacattgtacaatacttagagtccagctcatgaaattagtggg
atgtgtaggccgcactattgggatg------------------ccgcatcttcatctcct
ccgcttccga-atccttgcaagatagtccttaatgtccgaagctaggcattagttgccgg
ttcttgaatctctagcatgcgggagttattctcagttcgccagataaccagaaggctcgc
atgcatccggtctatctttactgtgatttacgagggctcaacgggtgaagaatcaggtct
--------------------------ccaactattaagctgcgtaagaaggt--------
-----------------cctacctgactttcatagggctagacatgaaccggc-------
----------------atgatgttaatctaaatgtagacagaatgttaaatgtattattt
caggaactagtcttatccaacctccgcgttgccaaatcgtctcgagaatcatttaaacct
gaacgtcgctgtggggatggccagcagtcta--------------agactgagtt-----
----------------aacgctggaggagccacatgccaagtgtccggacgggggatggc
acgtcttgacattcgcgcact----------------tcgg----------ccta-----
-------------tacgcaattccgtctacatcaggg--------ttggtcacgcacact
ctcagataccgtttgcaccaaacgatcgcgaattttgtcggcacctcacatcctttacgg
gggatcctctcactgcgacaagggtggcacacggctgcccgtactgaaacacccgcaatg
aaatcggaggtgccaattgcctagtcacgatatcccgta---------------------
------------------agtagttgtagctagtaaccgtacgcgattagg---tgtaaa
gcagctgtaaagtgaaccacggcactggtatagtagctgtcgatgccccgcg
>SEQ5
--------------gagagatggggctgctgagca-------------------------
--------------------------------------cctagctcctgaaaaca-----
------------------------------------------------cttg--------
-----------ctatacg---------catcc--atccgaagctaggcattagttgcctg
ttcttgaatctccagcaggcggaagttattctcagttcgccagataacgagaagactcgc
atgcatccggtctatctttactgtgatttccgagggttcaacgggtgaagaatgaggtct
--------------------------ccaactagtaagctgcgtaagaaggt--------
-----------------cctacctgactttcatagggctagacatgaaccg---------
------------------------gatctaaaggtagacagaatgttaaatgtattattt
caagaactagtcttatccaacctccgcgttgccaaatcgtctccagaatcatttaaacct
gaacgtcgctgtggggatgtcctatgagtt------------------------------
----------------tactcttgaggagcatcatgcatagggtccggaccggcgagagg
acgtatagacattcgcgcact----------------tcgg-------------------
----------------------cttactatttcctgggcatagaattggtcacgcacact
ctcagataccgtttgcaccaaacgatcgcgaattttgtcggcacctcacatcctttacgg
gggatcctctcactgcgacaagggtggga-------------------------------
-----ggaggtgctaagtcccgagtggcgataaagcgtaatgatacgacagc--------
----------c----gacagtattagtcgctagtaaccgaactcgatccgg---ggtaaa
gcagctgtaaagtgcaccacagcactggtatgatagcagtcgatttcccgcg
>SEQ6
--------------aagaaatgtagcaa---------acgcggaacggtgactagagttg
ttaccatgtttgccccaaacattggcctatacttagagtctcgcgcctaatggca-----
--------------------------------------------tgcgagtggccactat
cggcccacataatccatgacatggtgttcttt--atccgaagctaggcattagttgcctg
ttcttgaatctctagcaggcggaagttattctcagttcgccagataacgagaagactcgc
atgcatccggtctatctttactctgatttacgagggctcaacgggtgaagaatcaggtct
--------------------------caaactagtaagctgcgtaaga------------
----------------------------ttcatagggctagacatgatccggc-------
----------------atgatgttaatctaaatgtagacagaatgttaaatgtattattt
caagaaatagtcttatccaacctccgcgttgccaaatcgtctccagaatcatttaaacct
gaacgtcgctgtggggatggcc--------------------------------------
------------------cgcttaaggagcagcatgaaaagtgtgcggaccggcgagagc
acgtctaggaattcgcgcaat----------------ccgg-------------------
---------cgggtactctatttc-------------------agttggtcacgcacact
ctcagataccgtttgcaccaaacgatcgcgaattttgtcggcacctcacatcctttacgg
gggatcctctcactgcgacaagggtgggacacggcttcc-------------------aa
aaattggaagcgccaact----------------ccgtaattatatgacgacgccgttgg
gtct------------------------gctactaaccgaacgcg---------------
----------------------cactggtataatagctgacgatgccccg--
>SEQ7
--------------------------------------gacgcaacgctggctagagttg
atc------------------tggtccaatacttagtgtccagctcctgaaatta-----
----------cttgctatagt---------------------------ccttcagctctt
ccgcttgcga-atctatgacatatt---------atccgaagctaggcattagttgcctg
ttcttgaatctctagcaggcgggagttattctcagtccgccagataaccagaagactcgc
atgcatccggtctatctttactgtgaattgcgagggctcaacgggagaagaatcaggtct
--------------------------ccaactactaagctgcgtaagaaggt--------
-----------------cctagctgacttc------------------------------
----------------atgatgttaatctaaaggtagacagaatgtaaaatgtattattt
caagaactagtcttatccaacctccgcgttgccaaatcgtctccagaatcatttagacct
gaacgtcgctgtggggatgg----------------------------------------
----------------cacgcttaaggaggagcatgaaaagagt----------------
--------gcattagtgcaat----------------ccgg----------c--------
-----------------------------------------agggttggtcacgcacact
ctcagataccgtttgcaccaaacgatcgcgaattttgtcggcacctcacatcctttacgg
gggatcctctcactgcgacaagggtgggacacggcttcccgtcgtgtaccacccccaaaa
aaatcggaggtgccaattccctagtcgcgataacccgtaattatatgacgacgccgttgg
acctgccactc----gacagt----------------------cgatgagg---ggtaaa
gcagcggtaaagtgaaccacagcactggtataatagctgtcgatgccccgcg
>SEQ8
atgaaatttagcaaacgcgatgtgtgccccaaaca--------t----------------
---------------------tggccta-tagttagaggcttacgcctaatggca-----
------------------------------------------------tgcgagtggcca
ctatcggagcaatccatgacatggtgttcttt--atccgaagctaggcgttagttgcctg
ttcttgaatctccagcaggcggaagttattctcagttcgccagataacgagaagactcgc
atgcatccggtctatctttccggtgatttccgagggttcagcgggtgaactatgaggtct
--------------------------ccagcgagtaagattcgtacgaaggt--------
-----------------cctaactaattttcatcgggctagacatgacccc---------
------------------------gatctaaaggtagacagaatgttaaatgtattattt
caagaaatagtcttatccaacctccgcgttgccaaatcgtctccagaatcatttaaacct
gaacgtcgctgtggggatggcctatga---------------------------------
-----------------acgtttgaggaggaacatgcaaagtgtcaggaccggcgagagc
acgtttagccattcgcgcact----------------tcgg----------ccta-----
-------------tacgcaattcctacaacttctggggcatagaattggtcacgcacact
ctcagataccgtttgcaccaaacgatcgcgaattttgtcggcacctcacatcctttacgg
gggatcctctcactgcgacaagggtggga-------------------------------
----------------------cacggcttcccgtcgtggaggtgcttattc--------
----------cctagaacgacgccg-----------------ttggacctgccactcgac
actggggtaaagtgaaagacagcactggtata--------------------
>SEQ9
--------------gagagatggggcagctgagct-------------------------
--------------------------------------cctagctcctggaat-------
----------ctcttgatagg-------------------------------catctctt
cctcttccga-ttctatgcc--------------atccgaagctaggcattagttgcctg
ttcttgaatctctagcaggcggaagttattctcagttcgccagataacgagaagactcgc
atgcatccggtctatc---------------------------ggtg-------------
---------------------caagactaatca---------------------------
-------------------taccgcgtctccgt---------------------------
-------acaggtacaattatgtta---------tagacagaatgttaaatgtattattt
caagaactagtcttatccaacctccgcgttgccaaatcgtctccagaatcatttaaacct
gaacgtcgctgtggggatggccagcggcctattcaaaggggggaggctcagagttgtcgc
agccctggatatccaggacgcttcaggagcgaaatgctaagtgtctggaccgtcgatcgg
acttcttgacattcgcgaacc---------------------------------------
----------------aagagtccgactacatcaggggcaggaaattggtcacgcacact
ctcagataccgtttgcaccaaacgatcgcgaattttgtcggcacctcacatcctttacgg
gggatcctctcactgcgacaagggtggcacacggctgcccgtactgaaacacccgcaatg
aaatctggggtgccaattgcctagtcacgatatcccgta---------------------
------------------aatagttgtagctagtaaccgaa-------------------
---------aagcgaaccacggcactggtatagaaggtttgattgccccgcg
>SEQ10
--------------ctgaaattgagcaa---------agg--------------------
-----atgtgtgccccaaaccttggcccatagt---------------------------
------------------------------------------------------------
-------tagacgctgacgcgaagcattcttt--atccgaagctaggcattagttgcctg
ttcttgaatctctagcaggcgggagttattctcagttcgccagataaccagaagactcgc
atgcatccggtctatatttccggtgatttccgagggtcgagcgggcgaactattaggtct
-----------------------------------ccagcgagtaagaa-----------
----------------------ctaattcttatcgggctagacatgacccc---------
------------------------gatctagaggtagacagaatgttaaatgtattattt
caggaactagtcttatccaacctccgcgttgccaaatcgtctcgagaatcatttaaacct
gaacgtcgctgtggggatggcc-----------tatgagtt-------------------
----------------tacgcttgaggagcaacatgcaaaatgtccggaccggcga----
------cgtgcacttcgactt---------------------------------------
------------atacgcaattccgactacttcgggggcatagaattggtcacgcacact
ctcagataccgtttgcaccaaacgatcgcgaattttgtcggcacctcacatcctttacgg
gggatcctctcactgcgacaagggtggtacacgaattcc-------------------ac
aaaaaggaggtgccaact----------------ccgtaagtatatgacgacgccgttgg
atctgccactc----gacactagttgtagctactaaccgaacgcgatgccg---ggttaa
gcagc------------------------ataatagctgacgacgccccgct
>SEQ11
--------------gagagatggggctgctgagta-------------------------
--------------------------------------cctagctcctgaaagca-----
------------------------------------------------cttg--------
-----------ctatacg---------cat-----tccgaaggtaggcattagttgcctg
ttcttgaatctctagcaggcggaagttattctcagttcgccagataacgagaagactcgc
atgcatccggtctatctttactgtgatttccgagggttcaacggg---------------
----------------------------agctagtaagctgagtaagaaagt--------
-----------------c----------ttcctagggctagacatgaaccg---------
------------------------g-------ggtagacagaatgttaaatgtattattt
caggaactagtcttatccaacctccgcgttgccaaatcgtctcgagaatcatttaaacct
gaacgtcgctgtggggatggc---------------------------------------
-----------------acgcttacggaggagcatgaaaagaat----------------
--------gcattagtgcaat----------------ccgg-------------------
----------------------c---------------------gttggtcacgcacact
ctcagataccgtttgcaccaaacgatcgcgaattttgtcggcacctcacatcctttacga
gggatcctctcactgcgacaagggtgtga-------------------------------
-----ggaggtgctaaggcccgagtggcgataaagcgtaatgatacgacagc--------
----------c----gacagtatgggtcgctagtaacctaactcgatccgg---ggtaaa
gcagctgtaatgcgcaccacagcactggtatgagatcagtcgatttcccgcg
>SEQ12
--------------------------------------gaggcaaggctggctagagttg
atc------------------tggtccaatacttagtgtccagctcctgaaatta-----
------------------------------------------------ccttcaggactt
ccgcttgcga-atccatgacagatt---------atccgaagctaggcattagttgcctg
ttcttgaatctctagcaggcgggagttattctcagttcgccagatacccagaagaatcgc
atgcatccggtatatctttactgtgaatcgcgagggctccacgtgagaagaatcaggtct
--------------------------ccaactactaggctgcgtacgaaggt--------
-----------------ccgagttgacttc------------------------------
----------------atgaggttactcgaaaggtagacagaatgttaaatgtattattt
caagaactagtcttatccaacctccgcgttgccaaatcgtctccagaatcatttaaacct
gaacgtcgctgtggggagggtctgcagcctattcaaaggggggaggctcagagttgtcgc
agtcctgcgtatccgggacgcttcaggagcaacacgaaaagtgtcgggaccgtcgatcgg
tcgtcttgacattcgcgaactccccctgcttgcgggatcgg----------tctagaata
atatttgttgaactacgctgtaccggctaaataaggggcacaaaattggtcacgcacact
ctcagataccgtttgcaccaaacgatcgcgaattttgtcggcacctcacatcctttacgg
gggatcctctcactgcgacaagggtgggacgcagcttcccgccgt---------------
-----tgaggtgcttattccctag----------------------aactacgccgttgg
acctgccactc----gacactcg-------------------------------------
-----ggtaaagtgaaagatagcactggtata--------------------
>SEQ13
--------------aagaaatgaagcaa---------acgcagaacggtgactagagttg
ttaccatgtttgccacaaacattggccgatactagtagtctcgcgcatgcgagtg-----
----------------------------------------------------gccactat
cggcccacataatccaagacatggtgtgcttt--atccgaagctaggcattagttgccgg
ttcttgaatctctagcatgcgggagctattctcagttcgccagataaccagaaggctcgc
atgcatccggtctatctttactgtgatttc------tccaactcgtaagctgc-------
------------------------------------------gtaagaaggc--------
-----------------cctacctgactttcataaggctagacatgaaccg---------
------------------------gacctcaaggtagacagaatgtaaaatgtattgttt
caagaactagtcttatccaacctccgcgttgccaaatcgtctccagaatcatttagacct
gaacgtcgctgtggggatgtccaacagtttaattctgagtc-------------------
----------------gacgcttcaggagcaacatgaaacgtgtccggaccgtcgagggc
acgtcttgtcattcgcgaact---------------------------------------
------------ttacgcaattccgacttcatctggggcataatattggtcacgcacact
ctcagataccgtttgcaccaaacgatcgcgaattttgtcggcacctcacatcctttacgg
gggatcctctcactgcgacaagggtgggacacggcttcc-------------------at
aaagaggagg-gtcgaac----------------tcgtaattatatgacgaccccgttgg
atttgcgcgtc----gacagtagttgtaggtcctaaccgaacgccatgcgg---ggtaaa
tcagctgtgaagtgaaccacggcactcgtataatatctgacgctg-------
>SEQ14
---atgtaatttagcaaacgcgatgtgtgttagaggcttacgcagtggccgctataggag
caa---------------------------------------------------------
------------------------------------------------------------
----------------------------------ttccgaagctaggcataagttgcctg
ttcttgaatctctagcaggcgggagttattctcagtgcgccagatacccagaagaatcgc
atgcatccggtatatc-----------------------ggtgcaagaataatcaacccg
------------------------------------------------------------
------------------------cgtctccgtacagctaaaagtatgtta---------
----------------------------------tagacagaatgttaaatgtattattt
caaggactagtcttatccaacctccgcgttgccaaatcgtctccagaatcatttagacct
gaacgtcgctgtgggcattgccagcagcctattcaaacggaggaggctcagagttgtcgc
agccctggctatccgggacgcttccggaccaacctgcaaagtgtccgga-----------
------tgacactcgcgatat----------------ttgg-------------------
--------tgaacttcgccgttccgactacatcaggggcagaaacttggtcacgcacact
ctcagataccgtttgcaccaaacgatcgcgaattttgtcggcacctcacatcctttacgg
gggatcctctcactgcgacaagggtgtga-------------------------------
-----ggaggtgctaa---------------ggcccgtaatggttcgtcagc--------
---------------gacagtatgtgtggctagtaacctaactcgatccgg---ggtaaa
gcagctttcatgcgcaccacatcactggtctcagatcagtcgatttcccgct
>SEQ15
--------------------------------------gacgcaaggctgactagagttg
atc--------------------------------gtgtccggctcctgaaatta-----
----------cttgctacaat---------------------------ccttcagct---
----------------------------------atccgaagctaggcattagttgccgg
ttcttgaatctctagcatgcgggagctattctcagttcgccagataaccagaaggctcgc
atgcatccggtctatctatactttcatttccgagggttcgacg-----------------
--------------------------gcagctcgtaagctgagt----------------
----------------------------ttcctatggatagacattaaccg---------
-------------------------------gggtagacagaatgttaaatgtattattt
caagaaatagtcttatccaacctccgcgttgccaaatcgtctccagaatcatttaaacct
gaacgtcgctgtggggctggc---------------------------------------
----------------cacgtttgaggaggaaca--------------------------
acgtttaaccattcgcacacg----------------tcgg----------cctc-----
-------------tacgcaattcctacatcttttggggca-----ttggtcacgcacact
ctcagataccgtttgcaccaaacgatcgcgaattttgtcggcacctcacatcctttacgg
gggatcctctcactgcgacaagggtggcacacg---------------------------
-----------gcaaattccctagtgacaac-----------------------------
----------c----gacagtagtagtagctagtaaccgtactcgatgcgg---ggtaaa
gcagctgtaaagcgaacctggtcactggtataatagcagtcgataccccgcg
>SEQ16
--------------gagagatgtaggagccgagcagcacgcgca----------------
---------------------ttttccaatacttagggtccagctcatggaatta-----
------------------------------------------------cttg--------
-----------ctataggttccgaatcctccc--ctccgaagctaggcattagttgcctg
ttcttgaatctctagcaggcgggagttattctcggttcgccagataaccagaagactcgc
atgcatccggtctatctttattgtgatttccgagggctcaacggg---------------
----------------------------agctagtaagctgggtaagaaagt--------
-----------------c----------ttcctagcgctagacatgaacgg---------
------------------------a-------ggtagacagaatgttaaatgtattattt
caggaactagtcttatccaacctccgcgttgccaaatcgtctcgagaatcatttaaacct
gaacgtcgctgtggggatggcctgcggcct------------------------------
----------------attcaatggggggaggctcagagatgtc----------------
--------gcagccctggact----------------tcaggcgcgaattcgcga-----
-------------atcaagagtccgactacatcaggggcaggaaattggtcacgcacact
ctcagataccgtttgcaccaaacgatcgcgaattttgtcggcacctcacatcctttacgg
gggatcctctcactgcgacaagggtggga-------------------------------
-----gggggtgctaattcacgagtggggataaa--------------------------
----------c----gacagtattagtggctcgtaaccgatctcgatccgg---agtaaa
gcagctgtaaagtgcaccacag-------------------aatttcccgcg
>SEQ17
--------------------------------------gacgcaacgcgtgctagagttg
atc------------------tggtgctatacttagggtcaagctcctgatatta-----
----------cttgctatagt---------------------------ccttcagatctt
ccgtttgcga-atctttgacatatt---------atccgaagctaggcattaggtgccgg
ttcttgaatctctagcatgcgggagttattctcagttcgccagataaccagaaggctcgc
atgcatccggtctatctttactgtgaattgcg-------------------atcaggtct
--------------------------ccacctactaagctgcgtaagaaggt--------
-----------------cctagctgactt-------------------------------
--------------------tgttaatctaaaggtagacagaatgttaaatgtattattt
caagaactagtcttatccaacctccgcgttgccaaatcgtctccagaatcatttagacct
gaacgtcgctgtggggatggcccatgagtt------------------------------
----------------tacgcttggggaggaacatg------------------------
-------------------------------------acga----------ctta-----
-------------tacgcatttcc---------------atagaattggtcacgcacact
ctcagataccgtttgcaccaaacgatcacgaattttgtcggcacctcacatcctttacgg
gggatcctctcactgcgacaagggtcgcacacggccgcccgtactgatacacccgctatg
aaatctgggctgccaattgcctagtcaagatatcccgta---------------------
------------------attacttgtagctagtaaccgac-------------------
---------aagcgaacca---------------------------cccgcg
>SEQ18
-------------------------------gacagatcgctcaacggtggctagagttg
ttccaatgtctgcacgcaacattggccgatacttagagtccagctcatgaaattaatggg
acgtataagccgcactata-------------------------------------cccg
ccgcttccga-atccatgcaagat----------atccgaagctaggcattagttgcctg
ttcttgaatctctagcaggcgggagttattctcagtccgccagataaccagaagactcgc
atgcatccggtctatctttaacatgatttacgagggctcaaaaggtgaagaatcagcttt
--------------------------caaactagtaagctgcgtaaga------------
----------------------------tgcatagggctagacatgatccc---------
----------------atgatgaaaatttaaatgtagacagaatgttaaatgtattattt
caagaactagtcttatccaacctccgcgttgccaaatcgtctccagaatcatttaaacct
gaacgtcgcagtggggatggccatgagtc-------------------------------
----------------tacgcttgaggagcaacatgcaaaatgtccgg------------
-------------cgtgcact---------------------------------------
------------ttacgcaattccgactacttcgtgggcatagaattggtcacgcacact
ctcagataccgtttgcaccaaacgatcgcgaatattgtcggcacctcacatcctttacga
gggatcctctcactgcgacaagggtgggacac------------------accggcaata
gagtcggaggtgccaattccctagtcgggagaccccgtaattatatgaagacgccgttgg
acctgccactc----gacagt----------------------cgaagaga---ggtaaa
gcagcggtaaagtgaaccacagcgctggtataatagctgtcgatccctcgcg
>SEQ19
-----------------------------gaggca--------a----------------
---------------------tggtccactacttagtgtccagctcctgaaatta-----
------------------------------------------------ccttcaggactt
ccgcttgcgc-atccatgacagg-------tt--atccgaaggtaggcattagttgcctg
ttcttgaatctctagcaggcggaagttattctcagttcgccagataacgagaagactcgc
atgcatccggtctatctttccggtgctttccgagggttcagaggttgaactatgaggtct
--------------------------gcagcgagtaagattcatacgcaggt--------
-----------------cctaactaattttcatcgggctagacatgacccc---------
------------------------gatctaaaggtagacagaatgttaaatgtattattt
caagaaatagtcttatccaacctccgcgttgccaaatcgtctccagaatcatttaaacct
gaacgtcgctgtggggatggccatgga---------------------------------
-----------------gc---------------------------agtccggcgagagc
aaggctagaaattcgcgcact----------------tcgg----------cgtg-----
-------------tactcaat------------------------ttggtcacgcacact
ctcagataccgtttgcaccaaacgatcgcgaattttgtcggcacctcacatcctttacgg
gggatcctctcactgcgacaagggtgtga-------------------------------
----------------------agtggcgataaagcgtaatgatacgacagc--------
----------c----gacagtatgg-----------------tcgtaccgg---cgttac
ccagctgtattgcgcaccacagcactcgtacgagagctgtcgatgtccc---
