>SEQ0
ttacctgggaaatagccataaaccaaacatctgcccgtccatggcacacgagacatcatg
cgtagtcgagattacggtatcaccatagcactctggtcaaggagtcaccacctacaaccg
tatatcccggtgaacctacactcaagtgcgtaaggcaaatgacatcctatcgttaactca
atcgttatctttagctttgccaaccaagatataatagaagagcgttgagatcatcgtggg
ccctatagtggcgtctagtttgactgcctatactctgaggcacagtaccattggccctct
aagatgagcttccctaggagggattacaccggactcgttccgactgtggagtcaggtacg
gactttcgacctcatctaagcttgtttaatctcgccccggtccgcatgccatcgaagtgc
ttcagctcttctgtgtatggctcaagttcactgtcggtctgctgtgcggactcagcctgt
cttcatacttttttttcacaggaacatcatcaaagtcctggcctcagcacccgcagtcta
tgcaactaacgattccggcgagtgccgatcgttttcgaagatgcccaccgactattagga
ccctacttagacaaaataaaggttgtaatctaagtagaatgatagacggagccggtatca
ctaactcttcgtagaaaagcacttgtcgtggggagaaattgcgattatcatgatggacca
acagccgctgggcgtgactccgattcgacggttatgctcgacagtgggtctgtaccacga
ggttcgagccgggaaacgtaccatattataacgacacgattcagtggtctaaatagacga
gctctttaaccacgagcgcatctttaggaccgtaacagcgcggagagaatctgcctgata
tccatagagtactagacgcgcaaagcgccgtccgctaccctcgccttggaactgcctaac
cggtcagtgcgggtatggtggtgcccgatcatgaagaacacgagcctccgagcccgccct
tggcttacgggtagtgtgagagccttctcattaaaacggtaacttgagcgataccgatgc
cgacttgtacacgtagcgta
>SEQ1
gtacctgtgaaatagccaaaaacctaacagctgcccgtccgtggcacacgagacataatg
agtagtcgaaattacggcatcaccatagcacattggtcaaggcgtcaccacctacatccg
t-----------------------agggcgtaaggcaaaggagataatatcgttaactcg
agcgttatcttgagctttgccaaccaagatataatagaagagcgttgagatcatcgtggg
ccctatagtggcgtctagtttgactgcctatactctgaggcacagtaccattggccctct
aagatgagcttccctaggagggattacaccggact--------------agtcaagtacg
gactttcgacctcatctccgcttgtttaatatcgccccggtccgcatgacaccgaa----
---------tctgtgtatggctaaggttcactgtcggtctgctgtgcggactcagcctgt
cttcatacttttttttcacaggaacatcatcaaagtcctggcctcagcacccgcagtcta
tgcaactaacgatttcggcgagtgccgatcgttttcgaagatgcccaccgactattagga
ccctacttaga-----------------------tagaatgacagacggagcaggtatca
ctaactcttcgaagaaaagcactggtggtggggagaagttgcgattataatcatagacca
acacccgctgtgcgtgactctgattcgactgttatgctcgacagtggatctgtaccccga
ggttcgagccgggaaacgtaccatattataacgacacgattcagtggtctaaatagacga
gctctttaaccacgagcgcatctttaggaccgtaacagcgcggagagaatctgcctgata
tccagagagtcgtagtcccgcaaagcgccgtccgctacactcgccttggaactgcctaac
cggtcagtgcgagtatggtggtgcccgatcatgaaggacacgtgcctccgagcccgccct
tggcttacgggttgtctgagagccttctcattaaaccggtaacgtgagcgacacc-----
------gtacgcgtaacgta
>SEQ2
gtacctctgaaatagccaaaaacccaacagctgcccgtccgtggcacacgagacagaatg
agtagtcgaaagtacggcatcaccatagcacattgatcaaggcctcaccacctacatccg
t-----------------------a----------------------------taactcg
agcgttatcttaagctttgccaaccaagatataatagaagagcgttgagatcatcgtggg
ccctatagtggcgtctagtttgactgcctatactctgaggcacagtaccattggccct--
--------cttccccagtagggactacaccggact--------------agtcatgtacg
gactttcgatctcatctccgcttgtttaatatcgccccggt-------------------
-----------------------------------------cactgcggactcagcctgt
cttcatactttcttttcccaggaacatcatcaaagtcctggcctcagcacccgcagtcta
tgcaactaacgatttcggcgagtgccgatcgttttcgaagatgcccaccgactgttagga
ccctacttaga-----------------------tagaat--------------------
------------------------gtaatggggagacgttgcgaatataagcatagacca
acacccgctgtgcgtcgctctgattcgactgttatgctcgacagtcgat-----------
-------gtcgggaaacgtaccatattataacgacacgattcagtggtctaaatagacga
gctctttaaccacgagcgcatctttaggaccgtaacagcgcggagagaatctgcctgata
tccagaaagtcgtagtcccgcaaggcgccgtccgctacactcgccttggagctgcctaac
cggtcagatcgagtatggtgttggccggtcatgaaggacacgtgcctccgagccaggcat
tggcttacgggttgtgtgagtaccttctaattaaaccggtaacgtgagcgacacc-----
------gtacgcgtaacgta
>SEQ3
gtacctcaaaaatagccaaatacccaacagcaccccgtccgtggcacacg----------
----------------------------caccttcctcaacgcctcacaacgtgcatccg
-----------------------------------------------------taaatcg
agcgttatct----------caaccaagatataatagaagagcgttgagatcatcgtggg
ccgtatagtggcgtctagtttgactgcctatactctgaggcacagtaccattggccgtct
aagatgagattccctaggagggattacaccggactcgttccgacactggta---------
-----------------------gttcaataacgccccggtccgcatgccatcgaagtgt
ttcagctcttctgtgtatggctcaagttaactatcggtctgctgtgaggactcagcctgt
cttcatactatcttttcacaggaacatcatcaaagtcctggcctcagcacccgcagtcta
tgcaactaacgattccggcgagtgccgatcgttttcgaagatgcccaccgactattagga
gcatacttaga-----------------------tagaatgacagtcggagcaggtatct
ctaactcttcgaagataagcacttgtgctggggagaagttgcgattataaccatagaaca
acacccgctgtgcgtgcctcggattcgactgttatgctagacagtggatcggtaccccga
ggttctacccgggaaacgtcccatattataacgacacgattcaatggtctaaatagacga
gctctttaaccacgagcgcatctttaggaccgtaacagcgcggagagaatctgcctgata
tccatacagtgcgattcgcgcaa-------------accctcgccttgaatctgcctaac
ccgccagtgcgggtatggtggtgcccgatctcgaagaacacgagcctccgagcccgccct
tggtttacgggtagtgtgagagccatgtcattaaaacggtaacttgagcgagaccgatgc
gcacttgtacacgtagcgta
>SEQ4
gtacctgtgaaatagccaaaaacctaacagctgcccgtccgtggcacacgagacataatg
agtagtcgaaattacggcatcaccgtatcacattggtcaaggcgtcagcacctacatccg
gaa-------------------------------------------atatcgttaactcg
agcgttatcttgagctttgtcaaccaagatataatagaagagcgttgagatcatcgtggg
ccctatagtggcgtctagtttgactgcctatactctgaggcacagtaccattggccctct
aacatgagattccataggagggattacaccggactcgttccaacactggga---------
-----------------------gttcaataccgccccggtccgaatgccaacgaggtgt
ttcagcgcttctgtggatgactcaagttaactatcagtctgctgttaggactcagccggt
cttcatactatcttttcacaggaacatcatcaaagtcctggcctcagcacccgcagtcta
tgcaactaacgattccggcgagtgccgatcgttttcgaagatgcccaccgactattagga
ccctacttatacaaaataaaggttggaatctaagtggaatgatagacggagccggtatca
ctacctcatcgtagaaaagcacttgtagtggggagaaattgcgattatcatgagggacca
acacccgctgggcgtgactccgagtcgacggttatgctcgataatagttctgtaccacga
agttcgagcagggaaac---ccatattataacgacacgattcagtggtctaaatagacga
gctctttaaccacgagcgcatctttaggaccgttacggcgcggagagaatctgcctgata
tccagagacttgtagt----------------------acgcgccttggaactgcctaac
cggtcagtgcgagtatggtggtgcacgatcatgtaggacacgtgcctccgagc-------
-------cgggttgtcggagagcctactcatttaaccggtaaagtgagcgtcacc-----
------gtacgcgtaacgta
>SEQ5
gtatctgtgaaatagccaaaaaccgaacagctgcccgcccgtggctcacgagtcacattc
cggaa-------------------------------------------------------
----------------------------------------------atatcgttaactcg
agcgttatcttgagctttgtcaaccaagatataatagaagagcgttgagatcatcgtggg
ccctatattggcgtctagtttgactgcctatactctgaggcacagtaccattggccctct
aagatgagcgtccctaggagggattgcaccggactcgttcagactgtggagtcagatacg
gactttcgac-----------------gatctcgccccggcctgcatgctgtcgaagtgc
ttcagctcttct----------------------cgatctgctgtgcggactcagcctgt
cttcatacttttttttcacaggaacatcatcaaagtcctggcctcagcacccgcagtcta
tgcaactaacgattccggcgagtgccgatcgttttcgaagatgcccaccgactattagga
cccgacttaga-----------------------tagaat--------------------
------------------------ataatgtggaaaggttgcgaatatcagcatagac--
----------------------attcgcctgttgtgctcgacag----------------
---------cgggaaacgtaccatattataacgacacgattcagtggtctaaatagacga
gctctttaaccacgagcgcatctttaggaccgtaacagcgcggagagaatctgcctgata
tacatagagtccta------------------------cctcgccttggaactccgtatc
cggtcagtgcggctatggtggtgcccgatcatgaagaacacgagcctccgagcctgccct
tggcttacgggtagtgtcagagccttctcattgaaatggtgacttgagcg----------
------atacacgtagcgta
>SEQ6
gtatctgcgaaatagccgaaaaccgaacagcc----------------------------
------------------------------------------------------------
------------------------------------------------------------
-ggattatcttgaactttgtcaaccaagatataatagaagagcgttgagatcatcgtggg
ccctatagtggcgtctagtttgactgcctatactctgaggcacagtaccattggccctct
aggatgagattccctaggagggattacaccgggctcattcagacactggta---------
-----------------------gttcaataagg----------------atcgcagtgt
ttcagctcttctgtgtatggctcaagttaactatcggtctg-------------------
---------atcttttcacaggaacatcatcaaagtcctggcctcatcacccgcagtcta
tgcaactaacgattccggcgagcgccgatcgttttcgaagatgcccaccgactattagga
ccctacttaaa-----------------------tagcat--------------------
------------------------gtaatggggagacgttgcgaatatgagcatagacca
acacccgctgtgcgtcgctctg-----------acactcgatgtccg-------------
-----------------gtaccatattataacgacacgattcagtggtctaaatagacga
gctctttaaccacgagcgcatctttaggaccgtaacagcgcggagagaatctgcctgata
tccacagattcgtagtcactcatggcgccgtccgctacactcgccttggaactgcctaac
cggtcagtgcgagtacggtggtgcccgatcatgacggacacgtgcctcccagcccgccct
tcgcttacgggtggtctgagaaccatctcattaatccggtaacgggagtgacacc-----
------gtacgcgtaacgta
>SEQ7
gtacctttgaaatagccaaaaacctaacagctgcccgtccgtggcacatgagacataatg
agtagtcaaaattacggaatcaccatagcacattggtcaaggtgtcaccac---------
----------------------------------------------ctgggcgtaaggca
aacgttatctgcagctttgccaaccaagatataatagaagagcgttgagatcatcgtggg
ccctatagtggcgtctagtttgactgcctatactctgaggcacagtaccattggccctct
aagatgagatgtcctcggcgggattccaccggcctcgttccgtcactgatt---------
-----------------------gttcaaaaacaccccggtccgcttgccatcgaatagt
g--------------------------------------------gcggactcagccagc
cttcatactatcttttcacaggaacatcatcaaagtcctggcctcagcacccgcagtcta
tgcaactaacgatttcggcgagtgccgatcgttttcgaagatgcccaccgactgttagga
gca-------------------------------tagcatgacagtcggagcaagtagct
ctaactcttcgaagaaacgcgcttgtcctggggagaagttgtgaatataaccatag----
-----------gcgtgcctcggactcgactgttatgctaaacagtggatcgggccaccga
gtttgtacacgggaaatgtcccatattataacgacacgattcagtggtctaaatagacga
gctctttaaccacgagcgcatctttaggaccgtaacagcgcggagagaatctgcctgata
ttcagagaattgtagt------------------------------------------ac
cggtctgtgcgagtatgggggtgcacgatcatgtag------------------------
-------cgggttgtcagagagcctactcatttaa-------------------------
--------------------
>SEQ8
gtacctttgcaaaagccaaaaacctaaccgctgcccgtccgtggcacatgagacataatg
agtagtcaagctcaaggtgtcaccac----------------------------------
----------------------------------------------ctgggcgtaaggga
tacgttatctgcaactttg-caaccaagatataatagaagagcgttgagatcatcgtggg
ccgtatagtggcgtctagtttgactgcctatactctgaggcacagtaccattggccgtct
acgacgagcttccctaggagggattaaaccggact--------------agtccaatacg
gactttcgatctcatctccgcttgtttaatatcgccccggtccgcatgaaaccgaa----
---------tctgtggacggctaaggtgcactgtcggtctgctgtccggactcagcctgt
cttcatacttttttttcacaggaacatcatcaaagtcctggcctcatcacccgcagtcta
tgcaactaacgattccggcgagcgccgatcgttttcgaagatgcccaccgactattagga
cccgagtgggg-----------------------tagaat--------------------
------------------------ataatgtggaaaggtagcgaatctcaccatagacc-
-----------------------ttcgcctgttgtgctctacag----------------
--------------------ccatattataacgacacgattcagtggtctaaatagacga
gctctttaaccacgagcgcagctttaggaccgttacggcgcggagagaatctgcctgata
tccagagagtaatagttccgcaaag-------------------------actgcctaac
cag---------------------------atgaaggac-------------cccgccct
tggcttgcgggttgtctgagagccttctcattaaaccggta-------------------
------aaacgggtaacgta
>SEQ9
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------gcatcagccggatcaaccaagatataatagaagagcgttgagatcatcgtggg
ccctatagtggcgtctagtttgactgcctatactctgaggcacagtaccattggccctct
aagatgagattccttaggagggattacaccggactcgttccgacgctggtt---------
-----------------------gttcaataacgccccggtccgcttgccattgaagtgt
ttcagctcttccgtgtatggcccaagttaactatggttctggtgtgaggactcagcctgt
ttttatacaatcttgtcaaaggaacatcatcaaagtcctggcctcagcacccgcagtcta
tgcaactaacgattccggcgagtgccgatcgttttcgaagatgcccagcgactattagga
ccctgct-----------------------------------------------------
--------------------------aatggggagacgttgcgaatatgagaatagacca
a--------------------------------acactcgatgcccg-------------
-----------------gtaccatattataacgacacgattcagtggtctaaatagacga
gctctttaaccacgagcgcatctttaggaccgtaacagcgcggagagaatttgcctgata
aacacag-------------------------------tctcggcttggagctccgtatc
aggtcagtgcggctatggtggtacccgatcgtgaagaacacgagccaccaagcc------
---------------gtcagagccttctcattgaaatgctgacttgatcg----------
------ctacacgtaacgta
>SEQ10
ggtcctttgaaatagccaaaaacctaacagatgcccg--------------------atg
aatagacaaaattacggaatcaccatagcacattggtcaaggtgtcaccacctcg-----
-----------------------------------------------------taaggca
aacgtcatctgcagctttgccaaccaagatataatagaagagcgttgagatcatcgtggg
ccctatagtggcgtctagtttgactgcctatattctgaggcacagtaccattggccctct
aagatgaaattccctaggacggattacacctgactcgttccgccactggta---------
-----------------------gctcaataacgccccggtctgcatgccatcgaagtgt
ttcatctcttc---------------------atcggtctgctatgaggactcagccggt
cttcatactatcttctcacaggaacatcatcaaagtcctggcctcagcacccgcagtcta
tgcaactaacgatttcggcgagtgccgatcgttttcgaagatgcccaccgactgttagga
cccgagtgggg-----------------------tagaat--------------------
---------------------------aggcggaaaggtagcgaatctcaccatagacc-
-----------------------ttcgctagtcgtgctctacag----------------
--------------------ccatattataacgacacgattcagtggtctaaatagacga
gctctttaaccacgagcgcatctttaggaccgtaacagcgcggagagaatctgcctgata
tccatagagtactagacgcgcaaagcgccgtccgctaccctcgccttggaactgcctatc
gggtgagtgcgggtatggtggtggccgatcatgaagaacacgagcctccgagcccgccct
tggcttacgggtagtgtgagagccttctcattaaaccggtaacttgagggataccgatgc
cgacttgtacacgtagcgta
>SEQ11
ggatctgtgaaatagccgaaaaccggatagcc----------------------------
------------------------------------------------------------
------------------------------------------------------------
-cgattatcttgaactttgtcaaccaagatataatagaagagcgttgagatcatcgtggg
ccctatagtggcgtctagtttgactgcctatactctgaggcacagtaccattggccctct
aacatgagcttccctaggagggattacaacggactcgttccgactgtggtgtcaggtgcg
gacttccgacctcaactaagcttgttgaatttcgcccc----------------------
--------ttctgtgtatggctcaagttcactgtcggtctgctgtgcggactcagcctgt
cttcatcctttattttcacaggaacctcatcaaagtcctggcctcagcacccgcagtcta
tgcaactaacgattccggcgagtgccgatcgttttcgaagatgcccaccgactattagga
ccctacttatcctcaataaaggttgaaatcaaagtggaatgatagat-------------
-------------gaacagcacttgtagtggggagaaattgggattatcatgagggagca
acacccgctgggc--------------------gtgatcgttaatagttctttaccacga
agttcgagcagggaaac---ccatattataacgacacgattcagtggtctaaatagacga
gctctttaaccacgagcgcatctttaggaccgtaacagcgcggagagaatctgcctgata
tccagagagtaatagttccccaagg-------------------------actgcctaac
cag---------------------------atgaaggacacg-------------gccct
tggcttgcgggttgtctgagagccctctcattaaaccggta-------------------
------caacgggttacgta
>SEQ12
gtacctttgcaaaagccaaaaacctaacggctgcccgactgtggcacatgagacataata
ggtagtcaagctcaaggtgtcaccac----------------------------------
----------------------------------------------ctggacgtaagtga
tacgttagctgcaactgtg-caaccaagatataatagaagagcgttgagatcatcgtggg
ccgtatagtggcgtctagtttgactgcctatactctgaggcacagtaccattggccgtct
aggatgagattccctaggagggattacaccgggctcattcacacactggta---------
-----------------------gttcgataaag--------------------------
---------atcgcgtatggctcaagttaaatatcggtctg-------------------
-----------------acaggaacatcatcaaagtcctggcctcatcacccgcagtcta
tgcaactaacgattccggcgagcgccgatcgttttcgaagatgcccaccgactattagga
cccgagtgggg-----------------------tagaat--------------------
---------------------------aggcgaaaaggtagcgtatctcgccatagaac-
----------------------------------ttcgctacag----------------
--------------------ccatattataacgacacgattcaatggtctaaatagacga
gctctttaaccacgagcgcatctttaggaccgtaacagcgcggagagaatctgcctgata
cacatagagtccta------------------------cctcgccttggaactccgtatc
agt--------------------------------gcacactagcctccgagcctgccct
tggctttcgggtagtgtcggagccttctcattgaaatg----------------------
------gtacacgtggcgta
>SEQ13
gcatctttgaaatagccaaaaaccgaacagctgcccgcccgtggctcacgagtcacattc
cgca--------------------------------------------------------
------------------------------------------------------------
-gcgttatcttgaactt---caaccaagatataatagaagagcgttgagatcatcgtggg
ccctatagtggcgtgtagtttgactgcctatactctgaggcacagtactattggccctct
aacataagattccctagga------------------------ctgtcgtgtcaggtgcg
gacttccgacgtcaactaagcttgttgaatttcgcccc----------------------
--------ttctgtgtatggctccagttcac-----------------------------
-----tccttgattttcacaggaacctcatcaaagtcctggcctcagcacccgcagtcta
tgcaactaacgattc-----agtgccgatcgttttcgaagatgcccaccgactattagga
ccctacttagacaaaataaaggttgttatttaagtagaatgatagacggagccggtgaca
ctaactcttcgcggaaaagcacttgtcgtgggcagacattgcgattatcatgatggacca
acagccgctgggcgtgactccgattcggctgt---------------------accacga
ggttcgagccgggaaa----ccatattataacgacacgattcagtggtctaaatagacga
gctctttaaccacgagcgcatctttaggaccgtaacagcgcggagagaatctgcctgata
ttcagagaattgta----------------------------------------------
--------------------------gatgatgtgg------------------------
-------------gtcagagagccgacttatttaa-------------------------
--------------------
>SEQ14
ggatctgtgaaatagccgaaaaccggatagcc----------------------------
------------------------------------------------------------
------------------------------------------------------------
-------cgagaaacattgtaaaccaagatataataaaagagcgttgagatcatcgtggg
ccctatagtggcgtctagtttgactgcctatactctgaggcacagtaccattggccctct
acgacgagcttccctaggagggattaaagcggact--------------agtccaatacg
gactttcgatctcatctccgcttgtttaatatcgccgtggtccgcatgaaaccgta----
-------------------------------tgtcgttctgctgtgcgaactcagagtgt
cttcatacatttttttcacaggaacatcatcaaagtcctggcctcagcacccgcagtcta
tgcaactaacgattccggcgagtgccgatcgttttcgaagatgcccaccgactattagga
ccctagttaga-----------------------tagaat--------------------
------------------------gtagtggggaaacgttgcgaatctaagcatagacct
acacccggtgtccgtcgctctgatacgacttcaatgctcgaccg----------------
-------------------gccatattataacgacacgattcagtggtctaaatagacga
gctctttaaccacgagcgcatctttaggaccgtaacagcgcggagagaatctgcctgata
acgagaaagtcgtcgtcccggaaggtgccgtccgctacactcgccttggagctgactaac
cggtcaggtcgagtatggtgttggccggtcatgaaggacacgtgcctccgagctaggtat
tggcttacgggttgtgtgtg-------------------taacgggagcgaaacc-----
------gtacgcgaaacata
>SEQ15
gtacctgtcaaatagccaaaaacctaacagctgcccgtccgtggcatacgagacacaatg
agtagtcgaaattacaggggtcaccacctaaatccgt-----------------------
------------------------agggcgtaaggcaaaggagataatatcgttaactcg
agcgttatcttgagctttaccaaccaagatataatagaagagcgttgagatcatcgtggg
ccgtatagtggggtctagtttgactgcctatactctgaggcacagtccccttggccgtct
aatctgagatgtcctcagtgggaatccaccggcctcgtgccgtcactgatt---------
-----------------------gttcaaaaacaccccaa--------------------
-----------------------------------------cagtgttgactcacctagc
cttcatactatc--------ggaacatcatcaaagtcctggcctcagcacccgcagtcta
tgcaactaacgattccggcgagtgccgatcgttttcgaagatgcccaccgactattagga
cccgtgtgggg-----------------------tagaat--------------------
----------------------------agcgaaatggtagcgtatctcgcgatcgatct
tca---------------------------------------------------------
--------------------ccatattataacgacacgattcagtggtctaaatagacga
gctctttaaccacgagcgcatctttaggaccgtaacagcgcggagagaatcggcctgata
tg--------------------------------------tcggcttggtgctccgtatc
aggtcagtgcggctatggtggtagccgagcgtgaaaaacacgagccaactagcc------
---------------------------------------tgacttgatcg----------
------ctacacgtcacgaa
>SEQ16
ttacctcaaaaatagccaaagtcccaacagcaccccgtccgtggcac-------------
------------------------------------------------------------
------------------------------------------------------caatcg
agcaatatct----------caaccaagatataatagaagagcgttgagatcatcgtggg
ccctatagtggcgtctagtttgactgcctatactctgaggcacagtaccattggccctct
aacctaagattccctagcagg-----------------------------------ttcg
gacttccgaagtcaactacgcttgttgaagttcgcccc----------------------
--------ttctgtgtatggctccagtttac-----------------------------
-----tccttgattttcccaggaacatcatcaaagtcctggcctcatcaccctcagtcta
tgcaactaacgattccggcgagcgccgatcgttttcgaagatgcccaccgactattagga
cacgtgtggga-------------------------------------------------
-----------------------------gcgaaagggtagcgtatctcgcgatcgatct
aca---------------------------------------------------------
--------------------ccatattataacgacacgattcaatggtctaaatagacga
gctctttaaccacgagcgcatctttaggaccgtaacagcgcggagagaatctgcctgata
tacaaacggtccta------------------------cctcgccttggaactccgtatc
cggtcagtgcggctatggtggtgcccgatcattaag----------------cctgtcct
tggcctacgggtagtgtcag-------------------tgacttgagcg----------
------atacacgtagggta
>SEQ17
gtacctttgcaaaagccaaaaacctaaccacttcccgtccgtggtacatgagacataatg
agtagtcaagctcaaggtgtc---------------------------------------
-----------------------------------------------------taaggga
tagattatctgcaactttg-caaccaagatataatagaagagcgttgagatcatcgtggg
ccctatagtggcgtctagtttgactgcctatactctgaggcacagtaccattggccctct
aatctgagatgtcctctgtggga-------------------------------------
-------------atcactgattgttcaaaaacactccaa--------------------
-----------------------------------------cagtgttgactcacgtaga
cttcatattatc--------ggaacatcatcaaagtcctggcctcatcacccgcagtcta
tgcaactcacgattccggcgagcgccgatcgttttcgaagatgcccaccgactattagga
ccctacttatatgaaataaaggtggtaatctaagtggaatgatagacggcgccggtagca
ctacctcatcgtagaaaagcacttgtagtggggagaaattgcgattaccatgagggacca
agacccgctgggcgtgactccgagtcaacggttatgctcgataatagttctgtacctcgg
agt-----------------ccatattataacgacacgattcagtggtctaaatagacga
gctctttaaccacgagcgcatctttaggaccgtaacagcgcggagagaatctgcctgata
tccatagagtacgagacgcgcaaagcgccgtccactacactcgcactggacctgcctaaa
ccgtcagtgcgggtctggtggtgcccgatcgtgaa--------------------gccct
tggcttacgggtagtgtgagagccttctcattaaaacggtaacttgttcgataccgatgc
cgacttgtacacgtagcgta
>SEQ18
gaatctttgaaatagccaaaagccgaacagctgtccgcacgtggctcacgag--------
------------------------------------------------------------
------------------------------------------------------------
-tcactttccgcagcattgtcaaccaagatataatagaagagcgttgagatcatcgtggg
ccctatagtggcgtctagtttgactgcctatactctgaggcacagtaccattggccctct
aggatgagattccctaggagggaatactccgtgctcattcacacactggta---------
-------------------gttcgataaaaatcgccaag---------------------
------------------------------------------------------------
-----------------acaggaacatcatcaaagtcctggcctcatcacccgcagtcta
tgcaactaacgattccggcgagcgccgatcgttttcgaagatgcccaccgactattagga
ccctacttatcctcaataagagat------------------------------------
-------------gaacagaacttctagtggggaga------------------aaagca
aca----------------------------------tcgtttatagttatttaccacga
agtacgagcagggaaac---ccatattataacgacacgattcagtggtctaaatagacga
gctctttaaccacgagcgcatctttaagaccgtaacagcgaggagagaatctgcctgata
tccagaaagtcgtagtcccgcaaggcgccgtccgctacactccccatgcagctgcctaac
cggtccgatcgagtatggtgttggccggtcatgaaggacccgtgcctccgagccag----
----ttacgggttgagtgagcaccttcaaattaaaccggtaacgtgagcgaaacc-----
------ggacgcgtaacgt-
>SEQ19
ggatctgtcaaatagtcgaaacccggatagct----------------------------
------------------------------------------------------------
------------------------------------------------------------
-cgattatcgtgaactttgtcaaccaagatataatagaagaacgttgagatcatcgtggg
ccctatagtggcgtctagtttgactgcctatactctgaggcacagtaccattggccctct
acgacgagcttccctatgagggattaaaccggaca--------------agtgcaatagg
gactttcgatctcatctccgcttgtttaatatcgccccggtccgtatgca----------
---------tctgtggacggctaatgtgcactgtccgtctgctgtccggactcaggctgt
cttcatactttttttgcacaggaacatcatcaaagtcctggcctcagcacccgcagtcta
tgcaactaacgatttcggcgagtgccgatcgtgttcgaagatgcccaccgactattagga
cccgacttaga-----------------------tagaat--------------------
------------------------------------------------------------
---------------------------atgatcctgctcgacag----------------
---------cgggaaatataccatattataacgacacgattcagtggtctaaatagacga
gctctttaaccacgagcgcatctttaggaccgtaacagcgcggagagaatctgcctgata
tccagaaggtcgttgtcacgcaaggcgccatccgctacactcgccatggagctgcctaac
cggtcagatcgattgttctgttggccggtcattaaggacacgcgcctcagagccaggcat
tggcttacgggttgtgtgagtaccttctaattaaaccggtaacgtgagcgacaccg----
--------------------
