>SEQ0
ggcttgcactgcaatctttcttacctctgaccgcggagagcggacctcctctcgtaatct
gtcaagcgctcttgtgattcgaccccaatcgtggtggaactcaactctcttaggctagag
gaatagactattatggatacgacggacgcgttttcaacggtggtagattcgtgacgtgac
tggatctatggagtataaattagtgtgatgttggccgacgagcagtagcacccggtactc
gccactccctcggaaatccacatctagatgtcgctactagtttatactacgagcgtcacg
ggacgcggaacgctaaaaccctcaaacctaacgggctccctgcagtaacacctatcacgg
ctactccgggaggctggggtactgaaatcgcaagaatggctgctttcatttaaagttaat
cggcggttgaatcatgtgtcttttaaaaagacggacgactagggtagcagcgccacgata
ttaccgccggagggcggtagcagaaccgatcaagctgcagggatcaaacagatttcctga
ttccagcggatccgccctctagaggcttttactttcgccaacccatcttcccttcgatgg
gattttacttcaaagaacctggcagctacaagcccatttaccatgaggggtgtttcatag
gtccctcctccaggcccaggcgaactctggaggtgccgtagcctggctatatgccttaat
ccgttattcggcgaaagtggaccgtgtggttttgatgttctgccgggacaggggtcaacg
gtaaagtatcccggcgagtgaaatacctacggggcggctcctaatctgctcgagacgaca
cagcaccaatcggatggaaaccccacatgctttcgggacctcccgaacccacaaggttct
tcagacgtgaaactccgggttccgtaactttcgatgatctgcgcagctcggtatggtcca
cgggcagataggccgtacggcctcaaagtctctcaacttcttagatcaagataagtcttc
gcgttctactatcgcaattccgtgcggacgtgagtcctgtacccttttcgcagagacata
gtcccagccgcggccagtca
>SEQ1
ggcttgcactgcaatatttcttacctctgaccgcggagagc-------------------
--caagcgctcttttgattcgaccccaatcgttttggaactaaactctcttaggctagag
gaagtgactattattgatacgacggatgcgttttcaacgggggtagattcgtgacgtggc
tggatctatggagtataaattagtgtgatgttggccgacgagcagtagcacccggtactc
gccactccctcggaaatccacatctagatgtcgctactagtttatactacgagcgtcacg
gg-----------------------------------ccctgcagtaacacctatcacgg
gtactccgggaggctggggaacggacatcgcaagaatggctgattccatttaaatttaat
cggcggttgaatcatgt-------------------------ggcaggagcgccacgata
ttaccggcggagggcggtagcagaaccgatcatgctgcagggatcaaacagatttcctga
ttccagcggatccgccctctagaggcttttactatcgccaacccatcttcccttcgatgg
gaatttacttcaaagtactgggcagct---------------------ggtgtttcatag
gttcctcctccaggccca---------------tgccgtagcctggctatatgccttaat
ccgttattcggccaaagt-----------------------------------------g
gcaaagtatcctggcgagtgaaatacctacggggccgctcctaatctgctcgagacgaca
cagcaccaatcggatggataccccacatgctttcgggacctcccgaacccacaaggttct
tcagaagtgaaactcggaggtccgtaactttcattgatctgcgc----------------
-------atcggccgta-----------------------------------aagtcttc
gcgttctactatcggaattgcgagcggacgtgggtcctgtacccttttcgcagagacata
gtccaagctaaggccagtca
>SEQ2
---------------------gcctcctgaccgcggagagg-------------------
--caagcgctcttttgattcgagcataatcgttttggaact------------------g
gaagtgacttttattgatacgacggacgcgttttcaatgggggtagattcgttacgtggc
tggatctatcgagtattaattagtgtgatgttggccgacgagcagtagcacccggtactc
gccactccctcggaaatccacatctagatgtcgctactagtttatactacgagcgtcacg
gg-----------------------------------c---------------------g
gtactccggggggctggggaacggacaacgcaagaatggctgattccatttaaattaaat
cggcggttgaatcttgt-------------------------ggcgagagcgccaccata
ttaccggcggagcgcggtagcagaaccgatcaagctgcagggatcaaacagatttcctga
ttccagcggacccgccctctagaggcttttactttcgccaacccatcttcccttcgatgg
gaatttacttcaaagtgctggggagct---------------------ggtgttgcatag
gttcctcctccaggccca---------------tgccgtagcctggctataagccttaat
ccgtaattcggcctaagt-----------------------------------------g
gcaaagtatcctcgcgagtgaaatacctacggggccgctcctaatctgctcgagacgaca
cagcaccaatcggatggataccccacatgctttcgggacctcccgaacccacaaggttct
---------------------------------------tgcgc----------------
-------atcggctgta-----------------------------------aagtctta
gcgttctactatcggaattgcgagcggacgtgggttctggacccttttcgtagagacata
gtccaagctaaggccagcca
>SEQ3
cgattgcactgcaatatttcttacctctgatcgcggagagc-------------------
--caagcgctcttttgattcg-----------------------------------cgag
gaagtaactattattgatacgacggatgcgtcttcaatgggggtagattcgttacgtagg
tggatctatggagtataaattagtgtgatgttggccgacgagcagtagcacccggtactc
gccactccctcggaaatccacatctagatgtcgctactagtttatactacgagcgtcacg
gg-----------------------------------ccctgcagtaacacctatcaagg
gtaccccgggaggatggggaacggacatcgcaagaatggctgatcccacttaaatt----
---------aatcatgt-------------------------ggcaggagcgccacgcta
ttaccggcggagggcggtagcagaaccgatcaagcttcagggatcaaacagatttcctga
gtccagcggacccgccctctagaggcttttactttcgccaaaccatcttcccttcgatgg
gattttacttcaaagaacctggcagttacaagcctatttaccatgaggggtgtttcatag
gtccctccgccgggccccggaaaactctggaggtgccgtggactggctaaatgcc-----
------------------ggaccgtgtggttttgatgttctggcgggacaggggtcaacg
gtaaagtatcccggcgagtgaaatacctacggggcggctcctaatctgctcgagacgaca
cagcaccaatcggatgcaaaccccacatgctttcgggacctcccgaacccacaaggttct
gcagacctgaaactccgggttccttaactttcgatgatcagcgcacctcggtatggtcca
cgagcagataggccgttcagcctcaaagtcactcaacttctaagatcaagataagtctac
gcgttctactatcgcaaatccgtgcggacgtgagtcctgt--------------------
-tcacagccgcggccagtca
>SEQ4
------------------------------------------------------------
----ggctcgcactccaggcgccctcaatcgtttcggaactaaactctcttaggctagag
gaagtgactattattg------------------caacggaggtagatttgtgacgtggc
tggatctatggcgtataaattagtgtgattttggccgacgagcagtagcacccggtactc
gccactccctcggaaatccacatctagatgtcgctactagtttatactacgagcgtcacg
gg-----------------------------------ccatacagtaacacctatcacgg
gtactccgggaggc--------------------aatggctgattccattcacatttaat
cgaccgttgaatcatgt-------------------------------------------
--gcgggcggagggcggttgcagaaccgttcatgctgcagggatcaaacagatttcctga
ttccagcggatccgccctctagaggcttttactatcgccaacccatcttcccttcgatgg
gagtttacttcaaagtgctggggagct---------------------ggttttgcaatg
gttcctcctccaggccca---------------tgccgtagcctgacagccta-------
------------------------------------------------------------
-------------------aaaatacctacggggccgctcctaatctgctcgagacgaca
cagcaccaatcggatggataccccacatgctttcgggacctcccgaacccacaaggttct
gcagacctgaccctccgaggtccttaactttcgatgaacagcgcacctcg----------
----cagataggccgttccgcctcaca---------------------------------
---------------------------------------------------------atg
ttcacagccgcggccattca
>SEQ5
--------------------------------------agc-------------------
------------ttgcactcgacctcaatcgtttaggaactaaacgctcttaggctagag
gaagtgactattattgcaac----------------------------------------
-ggagctatggcgtatcaattagtgtgattttggccgacgagcagtagcacccggttctc
gccactccctcggaaatccacatctagatgtcgctactagtttatactacgagcgtcacg
gg--------------------------------------tacaatgacacctatcacgc
gtactccgggaggcc--------------------atggctcattcgattcacatttaat
cggctgttgaatcatgt-------------------------------------------
--gctggcggagggcggttgcagaaccgatcaagctgcagggatcaaacagatttcctga
ttccagcggacccgccctctagaggcttttactttcgccaacccatcttcccttcgatgg
gaatttacttcaaagtactgggcagtt-----------------------tgtttcatag
gttcctcctcctggctca---------------tgccgtagcctggctatatgccttaat
ccgttattcgaccaaagt-----------------------------------------g
gcaaagtatcctggcgagtgaaatacctacggggcggctcctaatctgctcgagacgaca
cagcaccaatcggatgcaaaccccacatgctttcgggacctcccgaatccacaaggttct
tcagacgtgaaactccgggttccgtaactttcgatgatctgcgctgctcggtatagtcca
cgggcagataggccgtacggcctcaaagtctctcaacttcctagatcaagataagtcttc
gcgttctactatcacaatcccgtgcggccgtg-----------------------ccata
gtctcaaccgcggccaa---
>SEQ6
ggcttgcactgcaatctttcttacgtcagaccggggagagcggacctcctctcgtagtct
gtcaagcgctcttgtgattcgaccccaatcgtggtggaactcaactatcttaggcg----
------------------acgacggacgcgttttcaacggtggtcgattcgtgacgtgac
tggatctatggaatgtaaattagtgtgattttggccgacgagcagtagcacccggtactc
gccactccctcggaaatccacatctagatgtcgctactagtttatactacgagcgtcact
gg-----------------------------------cccctcagccacacctaacacgg
gtactcacgca-------------------------------------------------
---cggttgaatcatgt-------------------------ggcaggagcgtcacgata
t----------------tagcagaaccgatcaagctgcagggatcaaacagatttcctga
ttccagcggatccgccctctagaggcttttactttcgccaacccatcttcccttcgatgg
gaatttaccgcaaagtgctgaggagct------------------------gttgcatag
gttcctcctccaggccca---------------------------------------aat
ccgtaattc--------------------------------------------------g
ccaatgtatcttcgcgagtgaaatacctacggggcggctcctaatctgctcgagacgaca
cagcaccaatcggatggaaaccccacatgctttcgggacctcccgaagccacaaggttct
gcagacctgaccctccaaggtccttaactgtcgttgaacagcgcagctcg----------
------------------------------------------------------------
--------------------------------------------------------caga
tacaatgtcgcggccattca
>SEQ7
ggctcgcact--------------------------------------------------
-ccaggcgccctcct------------------------ct---------taggctagaa
gaagtcactatt------------------attgcaacggaggtagatttgtgaagtgga
tcgatctat-----------tagtgtgattttggccgacgagcagtagcacccggttctc
gccactccctcggaaatccacatctagatgtcgctactagtttatactacgagcgtcacg
gg----------------------acgctaacgggctccctgcagaatc-----------
----------aggctggggtactgaaatcgcaggaatggctgctttcaattaaagttaat
cgcctgttgaatcatgtgtctttcaaaaagacggacgactagggtagcagcgccacgata
ttac----------------cagaaccgttcatgctgcagggatcaaacagatttcctga
ttccagcggatccgccctctagaggcttttactatcgccaacccatcttcccttagatgg
gaatttacttcaaagtactggggagct---------------------ggtggtgcatac
gttcctagtacaggccca---------------tcccgtagcctggctataagccttaat
ccg--------------------------------tacttcggcctaaga---------g
gcaaagtgtcc---------aaatacctacggggcgggtcctaatctgctcgagacgaca
cagcaccaatcggatgcaaaccccacatgctttcgggacctcccgaatccacaaggttct
------------------------------------------------------------
--agcgcataag------------------------------------------------
----------atcggaattgcgagcggacgtgggttcttgcccattttcgtagagacata
gtccaagctaaggccagcta
>SEQ8
ggcttgcactgtaatctttattacgtcagaccggggagagcggacctcctctcgtagtct
gtcaagctttcttgtgattcgaccccaatggtggtggaactcaactatcttaggcg----
------------------acgacggacgcgttttcaacggtggtcgatccgcgacgtgac
tgaatctatggaatgtaaagtagtgtgattttggccgacgagcagtagcacccggttctc
gccactccctcggaaatccacatctagatgtcgctactagtttatactaccagcgtcacg
gg----------------------------------------------------------
-ccctgcgggacgatggggaacggacatcgcgggcttggctgatcccacttaaatt----
---------aatcgtgt-------------------------ggcaggagcgccacgcta
ttaccggcggaggacgttagcagaaccgatcatgctgcagggatcaaacagatttcctga
ttccagcggatccgccctctagaggcttttactatcgccaacccatcttcccttcgatgg
gaatttatttcaaa---ctaggggcct------------------------gtttcatag
gttcctcctcgtggctca---------------tcccgtagtctggctatatgccttaat
ccgttatccgaccaaagt-----------------------------------------g
gcaaagattcctggcgagtgaaataccttcggggcggctgctaatctgctcgagacgaca
cagcaccaatcggatgcaaaccccacatgcttgcgggacctcccgaatccacaaggttct
gcagacctgacccc---------------ttcgatgaacagcacacctcg----------
----cggataggcagcctagca--------------------------------------
---------------------------------------------------------ata
ttcacacacgcggccataca
>SEQ9
ggcttgcactgcaatctttcttacctctaatc---------------------------t
gtcaagcggtcttgtgattggaccccaatcgtggtgtaactca----------ggcagag
gaatagactattttggacaggacggacgcgttttcaacggtggtagattcgtgacgtgac
t-------------------tagtgtgtttttggccgacgagcagtagcacccggtactc
gccactccctcggaaatccacatctacatgtcgctactagtttatactacgagcgtcact
gg-----------------------------------accctgagtcacacctaacacgg
gtactcacgcaag-----------------------------------------------
-----gttgaatcgtgt-------------------------------------------
-----------ggcagggggcagaaccgatcaagctgcagggatcaaacagatttcctga
ttccagcggatccgccctctagaggcttttactttcgcccacccatcttcccttcgatgg
gaatttacttcaaagtactga--------------------------------ttcatag
gtaccacctcctgggaca---------------tgacgcagcctggctgtatgccttaat
cctttattcgaccaaagtggc---------------------------------------
--------------------aaatacctacggggcggctcctaatctgctcgagacgaca
cagcaccaatcggatggaaaccccacatgctttcgggacctcgcgaacccacaaggttct
gccgacatgaccgtccgaggtccttaacgttcgatgaacagcgcacctcg----------
----cagattggccgtgccgaatcaca---------------------------------
---------------------------------------------------------atg
ttcacagccgcagccattcg
>SEQ10
cgattgcacttcaatatttcttacctctgatcgcggagagc-------------------
--caagcgctcttttgcttcg-----------------------------------cgag
gaaggaactatttttgatacgacggatgcgtcttcaatgggggtggattcgttacgtagg
aggatctatggagtctaagctagtgtgatgttggccgacgagcagtagcacccggtactc
gtcactccctcggaaatccacatctagatgtcgctactagtttatactacgagcgtcacg
gcgcgcggaacgctaaacccctcaaaccttacgggttccctgcagtaacacctatcgcgg
ctactccgggaggctggcgtactaagatcccaagaagggttgct----------------
-ggcgctcgaatcatgtgtcttttcaaaagacggacgact--------------------
--------------------cagaaccgatcaagctgcagggatcaaacagatttcctga
ttccagcggacccgccctctagaggcttttactttcgccaacccatcttcccttcgatgg
gattagacttcaaaaggcc----------------atttaccatgaggggtgtttcatag
gtccctcctccaggcccaggcgaactctggaggtgccgtagcctcgctttatgccttaat
ccgttattcggcgaatgtggaccgtgtggttttgacgttctgccgggacaggggtcatcg
gt------------------aaatacctacggggcgggtcctaatctgctcgagacgaca
cagcaccaatcggatgcaaaccccacatgctttcgggacctcccgaatccacaaggttct
tcagacgtgaaactccgggtttcgtaactttcgatcatctgcgc----------------
------cataggctgtccggcctcaaagtcgctctacttcttaaaacaagataagtcgta
gcgttc-------------ccgtgcggacgtgagtcctgtaccctcttcgcagagacata
gtgccagccgcggccagtca
>SEQ11
ggcttgcactgcaattattc---------------------------------------t
gtcaagcggtcttgtgagtggaccccaatcgtggtgtaactca----------ggcagag
gaatagattattttggacaggccggacgcgttttcaagggtagcagattcgtgacgtgcc
t-------------------tagtttgatgttggccgacgagcagtagcacccggtactc
gccactccctcggaaatccacatctagatgtcgctactagtttatactacgagcgtcacg
gg--------------------------------------tacaatgacacctaggacgt
atactccgcgagcc--------------------gatggctcattcgattcacaattaat
gggctgttgaataatgtgcttgc-------------------------------------
--------------------cagaaccgatcgagctgcagggatcaaacagatttcctga
ttccagcggacccgccctctagaggcttttactttcgccaacccatcttcccttcgatgg
gaacttgcttcaaactgctggggagca---------------------ggtgttgcatag
g------------------------------------gtaacctggctataagccttaac
ccgtaattcggcctaagt-----------------------------------------t
gcaaagtgtcctcgcgagtgaaataccttcggggcggctgctaatctgctcgagacgaca
cagcaccaatcggatgcaaaccccacatgcttgcgggacctcccgaatccacaaggttct
gcagacccgacccc---------------ttcgataaacagcgcacctcg----------
----cggataggcagccta-----------------------------------------
---------------------------------------------------------gca
atcacacacgcgaccataca
>SEQ12
-------------------------cctgaccgcggagagg-------------------
--caagcgctctttttattcgagcatactcgttgtggaact------------------g
gaagtgacttttattgatacgacggacgcgttttcaatggggg----------------c
tggatctatcgagtattaattagtgtgatgttggccgacgagcagtatcacccggtactc
gccactccctcggaaatccacatctagatgtcgctactagtttatactacgagcgtcacg
gg--------------------------------------tacaatgacacctatcacgc
gtactccgggaggcc--------------------atggctcgatcgattcacatt----
-----------tcatgt-------------------------------------------
--gctggcggatgacggttgcagaaccgatcatgctgcagggatcaaacagatttcctga
ttccagcggatccgccctctagaggcttttactatcgccaacccatcttcccttcgatgg
gagtttatttcaaattgctggcgaact---------------------ggtttttcaatg
gttctacctccaggccca---------------ttccgtaccctgac-------------
------------------------------------------------------------
--------------------aaatacctacggggcgggtcctaatctgctcgagacgaca
cagcaccaatcggatgcaaaccccacatgctttcgggacctcccgaatccacaaggttct
---------------------------------------agcgcatatcgaaattgcgag
c-----------------------------------------------------------
----------------------------------------------------gagacata
gtccaagctaaggccagcca
>SEQ13
cgattgcagtgcaatatttcttacctctgatcgcggagagc-------------------
--caagcgctctcttgaatcgcgc-----------------------------------g
gaagtaactgttattaatacgacggatgccttttcaatgagggcagattcgttacgtaa-
--------------------tagtgtgattttggccgacgagcagtagcacccggtactc
gccactccctcggaaatccacatctagatgtcgctactagtttatactacgagcgtcacg
gg----------------------acgctaacgggctccctgcagcatc-----------
----------gtgcaggggtactgatatcgaaggaatagctgcttgcaattaaagttaat
agcctgttgaatcacgtgttattct----------tgactagggtagcagcgcctcaata
gtac----------------cagaacggatcgagctgcagggatcaaacagatttcctga
ttccagcggacccgccctctagaggcttttactttcgccaacccatcttcccttcgatgg
gaaattaattcaaagtaccga--------------------------------ttcatag
gtaccaccacttgcgaca---------------tggcgcattctaccatagtggc-----
------------------------------------------------------------
--------------------aaatacctacggggccgctcctaatctgctcgagacgaca
cagcaccaatcggatggataccccacatgatttcgggacctcccgaacccacaaggttct
gcagacc--------------------ccttcgataaacagcacacatcg----------
----cggctaggcagcctagca--------------------------------------
---------------------------------------------------------ata
ttcgcacacgctcccataca
>SEQ14
ggcctgcaccgtaattattc---------------------------------------t
gtcaagcagtcttctgagtggaccccaatcgtggcataact---------caggc-agag
gaatagattattttggataggccagacgcgttttcaagggtagcagattcgtgacggg--
------cct-----------tagtgtgatgttggccgacgagcagtatcacccggtacac
gccactccctcggagatccacatctagatgtcgctactagtttatactacgagcgtcacg
gg----------------------accctaacgggctccctgcagaatc-----------
----------agaagggggtactgaaatcgcacgaatggctgctttcaattatagttaat
cgc--------------------caaaaagacggacgactagggtagcagcgttacgata
ttac----------------cagaaccgatcaagctgcagggatcaaacagatttcctga
ttccagcggatccgccctctagaggcttttactttcgcccacccatcttcccttcgatgg
gattgtacttcaaagaagctggcagcttcaagcccatttaccatgaggtgtgtttcatag
gtccctcctccaggcacaggcgaactctggaggtgccgtagcctggctatatggcttcaa
ctgt---------------------gtggttttaatgttctggcgggaaaggggtcaacg
gtaaagtatcccggcgagtgaaataccttcggggcggctgctaatctgctcgagacgaca
cagcaccaatcggatgcaaaccccacatgcttgcgggacctcccgaatccacaaggttct
------------------------------------------------------------
--tgcgcatcggctgta--------------------------------------tctta
gcgttctactatcggaattgcgagcgcacgtgggttctggacccttttcgtagagacata
gtccaagttaaggcaagcca
>SEQ15
gccttgcacggtcatctttattacgtcagaccggggagagcggacctcctctcgtagtct
gtcaagctttcttgtgattcgacccctat-------------------------------
----------------gaacgacggaggcggtttcaacggtgatcgatccgcgacgtgcc
tgaatctaatgaatgtaaagtagtgtgatgttggccgacgagcagtatcacccggtacac
gccactccctcggagatccacatctagatgtcgctactagtttatactacgagcgtcacg
gg-----------------------------------ccccgcagtttcacctatcacgt
gtactcggggaggctggggaacgggcatcgcaagattggctgattccatttaaatttaat
cggcggttg-----------------------------------caggagcgccacgata
ttaccggcgcagggcggtagcagaacggatcgagctgcagggatcaaacagatttcctga
ttccagcggacccgccctctagaggcttttactttcgccaacccatcttcccttcgatgg
gattttacttcaaagaacctgg-----------------accatgagtgaggtttcatag
gtccctcctccaggcccaggcgaactctggaggtgccgaagcctggctatgtgccttaat
ctgttattcggcgaaagtggaccctgtggttttgatgttctgccgggacagaggtcaacg
gtaaagta----------tgaaatacctacggggccgctcctaatctgcacgagacgaca
cagcaccaatcggatggataccccacatgctttcgggacctcccgaacccacaaggttct
gcagacccgagact----------------------------------------------
-----------------------------------------------aggacatattcgc
acactctcccataca---------------------------------------------
--------------------
>SEQ16
------------------------------------------------------------
-----------------------------ggctcgcagtccaggcgcccttaggttagag
gaagtgacta------------------caatcccaacgaaggtagatgtgtgacgtggc
tgaatgtatggcgtatacattagtgtgatgttggccgacgagcagtagcacccggtactc
gccactccctcggaaatccacatctcgatgtcgctactagtttatagtacgagcgtcacg
gg-----------------------------------ccatgcagtaacacctatcaagg
gtaccccgcgaggatggggaacggacatcgc-----------------------------
---------attcaggt-------------------------ggcaggaggaccacgcta
ttatcgatggacggcggtagcagaaccgatcaagctgcagggatcaaacagatttcctga
ttccagcggacccgccctctagaggcttttactttcgccaacccatcttcccttcgatgg
gaatttacttcaatgtactgggcagct---------------------ggtgtttcata-
---------------------------------tcccgtagccggagtatatgccttaat
ccgttattcggccaaagt------------------------------------------
----------------ggcaaaatacctacggggcggctcctaatctgctcgagacgaca
cagcaccaatcggatgcaaaccccacatgctttcgggacctcccgaatccacaaggttct
------------------------------------------------------------
--cgcgcaacggctgtg-----------------------------------aagtctta
gagttctacta---------------------------ggacccgtctcgtagagacata
gtccaagctaaggccaggga
>SEQ17
gtcctgcaccgtaatcattc---------------------------------------t
gtcaagcagtcctctgagtggaccccaatcgtggcataactga----------ggcaggg
gaatagattattttagataggccggacgcgtttgcaagggttgaagattcgtgacgggcc
t-------------------tagtgtgattttggccgacgagaagtagcacccggtactc
gccactccctcggaaatccacatctagatgtcgctactagtttatactacgagcgtcact
gcgcatggaacgctaaggccctgaaacctttcgggttccctgcagtaacaccta------
-------------------gactaagatcccaagaagggttgct----------------
-ggcgctcgaatcatgtgtcttttcaaaagacggccgact--------------------
--------------------cagaaccgatcaagctgcagggatcaaacagatttcctga
ttccagcggacccgccctctagaggcttttactttcgccaacccatcttcccttcgatgg
gaattttctt----------------------------------------tgcttcatag
gttcctcctcctggctca---------------tgcagtctcctggcaagaagtggcaa-
------------------------------------------------------------
----------------agtaaaatacctacggggcggctcctaatctgctcgagacgaca
cagcaccaatcggatgcaaacaccacatgctttcgggaccacccgaacccacaaggttct
tcagacgtgaaactccgggttccgtaactttcgatgatctgcgcagcttggtaagctcca
cgggcagataggccgtacggcctcaaagtctttcaacgtcttag----------------
----------atcgcaattctgtgctgacgtgagtcctgtaccctgttaggtgagacata
gacccag-------------
>SEQ18
ggcttgcactgcaatctttcttacctct--------------------------------
--caagcgatcttgtgattggaccccaaacgtggtgtaactcaggcag------------
-----------------------------------agccgtggtagattggtgacgtg--
-----------------aattagtgtgattttggccgacgagcagtagcacccggttctc
gccactccctcggaaatccacatctagatgtcgctactagtttatactaccagcgtcacg
gg----------------------cccctaacgggctccctgcaggatc-----------
----------agaagggtgtactgcaatcgcacgaatgactgctttcaattatagttaat
cgcc--------------------aaaaagacggacgactagggtagcagcgttacgata
ttac----------------cagaaccgatcaagctgcagggatcaaacagatttcctga
ttccagcggatccgccctctagaggcttttactttcgccaacccatcttcccttcgatgg
gacttaacttcaaagtactaggcagat---------------------ggtgtttcgtcg
gttcctactcc---------------------------taggctggctatattccttaat
ccgttattcggccatagt------------------------------------------
----ggcttcctgtcgagtgaaatacctacgggaccgctcctaatctgctcgagacgaca
cagcaccaatcggatggataccacacatgatttcgggacctcccgaacccacaaggttct
tcagacgtgaaactcg--------------------------gctgctgggtatagtcca
cgggcagataggccgtacggccagaaagtctctcaacttcctagatcaagagaggtcttc
gcgttctactatcacaatcccttgcggccgtg-----------------------ccata
gtctcaaccgcggccaa---
>SEQ19
---------------------gcctcctcaccgcggagaag-------------------
--caatcgctcttgtgattcgagcctaatcgttttggaacc------------------g
gagctgactt------------cggacgcgttttcaatgggcgtagattcgttacgaggc
tgtatctctcgagtattaattagtgtgatgttggccgacgagcagtagcacccggtactc
gccactccctcggaaatccacatctagatgtcgctactagtttatactacgagcgtcacg
gcggccggaacgc------------------------tcaaccagtaacacctatcgcgg
ctacacctggaggctggcgtactaagatcccaagaagggatgct----------------
-ggcgctcgaatcatgt----------------------------------------gta
ttttcaaaagacggacgaatcagaaccgatcaagctgcagggatcaaacagatttcctga
ttccagcggatccgccctctagaggcttttactttcgcccacccatcttcccttcgatgg
gattttacttcaaagaacctggcagctactagcccatgtaccatgaggggtgtttcataa
gtccatcctcctggcctc------------------------cggcctatatcccttaat
ccgttattcggcgaagggggacagtgaggttttcctgtactgccgggacaggggtcagca
gttaaatatccaggcgagggaaatacctacggggcggctcctaatctgctcgagacgaca
cagcaccaatcggatggaaaccccacatgctttcgggacctcccgaacccacaaggttct
tcagaagtgaaactcggaggtccgtaacttgcattgatcggcgc----------------
-------atcggctgta-------------------------------------------
-----------------ttgcgagccaacgtgggtcctgtaccttttccgcattgagata
gtccaagctaaggccagtca
