>SEQ0
atctactggagccgggcgagacacatggcatccgacttagtcaattcaaactgatcttcc
gtagtaaacgcattaccggctcttcacggatcagtgcatacgttcatagaacatagcagc
cgatgctggactcagcgcccttggtcccagtagccctggtttactgggcatccca-----
-----------agcaactctaacgcccttcttccatcgccttggctagaataggtaccac
agagctaacgaaagaggagggcttcaccggctctatcagatcatattaaatcagctggtg
ttagctaagggttctgtagcaagctaagaagttaggtgagttccattcagggattataga
ttacctttaccactagtgctactttggattgcatgctagataaagagagtatcttgttgt
ttggctgtctctggcgtagcttcgcgagcatagctttccataggaacactcttcctgtac
cccggggttggagtaaggttgacaacgaatgtaccattactgtttgggccgcgtaacaca
aaaacataatcgcgtgcgtggtgggaacacggggaagaaagtagctccagtaaaagtttg
ggtcatcatcggggcgtgggtctg-gaccactggcgaggagggctattcagtaaaaaagc
agtacgcaatttgccatgacgcgtaaggaacaccgttgatctagtattacgtttagacat
agctggacgcttgaacgtttgctatcgacagctagagttccaatagagcatta--ccgag
atggcacgaatcgcaagtacgctcatt----cggtcagttaggcgacggcccggatgcac
ggcgaacctacggcatgaccatttcgatgaatcccctccgttttcgagtacatggatcgc
ggagtggaacctatagctacaatgacgaccgataaaccatcctgccgaatcccactgaaa
tgtgttatagcaaacttcgagatagagtgcagagtcaactaaggaaatttaggaaagcac
aaatgatggttctctctgcagagtagaggcagttctagtagctcacaaactaaatcgacc
ctcttggacctcagtggtgctagttcgacatgacatgtattac
>SEQ1
ttcttctggagccgggcgacacacaaggcatccgacttagtcaattcacactgatctgcc
gtagtaagcgcatttccggctctacacggatcagtgcttacgttcatataacatagcagc
cgatgctggactcagcgcccttggtcccagttgtcctggtttactgtgccgccca-----
-----------agcaattttaacgcccttctcccaacgccttggctagaataggtaccac
agagctaacgaaagagcagggcttcacgggctctatcagagcatattaaatcagctggtg
ttagctaagggttctgtaggaagctcaaaagttaggtgagttccgttcagggattataga
ttacctttaccactagtgctgctttagattgcatgctagctaaagagagtatcttgttgt
ttggctgtctctggcgtatcttagcgagcatagctttccataggaacattcttcctgaac
cccggggttagagcaaggttgacaacgaatgt----ttactgtttgggccgcgtaacaca
aaaacataatcgcgtgcgtggtgggaacacggggaagaaagtagctccagtaaaagtttg
ggtcagcatcggggcgtgggtctc-gatcactggcgtggagggctattcagtaaaaaaac
agtccgcaatttgccatgacgcgtaaggaacagcgtagatttagtattacgtttagacgt
----------------------------cagctagagttccagtagagcatta--ccgag
atggcgcgaatcgcaagtacgctcatt----cggtcagttaggcgacggcccggatgcac
ggcgaacctacggcatgaccatttcgatgaatcccctccgttttcgagtacatggatcgc
ggagtggaacctatagcgacaatgacgacagatataccatccaggcgaatcgcattgaaa
tgtgttatagcaagattcgagatagagtgca-------------------tggaaaacac
caatgatggttctctctgcagagtagaggaagttctagtagctcacaaactaaatcgacc
ctcttggacgtcagtggtgcttgttcgacatgacaagtatgcc
>SEQ2
atctactggagccgggcgagatacctggcagccgcctaattcaattctcattgatcttcc
gtagtagacgcataacctgctgttctcggatcagtgcatacgttcatagaccatagcaga
ccatgctggactcagcgcccttcgtcccagtagccccggtttactgggcatccca-----
-----------agcaactctaacgcccttcttccatcgccttggctagaataggtaccac
agagctaacgaaagaggagggcttcaccggcactatcagatcatattaaatcagctggtg
ttagctaagggttctgtaggaagctcaaaagataggggagttccgttgagggattattga
taacctttaccactagtgcaggttcaccttgcatgctagctaatgagagtatcgtgttaa
tcggctgtatccggcgtatctaagcgagcatagcttttcataggaacattcttcctgaac
cccggggttagagcaaggttgacaatgaatgg----ttactgtttgggccgcgtaacaca
aaaacataatcgcgtgcgtggtgggaacacggggaagaaagtagctccagtaaaagtttg
ggtcagcatcggggcgtgggtctc-gttcactgacgtggagggctattcagta-------
--------------catgacgcataaggaacag---------------------------
----------------------------cagctagagttccactagagcatta--ccgac
atggcgggaatcgc------------------------ttaggcgacggcccggatgcac
ggcgaacctacggcatgaccatttcgatgaatcccctccgttttcgagtacatggatcgc
ggagtggaacctatagcgacaatgacgagcgataaaccatcctgccgaatcccactgaaa
tgtgtaatagcaaacttcgagatagagtgcagagtcaactatgg----------------
----gatggttctctctgcagagtagaggcagtt-----------------------acc
tgttttag-----------------------------------
>SEQ3
atctactggagccgcgcgagatacctgtcagccgcctagtt------------atcttcc
gtagacgacgcataacctgctgttctcagatcagtgcatacgttcatagaccacataaga
cgatgctggactcagcccccttcgtc----------------------------------
-----------------tctaacgcccttcttccatcgccttggctagaataggtaccac
agagctaacgaaagaggagagcttcaccggcactgtcagaccatattaaatcagctggtg
ttagctaagggttctgtaagaagatcaaaagttaggtga-------------attatcga
ttacctttacca--------------------atgcaaggtaaagagagtatcttgttgc
ttgtctgtctctggcgtatcttagcgagcatagctttccataggaacattcttcctgaac
cccggggttagagcaaggttgacaccgaatgt----ttactgtttgggccgcgtaacaca
aaaacataatcgcgtgcgtggtgggaacacggggaagaaagtagctccagtaaaagtttg
ggtcatcatcggggcgtgggtctc-gttcactcacatggagagctattcagtaa------
---------------atgacgcataacgaac-----------------------------
----------------------------cacctagagttccactagtgcatta--ccgac
acagcg-------------------------------gttaggcgacggcccggatgcac
ggcgaacctacggcatgaccatttcgatgaatcccctccgttttcgagtacatggatcgc
ggagtggaacctatagctacaatgacgacagaaatagcatccagccggttcgcattgaaa
tgtgttgtagcaagatccgagatagagtgca-------------------tggataacac
caatgacggctctccctgcagagtagaggaagttttattagctcacaaacttaatcgacc
ctcttggacgtcagtggtgcttgttagacatgacaagtatgcc
>SEQ4
ttctactggagacgggcgagatccctggaagc-------------------------tcc
gtggtagacgcataacctgctgttctcgg-------------------------agcaga
ccatgctggactcagcgcccttcgtcccagtagccccggtttactgggcaacgca-----
-----------agcaactctaacgaccttcctccatcgccttggctagaataggtacctc
agagctaacgaaagagcagggcttcacgggctctatcagagcatattaaatcagctggtg
ttagctaagggttctgtaagaagatcaaaaat--------------------attagcaa
tgacctttacca--------------------atgtaaggtaa-----------------
--gtctgtctctggcgtgtcttagcgagcatagctttccataggaaaattcttcctgaac
ccgggggttagagcaaggttgacaccgaatcc----ttactgtttgggccgcgtaacaca
aaaacataatcgcgtgcgtggtgggaacacggggaagaaagtagctccagtaaaagtttg
ggtcagcatcggtgcgtgggtctc-gattactggcgtagagggctattcagtaaaaaaac
agtccccaatttgccatgaccggtaaggaacagtccagatttggacttacgtttacatgt
----------------------------ccgctacagttccagtagagcatta--ctgag
atggcgagacccgcaagtac----------------------gcgacgtcccggatgcac
ggagaacctacggcatgaccatttcgatgaatcccctccgttttcgagtacatggatcgc
ggagtggaacctatagctacaatgtcgaccgataaaccaacctaccgaatcccactgaaa
tgtgttatagcaaacttcgggatagagtgcagagtcaactaaggaaatttaggaaagcac
aaatgatggtgctctctgcagagtagaggcggttctagtagctcacaaactaaatcgacc
cacttggacctcagtggtgctagttcgacatgacatgtattac
>SEQ5
atctcctggagccgggagagatacctgtgagccgcc------------------------
-tagtagacgcataacgtgccgttctcggatgagttcatacgttcataggcgataggaga
ccatgctggactcagcgcgcttcgtcccagtagccccggtttactgggcattcca-----
-----------agcaactcttacgcccttcttccatcgccttggctagaataggtacctc
agagctaacgaaagagcagggcttcacgggcactatcagagcatattaaatcagctggtg
ttagctaagggttctgtagcacgctaagaagttatgtgagttccattcagggattataga
ttaacttcaccactagtgctactttgaattgcatgctagataaagagtgaaacttgttgt
t-----------ggcttagcttcgcgagcatacctttccatagtaacactcttcctgtac
cccggggttggaataaggttgacaacgaatgtaccattactgtttgggccgcgtaacaca
aaaacataatcgcgtgcgtggtgggaacacggggaagaaagtagctccagtaaaagtttg
ggtcagcatcggtgcgtgggt----------------------ctattcaataaaacaac
agtccccaatttgccatgacgcgtaaggaacagcgtacgtttag----------------
----------------------------caactagagtgccagtagaggatta--ctgag
aaggcgctagtcgcaactac----------------------gcgacgtcccggatgcac
ggagaacctacggcatgaccatttcgatgaatcccctccattttcgagtacatggatcgc
ggagtggaacctatagctacaatgacgag------------------------gctgaaa
tgtgtaatagcaaacttcgagatagagtgcagagtcaactatgg----------------
----gatgattctctctgcaccgtggaggcagttttttttag------------------
-------------------------------------------
>SEQ6
atcgactggacccgggcgagatacctagcagccgcctaattctattctcattgatattcc
gtagtagacgcatagcctgctgttctcggatcagtacatacgttcatagaccttagaaga
ccatgc------------------------------------------------------
------------------------------atccatcgcgttggctagaataggtaccac
agagctaacgaaagaggagggcttcaccggctctatcagatcatattaaatcagctggtg
ttagctaagggttctgtaggacgcgctaaagatagttaagttccgttgcgggattattga
taacctttaccactagtgcaggttcagcttgcatgccagctaatgagaggatcgtgttaa
tcggctgtatccggcgtatctaggcgagcgtagcttttcataggaacattcttccggccc
cccggggttacagcaaggttgagaatgaatgg----ttactgtttgggccgcgtaacaca
aaaacataatcgcgtgcgtggtgggaacacggggaagaaagtagctccagtaaaagtttg
ggtcagcatcggggcgtg-------------------------ctattcagtaaacaaac
agtccgcgatttgccat-------------------------------------------
--------------------------------tagtattacgtttagacatcagcccgag
atggcgcgaatcgcaagtacgctcatt----cggtccgttaggcgacgtcccggatgcac
ggagaacctacggcatgaccatttcgatgaatcccctccattttcgagtacatggatcgc
ggagtggaacctatagctacaatgacggg------------------------gctgaaa
tgtgtaatagcaaacttcgaggtagagtgcagagtcaacta-------------------
---tgatgattatctctgcaccgtggaggcagtctttattag------------------
-------------------------------------------
>SEQ7
atctcctagacccgggagagatacctgtaagacgcc------------------------
-tagtagacgcataacgtgcggtactcggatgagtccatacatacataggcgataggaga
ccatgctgggctcagcgcgcttcgtcccagtagccacggtttactggggattcca-----
-----------agcaactcttacgcccatcttccatcgccttggctagaataggtacctc
agagctaacgaaagagcagggcttcaccggctctatcagagcatattaaatcagctggtg
ttagctaagggttctgtaggacgcgctacacatagttaagttcggttgcgggattattga
taacctttaccactagtgcaggttcagcttgcatgtcagttaataagaggatcgtgttaa
tcggcgctatccggggtttctaggcgagctta-------------------ttccggccc
gccgcggtcatagcaaggttgacaatgactgg----ttactgtttgggccgcgtaacaca
aaaacataatcgcgtgcgtggtgggaacacggggaagaaagtagctccagtaaaagtttg
ggtcatcatcggggcgtgggtctc-gttcactcacatggagagctgttcggt--------
-----------------gacgcataatgaac-----------------------------
----------------------------cacctagagtttcactagtgcatta--ccgac
acagcg-------------------------------gttaggcgacggcccggatgcac
ggcggacctacggcatgaccatttcgatgagtcccctccgttctcgagtacatggatcgc
ggagtggaacctatagcgacaatgacgagcgataaaccatcctgccgaatcccactgaaa
tgtgtaatagcaatcttcgagataaagcgcagaatgatctatgg----------------
----------------tgcagagtagaggcagtt----------------------aact
gttttag------------------------------------
>SEQ8
tcctactggaatcggccgagatccctggaaac-------------------------tcc
gtggtagacgcaaaacctgttgttctaga-------------------------agcaga
tcatgctcaactcagcgcccttcgtaccagtagccccggtgtactaggcaacgca-----
-----------agcaagtctaacgaccttcctccctcgccttggctagaataggtaccac
cgagctaacgaaagaggagggcttcaccggctctatcagatcatattaaatcagctggtg
ttagctaagggttctgtaca----------------------------------------
----------------------------------------------------cttgttgc
ttgtctgtctctggcgaatcttagcgagcatagctttgcataggaacgttctggctgaac
cccggggttagagcgaggttgacaccgaatgt----ttactgtttgggccgcgtaacaca
aaaacataatcgcgtgcgtggtgggaacacggggaagaaagtagctccagtaaaagtttg
ggtcatcatcggggcgtgggtctc-gttctctgtcttagagggctaatcagta-------
--------------catgacgcatacggta------------------------------
----------------------------cagctagggttcccctagagcataa--ccgac
atggcgggaatcgc------------------------ttaggcgacgtcccggatgcac
ggagaacctacggcatgaccatttcgatgaatcccctccattttcgagtacatggatcgc
ggagcggaacctatagctacaatgacgaca-----------------------gttgaaa
tgtgtta------------------agtgca-------------------tggaaaacac
caatgatggtt------------------aagttctagtagctcacaaactaaatcggcc
ctcttggacgtcagtggtgctagttcgacatgacaagtatgcc
>SEQ9
ttctactggaggcgggcgagatcactggaagc-------------------------tcc
gtggtagacgca------------------------------------------------
-----------------------------------cttgtttactag-------------
---------------------acaacctttatccatcgccttggctagaataggtaccac
agagctaacgaaagaggacagcttcaccggcactgtcagaccatattaaatcagctggtg
ttagctaagggttctgtaggacgcgctacacattgttaatttcggtggcgggattatagc
taacctttaccacta-------------------gtcagttaataagaggatcgtgttaa
tcggcgctgtccgg----------------------------------------------
----------gagcaaggtagacaatgactgg----ttactgtttgggccgcgtaacaca
aaaacataatcgcgtgcgtggtgcgaacacggggaagaaagtagctccagtaaaagtttg
ggtcagcatcggggcg--------------gtcacatggagagctgttcgtt--------
-----------------gacgcaaaatgaac-----------------------------
----------------------------cacctagagttacactagtgcatta--ccaac
acagcg-------------------------------gttaggcgacgtcccggatgcac
ggagaacctacggcatgaccatttcgatgaatcccctccattttcgagtacatggatcgc
ggagtggaacctatagctacaatgacgag------------------------gctgaat
tgtgtaatatctaacttagagatagcgcgcagagtcaaccatgg----------------
----gatgattctctct---------------tttttttcag------------------
-------------------------------------------
>SEQ10
ttctactgcaggcgggcgagatcataggaagc-------------------------ttc
gtggtagacgcat-----------------------------------------------
------------------------------------------------------------
------------gtttatttgagaacctttatccatcgccttggctagaataggtaccac
agagctaacgaaagaggagagcttcaccggcactgtcagaccatattaaatcagctggtg
ttagctaagggttctttaggaaactcaaaagaaaggggagttccgttgaggtattatgga
tcagctttaccactagtggaggttcacctagcatgctaggtattgagagtatcgtgttaa
tcggctgtttccggcgtatct---------------------------------------
-------ttacagaaatgttgacactgaatgg----ttactgcttgggccgcgtaacaca
aaaacataatcgcgtgcgtggtgggaacacggggaagaaagtagctccagtaaaagtttg
ggtcatcatcggggcgtg-------------------------ctattcagtaaacaaac
agtccccgctttgccag-------------------------------------------
--------------------------------tcgtattacgtttacacatga------g
atggcgcgaatcgcaactacgctcatt----cggtgggttaggcgacggcccggatgcac
ggcgaacctacggcatgaccatttcgatgaatcccctccgttttcgagtacatggatcgc
ggagtggaacctatagctacaatggcgaca-----------------------gtttaaa
cgtgtta------------------agtgca-------------------tggaacaaac
cactgatagctc--------------------------------acaacctaaatcggcc
cttttgggcggcagtggtgctagttcgacaggacaagtatgcc
>SEQ11
ttcttttagagccgggcgacacacaaggcaaccgatttagtca-----------------
--agtaagcgctttaccggctctacacggatcag------------------atagcagc
cgatgctggactcag---------------ttgtcctggttggctgtgccgccga-----
-----------agcaaatttacagcccttttcccaacgccttggctagaataggtaccac
agagataacgaaagaggagagcttcaccggcactgtcagaccatattaaatcagctggtg
ttagctaagggttctgttagaagatcgaaagttcggtga-------------attatcga
ttatctttacca--------------------ttgcaaggtaaagagattatcttgttgc
ttgtctgtctctggcgtatcttagcgaggatagctttccac------------------c
cccggggttagatcaaggttgacaccgactga----ttactgtttgggccgcgtaacaca
aaaacataatcgcgtgcgtggtgggaacacggggaagaaagtagctccagtaaaagtttg
ggtcatcatcggggcatgggtctc-gaccactggcg------------------------
-gtccgcaacttgccatgacgcgtaaggaacaacgtagatttagtattacgtttagacat
----------------------------aatctagagttcctgttgagcatta--ccgag
atggctcgaatcgcaagtgcgctcatt----cggtcagttcggcgacgtcccggatgcac
ggagaacctacggcatgaccatttcgatgaatccgctccattgtcgagtacagggatcgc
ggagtggaacctatagctacaatgacaagcgataatccatcctgccgaatccaactgaaa
cgtgtaatcgcacacttcgagttagagcgcacagtcaactatgg----------------
----aatggttctctctgcagtgtggaggcagtt-----------------------acc
tgttttag-----------------------------------
>SEQ12
tcctaccggaatcggccga-gagcccttgaaac------------------------tcc
gtggtaaacgcaaaacttgttgctctaga-------------------------agcaga
tcatgctcaactccgcgccattcgtaccagtagccccggtgtactagacaacgca-----
-----------agcgtgtctaacgaccttcctccctcgccttggctagaataggtacctc
agagctaacgaaagagcagggcttcaagggctctatcagagcatattaaatcagctggtg
ttagctaagggttctgtagcaagctacgaagtttcgtgcgttccattcagggattatcga
ttaacttcaacactagtgctactttgaattgcata-------------------------
--acttgttgttggcttagcatcgcgaacatacctgtcaatagtaacactctt-------
------------gtaaggttg---------------ttactgtttgggccgcgtaacaca
aaaacataatcgcgtgcgtggtgggaacacggggaagaaagtagctccagtaaaagtttg
ggtcagcatcggggcgtgcttttcagtaaacaaacagtccgcgatatgccata-------
------------------------------------------------------------
---------------------------------agtattacgtttagacatcagcccgag
aaggcacgaatcgcaagtacgctcatt----cggtccgttaggcgacggcccggatgcac
ggcgaacctacggcatgaccatttcgatgaatcccctccgttttcgagtacatggatcgc
ggagtggaacctatagctacaatgaccaca-----------------------gttgaaa
tttgtta------------------agtgca-------------------tcgaaaacac
caatgacggt---------------------------gtagctcacaaagtaaatcggcc
ctcttggacgtcagtggtgctagtttgatatgacaagtatgcc
>SEQ13
gtcttttagagacgggcgatacacatggcaaccgatttaatcaagtcagcggatccgata
gcagcagatgc-------------------------------------------------
---------------------tggactcatttgacctggttggctgtgccgccga-----
-----------agtaaattta-----------cagccgccttggctagaataggtaccac
agagctaacgaaagaggagagcttcaccggcactgtcagaccatattaaatcagctggtg
ttagctaagggttctttgggacgcgctacacatagttaagttcggttgcgggatgattta
gaacctttaccactagtgcaggttcaa-------------tcataagaggatcatgataa
tcggcgctatacggggtatctaggcgagctta-------------------ttccggccg
gccgcggtca--------------------------ttactgtttgggccgcgtaacaca
aaaacataatcgcgtgcgtggtgggaacacggggaagaaagtagctccagtaaaagtttg
ggtcatcatcggggcttggggctc-gttcacta---------------------------
--------------catgacgcataaggaacca---------------------------
----------------------------cagcttaagttccattagaacatta--ccgaa
atggcgggaatcg------------------------attaggcgacgtcccggatgcac
ggagaacctacggcatgaccatttcgatgaatcccctccattttcgagtacatggatcgc
ggagtggaacctatagctacaatgacgag------------------------gctgaat
cgtgtaacatctaacttagagatagtttg----------------------------att
ctatgtttgttttcag--------------------------------------------
-------------------------------------------
>SEQ14
atcgcctagacccgggagagatacccgtaatacgcc------------------------
-tagtagacgcacaacctgcggtactcggatgagtccttccatacataggc---------
--------ggctcaccgcgcttcgtcccagtagccacggtttattggggattcca-----
-----------agcaactattacgcccattttccatcgccttggctagaataggtacctc
agagctaacgaaagtgcagggcttcacgggctctatcagagcacattaaatcagctggtg
ttagctaagggttctgt-------------------------------------------
----------------------------------------------------cgtgttgc
ttgtctgtctctggcgaaccccggggtgt-------------------------------
------------------------------------ttactgtttgggccgcgtaacaca
aaaacataatcgcgtgcgtggtgggaacacggggaagaaagtagctccagtaaaagtttg
ggtcatcatcggggcatgg-------------------------tattcagtaaacaaat
agtgcgcgatttgctat-------------------------------------------
--------------------------------tagtattacgtttagacatcagacgcag
atggcgcgaacaatcggtcc-----------------gttaggcgacgtcccggatgcac
ggagaacctacggcatgaccatttcgatgaatcccctccattttcgagtacatgcatcgc
ggagcggaacctatagctacaatgccgaga-----------------------gtttaag
cgtgtta------------------agtgca-----------------------------
-----------------------------------------------aatgatatcggcc
cttttttgcggccgttgtgc-----------------------
>SEQ15
atctactggagccgctcagccgactagtaatct------------------------tcc
gtagacggcggataacctgccgttctcag-------------------------atcagt
gcatacgt---------------------------------tcatagaccacataagacg
aagctggactcagcccctctaaagcccctcttccatc------gctagaataggtacctc
agagctaacgaaagtgcagggcttcacgggctctatcagagcacattaaatcagctggtg
ttagctaagggttctgtagcaagcta------------------attcagggattatcga
ctaacttcaacactagtgctactttgaattgaata-------------------------
--acttgttgttggtttagcatcgcg---------------agtaacacactt-------
------------gtaaggttg---------------ttactgtttggggcgcgtaacaca
aaaacataatcgcgtgcctggtgggaacacggggaagaaagtagctccagtaaaagtttg
ggtcagcatcggggcgtgggtctc-gtgcacttacgtgcggggctatttagta-------
------------------------------------------------------------
---------------------------------catg-----------------------
-----acgcataatgaataggttcctcgcgggaatcccttaggcgacggcccggatgcac
ggcgaacctacggcatgaccatttcgatgaatcccctccgtttgcgagtacatggatcgc
ggagtggaacctatagctacaatggcgagt-----------------------gtttaag
cgtgttt------------------agtgca-------------------t--atgatat
ca------------------------------------------------------ggcc
ttttttgcggccggtgtgg------------------------
>SEQ16
ttatactgcaggcgggcgagatcataggaagc-------------------------tcg
gtggta------------------------------------------------------
------------------------------------------------------------
-----------tgtttatttcggaacctttatccatcgccttggctagaataggtaccac
agagctaacgaaagagcagggcttcacgggctctatcagagcatattaaatcagctggtg
ttagctaagggttctgtagcaagctacgaagt-------------gtcatggattatcga
tcaatttcaacactagtgcgcatac-----------------------------------
---cttgttgttgacttagcatctcgaacatacctgtcaattgaaacactctt-------
------------gtaaggttg---------------ttactgtttggggcgcgtaacaca
aaaacataatcgcgtgcctggtgtgaccacggggaagaaagtagctccagtaaaagtttg
ggtcagcatcggggcgtg-------------------------ctatgcagtaaacaagc
ggtccccgctttgacag-------------------------------------------
--------------------------------tcgtatttcgtt----------------
--ggcgcgaatcgcaacttcgctgatt----cggtgggttaggcgacgtcccggatgcac
ggagaacctacggcatgaccatttcgatgaatccgctccattgtcgagtacagggatcgt
ggagtggaacctatagctacaatgccaaccgataaaccaacctaccgaatcccaatgaaa
tctgtt-----------------------cagagtcaactaaagaaattgaggaaggcac
aaatgaaggtgatctctgcagactagagggggttctagtagttcacaa------------
-----------cagtggtgctagttcgacatgaactgtattac
>SEQ17
ttcttctggagccgggcgacacacagggcatccgacttagtcaattcagactgatctgcc
gtagtaagcgcatttgcggctctacacggagcagtacttacgttcatatgatatagcagc
cgctgt--------------------------gtcttggtttattgtgccgccca-----
-----------agctattttaacgcccttctcccaacgccttggctagaataggtacctc
agagctaacgaaagagcagggcttcacgggcactatcagagcatattaaatcagctggtg
ttagctaagggttctatagcaagctaagaagtaaggtgagttccattcagggattataga
ttacctctacctctagagctactttggatcgcatgctagataaagagagtatcttgttgt
ttggctgtctctggcgtagcttcgcgagcatagctttccataggaacactcttcctgcac
cctggggttggagtaaggttgacaaggaatgtaccattactgtttgggccgcgtaacaca
aaaacataatcgcgtgcgtggtgggaacacggggaagaaagtagctccagtaaaagtttg
ggtcagcatcggtgcgtgg----------------------------tcggtaaacaatc
cgtcgccgctatgcca--------------------------------------------
--------------------------------------------------------ggag
atggagcaaatcgcaactacgctcatt----cggggggttaggcgacgtcccggatgcac
ggagaacctacggcatgaccatttcgatgaatccccgccattttcgagtacatggatcgc
ggagtggaacctatagctacaatgtcgagcgatgaacca------------------aaa
agtgttatagcaaacttcgggatagagtgcaga---------------------------
-actgatggtgccctctgaagagtagaggcggttctagtagctcatacactaaatcgacc
cacttgggcctcagtggtgctagttcaacatgacaggtattac
>SEQ18
atcggctagacccgggagagataactgaaatac---------------------------
-tagttgacgcacaacctgcggta------------------------------------
----aggcggctcaccgcgcttcgtcccagtagca-------------------------
---------------------------------catcgccttggctagaataggtaccac
agagctaacgaaaggggagggctttaccggctctatcagatcatattaaatcagctggtg
ttagctaagggttctgtaggacgcgctaaag-------------gttgccggatttttga
taacctctaccgctagtgcaggtacagcttgcatgccagctaacgagaggatcgtgttga
tcggctgtatccggcgtatctaggcgagcgtagcttttcatcggaacattcttccggccc
cgcggggttacagcaaggttgggaatgaattg----ttactgtttgggccgcgtaacaca
aaaacataatcgcgtgcgtggtgggaacacggggaagaaagtagctccagtaaaagtttg
ggtcatcatcggggct--------------------------gctgttcgtt--------
-----------------gacgcaaaacgaac-----------------------------
----------------------------caccgagagttacactcgtgcatta--acaac
acagcg-------------------------------gttaggcgacggcccggatgcac
ggcgaacctacggcatgaccatttcgatgaatcccctccgttttcgagtacatggatcgc
ggagtggaacctataactacaatgaaggg------------------------gctgaaa
tgagtaatagcagagt-----------------------------------------caa
ctctgaggattatctatgctccgtggagggtgtctatactag------------------
-------------------------------------------
>SEQ19
ttctactggaggcgggcgagatcactggaagc-------------------------tcc
gtggtagacacac-----------------------------------------------
------------------------------------------------------------
------------------------tccttcatccatcgccttggctagaataggtaccac
agagctaacgaaagagcagggcttcacgggctctttcagagcatattaaatcagctggtg
ttagctaagggttctgtagcatgctaa------------------ttcagggattatcct
ttaacttcgacactagtggtactttgaattgaata-------------------------
--aattgttcttggtttagcatcgcgagtaatacactt----------------------
------------gtcaggttg---------------ttactgtttgggccgcgtatcaca
aaaacataatcgcgtgcgtggtgggaacacggggaagaaagtagctccagtaaaagtttg
ggtcatcatcggggcatgggtctc-gattactggcgtagagggctattcagtaaaaaaac
attccgcaatttgccatgaccggtaaggaacagtccagatttgga---------------
----------------------------ccgctacagttccagtagagcattt--ctgag
atggcgggacccgcaagtac----------------------gcgacgtcccggatgcac
ggagaacctacggcatgaccatttcgatgaatcccctccattttcgagtacatgcatcgc
ggagcggaacctatagctacaatgctgagagacataccgtccaggctaatcgcattcaaa
tgtgttatcgcaagtttcgagatagagtgca-----------------------------
--atgatggctctctctgcagagtagaggaagtg---------------------cgacc
ctcttggacgtcagtggtgcttgttccacattacaagtatgcc
