>SEQ0
gactaacggggggcgatcggtgagttgcacatagaaacacgcacgagttctagacctcgg
cgattatcattgcgcgcgtcacagctccctcattaacgcactattaccatgcattcggcg
gactacggtccactgcatatgcttttgtcgttcaaacgggaactttactttcccgcgctc
acattcctatttcgcgtggaaacaattgaggcatacctgttgtaaaatctctctcttacc
cggccactgtagtgggagagaaattaatcgcaatgtaagcagtgtactgtcccgttacgg
taaatacgatcttgggacctactaacaggaatagagagaaacagga--------------
ctcgcatgagcacttgactccgagtgcggaccgtatcttcaacaactactcttcccagcg
gctgagtcgatagaccacatgtgcaaccagctagacagccactcgtcgaatcggcgcgcg
cctctgctgatcgtaacgagtcacctccctggctgcactctgcatacatggagtaaacat
gccatgatatagacctcgtgcccggtcatatagacgatgcttaaagtcatgaatgtgccc
ttgccgagatggattatttaa--tttcgaaattttagatttctcaacctggagcggtcgg
acggaaggaaggcccgataacccctgtattataactcctgaaagtcaacgccccctgtcc
ctaacaccaattacattgcatgaacggtatgctggcactttaaaaggtatcgaagtcaac
tggaattgacaagaatggcgaaaacatcctggttgagtccgcaaaccgaaagtggtgtac
ggggagatccggcgtcatctgagtggcaactatgtgactaataacctatcagttttcttc
cccaacaaagagccaaggtcatcagcattgccgttgcgtaatgtacgtgggtttggtgta
ttccaaggcgaaattatcttacaagtgactgccaccgacattctgcttctaacagcctgc
gtacccgcgtctaccataccctatgccaggctgctaaggagcacagctgctccgggcaaa
ggtctgacggcccaataaactcgcgatgtcgcaccc
>SEQ1
gactatcggggagcgatcggtgagttgcacatagaaacactcacaagttctagacctcgg
c----------------------gctccctcattcacgaactattaccatgcattcggcg
gactacggtccactgcatacgcttttg-----------------ttactttcctgcgctc
acattcttatgtcgcgtggaaacaattgaggcatacctgttgtaaaatctccctcttacc
cggccactgtagtgggagagaaattactcgcaatgtaagcagtgtactgtcccgttacgg
taaata------------------------------agaaacagga--------------
ctgtcatgagcagttgacgccgagggccgaccgtatcatcaacaactactcttcccagcg
gctgagtcgatatcacacatgtgcaaccagctagacagccactcgtcgaatcggcgcgcg
cctctgatgatcgtaacgagtcacgtccctggctgcactctgcatacatggagtaaacat
gccatgatatagacctcgtgcccggtcatatagacgatgcttaaagtcatgaatgtgccc
ttgccgagatggagtatttaa--tttcg-------------------cttgagcggtcgg
acggaaggaaggcgcggtaacccctgtattataactcc----------------------
----caccagttacattgcataagaggtatgctggcactttaaaag--------------
-------gacaagaatggcga--------------agtccgcaaaccgaaagtggtgtac
ggggagatccggcgtcatctgagtggcaactatgtgactaataacctatcagttttcttc
cccaacatagagccaaggtcatcggcattgccgttgggtaatttatgttagtttggtgta
ttccaaggggaaattatcttacaagtgactgccaccgacatgctgattctaacatcctgc
gta---------------------------------------------------------
----------tccaataagctctcgatgtcgcacgc
>SEQ2
gactaacggggggcgatcgttgagtcacacatagacacacgcacgagatctagacctcgg
cgattatcattgcgcgcgtcacggctctctcattttcgtactattacaa-----------
-------------tgcttatgcttttgtcgttcaatcgggaactttattttcccgggctc
acattcctatttcg------aacaattgaggcatacctgttgtaaaatctctctcttacc
cggccactgtagtgggagagaaattaatcgcaatgtaagcagtgtactgtcccgttacgg
taaata------------------------------agaaacagga--------------
ctgtcat---------------agggccgaccgtatcatcaacaactactcttcccagct
gctgatttgatatcacacatgtgcaaccagctagtcagccactcgtcgatacggcgcgcg
cctctgctgatcgtaacgagtcacttccctggctgcactctgcatacatggagtaaacat
gccatgatatagacctcgtgcccggtcatatagacgatgcttaaagtcatgaatgtgccc
ttgccgagatggagtatttaa--tttcg---------------------------gtcgg
acggattgaaggcgcggtaacccctgaactataactcc----------------------
----caccagttacatggcataagaggtatgctggaactttaaaag--------------
-------aaaaagaatggcga--------------agtccgcaaaccgaaagtggtgtac
ggggagatccggcgtcctctgagtggcaactatgttactaataacctaccagttttcttc
cccaacaaagagccaaggtcatcggtatt-------------------------------
-tccaaggggaaatcatcgtacaagtgactgacaccgacatggtgattcta---------
------------------------------------------------------------
----------accaataagctctcgatgtcgcacgc
>SEQ3
gactaacggggggcgttcgttgagtcacacatagacacacgcacgagatctaggcctcgg
cgaatatcattgcgcgcgtcacggctctctcattttcgtacgattacaa-----------
-------------tgcttatgcgtttgtcgtacaatcgggaactgtattgtcccgggctc
acattcctaggtcg------aacaattgaggcatacctgttgtaaaatctccctcttacc
cggccactgtagtgggagagaaattactcgcaaggtaagcagtgtactgtcccgttacgg
caaata------------------------------agaagcagga--------------
ctgtcatgagcagttgacgccaaggt-------------------ctactcttcccagcg
gctgagttgatatggcacat-------------------cactcgttgaattggcgagcc
cctctggt--------------------ctggcagcactctgcatacatggagtaaacat
gccatgatatagacctcgtgcccggtcatatagacgatgcttaaagtcatgaatgtgccc
ttgccgagatggagtatttaatttt-----------------------------ggtcgg
acggattaaaggtgcggtaacccatgaactataactgccaccag----------------
---------------------------------ggaactataaaag--------------
-------aaaacgaattgcg---------------agtccgcaaaccgaaagtggtgtac
ggggagatccggcgtcctctgagtggcaactatgttattgataacctaccagttttcttc
cccaacaaagagccaaggtcaacggcattgccgttggctaatttatgttagtttggtgta
gtcaaaggggaaattatcttacaag-----------------------ctaacatc----
------------------------------------------------------------
----------cccaataaccgctcgatgtcgcgggc
>SEQ4
ggctatcggggagcgagcggtgagttgcacatagaaacactcacaatttctagaactcgg
c----------------------gcttcctcactaacgaactattacaatgcattcggcg
gactccggtccactacaaacgcttttg-----------------ttactttc--------
---------------gttgaaacaattgaggcatacctgttgtaaaatctctctcttacc
cggccactgtagtgggagagaaattaatcgcaatgtaagcagtgtactgtcccgttacgg
taaata------------------------------agtaacagga--------------
ctgtcatgtgcagttgacgccgtgggccgaccctaccatcaacaactattcgtcccagcg
gctgagtcgatatctcacatgtgcaaccagctagacagccactcgtcgaatcg-------
-------------------------tccctggctgcactctgcatacatgcagtaaacat
gccatgatatagacctcgtgcccggtcatatagacgatgcttaaagtcatgaatgtgccc
ttgccgagatggattatttaa--tttcggacatttagatatctcatcctggagcggtcgg
acggaaggaagctccgataacccctaa---------------------------------
----caccaattacattgcataaacgctatgctggcacttttaaaggtatcgaagtcaac
tgggattgacaagaatggcgaaaacatcctggttgagtccgcaaaccgaaagtggtgtac
ggggagatccggcgtcctctgagtggcaactatgttattgataacctaccagttttcttc
cccaacaaagagccaagctcaacggcagtgccgttggccaatttatgttactttggtgta
------------------------------------------------ctaacatcccca
at----------------------------------------------------------
------------------------------------
>SEQ5
gaataacggggggcgttcgttgaatcacacatagacacacgc--------------tcgg
cgaatatcattgcgcgcgtcaccgctctctcagtttagttcgattacaa-----------
-------------tgcttatgcgtttgtcgtacaatcgggaactgtattgtccccggctc
acattcctaggtcg------aacaattgaggcatacctgttgtaaaatctctctcttacc
cggccactgtagtgggagtgaaattaatcgcaatgtaagcagtgtactgtcccgttacgg
taaatacgctattgggaactactaccaagaacagacagaaacagga--------------
ctcgcatgtac------------------------------------actctgcccaacg
gctgagtcgat-----------------agctagacagccactcgtcaaaacggcgcgcg
cctctgctgatcgtaacgaggcaccacccaggctgcactctgcatacatggagtaaacat
gccatgatatagaactcgtgcccggtcatatagacgatgcttaaagtcatgaatgtgccc
ttgccgagatggagtatt-----------------------------cttgagcggtcgg
acggaaggaaggctcc--------------------------------------------
-------------------------------ctgtcacttaaaaag--------------
-------cacaagaatggcga--------------agtccgcaaaccgaaagtggtgtac
ggggagatccggcgtcctctgagtggcaactatgttactaataacctaccagttttcttc
cccaacaaagagccaaggtcatctgcattgccgttgcgtcatgtacgtgggtttggtgta
ttccagggagaaagtatcttacatgtgcctgctaccgacattctgctttcaacagcctga
gtacccgcgtctaccataccctatgccacgctgctacggaggacagctgctccgggcaaa
atgtcgcaacc-------------------------
>SEQ6
gaataacggggggcgctcgttga---------------------------------tcgg
cgaatttcattgcaca--------------------------------------------
-----------------------------atgcaattgggaactggattatccccggctc
acattccgaggtcg------aacaattgaggcatacctgttgtaaaatctccctcttacc
cggccactgcagtgggagagaaattactcgcaatgtaagcagtgtactgtcccgttacgg
taaata------------------------------agtaacaggc--------------
ctgtcatgtgcag------------------cctaccatcaacaactattcgtcccagcg
gctgagtcgatatctcacatgtgcaatcaactagacagccactcgtcgaatcg-------
-------------------------cccctggccgcactctgcatacatggagtaaacat
gccatgatatagacctcgtgcccggtcatatagacgatgcttaaagtcatgaatgtgccc
ttgccgagatggagta-------------------------------------------g
acggattgaaggcgcggtaatccctctactatcactcc----------------------
----taccagttacgtggcataataggtaaactggaactttaaaag--------------
-------aaacagaatggcga--------------agtccgcaaaccgaaagtggtgtac
ggggagatccggcgtcctctgagtggcaactatgttactaataacctaccagttttcttc
cccaacaaagagccaagctcaacggcagtgacgttggccaatttatgttactttggtgta
------------------------------------------------ctaatatcccca
at----------------------------------------------------------
------------------------------------
>SEQ7
gactaatggggggcgatcggtgagttg--------------------ttctaaacctcgg
cgataatcattgcgcgcggcacaactccctcatgaacgcactac----------------
------ggtccactgtatatgcttttgtcgttcaaaggggaactttagttttccccggtc
acattccattttcgtgtgtaaacaattgaggcatacctgttgtaaaatctctctcttacc
cggccactgtagtgggagagaaattaatcgcaatgtaagcagtgtactgtcccgttacgg
taatca------------------------------agaaaaagca--------------
ctgtcatgagcagttgac----------------------------------ccctagcg
gctg----------------------ccagctagacagacactcgtcgaatcggcgcgcg
cctctgatgatcgtaacgagtcacgtccctagctgcactctgcatacatggagtaaacat
gccatgatatagacctcgtgcccggtcatatagacgatgcttaaagtcatgaatgtgccc
ttgccgagatggagga-------------------------------------------g
aaggaatggaggcgcgataatccctcttctatcactcc----------------------
----taccagttacgtggcataataggtaaacttgaacattaaaag--------------
-------aaacagaatggcga--------------aggccgcaaaccgaaactgctggac
ggggagatccggcgtcctctgagtggcaactatgttactaataacctaccagttttcttc
cccaacaaagagccaagtttatcggtatt-------------------------------
--------------------acaagggactgacaccgacatggtgattctaaacc-----
------------------------------------------------------------
------------------------------------
>SEQ8
gactatcggggagcgaacggtgagttgcacatagaaacactcgcgagttcttgacctcgg
c----------------------gctacctcattcacgaactattaccatgcattcggtg
tactacggtccactgcatacggttttg-----------------ttacgttcctgcgctc
acaatcgtatgtggcgtggaaacaattgaggcatacctgttgtaaaatctctctcttacc
cggccactggagtgggagtgaaattaatcgcaatgtaagcagtgtactgtcccgttacgg
taaatg------------------------------------------------------
----cttgagcagtcgaagccaagggccgaccgtatcaccaacaactactcttcccagcg
gccgagtcgatatcacacatgtgcaaccagc-----------------------cgcgcg
cctctgatgatcctaacgagtcacgtccctggctgcactctgcatacatggagtaaacat
gctatgatatagacctcgtgcccggtcatatagatgatgcttaaagtcataaatgtgccc
ttgccgagatggagtatt------------------------------------------
--ggaaggaaggc-----------------------------------------------
----tacccac-------------------------------------------------
-----------------------------------agtccgcaaaccgaaagtggtgtac
ggggagatccggcgtcctctgagtggcaactatgttattaataacctaccagttttcttc
cccaacaaagagccaagctcagcggcagtgccgttggccactccatgttactttggtgta
------------------------------------------------ctaacatc----
------------------------------------------------------------
----------gccaat--------------------
>SEQ9
gactaacggcggacgttcaatgagtaacacatagacacgcccaccagaactaggcctcgg
cgaatattattgcgcgcgtcaccgctctctcattttcgtacgattgcaa-----------
-----------------------------atacaatcgggaactgtatagtcccggggtc
cgattcctaggtcg------aacaattgaggcatacctgttgtaaaatctctctcttacc
cggccactgtcgtgggagagaaattaatcgcaatgtaagcagtgtactgtcccgttacgg
taagta------------------------------agaaagagga--------------
ctgtca-----------------------accgtatcataaacaactactcttcccaggg
gttgagtcgatatcacccatgtgcaaccatctagacacccactcgtcgaatcag------
--------gatcgtaacgag-------------tgcactctgcatacatggagtaaacat
gcgatgatatagacctcgtgcccggtcatatagacgatgcttaaagtcatgaatgtgccc
ttgccgagatgtagtattgga---------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------aggaaggctacccac-------------aggccgcaaaccgaaactgctggac
ggggagatccggcgtcctctgagtggcaactatgttactaataacctaccagttttcttc
cccaacaaagagccaagctcaatagcagtgccgttgggcaatttatgtttccttggtgta
------------------------------------------------cttatatcccca
at----------------------------------------------------------
------------------------------------
>SEQ10
ggctatcgggcagcgagcgttgagttgcacatagaaacactcacaatttcttgaagtcag
c----------------------gcttcctcactaacgaactattacaatg---------
-------------------ctctttgg-----------------ttacttt---------
--------------------aacaattacggcatacctgttgtaaaatctctctcttacc
cggccactgtagtgggagagaaattaatcgcaatgtaagcagtgtacagtcccgttacgg
taaata------------------------------agtaacaggc--------------
ctgtcatgtgc------------------acgctaccatcaacaactattattcccagcg
gttgaatcgatacctaacatgtgcaatcaactagacagccactcgt------g-------
-------------------------cccctgggcgcactctgcatacatgcagtaaacat
gccatgatatagacctcgtgcccggtcatatagacgatgcttaaagtcatgaatgtgccc
ttgccgagatggattcttaaggctccctgtcacttaaac---------------------
------------------------------------------------------------
------------------------------------------------------------
--------acacgaatggcggg----------------ccgcaaaccgaaactgctggac
ggggagagccggcgtcctctgagtggcaactatgttactaataacgtaccagttttcttc
cccaacaaagagccaagctcaagggcagtgcctttggccaatttatgtgacttaggtgta
------------------------------------------------ccaat-------
------------------------------------------------------------
------------------------------------
>SEQ11
gactaatggggggcgatcgttgagttg--------------------ttctaaacctcgg
cgataatcattgcgcgcggcacaactccctcatgaacgcactac----------------
----------------------------ggtccgaaggggaactttaattttcaccggtc
acattccatcttcgtgtttcaacaattacggcatacctgttgtaaaatctctctcttacc
cggccactgtagtgggagagaaattaatcgcaatgtaagcagtgtacagtcccgttacgg
taaata--------------------------------------ga--------------
gtgtcatagaca--------------------------------------cttcccagct
gctgatttgatctcacacatgtgcacccagctagtcagccactcgtcgataccgtgcgcg
cctctgctgatcgtgacgatttacttccctggctgcactctgcatacatggagtaaacat
gccatgatatagacctcgtgcccggtcatatagacgatgcctaaagtcatgaatgtgccc
ttgccgagattgagtctttaggctccctgtgacttaaa----------------------
------------------------------------------------------------
------------------------------------------------------------
-------aacacgaatgcc----------------ggtccgcaaaccgaaagtggtgtac
ggggagatccggcgtcctctgagtggcaactatgttactaataacctaccagttttcttc
cccaacaaagagccaaagtcatcagcattgccgttgcgtaatgtacgtgggtttggtgta
ttccaaggcgaaaatatcttacgagc---------------------tctagcagcctgc
gtacccgcgtctaccataccctgtgccaggctgctaggtcagacgg--------------
----------cccaataaactcgcgatg--------
>SEQ12
gactaatggggggcgatcgttgagctg--------------------ttctaaacctcgg
cgatactcattgcgcgcggcacgattccctcatgaacgcactac----------------
----------------------------gggccgatggggaactttaattttcaccggtc
acattccatcctcgagtatcaacaattgaggcatacctgttgtaaaatctccctcttacc
cggccactgtagtgggagagaaattactcgcaatgtaagcagtgtactgtcccgttacgg
taaata--------------------------------------ga--------------
ctgtcat----------------------------------------acagtacccagct
caagattcgat---------------------agtcagcgattcgtccctaccg------
---------------accttttacttccatggctgcactctgcatacatggagtaaacat
gccatgatatagacctcgtgcccggtcatatagacgatgcttaaagtcatgaatgtgccc
ttgccgagatggattatttaatttc-----------------------------ggtcgg
acggattgaaggcgcggttacccctgaactataactcc----------------------
----caccagttacctggcataacaggtatgctgcaactttaaaag--------------
-------aagaagaatggtga--------------agtctgcaaactgaaagtgctgtac
ggggagatccggcgtcctctgagtggcaactatgttactaataacctaccagttttcttc
cccaacaaagagccaacctcaatagcattgccgttgggcaatttatttttccttggttta
------------------------------------------------ccaat-------
------------------------------------------------------------
------------------------------------
>SEQ13
gactaactgggggcgatcggtgagttgcacataggaacacgcacgagttttagacctcgg
cgattctcatggctacca------------------------------------------
------ggtcgtcttaatatgtattcgtcgttcaaacggg---------------cgctc
acattcttattt--------aacaattgaggcatacctgttgtaaaatctctctcttacc
cggccgctgtcgtgggagagaaattaatcgcaatgtaagcagtgtactgtcccgttacgg
taaata--------------------------------------ga--------------
ctggcat----------------------------------------acaggacccagct
caagatccgat---------------------actcagcgatgcgtccctaccg------
---------------accttttacttccatgg--gcactctgcatacatgcagtaaacat
gccatgatatagacctcgtgcccggtcatatagacgatgcttaaagtcatgaatgtgccc
tcgcagagatggattcttaaggttc-----------------------------------
------------------------------------------------------------
-------------------------------ctgtcacttaaagg---------------
-----------------------------------ggtccgcaaaccgaaagtggtgtac
ggggagatccggcgtcctctgagtggcaactatgttattaataacctaccagttttcttc
cccaacaaagagccaagctcaacggcagtgacggtggccaatttatgttactttggagta
tccccaat----------------------------------------------------
------------------------------------------------------------
------------------------------------
>SEQ14
------------------------gactacatagaaacacgcacgagttctagccctcgg
cgattatcaatgcgcgcgtcacagctccctcttttagccactat----------tcggcg
gactacggtccaatgcatatgcttttgtcgttccgacgggaaatttactt----------
--------atttcgggtggaaacgattgagccatacctgttgtaaaatctctctcttacc
cggccactggagtgggagtgaaattaatcgcaatgtaagcagtgtactgtcccgttaccg
ta---a---------------------------tcaagaaacagca--------------
cggtcatgagcagtagac----------------------------------ccctaacg
gctg----------------------------------------------------cgcg
cctctgatgatcgtaacgagtcacgtctcaagctgcactctgcatacatggagtaaacat
gccatgatatagacctcgtgcccggtcatatagacgatgcttaaagtcatgaatgtgccc
ttgccgagatggat--ttaaggcactgtcacttaaactcaagaattgc------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------ggtccgcaaaccgaaagtggtgtaa
ggggagatccggcgtcatctgagtggcaactatgtgactaataacctatcagttttcttc
cccaacaaagagccaaagtc-----------------cgaatttatgttagtttggtgta
ttcca---------------------gactgccaccgacatgctgattctatcattctgc
gtat--------------------------------------------------------
------------------------------------
>SEQ15
------------------------------------------------------------
-------------gaataacgggggtcgctcgttgagc----------------------
---------acaatgc--------------------------------------------
-------------------aaacaattgaggcatacctgttgtaaaatctctctcttacc
cggccgctgtcgtgggagagaaattaatcgcaatgtaagcagtgtactgtcccgttacgg
taaaga---------------------------ctgtcatacagcacctagctcaagatt
cggtagtcagcgatacgt----------------------------------ccctactg
acct----------------------------------------------------tttg
cttccatc-----------------------cctgcactctgcatacatgcagtaaacat
gccatgatatagacctcgtgcccggtcatatagacgatgcttaaagtcatgaatgtgccc
ttgccgagatggattcttaaggctc-----------cctgtcaattaa------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------cgtccgcaaaccgaaagtggtgtaa
ggagagatccggcgtcatctgagtggcaactatgtgactaataacctatcagttttcttc
cccaacaaagagccaaagtc-----------------cgaatttatgttagtttggtgta
ttcca---------------------gattgccaccgacatgctgattctaccataatgc
ggat--------------------------------------------------------
------------------------------------
>SEQ16
gacgaattgggtg----------------------------------ttctaaccctcgg
cgataatcattgcgcgcggcacaactccctcatgaacgcactac----------------
------ggtgcactgtatatgcttttgtcgttcaaagggggactttcatt----------
--------------------aacaattgaggcatacctgttgtaaaatctccctcttacc
cggccactgtagtgggagagaaattactcgcaaggtaagcagtgtactgtcccgttacgg
taaata------------------------------ataaacggga--------------
ctgtcatgagcagttgatgccgagggccgaccgtatcatcaacaactactcttcccaccg
gcggagtcggtctgacacatgttcaaccagctagaca---------cgaatcggcgcgcg
cctctgatgatcgtaaccag-------------tgcactctgcatacatggagtaaacat
gccatgatatagacctcgtgcccggtcatatagacgatgcttaaagtcatgaatgtgccc
ttgccgagatggagtatggaa---------------------------------------
------------------------------------------------------------
-------------------------ggaacgttaccac----------------------
-----------------------------------agtccgcaaaccgaaagtggtgtaa
ggggagatccggcgtcatctgagtggcaactatgtgactaatcacctatcagttttcttc
cccaacaaagagccaaagtcatcagcattgctgttgcgtaatgtacgtgcgtgtggtgta
ttctaaggcgacaatatcttacgtgc---------------------tctagcagcctgc
ttacccgggtctaccatactctgtgccaggatgctaggtcagacgg--------------
----------cccaataaactcgtgatg--------
>SEQ17
gaataacggggggcgctcattga---------------------------------tcgg
cgaatttcattgc-----------------------cgcaattg----------------
--------------------------------------ggaactggattagccccggctc
acattaccaggtcg------aacgattgagccagacctgttgtaaaatctctctcttacc
cggccactggagtgggagtgaaattaatcgcaatgtaagcagtgtactgtcccgttaccg
taaaca------------------------------agtaacaggc--------------
ctgtcatctgc------------------acgctaccatcaacaagtattattcacagcg
gttgaatcgattcctaacatgtgcattcaactagatagccattc----------------
--------------------------------gtgcactctgcatacatgcagtaaacat
gccatgatatagacctcgtgcccggtcatatagacgatgcttaaagtcatgaatgtgccc
ttgccgagatggattctttag---------------------------------------
------------------------------------------------------------
--------------------------gcgccctgtgacttaaaacg--------------
-------aatgcc----------------------ggtccgcaaaccgaaagtggtgtaa
ggagagatccggcgtcatctgagtggcaactatgtgactaataacctatcagttttcttc
cccaacatagagccaactttatcggtattacaagggactgattg----------------
------------------------------------------------caaac-------
------------------------------------------------------------
------------------------------------
>SEQ18
gactcatgttgcgcgattactaag------------------------------cctcgg
ccatactcactgcgcgcggcacctttccatcatgaacgcactac----------------
--------------------------------------gcaactttaattttcaccggtc
acattccatcttcgagtatcaacgattgagccatacatgttgtaaaatctctctcttacc
cggccactggagtgggagtgaaattaatcgcaatgtaagcagtgtactgtcccgttaccg
taagta------------------------------acaaagagga--------------
ctgtca---------------------------------aaacaacttctcttcccagtg
gtcgattggatatcccccatgagcaaccatccagccacctactcatcgaatcag------
---------------------gctcgtaacgagtgcactctgcatacatggagtatacat
gcgatgatatagacctcgcgcccggtcatatagacgatgcttaaagtcatgaatgtgccc
ttgccgagatgtagtatttgatttc-----------------------------ggtcgg
acggattgaaggcgtgttaaacccggaactat----------------------------
--------------------------acatgctggaaccttaaaag--------------
-------aaaaacaatgacga--------------agtccgcaaaccgaaagtggtgtaa
ggggagatccggcgtcatctgagtggcaactatgtgactaataacctatcagttttcttc
cccaacaaagagccaactttataggtattataagggacggattg----------------
------------------------------------------------ctaac-------
------------------------------------------------------------
------------------------------------
>SEQ19
gactaacggggggcgattgttg-----------------------agatctagacctcgg
ctattatcattgcgcgcgtcaccgctctctcattttcgtactattacta-----------
-------------tgcttatgtttttgttgttcaatcgggaccttgatattcccgggctc
acattcctacttcg------aacaattgaggcatacctgttgtaaaatctctctcttacc
cggccactgtagtgggagagaaattaatcgcaatgtaagcagtgtactgtcccgttacgg
taaata------------------------------agaaccagga--------------
atgttatgagcagtttacgccgaaggccgaccgtagcatcaacaactattcttcccaccc
gctgactcgatatcacacatgtgcaaccagctagacagcgactcgtcgaatcggcgcgcg
cctctgatgatcgtaacgagtcacgtccatggctgcactctgcatacatggagtaaacat
gccatgatatagacctcgtgcccggtcatatagacggtgcttaaagtcatgaatgtgccc
ttgccgagatggattatttaa--tttcgaaattttagatgtctcaacctgg---------
-------------------acccctgtattataactcctgcaagtcaacggcccctgtcc
ctaacaccaattacattgcatgaacggtatgccggcactttaaaaggtatcgaagcc---
--------------atggcgaaaacatcctggttgaggccgcaaaccgaaactgctggac
ggggggatccggcgtcctctgagtggcaactatgttactaataaccttccagttttcttc
cccaacaaagagccaaggtcatcaacagtgccgttccgtaatgtacgtaggtttggtgta
ttccaaggcgaaattatcttacaattgagtgacaccgccattctgcgtctaccat-----
-----------------actctatgccaggctgctaaggagcacagctgctccgggcaaa
ggtctgacggcccaataaactcacgatgtcccacca
