>SEQ0
gcgttatccaagatcattgtgccctacagtgccatatctatgcggtatagattgcggacg
agtcagggattgtttc----aaatcacgacactcaggccagtaccatactagctatcaca
catcggtcaagggcggaggcggggactagaactgtggttaattgaagtggtcgcagcata
caaccgctagcgtcacacgaggcattaaagtggggcaatggtactgtgggactaaacatg
ctagggagccgttccaccctaagcgtgacgtcagaggatatctacgtaagtgtcgaccgg
cgcttcctatgacgatttcgagtgcgcgttgtgatacacgtctgtgaacgaaactgaatt
tgaatcttcaggttccgggcgggccttttagtatgggttgacgttggggaattagcggac
caagacgttgtgctctggaatcagcacaggaaatgccatgctagatacactataaggtag
accacttattagttaccca----cctagctgttctctctgcccaacattcccaacaacat
cgcatcagtgaagagtcgttttggctttcaggggacgaagggcccaagcacgaattttca
tgggcggcgacatactttttgagaccccgaaagtggtcaagatcggttgtgccggtacca
gacaacaattgtgtttggggggcttcgcacagttagattcagcaaccctttaatgtagcg
gatgcatttcgcaccaagtatgctggggtagcagcatacgcagccgagaaacacattgga
aactttaccgttccacccgaacccatttgttcctgaagcttatctcaaccgcaactccag
tacagtggaggaacatgtcgctgatcgagcggaatctgagagcaaatggtgggtcggcag
gcccacgacgtaaggggatgagcagtaaagttttatatgccttttaagcgcgatttatat
aacttgtcttagcatcctcacgatcgaggagcgattgacataaggaaaccaacatcttcg
tttattttgacccgcttcagccacaaagctgatgaagagtgtaatggggggtcaacgtgg
cgaccagtcaggccgcccgttgtggaaa
>SEQ1
gcgttagccaagagcgttgcgccctccagtgccatatctatgcggtatggattgcggacg
agtcagggatttttta----aaatcacgacactcagggcagtaccatactagctctcacg
catc--------------------actagaagtgtggttaattgaagcggtcgcagcata
caaccggtagagtcacacgaggcattaaagtggggcaatggtactgtgggactaaacatg
ctagggagccgttcc-------gcgtgacgtcagaggatatctacgtaagtgtcgaccgg
cgcttcctatgacgatttcgagtgcacgttgtgatacaagtctgtgaacgaaactgtatt
tgaat--------------cgggccttttagtatgggttgacgttggggaattagcgtac
caagactttgtgctatggaatcagcacaggaaatgcgatgctcgctacactttaaggtag
accacttattagttaccca----cctagctgttctctctgcccaacattcccaacaacat
cgcatcagtgaagagtcgttttggctttcaggggacgaagggcccaagcacgaattttca
tgggcggcaacatactttaagagcccccgaaagtgttcaagatcggttgtgccggtacca
gacagcaattgtgtttgggtggcttcgcccagtta---------------------agcg
gatgcatttctcgacaagtgtgctggggtagcagcatacgcaaccgagaaacacggtgg-
---------------------cccatttgttcctgaagcttatctcaaccgcaactccag
tacagtggaggaacatgtcgctgatcgagcggaatctgagagcaaatggtgggtcggcag
gcccacgacgtaaggggatgagcagtaaagttttatattccttttaagcgccattgatat
aactggtcttagcatccgcacgatcgagacgcgcttgacataaggttaccaacatcttcg
tttattttgacccgcttcagccacaaagctgatgaagagtgtaatggggggtca------
----------------ccgttgttga--
>SEQ2
gcgttatccaagatcattgtgcattat--------------------tagattgcggacg
ag------------------------------tcaggcgagtactatactagctatcaca
catcagtcaagggcggaggtggagactagaactgtggttaatggaagagatcgccacata
caaccgctagcgtcacacgaggcattaaagtggggcaatggtactgtgggactaaacatg
ctagggagccgttccaccctaagcgtgacgtcataggatatctacgtaagtgtcgaccgg
cgcttcctatgacgatttcgagcgcgcgttgtgaaacacgtttgtgaccgaaactgaatt
tgaatcttcaggttccgggcgggcgttttagtatgggttgaccttgggtaattagaggac
caagacgttgtgctctggaatcagcaaacgaaatgcaatgctagatacactttaaggtag
accacttattagttaccca----catagctattctctctgcccaacattcccaacaacat
cgcatcagtgaagagtcgtattggctttcaggggacgaagggcccaagcacgaattttca
tgggcggcgacatactttttgagac---------------------ttgtgccggtacga
gacaacaattgtgtttgggggggtccgcacagttagattcagcaaccctttaatgtagcg
gatgcatttcgcacctagtatgctggggtagcagcatacgcagccgagaaacacattgga
aactttgccgttccacccgaacccatttgttcctgaagcttatctcaaccgcaactccag
tacagtggaggaacatgtcgctgatcgagcggaatctgagagcaaatggtgggtcgggag
gcccacgacgtaatgggatgagcggtaaagttttatattccttttaagcgccattgagat
aactggtcttggcaaccgcacgatcgagacgcgcttgacatgagcttaccaacatcttcg
ttaattttgatccgcttcagccacaacgcttataaagagtgtaatggggggtca------
----------------ccgttgttga--
>SEQ3
gcgttatcaaagatccttgtgcattat--------------------tagattgcggacg
ag------------------------------tcaggcgagtactatactagctatcaca
caaaagtcaacggcggaggtggagacaggatgtgtggttaacggaagggatcgccacata
caaccgc-----------------ttaaagtggggcaatggtactgtgggactaaacatg
ctagggagccgttcc-------gcgtgacgtcagaggatatctacgtaagtgtcgaccgg
cgctgcctatgacgatttcgagtgcacgttgtgatacaagtctgtgaacgaaactgtatt
tgaat--------------cgggccttttagtatgggttgacgttggtgaa---------
------------------aatcagcacaggaaatgcgatgctcgctacgctctaaggtag
accacttattaggtaccca----cctagctgttctctctgcccaacattcccaacaacat
cgcatcagtgaagagtcgttctggctttcaggggacgaagggcccaagcacgaattttca
tgggcggcgacaaactttttgagaccccgaaagt-------------------ggtccca
gacaacaattgtgtttggggtgcttcgcatagttagtttcagcaacact-----------
--------------caagtatccgggggtagcagcatatgcagccgagaaagacattgga
aactttaccgttccacccgaacccatctgttcctgaagcttatctcaaccgcaactccag
tacagtggaggaacatgtcgctgatcgagcggaatctgagagcaaatggtgggtcggcag
gcccacgacgtaatgggatgacaggtaaagttttattttccgtttaagcgccgttgcgat
aactggtctgggcaaccgcacaatcgagacgcgctcgagatgagcttaccaacttcttcg
ttaattttgatccgctgccgccacaagacttacaaagagt--------------------
----------------ccggtgttga--
>SEQ4
ccgttagccgagagcgttgcgccggctagttacatatctatgcggtatgcattgcggacg
agtcagggatttttta----aattcacgacactcagggcagtaccatactagctctcacg
catc--------------------actggaagtgtggttaattgaagcagtcccagcata
caaccagtagagtcaaacgaggcattaaagtggggcaatggtactgtgggactaaacatg
ctagggagccgttcc-------gcgtgacgtcagaggatatctacgtaagtgtcgaccgg
cgcttcctaggacgttttcgagcgcgcgttgtgaatgacgtttgtgaccggaactgaatt
tgagtcttcaggttccggccgggcgatttagtatgggttcaccttgggtaattagatgac
cacgatgttgtgaacttgaatcagcaaacgaaatgcaacgctagatacacttaagggtag
accacttattcgttaccca----cagagctgttctctatgcccaacattcccaacaacat
cgcatcagtgaagagtcgttctggctttcaggggacgaagggcccaagcacgaattttca
tgggcggcgtcatactttttgagac---------------------tagtgccggtacga
gacaacaattgtgtgcgggtggttccgcacagttagattcagtaaccctt----------
------------------tatgctggggtagcagcttacggagccgagaaacccattgga
aacttttccgttccacccgaacccctttgttcctgaagcttatctcaaccgcaactccag
tacagtggaggaacatgtcgctgatcgagcggaatctgagagcaaatggtgggtcggcag
gcccacgacgtaatgggatg--------aattttatgttccttttaagcaccattgaaat
aactggtcttagcatccgcacgatcgagacgccctttacgtaacgttaccaacatcttct
tttatggt---------------------------agagtg-------------------
----------------ccgttgttga--
>SEQ5
ccgttagctgagagcgttgcgcct------------------------------------
gcttgtgacttttttg----aatccacgacactaagggcagtaccatacttgcgctcacg
catc--------------------actcgaattgtggttaattatagcagtcccagcatg
cgcccagtagggtcaaacgaggcataaaagtggggcaatggtactgtgggactaaacatg
ctagggagccgttccaccctaagcgtgacgtcagaggatatctacgtaagtgtcgaccgg
cgcttcctgggacgcttgcgaccgcgcgatgagaatgacgtttgtgaccggaactgaatt
tgagtcttcaggctccggccgggcgcttaagaatgggttaaccttgggtaattagatgac
cccgatgttgtgaacttgaatcagcaaacgaaatgcaaccctgtatacacttaagggtaa
a---------------cca----cagagctgttctctctgcccgacattcccaacaacat
cgcatcagtgaagagtcgttttggctttcaggggacgaagggcccaagcacgaattttca
tgggcggcgacatactgtttgagac---------------------ttgtgccagtacaa
gccaacaattgtgtttgggggcgtccgcacagtaagattcattagccctttaatgtagcc
--------------ctagtttgctg------------------ccgggaaac--------
----------ttccacccgaacccatttgttcctgaagcttatctcaaccgcaactccag
tacagtggaggaacatgtcgctgatcgagcggaatctgagagcaaatggtgggtcgggag
gcccacgaggtaacgggatgacaggttaagttttcttttccgtttaagcgccgttgcgaa
aacaggtcggcgcaaccgcacaatcgagacgcgctcgagatgagctcaccaacttcatcg
ttaattttgatccactgccgccacaagaattacaaagagt--------------------
----------------ccggtgttgt--
>SEQ6
gagttatcaaagataattgtgcattat--------------------tagattgcggacg
agtcaggctagctatcacacaaaagacaacggccgaggtggagacaggaggtcaaccgc-
------------------------------------------------------------
------------------------ttaaagtggggcaatggtactgtgggactaaacatg
ctagggagccgttcc-------gcgtgacgtcagaggatatctacgtaagtgtcgaccgg
cgcttcctgggtcgcctgcgaccgcgcgatgagaatgatgtttgtgaccggacctgaa--
------------------tcgggcgcttaagattgggttaaccttgggtaattagatgac
accgatgttgtgaacttgaatcagcaaacgaaat-----------------------gga
acc-----ctgtatacact----tagagctgttctctctgcccaacattcccaacaacat
cgcatcagtgaagagtcgttttggctttcaggggacgaagggcccaagcacgaattttca
tgggcggcaagatactttaagatcccccgaaagtgttcatgatcggtcgtgccggtgcct
gacagaagtagtgttagggtggcttcgcccagttaagccgatacatttctcga-------
--------------caagtttgctggggtagcagcatacgcaagcgaggaacacgctgg-
---------------------cccagttgttcctgaagcttatctcaaccgcaactccag
tacagtggaggaacatgtcgctgatcgagcggaatctgagagcaaatggtgggtcggcag
gcccacgacgtaatgagatga----------------------------------ataag
tactggtcttagcatccgcacgatcgagacgccctttacataacgtaaccaacatcttct
tttacgtg----------------------------------------------------
----------------ccgttgttga--
>SEQ7
gcgttatcaaagataactgtgcattat--------------------tagattgcggacg
agtcagg-------------aaaagacaacggccgaggtggtgac-------ctaccgc-
------------------------------------------------------------
------------------------ttaaagtggggcaatggtactgtgggactaaacatg
ctagggagccgttcc-------gcgtgacgtcagaggatatctacgtaagtgtcgaccgg
cgcttcct---ttgaccacttcccgaagctgaatttgat-----tgatcaggttacgg--
------------------gcgggcgttttagtgtgggttgaacttggctaaatagagga-
----------------acgatacgcaaacgaaat-----------------------tag
accacttattggttaccca----catagctattctctctgcccgacattcccaacaacat
cgcatcagtgaagagtcgtattggctttcaggggacgaagggcccaagcacgaattttca
tgggcggcaagatactttaagatcccccgaaagtgtatatgatcggtcgtgccggtgcct
gacagaagtagtg-----------------agtta-----------ttctcga-------
--------------caagtttgctgggctagcagcatacgcaagcgagtaacacgatgg-
---------------------ccgagttgttcctgaagcttatctcaaccgcaactccag
tacagtggaggaacatgtcgctgatcgagcggaatctgagagcaaatggtgggtcggcag
gcccacgacgttatgagatga----------------------------------ataag
tactggtcttagcatccgcacgatcgagacgccctttacatcacgtaaccaacatctt--
------------------------------------------------------------
----------------ccgtggttga--
>SEQ8
gcattatccaagatcattgtgccctgcagggccatatctatgcggtatagaatgccgacg
agtcagggattgtctc----aaatcacgacactcaggccaataccataatagctatcac-
---c--------------------actagaacagtggttaattgacgtggtcgcggcata
cgaccgctagcgtcacgcgtggcataaaagtggggccatggtactgtgggactaaacatg
ctagggagccgttccaccctaagcgtgacgtcagaggatatctacgtaagtgtcgaccgg
cgcttcctaggacatttgcgagcgaacg-----------------gaccggtactgaatt
tgagtcttcagtttccggccgggcgatttagaatgcgttcgcctggggtaattggatgac
cacgacgttgtgaacgtgaatcaacaaacgaaaagcaacgcaagatacacttaagggtag
accacttattcgttaccca----ctgagctattctctctgcccgacattcccaacaacat
cgcatcagtgaagagtcgtattggctttcaggggacgaagggcccaagcacgaattttca
tgggcggcgacatactgtttcagac---------------------ttgtgccagtccaa
gccaacaatt-------------------cagtaagattcattagccctttaatgtagc-
------------------------g------------------ccgggaaac--------
----------ttccacccgaacccatttgttcctgaagcttatctcaaccgcaactccag
tacagtggaggaacatgtcgctgatcgagcggaatctgagagcaaatggtgggtcggcag
gcccacgacgtaatggg---------------------tccgtttaagcgccggggcaat
aattggcctgggcaaccgcacaatcgaggggcgctcgagatgggcttaccaacttcctcg
ttaatattgagccgctgccgccacaagactaacaaagagt--------------------
----------------ccggtgatga--
>SEQ9
gcgttagccaagagggttgcgccctccagtgccgcatcgatgtggtatggatcgcggaca
agttagggatttctta----aaaccccgacactcagggcagtgccatactagttctcacg
catc--------------------actagaagtgtggttaattgaagcggtcgcagcata
caaccggtagagtc----------ttaaagtggggcaatggtactgtgggactaaaaatg
ctagggagctgttcc-------gcgtgacgtcagaggatatctacgtaagtgtcgaccgg
cgcttcctaggacatttgagagcgaacg--------------------------------
-----ggccagtttccgg--------------------------------attggttgac
cactacgttgtgaacgtgaatcaataaacgaaaagcaacgcaagatacacttaaggggag
accacttaatcgttaccca----ctgatctgttctctctgcccaacattcccaacaacat
cgcatcagtgaagagtcgttttggctttcaggggacgaagggcccaagcacgaattttca
tgggcggcgacaagcttattgagaccccaaaag-------------tggtcccgg-----
----------------agggtgcttcgcatagttagtttcagcaaccct-----------
--------------caaggatccgggggtagcagcacatga-------------------
--------------------------tcgttcctgaagcttatctcaaccgcaactccag
tacagtggaggaacatgtcgctgatcgagcggaatctgagagcaaatggtgggtcggcag
gcccacgacgtaatgggatgacaggtaaagttttattttccgtttaagcgccgttgtgat
aactggtctgggcatccgctgaatcgagacacgctcgagatgagcttaccaacttcttcg
ttaattttgatacgctgccgcga-------------------------------------
----------------ccggtgttga--
>SEQ10
ccgttagccgagagcgttgagccggctattttcctaaccatgcggtacgcatcgcggacg
agtcagggatttttta----aattcacgacactctgggcagtacaatactagctctcacg
catc--------------------actggaagtgtggttaattgaagcagtcccagcata
caaccagtagagtcaaactaggcataaaagtggggcaatggtactgtgggactaaacatg
ctagggagccgttccaccctaagcgtgacgtcagaggatatctacgtaagtttcgaccgg
ctctgcctatgccgatttcgagtgcacgttgtgatacaagtctgtgaacaaaactgtaat
tgaat------------------------agtatcggtttacgttggtgaa---------
------------------aatcagcacaggaaatgcgatgctcgttaagctctaaggt--
--------------------------agctgttctctccgcccaacattcccaacaacat
cgcatcagtgaagagtcgttctgggtttcaggggacgaagggcccaagcacgaattttca
tgggcggcgacgtactgtttgagac---------------------tcgtgccggaacaa
gccaataattttgtctgggggagtccgcacagtaagattcattagccctttaatatcgcc
--------------ctagtttgctg------------------ccgagaaaca-------
-----------tctacctgaacccatttgttcctgaagcttatctcaaccgcaactccag
tacagtggaggaacatgtcgctgatcgaccggaatctgagagcaaatggtgggtcggcag
gcccacgacgtaatgtgatg--------aattttatgttccttttaggcaccattgaaat
aactggtcttagcaac----------------------------gtaaccaac-------
-----------------------------------agtgta-------------------
----------------ccggtgttga--
>SEQ11
gcgttatccaagatcattgtgcattat--------------------tagattgcagacg
agtcagg---------------------------------------------------ca
catccctcaagggcggaggtggagtttagaactgtggttaatcgaagagatcgccacata
caaccgctagcgtcacgcgaggcattaaagtggggcaatggtactgtgggactaaacatg
ctagggagccgttcc-------gcgtgacgtcagaggatatctacgtaagtgtcgaccgg
cgcttcctaggacattttcgagtgcgcgttgttactgacgttt-----------------
-------------ttcggccgggagaatt---------------------attagatgac
gtcggtgttgtgaacttgaatgagcgaacgcaatgcaacgctagatgcacttaagggtag
accacttattcgttaccc----------ctgttctctctgcccaacattcccaacaacat
cgcatcagtgaagagtcgttttggctttcaggggacgaagggcccaagcacgaattttca
tgggcggcgacatagtgtttgagac-----------------------------------
--tttcaattgtgtttgggggcg-----------------------cctttaatgtaacc
--------------ctagtttgct------------------------------------
----------ttccacccgaacccatgtgttcctgaagcttatctcaaccgcaactccag
tacagtggaggaacatgtcactgatcgagcagaatctgagagcaaatggtgggtcggcag
gcccatgacgtaatgggatgacgggtaaagttttattttcctttcaagcgccgttgcggt
aactggtct-----------------------gttcgcggtaagtttaccaacttcttcg
ttaattttgatccgctgccgccact-----------------------------------
----------------ccggtgttga--
>SEQ12
gccttatctaagggc-----------------catatctgtgcggtatagaatgccgacg
a------------------------acgacgcgcaggccaataccataatagctatcacc
------------------------actagaacagtgggtaatggacgtggtcgcggc---
-----------gtcacgcgttgcattaaagtggggcaatggtactgtgggactaaacatg
ctagggggccgttcc-------gcgtgacgtcagaggatatctacgtaagtgtcgaccgg
cgcttcctaggacgttttcgcgcgagggttgtgaatgacgtttgtggtcggaactggatt
tgaat-----------------------ttgtatgggtccaccttgggtaactagatgac
catgatagggtgaacttgaatcggcgcacgaaattaatcgttagatacacttaagggtag
tccactaattcgttacgca----cagagctgttctctctgcccaacattcccaacaacat
cgcatcagtgaagagtcgttttggctttcaggtgacgaagggcccaagcacgaattttca
tgggcggcgacaaactttctgagacaccgaaagtc-------------------gtccca
gacaacaattgtgtttgggatgcttcgcctatttagtttcaacaacaat-----------
--------------caactatgcgggggtagtagcatatgcggccgagaaagacattgga
aactttaccg-----------------tgttcctgaagcttatctcaaccgcaactccag
tacagtggaggaacatgtcgctgatcgagcggaatctgagagcaaatggtgggtcggcag
gcccacgacgtaatgggatgacatgtaaagttttattttgcgtttaagcgccgttgtgat
aactggtctgggcatccgctgaatcgagacacgctcttgatgagcttaccaacttcttcg
tta---------------------------------------------------------
----------------------------
>SEQ13
gcgttcctaaagagggttgcgacctccagtgccgcatccaagtggtatggatcgcggaca
agttagggatttctga----aaaccccgacactcagggtagtgccatactagttctcaca
caac--------------------actagaagtgcggttaattgaagcggtcgcagcata
caacccgtagagcc----------taaaagtggggcaatggtactgtgggactaaacatg
ctagggagccgttccaccctaagcgtgacgtcagaggatatctacgtaagtttcgaccgg
ctcttcctgggacgcttgccaccgcgcgatgagaacgacgtttgtgaacggaactga---
------------------cccagtgcttacgaatgggttaaccctgggtaa---------
--------------cttgaatcagcaaacggaatgcaaccctctatacacttaagggtaa
a---------------ccc----cagagctgttctctctgcccaacattcccaacaacat
cgcatcagtgaagagtcgttgtggctttcaggggacgaagggcccaagcacgacttttca
tgggcggcaacgtactgtttgggaccccgaaagcggtcaagaccggttgtgccggtacca
gaaaac-----------------------------------------------tgtagcg
gatgcatttcgcaccaagtatgctg-----------------------gaacacattgga
aactctaccgttccacccgaacccattcgttcctgaagcttatctcaagcgcaactccag
tacagtggaggaacatgtcgctgatcgagcggaatctgagagcaaatggtgggtcgggag
gcccacgacgtaatgagat----------------------------------ccataag
tactggtcttagcatccgcacgatcgagacgctgtctacccaaagtac------------
------------------------------------------------------------
----------------------------
>SEQ14
------------------------gacagtgccatatctatgcggtatagattgcggacg
agtcagggattgtttc----aaaccacgacac-----------------tagctatcaca
catcggtcaagggcggaggcggggactagaactgtggttaattgaagtggtcgcagcata
caaccgctagcg------------ttaaagtggggcaatggtactgtgggactaaacatg
ctagggagccgttcc-------gcgtgacgtcagaggatatctacgtaagtgtcgaccgg
cgctgcctgtgccgatttcgagtgcacgttgtgatacaagtctgtgaacaaaactgtaat
tggat------------------------agtataggtttacgtaggtgaa---------
------------------aatcagcacaggaaatgcgatgctccttaagctctaaagt--
--------------------------agctgttctctctgcccaacattcccaacaacat
cgcatcagtgaagagtcgttttggatttcaggggacgaagggcccaagcacgaattttca
tgggcggcgccgtccagtttgagac---------------------tcgtgcgggaacaa
tccaataatattatctgggggagtccgcacagtaagattaattagccctttaatctcgac
--------------ctagttttctg------------------cctagaaac--------
----------atctacctgaacccatttgttcctgaagcttatctcaaccgcaactccag
tactgtggaggaacatgtcgctgatcgagcggaatctgagagcaaatggtgggtcggcag
gcccacgacgtaatggg-------------------------------------------
-----------gtaaccgcacaatcgagcgtcgctcgggatgggcttaccaacttcctcg
ttattattgagccgctgccgccacagggcttacaaagggt--------------------
----------------ccggtgctca--
>SEQ15
ccgttagctgagagcgttgagccggctattttcctacccatggggtaagcatcgcggacg
agtgagggatttttta----aactcattacactctgggcaggacaatactagctctcac-
------------------------actggaagtggggttaattgaagcagtccca-----
--------------aaacgaggccttaaagtggggcaatggtactgtgggactaaacatg
ctaggaagccgttcc-------gcgtgacgtcagaggatatctacgtaagtgtcgaccgg
cgcttcctgggtcg-----------------------acgtttgtgaccgcaccagagtt
--------------------gggcgattaagattgggttaacctggggtaattagatgac
cccgatgttgt-------------------------------------------------
-----ctatttgatacact----tagagctgttctctctgcccaacattcccaacaacat
cgcatcagtgaagagtcgttttggatttcaggggacgaagggcccaagcacgaattttca
tgggcggcgacatactgtttcagac---------------------ttgtgccagtccaa
gccaacaatt-------------------cagtaagattcattagcccg-----------
-------------------------------------------ccgggaaac--------
----------ttccacccgaacccatttgttcctgaagcttatctcaaccgcaactccag
tacagtggaggtacatgtcgctgatcgagcggaatctgagagcaaatggtgggtcggcag
gcccacgacgtatagggatgacgggtaaagttttatttaccttacaagcgccgatgtggt
aactggact-----------------------gttcgcggtaagttta------------
--------gatcctctggcgccact-----------------------------------
----------------ccggcgctga--
>SEQ16
gcattatacaagatcattgtgccctgcagggccatatctatgcggtatagaatgcccaag
agtcagggattgtctc----aaatcacgacactcagt-----------------------
------------------------------------atcacctgacgtggtcgcggcata
cgaccgcgagtgtcacgcctggcattaaagtggggcaatcgtactgtgggactaaacatg
ctagggagccgttccaccctaagcgtgacgtcagaggatatctacgtaagtgtcgaccgg
cgcttcctaggacgttttccagagcacgttgtggatgacgtttgtgaccggaactgaatt
tgagtcttcaggttccggccgggcgacttagcatgggttcatgctgggaaattagatgac
catgatgtttttaacttaaatcggcaaacgaaatgcatcgagagatacacttaagggtag
accaattaatcgttacgca----cagagctgttctctctgcccaccattcccaacaccat
cgcatcagtgaagagtcgttttggaattcaggggacgaagggcccaagcacgaattttca
tgggcggcgacaaactttctgtgac--------------------------------cca
gaccacaactgaatatggggtgcttcgcctagttagtttcaacaataat-----------
--------------caactatgcgggggttgaggcata----------------------
------------------gaaactttacgttcctgaagcttatctcaaccgcaactccag
tacagtggaggaccatgtcgctgatcgagcggaatctgagagcaaatggtgggtcggcag
gcccacgatgttatgagatga----------------------------------ataag
ttctactcttagcatccgcacgatcgagacgccctttccatcacgtaa------------
------------------------------------------------------------
----------------ccgtggttga--
>SEQ17
----------------------------------ccgtcacgcggtactcatcgcggacg
cgtcagggatttttta----aattcacgacactccgagcagtacaatactagcactcacg
catc--------------------actggaagtgtgcttaattgaagcagtcccagcata
gaaccaatagattcaaactaggcataaaagtggggcaatggtactgtgggactaaacatg
ctagggagccgttccaccctaagcgtgacgtcagaggatatctacgtaagtttcgaccgg
ctcttcctgggtcgact-------------------------------------------
------------------------------------------------------------
---------------------------------------gttgtccccgctccagagtag
ttggttaacctggtgtctatttgtagagctattctctctgcccaacattcccaacaacat
cgcatcagtgaagagtcgtattggctttcaggagacgaagggcccaagcacgaattttca
tgggcggcaagatactttatgatcccccgaaagtgtatatcatcggtcgtgccggtgcct
gacagaagttgtg-----------------agttattctcga------------------
--------------caagtttgctgggcgagcagcatacgcaagcgagtaacacg-----
------------------------atgggttcctgaagcttatctcaaccgcaactccag
tacagtggaggaacatgtcgctgatcgagcggaatctgagagcaaatggtgggtcggcag
gcccacgacgtaaggggatgagca---------------ttttttaagcgcgatggaaat
cac-------------------------------------taaggaaaccaatagctgcg
tttattttgacccgcatcagtggaaa----------------------------------
----------------------------
>SEQ18
------------------------------gccatatctattcg----------------
----agggattcgaca----------------------------------------caca
cctgggtcatgggcggaagcggggaccagaactgtggttaattgaagtggt---------
------------------------taaaagtggggccatggtactgtgggactaaacatg
ctagtgagccgttccaccctaagcgtgacctcagaggatatctacgtaagtgtcgaccgg
cgct-------------------------tgggatccaagtctgtgtttgaa--------
------------------tcgggccttttagtatgggttgacgttggtgaa---------
------------------aatcagcacacgaaatgcgatgctggctacgctctaaggtag
accactaattagctaccca----ccaagctgttctctccgcccaacattcccaacaacat
cgcatcagtgaagagtcgttctgggtttcaggggacgaagggcccaagcacgaatcttca
tgggcggcgacatactgtttcagac-----------------------------------
-------------------------aattcagtaagattcattagccg------------
-------------------------------------------ccgggacac--------
----------ctccacccaaacccattagttcctgaagcttatctcaaccgcaactccac
tacagtggaggaacatgtctctgatcgagcggaatctgagagcaaatggtgggtcggcag
gcccacgacgtaatgagat----------------------------------ccataag
tactggtcttagcatccgcacgatcgagacgctgtctacccaaag---------------
------------------------------------------------------------
----------------------------
>SEQ19
---------------------------------------gcacgttatagaatgacgacg
ggtcagggattgtctc----gaatcacgacgctcgggcctatgccacaatagctatcacc
------------------------actagaacagtggttaattgacttggtcgctgcac-
------------tcccgcgtggcattaaagtggggcaatggtactgtgggactaaaaatg
ctagggagccgttcc-------gcgtgacgtcagaggatatctacgtaagtgtcgaccgg
cgct-------------------------taagatccaagtctgtgtttgaa--------
------------------tcgggccgtttagtatgggttgacgttggtgaa---------
-------------------------------------------------ctgtaatgcga
accactaattagctaccca----ccgaactgttctctccgcccaacattcccaacaacat
cgcatcagtgaagagtcgttctgggtttcagggcacgaagggcccaagcacgaatcttca
tgggcggcaagatactttatgatcccccgaaagtgtatatcatcggtcgtgccggtggct
gacagaagttgtcatcgcga----------------------------------------
--------------aaagtttgctgggcgagcagcatacgcaagcacgtaacacg-----
------------------------atgtgttcctgaagcttatctcaaccgcaactccag
tactgtggaggaacatgtcgctgatcgagcggaatctgagagcaaatggtgggtcggcag
gcccacgacgtaaggggatgagaagtaaagttttatgttcctattaagggccattgatag
aactggtctcagcctccccacgatcgagacccgcttgacataaggttaacaacatctt--
------------------ggccacaaagctgatgaagactgcgatggggggtca------
----------------cccttgttga--
