>SEQ0
ataagttgccgggagatgtagcataatcgaattgcgcatgccccttaatcctaattgaga
gttcggtcaagggctaagtacatgactactcacgcggctagctacttcgttccataatta
aatgcgttttgaggggtccggcttaaccgggaggtatccggtggtgtacagtgtgcgtct
tgtgttgaacttcagcacttcccctaatgcggcacgcatgccttccagccctggggttca
aatgacataattttactttgcttttctcgcccgtgtaacgtcttcagacgtagtcgagtt
cagaaagcaggagcacgaatagcgactactttcgcaaagtacgaacgcaaatggaactag
gcaggctaactctaagcgcagagggcagagtgtgagaggacccccccgatacgcgttagt
gactgtcattattatcgtcggcgagttcctctatggtgctttcttcctgaacaagcagta
tggtaatgagtcccatgttaatgatccagcgtatacgtttggcagcgtttgtgtggtggt
ccaggctgatctgcaagggaagcaactgtcctagccaagaagggacccctcttttcttct
atggcctcccgaacaacacttccgttaggcgagacacgccccaagtccgtagggaatggg
tctggatccagcggaccgacgatacgcttggtactccttcctttttaaaaggaccctcgg
cgagaatggtacccgtaaccggtacggcgctattgttaaagccatacctggtacgttcca
aacacgtgagtttaggtctggaatttcctatcgggaaggaggctcccttagatttcacga
acaattgcaggcttttactatcggtgacacaggtgtcacgtcggtaacgtctgtttcgct
acctcgttacctgagccgccgtggaagagacaagagtatcactcgaggctaattcgatga
atttcccatcgacactcgatattacctcttcgccccgaggcgatcttccaagccgttgcg
tggaagatcactcaacaatcattatgtcttcattctcgcactggccagatggggcacgat
gagttggttggccagcagca
>SEQ1
ataagtagccgggagatgtaggataatcgaattgttcatgccccttaatcctaa------
---------------------------------gttgctagctacttcgatccataatta
aatgcgttttgtagggtacggcttaaccgggaagtatccggtggtgtatagtgggcgttt
tgttttgatctccagtcattcccctaatgcggcacgcatgccttccagccctggggttca
aatgacataattttactttgcttttctcgcccatgtaacgtcttcagacgtagtcgagtt
cacaaagcaggagcacgaatagctactactttcgcaagatccggacgcaaattgaactag
gcaggctaactctaagcgcagagggcagggtgtgagtggacccacccgatacgcgttagt
gactgtcat-------------------ctccatggtgcgtactccctgaacaagcagta
tggtaatcagtcccatgttaatgatccagcgtatacgtttggcagcgtttgtgtggtggt
ccaggctgatctgcaagggaagcaactgtcctagccaagaagggacccctcttttcttct
acggc----------------ccgtaaggcgagacacgccccaagtccgtaggcaatggg
tttggatccagtagaccgacg-----------------tcctttttacaaggaccctcgg
caagaatggtacccctaaccggtatggcgctcttgttcacgccatatctggtaccgtcca
aacacgtgcgcttagctctggaatctcctatcgggaaggaggctcccttagatttcacga
acaattgcaggcttttactatcggtgacacaggtgtcacgtcggtaacgtctgtttcgct
acctcgtgacatgagccgccgtggaagagaccagagtatgactcgaggctaattagatga
atttcccatctatactcgatatta---------------------ttcgaagccgttgcg
tggaagatcactcaacaatcattatgtcttcattctagcactgtgcagatggggcacgat
gagttggttggccggcagca
>SEQ2
atcatttgcagggtgataaagcataatcgaattgcgcatggcccttaatcctaatggaga
gttcggtcaagggctaagtacattactactcacgcggctagctacttcgttccataatta
attgcgtttgtaggggtctggcctaaccgcgaggtatccggtggcgaaccgtgtaagtct
tgtgttgaacttcagcacttcccctaatgcggcacgcatgccttccagccctggggttca
aatgacataattttactttgcttttctcgcccgtgtaacgtcttcagacgtagtcgagtt
cacaaagcaggagcacgaatagctactactttcgcaagatccggacgcaaattgaactag
gcaagccagctctaagcgcatagggcagggcgtgagtggacccacccgatacgcgtttgc
gactgtcat-------------------ctccatggtgcgtactccctgaacaaacagta
tggtaatcagtcccatgttaatgatccagcgtatacgttgggcagcgtttgtgtggtggt
ccaggctgatctgcaagggaagcaactgtcctagccaagaagggacccctcttttcttct
atggcctcccgaacgacacttcagttagtcgagacacgccccaagtcgctagggaatggg
tctggatccagcggccccacgatg---------------------tagaaggaccctcgg
ctagaatcgtacccgtaaccggtacggcgctatttttaaagccttacctggtacgttcca
aacacgtg-----------agaatttcctatcgagaaggaggctcccttagatttcacga
acaattgcaggcttttactatcggtgacacaggtgtcacgtcggtaacgtctgtttcgct
ccctcgtgatatgagccgccgtcgaagagaccagagtatgactcgaggcgaatgatatga
atttcccatctatactcgatatta---------------------ttcgaagccgttgcg
tgcaagatccctcaata--------------------gcaccgtgcagatggggcacgat
gggttggttggcctgcagca
>SEQ3
ttcttttgcagggtgataaagca-----------------gcagttaatccaaatggaga
gtgcggtcaagggctaagtacattactact----------------------cataatta
atcgggtttgaaggggtatggcctatccgcgaggtatccggtggtgagccgtgtaagtct
tgcgttgaactatagcacttcccctgatgcggcacgcatgccttccagccctggggttca
aatgacataattttaatatgcttttctcgcccgtgtaacgtcttcagacgtattcgagtt
cagaaagcaggagcacgaatagccactactttcgcaaagtacgaacgcatatggaactag
gcagcttagctctaagcgaagaggtcagggtctgattggacccccccgatacccgt----
-------------atcgtcggcgattccctctatggtgctttcttcctgcacaactagta
tggtaatgagtcgcatgttaatgatccagcgtatacgtttggcagcgtttgtgtggtggt
ccaggctgatctgcaagggaagcaactgtcctagccaagaagggacccctcttttcttct
acggc----------------ccgtaaggcgagacacgccccacctccgtaggcaatggg
tttggatccagtagaccgacg-----------------tcctttttacaaggaccttcgg
cgagatcggtacccttaaccggtatggcactcttgtccacgccatatctggtaccgtccg
aaaacgtgcgcatagctctggaatttcctatcgagaaggaggctcccttagatttcacaa
acaattgcaggcttttactatcggtgacacaggtgtcacgtcggtaacgtctgtttcgct
ccctcgtgacatgagccgcggtggaagagtccagagtatgactccaggataatttg----
-------------actcgatttta---------------------ttcgaagccgttggg
tggaagatcactcaacaaacattatgtcttcagtcaagcactgtgcagatggggcacgat
gagttggtgggccggc----
>SEQ4
ataatttgccgggagatgtag----------------------cttaatcctaattgaga
gttcggtcaagggctaagtacatgactactcacgcggctagctactccgttcaacaatta
------------------cggcttaaccgggaggtatccggtggtggacagcgtgcgtct
tgtgttgaaattcagcacttcccctaatgcggcacgcatgccttccagccctggggttca
aatgacataattttactttgcttttctcgcccgtgtaacgtcttcagacgtagtcgagtt
cacaaagctggagcacgaatagctactactttcgcaagatccggacgcaacttgcactag
gcaagctaactttaagcgcagaaggcagggtgtgagtggagccaccgaatacg-------
----------------------------ctccatg--------------------cagca
tggtaatcag----------atgatccagcgtatacgtttggcagcgattgtgtggtggt
ccaggctgatctgcaagggaagcaactgtcctagccaagaagggacccctcttttcttct
atggcctcccgaaaaacactcccgttgggcgagacacgccccaagtccgtaggga-----
-----------cggaccgacgataagcttggtactcgttccttagca-------------
---------------------------cgctattgataaagccatacctggtacgttcca
tacacgtgagt---------gaatttcctatcgagaaggaggctcccttagatttcacaa
acaattgcaggcttttactatcggtgacacaggtgtcacgtcggtaacgtctgtttcgct
cccgcaggata-------------------------------------------------
---------------------------------------------atttgaaccgttggg
tggaagatcactgaacaaagattatgtcttcagtcaaggactg-----------------
aggttggtgggccggc----
>SEQ5
aaaatttgccgggagatgtag----------------------cttaatccaaattgaga
gttcggtcaagggctaagtagatg--------------------------tcagcaatta
------------------cggcttaaccgggagct------------------tgtgtct
tgtgttgaaattcagcacttcccctgatgcggcacgcatgcctcccagccctggggttca
aatgatataattttaatatgcttttctcgcccgtgtaacgtcttcagacgtattcgagtt
cacaaagccggagcacgaata--------------aagatccggacgcaaattgcactag
gccagccagctctacgcgaatagggtagggcgtgagtggacccccacgatacgcgttagg
gactgtcat-------------------ctccagggtgcgtactccctgaacaaacagta
tggtaatcaatcccatgttaatgatccaacgtatacgtttggcagcgattgtgtgggggt
ccaggctgatctgcaagggaagcaactgtcctagccaagaagggacccctcttttcttct
atgaccgcccgatcaacacttccgttcagcgcgacacgccccaagtccgtaggtaatggg
tctggatccagcgcccggtccattcgcttggtactcattcctttttaagaggtccctcgg
cgagaatggtacacgtaaccggtacggcgctatcgttacagccatacctggttcgttcta
aacatgtgagtttacgtctggaatttcctatcgagaaggaggctcccttagatttcacga
acaattgcaggcttttactatcggtgacacaggtgtcacgtcggtaacgtctgtttcgct
accttgttacctgagccgccgtggaagagacaagattatcactcgaggctaattcgatgc
atttcccatagacactcgatataacctcttcgccccgaggcgatcttccaagccgttgcg
tggaagatcactcaacactcattaagtcttgattctggcactggccagcttgggaaggat
gagttggttgtcgagcagca
>SEQ6
agcatttgcagggtgatagagcatgatcgtattgcgcatggcccttaatcctaatggaga
gttcggtcaattgctaagcacattactact-----------------cgttccttaatta
tttgccttcgtaagtgtctggactaaccgcgaggtatccggtggcgaaccgtgtaagtct
tgtgttgaacttcagcacttcccctaatgcggcacgcatgccttccagccctggggttca
aatgacataattttactttgcttttctcgcccgtgtaacgtcttcagacgtagtcgagtt
cataaagcaggagcaggaatagcgactactttcata------------------------
-----------------------ggcaagtccggagtggacccacccgatatgcgcttgc
gccagtcat------------------------------------cttgaacaaacagta
tggtaatcagtcccattctaatgatccagcgtacacgtttggcagcgattgtgtggtggt
ccaggctgatctgcaagggaagcaactgtcctagccaagaagggacccctcttttcttct
atggcctc-----------------------agacatgccccatgtccataggga-----
-----------cggaccgccgatatgcctggtacttgttccttagca-------------
---------------------------cgctattgataaaggcatatctggtaagtccca
tacacgtgagt---------gaatctcctatcgggaaggaggctcccttagatttcacga
acaattgcaggcttttactatcggtgacacaggtgtcacgtcggtaacgtctgtttcgct
acc--------------gccgtggaagagataagagtaacacacgaggctcattggatgt
attacccatcgacactcgatattacctattcggccc--------------------tgcg
tggaagatcagtcaacaatcactctgtcttctttaaggcacaggccagatggggcacgat
gagttggttggccagcagca
>SEQ7
ataacttgccgggagatgtagcatagtcgaattgcatgtgtcccttaatcctatttgaga
gttcggtcaagggctaggtactt------------------------tgttccataatta
aatgcgttttgaggggtccggcttgaccggtaggtatccggtgctgtacagtatgcctct
tcagttgaacgtc-------cccctaatgcggca-------cttccagccctggggttca
aatgacataattttactttgcttttctcgcccgtgtaacgtcttcagacgtagtcgagtt
cacaaagcagaaacacgaatagttactactttcgcaagatctgggcgcaaattgaactag
gcaggctcactctatgcgc-------------------------cccggtacgccttaat
gactggc--------------------------tggtacgtactccctgaacaagcagt-
--------------------atgatccagcgtatacgtttggcagcgtttgtgtggtggt
ccaggctgatctgcaagggaagcaactgtcctagccaagaagggacccctcttttcttct
agggcctc-----------------------agacatgccccatgtctatagggag----
------------ggaccgccgatatgccaggtaattgttccttagcacgagg--------
--------------------------------ttgataaaggcatatctggtaagtccca
ttcacgtgagt---------gaatttcctatcgagaaggaggctcccttagatttcacaa
acaattgcaggcttttactatcggtgacacaggtgtcacgtcggtaacgtctgtttcgct
tccgcaggaca-------------------------------------------------
------------------------------------------------ataacggttggg
tggaag--------------------------------------------------tcat
cagtggtccggc--------
>SEQ8
agcattaacagggtgatagagcatgatagtattgtgtatggcccttaatcctaattgaga
gttcggtcaattg------------c---------------------cgtcccttaatta
tttgccttcgtaagtgtcttgacaaaccgcgaggtctccggtggcgcagcgtgtaagtct
tgtgttggacttcagcacttcccctaatgcggcacgcatgccttccagccctggggttca
aatgacataattttactttgcttttctcgcccgtgtaacgtcttcagacgtagtcgagtt
cacaaagctggagcacgaatagctactactttcgcaagatccggacgcaacttccacttg
gcaagctaactttaagcgcagaaggctgggagtgagtggagccaccgaatacgc------
-------------------------------------------------tacatgcacca
tggtaatc----------atatgatccagcgtatacgtttggcagcgtttgtgtggtggt
ccaggctgatctgcaagggaagcaactgtcctagccaagaagggacccctcttttcttct
atgacctcccgaacgacacttcagttagtcgagacacaccccaagtcgctaggaaatggg
tctggatccagcggccccaggat----------------------tagtaggaccctcgg
ctagaatcgtacccctaaccggtacggcgctatttttaaaaccttacctggc--------
-------------------ggaatttcctatcgagaaggaggctcccttagatttcacaa
acaattgcaggcttttactatcggtgacacaggtgtcacgtcgttaacgtctgtttcgct
acctcgttacctgagccgccgtggaagagacaagagtatcactcgaggctaattcgatga
atttcccatcgacactcgatattacctcttcgccccgaggcgatcttccaacct------
---------------caatcattatgtcttcattgtcacactggccagatggcgcacgat
tagttggttggcca------
>SEQ9
ataagttgccgggagatgtaccataatcgaattccgcatgccccttaagcctaattgaga
gcttg-------------------------------------------------------
-----------aggggtctggcttaaccgggaggaatccggtggtgtacagtgtgcgtct
tatgttgatcttcagcacttcccctgatgcggcacgcatgccttccagccctggggttca
aatgacataattttaatatgcttttctcgcccgtgtaacatcttcagacgtattcgagtt
cagaaaggaggagcacgaatagcgtctactttcgtaaagtacgatcgcaaatggaactag
gctagctaactctaagcgcagagggcagagtgtg----------------------tagt
gactgtcattattctggtcggccagctccttttgggtgctttcttcctgaacaagcagtc
tg------------------atgatccagcgtatacgtttggcagcgtttgtgtggtggt
ccaggctgatctgcaagggaagcaactgtcctagccaagaagggacccctcttttcttct
acggc----------------ccgtaaggcgagacacgc------------ggcaatggg
tttggatccagtagaccgacg-----------------tcccttttacaaggaccctcgc
caagaatggtacctct-----------------------cggcatatttggtacggtcca
aacacgtgctcttagctctggaatttcctatcgagaaggaggctcccttagatttcacga
acaattgcaggcttttactatcggtgacacaggtgtcacgtcggtaacgtctgtttcgct
cccgcagaata-------------------------------------------------
---------------------------------------------atttgaatcgttggg
tggaatatcactgaacaaagatgctgtcttcagtcaaggactgagcggc-----------
--------------------
>SEQ10
------------------------------------------------------------
----ttcttttggctaagtacattactactc-----------------------------
----------------tatggcctatacgctag------------------------tct
tgcgttgaactatagcacttcccctaatgcggcacgcatgccttccagccctggggttca
aatgacataattttactttgcttttctcgcccgtgtaacgtcttcagacgtagtcgagtt
c----------------------------tttcata------------------------
-----------------------ggcaagttcggagtggacccacccgacatgcgcttgc
gccagtcaa--------------------------------------tggacaaacagaa
tggtaaacagtcccattctaatgatccagcgtatacgtttggcagcgattgtgtggtggt
ccaggctgatctgcaagggaagcaactgtcctacccaagaagggacccctcttttcttct
atgaccgcccgatcaacccttccgttcagcgctacacgccccaagtccgtaggcaatggg
tctggatccagcgcgcggtccattcgctttgtactcattcctttttaagaggtccctcgg
cga------------------------------------cggcatacctggttcgtccta
aaagtgtgagtttacgtctggaatttcctatcgagaaggaggctcccttagatttcacga
acaattgcaggcttttactatcggtgacacaggtgtcacgtcggtaacgtccgtttcgct
acctcgttacctgagccgccgtggaagcgacaagagcatcactcgaggctaattcg----
----------------------tacctcttcgccccgaggcgaagttccaacctcagtca
t--------------------------------------acgggccagagggcgcatgat
tagttggtagacca------
>SEQ11
agcatgttcagggtgatggagcatgatcgtattgcgcctgacccttaaacctaatggaga
gttcagtcaattgctaaccacattactact-----------------cgttccttaatta
tttgtcttcgtaagtgtctggactaaccgcgagatatccggtggcgcaccgtataagtct
tgggttgaacttcagcacttcccctaatgcggcacgcatgccttccagccctggggttca
aatgacataattttacgttgcttttctcgcccatgtaacgtcttcagacgtagtcgagtt
cgcaaggctggagcacgaatagctactacttccgcaagatccggacgcaactcgcactag
gcaagctacctttaagggcagaaggcagtgtgtgggtagagtcagcgatgaccctc----
---------------------------------------------------catgcagca
tgt-----------------atgatccagcgtatacgttgggcagcgtttgtgtggtggt
ccaggctgatctgcaagcgaagcaactgtcctagccaagaagggacccctcttttcttct
atggcctccagaacaacacttccgttaagcgagacacgctcctagtccgtagggaatggg
tttggatccagcggaccgacgatacgcttggtactccttcctttttaaaaggaccctcgg
ctaga-------------------------------------------------ggtcca
accacgtgtgtttagggctgtaatttcctatcgagaaggaggctcccttagatttcacaa
acaattgcaggcttttactatcggtgacacaggtgtcacgtcggtaacgtctgtttcgct
acctcgttacctgatccgccgtggatg------------cactcgaggctaattcg----
----------------------tacctcttcgccccgaggcgactttccaacctcattca
t--------------------------------------acgggccagagggcgcatgat
tagttggtagacca------
>SEQ12
ataatttgcagggagatgtag----------------------cttaagcctaattgaga
gttcggtcaagggctaagtacctgacaactcacgcggctagctactccggtcaacaatta
------------------cggcttaaccgggaggtatccggtggtggacagcgtgcgtct
tgcgttgaaattcggcacttcccctgatgcggcacgcatgccttccagccctggggttca
aatgacataattttaatatgcttttctcgcccgtgtaacgtcttcagacgtattcgagtt
cacaaagcagaaacgcgaatactcgcttctctcgcaagatatgggcgcaaattgaactag
gcaggatcactctatgcgctgtgg-------------------------tacgccttaat
gactggc--------------------------tggcacgtaccccgtgaacaagcagt-
--------------------atgatccagcgcatacgtttggcagcgtttgtgtggtggt
ccaggctgatctgcaagggaagcaactgtcctagccaagaagggacccctcttttcttct
acggc----------------ccgtaaggcgagacacgccccaagtccggacggaatggg
tatggatccagtagaccga---------------------------------------ga
caagaatggtacccctaacctgtatggcgctcttattcacgccatatcaggtaccgtcca
aacacgtgcgcgtagctccgtaatttcctatcgagaaggaggctcccttagatttcacaa
acaattgcaggcttttaatatcggtgacacaggtgtcacgtgggtaacgtctgtttcgct
tccgcaggaca-------------------------------------------------
------------------------------------------------ctaacggttggg
tggaag------------ccatcagtgcttcggt--------------------------
--------------------
>SEQ13
-----------------------------------------ttcttttgcatggtgcaga
g--cggtcaacggctaagtacattacgact----------------------cataatta
atcgcgattgaaggggtgtggcctatccggaaggtatccggtggtgagccgtgtaactct
tgcgtttctctacagcacttcccctgatgcggcacgcatgcctcccagccctggggttca
aatgatataattttaatatgcttttctcgccggtgtaacgtcttcagacgtattcgagtt
cacaaagccggagcacgaata--------------aaggaccggacgtaaattgaactag
gccagccagctctccgcgattagggtagggcgtgagtggaccctcacgatacgcgttacg
gactgtcag-----------------------------------ctccaggctgcgatta
tggtaatcaatctcatgttaatgatccagcgtatacgtttggcagcgtttgtgtggtggt
ccaggctgatctgcaagggaagcaactgtcctagccaagaagggacccctcttttcttct
atgactgcccgatcaaccgttccgtgcagcgcgacacgccccacgtccgtaggcaatggg
tctggatc------------------------actcattccttt----------------
--agaatggtacacgtaaccggtacggcgctttcgttccatccatacatggttcgttcta
aacatgtgagtttacgtctggaatttcctatcgagaaggaggctcccctagatttcacga
acaattccaggcttttactatcggtgacacaggtgtcacgtcggtaacgtctgtttcgct
acctcgttccctgagccgccttg---------------tcactcgaggctgattcg----
----------------------tagctcttcgcccctaggacaagttccaacctcagtca
t--------------------------------------------------gcgcatgat
t-------------------
>SEQ14
agcatgttcatggtaagggagtctaatcgtattgcgcctgaaccttaaacctaatggaaa
tttcaatcatttgctacccactttactact-----------------cgttccttaatca
tttgtcctcgtaagcgtctggactaaccgcgagatatccggtggcgcaccg---------
----------tctagcacttcccttaatgcggcacgcatgccttccagccctggggttcc
aatgacataattttactttgcttttctcgcccatgtaacgtcttcagacgtagtcgagtt
cacaaagcagaaacgcgaatactcgcttctctaacaagttacgggcagaaattgaactac
gcaggaacatcatatgcgcaatga------------------------------------
----------------------------ctggctggcacgtaccccgtgaaccagcagt-
--------------------atgatccagcgtatacgtttggcagcgtttgtgtggtggt
ccaggctgatctgcaagggaagcaactgtcctagccaagaagggacccctcttttcttct
atgaccgccctatta--------------------atgccccaattccgtaggcaatggg
tccggctccagcgctcggtccattcgctttgtactcattcctttttaaggggttcctcgg
caa------------------------------------cggcatacctacttcgaccta
taaatg-------------ggaagttcctatcgggaaggaggctcccttagttttcacga
acaattaaaggcttttactatcggtgacacaggtgtcacgtcggtaacgtctgtttcgct
acctcgggacatgagccgccctggaagaaaccacagtatgactcgaggctaattagatga
atttcctatctatactcgatatta---------------------ttcgaagccgttccg
tggaagatcactcaa------------------tcttgcactgcgcagatggagcacgat
gagctggttggccggc----
>SEQ15
gtaagtagccgggacatgtaggataatcgaattgttcatccgccttaatcctaat-----
------------------------------------gctaggtgcttcgatgcataatta
attgcgttttgtagggtacggcttaac-----------------------------gttt
tgttttgatctccagagtttcccctgatgcggcacgcatgccttccagccctggggttca
aatgacataattttaatatgcttttctcgcccgtgtaacgtcttcagacgtattcgagtt
cacaaacctggcgcactaatagctactactttcgcaagatccggacgcaacttccacttg
ggaagctaac--------------------------------------------------
---------------------------------------------------catgcacca
tggaaatgat----------atgatccagcgtatacgtttggcagcgtttgtgtggtggt
ccaggctgatctgcaagggaagcaactgtcctagccaagaagggacccctcttttcttct
atggcctccagaacaacacttccgttaagcgagactcgctcctagtccgtaggtaatggg
tttggatccagcgcaacgacgatacgcttcggacgccttcctttgtaaaaggaccctcgg
ctaggac-----------------------------------------------------
--caagcgtgtatatggctgtaatttcctatcgagaaggaggctcccttagatttcacaa
acaattgcaggcttttactatcggtgacacaggtgtcacgtcggtaacgtctgcttcgct
tcctcgtgacatgagccgcggtggaagagtccagagtataactccatg------------
-----------atactcgatttta---------------------ttcgaagccgttggg
tgg------------------------------tcaagcactgtgcagatggggcacgat
gagtgggtgggcctgc----
>SEQ16
atatgtagccgcgggttgtaggataatcgaatagttcataccccctaaacctaa------
---------------------------------gttgctagctacttcgatacataatt-
---------------------------------------------gcatagtgggctttt
tgttttgatatccagtcattcccctaatgcggcacccatgccttccagccctggggttca
aatgacataattttactttgcttttctcgcccgtgtaacgtctgcagacgtagtcgagtt
cacaaagctggagcacgaatcgctactactttcgcaagatccagacgcaactagcactag
gcaagctaactttaagcgacaaaaacacgttgtgagtggagccaccgactttgctc----
---------------------------------------------------catgcagca
tggtaatcag----------atgatccagcgtatacgtttggcagcgattgtgtggtggt
ccaggctgatctgcaagggaagcaactgtcctagccaagaagggacccctcttttcttct
atgaccacc-------------------------cttgcccgaattcctttggcaatggg
cccggatccagcgctcggtc-------------------------caaggggttcctcgg
caacggtact--------------------------------------------------
--------------------gaatttcctatcgagaaggaggctcccttagatttcgcga
acaattgcaggcttttactatcggtgacacaggtgtcacgtcggtaacgtctgtttcgct
tcctcgtgaggtggg---------------------tatgactcgaggctaattagatga
atttcccatctatactcgatatga---------------------ttcgaagccgtggcg
tggaataacactcaacaatcctgatgacttcattcttgcgctgtgcagatggggcacgat
cagagggttggccggcagca
>SEQ17
------------------------------------------------------------
------------------------------------------------------------
-------------ttattttggctaatatggag---------------------------
-----tatacgctagcacttcccctaatgcggcacgcatgccttccagccctggggttca
aatcacataattttacgttgcttttctcgcccatgtaacgtcttcagacgtagtcgagtt
cagtgagcaggatcacgaatagcgactactttcgcaaagtgagaacgcaaatggaaccag
gcaggctaactctaagcgccgagggcagagtgtgagaggacccccccgatacgcgttagt
gactgttattattatcctcggcgagttcctctacggt-------------acaagcagta
tggtaatgagtccgatgttaatgatccagcgtatacgttgggcagcgtttgtgtggtggt
ccaggcggatctgcaagcgaagcaactgtcctagccaagaagggacccgtcttttcttct
actgc----------------acgtaaggcggcacacgc---------------------
------accagtgcaccga---------------------------------------ga
caagattggtacccctaacctgtatgacgctcttattcacgccatatcagttaccgtcca
aacacgtgcgcgtagcaccggaatttcctatcgagtaggaggctcccttagatttcacaa
acaattgcaggcttttactatcggtgacacaggtgtcacgtcgttaacgtctgtttcgct
acctcgtgacatgagcccccgtggaagagaccagagtatgactcgaggctaattagatga
atttcccatctatactccctatta---------------------ttcgaagccgtcgcg
tggaagatcactcaacaatcattatgtcttcatc-------------------acacgat
gagttgtttggccggcagca
>SEQ18
atcatttgcagggtgatagagcattatcgtattgcgcatggcccctaatcctaatggaga
cttcggtcaattgctaagcacattac---------------------cgttacgtattca
tttgccttcgtaagtgtctggacaaaccgcgtggtatccggtggcgaaccgtgtaagtct
tgtgttggacttcagcac-tcccctaatgcggcacgcatgccttccagccctggggttca
aatgacataattttactttgcttttctcgcccgtgtaacgtcttcagacgtagtcgagtt
cacaaagcaggagcactaatagctactgcgttggcaagatccggacgcaaattgtactag
gcaggctaactctaagcgcagagggcagggtgtcagtggacccacccgatacgcgttcgt
gac-------------------------ctccatggtgcgtactccctgaacaagcagta
tggttatccggcccatcttaatgatccagcgtatacgtttggcagcgtttgtgtggtgtt
ccaggctgatctgcaagggaagcaactgtcctagccaagaagggacccctcttttcttct
atgacctcccgaacgacacttcagttattcgagacacaccccaactcgctaggaaatggt
gctggaaccagcggccccaggat----------------------tagtaggaccctcgg
ctagaatcgtaac-----------------------taaaaccttacacggc--------
-------------------ggaagttcctatcgggaaggaggctcccttagttttcacga
acaattaaaggcttttactatcggtgacacaggtgtcacgtcggtaacgtctgtttcgct
acctcattacctgagccgccgtggaagagacaggattat------------------tga
aattcccatctacactcgatattacctct----------------------cct------
---------------caatcattatggcttcattgtcacactggccagatggcgcacgat
tagttggttggcga------
>SEQ19
------------------------------------------------------------
------------------------------------------------------------
---ttgttttggccaatatggcctataggctag---------------------------
-gcgttgaactatagcacttcccctaatgcggcacgcatgccttccagccctggggttca
aatgacataattttactttgctttcctcgcccgtgtaacgtcttcagacgtagtcgagtt
cagaaagggggagcacgaatagcgtcttctttcgtaaagtacgatcgcaagtggagctag
ac---------------------ggcagagtgtg----------------------tagt
gactgtcattattcaggtcggccagccccttatggatgctttctacctcaacaagcagac
tg------------------atgatccagcgtatacgttgggcagcgtttgtgtggtggt
ccaggctgatctgcaagggaagcaactgtcctagccaagaagggacccctcttttcttct
acggg----------------ccgaaaggcgagacacgccccaagtccggacggaagggg
tatggatcgagtagaccga---------------------------------------gg
caagaatggtacccctagcctgtatggagctctaatgcaggcgatatcagataccgtgca
aaaacgtg------------gaatctcctatcgggaaggaggctcccttagatttcacca
acaattgcaggcttttactatcggtgacacaggtgtcacgtcggtaacgtctgtttcgct
gtc-------------------------------------actcgaggctgattcgtagc
tcttcgccgcctcagtcat-----------------------------------------
---------------------------------------------------gcgcgtgat
t-------------------
