>SEQ0
cgcttcgtagccccgctttgtgcag--acgtcccgcatactgatagaagcaaatcatgaa
atcgtcctaaacacccaacttctagcaatcccagggacctagactcaggatgtccggggc
ttcaaaactgctgccggctgagtgaccccacaaccattataaagcctaggagggcgcacg
tgctccaggt---ctcccaccctagggttgcgataatggcgtacgcgcggaagtttaagg
cgatatctgccccccatcgttggcatccttggagaatagtaatcacaccgcatgcactca
ttctctgcagttcaatgctttgttcttgaccgaggactgaaacaggttacagaggaccaa
ggagaatgtctacgcggtgtcctggagaatgatttaaatagacttcgaaaccctatgtgg
aacgtcccgctagtcaggctttgaaaaaacag-agcttgtcatgtcggttagggaatccc
catgatatcggtcgcggcctgccaaattgagccctgcagtgttggtcgtcatgtggagat
gtttcccgtgtgtaggtgtccagcaatgaccacgacttggtgagctattggtccaaaggg
acccccccgaacctgatcccaggcaggggcctgcccactgggagtgatccaatgaggtcg
ccgtgacaccttctaaccaccactttaaccgccctcgcccatttcatccctcatgacata
taacgactagggtgttcacggcagggaggggctacactttctactcgccgcacgaatatg
aacgttcgatggggcgagccgcgaaaaatggtcggagaagatagcctacggcacttacat
atatagggaagatgcggtgggcgggctacagatcactcggtggaaaacactaccgcaaac
atcttatgaaggagctattatacaattattcgctgagtaagtagtcaaggtgacgcccga
cagtcgcttccacaacacagtccggagaatcgaataagttcatttgtaacgtcccctggg
ggtgtcctactgaacaacttagccctaatgtcaagagtgctatcgtagcacccatcgaca
tcggacttactactgagcctgtgttc
>SEQ1
cgcttcgtatccccgctttttgcag--acgtcccgcatactgatagtagctaatcatga-
--------------------tctagcaatcacaggg------------------------
-tctaaactgctgccggctgagtgaccccacaatcattataaagcctaggaggccgcacg
tgctccaggt---ctccaaccatacggttgcgataatggcgtacgcgcggaagtttaagg
cgatatctgccccccatcgttggcatccttggagaatagtaatcacaccgcatgcactca
ttctctgcagttcaatgctttgttcttgaccgaggaccgaaacagggtacagaggaccaa
ggagaatgtctacgcggtgtcctggagaatgatttaaatagtcttcgaaaccctatgtgg
aacgtcccgctagtaaggctttgaaaaaacag-aacttatcatgtcggttagggaatccc
catgatatcggtcgcggcctgccaaattgagccctgcagtgttggtcgtcatgtggagat
gtttcccgtgtgtaggtgtccagcaatgaccacgacttggtgagctattggtccaaaggg
accccctggaacctgatcccaggcaggggcctgcacactggga----------------g
ccgtgacactttctaaccacctctttaaccccccgcgcccatttcatccctcatgacaaa
aaacgactagagtgttcacggcagggaggggcaacactttctactcgccgcacgaatatg
aac-----------------------aatggtcggagaagatagcctacggcacttacat
atatagggaagatgcggtgggcgggctacagatcactcggtggaaaacactaccgcaaac
atcttatgaaggagctattatacaaatattcgctgagtaggtagtcagagtgtcgcccga
gagtcggttctataacacagtccggagaatcgaggaagttcatttgtaacgtcccccggg
ggtgtcctactgcacaacttagccctaatgtcaagagtgctatcgtggcacccatcgaca
tcggactcactactaaggctgtgttc
>SEQ2
agcttcgtagccccgcttcgtgcag--acgtccagcatactgttagaagcaaatcatgaa
atcgt---------------tctagcaatcccagct------------------------
-tccaaactgctgccg-----------------------------ctaggagggcgcacg
tgctccaggt---ctaccaccctagggttgcgataatggcgtacgcgcggaagtttaagg
cgatatctgccccccatcgttggcatccttggagaatagtaatcacaccgcatgcactca
ttctctgcagtt--------------------------------ggttacagaggcccaa
ggagaatgtctacgcggtgtcctggagaatgatttaaatagtcctcgaaaccctatgtgg
aaagtcccgctggtaaggctttgaaaaaacgg-aacttaccatgtcagttagtgaatccc
tatgatatcggtggcgacatgccaaattgagccctgcagtgttggtcgtcatgtggagat
gtttcccgtgtgtaggtgtccagcaatgaccacgacttggtgagctattggtccaaaggg
accccct-----------------gggggcctgcacactggga-----------------
-------------aaaccacctctttatccccccgcgtccatttcatccctcatg-----
------------------cggcatggaagggcaacagtttctactcgccgcacgaagatg
aac-----------------------aatggtcggagaagatagcctacggcacttacat
atatagggaagatgcggtgggcgggctacagatcactcggtggaaaacactaccgcaaac
atcttatgaagcagctattatacaatgattggctgagtaagtagtcaagctggcccccca
aagtcgcttccacaacacagtccggagaatcgaataagttcatttgtaccgtcccctggg
ggtgccctactgaacaacttagccctaatgtcaagtgtgatatcgtagca----------
-----------actgagcctgtgtgc
>SEQ3
agcttcgtagccccgcttcgcgcag--acgtccagtatactgttagaagccaatcatgaa
atcgt---------------tctagcaaccccagct------------------------
-tccaaactgctgccg-----------------------------gtaggagggcgcacg
tgccccaggt---cttccaccctagggttgcgataatggcgtacgcgcggaagtttaagg
cgatatctgccccccatcgttggcatccttggagaatagtaatcacaccgcatgcactca
ttctctgcag----------------------------------ggttacagaggcccaa
gtagaatgtctacgcagcgtcctggcgaagtatctaaatg--------------------
---gtcccgctggtaaggctttgaaaaaacgg-aacttaccatgtcagttagtgaatccc
gatgatatccgtatcgacatgcc--attgagccctgcagtgttggacgtcatgtggagat
gtttcccgtgtgtatgtgtccagcaatgaccacgacttggtgagctattggtccaaaggg
accccctgcaacctgatcccaggcaggggcccg---------------------------
--gtgacactttctaaccacctctttaatcccccgcgcccttatcatccctcatgacata
ggacgactagagtgtttacggcacggaggggcaatactttctactcgccgcacgaatatg
aac-----------------------aatggtcggagaagatagcctacggcacttacat
atatagggaagatgcggtgggcgggctacagatcactcggtggaaaacactaccgcaaac
atcttatgaa----------------------------aagtatacaagccggcccccca
-----------------------ggagaatagaataagttcatttgtaccgtcccatggg
ggtgccctactgaacaacttagccctaatgacaagtgtgatatcatagca----------
-----------actgagcctgtgtgc
>SEQ4
agcttcgtagccccgcttcgtgcag--acctccagcatactggttgaagcaaatcatgac
atcgt---------------tctagcaatcccagct------------------------
-tccaatctgctgcca-----------------------------ctaggaaggcccacg
tgctccagct---ttaccaccctggggttgcgataatggcgtacgcgcggaagtttaagg
cgatatctgccccccatcgttggcatccttggagaatagtaatcacaccgcatgcgctca
ttctctccttta--------------------------------ggttacagaggcccaa
ggataa--------------------gtatgctttaattagtcctcgaaaccatatgtgg
aaagtcccgctgataaggctttgaaaagacgg-aacttaccatgtcagttagtgaaaccc
tatgatatcggtggagacatgccaaattgagccctgcagtgttggtcgtcatgtggagat
gtttcccgtgtgtaggtgtccagcaatgaccacgacttggtgagctattggtcccaaggg
accccctc----------------aggggcctgcacactggga----------------g
ccgtgacactttctaaccccccctttaaccccccgcgcccatttcatcccgcatgacaaa
aaacgactagagtgttcacggcagggagg---------------------------tatg
aac-----------------------aatggtcggagaagatagcctacggcacttacat
atatagggaagatgcggtgggcgggctacagatcactcggtggaaaacactaccgcaaac
atcttatgaggcagctattatacaatgattggatgattaagtagtcaagctggcccccca
aagtcgcttgcacaacacagtccggagattcga-------------------cccctggg
ggtgccctactaaacaacttggccctaatgtcaagcgggatatcgtaacaa---------
--------------------------
>SEQ5
accttcgtagccccgcttcgggcag--acgcacagcatactgttggaagcatatcatgaa
atcgt---------------tctagcaatcccagct------------------------
-tccaaactgcggccg-----------------------------ctaagtgggcgcacg
tgctccaggt---ctaccaccctcgggttgcgataatggcgtacgcgcggaagtttaagg
cgatatctgccccccatcgttggcatcgttggagaatagtaatcacaccgcatgcactca
ttctct-----------ctctgttcttgagcgaggaccgaaaaagggtacagaggaacaa
ggaaaatgtttacgcggtgtcctgg-----------------------------------
---------------------------------aacgtatcatgtcggttagggaatccc
cagtatatcgggcgcggcc-------ttgagccctgcagtgttggacgtcatgtggagat
gtttcccgtgtgtatgtgtccagcaatgaccacgacttggtgagctattggtccaaaggg
accccctagaacataatcccaggtaggggcctgcacacttgga----------------g
ccatgacact-------------tttaaccccccgcgccgatatcatccctcatgaaaat
aaacgactagagtgt---------------------------------------------
--------------------------aatggtcggagaagatagcctacggcacttacat
atatagggaagatgcggtgggcgggctacagatcactcggtggaaaacactaccgcaaac
atcttacgacgcg--------------attgattgattaagtagtcaaactagcccccgc
aagtagcttgcacaacacagtccggagattcga-------------------cccctggg
ggtgcactactaaacaactccgccctaatgtcaagcgggatatcgtaaaaa---------
--------------------------
>SEQ6
agcttcgtagcaccgcttcgcggag--acgtccagcatactgttagaagcgaatcatgaa
atcat---------------tctagcact-------------------------------
-tccaaactgctgccg-----------------------------gtaggagaccgcgcg
tgccccaggc---catccacccttgggttgcaataatggcgtacgcgcggaagtttaagg
cgatatctgccccccatcgttggcatcgttggagaatagtaatcacaccgcatgcactca
ttctctgcagttcaatgcttggttcgtgacctaggactgagacaggttacagagt-----
------------------atcctggagaatgatttaaataaact---------------g
agcgtcccggcagtcaggctttgaacaaacag-agcttatcatgt---------------
---------------ggcctgccaaattgagccctgcagtgttggtcgtcatgtggagat
gtttcccgtgtgtaggtgtccagcaatgaccacgacttggtgagctattggtccaaaggg
accccct-----------------ggcggcctgcacactggga-----------------
-------------aaaccacctcttaattcccccgcgtccatttcatccctgttg-----
-------------------------------------cttctactcgccgcacg------
--------------------------aatggtcggagaagatagcctacggcacttacat
atatagggaagatgcggtgggcgggctacagatcactcggtggaaaacactaccgcaaag
atcttatgaa--------------------------------------------------
-----------------------ggagaatagaataagttggtctgtaccgtcccatggg
ggt-------------------------tgacaagtgtgatatcatagta----------
-----------actgagcctgtgtgc
>SEQ7
agcttcgtggcaccgcttcccggag--atgtccatcataccgttagaatcgaatcatgaa
atcat---------------tcaaa-------aacc------------------------
-tccaaaatgctcccg-----------------------------gtaggagaccgcgcg
tgcctcaggc---catccaccattgggttgcgataatggcgtacgcgcggaagtttaagg
cgatatctgccccccatcgttggcatccttggagaatagtaatcacaccgcatgcactca
ttctatgcag----------------------------------cgttacagaggcgcaa
gtagaatctcttcggagcgtcctggcgaa-------------------------------
------------------gtttgaaaaaacggcgacttccca------------------
--------------------------ttgagccctgcagtgttggacgtcatgtggagat
gtttcccgtgtgtatgtgtccagcaatgaccacgacttggtgagctattggtccaaaggg
accccctgcaaccggatcccaggcaggggcccggtgacac--------------------
---------tttcgaaccacctctttaatcccccgcgcgcttatcatccctt--------
-----------------tcggcacggaggggcaatactttctactcgccgcacgaatatg
--------------------------aatggatggagaagatagcctacggcacttacat
atatagggaagatgcggtgggcgggctacagatcactcggtggaaaacactaccgcaaac
atcttatgaggcagctattatacgatgattggatgattaagtagtcaagcatcactccca
aagtcgcttgcacaacaccgtccggggattcga-------------------cccctg--
--------------caacttggccgtaatgtcaagtgggatatcataacaa---------
--------------------------
>SEQ8
agcttcgtagccccgcttcgcgcag--acgtccagtatactgtttgaagccaatcattaa
atcgt---------------tctagcaaccccaggt------------------------
-tccgaattgctgcca-----------------------------gta------------
---cccaggt---cgtccaccctagggttgcgataatggcgtacgcgcggaagtttaagg
cgatatctgccccccatcgttggcatccttggagaatagtaatcacaccgcatgcactca
ttctctgcag----------------------------------cgttacagaggcgcaa
gtagaagctcttcggcacgtcctggcgta-------------------------------
------------------gtttgaaaaaacggcgacttccca------------------
--------------------------ttgagccctgcagtgttggacgtcatgtggagat
gtttcccgtgtgtatctgtccagcaatgaccacgacttggtgagctattggtccaaaggg
acccccccgaacctgaacccagtcaggcgcctgcccactcgta-----------------
------gtgcttctaaccaccacttaaaccgccctcgcccatttcatccctcatgacata
taaagtatagggtgttgacggcagggaggggctacactttctactccccgcactaatctg
aacgttcgatggggcgtgccgcggacaatggtcggagaagatagcctacggcacttacat
atatagggaagatgcggtgggcgggctacagatcactcggtggaaaacactaccgcaaac
atcttatgagtcagctattatacgatgattggatgattaagtagtcgagcatcactccca
aagccgcttgcacaacaccgtccggggattcga-------------------cccctg--
--------------caacttggcc------------------tcataacaa---------
--------------------------
>SEQ9
agcttcgttacaccgcttcccggag--atgtccatcataccgttagaaacgaatcctgga
atcat---------------tcaaa-------aacc------------------------
-tccaaaatgctcccg-----------------------------gtaggagagcgcgcg
tgcctcaggt---catccaccattgggttgcgataatggcgtacgcgcggaagtttaagg
cgatatctgccccccatcgttggcaaccttggagactagtaatcacaccggatgcactca
ttctctgccg---------------------accgaccgaaccagagtacagaggaccaa
ggagaacgtctacgcagtgtcctggagaatgatttaaatagtcttcgcaaccctatgtgg
aacgtcccgctaggcaggctttgaaaacacag-aacttatca------------------
-------------gaaaccccctaatttgagccctgcagtgttggacgtcatgtggagat
gtttcccgtgtgtatctgtccagcaatgaccacgacttggtgagctattggtccaaaggg
accccctgggaac-----------------------------------------------
---------------accacctgttacttcct----------------------------
------------------------------------gtttctactcggcgcacg------
--------------------------aatggtcggagaagatagcctacggcacttacat
atatagggaagatgcggtgggcgggctacagatcactcggtggaaaacactaccgcaaat
atcttatgag-------------------------------------agcatcactccca
aaaccgattgcacaacaccgtccggggattcga-------------------cccctg--
--------------aa--------------------------------------------
--------------------------
>SEQ10
agcttcgtagccccgcttcgcgcag--accaccagcatactgagtgaagcaaatcatgac
atcgt-----------------taacaatcccagct------------------------
-tccaatctgctgcca-----------------------------cgaggaaggcccacg
tgctccagct---ttaccactctggggttgcgataatggcgtacgcgcggaagtttaagg
cgatatctgccccccatcgttggcatccttggagaatagtaatcacaccgcatgcactca
ttctctgcagttcaatgcttggttcgtaacctaggactgagacaggtt------------
-------------------tccagctgaatgatttaaataaact---------------g
agcgtcccggcagtcaggctttgaacaagcag-agcttatcatgt---------------
--------------------------ttgagccctgcagtgttggtcgtcatgtggagat
gtttcccgtgtgtaggtgtccagcaatgaccacgacttggtgagctattggtccaaaggg
acccccccaaacctgataccaggcaggcgcctgcccactcggagtgatcctatgaggtcg
ccgtgacaccttctagccaccactttaa-----------cattacatccctcatgacata
caacgactagggtgttcacggcagggagcagctacactttctactcgccgcacgagtatg
tacgttcgatgg--------------aatggtcggagaagatagcctacggcacttacat
atatagggaagatgcggtgggcgggctacagatcactcggtggaaaacactaccgcaaac
atcttatgaaggaactattatacaaatatttgctgaggaggtagtggcagtgtcgctcga
gagtcagttcaagaagacagtccggagaatcgaggacgttcatttgtaacgtcacccggg
ggtgtcctactgcata-------------------tgtgctatcgtggcacccatcgaca
tcggactcactactaaggctgtgttc
>SEQ11
agcttcgtagccccggttcccgcag--acccaaagcacgata------------------
------------------------------------------------------------
-tcgtatctgatgcca-----------------------------cgaggaacgccaacg
tgatccagct---ttaccactctggggttgcgataatggcgtacgcgcggaagtttaagg
cgatatctgccccccatcgttggcatccttggagaatagtaatcacaccgcatgcactca
ttctctgcag----------------------------------cgttacagagg-----
------------------gtcctggcgcag------------------------------
-------------------tttgaaaaagcgc-gactttcca------------------
--------------------------ttgagccctgcagtgttggtcgtcatgtggagat
gtttcccgtgtgtaggtgtccagcaatgaccacgacttggtgagctattggtccaaaggg
acccccccaaacctgataacaggcaggcgcctggccaatcggagtgatcatatggggtcg
ccgtgacaccttctagccacaagtttaa--------------------------------
------------------cagttagggag---------------tcgccgcaccagtatg
taggttcgaagg--------------aatggtcggagaagatagcctacggcacttacat
atatagggaagatgcggtgggcgggctacagatcactcggtggaaaacactaccgcaaag
atcttatgaagaagctattatacaaatattcgctgagaaggtagtcagggtggcgcccga
gggtcggttctataacacagtccggagaatcg--------------------cccccggg
ggtgtcctac----------------------aagagtgctaccgtggcacccatcgaca
taagactcagtactaacgctgtgttc
>SEQ12
cgcctcgtatccccgctttttgcag--acgtcccgcacaccgatagaagctaaccatga-
--------------------tctagcaataacaggg------------------------
-tctaaactgctgccggctaagtgaccccacaatcagtataaagcctaggaggccg----
------------------gcgatacggttgccataatggcgtacgcgcggaagtttaagg
cgatatctgccccccatcgttggcatccttggagaatagtaatcacaccgcatgcactca
ttctctgcag--------------------------------------------------
------------------gtcctgccgcag------------------------------
-------------------cttgaaaaagcgc-gactttcca------------------
--------------------------ttgagccctgcagtgttggacgtcatgtggagat
atttcccgtgtgtatgtgtccagcaatgaccacgacttggtgagctattggtccaaaggg
acccccc-------------aggcaggcgcctgcccactcgga-----------------
ccgtgacaccttctagccaccactttaa-----------cattacatccctcatgacata
caacgactagg------------------------actttcttctcgccgcacgagtatg
tacgttcgatgg--------------aatggtcggagaagatagcctacggcacttacat
atatagggaagatgcggtgggcgggctacagatcactcggtggaaaacactaccgcaaag
atcttatgaa----------------------------aagtatacaagcaggcacccca
-----------------------ggagaatagtataagttcatttgtaccgtcccatggg
ggtgccctactgaacaacatagccctaatgacaagtgtgatatcatagca----------
-----------agtgagcctgtttgc
>SEQ13
cgcctcgtatccccgctttttgcagcagcttctagcgtaaa-------------------
------------------------------------------------------------
-tgtaaactgctgccg-------------------------------------gctaagg
tacccca----------cactatacggttgcgataatggcgtacgcgcggaagtttaagg
cgatatctgccccccatcgttggcatccttggagaatagtaatcacaccgcatgcactca
ttctctgcagttcaatgcttggttggtaacctaggcctgagagaggtt------------
------------------------------------------------------------
tgcagctgatcagtcagggccggaacaagcag----------------------------
--------------------------ttgagccctgcagtgttggtcgtcatgaggagat
gtttcccgtgtgtaggtgtccagcaatgaccacgacttggtgagctattggtccaaaggg
accccctc----------------gggggcctgcacaatggga----------------g
ccgtgacactttctaacccccactttaaccccccgcgcccaattcatccgtga-------
--------------------------------------------tcacggcagggaggtg
aac-----------------------aatggtcggagaagatagcctacggcacttacat
atatagggaagatgcggtgggcgggctacagatcactcggtggaaaacactaccgcaaac
atcttatgaagaagctattatataactatt----------------------gcgcccca
gggtcggttctataacacagtccggagaatcg--------------------cccccggg
ggtgtcctac----------------------aagagcagtactaaagctgtgttc----
--------------------------
>SEQ14
agcttcgtagccccggttcccgcag-----------------------------------
------------------------------------------------------------
-acctatcaaattcca-----------------------------cgaggaacgccaacg
tgatccagct---ttacaactatggggttgcgataatggcgtacgcgcggaagttcaagg
cgatatctgccccccatcgttggcatccttggagaatattaatcacaccgcatgcactca
ttctctgcagtttaattctgggtaggtatcctaggcctgagagaggtt------------
------------------------------------------------------------
tgcacctgatcagtcagggccggaacaagca-----------------------------
--------------------------ttgagccctgcagtgtaggacgtcatgtggagat
gtttcccgtgtgtatctgtccagcaatgaccacgacttggtgagctattggtccaaaggg
accccctagaacgtaatcccaggtaggggccagcacacttgga----------------g
ccatgccacttttta-------------cccccggcgccgatataagccctcattaaaat
aaacgactagagtgc---------------------------------------------
--------------------------aatggtcggagaagatagcctacggcacttacat
atatagggaagatgcggtgggcgggctacagatcactcggtggaaaacactaccgcaaac
atcttatgacgcacc---------------------------------------------
--------------------ccaggagaatagtataagttcatttgtaccgtcccatggg
gct-----------------------------------aacaacatagaagtg-------
--------------------------
>SEQ15
cgcctcgtatccccgctctatgcag-----------------------------------
------------------------------------------------------------
-------cagcttcta-----------------------------gcgtaaatggaaact
gcttccggctaaggtaccccactacggttgcgataatggcgtacgcgcggaagtttaagg
cgatatctgccccccatcgttggcaaccttggagacgagtaatcacaccggatgcactca
ttctctgcag----------------------------------tgttacatagg-----
------------------gtcctggcgcag------------------------------
-------------------tataaaaaagggg-gactgtcca------------------
--------------------------ttgagccctgcagtgttggacgtcatgtggagat
atttcccgtgtgtatgtgtccagcaatgaccacgacttggtgagctattggtccaaaggg
accccccca---------------aggcgcatggccaatcggagtgatcatatggggtct
ccgtgacaccttctagccacaagtttac--------------------------------
------------------cagtaagggag---------------tcaccgcaccagtacg
taggttcgaagg--------------aatggtcggagaagatagcctacggtacttacat
atatagggaagatgcggtgggcgggctacagatcactcggtggaaaacactacctcaaac
atcttacgaagaagctattatacaattattcgctgtgaaggtagtcagggtggcgcctga
gtgtcggttctataac--------------------------------------------
-----cctac----------------------aagagtgctaccgtggcacccatcgaca
taagactca-----------------
>SEQ16
atctacgtagccccgcttagcgcag--accaccagcatacttagtgtagcaattcatgac
atcgt-----------------tagcaatacca---------------------------
-tccaatctgctgcca-----------------------------cgaggaaggcccacg
tgctacagtt---ttacctctctggggttgcgataatggcgtacgcgcggaagtttaagg
cgatatctgccgcccatcgttggcatccttggagaatagtaatcacaccgcatgcactca
ttcgctgccgcc------------------------cggaaccagagtacataggaccaa
ggagaacgtctacgaagtgtcctgcagaatgatttaaatagtcttcgcaaccatatatag
aacgtcccgctaggcaggctttgaaaacacag-aacttatcg-----------gaaaccc
c-------------------------ttgagccctgcagtgttggtcgtcatgtggagat
gtttcccgtgtgtaggtgtccagcaatgaccacgacttggtgagctattggtccaagggg
acccccccaaccctgaaaccaggcaggcgcccacccactcggagtgatcctatgagctcg
cggtgacagcttctagccaccactttaa-----------cattgcgtccctcatgaggca
gggagctcgatgg-----------------------------------------------
--------------------------aatggtcggagaagatagcctacggcacttacat
atatagggaagctgcggtgggcgggctacagatcactcggtggaaaacactaccgcaaac
atcttatgaaggagctattatacaattattcgctgagtaagtagtcaaggtaacg-----
-------ttccacagcacagt----------------gttcatttgtaccgtcccctggc
ggtgtcctactgaacaacttagacctaatgtaaagtgggctatcatagcacccatcgaca
tcggtc--------------------
>SEQ17
agcttcgtaaccgcgcttcgcgcaa--acgtccagtttactgtttgaaggcaatcactaa
atcgt---------------tctagcaaccccaggt------------------------
-tcc--------------------------------------------gaattcctgcca
gtacccaggt---cgtccaccctagagttgcgataatggcgtacgcgcggaagtttaagg
cgatatctgccccccatcgttggcatccttggagaatagtaatcacaccgcatgcactca
ttctctgccgttcaatgtatggttcgtgacctaggaatgagacaggctaca---------
--------------ccctatcctagagaatgaattaaataaact---------------c
agcgtcccggcagtcagtctttgatcaatcag-agcttatca------------------
------------tgtggcctgccaaattgagccctgcagtgttggacgtcatgtggagat
gtttcccgcgtgtatgtgtccagcaatgaccacgacttggtgagctattggtccaaaggg
accctcccaa--------------------atggccaatcggagtgatcatacgcggtcg
ccgtgacaccttctaaccacaagtttat--------------------------------
-------------------------------------cagtgagtcgccgcaccagtatg
taggttcgcaga--------------aatggtcggagaagatagcctacggcacttacat
atatagggaagatgcggtgggcgggctacagatcactcggtggaaaacactaccgcaaac
atcttatgaagaagctattatacaaatattcgctgagaaggttgtcaggttgtcgcccga
gggtcggttgtgtaacaaagtccggagaatca--------------------cccccggg
ggtgtccta-----------------------aagagtgctaccgtggcacccatcgaca
taagactcagtagtaacgctgtctcc
>SEQ18
cgtttcgtagccccgcttcgggcag--accaccggcata---------------------
--------------------gttaacatgcccagct------------------------
-tccaatctgccgcca-----------------------------acaggaaggcccct-
-------------tttccactctggggttgcgataatggcgtacgcgcggaagtctaagg
cgatatctgccgcccatcgttggcatccttggagaatagtaatcacaccgcatgcactca
ttcgctgcagttcaatgttttgtgctttaccgaggaccgaactagggtacagaggaccaa
gaagaatgttaacgcggtgtcctggagaatgatccatctc-------------------g
aacgtctcgctagtaagg-------------------tatcatgactgttagggtatccc
catgatatcggtctcggcctgccaaattgagccctgcagtgtaggacgtcatgtggagat
gtttcccgtgtgtatctgtccagcaatgaccacgacttggtgagctattggtccaaaggg
acccccccaaacctgataccaggcaggcgcctgcgcagtcggagtgatcctatgaggtcg
ccgtgacaccttctagccaccactttaa-----------cattagatcgctcatggcata
caacgactagggttttcctaca--------------------------------------
--------------------------aatggtcggagaagatagcctacggcacttacat
atatagggaagatgcggtgggcgggctacagatcactcggtggaaaacactaccgcaaag
atcttaggcagcagctattatacaatgattggctgagtaagaagtcaagctggcccccca
aagtcatttcgacaacacagtccggagaatcgcgtaagttcctttgtaccgtcccctggg
cgtgcgttactggacaacttaggcctaatgccaagtgtaatctcgtagca----------
-----------acagagcctgtgtgc
>SEQ19
agcttcgtagcgccgcttcgtgcat--ccctgctgcgtactggttgaagcaaatcatgac
acctt---------------tctagctatcccggct------------------------
-tcc-----------------------------------------ctagaaaggcacacg
cgatccagct---ttaccaccctgtggttgcgataatggcgaacgcgcggaagttcaagg
cgatatctgccccccatcgttggcatccttggagaatattaatcacaccgcatgcactca
ttctctgcagtttaagtctgggtaggtatcctagtcctgagaaaggttg-----------
------------------------------------------------------------
------------------------------------------------------------
------------------gcacctgattgagccctgcagtgttggtcgtcatgtggagat
gtttcccgtgtgtatgtgtccagcaatgaccacgacttggtgagctattggtccaaaggg
acccccttca--------------------cca---------------------------
-cctgttacttcct----------------------------------------------
------------------------------------------------------------
---gtttctact--------------aatggtcggagaagatagcctacggcacttacat
atatagggaagatccggtgggcgggctacagatcactcggtggaaaacactaccgcaaac
atcttatgaagaagctattatacaaatattcgctgagaaggtagtcagggtggcgcccga
gggtcgggtctataacacagtccggagaatcg--------------------cccccggc
gttgtactac----------------------aagagtgcttccgtggcacccatcgaca
tgagactcagtact------------
