>SEQ0
atgttcgagcttgcgtatccacgttagcctggcgcggcttgtattgtctccaatcaattg
atatctaatccctttatagacagctggcgtaaaacatcacagggtgctgggggttagtct
cctaatacgacatagcttcgggtccggacgctctcagtgggaggtcccccagctcaagac
aattttggttcaacgtgattgagtggccccggactgacccgtcaactgacttggggggag
tctacgccttttttcatattggggttaggtctacgagacggatctcctcgtttttaggga
aagtcagtcaatggggtcgtcgatagaggggaccctgaaaaaattcaagcttttgatcag
gcataggatacatggctcaaaattggcgaagacactgttattaccttataacctcaaatc
aggactagaaccggtccctctgtcccacaacagggaccgctgcacccttactgtcatag-
aattattgattcatggtacaactaatgctcgaacttcatttcctggattcttacgtggga
agacttccgtctctggaaaggaatgactgaaactctagtcatatggagatttagggaaaa
acaggtagttttgaagcctatgtaaatgtacttgaccacgatccattccgattaaagcct
ccataagggcggctcaaccgaccagatcggcgacatttcacccgattatacacatgtggc
tcccttcgacactattggtatcacgctccctagaagatcagtatattcaacccgcg-ata
ttcaggccttcaccggccagccacatccgggtcccttcctgcatttctaccggccagagt
atctcctgatgacatcctgtcgctggtgtcgagggtgagatttagcgtgacccgtacatt
tttggaaactaatatatagcatcagag------------gacgacccaaagaat--tggc
agtaggctggtcaacgagggcgcggagctcccttcgggagacgcactgtctgatgccccg
acccggggaggaggtctcaattgtctcgcacgtcaaaatagtattaaggcggacgggtcc
agggatagctaatgagtgttgacaaaaggcctgtac
>SEQ1
atgttcgagcttgcgtatcctcgttagcctggtgcagcttgtattgtctccagtcaattg
atatctcatcc--------------------aaacatcgcagggtggtggggattagtct
cctaatacgacataggtttgggtccggaccctctcagtgggag-----------------
-----------aacgtgatggagtggccccggactgacccgtcaactgacttggggggag
tctacgccttttttcatattggggttgggtctacgagacggatctcctcgtttttaggga
atgtcagtcaatggggtcgtccatagaggggaccctgaaaaaattcaagcttttgatcat
tcatacgatacattgctcaaaattggcg--------------accttttaacctccaatc
aggactagaaccggtcgcgctgtgcc----------------------tactgtcagag-
aattatagattcatcgtacagctaatgctcgaacttcatttcctggattcttacgtggga
agacttccgtctctggaaaggaatgactgaaactctagtcatatggagatttagggaaaa
acaggtagttttgaagcctatgtaaaggtacttgacctcgatccattccgattaaaggct
ccctaggggcggaccaaccgtccagatctgcgacattt----------------------
-----------ctattggtatcacgctccctagaatataagtatattcaacccgcg-ata
ttcaggccttcaccggccaggtacatccgggtcccttcctgcatttctaccgggcagagt
atctcctgatgacatcctgtcgctggtgtcgagggtgagatttagcgtgacccgtacatt
tttgg-------------------gag------------gacgacccaaagaat--tggc
agtagactgggctaccagggcgcggagcccccttggggagac------------------
---------------------tgtgtcgcacgtcaaaatagtattaagggggacgggtcc
agggataactaatgagtgttgacaaaaggcctgtgc
>SEQ2
atgttcgagcttgcgtatccccgctagcctggcgcgggttgtcttatcaccaaccaattg
atatctaatccctttatagacatctggcgtaaaacatcacagggtgctgggggttaggtg
c---------------ttcgggtgcggacgctgtcagtgggaggaaccccagtacaagtt
aattt-------------tggagtggccccggactgacccgtcaactgacttggggggag
tctacgccttttttcatattggggttgggtctacgagacggatctcctcgtttttaggga
atgtcagtcaatggggttgtccctagaggggaccctgaaaaaattcaagcttttgatcat
tcataggatacattactcaaaattggcg--------------accttttaacctccaatc
aggactagaaccggtcgcgctgtgcc----------------------ttcagtcagaa-
aaatatagattcatcctacagctaatgctcgaacttcatttcctggattcttacgtggga
agacttccgtctctggaaaggaatgactgaaactctagtcatatggagatttagggaaaa
ataggtagttttgaagcctatgttaatgtacttgaccacgatccattccgattcaaccct
ccataagggcggcgcaaacgaccagatctgcgacattt----------------------
-------------------------------------------cacccgatccgtgaaga
ctcaggccttcaccaggcaaccacatccgggtcccttcctgcatttctaccgggcagagt
atctcctgatgacatcctgtcgctggtgtcgagggtgagatttagcgtgacccgtacatt
tttgg-------------------tag------------gacgaccaaaagaat--tggc
agtagactgggctacccgagac--------------------------------------
---------------------tgtgtcgcacggaa-------------------gggtcc
agggattagtaatgagtgttgacaaaagggctgtgc
>SEQ3
atgttcgagc-----------------------gcggcttctattgtctccaatctattg
atatctaatccctttatagatagccggcgtaaaacatca---------------------
---aatacaacatagcttcgggtccggacgctctcagtgggatgtcctccagctcaagac
aattttggttcaacgggattgagtggccccggactgatccgtcaactgacttggggggag
tctacgccttttttaatattggggatgggtctacgagacggatctcctcgtttttaggga
acgtcagtcaatggggttgtacctgtaggggaccctgaaaaaattcaaggttttgatc--
---------------------attggcg--------------accttttaacctccaatc
a-----------------------------------------------------cagaa-
aaatatagatccatcctacggctaatgctcgaacttcatttcctggattcttacgtggga
agacttccgtctctggagaggaatgactgaaactctagtcatatggagatttagggaaaa
acaggtagttttgaagcgtatgtagaggtccttgacctcgatactttccgattaaaggct
ctctaggggcggaccaaccatcgagatctgcgacattt----------------------
-----------ctattggtaat-----------------------ttgaacacgcg-ata
ttcaggcctgcaccggccaggtacatccgggtcccttcctgcatttctaccggccagagt
ctctcctgatgacatcctgtcgctggtgtcgagggtgagatttagcgtgacccgtacatt
tt----------------------tat------------gacgaccaaaagaat--tgc-
------------------------------------------------------------
---------------------tgtgtctcacggaa-------------------gggtcc
agggatgagtgatgtgtcttgacaaaagggcaatgc
>SEQ4
atgatcgagcgtgcgtaaccccgccagcttggcgcgggctgtcttatcaccaaccaattg
ttttctaataactttatagacatttggcgtgaaacatcacagggtgcttggggttaggtg
c---------------ttcgggtgcagacgctgtcagtgggaggaatcccagtacaagtt
aattt-------------tggagtggccccggactgatccgtcaactgacttggggggag
tctacgccttttttaatattggggatgggtctacgagacggatctcctcgtttttaggga
aagtcagtcaatggggtcgtcgatagaggggaccctgagaaaattctagctttagatcag
gcataggatacatggctcaacattggcgaagaccctgttacttccttataacctgaaatc
aggactagatcccgtccctctgtccc-----------------------acaacagggg-
acttattgattcatggtacaactaatgctcgaacttcatttcctggattcttacgtggga
agacttccgtctctggaaaggaatgactgaaactctagtcatatggagatttagggaaaa
acaggtag-------------------------gacctcggtccagtccgagt-------
-----------------------agatctgcgacatat----------------------
-----------ctacaggtgtcacgctccctagaatataagtatattcaacccgcg-gtg
ttcaggccttccccggccaggtacatccgggtcccttcctgcatttctaccggccagagt
ctctcctgatgaaatcctgtcgttggtgtcgagggtgagatttagcgtgacccgtacatt
ttggg-------------------gag------------gacgacccacagaat--tggc
agt-------------agggcgcggagcccccttggggaga-------------------
--c------------------tttggcgcacgtcaaaatagtattaaggcggacggggcc
aggtat--------------------aggcctgtgc
>SEQ5
atgatcgagc-------------------tggcgcgggctgtcttatcaccatccaattg
ttttctaattcctttatagacagttggcgtgaaac---------------ggggcagatg
c---------------ttcgggtggagacgctgtcagtgggaggaatcccagttcaagtt
aattt-------------tggagtggccccggactgatccgtcaactgacttggggggag
tctacgccttttttaatattggggatgggtctacgagacggatctcctcgtttttaggga
aagtcagtcgatggggtcgtcgatagagggggccctaagaaaatactagctttagatcag
gcataggatacatggctcaacattggcgatgaccctgttacttccttataagctgagatc
aggactagttcccgaccctctgtccc-----------------------acaacagggg-
acttagtgattcatggtacaactaatgctcgaacttcatttcctggattcttacgtggga
agacttccgtctctggaaaggaatgactgaaactctagtcatatggagatttagggaaaa
acagttag------------------------------cggtccagttcgagt-------
-----------------------agatctgcgacatat----------------------
-----------ctacatgtgtcacgctccctagaatatcagtctaatcaacccgcg-gtg
ttcaggccttcccccgccaggtacatccgggtcccttcctgcatttctaccggccagagt
ctctcctgatgacatcctgtcgctggtgtcgagggtgagatttagcgtgacccgtacatt
tttgg-------------------aaactaaaatatagcagcaggcagtaggat--tgtc
aacg------------agggcgcggagctcccttcgggagacgcaccgcctgatgccccg
acc------------------cgtctcgcgcgtcaaaatagtattaaggcggacgggtcc
atggatagatagtcagtgttgacaaaaggcctgtac
>SEQ6
ctgatcgagcgtgcgtaaccccgccgacttggcgcaggtaataacatcg-----------
-------------------------------aaacaccacaggttg--------------
----------------tttgggtgcagacgctgtcagtgggaggaatcccagttcaagtt
aattt-------------tggagtggccccggactgacccgtcaactgacttggggggag
tctacgccttttttcatattggggttgggtctacgagacggatctcctcgtttttaggga
atgtcagtcaatggggtcgtccttagcggggacc----------------ttttgatcat
tcatacgctacaatgctcaaaattggcg--------------accttttgacctcca---
---------------cgtgctgtgcc----------------------cactgtcagag-
cattatagatttctattac--ctaatgctggaacttcatttcctggattcttacgtggga
agacttccgtctctggaaaagaatgactgaaactctagtcatatggagatttagggaaaa
ataggtagatttgaagcctatgttaatgtacttgaccacgatacattccgattcaaccct
ccataagggcggcgcaaacgaaaagatctgcgacattt----------------------
----------------------------------------------------cacccgat
ctcaggacttcaccaggcaaccacatccgggtcccttcctgcatttctaccggccagagt
ctctcctgatgacatcctgtcgctggtgtcgagggtgagatttagcgtgacccgtacatt
ttagg-------------------gag------------gacgacccatagaat--tgga
ataggatcccccttggggc-----------------------------------------
---------------------tgtgtcgcacgtccaaatagta-----------------
agggataactaatgagtgctgacaaaaggcctgtgc
>SEQ7
atgtacgagcttgtgtatccccggtcgcctgtcgcagattgt------------------
atatctcatcc--------------------aaacatcggggggtggtggagattagtct
cctaataccgcatatgtttgggtccggagcctctcagtgggag-----------------
-----------aacgtgatggagtggccccggactgatccgtcaactggcttggggggag
tctacgccttttttaatattggggatgggtctacgagacggatctcctcgtttttaggga
atgtc-------------------agaggggaccatgaaaaaattcaagcttttgatcat
tcataggagacataactcaaaattggcg--------------accttttaacctccaatc
aggactagaacccgtcgggctgtgcc----------------------ttcagtccgaa-
aaatatagattcgtccgaaaactaatgctcgaacttcatttcctggattcttacgtggga
agacttccgtctctggaaaggaatgactgaaactctagtcatatggagatttagggaaca
acagg------------------------gtgtgacctcgatactttccgattaaaggct
ctctaggggcggaccaaccatcgagatctgcgacattt----------------------
-----------ctattggtgat-----------------------tagaacacgcg-ata
ttcaggcctgcacc--------acatccgggtcccttcctgcatttctaccgggcagagt
atctcctgatgacatcctgtcgctggtgtcgagggtgagatttagcgtgacccgtacttt
tttgg-------------------tag------------gacgaccaaacgagt--tggc
agtagtctgggtc-----------------------------------------------
---------------------tgtctcacacggaa-------------------------
---------------------gcaagagggctgtgc
>SEQ8
atgatcgaccgtgcgtaaccccgccagcttggcgcggactgtcttaccaccgaccaattg
tttcctaataacttcatagataggtgc---------------------------------
----------------ttcgggtgcagacgctgttagtgggaggaatcccagtacaagtt
aattt-------------tggagtggcctcggactgatccgtcaaccggcttggggggag
tctacgccttttttaatattggggatgggtctacgagacggatctcctcgtttttaggga
aagtcagtcgatggggtcgtcgatagatcgag----------------------------
-cataggatgcatggctcagcattggagatgaccctgttacttccttataagccgagatc
gcggctactgaccgaccctctgt-cc----------------------cacaaaagggg-
acttagtgattcatggtacaactaatgctcgaacttcatttcctggattcttacgtggga
agacttcggtctctggaaaggaatgactgaaactctagtcatatggagatttagggaaaa
acaggtagtgttgaagcctatttcaatgtactggaccacgacccattccgatttaagcct
ccataagtgcggctcaaccgaccagatcggcgacagttcacccgagtatacacatgtcgc
tcccttcgacactattggtaacacgctacctagaacatccgtatcttcaacccgcg-ata
ttcagtccttcatcggccagcgacatccgggtcccttcctgcatttctaccgggcagagt
atctcctgatgacatcctgtcgctggtgtcgagggtgagatttagcgtgacccgtacttt
gtagg-------------------------------------gactcatagaat--tgga
atatgatccccctc----------------------------------------------
---------------------ggtgtcgcacgtccaaatagga-----------------
agggataactaatgagtgctgacaaaaggccggtg-
>SEQ9
aggttagagcttgcgcatccacgttagcctggcgcggctagtattgtctccaatcaattg
atatggaatccccttatagacagctggcgtaaaacatcgcaggatagc------------
----------------ttctggtccggacgctcgctgtgggagttgccccagcttaagac
aattttggttaaacgttattgagtggccccggactgatccgtcaactgacttggggggag
tctacgccttttttaatattggggatgggtctacgagacggatctcctcgtttttaggga
aggggagtcgataggctggtcgatagagggggccctaagaaaatcctagctttagatcag
gcataggatacatggctcaacattggcgatgaccctgttacttccttataagctcagatc
aggactaggtcccgaccctttgtccc-----------------------acgacagggg-
acttagtgattcatggtagaactaatgctggaacttcatttcctggattcttacgtggga
agacttccgtctctggaaaagaatgactgaaactctagtcatatggagatttagggaaaa
acaggtagttttgaagcctatgtaaggtcacttgacctcgttccactccgattaaaggct
ccgtcggggcggaccaaccgtccagatccgcgacattt----------------------
-----------ctatttgtcgcacgctcccttgaatataagtatattcaacccgcg-ata
ttaaggcc--------------acatccgggtcccttcctgcatttctaccgggcagagt
atctcctgatgacatcctgtcgctggtgtcgagggtgagatttagcgtgacccgtacttt
tttgg-----------------tag--------------gacgacctaacgagt--tggc
cgtagtctgggtc-----------------------------------------------
---------------------tgtctctcacggcagcatgagttctgtgc----------
------------------------------------
>SEQ10
atgttcgagcttgcgtagcctcgttagcgtggtgcagcttatattgtctccagtgaattg
aggtcacatcc-------------caacat-------cgcagggtggtggggattactat
cctaaaacgacaaaggtttgggtccggagcctctcag-----------------------
------------------tggagtggccccggactgacccgtcaactgacttggggggag
tctacgccttttttcatattggggttgggtctacgagacggatctcctcgtttttaggga
aaatcactcaatggggtcgtcgattgcgaggaccctgagaaaattctagctttagatacg
gcataggatacatggctca---------------------------tataacctgaa---
-------gatcccgtccctctgtcccacac------------------------------
acttattgattcatggtaccactaatgctggaacttcatttcctggattcttacgtggga
agacttccgtctctggaaaagaatgactgaaactctagtcatatggagatttagggaaaa
acagg------------------------gtgtgacctcgatactttccaattataggct
ctctaggcgcgg------------------------------------------------
--------actctattggt----------------gattagaacacgcg--------ata
ttcaggcctgcact--------acatccgggtcccttcctgcatttctaccgggcagagt
atctcctgatgacatcctgtcgctggtgtcgagggtgagatttagcgtgacccgtacttt
gttgg-------------------------------gaggaggacccaaagaat--tggc
agttgactcggctaccagggcgcc------------------------------------
---------------------tgtgtcgcaagtctaaatactattaagggggtcgggtcc
gacaa-------------------------------
>SEQ11
aggttagatcttgcgcat--------------------tagtcatgtctcccatcaattg
atatggaatccccttatagacagctggcgtaaaacatcgcaggat---------------
-----------------------------------agcttgagttgccccagcttaagac
aattttagttaaatgttattgagtggcccgggactgatccgtcaactgacttggggggag
tctacgccttttttaatattggggatgggtctacgagacggatctcctcgtttttaggga
aagtcagtcaatggggtcgtcaatagagggggccctgcgaatattcgagctttagatcag
gcataggatacatggctcgacattgtggaagaccctgttacttctctatgacctgaaatc
aggactagctcccgtccctctgtccc-----------------------acaacagggg-
a------------------aactaatgctctaacttcatttcctggattcttacgtggga
agacttcggtctctggaaaggaatgactgaaactctagtcatatggagatttacggaaga
acaggtagttgtgaagcctatgaaaaggtac---------------------taaaggct
ccctagcggcggaccaaccgtccagatctgcgacattt----------------------
-----------ctattggtatcacgctccctagaatttaagaatattcaacccgcg-ata
ttcaggccttcactggccaggtacatccgggtcccttcctgcatttctaccgggcagagt
atctcctgatgacatcctgtcgctggtgtcgagggtgagattcagcgtgtcccgtacttt
tttag----------------------------------------cagtaggat--tgtc
aacg------------agggtgctgagctcccttcaggaga-------------------
---------------------cgtgtcgcgagtcaaaatagtattaaggcggacgggccc
atggatgggcagttactgttgacaaaaggcctgtac
>SEQ12
ctgaactatcgtgcgtcaccccgacgacttggcgcaggtaataacatcg-----------
-------------------------------aaacaccacaggttatt------------
---------------------------tcgctgtccgt------------------tgtt
aattt-------------tggagtggcctcggactgatccgtcaaccggcttggggggag
tctacgccttttttaatattggggatgggtctacgagacggatctcctcgtttttaggga
atgtca-------------------gaggggaccatggaaacattctaatt---------
--------------------------------------ggccaccttttaacctcccatc
aggactagaagccgtcgggctgtgct-----------------------ttcataccgga
aaatattgattcgtccgaaaactaatgctcgaacttcatttcctggattcttacgtgggt
agacttccgtctctggaaaggaatgactgaaactctagtcatatggagatttagggaaaa
acaggtagttttgaagcctatgtaacttcacttgacctcgttccacaccgagtaaaggct
ccgtcggggc-------------agatccgcgacaact----------------------
-------------------------------cgatttgaagtatatactacccgcg-ata
ttaaggcc--------------acatccgggtcccttcctgcatttctaccgggcagagt
atctcctgatgacatcctgtcgctggtgtcgagggtgagatttagcgtgacccgtacttt
tttggaaactaatacatagcatcagag------------gaagacacaaagaat--aggc
aataggcttgtcaacgaggg--------------------acgcactgtctgatgcccct
acccgggcaggaggtctcaattgtctcgtgcgtcaacatagtataaaggacgacgggccc
aggaatagctaatgagcgttgacaaaaggcctgtac
>SEQ13
attttcgcgcttgcgtatc----------------------tcctatcaccaaccaattg
atttctcatccctttataaacatctggcgtaaaacatcacagggtgctcggggttaagtc
t---------------ttcgggttcggacgctctcagtgggagggatcccagtacaag--
------------------ttgagtggcctcggactgatccgtcaaccggcttggggggag
tctacgccttttttaatattggggatgggtctacgagacggatctcctcgtttttaggga
aagtcagtcaatgcggtcgtcgatagaggggaccctaaaaaaattcaagcttttgatcag
gcataggatacacggctcaaaattggcgaagacactgttgttaccttataacctcaaatc
aggacttgaaccgctccctctgtccc-----------------------acaacacgaac
cgctgcgccatcatggtacaactaatgctcgaacttcatttcctggattattacgtggga
agacttccgtctctggaaaggaatgactgaaactctagtcatatggagatttagggaaca
ataggtagatttgcagcccattttaatttacttgaccacgcttcattccgattcaaccct
ccataagggcgtcgcaaaggaaaagatcttcgacattt----------------------
----------------------------------------------------cgaccaat
ctcaggacttcaccaggaaaccacatccgggtcccttcctgcatttctaccgggcagagt
atctcctgatgacatcctgtcgctggtgtcgagggtgagatttagcgtgacccgtacttt
gttag-------------------------------------------------------
------------------------------------------------------------
------------------------------cagtagcttcaagtggcggcggacgggccc
gcggatgggcagttaca-------------------
>SEQ14
atgtacgagcttgtgtatcccctgtcgcctgtcgccgattgt------------------
atatctcatcc--------------------aaacatcggggggtggtgga---------
----------------tttgggtccggagcctctcagtgtgag-----------------
-----------aacgcgacagagtggccacggactgatccgtcaactgacttggggggag
gctacgccttttctaatattggggatgggtctacgagacggatctcctcgtttttaggga
acgtaagtcaatggggttgt----------------------------------------
--------------acctgtagttggcg--------------accttttaacctccaatc
a-----------------------------------------------------ccgaa-
aaatatagatccatcctacggctaatgctggaacttcatttcctggattgttacgtggga
agacttccgtctctggaaaagaatgactgaaactctagtcatatggagatttagggaaaa
actggtgtacttta---------------------------------------ctagcct
ccataagggcggctcaaccgtcc------------------ccgattatacgcatgtggc
gcccttcgacactattggtatcacgcagcctacaagatcagtatattgaacgcgcg-ata
ttcagtccttcaccggccaaccacatccgggtcccttcctgcatttctaccgggcagagt
atctcctgatgacttcctgtcactggtgtcgagggtgagattcagcgtgtcccgtacttt
ttagg-------------------------------------gaatcacagcat--tgga
atatgatccccctc----------------------------------------------
---------------------ggtttcgcacgtccaaatagga-----------------
-------------gagtgatgggaaaaggccgggg-
>SEQ15
attttcgcgcttgcg------------------------tatcttatcaccatccaattg
atttcttattc-------------tggcgtaaatcagcacagggtgctcggggtt-----
---------------------------aagttacaag-----------------------
------------------ttgagtggccccggactgacccgtcaactgacttggggggag
tctacgccttttttcatattggggttaggtctacgagacggatctcctcgtttttaggga
taatcgctcaatggggtcgtctattgcgaggacccttagaaaattctagctttatatacg
gcataggatacatggctca---------------------------tataacctga----
--------------------tgtcccaca-------------------------------
--atattgattcattgtaccactaatgctggaacttcatttcctggattcttacgtggga
agacttccgtctctggaaaagaatgactgaaactctagtcatatggagatttagggaaaa
actg---------------------------gtggacttaac------------tagcct
ccataagggcggctcaaccgtgc------------------ccgattatacgcgggtagc
gccctttcacactattggtatcacgcagcctgcaagatcagaatattga--------att
gaccgg--aaaacc--------acatccgggtcccttcctgcatttctaccggccagagt
ctctcctgatgacatcctgtcgctggtgtcgagggtgagatttagcgtgacccgtacatt
tttgg-------------------------------gaggaggacccaaagtat--tggc
atttcactcggcaaccaggg----------------------------------------
--------------------------agcaagccaa------------------------
------------------------------------
>SEQ16
aggttacagcttgcgcatccacgttagcctggcgcggctagtattgtctccaatcaattg
ataaggaatccccttatatgcagctgacgtaaaacctcgcatgatagc------------
----------------ttctggtgcggacgctcgctgtgcgagctgccccagcttaagac
aattttggtttaacgttattgagtggccccggactgacccgtcaactgacttggggggag
tctaagccttttttcatattggggttaggtctacgagacggatctcctcgtttttaggga
aagtcagtcgagggggtcgtcgatagagggggccctaagaaaatactctgtttagatcag
gcataggatacatggctcagcattggcgatgacccggtcacttccttataagctgagaac
aggactagttcccggccctctgtccc-----------------------acaacagcgg-
acttagtgattcatggtacaactaatgctcgaacttcatttcctggattcttacgtggga
agacttccgtctctggaaaggaatgactgaaactctagtcatatggagatttagggaaca
acagg------------------------------------------gtgattataggct
ctctaggcgcgta-----------------------at----------------------
-----------ctattgg-------------cgaatagaa--------------------
--aacgcg--------------acatccgagtcccttcctgcatttctaccggccagagt
atctcctgatgacatactgttgctggtgtcgagggtgagatttagcgtgacccgtacatt
ttagggaatcacagcattggaatag--------------gatcgccctgagagtgatggt
aaaaggccgggg------------------------------------------------
------------------------------------------------------------
------------------------------------
>SEQ17
ctgatcgagcgtgcgtaaccccgccgactttgc---------------------------
------------------------------------------------------------
-----------------ccaggtgcagaagctgtcagt----------------taagta
aattt-------------tgcagtggccccggactgatccgtcaactggcttggggggag
tctacgccttttttaatattggggatgggtctacgagacggatctcatcgtttgtaagga
atgtcagacaatggggtcgtccatagaggggaccctgtaaaaatgcattttttagagcat
tcatgcgatacattgctcaaaacttg---cgaccttttaacttcc-----aatcaggacc
agagccgtt------cgcgctgtgcc----------------------tactgtcagag-
aactatagattcatcgaacagctaatgctcgaacttcatttcctggattcttacgtggga
agacttccgtctctggaaaggaatgactgaaactctagtcatatggagatttagagaaca
ataggacgtattgaagtctatttcaatgtactggaccatgacccattccgatttaagcct
ccctgagtgcggctcaaccgactagatcggcgacagttcacccgagtatacacatgtcgc
tcccttcgacactattggtaagacgctacctaaaacctccttatctacaacccacg-ata
ttctgaccttcatcggcgagcgacatccgggtcccttcctgcatttctaccggccagagt
ctctcctgatgaaatcctgtcgtcggtgtcgagggtgagatttagcgtgacccgtacatt
ttagg-------------------------------------a------tgaat--tgga
atatgatccc---c----------------------------------------------
---------------------ggtgtcgcacgtccaaatagga-----------------
agtgataactgatgagtgctgacaaaaggccggtg-
>SEQ18
aggttacagcttgcgcatccacgttagcccggcgcggctactattgtctccaatcaattg
ataaggaatccccttatatgccgcagacgtaaaagctagcaagatagc------------
----------------ctctggtgcggacgctctctgtgcgagctgcc------------
------ggtttaacgttattgagtggcctcggactgatccgtcaaccggcttggggggag
tctacgccttttttaatattggggatgggtctacgagacggatctcctcgtttttaggga
aagtcaggcaatatggtcgtcggtagaggggaccctgggaacattcaagcttttaatcag
gcataggatacatggctcaaaattggcgaaga---------------------------c
acgactagaaccggtccctctcccccacaacaggtaccgccgcacccttcctgtcccac-
aattattgattcatggtataactaatgctggaacttcatttcctggattcttacgtggga
agacttccgtctctggaaaagaatgactgaaactctagtcatatggagatttagggaaaa
acagg--------------------------------gtgatactttacaattataggct
ctctaggcgctgac----------------------------------------------
-----------ctattggtggt-----------------------tagaacacggg-ata
ttcaggcttgcact--------acatccgggtcccttcctgcatttctaccgggcagagt
atctcctgatgacatcctgtcgctggtgtcgagggtgagatttagcgtgacccggacttt
gtagg-----------------------------------atgaattggaatatgatccc
c-----------------------------------------------------------
---------------------ggtgtcgcacgtccaaatagga-----------------
----------------agtgataacaaggccggtg-
>SEQ19
aggttagatcttgcgcat--------------------tagtcatggctcccatcaattg
atatagaatccccttctagacagctggcgtaaaacaccgcaggat---------------
-----------------------------------agcctgagtggccccagcgcaagac
aatttcaattaaatgttattgagtggccccggactgatccgtcaactgacttggggggag
tctacgccttttttaatattggggatgggtctacgagacggatctcctcgtttttaggga
aagtcaggcaatatgctc----------------------acactcaagcttttaatcag
gcataggatacatggctcaaaattggtgaaga---------------------------c
acgactagaaccggtccctctccatcacaagaggtaccgccgcacccttcctgtcccac-
aattatcaattcatggtataactaatgctcgaacttcatttactggattattacgtggga
agacttccgtctctggaaaggaatgactgaaactctagtcatatggagatttagggaaca
ataggtagttttgaagcctacgttaatgtacgtgaccacaatccattccgatttaaccct
ccataagtgcggcgcaaacgaccagatctgccacattt----------------------
------------------------------------------------------------
-----ctccccgtgaagaatccacatccgggtcccttccttcatttctaccgggcagagt
atctcctgatgacatcctgtcgctggtgtcgagggtgagatttagcgtgacccgtactct
tttggaaattattgtaaagtatcagag------------gaccacccaaaggaa--tggc
attaggctggtcaacgagggtgcggatctcccttcgggagacgcactgtctatagccccg
acc-------------------------------------------------------cg
gggaggaggtcggaagtgtcgacaaaaggcctgtac
