>SEQ0
gagaaatttgggcgggtttgctggaagttttgcgagtaagtgttaaccagagtacgtatg
agaattggctatctcccagtcgctttacctatgcatcgagtattggctccgtcaagtcgc
gccgacacgtgtttgttataacgtgctcgctttgcctggcctccaggattctcactaggt
gtgagaattcggggatgtttatagttagccacatgaaagatagcgatggcatcccgcagc
actcttcgtcgaaggggcaaagattgttgtagctgaccgcaaactctcagcaatgtctta
gcaaactcctttaggacagtattgtaatgcagtgtggtgtagctttcgacgcttcaaact
tatctagtcaaaacacctgtccttatcataacattgcggcagtaccttttcaatccttaa
gctcgcgtgcaatcggactttcggcgatgtaaatgttgtctaatcggttagtgcgccctt
agactcgccaagaccgttcggcgttgaaatcttatatcaggataccatcctgtagatttt
ctgtccgtcggcattatccaggccgcgtactctactcgttccaggaagacgaagaaggag
aaagctgtgtgtcgataagcgcacctcgagacggttattgctctcatttcgagagttgac
cgcagttagtagcagagttattctgtgccgtaaggtccggagcgacactgcctgggtata
tgtatctaaaacatcccccgtctgattgctaaaattaaacccacccactgaacgcgccga
acagagagccatgactgaggtctcctcttaatgtggcctgtcaaacgccttatattagtc
aatctattgtctcattccgttgtgccggggaacgattgcatgaagccttatcccccgtta
cgtccacggcgcaccattcttttattaaacattacgcccatcgcacactgtcagaaagga
ccatatagattcacaccctagtcagtctagagctgtgttataggacatttaccgggtaca
cagacgaatgcccaccagagagctcgccctcaccacacaggctgtcataaaagcctagat
cctaccaactattcggctct
>SEQ1
gagaaatttgggcgagtttgctggaagctttgcgagtaagtgttagccagagtacgtatg
ataattggctatctcccagtcgctttagctatgcatcgag--------------agtcgt
gccgacacgtgtttgttataacgtgctcgctttgcctggcctccaggattctcactaggt
gtgaggattcggggatgttcatagttagccacatgaaagatagcgatggcatcccgcagc
actcttcgtcgaaggggcaaagattgttgtagctgaccgcaaactctcagcaatgtctta
gcaaactcctttatgacagtatggtaatgcagtgtggtgtagctttcgacgcctcaacct
tatctagtcaaaacacctgtccttatcattacattgcggcagtacctttttaatccttaa
----------------------ggcgatgtatttgttgtctaatcggttagtgcgccctt
agactcgcc-----------gcgttgaaatcttatatcaggataccatcctgtagatttt
ctgtccgtcggcattatccaggccgcgtactctactcgttccaggaagacgaagaaggag
aaagctgtgtgtcgataatcgaacctagagacctttattgctctcatttggagagttgcc
cgcagttagtagcag-----------------tggtccggagcgacgctgcctgg-----
----------------cccgtgatattgctaaaattaaacccacccactgaacgcgccga
acagagagtcatgactgaggtctcctcttaatgtggcctgtcaaacgccttatattagac
aatctattgtctcattccgttgtgccggggaacgattgcatgaagccttatcccccgtta
cgtccacgacgcaccattcttttaataaacattacgcccagtgcataatatcaga-----
-----------------------------------tcatataggacatttaccccgtaca
caggcgaatgcccaccagagtgctcgtcctca----------------------------
-----caactattcggcttt
>SEQ2
gagaaacttgggcgggtttgcaggaagttgtgccagtaagtgttatccagagttcgtaag
agaattggctat--------------------gcctctagtattggcttcgtcaagtcgc
gtcgacacgtgttggttataacgtgctcatt----------------attctcactaggt
gtgtgaattcggggatgtttatagttagccacatgaaagatagcgatggcatcccgcagc
actcttcgtcgaaggggcaaagattgttgtagctgaccgcaaactctcagcaatgtctta
gcagactcttttatgacagtttggtattacaacgtaa----------------------t
tatctagtc---------------------acattgcggc--------------------
----------------acctaaggcgatgtatttgttctctactcggttagtgcgcactt
agcctcgcc-----------gcgttgaaatcttatatcaggagaccatcctgtagatttt
ctgtccgtcggcattatccaggccgcgtactctactcgttccaggaagacgaagaaggag
aaaggtgtgtgtcgatagtcgaacctagagtcctttattgctctcactcggagagttgcc
cgcagttagtaacag-----------------tcgtccggatcgacgctgcctgg-----
---------------------------------attaaacccacccactgaacgcggcga
acagaaagtcatgactgaggtctcctcttaatgtggcctgtcaaacgccttatattagtc
aatctattgtctcattacgttgtgccggggaacgattgcatgaagccttatcccccgtta
cgtccacgacgcaccattcttttaataaacattacgaccagtgcataatatcagg-----
-----------------------------------tcata--------------------
---------------gcgaatgcaaggcttt-----------------------------
--------------------
>SEQ3
gggaaacttgggcgggtttgcaggaacttgtgcgagtaagtgtaatccagagctagtaaa
agaattggctat--------------------gcctctaggattgccttcgtcaagtcgc
gccgacacgtgtcggttataacgtgct--tt----------------attcccacaaggt
gtgtgaactcggggacgtgtatagttagccacatgaaagatagcgatggcatcccgcagc
actcttcgtcgaaggggcaaagattgttgtagctgaccgcaaactctcagcaatgtctta
gcaaactcctttatgacactattgtaatgcagggtggtgtagctttcgatgcttccaact
tatctagtcaaaacacctgtccttatcataaccttgcggcagtaccttttcaatccttaa
gatcgcgtgcaatcggacttgcggcgatgtaaacgttgtctaatctgttagtgcgccctt
agactcgccaagaccgttcggcgttgaaatcttatatcaggagaccatcctgtagatttt
ctgtccgtcggcattatccaggccgcgtactctactcgttccagtaagacgaagaaggag
aaaggtctctgtcgatagtcgagcctagtggccttaattgctctcactcggagagttgcc
cgcagttagtaacag-----------------tcgtccggatcgacgctgcctgg-----
---------------------------------attaaaaccacccactgaacgcggcga
acagaaagtcatgactgaggtctcctcttaatgtggcctgtcaaacgccttatattagtc
aatctattgtctcattacgttgtgccggggaacgattgcatgaagccttatcccccgtta
cgtccacgacgcaccattcttttaataaacattactcccagtgcataatatcaga-----
-----------------------------------tcatacaggacattttccccctaca
caggcgaatgcccacgagagtgcacgtcctca----------------------------
-----catccactcggcttt
>SEQ4
gagaaatttgggcgggtttgccggaagttctgcgagtaagtgttaaccagagtacgcatg
agaattggcaatctcccagtcggtttacc-------------------------tgtcgg
ggcgacacttgtttgtaatagcgtgctcgctttgcctgggctccaggattctc-------
----------------gtttatagttagccacatgaaagatagcgatggcatcccgcagc
actcttcgtcgaaggggcaaagattgttgtagctgaccgcaaactctcagcaatgtctta
gcaaactcccttatgacactattgtaatgcagggtggtctatctttcgaagcttccaact
tatctagtcaaaacacctgtccttatcctaaccgtgcggcagtaccttttcaattcttaa
gatcgcgtgcaatcggacatgcggcgctgtaaacgttgtctaatctgttagtgcgccct-
--------------------gcgttgaaatcttatatcaggagaccatcctgtagatttt
ctgtccgtcggcattatccaggccgcgtactctactcgttccagtaagacgaagaaggag
aaaggtgtgtgtcaatagtcgaacctcgagtgttttattgctctcactcggggagttggt
cgcagttagtaacag---------------------------------------------
-------------------------------tcattcaccccacccactgaacgcggcga
acagaaagtcatgaatgaggtctcctcttaatgtggcctgccaaacgccttatattagtc
aatctattgtctcattccgttgtgccggggaacgattgcatgaagccttatcccccgtta
cgtccacgacacaccatacttttaataaacattacgcccagagcattatatcaga-----
------------------------------------------------tcaccccgtaca
caggcgaatgtccaccagggtgctcgtcctca----------------------------
-----caactattcgtctct
>SEQ5
gagaaacttgggcgggtttgaagtaagttgtgcgagcaagtgttatccagagttcgtaac
agaattggct----------------------gccactatcattggctgcgtcaaatcgc
ctggaaacgtgcttgttataccgtgttcatt----------------attctcaccaggt
gtttgaattcggggctttttatagttagccacatgaaagatagcgatggcatcccgcagc
actcttcgtcgaaggggcacaggttgttgtagctgaccgcaaactctcagcaatgtctta
gcaaactc---------------------------ggtgtagc-----------------
-------tcaaaacacctatccttatcataac----------------------ccttaa
gctcgcgtgcaaacggactttcggcggtgtaaatgttgtctaatcgattactgcgccctt
agactagccaagaccgttcggcgttgaaatcttatatcaggagaccatcctgtagatttt
ctgtccgtcggcattatccaggccgcgtactctactcgttccagtaagacgaagaaggag
aaagctgtgtgtcgataagcacacctcgatacggttattgttctcatttcgagagttgac
tgcagtaagtaacagagttattctgtgccgtaaggtccggagaggcactgactgggtata
tgtatctaaaacatccctcgtctgattgataaaattaaacccacccaatgaacgcgccga
acaga--------------gtctcctcttaatgtggcctgtcaaacgccttatattagtc
aatctattgtctcattccgttgtgccggggaacgattgcatgaagccttatcccccgtta
cgtccactgcgcaccattcttttattaaacatttcgcccatcgcacactgtccgaaagga
ccatatggatttagagctg----------------tgttataggacatttaccgggtata
cagacgtacgccccccatagagctcgccctcaccacacacgctgtcataaaagcctggat
--------------------
>SEQ6
gagaaatttgggcgaat----------------------gtgttagccaccgtacgta--
-------------------tctctttagctatccatcgag--------------------
---------tgttcgttataacgtgctcgctttgcctgacctccaggattctaactaggt
gggaggattcggggatgatcatagttagccacatgaaagatagcgatggcatcccgcagc
actcttcgtcgaaggggctaagattgttgtagctgaccgcaaactctcagcaatgtcttt
gcaaactc---------------------------ggtgtagc-----------------
-------tcgaaacacctagcgttatcgtaac----------------------ccttaa
tctcgcgtgcgaacggactttcggccgtgtaaatgttgtctaatcgattactgcgcccgt
agattagccaagacggttcggcgttgaaatcttatatcaggagaccatcctgtagatttt
ctgtccgtcggcattatccaggccgcgtactctactcgttccagtaagacgaagaaggag
aaaggtgtgtgtcgatattcgaaccgagattccttaattgctgtcactcggagagttgcc
cgacgttaggaacag-----------------tcgtccggatcggcgc------------
---------------------------------attatacccacccactgaacgcggcga
tcagaaagccatgactgaggtctcctcttaatgtggcctgtcaaacgccttatattagtc
aatctagtgtctcattacgttgtgccggggaacgattgcatgaagccttatcccccgtta
cgttcactgcgcatcatacgttgattaaacctttcgcccatcgcacactgtccgg-----
--------------------------agagagctgtgttataggacatttaccgggttta
cagacgtacgccccccatagagctccccctcaccacacacactgtcataaaagcatggat
--------------------
>SEQ7
gagatacttggccgggtttaaagaaagttgtgcgagcaagtgttatccagagttcgctac
agaaatggctgc------------------------------------------------
------------------------------------cagcctggaaacttctcaccaggt
gtttgaattcggggctttttatagttagccacatgaaagatagcgatggcatcccgcagc
actcttcgtcgaaggggctaagattgttgtagctgaccgcaaactctcagcaatgtcttt
gcaaactcccttatgacactattttaatacagggtgctctatctttc-------------
------------------------------------cggcactaccttttcaattcttaa
gctcgcatgcggccgg-----------------------ccaatctgatagtgcgccct-
--------------------gcgttgaaatcttatatcaggagaccatcctgtagatttt
ctgtccgtcggcattatccaggccgcgtactctactcgttccagtaagacgaagaaggag
aaaggtctctgtcgatagtcgagcctagtggccttacctgctctcactgggagagttacc
cgcagttagtcacag---------------------------------------------
--------------------------------tattaaaaccaccaaccgaatgcggcga
acagaaagtcatgactgaggtctcctcttaatgtggcctgtcaaacgccttatattagtc
aatctattgtctcattccgttgtgccggggaacgattgcatgaagccttttcccccgtta
cgtccacgacgcaccattctcttaataaacattacgaccattgcataatatcagg-----
-----------------------------------tcatgcaagacttt-----------
------------------------------------------------------------
--------------------
>SEQ8
gagagatttgggcgggtttgctggaagtta------------------------------
--------------gtaagtcgttttacctattgatccagtaatggttccgtcaagtcgc
gccgacatgtgtttgttataacgtgctcaatttgcctgtactccaggcttcccactagga
gcgtgagttaagggatgtttatagttagccacatgaaagatagcgatggcatcccgcagc
actcttcgtcgaaggggctaagattgttgtagctgaccgcaaactctcagcaatgtcttt
gcaaactcccttatgacactattgt---------------------cgaagcgtccaact
tatccagtcaaaacacctggccttatcctaaccgttcggcagtaccttttcaattcttaa
g---------------------------agaaatgttgtctaatctgttagtgcgccct-
--------------------gcgttgaaatcttatatcaggagaccatcctgtagatttt
ctgtccgtcggcattatccaggccgcgtactctactcgttccagtaagacgaagaaggag
aaagggccctgtcgatagtcgagcctggtggccttaattgt-------------------
--------------------------------aaggccggatcgacgcagcctgg-----
---------------------------------attaaaaccacccactgaacgcggcga
acagaaagtcatgactgaggtctcctcttaatgtggcctgtcaaacgccttatattagtc
aatctattgtctcattccgtcgtgccggggaacgattgcatgaagtcttttcccccgtta
cgttcactgcgaatcatatgttgattaaacctttcgcccatctcacactgtccgg-----
--------------------------agagagctgtgttataggacgtttaccgg-----
--------------ccatagagctcaccctcaacatacactctgtcctaaaagcatggat
--------------------
>SEQ9
gagaaatttgggcgagtatactggaagctttgcgagtaagtgttagccagagtacgtatg
ataattggctatctccgagtcgttttagctatgcatctag--------------agtcgt
gccgacacgtgtttgttataacgtgctcgcttggcctggcctccaggattcgg-------
--------------------atagttagccacatgaaagatagcgatggcatctcgcagc
actcttcgtcgaaggggcaaagattgttgtagctgaccgcaaactctcaccaatgtttta
gcaaactcatttaagacaatattga--------------------tcgaggcttccaact
tatctagtcaaaacacctgtcgttaccaaaaccttgcggcagtaccttttcaagccttaa
gatcgcctgcaatcggacttgcggcgatgtaaatgttgtctaatctgttag---------
---------------gttcggcgttgaaatcttatatcaggctaccatcctgtagatttt
ctgtccgtcggcattatccaggccgcgtactctactcgttc-----agacgaagaaggag
caagccgtgtgtcgctaagcgcacctcgagacggttcttcctctcagcagagttattcta
tgccgtaaggtcccc---------------------------------------------
---agcgaaaatgcctcccaactgattgctaaaattaaacccccccacggaacgcgtcta
acagagagccatccctgcggtctcctcttaatgtggcctgtcaaacgccttatatgagtc
aatctattgtctcattccgttgtgccggggaacgattgcatgaagccttatcccccctta
cgtccacgacgcaccattcttttaataaatattactcccactgcatc-------------
-----------------------------------tcatacaggtccttttcccactaca
caggcgaatgcccacgagcatccacgcggcttt---------------------------
--------------------
>SEQ10
gagatatttgggcggg----------------cgagtaagtgtcaacaaga---------
-----------------agtcggtttgccta-------------------------tcgg
ggcgagacttgtttctaatagcgtgctctctttgcctgggctccaggattctc-------
----------------gtttatagttagccacatgaaagatagcgatggcatcccgcagc
actcttcgtcgaaggggcaaagattgttgtagctgaccgcaaactctcagcaatgtctta
gcaaactc---------------------------ggtgtagc-----------------
-------tcgaagcacctaaccttatcgtaac----------------------ccttaa
tct--------------------gccgtgtcattgttgtctactcgatttctgcgcccgg
actttagccaagaagtttcggcgttgaaatcttatatcaggctaccatcctgtagatttt
ctgtccgtcggcattatccaggccgcgtactctactcgttc-----agacgaagaaggag
aaagggccctgtcgatagtcgagactgatagccttaattgt-------------------
--------------------------------aaggccggatcaacgcagcctgg-----
---------------------------------atcaaaaccaccccctgaacgcagcga
acagaaagtcatgacggatgtctccttttaatgtggcctgtcaaacgccttatatttgtc
aatctattgtctcattccgttgtgccggggaacgattgcatgaagccttatcccccgtta
cgtccacgacgcaccattcttttaattaaaattacttccactgtatctcatactg-----
------------------------------------------------------------
----------ctcacgagcatccacgcggactt---------------------------
--------------------
>SEQ11
--------------------------------------ggttttagccgccgtacgta-g
ctgtttagctat------------------------------------------------
-ccatcgagtgttcgttttaacgtgcacactttgcctgacctccaggattctatctaggt
gggaggattcggggatgatcatagttagccacatgaaagatagcgatggcatcccgcagc
actcttcgtcgaaggggctaagattgttgtagctgaccgcaaactctcagcaatgtcttt
gctaactcccttatgacactattgtcatgcagggtggtctatctttcgaagcttccaact
tatctagtcaaaacacctgtccttatc----------------------ttaattcttaa
gatcgcgtgcaatcggtcatgctacgctgtaaacgttgtctaatccgttagtgcgc----
--------------------gcgttgaaatcttatatcaggataccatactgtagatttt
ctgtccgtcggcattatccaggccgcgtactctactcgttccaggaagacgaagaaggag
acatgtgtgtgtcaatagtcgaacctcgagtattttactgctctcactcgggtagttggt
cgcagttagtaacag---------------------------------------------
----------------------------------------tcattcacc-----------
-cgtaaagtcatgaatgaggtctccttttaatgtggcctgtcaaacgccttatatttgtc
aatctatagtctcattccgttgtgccgtggaacgattgcatgaagccttatcccccgtta
cgtccacgacacaccatacttttaataaacataacgcccagagcattatatcaga-----
------------------------------------------------tcaccccgtaca
ctggcgaatgtcccccagggtggttaacctca----------------------------
-----caacaattcatctct
>SEQ12
---------------------------gagagcgagtaagtgttagccagagtacgtatg
ataatgggctatcaccgagtcgttttagctctgcatctag--------------agtcgt
gccggcacgtgtttgttataacgcgctcgcttggcctgg---------------------
--------------------atagttagccacatgaaagatagcgatggcatcccgcagc
actcttcgtcgaaggggctaagattgttgtagctgaccgcaaactctcagcaatctcttt
gtaaactgttgta-----------------------------------------------
-----gctcaaaacacctatctttatcataacc---------------------------
------------------------cggtgtaaatgttgtctaatctattactgcgccctt
cgattagccaagaccgttcgacgttgaaatcttatatcaggagaccatcctgtagatttt
ctgtccgtcggcattatccaggccgcgtactctactcgttccagtacgacgaagaaggag
aaaggtgtgtatcaatagtcgaacctcgagtgttttattgctctcacttggggatttggt
cgtagttagtaacag---------------------------------------------
-------------------------------tcattccccccacccaccgaacggggcga
actgaaagtcatgaatgaggtctcctcttaatgtggcctgtcaaacgccttatattagtc
aatctattgtctcattacgttgtgccggggaacgattgcatgaagccttatcccccgtta
cttccacgacgcaccattcttttaataaacattacgcccagtgcatcatatcaga-----
-----------------------------------tcatataggacattaaccccgtaca
caggcgaatggccaccagagtgccggtcctca----------------------------
-----caacttttcggtttt
>SEQ13
gacaaatttgggcgggtctactggaaactttgcaagtaagtgttagccagagtacttatg
gtaattgggtttctccgagtcgttttggttatgcatctag--------------agtcgt
tccgacactc--------------------------------------------------
--------------------atagttagccacatgaaagatagcgatggcatcccgcagc
actcttcgtcgaaggggcaaagattgttgtagctgaccgcaaactctcagcaatgtctta
acaaactcattaaagacaatattga--------------------tcgaggcttgcggc-
------------------------------------------------------------
-atcgcctgtgacgggactcgggct-----------------------------------
---------------gttaggcgttgaaatcttatatcaggagaccatcctgtagatttt
ctgtccgtcggcattatccaggccgcgtacgctactcgttccagtaagacgaagaagga-
---------------------------gaaacgaccccgtcgatcgtcgagactgattaa
ccggataaag--------------------------------------------------
-----------------------gcatgctggatcaaaaccac-------------tcga
acagaaagtcctgacggatgtctccttttaatgtggcctgtcaaacgccttatatttgtc
aatctatagtctcattccgttgtgccgtggaacgattgcctgaagccttatcccccgtta
cggctacggcgcaccattcttctaataaatattactcccactgcatc-------------
-----------------------------------t------------------------
----------------accatccacgcggtatt---------------------------
--------------------
>SEQ14
gagaaatttgggcgagtttgctggaagttttgcgagtaagtgttaaccagagtacgcatg
agaattggctacctcccagtcactttacctatgcatctagtattggctccgtcaagtcga
gccgacacgtgtttg-------------------cctggcctccaggattctcactagtt
gtgagaagtcggggatgtttatagttagccacatgaaagatagcgatggcatcccgcagc
actcttcgtcgaaggggctaagattgttgtagctgaccgcaaactctcagcaatctcttt
ccagacacttttatgacagtgtggtattacagcgtaa----------------------t
tatctagtcacaatgc--------------------------------------------
-------------ggcacctaaggcgatgtatttgttctctactcggttagtgcacattt
tgcctcgcc-----------gcgttgaaatcttatatcaggagaccatcctgtagatttt
ctgtccgtcggcattatccaggccgcgtactctactcgttccagtaagacgaagaaggag
aaagctgtgtgtcgataagcacacctcgatacgttttgtgttctcatttcgagagttcac
tgcagtaagtaaaagagttattatgtgccctaaggtccggagaggcactgac--------
----------------ctcatctgattgataaaagtaaacccacccaaagaacgggctga
acaga--------------gtctcctcttaatgtggcctgtcaaacgccttatattagtc
aatctattgtctcattccgttgtgccggggaacgattgcatgaagccttttcccccgtta
cgtccactgcggaccattcttttattaaacatgtcg-cgaaaggaccatatggat-----
-----------------------------------------------ttagagctgtacg
-----------------------tcgccctcaccacacacgctgttataaaagcctggat
--------------------
>SEQ15
gacaattttggcctagtagactggaagcttt-----------------agagtacgtatg
acaattgcgtatctctgcgtcgtttgagctatgcatctag--------------agtcgt
gccgagacgtggtttttataacctgctcgattggcctggcctcgagaattagt-------
--------------------atagttagccacatgaaagatagcgatggcatcccgcagc
actcttcgtcgaaggggctaagattgttgtagctgaccgcaaactctcagcaatctcttt
gcaaactc---------------------------ggtctagc-----------------
-------tcaatacacctaccctt------------------------------ccttaa
gctcgcgtgcaaacggactttcggaggtgtaaatgttgtttaatcgaatactgcgccctt
--------------------gcgttgaaatcttatatcaggagaccaacctgtagatttt
ctgtccgtcggcattatccaggccgcgtactctactcgttccagtaagacgtagaaggag
aaacgaccccgtcgaacggcgagactgactg-----------------------------
------------------------------------------------------------
---------------------------------ataaaggcatgctggaaaaccactcga
acaga---------------tctcctcttaatgtggcctgtcaaacgccttatattagtc
aatctagtgtctcattacgttgtgccggggaacgattgcatgaagccttatcccccgtta
cgtccacgacgcaccagtctcttaataaacattacggccattgcataatattagg-----
-----------------------------------tcatgcaagactat-----------
------------------------------------------------------------
--------------------
>SEQ16
----------------gacactggaaactttgcaagtaagtgttagccagagtacttatg
gtcaatgggtttgtccgagtcggtctggttatgcatctag--------------ggtcgt
ttcgacac----------------------------------------------------
-------------------catagttagccacatgaaagatagcgatggcatcccgcagc
tctcttcgtcgaaggggcaaagattgttgtagctgaccgccaactctcagcaatgtctta
gcaaactactttaagacactattgaaatgcagggtggtgtatctttccatgcttcaaact
tatctagtcaaagcacctgtccttatcataaccttgcggcagtatctactcaatccttaa
gaacgcttgcaataggacttgcggcgaagtaaacgttgtctaatctgttaatgcgccatt
agactcgccaataccgttcggcgttgaaatcttatatcaggagaccatcctgtagatttt
ctgtccgtcggcattatccaggccgcgtactctactcgttccagtaagacgaagaaggag
aaagggccctggccggatctacgcagcgtgg-----------------------------
------------------------------------------------------------
---------------------------------atcaaagccac----------------
-----aagtcatgacggatgtctcctcttaatgtggcctgtcaaacgccttatattagtc
aatctattgtctcattccgttgtgccggggaacgattgcatgaagccttttcccccgtta
ggtccacggcgcaccattcctgtaataaacgttactaccagtggataataccaga-----
--------------------------------------tacaggacatttttcccctact
caggcgaaagcgtcctcacatccactcgtcttt---------------------------
--------------------
>SEQ17
gaaaaatttgggcgagtatagtggaagctatgcgagtaagtgttagccagattacgtatg
ttaattgtctaactccgagtcgttttgactatgcatcaag--------------agtcgg
gccgagacgtgtttgttataacgtgctcgcttggcctgacctccaggattc---------
--------------------atagttagccacatgaaagatagcgatggcatcccgcagc
actcttcgtcgaaggggctaagattgttgtagctgaccgcaaactctcagcaatgtcttt
acaaactgctttaggagagtattgtaatgcagtgtggtggagctgga-------------
-atctagtctaaacacctgtcattatcatatcattgcggcagtaccttttcaatccttaa
gctcgcgtgcaatctgactttcagcgatgtaaatctcgtctaaccggttagtgcgccctt
aaactcgccaggaccggtcggcgttgaaatcttataacaggagaccatcctgtagatttt
ctgtccgtcggcattatccaggccgcgtactctactcgttccagtaagacgaagaaggag
aaaggtgtgtgtcgattgtcgaacctagggtcctttattgctctcactcggagagttgcc
cgcagttaataacag---------------------------------tgcctgg-----
---------------------------------attaaacccacccactgaacgcggcga
acagaacgtcatcactgaggtctcctcttaatgtggcctgtcaaacgccttatattagtc
aatctattgtctcattccgttgtgccggggaacgattgcatgaagccttttcccccgtta
cgtccacga------------------------acgaccattgcataatattagg-----
-----------------------------------tcgtgcaagacttt-----------
------------------------------------------------------------
--------------------
>SEQ18
------------gaggtttgcaggaacttgcgcgactaagtgtaatccaga---------
----------------------------ctatgcctctaggattgccttcctccagtcgc
gccgacacgtgtcggttacaacgtgcctt------------------attcccacaaggt
gtgtgaactcggggacgtgtatagttagccacatgaaagatagcgatggcatcccgcagc
actcttcgtcgaaggggcaaagattgttgtagctgaccgcaaactctcagcaatgtctta
gtaaacc----------------------------gatgtagc-----------------
-------tcaaaacaccta-----------------------------------------
------------------------cggcgtaaatgt------------------------
--attagccaagaccgttcggcgttgaaatcttttatcaggagaccatcctgtagatttt
ctgtccgtcggcattatccaggccgcgtactctactcgttccaggaagacgaagaaggag
aaagggccctggagatagttgagcctggtggccttaattgt-------------------
--------------------------------aaggcctaatcgacgcagcctgg-----
------------------------------------aaaaccacccactgaacgcggcca
acagtaagtcatgactggggtctcctcttaatgtggcctgtcaaacgccttatattagtc
aatctattgtctcattccgttgtgccggggaacgattgcatgaagccttatcccccgtta
cgtcca----------------aattaaaaatttcgcccatcgcacactgtccga-----
-------------------------------------aaggaccatatggatttaggata
cagatgtgcgccccccatagagctcgccctcaccacacacgctgtcataacagcctgga-
--------------------
>SEQ19
gagaaaattgggcgagtttgctg-----------------------ccagagcacgtatg
atgagtggctatctcccagtcgctttagcaatgcatcgag--------------tgtagt
gcccacacgtgtttgttatcacgtgctcgcttggcctggcctacaggatactcactaggt
gggaggattaggggatgttcatagttagccacatgaaagatagcgatggcatcccgcagc
actcttcgtcgaaggggcacaggttgttgtagctgaccgcaaactctcagcaatgtctta
gctaactgctttatgacagaatggtaatgcagtgcggtgtagctttcgacgcctcaacct
tatctagtcaa---------------------attgcggcagtaccttttgaatccttaa
----------------------ggcgatgtattcgttgtctattcggttagtgcgcccgt
agactcgcc-----------gcgttgaaatcttatatcaggataccatcctgtagatttt
ctgtccgtcggcattatccaggccgcgtactctactcgttccaggaagacgaagaaggag
aaaggtgtctgtcgatagtcgaccctagtggccttaattgctctcactcggagagttgcc
cgcggttagtaa------------------------------------------------
------------------------------------------------------------
----------------gagtcctcctcttaatgtggcctgtcaaacgccttatattagtc
aatctattgtctcattccgttgtgccggggaacgattgcatgaagccttatcccccgtta
cgtccacgacgcaccattcttataagtaaaattacttccactgtat--------------
------------------------------------------------------------
----------------------------ctca----------------------------
--taccatccacgcggactt
