>SEQ0
tgtcgcgcgcaactcgacagtaccgactttgccgtcctccatttacaatggtgatgctct
cgtctaggaaaacaggagtaattcatggtttcaggtcagcgtagcgctatgatccatccg
ggctgggtgtacatcgtccgcaaggaatgtccgtctcatcctcagattttagcaaaatct
aatctgagaacaaggggttatctcgagcccattaaacgaaataccatgcgtcggtgtcct
cggttttccgtagggcttccgattgatacgtaaaatatacttttaagcacgcccgcctac
attgccagactcaataaaagagtaggtaatctacgaggcggccatggtagagcgaagttg
gcggtagcggatcccctgaaatcgtctcaattattaggccgagagtaggccgcaatcata
aatctaacagggccttggccgggacgatcgcttagccccgcactacctgtctctggcaat
atcgactcgatttacccgctgcgaaaaccggttgtatggtatgagcctcgtcgttaagct
agtaagaagtaccttacgcccaatatatgggacggtaattagcagggttcgaacttccct
tacgaatcattaaaggggtcggagcgtgtcagggtggggctaggagctcgtgaggctaga
ttcatttcgagagatagtatgtaacgactcatcgaggtagacaagtaggtactaacaatt
cttgcttatcgaatctattaatggtacttccgctgtcggataacacaaccgacgcgtacc
tcaacccatgcaagtctcgcgcacgccccgcatgatttatgccataccaacgcttgtttg
cacaccgcaaggaaggttagctcgagccccaacaaggcaaatggcgctcatcgccagacc
gcaaacgggtagccttcataatgacatgagcgggaaaactttcatgcctagctaacaata
gatccaccgataatggttgcacaccctggcctttagggatagcggaggaacggcggagct
cttcgggctcagcttacagagtgacgttatttactcgacggttcatctcgtatcgcggat
tagggtggtcgtcagagtag
>SEQ1
ggtcgggcgcacctcgaaagtaccgactttgcagtcctccatttacaatggggatgctct
cgtctaggaaaacacgtgtcattcttggtttcag-------------------ccagccg
ggctggatgtacatggtccgaaaggaaagtccgtctaatcctcagattttagcaaaatgt
aatctgagaacaaggagttatctcgagcccattaaacgaaataccatgcttcggtgtcct
cggttttccgtagggcttccgattgatacgtaaaatatacttttaagcacgcccgcctac
attgctagacttgacaaaa-------------------cagccatcgtagaacgaagttg
gctgtagcggatcctctgaaatcgtctcaactattaggacgagagtaggccgcaatcata
aatctaacagggccttggactggacgatcgcttagcctaggactacctgtttctggcaat
at----------------ctgcgaaaaccggttgtatggtatgagcctcgtcgttaagct
agtaagaagtaccttacgcccaatatatgggacggtaattagcagggttcgaacttccct
tacgaattattaaaggcgtcggagcgtgtcagggttgggctaggagctcgtgaggctaga
ttcaattcgagagatagtatgtaacgactcatcgaggcagactaataggtactaacaatt
ctagcttaccgaacctattaatggtacttcagctgtcggataacacaacctacgcgtacc
tcaacccatgcaagtcgcgcgcacgccccgcatgatttatgccataccaacgcttgtttg
cacaccgcaaggaaggttagctcgagccccaacaaggcaaatggcgctcatcgccagacc
gcaaacgggtagccttcataacgagatgagcgggaaaacgttcatgcctagtgaacaata
gatccaccgataatggttgcacaccctggcctttagtgatagcggaggaacggcggagct
gttagggctcacattcccgagtgccgtta---------------------tatagcggat
aggggtggtcgtcagagtag
>SEQ2
cgtcgggcgcacctcaaaagtaccaactttgcagtcctccttttacaatgggcatgctct
cgtcttggaaaacacgtgccatacttggtctca-------------------cccagccg
ggctggatgtacatggtccgacagggaagtccttctaatcctcagacgtta---------
-------------ggagttttctcgagcccattaaacgaaataccatgcgtcggtgtcct
cggttttccgtagggcttccgattgatacgtaaaatatacttttaagcacgcccgcctac
attgccagactcaataacaaagtaggtattcta-----------------cggggcgt--
---gtagcgcatgccctgacaacgcctcaagtattaggccgagactaggccgcaatcata
aatctaacagg---------------------tagccccgcactacctctatctggcaat
atcgactcgatctacccgctgcgaaaaccggttgtatggtatgaccctcgtcgttaagct
agtaagaagtaccttacgcccaatataagggacggtaattagcagggttcgaacttccct
tacgaatcattcaaggggccggatcgtgtcaaagtggggctaggggctcgtgaggctaga
ttcatttcgggagatagtatgttatgactgatcgcggtagacaagtaggtactaacaatt
cttgcttttggaatctattaatggtacctccgctgtcggagaa----------------t
ataaccgacgc------ctagcacgccccgcatgatttatgccataccaacgcttgtttg
cacaccgcaaggaaggttagctcgagccccaacaaggcaaatggcgctcatcgccagacc
ggaaacgggctagt--------------------------------------gaacaata
gagccgcttacaatggatgcacaccctggcctttagtgatagcggaggatcggcggggct
gttagcgctcacattcccgagtgccgtta---------------------tttagcggat
agggttggtcgtcagagtag
>SEQ3
------------------cgtcctaactttgaagtcctccttttacaatgggcctgctct
cgtcttggaaaacacgtgcccttcttggt-----------------------cccagccg
ggctggatgtacatgttccgacagggaagcccttctaatcctcagacgtta---------
-------------ggagttttctcgagcccattaaacgaaataacatgcgtcggtgtcct
cggttttccgtagggcttccgattgatacgtaaaatatacttttaagtacgcccgcctac
atgaccagactctataaaagggtagataatcta-----------------ggaggcgccc
atggtagagcgtccccagaaaccgtctcaattattaggccgagagttgtccgctagcata
aatctatca-----------------------tggcc---------------ttggccgg
ggcgattcgatttacccgctgcgaaaaccgggtgtatggtatgagcctcgtcgttaagct
agtaagaagtaccttacgcccaatatatgggacggtaattagcagggttcgaacttccct
gacgaattattaaaggcgtccca----------------------actcgtgagaccagg
ttcaattcgagagatagtatgcaacgactcatcgaggcagactaataggtactaataatt
ctagcctagggaacccattaatggtaattcagctgtcgga--------------------
tcagcccatgcaagtcgcgtgcacgccccgcatgatttatgccataccaacgcttgtttg
caccccgcaaggaaggttagctcgagccccaacaaggcaaatggcgctcatcgccagacc
ggaaacgggcta------------------------------------------------
---ctgcacacaatggatgcacaccatggcctttagtgttagcggaggatcgccggggct
gttagcgcccaccttcccgagtgccgtta---------------------tttagcggct
agagttggtcgtcagactag
>SEQ4
---------------------agtcgctcttccctcctccatttacaatggtgatgctct
cgtct-------------------------tcaggtcaccgtagcgctatgagcgattcg
agcggggtgtacatcatgcgcaaggcatgtccgtctcaacctcagattttagcaaaatct
aatctgagaacaacgggttatctcgagcccattaaacgaaataccatgcgtcggtgtcct
cggttttccgtagggcttccgattgatacgtaaaatatacttttaagcacgcccgcctac
attgctagacttgacaaaa-------------------cagccatcgttgaacgaagttg
gctgtaccgtttcctctgaattcgtctcaactattacgacgagagcaggccgcattcata
a------------------ctacacgatcgcatagcctaggactacctgtttctagcaat
at----------------ctgcgaaaaccgggtgtatggtatgagcctcgtcgttaagct
agtaagaagtaccttacgcccaatatatgggacggtaattagcagggttcgaacttccct
tacgaattattaaaggtgtcagaacgtgtcagggttg-----------------------
-tcacatcgaa------------------tatcgagccagactaagaggtgctaacaatt
cttgc----------------tggtacttccgctgtcggataa----------------c
acaaccctcgcgaa-----cgcacgccccgcatgatttatgccataccaacgcttgtttg
cacaccgcaaggaaggttagctcgagccccaacaaggcaaatggcgctcatcgccagacc
ggaaacgggctagc----------------------------------------------
----cgcttacaatggatgcacatcgtggcccttagtgatagcggaggatcggcggggct
gttaacgctcacagtcccgagtgccctca---------------------tttagcggat
agggttcgtcgtcagagaag
>SEQ5
tgtcgcgcgccagtcgacagaaccgacttagccgtcctccatttacaatggtgatgctca
cttctaggaaaactggagtaattcatggtttcaggtcagcgtagcgctatgatc------
----------------tccgcaaggaatgtccgtatcatcctcagattttagcaaaatct
aatgtgagaacaaggggt--tctcgagcccattaaacgaaataccatgcgtcgctgtcct
cggttttccgtagggcttccgattgatacgtaaaatatacttttaagcacgcccgcctac
atggctagtcttgacaaaa----------------------------caaaacgaagttg
gctgtaccgtttcctctaaattcg---------------------caggccgc-------
-----tacgggacct---------------------------------------------
------------------ctgcgaaaaccggttgtatggtatgagcctcgtcgttaagct
agtaagaagtaccttacgcccaatatatgggacggtaattagcagggttcgaacttccct
tacgaatcattaaaggggtcggagcgtgtcagggtggggctaggagcacgtgaggctaga
ttcatatcgagtgataatatgtaacgacgcatcgagctacacaagaaggtactaacaatt
cttgcttatctaatctattaatggcacttccgctg------------------------c
ttaacccatgctagtctcgcgcacgccccgcatgatttatgccataccaacgcttgtttg
cacaccgcaaggaaggttagctcgagccccaacaaggcaaatggcgctcatcgccagacc
ggaaa-------------------------------------------------------
---ccgcttacaatggatccacatcgtggcccttagtcatagcggggtatcggcggggct
gttaacgctcatagtcccgactgccctca---------------------tttcaccgat
agggttcctcgtcagagaag
>SEQ6
tgtggcgcgccagtcgacagaaccgacatagccgtcctccatttacgatgggggttctca
cttctaagaaaactggagtaattcatggttgcaggccagcgtagcgctatgatc------
----------------tcagcaaggaatggccgtagcatcctctgattttaaccaaatct
actttgagaacatggcgt--tctcgagcccattaaacgaaataccatgcgtcggtgtcct
cggttttccgtagggcttccgattgatacgtaaaatatacttttaagcacgcccgcctac
atcgttagacttgccaaaa-------------------------------cacgaagttg
gctgtagcggattctctgcaatcgtctcaactattaggacgaaagtacgccgcaatcata
aatctaacagggccttgaactggacgatcgcttagcctagcactacgtgtttctggcaat
cc----------------ctgcgaaaaccggtcgtatggtatgagcctcgtcgttaagct
agtaagaagtaccttacgcccaatatatgggacggtaattagcagggttcgaacttccct
tacgagtcatcaaaggggttggagcgtgtcagggtggggctaggagcccgtgaggctaga
ttcatatcgagtgataatatgtaacgacgcatcgacattcacaagaaggtactaacaatt
cttggttatctagtctattaatggcacctccgctg------------------------c
ttaacccatgctagtctcgcgcacgccccgcatgatttatgccataccaacgcttgtttg
cacaccgcaagggaggttagctcgagccccaacaaggcaaatggcgctcatcgccagacc
ggaaacggggtacc----------------------------------------------
----------------------------gcacttagtgttagcggatgatcgcaggggtt
gttagcacccaacttcccgagtgccgt-----------------------tacggcagac
gag-----------------
>SEQ7
--------------------------cgtcgaattcctcattttacgattggcctgctct
cgttttggaaaacagg-------------------------------------ccagccg
ggctggatgtataagttcc-----------------------------------------
-----gaccgttaggagttttctcgagcccattaaacgaaataccatgcgtcggtgtcct
cggttttccgtagggcttccgattgatacgtaaaatatacttttaagcacgcccgcctac
atggctagtcattacaaag-----------------------------------cagttg
tctgtaccgtttcctctaaattcacaggccgctacgggacc-------------------
------------------------------------------------------------
------------------tcgcgaaaaccggttgtatggtatgagcctcgtcgttaagct
ggtaagaagtaccttacgcccaatatatgggacggtaattagcagggttcgaacttccct
tatgagtcatccaaggggttcgagcgtgtcaggctagggctagaagtccgtgaggctaga
tacatatggagtgataatatgtaacgacgcatggacattcacaagaatgtactcacaatt
cttggttatcgagtctattaatggcacctccgctg------------------------c
ttaatccatgcttgtctcgcgcacgccccgcatgatttatgccataccaacgcttgtttg
cacaccgcaaggaaggttagctcgagccccaacaaggcaaatggcgctcatcgccagacc
gctaacgggtcgcctacatcatgacat-------------------------------ga
tctccaccggcaatggctgcacaccctggccttaagggatagcggaggaacggcggagct
cttcgggctcagcttacagagtgac-------------------------gttacttact
cgaggtggtcgtcagaatag
>SEQ8
tgtcgggcgcaattcgacactaccggctttgccgtcctccatttacaatggtgatgctct
cgtctaggaaaacaggagtaatgcatggtttcaggtcagcaaagcgctatgatccatccg
ggctgggtgtacatcgtcctcgaggaatg-------------------------aagact
aatctgagaacaaggggatatctcgagcccattaaacgaaataccatgcgttgctgtcct
cggttttccgtagggcttccgattgatacgtaaaatatactttcaagcacgcccgcctac
ttcgttagacttgccaaaa-------------------------------cacgaagttg
gctgtagcggattctctgcaatggtctcaactattaggacgaaaatacgccgcaatcata
aatctaacagggccttgaactgaacgatcgcttggcttagcactaagtgtttgtggcaat
cc----------------ctgcgaaaaccgggtgtatggtatgagcctcgtcgttaagct
agtaagcagtaccttacgcccaatatatgggacgataattagcagggttcgaacttccct
taagagtcatccagggggttcgagcgtgtcaggctagggctc------------------
----------gtgataatatgtaaccacgcatgcacattcccaagaatgtactcacaatt
cttggttatcgagtctattcatggcacctccgctg------------------------c
ttaagccatgcttgtctagcgcacgccccgcatgatttatgccataccaaagcttgtttg
cacaccgcaaggaaggttagctcgagccccaacaaggcaaatggcgctcatcgccagacc
gctaacgggtcgcgtacatcatgacct---------------------------------
---------------gatctccacactggccttaagggataacggaggaacgacggagct
cctcgcgcgttac-----------------------------------------------
--------------------
>SEQ9
------------------------------------------------------------
-----------------------------cgcaggccagc------------tccagccg
ggctggatgtacaagttcc-----------------------------------------
-----gaccgttaggagttttctcgagcccattaaacgaaataccatgcgtcggtgtcct
cggttttccgtagggcttccgattgatacgtaaaatatacttttaagcactcccgcctac
attggtagacttgacaaac-------------------cagacatcggtcgacgaagttg
gctgtagcgtttcctttgaattcgtctcaactattaggacgagagcaggccggattcata
tctacac------------------------------------------tttctagcaat
at----------------ctgcgaaaaccgggtggatggtatgagcctcgtcgttaagct
agtaagcagtaccttacgcccaatatatgggacgataattagcagggttcgaacttccct
tacgaatcattcaaggggccggatcgtgtaaa----------------------------
---------aaggctagattgttaggactgttggcggtagacaagtaggaactaacaatt
cttgcttttggaatctcttaatggaatat-------------------------------
--------taccgacgtcaagcacgccccgcatgatttatgccataccaacgcttgtttg
cacaccgcaaggaaggttagctcgagccccaacaaggcaaatggcgctcatcggcagacc
cgaaactggccact----------------------------------------------
--------tacaatgaatccacatcgtggcccttcgtgatagctgaggatcggcggggct
gttaccgctcacagtcccgagttccctca---------------------tctagcggat
cggtttcgtcgta-------
>SEQ10
----------------taagtacggactttgccgtcctccatttacaatgatgatgcccc
cgtttaggaaaaccggagtaatgcatggtttcaggtcagcgtagcgctatcatccatccg
ggctgggtgtacttc-------------gtccgtctcatcctcagattttagcaaactct
aatctgagaacaaggagttatctcgagcccattaaacgaaataccatgcgttgctgtcct
cggttttccgtagggcttccgattgatacgtaaaatatactttcaagcacgcccgcctac
ttcgttagtttagccaaaa-------------------------------cacaaagttg
tctgtagcgggttctctgcaatggtcgcaacttttaggaagaaaatacgccgcaatgata
aatctaacaggaccttgaactgaccgatcgcttggcttagcattaagtgttt--------
------------------gtgcgaaaaccggttgtatggtatgagcctcgtcgttaagct
agtaagaagtaccttacgcccaatatatgggacggtaattagcagggttcgaacttccct
tacgaatcattaaagggttcggagcgtgtcagggtggggctaggaggtcgtgagcctaga
ttcatttcgagagataatatgtaatgactcaacaaggtaggcaagtatggactaacaatt
ctt--------------------gtacttccg---------------------------c
tcaacccatgcaagtctcgcgcacgccccgcatgatttatgccataccaacgcttgtttg
cacaccgcaaggaaggttagctcgagccccaacaaggcaaatggcgctcatcgccagacc
acaaacggccagccttcataacgagatgagggggaaaac--------------------a
gatcgaccgatcatggttgcacaccctgg-------------------------------
gttagggctcacattc----------------------------------tatagcagat
aggggtggtcgttagagtag
>SEQ11
---------------------agtcgctcttccctcctcaatttatactggtgatgcact
agtct-------------------------tcaggtcaccgtagcgctatgagcgattcg
agctgagtgtacataatgcgtaatgcatgtccgtctcaacctcagattttggcaaaatct
aatcggagaacaacgggttatctcgagcccattaaacgaaataacatgcgtcggtgtcct
cggttttccgtagggcttccgattgatacgtaaaatatacttttaagtacgcccgcctac
attggtagacttgataaac-------------------cagacatcggtagactaagttg
actgtagcgtttcctttgaattcgtctcaactatcgattcctatctacac----------
-------------------------------------------------tttctagcaat
at-----------------cgcgaaaaccgggtggatggtatgagcctcgtcgttaagcg
agtaagcagtaccttacgcccaatatatgggacgat--ttagcagggttcgaacttccct
tacgaatcattaaagtgctcggagcgtgtcaggttggggctaggagctcgtgcgggtaaa
ttcctttcatgcaatagtatctaacgactcatcca-------------------------
---------cgaatctattaatggtacttcccctgtcggataacacaaccgacgcgtacc
acaatccatgcaaggctcgcgcacgccccgcatgatttatgccataccaacgcttgtttg
cacaccgcaaggaaggttagctcgagccccaacaaggcaaatggagctcatcgccagacc
gctaacgcgtcttc----------------------------------------------
-----accggcaatggttgcacaccctggccttaaggcatagtggacgaacgccggagct
cttcgggc--------------------------------------------tacttact
cgaggtggtcgtcagaatag
>SEQ12
cgcagg----------------ccagct--------------------------------
-----------------------------------------------------ccagccg
ggctggatgtgtaagtaccgagcgttag--------------------------------
--------------gagttttctcgagcccattaaacgaaataacatgcgtcggtgtcct
cggttttccgtagggcttccgattgatacgtaaaatatacttttaagcacgcccgcctac
atggctagtcttggcaaaa----------------------------caagacgaagttg
gctgtaccgtttcctgtaaattcgcacgccgctacgggacct------------------
------------------------------------------------------------
------------------cagcgaaaaccggttgtatggtatgagcctcgtcgttaagct
agtaagaagtaccttacgcccaatatatgggacggtaattagcagggttcgaaattccct
tgcgaactattaaaggcgttggagcgtgtcagggttgggctagtagcgcgtgagg-----
---ctatg--------------------------aggcggacgaataggtactaacaatt
ctagattaccgaacctattaatggtacttcagctgtcggataacacaaagtacgcgtacc
tcaacccatgcaagtcgcgcgcacgccccgcatgatttatgccataccaacgcttgtttg
cacaccgcaaggaaggttagctcgagccccaacaaggcaaatggagctcatcgccagacc
caaaactgagtact----------------------------------------------
-----------------cccacatcgtggcccttcgtgatagctgaggatcggcggggct
gtttccgatcacagtcccgagt----------------------------tctagaggat
cggtttcgtagta-------
>SEQ13
tgtctggcgcaattcgacactaccggtt------------------agtgctgatgctct
cgtctaggaaaacaggggtaatgcatggtatcaggtcagcaaagcgctataatccatccg
ggctgggtgtacatcgtcctcgaggaatg-------------------------aagacg
aatctgagaacaagtggatatctcgagcccattaaacgaaataccatgcgtcggtgtcct
gggttttccgtagggctaccgattgatacgtaaaatatacttttaagcacgcccgcctac
attgctagactt----------------------------gccatcgttgcacgaagtcg
gctgtacagtttcctctgaattcgtctcaactatcccgacgagagcagaccgcattcata
a------------------ctacacgagcgcataccctaggcctagctatttctatcaat
at----------------ctgcgaaaaccgggtgtatggtatgagcctcgtcgttaagct
agtaagaagtaccttacgcccaatatatgggacggtaattagcagggttcgaacttccct
tacgaatctttaaagggttcggagcgtattagggtcgggctagcaggtcgtgagcctaga
ttcatttcgagagataatatgtaatgactcaacatggaaggcaagtatggattaacaatc
ct----------------------------------------------------------
--------tgcaagtcgcgcgcacgcccggcatgatttatgccatacctacgcttgtttg
caccccgcaaggaaggttagctcgagccccaacaaggcaaatggcgctcatcgccagacc
gggaacggggtacc----------------------------------------------
----------------------------gcacttcgtgttagcgggtgatcgcagggctt
gt--------------------------------------------------cggcagac
ggg-----------------
>SEQ14
tgtggctcgcgagtcgacagaacagacatagacgtcgtccctttacgatgggggatctca
cttcgaaaaaaactagactaattcatggttgcaggccaacgcagcgctatgatc------
----------------tcagcaaggaatggccgtagcatcctctgattttaacaaaattt
actttgagaacatggcgt--tctcgagcccattaaacgaaataccatgcgttgctgtcct
cggttttccgtagggcttccaattgatacgtaaaatatactttcaagcacgcccgcttac
atcgttagactagccaaaa-----------------------------------------
--catagcggattctgt----------------------------------gcaatcata
aatctaagagggccttgcactggacgattgcttagcgtaacactacgtgtttctggcaat
cc----------------ctgcgaaaaccggttgtatggtatgagcctcgtcgttaagct
agtaagaagtaccttacgcccaatatatgggacggtaattagcagggttcgaacttccct
tacgtattattaaaggcgtcggagcgtcccagggttgggctaggagctcgtgcggctaga
ttcaattcgagagatcgtatgtaaagactcatcgaggcagactaatcgggagtaacaatt
ctaacttacccaacctattaatggtatttcagcagtcggatcacacaacctacgcctacc
tcaacttatgcaagtcgcgcgcacgccccgcatgatttatgccataccaacgcttgtttg
cacaccgcaaggaaggttagctcgagccccaacaaggcaaatggcgctcatcgccagacc
gtaaacggggtacc----------------------------------------------
----------------------------gcgctttgtgttagcggatgatcgcaggggtt
tttaccaaccaacgtcccaagttccgt-----------------------tacggcagac
--------------------
>SEQ15
tgtctcgcgccagtcgacagaaccgactaaaccgtcctccatttacaatggtgatgctcg
cttctaggaaaactggagtaattcatggtcgc----------------------------
---------tatgatctcagcaaagaa------------------------gcaaaatct
aatgtgtgaaaaagtggt--tctcgagcccattaaacgaaataccatgcgtcggtgtcct
cggttttccgtagggcttccggttgatacgtaaaatatacttttaagcacgcccgcctac
attgccagactcagtagca-----------------------------------------
---------------aagtgttgccctgaagtattaggccgaggctaggcctctatcata
aatctaagtga---------------------tagcccctcaccacctctatctggcgat
atcgactcgatctacccgctgcgaaaaccggttgtatggtatgagcctcgtcgttaagct
ggtaagaagtaccttacgcccaatctatgggacggtaattagcagggttcgaacttccct
cccgcatcattaaagtcctcagaacgtgtcaggttggggctaggaactcgtgcgggtaaa
ttcttttg----------------------------------------------------
-----ctgccgaatctattaatggaacattccctgtctgataacccaaccgacgcatacc
acaatccatgcaaggctcgcgcacgccccgcatgatttatgccataccaacgcttgtttg
cacaccgcaaggaaggttagctcgagccccaacaaggcaaatggagctcatcgccagacc
ggaaacgggctagc----------------------------------------------
----cgcttacaatggatgcacatagtggccctaag--------------------ggct
gttaacgcacacagtcccgagtggcgtca---------------------tttagctgac
agagttcgtcctcacagaag
>SEQ16
agtctggcgcaattcgacactaccgatt------------------agtgctgatgcatt
cgtctaggagaacaggggtaatgcatgatatca---------------------------
--------atccatcctcctcgaggaatg-------------------------aaggcg
aatctgagaacaagtggatatctcgagcccattaaacgaaataacatgcgtcggtgtcct
cggttttccgtagggcttccgattgatacgtaaaatatacttttaactacgcccgcctac
actggaagacttgacaaac-------------------cagtcatcggacgacgaaggtt
gctgtagcgtttcctttgcattcgtctcaaatattaggacgagagcaggccggcac----
-------------------------------------------------tttcttgcaat
at----------------ctgcgaaaaccgggtggatggtatgagcctcgtcgttaagcg
agtaagcagtaccttacgcccaatatatgggacgat--ttagcagggttcgaacttccct
tacgaattattaaaggtgccgcagcgtct-------------------cgtgaggctaga
tgcaattcgagagatagtatgtagcgactcatcgaggcatactaatcggaacttacaat-
----------------attaatggtacttcagatgtcggataagacaacctacacgtacc
tcaacccattcaagtcgcgcgcacgccccgcatgatttatgccataccaacgcttgtttg
cacaccgcaaggaaggttagctcgagccccaacaaggcaaatggcgctcatcgccagacc
gctaacgggtggcggacatcatgacct---------------------------------
---------------gatctccccactggccttgagggattacggaggaacgacggagct
cctcgcgcgttac-----------------------------------------------
--------------------
>SEQ17
agtctggcgcaattctacacaaccgatt------------------aggggtgatgcatt
cgtctaggagaacatgggtaatgcatgatataa---------------------------
----------------tcctcgaggaa---------------------------------
-----ggaaccatgtggatatctcgagcccattaaacgaaataccatgcgtcggtgtcct
gggttttccgtagggctaccgattgatacgtaaaatatacttttaagcacgcccgcctac
actggaagacttgacaaac-------------------cagtcatcggacgacgaaggat
gctgtagcgttgcatttggattcgtctcagatattaggacgagcgcaggccggaac----
-------------------------------------------------tttcttgcaaa
at----------------gtgcgaaaaccggtcgtatggtatgagcctcgtcgttaagct
agtaagaagtaccttacgcccaatatatgggacggtaattagcagggttcgaacttccct
tccgaatcagtaaagggttcggag-----------------aggaggtcgtgagcctaga
ttcatttcgagagataatatgtaatgactcaacaaggtaggcaagtatggactaacaatt
cttgtacgaacg-----------------------------------------------c
tcaacgcctgcaagtctcgcgcacgccccgcgtgatttatgccataccaacgcttgtttg
caccccgcaaggaaggttagctcgagccccaacaaggcaaatggcgctcatcgccagacc
gtaaacgggttacc----------------------------------------------
----------------------------gcgctttgtgttagcggttgatcgcgtcccaa
gttccgt-------------------------------------------tacggcagac
--------------------
>SEQ18
agtctg----------------------------------------aggggtgatgcatt
cgtctcggagaaaatgggtaatgcatgaattaa---------------------------
----------------tcctcgagaaagg-------------------------aaca--
-----------atgaggatatctcgagcccattaaacgaaataccatgcgttgctgtcct
cggttttccgtagggcttccgattgatacgtaaaatatactttcaagcacgcccgcctac
attggaagacttgataaac-------------------cagacttcggtagactaagttg
actgtagcgtatccttgattcctatct-------------------------acac----
-------------------------------------------------tttctaacaat
at----------------c-gcgaaaaccggtcgtatggtatgagcctcgtcgttacgct
agtaagaagtaccttacgcccaatatatgggacggtaattagcagggttcgaacttccct
tacgaattattaaaggtgtcagaacgagt-------------------c-----------
---------agggttgtcacatcgga---tatcgacccacactaaggggtgctaacaat-
------------------------tcttgctgctgtcggataacacaaccctcgcgaa--
-------------------cgcacgccccgcatgatttatgccataccaacgcttgtttg
cacaccgcaaggaaggttcgctcgagccccaacaaggcaaatggcgctcatcggcagacc
gctaacgggtggcggacatcatgacct---------------------------------
---------------gattgccccactggccttgagggattacggaggaa----------
-------ctttac-----------------------------------------------
--------------------
>SEQ19
cgtagggcgcacctcaaaagtaccaactgtgcattcctccttttacaatgggca------
-------------acgtgccatgcttggtctca-------------------cctagccg
ggctggatgtagttggtccgacaaggaagtcctt--------------------------
--------------gagttttctcgagcccattaaacgaaataccatgcgtcggtgtctt
cggttttccgtagggcttccgattgatacgtaaaatatacttttaagcacgcccgcctac
atggctagtgttggcaaaa----------------------------caagacgtgggtg
cctgtgccgtttcct-------------caccttcgggacca------------------
------------------------------------------------------------
------------------c-gcgaaaaccgggtgtatggtatgagcctcgtcgttaagct
agtaagaagtaccttacgcccaatatatgggacggtaattagcagggttcgaacttccct
tacgattcattcaagtgaccggagcgtgtcaggttggggctaggagctcgtgcgggaaaa
ttcctttc--------------------------atgc-----aatagtatctaacgact
---aatccacgaatctataaagggtacttcccctgtcggataacccaaccgacgcgtacc
acaatccatgcaaggctcacgcacgccccgcatgatttatgccataccaacgcttgtttg
cacaccgcaaggaaggttagctcgagccccaacaaggcaaatggcgctcatcggcagacc
caaaactgagtact----------------------------------------------
-----------------cccacatcgtggcccttcgtgatagctgaggatgagcggggct
ttttccgatcacagtcccgagt----------------------------tctagtggat
cggtttcgtagta-------
