>SEQ0
ccctgttggctccgagaacttttaaggtctgatcacccttggccacccggatcgaggaga
tgttgacaccgaaaggcgtggatggcagcagcatctgttgcgtcatgaattttatgaggc
ccgcggagattac-----------aagaagtcatgcctatgggatgccacaccccga-cg
gcgcagtatctccgagccttttataatccctattacaggtgtatacatcaccctcgatat
ttatcggcgcatacgagctcgtaccgacccggaggtcttgtccccgtaaaatgtaaatgg
tggtgttttcaaccctaggctcagacgatggctagtggtaactagggaggcccacatgaa
cactatgggactttatcgctagtatgccctttacttctgctagcccgttgtcatacccga
tgactgccctgaataaaatggggttctatggacgatctgagcagatctcagttagaagtg
tatacgtactgccccattaacagcaatcggctctagcacagtgagagaaatcccatctat
ccctaggcgtagagggagtgggatctttttggcctctgcactggaattgagtcctccttc
acaggcaataagggactgaagtactaccagtcatgaaatcaagttcgtcgtcctcatcca
aagtcggatggacaacaggggtggccacgtccatggcgtgtgcccttgaagagcccgcaa
ccaatccttgcctctttgtggctgtaaggcatcgcacgcttgcgcagacctaattggctc
taacgacctaaacattgagcaatatcaggtcccaccttgcagcacatcgtcttgacggca
tgcgtctactcgagttcagtacgtccatcaggcactcgtatacactgtaatcttcagccc
gaacatgtcagaggagagttacctgtcaatgggcggtgattccacgcggatgagaactag
cagaccgtctaatggcgcgtgtttagaaggcaatgatgtagcgttggtcaggtacctatt
gagcgacgtatcccctaggcgccgctcggcacactcatcctaatgggcgcaatggaacgc
tatcccggttgtggtcgtaaccacacgcgcca
>SEQ1
ccctgttggctccgagaacttttaagatctgagcacccatggccaccaggatcgaggaga
tgttgtaaccgaaagccatggatgacagcagcaactgttgcctcattaattttatgaggc
ccgcggagattac-----------atgaagacatgcgtatgggatgccacagcccga-ct
gcgcagtatctacgagcct-------------ttacaggtgtatacatcaccctcgatat
ttatcggcgcatacgagctcgtaccgacccggaggtcttgtccccgtaaaatgtaaatgg
tggtgttttcaaccctaagctcagacgatggcaagtgctaactagggaggccttcaagaa
caataggggacttta---------------ttacttc-----------------------
tgactgccctgaataaaatagggttctatagccgatctgagcagatctcagttagaaatg
tatacgtactgccccattaacagtaatcggctctagcacagtgagagaaatcccatctat
ccctaggcgtagagggagtgggatctttttggcctctgcactggaattgagtcctccttc
acaggcaataagggactgaagtactaccagtcatgaaatcaaattcgtcgtcctcatcca
aagtaagatggacaacagggctggccacgtccgtggcgtgtgcccttctcgagcccgcaa
ccaatccttgcctctttgtggctgtaaggcatcgcacgcgtgc----------------c
taacgacctaaacactgagcaaaatcaggtcccaccttgcagcacatcgtcttgacggca
tgcgtctactcgagttcagtacgtccatcaggcactcgtatacactgtaatcttcagccc
gaacatgtcagaggcgagttacctgtcaatgggcgttgcttccacgcggatgagcaat--
-------------------cgtttagaaggtaatgaagtagcgttggttaggtacccatt
gagcgacgtatcccctaagccccgctcggcacactcatcctaatggaggcaatggaactc
tatcccggtcggggt-----------------
>SEQ2
ccctgttggctccgagaatttgtaagatctgagcacccatggc-----------------
tgttgtaactcaaacccgtgcatgacagtagcaactgatgcc------------------
---------------------------------------tgagtagccacagcccga-ct
gcgcaatatctaagagccc-------------ttacaggtgtatacatcaccctcgatat
ttatcggcgcatacgagctagtaccgacccggaggtcttgtccccgtaaaatgtaaatgg
tggtgttttcaaccctaggctcagacgatggctagtgttaattagggaggcccacatgaa
cacgataggactttatcgctagtatgcccacctgtt------------------------
-----------------atcataccctatggacgatctgagcaggtttcagttagaagtg
tataggtactggcccaataacagcaatcggctctagcaaagtgagagaaatcccatctat
ccctaggcgtagagggagtgggatctttttggcctctgcactggaattgagtcctccttc
acaggcaataagggactgaagtacgaccagtcatgacatcaagttcgtcgtcctcgtcca
aagtcggatggacaacaggggtggcgacgtccatggcgtgcgcccttgaagagcccgcaa
ccaatccttgcctctttgtggctgtaaggaa------------------ctaaattgctc
taacgacgtaaacattg--------------ccaccttgcagcacatcgtcttgacggca
tgcgtctactcgagttcagtacgtccatcaggcactcgtatacactgtaatcttcagccc
gaacatgtcagaggcgagttatctgtcaatcggcgttgcttccgcgaggatgagcaat--
-------------------cgtttagatggaaatgaagtagcgttggttaggtacccctt
cagcgacgtatcccctaagccccgctcggcacactcatcctaacggaggcattgaaactc
tatcccggtcgg--------------------
>SEQ3
ccctgatggctgcgtgaacttttaagatctgagcacccatggctagcaggatcgaggaga
tgttgtaaccgaaagccatggatgtcagcagcgactgttgcctcattaattttatgaggc
ccccggagattac-----------atgaagacatgcgtatgggatgccacagcccga-ct
gcggagtctctacgagcca-------------ttacaggtgtatacatcaccctcgatat
ttatcggcgcatacgagctagtaccgacccggaggtcttgtccccgtaaaatgtaaatgg
tggtgttttcaaccctaggctcagacgatggcaagtgttaattagggaggcccacatgaa
cacgataggactttagcgctat--------------------------------------
-----------------atcataccctatgcacgatctgagcaggttacagttagaagtg
tatagccactgtcccaataacagcaatcggctctagcacagtgagagaaatcccatctat
ccctaggcgtagagggagtgggatcttttcggcctctgcactggaattgagtcgtccttc
acaggcaataagtgactgaagtactaccagtcatgaaatccagttcgtcgtcctcatcca
aactgagatggacaacaggggtggccacctactgtgcgtctgcccttgaagagcccgcaa
ccaatccttgcctctttgtggctgtaagacattgcacgcttgcgcagacctaattgtctc
taacgacctcaacattgagcaatatgaggtcccaccttgcagcacatcgtcttgacggca
tgcgtctactcgagttcagtacgtccatcaggcactcgtttacactgtaatcttcagccc
gaacatgtcagaggcgagttacctgttattgggcgttgcttccacgcgtatgggaaat--
-------------------cgtttagaagttaatgaagtagcttgggttaggtactcttt
gagcgaggtatccccttagctcc-------------------------------------
--tcccgttcggggt-----------------
>SEQ4
ccctgtcggct---------------------------------accaggatcgaggaga
tgttgagac-----------------aggcgcaactgtttcctcattaattttatgaggc
gcgcggagattgc-----------attaagacatacgtatgggatgcaacagcccga-cg
gcgcagtatctacgag----------------ttacaggtgtatacatcaccctcgatat
ttatcggcgcatacgagctagtaccgacccggaggacttgtccccgtaaaatgtaaattg
tggtgttttcaaccctaggctcagacgatggctagtggtaactagggaggccctcatgaa
cactatgggactttaccgctagtgtgcccgtt----------------------------
-----------------gtggggttctatggacgatctgagcagatctcagttagaagtg
tc------------------catcaatcggccctagcaaagtgagagaaatcccatctat
ccctaggcgtagagggagtgggatctttttggcctctgcactggaattgagtccgccttc
acaggcaataagggactgaagtgcta--------------------gtcgtcctcatcca
aagtaagatggagaagagggctggccacgtccgtggagcgtgcccttctggagtccgcaa
ccaatccgtgcctctttgtggctgtaaga-------------------------------
------------------gctaaatcaggttccaccttgcagcacatcgtcttgacggca
tgcgtctactcgagttcagtacgtccatcaggcactcgtatacactgtaatcttcagccc
gaacatgtcagaggcgagttatctgtcaaacggcgtggt---------------------
-------------------------aatgtagacgaagtagcgttggttaggtacccctg
ccgtgacgtatccccttagccccgctcggcacactcatcctaacggaggcaatgaaactc
tatcccggtcgc--------------------
>SEQ5
ccctgttgtttccgagtacttttaaggtctgatcaccctcggccactcggatcgaggaga
tgttgacaccgaaa------------ggcggcgatggcagcagcatccgttgc-------
-----------gc-----------aagaaatcatgcctataggatgccacatgccca-cg
gcgcagtctctccgatccttttataatccctattacaggtgtacacatcaccctccatat
ttatcggcgcatacgagctcgtaccgacccggaggtcttgtccccgtaaaatgtaaatgg
tggtgttttcaacccgaggctcagacgatggctagtggtaactagggaggccttcatgaa
cgatatgggacttaaccgctagtgtgccc-------------------------------
-----gttt---------tggggtttaatggacgatctgagcagatctcggttagaagtg
tccct------------------caatcggccctagcacagtgagagaaatcccatctat
ccctaggcgtagagggagtgggatcttttcggcctctgcactggaattgagtcgtccttc
acaggcaataagtcagtcaactactaccagtcatgaaatccagtttatcgtcctcatcca
aactgagatggacaacgggggtggcctcctactgtgcgtctgcccttgaagaggccacca
ccaatccttgcctctttttggctgtaagacattgcacgcttgcgcagacctaatggtctc
taacgacctcaacattgaacaatatgcggtcccaccttgcagcacatcgtcttgacggca
tgcgtctactcgagttcactacgtccatcaggcactcgtatacactgtattcttcagccc
gaacatgtcagaggcgagttctctttcaaacggcatggt---------------------
-------------------------aatgtagacgaattagcgttggctaggtacccctg
ccgtgtcgtatcccgttatccccgctcggcacactcatcgtaacggaggcaatgaaactc
tatcccggt-----------------------
>SEQ6
ccctttaggct-----------------------------------------cgatgaga
tgttgaggc-----------------aggcgcaactgtttcctcattaattgtatgaggc
gcgcggagattgc-----------attcagacattcgtatgggacgcaacagcccga---
--------------------------------ttacaggtgtatacatcaccctcgatat
ttatcggcgcatgcgagctagtaccgacccggaggtcttgtccccgtaaaatgtaaatgg
tggtgttttcaaccctaggcacagaggatggctattgttacttagggaggcccacctgta
aaagatacggctttatcgctagtatgccc-------------acctggtatcataccca-
---------------------------atggccgatctgagcaggtttcagttagaagtg
tataggtactggtccaataacagcaatcggctctagcaaagtgagagaaatcccatctat
ccctaggcgtagagggagtgggatctttttggcctctgcactggaattgagtcctccttc
acaggcaataagggactgaagtactaccagtcatgaaatcaagttcgtcgtcctcttcca
aagtcggatggtcaacaggggagaccacgtccatggcgagtgcccttgaag---------
-----------------------gtaaggcatcgcacacttgcgcagacctaattcgctc
taacgaactaaacattgagcaatatcaggtctcaccttgcagcacatcgtcttgacggca
tgcgtctactcgagttcagtacgtccatcaggcactcgtatacactgtaatcttcagccc
gaacatgtcagaggagagttatctgtccatgatcggtgattccacgctgatgagaactag
cagacagtctaatg-----------------------gtagcgtag--------------
-------------------------tcggcacactcatcctaatgcgcgcaatggaaggc
tcgcgcca------------------------
>SEQ7
ccctttaggct-----------------------------------------cgatgaga
tgttgaggc-----------------aggcgcgaatgtttccagatgaattgtctgagg-
-------------------------------cattcgta----------------ga---
--------------------------------ttacaggtgtatacatcaccctcgatat
ttatcggcgcatacgagctcgtaccgacccggaggtcttgtccccgtaaaatgtaaatgg
tggtgttttcaaccctagggtcagacgatggctagtcttaactaggaaggcccacaagaa
cactatagggctttgccgattgtatgccctttacttgttctggcccgttgtcatacccgt
tgactgccctgaataaaatggggttctatggacgatctgagcagatatcagttagaagtg
tatacgtcctgccccattaacag---------ctagcacagtgagagaaatcccatctat
ccctaggcgtagagggagtgggatctttttggcctctgcactggaattgagtcctccttc
acaggcaataagggactgaagtactaccagtcatgaaatcgagttcgtcgtcctcctcca
aagtcgg---------------gaccacg-------------------------------
-------------------------------tggagcacttgcgcagacctaattcgctc
taacgaactaaacattgagaaatatc------caccttgcagcacatcgtcttgacggca
tgcgtctactcgagttcagtacgtccatcaggcactcgtatacactgtaatcttcagccc
gaacatgtcagaggagtgttatctgtccatgatcggtgcttcgacgctgaagcgatctag
cagacagtctaatg-----------------------gtagcgtag--------------
-------------------------tcggcacactcatcctaatgcgcgcaaagcacggc
tcgc----------------------------
>SEQ8
ccctgttggctccaagaacttttgagatctg--------tggccaccaggatcgaggaga
tgttgtaaccga-----------------------tcttggctcattaattttctgaggc
ccgcggaaattga-----------atgaagacaggcgtatgggatcccacaccccga-ct
acgcagtatttacgagcct-------------ttacaggtgtatacatcaccctcgatat
ttatcggcgcatacgagctagtaccgacccggcggtcttgtccccgtaaaatgtaaatgg
tggtgttttcaagcctaggctcagacgatgggtagtgttaattaggggggcccacatgaa
cacgctaggactttatcgctag--------------------------------------
-------------------gacgcccgatccacgatctgagcaggtttcagttagaagtg
tttaggtactggcccactgatagcaatcggcgctagcacagtgagagaaatcccatctat
ccctaggcgtagagggagtgggatctttttggcctctgcactggaattgagtcctccttc
acaggcaataaggg---------------ctcatgaaatcaaattcattgtcctcatcca
aagtaagatggacaacggggctggtcacgtcagttgcgtgtgcccttctcgagcccgcaa
ccaatccttgcctctttgtggcagtaagacct----------------------------
----------------------------atcccaccttgcagcacatcgtcttgacggca
tgcgtctactcgagttcagtacgtccatcaggcactcgtttacactgtaatcttcagccc
gaacatgtcaaaggatag---------------------ttccacgcggatgggatctag
cagactgtctaatggcgcgtgtctagaaggcaaagatgtagcgttggtcaggtgtctatt
aagcgacgtattccctaggcgccgctcggcacactcatcctaatgggcgcaatggaacgc
tatccagcttgtggtagcaacaaca-------
>SEQ9
ccctatcggct---------------------------------accaggatcgaggaga
tgttgagac-----------------aggtgcaactgtttcctcattcattttatgaggc
gcgtggagatcgc-----------attaagacatacgtatgggatgcaacagcccga-cg
gcgcagtatctaggac----------------ttacaggtgtatacatcaccctcgatat
ttatcggcgcatacgagctcgtaccgacccggaggtcttgtccccgtaaaatgtaaatgg
tggtgttttcaagcctagtctcagacgatgggtagtgttaattaggggggtccacatgaa
cacgctaagactttatcgctaggacgccc-------------------------------
--------------------------gatacacgatctgagcacgattca----------
-----------------------caatcggcgctagcaaagtgagagaaatcccatctat
ccctaggcgaagagggagtgggatctttttggcctctgcactggaattgagtcctccctc
acaggcaataagggtctgaagtactaccagtcatgaaatcaaattggtcgtccacatcca
aagtaac--------------------cgtccgtggcgtgtgcccgtctcgagcccgcaa
ccaatccttgc-------------------------------------------------
--aacgggtgcataccgagctaaa-------ccaccttgcagcacatcgtcttgacggca
tgcgtctactcgagttcagtacgtccatcaggcactcgtatacactgtaatcttcagccc
gaacatgtcagaggtgagttatctgtcaatcggcgttgcttacgcgatgatgagcaat--
-----------------------------------------------cgaggcacccctt
gagcgacgtatcccctaagccccgctcggaaaactcttcctaacggaggcattgaaactc
ttatccggttgg--------------------
>SEQ10
ccctttaggct-------------------------------------------------
ttttgaggc-----------------aggcgcaactgtttcctcaagaattgtatgaggc
gcgcggagattgc-----------attaagacattcgtatgggacgcaacagccc-----
--------------------------------ttacaggtgtatacatcaccctcgatat
ttatcggcgcatacgagctagttccgacccggaggtcttgtccccgtaaaatgtaaatgg
tggtgttttcaaccctaggctcagacgatgtctagtggtaactagggaggc---------
----atggggctttatcgctagtatgacctatacttatgttagcctgttgtcatacccga
tgacggccctgaataagatg--------------------------ctcagttagcagtg
tataagtactgccccattaacagcaattggctctagcacagtgagagaaatcccatctat
ccctaggcgtagagggagtgggatctttttggcctctgcactggaattgagtcctccttc
acaggcaataagggaatgaagtactaccagccatgaagtcaagtgcgtcgtcctcataga
aagtcggatgcacaacaggggtggccacgtccatggcgt-------------------aa
ccaatcatagcctctttaaagctgtaaggcatcccatgcttgcgcggacctaattggatc
taacgacctaaacatcga--------------caccttgcagcacatcgtcttgacggca
tgcgtctactcgagttcagtacgtccatcaggcactcgtatacactgtaatcttcagccc
gaacatgtcagatgagtgttttctttccatgatcggtgcttagatgcggacgtgacctag
cagacagtcttatg-----------------------ctagcgtag--------------
-------------------------taggcacacacatcctaatgcgcgcaaagcatggc
acac----------------------------
>SEQ11
---------------------------------cactttaggc--------tccaggaga
tgtggaggc-----------------aggcgcaacagtttcctcattaatatt-------
-----------gc-----------attcagacatacgtatgggacgcaac----------
-------------------------atcccgattacaggtgtatacatcaccctcgatat
ttatcggcgcatgcgagctagtaccgacccggaggtcttgtccccgtaaaatgtaaatgg
tggtgttttcaaccctaggctcagacgatggctagtggtaactagggaggcccaaatgca
gactatgggactt-tctgctaccatgact-------------------------------
-----gccccgaacaaaatggggttctatggacgatctgaacatatctcagttagaagtg
tatacatactggctcataaacagcaatcggctctagcacagtgagagaaatcccaactat
ccctaggcgtagagggagtgggatctttttggcctctgcactggaattgagtcctccttc
acaggcaataagtcagtcaaatactaccagtcatgaaatccagtttatcgtcctcatcga
aactgagatggacaacggggttgccctcctactgtgcgtctgcccttgaagaggacacca
ccagtccttgcatctttttggctgtaagacattgcacgcttgcgcagacttaatggtctc
tagcgacctcgacattgaacaatatgcggtcccaccttgcagcacatcgtcttgacggca
tgcgtctactcgagttcagtacgtccatcaggcactcgtatacactgtaatcttcagccc
gaacatgtcagaggcgagttctctttcaaacggcatggt---------------------
-------------------------aatgtagacgaactagggtcgtctaggtacccctg
ccgtgtcctatcccgtt--------------cactcatcgtaacggaggcaaagaaactc
tatcccggt-----------------------
>SEQ12
ctctgttgtttccgagtacatttaaggtctgatcaccctcggccactcgtagcgagggac
gat-----------------------agcagcatccgttgc-------------------
-----------gc-----------aagaaatcatgcctataggatgccacatgccca-cg
gcgcagtctctccgatccctttacaatccctattacagttgtatacatcaccctcgatat
ttatcggcgcatacgtgctcgtaccgacccggaggtcttgtccccgtaaaatgtaaatgg
tggtgttttcaaccctaagctcgaacgatggcaagtgctaacta----------------
-----------------------------------------------------ttacttc
tgactgccctgaataaaattgggatctataggcgatctgagcagatctcagttcgaaatg
gct--------------taacagtaatcggtactagcacattgagagaaatcccatctat
ccctaggcgtagagggagtgggatctttttggcctctgctctggaattgagtcctctttc
acaggcaataaggaactgaagtacgaccagtcatgacatcacgttcgtcgtcctcgtcca
aagtc------------------------tccatgacgtgcgcccttgaagagcccgcct
cgactccttgcctcttattggctgtaaggaactaaatt----------------------
----------------------------gctccaccttgcagcacatcgtcttgacggca
tgcgtctactcgagttcagtacgtccatcaggcactcgtatacactgtaatcttcagccc
gaacatgtcagaggtgagttttctctcaaacggcatggt---------------------
--------------------------agttagacgaactagggtcgtctaggtacccgt-
-------------------------------------------tggaggcaaagaaactt
tatcacggt-----------------------
>SEQ13
cccttgaggct-----------------------------------------tgatgaga
tgttcaggc----------------------------------------------ag---
gcgcgaatgtttccagctgaattgtctgaggcattcata----------------ga---
--------------------------------ttacaggtgtatacatcaccctcgatat
ttatcggcgcatacgagctagtaccgacccggaggtcttgtccccgtaaaatgtaaatgg
tggtgttttcaaccctaagctcagaagatggcaaagaagaacagggga------------
------------------------------------------------------ctttac
tgactgccctgaataaaatcggattctatagccgatctgagcagatctcaccat------
-----------------taaaagcaatcggctctagcaaagtgagagaaatcccatctat
ccctaggcgtagagggagtgggatctttttggcctctgcactggaattgagtcctccttc
acaggcaataaggaactgatgtacgaccactcatgacatcacgttcgacgtcctgttcga
aa------------------------tcctccttgacgtgcgcccttgacgagtccgcct
cgactccttgccccttattggccgtaagg-------------------------------
--------------------actaaattgctccaccttgcagcacatcgtcttgacggca
tgcgtctactcgagttcagtacgtccatcaggcactcgtttacactgtaatcttcagccc
gaacatgtcagaggcgagttgtctgtcagtcggcctttctcccgcggggatgagctatcg
ta-----------------------gatggaaatgaagtagcgatggttaggtacccctt
cagcgacgtatcccctatgtcccgcacggcacactcatcctaacggaggcgttcacactc
tctcccggtcgg--------------------
>SEQ14
cactttaggct------------------------------------------------a
tgttgaggt----------------------------------------------gaggc
gcgcggagattgc-----------attcagacgttcgtatggaacgccacaacccga---
--------------------------------tgtcaggtgtacacatcaccctctatat
ttatcggcgcatacgtgctcgtaccgacccggaggtcttgtccccgtataatgtaaatgg
tggtgttttcaaccctaagcactaacgagcgcaagtgctaacta----------------
------------------------------------------------------------
tgactgccctgaataaacttgggatctataagcgatctgagcagatctcaattcgaaatg
gtg--------------taacggtaaccggtactagcaaagtgagagaagtcccatctat
ccctaggcgtagagggagtgggatctttttggcctctgcactggaattgagtcctccttc
gcaggcaataaggaactgatggtcgagcactcatgccatcacattcgaagtcctgtacta
aa------------------------tcctccttgaagtgcgccgtagacgagtccgcct
cgactccttgccccttagtagctgtaagg-------------------------------
--------------------actatattgctccaccttgcagcacatcgtcttgacggca
tgcgtctactcgagttcagtacgtccatcaggcactcgtatacactgtaatcttcagccc
gaacatgtcagaggcgagttaactgtcaatgggc--------------------------
--------------------------------------------------ggtgcttttt
agaaggcgtatcccctaagccccgctcggcacactcatcctaatggaggcaatggaactc
tatcccggtcgggtt-----------------
>SEQ15
cactttaggct-----------------------------------------ccagggat
tgtggacag----------------------------tttcctcattaatttgt------
------------------------attcagacatacggatgggacgaaacatcccga---
--------------------------------ttacaggtgtatacatcaccctcgatat
ttatcggcgcatacgagctcgtaccgacccggaggtcttgtccccgtaaaatgtaaatgg
tggtgttttcaaccctaggatcagacgatggctagtgttaattaggtagatccccattaa
cacaataggactttatccctagtatgcccacctttt------------------------
-----------------ctcataccctatggacgatctgagc------------------
---agctaccggcccaataacagcaatcggctctagcacagtgagagaaatcccatctat
ccctaggcgtagagggagtgggatctttttggcctctgcactggaattgagtcctccttc
acaggcaataaggg---------------ctcatgaaatcagatccaatgtcctcatcca
aagtcagatggacaacgggactggtcctgtcagttgcgtgtgcccttctccagcccgcaa
ccaatccttgcgtctttgtggcagt-----------------------------------
-----------------------------ctacaccttgcagcacatcgtcttgacggca
tgcgtctactcgagttcagtacgtccatcaggcactcgtatacactgtaatcttcagccc
gaacatgtcagaggcgagtt---------------------------ggatgagctatgg
ta-----------------------gacggaaatgaagtagcgatggtacggtacccctt
cagagacgtatcccctatgtcccacgcggcacactcatcctaacggaggcgttcacactc
tctcccgatcgg--------------------
>SEQ16
cactttaggat-------------------------------------------------
------ggc-----------------aggtgcaggcgtttcctcattaat----------
--------attgc-----------attcagacatacgtatgggacgcgacatcccga---
--------------------------------ttacaggtgtatacatcaccctcgatat
ttatcggcgcatacgagctcgtaccgacccggaggtattgtccccgtaaaatgtaaatgg
tggtgttttcaaccctaagctcagacgaaggcaagtgcaaactagggaggccttcaggta
ctttaggggactttattact--------------------------------------tc
tgactgccctgaataaaagagggttctatagcagatctgggcagatctcagttagaaatg
----------gcccgattaacagtaatcggctctagcaaagggagagaagtcccatctat
ccctaggcgtagagggagtgggatctttttggcctctgcactggaattgagtcctccttc
gcaggccataagggacttaagtactaccagtcatgaaatcgagttcgtcgtcctcctaca
aagtccg---------------gaccacgtggagcac-----------------------
------------------------------------------------------------
--------------ttgcgcagaaaaaacatccaccttgcagcacatcgtcttgacggca
tgcgtctactcgagttcagtacgtccatcaggcactcgtatacactgtaatcttcagccc
gaacatgtcagaggagtgttatatgtccatgatcggtgattccacactgatgagaactag
caaaca-------------------------------gtagcgtag--------------
-------------------------ccggcacactcctcctaatgcgcgcaatggaaggc
ccgcgcca------------------------
>SEQ17
tcctgttggct-----------------------------------------ccgagaat
tgctgttg--------------------------------------taactcca------
------------------------tcccgtgcatgacagtagcaccagatgccttagtag
ccaaagcgcgactgcagaatatttaagagcccttacaggtgtacacatcaccctacatat
ttatcggcgcatacgagctcgtaccgacccggaggtcttgtccccgtaaaatgtaaatgg
tggtgttttcaaccctaggctcagacgatggcaagtgttaattcggaaagcccacgggaa
cacgattagactttagcgcta--------------t------------------------
-----------------atcataccctatgcgcggtctgcgcaggtttcagttagacgtg
tatagccactgtcccaataacagcaatcggctctagcaaagtgagagaaatcccatctat
ccctaggcgtagagggagtgggatctttttggcctctgcactggaattgagtcctccttc
acaggcaaaaaggg---------------ctcatgaaatcagatccaatgtccttatcca
aagtcagatggacaacgggactggtcgtgtcagttggctgtgccc---------------
----tccatgcgactttgtggcagt-----------------------------------
--------------------------------caccttgcagcacatcgtcttgacggca
tgcgtctactcgagttcagtacgtccatcaggcactcgtatacactgtaatcttcagccc
gaacatgtcagaggcgagtt---------------------------ggataagctatg-
----------------------------------gaagtagcgatggtagagtacccctt
cattgacgtatcccctatgtcacacgcggcgcactcatcctaacggaggcgttcacagtc
tctcccgatcgg--------------------
>SEQ18
ccctttaggac-------------------------------------------------
----gaggc-----------------agccgcgaatgtttccagatggttcgtaga----
------------------------------------------------------------
--------------------------------ttacaggtgtatacatcaccctcgatat
ttatcggcgcatacgagctcgtaccgacccggaggtcttgtccccgtaaaatgtaattgg
tggtgttttcaaccctaggatcagacgatggctattgttta------------------a
cacaatgggactttatccctaaccttttc-------------------------------
--------------------------tatggacgatctgagcag----------------
-----ctaccggcccaataacagcaatcggctctagcaaagtgagagaaatcccatctat
ccctaggcgaagagggagtgggatctttttggcctctgcactggaattgggtcctccctc
acaggcaataagtcagtcaactactactagtcatgaaacccagttcatcgtcctcatcca
aactgacaggcacaacgggggtg--------------------ccttgaagaggccacca
ccaatccttgcctctttatggctataagacattgcacgcttgcgcagacctaatggtctc
taacgacctcagccttgaacaatattcggtactacctcgcagcacatcgtcttgacggca
tgcgtctactcgagttcagtacgtccatcaggcactcgtttacactgtaatcttcagccc
gaacatgtcagaggagtgttagctgtccatgatcggtgctttgtcgctgaagcga-----
---------------------------------------agcgtag--------------
-------------------------tcggcacactcatcctaatcggcgcaaagcacggc
tcgc----------------------------
>SEQ19
-----------------------------------------------cgctgcgatgaca
tgttgaggc-----------------aggcgcaactgtttcctcattaattgtatgaggc
gcgcggagattgc-----------attcagacattcgtatgggacgccacagcccga---
--------------------------------ttacaggtgtatacatcaccctcgatag
ttatcggcgcatacgagctagtaccgacccggaggtcttgtccccgtaaaatgtaaatgg
tggtgttttcaaccctaggcacagaggttggctattgttacttagggaggcctacctgta
aaagatacggctttatcgttagtatgccc-------------acctggtatcataccc--
-----------------------------------tctgagcaggtttcagttagaagga
tataggtactggtctaataacagcaatcggctctagcaaagtgagagaaatcccatctat
ccctaggcgtagagggagtgggatctttttggcctctgcactggaattgagtcctccttc
acaggcaataagggactgaagtgcta--------------------gtcggcctcatcca
aa---------------gggctggccacgtccgtggaccgtgcccttc------------
----------cctctttgtggctgtaaga-------------------------------
------------------gctaaatcaggttccaccttgcagcacatcgtcttgacggca
tgcgtctactcgagttcagtacgtccatcaggcactcgtatacactgtaatcttcagccc
gaacatgtcagaggcgagttaccagtcaa-------------------------------
-------------------tgtttagaaggtcttgaagtagcattggttcggtacccata
gagcgacgtatcccctaagccccgctcggcacactca------------------aaccc
tatcccggtcagggt-----------------
