>SEQ0
agcacccactgtttaagggcattgcagccaaagcaggcgcgactcactctggtcggagaa
atgaacttctagggagcggtgtgtgcaatatgctaagcgcacagggccacctgtttcacc
cttccagtcgtcttgttaatttgccggtgacggggtcatgtattgattacctcttaatga
taaacgactagaccccattagccaaggggtcccggtgacttcagggtttacctcgcaggg
gctgattgttgtcgccaatggacaatgaaacgagatctcttgagtgtgaataaaaggcgg
gaaaaagattcgacactgccttggggccgggtactggatccttcattgtgagttaggccc
gacgcactaagagggaatggtccaggcctgggcttcgtgcgggtagtgtaggcctgccac
ctgctcaataccagggtcagttcaggccccaggctctgttgctaacgtgctttctctcac
attaggcaccgatcccacttggctacgtatgttgctacgaatttgctaacgttcttggtg
gtatacagctgtcagcccgcgggccctgatctgagaacaggtgatttctgccgacagctc
atcgcctatggtttggcttggggtctagtcttgcaggactttggtggacaatactcttcg
gcctgtcttaacagggattccctcacgatcattgaaggttgcggcttctgtgtattctcc
tgggctgacgaagggggccgcacttgtatttcgtcgtccatatcggtgagttcccaggct
acgagccagccatttcatcgactgtagatcctaacccttgccgtgcaactagtacgtcat
gccgtgactagaagcgtggttagctgattcaagttgtcgtatcgtgtgtccggtaaacat
tcctggcagtatcgctaacgtacaatgacataacaagccttaacttctgcgcagcgaaga
tacggcaagagactgaagcacggcaatctatgagtaggcacagttatacttgaatctggt
tctccgtggccacagcgctgtgattctgaatcatagctccgccccgatgaccctgggaac
tatctataacctatagtctc
>SEQ1
accactcactgtttaagggcattgcagtcaaagcaggcgcgactcactctggtcggagaa
atgaacttcaaggga-----------------------gcacagggccacctgtttcaca
cttccattcgtcttgttaatttgccggtgacggggtcatgtattgattacctcttaatga
taaacgcttaaaccccattagccaaggggtcccggtgacttcagggtttacctcgcaggg
gctgattgttgtcgccaatggacaatgaaacgagatctcttgagtgtgaataaaaggcgg
gaacaagattcgacaatgccttggggccgggtactgtatccttcactgtgagttaggccc
gacgcactaagagggaatggtccagacctgggcttcgtgctgctagtgtaggcctgccac
ctgctctaaaacagggtc-------------------------aacgttctatctctcac
atttggcaccgatcccgcttggctacgtatgttgctacgaatttgctaacgttcttggtg
gtatacagctgtcagcccgccggccctgatctgagaacaggtgatttctgccgacagctc
atcgactatggtttggctgggggtctaatcttgcagtactttggtgggcgatactcttcg
gcctgtcttaactgggattccctcacgatcattgacgggtgcagcttctgagtattctcc
tgggctggcgaagggggccgcacttgtatttcgtcgtccatatcggtgagttcccaggtt
acgagccagccatttcatcgactgtagatcctaacccttgccgtgcaactagtacgtcat
gccgtgactagaagcgtggttagctgattcaagttgtcgtatcgtgtgtccggtaaacat
tcctggcagtaacgctatcgtacaatgacataagaag-----------------------
tacggcaagatactgaagcagggcaatccatgagtaggaatagttatacttcaatatggt
tcgccgtggccaccgcgctgtgattctgaatcatag-----------------------a
tatctataaactatagtcta
>SEQ2
agcacccactgtttaagggcattgcacccaaagcaggcgcgtctcactttgctcggagaa
acgaacttctacgggtcggtgcgtgcaatatgctaagcgcacagggccaccagtttcacc
cctccagtcgtcttgttaatttgccgttgacgggctcatgtactgatttcctcttaatga
tctacgattagacccaattagccaaggggtcccggtgacttcagggattacctcgcaggt
gctgactgttgtcgccgatggacaatgaaacgagatctcttgagtgtgaataaaaggcgg
gaaaaagattcgacactgccttggggccgggcattgaatccttgatagtgagtta-----
-------------ggaatcgtccaggcctgggcttc-------------------gccac
ctggtcaataccagggtcagttcaggccccaggctctgtggctaacgcgcttcctcttac
attaggcaacgatcccacttggctacgtatgttgctacgaatttgctaacgttcttggtg
gtatacagctgtcagcccgcggggcctgatctgagaacaggtgatttctgccgacagctc
atcgactatggtttggctgggggtctaatctcccagtactatggtgggcgatactcgtcg
gcctctctcaa-----------------------------------tctccctattcccc
ttggctgggaaaggggaccacacttttatttcgtcgtccatagtggtgagttccaaggtt
acgagccagccattacatcgactgtagatcctaacccttgccgtgcaactagtacgtcat
gccgtgactagaagcgtggttagctgattcaagttgtcgtatcgtgtgtcctgtaaacat
tcctggcagtaccgctatcgtacaatcacataagaag-----------------------
tacgacatgatactgaagcaaggcaatccatgagtatgaatagttatacttcaatatggt
tctccgtggcgaccgcgctgttattctgaatcataa-----------------------a
tatctataaactatagtcta
>SEQ3
agcacccactgtttaagggcattgca----------------ctccctttgctcggagaa
acgaacttctacgggtcggtgcgcgcaatatgctaagcgcacaggcccaccagcttcacc
cctccagtcgtcttgttaatttgcccttgacgggctcatgtactgatttcctctcaatga
tcttcgattagacccaatttgccaaggggtcccggtgacttcagggattacctcgcaggt
gctgactgttgtcgccgatgcacaatgaaacgagatctcttgagtgtgaataaaaggcgg
gcacaagattcgacaatgccttggggccaggtactgcatcttgcactgagagttaaacca
gacgcaataagagggaatggaccagacctgggcttcgtgt---------------gacac
ctcctctaaaacagggtc-------------------------aacggtctctctctcac
attaggcaccgttgccgcttggctacgtatgttgctacgaatttgctaacgttcttggtg
gtatacagctgtca----gcgggccctgatctgagaacaggtgatttctgccgacagctc
atcgcctttgggttggcttggggtctagtcttg----------------------cttcg
gcctgtcttaacagggattccctaaggatcagtgaaggttaca-----------------
--gcttgacgaagggggccgcacttttgtttcggcgtttatatcggtgag----------
----gccagccatttcatcgactgtagatcctaacccttgccgtgcaactagaacgtcat
gccgtgactagaagcgtggttagctgattcaagttgtcgtatcgtgtgtcctgtaaacat
tctcggaagtaacgctatcgtacaatgacaaaagaag-----------------------
tacggcaagatactgaggcagggcaatcca------------------------------
----catggacaccgctctgtgattctgaatcattg-----------------------a
tatctataaactatagtcta
>SEQ4
ggcacccgatgtttaagggccttgcacccacaccaggcgcaac-----------------
------------gtgtcggtgcgtgcaatttgctaagcgcacagggccaccagtttcacc
cctccagtcgtgttgttactctgccgttgacgg---------------------------
------------------tagccaaggggtcccggtgacttcagggattacctcgcaggt
gctgactgttgtcgccgatgcacaatgaaacgagatctcttgagtgtgaataaaaggcgg
gaacaagattcgacactggcttggggccggggactgtatccttccctgtga---------
----------------atggtccagacctgcgcttcgtggtactagtgtaggcctgccac
ctgctctaaaacagggtc-------------------------aacgttctatcactcaa
atttggcacccttcccgcttggctacgtatgttgctacgaatttgctaacgttcttggtg
gtatacagctgtca----gcgggccctgatctgagaacaggtgatttctgccgacagctc
atcgagtatggtttgcctgggattcta-------------------------attcgtcg
gcctctccc-------------------------------------------tattcccc
ttggctgggaaaggggacaacacttgtatttcgtcgtccatagttgtgagttccaaggta
acgagccagcgattacatcgactgtagatcctaacccttgccgtgcaactagtacgtcat
gccgtgactagaagcgtggttagctgattcaagttgtcgtatcgtgtgtccggtaaacat
tcctggcagtaacgctattgtaaaatgacataagaag-----------------------
tacggcaagatactgaagcagggcaatccatcagtaggaaaagttatacttccatatggt
tcgccgtggccaccgccctgtcagtctgaatcatag-----------------------a
tatctataaactatagtcta
>SEQ5
atcactcactgtttgagggaatttcagtcgaagcaggcgcgactcactctggtcggagaa
atgaagttcaaggga-----------------------gcccagtgccacctgtttcaca
cttccattcgtcttgttaagttgccgtcga----------------ttacctgttaattg
taaacgcttaaacaccattagccaaggggtcccggtgacttcagggattacctcgcacgt
gctgactgttgtcgccgatggacaatgaaacgagatctcttgagtgtgaataaaaggcgg
gtaaaagagtcgacagtgccctgggtccgggcattgtatccttgatagtgagttaggca-
---------------------------ctgggctac-------------------gccac
gtggtccataccagggtccgttcaggccccatgctctgtggctaacgcgcttcctcttac
at----------------ttggctacgtatgttgctacgaatttgctaacgttcttggtg
gtatacagctgtcagcccgccggccctgatctgagaacaggtgatttctgccgacagctc
atcgcctatggattggctgggggtccaatcttgcagtacttcggtggtcgatactcttcg
gcctgtcttaactgggatgccctcacgatcattgacgggtgca-----------------
---------------------gcttgtatttcgtcgtccatatcggtgagttcctaggtt
--------------------actgtagatcctaacccttgccgtgcaactagtacgtcat
gccgtgactagaagcgtggttagctgattcaagttgtcgtatcgtgtgtccggtaaacat
tctcggaagtaacgcgatcggacaatgacaaaagagg-----------------------
------------------cagggtaatcca------------------------------
----catggacaccgcgctgtgtttctagatcattg-----------------------a
tatctataaactatagtcta
>SEQ6
accactcactgtttaagggcattgcattcaaagcagtcgcggctcactctgttcggagaa
atgaacttcaaggga-----------------------gcacaggtccacctgttacaca
cttccattcgtcttgttaatttgccggtgacggggtcatgtatggattacctcttaatca
taaacgcttaatcccggtttgccaaggggtcccggtgacttcagggtttacctcgcaggg
gctgattgttgtcgccaatggacaatgaaacgagatctcttgagtgtgaataaaaggcgg
gaagatgattggacactgcctttgggccaggtactggacccttcattgtgagtttggccc
gacgcactaagagggaatggtccaggcctggggttcgtgcggctagtgtaggcctgccac
ctgctcaataccagggtcagttcaggcaccaggatctgtagctaa----------ctcac
attaggcaccgatcccacttggctacgtatgttgctacgaatttgctaacgttcttggtg
gtatacagctgtcagcccgccggccctgatctgagaccaggtgatttctgccgacagctc
atcgcctatggattggctgggggtcgaatcttgcagtagttcggtggtcgatactcttc-
------------------------------------------------------------
--------------gggctacgggtgtatttcatcgtccatatcggtgagttcctctgtt
--------------------actgtagatcctaacccttgccgtgcaactagtacgtcat
gccgtgactagaagcgtggttagctgattcaagttgtcgtatcgtgtgtccggtaaacat
tccctgaagtaccgctatcgcacaatcacataataag-----------------------
ttcgacatgttacagaagcaaggcaatccaggagtatgaatagttatacttcaatatggg
gctccgtggcgaccgcgctctcagtcggaaacataa-----------------------a
tatcaataaactaaagtcta
>SEQ7
atcactctctgtttaaggtcattgcagccaaagcaggcgcatctcactctgctcggagaa
atgaacttttagggggcggtgtgt----------------------ccacctgtttgacc
attt----------------------------------------------------gtga
taaacgactagaccccattagccaaggggtcccggtgacttcagggattccctcgcaggt
gctgactgttgtcgccgatgcacaatgtaacgagatctcttgagtgtgaataaaaggcgg
gaggatgattggagagtgcatttgggacagg-------------attgtgagtttggccc
gacgctctaaaagggaaaggtccaggccaggggtacgtacgtctagtgtaggcctgccac
ctgctaaataccagggacagatctagctccaggatctgtagctaa----------ctcac
atcaggtaccgatcccacttggctacgtatgttgctacgaatttgctaacgttcttggtg
gtatacagctgtcagcccgccggccctgatctgagaccaggtgatgtctgccgacagctc
atagcctatggattggctgggggtccaatcgtgctctacttcggtggtcgatactgttcg
gcct--------------------------attgacgggtgca-----------------
---------------------ggttctatttcgtagcccatacaggtgagttccaacgtt
--------------------actgtagatcctaacccttgccgtgcaactagtacgtcat
gccgtgactagaagcgtggttagctgattcaagttgtcgtatcgtgtgtccggtaaacat
tctct--------------------tgacaaaagagg-----------------------
------------------cggggtagtcga------------------------------
----catggacacagggctgtgtttctagatcgttg-----------------------a
tgtctataaactatagtcta
>SEQ8
attactcactgtttgagggaatttgactcggagcaggcgcgactcactcgggtcggagaa
atcaagttcaaggga-----------------------gcccagtg--------------
cacccattcgtctcgattacctgtta----------------------------------
---------------aatgtgccaaggggtcccggtgacttcagggattccctcgcaggt
gctgactgttgtcgccgatgcacaatgtaacgagatctcttgagtgtgaataaaaggcgg
gaaaaaaactttacactgccttggggccgg--------tccttcattgtgaggtaggccc
gacgcacaaagaggggat--------------------gcgggtagtgtaggcatgccac
ctgctcaataccagggtcagttgaggccccaggctctcctgctaacgtgctttctctcac
atcaggtaccgttcccacttggctacgtatgttgctacgaatttgctaacgttcttggtg
gtatacagctgtcagcccgccggccctgatctgagaacaggtgatttctgccgacagctc
atcgcctatggtttggctgggggtccaatcttgcagtacttcggtggacgttactcttcg
tcctgtcttaactaggatgaccgcaagatcatggacgggtgca-----------------
---------------------gcttgtatttcgtcgcccatat-----------------
--------------------actgtagatcctaacccttgccgtgcaactagtacgtcat
gccgtgactagaagcgtggttagcggattcaagttgtcgtatcgtgtgtcctgtaaacat
tctcggaagtaacgcgattgtaccatgacaaaagagg-----------------------
------------------ccgggtaatcca------------------------------
----catcgacactgcgctgtgtttctagaacattg-----------------------a
tatcaataaactatagtcta
>SEQ9
accactcactgtttaggggcattgcaggcatagcaggcgctactcactctggttggagaa
atgaacttcagggaa-----------------------gcacagtgccacatgtttcacc
cttcctttcgtcttgttaatttgccggtgacggagtcatgtattgagtacctctaaa---
------------------tggccaaggggtcccggtgacttcagggattccctcgcagtt
gctgactgttgtcgccgatgcacaatgtaacgagatctcttgagtgtgaataaaaggcgg
gcacaagattcgacactgcctt-----------------------cggagagttaaacca
aacgcaataagagggaatggaccagacctgggcttcgtgt---------------gacac
ctccgctagaacagggtc------------------------------------------
-------accgttgtcgcttgtctacgtatgttgctacgaatttgctaacgttcttggtg
gtatacagctgtca----gcgggccctgatctgagaacaggtgatttctgccgacagctc
atcgcctatggtttggcttggggtctagtctagcaggactttggtgggtaatactcttcg
gcctgtcttaacagggattcccacgcgattattgaaggttgcg-----------cctcct
gtgtgtgacgaagggggccgcacttgtattgcgtcttccctatgcgtgagttcccaggcc
acgagcgagccattccaccgactgtagatcctaacccttgccgtgcaactagtacgtcat
gccgtgactagaagcgtggttagctgattcaagttgtcgtatcgtgtgtccggtaaacat
tcctggcagtaacgcgatcgtactacgtcaagataca-----------------------
---------------g-------------------acgaatagttatacagcaatatggt
tcgccgtagccaccacgctgtgatgctgaatcatag-----------------------a
tatgt---------------
>SEQ10
attacttact-----------------ttggagcaggtgggactcactcgtgacggacat
agcaagtccaaggga-----------------------gcccagtg--------------
gacccatttgtcccgattacttgtt-----------------------------------
--------------taatctgccaaggggtcccggtgacttcagggattacctcgcaggt
gctgactgttgtcgccgatgcacaatgaaacgagatctcttgagtgtgaataaaaggcgg
gcccaagattcgacaatgccttagtaccatgtactgcctcttgcactgagagttaaacca
gacccaataagcgcgaatggaccagacctgggcttcgtgt---------------gacac
cccccctaaaacggggtc-------------------------aacggtctctctctcac
attacgcaccgttgccgcttggctacgtatgttgctacgaatttgctaacgttcttggtg
gtatacagctgtcagcccgccggccctgatctgagaccaggtgatttctgccgacagctc
atcgcctatggattggctgggggtcctatcttacagtatttcggtggtcgatactcttcg
ggctgtcttaactgggatgccctcacgatctttgacaggtgca-----------------
---------------------gcttgtattttgtcgtccatatcggtgagttcctaggtt
--------------------actgtagatcctaacccttgccgtgcaactagtacgtcat
gccgtgactagaagcatggttagctgattcaagttgtcgtatagtgtgtccggtaaacat
tctcggaactaacgctatcttacaatgccaaaagaag-----------------------
tacggcaagatactgaggcagggcaatcc-------------------------------
-----------------------------------------------------------a
tatctataaactatagtcta
>SEQ11
accgctcactgtttaggtgctttgcaggcatagcaggcgcgactcactctgggtggagaa
atgaacttcagcgaa-----------------------gcagagtgccacatgtttcaac
cttcctttcctcttgttaatttgctggtgaccgagtcatgtagtgagtacctctaaa---
------------------tggccaaggggtcccggtgacttcagggtttacctcgcaggg
gctgattgttgtcgccaatggataatgaaacgagatctcttgagtgtgaataaaaggcgg
gcacatgattcgacactgcctt-----------------------ccgagagttaaacca
aacgcaataag-----------------tgggcttcgtgt---------------gacac
ctccgctagaaca-ggtt------------------------------------------
-------gccgttgtcgattggctacgtatgttgctacgaatttgataacgttcttggtg
gtatacagctgtcagcccgccggccctgatctgagaccaggtgattgctgccgacagctc
atcgcctattgtttggcttggggtctagtctagcaggactttggtgcgtaatactcttcg
gactttcttaacagggattcctactcgattattgaaggttgcg-----------cctcct
gtgtgtaacgaagtgggccggacttgtagtgcgtcttcactatgggtgtgttcccaggcc
acgagcgagccattccaccgactgtagatcctaacccttgccgtgcaactagtacgtcat
gccgtgactagaagcgtggttagctgattcaagttgtcgtatcgtgtgtccggtaaacat
tccctcaagaaccgctatcgcacaaccacagaataag-----------------------
---------------aagcaaggcaatccaggagtatgaatagttatacttcaatat---
------------tagcgctctaagtcggaaacagaa-----------------------a
tttcaataatctaaagtcta
>SEQ12
tgcacgcactgtttaggggcattgcaggcatagcaggcgctactcactgtggttggagaa
atcaacttaagtgaa-----------------------gcacagtgccaaatgtttcacc
cttcctttcgtcttattaattcgcc---------------------------ggtgacgg
taaa--------------tggccaaggggtcccggtgacttcagggtttacctcgcaggg
gctgattgttgtcgccaatggacaatgaaacgagatctcttgagtgtgaataaaaggcgg
gtaaaagagtcgacagtgcccagggtccgggcattatatccttgatactgagttaggca-
---------------------------ctgggccac-------------------gccat
gtggtccataccagggtccgttcaagcaccccgccctgtggctaacgcgcttcctctcac
a-----------------ttgtctacgtatgttgctacgaatttgctaacgttcttggtg
gtatacagctgtca----gcgggccctgatctgagaacaggtgatttctgccgacagctc
atcgtctatggtttggctggggatcca------------------------------tcg
tcctgtcttaactagtatgaccgcaagatcatggacgggtgca-----------------
---------------------gc------------------------------------a
--------------------actgtagatcctaacccttgccgtgcaactagtacgtcat
gccgtgactagaagcgtggttagctgattcaagttgtcgtatcgtgtgtccggtaaacat
tctcgg--------------------gtcaaaagacg-----------------------
------------------caggggtatcct------------------------------
----catggacaccccgctgtgtttctagatcattg-----------------------a
tatctat-------------
>SEQ13
-----------------------------------ggcgctactcactgtggttgaagaa
atcaacttaagtgag-----------------------gcacagtgccaaatggttcacc
ctttcttccgtcttattaattcgccggtatagg---------------------------
--------------ttaatggccaaggggtcccggtgacttcagggtttacctcgcaggg
gctgattgttgtcgccaatggacaatgaaacgagatctcttgagtgtgaataaaaggcgg
g------------------------------tactagacacttaattgtgagtttggccc
gacgcactatgagggaaaggtccaggcctggggttcgtgccgctg---------------
------------------aggtcaggcagcaggatctgtagatta----------ctcac
attaggcaccgaccccacttggctacgtatgttgctacgaatttgctaacgttcttggtg
ctatacagctgtcagcccgccggccctgatctgagaacaggtgatttctgccgacagctc
atcgtccattgattggctgggcatcctat-------------------------------
------------------------------------gaccgca-----------------
------------------------------------------------------------
--------------------actgtagatcctaaccctggccgtgcaactagtacgtcat
gcggtgactagaagcgtggttagctgattcaagttgtcgtatcgtgtgtccggtaaacat
tctcggaagtaacgccattgtaccatcacaaaagagg-----------------------
------------------ccgggtaatcca------------------------------
----catcgacactgctctgtgtttctagaacattg-----------------------a
catcaataaactatagtgta
>SEQ14
agaacccactttttaagggcattgcagccaaagcaggcgcgactcactctagccggagaa
gtgaacttctagggagcggtgtgtgcaatatgctaagtgcaaagggccacccgtttaagc
catccagtcgtcttgttaatttgccggtgactgggtcttgtattgtttaccacttaatga
taaacgcctagaccccattagccaaggggtcccggtgacttcagggattccctcgcagtt
gctgactgttgtcgccgatgcacaatgtaacgagatctcttgagtgtgaataaaaggcgg
gaaaaaggttcgacactgccttggggccgggcattaaatccttgatagtgagtta-----
------------------------------------------------------------
-----------------------ggacctcaggatctgtggctaacgcgcaggctcttac
agtaggcaacgatcccacttggctacgtatgttgctacgaatttgctaacgttcttggtg
gtatacagctgtcagcccgccggccctgatctgagaacaggtgatttctgccgacagctc
atcgtctatggtttggatgggcctcca------------------------------tcg
acctgtcttgactagaatgaccgcaagat-------------------------------
------------------------------------------------------------
---------------catggactgtagatcctaacccttgccgtgcaactagtgcgtcat
gccgtgactagaagcgtggttagctgattcaagttgtcgtttcgtgtgtccggtaaacat
tcctgacagtaaagctattgtaaaat----------------------------------
taccgcaagatactgaagcagggcaatccatcagtaggaaaagttatacttccatatggt
tcgccgtagccaccgccctgtcagtctgaatcatag-----------------------a
tatctataaactatagtcta
>SEQ15
attacttact-----------------ttggagcaggtgggactcactcgtgacggacat
ggcaagcccagtggt---------------------------------------------
--cccatttgtcccggttacttgtt-----------------------------------
--------------ttatctgccaaggggtcccggtgacttcagggattacctcgcaggt
gctgactgttgtcgccgatgcacaatgaaacgagatctcttgagtgtgaataaaaggcgg
gaaaaaggttcgacactgccct--------------------------------------
-------------tgaatcgtccagacctaggcttc------------------------
---------accagcgtcagttcaggccccacgctctgtgg----------------tac
atgaggaaaccatcccacttggctacgtatgttgctacgaatttgctaacgttcttggtg
gtatacagctgtcagcccgccggccctgatctgagaccaggtgatgtctgccgacagctt
atcgactatggtttggctgggggtatgatcttgcagtactttggtgggcgctactcttcg
gcctgtc---------------------------acgggtgcaccttctgagtattctcc
tgggatggccaagggg--------------------------tcggtgagttcccaggtt
acgagccacccaatttatcgactgtagatcctaacccttgccgtgcaactagtacgtcat
gccgtgactagaagcgtggttagctgattcaagttgtcgtatcgtgtgtccggtaaacat
tctcggatcaaaagcc--------------------------------------------
------------------------------------------------------------
---ccatggacaccccgctgtctttcgagatcgttg-----------------------a
tatctat-------------
>SEQ16
actaatcactgtctaagggcattgcattcaaagt------------------tcggagca
ctgaactt-------------------------------cacagcgccacctgtctcaca
cttccattcgtctttttaattcgccggtgacgggatcatgta------------------
-----------gcccggtttgccaaggggtcccggtgacttcagggtatacctcgcaggg
gctgattgttgtcgccaatggacaatgaaacgagatctcttgagtgtgaataaaaggcgg
gaaaaagaatcgacagcgccctgggtccgggcattgtatcattgatagtgagctaggca-
---------------------------ctgggctac------------------------
------------------cgttcaggccccatgctctgtggctaa---------------
---------------catttggctacgtatgttgctacgaatttgctaacgttcttggtg
gtatacatctgtcagcccgccggccctgatctgagaacaggtgatttctgccgacagctc
aaagcctatggattggctgggggtccaattgtgctctacttcagtggtcgatactgttcg
gcct--------------------------attgtcgggtgca-----------------
---------------------ggttctatttcgtggcccatacaggtgagttccaacgtt
--------------------actgtagatcctaacccttgccgtgcaactagtacgtcaa
gccgtgactagaagcgtggttagctgattcaagttgtcgtatcgtgtgtccggtaaacat
tcctgacagtaaagctattgtaacct----------------------------------
taccgcaagatactgaagcagggcaatacatcagtaggaagagttatacttccatatggt
tcgccgtagccaccgccctgtcactctga------------------------------a
cat-----------------
>SEQ17
accactcactgttgaacggcattgcat---------------ctctctctgttcggagaa
atgaacttcagggta-----------------------gcacaggtcgacttgttacaca
cttcgattcgtcttgttgatgtgcctgtaacggggtcttgtatggattacctcttaatca
taaacgcgtaattccgttttgccaaggggtcccggtgacttcagggtttacctcgcaggg
gctgattgttgtcgccaatggacaatgaaacgagatctcttgagtgtgaataaaaggcgg
gaaaaaggttcgacgctgccttggggccgcgcattaaatccttgatattgacttagg---
------------------------------------------------------------
-------------------------agctcaggttctgtggcaaacgcgcaggctcttac
agtaggcaaagttcccac-tggctacgtatgttgctacgaatttgctaacgttcttggtg
gtatacagctgtca----gcgggccctgatctgagaacaggtgatttc-----acagctc
atcgagtatggtttgcctgggattctaa------------------gtcgtctctcccta
tacc--------------------------------------------------------
---------------------ccttgtatttcgtcgtacatagttgtgagttccaaggta
acaagccagcgattacatcgactgtagatcctaacccttgccgtgcatctagaacgtcat
gccgtgactagaagcgtggttagctgattcaagttgtcgtatcgtgtgtcctgtaaacat
tcacggatcaaaagc---------------------------------------------
------------------------------------------------------------
-------------------------ccagatcgttg-----------------------a
--------------------
>SEQ18
attacttactttc-----------------gagcaggtgggactctctcgtgatggacat
ggcaagcccagtggt---------------------------------------------
--cttacttgttttat--------------------------------------------
------------------ttgccaaggggtcccggtgacttcagggattacctcgcaggt
gctgactgttgtcgccgatgcacaatgaaacgagatctcttgagtgtgaataaaaggcgg
gaagatgatt----------------------------------------------gccc
gacgcagaaagcgggaat-----------------cgcgcgactagtgtaggccttccac
ctgctcaataccagggtcagttcaggcaaaaggatcagtagctaa----------cgcaa
attaggcggcgatcccacttgtctacgtatgttgctacgaatttgctaacgttcttggtg
gtatacagctgtca----gcgggccctgatctgagaacaggtgatttctgccgacagctc
atcgacaatggtatggcagggggactaatcttccagtactttgggggacgatactcttcg
gcctgtcttaactgggataccctcacgatcattgacgagtgaaacttgtgagttttttcc
tggggt--------------------------gtcgtccatatcggtgagttcccaggtt
gcgtgcgagccatttcaacgactgtagatcctaacccttgccgtgcaactagaacgacat
gccgtgactagaagcgtggttagctgattcaagttgtcgtatcgtgtgtcctgtaaacat
tctcggaagtaatgccataggacaatgacaaaagaat-----------------------
-------------------agggcaagata------------------------------
---ctatggacaccgct------------------------------------------c
tatctataaactatagtaga
>SEQ19
ggcacccgatgtttaagggccttgca----------------------------------
------cccaacgtgtcggtgcgttcagtttactaagtgcacaggccccccagtatcacc
cctccagtagtgttgttactctgccggtgacgg---------------------------
------------------tagccaaggggtcccggtgacttcagggattccctcgcaggt
gctgactgttgtcgccgatgcacaatgtaacgagatctcttgagtgtgaataaaaggcgg
gtaaaagagtagatagtgccctaggtccgacctttgcatccttgatagtgagttcggca-
---------------------------atgggctac-------------------gcaac
gtggtccataccagggtccgttcaggccccacgctctgtgcctaacgcgctt--------
-----------------cctgtgtacgtatcttgctacgaatttgctaacgttcttggtg
gtatacagctgtca----gcggtccctgatctgagaacaggtgatttctgccgacagctc
ctcgcctatttgttcgcttggggtctcgtctagcaggactttagtgcgtaatactcttcg
gactttcttgacagggatttctactcgatgattggcggttgcg-----------cctact
ctgtgtaacgaaatgggccggacttttagtgcgtcttcactatccgtgtattcccagggc
acgagcgatccattccaccaactgtagatcctaacccttgccgtgccactagtacgtcat
gccgtgactagaagcgtggttagctgattcaagttgtcgtatcgtgtgtcctgtaaacat
tcacggatcaaacgccc-------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------
