>SEQ0
actgtttctcgggacgatgctagatatcggaccgctgctacacaaagacagcagacaggg
cggagaccaggaccctgattcattggggcgggcttgcggcgggatagccagggcagggtg
gcatacggagcggaccgataaaatatttccgtagcgcgtaccgcttctttagcaagtacc
tttgacatatttgtaccaacattcacacaccgggtaacggagataaaaacaaacgcgagc
gcttagtttagtcgttcgtctactaacgaaacctcactggtatgaattcagagcacctac
taattatatcctgaagatagcccgtggcagcaacgaggaacgaagacccttgccgttatc
aacatctctcgatcctatgaccctaatgtatttctactcattcataagtgcgtttagagg
ttgttatccaacaatagccgtcaattccaacaaccatggctcccgaggccggctaacagg
gttctccggcgaggctttcacgagaaaccgcttagggttcgtggcgatccgtgagcccgt
tattggaatcgttattattggaaatcgaagcgttaatataggcactcatagtgactggtg
-ttgggatttacctagcaagccacaatggacggaacggctgacgaagtttgcgacaag-g
ctgcaactaactcccggtcagcgtaaatttgtcgtctcaaccttagaaataaggtctcca
ttcttttattaatgggtttaggccatgatctgttcgggatgcaaagctttt-----tgag
tacgagtactgctctaatatgactctagctatatatctgggcttacattattcgaacact
aatacatgatctctcgtatgctcactcaccgctttaatccagtgcggaaaactcactgtg
caaccttatccagagcaggacttgccttcagccttgagcgaatcttaattaagattaaag
ttggaatgtaaacgagatttctcccatgtgcaacagaaatgccgcggcccacgttcggct
atagacgcgtggagaccacaagacttgttgggtcaacgtcccagcaattgccttgcgttc
ttatttcccggggaccatcacaagtga
>SEQ1
actgattctagggaccatgctagatatcgggccgcttctacacaaagacagcagacagag
cggagaccaggaccctgatt------------------gcgggatagccagggcagggtg
gcat----------------aaatatttccgtagcgcgtaccgcttctttcg--------
----------------caacattcacacagcgggtaacggagataaaaacaaacgcgagc
gcttagtttagtcgttcgtctactaacgaaacctcactggtatgaattcagagcacctac
taattatatcctaatgatagcccgtggcatcaacgaggagcgaagacccttg--------
-------ctcgaacctatgaccctaatgtatttcaactcgttcataagcgcatttagagg
ttgttaaccgacagtagccatcaattccaaaaaccatggctccccaggcaggctaacagg
gttctccggcgaggctctcacgagaaaccgcttagggttcgtggcgatccgtgagcccgt
tattggaatcgttattattggaaatcgaagcgttaatataggcactcatagtgactggtg
-ttgggatttacctagcaagccacaatgtacggaacggatgacgaggtttgcgataag-g
ctgcaactaactcccggtcagcgtaaatttgtcgtctcaacctcagaaataaggtttcca
ttctttta---------------------ctcttaggaatgcaaagctcta-----tgag
gacgactactgctctaatataactctagctatatatctgggcttacattattcgaacact
aatacatgatctctcgtatgctcactcaccgctttaatccagtgcggaaaactcactgtg
caaccttatccagagcaggacttgccttcagccttgcgcgaatcttatttaagattaaag
ctgcaatgtaaacgagagttctcccatgtgtg----------------------------
--------------------------gttgggtcaacgtcccagcaatagctttgggttc
ttatttcccggggaccatcacacgtta
>SEQ2
actgattctagggaccatgctagatatcggtccgcttctacacaa---------------
--------aggaccctgatt------------------------------gggcagggtg
gcat----------------aaatacttccgtagcgcgtaccgcttc-------------
----------------caacattcacacagcgggtaacggagataaaaacaaacgcgagc
gcttagtttagtcgttcgtctactaacgaaacctcactggtatgaattcagagcacgtac
--------------------------------aagggaaacgcagacccctgcccatatc
aacgtctctcgatccgatgaccctaat------------attcattagtgcggttagagg
ttgtt---------------------------atcatggctcccgaggccggctaagag-
--------------------cgagaaaccgcttagggttcgtggcgatccgtgagcccgt
tattggaatcgttattattggaaatcgaagcgttaatatagccactcatagtgactggtg
-ttgggatttacctagcaagccacaatgtacgcaacggatgaagaggttagcgatgag-g
ct-----------------------------tcgtctcaacctcagaaacatggtttcca
ttattata---------------------ctcttaggaatgcaaagctcta-----tgag
gacgactactgctctaatataactctagctatatatctgggcttaccttattcgaacact
aatacatgatctctcgtatgctcactcaccgctttactccagtgcggaaaactcactgtg
caaccttatcccgagcagcacgtgccttcagccttgcgcgaatcttgtttaagattaaag
ctg-------------------cccacgtgtg----------------------------
--------------------------gttaggtcaaggtccgatcaatagcattgggttc
ttatttcccggggaccatcacacgtta
>SEQ3
ggtgattctagggaccatgctagatatcgggccgcttctacacaaagactgcagt-----
------------tcctgatt------------------gcgggctagccag---------
--------------------gaatatttccgtagcgcgtgccgcttctttcg--------
----------------caacattcacacaccgggtaacggagacaaaaacaaacgcgagc
gcttagtttagtcgttcgtctactaacgaaacctcactggtatgaattcagagcacctac
taattatatcgtaaggatagcccgtggcatcaacgaggagcgaagaccgttgc-------
--------------------------tgtatttcaactcgttcacaagcgcatttagagg
ctgttaaccgacagtagccatcaagttcaaaaactatggctcccgaggcatgctaacagg
tttctccggcgaggctctgacgagaaaccgcttagggttcgtggcgatccgtgagcccgt
tattggaatcgttattaatggaaatcgaagcgttaatataggcactcatagtgactggtg
-ttgggatttacctagcctgccactatgtacgcaacgagtgaagcgtttagcgatgag-g
ct-----------------------------tcgactcaacctcagaaacaaggtttcca
tgattata----------------------------gaatgcaaagctcta-----tgag
gacgactactgctctaatataactctagctatatatctgggcttacattattcgaacact
aatacatgatctctcgtatgctcactcaccgctttaatccagtgcggaaaactcactgtg
caaccttatccacggcaggacttgccttcagccttgagcgaatcataattaagattagag
ttggaatgtaaacgagatttctctc-----------------cgcggcccccgctcgact
atagacccttggaggccacaaggcttgttgggtcaacgtcccagcaattgccttgcgttc
ttgtttcccggg---------------
>SEQ4
gctgtttctcgggacgatgctagatatcggaccgctgatacacaaaggcagcagtcaggg
cgggg-----------------------ctagcttgcggcgggatagccagggcggggtg
gcatacggagcggaccgacaaaatccttctgtagcgcctacctcttctttagcaggtacc
tttgacatatttg---taccattcacacagcgggtaacggagataaaaacaaacgcgagc
gcttagtttagtcgttcgtctactaacgaaacctcactggtgtgaattcagagcacgtac
--------------------------------tagggaaacgcacactcccgccaatatc
cacgtctctcgatccgatgaccctaat------------attcattagtgcgcttagagg
ttttt---------------------------atcatgggtcccgaggccggctaagag-
--------------------cgagaaaccgcttagggttcgtggcgatccgtgagcccgt
tattggaatcgttattattggaaatcgaagcgttaatataggcactcatagtgacgggtg
-tttggatttacctagcaagccacaatgtacgcaccg---gatgaa-------------g
atg------------------------------------acctcggaaacagggcttcca
tta-tta----------------------ctcttaggaatgcaaagctcta-----tggg
gacgactgctgctctaatataactctagctatatatctgggcttacattattcgaacact
aatacatgatctctcgtatgctcactcaccgctttaatccagtgcggaaaactcactgtg
caaccttatccacggcagca-------------------agttcataattaagattagag
ttggaatttacacgagatttctctc-----------------cgcggcccccgctcgact
atatactcttggaggccgcaaggcttgttggttcaacgtccccgcaagtgccttgcgttc
ttggttctcggg---------------
>SEQ5
actgattcaaggtacaatgctaga---------------------------------gag
cggagaccagtaccctga--------------------gcgggatagccaacgcagggtg
gcat----------------aaatatttccgttgcgcgtaccgcttctttcg--------
----------------caacattcacacaccgggtaacggagataaaaacaaacgcgagc
gcttagtttagtcgttcgtctactaacgaaacctcactggtatgaattcagagcacctac
--------------------------------agtggaaacgcagacccctgcccatatc
aacgtctctcgatccgaggaccctaat------------attctttagcgcggttagagg
ttgtt---------------------------atcatggctcccgaggccggctaagag-
--------------------cgagaaaccgcttagggttcgtggcgatccgtgagcccgt
tattggaatcgttattattggaaatcgaagcgttaatatagccactcatagtgactggtg
-ttgggatttacctagcatgtcccaatggaaggaacgactgccgaagattgcaacaag-g
ctgcaactaacgccaggtctgcgt---------------accttagaaataaggtctcca
ctcttttattaatgggtttaggccatgatctgttcgggatacacagctttt-----tgag
tacgagtactgctcaaatatgactctagctatatatctgggcttacattattcgaacact
aatacatgatttctcgtatgcttactcaccgctttaatccagtgcggaaaactcactgtg
caaccttatccagagcaggagttgcctacagccttgagcgaatcttaattaaaattaaag
ttggaaggtcaacgagatttctcccatgtgaaacaga--------------------gct
aaagacgcgtggagaccacatgacttcttggctca-------------------------
-----tcccggggaccaccacaagtga
>SEQ6
ggtgattctag-----------------------cttctacacaaagactgccgt-----
------------------------------------------------------------
-------------------------------tcgcgattgccgcttctttcg--------
----------------caacattcacacagcgggtaacggagataaaaacaatcgcgagc
gcttagtttagtcgttcgtctactaacgaaacctcactggtatgaattcagagcacgtac
taactatatcgtaaggatagcccgtggcatcaacgaggagcga-----------------
----------------------------------tactcgtccacaaacgcatttagagg
ctgttaaccgacagtagccatcaagttcaaaaactatggctcccggggcatgctaacagg
tttctgcggcaaggctctggcgagaaaccgcttagggttcgtggcgatccgtgagcccgt
tattggaatcgttattaatggaaatcaaagcgttaatataggcactcatagtgactggtg
-atggaatttacctagcaagccacaatgtacggaacggatgacgaggtttgcgataag-g
ctgcaactaactcccggtcagcgtaaatttttcgtctcaccctcagaaataaggtttcca
ttgtttca---------------------ctcttaggaatgcaaagct------------
------------tctaatatcactctagctatatatctgggcttacattattcgaacact
aatacatgatctctcgtatgctcactcaccgctttaatccagtgcggaaaactcactgtg
caaccttatccacggtagca-------------------agctcataattaagatcagag
ttggaatttacaacagatttctctc-----------------cgcggcccccgctcgact
atatactctttgtgggcgcaaggcttgttggttcaacgtccccgcaagtcatttgcgttc
ttggttctccgg---------------
>SEQ7
gctgtttctcgggacgatgatagatatcggacagctgctacacaaaggcagcagtcaggg
cgggg-----------------------cgagcttgcggcgggatagccagggcggggtg
gcatcccgtgcggaccgacaaaatccttctgtagcgcctacctctcccttag--------
----------ttg---taccattcacacagcgggtaacggagataaaaacaatcgcgagc
gcttagtttagtcgttcgtctactaacgaaacctcactggtatgaattcagagcacgtac
--------------------------------aagg------------------------
---gtctctcgaaccgatgaccctaat------------attcactattgcggttagagg
ttggt---------------------------atcatgactcgcgaggccggctaagag-
--------------------ccagaaaccgcttagggttcgtggcgatccgtgagcccgt
tattggaatcgttattattggaaaccgaagcgttaatataggcactcacagtgactggtg
-tggcgatttgcctagaaagccacaatggactgaacgg-cgacaag-------------g
gtgcaactaactccc----------------ggtctgcaaccttagaaacaaggtcccca
gtc-ttt----------------------tattaatgggtttaggccatgatctgttcgg
gacgagtactgctctaatattactctagctatatatctgggcttacattattcgaacact
aatacatgatctctcgtacgctcactcaccgctttaatccagtgcggaaaactcactgtg
caaccttacccacggtagca-------------------agctcaaaattaagatcaaag
ttggaatttacaaaagctttctctc-----------------agcggcccccgctgaa--
------------------caaggcttgttggttcaacg----------------------
-tggttctccgg---------------
>SEQ8
ggtgattctag-----------------------c-------------------------
------------------------------------------------------------
-------------------------------------tcgccgcttctttcg--------
----------------ctacattcacagagcgggtaacggagataaaaacaatcgcgagc
gcttagtttagtcgttcgtctactaacgaaacctcactggtatgaattcagagcacgtac
aaactatatcttaaggatagcccgtgg---------------------------------
----------------------------------tactcgtccacacacgcatttcgagg
ctgttaacctacagtcgccatcaaggtcaaaaactatgactcccggggcatgctaacagg
ttcctgcggcaaggctattgcgagaaaccgcctagggttcgtggcgatccgtgagcccgt
tattggaatcgttattaatggaaatcaaagcgttaatataggcactcatagtgactggt-
-------------------------------------gatgacgaggtttgcgataag-g
ctgcaactaagtccc----------------tcgtctccccgtttgaaataaggtttata
ttgtttca---------------------ctcttaggaatgcaaag--------------
------------------------ctagctatatatctgggcttacattattcgaacact
aatacatgatctctcgtatgctcgctcaccgctttaatccagtgcggaagactcactgtg
caaccttacccacggtagca-------------------agctcaaaattaaggtcagag
ttggaatttacaaaagctttctctc-----------------agcggaccccgct-----
---------------gaacaaggcttgttggttcaacg----------------------
-tggctctccga---------------
>SEQ9
actgattcaaggtacaatgcgaga------------------------------------
-----------------------------------gaggcgggataaccaacgcagggtg
gcatac--------------------------------tactgcttctgtcg--------
----------------caaaattcacacagcgggtaacggagataaaaacaaacgcgagc
gcttagtttagtcgttcgtctactaacgaaacctcactggtatgaattcagagcacgtac
taatgatatcctaatgagagcccgtggtatcaacgaggagcgaagacccttgc-------
--------tcgaaactatgaccctaatgtatttcacctcgttgataatcgcatttagagg
ttgttaaccgacagaagccatcaattccaaaaaccgtggctccccaggcaggctatcagg
gttctccggcgaggctctcacgagaaaccgcttagggttcgtggcgatccgtgagcccgt
tattggaatcgttattattggaaatcgaagcgttaatataggcactcatagtgacgggtg
-tttggatttacctacgaagacacaatgtacgcaccggctg-------------------
---------------------------------------acctcggaaacagagcttcca
ttatta-----------------------ctcttaggaatgctaagctcta-----tggg
gacgattgctgctctaatataactctagctatatatctgggcttaccttattcgagcact
aatacatgatatctcgtatgctcactcaccgctttactccagtgcggaaaactcactgtg
caaccttctccacggtagca-----------------------aataattaaggtcagag
ttggaatttacgacagagttttctc-----------------cgcggcccaagctcgacc
atacactctttgtgggcgcaaggcttgttggtacaacgtcgccgcaagtcatttgcgttt
ttggttctccgg---------------
>SEQ10
actgattcaaggtacaatgctaga---------------------------------gag
cggagaccagtaccctga--------------------gcgggattgccagcgcagggtg
gcat----------------aaacatttccgttgcgcgtaccgcttatttgg--------
----------------caacattcacacaccgggtaacggagataaaaacaaacgcgagc
gcttagtttagtcgttcgtctactaacgaaacctcactggtatgaattcagagcacctac
taactatatcgtagggatagcacgtggcatcaacgaggagcgaagaccgttgc-------
--------------------------tgtaattctactcgatcacaagtgcattcagagg
ctgttaaccgtcag----------------------tggctcccgaggcatgctaacagg
tttctccggcgaggctctgacgagaaaccgcttaggtttcgtggcgatccgtgagcccgt
tattggaatcgttattaatgcaaatcgaagcgttaatataggcactcatagtgactggtg
-ttgggatttacctagcatgtcccaatggaaggaacgactgcctaagattgcaacaag-c
ctgcaactaacgccaggtccgcgt---------------accttagaaataaggtgtcca
ctctgtaattaatgggtttaggccatgatctgttcgggatacactgcttgt-----tgaa
tacgagttctgctcacctatgactctagctatatatctgggcttacattattcgaacact
aagacatgatttctcgtatgcttactcaccgctttaatccagtgcggaaaacgcactgtg
caaccttatccagagcaggacttggcaccagcattacgcgaatctaatttaagattaaag
ctccaatctaaacgagagtt----------------------------------------
------------------------tggttgggtcaacgtcccagcaatagcttcgggttc
ttatttccagggggccatcacacgtta
>SEQ11
actgattttagggaccatg------------------------aaagacagcagacagag
cggagaccaggaccctgact------------------gcgggatagccagggcggggtg
gcat----------------ag---------tagcgcgtaccgc----------------
----------------caacattcacacagcgggtaacggagataaaaacaaacgcgagc
gcttagtttagttgttcgtctactaacgaaacctcactggtatgaattcagagcacgtac
--------------------------------agtggaagcgcagacccctgcccatatc
gacgactcacgatccgaggaccctaat------------attcttcagcgcggttagagg
gttgt---------------------------atcatggctcccgaggccggctatgag-
--------------------cgagaaaccgcttagggttcgtggcgatccgtgagcccgt
tattggaatcgttattattggaaatcgaagcgttaatatagccactcatagtgactggtg
-ttgggatgtacctagcaagt--------------------acgaagtttgtgccaag-g
ctgcaagtaactgctcgtcagcaaaaatttgtcttctcaaccttagaaaaaatttctgca
ttccactattaatgggattaggacatgatctgttcggaatgcaaaggtttt-----tgag
tacgagtactgctctaatatgactctagctatatatctgggcttacattattcgaacact
aatacatgatctctcgtatgctcactcaccgctttaatccagtgcggaaaactcactgtg
caaccttacccacggtagca-------------------agctcggaattaaggtcagag
ttggaatttacaaaagctttctctc-----------------agcggaacccgcagaa--
------------------caaggcttgttggttcaacg----------------------
-tggctctccga---------------
>SEQ12
actgattc-----aacgtg------------------------gaatgc-----------
tggagaccagtaccctgg--------------------gcgggaaatccaacgcatggtg
gcat----------------aaaggtttgctttgcgtgtaccgcttctttcg--------
----------------caacattcacacagcgggtaacggagataaaaacacacgcgagc
gcttagtttagtcgttcgtctactaacgaaacctcactggtatgaattcagagcacctac
--------------------------------aa--------------------------
------tctcgaaccgag------------------------------------------
----t---------------------------gacatgactcgcgaggacggctaagag-
--------------------cgagaaaccgcctagggttcgtggcgatccgtgagcccgt
tattggaatcgttattaatggaaatcaaagcgttaatataggcactcatagtgactggtg
-atgggatttacctaggaagccacaat--------------gtgaagct-----------
----------------------------------------------aaacatggtttcca
ttattata---------------------cttttaggaatgcaaatctcta-----tgag
gacgactactgctctaatataactctagctatatatctgggcttacattattcgaacact
aagacatgatttctcgtatgcttactcaccgctttaatccagtgcggaaaacgcactgtg
caaccttacccacggtagca-------------------agctcggaaataaggtcagag
ttggaatttacaaaagctttctccc-----------------agcggaacccgcagaa--
------------------aaaggcttgttgg------a----------------------
-tggctctccga---------------
>SEQ13
actgattcaaggtacaatgctagt---------------------------------gag
cacagaccagcaccctga--------------------tcggtattgccagcgcagggtg
gcgt----------------aaacatttccgtggggcgtaccgcttatttgg--------
----------------caacattcacacagcgggtaacggagataaaaacaaacgcgagc
gcttagtttagttgttcgtctactaacgaaacct--------tgaattcagagcacgtac
--------------------------------aagggaaacgcctaat------------
---------------------------------------attcattagtgcggttagagg
ttgtt---------------------------atcatggctcccgaggccggctaagtg-
--------------------cgagaaaccgcctagggttcgtggcgacccgtgagcccgt
tattggaatcgttattaatggaaatcaaagcgttaatataggcactcatagtgactggtg
-tggcgattttcctagaaagccaaaatggactgaacggcgacaag--------------g
gttcaactaactccc----------------ggtctgcaaccttagaaacaaggactcca
gtcagttgttgatgggtttatgccgtgctctgt-----------------------gcgg
gacgtgtactgctctaatattactctagctatatatctgggcttaccttattcgaacact
aatacatgatctctcgtatgctcactcaccgctttactccagtgcggaaaactcactctg
caaccttctccacggtacca-----------------------aataaaaaaagtcaggg
ttggaatttccgacagatttttctc-----------------cgcgtcccaagctcgacc
atagactctttgtgggcgccaggcttgttcgtacaa------------------gcgttt
ttggttctccgg---------------
>SEQ14
acagattctagggaccatgctagatatcagtccgcttcttcacaaaggaccctgtttggg
ca----------------------------------------------------------
--------------------------------tacgcgtaccacttc-------------
----------------caacattcacacagcgggtaacggagataaaaacaaacgcgagc
gcttagtttagttgttcgtctactaacgaaacctcactggtatgaattcagagcacgtac
taatt---------------------gcatcaacgaggagcgaaggccgttgc-------
--------------------------tgtattttaactcgttcgcaagcgcatgtagagg
ctcttaacagacagtagccatcaagttcaaaaactatggctcccgaggcatgctaccagg
tttctcctacgaggctctgacgagaaaccgcctagggttcgtggcgacccgtgagcccgt
tattggaatcgttattaatggaaatcaaagcattaatataggcactcatagtgactggtg
-a----------------------aacgttcgcaccggatgaaga---------------
-------------------------------------taaccttatta------------
-----------------------------ctcttaagaatgccaagctctc-----tggg
gacgactgctgctctaatataactctagctatatatctgggcttacattattcgaacact
aatacatgatctctcgtatgctcactcaccgctttaatccagtgcggaaaactcactgtg
caaccttctccacgttacca-----------------------aataaaaaaagtcaagg
ttggaatttccgacagatttgtcta-----------------------------------
-----gtctttgtgggcgccaggcttgttcctacaa------------------gcgttt
ttggttctccgg---------------
>SEQ15
cgtgattctag-----------------------cttctacacaaagactgccgc-----
------------------------------------------------------------
-------------------------------tcgcgattcccgcttctttcg--------
----------------caacattcacacagcgggtaacggagataaaaacaaacgcgagc
gcttagtttagtcgttcgtctactaacgaaacctcactggtatgaattcagagcacctac
tacctataccgtacggatagaacgtggcatcaacgaggaggga-----------------
----------------------------------tcctcgtccagaaaagcatttagagg
ctgttaaccgacagtagccatcaagttcaaaaactatgactcccggggcatgctaacagg
tttctgcggtaaggctctagcgagaaaccgcttagggttcgtggcgatccgtgagcccgt
tattggaatcgttattattggaaatcgaagcgttaatataggcactcatagtgactggt-
-------------------------------------gatgacgaggtttgagataag-g
ctgcacctaagtcac----------------gcgtctctccgtgagaaataaggtttata
ttgtttca---------------------ctcttaggaatgcagag--------------
--------------------------agctatatatctgggcttacattattcgaacact
aatacatgatctctcgtatgctcactcaccgctttaatccagtgcggaaaactcactgtg
caaccttatccacggcaggacttgccttcagccatgagcgaatcataattaagattagcg
ttggcatgtgaacgagatttctgcc-----------------------------------
---------------ccgcatggttttttgggtcaacgtcccagcaatagccttgcgttc
ttgtttcccggc---------------
>SEQ16
actaattttagagaccatg------------------------aaagacagcagacagag
cggagacccggacccttcct------------------gcgggatagccagggcg-----
---------------------g---------tagcgcgtaccgc----------------
----------------caacatccacacagcgggtaacgcagataaaaacaatcgcgagc
gcttagtttagtcgttcgtctactaacgaaacctcactggtatgaattcagagcacgtac
--------------------------------aagggaaacgcagacccctgcccatatc
atcgtctctcgatccgaagaccctaac------------actcgttagtgcggttagagg
ttctt---------------------------atcatggctcccgaggccggcagggag-
--------------------cgagaaaccgcttagggttcgtggcgatccgtgagcccgt
tattggaatcgttattattggaaatcgaagcgttaatctaggcactcatagtgactggtg
-ttgggatttacctagcctgtcccaatggaaggaacgactgccgaagtttgcagcaag-g
ctgcaactaac------------------------gccagtcttagaaataaggtctcca
ctcctctgttaatgggtttaggccatgatctgttcggg----------------------
-------actgctcaaatatgactc--gctatatatctgggcttacattattcgaacact
aatacatgatgtctcgtatgcttactcaccgctttaatccagtgcggaaaactcactgtg
caaccttacccacggtagca-------------------agctcaaaattaaggtaagag
ttgggattaacaatagctttctgtc-----------------agcggaccccgctgta--
------------------caaggcttgttgattcaacg----------------------
-tggctctcct----------------
>SEQ17
gctgtttctcgggatgatgctagatatcggaccgcggatacacaaaggcagcagtcagg-
-gagg-----------------------ctagcttgcggcgggatagccagtgcggcgtg
gtatacggagcggaccgacacaatccttctctagcgccaatctcttcttgagcaggtacc
tttgacctttttg---taccattcacacagcgggtaacggagataaaaacaatcgcgagc
gcttagtttagtcgttcgtctactaacgaaacctcactggtatgaattcagagcacgtac
--------------------------------aa--------------------------
----------------------cttat------------actccttaatgcggttagaag
ttgtt---------------------------atcaaggctcccgaggtccgctaagtg-
--------------------cgagaaaccgcttagggttcgtggcgatcggtgagcccgt
tattggaatcgttattattggaaatcgaagcgttaatataggcactcatagtgacgggtg
-ttggcagtcaccttgcaagccacaatgtacggaacggttgacgagttttgcggtagccg
gtccgagtaaatttg----------------tcgtctcaacctcagaaataagatttccg
ttctttt----------------------ctcttaggattgcaaagctcta-----tgag
gacgacaactgctc-------------gctatatatctgggcttacattattcgaacact
aatacaagatctctcgtatgctcactcaccgctttaatccagtgcggaaaagtcactgtg
caaccttacccccggtagca-------------------aggtcaaaattaagatcaaag
tccgaatattcaaaagctttctctc-----------------agcgccccccgctgaa--
------------------caaggcttgtgggttcaacg----------------------
-tcgttctcccg---------------
>SEQ18
actgcttgaaggtacactgctaga---------------------------------gaa
cggaaaccag-----------------------------cgggattgccagcgc------
---------------------cacatttccgttgcgcgtaccgcttatttgg--------
----------------catcattcacacaccgggtaacggagataaaaacaaacgcgagc
gcttagtttagtcgttcgtctactaacgaaacctcactggtatgaattcagagcacctac
--------------------------------aa--------------------------
----------------------------------------------------gctcgaac
cgagt---------------------------gacaggactcgcgaggacggctaagat-
--------------------cgacaaaccgcttagggttcgtggcgatccgtgagcccgt
tattggaatcgttattattggaaatcgaagcgttaatataggcactcatagtgactggtg
atgacgaggttc-------------------------gagaaaag--------------g
ctgcacctaagtcac----------------gcgtctctccgtgagaaataagg------
------------------------------------------------------------
------------tttataatgcttcaagctatatatctgggcttacattattcgaacact
aatacatgatctctcgtatgctcactcaccgctttaatccagtgcggaaaacccactgtg
caaccttctccacggtacca-----------------------aagaagaaaagtcaggg
ttggcattgccgacaaattttt-------------------------------------c
atagactctttgtgggcgccaggctttttcgtacaa------------------gcgttt
atggttctacgg---------------
>SEQ19
ggtgatcctag-----------------------cttctacaccaagac-----------
------------------------------------------------------------
--------------------------------tgcccctgccgcttctttcg--------
-------------------cattcacacagcgggtaacggagataaaaacaaacgcgagc
gcttagtttagtcgttcgtctactaacgaaacctcaatggtgtgaattcagagcacgtac
caatgatatcgtaatgacatcccgtggtatcaacgaggagcgaagacccttgc-------
--------tcgaaactttgaccctaatgaatttcacctcgttgataatcgcattcagagg
ttgttaactgacagaagccatcgtttccaaaaaccttggctccccaggcaggctatcagg
tttctccggcgaggctctcacgagaaaccgcttagggttcgtggcgatccgtgagcccgt
tattggaatcgttattattggaaatcgaagcgttaatatagccactcatagtgactggtg
-ttgggatagacctagcatgtcccaatggaaggcacgactgccgaaaatctcaacaag-g
ctgt-----------------------------------accttagaaataaggtctcca
ctcttttattaatgggtttaggccattaaccgttcgggatacacagctttt-----tcag
tacgagtactgctcaaatatgac----gctatatatctgggcttacattattcgaacact
aagacatgatttctcgtatgcttactcaccgctttaatccagtgcggaaaacgcactgtg
caaccttacccacggtagca-------------------agctcaaaattaatatcaaat
ttgtattttacaaaagctttcactc-----------------agcggcccccgatgaa--
------------------caaggcttgttggttcaacgtccag-----------------
---------------------------
