>SEQ0
ctaataaaacaagcgtctggatttggagagagagtgcaatgtccgataggggagaagacg
atccgctgaggtgtcagacatgggcagtggtcgagctcggccattgtggcttaattacct
gcagtaatctttgaacacgagagagatattcggggtgtacctgacacactgataaatgtt
tggaaccttgtttactggcttggggactttccggctggcttatttgataccgatataccc
ttgttatgggcctcaagggaggaaaaattcggcttcttcccactacttgcacaccaaaag
caatcgacaatgcttagacgctgttcttatattaagctgctatgatgatacttgatcacc
cctcgcgcctcatctgatttataactcccgtggagcggagttatccacgacagccccata
tccggatggtagaggtccctgtcggatacccttggagtgtaacagttgaacatttctgaa
gataacgtcggcaaggacggcaagtggataggttgcacccaggcacagttgaagtcaatc
cttattaatcgcttaagggcgctacggtagcagataggatccttgtatgccacaaatttg
acttactatccctagattttacgcgtacatgtcaaggatgtctcgctgcgatcctttgct
aaggggatggtccctttctttgatgtagtatctatatataatttcaacggacgatgtaac
tttggaacccggttcttaacacgattacgtgaaacgtagtccgcgaatccccgcaccagg
tttatattgtccactcttcggcaggcggatacatgttatgtgccaaaaagctcccatcac
tagcgtgctcgcaccaggagtgtccctctaacgcgacgaaaaaacaaattgttagctgtc
acgccatgggtcttttgacatacagtcgacggcactaatgttgccggtaagaggtctgca
gtagcaatatttaagatcctgtttttcgtgtcccccactctgtagttgctctgaaatcaa
caactgagtgaatatttacccattacaagggcctcgctttgccgctgggtctgtgtagga
ggcggcatcttgtctcgcgc
>SEQ1
ctaatgaaacaagcttatggattgtgagagagagtgcaacgtccgataggggagaagacg
atccgctgaggtgtcagacatggccagtggtcgatctctaccattgtgggctaattacct
gctgtaatctttgaacacgagacagatattcggggtgtacctgacacactggtaaatgtt
tggaaccttgtttagcggcttggggactttccggctggcttatttgataccgatataccc
ttgttatgggcctcaagggaggaaaaattcggcttgttcccactacttgcacaccaaaag
caatcgacaatgcttagaggctgttcttatattaagctgttacgatgatacttgatcacc
cctcgcgcctcacctgatttaaaactcccgtggagcggagttatccccggcagccccata
tccggatggtagaggtccctgtaggataccattgcagtctaacagttgatcatttctgaa
gataacgtcggcaaggacggcaagtggataggttgcacccaggcacagttgaagtcaatc
cttattaatcgcttaagggcgctacggtagcagataggatccttgtatgccacaaatttg
acttactatccctagattttacgcgtacatgtgaaggat---------------------
--ggggatggtccctctctttaatgtattagctatatataatttaaacggatgttgtaac
tttcgaacccggttataaacacgatgaggtgatacgtagtccgggaatgcccgcaccagg
ttcaaattgtccactcttcggcaggcggatacatgttatgtgccaaaaagctcccatcac
taacgtgctcgcaccaggagtgtccctctaacgcgacgaaaaaacaaattgttagcggtc
acgccatgggtcttttgacttacactcgacggcactaatgtt------------------
---ggaatatttaagatcct--------------------tgtagttgctctgcagtcaa
caactgatggaatctttacccattacaagggcgtcgctttgccgctggg-----------
-------tcttgtctcgc--
>SEQ2
ctaatgagacaagcttaaggcttgtgagggagtgtgcaacttccgaaagggaagaagacg
agccggagaggtgtcagacatggccagtggtcgatctctacaggtgttggctattcacct
gctgtaatctttgaacacgagagagagaatcgcg--------------------------
-ggcactttgtttagcgccttggggactttccggctggcttatttgataccgatataccc
ttgttatgggcctcaagggaggaaaaattcggcttgttcccactacttgcagaccaaaag
caatcgacaatgcttagaaggtgttcttatattaagctgctatgatgatacttgatcacc
cct------------------------ccgtggagcggaggtatgcccgacagctccata
tccggatggtagagcttcctgtcggatacactgggagtgtaacagttgtacatt------
------------aagaacggcaagtggataggttgcacccaggcacagttgaagtcaatc
cttattaatcgcttaagggcgctacggtagcagataggatccttgtatgccacaaatttg
acttactatccctagactttacgcgtacatgtgaggggg---------------------
--ggcgatggtccatctctttaatgtattagctgtatatcatttttacggacgttgtatc
tttcgaacccgattataaacacgatgaggtgatacgtagt--------------------
-tcaaattgttcac------gcaggcggatacatgttatgtgccaaaaagctcccatcac
taacgtgctcgcaccaggagtgtccctctaacgcgacgaaaaaacaaattgttagcggtc
tcgccatgggtcttttgacctacagtcgacggcacttatgttgccggtaagcggtctgca
ctagcaatacttaagatcctgtttttcgtttgccccactctgtagttgcactgagctcaa
caactgagtcaatatttacccaatataagggcctcgttttgccgctgggtctgtgtagga
ggcggaatcgtgtctcgagg
>SEQ3
ctaatgagacaagct------------------------------------gcgaagacg
agccggagtggtgtcaga------------------tctacaggtgttggctattcacct
gctgtaatgtttgaacacgagagagagaatcgag--------------------------
-gtcactttgtttaatcccgtggggactttccggctggcttatttgataccgatataccc
ttgttatgggcctcaagggaggaaaaattcggcttgttcccactacttgcacaccaaaag
caatcgacacagctt-------------------------tatgttgttatttgatcac-
---------------------------ccgtggagcggaggtatgcccgacagctccatc
tccggatggtagagcttcctgtcggatacactgggagagtaacaattgaacatt------
------------aagcagggcaagtggataggttgcacacaggcacagttgaagtctatc
cttattaatcgcttaagggcgctacggtagcagataggatccttgtatgccacaaatttg
cctgactatccctagattttacccgtacatgtcacggct---------------------
--ggggatggtccctctctttaatgtattagctatatataatttaaacgaatgttgtaac
tttcgaacccggttgtaaacacgatgaggggatatgtagtccgggaatgcccgcaa----
----------ccactcttcggcaggcggatacatgttatgtgccaaaaagctcccatcac
taacgtgctcgcaccaggagtgtccctctaacgcgacgaaaaaacaaattgttagcggtc
aggccatgagtcttttgacttacactcgacggtactaaagttgcc---------------
---------------------------------------ttgtagtttctctgcagtc--
------------------------acaagggcgtcgcttcgccgctgggtct--------
--------------------
>SEQ4
ctagtgaaacacgtttctggattgtgagataaagtgcaacgtccgataggggaggagacg
atccgctgaggtgtcagacatggccagtgttccttctctaccagtgtggg----------
---gcaatcgttgaacacgagacagatattcggagtgtacctgacatactggtaaatgtt
tggtcccttgtttaggggcttggggactttccggctggcttatttgataccgatataccc
ttgttatgggcctcaagggaggaaaaattcggcttgttcccactacttgcagaccaaaag
caatccacaatgcttagaaggtgttcttatatgaagctgctatgatgatactttatcacc
cct------------------------ccttggagcggagctatgcccgacagctccata
tccggatggtagagcttcctgtcggatacactgggagt----------------------
----------gggagaacggcaagtggataggttgcacacaggcacagttgaagtctatc
cttattaatcgcttaagggcgctacggtagcagataggatccttgtatgccacaaatttg
tcttactatccctagattttacgcgttcatgtcagggatgtctcgctgcgatcctttgct
aaggggatggtcccttactttgatgtagaatctatgtataatttcaaaagacgctgtaac
tatggaacccggttcttaacacgattacgtgaaacgtagtccttgaatccgcgcaccagg
gttttattgtccactcttcggcaggcggatacatgttatgtgccaaaaagctcccatcac
taacgtgctcgcaccaggagtgtccctctaacgcgacgaaaaaacaaattgttagcggtc
tcgccatgggtctcttgacctacagtcgacagcacttatgtcgccggtaagcggtctgcg
ctagcaatacttatgacctagtttttcgattgccccactctgttcttgcacagatctcag
caactgagtcaatagttccccactataagggcctcgttatgccgctgagtcagtatacga
g-------------------
>SEQ5
ctaatgag---------------------------------------------------t
gcccggagtggtgccaga------------------tctacaggtgttg-----------
------------------------------------------------------------
-gtcactttgtttgatctcgtggggactttccggctggcttatttgataccgatataccc
ttgttatgggcctcaagggaggaaaaattcggcttcttcccactacttgcacaccaaaag
caatcgacacagctt-------------------------tatcttgtaatttgatcac-
---------------------------ccgtggggcggaggtatggccgacagctccatc
cccggatggaagagcatcctgtcggat-------------------tgcacatt------
------------aagtagggcaagtggataggttgcacacaggcacagttgaagtctatc
cttattaatcgcttaagggcgctacggtagcagataggatccttgtatgccacaaatttg
atttactatccctagactttacgcgtacatgtgaggggg---------------------
--------------------------attagctgtatatcatttttacggacgttgtatc
attcgaaccccattataaagacgatgaggtg---------------------------cg
ttccaatggttcac------gcaggcggatacatgttatgtgccaaaaagctcccatcac
taacgtgctcgcaccaggagtgtccctctaacgcgacgaaaaaacaaattgttagcggtc
acgccatgggtcttttgacttagactcgacggcactaatgtc------------------
---ggaatatttaagttgct--------------------tgtagttgctctgcagtgaa
caactgatggaatctttaccaattacatgggcgtcgtattgccgctgggtct--------
----------tgtctcgc--
>SEQ6
ataatgagacaagcttaaggctggtgagggagtgtgcaacttccgaaagggaagaagccg
agccggaaaggtgtcagtcatggccagtggtcgatctccacaggtgttggctattcacct
gccgaaatgtttgaacacgatagagag---------------------------------
-tgcaatttgtttaattcgttggggactttccggctggcttatttgataccgatataccc
ttgttatgggcctcaagggaggaaaaattcggcttcttcccactacttgcacaccaaaag
caatcgacac------------------------------tactttgtaattttatctc-
---------------------------ccgtggggcggaggtatggccgacagctccacc
cccggatggaagagcatcctgccggat-------------------tgcacatt------
--------------------caagtggataggttgcacccaggcaccgttgaagtcaatc
cttattaattgcttaagggcgctacggtagcagataggatcgttgtatgccacaaatttg
tcttactatccctagattttacgggttcatggaagggaagtctcgctgcgatcctttgct
aagtgcatggtcccttactttgatgtcgaatctatgaataatttcaaaaggcgctgaaac
tatgtaacccggttccttacacgattacgtgtaacgtagtccttgaatccgcgcaccagg
gttttattgtctactcttctgcaggcggatacatgttatgtgccaaaaagctcccatcac
taacgtgctcgcaccaggagtgtccctctaacgcgaccaaaaaacaaattgttagcggtc
tcgccatgggtctcttgacctacagtcgacagcacttatgccgccggtaagcggtctgcg
ctaggaatacatatgacctactttttcgcttgcccca---------------gatctcag
caactgagtcaatagttccccactataaggggcgctttatcccgg---------------
--------------------
>SEQ7
ctaataaaacaaggatctggcgttgcagagagagagaaatgtccgataggggagaagccg
atccgctgaggtgtcagtcatcggcagaggtcgagcccg---------------------
---gtaatcttagtacacgagagtgatattcggggtgtacctgacacggtcataaatgtt
tggaaccttgtttactggcttggggactttccggctggcttatttgataccgatataccc
ttgttatgggcctcaagggaggaaaaattcggcttcttcccactacttgcacaccaaaag
aaatccgcacagctt-------------------------tatgttgttatttgatcac-
---------------------------ccgtgtagcggaggtatgcccgacatctccatc
tccggatggtatagcttcctgtcggatacactgggagagtaacaattgaacatt------
------------aagcacggcaactggataggttgcacccaggcacagttgaagtcaatc
cttattaatcgcttaagggcgctacggtagcagataggatccttgtatgccacaaattgg
aattactatccttagatcttacgcgtacatttaaggggg---------------------
--------------------------attagttgtacatgattt----------tgtatg
attcgaaccccattataaagaccatgaggtg-----------------------------
--tcaatggttcac------gcaggcggatacatgttatgtgccaaaaatttcccatcac
taacgtgctcgcaccaggagtgtccctctaacgcgacgaaaaaagaaattgtaagcggtc
acgccatggggcttttgacttacacccgacggcacgattgtt------------------
---ggaatatttaagtacct--------------------tgtagttgct----------
---------------ttacccagtacaagggcgtctctgtctcgc---------------
--------------------
>SEQ8
ctaatgag---------------------------------------------------t
gcccggagtggtgccaga------------------cctacaggtgttg-----------
------------------------------------------------------------
-gtcactttgtttgatctcgtggggacttaccggctggcttatttgataccgatataccc
ttgttatgggcctcaagggaggaaaaattcggcttcttcccactacttgcacaccaaaag
caaccgacaatgcgtagacgctgttcttatattaagctcctatgatgatgctcgagcacc
cctcgcgcctcatctgattgataactcccgtggagcggagttatccacgacagcctcata
tctggatggtagaggtccttatcggataccctttgaat----------------------
------------ggatcctgcaagtggatcggttgcacccaggcaccgttgaagtcaatc
cttattaattgcttaagggcgctacggtagcagataggatcgttgtatgccacaaatttg
cccgactatccctagattttacccgcacttgtcacggct---------------------
--ggggatggtccctctctctaatgtagtagctatatattgcttaaacgaatgttgtaac
tttcgcacccggtggtaaacacgatgaggggctatgtagtccgggactgcccgcaa----
----------ccactctttggcaggcggatacatgttatgtgccaaaaagctcccatcac
taacgtgctcgcaccaggagtgtccctctaacgcgacgaaaaaacaaattgttagcggtc
-----------------acttacactcgccggcactaatgtt------------------
---ggaatatttaagat-----------------------tgtagatgctctgcagtgaa
caacag------------------ataggggcgtcgctttgccgcggggtct--------
----------tgtctcgc--
>SEQ9
ctaataaaacaaggatctggcgttgcagagagagagaaatgtccgataggggagaaaccg
ttccgctgacttgtaagtcatcggcagaggtcgagcccg---------------------
---gtaatcttagtacacgacaatgatattcggggtgtacctgacacggtcttaaatgat
tggaaccttgtctactggcttggggactttccggctggcttatttgataccgatataccc
ttgttatgggcctcaagggaggaaaaattcggcttgttccgactacttgcagaccaaaag
aaatccgcacagc------------------------------------atttgataac-
-------------------------------------------tgcccaacagctccatc
tccggatggtatagcttcctgtcggatacactgggagagtaacaattgaacact------
------------aaccacggcaagtggataggttgcacacagccacagttgaagtctatc
cttattaatcgcttaagggcgctacggtagcagataggatccttgtatgccacaaatttg
acttactatccctagatttcatgcgtacatgtcaaggctgtctccctgcgatcctttgct
aaggggctgatccctttcattgatgtagtatctatatatgatttcaacggatgatgtaaa
tttagaatc-------------------gtgaaacgtagtccgcgaatctccgcacccgg
tttatattgtccactcttgggcaggcggatacatgttatgtgccaaaaatttcccatcac
taacgtgctcgcaccaggagtgtccctctaacgcgacgaaaaaagaaattgtaagcggtc
tcgccatgggtcttttgacctacagtcgacggcacttatgttgccggtaagcggtctgca
ctagcgatacttaggatcctgtttttcgtttgccccactctgtagttgca----------
---------------tgacccaatttaagggccgcgttttaccgctgggtctgtgtaggt
ggcggcatcatgtctcgagg
>SEQ10
ctaatgag----------------------------------------------------
--ccggagtgctgccaga------------------cctacaggtcttg-----------
------------------------------------------------------------
-gtcactttgtttgatctcttggggattttccggctgacttatttgataccgatataccc
ttgttatgggcctcaagggaggaaaaattcggcttgttccgactacttgcagaccaaaag
ctatcgacaatgcttacacgctgttcttatcttcagctgctatgatgatatttgaacacc
cctcgcccctcatctgatttataactcccgtggagcggacttcttcagcacacccccata
tccggatgttag--------------------------gtaacagttgaacatttctgaa
ggtaacgtcgacatggacgccaagtggataggttgcacccaggcacagttgaagtcaatc
cttattcatcgcttaagggcgctacggtagcagataggatccttgtatgccacaaatttg
aaataatatccttagatatcacgcgtacatgcaatgggg---------------------
--------------------------attagttctacatgattt----------tgtatg
attcgaaccccgttataagcaccatgaggtg-----------------------------
--tcaatgtttcac------gcaggcggatacatgttatgtgccaaaaatttcccatcac
taacgtgctcgcaccaggagtgtccctctaacgcgacgaaaaaagaaattgtaagcggtc
acgccatggggcttttggattg--------------------------------------
---------------------------------ttgagcatgtagttg------------
-------------atttacccagtacaagggcgtctgtgtctcga---------------
--------------------
>SEQ11
ccaatgag----------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------tgcatcgactcagtggggattttccggctgacttatttgataccgatataccc
ttgttatgggcctcaagggaggaaaaattcggcttgttccgactacttgcagaccaaaag
aaatccgcacagctt-------------------------tatgttgttatctgatcac-
---------------------------ccgtgtagcggaggtaggcccgacatctc----
--------------------------tacactggtagcgtaacaattgatcatt------
------------acgctcggcaactggataggttgcacccaggcacagttgaagtcaatc
cttattaatcgcttaagggcgctacggtagca----ggatccttgtatgccacaaattgg
tcttactatcccaagattttacgagttcatggcagggaagtctcgctg------------
-------cgatcctttgctttgatctcggatctttgaataatgtcaaatggcgcttaaac
tatgtagcccggttccttaaacgattacgtgtaacgtagtccttgaatccgcgcagcagg
gttttattg-----------gcaggcggatacatgttatgtgccaaaaagctcccatcac
taacgtgctcgcaccaggagtgtccctctaacgcgaccaaaaaacaaattgttagcggtc
gagccatgggtcttttgacctacagtcgacggcacttatgtcgcctgtatgcggactgca
ctagcattacttaagatcctgtttgtcgttt------------------------gtcaa
caactgagtcaatatttacacaatagaagggcctcgatttgccgctgggtctgtggag--
--------------------
>SEQ12
ctaatgagac--------------------------------------------------
-------------------------------------ctacaagtattggtcac------
------------------------------------------------------------
-------------------ttggggacttaccggctggcttatttgataccgatataccc
ttgttatgggcctcaagggaggaaaaattcggcttcttcccactacttacacaccaaaag
caatcgacacagcat-------------------------tatcttgtaatttgatcac-
---------------------------ccgtggcgcggaggtatgggcgagagctccatc
cccggatggaaaagcat--------at-------------------tgaacatt------
------------aagtagggcaagtggataggttgcacccaggcaccgttgaagtcaatc
cttattaattgcttaagggcgctacggtagcagatgggatcgttgtatgccacaaatttg
acttactttccct-------------------caagggtgtctcgctgcgatccatttct
aaacggatggtccctttctttgatgtagtatctatatataatttcaacggacgatgtaac
tttggaacccggctcttaacacgattacgtgaaacgtagtccgcgaatccccgcgaccgg
tttatattatccactcttcggcaggcggatacatgttatgtggcaaaaagctcccatcac
tagcgtgctcgcaccaggagtgtccctctaacgcgacgaaaaaacaaattgttagctgtc
ccgacaccggtctcttgacctacagtcgacagcacttatgtcgccggtaaggggtctgcg
ctagcaatgctta-----------------------------------------------
-----gagtcaatagattcccactataagggcctcgttatgccgctgagtcagtatacga
g-------------------
>SEQ13
ataatgagactagcttaaggctcgtgacgaagtgtgcaacttccgaaagggaagaacccg
agccggaaaggtggcagtcatggccagtggtcgatctccaccggtgttggctattcacct
gccgaaatgttt------------------------------------------------
-------------------ttggggattttccggctgacttatttgataccgatataccc
ttgttatgggcctcaagggaggaaaaattcggcttgttccgactacttgcagaccaaaag
caatcgacaacgcttagacgctcttcttatattaagcct-cgcgcctcaactgagttac-
---------------------------------------------cacgacagccccatc
tccgga----------------------------gagtgtaacatttgaacattgctgaa
gataacttctgcaaggacggcaactggataggttgcacccaggcacagttgaagtcaatc
cttattaatcgcttaagggcgctacggtagcagatgggatccttgtatgccacaaattgg
tcttac---------------agcgttcatctcagggatgtctcgc--------------
-------tggtcccttactttgatgaagaatctatgtataatttcaaaagacgctgtaac
tatggaacccggttcttaacacgattacttgaaacgtagtccctgatgccgcgcaccatg
gttttattgtccactcttcggcaggcggatacatgttatgtgccaaaaagctcccatcac
taacgtgctcgcaccaggagtgtccctctaacgcgaccaaaaaacaaattgttagcggtc
ag------------------tacgctcgatggtactaaagttg-----------------
----------------------------------------tgtagtttcactgcagtc--
------------------------acaagggcgtcgcttcgccgctgggtct--------
--------------------
>SEQ14
ctaacaagacaagc---------------------------------------gaagacg
agccggagtggtttcaga-----------------------------------ttcaact
gctgtaatgtttgaactc------------------------------------------
----actttgtttaattccgtggggattttccggctgacttatttgataccgatataccc
ttgttatgggcctcaagggaggaaaaattcggcttgtaccgactacttgcagaccaaaag
caatctacaatgcttcgaaggtgttgttatattaagatgctatgatggtacttgatcac-
-----------------------------------------------cgctagctccata
tccggatggtagagcttcctgtcaggtactctggga------------------------
------------tagaacggcaactggataggttgcacccaggcacagttgaagtcaatc
cttattaatcgcttaagggcgctacggtagcagataggatccttgtatgccacaaattgg
acttactctcgctaggtctcgct-------------------------------------
--g----cgatcgtttgccaaggggtagtatctatatataatttcaaaggacgatgtaac
tttggaaccgggtacctaacacgattacgtgaaaagtaggccgcgaatccccgcaccagg
tatatattgtcgactcttcggcaggcggatacatgttatgtgccaaaaagctcccatcac
taacgtgctcgcaccaggagtgtccctctaatgcgacggaaaaacaaattgttagcggtc
tcgccatgggtgttatgacctacagtcg-------------------taagcggtctgc-
--------acctaagatcctgtttttcgtttgccccactctgtagttgcactgagctcaa
caa--------------------------------------------ggtctgtgaagga
ggcagaatcgtgtctcgagg
>SEQ15
ctaatggg----------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------tatcggtcacttggggactttccggctggcttatttgataccgatataccc
ttgttatgggcctcaagggaggaaaaattcggcttcttcccactacttgcacaccaaaag
aaatccgcacagttt-------------------------tatgtggatatttgatcac-
--------------------------------------------gcccgacttctccatc
tcaggatgg-----------------tacgcagggagagtaacaattggacgtt------
------------aagcacgggaagtggataggttgcacccaggcacagttgaagtcaatc
cttattaatcgcttaagggcgctacggtagcagataggatccttgtatgccacaaatttg
acttactcacgctaggtctcgct-------------------------------------
------gcgatcgtttgccaaggggtagtatctatatataatttcaaagtacgatgtatc
tttggaaccgggtacctaacacgattacgtgaaaagtaggccgcgaatctccgcaccagg
tatataatgtcgactcttcggcagacggatacaagttatgtgccaaaaagctcccatcac
taacgtgttcgcaccaggagtgtccctctaacgcgacgaaaaaacaaattgttagcgctc
acgccatgggtattttgacttagactcaacggcactaatgtc------------------
---ggaatatttaagttgct--------------------tgtagttgctgtgcagtgaa
catctgatggaatccttaccacttacatgggcgtcgtattgccgctgggtct--------
----------tgtctcgc--
>SEQ16
ctaatcagac--------------------------------------------------
-------------------------------------ctacacgtattggtcac------
------------------------------------------------------------
-------------------atggggactttccggctggcttatttgataccgatataccc
ttgttatgggcctcaagggaggaaaaattcggcttgttcccactacttgcacaccaaaag
agatccgcacagc------------------------------------atttgataac-
-------------------------------------------tgcacaacagctccatc
tccggatgg------------------------ggagagtaacagttta-----------
------------aaccacggcaactggataggttgcacccaggcacagttgaagtcaatc
cttattaatcgcttaagggcgctacggtagca----ggatccttgtatgccacaaattgg
cctgacgatccctagatt--------------cacggct---------------------
--ggggatgatccctctctttaatgtattcgctatatataatttaaacgaatgttgtatc
tttcgaacc--------------------------gaagtccgggaatgcccgcaa----
----------ccactct---gcagacggatacaagttatgtgccaaaaagctcacatcac
taacgtgttcgcaccaggagtgtccctctaacgcgacgaaaaaacaaattgttagcgctc
aagccatgggtcctttaacttacacgcgacggcaccaatgtt------------------
---ggcatatttaggagcct--------------------tgtagttgctctgcagtcaa
caactgatggtatctttacccattttaagggcgtccctttgccgctggatct--------
----------ggtctcgc--
>SEQ17
caaacaagacaagc---------------------------------------gacgatg
acacggagtggtttcaga-----------------------------------ttcaact
gctgtaatttttgaactc------------------------------------------
----actttgtttaa-----tggggattttccggctgacttatttgataccgatataccc
ttgttatgggcctcaagggaggaaaaattcggcttgttccgactacttgcagaccaaaag
caatctacaatgcttcgaaggtgttgttatatttctatgctatgatgctactggatcac-
-----------------------------------------------cattagatccata
tcgggatggtagagcttcctggcaggtactctggga------------------------
------------tagtacggcaagtggataggttgcacccaggcaccgttgaagtcaatc
cttattaattgcttaagggcgctacggtagcagataggatcgttgtatgccacaaatttg
cttgactagccctaaattttacc-------------------------------------
--ggggaaggtccctttctttaatgtattagctatatataatttaaacgaatcttgtaac
tttccaaccctgttgtaaacacgatgacgggatatgtagtccggggatgcccgcaac---
--------------------gcaggcggatacatgttatgtgccaaaaatttcccatcac
taacgtgctcgcaccaggagtgtccctctaacgcgacgaaaaaagaaattgtaagcggtc
acgcaatggggcttttgataaacagtcgacggcactaatgtgtgcgttaaggggtctgca
gtagcaatatttaagatcctgtttttcgtgccgcccactatgtagttggtctgaaatcaa
caactgactgaatatgtaccccttacaagggccttgctttgccgctgggtctgtttagga
ggcgtcatcttgcctcgggc
>SEQ18
ctaatgag---------------------------------------------------t
gtccggagtggtcccaga------------------------------------------
------------------------------------------------------------
-------------------gtggggactttccggctggcttatttgataccgatataccc
ttgttatgggcctcaagggaggaaaaattcggcttcttcccactacttgcacaccaaaag
caatc--------------------ttaaaatcaagatgctatgatggtacttgaaca--
---------------------------------------------------agttccata
tccgaatggtagagcttcctctcaggttctctggg-------------------------
------------aataacggcaagtggataggttgcacccaggcacagttgaagtcaatc
cttattaatagcttaagggcgctacggtagcagataggatccttgtatgccacaaatttg
cgtcacggct--------------------------------------------------
--ggggattgtccggctctttaatgtattagctat-------------------tgtaac
tttcgaacacggt---------------------cgtagtccgggaatgcccgcaa----
----------ccactctt--gcagacggatacaagttatgtgccaaaaagctcacatcac
taacgtgttcgcaccaggagtgtccctctaacgcgacgaaaaaacaaattgttagcgctc
acgccatgggtcttttgacttagactcgccg-----------------------------
-----aatatttaagttgct--------------------tgtagttgctctgcagtgaa
caactgatggaatctttaccaattgcatgggcgtcgtattgccgctgggtct--------
----------tgtctcgc--
>SEQ19
ctaat------------------------------------------------------t
gtcatgagtggtgccaga------------------cctacaagtggtg-----------
------------------------------------------------------------
-gtcactttgtttgatctcgtggggactttccggctggcttatttgataccgatatatcc
ttgttatgggcctcaagggaggaaaaattcggcttgttcccactacttgcagaccaaaag
caatccacaatgctt-------------------agctgctatgatgatactttatcacc
cct------------------------ccttggagcggagctat----------------
----gatggtagtacttcctgtcgtatacactgggagtgg--------------------
------------gagaacggcaagtggatcggttgcacccaggcaccgttgaagtcaatc
cttattaattgcttaagggcgctacggtagcagataggatcgttgtatgccacaaatttg
acttaa--------------------------caagggtgtcccgctgcgatccatttct
aaacggatggtccctttctttaatgtattctcgatatataatttcaacggacgaagtaac
tttgtaagccggctcttaac-------------------tccgcgaatccc---------
-------------ctcttcggcagacgtatacaagttatgtgccaaaaagctcccatcac
taacgtgttcgcaccaggagtgtccctctaacgcgacgaaaaaacaaattgtcagcgctc
acgccatggggcttttg-------------------------------------------
------------------------------------------------------------
-cattgttgagcaatttacccagtataaggttgtctgctcga------------------
--------------------
