>SEQ0
gcaataacgctgtcgtgacatcaggcgccgaaccggaagcgtcgaacggtccgggtcccc
tcactgtccagaataaaatgtatcccataatccccctttcttgtgtactatgtcgcgaga
cgtcagtcgttagcgtcgctaataaacacttccaccacctgcaaggttccgtagcgtaat
tttactgcttgctccctaaaagacgctcgctacacgcctgggtgtttttagcaacacaca
gacttggctggcgttgttgatagtcgaaatgtagctgcggacaacagtttcttgcactaa
cggctaaggctgtgtttaatatgcttgacaaccattaagtgattaaattggcttttgaca
agtaagtccatataagctgctacataatgtctccgtcttgcgagcgaaggcagtctacgt
cgagaactaggcggccatacaacaataccctatcgggaagaagtaatatctcctgacatt
gagtccgagaaaaggaagggaactaagaagtgtggacgcagggaccagccctagaatacg
caacgaacaatcgactccacccaacggaaagtccctcatttgatttagtcattcgtgaag
taaaccacgtaaggaaatgcaagcgcctgttcgaaggagcgaggtgctccattaacctcg
attagtatgagctccgaagctctaccaagggcccacgacttcgcggtcttactctatacc
aaaccccgagcgtttttcgccggctcacaaagccagcacaaaggca-gcatacgcattca
tcgtatcgattctcccgctcacggtgcacctactgtgtgatggcgttgcagctatggggt
agtggctcattcgagagcacctactgtgcactggctacgtagggcctatctgaagtctgc
ttccttataacgctgggcggaagcaaccgagtctcggcttttttaggttcatgtgggcca
ccggtgcaatagtgcatagaaccctcccgtagtgccgcgtgggattaggggtttcacatc
acattccttgggagtgcttgatactttggcttctgcgtctggtatttcgtacttatgagt
caagcagttccaacaaataaa
>SEQ1
gcaataacgttgtcgtgacatcaggtgccgtacccgaagcgtcgaacg------------
----tgtccagaataaaatgtatcccatagtccccctgtcttgtgtactatggcgcgaga
cgtcagtcgttagcgtcgctaataaaaacttccaccccctgcaaggttacgtagcgcaat
tttattgcttgttccctaaaagacgctcgctacacgcctgggtgtttttagcaacacaca
gacttggctggcgttgttgattgtcgaaatgtagctgcggacaacagtttcttgcactaa
cggctaaggctgtgtttaatatgcttgacaacc------------------------aca
agtaagtccatctaagctgctacataatgtctccgtcttgcgagcgaaagca--------
-------------gccatacaacactaccctatcgggaagaagtaatatctcctgacatt
gagtcctagacaagttagggaacaaagaagtgtggacgcagggaccagccctagaatacg
caacgaacaatcgactccacccaacggaaagtccctcatttgatttagtcattcgtgaag
tcaaccacgcagggaaatgcaagctccaattccgaggagcgaggccctccattaacctcg
attag-------------------acaaggtcccccgacttcgcggtcttactctatacc
aaaccccgagcgtttatcgccggctcacaaagccagcccaaaggca-gcagacgcattca
tcgtgacgattctgccgcccacggtgcacctactgtgtgatggcgttgcagctatggggt
agtggctcattcgagagcacctactgtgcactggctacgtagggcctatctgaagtctgc
ttgcttataacgctgggcggaagcaaccgagtctcggcttctttgggttcaggtgggccc
ccggtgcaatagagcagagaaccc--------------------ttaggggtttcacttc
acagtccttgggagtgcttgatactttggcttctgcgtctggtctttcgtacttatgagt
caagcacttaccataaataaa
>SEQ2
gcaataacgctgtccagacatcaggcggcgaaccgg-------------------tcccc
tcactgtccagaataaaatgtattccataatccgcatctcttgtgtactatgtcgcgaga
t--------------------------acttccaccacctgcaaggttccgtagattaat
tttactactagctccct-aaagacgctcgcaacacgcctgggtgtttttagcaacacaca
gacttggctggcgttgttgatagtcgaaatgtagctgcggacaacagtttcttgcactaa
cggctaaggctgtgttttgtatgcttgacaaccattaggtgattaaaatggcttttgaca
agtaagtcca-----------------------caacttgcgagcaaaggcagtctacgt
agagaactaggcgatcatac----------------------------tctcccgacttt
gagtccgagaaa--------aacaaagaagtgtggacgcagggaccagccctagaatacg
caacgaacaatcgactccacccaacggaaagtcccccatttgatttagtcattcgtgaag
taaactacgtaagtaaatgcaagcgcctgttcgaaggagcgatatgctccattaacctcg
attagtatgtgctcctaagctctacaaagggcccacgacatcgcggacctacactatacc
caacccccagcgttttacgccggctgacaaagccagcacaaaggca-gcatatgcatt--
----------------gctcacggtgcacctactgtgtgatggcgttgcagctatggggt
agtggctcattcgagagcacctactgtgcactggctacctagggcctatctgaagtctgc
ttccttataacactgagcggaggcaacctagtctcggcttttttaggttcatgtgggcca
cggttgcaatagtgcatagaaccctcccgtagtgccgtgtgggattaggggtttcacatc
acattccttgggagtacttgatactttggcttccgcgtctagtctttcgtacatatgagt
caagcagttccaccaaataaa
>SEQ3
gcaagaacgctgtcc---------------------------------------------
----------gggtaaaatgtatgccataagcccccttacttgtgtaccatgtcgcgaga
cgtcagtcgttagcgtcgctattaaacacttccaccacctgcaaggttccgtagcg----
----------gctccctaaaagacgctcgcaacacgcctgggtgtttttagcaacacaca
gacttggctggcgttgttgatagtcgaaatgtagctgcggacaacagtttcttgcactaa
cggctaaggcggtgttttgtatgcttgacaaccattaggtgattaaaatcgcttttgaca
agtaagtcga-----------------------caacttgcgatcaaaggcagtctacgt
agcaaactaggcgatcatac----------------------------tttcccgacttt
gactccgagaaa--------aacaaagaagtgtggacgcagggaccagccctagaatacg
caacgaacaatcgactccagccaacggaaagtcccccatttgatttagtcattcgtgaag
tcaaccacgcagggaaatgcacgctccaactccgaggagcgaggccctcctttaccctcg
attaa-------------------acaaggtcctccgacttcgcgttcttactctat---
----------cgtttatcgccggctcacaaaatcagcccaaaggca-gcagacgcattca
tcgtgacgattctgccgcccacggtgcacctactgtgtgatggcgttgcagctatggggt
agtggctcattcgagagcacctactgtgcactggctacgtagggcctatctgaagtctgc
ttgcttataacgcttggccgaagcaaccgagtctcggcgtctttgggttcaggtgagccc
ccggtgcaatagagcagagaaccct-----------------------------------
-------tgaggtgtgctagatactttggcatctgcgtctggactttcgtacaagtgagt
cacgcacttaccataaataaa
>SEQ4
-----------------------gatatagtacccaaagcggccaaag------------
----tgtccagaagaaaatgtttcccatagtccccctgtgttgtgtactatggcgcgcga
cgtcacccgtt-----------------------------gcaaggttacgtagcgcaat
tttgttgcttgttcc-----agacgctcgcaacacgcctgggtgtttttagcaaaacaca
gacttggctggcgttgttgatagtcgaaatgtagctgcggacaacagtttcttgcactaa
cggataaggcggtgttttgtatgcttgacaaccataaggtgattaaaatcgcttttgaca
agtacgtcga-----------------------caacttgcgatcaaaggcagtctacgt
agcaaacta---------------------------------------tttccctacttt
aactccgagaaa--------aactaagaagtgtggacgcagggtccagccctagaatacg
caacgaacaatcgactccacccaacggaaagtccctcatttgatttagtcattcgtgaag
tagactacgtaagtaaatgcaagcgcctatttgaaggagcgatatgctccattaacctcg
atcagtatgtgctcctaaagtctacaaagggcccacgacatcgcggccctacgctatacc
taacccccagcgttttacgccggctgactaagccagcacaaaggca-gcatattcatt--
----------------gctcccggtgcacctactgtgtgatggcgttgcagctatggggt
agtggctcattcgagagcacctactgtgcactggctacgtagggcctatctgaagtctgc
ttgcttattacgcaggtcggaagcaaccgagtcc--------------------------
ccggtgcactagagcagagaaccct--------------------taggggtttcacttc
acagtcattgggagtgcttgatactttggcttctgcgtctggtctgtcgta---------
----cacttaccataaataaa
>SEQ5
gtaataaagct---------tcaggggccgaaccggaagcgtcgaacggtccgcgtccac
tcactgtccagaatagaatgtatgccgtaatcccccttgcttgtgtgctatgtcgcgaca
cgtcagtcgttagcgtcgctaataaacacttccaccacctgcaaggttccgtagcgtaat
tctactgcttctttcctaaaagacgctcgaaacacgcctgggtgttcttagcaacacaca
gacttggctggcgttgttgatagtcgaaatgtagctgcggacaacagtttcttgcactaa
cggctacggcggtgtttaatatgctttacgaccattaagtgattaaattggcttttgaga
agtaagtccatataagctgctacattatgtctcagtcttgcgagcgaag-----------
------ctaggcggccatacaacaataccctatcgggaagacgtaatatctcatgacatt
gagtcagacaagaggaagggaacaaagaagtgtggacgcagggaccagccctagaatacg
caacgaacaatcgactccagccaacggaaagtcgcccatttgatttagtcattcgtgaag
tcaaccacgcaggcaaatgcacgcgcccactccgaggagcgaggcccttctttaccc---
------------------------agtaggtcctccgacactaaac--------------
----------cgtttatcgccggctcacaaaagcagctccatggca-gcagtcgcattca
tcgttacgattgtgccgcccacggtgcacctactgtgtgatggcgttgcagctatgcggt
agtggctcat--gagagcacctactgtgcactggctacgtagggcctatctgaagtctgc
ttggctttaacgctgggcggaaacagccgag---------------------gtcggacc
ccggtggaatagagcagagaactct--------------------taggggtttcacttc
acagtccttgggagtgctaggttcttagact----------------cgtacttatgtga
caagcacttaccagaaataaa
>SEQ6
gtaataaagct---------tcaagggccgaaccggaa----------------------
-------------------gtatgccgtaatcccccttgcttgtgtgctatgtcgcgaca
cgtcagtcgtg----------------acttccaccacctg-------------------
---------------ctaaaagacgatcgaaacacgcctgggtgttcttagcaacacaca
gacttggctggcgttgttgatagtcgaaatgtagctgcggacaacagtttcttgcactaa
cggctaaggctg-------------------------gctgattaaaattgcttttgaca
agtaagtcca-----------------------catcctgcgaggaaaggcattctacgt
agagaactgggcgatcatac----------------------------tctcccgacttt
gagtccgagaaa--------aacaaagaagtgtggacgcagggaccagccctagaatacg
caacgaacaatcgactccagccaacggaaagtcccccatttgatttagtcattcgtgaag
tcaaatacgtaagtcaatgcaagcgcgtgttctaaggagcga------------------
-----tatgtgctgcgctaatctagaaagggcccacgac---------------------
-aacccccagcgttttacgctggctgacaaagccagcacaaaggcc-gcagatgcatt--
---------------------cggtgcacctactgggtgatggcgttgcagctatggggt
agtggctcattcgagagcacctactgtgcactggctacgtagggcctatctgaagtctgc
ttccttgttacactgggcggaggcaacctagtctcggcttttttaggttcatgtgggaca
cggtggcaatagtgcatagcaccctcccgtatggccgtgtgggattaggggtttcacata
acattccttgggagtacttgatactttggcttccgcgtctagtcttacgtacatatgagt
caagcagtcccactaaataaa
>SEQ7
acaataacggtgtcgtgacatcagctgccgtacccgaagcgtcgaact------------
----------gaaaaaaatgtatcccagagtccccctgtcttgtgtactatggcgagaga
cgtcagtccttagcgtcgctaataataacttccaccgcctgcaaggttacattgcggaat
tttatcgcctgttccctaaaagacgctcgcaacacgcctgggtgtttttagcaaaacaca
gacttggctggcgttgttgatagtcgaaatgtagctgcggacaacagtttcttgcactaa
cggctaaggctg-------------------------gctgataaaaattgcttttgaca
agtaagtaca-----------------------catcctgcgaagaaaggcattctacgt
agagaagcgggcgatcatac----------------------------tttcccgactgt
gaatccgagaag--------aacaaagaagtgtggacgcagggaccagccctagaatacg
caacgaacaatcgactccacccaacggaaagtcccccatttgatttagtcattcgtgaag
taaaccacgtaaggaaatgcaagcgcctcttcgaaggagcgaggtgctccattaacctcg
attagtatgagctccgaagctctaccaagggcccacgacatcgcggtcttgcactatccc
aaac-------------------------aagccagcactacggca-gcatacgcattca
tcgtat---------------cggtgcacctactgtgtgatggcgttgcagctatggggt
agtggctcattcgagagcacctactgtgcactggctacctagggcctatctgaagtctgc
ttcgttataccggtcggcggaagcgaccgagtctcggcttttctagggtcatgtgtgcca
ccggtacaagtgtgtattgaaccctcccgtagtgccgcgtgggattaggggtgtcacagc
atattccttggtagtgcttgatattttggcttctgcgtctggtatttcgtacttataagt
caagcagttcctacaaataaa
>SEQ8
tcaataacgttgtcgcgacatcaggcgccgtaccggcagcgtcgaacggtccgggtcccc
tcactgtctagtataaaatgtttcccataatcccactttgttaagtacta----------
-----------------------------------cacctacaaggtttcgcagcgtaat
ttcactgctggctcactaaaagacgatcgaaacacgcctgggtgttcttagcaacacaca
gacttggctggcgttgttgatagtcgaaatctagctgcggacaacagtttcttgcactaa
cggcgaaggttg-------------------------gctgataaaaattgct-------
---------------------------------tgtcctacgaagaaagggattctacgt
agagaatctaggttccc-------------------------------------------
--------------------aactaagaagtgtggacgcagggaccagccctagaatacg
caacgaacaatcgactccacccaacggaaagtccctcatttgatttagtcattcgtgaag
tcaaccacgcagggaaatgcaagctccaattccgaggagcggggccctccattaacctcg
aatag-------------------acaaggtcccccgacttcgcggtctt----------
-----------gtttaacgccggaacacaaagtaagcccaaaggca-gcagacgcattaa
tcttgacgattctgccccccacggtgcacctactgtgtgatggcgttgcaactatggggt
agtggctcattcgagagcacctactgtgcactggctacgtagggcctatctgaagtctgc
ttcctta----------------------ggtttaggcggctttgggttccggtggggcc
ccggtgcaatagagcagagaaccct--------------------ttgggggttcacttt
atagtccttgggagtgcttgatactttggcttttgcctctggtctatcgtatttatgact
caagcacttaccataaataaa
>SEQ9
gcaataatgttgtcgtgacatcaggtgccg------------------------------
----tgaccagaataaaatgaatcccatagtccgcctgacttgtctcctatggcgcgaga
cgtcagtagttggcgtcgctaataa-----------------aaggttgcgtagagcaat
tttattgcttgttccctaacagacgatcgaaacacgcctgggtgttcttagaaacacaca
gacttggctggcgttgttgatagtcgaaatgtagctgcggacaacagtttcttgcactaa
cggctacggctgggtttaatatgctttacgaccattaagtgattaaattggcttttgaga
agtaagtccatataagctgctacattatgtctcagtc-----------------------
------ctaggcggccatagaacactcccctatcgcgaagacgtaatatctcatgacatt
gagtcagacaagaggaagggaacaaagaagtgtggacgcagggaccagccctagaatacg
caacgaacaatcgactccacccaacggcaagtcccccatttgatttagtcattcgtgaag
tgaaccacgcaggccagtgcacgcgcccactccgaagagcgaggcccttcattaccc---
------------------------agtagggcctcccacaccaaac--------------
----------cgttaatagccggctcacaaaagcgggtcgatggca-gcagtcgcaataa
tcgttacgattgtgccccccacggtgctcctactgtttgatggcgttgcagctatggggt
agtgcctcattcgagagcacctactttgcactggctacgtagggcctatctgaagtctgc
tgggctttaacgctgcgcggaaacagccgag---------------------gtcggacc
ccgttgggatagagcggagatctct--------------------taggggtttctcttc
acagtccttgggagtgctaggttcttagact----------------cgtacttatgaga
caagcacttactagaaa----
>SEQ10
gtaattaa----------------------------------------------------
-------------------gtatcccgtaatccccattgc--------------------
cgtcagtcgtg----------------actgccacgacctg-------------------
---------------ctaaaagacgctcgcaacacgcctgggtgtttttagcaaaacaca
gacttggctggcgttgttgatagtcgaaatgtagctgcggacaacagtttcttgcactaa
cggctaaggcgctgttttgtatgcttgacaaccattaggtgattaaaatcgcttttgact
agtaagtcga-----------------------caacttgcggtcaaaggc---------
------------------------------------------------------------
---tacaagtaa--------aacaaagaagtgtggacgcagggaccagccctagaatacg
caacgaacaatcgactccacccaacggcaagtcccccatttgatttagtcattcgtgaag
taaaccacgtaaggaaatgcaagcgc--------------------ctccattgacctcg
ataagtatgagctcggaagctcta------------------gcggtcttactctgc---
---------------------ggctcacaaagccagcccaaaggca-tcatacccattca
tcgta----------------cggtgcacctactgtgtgatggcgttgcagctatggggt
agtggctcattcgagagcacctactgtgcactggctacgtagggcctatctgaagtctgc
ttccttgttacaatgggcggaggcaacctagtctcggcttttttaggttcatgtgggaca
cggtggcggccgtg----------------------------------------------
-------------agggctgatagtttggctcccgcgtctagtcttacgtaaacttgagt
caagcagtgccactaaataaa
>SEQ11
acaataacggtgttgtgacatcagctgccgaaccagaagcgtcgaact------------
----------gaaaaaaatgtatcccagagtccccctgtcttgtgtactatggcgggaga
cgtcagtccttagcgtcgataataataggttccaccgcgtgcaaggttgcattccggatt
tttatcgccttttccctaaaagacgctcgcaacacgcctgggtgtttttagcaacacaca
gacttggctggcgttgttgatagtcgaaatgtagctgcggacaacagtttcttgcactaa
cggctacgccggtgattaatatgctttacgatcattaggtgattaaattggctctta---
------------ttagctgctatattatgtctcagtctcgcgagcgaat-----------
------caagccggccatacaacaataccctatcgggagcaggtaatgtcacacg-----
----------agaggaagggaactaagaagtgtggacgcagggaccagccctagaattcg
caacgaacaatcgactccacccaacggaaagtccctcatttgatttagtcagtcgtgaag
tgaaccacgtaatgaaatgcaagcgcctcttcggagga----------------------
------------------------ggga-ggcgcgcgaagctccgaagct----------
--cgacccactatc---------ccaaacaagcccgcactacagca-gcatacccattca
tcgtat---------------cggtgcacctactgtgtgatggcgttgcagctatggggt
agtggctcattcgagagcacctactgtgcactggctacctagggcctatctgaagtctgc
ttgcttataacgcttgtccggagcaacggagtctcggggtctttgggttcaggtgagccc
ccggtgta------------------------------------------gtagcgcaga
gaacccttgaggtctgctagatactt----------------tctttcgtacaagtgagt
caggcacttacaataactaa-
>SEQ12
gtaataaagct-------------------------------------------------
------------tcaagggctatgccgtaatcccccatgcttgttcgctatgtagcgaca
cgtcaggcgtg----------------acttccaccacctg-------------------
--------------------agacgatcgaaacacgcctgggtgttcttagcaacaaaca
gacttggctggcgttgttgatagtcgaaatgtagctgcggacaacagtttcttgcactaa
cggctaaggcgctcttttgtatgcttgacaaccattagttgat-----------------
--taagttga-----------------------caacttgcggtca--------------
------------------------------------------------------------
---tacaagtaa--------aacaaagaagtgtggacgcagggaccagccctagaatacg
caacgaacaatcgactccagccaacggaaagtcccccatttgatttagtcattcgtgaag
gaacctacggaagtaaatacaagcgcctgttcgaaggagcgttatacccaattaacctcg
attagtatgtgctcctaagcgctacaaagggaccacgacatcgcgagcctacactatacc
aattccccagtgttttccgccggctgacaaagcaagcacaaaggca-gcatatgcatt--
----------------gctcacggtgcacctactgtgtgatggcgttgcagctatggggt
agtggctcattcgagagcacctactgtgcactggctacgtagggcctatctgaagtctgc
ttcctta----------------------ggtttaggcggctttgggatccggtggagcc
ccggtgcaacagagctgtgaacact--------------------ttggaggttcacttt
atactccttgggagtgcttgatactttggcttttg-------------------------
---------------------
>SEQ13
acaataacggtgttgtga------------------------------------------
----------------------------------cctgtcttgtgtactatggcgggaga
cgtcagtccttagcgtcgatataaataggttccaccgcgtgcaaggttgcattccggagt
tttatctcatattccctaaaagacgctcgcaacacgcctgggtgtttttagcaacacaca
gacttggctggcgttgttgatagtcgaaatgtagctgcggacaacagtttcttgcactaa
cggctacgcaggtaactaatatgctttatgatcattaggtgattaaacttgctctta---
------------ttagctgctatgttatgccttagtctcgcgagcgaat-----------
------cacggcggccatacaac---------------------attgtcacacg-----
----------agaggaagggaacaaagaagtgtgaacgcagggaccagccctagaatacg
caacgaacaatcgactccagccaacggaaagtcccccatttgatttagtcattcgtgaag
tgcgtgctctaaggagcgatatgtgctgcgctaatcta----------------------
------------------------gaaagggcccacgacatcc-----------------
-----cccaccgttttacgatggctgacaaagcccgcacaaaggcc-gcaggt-------
-----g---------------cggtgcacctactgggtgatggcgttgcagctatggggt
agtggctcattcgagagcacctactgtgcactggctacgtaaggcctatctgaagtctgc
ttctttaaaacactgagcggaggcaacctagtcccggccttttttggtccacgtgggcca
cggttgca----------------ttctgtagtgccgtgtgggattaggggtcgcacatc
acattcctttggagtacttgatacttaggcgtacgggtctagtttttcgtacatatgaat
caagcagttccaccaaataaa
>SEQ14
gcaataacgctgtccagacatcaggcggcgaacc--------------------------
-------------------ggtcccctcaatccgcatctcttgtgtactatgtcgggaga
t--------------------------------------------actccgtagattaat
tttactact----------aagacgctcgcaacacgcctgggtgtttttagcaacacaca
gacttggctggcgttgttgatagtcgaaatgtagctgcggacaacagtttcttgcactaa
cggcgaaggctg--------------------------ctgataaaaattgcctgtg---
-------------------------------------ttacgaagaaagggaggcttggt
tccc--------------------------------------------------------
--------------------aacaaagaagtgtggacgcagggaccagccctagaatacg
caacgaacaatcgactccagccaacggaaagtcgcccatttgatttagtcattcgtgaag
tcaaccatgcagggaaatgcaagctccaa-----------------ctccattaacctcg
aatag-------------------acaaggtcccccgacttcgcggtctt----------
------------------------------agtaagcccaaaggct-gcagccgca----
------------------ccacggtgcacctactgtgtgatggcgttgcagctatgcggt
agtggctcat--gagagcacctactgtgcactggctacgtagggcctatctgaagtctgc
t--------------ggcggtagcaaccgagtctcggcttttttaggtacatgttggcca
ccggtgcaatagtgcat----------------------------------tttcacttc
acaatccttgggagtgcttgatactttg-----------------------cttatgagt
caagcagt-------------
>SEQ15
------------------------------------------------------------
--------------gtaatagtcccttcaatccccatctcttgtgtactatgttgggaga
------------------------------------------------------------
----------------tactagacgatcgaaacacgactgggtgttcttagcaacaaaca
gacttggctggcgttgttgatagtcgaaatgtagctgcggacaacagtttcttgcactaa
cggctacggcggtgtttgaaatactttacgaccattaagtgagtacgttggcttttgaga
agtaagtccatataagctgctacattatgtctcagtcttgcgagcaaag-----------
------cgaggcggccatacaacaatacccgatcgggtagacgtaatatctcatgacatt
--------------------aacaaagaagtgtggacgcagggaccagccctagaatacg
caacgaacaatcgactccacccaacggaaagtccctcatttgatttagtcattcgtgaag
tcaaccacgcagggaaatgcacgctccaactccgaggagcgaggttgaata---------
---------------------------aggtcctccgactacgcgt--------------
----------tcttact------ctaacaaaatcagccctaaggca-tcagacgcattca
tcgcgactatgctgtcggccacggtgcacctactgtgtgatggcgttgcagctatgcggt
agtggctcat--gagagcacctactgtgcactggctacgtagggcctatctgaagtctgc
tt--ccttaggtttaggcgg--------------------------------------ct
tccggttcgtagagc------------------------------ttgggggttcacttt
atcgtccttggcagtgcttgagactt-ctct----------------catatttctgact
caagcacttaccatgaaaaaa
>SEQ16
acaataacggtgttgtaa------------------------------------------
----------------------------------cctgtattgtgtactatggcgggaga
catcagacctcagcgtggatataaagaggttccacagtgtggaaggtttcat--------
--------------tccggaagacgatcgaaacacgcctgggtgttcttagcaacacaca
gacttggctggcgttgttgatagtcgaaatgtagctgcggacaacagtttcttgcactaa
ctgataaggcggtgttttgtatgcttgacaaccataaggtgac----------ttctacg
tagaaatcta--------------------------------------------------
------------------------------------------------ttaccctacttt
aactccgataaa--------aacaaagaagtgtggacgcagggaccagccctagaatacg
caacgaacaatcgactccacccaacggcaagtcccccatttgatttagtcattcgtgaag
taaaccacgtaaggaaatgcaagcgcctcttcgaagaagcgaggttctccattaagc---
-------------------ctctaccaagggcccacgtcattgcggtcttgcactatccc
aaaccat-----------------------------------------------------
---------------------cggtgcaccaactgtgtgatggcgttgcagctatggggt
agtggctcattcgagagcacctactgtgcactggctacgtagggcctatctgaagtctgc
ttgcttataagactaagcggagtcaacctagtctcgccttttttaggttcgtgtgggcca
cggttggaatggtgcgtagaaccctcccgtagtgccgtgtgggcttaggggtttcac---
----------------------actttggcttccg-----------------ataagagt
caagcagttccacagaataaa
>SEQ17
gcaagaacgctgtcc---------------------------------------------
----------ggctaaaatgtatgccataggcccccttatttgtgtacaatgtcgcgaga
cgtcagtcgttagcgtcgctatgtaacacttccaccacctgcaaggttccgtagcg----
----------gctcccaaaaagacgatcgaaacacgactgggtgttcttagcaataaaca
gacttggctggcgttgttgatagtcgaaatgtagctgcggacaacagtttcttgcactaa
cggctactgcggtttttaatatgctttacga-----------------tggcttttgata
agtaattccatataagctgcaacattatgtctcagtcttgcgagcgagg-----------
------ctaggcggcaatacaacaataccctatcgggaagacgtaatatctcatgacgtt
gagtgagacaagaggaaaggaacaaagaagtgtggacgcagggaccagccctagaatacg
caacgaacaatcgactccagccaacggaaagtcgcccatttgatttagtcattcgtgaag
----------------------gcacctgttcgaaggagggttatacccaattaagctca
tttagtatgtgatcctaagcgctacaaaggaaccgcgacaacgcgcgcgtacactata--
---------------------------------------gaaggca-gcatattcagt--
----------------gctcacggtgcaactactgtgtgatggcgttgcaactatggggt
agtggctcattcgagagcacctactgtgcactggctacgtagggcctatctgaagtctgc
ttgatgataacgctg--------------agtctcggcttgtttgggttcggatgggccc
ccggtggagtagagcagacaacact--------------------taggggtttcacttc
acagtccttggcagtacttgatact----------------gtctttcgtacttatgagt
caagcacttaccataaataaa
>SEQ18
-------------------------gatagtacccaaagcggccaaag------------
----tgtccagaagaaaatgaatcccatagtcctcctgtgttgtgtgctatggcgcgcga
cttcg---------------------------------ttgcaaggttacgtagcgcaat
tta------------------------cgaaacacgactgggtgttcttagcaataaaca
gacttggctggcgttgttgatagtcgaaatgtagctgcggacaacagtttcttgcactaa
cggatacgactgggttt---------------------------agattggcttttgaga
agtaagtccgtataagctgctacattatgtcccagtc-----------------------
------ctaggcggctaaaggacactcccctattgcgaagacgtgatatctcatgacatt
gagtttgacaagaggaagggaacaaagaagtgtggacgcagggaccagccctagaatacg
caacgaacaatcgactccacccaacggcaagtcccccatttgatttagtcattcgtgaag
taaaccacataaggaaatgcaaccgc--------------------ctccattgacctcg
ataagtatgagctcggaagcgcgg------------------------------------
----------tgttgcactgcggctcacacagccagcccagaggca-tcattcccattca
tcgta----------------cggtgcacctactgtgtgatggcgttgcagctatggggt
agtggctcattcgggagcacctactgtgcactggctacgtagggcctatctgaagtctgc
ttgggtttaatg---------------------------------------ggtccgacc
ccggtggaatagagcagagatctct--------------------tcggggtttcacttc
acagtccttgggagtgctaggttcctagact----------------cgtacttatgtga
caagcacgttcctgaagtaaa
>SEQ19
gcaacaacgctgtccagacatcaggcggcgaacc--------------------------
------------------------------------------gtattcaatgtcgcgagg
t--------------------------actgccaccggccgaaaggttccgtagattaat
tttattactagctccataa-agacgctcgcaacacgcctgggtgtttttagcaacacaca
gacttggctggcgttgttgatagtcgaaatgtagctgcggacaacagtttcttgcactaa
cggcgaaggcgg--------------------------ctggtaaaaatttcctgtg---
-------------------------------------ttacgaagaaagggaggcttggt
tccc--------------------------------------------------------
--------------------aacaaagaagtgtggacgcagggaccagccctagaatacg
caacgaacaatcgactccacccaacggaaagtcccccatttgatttagtcattcgtgaag
tcaaccacgcgggtaaatacacgctcctattccgaggagcagggccctcca---------
------------------------acaagctcccccgacttcgcggtctt----------
-----------------------------------gtttaacggcgcgcagacgcattca
tcttgtcgattctgccccc--cggtgcacctactgtgtgatggcgttgcagctatggggt
agtggctcattcgggagcacctactgtgcactggctacgtagggcctatctgaagtctgc
ttgttgataacgctg--------------agtcccggcttgttt---------------c
cgggtggagtagaccagacaacgct-------------------------------cttc
acagtccttcgcagtacttgacgctt----------------tttttcgtacttatgagt
ctagcacttaccataaatata
