>SEQ0
aacagcccgtgcggtctcgaatgagcttcattcgcttagctccgcttccgcccggcactt
ggcggttgccatatttgcggtgataagctgcagtaaatagattttccaggattgcaaacc
tacccaacgatcagctcggagcacgggcgtgagccaagacgtacaacatataacaaagga
ggaggacgagcccggactgacccaaggtatatcacgtaactctccggagtttcattcgtt
atctcaagtatcccgggctatagtatcaacatacgtcgtccttgttactaaacctcgatc
cagtgataggtgcatcaccgacagctttcgaacagctgtatacactgggtgggaggtaag
tttaagttaaattcatacactataatcccgagtggagatctggacagtaatggtaatgcg
tttgaaggaagggattcatatgaactcacagcgggactacgcttaacaagcctcctctgg
gcccactgcaggagcgactccgtgtttatgtgcacagagcaatagtcagttaaggacttc
ctaaactaatgcgtggctgagtgtcaagttggcagaatgcgcagtagaatttgggagacg
gaatggggactgctctgcgccaacgtaacagttataaacgagcaggcttctactcaaact
agtaagtcaaaaagttcgggtggcatctattgatcgaccaggataattagctagggc---
----------atttaacgagtgactggtgacat-gcaatgcagaactcccgttcccctcg
tagattcgtcgtacatagacagaatgccgagaaacgagcagggcccgtgtgtgtgagtgt
tcgtcctacgatccatttaggctgcgaatatgtcagattcaagtccataacctctcattc
gccttcggtcggggacagtaatgcgtctcgtcaggtgtattacctggcgtgcggtcttcg
ggctgggtgtcctactgacgtatgaaacttaagtgtcctttgcagggtagacggtcggca
gatagatgctgcttaattgccgtttatggaataatcaaagtagattactcaacgttctcg
gagggaattgtcgccacttgatgcccgaatggta
>SEQ1
aacagcccgagcggactcgaaagatttttattcgcttggctccgcttccgctcggcgctt
ggcggttgccacattagcggtgataagctgaactcaatagattttccaggattgcaaacc
tgc--------------------cgggcgtgttccaagacttacaacatataacaaagaa
ggaggacgagccctgactgacccaaggtatatcacgtaactctccggagtttcattcgtt
atctcaagtatcccgggctatagtatcaacatacgtcgtccttgttactaaacctcgatc
cagtggtacgtgcatcaccgacagcttgcgaacagctgtatacactgggtgggagggaag
gttaagttaaattcaaacactataatcccgagtggagatctggacagtaacggtaatgcg
tttgaaggaagggattcttatgaactcacagcgggactacgcttaacaagcctcct----
--------------cgactccgtgtttatgtgcacagagcaatagtcctttaaggacttc
ctaaactaatgcgtggctgagtgtcaagttggcagaatgcgcagtagaatttgggagacg
ggatggggactggtctgcgcc---------------------------------caaact
agtaagtcaaaaagtacgggtggcatctttcgatcgaccagggtaattagctagggc---
----------atttaacgagtgtctggtgacat-gcaatgcagaactcccgatcccctcg
tagattcgtcgtccatagacagaattccgagaaacgagcagggcccgtgtgtgtgagtgt
tcgtcctacgatccatttaggctgcgaatatgtccgattcaagtccctaacctctcattc
gccttcggtcggggacggtaatgcgtctcgtcatgtgtattacctggcgtgcggtcttcg
gcctgggtgtcctactgacgtatgaaacttcagtgtcctgtgcagggtagacggccgcca
gaaagatgctgtt---------------------------------------agttctcg
gaggggattgtcg---------------------
>SEQ2
aacagcccgtgaggtctcgaatgatcttcattcgcttagctccgcttccgcccggcacta
ggaggttgccatatttg------------------aatagattttccaggattgcaaagc
tgcccaaagatcagctcggagcacg----------------tacaacatataacaaagga
ggaggaccagcccggactgacccaaggtatatcacgtaactctccggagtttcattcgtt
atctcaagtatcccgggctatagtatcaacatacgtcgtccttgttactaaacctcgatc
cagtggtacgtgcat-----------------cagcagtatacaatgggtggcagtgagg
gataagttaaatt-------------------------tctggacagtaacggtaatgcg
tttgaaggaaggaattcttatgaactcacagcgggactccgcaaa---------------
--------------cgactccgtgtttatgtgcacagagcaatagtcagttaaggacttc
ctaaactaatgcgtggctgagtgtcaagttggcagaatgcgcagtagaatttgggagccg
ggatgg------------------------------------------------caaact
-------------------agggcatatatcgatcgagcag-------------------
------------------ggtgtctggtgtcat-gcaatgcagaactcccgattcgctcg
tagttcc-----------------------gagacgagcagggcccgtgtgtgtgagtgt
tcgtcctacgatccatttaagctgcgaatatgtccgattcaagtccctaacctctcattc
gccttcggtcggggacggtaatgcg-------------------------gcggtcttcg
gcctgggtgtcctactgacgtatgaaacttcagtctcacc-------------------a
gaaagacgct------------------------------------------agttctcg
gaggggattgtcg---------------------
>SEQ3
aacagcctgagcgaactcgaaaga---------------------------tcggcgctt
ggcggttgccacattagcggtgataagctgaactcaatagattttccagggttgcaaacc
tgc--------------------cgggcgtgtttcaagacttacaacatatcacaaagaa
ggaggacgagccttgactgacccaaggtatatcacgtaactctccggagtttcattcgtt
atctcaagtatcccgggctgtagtatcaacatacgtcgtccttgttactaaacctcgatc
cagtggtacgtgcac-----------------cagcagtatacaatgggtggcagtga--
-------------------------------------gtctggacagtaacagtaacgcg
ttggaaggaagcaattc-------------gcgggactccgcaaa---------------
--------------cgactccgtgtttatgtgcacagagcaatagtcctttaaggacttc
ctaaactaacgcgtggctgagtgtcaagttggcagaatgcgcagtagaatttgggagacg
agatgg------------------------------------------------caaact
------------------------------------------------------------
------------------agtgtatggtgtcat-gcaatgcagagctcccgattcagtcg
tagttcc-----------------------gagacaagcagggcccgtgtgtgtgagtgt
tcgtcctacgatccatttaagctgcgaatatgtccgattcaagtccctaacctctcattc
gccttcggtcggggacggtaatgcgtctcatcatgggtattacctggcgggcggtcttcc
gcatgggtgtcctactgacgtatgaaacttcattgtccct--------------------
----------------------------------------------------agttctcg
gaggggatcgtcg---------------------
>SEQ4
gacagactgatcgaactcggaaga---------------------------tccgtgctt
ggcggttgcctcattagcggtgaaaagctgaactcagtagatcatccagggttgcgaacc
tgc--------------------cgggcgtgtttcaagactgacaacatatcacaaagaa
ggaggacgacccttga----cccaaggtatatcacgtaactctccggagtttcattcgtt
atctcaagtatcccgggctatagtatcaacatacgtcgtccttgttactaaacctcgatc
cagtggtacgtgca------------------cagcagtatacaatgggtggcagtgagt
ctggagaaagcca-------------------------ttcgggggg-------------
------------------------------------------------------------
--------------ctactccgtgtttatgtgcacagagcaattgtcctttaaggacttc
ctaaactaatgcgtggctgagtgtcaagttggcagaatgcgcagtagaattttggagacg
ggatcgggactggtctgcgccaa-------------------------------------
-------------gtacgggtggcatctgt--------------aattagctagggc---
----------atttaacgagtgtctggggagat-gcaatgcagaactccccatcccatcg
taaattcgatgtccgtagacagaactctg-agaacgagcagggcccgtgtgtgtgagtgt
tcgtcctacgatccatttaggctgcgaatatgtgagattcaagtccataacctctcattc
gccttcggtcggggacagtaatgcgactcatctggtgtattacctggcttc---------
-------------------------aacttaggtgtcctttgcagggtagacgttcggca
gccagatgctgcttaattgccctttatggaataacctaagcagattactcaacgctctcc
ttgatgc---------------------------
>SEQ5
aacaggctgagcgaactcgaagga---------------------------tcggagctt
ggcggttgccacattaggggcgataagctgaactcaataaattttccagggttgcaaacc
tgc--------------------cgggcgtgtctaaagacttactacatatcataaagaa
ggaggacgagccttgactgacccaaggtatatcacgtaactctccggagtttcattcgtt
atctcaagtatcccgggctatagtatcaacatacgtcgtccttgttactaaacctcgatc
cagtggtacgtcga------------------cagcagcacacaatgggtggcagtgaat
ctcgagaaggcca-------------------------ttcgggagg-------------
------------------------------------------------------------
--------------ctactccgtgtttatgtgcacagagcaatagtcctttaaggacttc
ctaaactaacgcgtggctgagtgtcaagttggcagaatgcgcagtagaatttgggagacg
gaatgaggtccgctctgcgccaacgtaacagttataaacgcgcaggcttctagtgaaact
agcgggt--------------ggcatctgttgatcgacccggagaattagctagcgc---
----------atttaacgagagactggtgacat-gcaatgcagaactgccgttctcaatg
ccga--------------------------gaaacaagcagggcccgtgtgtgtgagtgt
tcgtcctacgatccatttaagctgcgaatatgtccgattcaagtccctaacctctcattc
gccttcggtcggggacggtaatgcgtcttgtcatgtgtattacctggcgttcggtctttg
gcatgggagtcctactcacgtatgaaacttccgtgtcctgtgcaaggttgacggctgcca
gaaagatgct------------------------------------------------cg
gaggggactgacg---------------------
>SEQ6
gacagcccgtgaggtctcgaatgatcttcattcgcttagccccgcttgcgccctgcacta
ggaggttgccatatttg------------------aatatattttccaggattgcaaagc
-----------------------------------------tacaacaaataa-------
----------cccgtactgacccaaggtatatcacgtaaccctccggagtttcattcgtt
atctcacgtatcccgggctatagtatcaacatacgtcgtacttgttactaaacctcgatc
cagtggtacgtggat------------------------------agggtggcagtgagg
gataagtttaact-------------------------tctggacagtaacggtaatgcc
ttagaagg-------------------acagcgggacttcgcaaa---------------
--------------cgactccgtgtttatgtgcacagagcaatagtcagttaaggacttc
ctaaactaatgcgtagctgagtgtcaagttggcagaatgcgcagtagaatttgggagacg
agatgg------------------------------------------------caaac-
----------------------------------------g-------------------
------------------agtgtatggtatcat-gcaatgcagagctcccgattcagccg
tagttgc-----------------------gagacaagcagggcccgtgtgtgtgagtgt
tcatcctacgatccatttaagctgcgaatatgtccgattcaagtccctaaccactcattc
gccttcggtcggggacagtaatgcg-------------------------gcggccttcg
gcctgggtgtcctactgacgtatgaaacttaaatctcccc-------------------a
gaaagacgct--------------------------------------------------
-gggggat--------------------------
>SEQ7
aaaagcccgtgaggtctcgaatgatcttcattcgctgagcttcgcttccgcccggg----
-----------------------------------aataaaatatccaggattgcaaatc
tgcccaaagatgagctcggcgcacg----------------------------------t
agaggactagcccggactgacccaaggtatatcacgtaactatccggagtttcattcgtt
atctcatgtattccgggctatagtatcaacatacgtcgtccttgtgactaaacctcgatc
gagtggtacatgctt-----------------cagacgaatacaatgggtggcagtgagg
cataagttaaatt-------------------------tctggac---------------
-----aggaaggaattcttaa---------------------------------------
--------------cgactccgtgtttatgtgcacagagcaatagtcctttaaggacttc
ctaaactaatgcgtggctgagtgtcaagttggcagaatgcgcagtagaatttgggagacg
agacgg------------------------------------------------------
------------------------------------------------------------
--------------------tatatggtatcat-gcaatgcagagcttccgcttcagccg
------------------------------tagtcgagcagggcccgtgtgtgtgagtgt
tcgtcctacgatccatttaggctgcgaatatgtgagattcacgtccataacctctcattc
gccttcggtcggggacagtaatgcc-------------------------gcgaccttcg
gcgtgggtgtcctactgacgtcccagaaagacgct-------------------------
------------------------------------------------------------
-gggggat--------------------------
>SEQ8
aaaagcccgttaggtctcgaatgatctacattcgatgagcttcgattcagcccgga--ta
aaataaaa----------------------------------------------------
-----------------------------------tgagctcggcgcacgtaga------
-------------ggactagcccaaggtatatcacgtaactctcctgagtttcactcgtt
atctcaagtatcccgggctgtagtatcaacatacgtcgtccatgttactaaacctcgatc
cagtggtacgtggat------------------------------agggtggcagtgagg
ga------------------------------------gctggttagtaacggtaatgcc
atagaagg-------------------acagccggacttcgcaaa---------------
--------------cgactccgtgtttatgtgcacagagcaatagtcctttaaggacctc
ctaaactaatgcgtggctgagtgtcaagttggcagaatgcgcagtagaatttgggagacg
ggatcgggactggtctgcgccaa-------------------------------------
----------------------------------------gtacgggcagcttctgtaat
tagctagagcgtttaacgagtgtctgatgagatggaatatcgtaaattcgatgtccgtag
acagaactctg-------------------agaacaagcagggcccgtgtgtgtgagtga
tcatcttacgatccatttaagctgcgaatatgtccgattcaagtccctaaccaatcattc
gccttcggtcggggacagtaatgcgg-------------------------cggcctgcg
gcctgggtgttctactgacggatgaactgtaaatctcccgagaaagacgctgggggat--
------------------------------------------------------------
----------------------------------
>SEQ9
taaagcccgttagctctcgaatgatct---------------------------ga--ta
aaataaaa----------------------------------------------------
-----------------------------------tgagctcggctcacgtaga------
-------------ggactagcccaaggtatatcacgtaactctccggagtttcattcgtt
atctcaagtatcccgggctatagtatcaacatacgtcgtccttgttactaaacctcgatc
cattagtacg-----------------------------------atggtggcagtgaag
ga------------------------------------gctggttagtaacagtaatgcc
atagaagg-------------------gcagccggacttcgcaaa---------------
--------------------cgtgtttatgtgcacagagcaatagtcctttaaggacttc
ctaaactaacgcgtggctgagtgtcaagttggcagaatgcgcagtagaatttgggagacg
ggatcgggactggtctgcgacaa-------------------------------------
----------------------------------------gtacgtgctgcttctgt---
----------gtttaacgagtgtct-----------------------------------
---------------------------------tcgagcagggcccgtgtgtgtgagtgt
tcgtcctacgatccatttaggctgcgaatatgtccgattcaagcccctaacctctcattc
gccttcggtcggggacagtaat---g-------------------------cggcctgcg
gcc---------------------gattgtaattctcccgagaacgacgctcggggtt--
------------------------------------------------------------
----------------------------------
>SEQ10
taaaaccctttagctctcgaatga------------------------------------
------------------------------------------------------------
-----gaaaatgagctcggctcacg----------------------------------t
agaggactag----------cccaaggtatatcacgtaactctccggagtttcattcttt
atctcaagtatcccgggctatagtatcaacatacgtcgtccttgttactaaacctcgatc
gagtggtacatgctt-----------------cagacgaatacaatgtgtgaca------
--------------------------------------tctggaa---------------
-----aggaaggaattcgt-----------------------------------------
--------------cgactccgtgtttatgtgcacagagcaatagtcagttaaggacttc
ctaaactaatgcgtggctgagtgtcaagttggcagaatgcgcagtagaatttgggagccg
agacgg------------------------------------------------------
------------------------------------------------------------
--------------------tatatggtatcct-gcaatgcagagcttccgcttcggccg
------------------------------tagtcgagcagggcccgtgtgtgtgagtgt
tcgtcctacgatccatttaggctgcgaatatgtccgattcaagcccctaacctctcattc
gccttcggtcggggacagtaatgcc-------------------------gcgaccttcg
gcgtgggtgtcctacagacgtc--------------------------------------
------------------------------------------------------------
--ggggat--------------------------
>SEQ11
aaaagcccgttaggtcttgaatgatccacattcgatgagctccgattcagcccgg-----
------------------------------------------------------------
-------------------------------------------------ataaaataaaa
tgagctcggcggaggactagcccaaggtatatcacgtaactctccggagtttcattcttt
atctcaagtatcccgggctatagtatcaacatacgtcgtccttgttactaaacc---atc
gagtggtacatcc-------------------cagacgaatacaatctgtgacatgtgga
aaggaaggaattc-----------------------------------------------
------------------------------------------------------------
------------------gtcgtgtttatgtgcacagagcaatagtcagttaaggacttc
ctaaactaatgcgtggctgagtgtcaagttggcagaatgcgcagtagaatttgggagacg
agatcgggactggtctacgacaa-------------------------------------
----------------------------------------gtacgtgccgcttctgt---
----------gtggaacgagtgtct-----------------------------------
---------------------------------tcaagcagggcccgtgtgtgtgagtgt
tcgtcctacgatccttttaagctgcgaatatgtccgattcaagtcgctaacctctcattc
gccttcggtcggggacggtaatgcgtctcgtcaggtgtattacctggcgtgcggtcttcg
gcctggg-------------------acttcagtctcctgtactgggtagagcgccgcca
gaaagatgctgttagttctcggaggg----------------------------------
----------------------------------
>SEQ12
taaaaccctttagctctcg-----------------------------------------
------------------------------------------------------------
-----gaaacggagctcgccttacg----------------------------------t
aaaggagtag----------cccaaggtatatcacgtaactctcctgagtttcactcgtt
atctgaagtatcccgggctgtagtatcaacatacgtcgtccatgttactaaacctcgatc
cagtggaacgtgcat------------------------------------gcagtgagg
gataagataaatt-------------------------tctggacagtagcggtaatgcg
tttgaaggaaggcatccttatgaactcacagcgggactccgccca---------------
--------------cgactccgtgtttatgtgcacagagcaatagtcagttaaggacttc
ctaaactaatgcgtggctgagtgtcaagttggcagaatgcgcagtagaatttgggagacg
agacgg------------------------------------------------------
------------------------------------------------------------
-------------------------------------ttgcagagcttccgcttcggagg
------------------------------tcgtcaagcagggcccgtgtgtgtgagtgt
tcgtcctacgatccatttaagctgcgaatatgtccgattcaagtccctaacctctcattc
gccttcggtcggggacagttatgtc-------------------------gcgaccttcc
tcgtgggtgtcctacagacgccggggat--------------------------------
------------------------------------------------------------
----------------------------------
>SEQ13
aaaaccccgttaggtctcgaatgatatacattcgatgagcttcgattcagcccagc----
------------------------------------------------------------
-----taaaatgaactc-------------------------------------------
--------------------cccaaggtatatcacgtaactctccggagtttcattcgtt
atctcaagtatcccgggctatagtatcaacatacgtcgaccttgttactaaacctcgatc
gagtggtacatgcct-----------------cagacgaatacaacgggtgtaagtgagg
cataggctaaatt-------------------------tctggac---------------
-----ag---------ctt-----------------------------------------
--------------cgactccgtgtttatgtgcacagagcaatagtcagttaaggacttc
ctaaactaatgcgtggctgagtgtcaagttggcagaatgcgcagtagaatttgggagacg
acacgg------------------------------------------------------
------------------------------------------------------------
--------------------tatctggtatcat-gcaatgcagagcttccgcgt------
---------------------------------acgagcagggcccgtgtgtgtgagtgt
tcgtcctacgatccatttaggctgcgaatatgtccgattcaagtccctagcctctcattc
gccttcggtcggggacagtaatgcg-------------------------gcggccttct
gcgtgagggtcctactgacgtatgaaacttaaatc-------------------------
------------------------------------------------------------
-ac-------------------------------
>SEQ14
aaaagcccgtgaggtctcgaaggatcttcattctctgagcttcgcttccgcccgggatta
aaatatcg----------------------------------------------------
-----------------------------------aggattccaaatctgcccaaagatt
tgaggactagcccggactgacccaaggtatatcacgtaaccctccggagtttcatgcgtt
atctcacgtatcccgggctatagtatcaacatacgtcgtacttgttactaaacctcgatc
cattagtacg-----------------------------------atggtggcagtaaag
ga------------------------------------gctggttagtaacagtaatgcc
atagacgg-------------------gcagccggacttcgcaaa---------------
--------------------cgtgtttatgtgcacagagcaatagtcagttaaggacttc
ctaaactaatgcgtggctgagtgtcaagttggcagaatgcgcagtagaatttgggagacg
ggat--------------ggcaa-------------------------------------
----------------------------------------actagggcatatgtcga---
----------tcgagaagggtgtccgattcgctcgtatttccgag---------------
---------------------------------acaagcagggcccgtgtgtgtgagtgt
tcgtcctacgatccatttaagctgcgaatatgtccgattcaagtccctaacctctcattc
gccttcggtcggggacggtgatgcgacttgtcatgtttattacctggcgttcggcctttg
gcacgggagtgtcctgtgc-----aaggttgacgcctgccagaaagatgctcggtgagga
ctgacg------------------------------------------------------
----------------------------------
>SEQ15
aaaagcccgtgtggtctcgaaggatcttcatgctcttatcatcgcttccgcccgcgggtg
cccaa-------------------------------------------------------
-----------------------------------------------------------a
gatggactagcccggactgacccaaggtatatcacgtaactctccggagtttctttcttt
atctcaagtatcccgggctatagtatcaacatacgtcgtccttgttactaaaccttgatc
cagtggtacgtg-------------------------gtatacaatcggtggcagtgagt
ctggagaaagcca-------------------------ttcgggggg-------------
------------------------------------------------------------
--------------ctactccgtgtttatgttcacagagcaatagtcagttaaggacttc
ctaaactaatgcgtggctgagtgtcaagttggcagaatgcgcagtagaatttgggagccg
gcatggggactgctctgcgacaacggaacacttataaacgagcaggcttctactcaaact
agtacgtcaaaaagttggggcagcatctattgatcgaccaggatacatagctatggc---
----------atttaacgagtggctggtgacac-gcaatgcagaactcccgttccgctcg
tgggttcctcgtacatagacagaatgccgagaaacgagcagggcccgtgtgtgtgagtgt
tcgtcctacgatccatttaggctgcgaatatgtccgattcaagcccctaacctctcattc
gccttcggtcggggacagtaatgcg-------------------------gcggcctgcc
gcctggaactgtaaatctcccaagaaa---------------------------------
----gacgctgtgggat-------------------------------------------
----------------------------------
>SEQ16
aacagccggtgcgttctcgaataagcttcattcgagtagctccgctcccgcccggcactt
ggcggttcccatatt-------------------------------caggagtgcaagcc
gacccaacgatcagctcggtgcacgggcgtgagccaacacgtacaacatataacaaat--
--------------------cccaaggtatatcacgtaactctccggagtttcattcgtt
atctcaagtatcccgggctatagtatcaacatacgtcgtccttgttactaaacctcgatc
gagtggtacttgc-----------------------------------------------
------ttaatgt----------------------------------ttgacat-ctgga
agtgaaggaattcctcc-------------------------------------------
----------------actccgtgtttatgtgcacagagcaatagtcagttaaggacttc
ctaaactaatgcgtggctgagtgtcaagttgtcagaatgcgcagtagaatttgggagacg
gcatgggaactgctctgcgacaactgaacacttataaccgagc-----------caaact
ag----------------ggcagcgtctattgatcgaccaggatacatagctatcgc---
----------atttaacgagtggctggtgacac-gcaatacagaactcgtgttccgctcg
tggggtcctcgta-----------------gatacgagcagggcccgtgtgtgtgagtgt
tcgtcctacgatccattttggctgcgaatatgtcagattcaagtccataacctctcattc
gccttcggtcggggacagtaacgcg-----------------------------------
----------------------ggggcctgcggcctggtatag-----------------
------------------------------------------------------------
----------------------------------
>SEQ17
gacagcccgtgagg-----------------------agccccgcttgcaccctgcacta
gggggttgccatatttg------------------aatatattttccaggattgcaaagc
tac---------------------------------------------------------
-aagaaataacccgtactgacccaaggtatatcacgtaactctccggagtttcattcgtt
atctcaagtatcccgggctatagtatcaacatacgtcgtccttgttactaaacctcgatc
ccgtgctacgt---------------------cggcagcatctcaagtat----------
--------------------------------------tcgggagg--------------
------------------------------------------------------------
--------------ctactccgtgtttatgtgcacagagcaattgtcctttaaggacttc
ctaaactaatgcgtggctgagtgtcaagttggcagaatgcgcagtagaattttggagacg
tgatgg------------------------------------------------caaact
agggcgt-----------------------------------------------------
------------------atagtcaggtgtaat-gccaagcagtcctcccaattcgctcg
tag-------------------------------caagcagggcccgtgtgtgtgagtgt
tcgtcctacgatccatttaagctgcgaatatgtccgattcaagtccctaacctctcattc
gccttcggtcggggacagtaatgcg-------------------------gcggccttct
gcgtgagagtcctactgacgtatgaaacttaaat--------------------------
------------------------------------------------------------
----------------------------------
>SEQ18
ataagcgcgttaggtctccaatgatctacatacgataagcttcgcttctgcccgg-----
-----------------------------------------------------ataaagt
aa------aatgagcgcggcgcacgtagaggact----------------------at--
--------------------cccaaggtatatcacgtaactctccggagtttcattcgtt
atctcaagtatcccgggctatagtatcaacatacgtcgtccttgttactaaacctcgatc
cagtggaacgcgcat---------------------------------------ttgagg
gataagataaagt----------------------------------ttgcggtaatgcg
tataaaggtaggcctccttatgaacttacagctggactccgcccc---------------
--------------cgactccgtgtttatgtgcacagagcaatagtcagttaaggacttc
ctaaactaatgcgtggctgagtgtcaagttggcagaatgcgcagtagaatttgcgagacg
ggaagggaactgctctgcgacaactgaacactgataaccgagc-----------caaact
ag----------------ggcaccgtctattgatcgatcaggatacatagctctcgc---
----------atttaacgagtggctggtgtcac-gcaatacaagactcgggttccgctcg
tggggtcctcgta-----------------gatacgagcagggcccatgtgtgtgagtgt
tcgtcctacgatccattttggctgcgaatatgtcagattcaagtccataacctctcaatc
gccttcggtcggggacggtaatgcgtctagtcatgggtaatagc----------------
---tgggtgacttactgacgtatgaaacttcagtctggcgtccagatagatgatgtttct
cggaggggctt-------------------------------------------------
----------------------------------
>SEQ19
aaaagcc----------------atccacattcgacgggctccgattcagcccgg-----
------------------------------------------------------------
-------------------------------------------------ataaagtaaaa
ggagctcggcggaggactagcccaaggtatatcatgtagctctcctgagtttcactcgtt
atctgaagtatcccgggctgtagtatcaacatacgtcgtccatgttactaaacctcgatc
ccgtagaacgtgcat---------------------------------------------
-------------------------------------------------------gcagt
ttcgcaggaacgcctccttatgaacccacagggggactcgtgcca---------------
--------------cgactcagtgtttatgtgcacagagcaatagtcctttaaggacttc
ctaaactaacgcgtggctgagtgtcaagttggcagaatgcgcagtagaatttgggagacg
gaaagaggtccgctctgcgccaacgtaacagttataaacgcgcaggcttctagtggaaca
agc-------------------------------------gggaggcaactggtcgc---
----------atttaacgatacactggtcaaatctcaatgccga----------------
------------------------------gatacgagcagggcccgtgtgtgtgagtgt
tcgtcctacgatccatttaggctgcgaatatgtgagattcacgtccataacctctcattc
gccttcggtcggggacagtcatgcc-------------------------gcgaccttcg
gagtgggtgtcccacagacgtggat-----------------------------------
------------------------------------------------------------
----------------------------------
