>SEQ0
atggagcgacaaacccctcaggtcctacatgtactaacagttgcgctcacgtagtagccg
ctggcaccagcaagaacgaagctagccccatatgctgccggctaatgctcatgacgctcg
ctgagctctgagtgcggttccttgtcgcgccccgcaacagattcgaaaatgaggtccaac
gcctgttcctgtttcctgctaacttttaccaatgtcttatatcaccagcccatagtcttt
ccgacggtcaccgtaccgaaacgttagtggcccaaacggctagctgttatcttctactgg
aacctgaccggtgagtgcacatatagacacatgcggatgctgggcttcagttttcacgta
cctatgagtcgagaagagtactgtctcaagcagactgtcagtttgcggttcttcaaaagt
ttttggagcgacgttattcgggttaagctcatacagctgatgagcgtaacctttcgcggg
cacttaaagaacgaagagaacagttagcggaaagttactgatttgaaccgcataatccgg
ctctgctactccataatcgactgatgaaatggtttatgattcgcctatgcccgagtcgtg
gctgtggtctagtgcaccccctgcgtacgctagtatgttctcttgcggggggggatatgg
gaacttaagtcgtcctccatgcccaatatagactcgccagcgcgagacgccttgacgggt
gtctactccaaccatgcccgggactgatttcatccatctgatgagagcataatagggtct
ctggttacggagattgtctgaagagcgctggggcgggattggcaggcgtgccgagcatag
gtagtaactaggtcccaggctggtcttgttcgggctatagactagaatttctgctctccc
tgtgtcgctag---------------------gccgttttgcccatgcgatacaaaggct
attgaaccaggggtttccttaaccatgagacacaaatcccg----ctaagcagcgttaaa
c---------ttacaggcatgatactggtgccgctccgtatcgctcaagcaaggacttta
cctcgctcaacccgactgaaagttttcacaatccccacctagagaaacaacgtt
>SEQ1
atggagcgctaaacccctcaggtcctacatgtactaacagttgt----------------
------------------------gccccatatgctggcggttaatgctcatgacgctcg
ctgagctctgagtgcggttcctagtcgcgcccctcaacaaattctaatatgaggtccaac
ccatgttc-------------acttttaccaatgtcttatatcaccagcccatagtcttt
ccgacggtcaccgtaccgaaacgttagtggcccaaacggctagctgttatcttctactgg
caccggaacagtcagtgcacatatagacacatgcggatgctcggcttcagttttcacgta
cctttgagtcgataggagtactgtctcaagcagactgtcagttcgcggttcttcaaaagt
ttttgcagcgacgttattcgggttaa-------------------gtaacctttcgaggg
cacttaa---------aaaacagttagcggaaagttactgatttgaaccgcataatccgg
ctctgctactccataatcgactgatgaaatggtttatgattcgcctatgcccgagtcgtg
gctgtcgtctag----------------gctagtatgttctcttgcgggggtggatatgg
gaactaaagtcgtc--------------------cgccagcgcgagacgccttgacgggt
gtctactacaataatgcccgtgactgatttcatccatctgatgagagcataataggg---
-----------------ctgaagagcgctggggcgggattggcaggcgtgccgagcatag
gtagtaactaggtcccaggctggtcttgttcgggctatagactagaatttctgctctccc
tgtctcgctcg---------------------gccgttttacccatgcgatacaaaggct
attgaaccagtggtttccttaaccaagagacac------------------------aaa
c---------ttacagggatgatactggggccgctccatatcgctcaagcaaggacttta
cctcgatc---------------------------------gagcaacaagatt
>SEQ2
atggagcgacaaacccctcaggtcctacatgtactaacagttgcgctcacgtagcagccg
ctggcaccagcaagaaggaagctagccccatattctgccggcaaatgctcatgccgctcg
ctgcgctctcagtgcggttccttgtcgctcccggc------------------g-acaga
ttcgaaaatgatttcctgctcacttttaccaatgtcttatatcaccaacccttagtcttt
ccgacggtcaccgtaccgaaacgttagtggcccaaacggctagctgttatcttctactgg
cacccgaacagtcagtacacatatagaaacatgcgga-----------------------
------------------ttctgtctcacgcagactgtcagttcgcggttattcaaaagt
ttctgcagcgacgttattcgggtcaa-------------------gtaaactttcgatgt
cagttaa---------aaaacagttagcggaaagttactgatttgaaccgcataatccgg
ctctgctactccataatcgactgatgaaatggtttatgattcgcctatgcccgagtcgtg
gctgtgatatagtgcacccccttcgtacgctagtatgttctcttgcggggggggatatgg
gaacttaattcgtcctccatgcccaatctagactagccagggcgagacgcgttgacgggt
gtctactccaaccatgcccggcactgttttcattcatctgatgagagcataataggagct
ctggttacggagatcgtctgaagagcgctggggcgggattggcaggcgtgccgagcatag
gtagtaactaggtcccaggctggtcttgttcgggctatagactagaatttctgctctccc
tctg--------------------------------------------gatacaaaggct
tttgaaccaggggtttgcttaaccatgagacacaaatcccg----gtaaggagcgttaaa
c---------ttacagtcatg-------------------------aagcgaggactttc
cctcgctcaatccgactgaaagttttcacaaaccacacct--------------
>SEQ3
atgcagcgacaaacccctcaggtcctacgtgtactaacatttgcgctcacgtagtagccg
ctggcaccagcaagaa-----------------------cgctaatgctcatgacgctcg
ctgagctccgagtgcggttccttgtcgcgccccgc------------------atccagc
gcctgttcctgttccctgctcacttttaccaatgtcttatatcaccaacccttagtcttt
ccgacggtcaccgtaccgaaacgttagtggcccaaacggctagctgttatcttctactgg
taccccaacggtc--------------aacatgcgga-----------------------
------------------ttctgtatcacgtagactgtcagttcgcggttattcaaaaat
-------------ttagtcgggacaa-------------------gtaaactttcgattt
cagttaa---------aaaacagttagcggaaagttactgatttgaaccgcataatccgg
ctctgctactccataatcgactgatgaaatggtttatgattcgcctatgcccgagtcgtg
gctgtggtctagtgcaccccctgcgtacgctagtatgttcacttgcggggggggatatgg
gaacttaagtcgtcctccatgcccatt---------------------acattgacgggt
gtctactccaaccatgcccgggactcatttcatccatctgatgagggcataagagggtct
ctg---------------tgaagagcgctggggcgggattggcaggcgtgccgagcatag
gtagtaactaagtcccaggctggtcttgttcgggctatagactagtatttctgctctccc
tctg--------------------------------------------gatacataggct
tttgaaccaggggtttgcttaaccatgagacacaaatcccg----gtcaggagcgttaaa
c---------ttacagtcacg-------------------------aagcgaggactttc
ccacgctctatccgactgtaagttttcacaaaccacacca--------------
>SEQ4
acgcagcgataatcccctca-----------------------------cgtaggagcgg
ctggcaccagcgagaa-----------------------cgctaatgctcatgacgctcg
ctgg-------------------------------------------------gtccaac
gcctgttcctgtgccctgctaacatttaccaatgtcttatatcatcagcccatagtcttt
ccgacggtcaccgtaccgaaacgttagtggcccaaacggctagctgttatcttctactgg
aacctgaacggt-----------tagacacatgcagatgatgggcttcagtcttcacgta
cctttgagtcgagaagagtactgtctcaagca------------------tttcaaaagt
ttttggagcgacgttattcgggttaagctcatacagctg------atgagcgtacgaag-
----------------agaacagttagcggaaagttactgatttgaaccgcataatccgg
ctctgctactccataatcgactgatgaaatggtttatgattcgcctatgcccgagtcgtg
gctatcgtctag----------------gctagtatgttcccttgcgggggtggatatga
gaacaaaagtcgtc--------------------cgccagcgagagacgccttgacgggt
gtcttctagaatcatgccggtgactcaatt------------------ataataggg---
-----------------atgaagagcgctggggcgggattggcaggcgtgccgagcatag
gtagtaactaggtcccaggctggtcttgttcgggctatagactagaatttctgctctccc
tctg--------------------------------------------gatacaaaggct
tttgaaccaggggtttgcttaaccatgatacacaaatcccg----ggaaggagcgttaca
c---------ttacagttatg-----------------------------------tttc
cctcgctcactccgactgacagctttcacataccactcct--------------
>SEQ5
atggagcgacaaacccctcaggtcctacatgtactaacagttgcgctcaggtagcagccg
ctggcaccag-----------------------------------tgctcatgccgctcg
ctgcgctctcagtgcggttccttgtcgctccgggccaccgattcgaatatga--------
-----------tttcctgctcacttttaccaatctcttatatcaccagcccatagtcttt
ccgacggtcaccgtaccgaaacgttagtggcccaaacggctagctgttatcttctactgg
caccggaacagtcagggcacttatagacacatgcggt----------------------a
ccgttcagtcgataggagtattgtctcaagcagactatcagttcgcggttcttcaaaagt
tttcgcagccacgttattcgggttaa-------------------gtaaactttggaggg
cacttaa---------aaaacagttagcggaaagttactgatttgaaccgcataatccgg
ctctgctactccataatcgactgatgaaatggtttatgattcgcctatgcccgagtcgtg
gctgtggtctagtgcaccccctgcgtacattagaatgttcgcttgctggaggggatatgg
gaacttaagtcgtcctccatgcccaacatagact---------------ccttgacgtg-
----------------------actgatttcttcgatctgatgagaggataatggggtct
ctggtgacggagattgtctcaagagcgctggggcgggattggcaggcgtgccgagcatag
gtagtagctaggtcccaggctggtcttgttcgggctatagactagaatttctgctctccc
tctg--------------------------------------------gatacaaaggct
tctgaaccaggggtttgcttaaccatgatacacaaatcccg----ggaaggagcgttaga
c---------ttccagttat----------------------------------------
-----------ccgactggcacctttcacatacgactcct--------------
>SEQ6
atgcagcgataatcccctc-----------------------------acgtaggagcgg
ttggcaccagcgagaa------------------------------------------cg
tgacgcttccatcgcgtgttccggtgccc-------------------------------
----------------tgctaacatttaccaatgtcttatatcataagcccatagtcttt
ccgacggtcaccgtaccgaaacgttagtggcccaaacggctagctgttatcttatactgg
cagccggacagtaagtacacata-------------------------------------
----------tagaaacttgctgtctcacgcagattgtcagttcgcggttattaaaaagt
ctctgcatcgacgttattcgggtcaagtaaactttagatgtcagttaaa-----------
-----------------aaacagttagcggaaagttactgatttgaaccgcataatccgg
ctctgctattccataatcgactgatgaattggtttatgattcgcctatgcccgagtcgtg
gctgtggtctagagcgccggctgcgtacgcgagtttgttcactagcctggtgggaaatag
gaaattaagtc--------------------------------------caatgacgggt
gtctactccaaccatgccttggactcctttcacccatctgatgagggcacaagagggtct
atg---------------tgaagagcgctggggcgggattggcaggcgtgccgagcatag
gtagtagctaggtcccaggctggtcttgttcgggctatagactagaatttctgctctccc
tgtctcgctcg---------------------gcctttttatccatgcggttaggaggct
attgaacccgtagtttgcttaacc-----------------------------------a
c---------ttacagggatgatactggggccgctcgatatcgctcaagcaaggacttta
cctcgatcgagcaacaagatt---------------------------------
>SEQ7
atggagctacaatcgcctcaggtcctacatgtcctaacagttgggatcacgtagcagccg
ctggcacccgaaagaaggaagctagcg------------------ccctcatgccgttcg
ctgcgctctcagtgcggatccttgttgctgccggctacagtttcgaaaatga--------
-----------tttcatgctcacttttaccaatctcttatatcaccagcccatagtcttt
ccgacggtcaccgtaccgaaacgttagtggcccaaacggcaagctgttatcttctactgg
aacctgaccggtgaatggacaaatagaaacatgcggatgcagggctactgttttcacgta
cctatgagtcgagaaaagtactgtctctagcagactgtcagtttgcggttctgcaaaagt
ttttggagcgacgttaatcgggttaagctcatacagctgatgagcgtaacctttcgcggg
cacttaaagaacgaagataacagttagcggaaagttactgatttgaaccgcataatccgg
ctctgctactccataatcgactgatgaaatggtttatgattcgcctatgcccgagtcgtg
gctgtggtctagtgcaccccctgcctacgc------------------------------
--tattaagtcgtccgcgatgcccatt---------------------acattgacgggt
gtctactccaaccatgcccgggac---------------------agcattagaggggct
ctg---------------tgaagagcgctggggcgggattggcaggcgtgccgagcatag
gtagtagctaggtcccaggctggtcttgttcgggctatagactagaatttctgctgtccc
tctctcgctcg---------------------ggctttttatccatgcggttaggaggcc
attgatcccgtagtttgcttaacc-----------------------------------a
c---------tgccagggatgatactggggccactcgatttcgctcaagaaaggacttta
cctcgatcgagctgcaagatt---------------------------------
>SEQ8
acgtagcgatcacccc--------------------------------------------
--gaagccagcgagaa-----------------------cgctaatgctcatgacgctca
ctggggtcgtag------------------------------------------------
-cctgttcctgtgccctgctcacttttaccaatgtcttatatcaccaacccttagtcttt
ccgacggttaccgtaccgaaacgttagtggcccaaacggctagctgttatcttctactgg
cagccggacagtaagtggacatat------------------------------------
--------------------ctgtctca----------------------cttaaaaagt
ctctgcatcgaagttattcgggtcaa-------------------gtaaactttagatgt
cagttaa---------aaaacagttagcggaaagttactgatttgaaccgcataatccgg
ctctgctactccataatcgactaatgaaatggtttatgattcgcctatgcccgagtcgtg
gctatcgtctag----------------gctagtgtgttcccttgcgg------------
-------agtcgtc--------------------cgccagcgagagacgcgttgactgg-
------------------------------------------------------------
------------attatatgaagagcgctggggcgggattggcaggcgtgccgagcatag
gtagtaactaggtcccaggctggtcttgttcgggctatagactagaatttctgctctccc
tgtggcgctag---------------------gccgttttacccatgcgagacaaaggct
at------------------------gagacacaaatcgc--------------------
---------------gctatgatactggtgccgctccgtctc------------------
----------------------tcatcacaatccccac----------------
>SEQ9
gtgcagcgataatcccctc-----------------------------atgtaggagctg
ttggcaccagtaagaa------------------------------------------cg
tgacgcttccatggcgtgaaccgg------------------------------------
-----------tgccctgctcacttttaccaatgtcttatatcaccaacccttagtcttt
ccgacggtcaccgtaccgaaacgttagtggcccaaacggctagctgttatcttctactgg
cagccgtacagcatgtcgacg---------------------------------------
----------------------gtctca----------------------cttaaaaagt
ctctgcatcgaagttattcgggtaaa-------------------gtgaaccttagatgt
cagttaa---------agaacagtcagcggaaagttactgatttgaaccgcataatccgg
ctctgctactccataatcgactaatgaaatggtttatgattcgcctatgcccgagtcgtg
gctgtgctctactgcaccccctgcatacattagagtgttc--------------------
----ttaagtcggcctccatgcac------------------------------------
----------aacatagacgtgactgatttcttcaaactgataagaggataatggggtcc
ctggtgacggagattgtctcaagaccgctggggcgggattggcaggcgtgccgagcatag
gtagtaactaggtcccaggctggtcttgttcgggctatagactagaatttctgctctccc
tctg--------------------------------------------gatacatattct
tttgaac------------------------acaaatcgcg----gtcaggagccttaaa
c---------ttacagtcacg------------------------------aggcctctc
ccacgctctatccgactgtatgttttcacaaaccacccca--------------
>SEQ10
ctggagctacactcgcttcaggtcatacatgtcctaacagttgggatcatctagcagccg
ctggcacccgaaagaaggaagatagcg------------------ccttcatgccgttcg
ctgc----------------tctgttgccgccggctacagtttcgaaaatga--------
-----------ttgcatgctaacttttaccaatgtcttatatcaccagcccatagtcttt
ccgacggtcaccgtaccgaaacgttagtggcccaaacggctagctgttatcttctactgg
agcttgaccggttaatggacaaatagacacatgcggaggcaggggtactgttttcacgta
cctatgtgtcgagaaaagtactgtctttagcagactgtcagtttgcggctctgcaaaag-
----------------atcggattaagctcatacagctgatgagcggaacctttcgcgg-
-----------------taacagttagcggaaagttactgatttgaaccgcataatccgg
ctctgctactccataatctactgatgaaatggtttatgattcgcctatgcccgagtcgtg
gctgtgctccactgctaccctac-------------------------------------
------------------------------------------------------------
----------aacatagacgtgactgatttcttcaaactgataagaggataatggggtcc
ctggtgacggagattgtctcaagagcgctggggcgggattggcaggcgtgccgagcatag
gtagtaactaggtcccaggctagtcttgttcgggctatagactagattttctgctctccc
tctg--------------------------------------------------------
-----------------cttaaccatgagacacaaatcccg----gtcagcagcgttaaa
c---------ttacagtc------------------------------------------
----------------------ttttcacaaaccacacca--------------
>SEQ11
ctgcagcgacaaacccctccggtcctacgtgaactaacatctgc----------------
---gctcccgctagaa--------------------------------------cgctcg
ctgacctctaagtgcggttccttgtcgcggcccgg------------------atccggc
ggcgggccctgttccctgctcacttttaccaatgtcttatatcaccaacccttagtcttt
ccgtcggtcaccgtaccgaaacgttagtggcccaaacggctagctgttatcttctactgg
tatcccaacggtcaacatgcgga-------------------------------------
------------------ttctgcaccccgtagactgtaagttcgctgtta---------
------------------cgggacaa-------------------ctaaactttcgattt
tagtcga---------aagacagttagcggaaagttactgatttgaaccgcataatccgg
ctctgctactccataatcgactgatgaaatggtttatgattcgcctatgcccgagtcgtg
gctgtggactagagcgccggcagggtacgtgagtgtgttcactagcctggtgggaaatag
gaaattaagtc--------------------------------------caatgccgggc
gtctactccaaccatgccttggactcctttcacccatctgatgagggcacaagagggtct
att---------------gcaagagcgctggggcgggattggcaggcgtgccgagcatag
gtagtaactaggtcccaggctggtcttgttcgggctatagactagaatttctgctctccc
tgtggcgctag---------------------gccgttttacccatgcgagacaaagact
aat---------------------------------------------------------
--------------------------------------cgcgctagcatactggtgccgc
tccttctcaagtcacagtctacac------------------------------
>SEQ12
atggagcgctaaacccctcaggtcctacatgcccca------------------------
------------------------------tatgctggcggttaatgctcatgacgctcg
ctgacctatgagtttggttcctagtcgcgcccctcaacaaattctaatattaggtccaac
-------------ccatgttaacttttaccaatgtcttatatcaccagcccctagtcttt
ccgacggtcaccataccgaaacgttagtggcccaaacggctagctgttatcttctactgg
cagttggacagtaagtggacct--------------------------------------
------------------ttctgtctca-----------------------ttaataagt
ctctgaatggaaattattcgggtcaa-------------------ggaaattgtagatgt
cagtaaa---------aaagcagttagcggaaagttactgatttgaaccgcataatccgg
ctctgctactccataatcgactgatgaaatggtttatggttcgcctatgcccgagtcgtg
gccgtggtccagagcgccggctgcgtacgcgagtttgttcactagcctggtgggaaatac
gaacttatgtc--------------------------------------caatgacaggt
ttctacaccaagtatgccttggactcctttcacccatctgatgagggcacaacagggtct
atg---------------cgaagagcgcttgggcgggattggcaggcgtgccgagcatag
gtagtaactaggtcccaggctggtcttgttcgggctatagactagaatttctgctctccc
tgtctcgctcg---------------------gccgttttaccca---------------
--tgaaccaatggtttcctcaaccaagaggcagaa------------------------a
c---------ttacagggatgatactggggccgctctatatcgctcaagcaaggacttta
cctcacaagatt------------------------------------------
>SEQ13
------------------------------------------------acgtagagatca
ccccagccagcgagaacg----------------------------------------ca
ctggggtcgtag--------cctgttcctgtggtc-------------------------
----------------tgctaacttttaccaatgtcttatatcaccagcccctagtcttt
ccgacggtcaccataccgaaacgttagtggcccaaacggctagctgttatcttctactgg
cagcccgacagcaagtacacaca-------------------------------------
----------aagaaatttgttgtcacacgcagattgtcagttcgcggttataaaaaagt
ctctgaatcgaccttattcgggt-------------------------------------
-----------------caacagttagcggaaagttactgatttgaaccgcataatccgg
ctctgctactccataatcgactgatgaaatggtttatgattcgcctatgcccgagtcgtg
ccggtggtctagtgcaccccctg----ccc------------------------------
--tctgaggtcgt------------------------------------cattgacgggt
gtctactccaaccatgcccgggac---------------------agcattagaggggct
ctg---------------tgaagagcgctggggcgggattggcaggcgtgccgagcataa
gtagtaactaggtcccaggctggtcttgttcgggctatagactagaatttctgctctccc
cctctcgctcg---------------------ggctttttatccatgcggttaggaggcc
attgatcccgtagtttgtttaacc-----------------------------------a
c---------tgccagggatgatactggggccactcgatttcgctcaagaaaggacttta
cctcgatcgagctgcaagatt---------------------------------
>SEQ14
atggagcgacaaaccccaggggtcctacttgtactaacagttgcgctcacgtagcagccg
ctggcaccagcaagaagcaagatagccccatattctgccggcaaatgctcatgccgctcg
ctgcgcactcagtgcggttccttgtcgatcccggcgacagattcgaaaatga--------
--------------------cacttttaccaatctcttatatcaccagcccatagtcttt
ccgacggtcaccgtaccgaaacgttagtggcccaaacggcaagctgttatcttctactgg
taccccaacgat--------------------gcggatgtcgta---------------t
caatttagtggggacaacta----------------------------------------
----------------------------------aactgtcgattgca------------
-----------ggtaaaaaacagttagcggaaagttactcatttgaaccgcataatccgg
ctctgctactccataatcgactgatgaaatggtttatgattcgcctatgcccgagtcgtg
gttgtgctccactgctaccc-ac-------------------------------------
------------------------------------------------------------
----------aacataggcgtgactgatttcgtgtaactgataagaagataatggtgtcg
ctggt---------------aagagcgctggggcgggattggcaggcgcgccgagcatag
gtagtagctaggtcccaggctggtcttgttcgggcgatagactagaatttctgctctcgc
actggatacat-------------------------------------------------
-------------------ttttttttgaacacaattcgcg----ggcaggagccttaat
c---------ttacagttacgag-------------------------------------
------------------------------------------------------
>SEQ15
atggagctacaatctcctcaggtcctacatgtcctaacatttggtatcacgtagcagccg
ctggcacccgaaagaaggaatctagcg------------------cgctcatgccgttcg
ctgcgctcgcagtgcggatccttgctgctgccggctacagtttcgaaaagga--------
-----------tttcatgccaacttttaccaatgtcttatatcaccagcccctagtcttt
ccgacggtcaccataccgaaacgttagtggcccaaacggctagctgttatcttctactgg
agcttgaccggttaatggacaaatagacacatgcggaggcaggggtactgttttcacgta
cccaagtgtcgagaaaagtactgtcattagcagactgtcagtttgcggctctgca-----
----------------------ttaagctcatacagatgatg------------------
-----------------taacagttagcggaaagttactgatttgaaccgcataatccgg
ctctgctactccataatcgactgatgaaatggtttatgattcgcctatgcccgagtcgtg
ccgttggtctactgcacccccag-------------------------------------
------aggtcgt------------------------------------cattgacgggt
gtctactccaaccatgcccgagat---------------------agctttagaggggct
ctg---------------tgaagagcgcttgggcgggattggcaggcgtgccgagcatag
gtagtaactaggccccaggctggtcttgttcgggctatagactagaatttctgctctccc
tctctcgctcg---------------------agctttt----------------aggcc
attgatcccgtagtttgcttaacc-----------------------------------a
c---------tgccagggttgatac--------------ttcgctaaagataggacctta
cctcgatcgagcttct--------------------------------------
>SEQ16
ctgcagggacaaacccctccggtcctacgtgaaataacatctgc----------------
---gctcccgctagaa--------------------------------------tgctcg
ctgacctctaagtggggttccttgtcgcggcccgg------------------ctccggt
ggcgggccctgt-------taacttttaccaatgtcttatatcaccagcccctagtcttt
ccgacggtcaccataccgaaacgttagtggcccaaacggctagctgttatcttttacagg
cagccggacagtaagt--------------------------------------------
--------------------------------gattggtatttcgccgttattaaaaggt
ccctgcatcgacgttatttgggtcga-------------------gtaaacttt------
-------------------acagtcagcggaaagttactgatttgaaccgcataatccgg
ctctgctactccataatcgactaatgaaatggtttatgattcgcctatgcccgagtcgtg
gctgtggactagagggccggcagggtacgtgagtgtgtccactagcctggtgggagatag
gaaattaagtc--------------------------------------cagtgccgggc
ctctagtccaaccacgccttggactcctttcaaccatctgatggagggacaagagggtcc
aat---------------gcaagagcgctggggcgggattggcaggcgtgccgagcatag
gtagtagctaggtcccagcctggtcttgttcgggctatagactagaatttctgctctccc
tgtgggcccag---------------------gcagtctgacccatgcgagacaaaga--
------------------------------------------------------------
------------------------------------------ctagcatactggtgccgc
tccttctcaag-------------------------------------------
>SEQ17
ctgcagcgacgaacctctccggtcctacgtgaaccaa-----------------------
cttccgcccgctagaa--------------------------------------cgctcg
ctgacctataagggcggttacttgtcttggcccgg------------------atccgga
ggcgggccctgttccctgctaacttttaccaatgtcttatatcaccagcccctagtcttt
ccgacggtcaccataccgaaacgttagtggcccaaacggctagctgttatcttctactgg
aacctgagcggtgaatggacaaatagaaacatgcggatgcaaggttactgttttaacgta
cctataagtcgagaaaag---------------------agtatgcggttctgcaatagt
ttttggtgcgactttaatcgtgttaagctcatacagctgatgagcgtaacctttcgcggg
cgctt-----------aaggcagttagcggaaagttactgatttgaaccgcataatccgg
ctctgctactccataatcgactgatgaaatggtttatggttcgtctatgcccgagtcgtg
gctgtgc-----------------------------------------------gtatgg
gaacttaaggcgcgctccatgccc------------------------------------
----------attacatccgggcctcatttcatccatctgctgtccg-------------
------------------tgaagagcgcttgggcgggattggcaggcgtgccgagcatag
gtagtaactaggccccaggctggtcttgttcgggctatagactagaatttctgctatccc
tgtgggcccag---------------------gcagtctgacccatgcgagacaaagact
aac---------------------------------------------------------
---------------------atactggtgccactccctctcacg---------------
------------------------------------------------------
>SEQ18
acggagcgacagaccccgacggtcctacttgtactaacagtggcgctcacgaagcagccg
ctggcaccagcaagaatcaagatagccccatattctgcggccacatgctcatgccgctcg
ctgcgcccttagtgcggttccttctcgatcacggcgacagattcgaaaatga--------
--------------------caattttaccaatctcttatatcaccagcccatagtcttt
ccgacggtcaccgtaccgaaacgttagtggcccaaacggcaagctgttatcttctactgg
aacctacac-tt--------------------gcaggagctggacttcagtcttcacgct
ccattaagctgagaagagtactgtctcaagta------------------ttttagaaat
ttttggagcgacgtaattcgggttaagctcttacagctgatgagcgta------------
-----------cggagagaacagttagcggaaagttactgatttgatccgcataatccgg
ctctgctattccataatcgactgatgaattggtttatgattcgcctatgcccgagtcgtg
gctgagctccactgctaccctac-------------------------------------
------------------------------------------------------------
----------aacatatacgtgactgatttcttcaaactattaagaggttaatggggtcc
ctggtgacggcgattgtctcaagagcgctggggcgggattggcaggcgcgccgagcatag
gtagtagctaggtcccaggctggtcttgttcgggcgatagacgagaatttctgctctcgc
tgtggcgctag-------------------------------------------------
-------------------gggctatgagacacaaatcgcgctatgatactggtgccgct
ccgtctctcatcacaatccccac-------------------------------------
------------------------------------------------------
>SEQ19
caccatggacaaacccctatggtccgacgt------------------------------
-------ccgctagaa--------------------------------------tgctcg
ctgacccctaagtgggggtcctggtcgcggcccgg------------------ctccggt
ggcgggcccagt-------acacttttaccaatctcttatatcaccagcccatagtcttt
ccgacggtcaccgtaccgaaacgttagtggcccaaacggctagctgttatcttctactgg
cagccggacagcaagt--------------------------------------------
--------------------------------gattgttatttcgccgttattaaaaggt
ccctgcatccacgttatttgggcaga-------------------cttaacttt------
-------------------ccagttagcggaaagttactgatttgaaccgcataatccgg
ctctgctactccacaatcgactgatgaaatggtttatgattcgcctatgcccgagtcgtg
gttgtg------------------------------------------------------
------------------------------------------------------------
ctccactgcgacacaacatcgg-------------------taagaagacaatggtgtcg
ctg---------------gtaagagcgctggggcgggattggcaggcgtgccgagcatag
gtagtagcgaggtcccaggctggtcttgttcgggctatagactagaatttctgctctccc
tctctcgatcgagcttttaggccaatgatcccgtagtttgcttaaccacagccggagttg
ata---------------------------------------------------------
--------------------------------------cttcgttaaagataggacctta
cctcgatcgagctact--------------------------------------
