>SEQ0
ttaggataaactaacgtccgtcagctccatgcgaataccgcgtcttggcatacctgggct
caatcaccttacgtaaattactcggactctctctagcaaaaatcgcctgctacaaaagtt
ctactcacgagttcgagcgcagtgatctccatctcaatgctcccaggagcacccaaatgc
tattcgggtgtgaggtgcagtccttctgaatacaaacttcttcagtgatcatccgctcga
gcggatccagacctatctatgcgccctacttaagtatttaatgtgcgccctcccacgata
gtgcagaccacataccggccgacttgccaggctttcagaattccgacgatccgatgtcta
ggtggtgccaagaccacgtgcacaaaataagcaaacgatggcgcatgtacgtcgctctct
ctgttgtagtgtattgcaggattacgcggctactttcagagaccagactgtcctgcagat
cgtttatacaggagttgtggtgcccgttatccggctcgtaattgtggacggacctgagta
attgtcttgccgaaactgcctgaaaagccgcgtattgcaagagtgggttgcataagagta
tcagctgggccgaccccggagtcctatttaatctgacgcatacgttgatgcgggttatct
ggcctaagccatactaaactagttaaccgctactaaagtccgtcactacccgaagaatag
ttggactaatctctaaactaagcccgaaaccaaacctcgattcgttgcttgattttctag
tcttgaccgccggttgccgcctgtggcgttcacctctcgtagccagcccaaatttgctag
cgttgtccgatcgctgcgtgtttgctaccgttcgactgccgggagggatatcgctttgaa
tccaccccaaacgtctgtaaggaccattcggatcagcacagctttgcttttgtggacgct
agataggtaacacctcgcagcaccccagtccctgaagaccattcagtagatccttccggt
ttattcaaactagtatatcctcttgacacggagtgggtcagataggcagctaattcttgc
atccatggttgtcagtggac
>SEQ1
ttaagataaactaacgtccgtcagctccatgcgaataccgcgtcttggcataactgggct
caatcaccttacgtaaattactcggactctctctagccaaaatggcctgctcaaaaagtt
ctactcacgagtttgatcgcagtgatgtccatctcaatggtcc-----------------
--------tgtgagctgcagtccttctgaatacaaacttcttcagtgatcatccgctcga
gcggatccagacctatctatgcgccctacttaagtatttaatgtgcgccctcccacgata
gtgcagaccacataccggccgacttgctaggctttcagaattctgac-------------
------gccaagaccaccttcacaaaatatgcaaacgatggcacatgtacttcgctatct
ctgttgtagtgaattgcgggattacgcggttac---------------------------
----------ggagttgtggtgcccgttatccggctcgtaattgtggacggacctgagta
attgtcttgccgaaactgcctgaaaagccgcgtattgcaagagtgggttgcataagagta
tcagctgggccgaccccggcgttcgatttaatc------------------------ttt
ggcctaagccatactaaactagttaaccgctaataaagtccgtcactacccaaagaatag
ttggactactttctaaacaaagccccaaaccaagccacgattccttgcttgaaggtctag
tcttgaccaccggttgccgcctgtggcgttcacctctcgtagccagcccaaatttgctag
cgttgtccgatcgctgcgtgtttgctaccgttcgactgccgggagggatatcgctttgaa
tccaccccaaacgtctttaaggaccattcggatccgcacagctttggttttgtg------
--------------tcgcagcaccccagtccctgaagcccattaattagatccttccggt
ttattcaagctagtatatcctcttgagatggagtgggtcagataggcagctaattcttgc
atctatggttgtcatagg--
>SEQ2
ttaagattacgtaacgtccgtcacctccatgcgaataccgcgtctttgcataactgggcc
caatcaccttacgtaagttacacggactcgctctagccaaaatggcctgctcaaaaagtt
ctactcacgagtttgatcg-----------------------------------------
---------atggtcgtcagtccttctgaatacaaacttcttcggtgatcatccgctcga
gcggatccagacctatctatgcgccctacttaagtatttaatgtgcgccctcccacgata
gtgcagaccacataccggcctacttgctaggctttcagaattctgac-------------
------gccaagaccaccttcacaa-----------------ccatgtgtttcgctatct
ctgttgtagtgaattgcgggattaccccgttac---------------------------
----------ggagtcggggtgcccgttatccggctcgtaattgtggacggacctgagta
attgtcttgccgaaactgcctgaaaagccgcgtattgcaagagtgggttgcatacgagta
tcagctggaccgacgccggcgtttgacttaatc------------------------ttt
ggcctaagccatactaaactggttaaccgctaataaaaaccgtcactaccctaagaactg
ttggtctactgtcttaacaaag-----------------------------------tag
tcttgaccaccggatgccacctgtggcgttcacctctcgtagccagcccaaatttgctag
cgttgtccgatcgctgcgtgtttgctaccgttcgactgccgggagggatatcgctttgaa
tccaccccaaacgtctgtagggaccagtcggatcagcacagatttgcttatgtggacgct
agacaggtaacacctcgcagcaccccagtccctgaagaccattcagtagatccttccggt
ttattcaaactagtagatcccctccacacggagtgggtcagataggtagctaattcttgc
atccatggttgtcagtggag
>SEQ3
tttacataaactaac--------------tgcgaataccgcctcttggcataactgggcg
caatcaccttacgtaaattactcggactctctctaggcaaaatggccggctcaaaaagtt
ctactcaggagtttgatcgcagtgattgccatcgcaatggtgt-----------------
--------tgtgacctgcagtccttctgaatacaaacttcttcagtgatcatccgctcga
gcggatccagacctatctatgcgccctacttaagtatttaatgtgcgccctcccacgata
gtgcagaccacttaccggcccacttgccaggcttacagacttccg---------------
------gccaaggccatgtgcacaaaa---------------------------------
-tattatcacagatcgta------------------------------------------
----tatacaggagtagtcgtgcccgttatccgactcgtaattgtggacggacctgagaa
attgtcttgccgaaactgcctgaaaagccgcgtattgcaagagtgggttgcatacgagta
tcagctggttcgacgcctgcttatgactaaatc------------------------ttt
ggcctaagccata------------gccggtaataaaaatcgtaactaccctaagaactg
ttggtctactgtcttaacgatg-----------------------------------tag
tcttgaccaccggatgccacctgtggcgttcacctctcgtagccagcccaaatttgctag
cgttgtccgatcgctgcgtgtttgctaccgttcgactgccgggagggatatcgctttgaa
tccacccccagcgtctgtaagg-----------------agctttggttttgtg------
--------------tcgcagcaccccagtccctgaactcgattaattagatcctatcggt
ttattcaagctagtatatcctcttgagatggagtgggtcacataggcagctacttcttgc
atctatggttgtcatagg--
>SEQ4
ttaggctaaactaacgtgcgtcagctccatgcgaataccgcggcttggcatacctggtct
caatcaccgtgcataaattactcggactgtctctagcaaaaatcgcctactataaaagat
ctactcacgagttcgagcgcagtcaactccatctcaatgctcccaggagcgcccaaatgc
tatgcgggtgtga-----ggtccttctgaacacaaacttcttcactgatcatccgctcga
gcggatccagacctatctatgcgccctacttaagtatttactgtgcgccctcccacgata
gggcagaccacttaccggccgagttgctaggctttcaggattctgat-------------
------accaagagcaccttctcaaaatatgcaaacgatggcacatgtacttcgctatct
cggttgtgctgaattgcgggcttacgcggtgcc---------------------------
----------ggacttttggtgcccgttatccgactcgtaattgtggacggacctgagaa
attgtcttgccgaaactgcctgaaaagccgcgtattgcaagagggggttgcatacgagta
tcagctgattcgacgcctgcttatgactaaaac------------------------ttc
ggcctaagccata------------gccgttaataaaaatcgtaactaccctaagaactg
ttcgtcaacagtcttaacga-------------------------------------tag
tcttgaccaccggatgccacctgtggcgttcacctctcgtagccagccccaatttgctag
cgttgtccgatcgctgcgtgtttgctaccgttcgactgccgggagggatatcgctttgaa
tacgccacaaacgtctgtaaggcccattcggatcagcacagctttgcttttgtgaacggt
agataggtaacacctcgcagcaccccagtccctgaagacctttcagtagatccttccggt
ttattcaaactagtatagcctcccgacaccgagtgtctcagaaaggcatctaattcttgc
atccatggttgtcagtggac
>SEQ5
ttaggctaaactaaagtgcgtcagctccatgcgaatacggcggcttggcatacctggact
caatcaccgtgcataaattactcgga----------------------------------
--------gagttccagcgcagtcaactccgtctcaaagc--------------------
------ggtgtga-----ggtccttctgaatacgaacttcttcagtgatcatccgctcga
gcggatccagacctatctatgcgccctacttaactatttaatgtgcgccctcccacgata
gtgcagacgacataccggcctacttgctatgctttcagaattctgac-------------
------gaca--------------------------------------gtttcgctatct
ctgttgtagtgaattgcg------------------------------------------
----------ggagtcggggtgcccgttatccgactcgtaattgtggacggacctgagaa
attgtcttgccgaaactgcctgaaaagccgcgtattgcaagagggggttgcatacgagta
tcacctggttcgactcctgcttatgcctaaatc------------------------tt-
agccgaagccata------------gccggtcataaaaatcctaactactctaagaactg
ttggtctactgtcttaacgatg-----------------------------------tag
tcttaactactgcatgccacctgtggcgttctcctctcgtagccagcccaaatttgctag
cgttgtccgatcgttgcgtgtttgctaccgttcgactgccgggagggatatcgctttgaa
tccacccctaacgtctgtagggaccagtcggatcaacgcagatttgcttaagtggacgct
agataggtaacacttcgcagcaccccagtccctgaacacaatgcagtagatcatgccggt
ttattcagactagtagaccccacccacacggagtgggtcagagtggtagctaattcttgc
atccatggttggcagtggac
>SEQ6
ttaggctaaact------------------------------------catgcctggact
caatcaccgtgcataaattcctcgga----------------------------------
------------tccggcgcattcaactccggcccaaa----------------------
---------gcggtgtgtggtccttctgaatacaaacttcttcagtgatcatccgcccga
gcggatccagacctatctatgcgccctacttaagtatttaatgtgcgccctcccacgata
gggcagaacacctacagcccgacttgctaggctttcagaattctgag-------------
------gcca------------caagatatgcaaacgatggcacatgtacttcgct----
----------------cggcattacgcggttac---------------------------
----------ggagttgtggtgcccgttatccggctcgtaattgtggacggacctgagta
attgtcttgccgaaactgcctgaaaagccgcgtattgcaagagtgggttgcatacgaata
tcagctgggtcgaccccggcgttcgatttcatc------------------------ttt
ggcctaagccataataaactagttaaccgcgaataaag---------------------g
ctggactactttctaaacaaagccccaaacc--------------------------tag
tcatgaccgccggttgccgactgtggcgttcacctctcgtagctagcccaaatttgctag
cgttgtccgatcgctgcgtgtttgctaccgttcgactgccgggagggatatcgctttgaa
tccgc---------------------------tcatcacagctttacttttgtgaacggt
agatagttaacacctcgcagcaccccagtccctgaagacctttcagtagatccttccggt
ttattcaaactagtatagcctcccgacaccgagtgtctccgagaggcttctaattcttgc
atcgatggtggtcaatggac
>SEQ7
ttagcctaaact--------------------------catgcctggactcaatccggca
cattca-----------------------actccggcccaaa------------------
------------------------------------------------------------
---------acggtgtgtggtccttctgaatacaaacttgttcagtgatcatccgctcga
gcggatccagacctatctatgcgccttacttaagtatttaatgtgcgccctcccacgata
gtgcagacgacatatcggcctacttgctaagcttacataattctgac-------------
------gaca--------------------------------------gtttcgctatcc
ctgttgtagtgacctgcg------------------------------------------
----------ggagtcggggtgcccgttatccggctcgtaattgtggacggacctgagta
attgtcttgccgaaactgcctgaaaagccgcgtattgcaagagtgggttgcatacgagta
tcagctggaccgacgccggcgtttggcttaatc---------------------------
-----tagtcatactaa-----------------aaataccgtcactagcctaagaactg
ttggtctactgtcttaacaaag--------------------------------------
--ttgaccaccggat-----ctgtggcgttcacctctcgtagccagcccaaatttgctag
cgttgtccgatcgctgcgtgtttgctaccgttcgactgccgggagggataccgctttgaa
tccaccccaaaagtctgtagggaccagtcggatcagcacaggtttgcttaagtggacgct
ggacaggtaactcctcgcagcacgacagtccctgaagaccactcagtagatccttccggt
ttaatcatacgagtagatcccctccacacggcgtgggtcagataggtagctaattcttgc
atcaatggttgtcagttaag
>SEQ8
ttaggataaactaccgtccgtcatctccatgagaataccgcgtgttgccatatatgg---
-------------------actcggactctctctagcattaatcgcctgctacacaagtt
cttgtcacaagttcgagcgcagtgtggtccatctcaatgctcccaggagcacccaaatgc
tattcgggtgtgaggtgcagtccttctgaatacaaacttcttcagtgatcatccgctcga
gcggatccggacctatctatgcgccctacttaagtatttaatgtgcgccctcccacgata
gggcagacgccatgccgaccgagttgctagggtctcaggtttctgat-------------
------acca----------------agaggcaaacgatggtacatgtacttcgctctct
cggtt------------g------------------------------------------
----------ggacttttggtgcccgttatccggctcgtaattgtggacggacctgagta
attgtcttgccgaaactgcctgaaaagccgagtattgcaagagtgggttgcatacgagta
tcagctgtgtcttccccggcggtcgatttcatc---------------------------
-----------------------------------------tctagtccataataaacta
gtggactactttctaaacaaagccccgatcc--------------------------tag
tcatgaccgccggttgccgactgtggcgttcacctctcgtagctagcccaaatttgctag
cgttgtccgatcgctgcgtgtttgctaccgttcgactgccgggagggatatcgctttgaa
tccaccccaaacgtctttaaggaccattcgtatccgcacagctttggttttgtg------
--------------tcggagcaccccagtccct---ga------------------cggt
ttattaaagctagtagatccaattgagatggagtgggtcacataggcagctaattctttc
atctagggttgtcatagg--
>SEQ9
tttacataaactaac--------------tgcgaatgccgcctcttggcatgactgggcg
caatcaccttacgtaaattactcggcctctctctaggcaaaatggccggctcaaaaagtt
ctac------------------tgattgccatcgcaatggtct-----------------
--------tgtgacctgcagtccttctgaatacaaacttcttcggtgatcatccgctcga
gcggatccagacctatctatgcgccctacttaagtatttaatgtgcgccctcccacgata
gtgcagaccacttaccggcccacttgccaggcttacagacttccgaa-------------
-----------ggccatgtgcacaaaa---------------------------------
-tcttatcacagatcgta------------------------------------------
------------------gatgcccgttatccggctcgtaattgtggacggacctgagta
attgtcttgccgaaacggcctgaaaagccgcgtattccaagagtgggttgcataagagta
tcaggcggaccgacgccggcgtttgacttaatt------------------------ttt
gg--------------------ttagccgctaataaaaaccgtcgctaccctaaaa----
---------------------------------------------------------tag
tcttgacctccggatgccacctgtggcgttctcctctcgtagccagcccaaatttgctag
cgttgtccgaacgttgcgtgtttgctaccgttcgactgccgggagggatatcgctttgaa
cccacacctaacgtctgtagggaccagtcggatcaatacaaacctgctaaagtggaccct
acacagggaacacttcgcagcaccccagtccctgaacacaatgcagtagatcatgccggt
ttattcatacgagtagaccccacccacacggagtgggtgagagtggtagctacttcttgc
gcccatggttggcagtggag
>SEQ10
ttaagataaacttacat--------------cgaatgccgccgcttggcatgactgggcg
caatcaccttacataaattactcggcctctctctaggtaaaatggccggctcaaaaagtt
ctac------------------tgattgccatcacaatggtct-----------------
-------------------ttccttctgaatacaaacttcttcagtgatcatccgcccga
gcggatccagacctatctatgcgccctacttaagtatttaatgtgcgccctcccacgata
gggcagccgccatgccgaccgagttgctatggtctcgggtttctgat-------------
------acca----------------agacgcaaacgaa---------------------
------------------------------------------------------------
----------gggacagggatgcccgttatccgactcgtaattgtggacggacctgagaa
attgtcttgccgaaactgcctgaaaagccgcgtattgcaagagggggttgcatacgagta
tcagctgttttctagtc---------cataatc---------------------------
-------------------------------------------------------aactg
gtggactacttcctaaacaaagccccgagcc--------------------------tag
tcatgacagccggttgccgactgtggcgttctcctctcgtagccagcccaaatttgctag
cgttgtccgatcgttgcgtgtttgctaccgttcgactgccgggagggatatcgctttgaa
tccaccccaaacgtctggaaggaccattcggatcagcacagctttggttatgttgacgtt
agataggtagcaccttgcagcacctcagtccctgaag-------------------cggt
ttatacaaactcgtatattctcttgacacggagtaggtcggataggcagctaattctttc
atgcatggttgtcagtcgac
>SEQ11
ttaggctaaactaaagtgcgtcagctccctgcgaatacggcggcttggcatagctggact
caatcaccgtgcacaaattagtcgga----------------------------------
--------gagctccagcgtagtcaactccgtctcaa-----------------------
--------agcggtgtaaggtccttctgaatacaaacttgttcagtgatcatccgctcga
gcggatccagacctatctatgcgccttacttaagtatttaatgtgcgccctcccacgata
gtgcatacaacacaccggcctacttgctaggctttcagaattctgac-------------
-----------------------------------caagaccaccttcacaactctatgt
tggttac-----------------------------------------------------
----------ggagtc--ggtgcccgttatccgactcgtaattgtggacggacctgagaa
attgtcttgccgaaactgcctgaaaagccgcgtactgcaagagggggttgcatacgagta
tctcctgggtcctccccggcgttcgatttcaac------------------------ttt
ggcataagccataacaaactagttaacggcgtagaaag---------------------g
ctgcactattttctaagctaagccccaaacc--------------------------ttg
tcatgaccgcgggttgccgactgtggcgttcacctctcgtagccagcccaaatttgctag
cgttgtccgatcgctgcgtgtttgctaccgttcgactgccgggagggatatcgctttgaa
c----------------tagggactgctaaagt---------------------------
---------acacttcgcagcaccccaggccc-------------------catgccggt
ttcttcataagaggagacccctcccacacggggtgcgtgagagtggtagctacgtcttgc
gcccatgcttggcagtggag
>SEQ12
ttagcctaaac----------------------------------tcgca----------
-----------cgcacatgg----------------------------------------
------------------------------------------------------------
---------------tgtgctccttctgaatacaaacttcttcagtgatcatccgcccga
gcggatccagacctatctatgagccctacttaagtatttaatgtgcgccctcccacgaaa
gggcagcccccatgcc--------------------------------------------
------------------------aaagccgcaaacgaagggaca---------------
------------------------------------------------------------
-------------------gtgcccgttatccggctcgtaattgtggacggacctgagta
attgtcttgccgaaacagcctgaaaagccgcgtattgcaatagtgggttgcatacgaata
tcagctgggctgcccgggccgttggattgaa-----------------------------
------agccctactaaactagttaaccgctaataaagtccgtcactacgcaaggaatag
tcg---------------------ccactccaagccccgatacctggcatgaaggtctag
tcttgaccaccggttgccgcctgtggcgttctcctctcgtagccagcccaaatttgctag
cgttgtccgaacgttgcgtgtttgctaccgttcgactgccgggagggatatcgctttgaa
tcccccccaaaagtctgtagggaccagacggatcagtacaggtgtgcttaagcggtcgcc
agacaagaaactcctcgaagcactacagtccctgaagaccactcagtatatccatctggt
ttaatcgtacgcgtagatcccctccacacggcgggggtcagataggtaggtgattcttgc
atcaatggttgtcacttaag
>SEQ13
ttaggataaactaccgtccgagatctccatgagtataccgc-------------------
-------------------actcggactctctctagcgtaattcggctgctacacaagtt
cttgtcaaaagttcgagcgccgtgttgtgcatctcaatgctccgaggagcaaccaaatgc
t-------------------tcctactgaatacaaacttcttcagtgatcatccgctcga
gcggatccagacctatctatgcgccctacttaagtatttaatgtgcgccctcccacgata
gtgcagacgacataccggcctgcttgctatactttcagaattctgac-------------
------gacg--------------------------------------gtttcgtgatct
ctgttagagtgaacc---------------------------------------------
----------ggggtcggggtgcccgtaatccggctcgtaattgtggacggacctgagta
attgtcttgccgaaacggcctgaaaagccgcgtattccaagagtgggttgcataagagta
tcagctggaccgacaccggcgtttgacttaatc---------------------------
--------------------------------tcatgaaccgtcactaccctaagaactg
taggtctaatgtcttaacaaag-----------------------------------tag
tctcgatcaccgactgccacctgtggcgttctcctctcgtagccagcccaaatttgctag
cgttgtccgaacgttgcgtgtttgctaccgttcgactgccgggagggatatcgctttgaa
tccacccccaacatctttaaggagcattcgtatccgcacagctttggttttgtg------
--------------tcggagcatcccagtccctga---------------------cagt
atattaaagctagtagttccaattgagatgcagtgggtcacataggcagctaattcttta
gg------------------
>SEQ14
ttaggctaaactaatgtgcgtcagctacctccgaatacggcgggttggca----------
-----------cacacattagtcggagctccagcgtagacaac-----------------
------------------------------------------------------------
--------tccgtctcgtggtccttctgaacacaaacttcttcactgatcatccgctcga
gcggatccagacctatctatgcgccctacttaagtatttactgtgcgccctcccacgata
gtgcagaccatacaccggccgacttgccgggcttacagagtaccgacgatccggtgtcta
ggtggtgcgaataccatgtgcataaaaaaagcacacgatggcgcaggtacctcggtgtcc
ctgctgtagtgtattacaggattacgcggctacattcggagaccagactgtcctgcagat
cgtttatacaggagttgtggtgcccgttatccggctcgtaattgtggacggacctgagta
attgtcttgccgaaactgcctgaaaagccgcgtattgcaagagtgggttgcatacgagta
tcagctgggctgcccgggccgttggattgaa-----------------------------
------agccctactaaactagttaaccgctaataaagtccggcacttcgcaaagaatag
tgg---------------------ccactccaaaccccgatacctggcaagattgtctag
tcttgaccaccggatgccgcctgtggcgttcacctctcgtagccagccccaatttgctag
cgttgtccgatcgctgcgtgtttgctaccgttcgactgccgggagggatatcgctttgaa
cccacacctaacgtctgccggtacaagtcggaccaatgcaaacctgctagagtggaccct
acacagggaacacttcgcagcaccacaggcgctgaacacaatgcagtagatcaggcccgg
ttctccatacgagta-------------------------------------------gc
gcccatggtaggcagtggag
>SEQ15
ttttcataatctaac--------------tgcgaataccgcctctcggcacaactgggcg
caatcacctcacataaattactcggactctctctaggcaaaatggccggctcaaaaagtt
ctactcaggagtttgatcgcagtgattgccatcgcaatggtgt-----------------
--------tgtgacctgcagtccttctgaatataatcttcttcagtgatcatccgctcga
gcggatccagacctatctatgcgccctacttaagtatttaatgtgcgcccttccacgata
gagcagacggcatgccgaccgacttgc---------------------------------
----------------------------gcgcaaacgaaggtacaggtacatcgctctct
cggttg------------------------------------------------------
----------gggcttttggtgcccgttatccgactcgtaattgtggacggacctgagaa
attgtcttgccgaaactgcctgaaaagccgcgtattgcaagagggggttgcatacgagta
tt----------------------------------------------------------
--------------taaactagttaacggctaataaaaaccgtcactaccctaagaactg
ttggtctactgtcttaacaaag-----------------------------------tag
tcctgactaccggatgccatctgtggcgttcacctctcgtagccagcccaaatttgctag
cgttgtccgatcgctgcgtgtttgctaccgttcgactgccgggagggatatcgctttgaa
cccacacctaacttctgtagggaccagtcgg-----------------------------
--------aacactgcgcagcactccagtccctgcacacaatgcagtagaacatgccggt
ttattcatacgtatagaccccacccacacggagtgggtgagagaggtagctgcttctggc
acccatggttggcagtggag
>SEQ16
------------------------------------------------------------
--------------------------------ttagcctaaactgcacgc----------
------------------------------------------------------------
------------aggtgtgctccttctgaatacaaacttcttcagtgatcatccgctcga
gcggatccagacctatctatgcgccctacttaagtatttaatatgcgccctcccacgata
gtgcagacgacatatcggcctatttccgcagcttacataatactgac-------------
------g-----------------------------------------gtttcgctatcc
ctgttgtagtgccctgcg------------------------------------------
----------ggagtcggggtgcccgttatccgactcgtaattgtggacggacctgagaa
attgtcttgccgaaactgcctgaaaagccgcgtattgcaagagggggttgcatacgagta
tcagctctgtcttccccggcggtc------------------------------------
------------------------------------------caagtccataagatacta
gtggactactttctaaacaacgccccgatcc--------------------------tag
tcatgaccgccggttgccgactgtggcgttcacctctcgtagccagcccaaatttgctag
cgttgtccgatcgctgcgtgtttgctaccgttcgactgccgggagggatatcgctttgaa
aatacccccaacgtatgttaggacc----------------------tttgctc------
--------------tcgcagcaccccattccctgaaga------------------cact
ttggtcaaactagtttgtcctcttgacacggagtgggtcagataggcagctaattcttgc
atccttggttgccagtcgac
>SEQ17
tcaggctaaactaaagtgcgtcagctccctgtgagcccggcggctgggcatagttggact
cagtcacgtggcacaaat------------------------------------------
--------gagtgtcaaagctgtaa-----------------------------------
------------------ggtccttctgaatacaaacttcttcagtgatcatccgctcga
gcggatccagacctatctatgcgccctacttaagtatttaatgtgcgccctcccacgata
gggcagaactccaacaggacgacttgctaggcttacagaattgtgag-------------
-----------------------------------------------------gccacaa
gagttgcacggcattacgcggttac-----------------------------------
----------ggagttgtggtgcccgttatccggctcgtaattgtggacggacctgagta
attgtcttgccgaaacagcctgaaaagccgcgtattgcaatagtgggttgcatacgaata
tcagctggaccgacgccggcgtttgacttaatc------------------------ttt
ggcctaagccattctaaactggttaaccgctaataaaaaccgtcactgccctaagaactg
ttggtatactgtcttaacgaag--------------------------------------
------ccacgggatgccacctgtggcgttcacctctcgtagccagcccaaatttgctag
cgttgtccgatcgctgcgtgtttgctaccgttcgactgccgggagggatatcgctttgaa
cccacacctcacttctgtagggacgcgtcggaacagt-----------------------
--------------gcgcagcactacagtacctgcacataa-------------------
-tgttcatacgtatagaccccacccacacggagtgggtgggaga--------------tc
acccatggttggcagtggag
>SEQ18
ttagtctacacttatgtgcgtcagctacctgcgaatacggcgggttggca----------
-----------cacagattactc-------------------------------------
-------cgagctccagcgtagacaacgtcgtctc-------------------------
----------------gtggtccttctgaacacaaacttcttcactgatcatccgctcga
gcggatccagacctatctatgcgccctacttaagtatttactgtgcgccctcccacgata
gggcagccgccatgccgaacgagttgctttggtctcgggtttctgat-------------
------------------------------------------------------------
------------------------------------------------------------
-----------agacagggatgcccgttatccggctcgtaattgtggacggacctgagta
attgtcttgccgaaacagcctgaaaagccgcgtattgcaatagtgggttgcatacgaata
tcagcagggtcgaccccggcgttcgatgtcatc------------------------ttt
ggcataagccataataaactacttaaccgagaataaag---------------------g
ctggactactt------caaggcc---------------------------------tag
tcatgaccgccggttgccgactgtggcgatcacctctcgtagctagcccaaatttgctag
cgttgtccgatcgctgcgtgtttgctaccgttcgactgccgggagggatatcgctttgaa
tccacccacaaagtctgtagggaccagtcgga---------------------ggacgct
ggacaggtaactcctcgcagcacgacagtccctaaagaccagtcagtagatccttccagt
ttaatcatacgagtacatcccctccacacagcgtgggtctgataggtaactaattcttgc
atcaatggttgacagttaag
>SEQ19
ttaagaaaaactaacgtccgtcagccccatgcgaatgccgcgtcttggcataactgggct
caatcaccttacgtacattagtcggattctctctagcgaaaatggcctgctcaaataatt
ctactcacgagtttgattgcagtgatatccatcgcaatgggcc-----------------
--------tgtgagccgcagtccttctgaatacaaacttcttcagtgatcatccgctcga
gcggatccagacctatctatgcgccctacttaagtatttaatgtgcgccctcccacgata
gtgctgacgacatatgggccgacttgctaagcttagataattctgac-------------
------gaca--------------------------------------gtttcggtatcc
ctgttgtaatgacctg--------------------------------------------
----------ggagtcggggtgcccgttatccgactcgtaattgtggacggacctgagaa
attgtcttgccgaaactgcctgaaaagccgcgtattgcaagagggggttgcatacgagta
tcagctggaccgtcaccggcgtttgacttaacc---------------------------
------------------------------------taaccttcactaccctaataactg
taggtctaatgtcttaacaaag-----------------------------------tag
---------------gccgcctgtggcgttcacctctcgtagctagcccaaatttgctag
cgttgtccgatcgctgcgggtttgctaccgttcgactgcagagagggatatcgctttgaa
aatacgac----------------------------------------------------
------------cctcgcagcacccaattccctgagg-----------------------
----tcaaactagtttggcctcttgacacggagtaagtcagataggcacctaattcttgc
atccttggtggccattcggc
