>SEQ0
cataatgcctatgcgagacgtgccatcgctatctgagcgacttatgcggaccagacacac
acaatagtggtgtctacctaaaagccgctttggcctagtcagatgccgacgtataagccg
tagcgctgctagcacaaccgtctatatgcgccaacggtacactagcttccgagagggggt
agaacaaacggaacacgtgacggaacatgcgcaccgtatcgcaggaactaccggtgttaa
ggtgccccccaggtatcatagagagtgtgtcggtcgaagttgcgctctcacctaaacttt
ttcggagtattttggagaggcctcgaacccgattttcttttcaccactaggacgaggttc
tctaatctgtccaagtactcccgtagaaagaaaagtgtgtgttgcgacatcaagagggta
aaggtgatggttcggaacgatcacaagtcttattaatcgtctgatatcacgacattgtaa
ccgtgttaggagtccatgcactgcttcatggtacatacgtatgaacccgccctctttagt
cgacgagctggagggggagccgaaacccttctgtgtagaaaaatcctacgctttgctgtc
ttcacaaaaaccttatgatgcgaacgtgttcagtgtgtgttcgagtgcggattatgaagt
tatcagtcaggaatatctttttgcgacctagtgacaaaacgacggcgcagcgtaccgtag
taagggagtgcaaacagaggtgcggattgtgtacttccttggtacaaggccaaatgacct
tccgggccatccaccgtagttacgtctctgctagcttaaatttgagtctaaatggaacga
gccggtacgtctacgtggagcctcggattgacgtcggttacctactacgaacccagcgga
cgtcgtcgtctttaaaccacgtccctccagggagtgatccatgaaagttactaagatatg
gcttcaagtgggaagtacgacgtgacgtccaatagctcagctcaaagcttatagagattt
tactcgtgtaacggacgtctgctccgctcgatcaacccgtgcgtgaaggcgcatccgaag
tcaaacacgttaccgtggcg
>SEQ1
cataatgcctatgcgagacgagccatcgctatctgaacgacttaagcggaccagacacac
acaatagtggtgtcttcctaaaagccgctttggcctagtca-------------------
----gctgctagcacaacggtctaaatgcgccaacggcacactagcttcagagagggggt
agaacaaccggaagacttgacggaacatgcgcaccgtatcgcaggaactaccggtgttaa
ggtgccccccaggtatcatagagagtgtgtcggtcgaagttgcgctctcacctaaacttt
tccggagtatttttgagagccctcgaacccgattttcttttatgctctaggacgtggttc
tctaatttgttcaagtactcccgaagaaagaaaagtgtgtgtttcgacatcaagagggta
aagatgatgg---------------------ataaaacgtcagatttcacgacattgtaa
ccgtgttagaagtctatgcactgcttcatggtacatacgtatgaacccgccctctttagt
cgacgagctggagggggagccgaaacccttctgtgtagaaaaatcctacgctttgctgtc
ttcacaaaaacctcatgaagcgaacgcgatcagtgtgtgttcgagtgcggattatgaagt
tatcagtcaagaatatcttttttcgacgttgtgacaaaacgacggcgcag----------
-------gtccaaacagaggtgtgcattatgtcct-------------------------
-------------------tgacgtctctgctagcttaaatttgagtctaaatggaacga
gcccgtacgtctacgtggagcctcggattgacgtcggttacctactacgaacccagcgga
cgtcgtcgtctttaaatcacatccctccacggagtgatccatgaaagttactaagatatg
gcttcaagtgggaagtacgacgt---------------------------------attt
tactcgtgtcgcggacgtctgctccgctcgacctactcgtgcgtgaaagctcatctgatg
tcaaacgcgttaccgtggcg
>SEQ2
cctaatgcctatgcgtgacgagccatcgctatctg---------------------acac
gcaatagtggtgtctaccgaaaagccgctttggcctagtca-------------------
------------------------------gcaacggcacactatcttcagagagggggt
agaacaaccggaagactagacggaacatgcgcaccgtatcgcaggaactaccggtgttaa
ggtgccccccaggtatcacagagagtgtgtcggtcgaagttgcgctctcacctaaacttt
ttcagagtattttgaagaggcatcgaacccgattttcttttcaccactaggacgaggttc
tttaaactgtccgagttctccactagaaagaaaagtgtgtgttgcgacctcaagagggta
aaggtgatggtttggcacgatcacaagtcttattaatcgtctgaaatcacgacattgtaa
ccgtgttcgg---------actgcttcatggtacatacgtatgaacccgccctcgttagt
cggcgagctggagggggagccgaaacccttctgtgcagaaaaatcctacgctttgctgtc
ctcccaaaaacctcaccaagctaacgcgatcagagtgtgttcgagttcggattatgaagt
tatcagtcaagaatatcttttttcgacgttgtgacgcag---------------------
-------gtccaaacagaggtgtgctttatgtccc-------------------------
-------------------ttacgtctctgctagcttaaatttgagtctaaatggaacga
gccggtacgtctacgtggagcctcggattgacgtcggttacctactacgaacccagcgga
cgtcgtcgtctttaaaccaggtccctccagggagtgatccatgaaagttactaagatatg
gcttcaagagggaagtacgacgtaacgtccaatagctcagctcaaaccttatagagatct
gactcgaataacggacgtctgctccgctcgatcaacccttacgtgaaggcgcaaccgaag
tcaaacacggtcccatggcg
>SEQ3
cattatgcctacgcga----------------ctgagcgacttttgaggacgagacacac
acaatagtggtgtctacctaaaagccgctttggcctagtcagatgccgttctataagccg
tagccctgctagcacaaccctctatatccgccaacggtacactaacgtccgagagggggg
agaacaaacagaacacgtgacggaacatgcgcaccgtatcgcaggaactaccggtgttaa
ggtgccccccaggtatcatagagagtgtgtcggtcgaagttgcgctctcacctaaacttt
ttcg--------------------gaacccgattttcttgtcaccattaggacgaggttc
tctgatctg-------------------agaaaaatgtgtgttgagacatcaagagggta
aaggtgatggttcggaacgatcacaactcttattaatcgtctgat---------------
--------------------ctgcttcatggtacatacgtatgaacccgccctctttagt
cgacgagctggagggggagccgaaacccttctgtgtagaaaaatcctacgctttgctgtc
ttctcaaaaaccttatgag-----------------------------------------
tgtcagtcag----------------cctagtgaaaagacgacggtgcagggtaccgtag
taagggagtccaaacagaggtgcg---------------------gaggccaaatgacca
tccgggccatccaccgtagtgacgtctctgctagcttaaatttgagtctaaatggaacga
gcccgtacgtctacgtgcagcctcggattgacgtcggttacctactacgaacccagcgga
cgtgctcgtctttacatcatctcccttcacggagtgaaccatgaaag---------tatg
gcttcaagtgggaagtacgacgt-------------------------------------
---------cgcggacgtctgctccgctcgacctactagtgcgtgaaagctcatctgata
tcaaacgcgttaccgtggcg
>SEQ4
cattatgcccacgcg-------------------------------------actgacac
acaatagtggtgtctacc-----------------tagtcagaacccgtcctataagccg
tagccctgctagcacatccctctaaatccgccaacggtactctaacgtccgagagggggg
cgaacaaacag---------cggaacatgcgcaccgtatcgcaggaactaccggtgttaa
ggtgccccccaggtatcatagagagtgtgtcggtcgaagttgcgctctcacctaaacttt
tccggagtatttctgagagccctcgaacccgattttcttttatgctc-------------
---aatttgttcatgtactcccgaagaaaaaaaagtgtgtgtttcgacatcaagagggta
aagatgatgg---------------------ataaaacgtcaggtttcacgacattgtaa
ccgtgttaaaagtctttgcgctgcttcatggtacatacgtatgaacgcgccctcgttagt
cggcgagctggagggggagccgaaacccttctgtgcagaaaaatcctacgctttggtgtc
atagcaaaaaccttatgatgcgaa-----------cgtgttcaagatcggattatgatgt
tatcagtcaggaatatctttttgggacctacgcgtcaggaa-------------------
-------gtgcaaacagaggtgcggattgtgtaca-----------------aatgacct
tccgggccctccgccgttttgacgtctctgctagcttaaatttgagtctaaatggaacga
gcccgtacgtctacgtggagcctcggattgacgtcggttacctactacgaacccagcgga
cgtaatcgcctttaaatcacatttctccacggagtgatccatgaaagtgacaaagatatg
gcttcaag------------------------------------------------attt
tactcgtgtcgcggtcgtctgctcggctcgacctactcgtgcgtgaaagctcatctgatg
tcaaacgcgttaccgcggcg
>SEQ5
----------------------------------------------------tctgacgc
gcaatagtggggtctaccgaaaagccg---------------------------------
------------------------------ccaacggcacactatctgcagagagggggt
agaacaaccggaagaatagacggaacatgcgcaccgtatcgcaggaactaccggtgttaa
ggtgccccccaggtatcatagagagtgtgtcggtcgaagttgcgctctcacctaaacttt
tccggagtatttctgagagccctcgagcccgattttcttttatgctc-------------
---aatttgttcatgtactcccgaagaacaaaaagtgtgtctttcgacatcatgagggta
aagatgatgg---------------------ataaaacgtcaggtatcacgacattggaa
ccgtgctaaaagtctttgctctgcttcatggtacatacgtatgaacccgccctcgttagt
cggcgagctggagggggagccgaaacccttctgtgcagaaaaatcctacgctttgctgtc
gtcataaaaacctcatgaagcgaaggcgagcagtgtgtgttcaagtgccaaatatgaagt
tatcagtcaagcatatctttgttcgacgttgtgacaaaacgacggcgcag----------
-------gtccaacct--------------------------------------------
-------------------tgacgtctctgctagcttaaatttgagtctaaatggaacga
gcccgtacgtctacgtgcagcctcggattgacgtcggttacctactacgaacccagcgga
cgtcgtcgtctttaaaccaggtccctgcacggagtgatccatgaaagttacgaagtgatg
gcttcaagagggaagtacgacgtagcgtccaatagctcagctccaacattattgagatct
gactcgaataacggacgtctgctccgctcgatcaacccttacgtgaacgcgcaaccgaag
tcaaacacggtcccatggcg
>SEQ6
----------------cagttggcctacgcgactgagcgagttatgaggtcgagacacac
acaaaagtggcgtctccctaaaagccgctttggcctagtcagatgccgttcgataacccg
tagccctgctagccgaaccctctagttccgccaacggtacactaacgtccaagagggggg
acaacaaacagaacacgtgacggaacatgcgcaccgtatcgcaggaactaccggtgttaa
ggtgccccccaggtatcatagagagtgtgtcggtcgaagttgcgctctcacctaaacttt
tccggagtat------------------ccgatttcctgttatgctc-------------
---aatttgttcatttactcaagaagaacaaaaagtgtgtgtttcgacatc---------
-------------------------------ataaaacgtaagatatcacgacattggaa
ccgtggtaaacgtccttgctctgcttcatggcacatacgtatgaacccgccctcgttagt
cggcgagctggagggggagccgaaacccttctgtgcagaaaaatcctacgctttgctgtc
ttcactaaaatctcatgaagccaacgcgttcagtgtgtgctcgagtacgcattatgaagt
tatcagtcaagattatcttttttcgacgttgtgacaaaacgccggcgcag----------
-------ctccaaacagaggtttgcattatgtcct-------------------------
-------------------ttacgtctctgctagcttaaatttgagtctaaatggaacga
gccggtacgtctacgtggagcctcggattgacgtcggttacctactacgaacccagcgga
cgtgctcgtctttacatcctatccctttacggaatgaaccatgaaag---------tctg
gattcaagtgggaagtacgacat-------------------------------------
---------cgcgaacgtctgctccggtcgacctactagagcgtgaaagctcatctgata
ttaaactcgttaccgtggcg
>SEQ7
cctaatgtctatgggtgaagagccatagctatctg---------------------acac
gaaattgtggtgtctaccgataaacctcttaggcctagtcag------------------
-------------------------------caacggcacactatcttcagagagggggt
aggacaactggaagactagacggaacatgcgcaccgtatcgcaggaactaccggtgttaa
ggtgccccccaggtatcatagagagtgtgtcggtcgaagttgcgctctcacctaaacttt
ttcagagtattttgaagagggaacgagcccgcttttc-------------------gatc
tttaaaccatccgagttctccactggacagaaaagtgtgtcttgcgaccacaagagggta
aaggtgacggtttggcgcga----------------------------------------
--------------ttcggactgcttcatggtacatacgtatgaacgcgccctcgttagt
cggcgagctggagggggagccgaaacccttctgtgcagaaaaatcctacgctttggtgtc
ttctgaagcatcttataag-----------------------------------------
tgtcagtcag----------------cctagtgaaaagacgacggtacagggtaccgttg
taagggagtaggccca-------------------------------------ctgacca
tccgggccatccactgtagtgacgtctctgctagcttaaatttgagtctaaatggaacga
gcccgtacgtctacgtggagcctcggattgacgtcggttaactactacgaacccagcgga
cgtcgtcgtctttaaaccaggtccc--------------------------------atg
gcttcaagagggaattacgacgtaacgaccaacagctaagctcaaaccttatatagaacg
gactcgagtaacggacgtctgcaccgctcgatcaacccgtacgtgaaggcgcaaccgaag
tcagtc--------------
>SEQ8
---------------actaatgccatagctatctga------------------------
-------------cacccgataaacatcttaggcctaggcag------------------
-------------------------------cagcggcacattagcttcatagagggggt
aggacaactgaatgactagacggaacatgcgcaccgtatcgcaggaactaccggtgttaa
ggtgcgccccaggtatcatagagagtgtgtcggtcgaagttgcgctctcacctaaacttt
tcaggagtat------------------ccg-----------------------------
---aatttgttcattgactcaagaagaa--------------------atc---------
-------------------------------ataagacgtaagatatcacgacagtggaa
cagtcgtaaatgtccttgctctgcttcatggcacatacgtatgaacccgccctcgttagt
cggcgagctggagggggagccgaaacccttctgtgcagaaaaatcctacgctttgctgtc
ttcactaaactctcgtgaagccaacgcgctcagtgtgtgctcgagtacgcattatgaagt
taccagtcaagattgtctctttacgacgttttgacaaaacgccggcg-------------
----------caaacaaaggttttcattatgtcct-------------------------
-------------------ttacgtctctgctagcttaaatctgagtctaaatggaacga
gccggtacgtctacgtggagcctcggattgacgtcggttacctactacgaacccagcgga
cgtgctcgtctttacatcatctcccttcacggagt-------------------------
----------ggaagtacgacgt-------------------------------------
---------cgcggacgtctgctccgctcgacctactagtgcgtgaaagctcatctgaga
tcaaacgcgttaccgtggcg
>SEQ9
----------------------------------------------------tctgacgc
gcaatagtggc-------------------------------------------------
----------------------------------cgggacactatctgcagtgagggggt
agaacaaccggaagaatagacggaacatgcgcaccgtatcgcaggaactaccggtgttaa
ggtgcgccctaggtatcatagagagtgtgtcggtcgaagttgcgctctcacctaaacttt
tccgcagtatttttgagagccctccaacccgattttatcttatgctctaggacgtggctc
tataaattgttcaagtactcccgaagaaagaagagtggtggtttcgacatcacgagggta
aagctactgg---------------------ataaaacgtcatatttcac----------
--------------tatgcactgcttcatggtacatacgtatgaacgcgccctcgttagt
cggcgagctggagggggagccgaaacccttctgtgcagaaaaatcctacgctttggtgtc
gtcataaaaacctcatgaagcgaagacgaggagtgtgtgttcaagtgcc-----------
-----atcaagcttatcttggttc--------------------gcgcac----------
-------gtccaacct--------------------------------------------
-------------------tgacgtctctgctagcttaaatttgagtctaaatggaacga
gccagtacgtctacgtggagcctcggaatgacgtcggttacctactacgaacccagcgga
cgtcgtcgtcctcaaatcacagcgctccacggagtgattcatgaaagttactaagatatc
gctttaagtgggaagtacgacgt---------------------------------attt
tact-------------------------------------catcaaagctcatctgatg
tcaaacgcgttaccgtggcg
>SEQ10
cataatgcctatcggtgacgtgccatggctatctgagc------------------gtct
acaatagtgctgtctacctaaaaggcgcgttggcctactcagctgccgacctatagtccg
tagcgctaccagcacaaccgtctatatgcgccaacggtacactagcttccgagagggggt
gcaacaaacgaaacacgtcacggaacatgcgcaccgtatcgcaggaactaccggtgttaa
ggtgcgccctaggtatcatagagagggtgtcggtcgaagttgcgctctcacctaaacttt
ttcagagtatgcttcagagggaacgagcccgcttttc-----------------------
--------------gttctccactgcacggaaaagtctgtctagcgcccacaagagcgta
aaggtgacggcttggctcga----------------------------------------
--------------ttcggactgcttcatggtacatacgtatgaacgcgccctcgttagt
cggcgcgctggagggggagccgaaacccttctgtgcagaaaaatcctacgctttggtgtc
gtcataacaacctcacgaagcgactacgaggagtatgtgttcaaatgcc-----------
-----atcaagtttatcttggttc------------------------------------
-------gcgcaccct--------------------------------------------
-------------------ttacatctctgctagcttaaatctgagtctaaatggaacga
gccggtacgtctacgtggagcctcggattgacgtcggttacctactacgaacccagcgga
cgtgctcgtctttacatcacctcccttcacggagc-------------------------
----------ggaagtacgacgt-------------------------------------
---------cgcggaggtctgctccgaccgacctcctagtgcgtga--------------
---------ttaccgtggcg
>SEQ11
----------------------------------------------------tgtgaggc
gctatagtgg--------------------------------------------------
----------------------------------cggggccctctctgcagtgaggggga
agaacaaccggaagaatagacggaacatgcgcaccgtatcgcaggaactaccggtgttaa
ggtgccccccaggtatcatagagagtgtgtcggtcgaagtttcgctctcacctaaacttt
gccggattatttctgagagccctcgagcccgatttccttttttgctt-------------
-------tgttcatgtactcccgggaaacaaaaagagtgtctttcgacataatgagggta
aagatgatgg---------------------ataaaacgtcaggtatcccgacattagaa
tcgtgataaaaggctttactctgcttcatggcacatacgtaagaacccgccctcgttagt
cggcgagctggagggggagccgaaacccttctgtgcagaaaaatcctacgctttgctgtc
atcgctaaaaccttctgatgcgaacgtgtgcaagatcggataatg---------------
--------------atctttttgcgacctacgcgtcaggaa-------------------
-------gtgcaaacagaggtgcggatagtgtaca-----------------gatgacct
tcctggccgtccgccgttctgacgtctctgctagcttaaatttgagtctaaatggaacga
gcccgtacgtctacgtgcagcctcggattgacgtcggttacctactacgaacccagcgga
cgccgtcgtcttgaaacccggtcc--------------------------------tatg
gcttcaagagggaattacgacgtaacgaccaacagcaaagctcaaaccttat--------
-------gtaacggaagtctgcaccgctagatcaaccggtacgtgaaggtgcgacct---
--------------------
>SEQ12
cataatgcctattcgagacgtgccatcgctatctgagc------------------gcac
ataatagtggtgtcaacctaaaagccgctttggcctagtcagatgccgac----------
-----------gtataaccgtctataggcgccaacgctacactagcttccgagagggggt
agaacaaatggaacacgtgtcggaacatgcgcaccgtatcgcaggaactaccggtgttaa
ggtgcgccctaggtatcatagagagggtgtcggtcgaagttgcgctctcacctaaacttt
ttcg--------------------gaacccgattatcttgtcaccatgaggacgaggttc
tctaatctg-------------------agaaaaatgcgtgttgagacatcaagagggta
aagggaatggttcggaacgatcacagctctaaataatcgtctcat---------------
--------------------ctgcttcatggcacatacgtatgaacccgccctcgttagt
cggcgagctggagggggagccgaaacccttctgtgcagaaaaatcctacgctttgctgtc
ttcactaaaatctcatgaagacaacgcgttaagtgtaggatcgagtacgaattacgaagt
tatcagtcaagattatcttttttcgacgttgtgacaaaacgccggcgcag----------
-------ctccaaacagaggtctgcattacgt----------------------------
-------------------tgacgtctctgctagcttaaatttgagtctaaatggaacga
gccagtacgtctacgtggagcctcggaatgacgtcggttacctactacgaacccagcgga
cgcaatcgcctttaaatcacatttctccacgcagtcatccatgaaagtaaaaaagatatg
gcttcaag----------------------------------------------------
--ctcgtgtcgcggtcgtctgctcggctcgacctactcgagcgtgaaagctcaactgatg
tcaaacgcgttaccgcggcg
>SEQ13
---------------------------------------cctaatgtcgctatctgacac
gaaattgtagtgtctaccgataaagctcttaggcctagtcag------------------
-------------------------------caagcgcacactatcttcagagagggggg
acgacatttggaagactggacggaacaggcgcaacgtatcgcaggaactaccggtgttaa
ggtgccccccaggtatcatagagagtgtgtcggtcgaagttgcgctctcacctaaacttt
tccgctgtctttttgagagccctcccacccgattttatcttatgctctaggacgtggctc
tataaat--------------------aagcagagtggtggtttcgacttcacga-----
-------------------------------atgaaacgtcatatttcac----------
--------------tatgcactgcttcatggtacatacgtatgaacccgccctcgttagt
cggcgagctggagggggagccgaaacccttctgtgcagaaaaatcctacgctttgctgtc
ttcactaaaatctcatgaagc-------------gtgtgctcgagtacggattacgaagt
taccagccaagattatctttt--------------aaaacaccggcgcag----------
-------ctccaaacgcagggttgca----------------------------------
-------------------tgacgtctctactagcttaaatttgagtctaaatggaacga
gccagtacgtctacgtggagcctcggaatgacgtcggttacctactacgaacccagcgga
cgtgctcgtctttaca--------------------------------------------
--------------atacgacgt-------------------------------------
---------cgcgaaggtctgctccactcgaccgaccagtgcgtgaacgctcatctgata
tcaaccgcgttaccgcggcg
>SEQ14
-------------------------------tctg-------------------------
------------------------------------------------------------
--------------------------------accgggccgctatctgctgtgagggggt
agaacaaccggaagaattgacggaacatgcgcaccgtatcgcaggaactaccggtgttaa
ggtgccccccaggtatcatagagagtgtgtcggtcgaagttgcgctctcacctaaacttt
gtcagtgtatgcttcagagggaacaagctcgctgttc-----------------------
--------------gttatccactgcacggaaaagtctgtctagcgcccacaagagcgta
aaggtgacggcttggctc------------------------------------------
------------------gactgcttcatggtacatacgtatgaacccgccctctttagt
cgacgagctggagggggagccgaaacccttctgtgtagaaaaatcctacgctttgctgtc
gtcataacaacctcacgaagctac-----------------caaatccc-----------
-----a----------------tc------------------------------------
-------gcgcaccct--------------------------------------------
-------------------tgacgtatctgctagcttaaatttgagtctgaatggaacga
gcccgtacgtctacgtgcagcctcggattgacgtcggttacctactacgaacccagcgga
cgtgctcgtctttacatcacctccctttacggagc-------------------------
----------tggaggaagacgt-------------------------------------
---------cgcgaag----------------------gtgagtga--------------
---------ttaccgtgacg
>SEQ15
----------------catgatgcctacgcgacttagcgacttttgaggacgagacacac
acaatagtggtgtctacataaaaggcgcttttggctagtcacatgccgttctgtaagacg
tagccct--------------------ccgccagcggttcactcacggccgggagggagg
agagcaaacagaatacgtgacggaacctgcgcaccgtatcgcaggaactaccggtgttaa
ggtgccccccaggtatcatagagagtgtgtcggtcgaagttgcgctctcacctaaacttt
gccggattatttctgagaaccctcgagcccgatctatttttttgctt-------------
-------tgttcatgtactcccgctaaa--------------------ctaatgagggta
aaaaggatgg---------------------acaaaacgtcaggtatcctgacattagaa
tcgggataaatgtctttactctgcttcatggtacatacgtatgaacgcgccctcgttagt
cggcgagctggagggggagccgaaacccttctgtgcagaaaaatcctacgctttggtatc
ttctcatgcatcctataag-----------------------------------------
tgtcagtcagcctagtgcccgttg------------------------------------
-------------------------------------taaggtagtaggctcactgacca
tccgggatatccactgtagttacatctctgctagcttaaatctgagtctgaatggaacga
gccggtacgtctacgtggagcctcggattgacgtcggttacctactacgaacccagcgga
cgtgctcggctttaaatcacctccctttcc------------------------------
----------tagaggaagacgt-------------------------------------
-----------------------------------------------------------a
gcgatggtgatagcgtgacg
>SEQ16
----------------------------------------------------tcagacgt
gcgatagtggggtctgccgaaaagccg---------------------------------
----------------------------------cggcaaactatcttcagagatggggt
agaacaaccggaagaagagacggaacatgcgcaccgtatcgcaggaactaccggtgttaa
ggtgccccccaggtatcatagagagtgtgtcggtcgaaggtgcgctctcacctaaacttt
gccggattatttcggagagccctt------------------------------------
-------------------------------tgaaaatgtcgttcgacataatgagggta
aagatgatgg---------------------ataaagcgtcaggtatcccgatattagaa
tcgtgagaaaaggccttactctgcttcatggcacatacgtatgaacccgccctcgttagt
cggcgagctggagggggagccgaaacccttctgtgcagaaaaatcctacgctttgctgtc
ttcacaaaaacttcac--------------cagtatgggttagagtgctggttatgaagt
tatcagtcaagaatatcttttttcgccgtagtgacaaaacgacggcgcag----------
-------gtccaaacagaggtgtgcattatgtcct-------------------------
-------------------tgacgtctctgctagcataaatttgagtctaaatggaacga
gcccgtacgtctacgtggagcctcggattgacgtcggttacctactacgaacccagcgga
cttcgtcgtctttgggtcacaaccctccgcggagtgacccatgaaagttact--------
--------------gtacgacgt---------------------------------attt
tgcacgtgtcgcgaacgtctgctccgctcgacctactcgtgcgtgaaagctcatctgatg
tcaaacgcgttaccgttgca
>SEQ17
catactgcatttcggggacgtgccgtggctatctgagg------------------gtct
acaatagtgctgtccacctagtaggcgcgttg-------------------catagtccg
tagcgcttctaggacaacggtgcgtaggcgccaacgg-----------------------
---acaaacgacacacgtcacggaacatgcgcaccgtatcgcaggaactaccggtgttaa
ggtgccccccaggtatcatagagagtgtgtcggtcgaagttgcgatctcacctaaacttt
ttcg--------------------gaacccgattatcttgtcaccatgaggacgacgttc
tctaatcgg-------------------agaaaaatgcgtgttgagaccttcgga-----
----------------acgatcacagctctaaaacatcgtctaat---------------
--------------------ctgcttcatggcacatacgtatgaacccgccctcgttagt
cggcgagctggagggggagccgaaacccttctgtgcagacaaatcctacgctgtgctgtc
ttctcg------------------------------------------------------
tgtcagtcag--------------------------------------------------
-------------------------------ccgttgaaaggtagtagactctctgacca
tccg---------------cgacgtatctgctagcttaaatttgagtctgaatggaacga
gcccgtacgtctacgtgcagcctcggattgacgtcggttacctactacgaacccagcgga
cgtcggcgtctttaaaccaggtccctacacgaaatgttccatcaaagt------------
---------------taagaagtgatgaccaatagctgacctcccacattatctagatct
gtcttgaataaccgacgtctgcgccgctcgttcaacccttaccttaacgcgcaaccga--
--------------atggcg
>SEQ18
----------------------------caatttgagccacttatgcggaccagacacac
acaataggggtgtctacctataagccgcttcggcctagtcagatgccgacgtataagtct
tagccctgcgagcacagccgtctatatgagccaacggtacagtagctcccgagagggggt
agaacaaacggaaca-----cggaacatgcgcaccgtatcgaaggaactaccggtgttaa
ggtgccccccaggtatcatagagagtgtgtcggtcgaagttgcgctctcacctaaacttt
ttcagagtattttgttgaggcatcgaaaccgattcttt----------------------
---agactgtccgagttctccactacaaagaaaagtgtgtgttgcgacctcaagagggta
acggttatggtttggcaggatcacaagtcttattaatcgtctgaaatcacgacattgtaa
ccgtgttcgga---------ctgcttcatggcacatacgtatgaacccgccctcgttagt
cggcgagctggagggggagccgaaacccttctgtgcagaaaaatcctacgctttgctgtc
gtcataacaacctcacgcagcgactacgaggagtgtctgttgaaatgcc-----------
------------------------------------------------------------
-------acgcaccct--------------------------------------------
-------------------tgacgtctctgctagcttaaatttgagtctaaatggaacga
gcccgtacttctacgtgcagcctcggattgacgtcggttacctactacgaacccagcgga
cgtcgtcgtctttaaaccaggtccctcttgggagtgatccatgaaagttaccaagatagg
gctgcaagagggaagttcgacgtaacgtcaaatagctcagctcataccttatagagatct
gactcgaataacggacatctgctccgctcgatcaacccttaagtaaaggt----------
----acacgctcccatggcg
>SEQ19
------------------------------------actaatgccatagctatctgacac
ccgata--gacatcttagggctaggca---------------------------------
------------------------------gcatcggcacattagctgcatagagggggt
aggacaactgattgactagacggaacatgcgcaccgtatcgcaggaactaccggtgttaa
ggtgccccccaggtatcatagagagtgtgtcggtcgaagttgcgctctcacctaaacttt
tccggagcatttctgatagccctcgagcccgattttcttttgtgctc-------------
---cact---------------------------------------acaacatga-----
--------gg---------------------ataaaacgtcaggtatcacgacattggaa
ccgagctaaa----------ctgcttcatggtacatacgtatgaacccgccctcgttagt
cggcgagctggagggggagccgaaacccttctgtgcagaaaaatcctacgctttgctgtc
gtcataaaaacctaatgaagcgaaagcgagcagttcgcgttcaagtgccatacttgaagt
taccagtcaagcatatcgttgttggtcgctgtgacaaaacgacggcgcag----------
-------gtcaaacct--------------------------------------------
-------------------ttacatctctgctagcttaaatctgagtctgaatggaacga
gccggtacgtctacgtggagcctcggattgacgtcggttacctactacgaacccagcgga
cgtcgtcgtcttcaatccaggtccgtccaggaagtgatccatgaaagctactaagatatg
gcttcaagagggaagtacgacgtaacatccaattgctcagcttaaaccttatagagatct
gactcgaataacgggcgtctgctccgttcgatccactctaacgtgtaggcgccaccgaag
tcacacacggtcccatcgcg
