>SEQ0
agctggaatggacagggtcttcctccaactacttggctgtcccattgacattagtccctc
ttgcgtgttggcctcctcgccgtgaaatacataagccgtagtgcgccggagccacagtcc
agtttcaaaggtaatcccttacgcatcgtgttatactgtttaaaagtcacgacgacaata
tgggttgcgactgtagctagcgtagtgattaggtaaagcttcataccgcggtgcataggc
aagtagaacatgtccgttttggatctccccccgaggtctgcttcggccaactaccacaca
agttctagccccgttggaagcaggacgaagccccggaattatcccgcttggagcgcagag
cctattctgtcggcatggtgctacgccactgtaagttgggttggttagtgtttctctaca
atcctgaacatccaatactgttaggataagtgtgaattaaatttgttataataggtcagc
cacaagccgccgctctgatcacggccacagtaggtcggtgtaaaccatttcagtagttag
ccacactggggcaccgtccctgtgttgaaatagtcagcgccgttacagggaatcatgctc
agatggcccgaggcctactcgcaagtgatcctggaaatgcgttagccttatgcggtattt
cgtgcagtatgggaatataggcagtatggagaacctatcatatacgatatccaggtggat
ctatgccaatttatgagtgcaccaaacacttctacaacgtatctttcagccaaagtttcc
ggcaaacgttttcccgttggtccatcgaaaaaagggctgacccagttttgtaagatacaa
tatcgtcgtaaacaaaggacgtttgccaaaccgacaacggtaccgggttcgtgcacggaa
aaatcgttccgtatacttaatctggtctagactcccccgcacaactgcgtgcgtggggac
atttgcaaccagcaggacacgggcgggatgtgctgggtaatcattccagtcttcgggcga
gaaaggaaccacgcttcgtcatatgtaattgaccacacatcacgcaaagtgatgtatttt
gctagagggatggtcctcac
>SEQ1
agctggaatcgacagggtcttcctccaactacgtggctgtcccattgacattagtccctc
ttgcgtgttggcctcctcgcggtgaaat-------------------------acagacc
agtttcaaaggtaatcccttacgcatcgtgtaatactgctc---------------aata
tggcttagtaccgtagctagcgtagtgattaggcaaagcttcataccgcggtgcataggc
aagtcgaacatgtccgttttggatctccccccgaggtctgcttcggccaactaccacaca
agttctagccccgttggaagcgagacgaagcgcaggaattaacccgctttgagcacagag
cctgttctgacgg-------------cactgtaagttgggttggttagtgtttctctaca
atcaagatcattccatactagtaggctaagtgtgaattaaatttgttctaataggtcagc
cacaagccgccgctttgatcacggccacagtaggtcggtgtaaaccatttcagtagttag
ccacactggggcaccgtccctgtgttgaaatagtcagcgccgttacagggaatcatgctc
agctggcccgaggcctgcccgcaattgatcctggatatgcgttagcctttgggga-----
----------------------------------------------agatccaggtggat
ctatgccaatttacgagtgcacaaaacacttctacatcgtatctttcagccaaattttcc
ggggaa---------gtttttccatcgaaaaaagggttcacccagttttgtaagatacaa
tatcgtcgtaaacaaaggacgtttgccaaaccgacaacggtaccgggttcgtgcacggaa
aaatcgttccgtatacttaatctggtctagactccaccgcacaaccgcgtgcgtggagac
atttgcaaccagcaggacacgggcgggatgtactgggtaatcattcgattcttcgggcga
gaaaggaa-----------------------------------gtaatttcatgtatttt
--------------------
>SEQ2
ggctggcatggacagggtcttcatccaactacgtggctctcccattgacattagtgcctc
ttgcgtgttgg-----------------------------------------------cc
agtttca-----------------ctcgtgtcatgctgctc---------------aata
tggcttagtaccgtagctagcgtagtgattaggtaaagcttcataccgcggtgcataggc
aagtagaacatgtccgttttggatctccccccgaggtctgcttcggccaactaccacaca
agttctcgccccgttggaagcgagacgaagcgaaggaattaccacgatttgagcacagag
cctgttctgacgg-------------cactgtaagtt-----------------------
----agatcattccatactagtaggctaagtgtcaattacatttgttctaataggtcagc
cacgaggcgccgctttgatcacggccacagtaggtcggtgtaaaccatttcagtagttag
ccacactggggcaccgtccctgtgttgaaatagtcagcgccgttacagggaatcatgctc
agctcgcccaaggcctgcccgcaattgatcctggatgggcgttagtctttgggga-----
----------------------------------------------agatccatgtggat
ctatgccaatttacgagtgcaaaaaacacttcgacttcgtatctttccgccaag------
-------------------ttccatcgaaaaaagggctgacccagttttgtaagatacaa
tatcgtcgtaaacaaagaacgtttgccaaaccgacaacggtaccgggttcgtgcacggaa
aaatcgttccgtatact---------------tcctccgcacaaccgcgtgcggggatac
atctgcaaccaacagga------------------gttaatcattcgattcttcggtcga
gaaaggaa-----------------------------------gtaatttcctgtattta
--------------------
>SEQ3
agctggaatgtccggggttttcctcccactactcggctgtcccattgacactagtccctc
ttccgtgttagactcctcgccgtgaaatacataagccgtagtgcgccggagccacagtcc
agtttgaaaggtaagcccttacgcatcgcgtgatactgattaaaagtcacgacgagaata
tgggttgcgagtgttggtagcgtagtgattaggtaaagcttcataccgcggtgcataggc
aagtagaacatgtccgttttggatctccccccgaggtctgcttcggccaactaccacaca
agttgtagcaccgttgga----------------------atcccgcttggagcgcagag
cctatactgtcggcatggtgctgcgccactgtaagttgggtcggttagtgtttctctaca
atcctaaacatccaatacggttaggataagtgtgacttagacttgatataagaggcgagc
cagaagccgctgctctgatcacggccacagtaggtcggtgtaaaccatttcagtagttag
ccacactggggcaccgtccctgtgttgaaatagtcagcgccgttacagggaatcatgctc
agatggctcgaggcctcctcgcaagtgatcctggaaaagcgtcagccttatgcggtattc
cgtgcagtgagggaatata-----------------------------------------
------------atgagtgcaccaaacacttccacaaggtatctgtgagcgaaagtttcc
cgcaaacgttatcccgtttgtccatcgaaaaaagggctgacccagttttgtaagatacag
tatcgtcgtaaacaaagaacgtttgccaaaccgacaacggtaccgggttcgtgcacggaa
taatcgttccgtatacttaatctggtctagacggcaccgcacaaccgcgtgcgtgcagac
attcgcaaccagtaggacgt-----------------taatcatacgattcttggggcga
gaaaggaa-----------------------------------gtaatttcatgtatttt
--------------------
>SEQ4
ggctggcatggacagggtcgtcacccaactacgtggctctcccattggcattagtgcctc
ttgtatcttg------------------------------------------------ct
agtttca-----------------gtcgtgtcatgctgctc---------------aata
tcgcttaataccgtaactagcgtagtgagtaggtaaagcttcataccgcggtgcataggc
aagtagaacatgtccgttttggatctccccccgaggtctgcttcggccaactaccacaca
agttcttgccccgttgaaagcagggcgaagcaccggaatcatcgcgcttggagcgcag--
----------cggcatggtgctacgccactgtaagtt----------------ctctaca
atcctgaacatccaatactgttaggttaag------------------tcataggtccgt
cacaagcccccgttctgatcacggccacagtaggtcggtgtaaaccatttcagtagttag
ccacactggggctccgtccctgtgttgaaatagtcagcgccgttacagggaatcatgctc
agatggctcgaggcctcctcgaaa--------------gcgtcagccttatgcggtactc
catgcagtgaggaaatgta-----------------------------------------
---------------agtgcaccaaacccttccacaaggtatctgtgagcgaaagtttcc
cgcaaacgt----------ttccatcgaaaaaagggctgacccaggtttgtaagatacaa
tatcgtcgtaaacaaaggacgtttgccaaaccgacaacggtaccgggttcgtgcacggaa
aaatcgttccgtatacttaatctggtctagactcccccgcgcaactgcgtgcgtggggac
atttgcaaccatcaggacacgggcgggatgtgctgggtaataattagaatcttcgggcga
gaaaggaa------------------ccattactaaacatcacgcaaagtgatgtatttt
gctagaggggtggtccccac
>SEQ5
agcaggaatcgacagggtcttcttcaaactacgtggctgtcccattgacattagtccctc
ttgcgcgtgggcccccccgcggtgcca---------------------------------
-gttttaaaggtaatccctaacgcatcgtgtaatactgtt---------------gaata
tggcttagtaccgtagctagcgtagtgagtaggtaaagcttcataccgcggtgcataggc
aagtagaacatgtccgttttggatctgcccccgaggtctgcttcggccaactaccacaca
agttgtagcaccgctg-------------------gcat---cccgcttggagagcagac
cctatactgtcggcatggtgctgcgccactgtaagttcggtcggttagtctttcgctaca
agcctagacatccattacggttaggaaaagtgtgacttagacttgatacaagaggcgagc
cagaagcctgtgctcgtatcacggccacagtaggtcggtgtaaaccatttcagtagttcg
ccacactggggctccgtccctgtgttgaaatagtcagcgacgttacagggaatcatgctc
agctcccccaaggcat-----------------------tgttagtctttgggga-----
----------------------------------------------agatccatggggat
ctatgacaatttacgcgtgcaaaaaacccttc---------g------------------
-------------------ttccatcgaaaaaagggctgacccagttttgtaagatacaa
tatcgtcgtaaacaaaggacgtttgccaaaccgacaacggtaccgggttcgtgcacgga-
------------------acaattgtctatacggcaccgcacaaccgcgtgcgtgcagac
attcgaaaccagtaggacgt-----------taatcaaacgctt------cttggggcga
gaaacgaa-----------------------------------gta--atttcaggtatt
tt------------------
>SEQ6
agctggaatcgacaggctcatcctccaactacgtgactgtcccattgacatcactccctc
ttgcgtgttggcctcctcgcggtgaaat-------------------------acagacc
agtttcatatgtaatccatc------------------------------------aaga
tgccatagtaccgtagctagcgtagtgattaggtcaagcttcataccgcggtgcataggc
aagtagaacatgtccgttttggatctccccccgaggtctgcttcggccaactaccacaca
agttctcgccccgtgggaagcgagacgaagcgaaagaattaccacga-------------
---------------------gacggcactgtaagtt-----------------------
----agatcattccatactagtaggcaaagtgttaactacatttgttctaa---------
-------------tttgaacacggccacagtaggtcggtgtaaaccatttcagtagttag
ccacactggggcaccgtccctgtgttgaaatagtcagcgccgttacagggaatgatgctc
aggtggcccaaggccggcccgcaattgaccctgtatgggcctta----------------
------------------------------------------------------------
------------gtaggtccat----------------gtatctttccgcaaac------
-------------------ttccatcgaaaaaagggctgacccagttttgtaagatacag
tatcgtcgtaaacaaagaacgtttgccaaaccgacaacggtaccgggttcgtgcacggaa
caattg-------------------tcgatacgacaccgcacatccgcgagcgtgcagcc
attcgaaaccagtatggcgt-----------------taatcaaactctacttggggcga
gaaacgaa-----------------------------------gtaatttcaggtatttt
--------------------
>SEQ7
agctggaatcgacaggctcattctccaactacgtgactgtcccagtggt-----------
------------------------------------------------gaaatacagacc
agtttcatatgtgatccatt------------------------------------aaga
tgccatattaccgtagctagcgtagtgattaggtcaagcttcataccgcggtgcataggc
aagtagaacatgtccgttttggatctccccccgaggtctgcttcggccaactaccacaca
cgttcttgccccgttgaaatcagggcgaagtaccggaatcatcgcgcttggagcgcag--
----------cggcatggtgctacgccacggtcattt----------------ctctacg
aatctgaacatccaatagtgttaggttaag------------------ccataggtccgt
tacaagcccccgttctgatcacggccacagtaggtcggtgtaaaccatttcagtagttag
ccacactggggctccgtccctgtgttgaaatagtcagcgccgttacagggaatcatgctc
tgatggcccgaggcctcgccgccagtgatcctggacaagcgtcagccttatgcggtattc
cgtgcagtgagggtatata-----------------------------------------
------------atgagtgcaccaaacacttccacaaggtatctgtgagcgaaagtttcc
gtcaaacattatcccgtttgtccatcgaaaaaagggctgacgcaggtttgtaagatacaa
tatcgtcgtaaacaaaggacgtttgccaaaccgacaacggtaccgggttcgtgcacggaa
atatcgttccgtatacctaatctggtatagac---------------------tagggac
atttgccaccaacaggacacgggcgggatgtgctgtgtaaactttccagtctttagtcag
a----------------------tgtaattgaccacacatcaagcaaagtgatgtatttt
gttagagggatggtcctcac
>SEQ8
agctggaatcgtca-------------------tggctgtcccaatgacattagtaagtc
tcgcgtgttggcctcctcgcggtgaaat-------------------------acagaac
agtttcaaaggtaatcccttacgcatcgtgtaatactgctc---------------aata
tacctttgtaccgtagctagcgtagtgattaggtcaagcttcataccgcggtgcataggc
aagtagaacatgtccgttttggatctccccccgaggtctgcttcggccaactaccacaca
cgttcttgccccgttgaaatcagggcgaagt-----------------------------
----------cgacatggtgctacgccacggt---------------------ctctacg
aatctgaacatccaatagtgttaggttagg------------------ccaggggtccgt
tacaagcccccgttctgatcacggcgacagtaggtcggtgtaaaccatttcagtagttag
ccacactggggcaccgtccctgtgttgaaatagtcagcgccgttacagggaatgatgctc
agatggtccgaggcctactc-----------------tgcgttagccttatgcggtattt
cgtgcagtatgggaatataggcagtaaggagaacatatcataaacggtatccaggtggat
ctatgccagtttatgagtgcacc----------------------------aatgtttcc
gacaaacgttttcccggtgctccatcgaaaaaagggctgacccacttttgtaagatacag
tatcgtcgtaaacaaagaacgtttgccaaaccgacaacggtaccgggttcgtgcacggaa
caattg-------------------tctatacggcaccatacaaccgcgtgcgtgcacac
attcgaaaccagtaggacgt-----------------taatcaaccgcttcttagcgcga
gaaacgga-----------------------------------gtaatttcaggtaattg
--------------------
>SEQ9
ggctggcatggactgggtcgtcacccaactacggggcgctcccataggcattattgcctc
ttttatcttg------------------------------------------------ct
agtttca-----------------gtcgtgtcatgctgctc---------------aata
tcgcttaatcgcgtaactagcgtagtgagtaggttaagcttcataccgcggtgcataggc
aagtagaacatgtccgttttggatctcaccccgaggtctgcttcggccaactaccacaca
agtttttacaagtccg--------------------------------------------
--------------------------cactgtaagtt-----------------------
----agatcattcgatacttgtaggcaaagtgtgaactacatttgttctaa---------
-------------tttgatcacggccacagtacgtcggtgtaaaccatttcagtagttag
ccacactggggcaccgtccctgtgttgaaatagtcagcgccgttacagggaatcacgctc
agctggcccgaggccggct-------------------gccttagcctt-----------
----------------------------------------------agatccaggtggat
ctatgccaatttacgacttcagaaaacacttctacatcgtatctttccgcccaattttcc
--------------------tccatcgaaaaaagggttcacccagttttgtaagatacaa
tatcgtcgtaaacaaaggacgtttgccaaaccgacaacggtaccgggttcgggcacggaa
caattg---------------------------------cacaaccgcgtgcgtgcagac
atgcgaaaccagtaggacgt-----------------taatcaaacgcttctttgcgcga
gaaacgaa-----------------------------------gcaat----tgtttttt
--------------------
>SEQ10
ggctggcatggagaaggtcgtcaccaaactacgtggctctc-------------------
------------------------------------------------------------
--------------------actgatagtatcatgctc------------------tata
tctctgaagaccgtaactagcgtagtgattaggtcaagcttcatcccgcggtgcataggc
aagtagaacatgtccgttttggatctccccccgaggtctgcttcggccaactaccacaca
cgttcttgccccgttgaaatctgggcgaagtaccggaatcatcgcgcttggagcgctg--
----------cggcatggtgctacgccacggtcattt----------------ctctacg
aatctgaacctacaacagtgctaggttcag------------------gcatatgtccgt
tacaagcccccgttctgatcacggccacagtaggtcggtggaaaccatttcagtagttcg
ccacactggggctccggccctgtgttgaaatagtcagcgacgttacagggaatcatgctc
agatggctcgaggcctcctcgcaagtgatcctggaaaagcgtcagtcttattcggtatcc
cgtgcag-----------------------------------------------------
------------atgagtgtaccaaacccttccacaaggtagctctgagcgaaagtttca
tgcaaaggttatcccgtttgtccatcgaaaaaagggctgacccagttttgtaagatacaa
tatcgtcgtaaacaaagaacgtttgccaaaccgacaacggtaccgggttcgtgcacggaa
aaatcgttccgtatact---------------tcctccgcacaaccgggggcggggatac
atctgcaaccaacagta------------------gttaaccattcgatacttcggtcga
gaaaagaa-----------------------------------gtaagtt----------
--------------------
>SEQ11
agctggaatgcccgaggttttcctcccactactaggcggtccgatcggtgtca-------
----------aacttctcgccgtgaaacacataagtcgtagtgcgccggaatcacagtcc
agtttgaaaggtaagcccttacgcatcgcgtgttaccgattaaaaagcacgacgagaata
tgggttgcgagtgtaggtagcgtagtgattaggtcaagcttcataccgcggtgcataggc
aagtagaacatgtccgttttggatctccccccgaggtctgcttcggccaacaaccacaca
agttctagcccggttgggagcagcaagaagccccggaattattccgcgtggagaacagag
cgtattctgtcggcatggtgctacgccactgtgagatgggt-------------------
------------------tggttagataagtgacgattaaat------------------
---aaacccccgctcttatcacgtcgacagtaggtcggtgtaaaccatttcagtagttag
ccacactggggcaccgtccctgtgttgaaatagtcagcgccgttacagggaatgatgctc
tgattgcccaaggtctcgccgccagagagcctggaca---------------cggtcttc
cgtgcagttagggtatata-----------------------------------------
------------gtcagtgcaccaaacacttccacaaggtatctttaagcgaaagtttcc
ctcgaacattatcacgttagtccatcgaaaaaagggctgacgcaggtttgtaagatacaa
tatcgtcgtaaacaaaggacgtttgccaaaccgacaacggtaccgggttcgtgcacggaa
gtatcgttccgtaaacctaatctggtatagac---------------------tagggac
atttgccaccaacaggacaggggcgggatgtgctgtctaaactttccagtctttagtcag
at-----------------------------------------gtgattgtccacatttg
-ttagagggatggtcctcag
>SEQ12
agcagcaatcgacagggtcttcttcaaactacgtggggatttc--------------ctc
ttgcgcgtgggcgccccctcggtg------------------------------------
---------------ccctaacgcatcgtgtaacattgtag---------------aata
tggcttagtaccgaagctagcgtagtgattaggtaaagcttcataccgcggtgcataggc
aagtagaacatgtccgttttggatctccccccgaggtctgcttcggcctactaccacaca
cg----------------------------------------------------------
----------cgacatggtg---------------------------------ctctacg
aatctgaacttccaatggtgttaggttagg------------------------------
--------------ccagggacggccacagtaggtcggtgtaaaccatttcagtagttag
ccacactggggcaccgtccctgtgttgaaatagtcagcgccgttacagggaatcatgctc
aaatggctcgaggcctcctcgaaa--------------gcgtgagccttaggcggtacac
catgcagtgatgaaat--------------------------------------------
------------gtaggggcaccaaacccttccacaagatatctgtgagcgaaagtttcc
cccaaacgt----------gtccatcgaaaaaagggttcacccagttttgtaagatacaa
tatcgtcgtaaacaaaggacgtttgccaaaccgacaacggtaccgggttcgggcacggaa
caatag---------------------------------cacaaccgggtgcgtgcagag
atgctcaacctttaggacgt-----------------taatcaaacgcttctttgcgcga
gaaacgag-----------------------------------gcaat----tgtttttt
--------------------
>SEQ13
---------------------------------------tcccattgacattagtccctc
ttgtgtgttggcctacgcgccgtgaaatacataagcccaagt------------------
-gcttcaaaggtaatcccttgcgcaacgagttatagtgtttcaaagtcacgacgacaata
tgggttgtgactgtagctagcgtagtgattaggcaaagcttcataccgcggtgcataggc
aaatcgaacatgtccgttttggatctccccccgaggtctgcttcggccaactaccacaca
cgttcttagcccgttg-------------------aaataagggcgcttcgag-------
-------------cgtggtgctacgccacggtcatt----------------tctgtacg
aatctgaacatccaatagtgttagg------------------ttaagccataggtccgt
gacaagcccccgttctgatcacggccacagtaggtcggtgtaaaccatttcagtagttag
ccacactggggctccgtccctgtgttgaaatagtcagcgccgttacagggaatcatgctc
aggtggcccaaggc----------------------------cggcccg-----------
------------------------------------------------------------
------caattgacacagtaaggaggtcatctttccgcaaac------------------
-------------------ttccatcgaaaaaagggttcacccagttttgtaagatacaa
tatcgtcgtaaacaaaggacgtttgccaaaccgacaacggtaccgggttcgggcacggaa
aaatcgttccggacagttaatctggtctagactcccgcgcgcaactgcttgcgtggggat
atttgca------aggatgt-----------gctaggtaatcttaagaagcttcgggcga
gagaggaa-----------------------------------gcattgtcatgtgtttt
gttagaggggtggtcccgac
>SEQ14
atgtggtatggacagggtcgt---------------------------------------
----------gtctcctcgccgtgaaatacctaagctgtagtgcgccggagacacagtcc
agtttcaaacgcaatcgcttacacatcgtgttatactgtttaaaaatcacgacgacaata
tgggtcgcgactgtagctagcgtggtgatttggaaaagcttcataccgcggtgcataggc
aagtagaacatgtccgttttggatctcccccccaggtctgcttcggccaactaccacaca
agttctagccctgatggaaccaggactaagccacggaattatcccgcttggagcgtagag
cctgttctgtcggcatggtgctacgccactgtaatttgggttggttagtgcttctctaca
atcctgaacctccaatactattaggataagtgtgaattatatttgatataataggtcagc
cacaagccaccggtctgatcacggccacagtaggtcggtgtaaaccatttcagtagttcg
ccacactggggctccgtccttgtgttgaaatagtcagcgacgttacagggaatcatgctc
ggagggcacgaggcctcctcgcaagag-------------------------------tc
cgtgcagtgaggggaaata-----------------------------------------
------------atgagtgcaccatacacttccacaaggtatctgtgggcgaaagtttcc
cgcaaacgttatcccatttgtccatcgaaagaagggttcacccagttttgtaagatacaa
tatcgtcgtaaacaaaggacgtttgccaaaccgacaacggtaccgggttcgggcacggaa
caattg---------------------------------cacaaccgcgtgcgtgccgaa
atgcaaaaccagtaggacgt-----------------taatctaacgcttcttttcgcga
gaaacgaa------------------------------------------attgtttttt
--------------------
>SEQ15
agcaggaaccaacagggtcttcttcaaactacgtggctgacccattgacattagaacctc
ttgcgcgtgggcgcccccccggtgcca---------------------------------
-gtttaaaaggtaatccctaacgcatcgtgtaatact-----------------------
--------ttccgtagcaagcgtagtgattaggcaaagcttcataccgcggtgcataggc
aagtcgaacatgtccgttttggatctccccccgaggtctgcttcggccaactaccacaca
cgtt------------------------------------------cttggaa-------
--------gtcgacatggtgctacgcaacgg---------------------tctctacg
aatctgaacatccaatagtgttagg------------------ttaggccaggggcccgc
taccaggccccgtactgatcacggccacagtaggtcggtgtaaaccatttcagtagttcg
ccacactggggctccgtccctgtgttgaaatagtcagcgacgttacagggaatcatgctc
agctcccccaaggcat-----------------------tgttagtctt----gt-----
----------------------------------------------agatccatggggat
ctatgacaatttacgcgtggcaaaagaccctc---------g------------------
-------------------ttccatcgaaaaaagggctgacccagttttgtaagatacaa
tatcgtcgtaaacaaagaacgtttgccaaaccgacaaccgtaccgggttcgtgcacgga-
------------------aatctggtcttgtctcccgcgcgcaactgcttgcgtggtgaa
agttgca------aggaggt-----------tctaggtatgcttaagaagcttggggcga
gcgaggaa-----------------------------------gca--gtcatgtgattt
gttagaggggtggtcccgat
>SEQ16
ggttcgcattgaccgggtcgtcacccaa---------------------------gcctc
ttttatcttg------------------------------------------------ca
agtttca-----------------gtcgtgtcatgctgctgcg-----------------
-----------------tgacgtagtgattaggcaaagcttcataccgcggtgcataggc
aagtcgaacatgtccgttttggacctccccccgaggtctgcttcggccaactaccacaca
agtcc--------------------agaagccccgcaattattctacgtggagaacagag
agactcctgtaggcatggtgctacgccaccgtgagatgggttggttag------------
--------------ataattgtcgattaaa------------------------------
--tagacccccgctcttatcacggccacagtaggtcggtgtaaaccatttcagtagttag
ccacactggggcaccgtccctgtgttgaaatagtcagcgccgttacagggaatcatgctc
aggttgcccaaggccggcccgcagttgaccctgtttggaggtccatt-------------
------------------------------------------------------------
---------------------------------------tatcattccgcaagc------
-------------------ttccatcgaaaaaagggctgacccagttttgtaagatacag
tatcgtcgtaaacaaagaacgtttgccaaaccgacaacggtaccgggttcgtgcacggaa
gaattg-------------------tctatacggcaccgcacaaccgc------------
------------------------------------------------ttcttggggtga
gaaactaa-----------------------------------gtaattggtagttt---
--------------------
>SEQ17
agcagcaatcgacagggt-------------------------------gggatttcctc
tagcgcgtcgtctcccccgcggtg------------------------------------
---------------ccctaactcatcttgtaacattgtaa---------------aata
tggcttagtaacgcagctagcgtagtgattaggcaaagcttcataccgcggtgcataggc
aagtcgaacatgtccgttttggagctccccccgaggtctgcttcggccaactaccacaca
agtacttgccacgttgaaagcatggcgaagcaccggaatcatcacgcttggagcccag--
----------cggtatggtgctgcgccactgt----------------------------
--------------acactgttaggttaag------------------tcataggtccgt
cacaagccccgttt-----cacggccacagtaggtcggtggaaaccatttcagtagttcg
ccacactggggctccggccctgtgttgaaatagtcagcgacgttacagggaatcatgctc
agctggccagaggcctgccagcaattgatcctggttatgggttagccttgga--------
----------------------------------------------agatccaggtggat
cgatgccatttta-------------------cacatcggatatttcagccaaattttcc
ggggaa---------gtttttccatcgaaaaaagggctgacccagttttgtaagatacag
tatcgtcgtaaacaaagaacgtttgccaaaccgacaacggtaccgggttcgtgcacggaa
caattg---------------------------------cacaaccgcctgcgttgagtc
atgcggaaccagtaggacgt-----------------taatcatacgcttcttggcgcga
gaaacgaa-----------------------------------gcaat----tgtttttt
--------------------
>SEQ18
agctagaacgtcaggggttttct------------------ccattgacactagggcttc
ttccgtgttagacttctcgccgtgaaatatataagccgtagaccgccggagccacagtcc
cgattgaaagataagcccttacgcatagcgtgatacag------------------atta
caagtcacgtctgttggtagcgtagtgat---gcaaagcttcataccgcggtgcataggc
aaatcgaacatgtccgttttggatctccccccgaggtctgcttcggccaactaccacaca
agttccagccccgtaggaagcgacacgaagcgcaggaattaacccgctttgag-------
----------------------acgccactgtaagtcgggttgattagtgtttctctaca
-------------------------------gtgaattaaatttgttctactaggtcagc
cacaagccgccgctttgatcacggccacagtaggtcggtgtaaaccatttcagtagttcg
ccacactggggctccgtccctgtgttgaaatagtcagcgacgttacagggaatcatgctc
aactgggccgaggcctgcccgcaagtgaccctggatatacgttagccgttgggga-----
----------------------------------------------agatccaggtggat
ctatgccaat------------aaaacagttcttcatcgtatctttcaaccaaattttcc
ggggaa---------gtttttccatcgaaaaaagggctgacccagttttgtaagatacaa
tatcgtcgtaaacaatcgacgtttgccaaaccgacaacggtaccgggttcgtgcacggaa
gtatcgttccgtaaacctaatct------------------------------tggggac
atttgccactaccaggacagggacgggatgtgctatctaaactttacagtctttagtgac
gt-----------------------------------------gtgattgtccacatttg
-ttagagggatggtactcag
>SEQ19
agctag-----------------------------------tcattgacactacggcttc
ttccgtgttagacttctcgccgtgaattatataagccgtaggtcac--------------
-gattgaaaggtaagcccttacgcatagcgtcgtgg------------------------
------------gtaggtagcgtagtgattaggtaaagcttcataccgcggtgcataggc
aagtagaacatgtccgttttggatctccccccgaggtctgcttcggccaactaccacaca
cgttcttgccccgttgaaattcgcgtt---------------------------------
------------------tgtcgcgctgctat-----------------------ctacg
aatctgagcctacaacagtgctaagttcag------------------gcatatgtccgt
tacaagcccccgttttgatcacggccacagtaggtcggtgtaaaccatttcagtagttcg
ccacactggggctccgtccctgtgttgaaatagtcagcgacgttacagggaatcatgctc
tggtggtccttagtaggtccat--------------------------------------
------------------------------------------------------------
--------------------------------------gtatctttccgcaaac------
-------------------ttccatcgaaaaaagggctgacccagttttgtaagatacag
tatcgtcgtaaacaaagaacgtttgccaaaccgacaacggtaccgggttcgtgcacggaa
caatta---------------------gatacgacgccgcacatccgcgagtgtgcagcc
attcgaaaccagtatgtctt-----------------taatcaaactctccgtgggggga
gcaacgaa-----------------------------------gtaatttgaggaatttt
--------------------
