>SEQ0
-ccaagcgccgcacctgtgtgagcgagattctacacgaaataaggtgacgaatcattgcc
ttagcatcctcctttccacacatctctccgctctttacagttgttaatggtgattaagtt
tagtccccccagtgacctgcccgtacgtgctagggaacctgcaatatcggtggttggatt
tcaagagtcaaaattcctaatcaaatcgtcagaacatcagagtgaggccgttgaaatatg
gtgattccttgttacctgctttccaatcattcaatgtgtcaggtttcaaggcaccagggc
gcgctaaactatgaataa---------------------aagcgtgacccttaaaccaat
ccatacaggtcccaaatgtccggtacgcggacaaccaaaatcatcgg--cccatgcaagc
accttcaactgggtaactttgtgtcaggtacctgaccaagatgaccggcgatatcattag
accgccacttatgaagaggatctcacaatgataaccctgcagacgcgggttctgcaccat
cctgatccgggtcggtaaccttagatccaatcactgttcttagtgccgggacacgctagg
ggacgccttccctgactgtatcaaactcccacggggacagccttgagagtcgctcatcga
gacagtcatagtgaaggacgtgaaggcagcactaacgacggccctcgatgcggcggtaga
aaatgcggacccgcgatgttcacgcacatatacgacggtagggctcacgcacagacaaga
aatccatcaagtagcgatcatgttggttacctttatgagaagatgaggtctgccctgcca
gtcttgaaatcatgaccagctgttgcacgggttttcgagcacctttaatgtttaggggct
gtctatcgagtatgctccctatgtgcaccccatcgcccgttaccccccccgaagcgactg
acgaggacctcagccaccaacagtcgaggggctcctgtatattcattatgtataggccgg
atcgctaccacccaattgagaaatgcgacattcgctaaactcgcaaaggggtgtagccct
catcctgttaccagcgctttcatctcccctacgtgactggccct
>SEQ1
-ccaagcgccgcacctgtgtgagcaagatgctatccgaaataaggtgacgaatcattgcc
ttagcatcctcctttccagacatctctccactctctacagtagtttatggtgattaagtt
tagtccctccagtga--------------------------caagatcggtggtcggatt
tcaagagtcaaaattccgaatcaaatcgtcagaacatcagagtgaggccgttgaaatatg
gtgattccttgttacctgctttccaatcattcaatgtgtcaggtttcaaggcaccagggc
gcgctaaactatgaataa---------------------aagcgtga-------------
----------------------------ggagaaccacaatcattgc--cccatgcaagc
tccttctactgggtaactttgtgtcaggtaccggaccaagattaccggcgatatcattag
gccacaacttataaggaggatctcacaatgataaccctgcaaacgcgggttctgcaccat
cctgatccggctcggtaaccttagatccaatcactgttcttagtgccgggacacgctagg
ggacgccttacctgactgtatcaaacgccgacggggacagccttgagagtcgctcatcgc
gacagtcatagacaaggacgtgaaggcagcactaacgacggccctcgattcggcggtaga
aaatgcggaccc-------------------acgacagtagggctcacgcacagacaagg
aatccatgaaatagctatcatgttggttacctttatgagaagaggaggtctgccctgcca
gtcttgaaatcatgaccagctgttgcacgggttttcgagcacctttaatgtttaggggct
gtctatcgagtatgctccctatgtgcaccccatcgcccgttaccccgcccgaagggactg
gcgaggccctcagccaccaacagccgaggggctgctgtatattcgttatgtatgggccgg
atcgctaccacccaattgagaaatgcgactttggaaaaccgcgcaaaggggtgtagccct
cattctgttaccagcgctttgatctccgctatgagactggccct
>SEQ2
---------------------cccaagatgctatccgaagtaaggtgacgattcactgcc
ttaacatcctcctttccagacatccctccactcactatagtagttaatggtgcttaagtt
tagcccctgcagtga--------------------------caggatcggtcgtcgaatt
tc-----------------aacaaatcgtcagaacatcagagtgaggccgttgaaatatg
gtgattccttgttacctgctttccaatcattcaatgtgtcaggtttcaaggcaccagggc
gcgctaacctatgaataa---------------------aagcgtgacccttacaccaat
acatacaacgc-----------------ggacaaccaaaatcatcgg--gccatgcaagc
aacttcaactgggtaactttgtgtcgggtacctgaccaaggtgaccggcgatgtcattag
accgccacttatgaagaggacttcac-------------ccgacgcgggttctgcaccat
cctgatccggctcggtaaccttagatccaatcactgttcttagtgccgggacacgctagg
ggacgccttacctgactgtatcaaacgacgacggcga---------------------aa
gacagttatagacaaggacgtgaagacagcactaatatcggccctcgattcgggggtaga
aaatgcggtacc-------------------acgacagtagggctcacgcaca-------
---------------aatcatgttggttgcctttatgagaagatgaggtctgccctgcca
gtcttgaaatcatgaccagctgttgcacgggttttcgagcacctttaatgtttaggggct
gtctatcgagtatgctccctatgtgcacctcatcgcccgttaccccgcccgaagcgac--
--------------------------aggggctgctgtatattcgt--------------
---gcttccacccaattgagaaatgcgacttaggaaaaccgcgcaaaggggagc------
-------ttaccagcgctttgatctctgctatgacagtggccct
>SEQ3
----------------------ccaagcgccacacctctgtaaggtgacgaatca-----
-------------------------ctccgctctttacagttgtttatggggatagagtt
tagtcgccccagtgaccagctcgtacatgctagggaacctgtaatatcgttggttggatt
tcaagagtcaaaattcctaatcaaatcgtcagaacaccagagtgaggccgttgaaatatg
gtgattccttgttacctgctttccaatcattcaatgtgtcaggtttcaaggcaccagggc
gcgctaaactatgaataa---------------------tag------------------
----------------------------gaagaaccacaatcattgc--cacatgcaatc
tccttctgctgggtaactttgtgtcaggtaccgga-------------------------
--cacaacttataaggtgaagct-------------------acgcgggttctgcaccat
cctgatccggctcggttaccttagatccaatcactgttcttagtgccgggacacgctagg
ggacgccttacctgactgtatcaaacgacgacggcga---------------------aa
gccagttatagacaaggacgtgaagagagcact---------------------tctaga
aagtgcggtgcc-------------------tcgacagtag-------------------
---------------gatcatgatggttgcctttatgagaagatgaggtctgccctgcca
gtcttgaaatcatgaccagctgttgcacgggttttcgagcacttttaatgtttaggggct
gtctatcgagtatgctccctatgtgcaccccatcgcccgttaccctccccgctg------
------------------------------------------------------taccgg
atcgctacaacccaagtgagaaatgcgactttggaaaaccgcgcataggggtttagccct
cattcttttaccagcgctttgacctccgctatgggactggctct
>SEQ4
----------------------cctagcgcagcaactgggtgagttgacggatcattgca
taagcatcgtcctttccacacctctct-------------------------ataaatat
tagtccccccactgacctgcccgtacgtgcgaggctgcctacaatatcggtggttgga--
-------------------ttcaaatcgtcagaacatcagagtgaggccgttgaaatttg
gtgattccttgttacctgctttccaatcattcaatgtgtcacgtttcaaggcaccagggc
gccctaaactatgagtaa---------------------aaggctgaccctccaaccaat
ccatacaggtcgcagatgtccggtacgcggacaaccaaaatcatcgg--cccatgcaagc
ctcttcaactgggtatctttgtgtcagatacctgaccaaggggaccggc-----------
------------------gatctcacaatgataaccctgaagacgcgggttctgcaccat
cctgatccggctcggtaaccttagatccaatcactgttcttagtgccgggacacgctagg
ggacgccttacctgactgtctcaatggacgacggaga---------------------aa
tacagtaatagactatgacgtgaagacagcactaacctcggccctcgattcgggggtaga
aattggggtacc-------------------acgacagtagtgctcactcaca-------
---------------aatcatgttggtcgcctt-----------gaggtctgccctgcca
gtcttgaaatcatgaccagctgttgcacgggttttcgagcacctttaatgtttaggggct
gtctatcgagtatgctccctatgtgcaccccagcgcccgttaccctccccgttg------
------------------------------------------------------taccgc
atctctacaacccaagtgagaaatgcgactttggaaaaccgc------------------
---------gccagcgctttgacctccgttatgagagtggctcc
>SEQ5
cccaagcgc---------------------ctatccgaagtaaggtgacgaatcactgcc
ttaacatcatccttttcagacatccctccaccccctatagtagttaatagtgcttaagtt
aagcccctgcagtga--------------------------caggatacgtcgtcgcatt
tc-----------------aacaaatcgtcagaacatcagagtgaggccgttgaaatatg
gtgattccttgttacctgatttccaatcattcaatgtgtcaggtttcaaggcaccagggc
gcgctaaactatgaataa---------------------aagcgtga-------------
----------------------------gcagagccacaatcattgc--cccctgcaagc
tccttctactgggcagctttgtgtcaggtaacggaccaagaataccggcgctatcattag
gccataacttataagggggatctaacaatgaaaaccctgcaaacgcgggttctgcaccat
cctcatccggctcggtaaccttagatccaatcactgttcttagtgacgggacacgctagg
ggacgccttacctgactgtatcaaactcccacggggacagccttgagattcgctaatcga
gaccgtcatagttaaggacgtgaaggcagcactaaggacagccctcgctgcggcggtaga
aaatgcggatccgcgatgttgacgcacatatacgacggtagggctcacgcacagataaga
aatctatcaagtagcgatcatattggttgcctctatgagaagatgaggtctgccctgcca
gtcttgaaatcatgaccagctgttgcacgggttttcgagcacctttaatgtttaggggct
gtctatcgagtatgctccctatgagcaccccatcgcccgttaccccgcccgaagggattg
gggacgccctcag-------------------------------gtaatgcatgggccgg
atcgctaccacccaattgtggaatgcgactttggaaatccgcgcaaaggggtgtagccct
ca----------------tggatctccgttatcagactggccct
>SEQ6
---------------------cccaagatgctaaccgaagttcggtgatgattgactgcc
ttaacatcctccgtgccagacatccctccgctcactatcgtagttaatggtgcttaagtt
tagcccctgcagtga--------------------------cag----------------
-------------------gacaaatcgtcagaacatcagagtgaggccgttgaaatatg
gtgattccttgttacctgctttccaatcattcaatgtgtcaggtttcaaggcaccagggc
gagcttaactacgaataa---------------------aagcgtga-------------
--------------------------------aaccataatcatttc--cccttgcaatc
tccttctaccgggtaactctgtatcaggtaacggaccaagattaccggcgatatccttgg
gccgcaacttataacgaggatctcacgatgaaaaccctgcaaacgcgggttctgcacgat
cctgatccggctcggtaaccttagatccaatcactgttcttagtgccgggacacgctagg
ggacgccttacctgactgtctcaaactcccacggcgacagccttgagagtcgcgcatcga
gtcagtcatagtgaaggacgtgaaggcagcactaacgacggccctcggtgcggcggtgga
aaatgcggacccgcgatgttcacgtacagatacgacgatagggctcccgcacagacaaga
aatccatcaaggagtgatcatgttggttacctctatgagaagatgaggtctgccctgcca
gtcttgaaatcatgaccagctgttgcacgggttttcgagcacctttaatgtttaggggct
gtctatcgagtatgctccctatgtgcaccccatcgcctgttaccctccccgcgg------
------------------------------------------------------aaccgg
atctctacaacccaagagagaaatgtgactttggaaaaccgcgcgttggggttcagccct
ccttcttgtaccagcgttttgacgtccgctatgtgactggctct
>SEQ7
cccaggcgc---------------------ctatccgaagtaaagtcaagaatcactgcc
ttaacatcatcctttttagagatacctccacccccttttgtagttaatagtgcttaagt-
-----------------------------------------ccggatacgtcgtggcctt
tt-----------------atcaaatcgtcagaacatcagagtgaggccgttgaaatatg
gtgattccttgttacctgctttccaatcattcaatgtgtcaggtttcaaggcaccagggc
gagcttaactacgaataa---------------------aagcgtga-------------
----------------------------------------------------ttgcaatc
tcctgctaccgggcaactctgtatcaggtaacggaccaag--------------------
--cgcaacgtataacgaggatctcacgatgaaaaccctgcaaacgcgggttctgcaccat
cctgatccggctcggtaaccttagatccaatcactgttcttagtgccgggacacgctagg
ggacgccttacctgactgtctcaaactcccacggggacagccttgagagtcgctcatcga
gtcagtcatagtgaaggacgtgtaggcagcactaatgacggccctcgatgcggcggtaga
aaatgctgacccgcaatgttcacgcacatctacgacggtaagtctcacgcacagacaag-
---------------gatcatgttggttacctttattagaaga-gaggtctgccctgcca
gtcttgaaatcacgaccagctgttgcacgggttttcgagcacctttaatgtttaggggct
gtctatcgagtatgctccctatgtgcaccccatcgcccgtgaccccg-------------
--------ctcag-------------------------------gtaatgcatggaccgg
atcggtaccacccaattgtggaatgcgacattggaaatccgcgcaaaggggtgtagccct
ca----------------tggaactaccttttcagactggcctt
>SEQ8
----------------------ccaagcgcggcaacgaaattaggtgaagaatcaatgcc
ttagcatcctccttaccactcatctctccgctctttacagttgttaacggtgataaagtt
cagtcacgacagtgacatgcacgtacgtg-------------------------cggatt
tcaagagtcaaaattcctaatcaaatcggcagaacaccagagtgagaccgttgaaatatg
gtgattccttgttacctgctttccaatcattcaatgtgtcaggtttcaaggcaccagggc
gccctaaactatgagtaa---------aacgctgaccctcca-accg-------------
----------------------------atccagccaaactcatcgg--cccatgcaagc
ctattcaactgggtatctttttgtcagatacctgatcaagg-------------------
------------gtaacggatctcacaatgataaccctgaagacgcgggttctgcaccat
cctcatccggctcggtaaccttagatccaatcactgttcttagtgacgggacacgctagg
ggacgccttacctgactgtatcaaacgaggacggcga---------------------at
gccatttatagacaaggacgtgaagagagcact---------------------------
-----------------------------------------------------tctatta
agtgtggtgccttaggatcatgatggatgcttttatgagaagatgaggtctgccctgcca
gtcttgaaatcatgaccagctgttgcacgggttttcgagcacctttaatgtttaggggct
gtctatcgagtatgctccctatgagcaccccagcgcccgttaccctccccgatg------
------------------------------------------------------taccga
atctctacaaccccagtgagaaatgcgactttggaaaaccg-------------------
---------cccagcgctttgacctccgttatgagattggctcc
>SEQ9
---------------------cccaagatgccaaccgaagttcggtgatgattgactgca
ttaacatccttcgtgccagacaacgctccgctcactatcgtagttaagagtgcttaactg
tagcc-------------------------------------------------------
-------------------caccaatcgtcaggacatcagagtgaggccgttgaaatatg
gtgattccttgttacctgctttccaatcattcaatgtgtcaggtttcaaggcaccagggc
gcgctaaactatgaa---------------------------------------------
-------------------------------ggaccacaaccattgc--cacatgcgatg
tccttttgctgggtaactttgtgtcaggtaccgga-------------------------
--cactacttataaggtgaagct---------------------gcgggttctgcaccat
cctgatccggctcggtaaccttagatccaatcactgttcttagtgccgggacacgctagc
ggacgccttacctgactgtctcaatcgacgacggcga---------------------aa
gaccgttatcgacaaggacgtgtacacagcact------------------gggggtaga
aaattcggttcc-------------------acgacagtagggctgacgcaaa-------
---------------aatcatgttggttgcctttatgagaagatgaggtctgccctgcca
gtcttgaaatcatgaccagctgttgcacgggttttcgagcacctttaatgtttaggggct
gtctatcgagtacgctccctatgtgcacctcatcgcaagttaccccgccggaaacgacag
gggctg------------------------------------------------------
--ctctgccccccgattgagaaatgcgccttgggaaaaccgcgcaaagcggagc------
----------------------ttactgatatgacagtggtcct
>SEQ10
----------------------ctaagcgcggcaacgaaattaggtgacgaataaatgcc
gtagcctcatcct-------------------------agttgtcaagggtgatatagtt
gagtcacgaccgtgacatgaacgtacgtg-------------------------c-----
------------------aatcaaatcgtcataacatcagagtgaggccgttgaaatatg
gtgattccttgttacctgctttccaatcattcaatgtgtcaggtttcaaggcaccagggc
gcgctaaactatgaataatccatacagggccctaatttccggtactc-------------
----------------------------ggacaaccaaaatcatcgg--cccatgcaagc
accttcaacagggtagatttgtgtcaggtacctgacccagatgcccggcgatatcattac
atccccccttatgaggaggatctcacaatgataaccctacagtcgcgggttctgcaccat
cctgatccggctcgtcaaccttagatccaatcactgttcttagtgccgggacacgctagg
ggacgccttacctgactgtctcaaacgaggacggagt---------------------at
gccatttatagacaagg-------------act---------------------------
-----------------------------------------------------tctatta
agtgttgtgccttaggatcatgatggatgcttttatgagaagatgaggtctgccctgcca
gtcttgaaatcatgaccagctgttgcacgggttttcgagcacctttaatgtttaggggct
gtctatcgagtacgctccctatgtgcaccccagcgcccgttac-----------------
--------------------------------------------------------tcga
atctctacaacccctgtgagaaatgcgactttgggaaaacg-------------------
---------accagcgctttgacctccgttatgcgattggatcc
>SEQ11
---------------------cccaagatgtcaaccgaatgtcggtgatgattgactgca
ttaacatcct---------------------tcactatcgtagttaagagtgcttaacgg
tagcc-------------------------------------------------------
-------------------cacaaatcgtcagaacatcagagtgaggccgttgaaatatg
gtgattccttgttacctgatttccaatcattcaatgtgtcaggtttcaaggcaccagggc
gcactaaacaatgagtaa---------------------aacgctgaacctccaaccg--
----------------------------gtccagccaaacttatcgt--actatgcaagc
ctattcaactgggaatctttttgtcagatacctgatcaagggtaacg-------------
------------------ggtatcacaatgataaccgccaagccgcgggttctgcaccat
cctgatccgggtcggtaaccttagatccaatcactgttcttagtgccgggacacgctagg
ggacgccttacctgactgtctcaatcgacgacggcgg---------------------aa
gaccaatatctacaaggacgtgcccacaccactggggg----------------------
-------------------------------actacagtacggctgacgcaaa-------
---------------agtcatgatggttgcctt-----------gaggtctgccctgcca
gtcttgaaatcatgaccagctgttgcacgggttttcgagcacctttaatgtttaggggct
gtctatcgagtatgctccttatgtgcaccccagtgcccgttac-----------------
--------------------------------------------------------tcga
atctctacaacccctgtgagaaatgcgacttggggaaaacc-------------------
---------accagcgctttgacctccgttatgccattggatcc
>SEQ12
---------------------gccaagagggtaaccgaagttcgg---------------
--------------------------------cactatcgtagttaatggtgcttaagtt
taacccctgcagtga--------------------------cag----------------
-------------------gacaaatcgtcagaacatcagagtgaggccgttgaaatatg
gtgattcctagttacctgctttccaatcattcaatgtgtcaggtttcaaggcaccagggc
gcgctaaaccat------------------------------------------------
----------------------------acagggccctaatttccactactcatgcaagc
acctgaaacagggaagatttgtgtcaggtacctgaaccagatgcccggcgatatcattac
atcacccattatgaggaggatcttacaatgataatcctacagtcgcgggttctgcaccat
cctgatccggctcggtaaccttagatccaatcactgttcttagtgccgggacacgctagg
ggacgccttacctgactgtatcaaacgccgacgaggacagccttgagagtcgctcatcgc
g------------------gtgaaggcagcactaacgacggccctcgatacggagc----
-------------------------------acgacagtggggctcaggcacatacaatg
--------------------------------------------gagatctgccctgcca
gtcttgaaatcatgaccagctgttgcacgggttttcgagcacctttaatgtttaggggct
gtctatcgagtatgctccctatgtgcaccccatcgcctgttaccctccccgcgg------
------------------------------------------------------------
--------accccaagagagaaatgtg--------------cgcgttggcgatcagccct
ccttcttgtaccagcgctttgacgtccgctatgtgactggctct
>SEQ13
---------------------cccaagcgcctttccgaagt-------------------
--aacatcatccttttcagacatc-----------------------tagagcttaagtt
aagcccttacagtgaca-------------------------------------------
-------------------ggcaaatcgtcagaacatcagagtgaggccgttgaaatatg
gtgattccttgttacctgatttccaatcattcaatgtgtcaggtttcaaggcaccagggc
gcgctaacgtatgaataa---------------------cagcgtga-------------
----------------------------gcagagccgcaatcattgc--accattcaagc
tccttctacggggcagcttatcgtcaggtaacggaccaagaataccggcgctatcattag
gccagaacttataagggggatctaagaatgaaaaccctgcaaaagcgggttctgcaccat
cctcatccggctcggtaaccttagatccaatcactgttcttagtgacgggacacgctggg
ggacgtcttacctgactgtatcaaacgacgacggcgc---------------------aa
gacagttagagccaaggacgtgaatacagcacttatatcggccctcaacc----------
------------------------------------------------------------
---------------aatcatgttggttgcccttatttgacgatgaggtctgccctgcca
gtcttgaaatcatgaccagctgttgcacgggttttcgagcacctttaatgtttaggggct
gtctatcgagtatgctccctatctgcacgccaggccccggtac-----------------
--------------------------------------------------------tcga
atctatacaacccctgtgagaaatgcgactatggtaaaccg-------------------
---------accagcgctttaacctccgttatgcgattggatcc
>SEQ14
----------------------gtaagcgcggcaacgaatttaggttacgaataaattcc
gtagcctcatc-------------------------atagctgtcaagggtgatattatt
gagtcacgtccgtgacatgaacgtaca---------------------------------
-------------------atccaatcgtcagaacatcagagtgaggccgttgaaatatg
gtgattccttgttacctgctttccaatcattcaatgtgtcaggtttcaaggcaccagggc
gcgctaaactatgcataa---------------------aagcgtga-------------
----------------------------tcagagccacaaccattgc--cccttgcaagc
tccttctacttggcagctttgtgtcagggaacggaccaagtataccggcgctatcattag
g---------------------------------------aaacgcgggttctgcaccat
cctgatccggctcgtcaaccttagatccaatcactgttcttagtgccgggacacgctagg
ggacgccttacctgactgtctcgaactcccacggggacagccttgagagtcgctcatcga
gacagtcatagtgaatgacatgaagtcagcactatcgacagccctcgatccgggggtagt
aaatgcggacccgcgatg--------------------------ttacgaacagacgaga
aatccatcaagt-------------attacctttatgagaagatgaggtctgccctgcca
gtcttgaaatcatgaccagctgttgcacgggttttcgagcacctttaatgtttaggggct
gtctatcgagtatgctccctatgtgcaccccagcgccggttac-----------------
--------------------------------------------------------tcta
atctctacaacccctttgagaaatgcgactttggggaaacg-------------------
---------accagcgctttaacctccgttttgcgattggatcc
>SEQ15
-------------------------------------cgaagcgccgagattctattgcc
ttagcatccggctttccacacatctctaccctctttacacttgttaatggtgattaagtc
tagtccccccagtaacctggccggacatactagggaacctgcaatatcggtggatggatt
tcaagagtcaaagttcctaatcaaatcgtcagatcatcagagtgaggccgttgaaatatg
gtgattccttgttacctgctttccaatcattcaatgtgtcaggtttcaaggcaccagggc
gccccaaactatgagtag---------------------aacgcagaccatcagccaaac
tca---------------------------------------------------------
---tcggacttgggatctttttgtcagatacctgatcacgggtaac--c-----------
------------------------------------ctgaagatgcgggttctgcaccat
cctgatccggctcggttaccttagatccaatcactgttcttagtgccgggacacgctagg
ggacgccttacctaactgtatcaaacgatgacagcga---------------------aa
gacagttatagacagggacgtgaagacagccct-aatatcggcc----------------
-------------------aaatgcggtaccacgacagtaggtctcacgcacaa------
----------------atcatggtcgttgcctttat------g-gagatctgccctgcca
gtcttgaaatcatgaccagctgttgcacgggttttcgagcacctttaatgtttaggggct
gtctatcgagtatgctccctatgtgc----------------------------------
------------------------------------------------------------
-----------------------------------aatctataca---------------
---------acccatgtttggatcc-------------------
>SEQ16
-------------------------------------caaagcgccgagggcgtatttcc
ttagcatccggccatccacgcacctctaccctcttcacacatgttaaaggtcattaagtc
tagtccccccagtaacctggccggacatactatggaacctttaatatcgttggatggatt
tcaagagtcaaagttcctaatcaaatcttcagaacatcagagtgaggccgtcgaaatatg
gtgattccttgttacctgatttccaatcattcaatgtgtcaggtttcaaggcaccagggc
gccctaaactatgagaaa---------------------taggctgacccctcacccaat
ccatacaggtcgcagatgt------------------------------ccgcagcacgc
ctcttcaactgggtatctttttgtccgatacgtgaccaaggggaccggc-----------
------------------------------------gtgaagacgcgggttctgcacgat
cctgatccggctcggtaaccttagatccaatcactgttcttagtgccgggacacgctagg
ggacgccttacctgactgtctcaacctcccatcggcacagccttgagtgtcgctcatcga
gacagtcagagtgaaggacgtgtaggcggccctcgatgcagcgg----------------
-------------------gcacgcacatccacgacggtaaatctcacgcacaggcaag-
---------------catcatgttggttacctctattagaaca-gaggtctggcctgcca
gtcttgaaatcatgaccagctgttgcacgggttttcgagcacctttaatgtttaggggct
gtctatcgagtatgctccctatgtgcacctcatcgcccttgaccccgtccgaag------
---------------------------------------------------------cga
cttcgttccacccaattgagaaatgcgacttaggaaaaccgcgtt---------------
---------accagcgctttaatctttgcaatgacattggacct
>SEQ17
-------------------------------------cgaagcgccgagattctattccc
ttagcatccggctttccgcacatctctaccctctttacgcttgttaggggtgattaagac
tactcccctcagtaacctgggcggacattctagggaacctgc------------------
----------------ctaatcaaatcggcagaacaccagagtgagaccgttgaaatatg
gtgattccttgttacctgctttccaatcattcaatgtgtcaggtttcaaggcaccagggc
gcgccaaaccat------------------------------------------------
----------------------------atagggccctaatttccactactcatgcaacc
cccagaaacagtgaagatctgtgtcaggtatctgaaccagatgcccggcgatatcattac
atccccagttttgaggaggatcttataat---------------gcgggttctgcaccat
cctgatccggctcggttaccttagatccaatcactgttcttagtgccgggacacgctagg
ggacgccttacctgactgtatcaaacaacgacggcgc----------------------a
agcatatagagccaaggacgttaatacagcacttctatcggccctca-------------
------------------------------------------------------------
----------------------------accataatttgacgatgaggtctgccctgcca
gtcttgaaatcatgaccagctgttgcacgggttttcgagcacctttaatgtttaggggct
gtctatcgagtatgctccctatgtgcagcccatggcccggtg------------------
--------------------------------------------gtaatgcatgggccgg
atcgctaccacccaattgtggaatgcgactttgggaatccgcgcaaaggggtgtagccct
ca----------------tggaactccgttatcagactggacct
>SEQ18
----------------------ccaagagcggcaacggaattaggtgaagaatcaacgcc
tgagcatcctccttcccacttatctctccgctctttacagttattagcggtgataaagtt
cagtcacgacagggacattcacttacgtg-------------------------cggatt
tcaagagtcaaacttcctaatcaaatcgtcagaacatcagagtgaggccgttgaaatatg
gtgattccttgttacctgctttccaatcattcaatgtgtcaggtttccaggcaccagggc
gcgctaaactatgaataa---------------------aagcgtga-------------
----------------------------ggagaaccagaatcatagc--gtcttgccatc
ttcttctactgggtaactttgtctcaggtaccgtacaaagattgccggcgatatcatt--
------------gggccagaatacacaatgataaccctgcaaacgcgggttctgcaccat
cctcatccggctcggtaaccttagatccaatcaccgttcttagtgacgggacacgctagg
ggacgccttacctgactgtatcaaactccgacggcgacagccttgagagtcgcgcatcga
gtcagtcatagtgagagacgtgatggcagcactaactacggccctcggtgcggcggtgga
aaatgccgacccgcgatgttcacgtacagatacgacgacaggactcccgcatagacaaga
aatacatcaacgagtgaacatgttggttacctctatgagaaaatgagatctgccctgcca
gtcttgaaatcatgaccagctgttgcacgggttttcgagcacctttaatgtttaggggct
gtctatcgagtatgctccctatgtgcaccccagcgcccgttaccctgcacgttg------
------------------------------------------------------tacctc
atctctacaacccaagtgagaaatgcgacttcggaaaaccgc------------------
---------accagcgctttgaccaccgttatgagagtgactcc
>SEQ19
-------------------------------gccaagaggttaaccgcaggtcggcttta
t-----------------------------------------------------------
-----------------------------cgtagttacctccagtgacag----------
--------------------gcaaatcgtcagaacatcagagtgaggccgttgaaatatg
gtgattccttgttaccttatttccaatcattcaatgtgtcaggtttcaaggcaccagggc
gc----aagcgtgag---------------------------------------------
------------------------------------------------------gcacgc
tacttatactgggcagctttgt------------accaagaataccggcggtatc-----
-------------agggggatctaacaatgaaaaccctgtaaacgcgggttctgcaccat
cctgatccggctcgtcaaccttagatccaatcactgatcttagtgccgggacacgctagg
ggacgccttacctgactgtctcgatggacgacggaga---------------------aa
tacagtaatagactatgacgtgaatacagcaataacctcggccctcgattcg--------
---------------------------------gacagttgtgctcactcaca-------
---------------actcatgttggtcgcctt-----------gagatctgccctgcca
gtcttgaaatcatgaccagctgttgcacgggttttcgagcacctttaatgtttaggggct
gtctatcgagtatgctccctatgtgcaccccagcgctcgt--------------------
------------------------------------------------------------
-----gacaacacctgtgagaaatgcgaatttgggtcgacg-------------------
---------accagcgctttgacctccgttatgggattggatcc
