>Carnegiea_gigantea 1067 bp 
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------ccgcgccgggggcaacccccggcgccgcaacgaaaccccggcgcgaa
ccgcgccaaggaacacgaactcatggcgtgcccgcccgcgcccgttccgccggcgcgcgg
gggcggcacctgcccctacttaa-aacgtaacgactctcggcaacggatatttcgg--ct
ca-tggtagacgagcacctcgcaaactgcgatacttggtgtgaattgcagaatcccgtga
accatcgagtctttgaacgcaagttgcgcccgaagccttccggccgagggcacgtctgcc
tgggcgtcacgcatcgcgcctcccgccccc-cgcccgcc-----ggggggggaggatgat
ggcctcccgcgccccagccggggcgcggctggcctaaaacgggagcccgcggcgacgagc
tgcggcggcgattggtggtggacg-aggcctcaagtggccgccgtttgcatcgcgccgcg
cacgcacgccgccgggaagggctcgtcggaccctgacgtg--tgctggaagcacagaacc
gttgcgaccccaggtca-ggcggggctacccgctgagtttaagcatatcaataagcggag
gaaaagaaacttacaaggattcccctagtaacggcgagcgaaccgggaagagcccagctt
taaaatcgggcggcctcgccgtccgaattgtagtctggagaagcgtcctctgcggcggac
cgggcccaagtcccctggaaaggggcgccggagagggtgagagccccgtcgtgcccggac
cctgtcgcaccacgagcctgtcgc--------------
>Cephalocereus_senilis 1067 bp 
------------------------------------------------------------
------------------------------------------------------------
-----------------------------caaggtttcctaggtaaggatcattgtcgaa
a-ctgcccagcagaaaga-cc-gcgaacatg-tttaccccaacatgcggggaggggtgcc
tcg-gctccctccccgcgccgggggcaacccccggcgcagcaacgaaaccccggcgcgaa
ccgcgccaaggaacacgaaatcatggcgtgcccgcccgcgcccggtccgccggcgcgcgg
gggcggcacctgtccctacttaa-aaagtaaagactctcggcaacggatatctcggctat
tgacatcgatgaagaaagtagcgaaatgcgataattggtgtgaattgcagaat-ccgtga
accatcgagtttttgaaagcaagttgcgcccgaagccttccggccgagggcacgtctgcc
tgggcgtcaagcatcgcgcctccccccc---cgcccgcc----gggggagggaggatgtt
ggcctcccgcgcccctgtcggggcgcggctggcctaaaacgggagcccgcggcgacgagc
ggcggcggcgattggtggtggacg-aggcctcaagtggccgccgtttgcatcgcgccgcg
cccgcgcgccgccgggtagggctcgtcggaccctgacgtg--tgcaggaagcacaaaacc
gttgcgaccccaggt---aggggggctacccgctaaat----------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------
>Myrtillocactus_schenckii 1067 bp 
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------aggatcattgtcgaa
acctgcccagcagaaagaccc-gcgaacgtgttttgccccaacatgcggggaggggtgcc
tcg-gccccctccccgagccgggggcagcccccggcgcagcaacgaaaccccggcgcgaa
ccgcgccaaggaacacgaactcatggcgtgcccgcccgcgcccggtccgccggcgcgcgg
gggcggcacctgtccctacttaagaacgtaacgactctcggcaacggatatctcggctct
cg-catcgatgaagaacgtagcgaaatgcaatacttggtgtgaattgcagaatcccgtga
accatcgagtctttgaacgcaagttgcgcccgaagccttccggccgagggcacgtctgcc
tgggcgtcacgcatcgcgcctccccccc---cgcc--------ggggggggaaggatgat
ggcctcccgcgccccgggcggggcgcggctggcctaaaacgggagcccgcggcgacgagc
tgcggcggcgactggtggtggacg-aggcctcgagcggccgccgtttgcatcgcgccgcg
cacgcacgccgccggggcgggctcgtcggaccctgacgtgcttgctgaaagcacagaacc
gttgcgaccccaggtca-ggcggggctacccgctgagtttaagcatatcaataagcggag
gaaaagaaacttacaaggattcccctagtaacggcgagcgaaccgggaagagcccagctt
taaaatcgggcggcctcgccgtccgaattgtagtctggagaagcgtcctctgcggcggac
cgggcccaagtcccctggaaaggggcgccagagagggtgagagccccgtcgtgcccggac
cctgtcgcaccacgag----------------------
>Neobuxbaumia_euphorbioides 1067 bp 
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------gaaggatcattgtcgaa
a-ctgcccagcagaaaga-cc-gcgaacatg-tttaccccaacatgcggggaggggtgcc
tcg-gccccctccccgcgccgggggcaacccccggcgccgcaacgaaaccccggcgcgaa
ccgcgccaaggaacacgaactcatggcgtgcccgcccgcgcccggtccgccggcgcgcgg
gggcggcacctgtccctacttaa-aacgtaacgactctcggcaacggatatctcggctct
ct-catcgatgaagaacgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtga
accatcgagtctttgaacgcaagttgcgcccgaagccttccggccgagggcacgtctgcc
tgggcgtcacgcatcgcgcctccccccccctcgcccgcc------gggggggaggatgat
ggcctcccgcgccccagccggggcgcggctggcctaaaacgggagcccgcggcgacgagc
ggcggcggcgattggtggtggacg-aggcctcaagtggccgccgtttgcatcgcgccgcg
cacgcacgccgccgggtagggctcgtcggaccctgacgtg--tgcaggaagcacagaa-c
gttgcgacccca------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------
>Neobuxbaumia_mezcalaensis 1067 bp 
------------------------------------------------------------
------------------------------------------------------------
-----------------tcacaaatttaaatatgtttattgcggaaggatcattgtcgaa
a-ctgcccagcagaaaga-cc-gcgaacatg-tttaccccaacatgcggggaggggtgcc
tcg-gccccctccccgcgccgggggcaacccccggcgccgcaacgaaaccccggcgcgaa
ccgcgccaaggaacacgaactcatggcgtgcccgcccgcgcccggcccgccggcgcgcgg
gggcggcacctgtccctacttaa-aacgtaacgactctcggcaacggatatctcggctct
cg-catcgatgaagaacgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtga
accatcgagtctttgaacgcaagttgcgcccgaagccttccggccgagggcacgtctgcc
tgggcgtcacgcatcgcgcctccccccc---tgcccgcc------gggggggaggaggat
ggcctcccgcgcccctgccggggcgcggctggcctaaaacgggagcccgcggcgacgagc
ggcggcggcgattggtggtggacg-aggcctcaagtggccgccgtttgcatcgcgccgcg
cacgcgcgccgccgggtagggctcgtcggaccctgacgtg--tgcaggaagcacaaaa-c
gttgcgacccca-gtcaggcgggggctacccgctgaattt--------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------
>Neobuxbaumia_multiareolata 1067 bp 
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------gaaggatcattgtcgaa
a-ctgcccagcagaaaga-cc-gcgaacatg-tttaccccaacatgcggggaggggtgcc
ccg-gccccctccccgcgccgggggcaacccccggcgccgcaacgaaaccccggcgcgaa
ccgcgccaaggaacacgaactcatggcgtgcccgcccgcgcccggtccgccggcgcgcgg
gggcggcacctgtccctacttaa-aacgtaacgactctcggcaacggatatctcggctct
ct-catcgatgaagaacgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtga
accatcgagtctttgaacgcaagttgcgcccgaagccttccggccgagggcacgtctgcc
tgggcgtcacgcatcgcgcctcccccccc--tgcccgcc-----ggggggggaggatgat
ggcctcccgcgcccctgtcggggcgcggctggcctaaaacgggagcccgcggcgacgagc
ggcggcggcgattggtggtggacg-aggcctcaagtggccgccgtttgcatcgcgccgcg
cccgcgcgccgccgggtagggctcgtcggaccctgacgtg--tgcaggaagcacaaaacc
gttgcgacccca-gtca-ggcggggctaccc-ctgaatttaagca---------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------
>Neobuxbaumia_polylopha 1067 bp 
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------ctgcggaaggatcattgtcgaa
a-ctgcccagcagaaaga-cc-gcgaacatg-tttaccccaacatgcggggaggggtgcc
tcg-gccccctccccgcgccgggggcaacccccggcgcagcaacgaaaccccggcgcgaa
ccgcgccaaggaacacgaactcatggcgtgcccgcccgcgcccggtccgccggcgcgcgg
gggcggcacctgtccctacttaa-aacgtaacgactctcggcaacggatatctcggctct
cg-catcgatgaagaacgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtga
accatcgagtctttgaacgcaagttgcgcccgaagccttccggccgagggcacgtctgcc
tgggcgtcacgcatcgcgcctccccccct--cgcccgcc-----gggggggggagaggtt
ggccctccgcgcccctgccggggcgcggctggcctaaaacgggagcccgcggcaacaagc
ggcggcggcaattggtggtggacg-aggcctcaaatggccgccgtttgcatcgcgccgcg
cacacacaccgccgggtagggctcgtcggaccctgatatg--tgcaggaaacacaaaacc
gttgcaacccca-gtcaggcgggggctacccgctgaatttaagcatat------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------
>Neobuxbaumia_scoparia 1067 bp 
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------cggaaggatcattgtcgaa
a-ctgcccagcagaaaga-cc-gcgaacttt-tttaccccaacatgcggggaggggtgcc
ccg-gccccctccccgcgccgggggcaacccccggcgccgcaacgaaaccccggcgcgaa
ccgcgccaaggaacacgaactcatggcgtgcccgcccgcgcccggtccgccggcgcgcgg
gggcggcacctgtccctacttaa-aacgtaacgactctcggcaacggatatctcggctct
cg-catcgatgaagaacgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtga
accatcgagtctttgaacgcaagttgcgcccgaagccttccggccgagggcacgtctgcc
tgggcgtcacgcatcgcgcctcccccccc--tgcccgcc-----ggggggggaggatgat
ggcctcccgcgcccctgccggggcgcggctggcctaaaacgggagcccgcggcggcgagc
ggcggcggcgattggtggtggacg-aggcctcaagtggccgccgtttgcatcgcgccgcg
cacgcgcgccgccgggtagggctcgtcggaccctgacgtg--tgcaggaagcacaaaa-c
gttgcgacccca-gtca-g-----------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------
>Neobuxbaumia_tetetzo 1067 bp 
------------------------------------------------------------
------------------------------------------------------------
----------------------------------catgggacggaaggatcattgtcgaa
a-ctgcccagcagaaaga-cc-gcgaacatg-tttaccccaacatgcggggaggggtgcc
ccg-gccccctgcccgcgccgggggcaacccccggcgccgcaacgaaaccccggcgcgaa
ccgcgccaaggaacacgaactcatggcgtgcccgcccgcgcccggcccgccggcgcgcgg
gggcggcacctgtccctacttaa-aacgtaacgactctcggcaacggatatctcggctct
cg-catcgatgaagaacgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtga
accatcgagtctttgaacgcaagttgcgcccgaagccttccggccgagggcacgtctgcc
tgggcgtcacgcatcgcgcctcccccc----cgcccgcc------gggggggaggaggat
ggcctcccgcgcccctgccggggcgcggctggcctaaaacgggagcccgcggcgacgagc
ggcggcggcgattggtggtggacg-aggcctcaagtggccgccgtttgcatcgcgccgcg
cacgcgcgccgccgggtagggctcgtcggaccctgatgtg--tgcaggaagcacaaaacc
gttgcgacccca-gtca-ggcggggctacccgctgagtttaagcatatcaataagcggag
gaaaagaaacttacaaggattcccctagtaacggcgagcgaaccgggaagagcccagctt
taaaatcgggcggcctcgccgtccgaattgtagtctggagaagcgtcctctgcggcggac
cgggcccaagtcccctggaaaggggcgccagagagggtgagagccccgtcgtgcccggac
cctgtcgcaccacgagggctgtgcca------------
>Pachycereus_fulviceps 1067 bp 
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------ctgcggaaggatcattgtcgaa
a-ctgcccagcagaaaga-cc-gcgaacatg-tttaccccaacatgcggggaggggtgcc
tcg-gccccctccccaagccgggggcaacccccggcgccgcaacgaaaccccggcgcgaa
ccgcgccaaggaacacgaactcatggcgtgcccgcccgcgcccggtccgccggcgcgcgg
gggcggcacctgtccctacttaa-aacgtaacgactctcggcaacggatatctcggctct
cg-catcgatgaagaacgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtga
accatcgagtctttgaacgcaagttgcgcccgaagccttccggccgagggcacgtctgcc
tgggcgtcacgcatcgcgcctcccccc----cgcccgcc-----gggggggaaggatgat
ggcctcccgcgcccctgtcggggcgcggctggcctaaaacgggagcccgcggcgacgagc
tgcggcggcgattggtggtggacg-aggcctcaagtggccgccgtttgcatcgcgccgcg
cacgcgcgccgccggggagggctcgtcggaccctgacgtg--tgtgggaagcacaaaacc
gttgcgacccca-gtca-ggcggggccacccgctgagtttaagcatatcaataagcggag
gaaaagaaacttacaaggattcccctagtaacggcgagcgaaccgggaagagcccagctt
taaaatcgggcggcctcgccgtccgaattgtagtctggagaagcgtcctctgcggcggac
cgggcccaagtcccctggaaaggggcgccagagagggtgagagccccgtcgtgcccggac
cctgtcgcaccacgagggctgt----------------
>Pachycereus_gatesii 1067 bp 
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------------tgtcgaa
acctgcccagcagaaaga-cc-gcgaacatg-tttaccccaacatgcggggaggggtgcc
tcg-gccccctccccgcgccgggggcaacccccggcgccgcaacgaaaccccggcgcgaa
ccgcgccaaggaacacaaactcatggagtgcccgcccgcacccggtccgccggcgcgcgg
gggcggcacctgtccctactgaa-aacgtaacgactctcggcaacggatatctcggctct
cg-catcgatgaagaacgtagcgaaatgcgatacttggtgtgaattgcagaat-ccgtga
accatcgagtctttgaacgcaagttgcgcccgaagccttcgggccgagggcacgtctgcc
tgggcgtcacgcatcgcgcctccccccccc-cgcccgcg-----gggggggaaggatgat
ggcctcccgcgccccggccggggcgcggctggcctaaaacgggagcccgcggcgacgagc
tgcggcggcgattggtggtggacg-aggcctcaggtgggcgccgtttgcatcgcgccgcg
cacgcacgccgccgggaagggctcgtcggaccctgacgtg--tgctggaagcacaaaacc
gttgcgaccccaggtca-ggcggggctacccgctgagtttaagcatatcaataagcggag
gaaaagaaacttaccaggattcccctagtagcggcgagcgaaccgggaagagcccagctt
taaaatcgggcggcctcgccgtccgaattgtagtctggagaagcgtcctctgcggcggac
cgggcccaagtcccctggaaaggggcgccagagagggtgagagccccgtcgtgcccggac
cctgtcgcaccacgaggcgctttccccattcgggtttt
>Pachycereus_gaumeri 1067 bp 
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------gcggaaggatcattgtcgaa
acctgcccagcagaaaga-cc-gcgaacatg-tttaccccaacatgcggggaggggtgcc
tcg-gccccctccccgcgccgggggcaacccccggcgccgcaacgaaaccccggcgcgaa
ccgcgccaaggaacacgaactcatggagtgcccgcccgcgcccggtccgccggcgcgcgg
gggcggcacctgtccctactgaa-aacgtaacgactctcggcaacggatatctcggctct
cg-catcgatgaagaacgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtga
accatcgagtctttgaacgcaagttgcgcccgaagccttccggccgagggcacgtctgcc
tgggcgtcacgcatcgcgcctccccccc---cgcccgccggggggggggggaaggatgat
ggcctcccgcgccccggccggggcgcggctggcctaaaacgggagcccgcggcgacgagt
tgcggcggcgattggtggtggacg-aggcctcaagtggccgccgtttgcatcgcgccgcg
cacgcacgccgccgggaagggctcgtcggaccctgacgtg--tgctggaagcacaaaa-c
gttgcgacccca-gtca-ggcggg------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------
>Pachycereus_grandis 1067 bp 
----------------------tacgattgaatggtcc-ggtgaagtgttcggatcgcgg
cgacgtgggcggttcgccgccggcgacgtcgcgagaagtccactgaaccttatcatttag
aggaaggagaagtcgtaacaaggtttccgtaggtgaacctgcggaaggatcattgtcgaa
acctgcccagcagaaaga-cc-gcgaacatg-tttaccccaacatgcggggaggggtgcc
tcg-gccccctccccgcgccgggggcaacccccggcgccgcaacgaaaccccggcgcgaa
ccgcgccaaggaacacgaactcatggcgtgcccgcccgcgcccggtccgccggcgcgcgg
gggcggcacctgtccctacttaa-aacgcaacgactctcggcaacggatatctcggctct
cg-catcgatgaagaacgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtga
accatcgagtctttgaacgcaagttgcgcccgaagccttccggccgagggcacgtctgcc
tgggcgtcacgcatcgcgcctcccgccccc-cgcccgcc---ggggggggggaggatgat
ggcctcccgcgccccagccggggcgcggctggcctaaaacgggagcccgcggcgacgagc
tgcggcggcgattggtggtggacg-aggcctcaagtggccgccgtttgcatcgcgccgcg
cacgcacgccgccgggaagggctcgtcggaccctgacgtg--tgctggaagcacagaacc
gttgcgacccca-gtca-gggcgg------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------
>Pachycereus_hollianus 1070 bp 
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------ctgc-ggaagatcattgtcgaa
a-ctgcccagcagaaaga-cc-gcgaacatgttttgccccaacatgcggggaggggtgcc
ycg-gccccctccccgagccgggggcagcccccggcgcagcaacgaaaccccggcgcgaa
ccgcgccaaggaacacgaactcatggcgtgcccgcccgcgcccggtccgccggcgcgcgg
gggcggcacctgtccctacttaagaacgtaacgactctcggcaacggatatctcggctct
cg-catcgatgaagaacgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtga
accatcgagtctttgaacgcaagttgcgcccgaagccttccggccgagggcacgtctgct
tgggcgtcacgcatcgcgcctccccccc---cgcccgcc-----gggggggaaggatgat
ggcctcccgcgccccggtcggggcgcggctggcccaaaacgggagcccgcggcgacgagc
tgcggcggcgattggtggtggacg-aggcctcgagtggccgccgtttgcatcgcgccgcg
cacgcacgccgccggggcgggctcgtcggaccctgacgtgtttgctgaaagcacagaacc
gttgcgaccccaggtca-ggcggggctacccgctgagtttaagcatatcaataagcggag
gaaaagaaacttacaaggattcccctagtaacggcgagcgaaccgggaagagcccagctt
taaaatcgggcggcctcgccgtccgaattgtagtctggagaagcgtcctctgcggcggac
cgggcccaagtcccctggaaaggggcgccagagagggtgagagccccgtcgtgcccggac
cctgtcgcaccacgag----------------------
>Pachycereus_lepidanthus 1067 bp 
-----------------------accgattgaatggtccggtgaagtgttcggatcgcgg
cgacgtgggcggttcgccgccggcgacgtcgcgagaagtccactgaaccttatcatttag
aggaaggagaactcgtaac-aggtttccgtatgtgaacctgc-ggaagatcattgtcgaa
a-ctgcccagcagaaaga-cc-gcgaacatgtcttgccccaacatgcggggaggggtgcc
tcgtgccccctccccgagccgggggcagcccccggcgcagcaacgaaaccccggcgcgaa
ccgcgccaaggaacacgaactcatggcgtgcccgcccgcgcccggtccgccggcgcgcgg
gggcggcacccgtccctacttaaaaacgtaacgactctcggcaacggatatctcggctct
cg-catcgatgaagaacgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtga
accatcgagtctttgaacgcaagttgcgcccgaagccttccggccgagggcacgtctgcc
tgggcgtcacgcatcgcgcctcccccc----cgcccgcc-------gggggaaggatgat
ggcctcccgcgccccggccggggcgcggctggcccaaaacgggagcccgcggcgacgagc
tgcggcggcgattggtggtggacg-aggcctcgagtggccgccgtttgcatcgcgccgcg
cacgcacgccgccggggcgggctcgtcggaccctgacgtgtttgctgaaagcacagaacc
gttgcgaccccaggtca-ggcggggctacccgctgagtttaagcatatcaataagcggag
gaaaagaaacttacaaggattcccctagtaacggcgagcgaaccgggaagagcccagctt
taaaatcgggcggcctcgccgtccgaattgtagtctggagaagcgtcct-tgcggcggac
cgggcccaagtcccctggaaaggggcgccagagagggtgagagccccgtcgtgcccggac
cctgtcgcaccacgagcgtgt-----------------
>Pachycereus_marginatus 1067 bp 
---------------------------ttgaatggtcc-ggtgaagtgttcggatcgcgg
cgacgtgggcggttcgccgccggcgacgtcgcgagaagtccactgaaccttatcatttag
aggaaggagaagtcgtaacaaggtttccgtaggtgaacctgcggaaggatcattgtcgaa
acctgcccagcagaaaga-cc-gcgaacatg-ttcaccccaacatgcgggaaggggtgcc
tcg-gccccctccccgcgcccggggcaacccccggcgcagcaacgaaaccccggcgcgaa
ccgcgccaaggaacacgaacgcatggcgtgcccgcccgcgcccggtccgccggcgcgcgg
gggcggcacctgtcccaactgaa-aacgtaacgactctcggcaacggatatctcggctct
cg-catcgatgaagaacgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtga
accatcgagtctttgaacgcaagttgcgcccgaagccttccggccgagggcacgtctgcc
tgggcgtcacgcatcgcgcctccccccc---cgcccgccgggggggggggggaggatgat
ggcctcccgcgccccggccggggcgcggctggcctaaaacgggagcccgcggcgacgagc
tgcgacggcgattggtggtggacg-aggcctcagatggccgccgtttgcatcgcgccgcg
cacgcacgccgccgggaagggctcgtcggacccggacgtg--tgctggaagcacaaaacc
gttgcgaccccaggtca-ggcggggctacccgctgagtttaagcatatcaataagcggag
gaaaagaaacttacaaggattcccctagtaacggcgagcgaaccgggaagagcccagctt
taaaatcgggcggcctcgccgtccgaattgtagtctggagaagcgtcctctgcggcggac
cgggcccaagtcccctggaaaggggcgccagagagggtgagagccccgtcgtgcccggac
cctgtcgcaccacgaggcgctt----------------
>Pachycereus_militaris 1067 bp 
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------aaggatcattgtcgaa
acctgcccagcagaaaga-cc-gcgaacatg-ttttccccaacatgcggggaggggtgcc
tcg-gccccctccccgcgccgggggcaacccccggcgccgcaacgaaaccccggcgcgaa
ccgcgccaaggaacacgaactcatggcgtgcccgcccgcgcccggtccgccggcgcgcgg
gggcggcacctgtccctacttaa-aacgtaacgactctcggcaacggatatctcggctct
cg-catcgatgaagaacgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtga
accatcgagtctttgaacgcaagttgcgcccgaagccttccggccgagggcacgtctgcc
tgggcgtcacgcatcgcgcctccccccc---cgcccgccggggggggggggaaggatgat
ggcctcccgcgccccggccggggcgcggctggcctaaaacgggagcccgcggcggcgagc
tgcggcggcgattggtggtggacg-aggcctcgagtggccgccgtttgcatcgcgccgcg
cacgcacgccgccggggagggctcgtcggaccctgacgtg--tgctgaaagcacagaacc
gttgcgacccca-gtca-ggcggggctacccgctgagtttaagcatatcaataagcggag
gaaaagaaacttacaaggattcccctagtaacggcgagcgaaccgggaagagcccagctt
taaaatcgggcggcctcgccgtccgaattgtagtctggagaagcgtcctctgcggcggac
cgggcccaagtcccctggaaaggggcgccagagagggtgagagccccgtcgtgcccggac
cctgtcgcaccacgaggcgcgt----------------
>Pachycereus_pringlei 1067 bp 
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------cggaaggatcattgtcgaa
acctgcccagcagaaaga-cc-gcgaacatg-tttaccccaacatgcggggaggggtgcc
tcg-gccccctccccgcgccgggggcaacccccggcgccgcaacgaaaccccggcgcgaa
ccgcgccaaggaacacgaactcatggcgtgcccgcccgcgcccggtccgccggcgcgcgg
gggcggcacctgtccctacttaa-aacgtaacgactctcggcaacggatatctcggctct
cg-catcgatgaagaacgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtga
accatcgagtctttgaacgcaagttgcgcccgaagccttccggccgagggcacgtctgcc
tgggcgtcacgcatcgcgcctcccgccccc-cgcccgcc----gggggggggaggatgat
ggcctcccgcgccccagccggggcgcggctggcctaaaacgggagcccgcggcggcgagc
tgcggcggcgattggtggtggacg-aggcctcaagtggccgccgtttgcatcgcgccgcg
cacgcacgccgccgggaagggctcgtcggaccctgacgtg--tgctggaagcacagaacc
gttgcgacccca-gtcagggcggggctacccgctgagtttaagcatatcaataagcggag
gaaaagaaacttacaaggattcccctagtaacggcgagcgaaccgggaagagcccagctt
taaaatcgggcggcctcgccgtccgaattgtagtctggagaagcgtcctctgcggcggac
cgggcccaagtcccctggaaaggggcgccagagagggtgagagccccgtcgtgcccggac
cctgtcgcaccacgaggcgct-----------------
>Pachycereus_schottii 1067 bp 
----------------------tacgattgaatggtcc-ggtgaagtgttcggatcgcgg
cgacgtgggcggttcgccgccggcgacgtcgcgagaagtccactgaaccttatcatttag
aggaaggagaagtcgtaacaaggtttccgtaggtgaacctctggaaggatcattgtcgaa
acctgcccagcagaaaga-ccggcgaacatg-tttaccccaacatgcggggaggggtgcc
tcg-gccccctccccgcgccgggggcaacccccggcgccgcaacgaaaccccggcgcgaa
ccgcgccaaggaacacaaactcatggagtgcccgcccgcgcccggtccgccggcgcgcgg
gggcggcacctgtccctactgaa-aacgtaacgactctcggcaacggatatctcggctct
cg-catcgatgaagaacgtagcgaaatgcgatacttggtgtgaattgcagaat-ccgtga
accatcgagtctttgaacgcaagttgcgcccgaagccttcgggccgagggcacgtctgcc
tgggcgtcacgcatcgcgcctccccccccc-cgcccgcg-----gggggggaaggatgat
ggcctcccgcgccccggccggggcgcggctggcctaaaacgggagcccgcggcgacgagc
tgcggcggcgattggtggtggacg-aggcctcaggtgggcgccgtttgcatcgcgccgcg
cacgcacgccgccgggaagggctcgtcggaccctgacgtg--tgctggaagcacaaaacc
gttgcgaccccaggtca-ggcggggctacccgctgagtttaagcatatcaataagcggag
gaaaagaaacttaccaggattcccctagtagcggcgagcgaaccgggaagagcccagctt
taaaatcgggcggcctcgccgtccgaattgtagtctggagaagcgtcctctgcggcggac
cgggcccaagtcccctggaaaggggcgccagagagggtgagagccccgtcgtgcccggac
cctgtcgcaccacgaggcgc------------------
>Pachycereus_tepamo 1067 bp 
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------tcattgtcgaa
acctgcccagcagaaaga-cc-gcgaacatg-tttaccccaacatgcggggaggggtgcc
tcg-gccccctccccgcgccgggggcaacccccggcgccgcaacgaaaccccggcgcgaa
ccgcgccaaggaacacgaactcatggcgtgcccgcccgcgcccggtccgccggcgcgcgg
gggcggcacctgtccctacttaa-aacgcaacgactctcggcaacggatatctcggctct
cg-catcgatgaagaacgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtga
accatcgagtctttgaacgcaagttgcgcccgaagccttccggccgagggcacgtctgcc
tgggcgtcacgcatcgcgcctcccgccccc-cgcccgcc----gggggggggaggatgat
ggcctcccgcgccccagccggggcgcggctggcctaaaacgggagcccgcggcgacgagc
tgcggcggcgattggtggtggacg-aggcctcaagtggccgccgtttgcatcgcgccgcg
cacgcacgccgccgggaagggctcgtcggaccctgacgtg--tgctggaagcacagaacc
gttgcgacccca-gtca-ggcggggctacccgctgagtttaagcatatcaataagcggag
gaaaagaaacttacaaggattcccctagtaacggcgagcgaaccgggaagagcccagctt
taaaatcgggcggcctcgccgtccgaattgtagtctggagaagcgtcctctgcggcggac
cgggcccaagtcccctggaaaggggcgccagagagggtgagagccccgtcgtgcccggac
cctgtcgcaccacgaggcg-------------------
>Pachycereus_weberi 1067 bp 
tgtacacactgcccgtcgctcctacgattgaatggtcc-ggtgaagtgttcggatcgcgg
cgacgtgggcggttcgccgccggcgacgtcgcgagaagtccactgaaccttatcatttag
aggaaggagaagtcgtaacaaggtttccgtaggtgaacctgcggaaggatcattgtcgaa
acctgcccagcagaaaga-cc-gcgaacatg-tttaccccaacatggggggaggggtgcc
ccg-gccccctccccgcgccgggggcaacccccggcgccgcaacgaaaccccggcgcgaa
ccgcgccaaggaacacgaactcatggcgtgcccgcccgcgcccggtccgccggcgcgcgg
gggcggcacctgtccctacttaa-aacgcaacgactctcggcaacggatatctcggctct
cg-catcgatgaagaacgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtga
accatcgagtctttgaacgcaagttgcgcccgaagccttccggccgagggcacgtctgcc
tgggcgtcacgcatcgcgcctcccgccccc-cgcccgcc---ggggggggggaggatgat
ggcctcccgcgccccagccggggcgcggctggcctaaaacgggagcccgcggcggcgagc
tgcggcggcgattggtggtggacg-aggcctcgagtggccgccgtttgcatcgcgccgcg
cacgcacgccgccgggaagggctcgtcggaccctgacgtg--cgctggaagcacagaacc
gttgcgacccca-gtca-ggcgg-------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------
>Stenocereus_aragonii 1067 bp 
------------------------------------------------------------
------------------------------------------------------------
---------------taacaaggtttccgtaggtgaacctgcggaaggatcattgtcgaa
acctgcccagcagaaaga-cc-gcgaacatg-tttaccccaacatgcggggaggggcgcc
tcg-gccccctgcccgcgccgggggcaacccccggcgcagcaacgaaaccccggcgcgaa
ccgcgccaaggaacacgaactcatggcgtgcccgcccgcgcccggtccgccggcgcgcgg
gggcggcacctgtccctacttaa-aacgtaacgactctcggcaacggatatctcggctct
cg-catcgatgaagaacgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtga
accatcgagtctttgaacgcaagttgcgcccgaagccttccggccgagggcacgtctgcc
tgggcgtcacgcatcgcgcctcccgccccc-cgcccgcc-----ggggggggaggatgat
ggcctcccgcgccccagccggggcgcggctggcctaaaacgggagcccgcggcgacgagc
tgcggcggcgattggtggtggacgaaggcctcaagtggccgccgtttgcatcgcgccgcg
cacgcacgccgccggggagggctcgtcggaccctgacgtg--tgctggaagcacagaacc
gttgcgacccca-gtca-gg----------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------
>Stenocereus_chrysocarpus 1067 bp 
---------------------------ttgaatggtccgggtgaagtgttcggatcgcgg
cgacgtgggcggttcgccgccggcgacgtcgcgagaagtccactgaaccttatcatttag
aggaaggagaagtcgtaacaaggtttccgtaggtgaacctgcggaaggatcattgtcgaa
acctgcccagcagaaagaccc-gcgaacatgttctgccccaacatgcggggaggggcgcc
tcg-gccccctccccgagccgggggcagcccccggcgcagcaacgaaaccccggcgcgaa
ccgcgccaaggaacacgaactcatggcgtgcccgcccgcgcccggtccgccggcgcgcgg
gggcggcacctgtccctacttaagaacgtaacgactctcggcaacggatatctcggctct
cg-catcgatgaagaacgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtga
accatcgagtctttgaacgcaagttgcgcccgaagccttccggccgagggcacgtctgcc
tgggcgtcacgcatcgcgcctccccccc---cgcccgcc----ggggggggaaggatgat
ggcctcccgcgccccggccggggcgcggctggcctaaaacgggagcccgcggcgacgagc
tgcggcggcgactggtggtggacg-aggcctcgagcggccgccgtttgcatcgcgccgcg
cacgcacgccgccggggcgggctcgtcggaccctgacgtgtttgctgaaagcacagaacc
gttgcgaccccagg----------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------
>Stenocereus_eichlamii 1067 bp 
------------------------------------------------------------
------------------------------------------------------------
----------------aaaaaagtttccgtaggtgaacctgcggaaggatcattgtcgaa
acctgcccagcagaaaga-cc-gcgaacatg-tttaccccaacatgcggggaggggcgcc
tcg-gccccctgcccgcgccgggggcaacccccggcgcagcaacgaaaccccggcgcgaa
ccgcgccaaggaacacgaactcatggcgtgcccgcccgcgcccggtccgccggcgcgcgg
gggcggcacctgtccctacttaa-aacgtaacgactctcggcaacggatatctcggctct
cg-catcgatgaagaacgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtga
accatcgagtctttgaacgcaagttgcgcccgaagccttccggccgagggcacgtctgcc
tgggcgtcacgcaccgcgcctcccgccccc-cgcccgcc----cggggggggaggatgat
ggcctcccgcgccccagccggggcgcggctggcctaaaacgggagcccgcggcgacgagc
tgcggcggcgattggtggtggacgaaggcctcaagtggccgccgtttgcatcgcgccgcg
cacgcacgccgccggggagggctcgtcggaccctgacgtg--tgctggaagcacagaacc
gttgcgaccc-a-gtca-ggcggggctaccc-----------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------
>Stenocereus_fricci 1067 bp 
-----------------------acgattgaatggtcc-ggtgaagtgttcggatcgcgg
cgacgtgggcggttcgccgccggcgacgtcgcgagaagtccactgaaccttatcatttag
aggaaggagaagtcgtaacaaggtttccgtaggtgaacctgcggaaggatcattgtcgaa
acctgcccagcagaaagaccc-gcgaacgtgttttgccccaacatgcggggaggggcgcc
tcg-gccccctccccgagccgggggcagcccccggcgcagcaacgaaaccccggcgcgaa
ccgcgccaaggaacacgaactcatggcgtgcccgcccgcgcccggtccgccggcgcgcgg
gggcggcacctgtccctacttaagaacgtaacgactctcggcaacggatatctcggctct
cg-catcgatgaagaacgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtga
accatcgagtctttgaacgcaagttgcgcccgaagccttccggccgagggcacgtctgcc
tgggcgtcacgcatcgcgcctccccccc---cccgccccccggggggggggaaggatgat
ggcctcccgcgccccggtcggggcgcggctggcctaaaacgggagcccgcggcgacgagc
tgcggcggcgactggtggtggacg-aggcctcgagcggccgccgtttgcatcgcgccgcg
cacgcacgccgccggggcgggctcgtcggaccctgacgtgtttgctgaaagcacagaacc
gttgcgaccccaggt---------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------
>Stenocereus_martinezii 1067 bp 
------------------------------------------------------------
------------------------------------------------------------
--gaaggagaagtcgtaacaaggtttccgtaggtgaacctgcggaaggatcattgtcgaa
acctgcccagcagaaagaccc-gcgaacatgttttgccccaacatgcggggaggggcgcc
tcg-gccccctccccgagccgggggcagcccccggcgcagcaacgaaaccccggcgcgaa
ccgcgccaaggaacacgaactcatggcgtgcccgcccgcgcccggtccgccggcgcgcgg
gggcggcacctgtccctacttaagaacgtaacgactctcggcaacggatatctcggctct
cg-catcgatgaagaacgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtga
accatcgagtctttgaacgcaagttgcgcccgaagccttccggccgagggcacgtctgcc
tgggcgtcacgcatcgcgcctccccccc---cgcccgcc---gggggggggaaggatgat
ggcctcccgcgccccggccggggcgcggctggcctaaaacgggagcccgcggcgacgagc
tgcggcggcgactggtggtggacg-aggcctcgagcggccgccgtttgcatcgcgccgcg
cacgcacgccgccggggcgggctcgtcggaccctgacgtgtttgctgaaagcacagaacc
gttgcgaccccaggtca-ggcggggctacccgctgagtttaagcatatcaataagcggag
gaaaagaaacttacaaggattcccctagtaacggcgagcgaaccgggaagagcccagctt
taaaatcgggcggcctcgccgtccgaattgtagtctggagaagcgtcctctgcggcggac
cgggcccaagtcccctggaaaggggcgccagagagggtgagagccccgtcgtgcccggac
cctgtcgcaccacgaggcg-------------------
>Stenocereus_stellatus 1067 bp 
------------------------------------------------------------
------------------------------------------------------------
-----------------acaaggtttccgtaggtgaacctgcggaaggatcattgtcgaa
acctgcccagcagaaagaccc-gcgaacgtgttttgccccaacatgcggggaggggcgcc
tcg-gccccctccccgagccgggggcagcccccggcgcagcaacgaaaccccggcgcgaa
ccgcgccaaggaacacgaactcatggcgtgcccgcccgcgcccggtccgccggcgcgcgg
gggcggcacctgtccctacttaagaacgtaacgactctcggcaacggatatctcggctct
cg-catcgatgaagaacgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtga
accatcgagtctttgaacgcaagttgcgcccgaagccttccggccgagggcacgtctgcc
tgggcgtcacgcatcgcgcctcccccccc--cgcccgcc---gggggggggaaggatgat
ggcctcccgcgccccggacggggcgcggctggcctaaaacgggagcccgcggcggcgagc
tgcggcggcgactggtggtggacg-aggcctcgagcggccgccgtttgcatcgcgccgcg
cacgcacgccgccggggcgggctcgtcggaccctgacgtgtttgctgaaagcacagaacc
gttgcgaccccaggtca-ggcggggctacccgctgagtttaagcatatcaataagcggag
gaaaagaaacttacaaggattcccctagtaacggcgagcgaaccgggaagagcccagctt
taaaatcgggcggcctcgccgtccgaattgtagtctggagaagcgtcctctgcggcggac
cgggcccaagtcccctggaaaggggcgccagagagggtgagagccccgtcgtgcccggac
cctgtcgcaccacgagg---------------------
