>Aspergillus_fumigatus_AY373851_1 Aspergillus_fumigatus_AY373851.1 803 bp 
---------------------------------------tccgtaggtg-aacctgc-gg
aaggatcattaccgagtga-gggccctc-------------------------tgggtcc
aa-----cctcccaccc---gtgtctatc----gtaccttgttgcttcggcgggcccgcc
gtttcgacggccgccggggaggccttgcgcccccgggcccgcgcccgccgaagaccccaa
catgaacgctgttc----tgaaagtatgcagtctgagttgatt-----------------
--------------------atcgtaatcagttaaaactttcaacaacggatctcttggt
tccggcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaattcagt
-gaatcatcgag--tctttgaac-gcacattgcgccccct-g-----gtattcc-ggggg
gcatgcctg-tccgagcgtca-ttgctgccctcaagcac------ggcttg---------
-----------------tgtgtt---gggcc-cccgtcccc-ctctcccgggggacgggc
ccg-aaaggcagcgg-c-------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------ggcaccgcgtccggtc
ctcgagcgtatggggctttgtcacctgctc-tgtaggcccggccggcgcc-agccgacac
-ccaactttatttttctaaggttgacctcggatca-ggtagggatacccgctgaa-ctt-
--aagcatatcaataagcggaggaaaagaaaccaacagggattgcctc------------
---------------------------------------------
>Aspergillus_sp__AM176671_1_deep_sea_sediment Aspergillus_sp._AM176671.1_deep_sea_sediment 803 bp 
------------------------------------------------------------
aaggatcattaccgagtga-gggccctc-------------------------tgggtcc
aa-----cctcccaccc---gtgtttatt----ttaccttgttgcttcggcgggcccgcc
--ttaactggccgccgggg-ggc-ttacgcccccgggcccgcgcccgccgaagacacc--
ctcgaactctgtct------gaagattgtagtctgag-tgaaa-----------------
--------------------atataaattatttaaaactttcaacaacggatctcttggt
tccggcatcgatgaagaacgcagcgaaatgcgatacgtaatgtgaattgca-aattcagt
-gaatcatcgag--tctttgaac-gcacattgcgccccct-g-----gtattcc-ggggg
gcatgcctg-tccgagcgtca-ttgctgccctcaagcac------ggcttg---------
-----------------tgtgtt---gggcc-ccgtcctcc-gatc-ccgggggacgggc
ccg-aaaggcagcgg-c-------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------ggcaccgcgtccggtc
ctcgagcgtatggggctttgtcacccgctc-tgtaggcccggccggcgct-tgccgatca
--acccgaatttttatccaggttgacctcggatca-ggtagggatacccgctgaa-ctt-
--aa--------------------------------------------------------
---------------------------------------------
>Aureobasidium_GI932_EU108769_3582m Aureobasidium_GI932_EU108769_3582m 803 bp 
---gaattcgcccttggaagtaaaagtcgtaacaaggtttccgtaggtg-aacctgc-gg
aaggatcattaaagagtaa-gggtgctc-------------------------agcgccc
ga-----cctccaaccc---tttgttgttaaaactaccttgttgctttggcgggaccgct
cggtctcgagccgctggggattc------gtcccaggcgagcgcccgccagagttaa---
accaaactcttgtt---a-tttaaccggtcgtctgagttaaaa-----------------
--------------------ttttgaataaatcaaaactttcaacaacggatctcttggt
tctcgcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaattcagt
-gaatcatcgaa--tctttgaac-gcacattgcgcccctt-g-----gtattcc-gaggg
gcatgcctg-ttcgagcgtca-ttacaccactcaagcta------tgcttg---------
------------------gtatt---gggcg-tcgtcctta--------gttgggcgcac
ctt-aaagacctcgg-c-------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------gaggcca--ctccggc
tttaggcgtagtagaatttattcgaacgtc-tgtcaaaggagaggaactc-tgccgactg
--aaacctttatttttctaggttgacctcggatca-ggtagggatacccgctgaa-ctt-
--aagcatatcaataagcggaggaaagggcgaattc------------------------
---------------------------------------------
>Aureobasidium_pullulans_AF455533_1 Aureobasidium_pullulans_AF455533.1 803 bp 
-------------ttggaagtaaaagtcgtaacaaggtttccgtaggtg-aacctgc-gg
aaggatcattaaagagtaa-gggtgctc-------------------------agcgccc
ga-----cctccaaccc---tttgttgttaaaactaccttgttgctttggcgggaccgct
cggtctcgagccgctggggattc------gtcccaggcgagcgcccgccagagttaa---
accaaactcttgtt---a-tttaaccggtcgtctgagttaaaa-----------------
--------------------ttttgaataaatcaaaactttcaacaacggatctcttggt
tctcgcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaattcagt
-gaatcatcgaa--tctttgaac-gcacattgcgcccctt-g-----gtattcc-gaggg
gcatgcctg-ttcgagcgtca-ttacaccactcaagcta------tgcttg---------
------------------gtatt---gggcg-tcgtcctta--------gttgggcgcgc
ctt-aaagacctcgg-c-------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------gaggcca--ctccggc
tttaggcgtagtagaatttattcgaacgtc-tgtcaaaggagaggaactc-tgccgactg
--aaacctttatttttctaggttgacctcggatca-ggtagggatacccgctgaa-ctt-
--aagcatatcaataagcggagg-------------------------------------
---------------------------------------------
>Candida_palmioleophila_AB016582_1 Candida_palmioleophila_AB016582.1 803 bp 
--------------------------------ctgtattctaattgccagcgcttaattg
cgcggcgatta-------------------------------------------------
-----aaccttacacacaatgtttttctttattagaaactattgctttggcttggctaag
aaattagtcgggccagaggtttacacaaacttc-------------------aattttta
attgaattgttatttaatactttgtcaatttgttgattaaat------------------
--------------------tcaaacaatcttcaaaactttcaacaacggatctcttggt
tctcgcatcgatgaagaacgcagcgaaatgcgataagtaatatgaattgcagattttcgt
-gaatcatcgaa--tctttgaac-gcacattgcgccctct-g-----gtattcc-agagg
gcatgcctg-tttgagcgtca-tttctctctcaaaccct---------------------
----------tgggtttggtattgagtgatactcttagtcgaact-----aggcgtttgc
ttg-aaatttattgg-catgagtgacgctgagaagtgcattca-----------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------------ggaaatatc
aatgtattaggtttatccaactcgttgacaattcttggttgtgaattttgtgttagcttg
cctaaaaaacacaaacaagt----------------------------------------
---------------------------------------------
>Cerebella_androprogonis_AJ306620_1 Cerebella_androprogonis_AJ306620.1 803 bp 
------------------------------------------------------------
----atcattacctagagtttgtagacttcggtctgcta---------------------
-------cctcttaccc----atgtcttttaagtaccttcgtttcctcggtgggtccgcc
cgccgactggacaaca--------------------------------------------
ttcaaaccctttgc---agttgcaatcagcgtctgaaaaaaca-----------------
-------------------------taatagttacaactttcaacaacggatctcttggt
tctggcatcgatgaagaacgcagcgaaatgcgataagtagtgtgaattgcagaattcagt
-gaatcatcgaa--tctttgaac-gcacattgcgcccctt-g-----gtattcc-atggg
gcatgcctg-ttcgagcgtca-tttgtaccttcaagctc------tgcttg---------
------------------gtgtt---gggtgttttgtctcgcctctgcgtgtagactcgc
ctt-aaaacaattgg-c-------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------agccggcgtattgatt
tcggagcgcagtacatctcgcgctttgcactcataac--------------gacgacgtc
caaaagtacaattttacactcttgacctcggatca-ggtagggatacccgctgaa-ctt-
--aagcatatcaataagcggagga------------------------------------
---------------------------------------------
>Cladosporium_GI900_EU108743_3613m Cladosporium_GI900_EU108743_3613m 803 bp 
---------------ggaagtaaaagtcgtaacaaggtctccgtaggtg-aacctgcggg
agggatcattacaagttga-ccccggtct------------------------aaccacc
gg-gatgttcataaccc---tttgttgtc----cgactctgttgcctc--cggggcgacc
ctgcct--------------------------tcgggcgggggctccgggtggacac---
ttcaaactcttgc------gtaactttgcagtctgagtaaact-----------------
--------------------taattaataaattaaaacttttaacaacggatctcttggt
tctggcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaattcagt
ggaatcatcgaa--tctttgaac-gcacattgcgcccccc-t-----gtattccgggggg
gcatgcctg-ttcaagcgtca-tttcaccactcaagcct------cgcttg---------
------------------gtatt---gggca-acgcggtcc--------gcc--gcgtgc
ctc-aaatggggggg-c-------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------tgggtct--tctgtcc
cctaagcgttgtggaaactattcg-----c-taaagggtgttcgggaggc-tacgccgta
-aaacaaccccatttctaaggttgacctcggatca-ggtagggatacccgctgaa-ctt-
--aagcatatcaataagcggagga------------------------------------
---------------------------------------------
>Cladosporium_GI901_EU108744_3610m Cladosporium_GI901_EU108744_3610m 803 bp 
---gaattcgcccttggaagtaaaagtcgtaacaaggtctccgtaggtg-aacctgc-gg
agggatcattacaag-aac-gcccgggc-------------------------tacggcc
tg-gttattcataaccc---tttgttgtc----cgactctgttgcctc--cggggcgacc
ctgcct--------------------------tcgggcgggggctccgggtggacac---
ttcaaactcttgc------gtaactttgcagtctgagtaaact-----------------
--------------------taattaataaattaaaacttttaacaacggatctcttggt
tctggcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaattcagt
-gaatcatcgaa--tctttgaac-gcacattgcgccccct-g-----gtattcc-ggggg
gcatgcctg-ttcgagcgtca-tttcaccactcaagcct------cgcttg---------
------------------gtatt---gggca-acgcggtcc--------gcc--gcgtgc
ctc-aaatcgtccgg-c-------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------tgggtct--tctgtcc
cctaagcgttgtggaaactattcg-----c-taaagggtgttcgggaggc-tacgccgta
-aaacaaccccatttctaaggttgacctcggatca-ggtagggatacccgctgaa-ctt-
--aagcatatcaataagcggaggaaagggcgaattc------------------------
---------------------------------------------
>Cladosporium_GI924_EU108761_3582m Cladosporium_GI924_EU108761_3582m 803 bp 
------------------------------------------------------------
---------tacaag-aac-gcccgggc-------------------------tacggcc
tgagttattcataaccc---tttgttgtc----cgactctgttgcctc--cggggcgacc
ctgcct--------------------------tcgggcgggggctccgggtggacac---
ttcaaactcttgc------gtaactttgcagtctgagtaaact-----------------
--------------------taattaataaattaaaacttttaacaacggatctcttggt
tctggcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaattcagt
-gaatcatcgaa--tctttgaac-gcacattgcgccccct-g-----gtattcc-ggggg
gcatgcctg-ttcgagcgtca-tttcaccactcaagcct------cgcttg---------
------------------gtatt---gggca-acgcggtcc--------gcc--gcgtgc
ctc-aaatcgtccgg-c-------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------tgggtct--tctgtcc
cctaagcgttgtggaaactattcg-----c-taaagggtgttcgggagg-----------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------
>Cladosporium_cladosporioides_AY345352_1_Antarctica Cladosporium_cladosporioides_AY345352.1_Antarctica 803 bp 
--------------------------------------tccgtaaggtg-aacctgc-gg
agggatcattacaag-tga-ccccggtt-------------------------taccacc
gg-gatgttcataaccc---tttgttgtc----cgactctgttgcctc--cggggcgacc
ctgcct--------------------------tcgggcgggggctccgggtggacac---
ttcaaactcttgc------gtaactttgcagtctgagtaaatt-----------------
--------------------taattaataaattaaaactttcaacaacggatctcttggt
tctggcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaattcagt
-gaatcatcgaa--tctttgaac-gcacattgcgccccct-g-----gtattcc-ggggg
gcatgcctg-ttcgagcgtca-tttcaccactcaagcct------cgcttg---------
------------------gtatt---gggca-acgcggtcc--------gcc--gcgtgc
ctc-aaatcgaccgg-c-------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------tgggtct--tctgtcc
cctaagcgttgtggaaactattcg-----c-taaaggtggttcgggaggc-tacgccgta
-aaacaaccccatttctaaggttgacctcggatca-ggtagga-----------------
------------------------------------------------------------
---------------------------------------------
>Cladosporium_herbarum_AF177734_1_Greenland_glacial_ice Cladosporium_herbarum_AF177734.1_Greenland_glacial_ice 803 bp 
--------------------------------------ctccgtaggtg-aactgc--gg
agggatcattacaag-aac-gcccgggc-------------------------ttcggcc
tg-gttattcataaccc---tttgttgtc----cgactctgttgcctc--cggggcgacc
ctgcct--------------------------tcgggcgggggctccgggtggacac---
ttcaaactcttgc------gtaactttgcagtctgagtaaact-----------------
--------------------taattaataaattaaaacttttaacaacggatctcttggt
tctggcatcgatgaaaaacgcagcgaaatgcgataagtaatgtgaattgcagaattcagt
-gaatcatccaaatctttgaaac-gcacattgcgccccct-g-----gtattcc-ggggg
gcatgcctgtttcgaacgtcattttcaccactcaagcct------cgcttt---------
------------------ggttttgggggca-acgcggtcc--------gcc--gcgtgc
ctc-aaatcgtccgg-c-------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------tgggtct--tctgtcc
cctaagcgttgtggaaactattcg-----c-taaagggtgttcgggaggc-tacgccgta
-aaacaaccccatttctaaggttga-ctcggatca-ggtagggatacccgctgaa-tt--
------------------------------------------------------------
---------------------------------------------
>Cladosporium_sp__DQ317332_1_Ross_Sea_Antarctica Cladosporium_sp._DQ317332.1_Ross_Sea_Antarctica 803 bp 
------------------------------------------------------------
--ggatcattacaag-tga-ccccggtct------------------------taccacc
gg-gatgttcataaccc---tttgttgtc----cgactctgttgcctc--cggggcgacc
ctgcct--------------------------tcgggcgggggctccgggtggacac---
ttcaaactcttgc------gtaactttgcagtctgagtaaact-----------------
--------------------taattaataaattaaaacttttaacaacggatctcttggt
tctggcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaattcagt
-gaatcatcgaa--tctttgaac-gcacattgcgccccct-g-----gtattcc-ggggg
gcatgcctg-ttcgagcgtca-tttcaccactcaagcct------cgcttg---------
------------------gtatt---gggca-acgcggtcc--------gcc--gcgtgc
ctc-aaatcgaccgg-c-------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------tgggtct--tctgtcc
cctaagcgttgtggaaactattcg-----c-taaagggtgttcgggaggc-tacgccgta
-aaacaaccccatttctaaggttgacctcggatca-ggtagggatacccgctgaa-ctt-
--aagcatatcaataagcggagga------------------------------------
---------------------------------------------
>Cladosporium_uncultured_soil_fungus_DQ421000_1 Cladosporium_uncultured_soil_fungus_DQ421000.1 803 bp 
-cttggtcatttagaggaagtaaaagtcgtaacaaggtctccgtaggtg-aacctgc-gg
agggatcattacaag-aac-gcccgggc-------------------------tacggcc
tg-gttattcataaccc---tttgttgtc----cgactctgttgcctc--cggggcgacc
ctgcct--------------------------tcgggcgggggctccgggtggacac---
ttcaaactcttgc------gtaactttgcagtctgagtaaact-----------------
--------------------taattaataaattaaaacttttaacaacggatctcttggt
tctggcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaattcagt
-gaatcatcgaa--tctttgaac-gcacattgcgccccct-g-----gtattcc-ggggg
gcatgcctg-ttcgagcgtca-tttcaccactcaagcct------cgcttg---------
------------------gtatt---gggca-acgcggtcc--------gcc--gcgtgc
ctc-aaatcgtccgg-c-------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------tgggtct--tctgtcc
cctaagcgttgtggaaactattcg-----c-taaagggtgttcgggaggc-tacgccgta
-aaacaaccccatttctaaggttgacctcggatca-ggtagggatacccgctgaa-ctt-
--aagcatatcaataagcggagga------------------------------------
---------------------------------------------
>Cryptococcs_GI817_DQ191309_3619m Cryptococcs_GI817_DQ191309_3619m 803 bp 
-cttggtcatttagaggaagtaaaagtcgtaacaaggtttccgtaggtgaacc-tgc-gg
aaggatcattaatgaatttaga------------ttgaa---------ccataggcgaaa
gccagtggttcttct-------ttcatatccataacacctgtgcactgtt----------
--------------------------------------ggatgcttgcatccacttttaa
actaaac------a-----ttattgtaacaaatgtag-tctta-----------------
--------------------ttat-aacataataaaactttcaacaacggatctcttggc
tctcgcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaattcagt
-gaatcatcgaa--tctttgaac-gcaccttgcgctcctt-g-----gtattcc-gagga
gcatgcctg-tttgagtgtca-tgaaaccctcaaaccca------agttttggatttcga
tccatgcttgag--tttggatttggatgttt-gc-cggt------gatgaaccgactcat
ctt-aaaagtattag-cttggatctgtctatatgactggtttga----------------
------------------------------------------------------------
------------------------cttggcataataagtattttgct-gaggacatcttc
--ggatgg--ccaggacctagactactgtctgctaactaaaccatcactttaagtgcatc
tttggatgttactcattgtgt--------a------------------------------
---------acttt--gacatctggcctcaaatca-agtaggactacccgctgaa-ctt-
--aagcatatcaataagcggagg-------------------------------------
---------------------------------------------
>Cryptococcs_GI944_EU18779_3582m Cryptococcs_GI944_EU18779_3582m 803 bp 
---------------ggaagtaaaagtcgtaacaaggtttccgtaggtgaacc-tgc-gg
aaggatcattaatgaatttaga------------ttgaa---------ccataggcgaaa
gccagtggttcttct-------ttcatatccataacacctgtgcactgtt----------
--------------------------------------ggatgcttgcatccacttttaa
actaaac------a-----ttattgtaacaaatgtag-tctta-----------------
--------------------ttat-aacataataaaactttcaacaacggatctcttggc
tctcgcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaattcagt
-gaatcatcgaa--tctttgaac-gcaccttgcgctcctt-g-----gtattcc-gagga
gcatgcctg-tttgagtgtca-tgaaaccctcaaaccca------agttttggatttcga
tccacgcttggagtttgggatttggatgttt-gc-cggt------gatgaaccgactcat
ctt-aaaagtattag-cttggacctgtctatatgactggtttga----------------
------------------------------------------------------------
------------------------cttggcataataagtattttgct-gaggacatcttc
--ggatgg--ccaggacctagactactgtctgctaactaaaccatcactttaagtgcatc
tttggatgttactcattgtgt--------a------------------------------
---------acttt--gacatctggcctcaaatca-agtaggactacccgctgaa-ctt-
--aagcatatcaataagcggaggaaagggcgaattc------------------------
---------------------------------------------
>Cryptococcs_magnus_AF190009_1 803 bp 
---------------------------------------tccgtaggtgaacc-tgc-gg
aaggatcattaatgaatttaga------------ttgaa---------ccataggcgaaa
gccagtggttcttct-------ttcatatccataacacctgtgcactgtt----------
--------------------------------------ggatgcttgcatccacttttaa
actaaac------a-----ttattgtaacaaatgtag-tctta-----------------
--------------------ttat-aacataataaaactttcaacaacggatctcttggc
tctcgcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaattcagt
-gaatcatcgaa--tctttgaac-gcaccttgcgctcctt-g-----gtattcc-gagga
gcatgcctg-tttgagtgtca-tgaaaccctcaaaccca------agttttggatttcga
tccatgcttgag--tttggatttggatgttt-gc-cggt------gatgaaccgactcat
ctt-aaaagtattag-cttggatctgtctatatgactggtttga----------------
------------------------------------------------------------
------------------------cttggcataataagtattttgct-gaggacatcttc
--ggatgg--ccaggacctagactactgtctgctaactaaaccatcactttaagtgcatc
tttggatgttactcattgtgt--------a------------------------------
---------acttt--gacatctggcctcaaatca-agtaggactacccgctgaa-ctt-
--aagcatatcaataagcggagga------------------------------------
---------------------------------------------
>Cryptococcus_niccombsii_AY029346_1_Antarctica Cryptococcus_niccombsii_AY029346.1_Antarctica 803 bp 
---------------------------------------tccgtaggtgaacc-tgc-gg
aaggatcactagtgattaaatcgagagcg-----tcttc---------att---------
-----gacctctcaccc---ttcacatccacatacaccctgtgaatcgtttggctttttc
attaat--------------agagcgcaagctcgacaagtgaaaaagtcatca---ttta
tacatac------c-----ccagtcttatgaatgtaacagttt-----------------
--------------------taataaacataataaaacttttaacaacggatctcttggt
tctcgcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaattcagt
-gaatcatcgaa--tctttgaac-gcaccttgcgctcctt-g-----gtattcc-gagga
gcatgcctg-tttgagtgtca-tgaaactctcacccttc------aacttt----cttaa
tagtggttgcaggcgtggact--tgagcgct-gc-tggt---tttaattaaccggctcgc
ttg-aaatgaattag-c--agatccttttt-gtaatcggttcca----------------
------------------------------------------------------------
------------------------ctcgacgtgataagtatttcgcc-gaggacatcttt
acggatgg--ccgagataaaga----------------------aagtcttagatccgct
tctaattcttag-----cctt--------a---------------------cgcaagtaa
gctaaacccatttt--atgatctggcctcaaatca-ggtaggactacccgctgaa-ctt-
--aagcatatcaataagcggagga------------------------------------
---------------------------------------------
>Cystofilobasidium_AF294943_1_psychrophile_from_glacier Cystofilobasidium_AF294943.1_psychrophile_from_glacier 803 bp 
------------------------------------------------------------
-----------gtgattaaatcgagagtg-----tcttc---------att---------
-----gacctctcaccc---ttcacatccacataca-cctgtgcaccgtttggctcttat
aaaaga--------------cgaaagtctgc--------aatgagagtcatcaat-ttta
tacatac------c-----ccagtcttatgaatgtaacagttt-----------------
--------------------taataaacataataaaacttttaacaacggatctcttggt
tctcgcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaattcagt
-gaatcatcgaa--tctttgaac-gcaccttgcgctcctt-g-----gtattcc-gagga
gcatgcctg-tttgagtgtca-tgaaactctcaaccttc------aacttt----tttat
taa-ggctgaaggcttggact--tgagcgct-gc-tggt---tctcacgaaccggctcgc
ttg-aaatgaattag-c--agatccttttt-gtaatcggttcca----------------
------------------------------------------------------------
------------------------ctcgacgtgataagtatttcgcc-gaggacatatga
aagtatgg--ccgagataaaga----------------------aagttctagatccgct
tctaattcttagataaagctt--------g---------------------ctttactaa
ac----cccatttt--atga----------------------------------------
------------------------------------------------------------
---------------------------------------------
>Cystofilobasidium_GI898_EU108742_3613m Cystofilobasidium_GI898_EU108742_3613m 803 bp 
gaattcgccccttggaagtaaaagtcgtaaccacggtttcccgtaggtgtaacctgcgga
aaggatcattaccgagtgaggggccctc-------------------------tgggttc
caacc--ttccccaccc---gtgtctatc----gtaccttgttgcttcggcgggcccgcc
gtttcgacggccgccggggaggccttgcgcccccgggcccccgcccgccgaagaccccaa
catgaacgctgttc----tgaaagtatgcagtctgagttgatt-----------------
--------------------atcgtaatcagttaaaactttcaacaacggatctcttggt
tccggcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaattcagt
-gaatcatcgag--tctttgaac-gcacattgcgccccct-g-----gtattcc-ggggg
gcatgcctg-tccgagcgtca-ttgctgccctcaagcac------ggcttg---------
-----------------tgtgtt---gggcc-cccgtcccc-ctctcccgggggacgggc
ccg-aaaggcagcgg-g-------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------ggcaccgcgtccggtc
ctcgagcgtatggggctttgtcacctgctc-tgtaggcccggccggcgcc-agccgacac
-ccaactttatttttctaaggttgacctcggatca-ggtagggatacccgctgaa-ctt-
--aagcatatcaataagcggaggaaagggcgaattc------------------------
---------------------------------------------
>Cystofilobasidium_GI913_EU108753_3606m Cystofilobasidium_GI913_EU108753_3606m 803 bp 
----------------------------------------------------cctgc-gg
aaggatcactagagatttcgccct------------------------------------
--ccggggctctctttt---tcttcacaca-----cccctgtgcactt------------
-----------------------tggctgccgcttcattgcggtggtcttttataattac
cataccc-atatac-----acaagtcattgaatgtaa-aatcg-----------------
--------------------ttat-aaactaatataactttcaacaacggatctcttggt
tctcgcatcgatgaagaacgcagcgaattgcgataagtaatgtgaattgcagaattcagt
-gaatcatcgaa--tctttgaac-gcatcttgcgctcttt-g-----gtattcc-gaaga
gcatgcctg-tttgagtgtca-tgaaactctcacctgca------gcactc----tttta
ttagagggctggagcgtggacg-tgagtgct-gc-tggtgccctcgctgcatcggctcac
ttg-aaatttattag-c--tgaatcctct--agtgttggttcta----------------
------------------------------------------------------------
------------------------ctcgacgtgataagatctccgtc-gaggacagtgct
ccttgtgggcgttggccaccgc----------------------tagctgttgatacgct
cctaattagcgcagacttcga--------g---------------------tgctggca-
---------acttt--gacaactggcctcaaattt-------------------------
---agagaatca------------------------------------------------
---------------------------------------------
>Cystofilobasidium_capitatum_AY052492_1_cold_adapted_yeast Cystofilobasidium_capitatum_AY052492.1_cold_adapted_yeast 803 bp 
-----------------------------------------------------ctgc-gg
aaggatcactaaagaattcgccct------------------------------------
--tcggggctctc--tt---tattcacaca-----cccctgtgcactt------------
-----------------------tggccacctctttgttgaggtgtgtctttttaattac
cataccctataaac-----acaagttattgaatgtaa-aatcg-----------------
--------------------ttat-aaactaatataactttcaacaacggatctcttggt
tctcgcatcgatgaagaacgcagcgaattgcgataagtaatgtgaattgcagaattcagt
-gaatcatcgaa--tctttgaac-gcatcttgcgctcttt-g-----gtattcc-gaaga
gcatgcctg-tttgagtgtca-tgaaactctcacctcca------atcttt----tttaa
ctagaaggttggggcgtggacg-tgagtgct-gc-tggtgccctggttgcatcggctcac
ttg-aaattcattag-c--tgaatccttt--aaagtaggttcta----------------
------------------------------------------------------------
------------------------ctcgacgtgataagatctccgtc-gaggacagtgct
tc-----ggcattggccaacga----------------------taa-agttgatacgct
tctaattagcgcagacttcga--------g---------------------tgctggca-
---------atttt-gacaacttggcctcaaatca-ggtaggactacccactgaa-ctt-
--aagcatatcaa-----------------------------------------------
---------------------------------------------
>Cystofilobasidium_infirmo_miniatum_AF444400_1 Cystofilobasidium_infirmo_miniatum_AF444400.1 803 bp 
----------------------------------------tccgtaggtgaacctgc-gg
aaggatcactagagatttcgccct------------------------------------
--ccggggctctctttt---tcttcacaca-----cccctgtgcactt------------
-----------------------tggctgccgcttcattgcggtggtcttttataattac
cataccc-atatac-----acaagtcattgaatgtaa-aatcg-----------------
--------------------ttat-aaactaatataactttcaacaacggatctcttggt
tctcgcatcgatgaagaacgcagcgaattgcgataagtaatgtgaattgcagaattcagt
-gaatcatcgaa--tctttgaac-gcatcttgcgctcttt-g-----gtattcc-gaaga
gcatgcctg-tttgagtgtca-tgaaactctcacctgca------gcactc----tttta
ttagagggctggagcgtggacg-tgagtgct-gc-tggtgccctcgctgcatcggctcac
ttg-aaatttattag-c--tgaatcctct--agtgttggttcta----------------
------------------------------------------------------------
------------------------ctcgacgtgataagatctccgtc-gaggacagtgct
ccttgtgggcgttggccaccgc----------------------tagctgttgatacgct
cctaattagcgcagacttcga--------g---------------------tgctggca-
---------acttttgacaacttggcctcaaatca-ggtaggactacccactgaa-ctt-
--aagcatatcaataagcggagga------------------------------------
---------------------------------------------
>Dothioraceae_sp__EF060638_1_marine Dothioraceae_sp._EF060638.1_marine 803 bp 
-ctccgtcatttagaggaagtaaaagtcgtaacaaggtttccgtaggtg-aacctgc-gg
aaggatcattaaagagtaa-gggtgctc-------------------------agcgccc
ga-----cctccaaccc---tttgttgttaaaactaccttgttgctttggcgggaccgct
cggtctcgagccgctggggattc------gtcccaggcgagcgcccgccagagttaa---
accaaactcttgtt---a-tttaaccggtcgtctgagttaaaa-----------------
--------------------ttttgaataaatcaaaactttcaacaacggatctcttggt
tctcgcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaattcagt
-gaatcatcgaa--tctttgaac-gcacattgcgcccctt-g-----gtattcc-gaggg
gcatgcctg-ttcgagcgtca-ttacaccactcaagcta------tgcttg---------
------------------gtatt---gggtg-ccgtcctta--------gttgggcgcgc
ctt-aaagacctcgg-c-------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------gaggcct--caccggc
tttaggcgtagtagaatttattcgaacgtc-tgtcaaaggagaggacttc-tgccgactg
-aaaccttttatttttctaggttgacctcggatca-ggtagggatacccgctgaa-ctt-
--aagcatatc-ataagcggaggaaaaaaaccaacagggattgccctattacggcgaatg
aaccgcacgctcaaattgaaactggcctcggtcccattgtaattg
>Filobasidium_globisporum_AF444336_1 Filobasidium_globisporum_AF444336.1 803 bp 
---------------------------------------tccgtaggtgaacc-tgc-gg
aaggatcattattgaattcaaatcatctgtggcttcggc---------ccggatgtgcca
acaggtaacactgttgg---taattctatccataacacctgtgaactgtt----------
--------------------------------------ggatgcttgcatccacttttaa
actaaac------a-----ttattgtaacaaatgtag-tctta-----------------
--------------------ttat-aacataataaaacttttaacaacggatctcttggc
tctcgcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaattcagt
-gaatcatcgaa--tctttgaac-gcaccttgcgctcctt-g-----gtattcc-gagga
gcatgcctg-tttgagtgtca-tgaaactctcaaaccca------agttttggatttcgg
tccatgcttgag--tttggatttggatgttt-gc-cggt------gatgaaccgactcat
ctt-aaaagtattag-c-tagatctgtctctatgactggtttga----------------
------------------------------------------------------------
------------------------cttggcataataagtattttgct-gaggacatcttt
cgggatgg--ccaggacctagactattgtctgctaactaaaccatcactttaagtgcatc
tttggatgttactcattgtgt--------a------------------------------
---------acttt--gacatctggcctcaaatca-ggtaggactacccgctgaa-ctt-
--aagcatatcaataagcggagga------------------------------------
---------------------------------------------
>Mycosphaerella_macrospora_AF362049_1 Mycosphaerella_macrospora_AF362049.1 803 bp 
---------------------------------------tccgtaggta-acctc----g
agggatcattacaag-aac-gcccgggc-------------------------ttcggcc
tg-gttattcataaccc---tttgttgtc----cgactctgttgcctc--cggggcgacc
ctgcct--------------------------tcgggcgggggctccgggtggacac---
ttcaaactcttgc------gtaactttgcagtctgagtaaact-----------------
--------------------taattaataaattaaaacttttaacaacggatctcttggt
tctggcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaattcagt
-gaatcatcgaa--tctttgaac-gcacattgcgccccct-g-----gtattcc-ggggg
gcatgcctg-ttcgagcgtca-tttcaccactcaagcct------cgcttg---------
------------------gtatt---gggca-acgcggtcc--------gcc--gcgtgc
ctc-aaatcgtccgg-c-------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------tgggtct--tctgtcc
cctaagcgttgtggaaactattcg-----c-taaagggtgttcgggaggc-tacgccgta
-aaacaaccccatttctaaggttgacctcggatca-ggtagggata--------------
------------------------------------------------------------
---------------------------------------------
>Penicillium_GI920_EU108757_3585m Penicillium_GI920_EU108757_3585m 803 bp 
------------------------------------------------------------
--------ttaccgagtga-gggccctc-------------------------tgggtcc
aa-----cctcccaccc---gtgtttatt----ttaccttgttgcttcggcgggcccgcc
--ttaactggccgccgggg-ggc-ttacgcccccgggcccgcgcccgccgaagacacc--
ctcgaactctgt-t------gaagattgtagtc-gag-tgaaa-----------------
--------------------atataaattatttaaaactttcaacaacggatctcttggt
tcc-gcatcgatgaagaacgcagcgaaatgcgatacgtaatgtgaattgca-aattcagt
-gaatcatcgag--tctttgaac-gcacattgcgccccct-g-----gtattcc-ggggg
gcatgcctg-tccgagcgtca-tttatgccctcaagcac------ggcttg---------
-----------------tgtgtt---gggcc-ccgtcctcc-gatc-ccgggggacgggc
ccg-aaaggcagcgg-c-------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------ggcaccgcgtccggtc
ctcgagcgtatggggctttgtcacccgctc-tgtaggcccggccggcgct-tgccgatca
--acccaaatttttat--------------------------------------------
------------------------------------------------------------
---------------------------------------------
>Penicillium_chrysogenum_AM158209_1_deep_sea_sediment Penicillium_chrysogenum_AM158209.1_deep_sea_sediment 803 bp 
------------------------------------------------------------
aaggatcattaccgagtga-gggccctc-------------------------tgggtcc
aa-----cctcccaccc---gtgtttatt----ttaccttgttgcttcggcgggcccgcc
--ttaactggccgccgggg-ggc-ttacgcccccgggcccgcgcccgccgaagacacc--
ctcgaactctgtct------gaagattgtagtctgag-tgaaa-----------------
--------------------atataaattatttaaaactttcaacaacggatctcttggt
tccggcatcgatgaagaacgcagcgaaatgcgatacgtaatgtgaattgca-aattcagt
-gaatcatcgag--tctttgaac-gcacattgcgccccct-g-----gtattcc-ggggg
gcatgcctg-tccgagcgtca-tttctgccctcaagcac------ggcttg---------
-----------------tgtgtt---gggcc-ccgtcctcc-gatc-ccgggggacgggc
ccg-aaaggcagcgg-c-------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------ggcaccgcgtccggtc
ctcgagcgtatggggctttgtcacccgctc-tgtaggcccggccggcgct-tgccgatca
--acccaaatttttatccaggttgacctcggatca-ggtagggatacccgctgaa-ctt-
--aa--------------------------------------------------------
---------------------------------------------
>Penicillium_chrysogenum_AY373903_1 Penicillium_chrysogenum_AY373903.1 803 bp 
---------------------------------------tccgtaggtg-aacctgc-gg
aaggatcattaccgagtga-gggccctc-------------------------tgggtcc
aa-----cctcccaccc---gtgtttatt----ttaccttgttgcttcggcgggcccgcc
--ttaactggccgccgggg-ggc-ttacgcccccgggcccgcgcccgccgaagacacc--
ctcgaactctgtct------gaagattgtagtctgag-tgaaa-----------------
--------------------atataaattatttaaaactttcaacaacggatctcttggt
tccggcatcgatgaagaacgcagcgaaatgcgatacgtaatgtgaattgca-aattcagt
-gaatcatcgag--tctttgaac-gcacattgcgccccct-g-----gtattcc-ggggg
gcatgcctg-tccgagcgtca-tttctgccctcaagcac------ggcttg---------
-----------------tgtgtt---gggcc-ccgtcctcc-gatc-ccgggggacgggc
ccg-aaaggcagcgg-c-------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------ggcaccgcgtccggtc
ctcgagcgtatggggctttgtcacccgctc-tgtaggcccggccggcgct-tgccgatca
--acccaaatttttatccaggttgacctcggatca-ggtagggatacccgctgaa-ctt-
--aagcatatcaataagcggaggaaaagaaaccaacagggattgcccc------------
---------------------------------------------
>Penicillium_commune_AF236103_1_Antarctica Penicillium_commune_AF236103.1_Antarctica 806 bp 
tctcggtcatttagaggaagtaaaagtcgtaacaaggtttccgtaggtg-aacctgc-rg
aaggatcattaccgagtga-gggccctc-------------------------tgggtcc
aa-----cctcccaccc---gtgtttatt----ttaccttgttgcttcggcgggcccgcc
--ttaactggccgccgggg-ggc-tcacgcccccgggcccgcgcccgccgaagacacc--
ctcgaactctgtct------gaagattgaagtctgag-tgaaa-----------------
--------------------atataaattatttaaaactttcaacaacggatctcttggt
tccggcatcgatgaagaacgcagcgaaatgcgatacgtaatgtgaattgca-aattcagt
-gaatcatcgag--tctttgaac-gcacattgcgccccct-g-----gtattcc-ggggg
gcatgcctg-tccgagcgtca-ttgctgccctcaagccc------ggcttg---------
-----------------tgtgtt---gggcc-ccgtcctcc-gatctccgggggacgggc
ccg-aaaggcagcgg-c-------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------ggcaccgcgtccggtc
ctcgagcgtatggggctttgtcacccgctc-tgtaggcccggccggcgct-tgccgatca
--acccaaatttttatccaggttgacctcggatca-ggtagggatacccgctgaa-ctt-
--aagcatatcaataagcggagga------------------------------------
---------------------------------------------
>Penicillium_corylophilum_AY345354_1_Antarctica Penicillium_corylophilum_AY345354.1_Antarctica 803 bp 
---------------------------------------tccgtaggtg-aacctgc-gg
aaggatcattaccgagtga-gggccctc-------------------------tgggtcc
aa-----cctcccaccc---atgtttatt----gtaccttgttgcttcggcgggcccgcc
--tca--cggccgccgggg-ggc-ttctgccctctggcccgcgcccgccgaagacacc--
attgaacactgtct------gaagattgcagtctgag-caatt-----------------
--------------------agctaaataagttaaaactttcaacaacggatctcttggt
tccggcatcgatgaagaacgcagcgaaatgcgatacgtaatgtgaattgcagaattcagt
-gaatcatcgag--tctttgaac-gcacattgcgcccctt-g-----gtattcc-ggggg
gcatgcctg-tccgagcgtca-ttgctgccctcaagcac------ggcttg---------
-----------------tgtgtt---gggcc-ccgtcctcc---ttcccgggggacgggc
ccg-aaaggcagcgg-c-------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------ggcaccgcgtccggtc
ctcgagcgtatggggctttgtcacccgctcttgtaggcccggccggcgct-tgccgacaa
--ccatcaatcttttttcaggttgacctcggatca-ggta--------------------
------------------------------------------------------------
---------------------------------------------
>Penicillium_expansum_AF218786_1_Antarctica Penicillium_expansum_AF218786.1_Antarctica 806 bp 
tctcggtcatttagaggaagtaaaagtcgtaacaaggtttccgtaggtg-aacctgc-rg
aaggatcattaccgagtga-gggccctt-------------------------tgggtcc
aa-----cctcccaccc---gtgttta-t----ttacctcgttgcttcggcgggcccgcc
--ttaactggccgccgggg-ggc-tcacgcccccgggcccgcgcccgccgaagacacc--
cccgaactctgcct------gaagattgtcgtctgag-tgaaa-----------------
--------------------atataaattatttaaaactttcaacaacggatctcttggt
tccggcatcgatgaagaacgcagcgaaatgcgatacgtaatgtgaattgca-aattcagt
-gaatcatcgag--tctttgaac-gcacattgcgccccct-g-----gtattcc-ggggg
gcatgcctg-tccgagcgtca-ttgctgccctcaagccc------ggcttg---------
-----------------tgtgtt---gggcc-ccgtcctcc-gatt-ccgggggacgggc
ccg-aaaggcagcgg-c-------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------ggcaccgcgtccggtc
ctcgagcgtatggggctttgtcacccgctc-tgtaggcccggccggcgct-tgccgatca
--acccaaatttttatccaggttgacctcggatca-ggtagggatacccgctgaa-ctt-
--aagcatatcaataagcggagga------------------------------------
---------------------------------------------
>Penicillium_griseoroseum_GI737_DQ191308_1_glacial_ice Penicillium_griseoroseum_GI737_DQ191308.1_glacial_ice 803 bp 
----------------------------------tccattgcggaggag---------ga
aagaactttcactcagtga-gggaaata-------------------------agggttt
t------cctcccaccc---gtgttaatt----ttaccttgttgcttcggcgggcccgcc
--ttacctggccgccgggg-ggc-ttacgcccccgggcccgcgcccgccgaagacacc--
ctcgaactctgtct------gaagattgaagtctgag-tgaaa-----------------
--------------------atataaattatttaaaactttcaacaacggatctcttggt
tccgg-atcgatgaagaacgcagcgaaatgcgatacgtaatgtgaattgca-aattcagt
-gaatcatcgag--tctttgaac-gcacattgcgccccctgg-----ggattcc-ggggg
gcatgcctg-tccgagcgtca-ttgctgccctcaagccc------ggcttg---------
-----------------tgtgtt---gggcc-ccgtccccc-aatctccgggggacgggc
ccacaaaggcagcggcc-------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------ggcaccgcgtccggtc
cttgagcgaatggggctttgtcacccgcttctgtaggcccggccggcgccttgcctatca
-actccaaatttttatccaggatgacctcggatca-ggaaggggataccgcagaacctt-
--aagcatatcaatagccggagtaaaatttttagagagcctaa-----------------
---------------------------------------------
>Penicillium_sp__AF177735_1_Greenland_glacial_ice Penicillium_sp._AF177735.1_Greenland_glacial_ice 803 bp 
--------------------------------------gttcgtaggtg--aactgc-gg
gaggatcattaccgagtga-gggccctc-------------------------tgggtcc
aa-----cctcccaccc---gtgtttatt----ttaccttgttgcttcggcgtgcctgcc
----ttttggctgccgggg-gtc-gtctgtccccgggtccgcgctcgccgaagacacc--
ttagaactctgtct------gaagattgtagtctgag-attaa-----------------
--------------------atataaattatttaaaactttcaacaacggatctcttggt
tccggcatcgatgaagaacgcagcgaaatgcgatacgtaatgtgaattgcagaattcagt
-gaatcatcgag--tctttgaac-gcacattgcgccctct-g-----gtattcc-ggagg
gcatgcctg-tccgagcgtca-ttgctgccctcaagcac------ggcttg---------
-----------------tgtgtt---gggct-ccgtcctcc----ttccgggggacgggc
ccg-aaaggcagcgg-c-------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------ggcaccgcgtccggtc
ctcaagcgtatggggctttgtcacccgctt-tgtaggactggccggcgcc-tgccgatca
---accaaacttttttccaggttgacctcggatca-ggtagggatacccgctgaa-ctt-
--aagcatatcaat----------------------------------------------
---------------------------------------------
>Penicillium_sp__AF177739_1_Greenland_glacial_ice Penicillium_sp._AF177739.1_Greenland_glacial_ice 803 bp 
------------------------------------------------------------
--------------------gggccctc-------------------------tgggtcc
aa-----cctcccaccc---gtgtttatt----ttaccttgttgcttcggcgggcccgcc
--ttaactggccgccgggg-ggc-tcacgcccccgggcccgcgcccgccgaaaacacc--
ctcgaactctgtct------gaagattgaagtctgag-tgaaa-----------------
--------------------atataaattatttaaaactttcaacaacggatctcttggt
tccggcatcgatgaagaacgcagcgaaatgcgatacgtaatgtgaattgca-aattcagt
-gaatcatcgag--tctttgaac-gcacattgcgccccct-g-----gtattcc-ggggg
gcatgcctg-tccgagcgtca-ttgctgccctcaagccc------ggcttg---------
-----------------tgtgtt---gggcc-ccgtcctcc-gatctccgggggacgggc
ccg-aaaggcagcgg-c-------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------ggcaccgcgtccggac
ctcgagcgtatggggctttgtcacccgc---tgtaggcccggccggcgct-tgccgaaca
--acccaaattttta-ccaggttgacctcggatca-ggtaggg-tacccgtgaat-taa-
------------------------------------------------------------
---------------------------------------------
>Penicillium_sp__AF261663_1_Greenland_glacial_ice Penicillium_sp._AF261663.1_Greenland_glacial_ice 803 bp 
--------------------------gcgtaacaaggtttc--gtagtg-aacctgc-gg
aaggatcattaccgagtga-gggccctc-------------------------tgggtcc
aa-----cctcccaccc---gtgtttatt----ttaccttgttgcttcggcgggcccg-c
--ttaactgg-cgccgggg-ggc-ttacg-ccccgggcccgcg-ccgccgaagacacc--
ctcgaactctgtct------gaagattgtagtctgag-tgaaa-----------------
--------------------atataaattatttaaaactttcaacaacggatctcttggt
tccggcatcgatgaagaacgcagcgaaatgcgatacgtaatgtgaattgca-aattcagt
-gaatcatcgag--tctttgaac-gcacattgcgccccct-g-----gtattcc-ggggg
gcatgcctg-tccgagcgtca-tttctgccctcaagcac------ggcttg---------
-----------------tgtgtt---gggcc-ccgtcctcc-gatc-ccgggggacgggc
ccg-aaaggcagcgg-c-------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------ggcaccgcgtccggtc
ctcgagcgtatggggctttgtcacccgctc-tgtaggcccggccggcgct-tgccgatca
--acccaaatttttatccaggttgacctcggatca-ggtagggatacccgctgaa-ctt-
--aagcatatcaataagcggaggacctgag------------------------------
---------------------------------------------
>Penicillium_sp__AY391833_1_glacier Penicillium_sp._AY391833.1_glacier 803 bp 
------------------------------------------------------------
aagtatcattaccgagtga-gggccctc-------------------------tgggtcc
aa-----cctcccaccc---gtgtttatt----atacctagttgcttcggcgggcccgcc
--gtca-tggccgccgggg-ggcaccctgcccccgggcccgcgcccgccgaagccccc--
cctgaacgctgtct------gaagattgcagtctgag-cgatt-----------------
--------------------agctaaatcagttaaaactttcaacaacggatctcttggt
tccggcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaattcagt
-gaatcatcgag--tctttgaac-gcacattgcgccccct-g-----gtattcc-ggggg
gcatgcctg-tccgagcgtca-ttgctgccctcaagcac------ggcttg---------
-----------------tgtgtt---gggcc-cccgccccccggctcccggggggcgggc
ccg-aaaggcagcgg-c-------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------ggcaccgcgtccggtc
ctcgagcgtatggggcttcgtcacccgctc-tgtaggcccggccggcgcc-cgccggcga
cccccctcaatctttctcaggttgacctcggatca-ggtagggatacccgctgaa-ctt-
--aa--------------------------------------------------------
---------------------------------------------
>Phoma_GI950_EU108785_3563m 803 bp 
-gcgaattcgcccttggaagtaaaagtcgtaacaaggtttccgtaggtg-aacctgc-gg
aaggatcattacctagagtttgtagacttcggtctgcta---------------------
-------cctcttaccc----atgtcttttgagtaccttcgtttcctcggcgggtccgcc
cgccgattggacaaca--------------------------------------------
ttcaaaccctttgc---agttgcaatcagcgtctgaaaaaaca-----------------
-------------------------taatagttacaactttcaacaacggatctcttggt
tctggcatcgatgaagaacgcagcgaaatgcgataagtagtgtgaattgcagaattcagt
-gaatcatcgaa--tctttgaac-gcacattgcgcccctt-g-----gtattcc-atggg
gcatgcctg-ttcgagcgtca-tttgtaccttcaagctc------tgcttg---------
------------------gtgtt---gggtg-tttgtctcgcctctgcgtgtagactcgc
ctt-aaaacaattgg-c-------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------agccggcgtattgatt
tcggagcgcagtacatctcgcgctttgcactcataac--------------gacgacgtc
caaaagtacatttttacactcttgacctcggatca-ggtagggatacccgctgaa-ctt-
--aagcatatcaataagcggaggaaagggcgaattcgtttaaacctgcaggactagtccg
ttagtgagggtaattctga--------------------------
>Phoma_glomerata_AY183371_1 803 bp 
-cttgggtcattagaggaagtaaaagtcgtaacaaggtttccgtaggtg-aacctgc-gg
aaggatcattacctagagttgtaggcttt--gcctgcta---------------------
-------tctcttaccc----atgtcttttgagtaccttcgtttcctcggcgggtccgcc
cgccgattggacaa----------------------------------------------
tttaaaccatttgc---agttgcaatcagcgtctgaaaaaact-----------------
-------------------------taatagttacaactttcaacaacggatctcttggt
tctggcatcgatgaagaacgcagcgaaatgcgataagtagtgtgaattgcagaattcagt
-gaatcatcgaa--tctttgaac-gcacattgcgcccctt-g-----gtattcc-atggg
gcatgcctg-ttcgagcgtca-tttgtaccttcaagctc------tgcttg---------
------------------gtgtt---gggtg-tttgtctcgcctctgcgcgtagactcgc
ctc-aaaacaattgg-c-------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------agccggcgtattgatt
tcggagcgcagtacatctcgcgctttgcactcataac--------------gacgacgtc
caaaagtacatttttacactcttgacctcggatca-ggtagggatacccgctgaa-ctt-
--aagcatatcaatagccgggag-------------------------------------
---------------------------------------------
>Phoma_uncultured_soil_fungus_DQ420965_1 Phoma_uncultured_soil_fungus_DQ420965.1 803 bp 
-cttggtcatttagaggaagtaaaagtcgtaacaaggtttccgtaggtg-aacctgc-gg
aaggatcattacctagagtttgtagacttcggtctgcta---------------------
-------cctcttaccc----atgtcttttgagtaccttcgtttcctcggcgggtccgcc
cgccgattggacaaca--------------------------------------------
ttcaaaccctttgc---agttgcaatcagcgtctgaaaaaaca-----------------
-------------------------taatagttacaactttcaacaacggatctcttggt
tctggcatcgatgaagaacgcagcgaaatgcgataagtagtgtgaattgcagaattcagt
-gaatcatcgaa--tctttgaac-gcacattgcgcccctt-g-----gtattcc-atggg
gcatgcctg-ttcgagcgtca-tttgtaccttcaagctc------tgcttg---------
------------------gtgtt---gggtg-tttgtctcgcctctgcgtgtagactcgc
ctt-aaaacaattgg-c-------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------agccggcgtattgatt
tcggagcgcagtacatctcgcgctttgcactcataac--------------gacgacgtc
caaaagtacatttttacactcttgacctcggatca-ggtagggatacccgctgaa-ctt-
--aagcatatcaataagcggagga------------------------------------
---------------------------------------------
>Pseudozyma_GI895_EU108740_3621m Pseudozyma_GI895_EU108740_3621m 803 bp 
------------------------------------------------------------
------------------------------------gtgggctcgcaccctgtccaacta
aacctgagctacctttt-----------ttatataacacggttgcatcggtccgtctgtc
gaaaccagtagcgctcat--agcgagcagcgtctggggaaagacgggtcggcgcttctta
ccaacacttttgaa---cactaggattggaaggacaaaaatcatttttttgatgatggaa
gcgactggtaatgcggtcgtctaaattgaaaaaacaacttttggcaacggatctcttggt
tctcccatcgatgaagaacgcagcgaattgcgataagtaatgtgaattgcaga----agt
-gaatcatcgaa--tctttgaacggcaccttgcgctcccg-gcagatttaatctggggga
gcatgcctg-tttgagggccg-cgaattgtttcgaacgaacagc----------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------
>Pseudozyma_antarctica_AY641557_1_Antarctica Pseudozyma_antarctica_AY641557.1_Antarctica 803 bp 
------------------------------------------------tgaacctgc-ag
atggatcatttcgatgaaaaccttttttcttgaggtgtg---gctcgcacctgtctaact
aaatcgagctaccacat--------------tttaacacggttgcatcggttggctgtca
aacagtgcgcgcggcgaattcattttcgcccgcgctctgcgagacggtcgacactttacc
aaaaacactgttgataccataggatttgaacgtagatgaaact-----------------
-cgactggtaatgcggtcgtctaaaatctaaaaacaacttttggcaacggatctcttggt
tctcccatcgatgaagaacgcagcgaattgcgataagtaatgtgaattgcaga----agt
-gaatcatcgaa--tctttgaac-gcaccttgcgctcccg-gcagatctaatct-gggga
gcatgcctg-tttgagggccg-cgaattgtttcgaacga-cagctttcttatttagttga
ga--gagctggcggatcggtattgagggtcttgc------cattttccacggtggctccc
tcg-aaatgcattag----------------cgcatccattcgataggcaagacggacga
aagctcgttatttcgcccacgtctttccctgccgggttttgataatatcaggacttcgga
gaggaaaggcgctgggtcgaggagctggacgcgacgttt---------------------
--------------------------------------------tgctggttggagtgct
tctgaaccccgcccatgcctccttctc------------------------cggaagagg
aagggatttaatttcaattcatcggcctcagat---ggtaggactacccgctgaa-cta-
------------------------------------------------------------
---------------------------------------------
>Pseudozyma_prolifica_AM160639_1 Pseudozyma_prolifica_AM160639.1 803 bp 
------------------------------------------------tgaacctgc-ag
atggatcattttgatgaaaaaccttttttttctgaggtgtggctcgcacctgtccaacta
aacctgagctacctttt-----------ttatataacacggttgcatcggtcggtctgtc
gaaaccagtagcgctcat--agcgagcagcgtctggggaaagacgggtcggcgcttctta
ccaacacttttgaa---cactaggattggaaggacaaaaatcatttttttgatgatggaa
gcgactggtaatgcggtcgtctaaattgaaaaaacaacttttggcaacggatctcttggt
tctcccatcgatgaagaacgcagcgaattgcgataagtaatgtgaattgcaga----agt
-gaatcatcgaa--tctttgaac-gcaccttgcgctcccg-gcagatttaatct-gggga
gcatgcctg-tttgagggccg-cgaattgtttcgaacga-cagcttttttttcttgttga
gaaagagctggcggatcggtagtgagggtct--------ctgccatttaccgtggctccc
tcg-aaatgcattag--------------cgcatccattggaaggcggaaagacggacga
aagctcgagtttttttgccctcgcttccctgccgggttttgataatgtcaggacttcgga
ggcgaagagagggcgggagctggacgcaacgacttttc----------------------
--------------------------------------------tgctgtttggcgtgct
tctgaaccccgcccatgcctctgctttaac---------------------cacagagga
agggatttatttttcaattcatcggcctcagatt--ggtaggactacccgctgaa-ctt-
--aagcatatc-------------------------------------------------
---------------------------------------------
>Rhodotorula_GI902_EU108745_3610m Rhodotorula_GI902_EU108745_3610m 803 bp 
--gaattcg-cccttggaagtaaaagtcgtaacaaggtttccgtaggtgaacc-tgc-gg
aaggatcattagtgaatataggacgtcca-----actta---------actt-ggag---
--tccgaactctcactt---tcta-----------accctgtgcatttgtttg-------
--------------------ggatagtaactctcgcaagagggcgaactcctatt-cact
tataaac------a-----caaagtctatgaatgtattaaatt-----------------
--------------------ttat-aacaaaataaaactttcaacaacggatctcttggc
tctcgcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaattcagt
-gaatcatcgaa--tctttgaac-gcaccttgcgctccat-g-----gtattcc-gtgga
gcatgcctg-tttgagtgtca-tgaatacttcaaccctc------ctcttt----cttaa
tgattgaagaggtgtttggtttctgagcgct-gc-tggc---ctttagggtctagctcgt
tcg-taatgcattag-c--atccgcaatcg-aacttcggattga----------------
------------------------------------------------------------
------------------------cttggcgtaatagactattcgct-gaggaattct-a
gtcttcgg-actagagccgggt----------------------tgggttaaaggaagct
tctaat-cagaa------------------------------------------------
-tgt-ctacatttt--aagattagatctcaaatca-ggtaggactacccgctgaa-ctt-
--aagcatatcaataagcggaggaaagggcgaattc------------------------
---------------------------------------------
>Rhodotorula_GI903_EU108746_3610m Rhodotorula_GI903_EU108746_3610m 803 bp 
--gaattcgccccttggaagtaaaagtcgtaacaaggtttccgtaggtgaacc-tgc-gg
aaggatcattagtgaatataggacgtcca-----actta---------actt-ggag---
--tccgaactctcactt---tcta-----------accctgtgcatttgtttg-------
--------------------ggatagtaactctcgcaagagggcgaactcctatt-cact
tataaac------a-----caaagtctatgaatgtattaaatt-----------------
--------------------ttat-aacaaaataaaactttcaacaacggatctcttggc
tctcgcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaattcagt
-gaatcatcgaa--tctttgaac-gcaccttgcgctccat-g-----gtattcc-gtgga
gcatgcctg-tttgagtgtca-tgaatacttcaaccctc------ctcttt----cttaa
tgattgaagaggtgtttggtttctgagcgct-gc-tggc---ctttagggtctagctcgt
tcg-taatgcattag-c--atccgcaatcg-aacttcggattga----------------
------------------------------------------------------------
------------------------cttggcgtaatagactattcgct-gaggaattct-a
gtcttcgg-actagagccgggt----------------------tgggttaaaggaagct
tctaat-cagaa------------------------------------------------
-tgt-ctacatttt--aagattagacctcaaatca-ggtaggactacccgctgaa-ctt-
--aagcatatcaataagcggaggaaagggcgaattc------------------------
---------------------------------------------
>Rhodotorula_GI904_EU108747_3610m Rhodotorula_GI904_EU108747_3610m 803 bp 
--gaattcg-cccttggaagtaaaagtcgtaacaaggtttccgtaggtgaacc-tgc-gg
aaggatcattagtgaatataggacgtcca-----actta---------actt-ggag---
--tccgaactctcactt---tcta-----------accctgtgcatttgtttg-------
--------------------ggatagtaactctcgcaagagggcgaactcctatt-cact
tataaac------a-----caaagtctatgaatgtattaaatt-----------------
--------------------ttat-aacaaaataaaactttcaacaacggatctcttggc
tctcgcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaattcagt
-gaatcatcgaa--tctttgaac-gcaccttgcgctccat-g-----gtattcc-gtgga
gcatgcctg-tttgagtgtca-tgaatacttcaaccctc------ctcttt----cttaa
tgattgaagaggtgtttggtttctgagcgct-gc-tggc---ctttagggtctagctcgt
tcg-taatgcattag-c--atccgcaatcg-aacttcggattga----------------
------------------------------------------------------------
------------------------cttggcgtaatagactattcgct-gaggaattct-a
gtcttcgg-actagagccgggt----------------------tgggttaaaggaagct
tctaat-cagaa------------------------------------------------
-tgt-ctacatttt--aagattagatctcaaatca-ggtaggactgcccgctgaa-ctt-
--aagcatatcaataagcggaggaaagggcgaattc------------------------
---------------------------------------------
>Rhodotorula_GI908_EU108748_3606m Rhodotorula_GI908_EU108748_3606m 803 bp 
------------------------------------------------------------
----atcattagtgaatataggacgtcca-----actta---------actt-ggag---
--tccgaactctcactt---tcta-----------accctgtgcatttgtttg-------
--------------------ggatagtaactctcgcaagagggcgaactcctatt-cact
tataaac------a-----caaagtctatgaatgtattaaatt-----------------
--------------------ttat-aacaaaataaaactttcaacaacggatctcttggc
tctcgcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaattcagt
-gaatcatcgaa--tctttgaac-gcaccttgcgctccat-g-----gtattcc-gtgga
gcatgcctg-tttgagtgtca-tgaatacttcaaccctc------ctcttt----cttaa
tgattgaagaggtgtttggtttctgagcgct-gc-tggc---ctttagggtctagctcgt
tcg-taatgcattag-c--atccgcaatcggaacttcggattga----------------
------------------------------------------------------------
------------------------cttggcgtaatagactattcgct-gaggaattct-a
gtcttcgg-actagagccgggt----------------------tgggtttaaaggg---
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------
>Rhodotorula_GI909_EU108749_3606m Rhodotorula_GI909_EU108749_3606m 803 bp 
------------------------------------------------------------
---------------------gacgtcca-----aactt---------cactgtgaggag
tcccggaactctcactt---tcta-----------accatgtgcatttgtttg-------
--------------------ggatagtaactctcgcaagagggcgaactcctatt-cact
tataaac------a-----caaagtctatgaatgtattaaatt-----------------
--------------------tt-t-aacaaactaaaactttcaacaacggatctcttggc
tct-gcatcgacgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaattcagt
-gaatcatcgaa--tctttgaac-gcaccttgcgctccat-g-----gtattcc-gtgga
gcatgcctg-tttgagtgtca-tgaatacttcaaccctc------ctcttt----cttaa
tgattgaagaggtgtttggtttctgagcgct-gc-tggc---ctttagggtctagctcgt
tcg-taatgcattag-c--atccgcaatcg-aacttcggattggac--------------
------------------------------------------------------------
------------------------ttgggcgtaatagactattcgcgtgaggaattctaa
gtcttcgg-actta----------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------
>Rhodotorula_GI910_EU108750_3606m Rhodotorula_GI910_EU108750_3606m 803 bp 
------------------------------------------------------------
------actcgaaatatataggacgtcca-----actta---------actt-ggag---
--tccgaactctcactt---tcta-----------accctgtgcatttgtttg-------
--------------------ggatagtaactctcgcaagagggcgaactcctatt-cact
tataaac------a-----caaagtctatgaatgtattaaatt-----------------
--------------------ttat-aacaaaataaaactttcaacaacggatctcttggc
tctcgcatcgatgaagaacgcagcgaaatgccataagtaatgtgaattgcagaattcagt
-gaatcatcgaa--tctttgaac-gcaccttgcgctccat-g-----gtattcc-gtgga
gcatgcctg-tttgagtgtca-tgaatacttcaaccctc------ctcttt----cttaa
tgattgaagaggtgtttggtttctgagcgct-gc-tggc---ctttagggtctagctcgt
tcg-taatgcattag-c--atccgcaatcg-aacttcggattga----------------
------------------------------------------------------------
------------------------cttggcgtaatagactattcgctggaggaattct-a
gtcttcgg-actagagccgggt----------------------tgggttaaaggaagct
tctaat-cagaa------------------------------------------------
-tgt-ctacatttt--aagattagatctcaaatca-ggtaggacta--------------
------------------------------------------------------------
---------------------------------------------
>Rhodotorula_GI911_EU108751_3606m Rhodotorula_GI911_EU108751_3606m 803 bp 
------------------------------------------------------------
----atcattagtgaatataggacgtcca-----actta---------actt-ggag---
--tccgaactctcactt---tcta-----------accctgtgcacttgtttg-------
--------------------ggatagtaactctcgcaagagagcgaactcctatt-cact
tataaac------a-----caaagtctatgaatgtattaaatt-----------------
--------------------ttat-aacaaaataaaactttcaacaacggatctcttggc
tctcgcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaattcagt
-gaatcatcgaa--tctttgaac-gcaccttgcgctccat-g-----gtattcc-gtgga
gcatgcctg-tttgagtgtca-tgaatacttcaaccctc------ctcttt----cttaa
tgattgaagaggtgtttggtttctgagcgct-gc-tggc---ctttacggtctagctcgt
tcg-taatgcattag-c--atccgcaatcg-aacttcggattga----------------
------------------------------------------------------------
------------------------cttggcgtaatagactattcgct-gaggaattct-a
gtcttcgg-actagagccgggt----------------------tgggttaaaggaagct
tc----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------
>Rhodotorula_GI914_EU108754_3591m Rhodotorula_GI914_EU108754_3591m 803 bp 
------------------------------------------------------------
------------tgaatataggacgtcca-----actta---------actt-ggag---
--tccgaactctcactt---tcta-----------accctgtgcatttgtttg-------
--------------------ggatagtaactctcgcaagagggcgaactcctatt-cact
tataaac------a-----caaagtctatgaatgtattaaatt-----------------
--------------------ttat-aacaaaataaaactttcaacaacggatctcttggc
tctcgcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaattcagt
-gaatcatcgaa--tctttgaac-gcaccttgcgctccat-g-----gtattcc-gtgga
gcatgcctg-tttgagtgtca-tgaatacttcaaccctc------ctcttt----cttaa
tgattgaagaggtgtttggtttctgagcgct-gc-tggc---ctttagggtctagctcgt
tcg-taatgcattag-c--atccgcaatcg-aacttcggattga----------------
------------------------------------------------------------
------------------------cttggcgtaatagactattcgct-gaggaattct-a
gtcttcgg-actagagccgggt----------------------tgggttaaaggaagct
tctaat-cagaa------------------------------------------------
-tgt-ctacatttt--aaga----------------------------------------
------------------------------------------------------------
---------------------------------------------
>Rhodotorula_GI926_EU108763_3582m Rhodotorula_GI926_EU108763_3582m 803 bp 
--gaattcg-cccttggaagtaaaagtcgtaacaaggtttccgtaggtgaacc-tgc-gg
aaggatcattagtgaatataggacgtcca-----actta---------actt-ggag---
--tccgaactctcactt---tcta-----------accctgtgcatttgtttg-------
--------------------ggatagtaactctcgcaagagggcgaactcctatt-cact
tataaac------a-----caaagtctatgaatgtattaaatt-----------------
--------------------ttat-aacaaaataaaactttcaacaacggatctcttggc
tctcgcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaattcagt
-gaatcatcgaa--tctttgaac-gcaccttgcgctccat-g-----gtattcc-gtgga
gcatgcctg-tttgagtgtca-tgaatacttcaaccctc------ctcttt----cttaa
tgattgaagaggtgtttggtttctgagcgct-gc-tggc---ctttagggtctagctcgt
tcg-taatgcattag-c--atccgcaatcg-aacttcggattga----------------
------------------------------------------------------------
------------------------cttggcgtaatagactattcgct-gaggaattct-a
gtcttcgg-actagagccgggt----------------------tgggttaaaggaagct
tctaat-cagaa------------------------------------------------
-tgt-ctacatttt--aagattagatctcaaatca-ggtaggactacccgctgaa-ctt-
--aagcatatcaataagcggaggaaagggcgaattc------------------------
---------------------------------------------
>Rhodotorula_GI927_EU108764_3582m Rhodotorula_GI927_EU108764_3582m 803 bp 
--gaattcg-cccttggaagtaaaagtcgtaacaaggtttccgtaggtgaacc-tgc-gg
aaggatcattagtgaatataggacgtcca-----actta---------actt-ggag---
--tccgaactctcactt---tcta-----------accctgtgcatttgtttg-------
--------------------ggatagtaactctcgcaagagggcgaactcctatt-cact
tataaac------a-----caaagtctatgaatgtattaaatt-----------------
--------------------ttat-aacaaaataaaactttcaacaacggatctcttggc
tctcgcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaattcagt
-gaatcatcgaa--tctttgaac-gcaccttgcgctccat-g-----gtattcc-gtgga
gcatgcctg-tttgagtgtca-tgaatacttcaaccctc------ctcttt----cttaa
tgattgaagaggtgtttggtttctgagcgct-gc-tggc---ctttagggtctagctcgt
tcg-taatgcattag-c--atccgcaatcg-aacttcggattga----------------
------------------------------------------------------------
------------------------cttggcgtaatagactattcgct-gaggaattct-a
gtcttcgg-actagagccgggt----------------------tgggttaaaggaagct
tctaat-cagaa------------------------------------------------
-tgt-ctacatttt--aagattagatctcaaatca-ggtaggactacccgctgaa-ctt-
--aagcatatcaataagcggaggaaagggcgaattc------------------------
---------------------------------------------
>Rhodotorula_GI928_EU108765_3582m Rhodotorula_GI928_EU108765_3582m 803 bp 
--gaattcg-cccttggaagtaaaagtcgtaacaaggtttccgtaggtgaacc-tgc-gg
aaggatcattagtgaatataggacgtcca-----actta---------actt-ggag---
--tccgaactctcactt---tcta-----------accctgtgcatttgtttg-------
--------------------ggatagtaactctcgcaagagggcgaactcctatt-cact
tataaac------a-----caaagtctatgaatgtattaaatt-----------------
--------------------ttat-aacaaaataaaactttcaacaacggatctcttggc
tctcgcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaattcagt
-gaatcatcgaa--tctttgaac-gcaccttgcgctccat-g-----gtattcc-gtgga
gcatgcctg-tttgagtgtca-tgaatacttcaaccctc------ctcttt----cttaa
tgattgaagaggtgtttggtttctgagcgct-gc-tggc---ctttagggtctagctcgt
tcg-taatgcattag-c--atccgcaatcg-aacttcggattga----------------
------------------------------------------------------------
------------------------cttggcgtaatagactattcgct-gaggaattct-a
gtcttcgg-actagagccgggt----------------------tgggttaaaggaagct
tctaat-cagaa------------------------------------------------
-tgt-ctacatttt--aagattagatctcaaatca-ggtaggactacccgctgaa-ctt-
--aagcatatcaataagcggaggaaagggcgaattc------------------------
---------------------------------------------
>Rhodotorula_GI929_EU108766_3582m Rhodotorula_GI929_EU108766_3582m 803 bp 
--gaattcg-cccttggaagtaaaagtcgtaacaaggtttccgtaggtgaaccttgc-gg
aaggatcattagtgaatataggacgtcca-----actta---------actt-ggag---
--tccgaactctcactt---tcta-----------accctgtgcatttgtttg-------
--------------------ggatagtaactctcgcaagagggcgaactcctatt-cact
tataaac------a-----caaagtctatgaatgtattaaatt-----------------
--------------------ttat-aacaaaataaaactttcaacaacggatctcttggc
tctcgcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaattcagt
-gaatcatcgaa--tctttgaac-gcaccttgcgctccat-g-----gtattcc-gtgga
gcatgcctg-tttgagtgtca-tgaatacttcaaccctc------ctcttt----cttaa
tgattgaagaggtgtttggtttctgagcgct-gc-tggc---ctttagggtctagctcgt
tcg-taatgcattag-c--atccgcaatcg-aacttcggattga----------------
------------------------------------------------------------
------------------------cttggcgtaatagactattcgct-gaggaattct-a
gtcttcgg-actagagccgggt----------------------tgggttaaaggaagct
tctaat-cagaa------------------------------------------------
-tgt-ctacatttt--aagattagatctcaaatca-ggtaggactacccgctgaa-ctt-
--aagcatatcaataagcggaggaaagggcgaattc------------------------
---------------------------------------------
>Rhodotorula_GI931_EU108768_3582m Rhodotorula_GI931_EU108768_3582m 803 bp 
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------aaccctc------ctcttt----cttaa
tgattgaagaggtgtttggtttctgagcgct-gc-tggc---ctttagggtctagctcgt
tcg-taatgcattag-c--atccgcaatcg-aacttcggattga----------------
------------------------------------------------------------
------------------------cttggcgtaatagactattcgct-gaggaattct-a
gtcttcgg-actagagccgggt----------------------tgggttaaaggaagct
tctaat-cagaa------------------------------------------------
-tgt-ctacatttt--aagattagatctcaaatca-ggtaggactacccgctgaa-ctt-
--aagcatatcaataagcggaggaaagggcgaattcgttt--------------------
---------------------------------------------
>Rhodotorula_GI933_EU108770_3582m Rhodotorula_GI933_EU108770_3582m 803 bp 
--gaattcg-cccttggaagtaaaagtcgtaacaaggtttccgtaggtgaacc-tgc-gg
aaggatcattagtgaatataggacgtcca-----actta---------actt-ggag---
--tccgaactctcactt---tcta-----------accctgtgcatttgtttg-------
--------------------ggatagtaactctcgcaagagggcgaactcctatt-cact
tataaac------a-----caaagtctatgaatgtattaaatt-----------------
--------------------ttat-aacaaaataaaactttcaacaacggatctcttggc
tctcgcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaattcagt
-gaatcatcgaa--tctttgaac-gcaccttgcgctccat-g-----gtattcc-gtgga
gcatgcctg-tttgagtgtca-tgaatacttcaaccctc------ctcttt----cttaa
tgattgaagaggtgtttggtttctgagcgct-gc-tggc---ctttagggtctagctcgt
tcg-taatgcattag-c--atccgcaatcg-aacttcggattga----------------
------------------------------------------------------------
------------------------cttggcgtaatagactattcgct-gaggaattct-a
gtcttcgg-actagagccgggt----------------------tgggttaaaggaagct
tctaat-cagaa------------------------------------------------
-tgt-ctacatttt--aagattagatctcaaatca-ggtaggactacccgctgaa-ctt-
--aagcatatcaataagcggaggaaagggcgaattc------------------------
---------------------------------------------
>Rhodotorula_GI939_EU108775_3582m Rhodotorula_GI939_EU108775_3582m 803 bp 
------------------------------------------------------------
-------------------------tcca-----actta---------actt-ggag---
--tccgaactctcactt---tcta-----------accctgtgcatttgtttg-------
--------------------ggatagtaactctcgcaagagggcgaactcctatt-cact
tataaac------a-----caaagtctatgaatgtattaaatt-----------------
--------------------ttat-aacaaaataaaactttcaacaacggatctcttggc
tctcgcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaattc-gt
-gaatcatcgaa--tctttgaac-gcaccttgcgctccat-g-----gtattcc-gtgga
gcatgcctg-tttgagtgtca-tgaatacttcaaccctc------ctcttt----cttaa
tgattgaagaggtgtttggtttctgagcgct-gc-tggc---ctttagggtctagctcgt
tcg-taatgcattcg-c--atccgcaatcg-aacttcggattga----------------
------------------------------------------------------------
------------------------cttggcgtaatagactattcgct-gaggaattct-a
gtcttcggaactagagccgggt----------------------tgggttaaaggaagct
tctaat-cagaa------------------------------------------------
-tgt-ctacatttt--aagattagatctcaattta-------------------------
------------------------------------------------------------
---------------------------------------------
>Rhodotorula_GI945_EU108780_3582m Rhodotorula_GI945_EU108780_3582m 803 bp 
-ggaattcg-cccttggaagtaaaagtcgtaacaaggtttccgtaggtgaacc-tgc-gg
aaggatcattagtgaatataggacgtcca-----actta---------actt-ggag---
--tccgaactctcactt---tcta-----------accctgtgcatttgtttg-------
--------------------ggatagtaactctcgcaagagggcgaactcctatt-cact
tataaac------a-----caaagtctatgaatgtattaaatt-----------------
--------------------ttat-aacaaaataaaactttcaacaacggatctcttggc
tctcgcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaattcagt
-gaatcatcgaa--tctttgaac-gcaccttgcgctccat-g-----gtattcc-gtgga
gcatgcctg-tttgagtgtca-tgaatacttcaaccctc------ctcttt----cttaa
tgattgaagaggtgtttggtttctgagcgct-gc-tggc---ctttagggtctagctcgt
tcg-taatgcattag-c--atccgcaatcg-aacttcggattga----------------
------------------------------------------------------------
------------------------cttggcgtaatagactattcgct-gaggaattct-a
gtcttcgg-actagagccgggt----------------------tgggttaaaggaagct
tctaat-cagaa------------------------------------------------
-tgt-ctacatttt--aagattagatctcaaatcacggtaggactacccgctgca-actt
acacgcatatcaataagcggaggaagggcgaattc-------------------------
---------------------------------------------
>Rhodotorula_GI946_EU108781_3582m Rhodotorula_GI946_EU108781_3582m 803 bp 
--gaattcg-cccttggaagtaaaagtcgtaacaaggtttccgtaggtgaacc-tgc-gg
aaggatcattagtgaatataggacgtcca-----actta---------actt-ggag---
--tccgaactctcactt---tcta-----------accctgtgcatttgtttg-------
--------------------ggatagtaactctcgcaagagggcgaactcctatt-cact
tataaac------a-----caaagtctatgaatgtattaaatt-----------------
--------------------ttat-aacaaaataaaactttcaacaacggatctcttggc
tctcgcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaattcagt
-gaatcatcgaa--tctttgaac-gcaccttgcgctccat-g-----gtattcc-gtgga
gcatgcctg-tttgagtgtca-tgaatacttcaaccctc------ctcttt----cttaa
tgattgaagaggtgtttggtttctgagcgct-gc-tggc---ctttagggtctagctcgt
tcg-taatgcattag-c--atccgcaatcg-aacttcggattga----------------
------------------------------------------------------------
------------------------cttggcgtaatagactattcgct-gaggaattct-a
gtcttcgg-actagagccgggt----------------------tgggttaaaggaagct
tctaat-cagaa------------------------------------------------
-tgt-ctacatttt--aagattagatctcaaatca-ggtaggactacccgctgaa-ctt-
--aagcatatcaataagcggaggaaagggcgaattc------------------------
---------------------------------------------
>Rhodotorula_GI947_EU108782_3582m Rhodotorula_GI947_EU108782_3582m 803 bp 
--gaattcg-cccttggaagtaaaagtcgtaacaaggtttccgtaggtgaacc-tgc-gg
aaggatcattagtgaatataggacgtcca-----actta---------actt-ggag---
--tccgaactctcactt---tcta-----------accctgtgcatttgtttg-------
--------------------ggatagtaactctcgcaagagggcgaactcctatt-cact
tataaac------a-----caaagtctatgaatgtattaaatt-----------------
--------------------ttat-aacaaaataaaactttcaacaacggatctcttggc
tctcgcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaattcagt
-gaatcatcgaa--tctttgaac-gcaccttgcgctccat-g-----gtattcc-gtgga
gcatgcctg-tttgagtgtca-tgaatacttcaaccctc------ctcttt----cttaa
tgattgaagaggtgtttggtttctgagcgct-gc-tggc---ctttagggtctagctcgt
tcg-taatgcattag-c--atccgcaatcg-aacttcggattga----------------
------------------------------------------------------------
------------------------cttggcgtaatagactattcgct-gaggaattct-a
gtcttcgg-actagagccgggt----------------------tgggttaaaggaagct
tctaat-cagaa------------------------------------------------
-tgt-ctacatttt--aagattagatctcaaatca-ggtaggactacccgctgaa-ctt-
--aagcatatcaataagcggaggaaagggcgaattc------------------------
---------------------------------------------
>Rhodotorula_GI948_EU108783_3582m Rhodotorula_GI948_EU108783_3582m 803 bp 
--gaattcg-cccttggaagtaaaagtcgtaacaaggtttccgtaggtgaacc-tgc-gg
aaggatcattagtgaatataggacgtcca-----actta---------actt-ggag---
--tccgaactctcactt---tcta-----------accctgtgcatttgtttg-------
--------------------ggatagtaactctcgcaagagggcgaactcctatt-cact
tataaac------a-----caaagtctatgaatgtattaaatt-----------------
--------------------ttat-aacaaaataaaactttcaacaacggatctcttggc
tctcgcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaattcagt
-gaatcatcgaa--tctttgaac-gcaccttgcgctccat-g-----gtattcc-gtgga
gcatgcctg-tttgagtgtca-tgaatacttcaaccctc------ctcttt----cttaa
tgattgaagaggtgtttggtttctgagcgct-gc-tggc---ctttagggtctagctcgt
tcg-taatgcattag-c--atccgcaatcg-aacttcggattga----------------
------------------------------------------------------------
------------------------cttggcgtaatagactattcgct-gaggaattct-a
gtcttcgg-actagagccgggt----------------------tgggttaaaggaagct
tctaat-cagaa------------------------------------------------
-tgt-ctacatttt--aagattagatctcaaatca-ggtaggactacccgctgaa-ctt-
--aagcatatcaataagcggaggaaagggcgaattc------------------------
---------------------------------------------
>Rhodotorula_GI949_EU108784_3582m Rhodotorula_GI949_EU108784_3582m 803 bp 
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------aatt-----------------
--------------------ttat-aacaaaataaaactttcaacaacggatctcttggc
tctcgcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaattcagt
-gaatcatcgaa--tctttgaac-gcaccttgcgctccat-g-----gtattcc-gtgga
gcatgcctg-tttgagtgtca-tgaatacttcaaccctc------ctcttt----cttaa
tgattgaagaggtgtttggtttctgagcgct-gc-tggc---ctttagggtctagctcgt
tcg-taatgcattag-c--atccgcaatcg----ctcggattga----------------
------------------------------------------------------------
------------------------cttggcgtaatagactattcgct-gaggaattct-a
gtcttcgg-actagagccgggt----------------------tgggttaaaggaagct
tctaat-cagaa------------------------------------------------
-tgt-ctacatttt--aagattagatctcaaatca-ggtaggactacccgctgaa-ctt-
--aagcatatcaat----------------------------------------------
---------------------------------------------
>Rhodotorula_GI951_EU108786_3563m Rhodotorula_GI951_EU108786_3563m 803 bp 
-------------------------------------------taggtgaacc-tgc-gg
aagga-cattagtgaatataggacgtcca-----actta---------actt-ggag---
--tccgaactctcactt---tcta-----------accctgtgcatttgtttg-------
--------------------ggatagtaactctcgcaagagggcgaactcctatt-cact
tataaac------a-----caaagtctatgaatgtattaaatt-----------------
--------------------ttat-aacaaaataaaactttcaacaacggatctcttggc
tctcgcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaattcagt
-gaatcatcgaa--tctttgaac-gcaccttgcgctccat-g-----gtattcc-gtgga
gcatgcctg-tttgagtgtca-tgaatacttcaaccctc------ctcttt----cttaa
tgattgaagaggtgtttggtttctgagcgct-gc-tggc---ctttagggtctagctcgt
tcg-taatgcattag-c--atccgcaatcg-aacttcggattga----------------
------------------------------------------------------------
------------------------cttggcgtaatagactattcgct-gaggaattct-a
gtcttcgg-actagagccgggt----------------------tgggttaaaggaagct
tctaat-cagaa------------------------------------------------
-tgt-ctacatttt--aagattagatctcaaatca-ggtaggac----------------
------------------------------------------------------------
---------------------------------------------
>Rhodotorula_GI952_EU108787_3563m Rhodotorula_GI952_EU108787_3563m 803 bp 
---------------------------------------------ggtgaacc-tgc-gg
aaggatcattagtgaatataggacgtcca-----actta---------actt-ggag---
--tccgaactctcactt---tcta-----------accctgtgcatttgtttg-------
--------------------ggatagtaactctcgcaagagggcgaactcctatt-cact
tataaac------a-----caaagtctatgaatgtattaaatt-----------------
--------------------ttat-aacaaaataaaactttcaacaacggatctcttggc
tctcgcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaattcagt
-gaatcatcgaa--tctttgaac-gcaccttgcgctccat-g-----gtattcc-gtgga
gcatgcctg-tttgagtgtca-tgaatacttcaaccctc------ctcttt----cttaa
tgattgaagaggtgtttggtttctgagcgct-gc-tggc---ctttagggtctagctcgt
tcg-taatgcattag-c--atccgcaatcg-aacttcggattga----------------
------------------------------------------------------------
------------------------cttggcgtaatagactattcgct-gaggaattct-a
gtcttcgg-actagagccgggt----------------------tgggttaaaggaagct
tctaat-cagaa------------------------------------------------
-tgt-ctacatttt--aagattagatctcaaatca-ggtaggactaccc-----------
------------------------------------------------------------
---------------------------------------------
>Rhodotorula_GI959_EU108793_3501m Rhodotorula_GI959_EU108793_3501m 803 bp 
------------------------------------------------------------
-------actctaagatataggacgtcca------ctta---------acttggcag---
--tccgaactctcactt---tcta-----------accctgtgcacttgtttg-------
--------------------ggatagtaactctcgcaagagagcgaactcctatt-cact
tataaac------a-----caaagtctatgaatgtattaaatt-----------------
--------------------ttat-aacaaaataaaactttcaacaacggatctcttggc
tctcgcatcgatgaagaacgcagcgaaatgccataagtaatgtgaattgcagaattcagt
-gaatcatcgaa--tctttgaac-gcaccttgcgctccat-g-----gtattcc-gtgga
gcatgcctg-tttgagtgtca-tgaatacttcaaccctc------ctcttt----cttaa
tgattgaagaggtgtttggtttctgagcgct-gc-tggc---ctttacggtctagctcgt
tcg-taatgcattag-c--atccgcaatcg-aacttcggattga----------------
------------------------------------------------------------
------------------------cttggcgtaatagactattcgct-gaagaattct-a
gtcttcgg-actagagccgggt----------------------tgggttaaaggaagct
tctaat-cagaa------------------------------------------------
-tgt-ctacatttt--aagattagatctc-aatca-ggtaggactacccgctgaa-ctt-
--aagc------------------------------------------------------
---------------------------------------------
>Rhodotorula_GI962_EU108795_3501m Rhodotorula_GI962_EU108795_3501m 803 bp 
-----------------------------------ggtttccgtaggtgaacc-tgc-gg
aaggatcattagtgaatataggacgtcca-----actta---------actt-ggag---
--tccgaactctcactt---tcta-----------accctgtgcatttgtttg-------
--------------------ggatagtaactctcgcaagagggcgaactcctatt-cact
tataaac------a-----caaagtctatgaatgtattaaatt-----------------
--------------------ttat-aacaaaataaaactttcaacaacggatctcttggc
tctcgcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaattcagt
-gaatcatcgaa--tctttgaac-gcaccttgcgctccat-g-----gtattcc-gtgga
gcatgcctg-tttgagtgtca-tgaatacttcaaccctc------ctcttt----cttaa
tgattgaagaggtgtttggtttctgagcgct-gc-tggc---ctttagggtctagctcgt
tcg-taatgcattag-c--atccgcaatcg-aacttcggattga----------------
------------------------------------------------------------
------------------------cttggcgtaatagactattcgct-gaggaattct-a
gtcttcgg-actagagccgggt----------------------tgggttaaaggaagct
tctaat-cagaa------------------------------------------------
-tgtgctacatttt--aagattagatctc-------------------------------
------------------------------------------------------------
---------------------------------------------
>Rhodotorula_GI966_EU108797_3501m Rhodotorula_GI966_EU108797_3501m 803 bp 
--------------------------------------ttccgtaggtgaacc-tgc-gg
aaggatcattagtgaatataggacgtcca-----actta---------acttgggag---
--tccgaactctcactt---tcta-----------accctgtgcatttgtttg-------
--------------------ggatagtaactctcgcaagagggcgaactcctatt-cact
tataaac------a-----caaagtctatgaatgtattaaatt-----------------
--------------------ttat-aacaaaataaaactttcaacaacggatctcttggc
tctcgcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaattcagt
-gaatcatcgaa--tctttgaac-gcaccttgcgctccat-g-----gtattcc-gtgga
gcatgcctg-tttgagtgtca-tgaatacttcaaccctc------ctcttt----cttaa
tgattgaagaggtgtttggtttctgagcgct-gc-tggc---ctttagggtctagctcgt
tcg-taatgcattag-c--atccgcaatcg-aacttcggattga----------------
------------------------------------------------------------
------------------------cttggcgtaatagactattcgct-gaggaattct-a
gtcttcgg-actagagccgggt----------------------tgggttaaaggaagct
tctaattcagaa------------------------------------------------
-tgtgctacattcttaagcattagatct--------------------------------
------------------------------------------------------------
---------------------------------------------
>Rhodotorula_glucinis_EF194846_1_marine Rhodotorula_glucinis_EF194846.1_marine 803 bp 
-------------tggaaggtaaaaatcgtaacaaggtttccgtaggtgaacc-tgc-gg
aaggatcattagtgaacataggacgtcca-----actta---------actt-ggag---
--tccgaactctcactt---tcta-----------accctgtgcatttgtttg-------
--------------------gggtagtagcctct----cggggcgaatccctatt-cact
tataaac------a-----caaagtctatgaatgtatttaatt-----------------
--------------------ttat-aacaaaataaaactttcaacaacggatctcttggc
tctcgcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaattcagt
-gaatcatcgaa--tctttgaac-gcaccttgcgctccat-g-----gtattcc-gtgga
gcatgcctg-tttgagtgtca-tgaatacttcaaccctc------ctcttt----cttta
tgatcgaagaggtgtttggattctgagcgtt-ttgctgg---cctcacggtcgagctcgc
tcg-taatgcattag-c--atccgcaatcg-aacttcggattga----------------
------------------------------------------------------------
------------------------cttggcgtaatagactattcgct-gaggaattct-a
gtcttcgg-actagagccgggt----------------------tggattaaaggaagct
cctaat-cctaa------------------------------------------------
-tgt-ct--atttt--aagattagatctcaaatca-ggtaggactacccgctgaa-ctt-
--aagcatatcaataagcggaggaa-----------------------------------
---------------------------------------------
>Rhodotorula_mucilaginosa_AF444614_1 Rhodotorula_mucilaginosa_AF444614.1 803 bp 
---------------------------------------tccgtaggtgaacc-tgc-gg
aaggatcattagtgaatataggacgtcca-----actta---------actt-ggag---
--tccgaactctcactt---tcta-----------accctgtgcacttgtttg-------
--------------------ggatagtaactctcgcaagagagcgaactcctatt-cact
tataaac------a-----caaagtctatgaatgtattaaatt-----------------
--------------------ttat-aacaaaataaaactttcaacaacggatctcttggc
tctcgcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaattcagt
-gaatcatcgaa--tctttgaac-gcaccttgcgctccat-g-----gtattcc-gtgga
gcatgcctg-tttgagtgtca-tgaatacttcaaccctc------ctcttt----cttaa
tgattgaagaggtgtttggtttctgagcgct-gc-tggc---ctttacggtctagctcgt
tcg-taatgcattag-c--atccgcaatcg-aacttcggattga----------------
------------------------------------------------------------
------------------------cttggcgtaatagactattcgct-gaggaattct-a
gtcttcgg-actagagccgggt----------------------tgggttaaaggaagct
tctaat-cagaa------------------------------------------------
-tgt-ctacatttt--aagattagatctcaaatca-ggtaggactacccgctgaa-ctt-
--aagcatatcaataagcggaggaaaag--------------------------------
---------------------------------------------
>Rhodotorula_mucilaginosa_AM117824_1_deep_sea Rhodotorula_mucilaginosa_AM117824.1_deep_sea 803 bp 
------------------------------------------------------------
aaggatcattagtgaatataggacgtcca-----actta---------actt-ggag---
--tccgaactctcgctt---tcta-----------accctgtgcacttgtttg-------
--------------------ggatagtaactctcgcaagagagcgaactcctatt-cact
tataaac------a-----caaagtctatgaatgtattaaatt-----------------
--------------------ttat-aacaaaataaaactttcaacaacggatctcttggc
tctcgcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaattcagt
-gaatcatcgaa--tctttgaac-gcaccttgcgctccat-g-----gtattcc-gtgga
gcatgcctg-tttgagtgtca-tgaatacttcaaccctc------ctcttt----cttaa
tgattgaagaggtgtttggtttctgagcgct-gc-tggc---ctttacggtctagctcgt
tcg-taatgcattag-c--atccgcaatcg-aacttcggattga----------------
------------------------------------------------------------
------------------------cttggcgtaatagactattcgct-gaggaattct-a
gtcttcgg-actagagccgggt----------------------tgggttaaaggaagct
tctaat-cagaa------------------------------------------------
-tgt-ctacatttt--aagattagatctcaaatca-ggtaggactacccgctgaa-ctt-
--aa--------------------------------------------------------
---------------------------------------------
>Rhodotorula_sp__DQ015695_1_Antarctic_sea_ice_psychrophile Rhodotorula_sp._DQ015695.1_Antarctic_sea_ice_psychrophile 803 bp 
------------------------------------------------------------
-----------------------tgtcga-----actcc---------att--ggag---
--tccgaactctcactt---tcta-----------accctgtgcacttgtttg-------
--------------------ggatagtaactctcgcaagagagcgaactcctatt-cact
tataaac------a-----caaagtctatgaatgtattaaatt-----------------
--------------------ttat-aacaaaataaaactttcaacaacggatctcttggc
tctcgcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaattcagt
-gaatcatcgaa--tctttgaac-gcaccttgcgctccat-g-----gtattcc-gtgga
gcatgcctg-tttgagtgtca-tgaatacttcaaccctc------ctcttt----cttaa
tgattgaagaggtgtttggtttctgagcgct-gc-tggc---ctttacggtctagctcgt
tcg-taatgcattag-c--atccgccatcg-aacttcggattga----------------
------------------------------------------------------------
------------------------cttggcgtaatagactattcgct-gaggaattct-a
gtcttcgg-attagagccggga----------------------tgggttaaaggaagct
tctaat-cagaa------------------------------------------------
-tgt-ctacatttt--aagattagatctcaaatta--ggaggactacccgctgaa-ctt-
--aagcatatcaataagcggaggaa-----------------------------------
---------------------------------------------
>Rhodotorula_sp__DQ643075_1_deep_sea Rhodotorula_sp._DQ643075.1_deep_sea 803 bp 
---------------------------------------tccgtaggtgaacc-tgc-gg
aaggatcattagtgaatataggacgtcca-----actta---------actt-ggag---
--tccgaactctcactt---tcta-----------accctgtgcacttgtttg-------
--------------------ggatagtaactctcgcaagagagcgaactcctattccact
tataaac------a-----caaagtctatgaatgtattaaatt-----------------
--------------------ttat-aacaaaataaaactttcaacaacggatctcttggc
tctcgcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaattcagt
-gaatcatcgaa--tctttgaac-gcaccttgcgctccat-g-----gtattcc-gtgga
gcatgcctg-tttgagtgtca-tgaatacttcaaccctc------ctcttt----cttaa
tgattgaagaggtgtttggtttctgagcgct-gc-tggc---ctttacggtctagctcgt
tcg-taatgcattag-c--atccgcaatcg-aacttcggattga----------------
------------------------------------------------------------
------------------------cttggcgtaatagactattcgct-gaggaattct-a
gtcttcgg-actagagccgggt----------------------tgggttaaaggaagct
tctaat-cagaa------------------------------------------------
-tgt-ctacatttt--aagattagatctcaaatca-ggtaggactacccgctgaa-ctt-
--aagcatatcaataagcggaggaa-----------------------------------
---------------------------------------------
>Saccharomyces_cerevisiae_AM900396_1 Saccharomyces_cerevisiae_AM900396.1 803 bp 
tgcgcttaagtgcgcggtcttgctaggcttgtaagtttctttcttgctattccaaacggt
gagagatttctgtgcttttgttatagg---------------------acaattaaaacc
gtttcaatacaacacactgtggagttttcatatctttgcaactttttctttgggcattcg
agcaatcggggcccagagg-------------taacaaacacaaacaattttatttattc
attaaatttttgtcaaaaacaagaattttcg--taactggaaa-----------------
--------------------ttttaaaatattaaaaactttcaacaacggatctcttggt
tctcgcatcgatgaagaacgcagcgaaatgcgatacgtaatgtgaattgcagaattccgt
-gaatcatcgaa--tctttgaac-gcacattgcgcccctt-g-----gtattcc-agggg
gcatgcctg-tttgagcgtca-tttccttctcaaacatt------ctgttt---------
-----------------ggtagtgagtgatactctttggagttaacttgaaattgctggc
ctt----ttcattgg---------------------------------------------
------------------------------------------------------------
-----------------------------------atgttttttttccaaagagaggttt
ctctgcgtgcttgaggtataatg-------------------------------------
-----------------------------caagtacggtcgttttaggttttaccaactg
cggctaatcttttttatactgagcgtattggaacg-------------------------
------ttatcgataagaagagagcgtctaggcgaacaatgttcttaaa-----------
---------------------------------------------
>Sporidiobolales_sp__EF060587_1_marine Sporidiobolales_sp._EF060587.1_marine 803 bp 
tcttggtcatttagaggaagtaaaagtcgtaacaaggtttccgtaggtgaacc-tgc-gg
aaggatcattagtgaatataggacgtcca-----actta---------actt-ggag---
--tccgaactctcactt---tcta-----------accctgtgcacttgtttg-------
--------------------ggatagtaactctcgcaagagagcgaactcctatt-cact
tataaac------a-----caaagtctatgaatgtattaaatt-----------------
--------------------ttat-aacaaaataaaactttcaacaacggatctcttggc
tctcgcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaattcagt
-gaatcatcgaa--tctttgaac-gcaccttgcgctccat-g-----gtattcc-gtgga
gcatgcctg-tttgagtgtca-tgaatacttcaaccctc------ctcttt----cttaa
tgattgaagaggtgtttggtttctgagcgct-gc-tggc---ctttacggtctagctcgt
tcg-taatgcattag-c--atccgcaatcg-aacttcggattga----------------
------------------------------------------------------------
------------------------cttggcgtaatagactattcgct-gaggaa-tct-a
gtcttcgg-atta-aacccggt----------------------tgggttaaaggaagct
tctaat-cagaa------------------------------------------------
-tgt-ctacatttt--aaga-tagatctcaaatca-gggaggact-cccgctgaa-ctt-
---agcctatcattagcggaggaaaagaactaacagggtttc------------------
---------------------------------------------
