>Oxyrrhis_marina_30_NAX01_3 385 bp 
ttgtggaaaagcgaaatca----tcatgggcattctaccctcccatctacttttttaatg
tgtacttgaccaga----tagaaaagcgcagcgacgaatttctagaatcagtaaacgaag
acgagcgcagcaaaatgcgaaaagccaaacgatatgctgatgatcgtgatgtttttgcaa
ttctaatacaggaagtgggacagtgttgtctcgtctttgttgcagggtatcggaatgtgt
gatttcgtaagttgctagcattgcgggcattgcac-cttacggcggcacgacagaacatg
gtggccttcttcaccatgcgtattgctctattgctgctaacacgcactggaattctgtca
cttgttaacgatgttgaatacccgct
>Oxyrrhis_marina_30_POR01 385 bp 
ttgtggaatattttagcgcccccatttcaatgctctacggcaacactgac-gccatttct
cctttcagtacccaatacttacaacgcgcagcaacgaatttctggaatcagtatacgatg
acgagcgcagccaattgcgataattagtgcgatatgctggtgttcgagaagtgtcgattg
ctctattgcgtggagtgcgacttcaatgtcacacctatgatgcagggtcaccgactattc
g-tgctgcatgtgccccgcacagtatgcactttgcattgtgggaggccaattcccacagc
aacacaatctgtcgcagaattcaaaagctaactaa--------------------tatga
cctgtcatcgtttgtgaacacccgct
>Oxyrrhis_marina_30_POS01 385 bp 
ttgtggaatattttagcgcccccatttcaatgctctacggcaacactgac-gccatttct
cctttcagtacccaatacttacaacgcgcagcaacgaatttctggaatcagtatacgatg
acgagcgcagccaattgcgataattagtgcgatatgctggtgttcgagaagtgtcgattg
ctctattgcgtggagtgcgacttcaatgtcacacctatgatgcagggtcaccgactattc
g-tgctgcatgtgccccgcacagtatgcactttgcattgtgggaggccaattcccacagc
aacacaatctgtcgcagaattcaaaagctaactaa--------------------tatga
cctgtcatcgtttgtgaacacccgct
>Oxyrrhis_marina_30_SUN01 385 bp 
ttgt-ggaaagcgaaatca----tcatgggcattctaccctcccatctacttttttaatg
tgtacttgaccaga----tagaaaagcgcagcgacgaatttctagaatcagtaaacgaag
acgagcgcagcaaaatgcgaaaagccaaacgatatgctgatgatcgtgatgtttttgcaa
ttctaatacaggaagtgggacagtgttgtctcgtctttgttgcagggtatcggaatgtgt
gatttcgtaagttgctagcattgcgggcattgcac-cttacggcggcacgacagaacatg
gtggccttcttcaccatgcgtattgctctattgctgctaacacgcactggaattctgtca
cttgttaacgatgttgaatacccgct
>Oxyrrhis_marina_351_AZO01 385 bp 
ttgtggataatccagatga----atatgtgaattctaccccttcatgcga-gaaaagtcc
tgtaccttctcaag----tagaaaagcgcagcgacgaatttctagaatcaataaacgaag
acgagcgcagcaaaatgcgaaaagccgaacgatatgctgatgatcgtgatgtttgtgcaa
ttctaatacaggaagtggggcaatgttgtctcgtccttgttgcagggtatcggactatgt
gatatcgtaagctgcttgcaccaccagcattgcgc-ttgtcgatgacatgattggatatg
gtggttatctgcaccatacgacagtaaccaacagatgttatacacactgaaattctgtca
cttgttaacgatgttgaacacccgct
>Oxyrrhis_marina_351_AZO02 385 bp 
ttgtggataatccagatga----atatgtgaattctaccccttcatgcga-gaaaagtcc
tgtaccttctcaag----tagaaaagcgcagcgacgaatttctagaatcaataaacgaag
acgagcgcagcaaaatgcgaaaagccgaacgatatgctgatgatcgtgatgtttgtgcaa
ttctaatacaggaagtggggcaatgttgtctcgtccttgttgcagggtatcggactatgt
gatatcgtaagctgcttgcaccaccagcattgcgc-ttgtcgatgacatgattggatatg
gtggttatctgcaccatacgacagtaaccaacagatgttatacacactgaaattctgtca
cttgttaacgatgttgaacacccgct
>Oxyrrhis_marina_351_FAR01_5 385 bp 
ttgtggaaaatgaaaattg--------ttgtatcctaccctcaaatagaa-agaaagtgt
ctaagaacccatcaatttttgaaaagcgcagcgacgaatttctagaatcaataatcgaag
acgagcgcagcaaattgcgaaaagcaaaacgatatgctgatgatcgagatgttcaggcaa
ttctaatacaggaagtgggacagttgtgtctcgtctttgttgcagggtatcggaacatgt
gtttatgtacggtgccagcttaactagcagtgcac-ttgacatcggcatgaccggatgtg
gtggat-tcatcaccataagttgcaattacgcaaatgctacacattttcagattctgtca
cttgttaacgatgttgagtacccgct
>Oxyrrhis_marina_353_ANT01_2 385 bp 
ttgtggaaaatgaaaattg--------ttgtatcctaccctcaaacagag-agaatgtgt
cttaaaacctataaatctttgaaaagcgcagcgacgaatttctagaatcaataatcgaag
acgagcgcagcaaattgcgaaaagcaaaacgatatgctgatgatcgagatgttcaggcaa
ttctaatacaggaagtgggacagttgtgtctcgtctttgttgcagggtatcggaacatgt
gtttatgtacggtgccagcttaaccagcagtgcac-ttgacatcggcatgaccggatgtg
gtggat-tcatcaccataacttgcaattacgcaaatgctacacattttcagattctgtca
cttgttaacgatgttgagtacccgct
>Oxyrrhis_marina_353_GAL01_2 385 bp 
ttgtggaaaatgaaaattg--------ttgtatcctaccctcaaacagag-agaatgtgt
cttaaaacctataaatctttgaaaagcgcagcgacgaatttctagaatcaataatcgaag
acgagcgcagcaaattgcgaaaagcaaaacgatatgctgatgatcgagatgttcaggcaa
ttctaatacaggaagtgggacagttgtgtctcgtctttgttgcagggtatcggaacatgt
gtttatgtacggtgccagcttaaccagcagtgcac-ttgacatcggcatgaccggatgtg
gtggat-tcatcaccataacttgcaattacgcaaatgctacacattttcagattctgtca
cttgttaacgatgttgagtacccgct
>Oxyrrhis_marina_353_GAL03_4 385 bp 
ttgtggaaaatgaaaattg--------ttgtatcctaccctcaaacagag-agaatgtgt
cttaaaacctataaatctttgaaaagcgcagcgacgaatttctagaatcaataatcgaag
acgagcgcagcaaattgcgaaaagcaaaacgatatgctgatgatcgagatgttcaggcaa
ttctaatacaggaagtgggacagttgtgtctcgtctttgttgcagggtatcggaacatgt
gtttatgtacggtgccagcttaaccagcagtgcac-ttgacatcggcatgaccggatgtg
gtggat-tcatcaccataacttgcaattacgcaaatgctacacattttcagattctgtca
cttgttaacgatgttgagtacccgct
>Oxyrrhis_marina_356_MAL01 385 bp 
ttgtggaatattctaaggcccccatttcaatgctctacggcaacactgac-gccatttct
cctttcagtactcaatacttacaacgcgcagcaacgaatttctggaatcagtatacgatg
acgagcgcagccaattgcgataattagtgcgatatgctggtgttcgagaagtgtcgattg
ctctattgcgtggagtgcgacttcaatgtcacacctatgatgcagggtcaccgactattc
g-tgctgcatgtgctccgcacagtatgcactttgcattgtgggaggtcaattcccacagc
aaaacaatctgtcgcagaattcaaaagctaactga--------------------tatga
cctgtcatcgtttgtgaacacccgct
>Oxyrrhis_marina_39_NAP01_2_4 385 bp 
ttgtggataatccaaatga----atatgtgaattctaccccttcatgcga-gaaaagtcc
tgtattacctaaag----tagaaaagcgcagcgacgaatttctagaatcaataaacgaag
acgagcgcagcaaaatgcgaaaagccgaacgatatgctgatgatcgtgatgtttgtgcaa
ttctaatacaggaagtggggcactgttgtctcgtccttgttgcagggtatcggactatgt
gatatcgtaagcagcttgcaccaccagcattgcgc-ttgtcgatgacatgattggatatg
gtgcatatctgcaccatacgccagtaaccaacagatgttatacacactgaaattctgtca
cttgttaacgatgttgaacacccgct
>Oxyrrhis_marina_39_NAP03_5 385 bp 
ttgtggataatccagagga----atctgtgaattccaccccttgatgcga-gaagagtac
tgtgtcatttcaag----tagaaaagcgcagcgacgaatttctagaatcaataaacgaag
acgagcgcagcaaaatgcgaaaagccggacgatatgctgatgatcgtgatgtttgtgcaa
ttctaatacaggaagtggggcaatgttgtctcgtccttgttgcagggtatcggactatgt
gatatcgtaagctgcttgcaccaccagcattgcgc-ttgtcgatgacatgattggatatg
gtggttatctgcaccatacgacactaaccaacagatgttacacacactgaaattctgtca
cttgttaacgatgttgaacacccgct
>Oxyrrhis_marina_39_NAP07 385 bp 
ttgtggataatccagatga----atctgtgaattctaccccttcatgcga-gaaag--tc
tgtaccatctcaag----tagaaaagcgcagcgacgaatttctagaatcaataaacgaag
acgagcgcagcaaaatgcgaaaagccgaacgatatgctgatgatcgtgatgtttgtgcaa
ttctaatacaggaagtggggcaatgttgtctcgtccttgttgcagggtatcggactatgt
gatatcgtaagctgcttgcaccaccagcattgcgc-ttgtcgatgacatgattggatatg
gtggttatctgcaccatacgacagtaaccaacagatgttatacacactgaaattctgtca
cttgttaacgatgttgaacacccgct
>Oxyrrhis_marina_44_ABE01_3 385 bp 
ttgtggaaaatgaaaattg--------ttgtatcctaccctcaaacagag-agaatgtgt
cttaaaacctataaatctttgaaaagcgcagcgacgaatttctagaatcaataatcgaag
acgagcgcagcaaattgcgaaaagcaaaacgatatgctgatgatcgagatgttcaggcaa
ttctaatacaggaagtgggacagttgtgtctcgtctttgttgcagggtatcggaacatgt
gtttatgtacggtgccagcttaaccagcagtgcac-ttgacatcggcatgaccggatgtg
gtggat-tcatcaccataacttgcaattacgcaaatgctacacattttcagattctgtca
cttgttaacgatgttgagtacccgct
>Oxyrrhis_marina_44_GLE01 385 bp 
ttgtggaaaatgaaaattg--------ttgtatcctaccctcaaacagag-agaatgtgt
cttaaaacctataaatctttgaaaagcgcagcgacgaatttctagaatcaataatcgaag
acgagcgcagcaaattgcgaaaagcaaaacgatatgctgatgatcgagatgttcaggcaa
ttctaatacaggaagtgggacagttgtgtctcgtctttgttgcagggtatcggaacatgt
gtttatgtacggtgccagcttaaccagcagtgcac-ttgacatcggcatgaccggatgtg
gtggat-tcatcaccataacttgcaattacgcaaatgctacacattttcagattctgtca
cttgttaacgatgttgagtacccgct
>Oxyrrhis_marina_44_JUR01 385 bp 
ttgtggaaaatgaaaattg--------ttgtatcctaccctcaaacagag-agaatgtgt
cttaaaacctataaatctttgaaaagcgcagcgacgaatttctagaatcaataatcgaag
acgagcgcagcaaattgcgaaaagcaaaacgatatgctgatgatcgagatgttcaggcaa
ttctaatacaggaagtgggacagttgtgtctcgtctttgttgcagggtatcggaacatgt
gtttatgtacggtgccagcttaaccagcagtgcac-ttgacatcggcatgaccggatgtg
gtggat-tcatcaccataacttgcaattacgcaaatgctacacattttcagattctgtca
cttgttaacgatgttgagtacccgct
>Oxyrrhis_marina_44_LLA01 385 bp 
ttgtggaaaatgaaaattg--------ttgtatcctaccctcaaacagag-agaatgtgt
cttaaaacctataaatctttgaaaagcgcagcgacgaatttctagaatcaataatcgaag
acgagcgcagcaaattgcgaaaagcaaaacgatatgctgatgatcgagatgttcaggcaa
ttctaatacaggaagtgggacagttgtgtctcgtctttgttgcagggtatcggaacatgt
gtttatgtacggtgccagcttaaccagcagtgcac-ttgacatcggcatgaccggatgtg
gtggat-tcatcaccataacttgcaattacgcaaatgctacacattttcagattctgtca
cttgttaacgatgttgagtacccgct
>Oxyrrhis_marina_44_MIL01_3 385 bp 
ttgtggaaaatgaaaattg--------ttgtatcctaccctcaaacagag-agaatgtgt
cttaaaacctataaatctttgaaaagcgcagcgacgaatttctagaatcaataatcgaag
acgagcgcagcaaattgcgaaaagcaaaacgatatgctgatgatcgagatgttcaggcaa
ttctaatacaggaagtgggacagttgtgtctcgtctttgttgcagggtatcggaacatgt
gtttatgtacggtgccagcttaaccagcagtgcac-ttgacatcggcatgaccggatgtg
gtggat-tcatcaccataacttgcaattacgcaaatgctacacattttcagattctgtca
cttgttaacgatgttgagtacccgct
>Oxyrrhis_marina_44_NOR01 385 bp 
ttgtggaaaatgaaaattg--------ttgtatcctaccctcaaacagag-agaatgtgt
cttaaaacctataaatctttgaaaagcgcagcgacgaatttctagaatcaataatcgaag
acgagcgcagcaaattgcgaaaagcaaaacgatatgctgatgatcgagatgttcaggcaa
ttctaatacaggaagtgggacagttgtgtctcgtctttgttgcagggtatcggaacatgt
gtttatgtacggtgccagcttaaccagcagtgcac-ttgacatcggcatgaccggatgtg
gtggat-tcatcaccataacttgcaattacgcaaatgctacacattttcagattctgtca
cttgttaacgatgttgagtacccgct
>Oxyrrhis_marina_44_PLY01_5 385 bp 
ttgtggaaaatgaaaattg--------ttgtatcctaccctcaaacagag-agaatgtgt
cttaaaacctataaatctttgaaaagcgcagcgacgaatttctagaatcaataatcgaag
acgagcgcagcaaattgcgaaaagcaaaacgatatgctgatgatcgagatgttcaggcaa
ttctaatacaggaagtgggacagttgtgtctcgtctttgttgcagggtatcggaacatgt
gtttatgtacggtgccagcttaaccagcagtgcac-ttgacatcggcatgaccggatgtg
gtggat-tcatcaccataacttgcaattacgcaaatgctacacattttcagattctgtca
cttgttaacgatgttgagtacccgct
>Oxyrrhis_marina_44_STA01 385 bp 
ttgtggaaaatgaaaattg--------ttgtatcctaccctcaaacagag-agaatgtgt
cttaaaacctataaatctttgaaaagcgcagcgacgaatttctagaatcaataatcgaag
acgagcgcagcaaattgcgaaaagcaaaacgatatgctgatgatcgagatgttcaggcaa
ttctaatacaggaagtgggacagttgtgtctcgtctttgttgcagggtatcggaacatgt
gtttatgtacggtgccagcttaaccagcagtgcac-ttgacatcggcatgaccggatgtg
gtggat-tcatcaccataacttgcaattacgcaaatgctacacattttcagattctgtca
cttgttaacgatgttgagtacccgct
>Oxyrrhis_marina_45_BOG01_2 385 bp 
ttgtggaaaatgaaaattg--------ttgtatcctaccctcaaacagag-agaatgtgt
cttaaaacctataaatctttgaaaagcgcagcgacgaatttctagaatcaataatcgaag
acgagcgcagcaaattgcgaaaagcaaaacgatatgctgatgatcgagatgttcaggcaa
ttctaatacaggaagtgggacagttgtgtctcgtctttgttgcagggtatcggaacatgt
gtttatgtacggtgccagcttaaccagcagtgcac-ttgacatcggcatgaccggatgtg
gtggat-tcatcaccataacttgcaattacgcaaatgctacacattttcagattctgtca
cttgttaacgatgttgagtacccgct
>Oxyrrhis_marina_45_LOG01 385 bp 
ttgtggaaaatgaaaattg--------ttgtatcctaccctcaaacagag-agaatgtgt
cttaaaacctataaatctttgaaaagcgcagcgacgaatttctagaatcaataatcgaag
acgagcgcagcaaattgcgaaaagcaaaacgatatgctgatgatcgagatgttcaggcaa
ttctaatacaggaagtgggacagttgtgtctcgtctttgttgcagggtatcggaacatgt
gtttatgtacggtgccagcttaaccagcagtgcac-ttgacatcggcatgaccggatgtg
gtggat-tcatcaccataacttgcaattacgcaaatgctacacattttcagattctgtca
cttgttaacgatgttgagtacccgct
>Oxyrrhis_marina_81_JAP01 385 bp 
ttgtggataatccagagga----atctgtgaattccaccccttgatgcga-gaagagtac
tgtgtcatttcaag----tagaaaagcgcagcgacgaatttctagaatcaataaacgaag
acgagcgcagcaaaatgcgaaaagccggacgatatgctgatgatcgtgatgtttgtgcaa
ttctaatacaggaagtggggcaatgttgtctcgtccttgttgcagggtatcggactatgt
gatatcgtaagctgcttgcaccaccagcattgcgc-ttgtcgatgacatgattggatatg
gtggttatctgcaccatacgacactaaccaacagatgttacacacactgaaattctgtca
cttgttaacgatgttgaacacccgct
>Oxyrrhis_marina_82_KOR01 385 bp 
ttgtggaaaatgaaaattg--------ttgtatcctaccctcaaacagag-agaatgtgt
cttaaaacctataaatctttgaaaagcgcagcgacgaatttctagaatcaataatcgaag
acgagcgcagcaaattgcgaaaagcaaaacgatatgctgatgatcgagatgttcaggcaa
ttctaatacaggaagtgggacagttgtgtctcgtctttgttgcagggtatcggaacatgt
gtttatgtacggtgccagcttaaccagcagtgcac-ttgacatcggcatgaccggatgtg
gtggat-tcatcaccataacttgcaattacgcaaatgctacacattttcagattctgtca
cttgttaacgatgttgagtacccgct
>Oxyrrhis_marina_CCAP11333 385 bp 
ttgtggaaaatgaaaattg--------ttgtatcctaccctcaaacagag-agaatgtgt
cttaaaacctataaatctttgaaaagcgcagcgacgaatttctagaatcaataatcgaag
acgagcgcagcaaattgcgaaaagcaaaacgatatgctgatgatcgagatgttcaggcaa
ttctaatacaggaagtgggacagttgtgtctcgtctttgttgcagggtatcggaacatgt
gtttatgtacggtgccagcttaaccagcagtgcac-ttgacatcggcatgaccggatgtg
gtggat-tcatcaccataacttgcaattacgcaaatgctacacattttcagattctgtca
cttgttaacgatgttgagtacccgct
>Oxyrrhis_marina_CCAP11334 385 bp 
ttgtggttgatc-aaacaacgctttgccagtgctgtacggccacccgaac-ggagcagcg
tttgtt-----tcaagacatacaatgtacatcaacgaatttctagaatcaatatgcgagg
acgaacgtagccaattgcgataatatgcgtgagatgctggtgttcgagaagcgataaatt
ttctattgcgtgaagcgcaatcattcgattgcgcacacgatgcagggcaaagggc-----
-acagcacgatcaatgactttggtgcacactttag-ttttggtctgtgtgttagtggatt
ggaacaagatgtccaatcctgttgatcaacatttacaataactattaagcaaatgcgccg
cctgtcattgtatgagaatacccgct
>Oxyrrhis_marina_CCAP11335 385 bp 
ttgtggttgatc-aaacaacgctttgccagtgctgtacggccacccgaac-ggagcagcg
tttgtt-----tcaagacatacaatgtacatcaacgaatttctagaatcaatatgcgagg
acgaacgtagccaattgcgataatatgcgtgagatgctggtgttcgagaagcgataaatt
ttctattgcgtgaagcgcaatcattcgattgcgcacacgatgcagggcaaagggc-----
-acagcacgatcaatgactttggtgcacactttag-ttttggtctgtgtgttagtggatt
ggaacaagatgtccaatcctgttgatcaacatttacaataactattaagcaaatgcgccg
cctgtcattgtatgagaatacccgct
>Oxyrrhis_marina_CCMP1739 385 bp 
ttgtggaaaagcgaaatca----tcatgggcattctaccctcccatctacttttttaatg
tgtacttgaccaga----tagaaaagcgcagcgacgaatttctagaatcagtaaacgaag
acgagcgcagcaaaatgcgaaaagccaaacgatatgctgatgatcgtgatgtttttgcaa
ttctaatacaggaagtgggacagtgttgtctcgtctttgttgcagggtatcggaatgtgt
gatttcgtaagttgctagcattgcgggcattgcac-cttacggcggcacgacagaacatg
gtggccttcttcaccatgcgtattgctctattgctgctaacacgcactggaattctgtca
cttgttaacgatgttgaatacccgct
>Oxyrrhis_marina_CCMP1788 385 bp 
ttgtggataatccagatga----atatgtgaattccaccccttcatgcga-gaaaagtgc
tgtacctgctcaag----tagaaaagcgcagcgacgaatttctagaatcaataaacgaag
acgagcgcagcaaaatgcgaaaagccgaacgatatgctgatgatcgtgatgtttgtgcaa
ttctaatacaggaagtggggcaatgttgtctcgtccttgttgcagggtatcggactatgt
gatatcgtaagctgcttgcaccaccagcatttcgc-ttgtcgatgacatgattggatatg
gtggttatctgcaccatacgacagtaaccaacagatgttatacacactgaaattctgtca
cttgttaacgatgttgaacacccgct
>Oxyrrhis_marina_CCMP1795 385 bp 
ttgtggataatccagatga----atatgtgaattccaccccttcatgcga-gaaaagtgc
tgtacctgctcaag----tagaaaagcgcagcgacgaatttctagaatcaataaacgaag
acgagcgcagcaaaatgcgaaaagccgaacgatatgctgatgatcgtgatgtttgtgcaa
ttctaatacaggaagtggggcaatgttgtctcgtccttgttgcagggtatcggactatgt
gatatcgtaagctgcttgcaccaccagcatttcgc-ttgtcgatgacatgattggatatg
gtggttatctgcaccatacgacagtaaccaacagatgttatacacactgaaattctgtca
cttgttaacgatgttgaacacccgct
>Oxyrrhis_marina_CCMP604 385 bp 
ttgtggataatccagatga----atatgtgaattccaccccttcatgcga-gaaaagtgc
tgtacctgctcaag----tagaaaagcgcagcgacgaatttctagaatcaataaacgaag
acgagcgcagcaaaatgcgaaaagccgaacgatatgctgatgatcgtgatgtttgtgcaa
ttctaatacaggaagtggggcaatgttgtctcgtccttgttgcagggtatcggactatgt
gatatcgtaagctgcttgcaccaccagcatttcgc-ttgtcgatgacatgattggatatg
gtggttatctgcaccatacgacggtaaccaacagatgttatacacactgaaattctgtca
cttgttaacgatgttgaacacccgct
