>Aegopogon_bryophilus 668 bp 
tcgtgaccctgaccaaaaaagaccgtgaatatgtcatccatgc-c-gccgtt--tgatgg
g-gcttgcacctgtctctcggtatggggcaca-t---acctt---tttct--acaagggt
tgtg-ctcc---aaaaagaacccacggcgctgtatggcgtcaaggaaaactgat----at
tacttgttc-gg---ggcct----agttcggcttgccggac-taa-ccccgggcagagat
-gatatgcta----atc-cacatgactctcggcaacggatatctcggctctcgcatcgat
gaagaacgtagcaaaatgcgatacctggtgtgaattgcagaatcccgtgaaccatcgagt
ttttgaacgcaagttgcgcccgaggccttctggttgagggcacgtctgcctgggcgtcac
gccaaaagacactccccaacatgccc-tatgttg--gt------tgggacgtggtattta
gcc-cctcgtgcc-ttt-ggcgcggtgggcacaagttggggctgccggcagtgccgatca
cagcacaaggtggatgacgcaagttgttctcggtgctatgatatgtactgattaaggcga
tt-----ctat-ggcccattgga-ccc-a-cggatcgaagtgcacatcgttcgaaccgcg
a
>Aegopogon_cenchroides 668 bp 
tcgtgaccctgaccaaaaaagaccgtgaacatgtcatccatgc-c-gccgtt--tgatgg
g-gcttgcacccgtctctcggtatggggcaca-t---acctt---cttct--agaaggga
agtgccccc---aaaaagaacccacggcgctgtatggcgtcaaggaaaactgat----at
tgcttgttt-gg---ggcca----cgttcggcttgccggac-taa-ccctaggcagtgat
-gatatgcta----atc-cacatgactctcggcaacggatatctcggctctcgcatcgat
gaagaacgtagcaaaatgcgatacctggtgtgaattgcagaatcccgtgaaccatcgagt
ttttgaacgcaagttgcgcccgaggccttctggttgagggcacgtctgcctgggcgtcac
gccaaaagacactccccaacatgccc-tatgttg--gt------tgggacgtggtattta
gcc-cctcgtgcc-attgggcgcggtgggcacaagttggggctgccggcagtgccgatca
cagcacaaggtggatgacgcaagttgttctcggtgctatgaaacgtactgattaaggcga
tt-----ctac-ggcccattgtacccc-a-cggatcgaagtgcacatcgttcgaaccgcg
a
>Bealia_mexicana 677 bp 
tcgtgaccctgaccaaaacagaccgtgaacatgtcatccatgc-c-gccggt--tgatgg
g-gsttgcacccgtctcccagcacggggcaca-a---acctt---cttca--agaagaga
gtgc-ccca---aaaaagaacccacggcgccgtatggcgtcaaggaaaactaata---aa
tcctagcty-cg---gggca----cgctcggcttgccggac-gaa-ccccgagcagtgat
-gctatgsta----ata-cacatgactctcggcaacggatatctcggctctcgcatcgat
gaagaacgtagcaaaatgcgatacctggtgtgaattgcagaatcccgtgaaccattgagt
ttttgaacgcaagttgcgcctgaggccttttggttgagggcacgtctgcctgggcgtcac
gccaaaagacactcctca------ccaaatcctg--gt------gtggacgtgatatttg
gcc-cctcgtgcc-tttg-gcacggtgggcctaagtaggggctgccggcggtgccgatca
cagcacaaggtggatgacgcaagttgttctcggtgctacgatatgaaccgtttacggcat
aa-----ctataagccctttgga-ccc-a-gcgaccgatgcacacgtagctcggaccgcg
a
>Blepharidachne_kingii 668 bp 
tcgtgaccctgaccaaaacagaccgcgaacgtgtcatcaatgc-t-gccggg--agacgg
g-tcttgcactcgtctcttggttaggcgtgcc-a---acctt---ctt----cggaaggt
aggg-accc---taaaagaacccacggcgccgtatggcgtcaaggaacactgaaa---tt
gccttgcgc-gg---gacca----cgaccggcctgtcggac-gta-ccccgtgcagggat
-gatatgtta----atc-cacatgactctcggcaacggatatctcggctctcgcatcgat
gaagaacgtagcaaaatgcgatacctggtgtgaattgcagaatcccgtgaaccatcgagt
ttttgaacgcaagttgcgcctgaggccttatggccgagggcacgtctgcctgggcgtcac
gccaaaagacactccaca------cc-aatcctg--gt------gcggacgtggtattcg
gcc-cctcgtgcc-att--gcgcggtgggcctaagtctgggctgccggcggtgccgatca
cagcacaaggtggatgacgcaagttgttctcggtgttgcgatttggaccgctttcagtga
tg-----atac-ggccctcgaga-ccc-a-tagacccaagcacacgtcgcttggaccgcg
a
>Blepharoneuron_shepherdii 668 bp 
tcgtgaccctgaccaaaacagaccgtgaacatgtcatccatgc-c-gccggg--tgatgg
g-gcttgcacccatctcctggcacggggcaca-g---acctt---cttct--agaagaga
aatg-cccc---aaaaagaacccacggcgccgtacggcgtcaaggaacactgata---aa
tctttgctc-ag---gag-a----cgtccggcttgccggac-gaa-ccttgtgcagcgat
-gctattcga----ata-cacatgactctcggcaacggatatctcggctctcgcatcgat
gaagaacgtagcaaaatgcgatacctggtgtgaattgcagaatcccgtgaaccatcgagt
ttttgaacgcaagttgcgcccgaggccttttggttgagggcacgtctgcctgggcgtcac
gccaaaagacactcccca------cc-aatctcg--gt------gcggacgtggtatttg
gcc-tctcgtgtc-tttgtgcgcggtgggcacaagttggggctgccggcggtgccgatca
cagcacaaggtggatgacgctagttgttctcggtgctacgatacgatccgctcacggcaa
tt-----gtac-ggcccttttga-ccc-a-ttgatcgaagcgcatgccgctcgaaccgcg
a
>Blepharoneuron_tricholepis 671 bp 
tcgtgaccctgaccaaaacagaccgtgaacatgtcatccatgc-c-gctggt--tgatgg
g-gcttgcacctgtcacccagcacggggcaca-g---acctt---cttct--agaagtga
aatg-tccc---aaaaagaacccacggcgccgtatggcgtcaaggaacactgata---aa
tccttgctc-gg---gggca----cgtctggcttgccggac-gaa-ccccgtgcagcggt
agctatgtga----ata-cacatgactctcggcaacggatatctcggctctcgcatcgat
gaagaacgtagcaaaatgcgatacctggtgtgaattgcagaatcccgtgaaccatcgagt
ttttgaacgcaagttgcgcccgaggccttttggttgagggcacgtctgcctgggcgtcac
gccaaaagacactcccca------cc-aatccyg--gt------gcggacgtggtatttg
gcc-cctcgtgcc-tttgtgcgcggtgggcagaagttggggctgccggcggtgccggtca
cagcacaaggtggatgacgcaagttattctcggtgctacgacacggaccgcttacggcaa
t-------cac-ggcccttttga-ccc-a-ttgaccgaagcgcatgccgctcggaccgcg
a
>Bouteloua_trifida 668 bp 
tcgtgaccctaaccaaaacagaccgtgaacatgttacccatgc-c-gctggg--cgatgg
g-tctcgcacccatctctcagaacagggtgcc-g---acctt---cgt----tagagggg
aggg-gccc---taaatgaacccacggcgccgtatggcgtcaaggaacacagata---tt
gccttgcgt-gg---ggtgt----ggactggcatgccagtc-ggacccccgtgcagcgat
-catatgtta----ttt-cacatgactctcggcaacggatatctcggctctcgcatcgat
gaagaacgtagcaaaatgcgatacctggtgtgaattgcagaatcccgtgaaccatcgagt
ttttgaacgcaagttgcgcccgagaccttctggtcgagggcacgtctgcctgggcgtcat
gccaaaagacacacccca------cc-catcaag--ttgaggtggaggaagtggtatttg
gct-ctccgtgca-tctaggtgcggtgggcctaagttggggctgccggcggtgccgatca
cagcacaaggtggatgacgcaagttgttctc-gtgctatgattcggactgttttcggtga
cg-----ctat-ggccctttgca-ccc-a-tgtaccaaagcgcacaacgcttggaccacg
a
>Chaboissaea_decumbens 668 bp 
tcgtgaccctgaccaaaacagaccgtgaacatgtcatcgatgc-c-actgat--tgacgg
g-gcttgcacctgtctcttggtctggggcaaa-t---accttca-ctttt--gaagggaa
agtg-cccc---aaaaagaacccacggcgccgtatggcgtcaaggaacacttgt----at
tgcttgccc-ag---ggcca----cggtcggcttgccgaacggaa-ccctgtgcagtgat
-gatatgcta----atc-aacatgactctcggcaacggatatctcggctctcgcatcgat
gaagaacgtagcaaaatgcgatacctggtgtgaattgcagaatcccgtgaaccatcgagt
ttttgaacgcaagttgcgcccgaagccttctggttgagggcacgtctgcctgggcgtcac
gccaaaagacactcccca------cc-catccta--gt------ggggacgtggtttttg
gcc-cctcgtgcc-ttt-ggcgcggtgagccaaagttggggctgctggcggtgccgatca
cagcacaaggtggatgacgcaagttgttctcggtgctatgatatgagccgcatatggcga
tc-----ctat-agccctttgga-ccc-a-ttaatcgacacgcatgttgctcgaaccgcg
a
>Chaboissaea_ligulata 671 bp 
tcgtgaccctgaccaaaacagaccgtgaacatgttatccatgc-c-accgat--tggcgg
g-gcttgcacccrtctctcggcctgggacaaa-t---accttca-ttatt--gaggggaa
aatg-cccc---aaaaagaacccacggcgccgtatggcgtcaaggatcacttgt----at
tgcttgcca-ag---gccca----cggtcggcttgccgaacggaa-ccttgtgcagtgat
-gatatgcta----atc-aacatgactctcggcaacggatatctcggctctcgcatcgat
gaagaacgtagcaaaatgcgatacctggtgtgaattgcagaatcccgtgaaccatcgagt
ttttgaacgcaagttgcgcccgaagccttctggttgagggcacgtctgcctgggcgtcac
gccaaaagacactcccca------cc-catcata--gt------ggagacgtggtatttg
gcc-cctcgtgcc-ttt-ggtgcggtgagcaaaagttggggctgccggcggtgccgatca
cagcacaaggtggatgacgcaagttgttctcggtgctatgatatgagccgcatacggcga
tg-----ctat-ggccctttgga-ccc-a-ttaatcgaagcgcgcgtcgctcgaaccgcg
a
>Distichlis_spicata 686 bp 
tcgtgaccctgaccaaaacagaccgtgaacgtgtcctccatgc-c-gccggg--ttacag
g-tcyttcacctgtctctcggtacagggcgcc-a---acctt---ctt----yggarggg
aggg-gccc---taaaagaacccacggcgccgtatggcgtcaaggaacactgata---tt
gcgtagcac-gg---ggsca----cggtcggcttgccgggt-gca-ccccgtgccgcgat
-gatacatta----atc-cacatgactctcggcaacggatatctcggctctcgcatcgat
gaagaacgtagcaaaatgcgatacctggtgtgaattgcagaatcccgtgaaccatcgagt
ttttgaacgcaagttgcgcccgaggccttgyggtcgagggcacgtctgcctgggcgtcac
gccaaaagacactccaca------cc-cgtcaag--gt------gcggatgtggtatctg
gcc-cctcgtgcg-att--gtgcggtgggcctaagttggggctgccggcggtgccgacca
cagcrcaaggtggatgacgcaagttgttctcggcgctatgattcggaccgctttcggtga
tg-----ccac-ggccctctgta-ccc-a-tcgaccgaagcgcacatcgctcggaccgcg
a
>Hilaria_cenchroides 686 bp 
tcgtgaccctgaccaaagcagaccgtgaatttgtcatccatgc-t-gccgga--tgatgg
g-tccwgtactcatcactcggcatacggacggttccawcctt---ctt----yggaaggg
aggt-gtcc---gaaaagaacccacggcgccggatggcgtcaaggaagacaatca---tt
gctttgtgc-ggtgcggatg----tgtctggcatgccgggcactccctctgtgcggtgag
-catgttttargagatt-cacacgactctcggcaacggatatctcggctcttgcatcgat
gaagaacgtagcaaaatgcgatacctggtgtgaattgcagaatcccgtgaaccatcaagt
ttttgaacgcaagttgcgcccgaggccatttggttgagggcacgtctgcctgggcgtcac
gccaaaagacactcccca------tc-aatcatg--tt------gtggatgtggtgtatg
gct-cctcccacc---gcggcagggtgagctcaaagtygggctgtcggggctgccgatga
cagcgcaaggtggatgacgcaagttgttctatgtgctatgattcggctagctctcgacaa
tgaggatttgg-ccctttttaga-ccc-a-tyatccaaagaacctgtatcttggaccacg
a
>Lycurus_phleoides 683 bp 
tcgtgaccctgaccaaaacagaccgtgaacatgtcatccatgc-c-accggt--wgacgg
g-gctcgcacccgtctctcggtctggggcamc-t---accttcatttttt--gatgggaa
aktg-cccc---aaaaagaacccacggcgccgtatggcgtcaaggaacacttgt----at
tgcttgctc-gg---ggcta----cggtcggcttgccgaatggaa-ccccgtgcagtgat
-gatatgcta----atc-aacatgactctcggcaacggatatctcggctctcgcatcgat
gaagaacgtagcaaaatgcgatacctggtgtgaattgcagaatcccgtgaaccatcgagt
ttttgaacgcaagttgcgcccgaggccttctggttgagggcacgtctgcctgggcgtcac
gccaaaagacactcccca------cc-aatccta--gt------ggggacgtggtatttg
gcc-aatcgtgcc-ttt-ggcrcggtgggcaaaagttggggctgccggcggtgccgatca
cagcacaaggtggatgacgcaagttgttctcggtgttatgatatgtaccgcaaacggcga
tg-----gtat-ggccctttgga-ccc-a-tcaatcgaagcgcgygtcgctcgaaccgcg
a
>Lycurus_setosus 686 bp 
tcgtgaccctgaccaaaacagaccgtgaacatgtcatccatgc-c-accggt--wgacgg
g-gctcgcacccgtctctcggtctggggcamc-t---accttcatttttt--gatgggaa
aktg-cccc---aaaaagaacccacggcgccgtatggcgtcaaggaacacttgt----at
tgcttgctc-gg---ggcta----cggtcggcttgccgaatggaa-ccccgtgcagtgat
-gatatgcta----atc-aacatgactctcggcaacggatatctcggctctcgcatcgat
gaagaacgtagcaaaatgcgatacctggtgtgaattgcagaatcccgtgaaccatcgagt
ttttgaacgcaagttgcgcccgaggccttctggttgagggcacgtctgcctgggcgtcac
gccaaaagacactcccca------cc-aatccta--gt------ggggacgtggtatttg
gcc-aatcgtgcc-ttt-ggcrcggtgggcaaaagttggggctgccggcggtgccgatca
cagcacaaggtggatgacgcaagttgttctcggtgttatgatatgtaccgcaaacggcra
tg-----gtat-ggccctttgga-ccc-a-tcaatcgaagcgcgtytcgctcgaaccgcg
a
>Muhlenbergia_alamosae 695 bp 
tcgtgaccctkaccaaaacagaccgtgaacatgtcatccatgc-y-gccgtc--tgacgg
g-gcttgcacccgtctctcggtaaggggtaca-t---acctt---cttct--agaaggga
agtg-cccc---aaaaagaacccacggcgcygtatggcgtcaaggaacactgat----at
tgcgtgttt-gg---ggcaa----tgttcggcmtgctggac-tag-ccccgggcagtgat
-gatatgtta----atc-cacatgactctcggcaacggatatctcggctctcgcatcgat
gaagaacgtagcaaaatgcgatacctggtgtgaattgcagaatcccgtgaaccatcgagt
ttttgaacgcaagttgcgcccgaggccttctggttgagggcacgtctgcctgggcgtcac
gccaaaagacactcccaa------cc-aatctcg--gt------tgggacgtggtrtttg
gcc-cctcgtgccttttkggtgcggtgggcagaagttggggctgccggcggtgccgatca
cagcacaaggtggatggcgcaagttgttctcagtgctatgatacgaaccgcttayggcgt
tg-----ctac-ggcccttakga-ccc-a-tggatcgaagcrcacatcgctcgaaccgcg
a
>Muhlenbergia_annua 668 bp 
tcgtgaccctgaccaaaacagaccgtgaacttgtcatccatgc-c-gttggt--tgatgg
g-gcttgcacccgtctcccagctaggggcaca-g---acctt---cttcg--tgaagaga
aatg-cccc---aaaaagaacccacggcgccgtatggcgtcaaggatcactgaaa---aa
tccttgctc-gg---gtgca----cgtctggcttgccggat-gga-ccctgtgcagcgat
-gctatgcga----aaatcacatgactctcggcaacggatatctcggctctcgcatcgat
gaagaacgtagcaaaatgcgatacctggtgtgaattgcagaatcccgtgaaccatcgagt
ttttgaacgcaagttgcgcccgaggcctttcggttgagggcacgtctgcctgggcgtcac
gccaaaagacactcccca------cc-aatctta--gt------gtggacgtggtatttg
gct-cctcgtgcc-tttgcgcgcggtgggcataagttggggctgccggcggtgccggtca
cagcacaaggtggatgacgcaagtttttctcggtgctatgatacggacccgtgatggcaa
tt-----gtat-ggcccgttcga-ccc-a-atgaccgaagcgcatgccgctcggaccgcg
a
>Muhlenbergia_arenacea 674 bp 
tcgtgaccctgaccaaaacagaccgtgaacatgtcatccatgc-c-accggt--tgacgg
g-gcttgcacccgtctctcggtccggggcaca-t---accttca-tttta--gaagggaa
agtg-tccc---aaaaagaacccacggcgccgtatggcgtcaaggaacacttgt----at
tgcttgctcggg---ggcca----aggtcggcttgccgaacggaacccccgtgcagtgat
-gatatgcta----atc-aacatgactctcggcaacggatatctcggctctcgcatcgat
gaagaacgtagcaaaatgcgatacctggtgtgaattgcagaatcccgtgaaccatcgagt
ttttgaacgcaagttgcgcccgaggccttctggttgagggcacgtctgcctgggcgtcac
gccaaaagacact-ccca------ca-catccta--gt------ggggacgtggtatttg
gcc-cctcgtgcc-tttgtgcgcggtgggcaaaagttggggctgccggcggtgccgatca
cagcacaaggtggatgacgcaagttgttctcggtgytatgatacgagcygcatacggcga
tg-----ctat-ggccctttgga-ccc-a-tcaatcgaagcgcacgccgctcgaaccgcg
a
>Muhlenbergia_argentea 674 bp 
tcgtgaccctgaccaaaacagaccgtgaacatgtcatccatgc-t-gccggt--tgatgg
g-gcttgcacccgtctcctagcacggggcata-g---acctt---cctcg--agaagaga
aatg-tccc---aaaaagaacccacggcgccgtatggcgtcaaggaacactgata---aa
tctttgctc-gg---gggca----cgtctggcttgccggat-gaa-ccccgcgcagcgat
-gctatgcga----ata-tagatgactctcggcaacggatatctcggctctygcatcgat
gaagaacgtagcaaaatgcgatacctggtgtgaattgcagaatcccgtgaaccatcgagt
ttttgaacgcaagttgcgcccgaggccttttggtcgagggcacgtctgcctgggcgtcac
gccaaaagacactccgca------cc-aatccgg--tt------gtggacgtggtatttg
gcc-ccycgtgca-tttgtgcgcggtgggcagaagttggggctgccggcggtgccgatca
cagcgcatggtggatgacacaagttgttctcggtgctatgatacgaactgctcacggcaa
tt-----caac-gctcctttgga-tcc-a-ttgaccgaagcgcacactgctcggaccgcg
a
>Muhlenbergia_arsenei 668 bp 
tcgtgaccctgaccaaaacagaccgtgaacatgtcatccatgc-c-gccgtc--tgacgg
g-gcttgcacccgtctctcggtctggggcaca-tttcttctt---cttct--agaaggga
agcg-cccc---aaaaagaacccacggcgccgtatggcgtcaaggaacactgat----at
tgcttgttt-gg---ggcca----cgttcggcttgccggac-taa-cctcaggcagtgat
-gatatgcta----atc-cacatgactctcggcaacggatatctcggctctcgcatcgat
gaagaacgtagcaaaatgcgatacctggtgtgaattgcagaatcccgtgaaccatcgagt
ttttgaacgcaagttgcgcccgaggccttctggttgagggcacgtctgcctgggcgtcac
gccaaaagacactcccca------cc-catctcg--gt------tgggacgtggtatttg
gcc-cctcgtgcc-tttgggcacggtgggcagaagttggggctgccggcggtgccgatca
cagcacaaggtggatggcgcaagttattctcggtgctgtgatacgaaccgcttacggcga
tg-----c-ac-agccctttgga-ccc-a-tggatcgaagcgcatgtcgctcggaccgcg
a
>Muhlenbergia_brevis 668 bp 
tcgtgtccctgaccaaaacagaccgtgaatatgtcatccatgc-cagctggt--tgatgg
g-gcttgcacccgtctcccagctcggggcaca-g---acctt---cttct--tgaagaga
aatg-cccc---aaaaagaacccacggcgccgtatggcgtcaaggaacacagaaa---aa
tccttgttc-gg---gtgca----cgtccggcttgccggat-gga-ccccgtgcagtgat
-gctatgcga----aaa-cacatgactctcggcaacggatatctcggctctcgcatcgat
gaagaacgtagcaaaatgcgatacctggtgtgaattgcagaatcccgtgaaccatcgagt
ttttgaacgcaagttgcgcccgaggccttttggttgagggcacgtctgcctgggcgtcac
gccaaaagacactcccca------cc-aatctta--gt------gtggatgtggtatttg
gct-cctcgtaccttttgggtgcggtgggcagaagttggggctgccggcggtgccgatca
cagcacaaggtggatgacgcaagttgttctcggtgctatgatacggactgcttatggcaa
tt-----gcat-ggccctttgaa-ccc-a-atcaccgaagcgcatgccgctcggaccgcg
a
>Muhlenbergia_brevivaginata 677 bp 
tcgtgaccctgaccaaaayagaccgtgaacatgtcatcgaatc-c-gccggt--tgacgg
gtatttttacccgtctctcggtatggggcacg-t---acctt---cttcat-agaagcga
aggg-cccc---aaaaagaacccacggcgccgtatggcgtcaaggaaaactggt----at
tgcttgctc-ag---ggcaa----tgaacggcttgccgaacggaa-ccctgagcagcgat
-gatattgt-----atc-aacatgactctcggcaacggatatctcggctctcgcatcgat
gaagaacgtagcaaaatgcgatacctggtgtgaattgcagaatcccgtgaaccatcgagt
ttttgaacgcaagttgcgcccgaggccttttggycgagggcacgtctgcctgggcgtcac
gccaaaagacactcccca------ca-catccta--gt------ggggacgtggtatttg
gcc-actcgtgcc-tttgcgcgcggtgggctaaagttggggctgccggcggtgccgatca
cagcacaaggtggatgacgcaagttgttctcggtgctacgatacgagccgcatacggtga
tg-----ttat-ggccctctgga-ccc-a-ttgatcgaagygcttgtcgctcgaaccgcg
a
>Muhlenbergia_capillipes 668 bp 
tcgtgaccctgaccaaaacagaccgtgaacatgtcatccatgc-c-gctggt--tgatag
g-tcttgcacctgtctcctagcatggagcacg-t---acctt---ct-----agaaggga
aatg-cccc----aaaagaacccacggcgccgtatggcgtcaaggaaaactgaa----aa
tccttgctc-gg---gtgca----tgtccggcttgccggac-gat-gcccttgcagcgat
-gctatgcga----aaa-cacacgactctcggcaacggatatctcggctctcgcatcgat
gaagaacgtagcaaaatgcgatacctggtgtgaattgcagaatcccgtgaaccatcgagt
ttttgaacgcaagttgcgcccgaggccttttggttgagggcacgtctgcctgggcgtcac
gctaaaagtcactcccca------cc-atccttg--gt------gaggatgtggtatttg
gct-cctcgtgcc-tttgtgcgcggtgggcagaagttggggctgccggcggtgccgatca
cagcacaaggtggatgacggaagttattctaggtgctacgatacgaaccgtacacggcaa
tt-----gtat-ggcccttttga-ccc-a-acgaccgaagcgcacgttgctcggaccgcg
a
>Muhlenbergia_ciliata 668 bp 
tcgtgaccctgaccaaaacagaccgtgaacacgtcatccatgc-c-gccgtc--tgatag
g-tcttgcacctatctatcggtacggggtaca-t---acctt---tgtct--tgaaggga
agtg-cccc---aaaaagaacccacggcgccgtatggcgtcaaggaaaacttat----at
tgcttcttt-gg---ggcca----tgttcggcttgccggac-aaa-ccccgagcagcgat
-gctatggaa----atc-ca-atgactctcggcaacggatatctcggctctcgcatcgat
gaagaacgtagcaaaatgcgatacctggtgtgaattgcagaatcccgtgaaccatcgagt
ttttgaacgcaagttgcgcccgaggccttctggttgagggcacgtctgcctgggcgtcac
gcaaaaagacactcccta------tc-catcttg--gt------tgggacgtggcatttg
gcc-tctcgtgcc-ttcgggtgcggtgggcagaagttggggctgccggcggtgccgatca
cagcacaaggtggatggcgcaagttgttctcggtgctatgatacgaaccgcttatggcaa
tg-----caaa-ggccctttgga-ccc-a-tggatcgaagcgcacagcgctcggaccgcg
a
>Muhlenbergia_curtifolia 668 bp 
tcgtgaccctgaccaaaacagaccgtgaacatgtcatccatgc-c-gccgtt--tgatgg
g-gcttgcacccatctctcggtatggggcacg-t---acctt---cttct--agaaggga
agtg-cccc---aaaaagaacccacggcgccgtatggcgtcaaggaaaactgat----at
tgcttgttt-gg---ggcca----cgttcggcttgccggac-taa-ccccgggcagtgat
-gatatgcta----atc-cacatgactctcggcaacggatatctcggctctcgcatcgat
gaagaacgtagcaaaatgcgatacctggtgtgaattgcagaatcccgtgaaccatcgagt
ttttgaacgcaagttgcgcccgaggccttctggttgagggcacgtctgcctaggcgtcac
gccaaaagacactcccca------cc-catctcg--gt------tgggacgtggtatttg
gcc-cctcgtgcc-tttcagcgcggtgggcagaagttggggctgccggcagtgccgatca
cagcacaaggtggatgacgcaagttgttctcggtgctatgatacgaactgcttacggcga
tg-----ctac-ggcccatcgga-ccc-a-tggatcgaagcgcacatcgctcggaccgcg
a
>Muhlenbergia_diversiglumis 668 bp 
tcgtgaccctgaccaaaatagactgcgaacatgtcatccatgc-t-gccgtt--tggtgg
g-tctggcacccatctctcggtatgggttgca-t---aactt---cttct--agaaggga
agca-tccc---aaaaagaacccacggcgccgtatggcgccaaggaaaactgat----at
tgcttgttt-gg---ggcca----tgttcggcttgccggac-taa-ccctgggcagtgat
-gatatgcta----atc-cacatgactctcggcaacggatatctcggctctcgcatcgat
gaagaacgtagcgaaatgcgatacctggtgtgaattgcagaatcccgtgaaccatcgagt
ttttgaacgcaagttgcgcccgaagccttctggttgagggcacgtctgcctgggcgtcac
gccaaaagacactcccca-------c-catctcg--gt------tgggacgtggtatttg
gcc-cctcgtgcc-tttcggcacggtgggcagaagttggggctgccggcagtgccgatca
cagcacaaggtggatgacgcaagttgttctcggtgctatgatacgagctgcttacggcga
tg-----ctac-agccctttgga-ccc-a-tggttgtaagcgaacatcgcttggaccgcg
a
>Muhlenbergia_dumosa 668 bp 
tcgtgaccctgaccaaaacagaccgtgaacatgtcatccatgctc-gccgtt--tgacgg
g-gcttgcacccgtctctcggcccggggcaca-t---acctt---ctttt--agaaggga
aggg-cccc---aaaaagaacccacggcgccgtatggcgtcaaggaacactgat----at
tgcttgctt-gg---ggcca----cgttcggcttgccggat-gaa-ccccgggcagtgat
-gatatgcta----atc-cacatgactctcggcaacggatatctcggctctcgcatcgat
gaagaacgtagcaaaatgcgatacctggtgtgaattgcagaatcccgtgaaccatcgagt
ttttgaacgcaagttgcgcccgaggccttctggttgagggcacgtctgcctgggcgtcac
gccaaaagacactcccca------cc-catcttg--gt------agggacgtggtatttg
gtc-ccccgtgcc-ttttggcgcggtgggcaaaagttggggctgccggcggtgccgatca
cagcacaaggtggatgacgcaagttgttctcggtgctacgatacgaactgcttacggcga
tg-----ctac-ggccctttgga-ccc-a-ttgatcgaagcgcatgtcgctcggaccgcg
a
>Muhlenbergia_eludens 671 bp 
tcgtgaccctgaccaaaacagaccgtgaacatgtcatccatgc-c-gctggw--cgatgg
g-gcttgcacccgtctcccagcttggggcacg-g---acctt---cttcc--ggaagaga
aatg-cccc--aaaaaagaacccacggcgctgtatggcgtcaaggaacactaaga---aa
tctttgctc-gg---gtgca----cgtctggcttgccggat-gga-cctcgtgcagcgat
-gatatgcaa----aaa-cacatgactctcggcaacggatatctcggctctcgcatcgat
gaagaacgtagcaaaatgcgatacctggtgtgaattgcagaatcccgtgaaccatcgagt
ttttgaacgcaagttgcgcccgagaccttttggttgagggcacgtctgcctgggcgtcac
gccaaaagacactccaca------cc-aaccttg--gt------gtggacgtggtatttg
gct-catcgtgcc-cttgtgcgcggtgggcagaagttggggctgccggcggtgccgatca
cagcacaaggtggatgacgcaagttgttctcggtgctaggatacggacccctgatggcaa
tt-----gcac-ggccctatgga-ccc-a-tggaccggagtgcccgtcgctcggaccgcg
a
>Muhlenbergia_emersleyi 668 bp 
tcgtgaccctgaccaaaacagaccgtgaacatgtcatccatgc-c-gccgga--tgacgg
g-tcttgcacccgtctctcggcacggggcact-t---acctt---cttct--agaaggga
aggg-cccc---aaaaagaacccacggcgccgtatggcgtcaaggaacactgata---aa
tccttgctc-gg---ggctt----tggtcggcttgccggtc-gaa-ccccttgcagcgat
-gatatgcga----atc-cacatgactctcggcaacggatatctcggctctcgcatcgat
gaagaacgtagcaaaatgcgatacctggtgtgaattgcagaatcccgtgaaccatcgagt
ttttgaacgcaagttgcgcccgaggccttctggtcgagggcacgtctgcctgggcgtcac
gccaaaagacactcccct------cc-aatcccg--gt------gtggacgtggtatttg
gcc-cctcgtgcc-ttagcgtgcggtgggcagaagtttgggctgccggcggtgccgatca
cagcacaaggtggatgacgcaagttgttctcggtgctacgatacgaaccgcttacggcaa
tg-----ctat-ggccctttgga-ccc-t-tcgaccgaagcgcatgccgctcggaccgcg
a
>Muhlenbergia_expansa 683 bp 
tcgtgaccctgaccaaaacagaccgtgaacatgtcatccatgc-c-gccgga--agaygg
g-tcytgcacccgtctctcggcacggggcacy-t---acctt---ctyct--agaaggaa
aggg-cccc---aaaaagaacccacggcgccgtatggcgtcaaggaacactgata---aa
tccttgctc-gg---ggctt----yggtcggcttgccggtc-gaa-ccccttgcagcgat
-gatatgcga----atc-cacatgactctcggcaacggatatctcggctctcgcatcgat
gaagaacgtagcaaaatgcgatacctggtgtgaattgcagaatcccgtgaaccatcgagt
ttttgaacgcaagttgcgcccgaggccttctggtcgagggcacgtctgcctgggcgtcac
gccaaaagacactcccca------cc-aatcccg--gt------gtggacgtggtatttg
gcc-cctcgtgcc-ttagcgtgcggtgggcagaagtttgggctgccggcggtgccgatca
cagcacaaggtggatgacgcaagttgttctcggtgctacgatacgaaccgcttacggcaa
tg-----ctat-ggccctttgga-ccc-t-tcgaccgaagcgcatgccgctcggaccgcg
a
>Muhlenbergia_flavida 668 bp 
tcgtgaccctgaccaaaacagattgtgaacatgtcatcgatgc-c-gctggttgtgatgg
g-gcttgcacctgtctcctagcacggggcaca-g---acctt---cctctcgaggagaga
aatgcccta---aaaaagaacccacggcgccgtatggcgtcaaggaacactgataatcaa
tctttgctc-ga---gggac----tgtctggcttgccaggc-gaa-ccccgtgcagcgat
-gctatgcga----ata-cacatgactctcggcaacggatatcttggctctcacatcgat
gaagaacgtagcaaaatgcgatacctggtgtgaattgcagaatcccgtgaaccatcgagt
ttttgaacgcaagttgcgcccgaggccttttggttgagggcacgtctgcctgggcgtcac
gccaaaagacactcccc-------ct-aattcgg--gt------gtggatgtggta-ttg
gcc-cctcgtgca-tttgtgcgtggtgggcagaagttggggctgccggcagtgccgatca
cagcacgtggtggatgacacaagttgttctcggtgctatgatatgagctgctcacggcaa
tt-----caac-gctcctttgga-ccc-a-ttgaacgaattgcaagctgctcggaccacg
a
>Muhlenbergia_flaviseta 671 bp 
tcgtgaccctgaccaaaacagaccgtgaacaagtcatccatgc-t-gccaat--tgacag
g-gctcgcacctgtccattggtctcgggcacg-t---accttc--ttttt--agaaggta
acgg-cccc---aaaaagaacccacggcgccgtatggcgtcaaggaaaactgat----at
tgcttgcat-gg---ggcca----cgattggcttgctgaactgaa-ccccgtgcagcgat
-gatatgcta----atc-cacatgactctcggcaacggatatctcggctctcgcatcgat
gaagaacgtagcaaaatgcgatacctggtgtgaattgcagaatcccgtgaaccatcgagt
ttttgaacgcaagttgcgcccgaggccttttggttgagggcacgtctgcctgggcgtcac
gctaaaagacactctcca------cc-tatctta--gt------ggggacgtggtatttg
gcc-cmtcgtgcc-tttgcgtgcgatgggcagaagttggggctgccggcggtgccgatca
cagcacaaggtggatgacgtaagttgttctcggtgctacgatacgaactgcgtatggcaa
ag-----atat-ggccctttgga-ccc-a-tcgatcgaggcgcgtgtcgctcgtaccgcg
a
>Muhlenbergia_fragilis 668 bp 
tcgtgaccctgaccaaaacagaccgcgaacatgtcatccatgc-c-gctggg--tgatgg
g-gcttgcacctgtctcctagcatggggcaca-g---acctt---cc-----agaagaga
aatg-cccc---aaaaagaacacacggcgccgtatggcgtcaaggaaaactgga----at
tccttgctc-gg---gtgca----cgtctggcttgctggat-gga-ccccgtgcagcgat
-gatatgcga----aaa-cacatgactctcggcaacggatatctcggctctcgcatcgat
gaagaacgtagcaaaatgcgatacctggtgtgaattgcagaatcccgtgaaccatcgagt
ttttgaacgcaagttgcgcctgaggccttttggttgagggcacgtctgcctgggcgtcac
gctaaaagacactcctca------cc-aacctcg--gt------gtggatgtggtatttg
gct-cctcgtgcc-cttgtgtgcggtgggcagaagttggggctgctggcggtgcagatca
cagcacaaggtggatgacgcaagttattctcggtgctatgatatgaaccttactcggcaa
tt-----gcac-ggccctttgga-ccc-a-atgatcgaagcgcacgacgctcggaccgcg
a
>Muhlenbergia_gigantea 671 bp 
tcgtgaccctgaccaaaacagaccgtgaacatgtcatccatgc-c-gccgga--tgacgg
g-tcttgcacccgtctctcggcacggggcact-t---acctt---cttct--agaaggga
aggg-cccc---aaaaagaacccacggcgccgtatggcgtcaaggaacactgata---aa
tccttgctc-gg---ggctt----tggtcggcttgccggtc-gaa-ccccttgcagcgat
-gatatgcga----atc-cacatgactctcggcaacggatatctcggctctcgcatcgat
gaagaacgtagcaaaatgcgatacctggtgtgaattgcagaatcccgtgaaccatcgagt
ttttgaacgcaagttgcgcccgaggccttctggtcgagggcacgtctgcctgggcgtcac
gccaaaagacactcccca------cc-aatcccg--gt------gtggacgtggtatttg
gcc-cctcgtgcs-ttagcgtgcggtgggcagaagtttgggctgccggcggtgccgatca
cagcacaaggtggatgacgcaagttgttctcggtgctacgatacgaaccgcttacggcaa
tg-----ctat-ggccctttgga-ccc-t-tcgaccgaagcgcatgccgctcggaccgcg
a
>Muhlenbergia_himalayensis 668 bp 
tcgtgaccctgaccaaaacagaccgtgaacatgtcatccatgc-c-gccgtt--tgatgg
g-gcttgcacccgtctctcggtatggggcaca-t---acctt---cttct--agaaggga
agtg-gccc---aaaaagaacccacggcgccgtatggcgtcaaggaaaactgat----at
tgcttgttt-cg---ggcca----cgtccggcttgccggac-taa-ccccgggcagtgat
-gatatgcta----atc-cacatgactctcggcaacggatatctcggctctcgcatcgat
gaagaacgtagcaaaatgcgatacctggtgtgaattgcagaatcccgtgaaccatcgagt
ttttgaacgcaagttgcgcccgaggccttctggttgagggcacgtctgcctgggcgtcac
gccaaaagacactcccca------cc-catctcg--gt------tgggacgtggtatttg
gcc-cctcgtgcc-tttcggcgcggtgggcagaagttggggctgccggcagtgccgatca
cagcacaaggtggatgacgcaagttgttctcggtgctatgatacgaactgcttacggcga
tg-----ctat-ggcccattgga-ccc-a-tggatcgaagcgcacatcgctcggaccgcg
a
>Muhlenbergia_jonesii 668 bp 
tcgtgaccctgaccaaaacagaccgtgaacatgtcatccatgc-t-gccaat--tgatgg
g-cctcgcacccgtcaattggtctggggcacg-t---acttc---ttttt--agaaggga
acga-cccc---tacaagaacccacggcgccgtatggcgtcaaggaatactgat----at
tgcttgctc-gg---ggcaa----cgatcggcttgctgaacgaaa-ccctgtgcagtgat
-gatttgcta----att-cacatgactctcggcaacggatatctcggctctcgcatcgat
gaagaacgtagcaaaatgcgatacctggtgtgaattgcagaatcccgtgaaccatcgagt
ttttgaacgcaagttgcgcccgagaccttctggtcaagggcacgtctgcctgggcgtcac
gccaaaagacactcccca------cc-agtatta--gt------ggggacgtggtatttg
gtc-cttcgtgcc-tttgcgcgcggtgggcaaaagttggggctgccggcggtgccgatca
cagcacaaggtggatgacgcaagttgttctcggtgctatgatacgaaccgcatacggcaa
tg-----ctat-ggccctttgga-ccc-a-tcaatcgaagcgcgcgtcgctcgtaccgcg
a
>Muhlenbergia_lehmanniana 668 bp 
tcgtgaccctgaccaaaacagaccgtgaacatgtcatccatgc-c-gccgga--tgacgg
g-tcttgcacccgtctctcggcacggggcact-t---acctt---cttct--agaaggga
aggg-cccc---aaaaagaacccacggcgccgtatggcgtcaaggaacactgata---aa
tccttgctc-gg---ggctt----tggtcggcttgccggtc-aaa-ccccttgcagcgat
-gatatgcga----atc-cacatgactctcggcaacggatatctcggctctcgcatcgat
gaagaacgtagcaaaatgcgatacctggtgtgaattgcagaatcccgtgaaccatcgagt
ttttgaacgcaagttgcgcccgaggccttctggtcgagggcacgtctgcctgggcgtcac
gccaaaagacactcccca------cc-aatcccg--gt------gtggacgtggtatttg
gcc-cctcgtgcc-ttagcgtgcggtgggcagaagtttgggctgccggcggtgccgatca
cagcacaaggtggatgacgcaagttgttctcggtgctacgatacgaaccgcttacggcaa
tg-----ctat-ggccctttgga-ccc-t-tcgaccgaagcgcatgccgctcggaccgcg
a
>Muhlenbergia_ligularis 668 bp 
tcgtgaccctgaccaaaacagaccgtgaacatgtcatccatgc-c-gccggt--tgatgg
g-gcttgcacccatctcccagcacggggcacg-g---acctt---cttct--agaagaga
aatg-cccc---aaaaagaacccacggcgccgtatggcgtcaaggaacactgata---aa
tccttgctc-gg---gggca----cgtccggcttgccgaac-gaa-ccccgtgcagcgat
-gctatgcaa----ata-cacatgactctcggcaacggatatctcggctctcgcatcgat
gaagaacgtagcaaaatgcgatacctggtgtgaattgcagaatcccgtgaaccatcgagt
ttttgaacgcaagttgcgcccgaggccttttggtcgagggcacgtctgcctgggcgtcac
gccaaaagacactcccca------cc-aatcccg--gt------gcggacgtggtatttg
gcc-cctcgtgcc-tttgtgcgtggtgggcacaagttggggctgccggcagtgccgatca
cagcacaaggtggatgacgcaagttgttctcggtgctatgatacgaactgcttacggcaa
tt-----atat-ggccctttgga-ccc-a-ttgaccgaagcgcacaccgctcggaccgcg
a
>Muhlenbergia_lucida 677 bp 
tcgtgaccctgaccaaaacagaccgtgaacatgtcatccatgc-c-gccgga--tgacgg
g-tcttgcacccgtctctcggcacggggcact-t---acctt---cttct--agaaggga
aggg-cccc---aaaaagaacccacggcgccgtatggcgtcaaggaacactgata---ar
tccttgctc-gg---ggctt----tggtcggcttgccggtc-gaa-ccccttgcagcgat
-gatatgcga----atc-cacatgactctcggcaacggatatctcggctctcgcatcgat
gaagaacgtagcaaaatgcgatacctggtgtgaattgcagaatcccgtgaaccatcgagt
ttttgaacgcaagttgcgcccgaggccttctggtcgagggcacgtctgcctgggcgtcac
gccaaaagacactccccw------cc-aatcccg--gt------gtggacgtggtatttg
gcc-cctcgtgcc-ttagcgtgcggtgggcagaagtttgggctgccggcggtgccgatca
cagcacaaggtggatgacgcaagttgttctcggtgctacgatacgaaccgcttacggcaa
tg-----ctat-ggccctttgga-ccc-t-tsgaccgaagcgcatgccgctcggaccgcg
a
>Muhlenbergia_microsperma 671 bp 
tcgtgaccctgaccaaaacagaccgtgaacatgtcatccatgctt-cccgtt--tgacgg
g-gcttgcacccgtctctcggtccggagcact-t---acctt---cttat--agaaggga
aggg-cccc---aaaaagaacccacggcgccgtatggcgtcaaggaacactaat----at
ttcttgctt-gg---ggccg----cgttcggcttgccggat-gaa-ccccgggcagtgat
-gatatgcta----atc-cacatgactctcggcaacggatatctcggctctcgcatcgat
gaagaacgtagcaaaatgcgatacctggtgtgaattgcagaatcccgtgaaccatcgagt
ttttgaacgcaagttgcgcccgaggccttctggttgagggcaygtctgcctgggcgtcac
gcaaaaagacactcccca------cc-catcttg--gt------ggagacgtggtatttg
gctaccccgtgcc-ataaggcacggtgggcaaaagtttgggctgccggcggtgccgatca
cagcacaaggtggatgacgcaagttattctcggtgctacgatacgaaccgcttacggcga
tg-----ctat-gcccctttgga-ccc-a-ttgatcgaagcgcccgtcgctcggaccgcg
a
>Muhlenbergia_minutissima 668 bp 
tcgtgaccctgaccaaaacagaccgtgaacatgtcatccatgc-c-gctggt--agatgg
g-gcttgcacccgtctcccagcttggggcacg-g---acctt---cttcc--ggaagaga
aatg-cccc--aaaaaagaacccacggcgctgtatggcgtcaaggaacactaaga---aa
tctttgctc-gg---gtgca----cgtctggcttgccggat-gga-cctcgtgcagcgat
-gatatgcaa----aaa-cacatgactctcggcaacggatatctcggctctcgcatcgat
gaagaacgtagcaaaatgcgatacctggtgtgaattgcagaatcccgtgaaccatcgagt
ttttgaacgcaagttgcgcccgagaccttttggttgagggcacgtctgcctgggcgtcac
gccaaaagacactccaca------cc-aaccttg--gt------gtggacgtggtatttg
gct-catcgtgcc-cttgtgcgcggtgggcagaagttggggctgccggcggtgccgatca
cagcacaaggtggatgacgcaagttgttctcggtgctaggatacggacccctgatggcaa
tc-----gcac-ggccctatgga-ccc-a-tggaccggagtgcccgtcgctcggaccgcg
a
>Muhlenbergia_monandra 668 bp 
tcgtgaccctgaccaaaacagaccgtgaacatgtcatccattc-c-accgat--tgacgg
g-gcttgcacccgtctctcggactggggcaaa-t---accttca-ttctt--gaagggaa
agtg-cccc---aaaaagaacccacggcgccgtatggcgtcaaggaacacttgt----at
tgcttgccc-gg---ggcct----cggtcggcttgccgaactgaa-ccccgtgcagtgat
-gatatacta----atc-aacatgactctcggcaacggatatctcggctctcgcatcgat
gaagaacgtagcaaaatgcgatacctggtgtgaattgcagaatcccgtgaaccatcgagt
ttttgaacgcaagttgcgcccgaggccttctggttgagggcacgtctgcctgggcgtcac
gtcaaaagacactcccca------cc-catccta--gt------ggggatgtggtatttg
gcc-cctcgtgcc-ttt-ggcgcggtgggcaaaagttggggctgccggcggtgccgatca
cagcacaaggtggatgacgcaagttgttctcggtgctaggatacgagccgcatacggcga
tg-----ctat-ggccctttgga-ccc-a-tcaatcgaagcgcgcgtcgctcgaaccgcg
a
>Muhlenbergia_montana 668 bp 
tcgtgaccctgaccaaaacagaccgtgaacatgtcatccatgc-t-gccaat--tgacgg
g-cctcgcacccgtcaattggtctggggcacg-t---acttc---ttctt--agaaggga
acga-cccc---tacaagaacccacggcgccgtatggcgtcaaggaatactgat----at
tgcttgctc-gg---ggcaa----cgatcggcttgccgaacgaaa-ccctgtgcagtgat
-gatttgcta----att-cacatgactctcggcaacggatatctcggctctcgcatcgat
gaagaacgtagcaaaatgcgatacctggtgtgaattgcagaatcccgtgaaccatcgagt
ttttgaacgcaagttgcgcccgagaccttctggtcaagggcacgtctgcctgggcgtcac
gccaaaagacactcccca------cc-agtatta--gt------ggggacgtggtatttg
gtc-cttcgtgcc-tttgcgcgcggtgggcaaaagttggggctgccggcggtgccgatca
cagcacaaggtggatgacgcaagttgttctcggtgctatgatacgaaccgcatacggcaa
tg-----ctat-ggccctttgga-ccc-a-tcaatcgaagcgcgcgtcgctcgtaccgcg
a
>Muhlenbergia_nigra 671 bp 
tcgtgaccctgaccaaaacagaccgtgaacatgtcatccatgc-c-gccggt--tgacgg
g-tcttgcacccgtctctcggcacggggcact-t---acctt---cttct--agarggga
aggg-cccc---aaaaagaacccacggcgccgtatggcgtcaaggaacactgata---aa
tccttgctc-gg---ggctt----tggtcggcttgccggtc-gaa-ccccttgcagcgat
-gatatgcga----atc-cacatgactctcggcaacggatatctcggctctcgcatcgat
gaagaacgtagcaaaatgcgatacctggtgtgaattgcagaatcccgtgaaccatcgagt
ttttgaacgcaagttgcgcccgaggccttctggtcgagggcacgtctgcctgggcgtcac
gccaaaagacactcccca------cc-aatcccg--gt------gtggacgtggtatttg
gcc-cctcgtgcc-ttagcgtgcggtgggcagaagtttgggctgccggcggtgccgatca
cagcacaaggtggatgacgcaagttgttctcggtgctacgatacgaaccgcttacggcaa
tg-----ctat-ggccctttgga-ccc-t-tcgaccgaagcgcatgccgctcggaccgcg
a
>Muhlenbergia_pauciflora 668 bp 
tcgtgaccctgaccaaaacagaccgtgaacatgtccctcatgc-t-gccgtc--tgacgg
g-gcttgcacccgtctctcggtctggggcaaa-t---acctt---cttct--agaaggga
atgg-cccc---aaaaagaacccacggcgctgtatggcgtcaaggaacactgat----at
tgcttgttt-gg---ggcca----tgtccggcttgccggat-gta-cctcgggcagtgat
-gatatgcta----atc-cacatgactctcggcaacggatatctcggctctcgcatcgat
gaagaacgtagcaaaatgcgatacctggtgtgaattgcagaatcccgtgaaccatcgagt
ttttgaacgcaagttgcgcccgaggccttctggttgagggcacgtctgcctgggcgtcac
gccaaaagacactcccca------cc-catcttg--gt------tgggatgtggtatttg
gcc-cctcgttcc-tttgggcgcggtggacagaagttggggctgccggcggtgccgatca
cagcacaaggtggatggcgcaagttgttctcggtgctacgatacgaaccgcttacggcga
tg-----ctac-agccctttgga-cccaa-ttgatcgatgcgaacatcgctcggaccgcg
a
>Muhlenbergia_peruviana 668 bp 
tcgtgaccctgaccaaaacagaccgtgaacatgtcatccatgc-t-gccaat--tgacgg
g-ccttgtacctgtcaattggt-tggggcacg-t---acttc---tttta--agaatgga
acga-cccc---tacaagaacccacggcgccgtatggcgtcaaggaaaactgat----at
tgcttgcac-ag---ggcaa----cgatcggcttgctgaacggaa-ccctgtgcagtgat
-gatttgcta----act-cacatgactctcggcaacggatatctcggctctcgcatcgat
gaagaacgtagcaaaatgcgatacctggtgtgaattgcagaatcccgtgaaccatcgagt
ttttgaacgcaagttgcgcccgagaccttctggttgagggcacgtctgcctgggcgtcac
gccaaaagacactcccca------ca-attctgt--gt------ggggatgtggtatttg
gtc-cctcgtgcc-tttgagcgcggtgggcaaaagttggggctgccggcggtgccgatca
cagcacatggtggatgacgcatgttgttctcggtgctatgatacgaaccgcatacggcaa
tg-----atat-ggcccattgga-ccc-a-tcgatcgaagcgcgaaccgc---------g
a
>Muhlenbergia_polycaulis 674 bp 
tcgtgaccctgaccaaaacagaccgtgaacatgtcatccatgc-c-gccgtt--tgatgg
g-gcttgcacccgtctctcggtatggggcaca-t---acctt---cttct--agaaggga
agtg-cccc---aaaaagaacccacggcgccgtatggcgtcaaggaaaactgat----at
tgcttgttt-gg---ggcca----ygttcggcttgccggac-taa-ccccgggcagtgat
-gatatgcta----atc-cacatgactctcggcaacggatatctcggctctcgcatcgat
gaagaacgtagcaaaatgcgatacctggtgtgaattgcagaatcccgtgaaccatcgagt
ttttgaacgcaagttgcgcccgaggccttctggttgagggcacgtctgcctgggcgtcac
gccaaaagacactcccca------cc-cacctcg--gt------tgggacgtggtatttg
gcc-cctcgtgcc-tttcggcgcggtgggcagaagttggggctgccggcagtgccgatca
cagcacaaggtggatgacgcaagttgttctcggtgctatgatacgaactgcttacggcga
tg-----ctac-ggcccattgga-ccc-a-yggatcgaagcgcacatcgctcggaccgcg
a
>Muhlenbergia_porteri 677 bp 
tcgtgaccctgaccaaaacagaccgtgaacatgtcatccatgctt-gccgtt--tgacgg
g-gcttgcacccgtctctcggtccggggcack-t---acctt---cttst--agaaggga
aggg-cccc---aaaaagaacccacggcgccgtatggcgtcaaggaacactgat----at
tgcttgctt-gg---ggcca----cgttcggcttgccggat-gaa-ccccgggcagtgat
-gatatgcta----atc-cacatgactctcggcaacggatatctcggctctcgcatcgat
gaagaacgtagcaaaatgcgatacctggtgtgaattgcagaatcccgtgaaccatcgagt
ttttgaacgcaagttgcgcccgaggccttctggttgagggcacgtctgcctgggcgtcac
gccaaaagacactcccca------cc-aatcttg--gt------ggagacgtggtatttg
gct-ccccgtgcc-ttatggcgcggtgggcaaaagtttgggctgccggcggtgccgatca
cagcacaaggtggatgacgcgagttgttctcggtgctgcgataccaactgcttacggcga
tg-----ctat-rgccctttgga-ccc-a-gtgatcgaagcgcacgtcgctcggaccgcg
a
>Muhlenbergia_pungens 671 bp 
tcgtgaccctgaccaaaacagaccgtgaacatgtcatccatgc-c-gccggt--tgatgg
g-gcttgcacccgtctctcggtatggggcaca-a---accttc--ttttt--agaaggaa
atgg-cccc---aaaaagaacccacggcgccgtatggcgtcaaggaacacttgt----at
tgcttgctc-gg---ggata----cgatcggctcgccgaacggaa-ccccgtgcagtgat
-gatatgcta----atc-aacatgactctcggcaacggatatctcggctctcgcatcgat
gaagaacgtagcaaaatgcgatacctggtgtgaattgcagaatcccgtgaaccatcgagt
ttttgaacgcaagttgcgcccgaggccttctggttgagggcacgtctgcctgggcgtcac
gccaaaagacactcccca------cc-catccta--gt------ggggacgtggtatttg
gcc-ccccgtgcc-tttgcgcgcggtgggcaaaagttggggctgccggcggtgccgatca
cagcacaaggtggatgacgcaagttgttctcgrtgctacgatacgagccgcatacggcga
tg-----ctat-ggccctttgga-ccc-a-tcgatcgaagcacgcgtcgctcgaaccgcg
a
>Muhlenbergia_ramosa 668 bp 
tcgtgaccctgaccaaaacagaccgtgaacatgtcatccatgc-c-gccgtt--tgatgg
g-gcttgcacctgtctctcggtatggggcacg-t---acctt---cttct--agaaggga
agtg-cccc---aaaaagaacccacggcgccgtatggcgtcaaggaaaactgat----at
tgcttgttt-cg---ggcca----cgtccggcttgccggac-gaa-ccccgggcagtgat
-gatatgcta----atc-cacatgactctcggcaacggatatctcggctctcgcatcgat
gaagaacgtagcaaaatgcgatacctggtgtgaattgcagaatcccgtgaaccatcgagt
ttttgaacgcaagttgcgcccgaggccttctggttgagggcacgtctgcctgggcgtcac
gccaaaagacactcccca------cc-catctcg--gt------tgggacgtggtatttg
gcc-cctcgtgcc-tttcggcgcggtgggcagaagttggggctgccggcagtgccgatca
cagcacaaggtggatgacgcaagttgttctcggtgctatgatacgaactgcttacggcga
tg-----ctac-ggcccattgga-ccc-a-tggatcgaagcgcacatcgctcggaccgcg
a
>Muhlenbergia_ramulosa 668 bp 
tcgtgaccctgaccaaaacagaccgtgaacatgtcatccatgc-c-gccgtt--tgatgg
g-gcttgcacctgtctctcggtttgggacctg-g---aactt---cat-----gaaggga
aggg-tcccaaaaaaaagaacccacggcgccttatggcgtcaaggaaaacttaaa---tt
gccttgctc-gg---ggctt----cgaccggcgtgccggat-gaa-ccccgtgcagcgat
-gatatgcta----atc-aacatgactctcggcaacggatatctcggctctcgcatcgat
gaagaacgtagcaaaatgcgatacctggtgtgaattgcagaatcccgtgaaccatcgagt
ttttgaacgcaagttgcgcccgagaccttctggtcgagggcacgtctgcctgggcgtcac
gccaaaagacactcccca------cc-aatcctg--gt------gtggacgtggtatttg
gcc-cctcgtgcc-cttgagcatggtgggcagaagttggggctgccggcggtgccggtca
cagcacaaggtggatgacgcaagttgttctcggtgctgtgtttcg-accgcttacggcgc
t-----------tgccctttgga-ccc-a-tctaccgaagtgcatgtcgctcggactgcg
a
>Muhlenbergia_reederorum 689 bp 
tcgtgaccctgaccaaaacagaccgtgaacatgtcatccatgc-c-gccgga--wgacgg
g-tcytgcacccgtctctcggcacggggcamt-t---acctt---cttct--agaaggga
aggg-cccc---aaaaagaacccacggcgccgtatggcgtcaaggaacactgata---aa
tccttgctc-gg---ggctt----cggtcggcttgccggtc-gaa-ccccttgcagcgat
-gatatgcga----atc-cacatgactctcggcaacggatatctcggctctcgcatcgat
gaagaacgtagcaaaatgcgatacctggtgtgaattgcagaatcccgtgaaccatcgagt
ttttgaacgcaagttgcgcccgaggccttctggtcgagggcacgtctgcctgggcgtcay
gccaaaagacactcccca------cc-aatcccg--gt------gyggacgtggtatttg
gcc-cctcgtgcc-ttagcgygcggtgggcagaagtttgggctgccggcggtgccgatca
cagcacaaggtggatgacgcaagttgttctcggtgctgcgatacgaaccgcttacggcra
tg-----ctat-ggccctttgga-ccc-t-tcgaccgaagcgcatgccgctcggaccgcg
a
>Muhlenbergia_reverchonii 668 bp 
tcgtgaccctgaccaaaacagaccgtgaacatgtcatccatgc-c-gccgga--agatgg
g-tcttgcacccgtctctcggcacggggcact-t---gcctt---cttct--agaaggaa
aggg-cccc---aaaaagaacccacggcgccgtatggcgtcaaggaacactgata---aa
tccttgctc-gg---ggctt----tggtcggcttgccggtc-gaa-ccccttgcagcgat
-gatatgcga----atc-cacatgactctcggcaacggatatctcggctctcgcatcgat
gaagaacgtagcaaaatgcgatacctggtgtgaattgcagaatcccgtgaaccatcgagt
ttttgaacgcaagttgcgcccgaggccttttggtcgagggcacgtctgcctgggcgtcac
gccaaaagacactcccca------cc-aatcccg--gt------gtggacgtggtatttg
gcc-cctcgtgcc-ttagcgtgcggtgggcagaagtttgggctgccggcggtgccgatca
cagcacaaggtggatgacgcaagttgttctcggtgctacgatacgaaccgcttacggcaa
tg-----ctat-ggccctttgga-ccc-t-tcgaccgaagcgcatgccgctcggaccgcg
a
>Muhlenbergia_richardsonis 668 bp 
tcgtgaccctgaccaaaacagactgtgaacatgtcatccatgc-c-accgat--tgacgg
g-gcttgcacccgtctctcggtctggggcacatt---accttca-ttttt--gaaggaaa
agtg-gccc---aaaaagaacccacggcgccgtatggcgtcaaggaacacttgt----at
tgcttgctc-gg---ggcta----agatcggcttgccgaacggaa-ccccggacagtgat
-gatatgcta----atc-aacatgactctcggcaacggatatctcggctctcgcatcgat
gaagaacgtagcaaaatgcgatacctggtgtgaattgcagaatcccgtgaaccatcgagt
ttttgaacgcaagttgcgcccgagaccttctggttgagggcacgtctgcctgggcgtcac
gccaaaagacactcccca------cc-caaccta--gt------ggggacgtggtatttg
gct-cctcgtgtc-gttatgcacggtgggcaaaagttggggctgccggcggtgccgatca
cagcacaaggtggatgacgcaagttgttctcggtgctacgatacaagccgtgtacggcga
tg-----ctat-ggccctttgga-ccc-atttaatcgaagcgcgcgtcgctcgaaccgcg
a
>Muhlenbergia_schreberi 668 bp 
tcgtgaccctgaccaaaacagaccgtgaacatgtcatccatgc-c-accgtt--tgatgg
g-acttgcacccgtctctcggtatggggcacg-t---acctt---cttct--agaaggga
agtg-cccc---aaaaagaacccacggcgccgtatggcgtcaaggaaaactgat----at
tgcttgttt-cg---ggcca----cgtccggcttgccggac-taa-ccccgggcagtgat
-gatatgcta----atc-aacatgactctcggcaacggatatctcggctctcgcatcgat
gaagaacgtagcaaaatgcgatacctggtgtgaattgcagaatcccgtgaaccatcgagt
ttttgaacgcaagttgcgcccgaggccttctggttgagggcacgtctgcctgggcgtcac
gccaaaagacactcccca------cc-catctcg--gt------tgggacgtggtatttg
gcc-cctcgtgcc-tttcggcgcggtgggcagaagttggggctgccggcagtgccgatca
cagcacaaggtggatgacgcaagttgttctcggtgctatgatacgaactgcttacggcga
tg-----ctac-ggcccattgga-ccc-a-tggatcgaagcgcacatcgctcggaccgcg
a
>Muhlenbergia_seatonii 680 bp 
tcgtgaccctgaccaaaacagaccgtgaacatgtcatccatgc-c-accggt--tgatgg
g-gcttgcacccatctctcggtctggagcacg-t---acctaca-ttttt--gtagggaa
tgtg-cccc---aaaaagaacccacggcgctgtatggcgtcaaggaacacttgt----at
tgcttgctc-gg---agtca----cgttsggcttgccgaaaggaa-ccccgggcagtgat
-gatatgata----atc-aacatgactctcggcaacggatatctcggctctcgcatcgat
gaagaacgtagcaaaatgcgatacctggtgtgaattgcagaatcccgtgaaccatcgagt
ttttgaacgcaagttgcgcccgaggccttctggttgagggcacgtctgcctgggcgtcac
gycaaaagacactccccr------cc-tatctga--gt------agggatgtggtatttg
gcc-cctcgtgcc-tttgcgtgcggtgggcaaaagttggggctgccggcggagccgatca
cagcacaaggtggatgacgtaagttgttctcggtgctacgataygagccgcacacggcaa
tg-----ctat-ggccctttgga-ccc-a-tcaatcgaagcgcgtgtcgctcgaaccgcg
a
>Muhlenbergia_setarioides 668 bp 
tcgtgaccctgaccaaaacagaccgtgaacatgtcatccatcc-c-gccggt--tgatgg
g-gcttgcacccgtctctcggtctggggcaca-t---atctt---cttct--agaaggga
tgggctcca---aaaaagaacccacggcgccgtatggcgtcaaggtacactgaa----at
tgcttgctt-gg---ggcaacgatcgatcggcttgccggtt-gaa-ccccgggcagtgat
-gatatgcta----atc-aatatgactctcggcaacggatatctcggctctcgcatcgat
gaagaacgtagcaaaatgcgatacctggtgtgaattgcagaatcccgtgaaccatcgagt
ttttgaacgcaagttgcgcccgagaccttctggttgagggcacgtctgcctgggcgtcac
gccaaaagacactcccca------cc-catcttg--gt------gtggatgtggtatttg
gcc-cctcgtgcc-tttgtgcacggtgggcaaaagatggggctgccggcggtgccgatca
cagcacaaggtggatgacggaagttgttctcggtgctatgatatgaaccgcttacggcga
tg-----ctat-ggccctttgga-ccc-a-tccatcgaagcgcatgtcgctcgaaccgcg
a
>Muhlenbergia_sinuosa 674 bp 
tcgtgtccctgaccaaaacagaccgtgaacatgtcatccatgc-t-gccggt--tgatgg
g-gcttgcacccgtctcccagctcggggcaca-g---acctt---cttct--tgaagaga
aatg-cccc---aaaaagaacccacggcgccgtatggcgtcaaggaaaacagaaa---aa
tccttgtat-gg---gtgca----cgtccggcwtgccggat-gga-ccccatgcagtgat
-gmtatgcga----aaa-cacatgactctcggcaacggatatctcggctctcgcatcgat
gaagaacgtagcaaaatgcgatacctggtgtgaattgcagaatcccgtgaaccatcgagt
ttttgaacgcaagttgcgcccgaggccttttggttgagggcacgtctgcctgggcgtcac
gccaaaagacactcccca------ca-aatcttt--gt------gcggatgtggtatttg
gct-cctcgtgcc-tttgggcgcggtgagcagaagttggggctgccggcggtgccgatca
cagcacaaggtggatgacgcaagttgttctcggtgctatggtacggactgctgacggcga
-------gcat-ggccctttgga-ccc-a-ttgaccgaagcgcacgccgctcggaccgcg
a
>Muhlenbergia_sobolifera 668 bp 
tcgtgaccctgaccaaaacagaccgtgaacatgtcatccatgc-c-gccgtt--tgatgg
g-gcttgcacccgtctctcggtatggggcacg-t---acctt---cttct--agaaggga
aatg-cccc---aaaaagaacccacggcgccgtatggcgtcaaggaaaactgat----at
tgcttgttt-cg---gggca----cgtccggcttgccggac-taa-ccctgggcagtgat
-gatatgcta----ata-cacatgactctcggcaacggatatctcggctctcgcatcgat
gaagaacgtagcaaaatgcgatacctggtgtgaattgcagaatcccgtgaaccatcgagt
ttttgaacgcaagttgcgcccgaggccttctggttgagggcacgtctgcctgggcgtcac
gccaaaagacactcccca------cc-catctcg--gt------tgggacgtggtatttg
gcc-cctcgtgcc-tttcggcgcggtgggcagaagttggggctgccggcagtgccgatca
cagcacaaggtggatgacgcaagttgttctcggtgctatgatacgaactgcttacggcga
tg-----ctat-ggcccattgga-ccc-a-tggatcgaagcgcacatcgctcggaccgcg
a
>Muhlenbergia_stricta 680 bp 
tcgtgaccctgaccaaaacagaccgtgaacatgtcatccatgc-c-gccgga--tgacgg
g-tcttgcacccgtctcccggcacggggctct-t---acctt---cttct--agaaggga
aggg-cctc---aaaaagaacccacggcgccgtatggcgtcaaggaacactgata---aa
tccttgcay-gg---ggctt----tggtcggcttgccgswc-gaa-cyccttgcagcgat
-gatatgcga----atc-cacatgactctcggcaacggatatctcggctctcgcatcgat
gaagaacgtagcaaaatgcgatacctggtgtgaattgcagaatcccgtgaaccatcgagt
ttttgaacgcaagttgcgcccgaggccttctggttgagggcacgtctgcctgggcgtcac
gccaaaagacactcccca------cc-aatctcg--gt------gtggacgtggtatttg
gcc-cctcgtgcc-ttagcgtgcggtgggcagaagtttgggctgccggcggtgccgatca
cagcacaaggtggatgacgcaagttgttctcggtgctacgatacgaaccgcttacggcaa
tg-----ctat-ggccctttgga-ccc-t-tcgaccgaagcgcatgccgctcggaccgcg
a
>Muhlenbergia_tenuifolia 668 bp 
tcgtggccctgaccaaaacaaaccgtgaacatgtcatccatgctt-gccgat--tgacgg
g-gcttgcacccgtctctcggtctggggcgca-g---acctt---gtacc----aaggga
aggg-cccc---aaaaagaacccacggcgtcgtatgacgtcaaggaacactgat----at
tgcttgctt-gg---ggcca----cattcggcttgctggat-gac-ccccgagcagtgat
-gatatgcta----atc-aacatgactctcggcaacggatatctcggctctcgcatcgat
gaagaacgtagcaaaatgcgatacctggtgtgaattgcagaatcccgtgaaccatcgagt
ttttgaacgcaagttgcgcccgaggccttttggttgagggcacgtctgcctgggcgtcac
gccaaaagacactcccct------cc-catcctg--gt------ggggacgtggtatttg
gcc-ccccgtgcc-ttttggcacggtgggcaaaagttggggctgccggcggtgccgatca
cagcacaaggtggatgacgcaagttgttctcgatgctaggatacggacagcttatggcaa
tg-----atat-ggccctttgga-ccc-a-ttgatcgaagtgcacgtcgctcggaccgcg
a
>Muhlenbergia_torreyi 668 bp 
tcgtgaccctgaccaaaacagaccgtgaacatgtcatccatgc-c-gccggt--tgatgg
g-gcttgcacccatctcccggcatggggca---g---acctt---cttac--agaagaga
actg-cccc---aaaaagaacccacggcgccgtatggcgtcaaggaagactgaaa---aa
tccttgctc-gg---gtgca----agttcggcttgccggac-gga-ccccgtgcagcgat
-gctatgcga----aaa-cacatgactctcggcaacggatatctcggctctcgcatcgat
gaagaacgtagcaaaatgcgatacctggtgtgaattgcagaatcccgtgaaccatcgagt
ttttgaacgcaagttgcgcccgaggccttttggttgagggcacgtctgcctgggcgtcac
gccaaaagacactcccca------cc-aatctcg--gt------gcggatgtggtatttg
gct-cctcgtgcc-tttgtgcgcggtgggcataagttggggctgccggcggtgccgatca
cagcacaaggtggatgacgcaagttgttctcggtgctacgatacgaaccgctcacggcaa
tt-----gtac-ggccttttgga-ccc-a-ttgaccgaagcgcacgccgctcggaccgcg
a
>Muhlenbergia_utilis 668 bp 
tcgtgaccctgaccaaaacaaactgtgaacatgtcatccatgc-c-accgat--tgacgg
g-gcttgcacccgtctctcggtctggggcacatt---actttca-ttttt--gaaggtaa
agtg-gccc---aaaaagaacccacggcgccgtatggcgtcaaggaacacttgt----at
tgcttgctc-gg---ggcta----agatcggcttgccgaacggaa-ccccggacagcgat
-gatatgcta----atc-aacatgactctcggcaacggatatctcggctctcgcatcgat
gaagaacgtagcaaaatgcgatacctggtgtgaattgcagaatcccgtgaaccatcgagt
ttttgaacgcaagttgcgcccgagaccttctggttgagggcacgtctgcctgggcgtcac
gccaaaagacactcccca------cc-caatcta--gt------ggggacgtggtatttg
gcc-cctcgtgcc-gttgcgcacggtgggcaaaagttggggctgccggcggtgccgatca
cagcacaaggtggatgacgcaagttgttctcggtgctaagatacgagccgtgtacggcga
tg-----ctat-ggccctttgga-ccc-a-ttaatcgaagcgcgcgtcgctcgaaccgcg
a
>Muhlenbergia_vaginata 668 bp 
tcgtgaccctgaccaaaacagaccgtgaacatgtcatccatgc-c-gccggt--tgatgg
g-gcttgtacccgtctactagcacggggcacg-g---aactt---cttcc--ggaagaga
agtg-cccc---aaaaagaacccacggcgccgtatggcgtcaaggaacactgata---aa
tccttgctc-ga---ggaca----cgttcggcttgccggac-gat-ccccgtgcagcgat
-gctatgcga----ata-cacatgactctcggcaacggatatctcggctctcgcatcgat
gaagaacgtagcaaaatgcgatacctggtgtgaattgcagaatcccgtgaaccatcgagt
ttttgaacgcaagttgcgcccgaggccttttggttgagggcacgtctgcctgggcgtcac
gccaaaagacactctcca------cc-aatcctg--gt------gcggatgtggtatttg
gcc-cctcgtgcg-tttgtgcacggtgggcagaagttggggctgccggcggtgccgatca
cagcacaaggtggatgacgcaagttgttctcggtgctacgatagaaaccgcttacggcaa
tt-----gtac-ggccctttgga-ccc-a-ttga-cgaagcgcacgccgctcggaccgcg
a
>Muhlenbergia_villiflora_var__villiflora Muhlenbergia_villiflora_var._villiflora 671 bp 
tcgtgaccctgaccaaaacagaccgtgaacttgtcatccatgc-c-accgat--tgacgg
g-gcttgcacccgtctctcggtctggggcaaa-t---accttca-tttca--gaagggaa
agtg-cccc---aaaaagaacccacggcgccgtatggcgtcaaggaacacttgt----at
tgcttgccc-gg---ggcca----cggtcggcttgccgaacggaa-ccccgtgcagtgat
-gatatgcta----atc-aacatgactctcggcaacggatatctcggctctcgcatcgat
gaagaacgtagcaaaatgcgatacctggtgtgaattgcagaatcccgtgaaccatcgagt
ttttgaacgcaagttgcgcccgaggccttctggttgagggcacgtctgcctgggcgtcac
gccaaaagacactcccca------cc-catccta--gt------ggggacgtggtatttg
gcc-cctcgtgtc-tttgggcgcggtgggcamaagttggggctgccggcggtgccgatca
cagcacaaggtggatgacgcaagttgttctcgttgctacgatacgagccgcatacggcaa
tg-----ctat-ggccctttgga-ccc-a-tcaatcgaagcgcgcgtcgctcgaactgcg
a
>Muhlenbergia_virescens 671 bp 
tcgtgaccctgaccaaaacagaccgtgaacatgtcatccatgc-t-gccaat--tgacgg
g-cctcgcacccgtcaattggtctggggcacg-t---acttc---ttctt--agaaggga
acga-cccc---tacaagaacccacggcgccgtatggcgtcaaggaatactgat----at
tgcttgctc-gg---ggcaa----cgatcagcttgctgaacgaaw-ccctgtgcagtgat
-gatttgcta----att-cacatgactctcggcaacggatatctcggctctcgcatcgat
gaagaacgtagcaaaatgcgatacctggtgtgaattgcagaatcccgtgaaccatcgagt
ttttgaacgcaagttgcgcccgagaccttctggtcaagggcacgtctgcctgggcgtcac
gccaaaagacactcccca------cc-attatta--gt------ggggacgtggtatttg
gtc-cttcgtgcc-tttgcgcgcggtgggcaaaagttggggctgccggcggtgccgatca
cagcacaaggtggatgacgcaagttgttctcggtgctatgatacgaaccgcatacggcaa
tg-----ctat-ggccctttgga-ccc-a-tcaatcgaagcgcgcgtcgctcgtaccgcg
a
>Muhlenbergia_wrightii 686 bp 
tcgtgaccctgacmaaaacaraccgtgaacatgtcatccatgc-c-accggt--tgacgg
g-gcttgcacccgtctctcggtctggggcaaa-t---accttcg-tttta--gaagggaa
agtg-cccc---aaaaagaacccacggcgccgtatggcgtcaaggaacacttgt----at
tgcttgctc-rg---ggcca----cggtcggcttgccgaaygraa-ccccgtgcagtgat
-gatatgcta----atc-aacatgactctcggcaacggatatctcggctctcgcatcgat
gaagaacgtagcaaaatgcgatacctggtgtgaattgcagaatcccgtgaaccatcgagt
ttttgaacgcaagttgcgcccgaggccttctggttgagggcacgtctgcctgggcgtcac
gccaaaagacactcccca------cc-catccta--gt------ggggacgtggtatttg
gcc-cctcgtgcc-ttt-ggcgcggtgggcaaaagttggggctgccggcggtgccgatca
cagcacaaggtggatgacgcaagttgttctcggtgctacgatacgagccgcatacggcga
tg-----cyat-ggccctttgga-ccc-a-tcaatcgaagcgcgcgtcgctcgaaccgcg
a
>Pappophorum_vaginatum 668 bp 
tcgtgaccctgaacaaaacagactgtgaacatgtcgtccatgc-c-gctggg--taacag
g-gcttgcacctgtcacctggtacagggaacc-t---acttt---ctt----gtaaagtt
agtg-tccc---aaaaagaaccaacggcgccgtatggcgtcaaggaacaatgata---tt
gccttgctt--g---gttca----cgtttggcttgccggac-gaa-cccaatgcaaagat
-gagatgtta----atc-cacatgactctcggcaacggatatctcggctctcgcatcgat
gaagaacgtagcaaaatgcgatacctggtgtgaattgcagaatcccgtgaaccatcgagt
ttttgaacgcaagttgcgcccgaggccttttgactgagggcacgtctgcttgggcgtcac
tcctaaagacactcccca------cc-catcctg--gt------gcggacgtggtgtttg
gcc-cctcgcgcc-ttttggtgcggtgggcacaagttggggctgccggtgttgccgatca
cagcataaggtggataacaaatgttgttctcgaagctatgattcggaccacttctggtga
tg-----cgat-ggccctttgca-ccc-a-ttgacc-aagcgcacgttgcttggattgcg
a
>Pereilema_ciliatum 668 bp 
tcgtgaccctgaccaaaatagaccgtgaacatgtcatccatgc-t-gccgtt--tgacgg
g-gcttgcacccgcctctcggtctggggcaca-t---ccatt---cttct--agaatgga
agtg-cacc---aaaaagaacccacggcgccgtatggcgtcaaggaacactaat----at
tgcttgttt-gg---ggcca----cgttccgcttgcgggac-taa-ccctggacagtgat
-gatatgcta----atc-cacatgactctcggcaacggatatctcggctctcgcatcgat
gaagaacgtagcaaaatgcgatacctggtgtgaattgcagaatcccgtgaaccatcgagt
ttttgaacgcaagttgcgcccgaggtcttctggttgagggcacgtctgcctgggcgtcac
gccaaaagacactcccca------cc-catcttg--gt------tgggacgtggtatttg
gcc-cctcgtgcc-tttcggcgcggtgggcacaagtttgggctgccggcggtgccgatca
cagcacaaggtggatggcgcaagttgttctcggtgctgtgatatgaaccgcttacggtga
tg-----ctat-agccctttgga-ccc-a-tggatcgaagcgcacatcgctcggaccgcg
a
>Pereilema_crinitum 671 bp 
tcgtgaccctgaccaaaacagaccgtgaacatgtcatccatgt-c-gccgtt--tgacgg
g-gcttgcacccggctctcggtctggggcaca-t---ttctt---cttcc--agaaggga
tgcg-tccc---aaaaagaacccacggcgccgtatggcgtcaaggaacactgat----at
tgcttgttt-gg---ggcca----tgttcggcttgctggac-twa-ccccgggcagtgat
-gatatgcta----atc-cacatgactctcggcaacggatatctcggctctcgcatcgat
gaagaacgtagcaaaatgcgatacctggtgtgaattgcagaatcccgtgaaccatcgagt
ttttgaacgcaagttgcgcccgaggccttctggttgagggcacgtctgcctgggcgtcac
gccaaaagacactcccca------ca-tatcttg--gt------tgggacgtggtatttg
gcc-cctcgtgcc-tttgggcgcggtgggcagaagttggggctgccggcggtgccgatca
cagcacaaggtggatggcgcaagttgttctcggtgctgcgatacgaaccgcgtacggcga
tg-----ccac-ggccctttgga-ccc-a-tggatcgaagcgcatgtcgctcggaccgcg
a
>Redfieldia_flexuosa 668 bp 
tcgtgaccctgaccaaaacagaccgcgaacatgtcatccatgc-c-gccggt--tgacgg
g-gcttgcacccgtctctcggtatggggcaca-t---accttct-ttttt--gaagggaa
aggg-cccc---aaaaagaacccacggcgccgtatggcgtcaaggaaaacttgt----at
tgcttgctc-gg---ggcta----tgatcggcttgccgaacggaa-ccccgtgcagtgat
-gatatgcta----atc-aacatgactctcggcaacggatatctcggctctcgcatcgat
gaagaacgtagcaaaatgcgatacctggtgtgaattgcagaatcccgtgaaccatcgagt
ttttgaacgcaagttgcgcccgaggccttctggttgagggcacgtctgcctgggcgtcac
gccaaaagacactcccca------cc-catcctagggt------agggacgtggtatttg
gcc-cctcgtgcc-tttgtgcgcggtgggcaaaagttggggctgccggcggtgccgatca
cagcacaaggtggatgacgcaagttgttctcggtgctacgatacgagccgcatacggcga
tg-----ctat-agccctttgga-ccc-a-tggatcgaagcgcgcgtcgctcgaaccgcg
a
>Schaffnerella_gracilis 671 bp 
tcgtgaccctgaccaaaacagaccgtgaacatgtcatccatgc-c-accggt--tgacgg
g-g-tcgcacccgtctctcggtctggggcacc-t---accttcatttttt--gatgggaa
agtg-cccc---aaaaagaacccacggcgccgtatggcgtcaaggaacacttgt----at
tgcttgctc-gg---ggcaa----cggtcggcttgccgaatggaa-ccccgtgcagtgat
-gatatgcta----atc-aacatgactctcggcaacggatatctcggctctcgcatcgat
gaagaacgtagcaaaatgcgatacctggtgtgaattgcagaatcccgtgaaccatcgagt
ttttgaacgcaagttgcgcccgaggccttctggttgagggcacgtctgcctgggcgtcac
gccaaaagacactcccca------cc-aatccta--gt------ggggacgtggtatttg
gcc-aatcgtgcc-ttt-ggtgcggtgggcaaaagtgtgggctgccggcggtgccgatca
cagcacaaggtggatgacgcaagttgttctcggtgttatgatatgtaccgcaaacggtga
tg-----gtat-ggccctttgga-ccc-a-tgaatcgaagcgcgcgtcgytcgaaccgcg
a
