>Phytophthora_alticola_CMW19424_DQ988197 Phytophthora_alticola_CMW19424_DQ988197 895 bp 
ccacacct--aaaaactttccacgtgaaccgtatcaaac-ttttagttgggggtcttttt
cggcgacggctgctggcttcattgctggcggctgctgttgaat-gagccctatcatggcg
agcgtttaggctt---cggtctgaactagtagc-----ttttttaaacccatt-ctttat
tactgattatactgtggggacgaaagtctctgcttttaactagatagcaactttcagcag
tggatgtctaggctcgcacatcgatgaagaacgctgcgaactgcgatacgtaatgcgaat
tgcaggattcagtgagtcatcgaaattttgaacgcatattgcacttccgggttagtcctg
ggagtatgcctgtatcagtgtccgtacatcaaacttggctttcttccttccgtgtagtcg
gtgga--agatgtgccagatgtgaagtgtcttgcggctggt----cttcgggtc--ggct
gtgagtcctttgaaatgtactgaactgtacttctctttgctcgaaaagcgtggc--gttg
ctgattgtggaggctgcctgcgtagccagtctggcgaccagtttgtctgctgtggcg-tt
aatggaggagtgttcgattcgcggtatggttggcttcggctgaacagac-gcttattgaa
tggtttttcctgctatggcggtacagg--ttggtgaaccgtagctatgtg-ggcttggct
tttgaat-tggctttgctgttgcgaagtagagtgg-------------------cggctt
cagc------------tgtcgagggt-cgatcca----tttgggaag--tggtgggtact
t
>Phytophthora_alticola_CMW19425_DQ988196 Phytophthora_alticola_CMW19425_DQ988196 895 bp 
ccacacct--aaaaactttccacgtgaaccgtatcaaac-ttttagttgggggtcttttt
cggcgacggctgctggcttcattgctggcggctgctgttgaat-gagccctatcatggcg
agcgtttaggctt---cggtctgaactagtagc-----ttttttaaacccatt-ctttat
tactgattatactgtggggacgaaagtctctgcttttaactagatagcaactttcagcag
tggatgtctaggctcgcacatcgatgaagaacgctgcgaactgcgatacgtaatgcgaat
tgcaggattcagtgagtcatcgaaattttgaacgcatattgcacttccgggttagtcctg
ggagtatgcctgtatcagtgtccgtacatcaaacttggctttcttccttccgtgtagtcg
gtgga--agatgtgccagatgtgaagtgtcttgcggctggt----cttcgggtc--ggct
gtgagtcctttgaaatgtactgaactgtacttctctttgctcgaaaagcgtggc--gttg
ctgattgtggaggctgcctgcgtagccagtctggcgaccagtttgtctgctgtggcg-tt
aatggaggagtgttcgattcgcggtatggttggcttcggctgaacagac-gcttattgaa
tggtttttcctgctatggcggtacagg--ttggtgaaccgtagctatgtg-ggcttggct
tttgaat-tggctttgctgttgcgaagtagagtgg-------------------cggctt
cagc------------tgtcgagggt-cgatcca----tttgggaag--tggtgggtact
t
>Phytophthora_boehmeriae_DDS3884_EU301151 Phytophthora_boehmeriae_DDS3884_EU301151 895 bp 
ccacacct-aaaaaactttccacgtgaaccgt--tcaaccttttagttggggactcctcg
tcggcg----------------gctttcgggctgttggtgggttgaggcctatcaaagcg
agtgatttgggccgcaaggtctgagttgcgagt--tttccttttaaacccattacttaaa
tactgattatactgtggggacgaaagtctctgcttttaactagatagcaactttcagcag
tggatgtctaggctcgcacatcgatgaagaacgctgcgaactgcgatacgtaatgcgaat
tgcaggattcagtgagtcatcgaaattttgaacgcatattgcacttccgggttatgcctg
ggagtatgcctgtatcagtgtccgtacatcaaccttggcttccttccttccgtgtagtcg
gtggat-gggaatgccagacgtgaagtgtcttgctgtagcg--gttttcggactgcggcg
gcgagtcctttgaaatgta-gatactgttcttctctttgctcgaaaagctgtgcagaatg
tatgttgtggaggctgccatcacggcatgtc-ggcgactgattt-cgtgctgaggcgttt
--tggagaggggttcgattcgcggtagtgttggtttcggccgaacaatctgcttattggg
ttcttttccaggctttggcgtatgcggagtcggtgtaccgtagttgtgcgtggcttggcc
tttgaacgctcgttttgcgtggcgaagtagagtggcgaagtgtttgttttcggacgaatg
cggc------------tgccgaggaggcgataaatattttgggaaaatttagtgtgcgct
t
>Phytophthora_capsici_CBS128_23_DQ464056 Phytophthora_capsici_CBS128.23_DQ464056 895 bp 
ccacacct-aaaaaactttccacgtgaaccgtatcaacccttttagttgggggtcttgt-
----------------------------------------------accctatcatggcg
aatgtttggactt---cggtccgggcgagtagc-tttttgttttaaacccatt-tcacaa
ttctgattatactgtggggacgaaagtctctgcttttaactagatagcaactttcagcag
tggatgtctaggctcgcacatcgatgaagaacgctgcgaactgcgatacgtaatgcgaat
tgcaggattcagtgagtcatcgaaattttgaacgcatattgcacttccgggttagtcctg
ggagtatgcctgtatcagtgtccgtacatcaaacttggctttcttccttccgtgtagtcg
gtgga--ggatgtgccagatgtgaagtgtcttgcgtgttgt---ccttcgggtc--gact
gcgagtccttttaaatgtactgaactgtacttctctttgctcgaaaagcgtggt--gttg
ctggttgtggaggctgcctgcgtggccagtc-ggcgaccggtttgtctgctgcggcgttt
aaaggaggagtgttcgattcgcggtatggttggcttcggctgaacaggc-gcttattgaa
t-gcttttcctgctgtggcgtgatggg--ctggtgaaccgtagctgtgtttggcttggct
tttgaat-cggctttgctgttgcgaagtagagtgg-------------------cggctt
cggc------------tgtcgagggt-cgatcca---ttttgggaat-tttgtgtgcact
c
>Phytophthora_capsici_IMI352321_AF266787 Phytophthora_capsici_IMI352321_AF266787 895 bp 
ccacacct-aaaaaactttccacgtgaaccgtatcaacccttttagttgggggtcttgt-
----------------------------------------------accctatcatggcg
aatgtttggactt---cggtccgggcgagtagc-tttttgttttaaacccatt-tcacaa
ttctgattatactgtggggacgaaagtctctgcttttaactagatagcaactttcagcag
tggatgtctaggctcgcacatcgatgaagaacgctgcgaactgcgatacgtaatgcgaat
tgcaggattcagtgagtcatcgaaattttgaacgcatattgcacttccgggttagtcctg
ggagtatgcctgtatcagtgtccgtacatcaaacttggctttcttccttccgtgtagtcg
gtgga--ggatgtgccagatgtgaagtgtcttgcgtgttgt---ccttcgggtc--gact
gcgagtccttttaaatgtactgaactgtacttctctttgctcgaaaagcgtggt--gttg
ctggttgtggaggctgcctgcgtggccagtc-ggcgaccggtttgtctgctgcggcgttt
aaaggaggagtgttcgattcgcggtatggttggcttcggctgaacaggc-gcttattgaa
t-gcttttcctgctgtggcgtgatggg--ctggtgaaccgtagctgtgtttggcttggct
tttgaat-cggctttgctgttgcgaagtagggtgg-------------------cggctt
cggc------------tgtcgagggt-cgatcca---ttttgggaac-tttgtgtgcact
t
>Phytophthora_citricola_CBS221_88_IMI021173_FJ237526 Phytophthora_citricola_CBS221.88_IMI021173_FJ237526 895 bp 
ccacacct-aaaaaactttccacgtgaaccgtatcaacccttttagttgggggtcttgct
t------------------------------------tttttgcgagccctatcatggcg
aatgtttggactt---cggtctgggctagtagc-tttttgttttaaacccatt-ctacaa
tactgattatactgtggggacgaaagtctctgcttttaactagatagcaactttcagcag
tggatgtctaggctcgcacatcgatgaagaacgctgcgaactgcgatacgtaatgcgaat
tgcaggattcagtgagtcatcgaaattttgaacgcatattgcacttccgggttagtcctg
ggagtatgcctgtatcagtgtccgtacatcaaacttggctttcttccttccgtgtagtcg
gtgga--ggatgtgccagatgtgaagtgtcttgcgggtgtc----cttcgggtc--gtct
gcgagtcctttgaaatgtactgaactgtacttctctttgctcgaaaagcgtggt--gttg
ctggttgtggaggctgcctgcgtggccagtc-ggcgaccggtttgtctgctgcggcgttt
aatggaggagtgttcgattcgcggtatggttggcttcggctgaacaggc-gcttattgta
t-gcttttcctgctgtggcgtgatggg--ctggtgaaccgtagctgtgtgtggcttggct
tttgaat-cggctttgctgttgcgaagtagagtgg-------------------cggctt
cggc------------tgtcgagggt-cgatcca----tttgggaac-tttgtgtgcacc
t
>Phytophthora_citricola_CBS295_29_FJ560913 Phytophthora_citricola_CBS295.29_FJ560913 895 bp 
ccacacct-aaaaaactttccacgtgaaccgtatcaacccttttagttgggggtcttgct
t------------------------------------tttttgcgagccctatcatggcg
aatgtttggactt---cggtctgggctagtagc-tttttgttttaaacccatt-ctacaa
tactgattatactgtggggacgaaagtctctgcttttaactagatagcaactttcagcag
tggatgtctaggctcgcacatcgatgaagaacgctgcgaactgcgatacgtaatgcgaat
tgcaggattcagtgagtcatcgaaattttgaacgcatattgcacttccgggttagtcctg
ggagtatgcctgtatcagtgtccgtacatcaaacttggctttcttccttccgtgtagtcg
gtgga--ggatgtgccagatgtgaagtgtcttgcgggtgtc----cttcgggtc--gtct
gcgagtcctttgaaatgtactgaactgtacttctctttgctcgaaaagcgtggt--gttg
ctggttgtggaggctgcctgcgtggccagtc-ggcgaccggtttgtctgctgcggcgttt
aatggaggagtgttcgattcgcggtatggttggcttcggctgaacaggc-gcttattgta
t-gcttttcctgctgtggcgtgatggg--ctggtgaaccgtagctgtgtgtggcttggct
tttgaat-cggctttgctgttgcgaagtagagtgg-------------------cggctt
cggc------------tgtcgagggt-cgatcca----tttgggaac-tttgtgtgcacc
t
>Phytophthora_citricola_CH98U121C_AB367378_Japan Phytophthora_citricola_CH98U121C_AB367378_Japan 895 bp 
ccacacct-aaaaaactttccacgtgaaccgtatcaacccttttagttgggggtcttgct
t------------------------------------tttttgcgagccctatcatggcg
aatgtttggactt---cggtctgggctagtagc-tttttgttttaaacccatt-ctacaa
tactgattatactgtggggacgaaagtctctgcttttaactagatagcaactttcagcag
tggatgtctaggctcgcacatcgatgaagaacgctgcgaactgcgatacgtaatgcgaat
tgcaggattcagtgagtcatcgaaattttgaacgcatattgcacttccgggttagtcctg
ggagtatgcctgtatcagtgtccgtacatcaaacttggctttcttccttccgtgtagtcg
gtgga--ggatgtgccagatgtgaagtgtcttgcgggtgtc----cttcgggtc--gtct
gcgagtcctttgaaatgtactgaactgtacttctctttgctcgaaaagcgtggt--gttg
ctggttgtggaggctgcctgcgtggccagtc-ggcgaccggtttgtctgctgcggcgttt
aatggaggagtgttcgattcgcggtatggttggcttcggctgaacaggc-gcttattgta
t-gcttttcctgctgtggcgtgatggg--ctggtgaaccgtagctgtgtgtggcttggct
tttgaat-cggctttgctgttgcgaagtagagtgg-------------------cggctt
cggc------------tgtcgagggt-cgatcca----tttgggaac-tttgtgtgcacc
t
>Phytophthora_citricola_E_112_EU263906 Phytophthora_citricola_E_112_EU263906 895 bp 
ccacacct-aaaaaacttttcacgtgaaccgtatcaacccttttagttgggggtcttgct
-------------------------------------tttttgcgagccctatcatggcg
aatgtttggactt---cggtctgggctagtagc-tttttgttttaaacccatt-ctacaa
tactgattatactgtggggacgaaagtctctgcttttaactagatagcaactttcagcag
tggatgtctaggctcgcacatcgatgaagaacgctgcgaactgcgatacgtaatgcgaat
tgcaggattcagtgagtcatcgaaattttgaacgcatattgcacttccgggttagtcctg
ggagtatgcctgtatcagtgtccgtacatcaaacttggctttcttccttccgtgtagtcg
gtgga--ggatgtgccagatgtgaagtgtcttgcgggtgtc----cttcgggtc--gtct
gcgagtcctttgaaatgtactgaactgtacttctctttgctcgaaaagcgtggt--gttg
ctggttgtggaggctgcctgcgtggccagtc-ggcgaccggtttgtctgctgcagcgttt
aatggaggagtgttcgattcgcggtatggttggcttcggctgaacaggc-gcttattgta
t-gcttttcctgctgtggcgtgatggg--ctggtgaaccgtagctatgtgtggcttggct
tttgaat-cggctttgctgttgcgaagtagagtgg-------------------cggctt
cggc------------tgtcgagggt-cgatcca----tttgggaac-tttgtgtgcacc
t
>Phytophthora_citricola_E_IMI031372_AF266788 Phytophthora_citricola_E_IMI031372_AF266788 895 bp 
ccacacct-aaaaaacttttcacgtgaaccgtatcaacccttttagttgggggtcttgct
-------------------------------------tttttgcgagccctatcatggcg
aatgtttggactt---cggtctgggctagtagc-tttttgttttaaacccatt-ctacaa
tactgattatactgtggggacgaaagtctctgcttttaactagatagcaactttcagcag
tggatgtctaggctcgcacatcgatgaagaacgctgcgaactgcgatacgtaatgcgaat
tgcaggattcagtgagtcatcgaaattttgaacgcatattgcacttccgggttagtcctg
ggagtatgcctgtatcagtgtccgtacatcaaacttggctttcttccttccgtgtagtcg
gtgga--ggatgtgccagatgtgaagtgtcttgcgggtgtc----cttcgggtc--gtct
gcgagtcctttgaaatgtactgaactgtacttctctttgctcgaaaagcgtggt--gttg
ctggttgtggaggctgcctgcgtggccagtc-ggcgaccggtttgtctgctgcagcgttt
aatggaggagtgttcgattcgcggtatggttggcttcggctgaacaggc-gcttattgta
t-gcttttcctgctgtggcgtgatggg--ctggtgaaccgtagctatgtgtggcttggct
tttgaat-cggctttgctgttgcgaagtagagtgg-------------------cggctt
cggc------------tgtcgagggt-cgatcca----tttgggaac-tttgtgtgcacc
t
>Phytophthora_citricola_I_22F3_FJ392321 Phytophthora_citricola_I_22F3_FJ392321 895 bp 
ccacacctaaaaaaacttttcacgtgaaccgtatcaacccttttagttgggggtcttgct
-------------------------------------tttttgcgagccctatcatggcg
aatgtttggactt---cggtctgggctagtagc-tttttgttttaaacccatt-ctacaa
tactgattatactgtggggacgaaagtctctgcttttaactagatagcaactttcagcag
tggatgtctaggctcgcacatcgatgaagaacgctgcgaactgcgatacgtaatgcgaat
tgcaggattcagtgagtcatcgaaattttgaacgcatattgcacttccgggttagtcctg
ggagtatgcctgtatcagtgtccgtacatcaaacttggctttcttccttccgtgtagtcg
gtgga--ggatgtgccagatgtgaagtgtcttgcgggtgtc----cttcgggtc--gtct
gcgagtcctttgaaatgtactgaactgtacttctctttgctcgaaaagcgtggt--gttg
ctggttgtggaggctgcctgcgtggccagtc-ggcgaccggtttgtctgctgcggcgttt
aatggaggagtgttcgattcgcggtatggttggcttcggctgaacaggc-gcttattgta
t-gcttttcctgctgtggcgtgatggg--ctggtgaaccgtagctgtgtgtggcttggct
tttgaat-cggctttgctgttgcgaagtagagtga-------------------cggctt
cggc------------tgtcgagggt-cgatcca----tttgggaac-tttgtgtgcacc
t
>Phytophthora_citricola_I_CBS181_25_FJ392322 Phytophthora_citricola_I_CBS181.25_FJ392322 895 bp 
ccacacctaaaaaaacttttcacgtgaaccgtatcaacccttttagttgggggtcttgct
-------------------------------------tttttgcgagccctatcatggcg
aatgtttggactt---cggtctgggctagtagc-tttttgttttaaacccatt-ctacaa
tactgattatactgtggggacgaaagtctctgcttttaactagatagcaactttcagcag
tggatgtctaggctcgcacatcgatgaagaacgctgcgaactgcgatacgtaatgcgaat
tgcaggattcagtgagtcatcgaaattttgaacgcatattgcacttccgggttagtcctg
ggagtatgcctgtatcagtgtccgtacatcaaacttggctttcttccttccgtgtagtcg
gtgga--ggatgtgccagatgtgaagtgtcttgcgggtgtc----cttcgggtc--gtct
gcgagtcctttgaaatgtactgaactgtacttctctttgctcgaaaagcgtggt--gttg
ctggttgtggaggctgcctgcgtggccagtc-ggcgaccggtttgtctgctgcggcgttt
aatggaggagtgttcgattcgcggtatggttggcttcggctgaacaggc-gcttattgta
t-gcttttcctgctgtggcgtgatggg--ctggtgaaccgtagctatgtgtggcttggct
tttgaat-cggctttgctgttgcgaagtagagtga-------------------cggctt
cggc------------tgtcgagggt-cgatcca----tttgggaac-tttgtgtgcacc
t
>Phytophthora_citricola_I_US1_FJ665234 Phytophthora_citricola_I_US1_FJ665234 895 bp 
ccacacctaaaaaaacttttcacgtgaaccgtatcaacccttttagttgggggtcttgct
-------------------------------------tttttgcgagccctatcatggcg
aatgtttggactt---cggtctgggctagtagc-tttttgttttaaacccatt-ctacaa
tactgattatactgtggggacgaaagtctctgcttttaactagatagcaactttcagcag
tggatgtctaggctcgcacatcgatgaagaacgctgcgaactgcgatacgtaatgcgaat
tgcaggattcagtgagtcatcgaaattttgaacgcatattgcacttccgggttagtcctg
ggagtatgcctgtatcagtgtccgtacatcaaacttggctttcttccttccgtgtagtcg
gtgga--ggatgtgccagatgtgaagtgtcttgcgggtgtc----cttcgggtc--gtct
gcgagtcctttgaaatgtactgaactgtacttctctttgctcgaaaagcgtggt--gttg
ctggttgtggaggctgcctgcgtggccagtc-ggcgaccggtttgtctgctgcggcgttt
aatggaggagtgttcgattcgcggtatggttggcttcggctgaacaggc-gcttattgta
t-gcttttcctgctgtggcgtgatggg--ctggtgaaccgtagctgtgtgtggcttggct
tttgaat-cggctttgctgttgcgaagtagagtga-------------------cggctt
cggc------------tgtcgagggt-cgatcca----tttgggaac-tttgtgtgcacc
t
>Phytophthora_citricola_I_US10_FJ665235 Phytophthora_citricola_I_US10_FJ665235 895 bp 
ccacacctaaaaaaacttttcacgtgaaccgtatcaacccttttagttgggggtcttgct
-------------------------------------tttttgcgagccctatcatggcg
aatgtttggactt---cggtctgggctagtagc-tttttgttttaaacccatt-ctacaa
tactgattatactgtggggacgaaagtctctgcttttaactagatagcaactttcagcag
tggatgtctaggctcgcacatcgatgaagaacgctgcgaactgcgatacgtaatgcgaat
tgcaggattcagtgagtcatcgaaattttgaacgcatattgcacttccgggttagtcctg
ggagtatgcctgtatcagtgtccgtacatcaaacttggctttcttccttccgtgtagtcg
gtgga--ggatgtgccagatgtgaagtgtcttgcgggtgtc----cttcgggtc--gtct
gcgagtcctttgaaatgtactgaactgtacttctctttgctcgaaaagcgtggt--gttg
ctggttgtggaggctgcctgcgtggccagtc-ggcgaccggtttgtctgctgcggcgttt
aatggaggagtgttcgattcgcggtatggttggcttcggctgaacaggc-gcttattgta
t-gcttttcctgctgtggcgtgatggg--ctggtgaaccgtagctgtgtgtggcttggct
tttgaat-cggctttgctgttgcgaagtagagtga-------------------cggctt
cggc------------tgtcgagggt-cgatcca----tttgggaac-tttgtgtgcacc
t
>Phytophthora_citricola_II_22F2_FJ392324 Phytophthora_citricola_II_22F2_FJ392324 895 bp 
ccacacct-aaaaaacttttcacgtgaaccgtatcaacccttttagttgggggtcttgct
t------------------------------------tttttgcgagccctatcatggcg
aatgtttggactt---cggtctgggctagtagc-tttttgttttaaacccatt-ctacaa
tactgattatactgcggggacgaaagtctctgcttttaactagatagcaactttcagcag
tggatgtctaggctcgcacatcgatgaagaacgctgcgaactgcgatacgtaatgcgaat
tgcaggattcagtgagtcatcgaaattttgaacgcatattgcacttccgggttagtcctg
ggagtatgcctgtatcagtgtccgtacatcaaacttggctttcttccttccgtgtagtcg
gtgga--ggatgtgccagacgtgaagtgtcttgcgggtgtc----cttcgggtc--gtct
gcgagtcctttgaaatgtactgaactgtacttctctttgctcgaaaagcgtggt--gttg
ctggttgtggaggctgcctgcgtggccagtc-ggcgaccggtttgtctgctgcggcgttt
aatggaggagtgttcgattcgcggtatggttggcttcggctgaacaggc-gcttattgta
t-gcttttcctgctgtggcgtgatggg--ctggtgaaccgtagctgtgtgtggcttggct
tttgaat-cggctttgctgttgcgaagtagagtgg-------------------cggctt
cggc------------tgtcgagggt-cgatcca----tttgggaac-tttgtgtgcacc
t
>Phytophthora_citricola_II_CBS379_61_FJ392325 Phytophthora_citricola_II_CBS379.61_FJ392325 895 bp 
ccacacct-aaaaaacttttcacgtgaaccgtatcaacccttttagttgggggtcttgct
t------------------------------------tttttgcgagccctatcatggcg
aatgtttggactt---cggtctgggctagtagc-tttttgttttaaacccatt-ctacaa
tactgattatactgcggggacgaaagtctctgcttttaactagatagcaactttcagcag
tggatgtctaggctcgcacatcgatgaagaacgctgcgaactgcgatacgtaatgcgaat
tgcaggattcagtgagtcatcgaaattttgaacgcatattgcacttccgggttagtcctg
ggagtatgcctgtatcagtgtccgtacatcaaacttggctttcttccttccgtgtagtcg
gtgga--ggatgtgccagacgtgaagtgtcttgcgggtgtc----cttcgggtc--gtct
gcgagtcctttgaaatgtactgaactgtacttctctttgctcgaaaagcgtggt--gttg
ctggttgtggaggctgcctgcgtggccagtc-ggcgaccggtttgtctgctgcggcgttt
aatggaggagtgttcgattcgcggtatggttggcttcggctgaacaggc-gcttattgta
t-gcttttcctgctgtggcgtgatggg--ctggtgaaccgtagctgtgtgtggcttggct
tttgaat-cggctttgctgttgcgaagtagagtgg-------------------cggctt
cggc------------tgtcgagggt-cgatcca----tttgggaac-tttgtgtgcacc
t
>Phytophthora_citricola_III_15C9_FJ392327 Phytophthora_citricola_III_15C9_FJ392327 895 bp 
ccacacct-aaaaaacttttcacgtgaaccgtatcaacccttttagttgggggtcttgct
-------------------------------------tttttgcgagccctatcatggcg
aatgtttggactt---cggtctgggctagtagc-tttttgttttaaacccatt-ctacaa
tactgattatactgtggggacgaaagtctctgcttttaactagatagcaactttcagcag
tggatgtctaggctcgcacatcgatgaagaacgctgcgaactgcgatacgtaatgcgaat
tgcaggattcagtgagtcatcgaaattttgaacgcatattgcacttccgggttagtcctg
ggagtatgcctgtatcagtgtccgtacatcaaacttggctttcttccttccgtgtagtcg
gtgga--ggatgtgccagatgtgaagtgtcttgcgggtgtc----cttcgggtc--gtct
gcgagtcctttgaaatgtactgaactgtacttctctttgctcgaaaagcgtggt--gttg
ctggttgtggaggctgcctgcgtggccagtc-ggcgaccggtttgtctgctgcggcgttt
aatggaggagtgttcgattcgcggtatggttggcttcggctgaacaggc-gcttattgta
t-gcttttcctgctgtggcgtgatggg--ctggtgaaccgtagctgtgtgtggcttggct
tttgaat-cggctttgctgttgcgaagtagagtga-------------------cggctt
cggc------------tgtcgagggt-cgatcca----tttgggaac-tttgtgtgcacc
t
>Phytophthora_citricola_III_1E1_FJ392326 Phytophthora_citricola_III_1E1_FJ392326 895 bp 
ccacacct-aaaaaacttttcacgtgaaccgtatcaacccttttagttgggggtcttgc-
-------------------------------------tttttgcgagccctatcatggcg
aatgtttggactt---cggtctgggctagtagc-tttttgttttaaacccatt-ctacaa
tactgattatactgtggggacgaaagtctctgcttttaactagatagcaactttcagcag
tggatgtctaggctcgcacatcgatgaagaacgctgcgaactgcgatacgtaatgcgaat
tgcaggattcagtgagtcatcgaaattttgaacgcatattgcacttccgggttagtcctg
ggagtatgcctgtatcagtgtccgtacatcaaacttggctttcttccttccgtgtagtcg
gtgga--ggatgtgccagatgtgaagtgtcttgcgggtgtc----cttcgggtc--gtct
gcgagtcctttgaaatgtactgaactgtacttctctttgctcgaaaagcgtggt--gttg
ctggttgtggaggctgcctgcgtggccagtc-ggcgaccggtttgtctgctgcggcgttt
aatggaggagtgttcgattcgcggtatggttggcttcggctgaacaggc-gcttattgta
t-gcttttcctgctgtggcgtgatggg--ctggtgaaccgtagctgtgtgtggcttggct
tttgaat-cggctttgctgttgcgaagtagagtga-------------------cggctt
cggc------------tgtcgagggt-cgatcca----tttgggaac-tttgtgtgcacc
t
>Phytophthora_citricola_III_EF032477 Phytophthora_citricola_III_EF032477 895 bp 
ccacacct-aaaaaacttttcacgtgaaccgtatcaacccttttagttgggggtcttgct
-------------------------------------tttttgcgagccctatcatggcg
aatgtttggactt---cggtctgggctagtagc-tttttgttttaaacccatt-ctacaa
tactgattatactgtggggacgaaagtctctgcttttaactagatagcaactttcagcag
tggatgtctaggctcgcacatcgatgaagaacgctgcgaactgcgatacgtaatgcgaat
tgcaggattcagtgagtcatcgaaattttgaacgcatattgcacttccgggttagtcctg
ggagtatgcctgtatcagtgtccgtacatcaaacttggctttcttccttccgtgtagtcg
gtgga--ggatgtgccagatgtgaagtgtcttgcgggtgtc----cttcgggtc--gtct
gcgagtcctttgaaatgtactgaactgtacttctctttgctcgaaaagcgtggt--gttg
ctggttgtggaggctgcctgcgtggccagtc-ggcgaccggtttgtctgctgcggcgttt
aatggaggagtgttcgattcgcggtatggttggcttcggctgaacaggc-gcttattgta
t-gcttttcctgctgtggcgtgatggg--ctggtgaaccgtagctgtgtgtggcttggct
tttgaat-cggctttgctgttgcgaagtagagtga-------------------cggctt
cggc------------tgtcgagggt-cgatcca----tttgggaac-tttgtgtgcacc
t
>Phytophthora_citricola_III_P11835_2_DQ648146 Phytophthora_citricola_III_P11835.2_DQ648146 895 bp 
ccacacct-aaaaaacttttcacgtgaaccgtatcaacccttttagttgggggtcttgct
-------------------------------------tttttgcgagccctatcatggcg
aatgtttggactt---cggtctgggctagtagc-tttttgttttaaacccatt-ctacaa
tactgattatactgtggggacgaaagtctctgcttttaactagatagcaactttcagcag
tggatgtctaggctcgcacatcgatgaagaacgctgcgaactgcgatacgtaatgcgaat
tgcaggattcagtgagtcatcgaaattttgaacgcatattgcacttccgggttagtcctg
ggagtatgcctgtatcagtgtccgtacatcaaacttggctttcttccttccgtgtagtcg
gtgga--ggatgtgccagatgtgaagtgtcttgcgggtgtc----cttcgggtc--gtct
gcgagtcctttgaaatgtactgaactgtacttctctttgctcgaaaagcgtggt--gttg
ctggttgtggaggctgcctgcgtggccagtc-ggcgaccggtttgtctgctgcggcgttt
aatggaggagtgttcgattcgcggtatggttggcttcggctgaacaggc-gcttattgta
t-gcttttcctgctgtggcgtgatggg--ctggtgaaccgtagctgtgtgtggcttggct
tttgaat-cggctttgctgttgcgaagtagagtga-------------------cggctt
cggc------------tgtcgagggt-cgatcca----tttgggaac-tttgtgtgcacc
t
>Phytophthora_citricola_IV_15C7_FJ392328 Phytophthora_citricola_IV_15C7_FJ392328 895 bp 
ccacacct-aaaaaactttccacgtgaaccgtatcaaac--tttagttgggggtcttttt
cggcgacggctgctggcttcattgctggcggctgctgttggat-gagccctatcatggcg
agcgtttgggctt---cggtctgaactagtagc-----ttttttaaacccatt-ctttat
tactgattatactgtggggacgaaagtctctgcttttaactagatagcaactttcagcag
tggatgtctaggctcgcacatcgatgaagaacgctgcgaactgcgatacgtaatgcgaat
tgcaggattcagtgagtcatcgaaattttgaacgcatattgcacttccgggttagtcctg
ggagtatgcctgtatcagtgtccgtacatcaaacttggctttcttccttccgtgtagtcg
gtgga--ggatgtgccagatgtgaagtgtcttgcggctggt----cttcgggtc--ggct
gtgagtcctttgaaatgtactgaactgtacttctctttgctcgaaaagcgtggc--gttg
ctgattgtggaggctgcctgcgtagccagtctggcgaccagtttgtctgctgtggcg-tt
aatggaggagtgttcgattcgcggtatggttggcttcggctgaacagac-gcttattgaa
t-gtttttcctgctgtggcggtacggg--ttggtgaaccgtagctatgtg-ggcttggct
tttgaat-tggctttgctgttgcgaagtagagtgg-------------------cagctt
cggc------------tgtcgagggt-cgatcca----tttgggaat--ttgtgtgtact
t
>Phytophthora_citricola_IV_15C8_FJ392329 Phytophthora_citricola_IV_15C8_FJ392329 895 bp 
ccacacct-aaaaaactttccacgtgaaccgtatcaaac--tttagttgggggtcttttt
cggcgacggctgctggcttcattgctggcggctgctgttggat-gagccctatcatggcg
agcgtttgggctt---cggtctgaactagtagc-----ttttttaaacccatt-ctttat
tactgattatactgtggggacgaaagtctctgcttttaactagatagcaactttcagcag
tggatgtctaggctcgcacatcgatgaagaacgctgcgaactgcgatacgtaatgcgaat
tgcaggattcagtgagtcatcgaaattttgaacgcatattgcacttccgggttagtcctg
ggagtatgcctgtatcagtgtccgtacatcaaacttggctttcttccttccgtgtagtcg
gtgga--ggatgtgccagatgtgaagtgtcttgcggctggt----cttcgggtc--ggct
gtgagtcctttgaaatgtactgaactgtacttctctttgctcgaaaagcgtggc--gttg
ctgattgtggaggctgcctgcgtagccagtctggcgaccagtttgtctgctgtggcg-tt
aatggaggagtgttcgattcgcggtatggttggcttcggctgaacagac-gcttattgaa
t-gtttttcctgctgtggcggtacggg--ttggtgaaccgtagctatgtg-ggcttggct
tttgaat-tggctttgctgttgcgaagtagagtgg-------------------cagctt
cggc------------tgtcgagggt-cgatcca----tttgggaat--ttgtgtgtact
t
>Phytophthora_citrophthora_CMW20198_DQ988188 Phytophthora_citrophthora_CMW20198_DQ988188 895 bp 
ccacacct-aaaaaactttccacgtgaaccgtatcaacccttttagttgggggtgttgct
tggca---------------------------tttagctgagccgcgccctatcatggcg
aatgtttggactt---cggtctgggctagtagcttttttgttttaaa-ccatt-taacaa
tactgattatactgtggggacgaaagtctctgcttttaactagatagcaactttcagcag
tggatgtctaggctcgcacatcgatgaagaacgctgcgaactgcgatacgtaatgcgaat
tgcaggattcagtgagtcatcgaaattttgaacgcatattgcacttccgggttagtcctg
ggagtatgcctgtatcagtgtccgtacatcaaacttggctttcttccttccgtgtagtcg
gtgga--ggatgtgccagatgtgaagtgtcttgcggtttgtgtgccttcgggccgaggct
gcgagtcctttgaaatgtactgaactgtacttctctttgctcgaaaagcgtggt--gttg
ctggttgtggaggctgcctgcgtggccagtc-ggcgaccggtttgtctgctgcggcgttt
aatggaggagtgttcgattcgcggtatggttggcttcggctgaacaggc-gcttattgta
t-gcttttcctgctgtggcgtgatggg--ctggtgaaccgtagctgtgtgtggcttggct
tttgaat-cggctttgctgttgcgaagtagagtgg-------------------cggctt
cggc------------tgtcgagtgt-cgatcca---ttttgggaacgtttgtgtgcgct
t
>Phytophthora_citrophthora_IMI332632_AF266785 Phytophthora_citrophthora_IMI332632_AF266785 895 bp 
ccacacct-aaaaaactttccacgtgaaccgtatcaacccttttagttgggggtgttgct
tggcg--------------------------tttttgctgagccacgccctatcatggcg
aatgtttggactt---cggtctgggctagtagcttttttgttttaaacccatt-taacaa
tactgattatactgtggggacgaaagtctctgcttttaactagatagcaactttcagcag
tggatgtctaggctcgcacatcgatgaagaacgctgcgaactgcgatacgtaatgcgaat
tgcaggattcagtgagtcatcgaaattttgaacgcatattgcacttccgggttagtcctg
ggagtatgcctgtatcagtgtccgtacatcaaacttggctttcttccttccgtgtagtcg
gtgga--ggatgtgccagatgtgaagtgtcttgcggtttttgtgccttcgggccgtggct
gcgagtcctttgaaatgtactgaactgtacttctctttgctcgaaaagcgtggt--gttg
ctggttgtggaggctgcctgcgtggccagtc-ggcgaccggtttgtctgctgcggcgttt
aatggaggagtgttcgattcgcggtatggttggcttcggctgaacaggc-gcttattgta
t-gcttttcctgctgtggcgtgatggg--ctggtgaaccgtagctgtgtgtggcttggct
tttgaat-cggctttgctgttgcgaagtagagtgg-------------------cggctt
cggc------------tgtcgagtgt-cgatcca---ttttgggaacgtttgtgtgcgct
t
>Phytophthora_colocasiae_9177_AY251657 Phytophthora_colocasiae_9177_AY251657 895 bp 
ccacacct-aaaaaactttccacgtgaaccgtatcaacccttttagttgggggtgttgct
tggca---------------------------ttttgctgag--gcgccctatcatggcg
aatgtttggactt---cggtctgggctagtagc-tttttgttttaaa-ccctt-taacaa
tactgattatactgtggggacgaaagtctctgcttttaactagatagcaactttcagcag
tggatgtctaggctcgcacatcgatgaagaacgctgcgaactgcgatacgtaatgcgaat
tgcaggattcagtgagtcatcgaaattttgaacgcatattgcacttccgggttagtcctg
ggagtatgcctgtatcagtgtccgtacatcaaacttggctttcttccttccgtgtagtcg
gtgga--ggatgtgccagatgtgaagtgtcttgcggtttgtgtgccttcgggccgaggct
gcgagtcctttgaaatgtactgaactgtacttctctttgctcgaaaagcgtggt--gatg
ctggttgtggaggctgcctgcgtggccagtc-ggcgaccggtttgtctgctgcggcgttt
aatggaggagtgttcgattcgcggtatggttggcttcggctgaacagac-gcttattgta
t-gcttttcctgctgtggcgtgatggg--ctggtgaaccgtagctgtgtgtggcttggct
tttgaat-cggttttgctgttgcgaagtagagtgg-------------------cggctt
cggc------------tgtcgagtgt-cgatcca---ttttgggaacttttgtgtgcgct
t
>Phytophthora_colocasiae_IMI368918_AF266786 Phytophthora_colocasiae_IMI368918_AF266786 895 bp 
ccacacct-aaaaaactttccacgtgaaccgtatcaacccttttagttgggggtgttgct
tggca---------------------------ttttgctgag--gcgccctatcatggcg
aatgtttggactt---cggtctgggctagtagc-tttttgttttaaa-ccctt-taacaa
tactgattatactgtggggacgaaagtctctgcttttaactagatagcaactttcagcag
tggatgtctaggctcgcacatcgatgaagaacgctgcgaactgcgatacgtaatgcgaat
tgcaggattcagtgagtcatcgaaattttgaacgcatattgcacttccgggttagtcctg
ggagtatgcctgtatcagtgtccgtacatcaaacttggctttcttccttccgtgtagtcg
gtgga--ggatgtgccagatgtgaagtgtcttgcggtttgtgtgccttcgggccgaggct
gcgagtcctttgaaatgtactgaactgtacttctctttgctcgaaaagcgtggt--gatg
ctggttgtggaggctgcctgcgtggccagtc-ggcgaccggtttgtctgctgcggcgttt
aatggaggagtgttcgattcgcggtatggttggcttcggctgaacagac-gcttattgta
t-gcttttcctgctgtggcgtgatggg--ctggtgaaccgtagctgtgtgtggcttggct
tttgaat-cggctttgctgttgcgaagtagagtgg-------------------cggctt
cggc------------tgtcgagtgt-cgatcca---ttttgggaacttttgtgtgcgct
t
>Phytophthora_cryptogea_CRP235_AY659443 Phytophthora_cryptogea_CRP235_AY659443 895 bp 
ccacacct-aaaaaactttccacgtgaaccgtatcaacctttttaaattgggggctcccg
t-----------ctggccggccggttttcggctggctgggtgg-cggctctatcatggcg
accgcttgggcct---cggcctgggctagtagc--gtattttttaaacccatt-cctaat
tactgaatatactgtggggacgaaagtctctgcttttaactagatagcaactttcagcag
tggatgtctaggctcgcacatcgatgaagaacgctgcgaactgcgatacgtaatgcgaat
tgcaggattcagtgagtcatcgaaattttgaacgcatattgcacttccgggttagtcctg
ggagtatgcctgtatcagtgtccgtacactaaacttggctcccttccttccgtgtagtcg
gtggatggggacgcgcagatgtgaagtgtcttgcggctggt----cttcggtcc--ggct
gcgagtcctttgaaatgtactacactgtacttctctttgctcgaaaagcgtgac--gttg
ctggttgtggaggctgcctgtgtggcatgtc-ggcgaccggtttgtctgctgcggcgttt
aatggaggagtgttcgattcgcggtatgattggcttcggctgaacagac-gcttattggg
t-gcttttcctgctgtggctggatgga--ctggtgaaccgtagctgtgctaggcttggcg
tttgaac-cggcggtg-tggtgcgaagtagggtgt-------------------ctgttc
cggcgcaagctggggtggacgagggt-cgatcca----tttgggaaacgttgtgtgcgct
t
>Phytophthora_fallax_NZFS446_DQ297397 Phytophthora_fallax_NZFS446_DQ297397 895 bp 
ccacaccttaaaaaa--ttccacgtgaactgtattgtcaaccaaattcggggattccttg
ctagcgtgccttcgggcg--------------tgccggtaggttgagacccatcaaacga
aaacatcgg--ctgaaaggtcggagccagtagt--tacctttgtaaacccttt-actaaa
tactga-aaaactgtggggacgaaagtccttgctttt-actagatagcaactttcagcag
tggatgtctaggctcgcacatcgatgaagaacgctgcgaactgcgatacgtaatgcgaat
tgcaggattcagtgagtcatcgaaattttgaacgcatattgcacttccgggttatgcctg
gaagtatgcctgtatcagtgtccgtatatcaaacttgccttccttccttccgtgtagtcg
gtggatgggaacgtgcagatgtgaagtgtcttggcggcgtc----gcttcggcggtgctg
gcgagtccttttaaatacaagatactgttcttctctttgctcgaaaagcgtgtg--ggat
gtggttgtggaggctgcctgcgtggccagtc-ggcgactgattt-cgtgctgagacg---
-gtggggaggggcttgattcgcggtatggttggcttcggctgaacttct-gcttattggg
c-ttctttcatgtcttggcgtatgcgatttcggtgtaccgtagctgtgtgtggcttggct
tttgaac-cgtgttctgtg-tgcgaagtagagtgggcatgtggttttcggactgcgt---
----------------ggccgaggggacgagacc---ttttgggaaattgtgctgctact
t
>Phytophthora_multivora_CBS124094_FJ237517 Phytophthora_multivora_CBS124094_FJ237517 895 bp 
ccacacctaaaaaaactttccacgtgaaccgtatcaaccctttcagttgggggccttgct
-------------------------------------tttttgcgagccctatcatggcg
aatgtttggactt---cggtctgggctagtagc-tttttgttttaaacccatt-ctacaa
tactgattatactgtggggacgaaagtctctgcttttaactagatagcaactttcagcag
tggatgtctaggctcgcacatcgatgaagaacgctgcgaactgcgatacgtaatgcgaat
tgcaggattcagtgagtcatcgaaattttgaacgcatattgcacttccgggttagtcctg
ggagtatgcctgtatcagtgtccgtacatcaaacttggctttcttccttccgtgtagtcg
gtgga--ggatgtgccagatgtgaagtgtcttgcaggtgtc----cttcgggtc--gtct
gcgagtcctttgaaatgtactgaactgtacttctctttgctcgaaaagcgtggc--gttg
ctggttgtggaggctgcctgcgtggccagtc-ggcgaccggtttgtctgctgcggcgttt
aatggaggagtgttcgattcgcggtatggttggcttcggctgaacaggc-gcttattgta
t-gcttttcctgctgtggcgtgatgga--ctggtgaaccgtagctgtgtgtggcttggct
tttgaat-cggctttgctgttgcgaagtagagtgg-------------------cggctc
cggc------------tgtcgagggt-cgatcca----tttgggaac-tttgtgtgcacc
t
>Phytophthora_multivora_CBS124095_FJ237521 Phytophthora_multivora_CBS124095_FJ237521 895 bp 
ccacacctaaaaaaactttccacgtgaaccgtatcaaccctttcagttgggggccttgct
-------------------------------------tttttgcgagccctatcatggcg
aatgtttggactt---cggtctgggctagtagc-tttttgttttaaacccatt-ctacaa
tactgattatactgtggggacgaaagtctctgcttttaactagatagcaactttcagcag
tggatgtctaggctcgcacatcgatgaagaacgctgcgaactgcgatacgtaatgcgaat
tgcaggattcagtgagtcatcgaaattttgaacgcatattgcacttccgggttagtcctg
ggagtatgcctgtatcagtgtccgtacatcaaacttggctttcttccttccgtgtagtcg
gtgga--ggatgtgccagatgtgaagtgtcttgcaggtgtc----cttcgggtc--gtct
gcgagtcctttgaaatgtactgaactgtacttctctttgctcgaaaagcgtggc--gttg
ctggttgtggaggctgcctgcgtggccagtc-ggcgaccggtttgtctgctgcggcgttt
aatggaggagtgttcgattcgcggtatggttggcttcggctgaacaggc-gcttattgta
t-gcttttcctgctgtggcgtgatgga--ctggtgaaccgtagctgtgtgtggcttggct
tttgaat-cggctttgctgttgcgaagtagagtgg-------------------cggctc
cggc------------tgtcgagggt-cgatcca----tttgggaac-tttgtgtgcacc
t
>Phytophthora_multivora_P1817_AB367494 Phytophthora_multivora_P1817_AB367494 895 bp 
ccacacct-aaaaaactttccacgtgaaccgtatcaaccctttcagttgggggccttgct
-------------------------------------tttttgcgagccctatcatggcg
aatgtttggactt---cggtctgggctagtagc-tttttgttttaaacccatt-ctacaa
tactgattatactgtggggacgaaagtctctgcttttaactagatagcaactttcagcag
tggatgtctaggctcgcacatcgatgaagaacgctgcgaactgcgatacgtaatgcgaat
tgcaggattcagtgagtcatcgaaattttgaacgcatattgcacttccgggttagtcctg
ggagtatgcctgtatcagtgtccgtacatcaaacttggctttcttccttccgtgtagtcg
gtgga--ggatgtgccagatgtgaagtgtcttgcaggtgtc----cttcgggtc--gtct
gcgagtcctttgaaatgtactgaactgtacttctctttgctcgaaaagcgtggc--gttg
ctggttgtggaggctgcctgcgtggccagtc-ggcgaccggtttgtctgctgcggcgttt
aatggaggagtgttcgattcgcggtatggttggcttcggctgaacaggc-gcttattgta
t-gcttttcctgctgtggcgtgacgga--ctggtgaaccgtagctgtgtgtggcttggct
tttgaat-cggctttgctgttgcgaagtagagtgg-------------------cggctc
cggc------------tgtcgagggt-cgatcca----tttgggaac-tttgtgtgcacc
t
>Phytophthora_multivora_VHS16168_FJ237513 Phytophthora_multivora_VHS16168_FJ237513 895 bp 
ccacacct-aaaaaactttccacgtgaaccgtatcaaccctttcagttgggggccttgct
-------------------------------------tttttgcgagccctatcatggcg
aatgtttggactt---cggtctgggctagtagc-tttttgttttaaacccatt-ctacaa
tactgattatactgtggggacgaaagtctctgcttttaactagatagcaactttcagcag
tggatgtctaggctcgcacatcgatgaagaacgctgcgaactgcgatacgtaatgcgaat
tgcaggattcagtgagtcatcgaaattttgaacgcatattgcacttccgggttagtcctg
ggagtatgcctgtatcagtgtccgtacatcaaacttggctttcttccttccgtgtagtcg
gtgga--ggatgtgccagatgtgaagtgtcttgcaggtgtc----cttcgggtc--gtct
gcgagtcctttgaaatgtactgaactgtacttctctttgctcgaaaagcgtggc--gttg
ctggttgtggaggctgcctgcgtggccagtc-ggcgaccggtttgtctgctgcggcgttt
aatggaggagtgttcgattcgcggtatggttggcttcggctgaacaggc-gcttattgta
t-gcttttcctgctgtggcgtgatgga--ctggtgaaccgtagctgtgtgtggcttggct
tttgaat-cggctttgctgttgcgaagtagagtgg-------------------cggctc
cggc------------tgtcgagggt-cgatcca----tttgggaac-tttgtgtgcacc
t
>Phytophthora_multivora_VHS16439_FJ237516 Phytophthora_multivora_VHS16439_FJ237516 895 bp 
ccacacctaaaaaaactttccacgtgaaccgtatcaaccctttcagttgggggccttgct
-------------------------------------tttttgcgagccctatcatggcg
aatgtttggactt---cggtctgggctagtagc-tttttgttttaaacccatt-ctacaa
tactgattatactgtggggacgaaagtctctgcttttaactagatagcaactttcagcag
tggatgtctaggctcgcacatcgatgaagaacgctgcgaactgcgatacgtaatgcgaat
tgcaggattcagtgagtcatcgaaattttgaacgcatattgcacttccgggttagtcctg
ggagtatgcctgtatcagtgtccgtacatcaaacttggctttcttccttccgtgtagtcg
gtgga--ggatgtgccagatgtgaagtgtcttgcaggtgtc----cttcgggtc--gtct
gcgagtcctttgaaatgtactgaactgtacttctctttgctcgaaaagcgtggc--gttg
ctggttgtggaggctgcctgcgtggccagtc-ggcgaccggtttgtctgctgcggcgttt
aatggaggagtgttcgattcgcggtatggttggcttcggctgaacaggc-gcttattgta
t-gcttttcctgctgtggcgtgatgga--ctggtgaaccgtagctgtgtgtggcttggct
tttgaat-cggctttgctgttgcgaagtagagtgg-------------------cggctc
cggc------------tgtcgagggt-cgatcca----tttgggaac-tttgtgtgcacc
t
>Phytophthora_multivora_WAC13200_FJ237522 Phytophthora_multivora_WAC13200_FJ237522 895 bp 
ccacacctaaaaaaactttccacgtgaaccgtatcaaccctttcagttgggggccttgct
-------------------------------------tttttgcgagccctatcatggcg
aatgtttggactt---cggtctgggctagtagc-tttttgttttaaacccatt-ctacaa
tactgattatactgtggggacgaaagtctctgcttttaactagatagcaactttcagcag
tggatgtctaggctcgcacatcgatgaagaacgctgcgaactgcgatacgtaatgcgaat
tgcaggattcagtgagtcatcgaaattttgaacgcatattgcacttccgggttagtcctg
ggagtatgcctgtatcagtgtccgtacatcaaacttggctttcttccttccgtgtagtcg
gtgga--ggatgtgccagatgtgaagtgtcttgcaggtgtc----cttcgggtc--gtct
gcgagtcctttgaaatgtactgaactgtacttctctttgctcgaaaagcgtggc--gttg
ctggttgtggaggctgcctgcgtggccagtc-ggcgaccggtttgtctgctgcggcgttt
aatggaggagtgttcgattcgcggtatggttggcttcggctgaacaggc-gcttattgta
t-gcttttcctgctgtggcgtgatgga--ctggtgaaccgtagctgtgtgtggcttggct
tttgaat-cggctttgctgttgcgaagtagagtgg-------------------cggctc
cggc------------tgtcgagggt-cgatcca----tttgggaac-tttgtgtgcacc
t
>Phytophthora_multivora_WAC13204_FJ237518 Phytophthora_multivora_WAC13204_FJ237518 895 bp 
ccacacctaaaaaaactttccacgtgaaccgtatcaaccctttcagttgggggccttgct
-------------------------------------tttttgcgagccctatcatggcg
aatgtttggactt---cggtctgggctagtagc-tttttgttttaaacccatt-ctacaa
tactgattatactgtggggacgaaagtctctgcttttaactagatagcaactttcagcag
tggatgtctaggctcgcacatcgatgaagaacgctgcgaactgcgatacgtaatgcgaat
tgcaggattcagtgagtcatcgaaattttgaacgcatattgcacttccgggttagtcctg
ggagtatgcctgtatcagtgtccgtacatcaaacttggctttcttccttccgtgtagtcg
gtgga--ggatgtgccagatgtgaagtgtcttgcaggtgtc----cttcgggtc--gtct
gcgagtcctttgaaatgtactgaactgtacttctctttgctcgaaaagcgtggc--gttg
ctggttgtggaggctgcctgcgtggccagtc-ggcgaccggtttgtctgctgcggcgttt
aatggaggagtgttcgattcgcggtatggttggcttcggctgaacaggc-gcttattgta
t-gcttttcctgctgtggcgtgatgga--ctggtgaaccgtagctgtgtgtggcttggct
tttgaat-cggctttgctgttgcgaagtagagtgg-------------------cggctc
cggc------------tgtcgagggt-cgatcca----tttgggaac-tttgtgtgcacc
t
>Phytophthora_palmivora_TARS8_DQ987922 Phytophthora_palmivora_TARS8_DQ987922 895 bp 
ccacacct--aaaaactttccacgtgaaccgtatcaaaa--cttagttgggggtctcttt
cggcggcggctgctggcttcattgctggcggctgctgttggga-gagctctatcatggcg
agcgtttgggctt---cggtctgaactagtagc-----ttttttaaacccatt-ctttat
aactgattatactgtagggacgaaagtctctgcttttaactagatagcaactttcagcag
tggatgtctaggctcgcacatcgatgaagaacgctgcgaactgcgatacgtaatgcgaat
tgcaggattcagtgagtcatcgaaattttgaacgcatattgcacttccgggttagtcctg
ggagtatgcctgtatcagtgtccgtacatcaaacttggttttcttccttccgtgtagtcg
gtggt--ggatgtgccagatgtgaagtgtcttgcggctggt----cttcggatc--ggct
gtgagtcctttgaaatgtactgaactgtacttctctttgctccaaaagcgtggc--gttg
ctgattgtggaggctgcttgcgtagccagtctggcgaccagtttgtctgctgtggcg-tt
aatggaggagtgttcgattcgcggtatggttggcttcggctgaacagac-gcttattgaa
t-atttcttcagctgtggtggtat-ga--ttggtgaaccgtagctatgtg-agcttggct
tttgaat-tggctttgctgttgcgaagtagagtgg-------------------cggctt
cggc------------tgtcgagggt-cgatcca----tttgggaac--ttgtgtatgct
t
>Phytophthora_palmivora_UQ1294_AF266780 Phytophthora_palmivora_UQ1294_AF266780 895 bp 
ccacacct-aaaaaactttccacgtgaaccgtatcaaaa--cttatttgggggtctcttt
cggcggcggctgctggcttcattgctggcggctgctgttggga-gagctctatcatggcg
agcgtttgggctt---cggtctgaactagtagc-----ttttttaaacccatt-ctttat
aactgattatactgtagggacgaaagtctctgcttttaactagatagcaactttcagcag
tggatgtctaggctcgcacatcgatgaagaacgctgcgaactgcgatacgtaatgcgaat
tgcaggattcagtgagtcatcgaaattttgaacgcatattgcacttccgggttagtcctg
ggagtatgcctgtatcagtgtccgtacatcaaacttggttttcttccttccgtgtagtcg
gtggt--ggatgtgccagatgtgaagtgtcttgcggctggt----cttcggatc--ggct
gtgagtcctttgaaatgtactgaactgtacttctctttgctccaaaagcgtggc--gttg
ctgattgtggaggctgcttgcgtagccagtctggcgaccagtttgtctgctgtggcg-tt
aatggaggagtgttcgattcgcggtatggttggcttcggctgaacagac-gcttattgaa
t-atttcttcagctgtggtggtat-ga--ttggtgaaccgtagctatgtg-agcttggct
tttgaat-tggctttgctgttgcgaagtagagtgg-------------------cggctt
cggc------------tgtcgagggt-cgatcca----tttgggaac--ttgtgtatgct
t
>Phytophthora_plurivora_CBS124087_FJ665226 Phytophthora_plurivora_CBS124087_FJ665226 895 bp 
ccacacct-aaaaaacttttcacgtgaaccgtatcaacccttttagttgggggtcttgct
t------------------------------------tttttgcgagccctatcatggcg
aatgtttggactt---cggtctgggctagtagc-tttttgttttaaacccatt-ctacaa
tactgattatactgcggggacgaaagtctctgcttttaactagatagcaactttcagcag
tggatgtctaggctcgcacatcgatgaagaacgctgcgaactgcgatacgtaatgcgaat
tgcaggattcagtgagtcatcgaaattttgaacgcatattgcacttccgggttagtcctg
ggagtatgcctgtatcagtgtccgtacatcaaacttggctttcttccttccgtgtagtcg
gtgga--ggatgtgccagacgtgaagtgtcttgcgggtgtc----cttcgggtc--gtct
gcgagtcctttgaaatgtactgaactgtacttctctttgctcgaaaagcgtggt--gttg
ctggttgtggaggctgcctgcgtggccagtc-ggcgaccggtttgtctgctgcggcgttt
aatggaggagtgttcgattcgcggtatggttggcttcggctgaacaggc-gcttattgta
t-gcttttcctgctgtggcgtgatggg--ctggtgaaccgtagctgtgtgtggcttggct
tttgaat-cggctttgctgttgcgaagtagagtgg-------------------cggctt
cggc------------tgtcgagggt-cgatcca----tttgggaac-tttgtgtgcacc
t
>Phytophthora_plurivora_CBS124089_FJ665227 Phytophthora_plurivora_CBS124089_FJ665227 895 bp 
ccacacct-aaaaaacttttcacgtgaaccgtatcaacccttttagttgggggtcttgct
t------------------------------------tttttgcgagccctatcatggcg
aatgtttggactt---cggtctgggctagtagc-tttttgttttaaacccatt-ctacaa
tactgattatactgcggggacgaaagtctctgcttttaactagatagcaactttcagcag
tggatgtctaggctcgcacatcgatgaagaacgctgcgaactgcgatacgtaatgcgaat
tgcaggattcagtgagtcatcgaaattttgaacgcatattgcacttccgggttagtcctg
ggagtatgcctgtatcagtgtccgtacatcatacttggctttcttccttccgtgtagtcg
gtgga--ggatgtgccagacgtgaagtgtcttgcgggtgtc----cttcgggtc--gtct
gcgagtcctttgaaatgtactgaactgtacttctctttgctcgaaaagcgtggt--gttg
ctggttgtggaggctgcctgcgtggccagtc-ggcgaccggtttgtctgctgcggcgttt
aatggaggagtgttcgattcgcggtatggttggcttcggctgaacaggc-gcttattgta
t-gcttttcctgctgtggcgtgatggg--ctggtgaaccgtagctgtgtgtggcttggct
tttgaat-cggctttgctgttgcgaagtagagtgg-------------------cggctt
cggc------------tgtcgagggt-cgatcca----tttgggaac-tttgtgtgcacc
t
>Phytophthora_plurivora_CBS124091_FJ665229 Phytophthora_plurivora_CBS124091_FJ665229 895 bp 
ccacacct-aaaaaacttttcacgtgaaccgtatcaacccttttagttgggggtcttgct
t------------------------------------tttttgcgagccctatcatggcg
aatgtttggactt---cggtctgggctagtagc-tttttgttttaaacccatt-ctacaa
tactgattatactgcggggacgaaagtctctgcttttaactagatagcaactttcagcag
tggatgtctaggctcgcacatcgatgaagaacgctgcgaactgcgatacgtaatgcgaat
tgcaggattcagtgagtcatcgaaattttgaacgcatattgcacttccgggttagtcctg
ggagtatgcctgtatcagtgtccgtacatcaaacttggctttcttccttccgtgtagtcg
gtgga--ggatgtgccagacgtgaagtgtcttgcgggtgtc----cttcgggtc--gtct
gcgagtcctttgaaatgtactgaactgtacttctctttgctcgaaaagcgtggt--gttg
ctggttgtggaggctgcctgcgtggccagtc-ggcgaccggtttgtctgctgcggcgttt
aatggaggagtgttcgattcgcggtatggttggcttcggctgaacaggc-gcttattgta
t-gcttttcctgctgtggcgtgatggg--ctggtgaaccgtagctgtgtgtggcttggct
tttgaat-cggctttgctgttgcgaagtagagtgg-------------------cggctt
cggc------------tgtcgagggt-cgatcca----tttgggaac-tttgtgtgcacc
t
>Phytophthora_plurivora_CBS124092_FJ665233 Phytophthora_plurivora_CBS124092_FJ665233 895 bp 
ccacacct-aaaaaacttttcacgtgaaccgtatcaacccttttagttgggggtcttgct
t------------------------------------tttttgcgagccctatcatggcg
aatgtttggactt---cggtctgggctagtagc-tttttgttttaaacccatt-ctacaa
tactgattatactgcggggacgaaagtctctgcttttaactagatagcaactttcagcag
tggatgtctaggctcgcacatcgatgaagaacgctgcgaactgcgatacgtaatgcgaat
tgcaggattcagtgagtcatcgaaattttgaacgcatattgcacttccgggttagtcctg
ggagtatgcctgtatcagtgtccgtacatcaaacttggctttcttccttccgtgtagtcg
gtgga--ggatgtgccagacgtgaagtgtcttgcgggtgtc----cttcgggtc--gtct
gcgagtcctttgaaatgtactgaactgtacttctctttgctcgaaaagcgtggt--gttg
ctggttgtggaggctgcctgcgtggccagtc-ggcgaccggtttgtctgctgcggcgttt
aatggaggagtgttcgattcgcggtatggttggcttcggctgaacaggc-gcttattgta
t-gcttttcctgctgtggcgtgatggg--ctggtgaaccgtagctgtgtgtggcttggct
tttgaat-cggctttgctgttgcgaagtagagtgg-------------------cggctt
cggc------------tgtcgagggt-cgatcca----tttgggaac-tttgtgtgcacc
t
>Phytophthora_plurivora_CBS124093_FJ665225 Phytophthora_plurivora_CBS124093_FJ665225 895 bp 
ccacacct-aaaaaacttttcacgtgaaccgtatcaacccttttagttgggggtcttgct
t------------------------------------tttttgcgagccctatcatggcg
aatgtttggactt---cggtctgggctagtagc-tttttgttttaaacccatt-ctacaa
tactgattatactgcggggacgaaagtctctgcttttaactagatagcaactttcagcag
tggatgtctaggctcgcacatcgatgaagaacgctgcgaactgcgatacgtaatgcgaat
tgcaggattcagtgagtcatcgaaattttgaacgcatattgcacttccgggttagtcctg
ggagtatgcctgtatcagtgtccgtacatcaaacttggctttcttccttccgtgtagtcg
gtgga--ggatgtgccagacgtgaagtgtcttgcgggtgtc----cttcgggtc--gtct
gcgagtcctttgaaatgtactgaactgtacttctctttgctcgaaaagcgtggt--gttg
ctggttgtggaggctgcctgcgtggccagtc-ggcgaccggtttgtctgctgcggcgttt
aatggaggagtgttcgattcgcggtatggttggcttcggctgaacaggc-gcttattgta
t-gcttttcctgctgtggcgtgatggg--ctggtgaaccgtagctgtgtgtggcttggct
tttgaat-cggctttgctgttgcgaagtagagtgg-------------------cggctt
cggc------------tgtcgagggt-cgatcca----tttgggaac-tttgtgtgcacc
t
>Phytophthora_plurivora_IMI342898_AF266789 Phytophthora_plurivora_IMI342898_AF266789 895 bp 
ccacacct--aaaaacttttcacgtgaaccgtatcaacccttttagttgggggtcttgct
t------------------------------------tttttgcgagccctatcatggcg
aatgtttggactt---cggtctgggctagtagc-tttttgttttaaacccatt-ctacaa
tactgattatactgcggggacgaaagtctctgcttttaactagatagcaactttcagcag
tggatgtctaggctcgcacatcgatgaagaacgctgcgaactgcgatacgtaatgcgaat
tgcaggattcagtgagtcatcgaaattttgaacgcatattgcacttccgggttagtcctg
ggagtatgcctgtatcagtgtccgtacatcaaacttggctttcttccttccgtgtagtcg
gtgga--ggatgtgccagacgtgaagtgtcttgcgggtgtc----cttcgggtc--gtct
gcgagtcctttgaaatgtactgaactgtacttctctttgctcgaaaagcgtggt--gttg
ctggttgtggaggctgcctgcgtggccagtc-ggcgaccggtttgtctgctgcggcgttt
aatggaggagtgttcgattcgcggtatggttggcttcggctgaacaggc-gcttattgta
t-gcttttcctgctgtggcgtgatggg--ctggtgaaccgtagctgtgtgtggcttggct
tttgaat-cggctttgctgttgcgaagtagagtgg-------------------cggctt
cggc------------tgtcgagggt-cgatcca----tttgggaac-tttgtgtgcacc
t
>Phytophthora_plurivora_InfGaul_AY879291 Phytophthora_plurivora_InfGaul_AY879291 895 bp 
ccccacct-aaaaaacttttcacgtgaaccgtatcaacccttttagttgggggtcttgct
t------------------------------------tttttgcgagccctatcatggcg
aatgtttggactt---cggtctgggctagtagc-tttttgttttaaacccatt-ctacaa
tactgattatactgcggggacgaaagtctctgcttttaactagatagcaactttcagcag
tggatgtctaggctcgcacatcgatgaagaacgctgcgaactgcgatacgtaatgcgaat
tgcaggattcagtgagtcatcgaaattttgaacgcatattgcacttccgggttagtcctg
ggagtatgcctgtatcagtgtccgtacatcaaacttggctttcttccttccgtgtagtcg
gtgga--ggatgtgccagacgtgaagtgtcttgcgggtgtc----cttcgggtc--gtct
gcgagtcctttgaaatgtactgaactgtacttctctttgctcgaaaagcgtggt--gttg
ctggttgtggaggctgcctgcgtggccagtc-ggcgaccggtttgtctgctgcggcgttt
aatggaggagtgttcgattcgcggtatggttggcttcggctgaacaggc-gcttattgta
t-gcttttcctgctgtggcgtgatggg--ctggtgaaccgtagctgtgtgtggcttggct
tttgaat-cggctttgctgttgcgaagtagagtgg-------------------cggctt
cggc------------tgtcgagggt-cgatcca----tttgggaac-taagtgtgcacc
t
>Phytophthora_plurivora_MN21HH_DQ486661 Phytophthora_plurivora_MN21HH_DQ486661 895 bp 
ccacacct-aaaaaacttttcacgtgaaccgtatcaacccttttagttgggggtcttgct
t------------------------------------tttttgcgagccctatcatggcg
aatgtttggactt---cggtctgggctagtagc-tttttgttttaaacccatt-ctacaa
tactgattatactgcggggacgaaagtctctgcttttaactagatagcaactttcagcag
tggatgtctaggctcgcacatcgatgaagaacgctgcgaactgcgatacgtaatgcgaat
tgcaggattcagtgagtcatcgaaattttgaacgcatattgcacttccgggttagtcctg
ggagtatgcctgtatcagtgtccgtacatcaaacttggctttcttccttccgtgtagtcg
gtgga--ggatgtgccagacgtgaagtgtcttgcgggtgtc----cttcgggtc--gtct
gcgagtcctttgaaatgtactgaactgtacttctctttgctcgaaaagcgtggt--gttg
ctggttgtggaggctgcctgcgtggccagtc-ggcgaccggtttgtctgctgcggcgttt
aatggaggagtgttcgattcgcggtatggttggcttcggctgaacaggc-gcttattgta
t-gcttttcctgctgtggcgtgatggg--ctggtgaaccgtagctgtgtgtggcttggct
tttgaat-cggctttgctgttgcgaagtagagtgg-------------------cggctt
cggc------------tgtcgagggt-cgatcca----tttgggaac-tttgtgtgcacc
t
>Phytophthora_plurivora_PLU255_FJ665232 Phytophthora_plurivora_PLU255_FJ665232 895 bp 
ccacacct-aaaaaacttttcacgtgaaccgtatcaacccttttagttgggggtcttgct
t------------------------------------tttttgcgagccctatcatggcg
aatgtttggactt---cggtctgggctagtagc-tttttgttttaaacccatt-ctacaa
tactgattatactgcggggacgaaagtctctgcttttaactagatagcaactttcagcag
tggatgtctaggctcgcacatcgatgaagaacgctgcgaactgcgatacgtaatgcgaat
tgcaggattcagtgagtcatcgaaattttgaacgcatattgcacttccgggttagtcctg
ggagtatgcctgtatcagtgtccgtacatcaaacttggctttcttccttccgtgtagtcg
gtgga--ggatgtgccagacgtgaagtgtcttgcgggtgtc----cttcgggtc--gtct
gcgagtcctttgaaatgtactgaactgtacttctctttgctcgaaaagcgtggt--gttg
ctggttgtggaggctgcctgcgtggccagtc-ggcgaccggtttgtctgctgcggcgttt
aatggaggagtgttcgattcgcggtatggttggcttcggctgaacaggc-gcttattgta
t-gcttttcctgctgtggcgtgatggg--ctggtgaaccgtagctgtgtgtggcttggct
tttgaat-cggctttgctgttgcgaagtagagtgg-------------------cggctt
cggc------------tgtcgagggt-cgatcca----tttgggaac-tttgtgtgcacc
t
>Phytophthora_plurivora_PLU35_FJ237524 Phytophthora_plurivora_PLU35_FJ237524 895 bp 
ccacacct-aaaaaacttttcacgtgaaccgtatcaacccttttagttgggggtcttgct
t------------------------------------tttttgcgagccctatcatggcg
aatgtttggactt---cggtctgggctagtagc-tttttgttttaaacccatt-ctacaa
tactgattatactgcggggacgaaagtctctgcttttaactagatagcaactttcagcag
tggatgtctaggctcgcacatcgatgaagaacgctgcgaactgcgatacgtaatgcgaat
tgcaggattcagtgagtcatcgaaattttgaacgcatattgcacttccgggttagtcctg
ggagtatgcctgtatcagtgtccgtacatcaaacttggctttcttccttccgtgtagtcg
gtgga--ggatgtgccagacgtgaagtgtcttgcgggtgtc----cttcgggtc--gtct
gcgagtcctttgaaatgtactgaactgtacttctctttgctcgaaaagcgtggt--gttg
ctggttgtggaggctgcctgcgtggccagtc-ggcgaccggtttgtctgctgcggcgttt
aatggaggagtgttcgattcgcggtatggttggcttcggctgaacaggc-gcttattgta
t-gcttttcctgctgtggcgtgatggg--ctggtgaaccgtagctgtgtgtggcttggct
tttgaat-cggctttgctgttgcgaagtagagtgg-------------------cggctt
cggc------------tgtcgagggt-cgatcca----tttgggaac-tttgtgtgcacc
t
>Phytophthora_plurivora_PLU36_FJ665228 Phytophthora_plurivora_PLU36_FJ665228 895 bp 
ccacacct-aaaaaacttttcacgtgaaccgtatcaacccttttagttgggggtcttgct
t------------------------------------tttttgcgagccctatcatggcg
aatgtttggactt---cggtctgggctagtagc-tttttgttttaaacccatt-ctacaa
tactgattatactgcggggacgaaagtctctgcttttaactagatagcaactttcagcag
tggatgtctaggctcgcacatcgatgaagaacgctgcgaactgcgatacgtaatgcgaat
tgcaggattcagtgagtcatcgaaattttgaacgcatattgcacttccgggttagtcctg
ggagtatgcctgtatcagtgtccgtacatcaaacttggctttcttccttccgtgtagtcg
gtgga--ggatgtgccagacgtgaagtgtcttgcgggtgtc----cttcgggtc--gtct
gcgagtcctttgaaatgtactgaactgtacttctctttgctcgaaaagcgtggt--gttg
ctggttgtggaggctgcctgcgtggccagtc-ggcgaccggtttgtctgctgcggcgttt
aatggaggagtgttcgattcgcggtatggttggcttcggctgaacaggc-gcttattgta
t-gcttttcctgctgtggcgtgatggg--ctggtgaaccgtagctgtgtgtggcttggct
tttgaat-cggctttgctgttgcgaagtagagtgg-------------------cggctt
cggc------------tgtcgagggt-cgatcca----tttgggaac-tttgtgtgcacc
t
>Phytophthora_plurivora_PLU7_AJ007370 Phytophthora_plurivora_PLU7_AJ007370 895 bp 
ccacacct-aaaaaacttttcacgtgaaccgtatcaacccttttagttgggggtcttgct
t------------------------------------tttttgcgagccctatcatggcg
aatgtttggactt---cggtctgggctagtagc-tttttgttttaaacccatt-ctacaa
tactgattatactgcggggacgaaagtctctgcttttaactagatagcaactttcagcag
tggatgtctaggctcgcacatcgatgaagaacgctgcgaactgcgatacgtaatgcgaat
tgcaggattcagtgagtcatcgaaattttgaacgcatatcgcacttccgggttagtcctg
ggagtatgcctgtatcagtgtccgtacatcaaacttggctttcttccttccgtgtagtcg
gtgga--ggatgtgccagacgtgaagtgtcttgcgggtgtc----cttcgggtc--gtct
gcgagtcctttgaaatgtactgaactgtacttctctttgctcgaaaagcgtggt--gttg
ctggttgtggaggctgcctgcgtggccagtc-ggcgaccggtttgtctgctgcggcgttt
aatggaggagtgttcgattcgcggtatggttggcttcggctgaacaggc-gcttattgta
t-gcttttcctgctgtggcgtgatggg--ctggtgaaccgtagctgtgtgtggcttggct
tttgaat-cggctttgctgttgcgaagtagagtgg-------------------cggctt
cggc------------tgtcgagggt-cgatcca----tttgggaac-tttgtgtgcacc
t
>Phytophthora_plurivora_PLU77_FJ665230 Phytophthora_plurivora_PLU77_FJ665230 895 bp 
ccacacct-aaaaaacttttcacgtgaaccgtatcaacccttttagttgggggtcttgct
t------------------------------------tttttgcgagccctatcatggcg
aatgtttggactt---cggtctgggctagtagc-tttttgttttaaacccatt-ctacaa
tactgattatactgcggggacgaaagtctctgcttttaactagatagcaactttcagcag
tggatgtctaggctcgcacatcgatgaagaacgctgcgaactgcgatacgtaatgcgaat
tgcaggattcagtgagtcatcgaaattttgaacgcatattgcacttccgggttagtcctg
ggagtatgcctgtatcagtgtccgtacatcaaacttggctttcttccttccgtgtagtcg
gtgga--ggatgtgccagacgtgaagtgtcttgcgggtgtc----cttcgggtc--gtct
gcgagtcctttgaaatgtactgaactgtacttctctttgctcgaaaagcgtggt--gttg
ctggttgtggaggctgcctgcgtggccagtc-ggcgaccggtttgtctgctgcggcgttt
aatggaggagtgttcgattcgcggtatggttggcttcggctgaacaggc-gcttattgta
t-gcttttcctgctgtggcgtgatggg--ctggtgaaccgtagctgtgtgtggcttggct
tttgaat-cggctttgctgttgcgaagtagagtgg-------------------cggctt
cggc------------tgtcgagggt-cgatcca----tttgggaac-tttgtgtgcacc
t
>Phytophthora_plurivora_PLU9_FJ237523 Phytophthora_plurivora_PLU9_FJ237523 895 bp 
ccacacct-aaaaaacttttcacgtgaaccgtatcaacccttttagttgggggtcttgct
t------------------------------------tttttgcgagccctatcatggcg
aatgtttggactt---cggtctgggctagtagc-tttttgttttaaacccatt-ctacaa
tactgattatactgcggggacgaaagtctctgcttttaactagatagcaactttcagcag
tggatgtctaggctcgcacatcgatgaagaacgctgcgaactgcgatacgtaatgcgaat
tgcaggattcagtgagtcatcgaaattttgaacgcatattgcacttccgggttagtcctg
ggagtatgcctgtatcagtgtccgtacatcaaacttggctttcttccttccgtgtagtcg
gtgga--ggatgtgccagacgtgaagtgtcttgcgggtgtc----cttcgggtc--gtct
gcgagtcctttgaaatgtactgaactgtacttctctttgctcgaaaagcgtggt--gttg
ctggttgtggaggctgcctgcgtggccagtc-ggcgaccggtttgtctgctgcggcgttt
aatggaggagtgttcgattcgcggtatggttggcttcggctgaacaggc-gcttattgta
t-gcttttcctgctgtggcgtgatggg--ctggtgaaccgtagctgtgtgtggcttggct
tttgaat-cggctttgctgttgcgaagtagagtgg-------------------cggctt
cggc------------tgtcgagggt-cgatcca----tttgggaac-tttgtgtgcacc
t
>Phytophthora_plurivora_PLU92_FJ665231 Phytophthora_plurivora_PLU92_FJ665231 895 bp 
ccacacct-aaaaaacttttcacgtgaaccgtatcaacccttttagttgggggtcttgct
t------------------------------------tttttgcgagccctatcatggcg
aatgtttggactt---cggtctgggctagtagc-tttttgttttaaacccatt-ctacaa
tactgattatactgcggggacgaaagtctctgcttttaactagatagcaactttcagcag
tggatgtctaggctcgcacatcgatgaagaacgctgcgaactgcgatacgtaatgcgaat
tgcaggattcagtgagtcatcgaaattttgaacgcatattgcacttccgggttagtcctg
ggagtatgcctgtatcagtgtccgtacatcatacttggctttcttccttccgtgtagtcg
gtgga--ggatgtgccagacgtgaagtgtcttgcgggtgtc----cttcgggtc--gtct
gcgagtcctttgaaatgtactgaactgtacttctctttgctcgaaaagcgtggt--gttg
ctggttgtggaggctgcctgcgtggccagtc-ggcgaccggtttgtctgctgcggcgttt
aatggaggagtgttcgattcgcggtatggttggcttcggctgaacaggc-gcttattgta
t-gcttttcctgctgtggcgtgatggg--ctggtgaaccgtagctgtgtgtggcttggct
tttgaat-cggctttgctgttgcgaagtagagtgg-------------------cggctt
cggc------------tgtcgagggt-cgatcca----tttgggaac-tttgtgtgcacc
t
>Phytophthora_quercetorum_MND4_EF539180 Phytophthora_quercetorum_MND4_EF539180 895 bp 
ccacacct-aaaaaactttccacgtgaaccgtatcaaac--tttagttgggggtcttttt
cggcgacggctgctggcttcattgctggcggctgctgttggat-gagccctatcatggcg
agcgtttgggctt---cggtctgaactagtagc-----ttttttaaacccatt-ctttat
tactgattatactgtggggacgaaagtctctgcttttaactagatagcaactttcagcag
tggatgtctaggctcgcacatcgatgaagaacgctgcgaactgcgatacgtaatgcgaat
tgcaggattcagtgagtcatcgaaattttgaacgcatattgcacttccgggttagtcctg
ggagtatgcctgtatcagtgtccgtacatcaaacttggctttcttccttccgtgtagtcg
gtgga--ggatgtgccagatgtgaagtgtcttgcggctggt----cttcgggtc--ggct
gtgagtcctttgaaatgtactgaactgtacttctctttgctcgaaaagcgtggc--gttg
ctgattgtggaggctgcctgcgtagccagtctggcgaccagtttgtctgctgtggcg-tt
aatggaggagtgttcgattcgcggtatggttggcttcggctgaacagac-gcttattgaa
t-gtttttcctgctgtggcggtacggg--ttggtgaaccgtagctatgtg-ggcttggct
tttgaat-tggctttgctgttgcgaagtagagtgg-------------------cagctt
cggc------------tgtcgagggt-cgatcca----tttgggaat--ttgtgtgtact
t
>Phytophthora_quercetorum_WI111_EF539179 Phytophthora_quercetorum_WI111_EF539179 895 bp 
ccacacct-aaaaaactttccacgtgaaccgtatcaaac--tttagttgggggtcttttt
cggcgacggctgctggcttcattgctggcggctgctgttggat-gagccctatcatggcg
agcgtttgggctt---cggtctgaactagtagc-----ttttttaaacccatt-ctttat
tactgattatactgtggggacgaaagtctctgcttttaactagatagcaactttcagcag
tggatgtctaggctcgcacatcgatgaagaacgctgcgaactgcgatacgtaatgcgaat
tgcaggattcagtgagtcatcgaaattttgaacgcatattgcacttccgggttagtcctg
ggagtatgcctgtatcagtgtccgtacatcaaacttggctttcttccttccgtgtagtcg
gtgga--ggatgtgccagatgtgaagtgtcttgcggctggt----cttcgggtc--ggct
gtgagtcctttgaaatgtactgaactgtacttctctttgctcgaaaagcgtggc--gttg
ctgattgtggaggctgcctgcgtagccagtctggcgaccagtttgtctgctgtggcg-tt
aatggaggagtgttcgattcgcggtatggttggcttcggctgaacagac-gcttattgaa
t-gtttttcctgctgtggcggtacggg--ttggtgaaccgtagctatgtg-ggcttggct
tttgaat-tggctttgctgttgcgaagtagagtgg-------------------cagctt
cggc------------tgtcgagggt-cgatcca----tttgggaat--ttgtgtgtact
t
>Phytophthora_sp__1_DDS1221_EU593265 Phytophthora_sp._1_DDS1221_EU593265 895 bp 
ccacacct-aaaaaactttccacgtgaaccgtatcaaac--tttagttgggggtcttttt
cggcgacggctgctggcttcattgctggcggctgctgttgaat-gagccctatcatggcg
agcgtttaggctt---cggtctgaactagtagc-----ttttttaaacccatt-ctttat
tactgattatactgtggggacgaaagtctctgcttttaactagatagcaactttcagcag
tggatgtctaggctcgcacatcgatgaagaacgctgcgaactgcgatacgtaatgcgaat
tgcaggattcagtgagtcatcgaaattttgaacgcatattgcacttccgggttagtcctg
ggagtatgcctgtatcagtgtccgtacatcaaacttggctttcttccttccgtgtagtcg
gtgga--agatgtgccagatgtgaagtgtcttgcggctggt----cttcgggtc--ggct
gtgagtcctttgaaatgtactgaactgtacttctctttgctcgaaaagcgtggc--gttg
ctgattgtggaggctgcctgcgtagccagtctggcgaccagtttgtctgctgtggcg-tt
aatggaggagtgttcgattcgcggtatggttggctttggctgaacagac-gcttattgaa
t-gtttttcctgctatggcggtacggg--ttggtgaaccgtagctatgtg-ggcttggct
tttgaat-tggctttgctgttgcgaagtagagtgg-------------------cggctt
cggc------------tgtcgagggt-cgatcca----tttgggaat--ttgtgtgtact
t
>Phytophthora_sp__1_VHS9861_EU301118 Phytophthora_sp._1_VHS9861_EU301118 895 bp 
ccacacct-aaaaaactttccacgtgaaccgtatcaaac--tttagttgggggtcttttt
cggcgacggctgctggcttcattgctggcggctgctgttgaat-gagccctatcatggcg
agcgtttaggctt---cggtctgaactagtagc-----ttttttaaacccatt-ctttat
tactgattatactgtggggacgaaagtctctgcttttaactagatagcaactttcagcag
tggatgtctaggctcgcacatcgatgaagaacgctgcgaactgcgatacgtaatgcgaat
tgcaggattcagtgagtcatcgaaattttgaacgcatattgcacttccgggttagtcctg
ggagtatgcctgtatcagtgtccgtacatcaaacttggctttcttccttccgtgtagtcg
gtgga--agatgtgccagatgtgaagtgtcttgcggctggt----cttcgggtc--ggct
gtgagtcctttgaaatgtactgaactgtacttctctttgctcgaaaagcgtggc--gttg
ctgattgtggaggctgcctgcgtagccagtctggcgaccagtttgtctgctgtggcg-tt
aatggaggagtgttcgattcgcggtatggttggctttggctgaacagac-gcttattgaa
t-gtttttcctgctatggcggtacggg--ttggtgaaccgtagctatgtg-ggcttggct
tttgaat-tggctttgctgttgcgaagtagagtgg-------------------cggctt
cggc------------tgtcgagggt-cgatcca----tttgggaat--ttgtgtgtact
t
>Phytophthora_sp__DAR34210_L41375 Phytophthora_sp._DAR34210_L41375 895 bp 
ccacacct-aaaaaactttccacgtgaaccgtttcaaccctttcagttgggggccttgct
-------------------------------------tttttgcgagccctatcatggcg
aatgtttggactt---cggtctgggctagtagc-tttttgttttaaacccatt-ctacaa
tactgattatactgtggggacgaaagtctctgcttttaactagataacaactttcagcag
tggatgtctaggctcgcacatcgatgaagaacgctgcgaactgcgatacgtaatgcgaat
tgcaggattcagtgagtcatcgaaatttggaacgcatattgcactcccgggttagtcctg
ggagtatgcctgtatcagtgtccgtacatcaaacttggctttctccctcccgtgtagtcg
gtgga--ggatgtgccagatgtgaagtgtcttgcaggtgtc----cttcgggtc--gtct
gcgagtcctttgaaatgtactgaactgtacttctctttgctcgaaaagcgtggc--gttg
ctggttgtggaggctgcctgcgtggccagtc-ggcgaccggtttgtctgctgcggcgttt
aatggaggagtgttcgattcgcggtatggttggcttcggctgaacaggc-gcttattgta
t-gcttttcctgctgtggcgtgatgga--ctggtgaaccgtagctgtgtgtggcttggct
tttgaat-cggctttgctgttgcgaagtagagtgg-------------------cggctc
cggc------------tgtcgagggt-cgatcca----tttgggaac-tttgtgtgcacc
t
>Phytophthora_sp__P4242_AY946259 Phytophthora_sp._P4242_AY946259 895 bp 
ccacacct-aaaaaactttccacgtgaaccgtttcaaccctttcagttgggggccttgct
-------------------------------------tttttgcgagccctatcatggcg
aatgtttggactt---cggtctgggctagtagc-tttttgttttaaacccatt-ctacaa
tactgattatactgtggggacgaaagtctctgcttttaactagataacaactttcagcag
tggatgtctaggctcgcacatcgatgaagaacgctgcgaactgcgatacgtaatgcgaat
tgcaggattcagtgagtcatcgaaatttggaacgcatattgcactcccgggttagtcctg
ggagtatgcctgtatcagtgtccgtacatcaaacttggctttctccctcccgtgtagtcg
gtgga--ggatgtgccagatgtgaagtgtcttgcaggtgtc----cttcgggtc--gtct
gcgagtcctttgaaatgtactgaactgtacttctctttgctcgaaaagcgtggc--gttg
ctggttgtggaggctgcctgcgtggccagtc-ggcgaccggtttgtctgctgcggcgttt
aatggaggagtgttcgattcgcggtatggttggcttcggctgaacaggc-gcttattgta
t-gcttttcctgctgtggcgtgatgga--ctggtgaaccgtagctgtgtgtggcttggct
tttgaat-cggctttgctgttgcgaagtagagtgg-------------------cggctc
cggc------------tgtcgagggt-cgatcca----tttgggaac-tttgtgtgcacc
t
>Phytophthora_tropicalis_H213_AY207010 Phytophthora_tropicalis_H213_AY207010 895 bp 
ccacacct-aaaaaactttccacgtgaaccgtatcgacccttttagttgggggtcttgt-
----------------------------------------------accctatcatggcg
aatgtttggactt---cggtctgggcgagtagc-tttttgttttaaacccatt-tctcaa
tactgattatactgcggggacgaaagtctctgcttttaactagatagcaactttcagcag
tggatgtctaggctcgcacatcgatgaagaacgctgcgaactgcgatacgtaatgcgaat
tgcaggattcagtgagtcatcgaaattttgaacgcatattgcacttccgggttagtcctg
ggagtatgcctgtatcagtgtccgtacatcaaacttggctttcttccttccgtgtagtcg
gtgga--ggatgtgccagatgtgaagtgtcttgcggtttgt---ccttcgggtc--ggct
gcgagtccttttaaatgtactgaactgtacttctctttgctcgaaaagcgtggt--gttg
ctggttgtggaggctgcctgcgtggccagtc-ggcgaccggtttgtctgctgcggcgttt
aatggaggagtgttcgattcgcggtatggttggcttcggctgaacaggc-gcttattgta
t-gcttttcctgctgtggcgtgatggg--ctggtgaaccgtagctgtgtgtggcttggct
tttgaat-cggctttgctgttgcgaagtagagtgg-------------------cggctt
cggc------------tgtcgagggt-cgatcca---ttttgggaac-tttgtgtgcact
t
>Phytophthora_tropicalis_P4742_AY946257 Phytophthora_tropicalis_P4742_AY946257 895 bp 
ccacacct-aaaaaactttccacgtgaaccgtatcgacccttttagttgggggtcttgt-
----------------------------------------------accctatcatggcg
aatgtttggactt---cggtctgggcgagtagc-tttttgttttaaacccatt-tctcaa
tactgattatactgcggggacgaaagtctctgcttttaactagatagcaactttcagcag
tggatgtctaggctcgcacatcgatgaagaacgctgcgaactgcgatacgtaatgcgaat
tgcaggattcagtgagtcatcgaaattttgaacgcatattgcacttccgggttagtcctg
ggagtatgcctgtatcagtgtccgtacatcaaacttggctttcttccttccgtgtagtcg
gtgga--ggatgtgccagatgtgaagtgtcttgcggtttgt---ccttcgggtc--ggct
gcgagtccttttaaatgtactgaactgtacttctctttgctcgaaaagcgtggt--gttg
ctggttgtggaggctgcctgcgtggccagtc-ggcgaccggtttgtctgctgcggcgttt
aatggaggagtgttcgattcgcggtatggttggcttcggctgaacaggc-gcttattgta
t-gcttttcctgctgtggcgtgatggg--ctggtgaaccgtagctgtgtgtggcttggct
tttgaat-cggctttgctgttgcgaagtagagtgg-------------------cggctt
cggc------------tgtcgagggt-cgatcca---ttttgggaac-tttgtgtgcact
t
>END; 1 bp 
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
n
>nameless_1 1 bp 
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
n
>nameless_2 1 bp 
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
n
>nameless_3 1 bp 
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
n
