>Eteone_picta 1369 bp 
aggtttccgtaggtgaacctgcggaaggatcattatcgaaac--------gagaacgaaa
gttgcaaac--tttgaacgctaaatcc----------------------------tcgtc
ccccgcgagccgctgcc-------------------------------------cctcca
catcccgccctataacttcgcggcgggtg----cggttcgtgcgagcggacgaggtggcc
cc-----ggccccccttaggcgctatcgctgcgaggatcgttcctctcactcacgactc-
-----------------------gtggcggccggggatgtgttgccggcgtccgtcaaac
cccactcttaccatgcgaagggggtaccg------cgctcccgtcccctctc--------
--cgggagatagctactgtgcctcgaggtgaatcggtttaaagcggcgcgact-------
-------------------------------gccctactactgtcgtcctctcccgtc--
-gcccgccccgcttcgcat---------------------ctgtgcctcctccatactgt
cacg-----------agaaccttacgaaacgccgctccccgtgcgaatgttgcccgcgcg
tgcggacgtggctcc-aaaccaaagtcggcgaaggaaccctctcggggacccgagtcgcg
a--caaactactctaagcggtggatcactcggctcgtgcgtcgatgaagagcgcagccag
ctgcgtgaactaatgtgaattgcaggacacattgaacatcgacatcttgaacgcatattg
cggcatcggctcaaaccgttgccacgcctgtctcagggtcggttcactagcaatcg-ctc
cgcgttcctcctcgcggca---------------gcgccttgag--ccgtcgtagtccct
ccgccagggggggctccgtcgctccaagtgcagaccggttacgc----------gtcctc
cgttcgtccccctacccgttcggaaaaagacgcggccggc-----------------ctc
tctcacg----tcccgctcgcggtctcgcggcct----------ccggacggcggcttg-
-----gcttcctctgctcgcctccgg----------------------------------
----------------------------------ttcccgc-------------------
---tcgggacccaaccgtggactcctcctatgagagagagcgcccggctaagccgaccaa
cccttcg---------tcgttcctccgaacg-------------------tcgaaaaacc
actc---tgtcgacctgagatcagacgagact
>Notophyllum_crypticum_spm_11 1372 bp 
aggtttccgtaggtgaacctgcggaaggatcattatcgaaact-------gacccagatg
gtttcagatgagagg-----aaagtcc--------------------gaggaaactcgat
ttctcggcggcggtgccag-tgcctcgggagcgcagtctctcggcacgccagggcatcgt
ggcggcgtcccatggctcgggg-taggcta---cggatcttagtgggagatccgccgacc
cc----------------ggttcgctcggaaggggcgccagtgatctaaaaattgaaac-
-------------------------agcagtgcggggtacctgtcctg-ggg--aaggcc
ctcca---tattccccggggtgagcaccgttggcgcgcgcctgccc-ttact-----cgg
cgcga-----------------tcgtcgtgcgacggttcaaagaggcg-gaccacagtca
tc--ttcctcacagtmgacctcatatgt---ggcggagggtgatttatcccacccggc-g
agtccgccccgcattgcga-cccctcgctt-gcgagggttttgttttccccacgaactgt
tacc-aattgtgtgaaccatattacgaagc----ttgcgcgtccgtccgttgcccgggcg
t-----cgcaaggcc-aaactttattttccaaag----cctctacgaggtgagtacgaaa
ag-aaaactactctaagcggtggatcactcggctcgtgtgtcgatgaagagcgcagccag
ctgcgtgaattaatgtgaattgcaggacacattgaacatcgatatcttgaacgcatattg
cggcatcggcttccaccgatgccacgcctgtctcagggtcggtttactatctatcgcccc
cgcgctcctctcggtagcaatgcgga-ttcgtgggcgccttgggttttcacgcagcgctt
c--------ggtgctccgcggccctaagtgcagaccggtctccc-aaaaagttgattgtt
c---------------------ggggacggctcgtcccgatcgccagctctgtgtg-att
tttctcgacgctcgccctcaagagctcgtggcacagcccgtgg-tcggacggtggctcg-
------gcttctttgctcgcctccgc----ccgggttcctcgagt-ttataagccgtcga
aaa-aacaa-ccagcagcgagtgcctcggac-tttttcgac-------------------
---ttcggaccgaaccggtgact---------------------cggtttaaccaatagc
acgtg-----------tcctcc----gggat-------------------acgtgcgatc
actc---tgtcgacctgagatcagacgagact
>Notophyllum_crypticum_spm_12 1369 bp 
aggtttccgtaggtgaacctgcggaaggatcattatcgaaact-------gacccagatg
gtttcagatgagagg-----aaagtcc--------------------gaggaaactcgat
ttctcggcggcggtgccag-tgcctcgggagcgcagtctctcggcacgccagggcatcgt
ggcggcgtcccatggctcgggg-taggcta---cggatcttagtgggagatccgccgacc
cc----------------ggttcgctcggaaggggcgccagtgatctaaaaattgaaac-
-------------------------agcagtgcggggtacctgtcctg-ggg--aaggcc
ctcca---tattccccggggtgagcaccgttggcgcgcgcctgccc-ttact-----cgg
cgcga-----------------tcgtcgtgcgacggttcaaagaggcg-gaccacagtca
tc--ttcctcacagtcgacctcatatgt---ggcggagggtgatttatcccacccggc-g
agtccgccccgcattgcga-cccctcgctt-gcgagggttttgttttccccacgaactgt
tacc-aattgtgtgaaccatattacgaagc----ttgcgcgtccgtccgttgcccgggcg
t-----cgcaaggcc-aaactttattttccaaag----cctctacgaggtgagtacgaaa
ag-aaaactactctaagcggtggatcactcggctcgtgtgtcgatgaagagcgcagccag
ctgcgtgaattaatgtgaattgcaggacacattgaacatcgatatcttgaacgcatattg
cggcatcggcttccaccgatgccacgcctgtctcagggtcggtttactatctatcgcccc
cgcgctcctctcggtagcaatgcgga-ttcgtgggcgccttgggttttcacgcagcgctt
c--------ggtgctccgcggccctaagtgcagaccggtctccc-aaaaagttgattgtt
c---------------------ggggacggctcgtcccgatcgccagctctgtgtg-att
tttctcgacgctcgccctcaagagctcgtggcacagcccgtgg-tcggacggtggctcg-
------gcttctttgctcgcctccgc----ccgggttcctcgagt-ttataagccgtcga
aaa-aacaa-ccagcagcgagtgcctcggac-tttttcgac-------------------
---ttcggaccgaaccggtgact---------------------cggtttaaccaatagc
acgtg-----------tcctcc----gggat-------------------acgtgcgatc
actc---tgtcgacctgagatcagacgagact
>Notophyllum_crypticum_spm_13 1369 bp 
aggtttccgtaggtgaacctgcggaaggatcattatcgaaact-------gacccagatg
gtttcagatgagagg-----aaagtcc--------------------gaggaaactcgat
ttctcggcggcggtgccag-tgcctcgggagcgcagtctctcggcacgccagggcatcgt
ggcggcgtcccatggctcgggg-taggcta---cggatcttagtgggagatccgccgacc
cc----------------ggttcgctcggaaggggcgccagtgatctaaaaattgaaac-
-------------------------agcagtgcggggtacctgtcctg-ggg--aaggcc
ctcca---tattccccggggtgagcaccgttggcgcgcgcctgccc-ttact-----cgg
cgcga-----------------tcgtcgtgcgacggttcaaagaggcg-gaccacagtca
tc--ttcctcacagtcgacctcatatgt---ggcggagggtgatttatcccacccggc-g
agtccgccccgcattgcgaccccctcgctt-gcgagggttttgttttccccacgaactgt
tacc-aattgtgtgaaccatattacgaagc----ttgcgcgtccgtccgttgcccgggcg
t-----cgcaaggcc-aaactttattttccaaag----cctctacgaggtgagtacgaaa
ag-aaaactactctaagcggtggatcactcggctcgtgtgtcgatgaagagcgcagccag
ctgcgtgaattaatgtgaattgcaggacacattgaacatcgatatcttgaacgcatattg
cggcatcggcttccaccgatgccacgcctgtctcagggtcggtttactatctatcgcccc
cgcgctcctctcggtagcaatgcgga-ttcgtgggcgccttgggttttcacgcagcgctt
c--------ggtgctccgcggccctaagtgcagaccggtctccc-aaaaagttgattgtt
c---------------------ggggacggctcgtcccgatcgccagctctgtgtg-att
tttctcgacgctcgccctcaagagctcgtggcacagcccgtgg-tcggacggtggctcg-
------gcttctttgctcgcctccgc----ccgggttcctcgagt-ttataagccgtcga
aaa-aacaa-ccagcagcgagtgcctcggac-tttttcgac-------------------
---ttcggaccgaaccggtgact---------------------cggtttaaccaatagc
acgtg-----------tcctcc----gggat-------------------acgtgcgatc
actc---tgtcgacctgagatcagacgagact
>Notophyllum_crypticum_spm_14 1369 bp 
aggtttccgtaggtgaacctgcggaaggatcattatcgaaact-------gacccagatg
gtttcagatgagaggagtgaaaagtcc--------------------gaggaaactcgat
ttctcggcggcggtgccagttgcctcgggagcgcagtctctcggcacgccagggcatcgt
ggcggcgtcccatggctcggggttaggcta---cggatcttagtgggagatccgccgacc
cc----------------ggttcgctcggaaggggcgccagtgatctaaaaattgaaac-
-------------------------agcagtgcggggtacctgtcccg-ggg--aaggcc
ctcga--taattccccggggtgagcaccgttggcgcgcgcctgccc-ttact-----cgg
cgcga-----------------tcgtcgtgcgacggttcaaagaggcg-gaccacagtcc
cc-ttccctcacagcagacctcatatgt---ggcggagggtgatttatcccacccggc-g
agtccgccccgcattgcga-cccctcgctt-gcgagggttttgttttccccacgaactgt
tacc-aattgtgtgaaccatattacgaagc----ttgcgcgtccgtccgttgcccgggcg
t-----cgcaaggcc-aaactttattttccaaag----cctctacgaggtgagtacgaaa
ag-aaaactactctaagcggtggatcactcggctcgtgtgtcgatgaagagcgcagccag
ctgcgtgaattaatgtgaattgcaggacacattgaacatcgatatcttgaacgcatattg
cggcatcggcttccaccgatgccacgcctgtctcagggtcggtttactatctatcgcccc
cgcgctcctctcggtagcaatgcgga-ttcgtgggcgccttgggttttcacgcagcgctt
c--------ggtgctccgcggccctaagtgcagaccggtctccc-aaaaagttgattgtt
c---------------------ggggacggctcgtcccgatcgccagctctgtgtg-att
tttctcgacgctcgccctcaagagctcgtggcacagcccgtgg-tcggacggtggctcg-
------gcttctttgctcgcctccgc----ccgggttcctcgagt-ttataagccgtcga
aaa-aacaa-ccagcagtgagtgcctcggacttttttcgac-------------------
---ttcggaccgaaccggtgact---------------------cggtttaaccaatagc
acgtg-----------tcctcc----gggat-------------------acgtgcgatc
actc---tgtcgacctgagatcagacgagact
>Notophyllum_crypticum_spm_15 1369 bp 
aggtttccgtaggtgaacctgcggaaggatcattatcgaaact-------gacccagatg
gtttcagatgagaggagtgaaaagtcc--------------------gaggaaactcgat
ttctcggcggcggtgccag-tgcctcgggagcgcagtctctcggcacgccagggcatcgt
ggcggcgtcccatggctcggggttaggcta---cggatcttagtgggagatccgccgacc
cc----------------ggttcgctcggaaggggcgccagtgatctaaaaattgaaac-
-------------------------agcagtgcggggtacctgtcccg-ggg--aaggcc
ctcga--taattccccggggtgagcaccgttggcgcgcgcctgccc-ttact-----cgg
cgcga-----------------tcgtcgtgcgacggttcaaagaggcg-gaccacagtcc
cc-ttccctcacagcagacctcatatgt---ggcggagggtgatttatcccacccggc-g
agtccgccccgcattgcga-cccctcgctt-gcgagggttttgttttccccacgaactgt
tacc-aattgtgtgaaccatattacgaagc----ttgcgcgtccgtccgttgcccgggcg
t-----cgcaaggcc-aaactttattttccaaag----cctctacgaggtgagtacgaaa
ag-aaaactactctaagcggtggatcactcggctcgtgtgtcgatgaagagcgcagccag
ctgcgtgaattaatgtgaattgcaggacacattgaacatcgatatcttgaacgcatattg
cggcatcggcttccaccgatgccacgcctgtctcagggtcggtttactatctatcgcccc
cgcgctcctctaggtagcaatgcgga-ttcgtgggcgccttggg-tttcacgcagcgctt
c--------ggtgctccgcggccctaagtgcagaccggtctccc-aaaaagttgattgtt
c---------------------ggggacggctcgtcccgatcgccagctctgtgtgtttt
tttctcgacgctcgccctcaagagctcgtggcacagcccgtgg-tcggacggtggctcg-
------gcttctttgctcgcctccgc----ccgggttcctcgagt-cgtcag------aa
aga-aatac-aacggagtgagtgcctcgaac-tttttcgac-------------------
---ttcggaccgaaccggtgact---------------------cggtttaaccaatagc
acgtg-----------tcctcc----gggat-------------------acgtgcgatc
actc---tgtcgacctgagatcagacgagact
>Notophyllum_crypticum_spm_16 1369 bp 
aggtttccgtaggtgaacctgcggaaggatcattatcgaaact-------gacccagatg
gtttcagatgagaggagtgaaaagtcc--------------------gaggaaactcgat
ttctcggcggcggtgccag-tgcctcgggagcgcagtctctcggcacgccagggcatcgt
ggcggcgtcccatggctcggggttaggcta---cggatcttagtgggagatccgccgacc
cc----------------ggttcgctcggaaggggcgccagtgatctaaaaattgaaac-
-------------------------agcagtgcggggtacctgtcccg-ggg--aaggcc
ctcga--taattccccggggtgagcaccgttggcgcgcgcctgccc-ttact-----cgg
cgcga-----------------tcgtcgtgcgacggttcaaagaggcg-gaccacagtcc
cc-ttccctcacagcagacctcatatgt---ggcggagggtgatttatcccacccggc-g
agtccgccccgcattgcga-cccctcgctt-gcgagggttttgttttccccacgaactgt
tacc-aattgtgtgaaccatattacgaagc----ttgcgcgtccgtccgttgcccgggcg
t-----cgcaaggcc-aaactttattttccaaag----cctctacgaggtgagtacgaaa
ag-aaaactactctaagcggtggatcactcggctcgtgtgtcgatgaagagcgcagccag
ctgcgtgaattaatgtgaattgcaggacacattgaacatcgatatcttgaacgcatattg
cggcatcggcttccaccgatgccacgcctgtctcagggtcggtttactatctatcgcccc
cgcgctcctctaggtagcaatgcgga-ttcgtgggcgccttggg-tttcacgcagcgctt
c--------ggtgctccgcggccctaagtgcagaccggtctccc-aaaaagttgattgtt
c---------------------ggggacggctcgtcccgatcgccagctctgtgtgtttt
tttctcgacgctcgccctcaagagctcgtggcacagcccgtgg-tcggacggtggctcg-
------gcttctttgctcgcctccgc----ccgggttcctcgagt-cgtcag------aa
aga-aatac-aacggagtgagtgcctcgaac-tttttcgac-------------------
---ttcggaccgaaccggtgact---------------------cggtttaaccaatagc
acgtg-----------tcctcc----gggat-------------------acgtgcgatc
actc---tgtcgacctgagatcagacgagact
>Notophyllum_crypticum_spm_17 1369 bp 
aggtttccgtaggtgaacctgcggaaggatcattatcgaaact-------gacccagatg
gtttcagatgagaggagtgaaaagtcc--------------------gaggaaactcgat
ttctcggcggcggtgccag-tgcctcgggagcgcagtctctcggcacgccagggcatcgt
ggcggcgtcccatggctcggggttaggcta---cggatcttagtgggagatccgccgacc
cc----------------ggttcgctcggaaggggcgccagtgatctaaaaattgaaac-
-------------------------agcagtgcggggtacctgtcccg-ggg-aaaggcc
ctcta---ttttccccggggtgagcaccgttggcgcgcgcctgccc-ttact-----cgg
cgcga-----------------tcgtcgtgcgacggttcaaagaggcg-gaccacagtcc
cc-ttccctcacagcagacctcatatgt---ggcggagggttatttatcccacccggc-g
agtccgccccgcattgcga-cccctcgctt-gcgagggttttgttttccccacgaactgt
tacctaagtgtgtgaaccatattacgaagc----ttgcgcgtccgtccgttgcccgggcg
t-----cgcaaggcc-aaactttattttccaaag----cctctccgaggtgagtacgaaa
ag-aaaactactctaagcggtggatcactcggctcgtgtgtcgatgaagagcgcagccag
ctgcgtgaattaatgtgaattgcaggacacattgaacatcgatatcttgaacgcatattg
cggcatcggcttccaccgatgccacgcctgtctcagggtcggtttactatctatcgcccc
cgcgctcctctcggtagcaatgcgga-ttcgtgggcgccttgggttttcacgcagcgctt
c--------ggtgctccgcggccctaagtgcagaccggtctccc-aaaaagttgattgtt
c---------------------ggggacggctcgtcccgatcgccagctctgtgtg-att
tttctcgacgctcgccctcaagagctcgtggcacagcccgtgg-tcggacggtggctcg-
------gcttctttgctcgcctccgc----ccgggttcctcgagt-ttataagccgtcga
aaa-aacaa-ccagcagtgagtgcctcagac-tttttcgac-------------------
---ttcggaccgaaccggtgact---------------------cggtttaaccaatagc
acgtg-----------tcctcc----gggat-------------------acgtgcgatc
actc---tgtcgacctgagatcagacgagact
>Notophyllum_foliosum_spm_1 1369 bp 
aggtttccgtaggtgaacctgcggaaggatcattatcgaaact-------gacccaaatg
gtttcaaatgtgtggaatg-aaagtcc--------------------gaggaaattcgct
tcctcggcggcggtgccag-tgcctcgggagcgcagtctcccggcacgccagggcatcgt
ggcggcgtcccatggctcggggtcaggcta---cggatcttagtgggagattcgccgacc
cc----------------ggttcgctcggaaggggcgccagtgatctaaaaattgaaac-
-------------------------agcagtgcggggtacctgtcccg-gggaaaaggcc
ctcta--tttttctccggggtgagcaccgttggcgcgcgcctgccctttact-----cgg
cgcga-----------------tcgtcgtgcgacggttcaaagaggcg-gaccacagtcc
cccttccctcacggcagacctcagacgtggcggcggagggtgatttatcccacccggc-g
agtccgccccgcattgcga-cccctcgcttcgcgagggttttgttttccccacgaactgt
taca-aagtgtgtgaaccatattacgaagc----ttgcgcgtccgtccgttgcccgggcg
t-----cgcaaggcc-aaactttattttccaaag----cctcttcgaggtgagtacgaaa
ag-aaaactactctaagcggtggatcactcggctcgtgtgtcgatgaagagcgcagccag
ctgcgtgaattaatgtgaattgcaggacacattgaacatcgatatcttgaacgcatattg
cggcatcggcttccaccgatgccacgcctgtctcagggtcggtttactatctatcgcccc
cgcgctcctctcggtagcaatgcggatttcacgggcgccttggg-tttcacgcagcgctt
c--------ggtgctccgcggccctaagtgcagaccggtctcccaaaaaagttgattgtt
c---------------------ggggacggctcgt--------ccagctccgtgtg-ctt
tttctcgacgctcgccctcaaaagctcgtggcacagcccgtgg-tcggacggtggctcg-
------gcttctttgctcgcctccgg----ccgggttcctcgagatttataagtcgtcgg
aaataatac-aacggagtgagtgcctcgaac-tgtttcgac-------------------
---ttcggaccgaaccggtgact---------------------cggtttaaccaatagc
acgtg-----------tcctcctccgggaag-------------------ccgtgcgatc
a-tc---tgtcgacctgagatcagacgagact
>Notophyllum_foliosum_spm_10 1372 bp 
aggtttccgtaggtgaacctgcggaaggatcattatcgaaact-------gacccaaatg
gtttcaaatgtgtggaatg-aaagtcc--------------------gaggaaattcgct
tcctcggcggcggtgccag-tgcctcgggagcgcagtctctcggcacgccagggcatcgt
ggcggcgtcccatggctcggggtcaggcta---cggatcttagtgggagattcgccgacc
cc----------------ggttcgctcggaaggggcgccagtgatctaaaaattgaaac-
-------------------------agcagtgcggggtacctgtcccg-gggaaaaggcc
ctcta--tttttctccggggtgagcaccgttggcgcgcgcctgccctttacw-----cgg
cgcga-----------------tcgtcgtgcgacggttcaaagaggcg-gaccacagtcc
cccttccctcacggcagacctcagacgtggcggcggagggtgatttatcccacccggc-g
agtccgccccgcattgcga-cccctcgcttcgcgagggttttgttttccccacgaactgt
taca-aagtgtgtgaaccatattacgaagc----ttgcgcgtccgtccgttgcccgggcg
t-----cgcaaggcc-aaactttattttccaaag----cctcttcgaggtgagtacgaaa
ag-aaaactactctaagcggtggatcactcggctcgtgtgtcgatgaagagcgcagccag
ctgcgtgaattaatgtgaattgcaggacacattgaacatcgatatcttgaacgcatattg
cggcatcggcttccaccgatgccacgcctgtctcagggtcggtttactatctatcgcccc
cgcgctcctctcggtagcaatgcggatttcacgggcgccttggg-tttcacgcagcgctt
c--------ggtgctccgcggccctaagtgcagaccggtctcccaaaaaagttgattgtt
c---------------------ggggacggctcgt--------ccagctctgtgtg-ctt
tttctcgacgctcgccctcgaaagctcgtggcacagcccgtgg-tcggacggtggctcg-
------gcttctttgctcgcctccgg----ccgggttcctcgagatttataagtcgtcgg
aaataatac-aacggagtgagtgcctcgaac-tttttcgac-------------------
---ttcggaccgaaccggtgact---------------------cggtttaaccaatagc
acgtg-----------tcctcctccgggaag-------------------ccgtgcgatc
attc---tgtcgacctgagatcagacgagact
>Notophyllum_foliosum_spm_2 1369 bp 
aggtttccgtaggtgaacctgcggaaggatcattatcgaaact-------gacccaaatg
gtttcaaatgtgtggaatg-gaagtcc--------------------gaggaaattcgct
tcctcggcggcggtgccag-tgcctcgggagcgcagtctctcggcacgccagggcatcgt
ggcggcgtcccatggctcggggtcaggcta---cggatcttagtgggagattcgccgacc
cc----------------ggttcgctcggaaggggcgccagtgatctaaaaattgaaac-
-------------------------agcagtgcggggtacctgtcccg-ggg-aaaggcc
ctcta--tttttctccggggtgagcaccgttggcgcgcgcctgccc-ttact-----cgg
cgcga-----------------tcgtcgtgcgacggttcaaagaggcg-gaccacagtct
cctttccctcacggcggacctcagacgt---ggcggagggtgatttatcccacccggc-g
agtccgccccgcattgcga-cccctcgcttcgcgagggttttgttttccccacgaactgt
taca-aagtgtgtgaaccatattacgaagc----ttgcgcgtccgtccgttgcccgggcg
t-----cgcaaggcc-aaactttattttccaaag----cctcttcgaggtgagtacgaaa
ag-aaaactactctaagcggtggatcactcggctcgtgtgtcgatgaagagcgcagccag
ctgcgtgaattaatgtgaattgcaggacacattgaacatcgatatcttgaacgcatattg
cggcatcggcttccaccgatgccacgcctgtctcagggtcggtttactatctatcgcccc
cgcgctcctctcggtagcaacgcggatttcacgggcgccttggg-tttcacgcagcgctt
c--------ggtgctccgcggccctaagtgcagaccggtctcccaaaaaagttgattgtt
c---------------------ggggacggctcgt--------ccagctccgtgtg-ctt
tttctcgacgctcgccctcaaaagctcgtggcacagcccgtgg-tcggacggtggctcg-
------gcttctttgctcgcctccgg----ccgggttcctcgaga-ttataagtcgtcgg
aaataacac-aacggagtgagtgcctcgaac-tttttcgac-------------------
---ttcggaccgaaccggtgact---------------------cggtttaaccaatagc
acgtg-----------tcctcctccgggaag-------------------ccgtgcgatc
attc---tgtcgacctgagatcagacgagact
>Notophyllum_foliosum_spm_3 1378 bp 
aggtttccgtaggtgaacctgcggaaggatcattatcgaaact-------gacccaaatg
gtttcaaatgtgtggaatg-gaagtcc--------------------gaggaaattcgct
tcctcggcggcggtgccag-tgcctcgggagcgcagtctctcggcacgccagggcatcgt
ggcggcgtcccatggctcggggtcaggcta---cggatcttagtgggagattcgccgacc
cc----------------ggttcgctcggaaggggcgccagtgatctaaaaattgaaac-
-------------------------agcagtgcggggtacctgtcccg-ggg-aaaggcc
ctcta--tttttctccggggtgaacaccgttggcgcgcgcctgccc-ttact-----cgg
cgcga-----------------tcgtcgtgcgacggttcaaagaggcg-gaccacagtcc
cctttccctcacggcagacctcagacgt---ggcggagggtgatttatcccacccggc-g
agtccgccccgcattgcga-cccctcgcttcgcgagggttttgttttccccacgaactgt
taca-aagtgtgtgaaccatattacgaagc----ttgcgcgtccgtccgttgcccgggcg
t-----cgcaaggcc-aaactttattttccaaag----cctcttcgaggtgagtacgaaa
ag-aaaactactctaagcggtggatcactcggctcgtgtgtcgatgaagagcgcagccag
ctgcgtgaattaatgtgaattgcaggacacattgaacatcgatatcttgaacgcatattg
cggcatcggcttccaccgatgccacgcctgtctcagggtcggtttactatctatcgcccc
cgcgctcctctcggtagcaaygcggatttcacgggcgccttggg-tttcacgcagcgctt
c--------ggtgctccgcggccctaagtgcagaccggtctcccaaaaaagttgattgtt
c---------------------ggggacggctcgt--------ccagctcygtgtg-ctt
tttctcgacgctcgccctcaaaagctcgtggcacagcccgtgg-tcggacggtggctcg-
------gcttctttgctcgcctccgg----ccgggttcctcgaga-ttataagtcgtcgg
aaataayac-aacggagtgagtgcctcgaac-tttttcgac-------------------
---ttcggaccgaaccggtgact---------------------cggtttaaccaatagc
acgtg-----------tcctcctccgggaag-------------------ccgtgcgatc
attc---tgtcgacctgagatcagacgagact
>Notophyllum_foliosum_spm_4 1369 bp 
aggtttccgtaggtgaacctgcggaaggatcattatcgaaact-------gacccaaatg
gtttcaaatgtgtggaatg-aaagtcc--------------------gaggaaattcgct
tcctcggcggcggtgccag-tgcctcgggagcgcagtctctcggcacgccagggcatcgt
ggcggcgtcccatggctcggggtcaggcta---cggatcttagtgggagattcgccgacc
cc----------------ggttcgctcggaaggggcgccagtgatctaaaaattgaaac-
-------------------------agcagtgcggggtacctgtcccg-gggaaaaggcc
ctctatttttttctccggggtgagcaccgttggcgcgcgcctgccctttact-----cgg
cgcga-----------------tcgtcgtgcgacggttcaaagaggcg-gaccacagtcc
cctttccctcacggcagacctcagacgt---ggcggagggtgatttatcccacccggc-g
agtccgccccgcattgcga-cccctcgcttcgcgagggttttgttttccccacgaactgt
taca-aagtgtgtgaaccatattacgaagc----ttgcgcgtccgtccgttgcccgggcg
t-----cgcaaggcc-aaactttattttccaaag----cctcttcgaggtgagtacgaaa
ag-aaaactactctaagcggtggatcactcggctcgtgtgtcgatgaagagcgcagccag
ctgcgtgaattaatgtgaattgcaggacacattgaacatcgatatcttgaacgcatattg
cggcatcggcttccaccgatgccacgcctgtctcagggtcggtttactatctatcgcccc
cgcgctcctctcggtagcaacgcggatttcatgggcgccttggg-tttcacgcagcgctt
c--------ggtgctccgcggccctaagtgcagaccggtctcccaaaaaagttgattgtt
c---------------------ggggacggctcgt--------ccagctccgtgtg-ctt
tttctcgacgctcgccctcaaaagctcgtggcacagcccgtgg-tcggacggtggctcg-
------gcttctttgctcgcctccgg----ccgggttcctcgaga-ttataagtcgtcgg
aaataatac-aacggagtgagtgcctcgaac-tttttcgac-------------------
---ttcggaccgaaccggtgact---------------------cggtttaaccaatagc
acgtg-----------tcctcctccgggaag-------------------ccgtgcgatc
attc---tgtcgacctgagatcagacgagact
>Notophyllum_foliosum_spm_5 1372 bp 
aggtttccgtaggtgaacctgcggaaggatcattatcgaaact-------gacccaaatg
gtttcaaatgtgtggaatg-aaagtcc--------------------gaggaaattcgct
tcctcggcggcggtgccag-tgcctcgggagcgcagtctctcggcacgccagggcatcgt
ggcggcgtcccatggctcggggtcaggcta---cggatcttagtgggagattcgccgacc
cc----------------ggttcgctcggaaggggcgccagtgatctaaaaattgaaac-
-------------------------agcagtgcggggtacctgtcccg-ggg-aaaggcc
ctcta-ttttttctccggggtgagcaccgttggcgcgcgcctgccctttacw-----cgg
cgcga-----------------tcgtcgtgcgacggttcaaagaggcg-gaccacagtcc
cctttccctcacggcagacctcagacgt---ggcggagggtgatttatcccacccggc-g
agtccgccccgcattgcga-cccctcgcttcgcgagggttttgttttccccacgaactgt
taca-aagtgtgtgaaccatattacgaagc----ttgcgcgtccgtccgttgcccgggcg
t-----cgcaaggcc-aaactttattttccaaag----cctcttcgaggtgagtacgaaa
ag-aaaactactctaagcggtggatcactcggctcgtgtgtcgatgaagagcgcagccag
ctgcgtgaattaatgtgaattgcaggacacattgaacatcgatatcttgaacgcatattg
cggcatcggcttccaccgatgccacgcctgtctcagggtcggtttactatctatcgcccc
cgcgctcctctcggtagcaacgcggatttcatgggcgccttggg-tttcacgcagcgctt
c--------ggtgctccgcggccctaagtgcagaccggtctcccaaaaaagttgattgtt
c---------------------ggggacggctcgt--------ccagctctgtgtg-ctt
tttctcgacgctcgccctcaaaagctcgtggcacagcccgtgg-tcggacggtggctcg-
------gcttctttgctcgcctccgg----ccgggttcctcgaga-ttataagtcgtcgg
aaataatac-aacggagtgagtgcctcgaac-tttttcgac-------------------
---ttcggaccgaaccggtgact---------------------cggtttaaccaatagc
acgtg-----------tcctcctccgggaag-------------------ccgtgcgatc
attc---tgtcgacctgagatcagacgagact
>Notophyllum_foliosum_spm_6 1369 bp 
aggtttccgtaggtgaacctgcggaaggatcattatcgaaact-------gacccaaatg
gtttcaaatgtgtggaatg-aaagtcc--------------------gaggaaattcgct
tcctcggcggcggtgccag-tgcctcgggagcgcagtctctcggcacgccagggcatcgt
ggcggcgtcccatggctcggggtcaggcta---cggatcttagtgggagattcgccgacc
cc----------------ggttcgctcggaaggggcgccagtgatctaaaaattgaaac-
-------------------------agcagtgcggggtacctgtcccg-gggaaaaggcc
ctcta--tttttctccggggtgagcaccgttggcgcgcgcctgccctttact-----cgg
cgcga-----------------tcgtcgtgcgacggttcaaagaggcg-gaccacagtcc
cccttccctcacggcagacctcagacgtggcggcggagggtgatttatcccacccggc-g
agtccgccccgcattgcga-cccctcgcttcgcgagggttttgttttccccacgaactgt
taca-aagtgtgtgaaccatattacgaagc----ttgcgcgtccgtccgttgcccgggcg
t-----cgcaaggcc-aaactttattttccaaag----cctcttcgaggtgagtacgaaa
ag-aaaactactctaagcggtggatcactcggctcgtgtgtcgatgaagagcgcagccag
ctgcgtgaattaatgtgaattgcaggacacattgaacatcgatatcttgaacgcatattg
cggcatcggcttccaccgatgccacgcctgtctcagggtcggtttactatctatcgcccc
cgcgctcctctcggtagcaatgcggatttcacgggcgccttggg-tttcacgcagcgctt
c--------ggtgctccgcggccctaagtgcagaccggtctcccaaaaaagttgattgtt
c---------------------ggggacggctcgt--------ccagctccgtgtg-ctt
tttctcgacgctcgccctcaaaagctcgtggcacagcccgtgg-tcggacggtggctcg-
------gcttctttgctcgcctccgg----ccgggttcctcgagatttataagtcgtcgg
aaataatacaaacggagtgagtgcctcgaac-tttttcgac-------------------
---ttcggaccgaaccggtgact---------------------cggtttaaccaatagc
acgtg-----------tcctcctccgggaag-------------------ccgtgcgatc
attc---tgtcgacctgagatcagacgagact
>Notophyllum_foliosum_spm_7 1369 bp 
aggtttccgtaggtgaacctgcggaaggatcattatcgaaact-------gacccaaatg
gtttcaaatgtgtggaatg-aaagtcc--------------------gaggaaattcgct
tcctcggcggcggtgccag-tgcctcgggagcgcagtctctcggcacgccagggcatcgt
ggcggcgtcccatggctcggggtcaggcta---cggatcttagtgggagattcgccgacc
cc----------------ggttcgctcggaaggggcgccagtgatctaaaaattgaaac-
-------------------------agcagtgcggggtacctgtcccg-gggaaaaggcc
ctcta--tttttctccggggtgagcaccgttggcgcgcgcctgccctttact-----cgg
cgcga-----------------tcgtcgtgcgacggttcaaagaggcg-gaccacagtcc
cccttccctcacggcagacctcagacgtggcggcggagggtgatttatcccacccggc-g
agtccgccccgcattgcga-cccctcgcttcgcgagggttttgttttccccacgaactgt
taca-aagtgtgtgaaccatattacgaagc----ttgcgcgtccgtccgttgcccgggcg
t-----cgcaaggcc-aaactttattttccaaag----cctcttcgaggtgagtacgaaa
agaaaaactactctaagcggtggatcactcggctcgtgtgtcgatgaagagcgcagccag
ctgcgtgaattaatgtgaattgcaggacacattgaacatcgatatcttgaacgcatattg
cggcatcggcttccaccgatgccacgcctgtctcagggtcggtttactatctatcgcccc
cgcgctcctctcggtagcaatgcggatttcacgggcgccttggg-tttcacgcagcgctt
c--------ggtgctccgcggccctaagtgcagaccggtctcccaaaaaagttgattgtt
c---------------------ggggacggctcgt--------ccagctccgtgtg-ctt
tttctcgacgctcgccctcaaaagctcgtggcacagcccgtgg-tcggacggtggctcg-
------gcttctttgctcgcctccgg----ccgggttcctcgagatttataagtcgtcgg
aaataatac-aacggagtgagtgcctcgaac-tttttcgac-------------------
---ttcggaccgaaccggtgact---------------------cggtttaaccaatagc
acgtg-----------tcctcctccgggaag-------------------ccgtgcgatc
attc---tgtcgacctgagatcagacgagact
>Notophyllum_foliosum_spm_8 1375 bp 
aggtttccgtaggtgaacctgcggaaggatcattatcgaaact-------gacccaaatg
gtttcaaatgtgtggaatg-aaagtcc--------------------gaggaaattcgct
tcctcggcggcggtgccag-tgcctcgggagcgcagtctctcggcacgccagggcatcgt
ggcggcgtcccatggctcggggtcaggcta---cggatcttagtgggagattcgccgacc
cc----------------ggttcgctcggaaggggcgccagtgatctaaaaattgaaac-
-------------------------agcagtgcggggtacctgtcccg-gggaaaaggcc
ctcta--tttttctccggggkgagcaccgttggcgcgcgcctgccctttact-----cgg
cgcga-----------------tcgtcgtgcgacggttcaaagaggcg-gaccacagtcc
cccttccctcacggcagacctcagacgtggcggcggagggtgatttatcccacccggc-g
agtccgccccgcattgcga-cccctcgcttcgcgagggttttgttttccccacgaactgt
taca-aagtgtgtgaaccatattacgaagc----ttgcgcgtccgtccgttgcccgggcg
t-----cgcaaggcc-aaactttattttccaaag----cctcttcgaggtgagtacgaaa
ag-aaaactactctaagcggtggatcactcggctcgtgtgtcgatgaagagcgcagccag
ctgcgtgaattaatgtgaattgcaggacacattgaacatcgatatcttgaacgcatattg
cggcatcggcttccaccgatgccacgcctgtctcagggtcggtttactatctatcgcccc
cgcgctcctctcggtagcaatgcggatttcacgggcgccttggg-tttcacgcagcgctt
c--------ggtgctccgcggccctaagtgcagaccggtctcccaaaaaagttgattgtt
c---------------------ggggacggctcgt--------ccagctctgtgtg-ctt
tttctcgacgctcgccctcaaaagctcgtggcacagcccgtgg-tcggacggtggctcg-
------gcttctttgctcgcctccgg----ccgggttcctcgaga-ttataagtcgtcgg
aaatartac-aacggagtgagtgcctcgaac-tttttcgac-------------------
---ttcggaccgaaccggtgact---------------------cggtttaaccaatagc
acgtg-----------tcctcctccgggaag-------------------ccgtgcgatc
attc---tgtcgacctgagatcagacgagact
>Notophyllum_foliosum_spm_9 1369 bp 
aggtttccgtaggtgaacctgcggaaggatcattatcgaaact-------gacccaaatg
gtttcaaatgtgtggaatg-aaagtcc--------------------gaggaaattcgct
tcctcggcggcggtgccag-tgcctcgggagcgcagtctctcggcacgccagggcatcgt
ggcggcgtcccatggctcggggtcaggcta---cggatcttagtgggagattcgccgacc
cc----------------ggttcgctcggaaggggcgccagtgatctaaaaattgaaac-
-------------------------agcagtgcggggtacctgtcccg-ggg-aaaggcc
ctcta--tttttctccggggtgagcaccgttggcgcgcgcctgccc-ttact-----cgg
cgcga-----------------tcgtcgtgcgacggttcaaagaggcg-gaccacagtcc
cccttccctcacggcagacctcagacgt---ggcggagggtgatttatcccacccggc-g
agtccgccccgcattgcga-cccctcgcttcgcgagggttttgttttccccacgaactgt
taca-aagtgtgtgaaccatattacgaagc----ttgcgcgtccgtccgttgcccgggcg
t-----cgcaaggcc-aaactttattttccaaag----cctcttcgaggtgagtacgaaa
ag-aaaactactctaagcggtggatcactcggctcgtgtgtcgatgaagagcgcagccag
ctgcgtgaattaatgtgaattgcaggacacattgaacatcgatatcttgaacgcatattg
cggcatcggcttccaccgatgccacgcctgtctcagggtcggtttactatctatcgcccc
cgcgctcctctcggtagcaatgcggatttcacgggcgccttggg-tttcacgcagcgctt
c--------ggtgctccgcggccctaagtgcagaccggtctcccaaaaaagttgattgtt
c---------------------ggggacggctcgt--------ccagctctgtgtg-ctt
tttctcgacgctcgccctcaaaagctcgtggcacagcccgtgg-tcggacggtggctcg-
------gcttctttgctcgcctccgg----ccgggttcctcgagatttataagtcgtcgg
aaataatac-aacggagtgagtgcctcgaac-tttttcgac-------------------
---ttcggaccgaaccggtgact---------------------cggtttaaccaatagc
acgtg-----------tcctcctccgggaag-------------------ccgtgcgatc
attc---tgtcgacctgagatcagacgagact
>Paranaitisi_katoi_EU431132 1369 bp 
aggtttccgtaggtgaacctgcggaaggatcattaccgaaactcgcaaactgccgagaca
cttgtaggt-----ggttgctaagtcctctcctcatcgccttggggggaggcggccgggc
gctcgcgagactttgcttgctgcttcggcgacggctgcacccatgattc-----cacccc
gccctcttgtcgctatcagggctgtggctgcatcgagtctcacagtgggtacgaaagact
cccatgagcccagtccaggggttggatgccggaagggtccgtaagccaatatttgatttt
acaccattgcctgatgtgaacaacgatcgttgcggggtacctgactcgatcgggtacgcc
ccgga-----------ggggagagcaccgttggcacacggccctttttttttgtcagtcg
ctcgacaagagagggccggaccgtgccgtgcgacggtttaaagagacgacgccgcagcct
gctgacagtggcgg--attttcggattc---gccaaacgaggcagttccccacctggctt
agtccgccccgcatcg----tttcgttgtttgcgaacacctttttttcccaacatactgt
tttc-tgtaccggttatca-aaaacaagga----ccgcgcgtccgtccgttgcccgggcg
t-----ggcggtgccgaaacttttcgttccccag----c-------------ggacgaga
aa-gaaattactctaagcggtggatcactcggctcgtgtgtcgatgaagagcgcagccag
ctgcgtgaattaatgtgaattgcaggacacattgaacatcgatatcttgaacgcatattg
cggcatcggcccacaccgatgccacgcctgtctcagggtcggtttactagcaatcgtttc
ggattttcc----------------aattcgcaaacgccttgag-cctgtcgcagtttcc
c--tcgccggaaactccgtcgctctaaatgcagaccggtctccc-tcagcgcacatcaca
ctgcgcctcgttttccttagcgggggacggctcgt----------------------cct
ctttctg----ccggtttcgcggacaagcagaccagcggaaatctcggacggcggctcga
tttgtactttttgtgctcgcctccggatcaccgcgacacttgctttttttgt--------
-----------------------ccacgaactcgtccccgcatatttaaggagaggtttg
cggttcgtgtcgctcgagcgact---------------------tagcaccgttgttggg
gtctctgcgtgttgttttctccactcggaaaaacaattttcgcgagactttcaaacaata
tctcacttgtcgacctgagatcagacgagact
