>Amauroderma_rude_var__intermedium_X78753_X78774 Amauroderma_rude_var._intermedium_X78753_X78774 673 bp 
-------------------------ggaaggatcattatcgagtcttgaccgggttgtag
ctggccttccgaggcatgtgcacgccctgctcatccact-ctacacctgtgaacttactg
tgggtttcata--tcgtgaagcgtgtcgtttaac---ggctcgtgaagc----ggtctg-
tgcctgcgtttattacaaacccttgtaaagtaatagaacgtgtattgcgatgtaacgcat
ctatatacaactttcagcaacggatctcttg-----------------------------
------------------------------------------------------------
---------------------------------------tcatgaaatcttcaacctaaa
agcct-ttgcgggtttgttaggcttggacttggaggc-ttgtcggctc----attagtcg
gctcctcttaaatgcattagcttgg-ttccttgcggatcggc-tgtcggtgtgataattg
tcaacgccgcgaccgtgaagcg---tttggcgagcttctaaccgtctcg--ttagagaca
gattattgacctctg---------------------------------------------
----------
>Ganoderma_adspersum_X78742_X78763 Ganoderma_adspersum_X78742_X78763 673 bp 
-------------------------ggaaggatcattatcgagttttgactgggttgtag
ctggccttacgaggcatgtgcacgccctgctcatccgctcctacacctgtgcacttactg
tgggtttacgag-tcgcgaaacaggcccgttcattcgggcttgtggagc---gcacttgt
tgcctgcttttatcacaaactc-tataaagtattagaatgtgtattgcgatgtaacgcat
ctatatacaactttcagcaacggatctcttg-----------------------------
------------------------------------------------------------
---------------------------------------tcatgaaatcttcaacttacg
agcttcttgcgaggtttgtagggttggacttggaggc-ttgtcgg-tcttt-aaaggtcg
gctcctcttaaatgcattagcttgg-ttccttgcggatcgggttgtcggtgtgataa-tg
tctacg-cgcgaccgt-aagcg---tttggcaagcttctaaccgtctcggtatagagaca
agtttatgacctctg---------------------------------------------
----------
>Ganoderma_australe_AJ627590_AJ627591 Ganoderma_australe_AJ627590_AJ627591 673 bp 
--------------------------------------tcgagttttgactgggttgtag
ctggccttccgaggcacgtgcacgccctgctcatccact-ctacacctgtgcacttactg
tgggtttacggg-tcgcgaaacgggctcgtttattcgggcttgtggagc---gcacttgt
tgcctgcgtttatcacaaactc-cataaagtattagaatgtgtattgcgatgtaacgcat
ctatat------------------------------------------------------
------------------------------------------------------------
--------------------------------------------aaatcttcaacttaca
agctctttgcggggtttgtaggcttggacttggaggc-ttgtcgg-cctttaaatggtcg
gctcctcttaaatgcattagcttgatttccttgcggatcggc-tgtcggtgtgataa-tg
tctactccgcgaccgtgaagcg---tttggcaagcttctaaccgtctcgttacagagaca
gcttta------------------------------------------------------
----------
>Ganoderma_incrassatum_DAR73783 673 bp 
--------------------------------------tcgagttctgactgggttgtag
ctggccttccgaggcatgtgcacgccctgctcatccact-ctacacctgtgcacttactg
tgggtttacggg-tcgtgaaacgggctcgtttattcgggcttgttgagc---gcacttgt
tgcccgcgtttatcacaaactc-tataaagtatcagaatgtgtattgcgatgtaacgcat
ctatat------------------------------------------------------
------------------------------------------------------------
--------------------------------------------aaatcttcaatctaca
aacttcttatggggcttgtaggcttggacttggaggc-ttgtcggtcctttacaaggtcg
gctcctcttaaatgcattagcttgg-ttccttgcggatcggcttgtcggtgtgataa-tg
tctacgccgcgaccgtgaagcgtgtttgggcgagcttctaatccgttcgttacagaga-a
ccttta------------------------------------------------------
----------
>Ganoderma_lobatum_X78740_X78761 Ganoderma_lobatum_X78740_X78761 673 bp 
-------------------------ggaaggatcattatcgagttttgactgggttgtag
ctggccttccgaggcatgtgcacgccctgctcatccgct-ctacacctgtgcacttactg
tgggttacagga-tcgcgaaacggg-cactttacggggc--tccggagc----ggcttg-
tgcccgcgtttatcacaaaccc-catgaagtattagaatgtgtattgcgatgtaacgcat
ctatatacaactttcagcaacggatctcttg-----------------------------
------------------------------------------------------------
---------------------------------------tcatgaaatcttcaacttacg
agcttcttgcgaggtttgtaggcttggac-tggaggc-ttgtcgg-tcttt-acaggtcg
gctcctcttaaatgcattagcttgg-ttccttgcggatcgggttgtcggtgtgatac-tg
tctacgcgg----acttaagca---tttggcaagcttctaaccgtctcggtatagagaca
agtttatgacctctg---------------------------------------------
----------
>Ganoderma_lucidum_AF094511_AF044490 Ganoderma_lucidum_AF094511_AF044490 673 bp 
---------------------------aaggatcattatcgagttctgactgggttgtag
ctggccttcctaggctcgtgcacgccctgctcatccact-ctacacctgtgcacttactg
tgggtttcagat-cagtgaagcgtg-ctccttgcggggc-ttcgtgaag---gcgtctg-
tgcctgcgtttatcacaaactc-tataaagtattagaatgtgtattgcgatgtaacgcat
ctatatacaactttcagcaacggatctcttg-----------------------------
------------------------------------------------------------
---------------------------gctctcgcatcgtcatgaaatcttcaacctaca
agcct-ttgcggg-tttgtaggcttggatttggaggc-ttgtcggcccttt-gtcggtcg
gctcctcttaaatgcattagcttga-tt-cttgcggatcggc-tctcggtgtgataa-tg
tctacgccgcgaccgtgaagcg---tttggcgagcttctaaccgtcttcgcttgaagaca
gctttatgacctctgacctcaaatcaggtaggactacccgctgaacttaagctatcaata
a---------
>Ganoderma_lucidum_BCRC36123 679 bp 
acaaggtttccgtaggtgaacctgcggaaggatcattatcgagttttgactgggttgtag
ctggccttccgaggcatgtgcacgccctgctcatccact-ctacacctgtgcacttactg
tgggcttcaga--tcgtaaaacgggtccctttaccgggc-ttgcggagc---gtgtctg-
tgcctgcgtttatcacaaactc-tataaagtatcagaatgtgtattgcgatgtaacgcat
ctatatacaactttcagcaacggatctcttggctctcgcatcgatgaagaacgcagcgaa
atgcgataagtaatgtgaattgcagaattcagtgaatcatcgaatctttgaacgcacctt
gcgctccttggtattccgaggagcatgcctgtttgagtgtcatgaaatcttcaacctgca
agctt-ttgtgg--tttgtaggcttggacttggaggc-ttgtcgg-ccgtt-ctyggtcg
gctcctcttaaatgcattagcttgg-ttccttgcggatyggc-tctcagtgtgataa-tg
tctacgctgcgaccgtgaagcg---tttggcgagcttctaaccatc-tcagttggagaca
actttatgacctctgacctcaaatcaggtaggactacccgctgaacttaagcata-----
----------
>Ganoderma_lucidum_BCRC37033 673 bp 
----------------------tgcggaaggatcattatcgagttttgactgggttgtag
ctggccttccgaggcatgtgcacgccctgctcatccact-ctacacctgtgcacttactg
tgggcttcaga--tcgtaaaacgggtccctttaccgggc-ttgcggagc---gtgtctg-
tgcctgcgtttatcacaaactc-tataaagtatcagaatgtgtattgcgatgtaacgcat
ctatatacaactttcagcaacggatctcttggctctcgcatcgatgaagaacgcagcgaa
atgcgataagtaatgtgaattgcagaattcagtgaatcatcgaatctttgaacgcacctt
gcgctccttggtattccgaggagcatgcctgtttgagtgtcatgaaatcttcaacctgca
agctt-ttgtgg--tttgtaggcttggacttggaggc-ttgtcgg-ccgtt-gtcggtcg
gctcctcttaaatgcattagcttgg-ttccttgcggatcggc-tctcagtgtgataa-tg
tctacgctgcgaccgtgaagcg---tttggcgagcttctaaccgtc-tcagttggagaca
actttatgacctctgacctcaaatcaggtaggactacccgctgaacttaagcatatcaat
aa--------
>Ganoderma_lucidum_BCRC37043 673 bp 
-------tccgtagggtgaacctgcggaaggatcattatcgagttttgactgggttgtag
ctggccttccgaggcatgtgcacgccctgctcatccact-ctacacctgtgcacttactg
tgggcttcaga--tcgtaaaacgggtccctttaccgggc-ttgcggagc---gtgtctg-
tgcctgcgtttatcacaaactc-tataaagtatcagaatgtgtattgcgatgtaacgcat
ctatatacaactttcagcaacggatctcttggctctcgcatcgatgaagaacgcagcgaa
atgcgataagtaatgtgaattgcagaattcagtgaatcatcgaatctttgaacgcacctt
gcgctccttggtattccgaggagcatgcctgtttgagtgtcatgaaatcttcaacctgca
agctt-ttgtgg--tttgtaggcttggacttggaggc-ttgtcgg-ccgtt-ctcggtcg
gctcctcttaaatgcattagcttgg-ttccttgcggatcggc-tctcagtgtgataa-tg
tctacgctgcgaccgtgaagcg---tttggcgagcttctaaccgtc-tcagttggagaca
actttatgacctctgacctcaaatcaggtaggactacccgctgaacttaagcatatcaat
aagcggagga
>Ganoderma_lucidum_CWN01740 673 bp 
-------------------------------------atcgagttttgactgggttgtag
ctggccttccgaggcatgtgcacgccctgctcatccact-ctacacctgtgcacttactg
tgggcttcaga--tcgtaaaacgggtccctttaccgggc-ttgcggagc---gtgtctg-
tgcctgcgtttatcacaaactc-tataaagtatcagaatgtgtattgcgatgtaacgcat
ctatatacaactttcagcaacggatctcttggctctcgcatcgatgaagaacgcagcgaa
atgcgataagtaatgtgaattgcagaattcagtgaatcatcgaatctttgaacgcacctt
gcgctccttggtattccgaggagcatgcctgtttgagtgtcatgaaatcttcaacctgca
agctt-ttgtgg--tttgtaggcttggacttggaggc-ttgtcgg-ccgtt-ctcggtcg
gctcctcttaaatgcattagcttgg-ttccttgcggatcggc-tctcagtgtgataa-tg
tctacgctgcgaccgtgaagcg---tttggcgagcttctaaccgtc-tcagttggagaca
actttatgacctctgacctcaaatcaggtaggactacccgctgaacttaagcatatcata
----------
>Ganoderma_lucidum_X78745_X78766 Ganoderma_lucidum_X78745_X78766 673 bp 
-------------------------ggaaggatcattatcgagttttgactgggttgtag
ctggccttccgaggcatgtgcacgccctgctcatccact-ctacacctgtgcacttactg
tgggcttcaga--tcgtaaaacgggtccctttaccgggc-ttgcggagc---gtgtctg-
tgcctgcgtttatcacaaactc-tataaagtatcagaatgtgtattgcgatgtaacgcat
ctatatacaactttcagcaacggatctcttg-----------------------------
------------------------------------------------------------
---------------------------------------tcatgaaatcttcaacctgca
agctt-ttgtgg--tttgtaggcttggacttggaggc-ttgtcgg-ccgtt-gttggtcg
gctcctcttaaatgcattagcttgg-ttccttgcggatcggc-tctcagtgtgataa-tg
tctacgctgcgaccgtgaagcg---tttggcgagcttctaaccgtc-tcagttggagaca
actttatgacctctg---------------------------------------------
----------
>Ganoderma_lucidum_X87351_X87361 Ganoderma_lucidum_X87351_X87361 673 bp 
--------------------cctgcggaaggatcattatcgagttttgactgggttgtag
ctggccttccgaggcatgtgcacgccctgctcatccact-ctacacctgtgcacttactg
tgggcttcaga--tcgtaaaacgggtccctttaccgggc-ttgc-gagc---gtgtctg-
tgcctgcgtttatcacaaactc-tataaagtatcagaatgtgtattgcgatgtaac-cat
ctatatacaactttcagcaacggatctctt------------------------------
------------------------------------------------------------
---------------------------------------tcatgaaatcttcaacctgca
agctt-ttgtgg--tttgtaggcttggacttggaggc-ttgtcgg-ccgtt-gttggtcg
gctcctcttaaatgcattagcttgg-ttccttgcggatcggc-tctcagtgtgataa--g
tctacgctgcgaccgtgaagcg---tttggcgagcttctaaccgtc-tcagttggagaca
actttatgacctctg---------------------------------------------
----------
>Ganoderma_lucidum_X87354_X87364 Ganoderma_lucidum_X87354_X87364 673 bp 
--------------------cctgcggaaggatcattatcgagttttgaccgggttgtag
ctggccttccgaggcatgtgcacgccctgctcatccact-ctacacctgtgcacttactg
tgggcttcaga--ttgcgaggcacg-ctctttaccgggc-ttgcggagc---atatctg-
tgcctgcgtttatcacaaactc-tataaagtaacagaatgtgtattgcgatgtaac-cat
ctatatacaactttcagcaacggatctctt------------------------------
------------------------------------------------------------
---------------------------------------tcatgaaatcttcaacctaca
agctt-ttgtgg--tttgtaggcttggacttggaggc-ttgtcgg-ccgtt-atcggtcg
gctcctcttaaatgcattagcttgg-ttccttgcggatcggc-tctcggtgtgataa-tg
tctacgccgcgaccgtgaagcg---tttggcgagcttctaaccgtc----ttataagaca
gctttatgacctctg---------------------------------------------
----------
>Ganoderma_lucidum_Z37049_Z37099 Ganoderma_lucidum_Z37049_Z37099 673 bp 
-------------------------ggaaggatcattatcgagttctgactgggttgtag
ctggccttccgaggcacgtgcacg-cctgctcatccact-ctacacctgtgcacttactg
tgggtttcaga--ctgtgaagcg---tcccttgcggggcttcgtgaagc---gcgtctg-
tgcctgcgtttatcacaaactc-tataaagtattagaatgtgtattgcgatgtaacgcat
ctatatacaactttcagcaacggatctcttg-----------------------------
------------------------------------------------------------
---------------ccgaggagcatgcctgtttgagtgtcatgaaatctt--aactaca
agcct-ttgcgg--tttgtaggcttggacttggaggc-ttgtcgg-ccttt-gtcggtcg
gctcctcttaaatgcattagcttga-ttccttgcggatcggc-tctcggtgtgataa-tg
tctacgccgcgaccgtgaagcg---tttggcgagcttctaaccgtcttcgcttgaagaca
gctttatgacctctg---------------------------------------------
----------
>Ganoderma_lucidum_Z37050_Z37074 Ganoderma_lucidum_Z37050_Z37074 676 bp 
-------------------------ggaaggatcattatcgagttttgaccgggttgtag
ctggccttccgaggcatgtgcacgccctgctcatccact-ctacacctgtgcacttactg
tgggcttcaga--ttgcgaggcacg-ctctttaccgggc-ttgcggagc---atatctg-
tgcctgcgtttatcacaaactc-tataaagtaacagaatgtgtattgcgatgtaacacat
ctatatacaactttcagcaacggatctcttg-----------------------------
------------------------------------------------------------
---------------ccgaggagcatgcctgtttgagtgtcatgaaatct---aactaca
agctt-ttgtgg--tttgtaggcttggacttggaggc-ttgtcgg-ccgtt-atcggtcg
gctcctcttaaatgcattagcttgg-ttccttgcggatcggc-tctcggtgtgataa-tg
tctacgccgcgaccgtgaagcg---tttggcgagcttctaacygtc----ttataagaca
gctttatgacc-------------------------------------------------
----------
>Ganoderma_lucidum_Z37096_Z37073 Ganoderma_lucidum_Z37096_Z37073 673 bp 
-------------------------ggaaggatcattatcgagttctgactgggttgtag
ctggccttccgaggcacgtgcacgccctgctcatccact-ctacacctgtgcacttactg
tgggtttcagat-ctgtgaagcg----tccttgcggggcttcgtgaagc---gcgtctg-
tgcctgcgtttatcacaaactc-tataaagtattagaatgtgtattgcgatgtaacgcat
ctatatacaactttcagcaacggatctcttg-----------------------------
------------------------------------------------------------
---------------ccgaggagcatgcctgtttgagtgtcatgaaatctt--aactaca
agcct-ttgcgg--tttgtaggcttggacttggaggc-ttgtcggcccttt-gtcggtcg
gctcctcttaaatgcattagcttga-ttccttgcggatcggc-tctcggtgtgataa-tg
tctacgccgcgaccgtgaagcg---tttggcgagcttctaaccgtcttcgcttgaagaca
gctttatgacc-------------------------------------------------
----------
>Ganoderma_philippii_AJ608714_AJ608715 Ganoderma_philippii_AJ608714_AJ608715 673 bp 
---------------------------------------cgag-tttgactgggttgtag
ctggccttcc-aggcatgtgcacgccccgctcatccact-ctacacctgtgcactcactg
tgggcttcaga--tcgtgaagcggg-ctctttgctgggc-ttgtgaagc---gtgtctg-
tgcctgcgtttattacaaactc-tataaagtatcagaatgtgtattgcgatgtaacgcat
ctatat------------------------------------------------------
------------------------------------------------------------
--------------------------------------------aaatcttcaacctaca
agctt-ttgtggt-tttgtaggcttggacttggaggc-ttgtcgg-ccgtt-ctcggtcg
gctcctcttaaatgcatcagcttgg-ttccttgcggatcggc-tctcggtgtgataa-tg
tctacgccgcgaccgtgaagcg---tttggcgagcttctaaccgtc-tcagttgaagaca
gcttta------------------------------------------------------
----------
>Ganoderma_resinaceum_X78737_X78758 Ganoderma_resinaceum_X78737_X78758 673 bp 
-------------------------ggaaggatcattatcgagttttgactgggttgtag
ctggccttccgaggcatgtgcacaccctgctcatccact-ctacacctgtgcacttactg
tgggttccagacgttgtgaagcggg-ctctttacggtgc-ttgtaaagcggcgtgcctg-
tgcctgcgtttatcacaaactc-tataaagtattagaatgtgtattgcgatgtaacgcat
ctatatacaactttcagcaacggatctcttg-----------------------------
------------------------------------------------------------
---------------------------------------tcatgaaatcttcaacttaca
gacct-ttgcggg-tttgtaggcttggactttgaggc-ttgtcggccatgt-tttggtcg
gctcctcttaaatgtattagcttga-ttccttgcggatcggc-tctcggtgtgataa-tg
tctacg-cgcgaccgtgaagcg--ttttggcgagcttctaaccgtctcgtttgtgagaca
gctttatgacctctg---------------------------------------------
----------
>Ganoderma_steyaertanum_DAR73779 Ganoderma_steyaertanum_DAR73779 673 bp 
--------------------------------------tcgagttttgactgggttgtag
ctggccttccgaggcatgtgcacgccctgctcatccgct-ctacacctgtgcacttagtg
tgggcttcaga--tcgtaaaacgggtccctttaccgggc-ttgcggagc---gtgtctg-
tgcccgcgtttatcacaaactc-tataaagtatcagaatgtgtatcgcgatgtaacgcat
ctatat------------------------------------------------------
------------------------------------------------------------
--------------------------------------------aaatcttcaacctaca
agctt-ttgtgg--tttgtaggcttggacttggaggctttgtcgg-ccgct-cttggccg
gctcctcttaaatgcattagcttgg-ttccttgcggatcggc-tctcggtgtgataa-ta
tctacgctgcgaccgtgaagcg---tttggcgagcttctaaccgtc-tcagttggaga--
acttta------------------------------------------------------
----------
>Ganoderma_steyaertanum_DAR73780 Ganoderma_steyaertanum_DAR73780 673 bp 
--------------------------------------tcgagttttgactgggttgtag
ctggccttccgaggcatgtgcacgccctgctcatccgct-ctacacctgtgcacttagtg
tgggcttcaga--tcgtaaaacgggtccctttaccgggc-ttgcggagc---gtgtctg-
tgcccgcgtttatcacaaactc-tataaagtatcagaatgtgtatcgcgatgtaacgcat
ctatat------------------------------------------------------
------------------------------------------------------------
--------------------------------------------aaatcttcaacctaca
agctt-ttgtgg--tttgtaggcttggacttggaggctttgtcgg-ccgct-cttggccg
gctcctcttaaatgcattagcttgg-ttccttgcggatcggc-tctcggtgtgataa-ta
tctacgctgcgaccgtgaagcg---tttggcgagcttctaaccgtc-tcagttggaga--
acttta------------------------------------------------------
----------
>Ganoderma_steyaertanum_QFRI8647_1 Ganoderma_steyaertanum_QFRI8647.1 673 bp 
--------------------------------------tcgagttttgactgggttgtag
ctggccttccgaggcatgtgcacgccctgctcatccgct-ctacacctgtgcacttagtg
tgggcttcaga--tcgtaaaacgggtccctttaccgggc-tcgcggagc---gtgtctg-
tgcccgcgtttatcacaaactc-tataaagtatcagaatgtgtatcgcgatgtaacgcat
ctatat------------------------------------------------------
------------------------------------------------------------
--------------------------------------------aaatcttcaacctaca
agctt-ttgtgg--tttgtaggcttggacttggaggc-ttgtcgg-ccgtt-cttggccg
gctcctcttaaatgcattagcttgg-ttccttgcggatcggc-tctcggtgtgataa-ta
tctacgctgcgaccgtgaagcg---tttggcgagcttctaaccgtc-tcagttggaga--
acttta------------------------------------------------------
----------
>Ganoderma_subamboinense_var__laevisporum_X78736_X78757 Ganoderma_subamboinense_var._laevisporum_X78736_X78757 673 bp 
-------------------------ggaaggatcattatcgagttttgactgggttgtag
ctggccttccgaggcatgtgcacgccctgctcatccact-ctacacctgtgcacttactg
tgggcttcagacgtcgcgaagcggg-ctctttactgagc-ctgtagagcag-gtgtctg-
tgcctgcgtttatcacaaactc-cataaagtattagaatgtgtattgcgatgtaacgcat
ctatatacaactttcagcaacggatctcttg-----------------------------
------------------------------------------------------------
---------------------------------------tcatgaaatcttcaacttaca
gacct-ttgcggg-tttgtaggcttggactt-gaggc-ttgtggc-cgtgt-ttcggccg
gctcctcttaaatgcattagcttga-ttccttgcggatcggc-tctcggtgtgataa-tg
tctacgccgcgaccgtgaagcg--ttttggcgagcttctaaccgtcctcgttt--ggaca
gctttatgacctctg---------------------------------------------
----------
>Ganoderma_tropicum_BCRC37122 676 bp 
-------ttccgtaggtgaacctgcggaaggatcattatcgagtcttgactgggttgtag
ctggccttccgaggcatgtgcacgccctgctcatccact-ctacacctgtgcacttactg
tgggcttcaga--tcgtaaagcagggcccttcaccggsctttgcaggac---gtgtctg-
tgcctgcgtttatcacaaactc-tataaagtatcagaatgtgtattgcgatgtaacgcat
ctatatacaactttcagcaacggatctcttggctctcgcatcgatgaagaacgcagcgaa
atgcgataagtaatgtgaattgcagaattcagtgaatcatcgaatctttgaacgcacctt
gcgctccttggtattccgaggagcatgcctgtttgagtgtcatgaaatcatcaacctaca
agcct-ttgcggt-tttgtaggcttggacttggaggc-ttgtcgg-ccgtt-cttggtcg
gctcctcttaaatgcattagcttgg-ttccttgcggatcggc-tctcggtgtgataa-tg
tctacgccgcgaccgtgaagcg---tttggcaagcttctaacagtc-tcagttggagaca
gctttatgacctctgacctcaaatcaggtaggactacccgctgaacttaagcatatcaat
aagcggagga
>Ganoderma_tropicum_Z37068_Z37088 Ganoderma_tropicum_Z37068_Z37088 676 bp 
-------------------------ggaaggatcattatcgagtcttgactgggttgtag
ctggccttcccaggcatgtgcacgccc-gctcatccact-ctacacctgtgcacttactg
tgggcttcaga--tcgtaaagcarggcccttcaccgggctttgcaggac---gtgtctg-
tgcctgcgtttatcacaaactc-tataaagtatcagaatgtgtattgcgatgtaacgcat
ctatatacaactttcagcaacggatctcttg-----------------------------
------------------------------------------------------------
---------------ccgaggagcatgcctgtttgagtgtcatgaaatcatcaacctaaa
acctt-tgcggt--tttgtaggcttggacttggaggc-ttgtcgg-ccgtt-cttggtcg
gctcctcttaaatgcattagcttgg-ttccttgcggatcggc-tctcggtgtgataa-tg
tctacgccgtgaccgtgaagcg---tttggcaagcttctaacagtc-tcagttggagaca
gctttatgacctctgacctcaaatcaggtaggactacccgctgaactt------------
----------
>Ganoderma_weberianum_X78734_X78755 Ganoderma_weberianum_X78734_X78755 673 bp 
-------------------------ggaaggatcattatcgagttttgactgggttgtag
ctggccttccgaggcatgtgcacgccctgctcatccact-ctacacctgtgcacttactg
tgggtttcaaacgtcgtaaagcgagtctctttaccgagc-ttgtagagcg--gcgtctg-
tgcctgcgtttatcacaaactc-tataaagtattagaatgtgtattgcgatgtaacgcat
ctatatacaactttcagcaacggatctcttg-----------------------------
------------------------------------------------------------
---------------------------------------tcatgaaatcttcaacttacg
gacct-ttgcgggttttgtaggcttggactt-gaggc-ttgtcgg-cgtgt-ttcggtcg
gctcctcttaaatgcattagcttga-ttccttgcggatcggc-tctcggtgtgataa-tg
tctacgacgcgaccgtgaagcg--ttttggcgagcttctaaccgtccttgttt--ggaca
aatttatgacctctg---------------------------------------------
----------
>Tomophagus_Ganoderma_colossus_Z37071_Z37091 Tomophagus_Ganoderma_colossus_Z37071_Z37091 673 bp 
-------------------------ggaaggatcattatcgagttttgactgggttgtag
ctggccttccgaggcatgtgcacgccctgctcatccact-ctacacctgtgcacttactg
tgggtttcaga--tcgcagagcaagtc---ttctataggcttgtgaacc-----gcctg-
ggcctgcgtttattacaaatac-tataaagtactagaatgtgtattgcgatgtaacgcat
ctatatac-actttcagcaacggacc----------------------------------
------------------------------------------------------------
-----------------gaggagcatgcctgtttgagtgtcatgaaatcttcaacctaca
agcct-ttgcgggtttgttaggcttggttatggaggt-ttgtcggcct----tgcggtcg
gctcctcttaaatgcattagcttga-tttcttgcgaatcggc-tctcggtgtgatag-tg
tctatgccgcgaccgtgaagcg---tttggcaagcttctaaccgtctca--tgagagaca
gcttcttgacatctgacctcaaatcaggtaggactacccgctgaactt------------
----------
>END; 1 bp 
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------n
>nameless_1 1 bp 
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------n
