>Disciotis_venosa_AY544667 952 bp 
t-----------------------------------------------------------
---------------------------aagcatatcaataagcggagg------------
---------------aaaagaaaccaacagggattgcctcagtaacggcgagtgaagcgg
caaca---------------------------gctcaaattttaaagctggcgtctttgg
cgtccgcattgtaatttggagaggcatcttcggtttgggcgccagcctatgttccttgga
acaggacgtcacag----------------------------------------------
------------------------------agggtgagaatcccgtgcttggccggctgt
cccattccatgtgaagtgtcttcgacgagtcgagttgtttgg-----------------g
aatgcagctcaaaatgggtggtaaatttcatctaaagctaaatattggtgggagaccgat
agcgcacaagtagagtgatcgaaagatgaaaagcactttgaa-aatagagttaaaaagta
cgtgaaattgttgaaagggaagcgcttgagaccagactcggccggggatgatcagctgtc
cttctgggcagtgcacttgtctctggtcgggccagcatcggttgagacggcgggacaaag
gcttcgggaacgtg-------------------gctcc----tttcggggagtgttatag
cccgtcgcgtaatgccgccagc-----------ctcgaccgaggaccgcgcttcggctag
gatgctggcgtaatggtcttcagcgacccgtcttgaaacacggaccaaggagtctaacat
ctatgcgagtgtttgggtgtcaaacccccgcgcgaaatgaaagtgaacggaggtgggaac
ccgtaagggtg-----caccatcgaccggtcctgatgtcttcgga---------tggatc
tgagtaggagcatagctgttgggacccgaaagatggtgaactatgcctgaatagggtgaa
gccagaggaaactctggtggaggctcgcagcggttctgacgtgcaaatc----gatcgtc
aaatttgggtataggggcga---------------aagacta
>Morchella_angusticeps_AJ544203 952 bp 
tccgtaggtgaacctgc-------------------------------------------
----ggaaggatcattaccaag-----aaccatacagaaaagggaggcat----------
---------------taggggaccgaccagggctagtagctt-tacgttgttgaacgt--
---------------------------------------------------ccagtatgg
acccgaagcctcccccatctaaaccctctgcgtacctgtcccttcttgcttcccccggca
tctcgtcg----------------------------------------------------
------------------------------gggggagg--taaca---------------
--------accaaaactctctgtgaatcaaacagccgtcagaattataaaaca------a
acaaaaagttaaaactttcaacaacggatctcttggttcccacatcgatgaagaac----
---------------gcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaat
catcgaatctttgaacgcacattgcgccccctggtattccggggggca--------tgcc
tgttcgagcgtcataaaaacctcctcccccttcgggttttgttactatcgttgg---ggg
gttttggcctaatgggatagcgattggcaattcgtttcccaatgtcctaaatagacgtag
acccgcctccagatgcgacagc--------------------------------------
------------------------------accgaggccatcaaccgtggagtt------
----------------------------------------------atggga--------
----------------tataataggcttgcagtaaaatgctcacctctc-----tccaca
cgccgat----------------ggcacgacagttgcag---ttgcgggcgtaaattgga
gccct-----------------tttcaggaccctcgtggcctagcatcc----accatac
ataatttgacctcggatcaggtagggatacccgctgaactta
>Morchella_conica_AJ544194 952 bp 
tccgtaggtgaacctgc-------------------------------------------
----ggaaggatcattaccaag-----aaccacacagaaaagggcagc------------
----------------cgaggggccaccagggctagtagctt-tacgttgttgaacgt--
---------------------------------------------------cctggccgg
acccggagccgcccccatctaaaccctctgcgtacctgtcccgccttgcttcccccggct
acccgctg----------------------------------------------------
------------------------------gggggaggaacaaca---------------
--------accaaaactctttgtgaa-caagccgacgtcagaatcatagcaaa------a
caaaaaagttaaaactttcaacaacggatctcttggttcccacatcgatgaagaac----
---------------gcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaat
catcgaatctttgaacgcacattgcgccccctggtattccggggggca--------tgcc
tgttcgagcgtcataaaaacctcctcccccatcgggtttgattactatcgttgg---ggg
gttttggcctaatgggatagcgattggcaattagtttcccaatgtcctaaatagacgtag
acccgcctccagatgcgacagc--------------------------------------
------------------------------accgaggccatcaaccgtggagtt------
----------------------------------------------atggga--------
----------------tat-ataggcttgcagtaaaatgctcacctttc-----tccata
cgccgat----------------ggcacaccggtcgcag---ttgcgggcgtaaattgga
gccct-----------------tttcaggaccctcgtggcctagcatcc----accatac
acaatttgacctcggatcaggtagggatacccgctgaactta
>Morchella_crassipes_AJ539480 952 bp 
atcaatgctctgcatacat-tcattcaattgaatg-tggtgcagagtaggttatttctgc
tgaagggggatcccccggcaga-ggtggacggcacatgcaggctccgaac----------
---------------gacggaagccaaccatgtcgctgagtcccctggggctaggggcgg
taaaagcccctagccactc-cccgccgacggcgttgaccccatcgttctggcaccctctc
g----ccactgtcccaaccaaaaccctctgtgtaccct-tccctgttgcttcccccgggc
aactggctccggccagcc------------------------------------------
------------------------------ggggggagaaaccaa---------------
--------gcaaaaaccc--ttttcgcaaaacagacgtctgaacgcaaaaaacaaaacaa
aaaaaaagttaaaactttcaacaacggatctcttggttcccacatcgatgaagaac----
---------------gcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaat
catcgaatctttgaacgcacattgcgccctctggtattccggagggca--------tgcc
tgttcgagcgtcataaataccgctccccctc---ggattgcttgcggtccctgg---ggg
gttctggcaatgtg-------------------gattccccgtgctttgagggcatgcga
acgggctcccagtgctgaaagacataatgtt--cccagccgaaaccggtgatt-------
aatttcatcggcaggattcgtggcaggcagactgagggcgtcaaccgtggagtc------
----------------------------------------------atgagggtagaaac
ctccccctttgcaagtaacattgctctggcagttagatctgcaggcctg-----ccggtc
tggggatggacctcccactcgcaggcgtcacggccacga---tagcgggcgttaaacgga
atccgatccg-cctcacgggtggttgaagatccttgtgggctagcaacc----cctaaac
acattttgacctcggatcaggtagggatacccgctgaactta
>Morchella_elata_AJ544200 952 bp 
tccgtaggtgaacctgc-------------------------------------------
----ggaaggatcattaccaag-----aaccacacagaaaagggaggc------------
----------------aaaggggcctacaggtctagtagcttatacgttgttgaacgt--
---------------------------------------------------cctgcctgg
acccggagccgcccccatctaaaccctctgcgtacctgtcccttcttgcttcccccggca
tctcgtcg----------------------------------------------------
------------------------------gggggagg--taaca---------------
--------accaaaactctctgtgaatcaaacagccgtcagaattataaaac-------a
aataaaagttaaaactttcaacaacggatctcttggttcccacatcgatgaagaac----
---------------gcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaat
catcgaatctttgaacgcacattgcgccccctggtattccggggggca--------tgcc
tgttcgagcgtcataaaaacttcctcccccttcgggttttgttactatcgttgg---ggg
gttttggcctaatgggatagcgattggcaattcgtttcccaatgtcctgaatagacgtag
acccgccaccagatgcgacagc--------------------------------------
------------------------------accgaggccatcaaccgtggagtt------
----------------------------------------------atggga--------
----------------tatgataggcttgcagtaaaatgctcacctctc-----ttcaca
cgccgat----------------ggcacgacagttgcag---ttgcgggcgtaaattgga
gccct-----------------tttcaggacccttgtggcctagcatcc----accatac
ataatttgaccacggatcaggtagggatacccgctgaactta
>Morchella_esculenta_AJ623265 952 bp 
atcaatgctctgcatacat-tcattcaattgaatg-tggtgcagagtaggttatttctgc
tgaagggggatcccccggcaga-ggtggacggcacatgcaggctccgaac----------
---------------gacggaagccaaccatgtcgctgagtcccctggggctaggggcgg
taaaagcccctagccactc-cccgccgacggcgttgaccccatcgttctggcaccctctc
g----ccactgtcccaaccaaaaccctctgtgtaccct-tccctgttgcttcccccgggc
aactggctccggccagcc------------------------------------------
------------------------------ggggggagaaaccaa---------------
--------gcaaaaaccc--ttttcgcaaaacagacgtctgaacgcaaaaaacaaaac-a
aaaaaaagttaaaactttcaacaacggatctcttggttcccacatcgatgaagaac----
---------------gcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaat
catcgaatctttgaacgcacattgcgccctctggtattccggagggca--------tgcc
tgttcgagcgtcataaataccgctccccctc---ggattgcttgcggtccctgg---ggg
gttctggcaatgtg-------------------gattccccgtgctttgagggcatgcga
acgggctcccagtgctgaaagacataatgtt--cccagccgaaaccggtgatt-------
aatttcatcggcaggattcgtggcaggcagactgagggcgtcaaccgtggagtc------
----------------------------------------------atgagggtagaaac
ctccccctttgcaagtaacattgctctggcagttagatctgcaggcctg-----ccggtc
tggggatggacctcccactcgcaggcgtcacggccacga---tagcgggcgttaaacgga
atccgatccgccctcacgggtggttgaagatccttgtgggctagcaacc----cctaaac
acattttgacctcggatcaggtagggatacccgctgaactta
>Morchella_rufobrunnea_ODonnell_DQ355922 Morchella_rufobrunnea_ODonnell_DQ355922 952 bp 
------------------------------------------------------------
---------gatcattacaaaa-----tccaaccaaaaagaggcgaggaccgcggccgcc
tggtctccccggttaagaggcacccaccctcagcccccatctgcgcgcggcgggggat--
--------------------------------gcggggcctcccgtactggccgggccgc
gggcccctccgtcttcacacaaaccctctgtgtaccttgtccccattgcttccctcggaa
cgagagcttctccgggctggtccgggtggcggcgccccgtggaacgggcggcgcaacccg
attggccacgcctggctcgctcctcgcccggggggaggaaaaccc---------------
--------aaacaaaccctttgcgcgaaaaac-gacgtctgaacagaaaagaaaaca--a
actaaaagttaaaactttcaacaacggatctcttggttcccacatcgatgaagaac----
---------------gcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaat
catcgaatctttgaacgcacattgcgccctctggtattccggggggca--------tgcc
tgttcgagcgtcataaaaacctctccacccc---gggttca-tgagatccgggg---cgg
gtattggcggtgcg-------------------gatccctc-ccccctatacaacgggac
ggaggcgcccaccgctcaaagccatgaagataacccagccgaaagcg-------------
--------------------------------ccagggcgtcaaccgtggagtc------
----------------------------------------------atgagg--------
----------------aaccacgccccgcgaggggtgcctcccactctgggcgaccggtg
tatggaa-----------atgcgggcgtaaaagcacggg---aaatccgcgggaaccggc
gccgtctctggctgcggccgtggatgatccccgtggggggctagatacccaatcacattc
aagttttgacctcggatcaggtagggatacccgctgaactta
>Morchella_spongiola_AJ539476 952 bp 
ttaaacgctctgcacccatcccacgcagttgggtgaaggtgcagagcggatttctgtagc
taaaggaggtacccctggcaagtggctgacgacgcaagcagggctgaaat----------
---------------aa---acccctgccactgcggcgattcccctgtggctgtgggt-g
taaagacccacagcgactcgcaccgcggcaggacaccactcttaggtttgtcaccccctc
g----ccactgtcccaaccaaaaccctctgtgtaccct-tcccagttgcttcccccgggg
aactggctcctgccagcc------------------------------------------
------------------------------ggggggagaaaccaa---------------
--------gcaaaaacccttttttcgcaaaacagacgtccgaatttaaaaacaa-----a
acaaaaagttaaaactttcaacaacggatctcttggttcccacatcgatgaagaac----
---------------gcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaat
catcgaatctttgaacgcacattgcgccctctggtattccggagggca--------tgcc
tgttcgagcgtcataaataccgctccccctc---ggattgattgcgatccctgg---ggg
gttctggcaatgtg-------------------gtctccccgtgctttgagggcatgcga
acgggctcccagtgctgaaagacataacgtt--cccggccgaaaccggtgatt-------
aatttcaccggcaggattcgtggcaggcagactgagggcgtcaaccgtggagtc------
----------------------------------------------atgaggatagaaac
ctccccctttgcaagtaacattgctctggcagttagatctgcaggcctg-----ccggtc
tggggatggacctcccactcgcaggcgtcacggccacga---tagcgggcgttaaacgga
atccgatccgccttcactggtggttgaagatccttgtgggctagcaacc----cctaaac
atattttgacctcggatcaggtagggatacccgctgaactta
>Verpa_bohemica_FJ176853 952 bp 
------------------------------------------------------------
-------------------------------atatcaataagcggagg------------
---------------aaaagaaaccaacagggattgcctcagtaacggcgagtgaagcgg
caaca---------------------------gctcaaattttaaagctggcgtcttcga
cgtccgcattgtaatttggagaggcatcttcggattgggcgccagcctatgttccttgga
acaggacgtcacag----------------------------------------------
------------------------------agggtgagaatcccgtgcttggctggctgt
cccatttcatgtgaagtgtcttcgacgagtcgagttgtttgg-----------------g
aatgcagctcaaaatgggtggtaaatttcatctaaagctaaatattggtgggagaccgat
agcgcacaagtagagtgatcgaaagatgaaaagcactttgaa-aatagagttaaaaagta
cgtgaaattgttgaaagggaagcgcttgagaccagactcggctggtgatgatcagctgtc
cttttgggcagtgcacttgtcgccggttgggccagcatcggttgagacggcgggataaag
gttttgggaatgtg-------------------gctcc----tctcggggagtgttatag
cccagaatgcaatgccgccagc-----------ctcgaccgaggaccgcgcttcggctag
gatgctggcataatggtcttcagcgacccgtcttgaaacacggaccaaggagtctaacat
ctatgcgagtgtttgggtgtcaaacccttgcgcgaaatgaaagtgaacggaggtgggaac
ccgcaagggcg-----caccatcgaccggtcctgatgtcttcgga---------tggatc
tgagtaggagcatagctgttgggacccgaaagatggtgaactatgcctgaatagggtgaa
gccagaggaaactctggtggaggctcgcagcggttctgacgtgcaaatc----gatcgtc
aaatttgggtataggggcga---------------aagacta
