>Phytophthora_alticola_CMW19424_DQ988197 Phytophthora_alticola_CMW19424_DQ988197 909 bp 
ccacacct---aaaaactttccacgtgaaccgtatcaaac-ttttagttgggggtctttt
tcggcgac--ggctgctggcttcattgctggcggctg-----ctgttgaatgagccctat
c-------at-ggcgagcgtttaggcttc----------ggtctgaactagtag------
-cttttttaaacccatt-ctttattactgat-tatactgtggggacgaaagtctctgctt
ttaactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacgct
gcgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaacgc
atattgcacttccgggttagtcctgggagtatgcctgtatcagtgtccgtacatcaaact
tggctttcttccttccgtgtagtcggtgga-agatgtgc-cag-atgtgaagtgtcttgc
gg-ct----ggtcttcgggtc--ggct--gtgagtcctttgaaatgtactgaactgtact
-tctctttgctcgaaaagc-gt--ggcgttgctgattgtggaggctgcc-tgcgtagcca
gtctggcgaccagtttgtctgctgtggcg--ttaatggaggagtgttcgattcgcggtat
ggttggcttcggctgaacag-acgcttattgaatggtttttcc-tgcta-tggcg---gt
acaggttggtgaaccgtagctatgtg-ggcttggcttttgaattggctttgc-tgttgcg
aagtagagtggcgg----------cttcagc------------tgtcga-gggtcgatcc
atttgggaagtg----gtgggtactt------------
>Phytophthora_alticola_CMW19425_DQ988196 Phytophthora_alticola_CMW19425_DQ988196 909 bp 
ccacacct---aaaaactttccacgtgaaccgtatcaaac-ttttagttgggggtctttt
tcggcgac--ggctgctggcttcattgctggcggctg-----ctgttgaatgagccctat
c-------at-ggcgagcgtttaggcttc----------ggtctgaactagtag------
-cttttttaaacccatt-ctttattactgat-tatactgtggggacgaaagtctctgctt
ttaactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacgct
gcgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaacgc
atattgcacttccgggttagtcctgggagtatgcctgtatcagtgtccgtacatcaaact
tggctttcttccttccgtgtagtcggtgga-agatgtgc-cag-atgtgaagtgtcttgc
gg-ct----ggtcttcgggtc--ggct--gtgagtcctttgaaatgtactgaactgtact
-tctctttgctcgaaaagc-gt--ggcgttgctgattgtggaggctgcc-tgcgtagcca
gtctggcgaccagtttgtctgctgtggcg--ttaatggaggagtgttcgattcgcggtat
ggttggcttcggctgaacag-acgcttattgaatggtttttcc-tgcta-tggcg---gt
acaggttggtgaaccgtagctatgtg-ggcttggcttttgaattggctttgc-tgttgcg
aagtagagtggcgg----------cttcagc------------tgtcga-gggtcgatcc
atttgggaagtg----gtgggtactt------------
>Phytophthora_bisheria_Cg_2_3_3_AY241924 Phytophthora_bisheria_Cg.2.3.3_AY241924 909 bp 
ccacacctaaaaaaaactttccacgtgaaccgtatcaacccttttaattggggat-ttgc
ttggtgtgc-ggctagctggcctttattggctggcaggctgcgtgctgggcgagtcctat
c-------at-ggcaaacgtttgggcttc----------ggtctgagcaagtag------
-ctttttttaaaccatt-tcttaatactgat-tatactgtggggacgaaagtctctgctt
ttaactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacgct
gcgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaacgc
atattgcacttccgggttagtcctgggagtatgcctgtatcagtgtccgtacatcaaact
tggttttcttccttccgtgtagtcggtgga-ggatatgc-cag-atgtgaagtgtcttgc
gg-ct----ggctttcgggtc--ggctgcgcgagtcctttgaaatgtactgaactgtact
-tctctttgctcgaaaagt-ga--ggcgttgctggttgtggaggctgcc-cgcgtggcca
gtc-ggcgaccggtttgtctgctgcggtgttttactggaggagtgttcgattcgcggtat
ggttggcttcggctgaacag-gcgcttattggac-gttttccc-tgctg-tggcg---tg
atgagctggtgaaccgtagctatgta-ggcttggcttttgaaccggtgatac-tattgcg
aagtagagtggcgg----------cttcggc------------tgccgaggggtcgatcc
attttgggaaactt-tgtgtgtactt------------
>Phytophthora_bisheria_P_1_33_AF408625 Phytophthora_bisheria_P.1.33_AF408625 909 bp 
ccacacctaaaaaaaactttccacgtgaaccgtatcaacccttttaattggggat-ttgc
ttggtgtgc-ggctagctggcctttattggctggcaggctgcgtgctgggcgagtcctat
c-------at-ggcaaacgtttgggcttc----------ggtctgagcaagtag------
-ctttttttaaaccatt-tcttaatactgat-tatactgtggggacgaaagtctctgctt
ttaactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacgct
gcgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaacgc
atattgcacttccgggttagtcctgggagtatgcctgtatcagtgtccgtacatcaaact
tggttttcttccttccgtgtagtcggtgga-ggatatgc-cag-atgtgaagtgtcttgc
gg-ct----ggctttcgggtc--ggctgcgcgagtcctttgaaatgtactgaactgtact
-tctctttgctcgaaaagt-ga--ggcgttgctggttgtggaggctgcc-cgcgtgacca
gtc-ggcgaccggtttgtctgctgcggtgttttactggaggagtgttcgattcgcggtat
ggttggcttcggctgaacag-gcgcttattggac-gttttccc-tgctg-tggcg---tg
atgagctggtgaaccgtagctatgta-ggcttggcttttgaaccggtgatac-tattgcg
aagtagagtggcgg----------cttcggc------------tgccgaggggtcgatcc
attttgggaaactt-tgtgtgtactt------------
>Phytophthora_boehmeriae_CMW19441_DQ988207 Phytophthora_boehmeriae_CMW19441_DQ988207 909 bp 
ccccacct----aaaactttccacgtgaaccgttcaacct--tttagttgggga--ctcc
tcgtcggc--ggctttcgggctgt------------------tggtgggttgaggcctat
c-------aaagcgagtgatttgggccgc--------aaggtctgagttgcgag---ttt
ttccttttaaacccattacttaaatactgat-tatactgtggggacgaaagtctctgctt
ttaactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacgct
gcgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaacgc
atattgcacttccgggttatgcctgggagtatgcctgtatcagtgtccgtacatcaacct
tggcttccttccttccgtgtagtcggtggatgggaatgc-cag-acgtgaagtgtcttgc
tg-tagc--ggttttcggactgcggc---gcgagtcctttgaaatgta-gatactgttct
-tctctttgctcgaaaagc-tgtgcagaatgtatgttgtggaggctgcc-atcacggcat
gtc-ggcgactgattt-cgtgctgaggcg---ttttggagaggggttcgattcgcggtag
tgttggtttcggccgaacaatctgcttattgggt-tcttttcc-aggctttggcg-tatg
cggagtcggtgtaccgtagttgtgcgtggcttggcctttgaacgctcgttttgcgtggcg
aagtagagtggcgaagtgtttgttttcggacgaatgcggctgccgaggaggggataaaat
attttgggaaaatttagtgtgcgctt------------
>Phytophthora_boehmeriae_DDS3884_EU301151 Phytophthora_boehmeriae_DDS3884_EU301151 909 bp 
ccacacct--aaaaaactttccacgtgaaccgttcaacct--tttagttgggga--ctcc
tcgtcggc--ggctttcgggctgt------------------tggtgggttgaggcctat
c-------aaagcgagtgatttgggccgc--------aaggtctgagttgcgag----tt
ttccttttaaacccattacttaaatactgat-tatactgtggggacgaaagtctctgctt
ttaactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacgct
gcgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaacgc
atattgcacttccgggttatgcctgggagtatgcctgtatcagtgtccgtacatcaacct
tggcttccttccttccgtgtagtcggtggatgggaatgc-cag-acgtgaagtgtcttgc
tg-tagc--ggttttcggactgcggcg--gcgagtcctttgaaatgta-gatactgttct
-tctctttgctcgaaaagc-tgtgcagaatgtatgttgtggaggctgcc-atcacggcat
gtc-ggcgactgattt-cgtgctgaggcg---ttttggagaggggttcgattcgcggtag
tgttggtttcggccgaacaatctgcttattgggt-tcttttcc-aggctttggcg-tatg
cggagtcggtgtaccgtagttgtgcgtggcttggcctttgaacgctcgttttgcgtggcg
aagtagagtggcgaagtgtttgttttcggacgaatgcggctgccgaggaggcgat-aaat
attttgggaaaatttagtgtgcgctt------------
>Phytophthora_cactorum_IMI296524_AF266772 Phytophthora_cactorum_IMI296524_AF266772 909 bp 
ccacacct---aaaaactttccacgtgaaccgtttcaaaccaaatagttgggggtcttgt
ctggtggc--ggctgctggctttattgttggcggctg-----ctgctgggtgagccctat
c-------at-ggcgagcgtttgggcttc----------ggcctgagctagtag----ct
tttcttttaaacccatt-ccttaatactgat-tatactgtggggacgaaagtccttgctt
ttaactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacgct
gcgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaacgc
atattgcacttccgggttagtcctgggagtatgcctgtatcagtgtccgtacatcaaact
tggctttcttccttccgtgtagtcggtgga-ggagatgc-cag-atgtgaagtgtcttgc
gg-ct----ggttttcggacc--gact--gcgagtccttttaaatgtactgaactgtact
-tctctttgctcgaaaagc-gt--ggcgttgctggttgtggaggctgct-attgtagcaa
gtt-ggcgaccggtttgtctgctgcggcg--ttaatggaagagtgttcgattcgcggtat
ggttagcttcggctgaacaatgcgcttattggat-gttttttc-tgctg-tggcg---tg
atggaccggtgaaccatagctcagt--tgcttggcttttgaatcggctttgc-tgttgcg
aagtagagtggcgg----------cttcggc------------tgtcga-gggtcgatcc
atttgggaaatg---tgtgtgtactt------------
>Phytophthora_cactorum_P167_EU109566 Phytophthora_cactorum_P167_EU109566 909 bp 
ccacacct---aaaaactttccacgtgaaccgtttcaaaccaaatagttgggggtcttgt
ctggtggc--ggctgctggctttattgttggcggctg-----ctgctgggtgagccctat
c-------at-ggcgagcgtttgggcttc----------ggcctgagctagtag----ct
tttcttttaaacccatt-ccttaatactgat-tatactgtggggacgaaagtccttgctt
ttaactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacgct
gcgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaacgc
atattgcacttccgggttagtcctgggagtatgcctgtatcagtgtccgtacatcaaact
tggctttcttccttccgtgtagtcggtgga-ggagatgc-cag-atgtgaagtgtcttgc
gg-ct----ggttttcggacc--gact--gcgagtccttttaaatgtactgaactgtact
-tctctttgctcgaaaagc-gt--ggcgttgctggttgtggaggctgct-attgtagcaa
gtt-ggcgaccggtttgtctgctgcggcg--ttaatggaagagtgttcgattcgcggtat
ggttagcttcggctgaacaatgcgcttattggat-gttttttc-tgctg-tggcg---tg
atggaccggtgaaccatagctcagt--tgcttggcttttgaatcggctttgc-tattgcg
aagtagagtggcgg----------cttcggc------------tgtcga-gggtcgatcc
atttgggaaatg---tgtgtgtactt------------
>Phytophthora_captiosa_NZFS310_31_DQ297404 Phytophthora_captiosa_NZFS310.31_DQ297404 909 bp 
ccacacct-taaaaaat--tccacgtgaactgtattgtcaaccaaattcgggga--ctcc
ttgctagtgtgctttcgggcgtgc------------------cggtaggttgagacccat
c---------aaacgaaaacatcgactga--------aaggtcggagccagtag----tt
acctttgtaaacccttt-actaaatactgaa--aaactgtggggacgaaagtccttgctt
tt-actagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacgct
gcgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaacgc
atattgcacttccgggttatgcctggaagtatgcctgtatcagtgtccgtatatcaaact
tgccttccttccttccgtgtagtcggtggatgggaacgtgcag-atgtgaagtgtcttgg
cg-gcgt--cgcttcggcggt--gctg--gcgagtccttttaaatacaagatactgttct
-tctctttgctcgaaaagc-gt--gtgggatgtggttgtggaggctgcc-tgcgtggcca
gtc-ggcgactgattt-cgtgctgagacg-----gtggggaggggcttgattcgcggtat
ggttggcttcggctgaactt-ctgcttattgggc-ttctttca-tgtct-tggcg-tatg
cgattttggtgtaccgtagctgtgtgtggcttggcttttgaaccgtgttct--gtgtgcg
aagtagagtgggcg----------tgtggttttcggactgcgtggccgaggggacgagac
cttttgggaaattgtgctgc-tacttttgtggcggcat
>Phytophthora_captiosa_NZFS310_35_DQ297405 Phytophthora_captiosa_NZFS310.35_DQ297405 909 bp 
ccacacct-taaaaaat--tccacgtgaactgtattgtcaaccaaattcgggga--ctcc
ttgctagtgtgctttcgggcgtgc------------------cggtaggttgagacccat
c---------aaacgaaaacatcgactga--------aaggtcggagccagtag----tt
acctttgtaaacccttt-actaaatactgaa--aaactgtggggacgaaagtccttgctt
tt-actagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacgct
gcgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaacgc
atattgcacttccgggttatgcctggaagtatgcctgtatcagtgtccgtatatcaaact
tgccttccttccttccgtgtagtcggtggatgggaacgtgcag-atgtgaagtgtcttgg
cg-gcgt--cgcttcggcggt--gctg--gcgagtccttttaaatacaagatactgttct
-tctctttgctcgaaaagc-gt--gtgggatgtggttgtggaggctgcc-tgcgtggcca
gtc-ggcgactgattt-cgtgctgagacg-----gtggggaggggcttgattcgcggtat
ggttggcttcggctgaactt-ctgcttattgggc-ttctttca-tgtct-tggcg-tatg
cgattttggtgtaccgtagctgtgtgtggcttggcttttgaaccgtgttct--gtgtgcg
aagtagagtgggcg----------tgtggttttcggactgcgtggccgaggggacgagac
cttttgggaaattgtgctgc-tacttttgtggcggcat
>Phytophthora_cinnamomi_mc9_AY302153 Phytophthora_cinnamomi_mc9_AY302153 909 bp 
ccacacct--aaaaaactttccacgtgaaccgtatcaacccaattagttgggggcctgct
ctgggcggc-ggctgtcgatgtcaaagtcgacggctgctg--ctgcgtggcgggccctat
c-------actggcgagcgtttgggtccctctc--gggggaactgagctagtag----cc
tctcttttaaacccatt-ctgtaatactgaa-catactgtggggacgaaagtctctgctt
ttaactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacgct
gcgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaacgc
atattgcacttccgggttagtcctgggagtatgcctgtatcagtgtccgtacatcaaact
tggctctcttccttccgtgtagtcggtggatggaggtgc-cag-acgtgaggtgtcttgc
gg-gc----ggtcttcggact--ggct--gtgagtcccttgaaatgtactgaactgtact
-tctctttgctcgaaaagc-gt--gacgttgctggttgtggaggctgcc-tgtatggcca
gtc-ggcgaccggtttgtctgctgcggcg-tttaatggaggagtgttcgattcgcggtat
ggttggcttcggctgaacaaagcgcttattggat-gttcttcc-tgctg-tggcg---gt
acggatcggtgaaccgtagctgtgctaggcttggcgtttgaaccggcggtgt-tgttgcg
aagtagggtggcgg----------cttcggc------------tgtcga-gggtcgatcc
atttgggaactc---tgtgt---ctctgcggcgcactt
>Phytophthora_citricola_112_EU263906 Phytophthora_citricola_112_EU263906 909 bp 
ccacacct--aaaaaacttttcacgtgaaccgtatcaacccttttagttgggggtcttgc
tt-------------------------------------------ttttgcgagccctat
c-------at-ggcgaatgtttggacttc----------ggtctgggctagtag--c-tt
tttgttttaaacccatt-ctacaatactgat-tatactgtggggacgaaagtctctgctt
ttaactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacgct
gcgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaacgc
atattgcacttccgggttagtcctgggagtatgcctgtatcagtgtccgtacatcaaact
tggctttcttccttccgtgtagtcggtgga-ggatgtgc-cag-atgtgaagtgtcttgc
gg-gt----gtccttcgggtc--gtct--gcgagtcctttgaaatgtactgaactgtact
-tctctttgctcgaaaagc-gt--ggtgttgctggttgtggaggctgcc-tgcgtggcca
gtc-ggcgaccggtttgtctgctgcagcg-tttaatggaggagtgttcgattcgcggtat
ggttggcttcggctgaacag-gcgcttattgtat-gcttttcc-tgctg-tggcg---tg
atgggctggtgaaccgtagctatgtgtggcttggcttttgaatcggctttgc-tgttgcg
aagtagagtggcgg----------cttcggc------------tgtcga-gggtcgatcc
atttgggaactt---tgtgtgcacct------------
>Phytophthora_citricola_77a_EU594606 Phytophthora_citricola_77a_EU594606 909 bp 
ccacacct--aaaaaactttccacgtgaaccgtatcaaccctttcagttgggggccttgc
tt-------------------------------------------ttttgcgagccctat
c-------at-ggcgaatgtttggacttc----------ggtctgggctagtag--c-tt
tttgttttaaacccatt-ctacaatactgat-tatactgtggggacgaaagtctctgctt
ttaactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacgct
gcgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaacgc
atattgcacttccgggttagtcctgggagtatgcctgtatcagtgtccgtacatcaaact
tggctttcttccttccgtgtagtcggtgga-ggatgtgc-cag-atgtgaagtgtcttgc
ag-gt----gtccttcgggtc--gtct--gcgagtcctttgaaatgtactgaactgtact
-tctctttgctcgaaaagc-gt--ggcgttgctggttgtggaggctgcc-tgcgtggcca
gtc-ggcgaccggtttgtctgctgcggcg-tttaatggaggagtgttcgattcgcggtat
ggttggcttcggctgaacag-gcgcttattgtat-gcttttcc-tgctg-tggcg---tg
atggactggtgaaccgtagctgtgtgtggcttggcttttgaatcggctttgc-tgttgcg
aagtagagtggcgg----------ctccggc------------tgtcga-gggtcgatcc
atttgggaactt---tgtgtgcacct------------
>Phytophthora_citricola_IMI021173 Phytophthora_citricola_IMI021173 909 bp 
ccacacct--aaaaaactttccacgtgaaccgtatcaacccttttagttgggggtcttgc
tt------------------------------------------tttttgcgagccctat
c-------at-ggcgaatgtttggacttc----------ggtctgggctagtag--c-tt
tttgttttaaacccatt-ctacaatactgat-tatactgtggggacgaaagtctctgctt
ttaactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacgct
gcgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaacgc
atattgcacttccgggttagtcctgggagtatgcctgtatcagtgtccgtacatcaaact
tggctttcttccttccgtgtagtcggtgga-ggatgtgc-cag-atgtgaagtgtcttgc
gg-gt----gtccttcgggtc--gtct--gcgagtcctttgaaatgtactgaactgtact
-tctctttgctcgaaaagc-gt--ggtgttgctggttgtggaggctgcc-tgcgtggcca
gtc-ggcgaccggtttgtctgctgcggcg-tttaatggaggagtgttcgattcgcggtat
ggttggcttcggctgaacag-gcgcttattgtat-gcttttcc-tgctg-tggcg---tg
atgggctggtgaaccgtagctgtgtgtggcttggcttttgaatcggctttgc-tgttgcg
aagtagagtggcgg----------cttcggc------------tgtcga-gggtcgatcc
atttgggaactt---tgtgtgcacct------------
>Phytophthora_citricola_IMI031372_AF266788 Phytophthora_citricola_IMI031372_AF266788 909 bp 
ccacacct--aaaaaacttttcacgtgaaccgtatcaacccttttagttgggggtcttgc
tt-------------------------------------------ttttgcgagccctat
c-------at-ggcgaatgtttggacttc----------ggtctgggctagtag--c-tt
tttgttttaaacccatt-ctacaatactgat-tatactgtggggacgaaagtctctgctt
ttaactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacgct
gcgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaacgc
atattgcacttccgggttagtcctgggagtatgcctgtatcagtgtccgtacatcaaact
tggctttcttccttccgtgtagtcggtgga-ggatgtgc-cag-atgtgaagtgtcttgc
gg-gt----gtccttcgggtc--gtct--gcgagtcctttgaaatgtactgaactgtact
-tctctttgctcgaaaagc-gt--ggtgttgctggttgtggaggctgcc-tgcgtggcca
gtc-ggcgaccggtttgtctgctgcagcg-tttaatggaggagtgttcgattcgcggtat
ggttggcttcggctgaacag-gcgcttattgtat-gcttttcc-tgctg-tggcg---tg
atgggctggtgaaccgtagctatgtgtggcttggcttttgaatcggctttgc-tgttgcg
aagtagagtggcgg----------cttcggc------------tgtcga-gggtcgatcc
atttgggaactt---tgtgtgcacct------------
>Phytophthora_citricola_MN21HH_DQ486661 Phytophthora_citricola_MN21HH_DQ486661 909 bp 
ccacacct--aaaaaacttttcacgtgaaccgtatcaacccttttagttgggggtcttgc
tt------------------------------------------tttttgcgagccctat
c-------at-ggcgaatgtttggacttc----------ggtctgggctagtag--c-tt
tttgttttaaacccatt-ctacaatactgat-tatactgcggggacgaaagtctctgctt
ttaactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacgct
gcgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaacgc
atattgcacttccgggttagtcctgggagtatgcctgtatcagtgtccgtacatcaaact
tggctttcttccttccgtgtagtcggtgga-ggatgtgc-cag-acgtgaagtgtcttgc
gg-gt----gtccttcgggtc--gtct--gcgagtcctttgaaatgtactgaactgtact
-tctctttgctcgaaaagc-gt--ggtgttgctggttgtggaggctgcc-tgcgtggcca
gtc-ggcgaccggtttgtctgctgcggcg-tttaatggaggagtgttcgattcgcggtat
ggttggcttcggctgaacag-gcgcttattgtat-gcttttcc-tgctg-tggcg---tg
atgggctggtgaaccgtagctgtgtgtggcttggcttttgaatcggctttgc-tgttgcg
aagtagagtggcgg----------cttcggc------------tgtcga-gggtcgatcc
atttgggaactt---tgtgtgcacct------------
>Phytophthora_citricola_P15946_EU244846 Phytophthora_citricola_P15946_EU244846 909 bp 
ccacacct--aaaaaactttccacgtgaaccgtatcaaccctttcagttgggggccttgc
tt-------------------------------------------ttttgcgagccctat
c-------at-ggcgaatgtttggacttc----------ggtctgggctagtag--c-tt
tttgttttaaacccatt-ctacaatactgat-tatactgtggggacgaaagtctctgctt
ttaactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacgct
gcgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaacgc
atattgcacttccgggttagtcctgggagtatgcctgtatcagtgtccgtacatcaaact
tggctttcttccttccgtgtagtcggtgga-ggatgtgc-cag-atgtgaagtgtcttgc
ag-gt----gtccttcgggtc--gtct--gcgagtcctttgaaatgtactgaactgtact
-tctctttgctcgaaaagc-gt--ggcgttgctggttgtggaggctgcc-tgcgtggcca
gtc-ggcgaccggtttgtctgctgcggcg-tttaatggaggagtgttcgattcgcggtat
ggttggcttcggctgaacag-gcgcttattgtat-gcttttcc-tgctg-tggcg---tg
atggactggtgaaccgtagctgtgtgtggcttggcttttgaatcggctttgc-tgttgcg
aagtagagtggcgg----------ctccggc------------tgtcga-gggtcgatcc
atttgggaactt---tgtgtgcacct------------
>Phytophthora_citricola_P44_EF423556 Phytophthora_citricola_P44_EF423556 909 bp 
ccacacct--aaaaaacttttcacgtgaaccgtatcaacccttttagttgggggtcttgc
tt------------------------------------------tttttgcgagccctat
c-------at-ggcgaatgtttggacttc----------ggtctgggctagtag--c-tt
tttgttttaaacccatt-ctacaatactgat-tatactgcggggacgaaagtctctgctt
ttaactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacgct
gcgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaacgc
atattgcacttccgggttagtcctgggagtatgcctgtatcagtgtccgtacatcaaact
tggctttcttccttccgtgtagtcggtgga-ggatgtgc-cag-acgtgaagtgtcttgc
gg-gt----gtccttcgggtc--gtct--gcgagtcctttgaaatgtactgaactgtact
-tctctttgctcgaaaagc-gt--ggtgttgctggttgtggaggctgcc-tgcgtggcca
gtc-ggcgaccggtttgtctgctgcggcg-tttaatggaggagtgttcgattcgcggtat
ggttggcttcggctgaacag-gcgcttattgtat-gcttttcc-tgctg-tggcg---tg
atgggctggtgaaccgtagctgtgtgtggcttggcttttgaatcggctttgc-tgttgcg
aagtagagtggcgg----------cttcggc------------tgtcga-gggtcgatcc
atttgggaactt---tgtgtgcacct------------
>Phytophthora_citrophthora_CMW20198_DQ988188 Phytophthora_citrophthora_CMW20198_DQ988188 909 bp 
ccacacct--aaaaaactttccacgtgaaccgtatcaacccttttagttgggggtgttgc
ttggcattt-agctg--------------------------------agccgcgccctat
c-------at-ggcgaatgtttggacttc----------ggtctgggctagtag--c-tt
ttttgttttaaaccatt-taacaatactgat-tatactgtggggacgaaagtctctgctt
ttaactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacgct
gcgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaacgc
atattgcacttccgggttagtcctgggagtatgcctgtatcagtgtccgtacatcaaact
tggctttcttccttccgtgtagtcggtgga-ggatgtgc-cag-atgtgaagtgtcttgc
gg-tttgtgtgccttcgggccgaggct--gcgagtcctttgaaatgtactgaactgtact
-tctctttgctcgaaaagc-gt--ggtgttgctggttgtggaggctgcc-tgcgtggcca
gtc-ggcgaccggtttgtctgctgcggcg-tttaatggaggagtgttcgattcgcggtat
ggttggcttcggctgaacag-gcgcttattgtat-gcttttcc-tgctg-tggcg---tg
atgggctggtgaaccgtagctgtgtgtggcttggcttttgaatcggctttgc-tgttgcg
aagtagagtggcgg----------cttcggc------------tgtcga-gtgtcgatcc
attttgggaacgtt-tgtgtgcgctt------------
>Phytophthora_citrophthora_IMI332632_AF266785 Phytophthora_citrophthora_IMI332632_AF266785 909 bp 
ccacacct--aaaaaactttccacgtgaaccgtatcaacccttttagttgggggtgttgc
ttggcgtttttgctg--------------------------------agccacgccctat
c-------at-ggcgaatgtttggacttc----------ggtctgggctagtag--cttt
tttgttttaaacccatt-taacaatactgat-tatactgtggggacgaaagtctctgctt
ttaactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacgct
gcgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaacgc
atattgcacttccgggttagtcctgggagtatgcctgtatcagtgtccgtacatcaaact
tggctttcttccttccgtgtagtcggtgga-ggatgtgc-cag-atgtgaagtgtcttgc
gg-tttttgtgccttcgggccgtggct--gcgagtcctttgaaatgtactgaactgtact
-tctctttgctcgaaaagc-gt--ggtgttgctggttgtggaggctgcc-tgcgtggcca
gtc-ggcgaccggtttgtctgctgcggcg-tttaatggaggagtgttcgattcgcggtat
ggttggcttcggctgaacag-gcgcttattgtat-gcttttcc-tgctg-tggcg---tg
atgggctggtgaaccgtagctgtgtgtggcttggcttttgaatcggctttgc-tgttgcg
aagtagagtggcgg----------cttcggc------------tgtcga-gtgtcgatcc
attttgggaacgtt-tgtgtgcgctt------------
>Phytophthora_cryptogea_CRP235_AY659443 Phytophthora_cryptogea_CRP235_AY659443 909 bp 
ccacacct--aaaaaactttccacgtgaaccgtatcaacctttttaaattgggggctccc
gt-------------ctggccggccggttttcggctggctg-----ggtggcggctctat
c-------at-ggcgaccgcttgggcctc----------ggcctgggctagtag----cg
tattttttaaacccatt-cctaattactgaa-tatactgtggggacgaaagtctctgctt
ttaactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacgct
gcgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaacgc
atattgcacttccgggttagtcctgggagtatgcctgtatcagtgtccgtacactaaact
tggctcccttccttccgtgtagtcggtggatggggacgcgcag-atgtgaagtgtcttgc
gg-ct----ggtcttcggtcc--ggct--gcgagtcctttgaaatgtactacactgtact
-tctctttgctcgaaaagc-gt--gacgttgctggttgtggaggctgcc-tgtgtggcat
gtc-ggcgaccggtttgtctgctgcggcg-tttaatggaggagtgttcgattcgcggtat
gattggcttcggctgaacag-acgcttattgggt-gcttttcc-tgctg-tggct---gg
atggactggtgaaccgtagctgtgctaggcttggcgtttgaaccggcggtg--tggtgcg
aagtagggtgtctg----------ttccggcgcaagctggggtggacga-gggtcgatcc
atttgggaaacgt--tgtgtgcgctt------------
>Phytophthora_cryptogea_DDS3612_EU301139 Phytophthora_cryptogea_DDS3612_EU301139 909 bp 
ccacacct--aaaaaactttccacgtgaaccgtatcaacctttttaaattgggggctccc
gt-------------ctggccggccggttttcggctggctg-----ggtggcggctctat
c-------at-ggcgaccgcttgggcctc----------ggcctgggctagtag----cg
tattttttaaacccatt-cctaattactgaa-tatactgtggggacgaaagtctctgctt
ttaactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacgct
gcgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaacgc
atattgcacttccgggttagtcctgggagtatgcctgtatcagtgtccgtacactaaact
tggctcccttccttccgtgtagtcggtggatggggacgcgcag-atgtgaagtgtcttgc
gg-ct----ggtcttcggtcc--ggct--gcgagtcctttgaaatgtactacactgtact
-tctctttgctcgaaaagc-gt--gacgttgctggttgtggaggctgcc-tgtgtggcat
gtc-ggcgaccggtttgtctgctgcggcg-tttaatggaggagtgttcgattcgcggtat
gattggcttcggctgaacag-acgcttattgggt-gcttttcc-tgctg-tggct---gg
atggactggtgaaccgtagctgtgctaggcttggcgtttgaaccggcggtg--tggtgcg
aagtagggtgtctg----------ttccggcgcaagctggggtggacga-gggtcgatcc
atttgggaaacgt--tgtgtgcgctt------------
>Phytophthora_cryptogea_IMI045168_AF266796 Phytophthora_cryptogea_IMI045168_AF266796 909 bp 
ccacacct--aaaaaactttccacgtgaaccgtatcaacctttttaatttgggggcttcc
gt-------------ctggccggccggttttcggctggctg-----ggtggcggctctat
c-------at-ggcgaccgcttgggcctc----------ggcctgggctagtag----cg
tattttttaaacccatt-cctaattactgaa-tatactgtggggacgaaagtctctgctt
ttaactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacgct
gcgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaacgc
atattgcacttccgggttagtcctgggagtatgcctgtatcagtgtccgtacactaaact
tggctcccttccttccgtgtagtcggtggatggggacgcgcag-atgtgaagtgtcttgc
gg-ct----ggtcttcggtcc--ggct--gcgagtcctttgaaatgtactacactgtact
-tctctttgctcgaaaagc-gt--gacgttgctggttgtggaggctgcc-tgtgtggcat
gtc-ggcgaccggtttgtctgctgcggcg-tttaatggaggagtgttcgattcgcggtat
ggttggcttcggctgaacag-acgcttattgggt-gcttttcc-tgctg-tggct---gg
atggactggtgaaccgtagctgtgctaggcttggcgtttgaaccggcggtg--tggtgcg
aagtagggtgtctg----------ttctggcgtaagctggggtggacga-gggtcgatcc
atttgggaaacgt--tgtgtgcgctt------------
>Phytophthora_cryptogea_TCH010_EU301141 Phytophthora_cryptogea_TCH010_EU301141 909 bp 
ccacacct--aaaaaactttccacgtgaaccgtatcaacc-ttttaaattgggggctccc
gt-------------ctggccggccggttttcggctggctg-----ggtggcggctctat
c-------at-ggcgaccgcttgggcctc----------ggcctgggctagtag----cg
tattttttaaacccatt-cctaattactgaa-tatactgtggggacgaaagtctctgctt
ttaactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacgct
gcgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaacgc
atattgcacttccgggttagtcctgggagtatgcctgtatcagtgtccgtacactaaact
tggctcccttccttccgtgtagtcggtggatggggacgcgcag-atgtgaagtgtcttgc
gg-ct----ggtcttcggtcc--ggct--gcgagtcctttgaaatgtactacactgtact
-tctctttgctcgaaaagc-gt--gacgttgctggttgtggaggctgcc-tgtgtggcat
gtc-ggcgaccggtttgtctgctgcggcg-tttaatggaggagtgttcgattcgcggtat
gattggcttcggctgaacag-acgcttattgggt-gcttttcc-tgctg-tggct---gg
atggactggtgaaccgtagctgtgctaggcttggcgtttgaaccggcggtg--tggtgcg
aagtagggtgtctg----------ttccggcgcaagctggggtggacga-gggtcgatcc
atttgggaaacgt--tgtgtgcgctt------------
>Phytophthora_cryptogea_VHS14620_EU301142 Phytophthora_cryptogea_VHS14620_EU301142 909 bp 
ccacacct--aaaaaactttccacgtgaaccgtatcaacctttttaaattgggggctccc
gt-------------ctggccggccggttttcggctggctg-----ggtggcggctctat
c-------at-ggcgaccgcttgggcctc----------ggcctgggctagtag----cg
tattttttaaacccatt-cctaattactgaa-tatactgtggggacgaaagtctctgctt
ttaactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacgct
gcgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaacgc
atattgcacttccgggttagtcctgggagtatgcctgtatcagtgtccgtacactaaact
tggctcccttccttccgtgtagtcggtggatggggacgcgcag-atgtgaagtgtcttgc
gg-ct----ggtcttcggtcc--ggct--gcgagtcctttgaaatgtactacactgtact
-tctctttgctcgaaaagc-gt--gacgttgctggttgtggaggctgcc-tgtgtggcat
gtc-ggcnaccggtttgtctgctgcggcg-tttaatggaggagtgttcgattcgcggtat
gattggcttcggctgaacag-acgcttattgggt-gcttttcc-tgctg-tggct---gg
atggactggtgaaccgtagctgtgctaggcttggcgtttgaaccggcggtg--tggtgcg
aagtagggtgtctg----------ttccggcgcaagctggggtggacga-gggtcgatcc
atttgggaaacgt--tgtgtgcgctt------------
>Phytophthora_drechsleri_ATCC46742_AF266798 Phytophthora_drechsleri_ATCC46742_AF266798 909 bp 
ccacacct--aaaaaac-ttccacgtgaaccgtatcaacctttttaaattgggggcttcc
gt-------------ctggccggccggttctcggctggctg-----ggtggcggctctat
c-------at-ggcgaccgcctgggcctc----------ggcctgggttagtag----cg
tattttttaaa-ccatt-cctaattactgaa-aaaactgtggggacgaaagtctctgctt
ttaactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacgct
gcgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaacgc
atattgcacttccgggttagtcctgggagtatgcctgtatcagtgtccgtacactaaact
tggctcccttccttccgtgtagtcggtggatggggacgcgcag-atgtgaagtgtcttgc
gg-ct----ggtcttcggtcc--ggct--gcgagtccttttaaatgtactacactgtact
-tctctttgctcgaaaagc-gt--gacgttgctggttgtggaggctgcc-tgtgtggcat
gtc-ggcgaccggtttgtctgctgcggcgttttaatggaggagtgttcgattcgcggtat
ggttggcttcggctgaacag-acgcttattgggt-gctttttc-tgctg-cggcg---gg
atggactggtgaaccgtagctgtgctaggcttggcgtttgaaccggcggta--ttgtgcg
aagtagggtgtctg----------tctcggcgcaagctggggtgggcga-gggtcgatcc
atttgggaaacgt--tgtgtgcgctt------------
>Phytophthora_drechsleri_DSM62680_AY878548 Phytophthora_drechsleri_DSM62680_AY878548 909 bp 
ccacacct--aaaaaac-ttccacgtgaaccgtatcaacctttttaaattgggggcttcc
gt-------------ctggccggccggttctcggctggctg-----ggtggcggctctat
c-------at-ggcgaccgcctgggcctc----------ggcctgggttagtag----cg
tattttttaaa-ccatt-cctaattactgaa-aaaactgtggggacgaaagtctctgctt
ttaactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacgct
gcgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaacgc
atattgcacttccgggttagtcctgggagtatgcctgtatcagtgtccgtacactaaact
tggctcccttccttccgtgtagtcggtggatggggacgcgcag-atgtgaagtgtcttgc
gg-ct----ggtcttcggtcc--ggct--gcgagtccttttaaatgtactacactgtact
-tctctttgctcgaaaagc-gt--gacgttgctggttgtggaggctgcc-tgtgtggcat
gtc-ggcgaccggtttgtctgctgcggcgttttaatggaggagtgttcgattcgcggtat
ggttggcttcggctgaacag-acgcttattgggt-gctttttc-tgctg-cggcg---gg
atggactggtgaaccgtagctgtgctaggcttggcgtttgaaccggcggta--ttgtgcg
aagtagggtgtctg----------tctcggcgcaagctggggtgggcga-gggtcgatcc
atttgggaaacgt--tgtgtgcgctt------------
>Phytophthora_erythroseptica_ATCC36302_AF266797 Phytophthora_erythroseptica_ATCC36302_AF266797 909 bp 
ccacacct--aaaaaactttccacgtgaaccgtatcaacctttttaaattgggggcttcc
gt-------------ctggccggccggttttcggctggctg-----ggtggcggctctat
c-------at-ggcgaccgcttgggcctc----------ggcctgggctagtag----cg
tattttt--aaaccatt-cctaattactgaa-tatactgtggggacgaaagtctctgctt
ttaactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacgct
gcgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaacgc
atattgcacttccgggttagtcctgggagtatgcctgtatcagtgtccgtacactaaact
tggctcccttccttccgtgtagtcggtggatggggacgcgcag-atgtgaagtgtcttgc
gg-ct----ggtcttcggtcc--ggct--gcgagtcctttgaaatgtactacactgtact
-tctctttgctcgaaaagc-gt--gacgttgctggttgtggaggctgcc-tgtgtggcat
gtc-ggcgaccggtttgtctgctgcggcg-tttaatggaggagtgttcgattcgcggtat
ggttggcttcggctgaacag-acgcttattgggt-gcttttcc-tgctg-tggct---gg
atggactggtgaaccgtagctgtgctaggcttggcgtttgaaccggcggtg--tggtgcg
aagtagggtgtctg----------ttccggcgtaagctggggtggacga-gggtcgatcc
atttgggaaacgt--tgtgtgcgctt------------
>Phytophthora_fallax_NZFS446_DQ297397 Phytophthora_fallax_NZFS446_DQ297397 909 bp 
ccacacct-taaaaaat--tccacgtgaactgtattgtcaaccaaattcgggga--ttcc
ttgctagcgtgccttcgggcgtgc------------------cggtaggttgagacccat
c---------aaacgaaaacatcggctga--------aaggtcggagccagtag----tt
acctttgtaaacccttt-actaaatactgaa--aaactgtggggacgaaagtccttgctt
tt-actagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacgct
gcgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaacgc
atattgcacttccgggttatgcctggaagtatgcctgtatcagtgtccgtatatcaaact
tgccttccttccttccgtgtagtcggtggatgggaacgtgcag-atgtgaagtgtcttgg
cg-gcgt--cgcttcggcggt--gctg--gcgagtccttttaaatacaagatactgttct
-tctctttgctcgaaaagc-gt--gtgggatgtggttgtggaggctgcc-tgcgtggcca
gtc-ggcgactgattt-cgtgctgagacg-----gtggggaggggcttgattcgcggtat
ggttggcttcggctgaactt-ctgcttattgggc-ttctttca-tgtct-tggcg-tatg
cgatttcggtgtaccgtagctgtgtgtggcttggcttttgaaccgtgttct--gtgtgcg
aagtagagtgggca----------tgtggttttcggactgcgtggccgaggggacgagac
cttttgggaaattgtgctgc-tacttttgtggcggcat
>Phytophthora_fallax_NZFS448_DQ297398 Phytophthora_fallax_NZFS448_DQ297398 909 bp 
ccacacct-aaaaaaat--tccacgtgaactgtattgtcaaccaaattcgggga--ttcc
ttgctagcgtgccttcgggcgtgc------------------cggtaggttgagacccat
c---------aaacgaaaacatcggctga--------aaggtcggagccagtag----tt
acctttgtaaacccttt-actaaatactgaa--aaactgtggggacgaaagtccttgctt
tt-actagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacgct
gcgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaacgc
atattgcacttccgggttatgcctggaagtatgcctgtatcagtgtccgtatatcaaact
tgccttccttccttccgtgtagtcggtggatgggaacgtgcag-atgtgaagtgtcttgg
cg-gcgt--cgcttcggcggt--gctg--gcgagtccttttaaatacaagatactgttct
-tctctttgctcgaaaagc-gt--gtgggatgtggttgtggaggctgcc-tgcgtggcca
gtc-ggcgactgattt-cgtgctgagacg-----gtggggaggggcttgattcgcggtat
ggttggcttcggctgaactt-ctgcttattgggc-ttctttca-tgtct-tggcg-tatg
cgatttcggtgtaccgtagctgtgtgtggcttggcttttgaaccgtgttct--gtgtgcg
aagtagagtgggca----------tgtggttttcggactgcgtggccgaggggacgagac
cttttgggaaattgtgctgc-tacttttgtggcggcat
>Phytophthora_frigida_CMW19434_DQ988178 Phytophthora_frigida_CMW19434_DQ988178 909 bp 
ccacacctaaaaaaaactttccacgtgaaccgtatcaacccttttaattggggat-ttgc
ttggtgtgc-ggctagctggcc-ttattggctggcaggctgcgtgctaggcgagtcctat
c-------at-ggcaaacgtttggg-ttc----------ggcttgagctagtag-----c
ttttttttaaaccattt-ctttaatactgat-tatactgtggggacgaaagtctctgctt
ttaactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacgct
gcgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaacgc
atattgcacttccgggttagtcctggaagtatgcctgtatcagtgtccgtacatcaaaat
tggctttcttccttccgtgtagtcggtgga-ggatgtgc-cagaatgtgaagtgtcttgc
gg-ct----ggccttcgggtt--gact--gcgagtccttttaaatgtactgaactgtatt
-cctctttgctcgaaaagt-aa--ggcgttgcttgttgtggaggctgcc-cgtgtggcca
gtc-ggcgactggtttgtctgctgcggtgttttactggaggagtgttcgattcgcggtat
ggttggcttcggctgaacag-acgcttattgggt-gtttttcc-tgctg-tggcg---tg
atggactggtgaaccgtagctatgta-ggcttggcttttgaaccggtgatac-tattgcg
aagtagagtggcgg----------cttcggc------------tgccgaggggtcgatcc
attttgggaacttcatgtgtgtactt------------
>Phytophthora_frigida_CMW19435_DQ988177 Phytophthora_frigida_CMW19435_DQ988177 909 bp 
ccacacctaaaaaaaactttccacgtgaaccgtatcaacccttttaattggggat-ttgc
ttggtgtgc-ggctagctggcc-ttattggctggcaggctgcgtgctaggcgagtcctat
c-------at-ggcaaacgtttggg-ttc----------ggcttgagctagtag-----c
ttttttttaaaccattt-ctttaatactgat-tatactgtggggacgaaagtctctgctt
ttaactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacgct
gcgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaacgc
atattgcacttccgggttagtcctggaagtatgcctgtatcagtgtccgtacatcaaaat
tggctttcttccttccgtgtagtcggtgga-ggatgtgc-cagaatgtgaagtgtcttgc
gg-ct----ggccttcgggtt--gact--gcgagtccttttaaatgtactgaactgtatt
-cctctttgctcgaaaagt-aa--ggcgttgcttgttgtggaggctgcc-cgtgtggcca
gtc-ggcgactggtttgtctgctgcggtgttttactggaggagtgttcgattcgcggtat
ggttggcttcggctgaacag-acgcttattgggt-gtttttcc-tgctg-tggcg---tg
atggactggtgaaccgtagctatgta-ggcttggcttttgaaccggtgatac-tattgcg
aagtagagtggcgg----------cttcggc------------tgccgaggggtcgatcc
attttgggaacttcatgtgtgtactt------------
>Phytophthora_inflata_InfGaul_AY879291 Phytophthora_inflata_InfGaul_AY879291 909 bp 
ccccacct--aaaaaacttttcacgtgaaccgtatcaacccttttagttgggggtcttgc
tt------------------------------------------tttttgcgagccctat
c-------at-ggcgaatgtttggacttc----------ggtctgggctagtag--c-tt
tttgttttaaacccatt-ctacaatactgat-tatactgcggggacgaaagtctctgctt
ttaactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacgct
gcgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaacgc
atattgcacttccgggttagtcctgggagtatgcctgtatcagtgtccgtacatcaaact
tggctttcttccttccgtgtagtcggtgga-ggatgtgc-cag-acgtgaagtgtcttgc
gg-gt----gtccttcgggtc--gtct--gcgagtcctttgaaatgtactgaactgtact
-tctctttgctcgaaaagc-gt--ggtgttgctggttgtggaggctgcc-tgcgtggcca
gtc-ggcgaccggtttgtctgctgcggcg-tttaatggaggagtgttcgattcgcggtat
ggttggcttcggctgaacag-gcgcttattgtat-gcttttcc-tgctg-tggcg---tg
atgggctggtgaaccgtagctgtgtgtggcttggcttttgaatcggctttgc-tgttgcg
aagtagagtggcgg----------cttcggc------------tgtcga-gggtcgatcc
atttgggaacta---agtgtgcacct------------
>Phytophthora_inflata_InfRhod2_AY879293 Phytophthora_inflata_InfRhod2_AY879293 909 bp 
ccccacct--aaaaaacttttcacgtgaaccgtatcaacccttttagttgggggtcttgc
tt------------------------------------------tttttgcgagccctat
c-------at-ggcgaatgtttggacttc----------ggtctgggctagtag--c-tt
tttgttttaaacccatt-ctacaatactgat-tatactgcggggacgaaagtctctgctt
ttaactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacgct
gcgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaacgc
atattgcacttccgggttagtcctgggagtatgcctgtatcagtgtccgtacatcaaact
tggctttcttccttccgtgtagtcggtgga-ggatgtgc-cag-acgtgaagtgtcttgc
gg-gt----gtccttcgggtc--gtct--gcgagtcctttgaaatgtactgaactgtact
-tctctttgctcgaaaagc-gt--ggtgttgctggttgtggaggctgcc-tgcgtggcca
gtc-ggcgaccggtttgtctgctgcggcg-tttaatggaggagtgttcgattcgcggtat
ggttggcttcggctgaacag-gcgcttattgtat-gcttttcc-tgctg-tggcg---tg
atgggctggtgaaccgtagctgtgtgtggcttggcttttgaatcggctttgc-tgttgcg
aagtagagtggcgg----------cttcggc------------tgtcga-gggtcgatcc
atttgggaacta---agtgtgcacct------------
>Phytophthora_inundata_P1032_AF541914 Phytophthora_inundata_P1032_AF541914 909 bp 
ccacacct--aaaaaactttccacgtgaaccgtatcaaccccttaagattgggagcttgc
tcggcggcgtgcgtgctggcctgtaatgggtcggcgtgctg-ctgctgggcgggctctat
c-------atgggcgagcgtttgggcttc----------ggctcgagctagtag---ctt
tttcttttaaacccctt-ctttaattactga-aatactgtggggacgaaagtctctgctt
ttaactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacgct
gcgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaacgc
atattgcacttccgggttcgtcctggaagtatgcctgtatcagtgtccgtacatcaacct
tggttttcttccttccgtgtagtcggtgga-ggatatgc-cag-acgtgaagtgtcttgc
ta-gc----ggtctttcgagtctgccg--gcgagtcctttgaaatgtactgaactgtact
ctctctttgctcgaaaagc-gt--ggcgttgctggttgtggaggctgcc-cgtatggcca
gtc-ggcgaccggtttgttagctgtagta-tatactggaggagtgttcgattcgcggtat
ggttggcttcggctgaacaatctgcttattgggt-gcttttcc-tgctattggcg---gt
acaaactggtgaaccgtagctgtgtggagcttggcttttgaatcggctttgc---ttgcg
aagtagagtggcgg----------cttcggc------------tgccgaggggtcgatcc
attttgggaaatta-tgtgtgtgcggctt---------
>Phytophthora_inundata_P246B_AF266791 Phytophthora_inundata_P246B_AF266791 909 bp 
ccacacct--aaaaaactttccacgtgaaccgtatcaaccccttaagattgggagcttgc
tcggcggcgtgcgtgctggcctgtaatgggtcggcgtgctg-ctgctgggcgggctctat
c-------atgggcgagcgtttgggcttc----------ggctcgagctagtag---ctt
tttcttttaaacccctt-ctttaattactga-aatactgtggggacgaaagtctctgctt
ttaactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacgct
gcgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaacgc
atattgcacttccgggttcgtcctggaagtatgcctgtatcagtgtccgtacatcaacct
tggttttcttccttccgtgtagtcggtgga-ggatatgc-cag-acgtgaagtgtcttgc
ta-gc----ggtctttcgagtctgccg--gcgagtcctttgaaatgtactgaactgtact
ctctctttgctcgaaaagc-gt--ggcgttgctggttgtggaggctgcc-cgtatggcca
gtc-ggcgaccggtttgttagctgtagta-tatactggaggagtgttcgattcgcggtat
ggttggcttcggctgaacaatctgcttattgggt-gcttttcc-tgctattggcg---gt
acaaactggtgaaccgtagctgtgtggagcttggcttttgaatcggctttgc---ttgcg
aagtagagtggcgg----------cttcggc------------tgccgaggggtcgatcc
attttgggaaatta-tgtgtgtgcggctt---------
>Phytophthora_macrochlamydospora_T10455_L41373 Phytophthora_macrochlamydospora_T10455_L41373 909 bp 
ccacacct---aaaacttttccacgtgaaccgtatttt----tgacgttgggga--ctcc
tggctt------------------------------------cggccggttgagacctat
c---------acgcgaccgctcgggctga--------aaagtcggggccagtag-----c
ctttttttaaacccatt-ccgaactactgaaccatactgtggggacgaaagtccttgctt
ttaactagatagcaactttcagcagtggatgtctaggctcgcacatcgatggaggaccct
gcgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaacgc
atattgcacttccgggttatgcctgggagtatgcctgtatcagtgtccgtacatgaaact
tggctcccttccttccgtgtagtcggtggatggggacgcgcag-acgtgaagtgtcttgc
gg-cgg---cggcttcggccggctgct--gcgagtcctttgaaatgta-agacctgttct
-tctctttgcccgaaaagc-gttgcgtgagtgtggttgtggaggctgccgtttgcggcat
gtc-ggcgactgattt-cgtgctgaggcg----tgtggggagaggctcgattcgcggtat
ggttggcttcggctgaactt-ctgcttattggtc-tttttttcgcggctttggcgttttg
cggggtcggtgtaccgtagctgcgggtggcttggcctttgaaccgtgttcgtgcggagcg
aagtaaggtgggcg------------tgactgtagtgttatggccgagggggacgcaacc
atttgggaaagtaa-------tgcttttctgccggctt
>Phytophthora_macrochlamydospora_T10456_L41372 Phytophthora_macrochlamydospora_T10456_L41372 909 bp 
ccacacct---aaaacttttccacgtgaaccgtatttt----tgacgttgggga--ctcc
tggctt------------------------------------cggccggttgagacctat
c---------acgcgaccgctcgggctga--------aaagtcggggccagtag-----c
ctttttttaaacccatt-ccgaactactgaaccatactgtggggacgaaagtccttgctt
ttaactagatagcaactttcagcagtggatgtctaggctcgcacatcgatggaggaccct
gcgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaacgc
atattgcacttccgggttatgcctgggagtatgcctgtatcagtgtccgtacatgaaact
tggctcccttccttccgtgtagtcggtggatggggacgcgcag-acgtgaagtgtcttgc
gg-cgg---cggcttcggccggctgct--gcgagtcctttgaaatgta-agacctgttct
-tctctttgcccgaaaagc-gttgcgtgagtgtggttgtggaggctgccgtttgcggcat
gtc-ggcgactgattt-cgtgctgaggcg----tgtggggagaggctcgattcgcggtat
ggttggcttcggctgaactt-ctgcttattggtc-tttttttcgcggctttggcgttttg
cggggtcggtgtaccgtagctgcgggtggcttggcctttgaaccgtgttcgtgcggagcg
aagtaaggtgggcg------------tgactgtagtgttatggccgagggggacgcaacc
atttgggaaagtaa-------tgcttttctgccggctt
>Phytophthora_megakarya_IMI337104_AF266782 Phytophthora_megakarya_IMI337104_AF266782 909 bp 
ccacacct---aaaaactttccacgtgaaccgtatcaacc--tttagttgggggtctttt
tcggcggc--ggctgctggtttaattactggcggttg-----ctgctgggagagccctat
c-------at-ggcgagcgtttgggcttc----------ggtctgaactagtag------
-cttttttaaacccatt-cattattactgat-tatactgtggggacgaaagtctctgctt
ttaactagatagcaactttcagcagtggatgtctaggctcgcacctcgatgaagaacgct
gcgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaacgc
atattgcacttccgggttagtcctggaagtatgcctgtatcagtgtccgtacatcaaact
tggttttcttccttccgtgtagtcggtgga-ggatatgc-cag-atgtgaggtgtcttgc
gg-ct----ggccttcgggtc--ggct--gtgagtcccttgaaatgtactgaactgtact
-tctctttgctcgaaaagt-aa--agc-ttgcttgttgtggaggctgct-tgtgtaacca
gtc-ggcgactagtttgtctgctgtggcg--ttaatggaggagtgttcgattcgcggtat
gattggcttcggctgaacag-aagcttattgggc-gtttttcc-tgcta-tggcg---gt
atgaagtagtgaaccgtagttatgtg-ggcttggcttttgaatgtgctcg---ctgtgcg
aagtagagtggcga----------ctttggt------------tgtcga-gggtcgatcc
atttgggaaatt----gtgtgtactt------------
>Phytophthora_megakarya_NS128_AJ517466 Phytophthora_megakarya_NS128_AJ517466 909 bp 
ccacacct---aaaaactttccacgtgaaccgtatcaacc--tttagttgggggtctttt
tcggcggc--ggctgctggtttaattactggcggttg-----ctgctgggagagccctat
c-------at-ggcgagcgtttgggcttc----------ggtctgaactagtag------
-cttttttaaacccatt-cattattactgat-tatactgtggggacgaaagtctctgctt
ttaactagatagcaactttcagcagtggatgtctaggctcgcacctcgatgaagaacgct
gcgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaacgc
atattgcacttccgggttagtcctggaagtatgcctgtatcagtgtccgtacatcaaact
tggttttcttccttccgtgtagtcggtgga-ggatatgc-cag-atgtgaggtgtcttgc
gg-ct----ggccttcgggtc--ggct--gtgagtcccttgaaatgtactgaactgtact
-tctctttgctcgaaaagt-aa--agc-ttgcttgttgtggaggctgct-tgtgtaacca
gtc-ggcgactagtttgtctgctgtggcg--ttaatggaggagtgttcgattcgcggtat
gattggcttcggctgaacag-aagcttattgggc-gtttttcc-tgcta-tggcg---gt
atgaagtagtgaaccgtagttatgtg-ggcttggcttttgaatgtgctcg---ctgtgcg
aagtagagtggcga----------ctttggt------------tgtcga-gggtcgatcc
atttgggaaatt----gtgtgtactt------------
>Phytophthora_megasperma_IMI33317_AF266794 Phytophthora_megasperma_IMI33317_AF266794 909 bp 
ccacacct--aaaaaactttccacgtgaaccgtatcaaccccttaaatttgggggcttgc
tcggcggcgtgtgtgctggcctgtaatgggtcggcgtgctg-ctgctgggcgggctctat
c-------atgggcgagcgtttgggcttc----------ggctcgagctagtag---cta
tcaattttaaacccttt-cttaaatactgaa-catactgtggggacgaaagtctctgctt
ttaactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacgct
gcgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaacgc
atattgcacttccgggttagtcctgggagtatgcctgtatcagtgtccgtacatcaacct
tggttttcttccttccgtgtagtcggtgga-ggatatgc-cag-atgtgaagtgtcttgc
ta-gc----ggtctttcgagtctgccg--gtgagtccttttaaatgtactgaactgtact
ctctctttgcgcgaaaagc-gt--ggcgttgctggttgtggaggctgcc-cgtgtggcca
gtc-ggcgaccggtttgttagctgtggcg----tttggaggagtgttcgattcgcggtat
ggttggcttcggctaaacaatctgcttattgggt-gcttttcc-tgtca-tggcg---gt
atgaactggtgaaccgtagctgtgtggtgcttggcttttgaaccggctttgc-t-ttgcg
aagtagtgtgacgg----------cttcggc------------tgtcgaggggtcgatcc
attttgggaaactt-tgtgtgtgcagctt---------
>Phytophthora_megasperma_SCRP682_DQ116960 Phytophthora_megasperma_SCRP682_DQ116960 909 bp 
ccacacct---aaaaactttccacgtgaaccgtatcaaccccttaaatttgggggcttgc
tcggcggcgtgtgtgctggcctgtaatgggtcggcgtgctg-ctgctgggcgggctctat
c-------atgggcgagcgtttgggcttc----------ggctcgagctagtag---cta
tcaattttaaacccttt-cttaaatactgaa-catactgtggggacgaaagtctctgctt
ttaactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacgct
gcgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaacgc
atattgcacttccgggttagtcctgggagtatgcctgtatcagtgtccgtacatcaacct
tggttttcttccttccgtgtagtcggtgga-ggatatgc-cag-atgtgaagtgtcttgc
ta-gc----ggtctttcgagtctgccg--gtgagtccttttaaatgtactgaactgtact
ctctctttgcgcgaaaagc-gt--ggcgttgctggttgtggaggctgcc-cgtgtggcca
gtc-ggcgaccggtttgttagctgtggcg----tttggaggagtgttcgattcgcggtat
ggttggcttcggctaaacaatctgcttattgggt-gcttttcc-tgtca-tggcg---gt
atgaactggtgaaccgtagctgtgtggtgcttggcttttgaaccggctttgc-t-ttgcg
aagtagtgtgacgg----------cttcggc------------tgtcgaggggtcgatcc
attttgggaaactt-tgtgtgtgcggctt---------
>Phytophthora_melonis_IMI325917_AF266767 Phytophthora_melonis_IMI325917_AF266767 909 bp 
ccacacct--aaaaaactttccacgtgaaccgtatcaaca--agtagttgggggcctgct
ctgtgtggctagctgtcgatgtcaaagtcggcgactggctg-ctatgtggcgggctctat
c-------at-ggcgattggtttgggtcctcctcgtggggaactggatcatgag----cc
caccttttaaacccatt-cttgattactgaa-tatactgtggggacgaaagtctctgctt
ttaactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacgct
gcgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaacgc
atattgcacttccgggttagtcctgggagtatgcctgtatcagtgtccgtacatcaaact
tggctctcttccttccgtgtagtcggtggatggagacgc-cag-acgtgaggtgtcttgc
ggcgc----ggccttcgggct--gcct--gcgagtcccttgaaatgtactgaactgtact
-tctctttgctcgaaaagc-gt--gacgttgttggttgtggaggctgcc-tgtatggcca
gtc-ggcgaccagtttgtctgctgcggcg-tttaatggaggagtgttcgattcgcggtat
ggttggcttcggctgaacaatgcgcttattggat-gcttttcc-tgctg-tggtg---gt
atgggctggtgaaccgtagttgtgcgaggcttggcttttgaaccggcggtgt-tgtagcg
aagtagagtggcgg----------cttcggc------------tgtcga-gggtcgatcc
atttgggaactc---tgtgttgtctctgcggctt----
>Phytophthora_melonis_P12_AY739021 Phytophthora_melonis_P12_AY739021 909 bp 
ccacacct--aaaaaactttccacgtgaaccgtatcaaca--agtagttgggggcctgct
ctgtgtggctagctgtcgatgtcaaagtcggcgactggctg-ctatgtggcgggctctat
c-------at-ggcgattggtttgggtcctcctcgtggggaactggatcatgag----cc
ca-cttttaaacccatt-cttgattactgaa-tatactgtggggacgaaagtctctgctt
ttaactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacgct
gcgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaacgc
atattgcacttccgggttagtcctgggagtatgcctgtatcagtgtccgtacatcaaact
tggctctcttccttccgtgtagtcggtggatggagacgc-cag-acgtgaggtgtcttgc
ggcgc----ggccttcgggct--gcct--gcgagtcccttgaaatgtactgaactgtact
-tctctttgctcgaaaagc-gt--gacgttgttggttgtggaggctgcc-tgtatggcca
gtc-ggcgaccagtttgtctgctgcggcg-tttaatggaggagtgttcgattcgcggtat
ggttggcttcggctgaacaatgcgcttattggat-gcttttcc-tgctg-tggtg---gt
atgggctggtgaaccgtagttgtgcgaggcttggcttttgaaccggcggtgt-tgtagcg
aagtagagtggcgg----------cttcggc------------tgtcga-gggtcgatcc
atttgggaactc---tgtgttgtctctgcggctt----
>Phytophthora_multivesiculata_CBS545_96_AF266790 Phytophthora_multivesiculata_CBS545.96_AF266790 909 bp 
ccacacct--aaaaaactttccacgtgaaccgtatcaacccctttagttgggggtcttgc
ttggcgtgc-ggctgctggcct-ttattggttggctggctgcgtgctgggcgagccctat
c-------at-ggcgatcgtttggacctc----------ggtctgagctagtag----ct
tttgttttaaacccatt-ctttaatactgat-tatactgtggggacgaaagtctctgctt
ttaactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacgct
gcgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaacgc
atattgcacttccgggttagtcctgggagtatgcctgtatcagtgtccgtacatcaaact
tggctttcttccttccgtgtagtcggtgga-ggagacgt-cag-atgtgaagtgtcttgc
gg-tt----ggccttcgggtc--gtct--gcgagtcctttgaaatgtactgaactgtact
ctctctttgctcgaaaagc-gt--ggtattgttggttgtggagactgcc-tgtgtggcca
gtc-ggcgaccggtttgtctgctacggcg-tttaatggaggagtgttcgattcgcggtat
ggttggcttcggctgaacag-acgcttattggac-gtttttcc-tgctg-tggcg---tg
atgggctggtgaaccgtagctgtgtttggcttggtctttgaatcggctttgc-tgttgcg
aagtagagcggcgg----------cttcggc------------tgtcgaggggtcgatcc
attttgggaagtt--tgtgtgtactt------------
>Phytophthora_multivesiculata_CDL05_1_DQ835678 Phytophthora_multivesiculata_CDL05.1_DQ835678 909 bp 
ccacacct--aaaaaactttccacgtgaaccgtatcaacccctttagttgggggtcttgc
ttggcgtgc-ggctgctggcct-ttattggttggctggctgcgtgctgggcgagccctat
c-------at-ggcgatcgtttggacctc----------ggtctgagctagtag----ct
tttgttttaaacccatt-ctttaatactgat-tatactgt-gggacgaaagtctctgctt
ttaactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacgct
gcgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaacgc
atattgcacttccgggttagtcctgggagtatgcctgtatcagtgtccgtacatcaaact
tggctttcttccttccgtgtagtcggtgga-ggagacgt-cag-atgtgaagtgtcttgc
gg-tt----ggccttcgggtc--gtct--gcgagtcctttgaaatgtactgaactgtact
ctctctttgctcgaaaagc-gt--ggtattgttggttgtggagactgcc-tgtgtggcca
gtc-ggcgaccggtttgtctgctacggcg-tttaatggaggagtgttcgattcgcggtat
ggttggcttcggctgaacag-acgcttattggac-gtttttcc-tgctg-tggcg---tg
atgggctggtgaaccgtagctgtgtttggcttggtctttgaatcggctttgc-tgttgcg
aagtagagcggcgg----------cttcggc------------tgtcgaggggtcgatcc
attttgggaagtt--tgtgtgtactt------------
>Phytophthora_nicotianae_DDS3453_EU301133 Phytophthora_nicotianae_DDS3453_EU301133 909 bp 
ccacacct--aaaaaactttccacgtgaaccgtttc-aacccaatagttgggggtcttat
ttggcggc--ggctgctggcttaattgttggcggctg-----ctgctgagtgagccctat
c-aaaaaaaa-ggcgaacgtttgggcttc----------ggcctgatttagtagtctttt
tttcttttaaacccatt-ccttaatactgaa-tatactgtggggacgaaagtctctgctt
ttaactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacgct
gcgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaacgc
atattgcacttccgggttagtcctggaagtatgcctgtatcagtgtccgtacattaaact
tgactttcttccttccgtgtagtcggtgga-ggagatgt-cag-atgtgaagtgtcttgc
ga-tt----ggtcttcggacc--ggct--gcgagtccttttaaatgtactaaactgaact
-tctctttgctcgaaaagtggt--ggcgttgctggttgtgaaggctgct-attgtggcaa
att-ggcgactggtttgtctgctgcggcg--ttaatggaagagtgttcgattcgtggtat
ggttggcttcggctgaacaatgcacttattggac-gtttttcc-tgctg-tggcg---tg
atggactggtgaaccatagctcggt--ggcttggcttttgaattggctttgc-tgttgcg
aagtagggtggcag----------cttcggt------------tgtcga-gggtcgatcc
atttgggaactt---aatgtgtactt------------
>Phytophthora_nicotianae_UQ848_AF266776 Phytophthora_nicotianae_UQ848_AF266776 909 bp 
ccacacct-aaaaaaactttccacgtgaaccgtttc-aacccaatagttgggggtcttat
ttggcggc--ggctgctggcttaattgttggcggctg-----ctgctgagtgagccctat
c-aaaaaaaa-ggcgaacgtttgggcttc----------ggcctgatttagtagtctttt
tttcttttaaacccatt-ccttaatactgaa-tatactgtggggacgaaagtctctgctt
ttaactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacgct
gcgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaacgc
atattgcacttccgggttagtcctggaagtatgcctgtatcagtgtccgtacattaaact
tgactttcttccttccgtgtagtcggtgga-ggagatgt-cag-atgtgaagtgtcttgc
ga-tt----ggtcttcggacc--ggct--gcgagtccttttaaatgtactaaactgaact
-tctctttgctcgaaaagtggt--ggcgttgctggttgtgaaggctgct-attgtggcaa
att-ggcgactggtttgtctgctgcggca--ttaatggaagagtgttcgattcgtggtat
ggttggcttcggctgaacaatgcacttattggac-gtttttcc-tgctg-tggcg---tg
atggactggtgaaccatagctcggt--ggcttggcttttgaattggctttgc-tgttgcg
aagtagggtggcag----------cttcggt------------tgtcga-gggtcgatcc
atttgggaactt---aatgtgtactt------------
>Phytophthora_nicotianae_VHS16097_EU301134 Phytophthora_nicotianae_VHS16097_EU301134 909 bp 
ccacacct--aaaaaactttccacgtgaaccgtttc-aacccaatagttgggggtcttat
ttggcggc--ggctgctggcttaattgttggcggctg-----ctgctgagtgagccctat
caaaaaaaaa-ggcgaacgtttgggcttc----------ggcctgatttagtagtctttt
tttcttttaaacccatt-ccttaatactgaa-tatactgtggggacgaaagtctctgctt
ttaactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacgct
gcgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaacgc
atattgcacttccgggttagtcctggaagtatgcctgtatcagtgtccgtacattaaact
tgactttcttccttccgtgtagtcggtgga-ggagatgt-cag-atgtgaagtgtcttgc
ga-tt----ggtcttcggacc--ggct--gcgagtccttttaaatgtactaaactgaact
-tctctttgctcgaaaagtggt--ggcgttgctggttgtgaaggctgct-attgtggcaa
att-ggcgactggtttgtctgctgcggcg--ttaatggaagagtgttcgattcgtggtat
ggttggcttcggctgaacaatgcacttattggac-gtttttcc-tgctg-tggcg---tg
atggactggtgaaccatagctcggt--ggcttggcttttgaattggctttgc-tgttgcg
aagtagggtggcag----------cttcggt------------tgtcga-gggtcgatcc
atttgggaactt---aatgtgtactt------------
>Phytophthora_niederhauserii_P831_EF050511 Phytophthora_niederhauserii_P831_EF050511 909 bp 
ccacacct--aaaaaactttccacgtgaaccgtatcaaca--agtagttgggggcctgct
ctgtgtggctggctgtcgatgtcaaagtcgacggctggctg-ctgtgtggcgggctctat
c-------at-ggcgattggtttgggtcctcctcgtggggaactggatcatgag----cc
cactttttaaacccatt-cttaaatactgaa-tatactgtggggacgaaagtctctgctt
ttaactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacgct
gcgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaacgc
atattgcacttccgggttagtcctgggagtatgcctgtatcagtgtccgtacatcaaact
tggctctcttccttccgtgtagtcggtggatggagacgc-cag-acgtgaggtgtcttgc
ggcgc----ggccttcgggct--gcct--gcgagtcccttgaaatgtactgaactgtact
-tctctttgctcgaaaagc-gt--gacgttgttggttgtggaggctgcc-tgtatggcca
gtc-ggcgaccggtttgtctgctgcggcg-tttaatggaggagtgttcgattcgcggtat
ggttggcttcggctgaacaatgcgcttattggat-gcttttcc-tgctg-tggcg---gt
atgggctggtgaaccgtagctgtgcgaggcttggcttttgaaccggcggtgt-tgttgcg
aagtagggtggcgg----------cttcggc------------tgtcga-gggtcgatcc
atttgggaactc---tgtgttgtctctgcggctt----
>Phytophthora_niederhauserii_VHS17577_EU301137 Phytophthora_niederhauserii_VHS17577_EU301137 909 bp 
ccacacct--aaaaaactttccacgtgaaccgtatcaaca--agtagttgggggcctgct
ctgtgtggctgtctgtcgatgtcaaagtcgacggctggctg-ctgtgtggcgggctctat
c-------at-ggcgattggtttgggtcctcctcgtggggaactggatcatgag----cc
cactttttaaacccatt-cttaaatactgaa-tatactgtggggacgaaagtctctgctt
ttaactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacgct
gcgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaacgc
atattgcacttccgggttagtcctgggagtatgcctgtatcagtgtccgtacatcaaact
tggctctcttccttccgtgtagtcggtggatggagacgc-cag-acgtgaggtgtcttgc
ggcgc----ggccttcgggct--gcct--gcgagtcccttgaaatgtactgaactgtact
-tctctttgctcgaaaagc-gt--gacgttgttggttgtggaggctgcc-tgtatggcca
gtc-ggcgaccggtttgtctgctgcggcg-tttaatggaggagtgttcgattcgcggtat
ggttggcttcggctgaacaatgcgcttattggat-gcttttcc-tgctg-tggcg---gt
atgggctggtgaaccgtagctgtgcgaggcttggcttttgaaccggcggtgt-tgttgcg
aagtagggtggcgg----------cttcggc------------tgtcga-gggtcgatcc
atttgggaactc---tgtgttgtctctgcggctt----
>Phytophthora_palmivora_TARS8_DQ987922 Phytophthora_palmivora_TARS8_DQ987922 909 bp 
ccacacct---aaaaactttccacgtgaaccgtatcaaaa--cttagttgggggtctctt
tcggcggc--ggctgctggcttcattgctggcggctg-----ctgttgggagagctctat
c-------at-ggcgagcgtttgggcttc----------ggtctgaactagtag------
-cttttttaaacccatt-ctttataactgat-tatactgtagggacgaaagtctctgctt
ttaactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacgct
gcgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaacgc
atattgcacttccgggttagtcctgggagtatgcctgtatcagtgtccgtacatcaaact
tggttttcttccttccgtgtagtcggtggt-ggatgtgc-cag-atgtgaagtgtcttgc
gg-ct----ggtcttcggatc--ggct--gtgagtcctttgaaatgtactgaactgtact
-tctctttgctccaaaagc-gt--ggcgttgctgattgtggaggctgct-tgcgtagcca
gtctggcgaccagtttgtctgctgtggcg--ttaatggaggagtgttcgattcgcggtat
ggttggcttcggctgaacag-acgcttattgaat-atttcttc-agctg-tggtg---gt
at-gattggtgaaccgtagctatgtg-agcttggcttttgaattggctttgc-tgttgcg
aagtagagtggcgg----------cttcggc------------tgtcga-gggtcgatcc
atttgggaactt----gtgtatgctt------------
>Phytophthora_palmivora_UQ1294_AF266780 Phytophthora_palmivora_UQ1294_AF266780 909 bp 
ccacacct--aaaaaactttccacgtgaaccgtatcaaaa--cttatttgggggtctctt
tcggcggc--ggctgctggcttcattgctggcggctg-----ctgttgggagagctctat
c-------at-ggcgagcgtttgggcttc----------ggtctgaactagtag------
-cttttttaaacccatt-ctttataactgat-tatactgtagggacgaaagtctctgctt
ttaactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacgct
gcgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaacgc
atattgcacttccgggttagtcctgggagtatgcctgtatcagtgtccgtacatcaaact
tggttttcttccttccgtgtagtcggtggt-ggatgtgc-cag-atgtgaagtgtcttgc
gg-ct----ggtcttcggatc--ggct--gtgagtcctttgaaatgtactgaactgtact
-tctctttgctccaaaagc-gt--ggcgttgctgattgtggaggctgct-tgcgtagcca
gtctggcgaccagtttgtctgctgtggcg--ttaatggaggagtgttcgattcgcggtat
ggttggcttcggctgaacag-acgcttattgaat-atttcttc-agctg-tggtg---gt
at-gattggtgaaccgtagctatgtg-agcttggcttttgaattggctttgc-tgttgcg
aagtagagtggcgg----------cttcggc------------tgtcga-gggtcgatcc
atttgggaactt----gtgtatgctt------------
>Phytophthora_quercetorum_MND4_EF539180 Phytophthora_quercetorum_MND4_EF539180 909 bp 
ccacacct--aaaaaactttccacgtgaaccgtatcaaac--tttagttgggggtctttt
tcggcgac--ggctgctggcttcattgctggcggctg-----ctgttggatgagccctat
c-------at-ggcgagcgtttgggcttc----------ggtctgaactagtag------
-cttttttaaacccatt-ctttattactgat-tatactgtggggacgaaagtctctgctt
ttaactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacgct
gcgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaacgc
atattgcacttccgggttagtcctgggagtatgcctgtatcagtgtccgtacatcaaact
tggctttcttccttccgtgtagtcggtgga-ggatgtgc-cag-atgtgaagtgtcttgc
gg-ct----ggtcttcgggtc--ggct--gtgagtcctttgaaatgtactgaactgtact
-tctctttgctcgaaaagc-gt--ggcgttgctgattgtggaggctgcc-tgcgtagcca
gtctggcgaccagtttgtctgctgtggcg--ttaatggaggagtgttcgattcgcggtat
ggttggcttcggctgaacag-acgcttattgaat-gtttttcc-tgctg-tggcg---gt
acgggttggtgaaccgtagctatgtg-ggcttggcttttgaattggctttgc-tgttgcg
aagtagagtggcag----------cttcggc------------tgtcga-gggtcgatcc
atttgggaattt----gtgtgtactt------------
>Phytophthora_quercetorum_WI111_EF539179 Phytophthora_quercetorum_WI111_EF539179 909 bp 
ccacacct--aaaaaactttccacgtgaaccgtatcaaac--tttagttgggggtctttt
tcggcgac--ggctgctggcttcattgctggcggctg-----ctgttggatgagccctat
c-------at-ggcgagcgtttgggcttc----------ggtctgaactagtag------
-cttttttaaacccatt-ctttattactgat-tatactgtggggacgaaagtctctgctt
ttaactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacgct
gcgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaacgc
atattgcacttccgggttagtcctgggagtatgcctgtatcagtgtccgtacatcaaact
tggctttcttccttccgtgtagtcggtgga-ggatgtgc-cag-atgtgaagtgtcttgc
gg-ct----ggtcttcgggtc--ggct--gtgagtcctttgaaatgtactgaactgtact
-tctctttgctcgaaaagc-gt--ggcgttgctgattgtggaggctgcc-tgcgtagcca
gtctggcgaccagtttgtctgctgtggcg--ttaatggaggagtgttcgattcgcggtat
ggttggcttcggctgaacag-acgcttattgaat-gtttttcc-tgctg-tggcg---gt
acgggttggtgaaccgtagctatgtg-ggcttggcttttgaattggctttgc-tgttgcg
aagtagagtggcag----------cttcggc------------tgtcga-gggtcgatcc
atttgggaattt----gtgtgtactt------------
>Phytophthora_sp__1_DDS1221_EU593265 Phytophthora_sp._1_DDS1221_EU593265 909 bp 
ccacacct--aaaaaactttccacgtgaaccgtatcaaac--tttagttgggggtctttt
tcggcgac--ggctgctggcttcattgctggcggctg-----ctgttgaatgagccctat
c-------at-ggcgagcgtttaggcttc----------ggtctgaactagtag------
-cttttttaaacccatt-ctttattactgat-tatactgtggggacgaaagtctctgctt
ttaactagatagcaactttcagcagtggatgtctaggctcgcacatngatgaagaacgct
gcgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaacgc
atattgcacttccgggttagtcctgggagtatgcctgtatcagtgtccgtacatcaaact
tggctttcttccttccgtgtagtcggtgga-agatgtgc-cag-atgtgaagtgtcttgc
gg-ct----ggtcttcgggtc--ggct--gtgagtcctttgaaatgtactgaactgtact
-tctctttgctcgaaaagc-gt--ggcgttgctgattgtggaggctgcc-tgcgtagcca
gtctggcgaccagtttgtctgctgtggcg--ttaatggaggagtgttcgattcgcggtat
ggttggctttggctgaacag-acgcttattgaat-gtttttcc-tgcta-tggcg---gt
acgggttggtgaaccgtagctatgtg-ggcttggcttttgaattggctttgc-tgttgcg
aagtagagtggcgg----------cttcggc------------tgtcga-gggtcgatcc
atttgggaattt----gtgtgtactt------------
>Phytophthora_sp__1_VHS10154_EU301114 Phytophthora_sp._1_VHS10154_EU301114 909 bp 
ccacacct--aaaaaactttccacgtgaaccgtatcaaac--tttagttgggggtctttt
tcggcgac--ggctgctggcttcattgctggcggctg-----ctgttgaatgagccctat
c-------at-ggcgagcgtttaggcttc----------ggtctgaactagtag------
-cttttttaaacccatt-ctttattactgat-tatactgtagggacgaaagtctctgctt
ttaactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacgct
gcgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaacgc
atattgcacttccgggttagtcctgggagtatgcctgtatcagtgtccgtacatcaaact
tggctttcttccttccgtgtagtcggtgga-agatgtgc-cag-atgtgaagtgtcttgc
gg-ct----ggtcttcgggtc--ggct--gtgagtcctttgaaatgtactgaactgtact
-tttctttgctcg-aaagc-gt--ggcgttgctgattgtggaggctgcc-tgcgtagcca
gtctggcgaccagtttgtctgctgtggcg--ttaatggaggagtgttcgattcgcggtat
ggttggctttggctgaacag-acgcttattgaat-gtttttcc-tgcta-tggcg---gt
acgggttggtgaaccgtagctatgtg-ggcttggcttttgaattggctttgc-tgttgcg
aagtagagtggcgg----------cttcggc------------tgtcga-gggtcgatcc
atttgggaattt----gtgtgtactt------------
>Phytophthora_sp__1_VHS9861_EU301118 Phytophthora_sp._1_VHS9861_EU301118 909 bp 
ccacacct--aaaaaactttccacgtgaaccgtatcaaac--tttagttgggggtctttt
tcggcgac--ggctgctggcttcattgctggcggctg-----ctgttgaatgagccctat
c-------at-ggcgagcgtttaggcttc----------ggtctgaactagtag------
-cttttttaaacccatt-ctttattactgat-tatactgtggggacgaaagtctctgctt
ttaactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacgct
gcgaactgcgatacgtaatgcgaattgcaggattcagtgagtnatcgaaattttgaacgc
atattgcacttccgggttagtcctgggagtatgcctgtatcagtgtccgtacatcaaact
tggctttcttccttccgtgtagtcggtgga-agatgtgc-cag-atgtgaagtgtcttgc
gg-ct----ggtcttcgggtc--ggct--gtgagtcctttgaaatgtactgaactgtact
-tctctttgctcgaaaagc-gt--ggcgttgctgattgtggaggctgcc-tgcgtagcca
gtctggcgaccagtttgtctgctgtggcg--ttaatggaggagtgttcgattcgcggtat
ggttggctttggctgaacag-acgcttattgaat-gtttttcc-tgcta-tggcg---gt
acgggttggtgaaccgtagctatgtg-ggcttggcttttgaattggctttgc-tgttgcg
aagtagagtggcgg----------cttcggc------------tgtcga-gggtcgatcc
atttgggaattt----gtgtgtactt------------
>Phytophthora_sp__2_VHS13559_EU301121 Phytophthora_sp._2_VHS13559_EU301121 909 bp 
ccacacct-aaaaaaactttccacgtgaaccgtatcaaccctttaaattgggggtcttgc
ttggtgtgc-ggctggctggcctttattggctggcaggctgcgtgctgggcgagccctat
c-------at-ggcaaacgtttgggcttc----------ggtctgagctagtag----ct
ttatttttaaacccatt-tcttaatactgat-tatactgtggggacgaaagtctctgctt
ttaactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacgct
gcgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaacgc
atattgcacttccgggttagtcctgggagtatgcctgtatcagtgtccgtacatcaaact
tggctttcttccttccgtgtagtcggtgga-ggagacgc-cag-atgtgaagtgtcttgc
gg-ct----ggctttcgggcc--gact--gcgagtcctttgaaatgtactgaactgtact
-tctctttgctcgaaaagt-gt--ggcgttgctggttgtggaggctgcc-cgcgtggcca
gtc-ggcgaccggtttgtctgctgcggcgttttactggaggagtgttcgattcgcggtat
ggttggcttcggctgaacag-gcgcttattggac-gtttttcc-tgctg-tggcg---tg
atgggctggtgaaccgtagctgtgtgtggcttggcttttgaatcggttttgc-tattgcg
aagtagagtggcgg----------cttcggc------------tgtcgaggggtcgatcc
attttgggaaactt-tgtgtgtactt------------
>Phytophthora_sp__2_VHS13663_EU301123 Phytophthora_sp._2_VHS13663_EU301123 909 bp 
ccacacct-aaaaaaactttccacgtgaaccgtatcaaccctttaaattgggggtcttgc
ttggtgtgc-ggctggctggcctttattggctggcaggctgcgtgctgggcgagccctat
c-------at-ggcaaacgtttgggcttc----------ggtctgagctagtag----ct
ttatttttaaacccatt-tcttaatactgat-tatactgtggggacgaaagtctctgctt
ttaactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacgct
gcgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaacgc
atattgcacttccgggttagtcctgggagtatgcctgtatcagtgtccgtacatcaaact
tggctttcttccttccgtgtagtcggtgga-ggagacgc-cag-atgtgaagtgtcttgc
gg-ct----ggctttcgggcc--gact--gcgagtcctttgaaatgtactgaactgtact
-tctctttgctcgaaaagt-gt--ggcgttgctggttgtggaggctgcc-cgcgtggcca
gtc-ggcgaccggtttgtctgctgcggcgttttactggaggagtgttcgattcgcggtat
ggttggcttcggctgaacag-gcgcttattggac-gtttttcc-tgctg-tggcg---tg
atgggctggtgaaccgtagctgtgtgtggcttggcttttgaatcggttttgc-tattgcg
aagtagagtggcgg----------cttcggc------------tgtcgaggggtcgatcc
attttgggaaactt-tgtgtgtactt------------
>Phytophthora_sp__2_VHS16103_EU301125 Phytophthora_sp._2_VHS16103_EU301125 909 bp 
ccacacct-aaaaaaactttccacgtgaaccgtatcaaccctttaaattgggggtcttgc
ttggtgtgc-ggctggctggcctttattggctggcaggctgcgtgctgggcgagccctat
c-------at-ggcaaacgtttgggcttc----------ggtctgagctagtag----ct
ttatttttaaacccatt-tcttaatactgat-tatactgtggggacgaaagtctctgctt
ttaactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacgct
gcgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaacgc
atattgcacttccgggttagtcctgggagtatgcctgtatcagtgtccgtacatcaaact
tggctttcttccttccgtgtagtcggtgga-ggagacgc-cag-atgtgaagtgtcttgc
gg-ct----ggctttcgggcc--gact--gcgagtcctttgaaatgtactgaactgtact
-tctctttgctcgaaaagt-gt--ggcgttgctggttgtggaggctgcc-cgcgtggcca
gtc-ggcgaccggtttgtctgctgcggcgttttactggaggagtgttcgattcgcggtat
ggttggcttcggctgaacag-gcgcttattggac-gtttttcc-tgctg-tggcg---tg
atgggctggtgaaccgtagctgtgtgtggcttggcttttgaatcggttttgc-tattgcg
aagtagagtggcgg----------cttcggc------------tgtcgaggggtcgatcc
attttgggaaactt-tgtgtgtactt------------
>Phytophthora_sp__4_DDS3438_EU301128 Phytophthora_sp._4_DDS3438_EU301128 909 bp 
ccacacct--aaaaaactttccacgtgaaccgtatcaaccctttcagttgggggccttgc
tt-------------------------------------------ttttgcgagccctat
c-------at-ggcgaatgtttggacttc----------ggtctgggctagtag--c-tt
tttgttttaaacccatt-ctacaatactgat-tatactgtggggacgaaagtctctgctt
ttaactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacgct
gcgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaacgc
atattgcacttccgggttagtcctgggagtatgcctgtatcagtgtccgtacatcaaact
tggctttcttccttccgtgtagtcggtgga-ggatgtgc-cag-atgtgaagtgtcttgc
ag-gt----gtccttcgggtc--gtct--gcgagtcctttgaaatgtactgaactgtact
-tctctttgctcgaaaagc-gt--ggcgttgctggttgtggaggctgcc-tgcgtggcca
gtc-ggcgaccggtttgtctgctgcggcg-tttaatggaggagtgttcgattcgcggtat
ggttggcttcggctgaacag-gcgcttattgtat-gcttttcc-tgctg-tggcg---tg
atggactggtgaaccgtagctgtgtgtggcttggcttttgaatcggctttgc-tgttgcg
aagtagagtggcgg----------cttcggc------------tgtcga-gggtcgatcc
atttgggaactt---tgtgtgcacct------------
>Phytophthora_sp__4_HSA1210_EU301130 Phytophthora_sp._4_HSA1210_EU301130 909 bp 
ccacacct--aaaaaactttccacgtgaaccgtatcaaccctttcagttgggggccttgc
tt-------------------------------------------ttttgcgagccctat
c-------at-ggcgaatgtttggacttc----------ggtctgggctagtag--c-tt
tttgttttaaacccatt-ctacaatactgat-tatactgtggggacgaaagtctctgctt
ttaactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacgct
gcgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaacgc
atattgcacttccgggttagtcctgggagtatgcctgtatcagtgtccgtacatcaaact
tggctttcttccttccgtgtagtcggtgga-ggatgtgc-cag-atgtgaagtgtcttgc
ag-gt----gtccttcgggtc--gtct--gcgagtcctttgaaatgtactgaactgtact
-tctctttgctcgaaaagc-gt--ggcgttgctggttgtggaggctgcc-tgcgtggcca
gtc-ggcgaccggtttgtctgctgcggcg-tttaatggaggagtgttcgattcgcggtat
ggttggcttcggctgaacag-gcgcttattgtat-gcttttcc-tgctg-tggcg---tg
atggactggtgaaccgtagctgtgtgtggcttggcttttgaatcggctttgc-tgttgcg
aagtagagtggcgg----------cttcggc------------tgtcga-gggtcgatcc
atttgggaactt---tgtgtgcacct------------
>Phytophthora_sp__4_IMI133316_EU301126 Phytophthora_sp._4_IMI133316_EU301126 909 bp 
ccacacct--aaaaaactttccacgtgaaccgtatcaaccctttcagttgggggccttgc
tt-------------------------------------------ttttgcgagccctat
c-------at-ggcgaatgtttggacttc----------ggtctgggctagtag--c-tt
tttgttttaaacccatt-ctacaatactgat-tatactgtggggacgaaagtctctgctt
ttaactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacgct
gcgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaacgc
atattgcacttccgggttagtcctgggagtatgcctgtatcagtgtccgtacatcaaact
tggctttcttccttccgtgtagtcggtgga-ggatgtgc-cag-atgtgaagtgtcttgc
ag-gt----gtccttcgggtc--gtct--gcgagtcctttgaaatgtactgaactgtact
-tctctttgctcgaaaagc-gt--ggcgttgctggttgtggaggctgcc-tgcgtggcca
gtc-ggcgaccggtttgtctgctgcggcg-tttaatggaggagtgttcgattcgcggtat
ggttggcttcggctgaacag-gcgcttattgtat-gcttttcc-tgctg-tggcg---tg
atggactggtgaaccgtagctgtgtgtggcttggcttttgaatcggctttgc-tgttgcg
aagtagagtggcgg----------ctccggc------------tgtcga-gggtcgatcc
atttgggaactt---tgtgtgcacct------------
>Phytophthora_sp__4_IMI329674_EU301127 Phytophthora_sp._4_IMI329674_EU301127 909 bp 
ccacacct--aaaaaactttccacgtgaaccgtatcaaccctttcagttgggggccttgc
tt-------------------------------------------ttttgcgagccctat
c-------at-ggcgaatgtttggacttc----------ggtctgggctagtag--c-tt
tttgttttaaacccatt-ctacaatactgat-tatactgtggggacgaaagtctctgctt
ttaactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacgct
gcgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaacgc
atattgcacttccgggttagtcctgggagtatgcctgtatcagtgtccgtacatcaaact
tggctttcttccttccgtgtagtcggtgga-ggatgtgc-cag-atgtgaagtgtcttgc
ag-gt----gtccttcgggtc--gtct--gcgagtcctttgaaatgtactgaactgtact
-tctctttgctcgaaaagc-gt--ggcgttgctggttgtggaggctgcc-tgcgtggcca
gtc-ggcgaccggtttgtctgctgcggcg-tttaatggaggagtgttcgattcgcggtat
ggttggcttcggctgaacag-gcgcttattgtat-gcttttcc-tgctg-tggcg---tg
atggactggtgaaccgtagctgtgtgtggcttggcttttgaatcggctttgc-tgttgcg
aagtagagtggcgg----------ctccggc------------tgtcga-gggtcgatcc
atttgggaactt---tgtgtgcacct------------
>Phytophthora_sp__4_MJS278_EU301131 Phytophthora_sp._4_MJS278_EU301131 909 bp 
ccacacct--aaaaaactttccacgtgaaccgtatcaaccctttcagttgggggccttgc
tt-------------------------------------------ttttgcgagccctat
c-------at-ggcgaatgtttggacttc----------ggtctgggctagtag--c-tt
tttgttttaaacccatt-ctacaatactgat-tatactgtggggacgaaagtctctgctt
ttaactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacgct
gcgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaacgc
atattgcacttccgggttagtcctgggagtatgcctgtatcagtgtccgtacatcaaact
tggctttcttccttccgtgtagtcggtgga-ggatgtgc-cag-atgtgaagtgtcttgc
ag-gt----gtccttcgggtc--gtct--gcgagtcctttgaaatgtactgaactgtact
-tctctttgctcgaaaagc-gt--ggcgttgctggttgtggaggctgcc-tgcgtggcca
gtc-ggcgaccggtttgtctgctgcggcg-tttaatggaggagtgttcgattcgcggtat
ggttggcttcggctgaacag-gcgcttattgtat-gcttttcc-tgctg-tggcg---tg
atggactggtgaaccgtagctgtgtgtggcttggcttttgaatcggctttgc-tgttgcg
aagtagagtggcgg----------ctccggc------------tgtcga-gggtcgatcc
atttgggaactt---tgtgtgcacct------------
>Phytophthora_sp__9_MJS186_EU301148 Phytophthora_sp._9_MJS186_EU301148 909 bp 
ccacacct-taaaaaaccatccacgtgaaccgtattgtcaa-aacatttgggga--ctcc
ttgctagcgggctttcgggcttgc------------------cggtcggttgagacctaa
c-----------acgagagccttggctga--------aaagccggggtgagtag------
tttcttttaaacccttt-actaaaaactgaa--aaactgtggggacgaaagtccttgctt
tt-actagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacgct
gcgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaacgc
atattgcacttccgggttatgcctggaagtatgcctgtatcagtgtccgtatatcaaact
tgccttccttccttccgtgtagtcggtggatgggaacgtgcag-atgtgaagtgtcttgg
cg-gcgt--cgctttggcggt--gctg--gcgagtccttttaaatacaagatactgttct
-tctctttgctcgaaaagc-gt--gtgggatgtggttgtggaggctgcc-tgcgtggcat
gtc-ggcgactgattt-cgtgctgaggcg-----ttggaggtgggcttgattcgcggtat
ggttggcttcggctgaactt-ctgcttattgggt-tctaatct-tgctt-tggcg-tatg
cggggtcggtgtaccgtagtcgtgtg-ggcttggcttttgaaccgtgtttt--gcgtgcg
aagtagagtggccg----------tgtggttttcggactgcgtggccgagggaacgagac
cttttgggaaattgtgctgc-tacttttgtggcggcat
>Phytophthora_sp__9_TCH003_EU301149 Phytophthora_sp._9_TCH003_EU301149 909 bp 
ccacacct-taaaaaaccatccacgtgaaccgtattgtcaa-aacatttgggga--ctcc
ttgctagcgggctttcgggcttgc------------------cggtcggttgagacctaa
c-----------acgagagccttggctga--------aaagccggggtgagtag------
tttcttttaaacccttt-actaaaaactgaa--aaactgtggggacgaaagtccttgctt
tt-actagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacgct
gcgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaacgc
atattgcacttccgggttatgcctggaagtatgcctgtatcagtgtccgtatatcaaact
tgccttccttccttccgtgtagtcggtggatgggaacgtgcag-atgtgaagtgtcttgg
cg-gcgt--cgctttggcggt--gctg--gcgagtccttttaaatacaagatactgttct
-tctctttgctcgaaaagc-gt--gtgggatgtggttgtggaggctgcc-tgcgtggcat
gtc-ggcgactgattt-cgtgctgaggcg-----ttggaggtgggcttgattcgcggtat
ggttggcttcggctgaactt-ctgcttattgggt-tctaatct-tgctt-tggcg-tatg
cggggtcggtgtaccgtagtcgtgtg-ggcttggcttttgaaccgtgtttt--gcgtgcg
aagtagagtggccg----------tgtggttttcggactgcgtggccgagggaacgagac
cttttgggaaattgtgctgc-tacttttgtggcggcat
>Phytophthora_sp__9_VHS16234_EU301150 Phytophthora_sp._9_VHS16234_EU301150 909 bp 
ccacacct-taaaaaaccatccacgtgaaccgtattgtcaa-aacatttgggga--ctcc
ttgctagcgggctttcgggcttgc------------------cggtcggttgagacctaa
c-----------acgagagccttggctga--------aaagccggggtgagtag-----t
ttctttttaaacccttt-actaaaaactgaa--aaactgtggggacgaaagtccttgctt
tt-actagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacgct
gcgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaacgc
atattgcacttccgggttatgcctggaagtatgcctgtatcagtgtccgtatatcaaact
tgccttccttccttccgtgtagtcggtggatgggaacgtgcag-atgtgaagtgtcttgg
cg-gcgt--cgctttggcggt--gctg--gcgagtccttttaaatacaagatactgttct
-tctctttgctcgaaaagc-gt--gtgggatgtggttgtggaggctgcc-tgcgtggcat
gtc-ggcgactgattt-cgtgctgaggcg-----ttggaggtgggcttgattcgcggtat
ggttggcttcggctgaactt-ctgcttattgggt-tctaatct-tgctt-tggcg-tatg
cggggtcggtgtaccgtagtcgtgtg-ggcttggcttttgaaccgtgtttt--gcgtgcg
aagtagagtggccg----------tgtggttttcggactgcgtggccgagggaacgagac
cttttgggaaattgtgctgc-tacttttgtggcggcat
>Phytophthora_tropicalis_H213_AY207010 Phytophthora_tropicalis_H213_AY207010 909 bp 
ccacacct--aaaaaactttccacgtgaaccgtatcgacccttttagttgggggtcttgt
-----------------------------------------------------accctat
c-------at-ggcgaatgtttggacttc----------ggtctgggcgagtag--c-tt
tttgttttaaacccatt-tctcaatactgat-tatactgcggggacgaaagtctctgctt
ttaactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacgct
gcgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaacgc
atattgcacttccgggttagtcctgggagtatgcctgtatcagtgtccgtacatcaaact
tggctttcttccttccgtgtagtcggtgga-ggatgtgc-cag-atgtgaagtgtcttgc
ggttt----gtccttcgggtc--ggct--gcgagtccttttaaatgtactgaactgtact
-tctctttgctcgaaaagc-gt--ggtgttgctggttgtggaggctgcc-tgcgtggcca
gtc-ggcgaccggtttgtctgctgcggcg-tttaatggaggagtgttcgattcgcggtat
ggttggcttcggctgaacag-gcgcttattgtat-gcttttcc-tgctg-tggcg---tg
atgggctggtgaaccgtagctgtgtgtggcttggcttttgaatcggctttgc-tgttgcg
aagtagagtggcgg----------cttcggc------------tgtcga-gggtcgatcc
attttgggaactt--tgtgtgcactt------------
>Phytophthora_tropicalis_P4742_AY946257 Phytophthora_tropicalis_P4742_AY946257 909 bp 
ccacacct--aaaaaactttccacgtgaaccgtatcgacccttttagttgggggtcttgt
-----------------------------------------------------accctat
c-------at-ggcgaatgtttggacttc----------ggtctgggcgagtag--c-tt
tttgttttaaacccatt-tctcaatactgat-tatactgcggggacgaaagtctctgctt
ttaactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacgct
gcgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaacgc
atattgcacttccgggttagtcctgggagtatgcctgtatcagtgtccgtacatcaaact
tggctttcttccttccgtgtagtcggtgga-ggatgtgc-cag-atgtgaagtgtcttgc
ggttt----gtccttcgggtc--ggct--gcgagtccttttaaatgtactgaactgtact
-tctctttgctcgaaaagc-gt--ggtgttgctggttgtggaggctgcc-tgcgtggcca
gtc-ggcgaccggtttgtctgctgcggcg-tttaatggaggagtgttcgattcgcggtat
ggttggcttcggctgaacag-gcgcttattgtat-gcttttcc-tgctg-tggcg---tg
atgggctggtgaaccgtagctgtgtgtggcttggcttttgaatcggctttgc-tgttgcg
aagtagagtggcgg----------cttcggc------------tgtcga-gggtcgatcc
attttgggaactt--tgtgtgcactt------------
>END; 1 bp 
n-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------
