>Phytophthora_arecae 900 bp 
ccacacct--aaaaactttccacgtgaaccgtatcaaaactt---agttgggggtctctt
tcg---gcggcggctgctggcttcattgctggcg----gctgc-tgttgggagagctcta
tc------a-tggcgagcgtt-tgggcttc----------ggtct-gaactagtag--ct
t-----ttttaaacccattc-tttataactgattatactgtagggacgaaagtctctgct
tttaactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacgc
tgcgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaacg
catattgcacttccgggttagtcctgggagtatgcctgtatcagtgtccgtacatcaaac
ttggttttcttccttccgtgtagtcggtggt-ggatgtgc-cagatgtgaagtgtcttgc
g-gctgg----tcttc--ggatc--ggctgtgagtcctttgaaatgtactgaactgtact
-tctctttgctccaaaagc-gtggcgttgctgattgtggaggctgcttgcgtagccagtc
tggcgaccagtttgtctgctgtggcg--ttaatggaggagtgttcgattcgcggtatggt
tggcttcggctgaacag-acgcttattgaatatt-tcttcagctg-tggtggtat-gatt
ggtgaaccgtagctatgtg-agcttggcttttgaattggctttgct-gttgcgaagtaga
gtggcggct--------------t----cggctgtcga-gggtcgatcc-atttgggaac
t--tgtgta-t-------------------gcttcggc----atgcatctcaa
>Phytophthora_cactorum 900 bp 
ccacacct--aaaaactttccacgtgaaccgtttcaaaccaaat-agttgggggtcttgt
ctg---gtggcggctgctggctttattgttggcg----gctgc-tgctgggtgagcccta
tc------a-tggcgagcgtt-tgggcttc----------ggcct-gagctagtag--ct
tttc--ttttaaacccattc-cttaatactgattatactgtggggacgaaagtccttgct
tttaactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacgc
tgcgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaacg
catattgcacttccgggttagtcctgggagtatgcctgtatcagtgtccgtacatcaaac
ttggctttcttccttccgtgtagtcggtgga-ggagatgc-cagatgtgaagtgtcttgc
g-gctgg----ttttc--ggacc--gactgcgagtccttttaaatgtactgaactgtact
-tctctttgctcgaaaagc-gtggcgttgctggttgtggaggctgctattgtagcaagtt
-ggcgaccggtttgtctgctgcggcg--ttaatggaagagtgttcgattcgcggtatggt
tagcttcggctgaacaatgcgcttattggatgtt-ttttctgctg-tggcgtgatggacc
ggtgaaccatagctcagt--tgcttggcttttgaatcggctttgct-gttgcgaagtaga
gtggcggct--------------t----cggctgtcga-gggtcgatcc-atttgggaaa
t-gtgtgtg-t-------------------acttcggt----atgcatctcaa
>Phytophthora_capsici 900 bp 
ccacacct-aaaaaactttccacgtgaaccgtatcaaccctttt-agttgggggtcttgt
------------------------------------------------------acccta
tc------a-tggcgaatgtt-tggacttc----------ggtcc-gggcgagtag--ct
ttttg-ttttaaacccattt-cacaattctgattatactgtggggacgaaagtctctgct
tttaactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacgc
tgcgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaacg
catattgcacttccgggttagtcctgggagtatgcctgtatcagtgtccgtacatcaaac
ttggctttcttccttccgtgtagtcggtgga-ggatgtgc-cagatgtgaagtgtcttgc
gtgttgt----ccttc--gggtc--gactgcgagtccttttaaatgtactgaactgtact
-tctctttgctcgaaaagc-gtggtgttgctggttgtggaggctgcctgcgtggccagtc
-ggcgaccggtttgtctgctgcggcg-tttaaaggaggagtgttcgattcgcggtatggt
tggcttcggctgaacag-gcgcttattgaatgct-tttcctgctg-tggcgtgatgggct
ggtgaaccgtagctgtgtttggcttggcttttgaatcggctttgct-gttgcgaagtagg
gtggcggct--------------t----cggctgtcga-gggtcgatcc-attttgggaa
ctttgtgtg-c-------------------acttcggt----gcgcatctcaa
>Phytophthora_cinnamomi 900 bp 
ccacacct-aaaaaactttccacgtgaaccgtttcaacccaatt-agttgggggcctgct
ctgg--gcggcggttgtcgatgtcaaagtcgacggtt-gctgt-tgcgtggggggcccta
tc------actggcgagcgtt-tgggtccccctc--gggggaact-gagctagtag--cc
tctc--ttttaaacccatcc-tgtaatactgaacatactgtggggacgaaagtctctgct
tttaactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacgc
tgcgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaatttggaacg
catattgcacttccgggttagtcctgggagtatgcctgtatcagtgtccgtacatcaaac
ttggctctcttccttccgtgtagtcggtggatggaggtgc-cagacgtgaggtgtcttgc
g-ggcgg----tcttc--ggact--ggctgtgagtcccttgaaatgtactgaactgtact
-tctctttgctcgaaaagc-gtgacgttgctggttgtggaggctgcctgtatggccagtc
-ggcgaccggtttgtctgctgcggcg-tttaatggaggagtgtccgattcgcggtatggt
tggctccggctgaacaaagcgcttattggatgttcctccctgctg-tggcggtacggatc
ggtgaaccgtagctgtgctaggcttggcgtttgaaccggcggtgtt-gttgcgaagtagg
gtggcggct--------------t----cggctgtcga-gggtcgatcc-atttgggaac
t-ctgtgtc-tctccggcgcactt--gtgtgcttgtgg----tggcatctcaa
>Phytophthora_citricola 900 bp 
ccacacct-aaaaaacttttcacgtgaaccgtatcaaccctttt-agttgggggtcttgc
--------------------------------------------ttttttgcgagcccta
tc------a-tggcgaatgtt-tggacttc----------ggtct-gggctagtag--ct
ttttg-ttttaaacccattc-tacaatactgattatactgtggggacgaaagtctctgct
tttaactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacgc
tgcgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaacg
catattgcacttccgggttagtcctgggagtatgcctgtatcagtgtccgtacatcaaac
ttggctttcttccttccgtgtagtcggtgga-ggatgtgc-cagatgtgaagtgtcttgc
g-ggtgt----ccttc--gggtc--gtctgcgagtcctttgaaatgtactgaactgtact
-tctctttgctcgaaaagc-gtggtgttgctggttgtggaggctgcctgcgtggccagtc
-ggcgaccggtttgtctgctgcagcg-tttaatggaggagtgttcgattcgcggtatggt
tggcttcggctgaacag-gcgcttattgtatgct-tttcctgctg-tggcgtgatgggct
ggtgaaccgtagctatgtgtggcttggcttttgaatcggctttgct-gttgcgaagtaga
gtggcggct--------------t----cggctgtcga-gggtcgatcc-atttgggaac
t-ttgtgtg-c-------------------acctcggt----gcgcatctcaa
>Phytophthora_colocasiae 900 bp 
ccacacct-aaaaaactttccacgtgaaccgtatcaaccctttt-agttgggggtgttgc
ttg-----------------------------------gcatt-ttgctgaggcgcccta
tc------a-tggcgaatgtt-tggacttc----------ggtct-gggctagtag--ct
tttt--gttttaaacccttt-aacaatactgattatactgtggggacgaaagtctctgct
tttaactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacgc
tgcgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaacg
catattgcacttccgggttagtcctgggagtatgcctgtatcagtgtccgtacatcaaac
ttggctttcttccttccgtgtagtcggtgga-ggatgtgc-cagatgtgaagtgtcttgc
g-gtttgtgtgccttc--gggccgaggctgcgagtcctttgaaatgtactgaactgtact
-tctctttgctcgaaaagc-gtggtgatgctggttgtggaggctgcctgcgtggccagtc
-ggcgaccggtttgtctgctgcggcg-tttaatggaggagtgttcgattcgcggtatggt
tggcttcggctgaacag-acgcttattgtatgct-tttcctgctg-tggcgtgatgggct
ggtgaaccgtagctgtgtgtggcttggcttttgaatcggctttgct-gttgcgaagtaga
gtggcggct--------------t----cggctgtcga-gtgtcgatcc-attttgggaa
c-ttttgtg-t---------------gcgctttcgagt----gtgcatctcaa
>Phytophthora_cryptogea 900 bp 
ccacacct-aaaaaactttccacgtgaaccgtatcaacctttttaatttgggggcttccg
tctgg-ccggccggttttcg------------------gctgg-ctgggtggcggctcta
tc------a-tggcgaccgct-tgggcctc----------ggcct-gggctagtag--cg
tat---ttttaaacccattc-ctaattactgaatatactgtggggacgaaagtctctgct
tttaactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacgc
tgcgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaacg
catattgcacttccgggttagtcctgggagtatgcctgtatcagtgtccgtacactaaac
ttggctcccttccttccgtgtagtcggtggatggggacgcgcagatgtgaagtgtcttgc
g-gctgg----tcttc--ggtcc--ggctgcgagtcctttgaaatgtactacactgtact
-tctctttgctcgaaaagc-gtgacgttgctggttgtggaggctgcctgtgtggcatgtc
-ggcgaccggtttgtctgctgcggcg-tttaatggaggagtgttcgattcgcggtatggt
tggcttcggctgaacag-acgcttattgggtgct-tttcctgctg-tggctggatggact
ggtgaaccgtagctgtgctaggcttggcgtttgaaccggcggtgtg--gtgcgaagtagg
gtgtctgtt---ctggcgtaagctg---gggtggacga-gggtcgatcc-atttgggaaa
cgttgtgtg-c-------------------gcttcggc----gcgcatctcaa
>Phytophthora_drechsleri 900 bp 
ccacacct-aaaaaac-ttccacgtgaaccgtatcaacctttttaaattgggggcttccg
tctgg-ccggccggttctcg------------------gctgg-ctgggtggcggctcta
tc------a-tggcgaccgcc-tgggcctc----------ggcct-gggttagtag--cg
tat---tttttaaaccattc-ctaattactgaaaaaactgtggggacgaaagtctctgct
tttaactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacgc
tgcgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaacg
catattgcacttccgggttagtcctgggagtatgcctgtatcagtgtccgtacactaaac
ttggctcccttccttccgtgtagtcggtggatggggacgcgcagatgtgaagtgtcttgc
g-gctgg----tcttc--ggtcc--ggctgcgagtccttttaaatgtactacactgtact
-tctctttgctcgaaaagc-gtgacgttgctggttgtggaggctgcctgtgtggcatgtc
-ggcgaccggtttgtctgctgcggcgttttaatggaggagtgttcgattcgcggtatggt
tggcttcggctgaacag-acgcttattgggtgct-ttttctgctg-cggcgggatggact
ggtgaaccgtagctgtgctaggcttggcgtttgaaccggcggtatt--gtgcgaagtagg
gtgtctgtc---tcggcgcaagctg---gggtgggcga-gggtcgatcc-atttgggaaa
cgttgtgtg-c-------------------gcttcggc----gtgcatctcaa
>Phytophthora_erythroseptica 900 bp 
ccacacct-aaaaaactttccacgtgaaccgtatcaacctttttaaattgggggcttccg
tctgg-ccggccggttttcg------------------gctgg-ctgggtggcggctcta
tc------a-tggcgaccgct-tgggcctc----------ggcct-gggctagtag--cg
tat---ttttaaa-ccattc-ctaattactgaatatactgtggggacgaaagtctctgct
tttaactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacgc
tgcgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaacg
catattgcacttccgggttagtcctgggagtatgcctgtatcagtgtccgtacactaaac
ttggctcccttccttccgtgtagtcggtggatggggacgcgcagatgtgaagtgtcttgc
g-gctgg----tcttc--ggtcc--ggctgcgagtcctttgaaatgtactacactgtact
-tctctttgctcgaaaagc-gtgacgttgctggttgtggaggctgcctgtgtggcatgtc
-ggcgaccggtttgtctgctgcggcg-tttaatggaggagtgttcgattcgcggtatggt
tggcttcggctgaacag-acgcttattgggtgct-tttcctgctg-tggctggatggact
ggtgaaccgtagctgtgctaggcttggcgtttgaaccggcggtgtg--gtgcgaagtagg
gtgtctgtt---ccggcgtaagctg---gggtggacga-gggtcgatcc-atttgggaaa
cgttgtgtg-c-------------------gcttcggc----gcgcatctcaa
>Phytophthora_fragariae 900 bp 
ccacacct-aaaaaactttccacgtgaaccgtatcaacccactt-agttgggggcctgtc
ctgg--cggctggctgtcgatgtcaaagttgacggct-gctgc-tgtgtgtcgggcccta
tc------a-tggcgagcgtt-tgggtccctctc--gggggaact-gagccagtag--cc
cttttcttttaaacccattc-ttgaatactgaatatactgtggggacgaaagtctctgct
tttaactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacgc
tgcgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaacg
catattgcacttccgggttagtcctgggagtatgcctgtatcagtgtccgtacatcaaac
ttggctctcttccttccgtgtagtcggtggatggggacgc-cagacgtgaggtgtcttgc
g-ggtgg----ccttc--gggct--gcctgcgagtcccttgaaatgtactgaactgtact
-tctctttgctcgaaaagc-gtgacgttgttggttgtggaggctgcctgtgtggccagtc
-ggcgaccggtttgtctgctgcggcg-tttaatggaggagtgttcgattcgcggtatggt
tggcttcggctgaacaatgcgcttattggacgtt-cttcctgctg-tggcggtacggatc
ggtgaaccgtagctgtgcgaggcttggcctttgaaccggcggtgttggtcgcgaagtagg
gtggcggct--------------t----cggctgtcgaggggtcgatcc-atttgggaac
t--tgtgtc-tctgcggcgcgcttcggtgtgctgcggg----tggcatctcaa
>Phytophthora_fragariae_rubi 900 bp 
ccacacct-aaaaaactttccacgtgaaccgtatcaacccactt-agttgggggcctgtc
ctgg--cggctggctgtcgatgtcaaagttgacggct-gctgc-tgtgtgtcgggcccta
tc------a-tggcgagcgtt-tgggtccctctc--gggggaact-gagccagtag--cc
cttttcttttaaacccattc-ttgaatactgaatatactgtggggacgaaagtctctgct
tttaactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacgc
tgcgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaacg
catattgcacttccgggttagtcctgggagtatgcctgtatcagtgtccgtacatcaaac
ttggctctcttccttccgtgtagtcggtggatggggacgc-cagacgtgaggtgtcttgc
g-ggtgg----ccttc--gggct--gcctgcgagtcccttgaaatgtactgaactgtact
-tctctttgctcgaaaagc-gtgacgttgttggttgtggaggctgcctgtgtggccagtc
-ggcgaccggtttgtctgctgcggcg-tttaatggaggagtgttcgattcgcggtatggt
tggcttcggctgaacaatgcgcttattggacgtt-cttcctgctg-tggcggtacggatc
ggtgaaccgtagctgtgcgaggcttggcctttgaaccggcggtgttggtcgcgaagtagg
gtggcggct--------------t----cggctgtcgaggggtcgatcc-atttgggaac
t--tgtgtcttctgcggcgcgcttcggtgtgctgcggg----tggcatctcaa
>Phytophthora_gonapodyides 900 bp 
ccacacct-aaaaaac-ttccacgtgaaccgtatcaacccctta-aatttgggggcttgc
tcggc-ggcgtgcgtgctggcctgtaatgggtcggcgtgctgc-tgctgggcaggctcta
tc------atgggcgagcgtt-tgggcttc----------ggctc-gaactagtag--ct
atca-attttaaaccctttctttaaatactgaacatactgtggggacgaaagtctctgct
tttaactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacgc
tgcgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaacg
catattgcacttccgggttagtcctgggagtatgcctgtatcagtgtccgtacatcaacc
ttggttttcttccttccgtgtagtcggtgga-ggatatgc-cagacgtgaagtgtcttgc
t-ggcgg----tctttcgagtct--gccggtgagtcctttgaaatgtactgaactgtact
ctctctttgctcgaaaagc-gtggcgttgctggttgtggagcctgcccgtgtggccagtc
-ggcgaccggtttgttagctgtggcg-tttaatggaggagtgttcgattcgcggtatggt
tggcttcggctgaacaatctgcttattgggtgct-tttcctgtcattggcggtacgaact
ggtgaaccgtagctgtgtggtgcttggcttttgaaccggctttgct--ttgcgaagtagg
gtggcggct--------------t----cggctgtcgaggggtcgatcc-attttgggaa
a-ctttgtg-tg--------------tgcggcttcgtgctgcgcgcatctcaa
>Phytophthora_heveae 900 bp 
ccacacct-aaaaaa-tttccacgtgaaccgtaacaaaccaat--agttggggg------
--------------------cgagtttggcggct----actgc-tgctggacgagctcta
tc------a-tggcgagcgtt-tggacttc----------ggtct-gaactagtag--cc
cttc--ttttaaacccattc-ctaattactgattatactgtggggacgaaagtctctgct
tttaactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacgc
tgcgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaacg
catattgcacttccgggttagtcctgggagtatgcctgtatcagtgtccgtacaacaaac
ttggctttcttccttccgtgtagtcggtgga-ggagatgc-cagatgtgaagtgtcttgc
g-gctgg----ttctc--gaact--ggctgcgagtcctttgaaatgtactgaactgtact
-tctctttgctcgaaaagc-atggcgttgctggttgtggaggctgcctgtgtggcatgtc
-ggcgaccggtctgtctgctgcagcg--ttaatggaggcgtgttcgattcgcggtatggt
tggcttcggctgaacaatgcgcttattgtatgtg-tttcctgttg-tggcggtaatggct
ggtgtaccgtagctatgtggtgcttggcttttgaatcggctttgct-gttgtgaagtaga
gtggcggct--------------t----cggctgtcga-gggtcgatcc-atttgggaaa
t-ttgtgtg-t---------------gcctttattggc----gtgcatctcaa
>Phytophthora_hibernalis_Australia Phytophthora_hibernalis_Australia 900 bp 
ccacacct-aaaaaactttccacgtgaaccgtatcaaccctttt-agttgggggcttctg
ttcgg-ctggc-----tttt------------------gctgg-ctgggcggcggctcta
tc------a-tggcgagcgcc-tgggcctt--------cgggtct-gagctagtag--tc
ttc---ttttaaaccctttc-ttaaatactgaatatactgtggggacgaaagtctctgct
tttaactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacgc
tgcgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaacg
catattgcacttccgggttagtcctgggagtatgcctgtatcagtgtccgtacatcaaac
ttgcctcccttccttccgtgtagtcggtggatggggacgtgcagacgtgaagtgtcttgc
g-attgg----tcttc--gggcc--ggctgcgagtccttttaaatgtacagaacggtact
-tctctttgctcgaaaagc-ataatggaattggttgtggaagcttcccg-gtggcaagtc
-ggcgactggtttgtctgctacggcg-tttaatggaggaatgttcgattcgcggtatggt
tagcttcggctgaacaatgcgcttattggatgtt-tttcctgctg-tggtggtaatgact
ggtgaaccgtagctatgcagggattggcctttgaactgaggatgtt--gtgtgaagtaga
gtggcggtt----tggcgcaagct----gggctgtcga-gggtcgatcctatttgggaaa
t-ttgtgtt-----------------ggcggcttcggctgt-tggcatctcaa
>Phytophthora_hibernalis_New_Zealand Phytophthora_hibernalis_New_Zealand 900 bp 
ccacacct-aaaaaactttccacgtgaaccgtatcaaccctttt-agttgggggcttctg
ttcgg-ctggc-----tttt------------------gctgg-ctgggcggcggctcta
tc------a-tggcgagcgcc-tgggcctt--------cgggtct-gagctagtag--tc
ttc---ttttaaaccctttc-ttaaatactgaatatactgtggggacgaaagtctctgct
tttaactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacgc
tgcgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaacg
catattgcacttccgggttagtcctgggagtatgcctgtatcagtgtccgtacatcaaac
ttgcctcccttccttccgtgtagtcggtggatggggacgtgcagacgtgaagtgtcttgc
g-attgg----tcttc--gggcc--ggctgcgagtccttttaaatgtacagaacggtact
-tctctttgctcgaaaagc-ataatggaattggttgtggaagcttcccg-gtggcaagtc
-ggcgactggtttgtctgctacggcg-tttaatggaggaatgttcgattcgcggtatggt
tagcttcggctgaacaatgcgcttattggatgtt-tttcctgctg-tggtggtaatgact
ggtgaaccgtagctatgcagggattggcccttgaactgaggatgtt--gtgtgaagtaga
gtggcggtt----tggcgcaagct----gggctgtcga-gggtcgatcctatttgggaaa
t-ttgtgtt-----------------ggcggcttcggctgt-tggcatctcaa
>Phytophthora_hibernalis_Portugal Phytophthora_hibernalis_Portugal 900 bp 
ccacacct-aaaaaactttccacgtgaaccgtatcaaccctttt-agttgggggcttctg
ttcgg-ctggc-----tttt------------------gctgg-ctgggcggcggctcta
tc------a-tggcgagcgcc-tgggcctt--------cgggtct-gagctagtag--tc
ttc---ttttaaaccctttc-ttaaatactgaatatactgtggggacgaaagtctctgct
tttaactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacgc
tgcgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaacg
catattgcacttccgggttagtcctgggagtatgcctgtatcagtgtccgtacatcaaac
ttgcctcccttccttccgtgtagtcggtggatggggacgtgcagacgtgaagtgtcttgc
g-attgg----tcttc--gggcc--ggctgcgagtccttttaaatgtacagaacggtact
-tctctttgctcgaaaagc-ataatggaattggttgtggaagcttcccg-gtggcaagtc
-ggcgactggtttgtctgctacggcg-tttaatggaggaatgttcgattcgcggtatggt
tagcttcggctgaacaatgcgcttattggatgtt-tttcctgctg-tggtggtaatgact
ggtgaaccgtagctatgcagggattggcctttgaactgaggatgtt--gtgtgaagtaga
gtggcggtt----tggcgcaagct----gggctgtcga-gggtcgatcctatttgggaaa
t-ttgtgtt-----------------ggcggcttcggctgt-tggcatctcaa
>Phytophthora_ilicis 900 bp 
ccacacct-aaaaa--cttccacgtgaactgtatcgaa-caact-agttgggggtcttgt
ttgg--cgtgcggctgct----------tcggta----gctgc-tgctaggcgagcccta
tc------a-cggcgagcgtt-tggacttc----------ggtct-gagctagtag--ct
att---ttttaaacccattc-tttaatactgattatactgtggggacgaaagtctctgct
tttaactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacgc
tgcgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaacg
catattgcacttccgggttagtcctgggagtatgcctgtatcagtgtccgtacatcaaac
ttggctttcttccttccgtgtagtcggtgga-ggagacgc-cagacgtgaagtgtcttgc
g-gcgaa----ttttc--gaatt--tgctgtgagtcctttgaaatgtactgaactgtact
-tctctttgctcgaaaagc-gtggcgttgctggttgtggagcctgcccgcgtggccagtc
-ggcgaccggtttgtctgctgtggcg--ttaatggaggagtgttcgattcgcggtatggt
tagcttcggctgaacaa-gcgcttattggatgtt-cttcttgctg-tggcgtgatggact
ggtgaaccgtagctatgtgtggcttggcttttgaatcggctttgct-gttgcgaagtaga
gtggcggct--------------t----cggctgtcga-gggtcgatcc-atttgggaaa
t-ttgtgtg-t----------------atgacttcggttgt-aagcatctcaa
>Phytophthora_infestans 900 bp 
ccacacct--aaaaactttccacgtgaaccgtttc-aacccaat-agttgggggtcttac
ttg---gcggcggctgctggctttattgctggcg----gctac-tgctgggcgagcccta
tc----aaa-aggcgagcgtt-tggacttc----------ggtct-gagctagtag--ct
tttttattttaaacccttta-cttaatactgattatactgtggggacgaaagtctctgct
tttaactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacgc
tgcgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaacg
catattgcacttccgggttagtcctggaagtatgcctgtatcagtgtccgtacaacaaac
ttggctttctcccttccgtgtagtcggtgga-ggagatgc-cagatgtgaagtgtcttgc
g-gttgg----tttcc--ggacc--gactgcgagtcctttgaaatgtactaaactgtact
-tctctttgctccaaaagtggtggcattgctggttgtggacgctgctattgtagcgagtt
-ggcgaccggtttgtctgctgcggcg--ttaatggagaaatgctcgattcgtggtatggt
tgccttcggctgaacaatgcgcttattgggtgat-tttcctgctg-tggcgtgatggact
ggtgaaccatggctcttt--agcttggcatttgaatcggctttgct-gttgcgaagtaga
gtggcggct--------------t----cggctgccga-gggtcgatcc-atttgggaaa
t-gt-tgtg-t-------------------acttcggt----atgcatctcaa
>Phytophthora_lateralis 900 bp 
ccacacct-aaaaaac-ttccacgtgaaccgtatcaaaaccctt-agttgggggcttctg
ttcgg-ctggc-----ttcg------------------gctgg-ctgggcggcggctcta
tc------a-tggcgagcgca-tgggcctt--------cgggtct-gagctagtag--cc
ctct--ttttaaacccattc-ctaaatactgaatatactgtggggacgaaagtctctgct
tttaactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacgc
tgcgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaacg
catattgcacttccgggttagtcctgggagtatgcctgtatcagtgtccgtacatcaaac
ttgcctcccttccttccgtgtagtcggtggatggggacgtgcagacgtgaagtgtcttgc
g-attgg----tcttc--gggcc--ggctgcgagtcctttgaaatgtacagaactgtact
-tctctttgctcgaaaagc-atgacgttgttggttgtggaggctgtccgtgtggccagtc
-ggcgaccggtttgtctgctgcggcg-tttaatggaggagtgttcgattcgcggtatggt
tagcttcggctgaacaatgcgcttattggatgtt-ttttctgctg-tggcggtaatgact
ggtgaaccgtagctatgcagggcttggcttttgaaccgacggtgtt--gtgcgaagtaga
gtggcggtt----tggcgcaagct----gggctgtcga-gggtcgatcc-atttgggaaa
t-ttgtgtt-----------------ggcagcttcggctgt-tggcatctcaa
>Phytophthora_megakarya 900 bp 
ccacacct--aaaaactttccacgtgaaccgtatcaaccttt---agttgggggtctttt
tcg---gcggcggctgctggtttaattactggcg----gttgc-tgctgggagagcccta
tc------a-tggcgagcgtt-tgggcttc----------ggtct-gaactagtag--ct
t-----ttttaaacccattc-attattactgattatactgtggggacgaaagtctctgct
tttaactagatagcaactttcagcagtggatgtctaggctcgcacctcgatgaagaacgc
tgcgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaacg
catattgcacttccgggttagtcctggaagtatgcctgtatcagtgtccgtacatcaaac
ttggttttcttccttccgtgtagtcggtgga-ggatatgc-cagatgtgaggtgtcttgc
g-gctgg----ccttc--gggtc--ggctgtgagtcccttgaaatgtactgaactgtact
-tctctttgctcgaaaagt-aaagc-ttgcttgttgtggaggctgcttgtgtaaccagtc
-ggcgactagtttgtctgctgtggcg--ttaatggaggagtgttcgattcgcggtatgat
tggcttcggctgaacag-aagcttattgggcgtt-tttcctgcta-tggcggtatgaagt
agtgaaccgtagttatgtg-ggcttggcttttgaatgtgctc--gc-tgtgcgaagtaga
gtggcgact--------------t----tggttgtcga-gggtcgatcc-atttgggaaa
t--tgtgtg-t-------------------acttcggt----atgcatctcaa
>Phytophthora_megasperma 900 bp 
ccacacct-aaaaaactttccacgtgaaccgtatcaacccctta-aatttgggggcttgc
tcggc-ggcgtgtgtgctggcctgtaatgggtcggcgtgctgc-tgctgggcgggctcta
tc------atgggcgagcgtt-tgggcttc----------ggctc-gagctagtag--ct
atca-attttaaaccctttc-ttaaatactgaacatactgtggggacgaaagtctctgct
tttaactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacgc
tgcgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaacg
catattgcacttccgggttagtcctgggagtatgcctgtatcagtgtccgtacatcaacc
ttggttttcttccttccgtgtagtcggtgga-ggatatgc-cagatgtgaagtgtcttgc
t-agcgg----tctttcgagtct--gccggtgagtccttttaaatgtactgaactgtact
ctctctttgcgcgaaaagc-gtggcgttgctggttgtggaggctgcccgtgtggccagtc
-ggcgaccggtttgttagctgtggcg-tt---tggaggagtgttcgattcgcggtatggt
tggcttcggctaaacaatctgcttattgggtgct-tttcctgtca-tggcggtatgaact
ggtgaaccgtagctgtgtggtgcttggcttttgaaccggctttgct--ttgcgaagtagt
gtgacggct--------------t----cggctgtcgaggggtcgatcc-attttgggaa
a-ctttgtg-tg--------------tgcggcttcgtgctgcgcgcatctcaa
>Phytophthora_mirabilis 900 bp 
ccacacct--aaaaactttccacgtgaaccgtttc-aacccaat-agttgggggtcttac
ttg---gcggcggctgctggctttattgctggcg----gctac-t-ctgggcgagcccta
tc----aaa-aggcgagcgtt-tggacttc----------ggtct-gagctagtag--ct
tttttattttaaacccttta-cttaatactgattatactgtggggacgaaagtctctgct
tttaactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacgc
tgcgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaacg
catattgcacttccgggttagtcctggaagtatgcctgtatcagtgtccgtacaacaaac
ttggctttcttccttccgtgtagtcggtgga-ggagatgc-cagatgtgaagtgtcttgc
g-gttgg----ttttc--ggacc--gactgcgagtccttttaaatgtactaaactgtact
-tctctttgctccaaaagtggtggcattgctggttgtggacgctgctattgtagcgagtt
-ggcgaccggtttgtctgctgcggcg--ttaatggagaaatgctcgattcgtggtatggt
tggcttcggctgaacaatgcgcttattgggtgat-tttcctgctg-tggcgtgatggact
ggtgaaccatggctcttt--agcttggcatttgaatcggctttgct-gttgcgaagtaga
gtggcggct--------------t----cggctgccga-gggtcgatcc-atttgggaaa
t-gt-tgtg-t-------------------acttcggt----atgcatctcaa
>Phytophthora_nemorosa 900 bp 
ccacacct-aaaaaactttccacgtgaactgtatcgaa-caact-agttgggggtcttgt
ttgg--cgtgcggctgct----------tcggta----gctgc-tgctaggcaagcccta
tc------a-cggcgagcgtt-tggacttc----------ggtct-gagctagtag--ct
att---ttttaaacccattc-tttaatactgattatactgtggggacgaaagtctctgct
tttaactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacgc
tgcgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaacg
catattgcacttccgggttagtcctgggagtatgcctgtatcagtgtccgtacatcaaac
ttggctttcttccttccgtgtagtcggtgga-ggagacgc-cagacgtgaagtgtcttgc
g-gcgaa----ttttc--gaatt--tgctgtgagtcctttgaaatgtactgaactgtact
-tctctttgctcgaaaagc-gtggcgttgctggttgtggaggctgcccgcgtggccagtc
-ggcgaccggtttgtctgctgtagcg--ttaatggaggagtgttcgattcgcggtatggt
tagcttcggctgaacaa-gcgcttattggatgtt-cttcttgctg-tggcgtgatggact
ggtgaaccgtagctatgtgtggcttggcttttgaatcggctttgct-gttgcgaagtaga
gtggcggct--------------t----cggctgtcga-gggtcgatcc-atttgggaaa
t-ttgtgtg-t----------------atgacttcggttgt-atgcatctcaa
>Phytophthora_nicotianae 900 bp 
ccacacctaaaaaaactttccacgtgaaccgtttc-aacccaat-agttgggggtcttat
ttg---gcggcggctgctggcttaattgttggcg----gctgc-tgctgagtgagcccta
tcaaaaaaa-aggcgaacgtt-tgggcttc----------ggcct-gatttagtagtctt
tttttcttttaaacccattc-cttaatactgaatatactgtggggacgaaagtctctgct
tttaactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacgc
tgcgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaacg
catattgcacttccgggttagtcctggaagtatgcctgtatcagtgtccgtacattaaac
ttgactttcttccttccgtgtagtcggtgga-ggagatgt-cagatgtgaagtgtcttgc
g-attgg----tcttc--ggacc--ggctgcgagtccttttaaatgtactaaactgaact
-tctctttgctcgaaaagtggtggcgttgctggttgtgaaggctgctattgtggcaaatt
-ggcgactggtttgtctgctgcggca--ttaatggaagagtgttcgattcgtggtatggt
tggcttcggctgaacaatgcacttattggacgtt-tttcctgctg-tggcgtgatggact
ggtgaaccatagctcggt--ggcttggcttttgaattggctttgct-gttgcgaagtagg
gtggcagct--------------t----cggttgtcga-gggtcgatcc-atttgggaac
t-taatgtg-t-------------------acttcggt----atgcatctcaa
>Phytophthora_palmivora 900 bp 
ccacacct-aaaaaactttccacgtgaaccgtatcaaaactt---atttgggggtctctt
tcg---gcggcggctgctggcttcattgctggcg----gctgc-tgttgggagagctcta
tc------a-tggcgagcgtt-tgggcttc----------ggtct-gaactagtag--ct
t-----ttttaaacccattc-tttataactgattatactgtagggacgaaagtctctgct
tttaactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacgc
tgcgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaacg
catattgcacttccgggttagtcctgggagtatgcctgtatcagtgtccgtacatcaaac
ttggttttcttccttccgtgtagtcggtggt-ggatgtgc-cagatgtgaagtgtcttgc
g-gctgg----tcttc--ggatc--ggctgtgagtcctttgaaatgtactgaactgtact
-tctctttgctccaaaagc-gtggcgttgctgattgtggaggctgcttgcgtagccagtc
tggcgaccagtttgtctgctgtggcg--ttaatggaggagtgttcgattcgcggtatggt
tggcttcggctgaacag-acgcttattgaatatt-tcttcagctg-tggtggtat-gatt
ggtgaaccgtagctatgtg-agcttggcttttgaattggctttgct-gttgcgaagtaga
gtggcggct--------------t----cggctgtcga-gggtcgatcc-atttgggaac
t--tgtgta-t-------------------gcttcggc----atgcatctcaa
>Phytophthora_phaseoli 900 bp 
ccacacct--aaaaactttccacgtgaaccgtttc-aacccaat-agttgggggtcttac
ttg---gcggcggctgctggctttattgctggcg----gctac-tgctgggcgagcccta
tc----aaa-aggcgagcgtt-tgggcttc----------ggtct-gagctagtag--ct
tttttattttaaacccttta-cttaatactgattatactgtggggacgaaagtctctgct
tttaactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacgc
tgcgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaacg
catattgcacttccgggttagtcctggaagtatgcctgtatcagtgtccgtacaacaaac
ttggctttcttccttccgtgtagtcggtgga-ggagatgc-cagatgtgaagtgtcttgc
g-gttgg----ttttc--ggacc--gactgcgagtccttttaaatgtactaaactgtact
-tctctttgctccaaaagtggtggcattgctggttgtggacgctgctattgtagcgagtt
-ggcgaccggtttgtctgctgcggcg--ttaatggagaaatgctcgattcgtggtatggt
tggcttcggctgaacaatgcgcttattgggtgat-tttcctgctg-tggcgtgatggact
ggtgaaccatggctcttt--agcttggcatttgaatcggctttgct-gttgcgaagtaga
gtggcggct--------------t----cggctgccga-gggtcgatcc-atttgggaaa
t-gt-tgtg-t-------------------acttcggt----atgcatctcaa
>Phytophthora_pseudosyringae_470 Phytophthora_pseudosyringae_470 900 bp 
ccacacct-aaaaaactttccacgtgaactgtatcgaa-caact-agttgggggtcttgt
ttgg--cgtgcggctgct----------tcggta----gctgc-tgctaggcgagcccta
tc------a-cggcgagcgtt-tggacttc----------ggtct-gagctagtag--ct
att---ttttaaacccattc-tttaatactgattatactgtggggacgaaagtctctgct
tttaactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacgc
tgcgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaacg
catattgcacttccgggttagtcctgggagtatgcctgtatcagtgtccgtacatcaaac
ttggctttcttccttccgtgtagtcggtgga-ggagacgc-cagacgtgaagtgtcttgc
g-gcgaa----ttttc--gaatt--tgctgtgagtcctttgaaatgtactgaactgtact
-tctctttgctcgaaaagc-gtggcgttgctggttgtggaggctgcccgcgtggcctgtc
-ggcgaccggtttgtctgctgtggcg--ttaatggaggagtgttcgattcgcggtatggt
tagcttcggctgaacaa-gcgcttattggatgtt-cttcttgctg-tggcgtgatggact
ggtgaaccgtagctatgtgtggcttggcttttgaatcggctttgct-gttgcgaagtaga
gtggcggct--------------t----cggctgtcga-gggtcgatcc-atttgggaaa
t-ttgtgtg-t----------------atgacttcggttgt-atgcatctcaa
>Phytophthora_pseudosyringae_471 Phytophthora_pseudosyringae_471 900 bp 
ccacacct-aaaaaactttccacgtgaactgtatcgaa-caact-agttgggggtcttgt
ttgg--cgtgcggctgct----------tcggta----gctgc-tgctaggcgagcccta
tc------a-cggcgagcgtt-tggacttc----------ggtct-gagctagtag--ct
att---ttttaaacccattc-tttaatactgattatactgtggggacgaaagtctctgct
tttaactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacgc
tgcgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaacg
catattgcacttccgggttagtcctgggagtatgcctgtatcagtgtccgtacatcaaac
ttggctttcttccttccgtgtagtcggtgga-ggagacgc-cagacgtgaagtgtcttgc
g-gcgaa----ttttc--gaatt--tgctgtgagtcctttgaaatgtactgaactgtact
-tctctttgctcgaaaagc-gtggcgttgctggttgtggaggctgcccgcgtggcctgtc
-ggcgaccggtttgtctgctgtggcg--ttaatggaggagtgttcgattcgcggtatggt
tagcttcggctgaacaa-gcgcttattggatgtt-cttcttgctg-tggcgtgatggact
ggtgaaccgtagctatgtgtggcttggcttttgaatcggctttgct-gttgcgaagtaga
gtggcggct--------------t----cggctgtcga-gggtcgatcc-atttgggaaa
t-ttgtgtg-t----------------atgacttcggttgt-atgcatctcaa
>Phytophthora_pseudosyringae_472 Phytophthora_pseudosyringae_472 900 bp 
ccacacct-aaaaaactttccacgtgaactgtatcgaa-caact-agttgggggtcttgt
ttgg--cgtgcggctgct----------tcggta----gctgc-tgctaggcgagcccta
tc------a-cggcgagcgtt-tggacttc----------ggtct-gagctagtag--ct
att---ttttaaacccattc-tttaatactgattatactgtggggacgaaagtctctgct
tttaactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacgc
tgcgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaacg
catattgcacttccgggttagtcctgggagtatgcctgtatcagtgtccgtacatcaaac
ttggctttcttccttccgtgtagtcggtgga-ggagacgc-cagacgtgaagtgtcttgc
g-gcgaa----ttttc--gaatt--tgctgtgagtcctttgaaatgtactgaactgtact
-tctctttgctcgaaaagc-gtggcgttgctggttgtggaggctgcccgcgtggcctgtc
-ggcgaccggtttgtctgctgtggcg--ttaatggaggagtgttcgattcgcggtatggt
tagcttcggctgaacaa-gcgcttattggatgtt-cttcttgctg-tggcgtgatggact
ggtgaaccgtagctatgtgtggcttggcttttgaatcggctttgct-gttgcgaagtaga
gtggcggct--------------t----cggctgtcga-gggtcgatcc-atttgggaaa
t-ttgtgtg-t----------------atgacttcggttgt-atgcatctcaa
>Phytophthora_pseudosyringae_473 Phytophthora_pseudosyringae_473 900 bp 
ccacacct-aaaaaactttccacgtgaactgtatcgaa-caact-agttgggggtcttgt
ttgg--cgtgcggctgct----------tcggta----gctgc-tgctaggcgagcccta
tc------a-cggcgagcgtt-tggacttc----------ggtct-gagctagtag--ct
att---ttttaaacccattc-tttaatactgattatactgtggggacgaaagtctctgct
tttaactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacgc
tgcgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaacg
catattgcacttccgggttagtcctgggagtatgcctgtatcagtgtccgtacatcaaac
ttggctttcttccttccgtgtagtcggtgga-ggagacgc-cagacgtgaagtgtcttgc
g-gcgaa----ttttc--gaatt--tgctgtgagtcctttgaaatgtactgaactgtact
-tctctttgctcgaaaagc-gtggcgttgctggttgtggaggctgcccgcgtggcctgtc
-ggcgaccggtttgtctgctgtggcg--ttaatggaggagtgttcgattcgcggtatggt
tagcttcggctgaacaa-gcgcttattggatgtt-cttcttgctg-tggcgtgatggact
ggtgaaccgtagctatgtgtggcttggcttttgaatcggctttgct-gttgcgaagtaga
gtggcggct--------------t----cggctgtcga-gggtcgatcc-atttgggaaa
t-ttgtgtg-t----------------atgacttcggttgt-atgcatctcaa
>Phytophthora_pseudosyringae_Germany_PSEU16 Phytophthora_pseudosyringae_Germany_PSEU16 900 bp 
ccacacct-aaaaaactttccacgtgaactgtatcgaa-caact-agttgggggtcttgt
ttgg--cgtgcggctgct----------tcggta----gctgc-tgctaggcgagcccta
tc------a-cggcgagcgtt-tggacttc----------ggtct-gagctagtag--ct
att---ttttaaacccattc-tttaatactgattatactgtggggacgaaagtctctgct
tttaactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacgc
tgcgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaacg
catattgcacttccgggttagtcctgggagtatgcctgtatcagtgtccgtacatcaaac
ttggctttcttccttccgtgtagtcggtgga-ggagacgc-cagacgtgaagtgtcttgc
g-gcgaa----ttttc--gaatt--tgctgtgagtcctttgaaatgtactgaactgtact
-tctctttgctcgaaaagc-gtggcgttgctggttgtggaggctgcccgcgtggcctgtc
-ggcgaccggtttgtctgctgtggcg--ttaatggaggagtgttcgattcgcggtatggt
tagcttcggctgaacaa-gcgcttattggatgtt-cttcttgctg-tggcgtgatggact
ggtgaaccgtagctatgtgtggcttggcttttgaatcggctttgct-gttgcgaagtaga
gtggcggct--------------t----cggctgtcga-gggtcgatcc-atttgggaaa
t-ttgtgtg-t----------------atgacttcggttgt-atgcatctcaa
>Phytophthora_pseudotsugae 900 bp 
ccacacct--aaaaactttccacgtgaaccgtttcaaaccaaat-agttgggggtcttgt
ctg---gtggcggctgctggctttgttgttggcg----gctgc-tgctgggtgagcccta
tc------a-tggcgagcgtt-tgggcttc----------ggcct-gagctagtag--ct
tttc--ttttaaacccattc-cttaatactgattatactgtggggacgaaagtccttgct
tttaactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacgc
tgcgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaacg
catattgcacttccgggttagtcctgggagtatgcctgtatcagtgtccgtacatcaaac
ttggctttcttccttccgtgtagtcggtgga-ggagatgc-cagatgtgaagtgtcttgc
g-gctgg----ttttc--ggacc--gactgcgagtccttttaaatgtactgaactgtact
-tctctttgctcgaaaagc-gtggcgttgctggttgtggaggctgctattgtagcaagtt
-ggcgaccggtttgtctgctgcggcg--ttaatggaagagtgttcgattcgcggtatggt
tggcttcggctgaacaatgcgcttattggatgat-ttttctgctg-tggcgtgatggacc
ggtgaaccatagctcagt--ggcttggcttttgaatcggctttgct-gttgcgaagtaga
gtggcggct--------------t----cggctgtcga-gggtcgattc-atttgggaaa
t-gtgtgtg-t-------------------acttcggt----atgcatctcaa
>Phytophthora_ramorum 900 bp 
ccacacct-aaaaaactttccacgtgaaccgtatcaaaaccctt-agttgggggcttctg
ttcgg-ctggc-----ttcg------------------gctgg-ctgggcggcggctcta
tc------a-tggcgagcgct-tgagcctt--------cgggtct-gagctagtag--cc
cact--ttttaaacccattc-ctaaatactgaatatactgtggggacgaaagtctctgct
tttaactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacgc
tgcgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaacg
catattgcacttccgggttagtcctgggagtatgcctgtatcagtgtccgtacatcaaac
ttgcctcccttccttccgtgtagtcggtggatggggacgtgcagacgtgaagtgtcttgc
g-attgg----tcttc--gggcc--ggctgcgagtcctttgaaatgtacagaactgtact
-tctctttgctcgaaaagc-atgacgttgttggttgtggaggctgcccgtgtggccagtc
-ggcgaccggtttgtctgctgcggcg-tttaatggaggagtgttcgattcgcggtatggt
tagcttcggctgaacaatgcgcttattggatgct-ttttctgctg-tggcggtaatgact
ggtgaaccgtagctgtgcagggcttggcttttgaatcgacggtgtt--gtgcgaagtaga
gtggcggtt----cggcgcaagct----gggctgtcga-gggtcgatcc-atttgggaaa
c-ttgtgtt-----------------ggcggcttcggctgc-tggcatctcaa
>Phytophthora_sojae 900 bp 
ccacacct-aagaaactttccacgtgaaccgtatcaa--caagt-agttgggggcctgct
ctgtg-tggctgtctgtcgatgtcaaagtcggcggctggctgc-tgtgtggcgggctcta
tc------a-tggcgattggt-ttgggtcctcctcgtggggaact-ggatcatgag--cc
cact--ttttaaacccattc-ttaaatactgaatatactgtggggacgaaagtctctgct
tttaactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacgc
tgcgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaacg
catattgcacttccgggttagtcctgggagtatgcctgtatcagtgtccgtacatcaaac
ttggctctcttccttccgtgtagtcggtggatggagacgc-cagacgtgaggtgtcttgc
ggcgtgg----ccttc--gggct--gcctgcgagtcccttgaaatgtactgaactgtact
-tctctttgctcgaaaagc-gtgacgttgttggttgtggaggctgcctgtatggccagtc
-ggcgaccggtttgtctgctgcggcg-tttaatggaggagtgttcgattcgcggtatggt
tggcttcggctgaacaatgcgcttattggatgct-tttcctgctg-tggcggtatgggct
ggtgaaccgtagctgtgtgaggcttggcttttgaaccggcggtgtt-gttgcgaagtagg
gtggcggct--------------t----cggctgtcga-gggtcgatcc-atttgggaac
t-ctgtgtt-gtctctgcg-------gcttgctgcggagg--tggcatctcaa
>Phytophthora_syringae 900 bp 
ccacacct-aaaaaac-ttccacgtgaaccgtatcaaaacccttttattgggggcttctg
tctggtctggc-----ttcg------------------gctggattgggtggcggctcta
tc------a-tggcgaccgctctgagcttc----------ggcctggagctagtag--cc
cact--ttttaaacccattc-ttaattactgaacaaactgtggggacgaaagtctctgct
tttaactagatagcaactttcagcagtggatgtctaggctcgcacatcgatgaagaacgc
tgcgaactgcgatacgtaatgcgaattgcaggattcagtgagtcatcgaaattttgaacg
catattgcacttccgggttagtcctgggagtatgcctgtatcagtgtccgtacatcaaac
ttggctcccttccttccgtgtagtcggtggatggggatgcacagacgtgaagtgtcttgc
g-actgg----gcttc--ggctc--ggctgcgagtccttttaaatgtacagaactgtact
-tctctttgctcgaaaagc-gttatattactggttgtggaggctgcctgtgcggcaagtc
-ggcgaccggtttgttaactgcggcg-tttaatggaggagtgttcgattcgcggtatgga
tggcttcggctgaactg-acgcttattgagtact-tttcctgctg-tggtggtacgaact
ggtgaaccgtagctgtgtttggcttggcttttgaactggcgatgtg--gtgcgaagtaga
gtgacggttgttccggcgcaagctggagtgactgtcga-gggtcgatcc-atttgggaaa
ttttgtgtc-tg--------------tgcgacttcggttgcgtggcatctcaa
