>Cryptosphaeria_ligniota_AJ302418 Cryptosphaeria_ligniota_AJ302418 610 bp 
gggatcattatagagtta-ta-a------actcc-taaaacccatgtg-aacttacc--t
atgttgcctcggcgggaaa--------------------------gcctacccggtacct
acctaccctgta----gacacccggga-gcgagctaccctgtagcccgctgca------g
gcccacccgccggtggacagtt-gaactcttgtttttttttat-gtggcattctgaa-tg
attatacttaataagttaaaactttcaacaacggatctcttggttctggcatcgatgaag
aacgcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaatcatcgaatcttt
gaacgcacattgcgcccattagtattctagtgggcatgcctgttcgagcgtcatttcaa-
-ccctcaagcccta----gctgcttggtgttgggagtttac----ctgc-----------
gggtaattcctgaaataaat-cggcggagtcgcggtg-accccaagcgtagtaa--tttt
tcctcgctttaggtg-tgtcggtgctgacgttcggccgctaaaccccttattttct-agt
gg--ttgacctcgg
>Cryptosphaeria_pullmanensis_AJ302419 Cryptosphaeria_pullmanensis_AJ302419 610 bp 
gggatcattatagagtgt-ta-a------actcc-caaaacccatgtg-aacttacc--t
atgttgcctcggcgggaaa--------------------------gctgacccggatggt
aattaccctgta----gttacccggga-gcgagctacctcgtagcccgctgca------g
gcccacccgccggtggacagtt-aaactcttgttttttttcat--gtggcatctgaa-tg
attatacgtaataagttaaaactttcaacaacggatctcttggttctggcatcgatgaag
aacgcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaatcatcgaatcttt
gaacgcacattgcgcccattagtattctagtgggcatgcctgttcgagcgtcatttcaa-
-ccctcaagcccta----gctgcttggtgttgggagtttac----ctgc-----------
gggtaattcctcaaatgcat-cggcggagtcgcggtg-accccaagcgtagtaa--tttt
tcctcgctttcggag-tgtcggcgctggcgttcggccgttaaaccccctattttct-agt
gg--ttgacctcgg
>Cryptosphaeria_pullmanensis_UCD730SJ Cryptosphaeria_pullmanensis_UCD730SJ 610 bp 
gggatcattatagagtat-ta-a------actcc-caaaacccatgtg-aacttacc--t
atgttgcctcggcgggaaa--------------------------gctgacccggatggt
aattaccctgta----gttacccggga-gcgagctacctcgtagcccgctgca------g
gcccacccgccggtggacagtt-aaactcttgtttttttttat--gtggcatctgaa-tg
attatacgtaataagttaaaactttcaacaacggatctcttggttctggcatcgatgaag
aacgcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaatcatcgaatcttt
gaacgcacattgcgcccattagtattctagtgggcatgcctgttcgagcgtcatttcaa-
-ccctcaagcccta----gctgcttggtgttgggagtttac----ctgc-----------
gggtaattcctcaaatgcat-cggcggagtcgcggtg-accccaagcgtagtaa--ttct
tcctcgctttcggag-tgtcggcgctggcgttcggccgttaaaccccttattttct-agt
gg--ttgacctcgg
>Cryptosphaeria_subcutanea_AJ302420 Cryptosphaeria_subcutanea_AJ302420 610 bp 
gggatcattatagagtta-ta-a------actcc-taaaacccatgtg-aacttacc--t
atgttgcctcggcggggaa--------------------------gcttacccgg----t
acctaccctgta----gacacccggga-gcgagctaccctgtagcccgctgca------g
gcccacccgccggtggacagtt-aaactcttg---ttttttat-gtggcattctgaa-tg
attatacttaataagttaaaactttcaacaacggatctcttggttctggcatcgatgaag
aacgcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaatcatcgaatcttt
gaacgcacattgcgcccattagtattctagtgggcatgcctgttcgagcgtcatttcaa-
-ccctcaagcccta----gctgcttggtgttgggagtttac----ctgc-----------
gggtaattcctgaaataaat-cggcggagtcgcggtg-accccaagcgtagtaa--tttt
tcctcgcttcaggtg-tgtcggtgctgacgttcggccgttaaaccccctattttct-agt
gg--ttgacctcgg
>Cryptovalsa_ampelina_AY920391 610 bp 
gggatcattacagagtta-tc-t------aactc-ccaaaaccatgtg-aacttacc--t
atgttgcctcggcggggaa--------------------------gctaacccgg----t
acctacccagta----gttacccggga--gggcctaccctgtagctacccta-------t
agcgacccgccggtggactgct-aaactcttg---tttttaag--tgatattctgag-tg
tttaaacttaattagttaaaactttcaacaacggatctcttggttctggcatcgatgaag
aacgcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaatcatcgaatcttt
gaacgcacattgcgcccattagtattctagtgggcatgcctgttcgagcgtcatttcaa-
-cccttaagcctta----gttgcttagtgttgggggctcgc----ctagctatagacgc-
tggcgaccccttaaaaatat-cggcggagtcgtgtcg-accctaagcgtagtaa-tttat
tcctcgcttcaggct-tgtaggcgctggcgtccggccgttaaaccccctatttttt-aat
gg--ttgacctcgg
>Cryptovalsa_ampelina_DMO300 610 bp 
gggatcattacagagtta-tc-t------aactc-ccaaaaccatgtg-aacttacc--t
atgttgcctcggcggggaa--------------------------gctaacccgg----t
acctacccagta----gttacccggga--gggcctaccctgtagctacctta-------t
agcgacccgccggtggactgct-aaactcttg---tttttaag--tgatattctgag-tg
tttaaacttaattagttaaaactttcaacaacggatctcttggttctggcatcgatgaag
aacgcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaatcatcgaatcttt
gaacgcacattgcgcccattagtattctagtgggcatgcctgttcgagcgtcatttcaa-
-cccttaagcctta----gttgcttagtgttgggggctcgc----ctagctatagacgc-
tggcgaccccttaaaaatat-cggcggagtcgtgtcg-accctaagcgtagtaa-tttat
tcctcgcttcaggct-tgtaggcgctggcgtccggccgttaaaccccctaattttt-aat
gg--ttgacctcgg
>Cryptovalsa_ampelina_RANCHO4 610 bp 
gggatcattacagagtta-tc-t------aactc-ccaaaaccatgtg-aacttacc--t
atgttgcctcggcggggaa--------------------------gctaacccgg----t
acctacccagta----gttacccggga--gggcctaccctgtagctacccta-------t
agcgacccgccggtggactgct-aaactcttg---tttttaag--tgatattctgag-tg
tttaaacttaattagttaaaactttcaacaacggatctcttggttctggcatcgatgaag
aacgcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaatcatcgaatcttt
gaacgcacattgcgcccattagtattctagtgggcatgcctgttcgagcgtcatttcaa-
-cccttaagcctta----gttgcttagtgttgggggctcgc----ctagctatagacgc-
tggcgaccccttaaaaatat-cggcggagtcgtgtcg-accctaagcgtagtaa-tttat
tcctcgcttcaggct-tgtaggcgctggcgtccggccgttaaaccccctatttttt-aat
gg--ttgacctcgg
>Daldinia_concentrica_AF201708 610 bp 
gggatcattaccgagtta-tc-t------aaact-ccaaccctttgtgaaacttacc--g
tcgttgcctcggcgggctgc-------------------------gcttaccctg----t
agctaccctgta----gctacccggtaggcgcgc-------------------------t
ccaagcccgccggtggaccact-aaactctgt---tttaatac--cgaatctctgaa-tg
cttcaacttaataagttaaaactttcaacaacggatctcttggttctggcatcgatgaag
aacgcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaatcatcgaatcttt
gaacgcacattgcgcccattagtattctagtgggcatgcctattcgagcgtcatttcaa-
-cccttaagcctta----gttgcttagcgttgggagtctgc----gctgtacttgttacg
gcgcagttcctcaaagtgat-tggcggagttagggcatactctaagcgtagtaatatttc
ttctcgcttctg----tagttgtcctggcggcttgccgttaaacccctatattttctagt
gg--ttgacctcgg
>Diatrype_bullata_AJ302422 610 bp 
gggatcattacagagtta-cctt------aact--ccaaacccatgtg-aacttacc--t
atgttgcctcggcggggaa--------------------------gcctacccgg----t
aattaccctgta----gttacccggga-gcgagctaccctgtagcccgctgca------g
gcctacccgccggcggacactt-aaactcttg--ttttacagt--gaaacttctgat-at
tttatacttaataagttaaaactttcaacaacggatctcttggttctggcatcgatgaag
aacgcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaatcatcgaatcttt
gaacgcacattgcgcccattagtattctagtgggcatgcctgttcgagcgtcatttcga-
-ccatcaagcccca----gttgcttggttttgggagcctat----ctttag---------
ggatagctccttaaatagag-tggcggagtcgtgctg-accccaagcgtagtaa--ttct
ttctcgctttagg---tgccggtgccgacgtcctgccgttaaaccccctattttta-aaa
gg--ttgacctcgg
>Diatrype_disciformis_AJ302424 610 bp 
gggatcattacagagtta-cc-t------aact--ccaaacccatgtg-aacttacc--t
atgttgcctcggcggggaa--------------------------gcctacccgg----t
acctaccctgta----gttacccggga-gcgagctaccctgtagcccgctgca------g
gcctacccgccggtggacagtt-aaactcttg-tttttacagt--gaaacttctgat-at
tttatacttaataagttaaaactttcaacaacggatctcttggttctggcatcgatgaag
aacgcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaatcatcgaatcttt
gaacgcacattgcgcccattagtattctagtgggcatgcctgttcgagcgtcatttcga-
-ccatcaagccccg----gttgcttggttttgggagcctat----ctctag---------
ggatagctccttaaatagag-tggcggagtcgtgccg-accccaagcgtagtaa--tttc
ttctcgcttcagg---tgccggtgctgacgtcctgccgttaaaccccctattttta-aaa
gg--ttgacctcgg
>Diatrype_flavovirens_AJ302430 610 bp 
gggatcattacagagtta-tc-t------aactc-ccaaacccatgtg-aacttacc--t
acgttgcctcggcggggaa--------------------------gcctacccgg----t
acctaccctgta----gttacccggga-gcgagctaccctgtagcccgctgca------g
gcctacccgccggtggacatct-aaactcttg---ttttctag--tgattatctgag-tg
tttatacttaataagttaaaactttcaacaacggatctcttggttctggcatcgatgaag
aacgcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaatcatcgaatcttt
gaacgcacattgcgcccattagtattctagtgggcatgcctgttcgagcgtcatttcaa-
-ccctcaagcccta----gttgcttggtattgggagcttgc----ctac-----------
gggcaactcctcaaaagcat-tggcggagtcgcggtg-accccaagcgtagtaa---ttc
ttctcgc-ttaggtg-tgtcaacgctgacgttcagccactaaaccccctattttct-agt
gg--ttgacctcgg
>Diatrype_macowaniana_AJ302431 610 bp 
gggatcattacagagtta-tc-t------aact--cccaacccatgtg-aacttacc--t
ttgttgcctcggcggggaa--------------------------gcctacccgg----t
acctaccctgta----gttacccggga-gcgagctaccctgtagcccgctgct------g
gccgacccgccggtggacagta-aaactcttg---tttttagt--gaattatctgag-tg
tttatacttaataagttaaaactttcaacaacggatctcttggttctggcatcgatgaag
aacgcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaatcatcgaatcttt
gaacgcacattgcgcccattagtattctagtgggcatgcctgttcgagcgtcatttcaa-
-ccctcaagcccca----gttgcttggtgttgggagcttgc----ccct-----------
acgcaactcctgaaagctat-tggcggagccgcattg-gccctaagcgtagtaa--tttt
tcctcgcttcaggtg-tcccggtgctggcgtcctgccgtaaaacccccaattttac-aat
gg--ttgacctcgg
>Diatrype_oregonensis_DCA600 610 bp 
gggatcattacagagtta-cc-t------aact--cccaacccatgtg-aacttacc--t
ttgttgcctcggcgggaga--------------------------gcctacccgg----t
acctaccctgta----gttacccggga-gcgagctaccctgtagcccgctgct------g
gccgacccgccggtggacagta-aaactcttg---ttttttag--tgattatctgag-tg
tttatacttaataagttaaaactttcaacaacggatctcttggttctggcatcgatgaag
aacgcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaatcatcgaatcttt
gaacgcacattgcgcccattagtattctagtgggcatgcctgttcgagcgtcatttcaa-
-ccctcaagcccca----gttgcttggtgttgggagcctgc----cccccccggg-----
gagcagctcctcaaagctat-tggcggagtcgtattg-gccctaagcgtagtaa-ttttt
tcctcgcttctagtggttccagtgctggcgtccagccgtaaaacccctaattttct-agt
gg--ttgacctcgg
>Diatrype_sp_DBEY700 610 bp 
gggatcattacagagtta-tc-t------aact--cccaacccatgtg-aacttacc--t
atgttgcctcggcgggaaa--------------------------gcctacccgg----t
acctaccctgta----gttacccggga-gcgggctaccctgtagcccgctgct------g
gccgacccgccggtggacagta-aaactcttg---tttttagt--gaattgtctgag-tg
tttatacttaataagttaaaactttcaacaacggatctcttggttctggcatcgatgaag
aacgcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaatcatcgaatcttt
gaacgcacattgcgcccattagtattctagtgggcatgcctgttcgagcgtcatttcaa-
-ccctcaagcccca----gttgcttggtattgggagcttgc----ctgc-----------
gggcaactcctcgaagctat-tggcggagccgcgtgg-gccctaagcgtagtaa--tctt
ttctcgcttcaggtg-cttccgtgctggcgtccagccgtaaaacccccaattttt--aat
gg--ttgacctcgg
>Diatrype_spilomea_AJ302433 610 bp 
gggatcattacagagtta-cc-t------aact--ccaaacccatgtg-aacttacc--t
atgttgcctcggcggggaa--------------------------gcctacccgg----a
acctaccctgta----gttacccggga-gcgagctaccctgtagcccgctgca------g
gcctacccgccggcggacactt-aaactcttg--ttttacagt--gaaacttctgat-at
tttatacttaataagttaaaactttcaacaacggatctcttggttctggcatcgatgaag
aacgcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaatcatcgaatcttt
gaacgcacattgcgcccattagtattctagtgggcatgcctgttcgagcgtcatttcga-
-ccatcaagcccca----gttgcttggttttgggagcctat----ctctag---------
ggatagctccttaaatagag-tggcggagtcgtgctg-accccaagcgtagtaa--tttt
ttctcgctttagg---tgccggtgctgacgtcctgccgttaaaccccctattttta-aaa
gg--ttgacctcgg
>Diatrype_stigma_AJ302439 610 bp 
gggatcattacagagtta-tc-t------aactc-ccaaacccatgtg-aacttacc--t
atgttgcctcggcggggaa--------------------------gcctacccgg----t
acctaccctgta----gttacccggga-gcgagctaccctgtagcccgctgca------g
gcctacccgccggtggacagtt-aaactcttg--ttttacagt--gaaacttctgat-at
tttatacttaataagttaaaactttcaacaacggatctcttggttctggcatcgatgaag
aacgcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaatcatcgaatcttt
gaacgcacattgcgcccattagtattctagtgggcatgcctgttcgagcgtcatttcga-
-ccctcaagcctca----gttgcttggttttgggagcctat----ctcc-----------
ggatagctcctcaaatagag-tggcggagtcgtgctg-accccaagcgtagtaa--tttt
ttctcgctttagg---tgccggtgctgacgtcttgccgttaaaccccctattttt--aaa
gg--ttgacctcgg
>Diatrype_stigma_DCash200 610 bp 
gggatcattacagagtta-tc-t------aactc-ccaaacccatgtg-aacttacc--t
atgttgcctcggcggggaa--------------------------gcctacccgg----t
acctaccctgta----gttacccggga-gcgagctaccctgtagcccgctgca------g
gcctacccgccggtggacagtt-aaactcttg--ttttacagt--gaaacttctgat-at
tttatacttaataagttaaaactttcaacaacggatctcttggttctggcatcgatgaag
aacgcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaatcatcgaatcttt
gaacgcacattgcgcccattagtattctagtgggcatgcctgttcgagcgtcatttcga-
-ccctcaagcctca----gttgcttggttttgggagcctat----ctcc-----------
ggatagctcctcaaatagag-tggcggagtcgtgctg-accccaagcgtagtaa--tttt
ttctcgctttagg---tgccggtgctgacgtcttgccgttaaaccccctattttt--aaa
gg--ttgacctcgg
>Diatrype_undulata_AJ302436 610 bp 
gggatcattacagagtta-tc-t------aactc-ccaaacccatgtg-aacttacc--t
atgttgcctcggcggggaa--------------------------gcctacccgg----t
acctaccctgta----gttacccggga-gcgagctaccctgtagcccgctgca------g
gcctacccgccggtggacagtt-aaactcttg--ttttacagt--gaaacttctgat-at
tttatacttaataagttaaaactttcaacaacggatctcttggttctggcatcgatgaag
aacgcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaatcatcgaatcttt
gaacgcacattgcgcccattagtattctagtgggcatgcctgttcgagcgtcatttcga-
-ccttcaagcctca----gttgcttggttttgggagcctat----ccttc----------
ggatagctcctcaaatagagttggcggagtcgtgctg-accccaagcgtagtaa--tttc
ttctcgcttcagg---tgccggtgctgacgtcttgccgttaaaccccctatttca--aat
gg--ttgacctcgg
>Diatrype_whitmanensis_CDB011 610 bp 
gggatcattacagagtta-tt-t------aactc-ccaaacccgtgtg-aacttacc--t
acgttgcctcggcggggaa--------------------------gcctacccgg-tagt
atctaccctgta----gttacccggga-gcgagctaccctgtagcccgctgca------g
gcctacccgccggtggactgct-aaactcttg-tttttttggt--ggattatctgag-tg
tttatacttaacgagttaaaactttcaacaacggatctcttggttctggcatcgatgaag
aacgcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaatcatcgaatcttt
gaacgcacattgcgcccattagcattctagtgggcatgcctgttcgagcgtcatttcaa-
-ccctcaagcccta----gttgcttggtgttgggagcttat--ctctct-----------
ggataactcctcgaaagcat-tggcggagtcgcggtg-accccgagcgtagtaa---ttc
ttctcgctttaggtg-tgttagcgctgtcgtctagccgttaaaccttctattttct-agt
gg--ttgacctcgg
>Diatrypella_favacea_AJ302440 610 bp 
gggatcattacagagtta-tc-t------aactc-ccaaaaccatgtg-aacttacc--t
atgttgcctcggcggggaa--------------------------gcctacccgg----t
acctaccctgta----gttacccggga-gcgagctaccctgtagcccgctgct------g
gcctacccgccggtggactgtt-aaactcttg---ttttttag--tgattatctgag-tg
tttatacttaataagttaaaactttcaacaacggatctcttggttctggcatcgatgaag
aacgcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaatcatcgaatcttt
gaacgcacattgcgcccattagtattctagtgggcatgcctgttcgagcgtcatttcaa-
-ccctcaagcccta----gttgcttggtgttgggagcctat----ctcc-----------
ggatagctcctcaaaaccat-tggcggagtcgcgatg-gccccaagcgtagtaa--tttt
tattcgcttcaggtg-tgtcagcgctggcgttcagccgttaaaccccctattttct-agt
gg--ttgacctcgg
>Diatrypella_frostii_AJ302441 610 bp 
gggatcattacagagtta-tc-t------aact--cccaacccatgtg-aacttacc--t
ttgttgcctcggcgggaga--------------------------gcctacccgg----t
acctaccctgta----gttacccggga-gcgagctgccctgcagcccgctgct------g
gccgacccgccggtggacagta-aaactcttg---tttttagt--ggattatctgag-tg
tttatacttaataagttaaaactttcaacaacggatctcttggttctggcatcgatgaag
aacgcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaatcatcgaatcttt
gaacgcacattgcgcccattagtattctagtgggcatgcctgttcgagcgtcatttcaa-
-ccctcaagcccca----gttgcttggtgttgggagcctgc----ccccctaggg-----
gagcagctcctcaaagctat-tggcggagtcgtattg-gccctaagcgtagtaa--tttt
tcctcgcttttagtggttccagtgctggcgtccagccgtaaaacccctaattttct-agt
gg--ttgacctcgg
>Diatrypella_prominens_AJ302442 610 bp 
gggatcattacagagtta-tc-c------aact--cccaacccatgtg-aacttacc--t
ttgttgcctcggcgggagagcctacccggtacctaccctgtagttgcctacccgg----t
acctaccctgta----gttacccggga-gcgagctgccctgcagcccgctgct------g
gccgacccgccggtggacagta-aaactcttg--ttttttagt--ggattatctgag-tg
tttatacttaataagttaaaactttcaacaacggatctcttggttctggcatcgatgaag
aacgcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaatcatcgaatcttt
gaacgcacattgcgcccattagtattctagtgggcatgcctgttcgagcgtcatttcaa-
-ccctcaagccccc----gttgcttggtgttgggagcctgc----cccccctagggg---
gggcagctcctcaaagctat-tggcggagccgtgctg-gccctaagcgtagtaa--tttg
ttctcgcttctagtggttccagcgctggcgttcagccgtaaaacccctaattttct-agt
gg--ttgacctcgg
>Diatrypella_pulvinata_AJ302443 610 bp 
gggatcattacagagtta-tc-t------aactc-ccaaaaccatgtg-aacttacc--t
atgttgcctcggcggggaa--------------------------gcctacccgg----t
acctaccctgta----gttacccggga-gcgagctaccctgtagcccgctgct------g
gccgacccgccggtggactgct-aaactcttg---ttttttcg--tgattatctgag-tg
tttatacttaataagttaaaactttcaacaacggatctcttggttctggcatcgatgaag
aacgcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaatcatcgaatcttt
gaacgcacattgcgcccattagtattctagtgggcatgcctgttcgagcgtcatttcaa-
-ccctcaagcccta----gttgcttggtgttgggagcctat----ctcc-----------
ggatagctcctcaaaaccat-tggcggagtcgcgatg-gccccaagcgtagtaa--tttt
tattcgcttcaggtg-tgtcagcgctggcgtccagccgctaaaccccctatttttt-agt
gg--ttgacctcgg
>Diatrypella_quercina_AJ302444 610 bp 
gggatcattacagagttc-cc-t------aact--ccaaacccatgtg-aacttacc--t
atgttgcctcggcgggaaa--------------------------acctacccgg----t
aattaccctgta----gttacccggga-gcgagctacctggtagcccgctgca------g
gcctacccgccggtggacagtt-aaactcttg--ttttaccgt--gaaacttctgat-at
tttatacttaataagttaaaactttcaacaacggatctcttggttctggcatcgatgaag
aacgcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaatcatcgaatcttt
gaacgcacattgcgcccattagtattctagtgggcatgcctgttcgagcgtcatttcga-
-ccatcaagcccca----gctgcttggttttgggagcctat----ctccag---------
ggatagctccttaaatagag-tggcggagtcgtgctg-a-cccaagcgtagtaa---ttt
ttctcgcttctgg---tgccggtgctgacgtcctgccgttaaaccccctatttttt-aaa
gg--ttgacctcgg
>Diatrypella_sp_CA008 610 bp 
gggatcattacagagtta-at-a------aact--cccaacccatgtg-aacttacc--t
atgttgcctcggcgggaga--------------------------gcctacccgg----t
acctaccctgta----gttacccggga-gcgagctaccctgtagcccgctgct------g
gccgacccgccggtggacagta-aaactcttg---tttttagt--ggattatctgag-tg
tttatacttaataagttaaaactttcaacaacggatctcttggttctggcatcgatgaag
aacgcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaatcatcgaatcttt
gaacgcacattgcgcccattagtattctagtgggcatgcctgttcgagcgtcatttcaa-
-ccctcaagcccca----gttgcttggtgttgggagcctgca-cccccccggggg-----
ctgcagctcctcaaagctat-tggcggagtcgtattg-gccctaagcgtagtaa-ttttt
tcctcgcttctagtggttccagtgctggcgtccagccgtaaaacccctaatctttt-agt
gg--ttgacctcgg
>Diatrypella_sp_CA010 610 bp 
gggatcattacagagtta-at-a------aact--cccaacccatgtg-aacttacc--t
atgttgcctcggcgggaga--------------------------gcctacccgg----t
acctaccctgta----gttacccggga-gcgagctaccctgtagcccgctgct------g
gccgacccgccggtggacagta-aaactcttg---tttttagt--ggattatctgag-tg
tttatacttaataagttaaaactttcaacaacggatctcttggttctggcatcgatgaag
aacgcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaatcatcgaatcttt
gaacgcacattgcgcccattagtattctagtgggcatgcctgttcgagcgtcatttcaa-
-ccctcaagcccca----gttgcttggtgttgggagcctgca-cccccccggggg-----
ctgcagctcctcaaagctat-tggcggagtcgtattg-gccctaagcgtagtaa-ttttt
tcctcgcttctagtggttccagtgctggcgtccagccgtaaaacccctaatcttct-agt
gg--ttgacctcgg
>Diatrypella_sp_CA015 610 bp 
gggatcattacagagtta-at-a------aact--cccaacccatgtg-aacttacc--t
atgttgcctcggcgggaga--------------------------gcctacccgg----t
acctaccctgta----gttacccggaa-gcgagctaccctgtagcccgctgct------g
gccgacccgccggtggacagta-aaactcttg---tttttagt--ggattatctgag-tg
tttatacttaataagttaaaactttcaacaacggatctcttggttctggcatcgatgaag
aacgcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaatcatcgaatcttt
gaacgcacattgcgcccattagtattctagtgggcatgcctgttcgagcgtcatttcaa-
-ccctcaagcccca----gttgcttggtgttgggagcctgca-acccccaagggg-----
ctgcagctcctcaaagctat-tggcggagtcgtattg-gccctaagcgtagtaa-ttttt
tcctcgcttctagtggttccagtgctggcgtccagccgtaaaacccctaattttct-agt
gg--ttgacctcgg
>Diatrypella_sp_CA149 610 bp 
gggatcattacagagtta-at-a------aact--cccaacccatgtg-aacttacc--t
atgttgcctcggcgggaga--------------------------gcctacccgg----t
acctaccctgta----gttacccggga-gcgagctaccctgtagcccgctgct------g
gccgacccgccggtggacagta-aaactcttg---tttttagt--ggattatctgag-tg
tttatacttaataagttaaaactttcaacaacggatctcttggttctggcatcgatgaag
aacgcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaatcatcgaatcttt
gaacgcacattgcgcccattagtattctagtgggcatgcctgttcgagcgtcatttcaa-
-ccctcaagcccca----gttgcttggtgttgggagcctgca-cccccccggggg-----
ctgcagctcctcaaagctat-tggcggagtcgtattg-gccctaagcgtagtaa-ttttt
tcctcgcttctagtggttccagtgctggcgtccagccgtaaaacccctaattttct-agt
gg--ttgacctcgg
>Diatrypella_sp_CA7614 610 bp 
gggatcattacagagtta-at-a------aact--cccaacccatgtg-aacttacc--t
atgttgcctcggcgggaga--------------------------gcctacccgg----t
acctaccctgta----gttacccggga-gcgagctaccctgtagcccgctgct------g
gccgacccgccggtggacagta-aaactcttg---tttttagt--ggattatctgag-tg
tttatacttaataagttaaaactttcaacaacggatctcttggttctggcatcgatgaag
aacgcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaatcatcgaatcttt
gaacgcacattgcgcccattagtattctagtgggcatgcctgttcgagcgtcatttcaa-
-ccctcaagcccca----gttgcttggtgttgggagcctgca-acccccaagggg-----
ctgcagctcctcaaagctat-tggcggagtcgtattg-gccctaagcgtagtaa-ttttt
tcctcgcttctagtggttccagtgctggcgtccagccgtaaaacccctaattttct-agt
gg--ttgacctcgg
>Diatrypella_sp_UCDCH2 610 bp 
gggatcattacagagtta-at-a------aact--cccaacccatgtg-aacttacc--t
atgttgcctcggcgggaga--------------------------gcctacccgg----t
acctaccctgta----gttacccggga-gcgagctaccctgtagcccgctgct------g
gccgacccgccggtggacagta-aaactcttg---tttttagt--ggattatctgag-tg
tttatacttaataagttaaaactttcaacaacggatctcttggttctggcatcgatgaag
aacgcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaatcatcgaatcttt
gaacgcacattgcgcccattagtattctagtgggcatgcctgttcgagcgtcatttcaa-
-ccctcaagcccca----gttgcttggtgttgggagcctgcaccccccccggggg-----
ctgcagctcctcaaagctat-tggcggagtcgtattg-gccctaagcgtagtaa-ttttt
tcctcgcttctagtggttccagtgctggcgtccagccgtaaaacccttaattttct-agt
gg--ttgacctcgg
>Diatrypella_verrucaeformis_DHB500 Diatrypella_verrucaeformis_DHB500 610 bp 
gggatcattacagagtta-at-a------aact--cccaacccatgtg-aacttacc--t
atgttgcctcggggggaga--------------------------gcctacccgg----t
acctaccctgta----gttacccggga-gcgagctaccctgtagcccgctgct------g
gccgacccgccggtggacagta-aaactcttg---tttttagt--ggattatctgag-tg
tttatacttaataagttaaaactttcaacaacggatctcttggttctggcatcgatgaag
aacgcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaatcatcgaatcttt
gaacgcacattgcgcccattagtattctagtgggcatgcctgttcgagcgtcatttcaa-
-ccctcaagcccca----gttgcttggtgttgggagcctgca-cccccccggggg-----
ctgcagctcctcaaagctat-tggcggagtcgtattg-gccctaagcgtagtaa-ttttt
tcctcgcttctagtggttccagtgctggcgtccagccgtaaaacccctaattttct-agt
gg--ttgacctcgg
>Eutypa_lata_AJ302450 610 bp 
gggatcattacagagtta-cc-t------aact--ccaaacccatgtg-aacttacc--t
atgttgcctcggcggggaa--------------------------gcctacccgg----t
acctaccctgta----gctacccggga-gcgagctaccctgtagcccgctgca------g
gcctacccgccggtggacactt-aaactcttg---ttttttag--tgattatctgag-tg
tttatacttaataagttaaaactttcaacaacggatctcttggttctggcatcgatgaag
aacgcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaatcatcgaatcttt
gaacgcacattgcgcccattagtattctagtgggcatgcctgttcgagcgtcatttcga-
-ccttcaagcccta----gctgcttggtgttgggagcctat----ctcc-----------
ggatagctcctcaaaagcat-tggcggagtcgcggtg-accccaagcgtagtaa---ttc
ttctcgctttaggtg-tgtcacggctgacgtcttgccgttaaacccccaattttttaaat
gg--ttgacctcgg
>Eutypa_lata_DCA900 610 bp 
gggatcattacagagtta-cc-t------aact--ccaaacccatgtg-aacttacc--t
atgttgcctcggcggggaa--------------------------gcctacccgg----t
acctaccctgta----gctacccggga-gcgagctaccctgtagcccgctgca------g
gcctacccgccggtggacactt-aaactcttg--tttttttag--tgattatctgag-tg
tttatacttaataagttaaaactttcaacaacggatctcttggttctggcatcgatgaag
aacgcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaatcatcgaatcttt
gaacgcacattgcgcccattagtattctagtgggcatgcctgttcgagcgtcatttcga-
-ccttcaagcccta----gctgcttggtgttgggagcctat----ctcc-----------
ggatagctcctcaaaagcat-tggcggagtcgcggtg-accccaagcgtagtaa---ttc
ttctcgctttaggtg-tgtcacggctgacgtcttgccgttaaacccccaattttttaaat
gg--ttgacctcgg
>Eutypa_leptoplaca_AY684237 610 bp 
gggatcattacagagtta-cc-c------aactcaccaaacccatgtg-aacttacc--t
atgttgcctcggcggggaa--------------------------gcctacccgg----t
acctaccctgta----gttacccggga-gcgagctacgctgtagcccgctgca------g
gccaacccgccggtggactgtt-aaactcttg----ttatagt--ggaacttctgat-tt
tttatacttaataagttaaaactttcaacaacggatctcttggttctggcatcgatgaag
aacgcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaatcatcgaatcttt
gaacgcacattgcgcccattagtattctagtgggcatgcctgttcgagcgtcatttcaa-
-ccctcaagcccta----gttgcttggtgttgggagtttac----ctgc-----------
gggtaattcctgaaaagcat-cggcggagtcgtgttg-gccccaagcgtagtaa---ttt
ttctcgcttcaggtggttccagcgctggcgtccagccgctaaaccccctattcttt-agt
gg--ttgacctcgg
>Eutypa_maura_AJ302454 610 bp 
gggatcattacagagtta-tc-t------aactc-ccaaacccatgtg-aacttacc--t
acgttgcctcggcggggaa--------------------------gcctacccgg----t
aactaccctgta----cttacccggga-gcgagctaccctgtagcccgctgca------g
gcctacccgccggtggactgtt-aaactctgg----atatagt--ggaacttctgat-gt
tttatacttaataagttaaaactttcaacaacggatctcttggttctggcatcgatgaag
aacgcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaatcatcgaatcttt
gaacgcacattgcgcccattagtattctagtgggcatgcctgttcgagcgtcatttcaa-
-ccctcaagcccca----gcggcttggtgttgggagtttat----ctgc-----------
ggataattcctgaaaagcat-cggcggagccgtgctg-gccccaagcgtagtaa--tctg
ctctcgcttcaggtg--ctcagcgccggcgcctagccgctaaaccccctaattttctagt
gg--ttgacctcgg
>Eutypella_alsophila_AJ402367 610 bp 
gggatcattaatgagttt-tc-t------aaactccaaaccctttgagaaccttacc---
tagttgcctcggcgg------------------------------acttgccctgggacg
acctaccctgcagcgagttaccctgta-acgagttgccctgtagggacttgccc--tgta
gcctgcccgccggcggccaacctaaactctgt--ttttatcgt--ggcacttctgagga-
-ttattctaaatgaattaaaactttcaacaacggatctcttggttctggcatcgatgaag
aacgcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaatcatcgaatcttt
gaacgcacattgcgcccattagtattctagtgggcatgcctgttcgagcgtcatttcaa-
-ctatcaagccctg----tttgcttggcgttgggagacttg----tag---gccc-ggcc
tgcaagctcctgaaatagat-cggcggagtcgtggcg-accctcagcgtagtaa---tct
ttctcgcattagg---tgtcggcgccggcgtccggccgttaaaccccctatttat--ttt
agtcttgacctcgg
>Eutypella_caricae_AJ302460 610 bp 
gggatcattacagagtta-tc-t------aact--cccaacccatgtg-aacttacc--t
ttgttgcctcggcggggga--------------------------gcctacccgg----t
acctaccctgta----gttacccggga-gcgagctaccctgtagcccgctgct------g
gccgacccgccggtggacagta-aaactcttg---tttttagt--gaattatctgag-tg
tttatacttaataagttaaaactttcaacaacggatctcttggttctggcatcgatgaag
aacgcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaatcatcgaatcttt
gaacgcacattgcgcccattagtattctagtgggcatgcctgttcgagcgtcatttcaa-
-ccctcaagcccca----gttgcttggtgttgggagcttgc----ccct-----------
acgcaactcctgaaagctat-tggcggagccgcattg-gccctaagcgtagtaa--tttt
tcctcgcttcaggtg-tcccggtgctggcgtcctgccgtaaaacccccaattttac-aat
gg--ttgacctcgg
>Eutypella_cerviculata_AJ302461 610 bp 
gggatcattacagagtta-tttt------aactcctaaaccctatgtg-aacctacc--t
atgttgcctcggcggggaa--------------------------gcttaccctg----t
acctactctgta----ggtactcggt--gcgaactaccctgtagctagctgct------a
gctaacccgccgatggaccatttcaactcttg-ttttttctgt--ggcacatctgaactg
tttatacttaataagttaaaactttcaacaacggatctcttggttctggcatcgatgaag
aacgcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaatcatcgaatcttt
gaacgcacattgcgcccattagtattctagtgggcatgcctgttcgagcgtcatttcga-
-ccatcaagcttta----tttgcttggagttgggagtttgc----ctt------------
acgcaattccttaaatctat-tggcggagttgcaata-accctaagcgtagtaa--ttat
tcctcgctttaggtg-tgttagcgctgacgtttagccgttaaaccccctatattta-cgt
aggtttgacctcgg
>Eutypella_cerviculata_AJ302468 610 bp 
gggatcattacagagtta-tttt------aact--ccaaacctatgtg-aacttatt--t
ttgttgcctcggcgaggga--------------------------acttacctgg----t
acttaccctgta----agaactcaggaggcgagctaccctgtagcatgccgct------g
gcaaactcgccgaaggactattcgaattcttg----ttttagt--ggcacatctgaactg
tttatacttaataagttaaaactttcaacaacggatctcttggttctggcatcgatgaag
aacgcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaatcatcgaatcttt
gaacgcacattgcgcccattagtattctagtgggcatgcctgttcgagcgtcatttcga-
-ccatcaagcttta----tctgcttggagttgggaatttac----tcat-----------
aagtaattccttaaatctat-cggcggagttgcgata-atcccaagcgtagtaa--ttat
ttctcgctttaggtg-tgttagcgctgacatttagccgttaaaccctttatattta-cgt
aggtttgacctcgg
>Eutypella_kochiana_AJ302462 610 bp 
gggatcattacagagtta-tc-c------aactccgaaaccctttgag-aacttacc--t
tggttgcctcggcgggacg--------------------------acctaccctggaagg
acctaccctgtagcgcgctaccctgta-gcaacctaccctgtaggccccgtcccggggcg
gcgcgcccgccgacggccagtcgaaactctgt--ttataccgt--ggcacttctgaggat
gttatacttaataagttaaaactttcaacaacggatctcttggttctggcatcgatgaag
aacgcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaatcatcgaatcttt
gaacgcacattgcgcccactagtattctagtgggcatgcctgttcgagcgtcatttaaaa
cccatcaagccctattttgttgcttggcgttgggagatttc----cgggccgccg-cgcc
ggggaactcctcaaatctat-cggcggagtcgtggcg-accccaagcgtagtaa---ttc
ttctcgcctgagg---tgtcggcgccggcgtcctgccgctaaaccccctatatttt-taa
agtcttgacctcgg
>Eutypella_leprosa_AJ302463 610 bp 
gggatcattaaagagtag-tttttacaacaact--ccaaacccatgtg-aacttacc--t
atgttgcctcggcggggaa--------------------------gcctaccctg----t
acctaccctgta----gttaccctgta--------------------------------g
gtctacccgccagaggacttct-aaactctgt---ttttatat--gaaacttctgag-tg
tttaaacttaat-agttaaaactttcaacaacggatctcttggttctggcatcgatgaag
aacgcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaatcatcgaatcttt
gaacgcacattgcgcccattagtattctagtgggcatgcctgttcgagcgtcatttcaa-
-ccatcaagcccta----tttgcttggcgttgggagcttac----cctgcact---tgcg
ggacaactccttaaatatat-tggcggagtcgcgaag-accccaagcgtagtaa-ttttt
ttctcgctttagg---tgtcgacgctggcatccagccactaaacccccaattttg----t
aggtttgacctcgg
>Eutypella_prunastri_AJ302464 610 bp 
gggatcattatagagtta-tc-t------aactc-ccaaacccatgtg-aacttacc--t
atgttgcctcggcggggaa--------------------------gcctacccgg----t
acctaccctgta----gttacccggga-gcgagctaccctgtagcccgctgct------g
gcctacccgccggtggacagtt-aaactcttg----atatagt--ggaacttctgat-at
tttatacttaataagttaaaactttcaacaacggatctcttggttctggcatcgatgaag
aacgcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaatcatcgaatcttt
gaacgcacattgcgcccattagtattctagtgggcatgcctgttcgagcgtcatttcaa-
-ccctcaagcccta----gcggtttggtgttgggagtttat----ctac-----------
ggataattcctgaaaagcat-cggcggagccgtgctg-gccccaagcgtagtaa--tttt
ttctcgcttcaggtg--tccggcgctggttttcagccgctaaaccccccaattttt-aat
gg--ttgacctcgg
>Eutypella_scoparia_AJ302465 610 bp 
gggatcattaatgagttt-tc-t------aaactccaaaccct-tgag-aacatacc---
tagttgcctcggcgg------------------------------acttgccctgggacg
acctaccctgcagcgagttaccctgta-acgagttgccctgtagggacctgccc--tgta
gcctgctcgccggcggccaacctaaactctgt---tttattgt--ggcacttctgagga-
-ttattctaaatgaattaaaactttcaacaacggatctcttggttctggcatcgatgaag
aacgcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaatcatcgaatcttt
gaacgcacattgcgcccattagtattctagtgggcatgcctgttcgagcgtcatttcaa-
-ccatcaagcccta----tttgcttggcgttgggagacttg----tag---gtct-ggcc
tgcaagctcctgaaatagat-cggcggagtcgtggcg-accctcagcgtagtaa---ttc
ttctcgctttagg---tgtcggcgctggcgtttagccgttaaaccccctatttct--ttt
agtcttgacctcgg
>Eutypella_scoparia_DFMAL100 610 bp 
gggatcattaatgagttt-tc-t------aaactccaaaccct-tgag-aacatacc---
tagttgcctcggcgg------------------------------acttgccctgggacg
acctaccctgcagcgagttaccctgta-acgagttgccctgtagggacctgccc--tgta
gcctgctcgccggcggccaacctaaactctgt---tttattgt--ggcacttctgagga-
-ttattctaaatgaattaaaactttcaacaacggatctcttggttctggcatcgatgaag
aacgcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaatcatcgaatcttt
gaacgcacattgcgcccattagtattctagtgggcatgcctgttcgagcgtcatttcaa-
-ccatcaagcccta----tttgcttggcgttgggagacttg----tag---gtct-ggcc
tgcaagctcctgaaatagat-cggcggagtcgtggcg-accctcagcgtagtaa---ttc
ttctcgctttagg---tgtcggcgctggcgtttagccgttaaaccccctatttct--ttt
agtcttgacctcgg
>Eutypella_sp_DNEG200 610 bp 
gggatcattaaagagtag-ttattacaacaact--ccaaacccatgtg-aacttacc--t
atgttgcctcggcggggga--------------------------acctacccgg----t
acttaccctgta----g-------------------------------------------
-gcgacccgccgatggaccatc-aaactctgt---ttat-tat--gtaacttctgag-tg
tttaaacttaataagttaaaactttcaacaacggatctcttggttctggcatcgatgaag
aacgcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaatcatcgaatcttt
gaacgcacattgcgcccattagtattctagtgggcatgcctgttcgagcgtcatttcaa-
-ccatcaagcccta----tttgcttggcgttgggagcttaa----cctac-cc---tgta
ggataactcctcaaatatat-tggcggagtcgcgaag-accccaagcgtagtaa--tttt
ttctcgcttcaggtg-tgtcggcgctggcatccagccactaaacccctaattttt----t
agtcttgacctcgg
>Eutypella_sp_UCD2336Co 610 bp 
gggatcattaatgagttt-tc-t------aaactccaaaccct-tgag-aacatacc---
tagttgcctcggcgg------------------------------acttgccctgggacg
acctaccctgcagcgagttaccctgta-acgagttgccctgtagagacctgccc--tgta
gcctgcccgccggcggccaacctaaactctgt---tttattgt--ggcacttctgagga-
-ttattctaaatgaattaaaactttcaacaacggatctcttggttctggcatcgatgaag
aacgcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaatcatcgaatcttt
gaacgcacattgcgcccattagtattctagtgggcatgcctgttcgagcgtcatttcaa-
-ccatcaagcccta----tttgcttggcgttgggagacttg----tag---gccc-ggcc
tgcaagctcctgaaatagat-cggcggagtcgtggcg-accctcagcgtagtaa---ttc
ttctcgctttagg---tgtcggcgctggcgtttagccgttaaaccccctatttt---ttt
agtcttgacctcgg
>Eutypella_sp_UCD2338Co 610 bp 
gggatcattaaagagtag-tttttacaacaact--ccaaacccatgtg-aacttacc--t
atgttgcctcggcggggga--------------------------acctacccgg----t
acttaccctgta----g-------------------------------------------
-gcgacccgccgatggaccatc-aaactctgt---ttat-tat--gtaacttctgag-tg
tttaaacttaataagttaaaactttcaacaacggatctcttggttctggcatcgatgaag
aacgcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaatcatcgaatcttt
gaacgcacattgcgcccattagtattctagtgggcatgcctgttcgagcgtcatttcaa-
-ccatcaagcccta----tttgcttggcgttgggagcttaa----cctac-cc---tgta
ggataactcctcaaatatat-tggcggagtcgcgaag-accccaagcgtagtaa--tttt
ttctcgcttcaggtg-tgtcggcgctggcatccagccactaaacccctaattttt----t
agtcttgacctcgg
>Eutypella_sp_UCD2342Co 610 bp 
gggatcattaaagagtagttttttacaacaact--ccaaacccatgtg-aacttacc--t
atgttgcctcggcggggag--------------------------acctacccgg----t
agttaccctgta----gttaccctgta--------------------------------g
agctacccgtcgacggaccatc-aaactctgt---ttttctat--gaaacttctgag-tg
ttttaacttaataaattaaaactttcaacaacggatctcttggttctggcatcgatgaag
aacgcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaatcatcgaatcttt
gaacgcacattgcgcccattagtattctagtgggcatgcctgttcgagcgtcatttcga-
-ccatcaagcccta----tttgcttggcgttgggagcttac----cctgcagc---tgcg
ggataactcctcaaatatat-tggcagagtcgcgaag-accctaagtgtagtaa---ttc
ttctcgcttcagcag-tgttgacgctggcatctagccactaaacccttaattttta---t
aggtttgacctcgg
>Eutypella_sp_UCD2353Co 610 bp 
gggatcattaaagagtagttttttacaacaact--ccaaacccatgtg-aacttacc--t
atgttgcctcggcggggag--------------------------acctacccgg----t
agttaccctgta----gttaccctgta--------------------------------g
agctacccgtcgacggaccatc-aaactctgt---ttttctat--gaaacttctgag-tg
ttttaacttaataaattaaaactttcaacaacggatctcttggttctggcatcgatgaag
aacgcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaatcatcgaatcttt
gaacgcacattgcgcccattagtattctagtgggcatgcctgttcgagcgtcatttcga-
-ccatcaagcccta----tttgcttggcgttgggagtttac----cctgcagc---tgcg
ggataactcctcaaatatat-tggcagagtcgcgaag-accctaagcgtagtaa---ttc
ttctcgcttcagcag-tgttaacgctggcgtctagccactaaacccctaattttta---t
aggtttgacctcgg
>Eutypella_sp_UCD3Co 610 bp 
gggatcattaaagagtag-tttttacaacaact--ccaaacccatgtg-aacttacc--t
atgttgcctcggcggggga--------------------------acctacccgg----t
acttaccctgta----g-------------------------------------------
-gcgacccgccgatggaccatc-aaactctgt---ttat-tat--gtaacttctgag-tg
tttaaacttaataagttaaaactttcaacaacggatctcttggttctggcatcgatgaag
aacgcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaatcatcgaatcttt
gaacgcacattgcgcccattagtattctagtgggcatgcctgttcgagcgtcatttcaa-
-ccatcaagcccta----tttgcttggcgttgggagcttaa----cctac-cc---tgta
ggataactcctcaaatatat-tggcggagtcgcgaag-accccaagcgtagtaa--tttt
ttctcgcttcaggtg-tgtcggcgctggcatccagccactaaacccctaattttt----t
agtcttgacctcgg
>Eutypella_sp_UCD713SJ 610 bp 
gggatcattaaagagtag-tttttacaacaact--ccaaacccatgtg-aacttacc--t
atgttgcctcggcggggaa--------------------------gcctaccctg----t
acctaccctgta-----------------------------------------------g
gcctacccgccagaggacttct-aaactctgt---ttttatat--gaaacttctgag-tg
tttaaacttaat-agttaaaactttcaacaacggatctcttggttctggcatcgatgaag
aacgcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaatcatcgaatcttt
gaacgcacattgcgcccattagtattctagtgggcatgcctgttcgagcgtcatttcaa-
-ccatcaagcccta----tttgcttggcgttgggagcttac----cctgcact---tgcg
ggataactccttaaatatat-tggcggagtcgcggag-accccaagcgtagtaa--tttt
ttctcgctttagg---tgtcgacgctggcatccagccactaaacccccaatttta----t
aggtttgacctcgg
>Eutypella_vitis_AJ302466 610 bp 
gggatcattaaagagtag-tttttacaacaact--ccaaacccatgtg-aacttacc--t
atgttgcctcggcggggaa--------------------------a-ctacccgg----t
agctaccctgta----gctaccctgta---------------------------a----g
gaatactcgtcgacggaccatt-aaactctgt---ttttctat--gaaacttctgag-tg
ttttaacttaataaattaaaactttcaacaacggatctcttggttctggcatcgatgaag
aacgcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaatcatcgaatcttt
gaacgcacattgcgcccattagtattctagtgggcatgcctgttcgagcgtcatttcga-
-ccatcaagcccta----tttgcttggcgttgggagcttac----cctgcagt---tgcg
ggataactcctcaaatatat-tggcggagtcgcggag-accctaagcgtagtaa---ttc
ttctcgctttagtag-tgttaacgctggcatctggccactaaacccctaattttta---t
aggtttgacctcgg
>Eutypella_vitis_AY462566 610 bp 
gggatcattaaagagtag-tttttacaacaact--ccaaacccatgtg-aacttacc--t
atgttgcctcggcggggaa--------------------------a-ctacccgg----t
agctaccctgta----gttaccctgta---------------------------a----g
gactactcgtcgacggaccatt-aaactctgt---ttttctat--gaaacttctgag-tg
ttttaacttaataaattaaaactttcaacaacggatctcttggttctggcatcgatgaag
aacgcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaatcatcgaatcttt
gaacgcacattgcgcccattagtattctagtgggcatgcctgttcgagcgtcatttcga-
-ccatcaagcccta----tttgcttggcgttgggagcttac----cctgcagt---tgcg
ggataactcctcaaatatat-tggcggagtcgcggag-accctaagcgtagtaa---ttc
ttctcgctttagtag-tgtcaacgctggcatctggccactaaacccctaattttta---t
aggtttgacctcgg
>Eutypella_vitis_AY462568 610 bp 
gggatcattaaagagtag-tttttacaacaact--ccaaacccatgtg-aacttacc--t
atgttgcctcggcggggaa--------------------------a-ctacccgg----t
agctaccctgta----gctaccctgta---------------------------a----g
gactactcgtcgacggaccatt-aaactctgt---ttttctat--gaaacttctgag-tg
ttttaacttaataaattaaaactttcaacaacggatctcttggttctggcatcgatgaag
aacgcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaatcatcgaatcttt
gaacgcacattgcgcccattagtattctagtgggcatgcctgttcgagcgtcatttcga-
-ccatcaagcccta----tttgcttggcgttgggagcttac----cctgcagt---tgcg
ggataactcctcaaatatat-tggcggagtcgcggag-accctaagcgtagtaa---ttc
ttctcgctttagtag-tgtcaacgctggcatctggccactaaacccctaattttta---t
aggtttgacctcgg
>Libertella_sp_DQ286281 610 bp 
-ggatcattaaagagtag-ttattacaacaact--ccaaacccatgtg-aacttacc--t
atgttgcctcggcggggga--------------------------acctacccgg----t
acttaccctgta----g-------------------------------------------
-gcgacccgccgatggaccatc-aaactctgt---ttat-tat--gtaacttctgag-tg
tttaaacttaataagttaaaactttcaacaacggatctcttggttctggcatcgatgaag
aacgcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaatcatcgaatcttt
gaacgcacattgcgcccattagtattctagtgggcatgcctgttcgagcgtcatttcaa-
-ccatcaagcccta----tttgcttggcgttgggagcttaa----cctac-cc---tgta
ggataactcctcaaatatat-tggcggagtcgcgaag-accccaagcgtagtaa--tttt
ttctcgcttcaggtg-tgtcggcgctggcattcagccactaaacccctaattttt----t
agtcttgacctcgg
>Whalleya_microplaca_AJ390420 610 bp 
gggatcattaatgagtta-aa-a------aactcctaaacccactgtg-aacataccatt
ttgttgcctcggcaggttgtgtttgccctgtagctgctaccctggacctaccctg----g
acctaccctgta----gctacctggta-acacgtt------------------------t
aacggcctgccggtggtcttct-aaactcttg---ctatatattgcgaatttctgaacaa
gtaaaacttaataagttaaaactttcaacaacggatctcttggttctggcatcgatgaag
aacgcagcgaaatgcgataagtaatgtgaattgcagaattcagtgaatcatcgaatcttt
gaacgcacattgcgcctactagtattctagtgggcatgcctgttcgagcgtcatttcga-
-cccttaagcctct----gttgcttagtgttgggagcctac----ggt--------tata
gcgtagctccttaaagttagttggcggagttagggtacactctcagcgtagtaaacattt
ttctcgctgttgtagttgccttagctg-----ttgccattaaacctgtctattatttagt
aaggttgacctc--
