>Callicarpa_giraldii 676 bp 
tcgagacccgcaaagtagaccgcgaacacgtg-tttaaccaca--ttgggcccgcggcgc
ggggggaagcctcccgtcgcgatcccatccccgccg----gcgtgcgcgagagc-gttcc
gtcgtgcgggc-taacgaacccc-ggcgcggcatgcgccaaggaaaat-gaaa-----cg
tagcgtccgcct--cccgacgccccgttc-gcggggcgcgcgg-ggggacgggacgtcta
t---cgaatgtcaaaacgactctcggcaacggatatctcggctctcgcatcgatgaagaa
cgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtgaaccatcgagtctttga
acgcaagttgcgcccgaagccattaggccgagggcacgtctgcctgggcgtcacgcatcg
cgtcgcc-cccc-t-ccccgcgc--acc-gcg---ctcgcga--------ggggggcgga
gattggccccccgtgcgcgcttccgtcgcgtgcggtcggcccaaatgcgatccctcggcg
acgcacgtcacgactagtggtggttg-aacaacgctcaac--tctcgtgctgtcgtgcgg
--caccgcgtcgtcc-gttcgggca------tcaaca-acgacccaa-------------
-------------acttt--cgacc
>Clinopodium_tomentosum 679 bp 
------cctgcaaagcagaccgcgaacacgta--ctaacgccg---cgggtgcggcgc--
-gggggcaaccccctgccgtgtcccgtctcctgccg----gcgtgctccctcgg-gtcac
gctgtgcgggc-taacgaacccc-ggcgcggaatgcgccaaggaaaac-cgaa-----cg
aagcgtccgccc---ctggcatcccgttc-gcggagcgtgccg-cgggatcgggcgtcta
t---caaatgtcaaaacgactctcggcaacggatatctcggctctcgcatcgatgaagaa
cgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtgaaccatcgagtctttga
acgcaagttgcgcccgaagccattaggccgagggcacgtctgcctgggcgtcacgcatcg
cgtcgcc-ccccac-ccccgcgc--gca-tcg---ccgggcg------gttgggggcgga
cactggcctcccgtgcg-----cctcggcgtgcggccggcccaaatgagatccccgggcg
actggcgtcacgacaagtggtggttg-aacatctc---aa--tctctctcgtggtcgtgc
--cgccgtgtcgtcccgtacgggaa------tcgaga-atgacccaacggtg-cacggcg
cgaacagcgtcycacctc--cgacc
>Coleus_xanthanthus 676 bp 
tcgaaacctgcaaagcagaccgcggac-cgtg-tttaacgccgaccc-------------
----------------------------ccccgccgggacgcgcgccccagtgc-gcccc
cccgcgcgggc-taacaaacccc-ggcgcagtacgcgccaaggaaaac-agaaaaggatg
cagcgccgccgc---ggcgcgccccgtccggcgggacgcgcgc-cgtcgtccggcgtctg
tct-tgaaagtcgaaacgactctcggcaacggatatctcggctctcgcatcgatgaagaa
cgtagtgaaatgcgatacttggtgtgaattgcagaatcccgtgaaccatcgagtctttga
acgcaagttgcgcccgaagccattaggccgagggcacgtctgcctgggcgtcacgcatcg
cgtcgcc-cccc---gcccgcat--------------cggga--------cgggggcgga
cactggcctcccgtgcg-----ccccggcgcgcggccggcccaaatgcgatcccccggcg
acccgcgtcgcggcaagtggtggttg-agcacctc---aa------tcgatccgccgcga
--ccccgggccgtcc-gcacgggcgt-----cgacca-ccaaccctacggca-cgcgagt
gcctc---------------cgacc
>Collinsonia_canadensis 676 bp 
tcgaaacctgcaaagcagaccgtgaacacgtg-tttaacatca--ccgggcacggtgt-g
gggag-----actcacgccgtgtaccacccccgccg--gtgcgcgccctcgggc-gtcga
atcgtgcgggc-taacgaacccc-ggcgcggcatgcgccaaggaaaac-aaaa-----tt
tagcgtctgccc---tccgcatcccgttc-gcggggtgtgcgg-tgggagtggacgtcta
t---cgaatgtcataacgactctcggcaacggatatctcggctctcgcatcgatgaagaa
cgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtgaaccatcgagtctttga
acgcaagttgcgcccgaagccattaggccgagggcacgtctgcctgggcgtcacgcatcg
cgtcgcc-cctct--ccccgcgc--cga-gcg---ctcgtga--------agggggcgga
tattggcctcccgtgcg-----ccccggcgtgcggctggcccaaatgagatccctcggcg
actcatgtcgcgactggtggtggttg-aataactc---aa--tctcgcgtcttgtcgtgc
--tactgcgtcgttc-gtacgggcag-----cgaata-atgacccaacggtg-ctcgtgt
gttacagcaccgcacctt--cgacc
>Elsholtzia_ciliata 676 bp 
tcgaaacctgcaaagtagaccgcgaacatgtg-tttaacatca--tcaggcgcggcgtgg
gggaa-----actcccgtcgcgtcctgcccctgccg--gtgtacgctctcgggc-gctgc
atcgtgcgggc-taacgaacccc-ggcgcggcacgcgccaaggaaaac-gaaa-----tt
tagcatccgccc---tccgcatcccgttc-gcggggcgtgcgg--gggagcggctgtcta
t---cgaacgtcataacgactctcggcaacggatatctcggctctcgcatcgatgaagaa
cgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtgaaccatcgagtctttga
acgcaagttgcgcccgaagccgtcaggccgagggcacgtctgcatgggcgtcacgcatcg
cgtcgcc-cccct--ccccgccc--tca-gtg---ctcgtga--------gtggggtgga
tattggcctcccgtgcg-----cttcagcgtgcggctggcccaaatgtgatccctcggcg
actcgcatcgcgactagtggtggttg-aacagctc---aa--tctcgcgtcgtgtcgtgt
gttgcgttgttgtcc-gcgcgggcat-----cggatg-caaacccaacggtg-gcggtgc
----tcgcaccgcgcctt--cgacc
>Eriope_latifolia 676 bp 
tcgaaacctgcaaagcagaccgcgaacacgtg-taaaacgcat-----------------
--------------------------ctccccgccgtcgcgccccg---------cgcgc
gtcgtgcgggc-taacgaacccc-ggcgcggcacgcgccaaggaaaac-cgaa-----cc
aggcgccgtcct--ccccgcatcccgtcc-gcgggcagtgcgg-ggggcgtcgggctcca
tt--gaaaagtcaaaacgactctcggcaacggatatctcggctctcgcatcgatgaagaa
cgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtgaaccatcgagtctttga
acgcaagttgcgcccgaagccatcaggccgagggcacgtctgcctgggcgtcacgcatcg
--tcgcc-cccct--ccccgcgc--tcc-gtg---cggg---------acggggggcgga
tattggcctcccgtgcg-----ccccggcgcgcggttggcccaaatgcgatccccatgcg
gcccgagtcgcgacaagtggtggttg-aaatcctc---aa--tctctcgtctcgtcgtgc
--atccgggccgtgc-gtgcgggcat-----cggacatacgaccctacggcg-cggaggc
--------cccgcgccct--cgatc
>Hanceola_exserta 676 bp 
tcgaaacctgcgaggcagaccgcgaacacgtg-tttaacgcca-----------------
--------------------------tcccccgccgccgcgcgcgcacccgtgc-gccgc
gtcgcgcgggc-taacgaacccc-ggcgcggaacgcgccaaggaaaac-agaa-----tg
tagcgccggccc---ccca-----------gcaccccgtgcgg-ggggagcgggcgtcta
t---cgaatgtcaaaacgactctcggcaacggatatctcggctctcgcatcgatgaagaa
cgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtgaaccatcgagtctttga
acgcaagttgcgcccgaagccgtcaggccgagggcacgtctgcctgggcgtcacgcatcg
cgtcgcc-ccccct-acccgcgc--acc-gcg---ctcgtgg-------tggggggcgga
tattggcctcccgtgcg-----ccccggcgcgcggccggcccaaattcgatccctcggcg
accggcgtcgcgacaagtggtggttg-aactcctc---aa--tctcgcgcctcgtcgtgc
--tgccggatcgtcc-gtacgggctt-----cgaaca-acgacccaacggcg-cggcctt
----tgcggctgcgcctt--cgacc
>Hanceola_sinensis_1 676 bp 
tcgaaacctgcgaggcagaccgcgaacacgtg-tttaacgcca-----------------
--------------------------tcccccgccgccgcgcgcgcccccgtgc-gccgc
gtcgtgcgggc-taacgaacccc-ggcgcggaacgcgccaaggaaaac-agaa-----tg
tagcgccggccc---cccgcatcccgtcc-gcggtgcgtgcgg-ggggatccggcgtcta
t---cgaatgtcaaaacgactctcggcaacggatatctcggctctcgcatcgatgaagaa
cgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtgaaccatcgagtctttga
acgcaagttgcgcccgaagccgtcaggccgagggcacgtctgcctgggcgtcacgcatcg
cgtcgcc-ccccct-ccccgcgc--tcc-gcg---ctcgtgg------tgggggggcgga
tattggcctcccgtgcg-----ccccggcgcgcggccggcccaaatgcgatcccccggcg
acccgcgtcgcgacaagtggtggttg-aactcctc---aa--tctcgcgcctcgtcgtga
--tgccgggtcgtcc-gtgcgggctt-----cgagca-acgacccaacggcg-cggccct
---ctgcggccgcgcctt--cgacc
>Hanceola_sinensis_2 676 bp 
tcgagacctgcgaggcagaccgcgaacacgtg-tttaacgcca-----------------
--------------------------tcccccgccgccgcgcgcgc-cccgtgc-gccgc
gtcgtgcgggc-taacgaacccc-ggcgcggaacgcgccaaggaaaac--gaa-----tg
tagcgccgg-cc---cccgcatcccgtcc-gcggtgcgtgcgg-ggggatccggcgtcta
t---cgaatgtcaaaacgactctcggcaacggatatctcggctctcgcatcgatgaagaa
cgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtgaaccatcgagtctttga
acgcaagttgcgcccgaagccgtcaggccgagggcacgtctgcctgggcgtcacgcatcg
cgtcgcc-ccccct-ccccgcgc--gcc-gcg---ctcgtgg------tgggggggcgga
tattggcctcccgtgcg-----ccccggcgcgcggccggcccaaatgcgatcccccggcg
acccgcgtcgcgacaagtggtggttg-aactcctc---aa--tctcgcg-ctcgtcgtga
--tgccgggtcgtcc-gtgcgggctt-----cgagc--acgacccaacggcg-cggccct
---ctgcggccgcgcctt--cgacc
>Hanceola_sinensis_3 676 bp 
tcg-aacctgcgaggcagaccgcgaacacgtg-tttaacgcca-----------------
--------------------------tcccccgccgccgcgcgcgcacccgtgc-gccgc
gtcgtgcgggc-taacgaacccc-ggcgcggaacgcgccaaggaaaac--gaa-----tg
tagcgccggccc---cccgcatcccgtcc-gcgg-gcgtgcgg-ggggatccggcgtcta
t---cgaatgtcaaaacgactctcggcaacggatatctcggctctcgcatcgatgaagaa
cgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtgaaccatcgagtctttga
acgcaagttgcgcccgaagccgtcaggccgagggcacgtctgcctgggcgtcacgcatcg
cgtcgcc-ccccct-ccccgcgc--gcc-gcg---ctcgtgg------tgggggggcgga
tattggcctcccgtgcg-----ccccggcgcgcggccggcccaaatgcgatcccccggcg
acccgcgtcgcgacaagtggtggttg-aactcctc---aa--tctcgcg-ctcgtcgtga
--tgccgggtcgtcc-gtgcgggctt-----cgagc--acgacccaacggcg-cggccct
---ctgcggccgcgcctt--cgacc
>Hyptis_alata 676 bp 
tcgaaacctgcaaagcagaccgcgaacacgta-cctaaagcat-----------------
--------------------------ctcctcgccggcgcactcg------------tgt
gtcgtgcgggc-taacgaacccc-ggcgcggcatgcgccaaggaatac-cgaa-----cg
tggcattggccc--ccaggcatcccgttc-gcgggtactgccg-gggaagtcgatgtcta
t---cgaatgtcaaaacgactctcggcaacggatatctcggctctcgcatcgatgaagaa
cgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtgaaccatcgagtctttga
acgcaagttgcgcccaaagccattaggccgagggcacgcctgcctgggcgtcacgcatcg
cgtcgcc-ccca---tcccacgc-------tg---cgtggaa--------tgggggtgga
tactggcctcccgtgcg-----cccgtgcgtgcggccggcccaaatgcgatcccccggcg
acccgtgtcgcgacaagtggtggttg-aactcctc---aa--tctcaagtctcgtcgtgc
--attcgaactgtcc-gtgcgggcat-----cattta-gcgacccaacggtg-cggtggc
--cctgccgccgcactct--cgacc
>Hyptis_brevipes 676 bp 
tcgaaacctgcaaagcagaccgcgaacacgtg-actaacgcat-----------------
--------------------------ctccccgccggcgcacccg------------tgc
gtcgtgcgggc-taacgaacccc-ggcgcggcatgcgccaaggaaaac-cgaa-----cg
tggcatcggccc---cccgcatcccgtcc-gcgggcagtgcag-gggcagtcgacgtcta
t---cgaatgtcaaaacgactctcggcaacggatatctcggctctcgcatcgatgaagaa
cgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtgaaccatcgagtctttga
acgcaagttgcgcccgaagccattaggccgagggcacgtctgcctgggcgtcacgcatcg
cgtcgcc-ccct---ccccgcgc-------tc---cgcggga------acggggggcgga
tattggcctcccgtgag-----ccacggcgcgcggttggcccaaatgcgatcccccggcg
actcgcgtcgcgacaagtggtggttg-aactcctc---aa--tctctcgtctcgtcgcgc
--attcgggttgtcc-gtgcgggcat-----cgaaca-tcgaccctacggcg-cggtggc
--cccgctgccgcgctct--cgacc
>Isodon_adenanthus 676 bp 
tcgaaacctgcaaagcagaccgcgaacacgtt-tctaacgcca-----------------
--------------------------tcccccgccgcagcgcgcgcactcgtgc-cgcac
tgcgtgcgggc-taacgaacccc-ggcgcggaacgcgccaaggaaaacttaaa-----tt
tagcgtcggtcccgctccgcatcccgttc-gcgggtcgtgcggtgcggaacggacgtcta
t---cgaatgtcataacgactctcggcaacggatatctcggctctcgcatcgatgaagaa
cgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtgaaccatcgagtctttga
acgcaagttgcgcccgaagccattaggccgagggcacgtctgcctgggcgtcacgcatcg
cgtcgct-cccc----c----ca--ccc-acg---ttggcga--------ggggggcgga
tattggcctcccgtgtg-----cctcggcgtgcggccggcccaaatgagatcccccggcg
actcgcgtcgcgacaagtggtggttg-aacatctc---aa--tctcgcgtctcgtcgtg-
---gccgagccgtcc-gtggtgatc------cgaacg-atgacccaacggag-ctt----
-----------gctcctt--cgact
>Isodon_adenolomus 676 bp 
tcgaaacctgcaaagcagaccgcgaacacgtt-tctaacgcca-----------------
--------------------------tcccccgccgcagcgcgcgcactcgtgc-cgcgc
tgcgtgcgggc-taacgaacccc-ggcgcggaacgcgccaaggaaaacttaaa-----tt
tagcgtcggtcccgccccgcatcccgttc-gcgggccgtgcggtgcggaacgggcgtcta
t---cgaatgtcataacgactctcggcaacggatatctcggctctcgcatcgatgaagaa
cgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtgaaccatcgagtctttga
acgcaagttgcgcccgaagccattaggccgagggcacgtctgcctgggcgtcacgcatcg
cgtcgct-cccc----c----cc--acc-act---ctggcga-------gggggggcgga
tattggcctcccgtgcg-----cctcggcgtgcggccggcccaaatgcgatcccccggcg
actcgcgtcgcgacaagtggtggttg-aacatctc---aa--tctcgcgtctcgtcgtgc
--cgccgagccgtcc-gtggtgatc------cgaacg-atgacccaacggag-ctt----
-----------gctcctt--cgacc
>Isodon_amethystoides 676 bp 
tcgaaacctgcaaagcagaccgcgaacacgtt-tctaacgcca-----------------
--------------------------tcccccgccgcagcgcgcgcactcgtgc-cgcgc
ggcgtgcgggc-taacgaacccc-ggcgcggaacgcgccaaggaaaacttaaa-----tt
tagcgtcggtcccgccccgcatcccgttc-gcgggccgtgcggtgcggaacgggcgtcta
t---agaatgtcataacgactctcggcaacggatatctcggctctcgcatcgatgaagaa
cgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtgaaccatcgagtctttga
acgcaagttgcgcccgaagccattaggccgagggcacgtctgcctgggcgtcacgcatcg
cgtcgct-cccc----c----cc--acc-act---ctggcga--------ggggggcgga
tattggcctcccgtg-g-----cctcggcgtgcggccggcccaaatgcgatcccccggcg
actcgcgtcgcgacaagtggtggttg-aacatctc---aa--tctcgcgtctcgtcgtgc
--cgccgagccgtcc-gtggtgatc------cgaacg-atgacccaacggag-ctt----
-----------gctcctt--cgacc
>Isodon_bulleyanus 676 bp 
tcgaaacctgcaaagcagactgcgaacacgtt-tctaacgcca-----------------
--------------------------tcccccgccgcagcgcgcgcactcgtgc-cgcgc
ggcgtgcgggc-taacgaacccc-ggcgcggaacgcgccaaggaaaacttaaa-----tt
tagcgtcggtcccgccccgcatcccgttc-gcgggcattgcggtgcggaacgggcgtcta
t---tgaatgtcataacgactctcggcaacggatatctcggctctcgcatcgatgaagaa
cgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtgaaccatcgagtctttga
acgcaagttgcgcccgaagccattaggccgagggcacgtctgcctgggcgtcacgcatcg
cgtcgct-cccc----c----cc--acc-accacgctggcga-------gggggggcgga
tattggcctcccgtgcg-----cctcggcgtgcggccggcccaaatgcgatcccccggcg
actcgcgtcgcgacaagtggtggttg-aacatctc---aa--tctcgcgtctcgtcgtgc
--cgccgagccgtcc-gtggcgatc------cgaacg-atgacccaacggag-ctt----
-----------gctcctt--cgacc
>Isodon_calcicolus 676 bp 
tcgaaacctgcaaagcagactgcgaacacgtt-tctaacgcca-----------------
--------------------------tcccccgccgcagcgcgcgcactcgtgc-cgcgc
ggcgtgcgggc-taacgaacccc-ggcgcggaacgcgccaaggaaaacttaaa-----tt
tagcgtcggtcccgccccgcatcccgttc-gcgggcattgcggtgcggaacgggcgtcta
t---tgaatgtcataacgactctcggcaacggatatctcggctctcgcatcgatgaagaa
cgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtgaaccatcgagtctttga
acgcaagttgcgcccgaagccattaggccgagggcacgtctgcctgggcgtcacgcatcg
cgtcgct-cccc----c----cc--acc-accacgctggcga-------gggggggcgga
tattggcctcccgtgcg-----cctcggcgtgcggccggcccaaatgcgatcccccggcg
actcgcgtcgcgacaagtggtggttg-aacatctc---aa--tctcgcgtctcgtcgtgc
--cgccgagccgtcc-gtggcgatc------cgaacg-atgacccaacggag-ctt----
-----------gctcctt--cgacc
>Isodon_coetsa 676 bp 
tcgaaacctgcaaagtagaccgcgaacatgtt-tctaatgcca-----------------
--------------------------tcccctgccgcagcgcgtgctctcgtgc-cgcgc
ggcgtgcgggc-taacgaacccc-ggcgcggaacgcgccaaggaaaacttaaa-----tt
tagcgtcggtcccaccccgcatcccgttc-gcgggccgtgcggtgtggaa-gggcgtcta
t---cgaatgtcataacgactctcggcaacggatatctcggctctcgcatcgatgaagaa
cgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtgaaccatcgagtctttga
acgcaagttgcgcccgaagccattaggccgagggcacgtctgcctgggcgtcacgcatcg
cgtcgct-cccc---cc----cc--acc-acg---ctggcga--------ggggggcgga
tattggcctcccgtgcg-----cctcggcgtgcggctggcccaaatgcgatcccccggcg
actcgcgtcgcgacaagtggtggttg-aacatctc---aa--tctcgcgtctcgtcgtgc
----gcgagccgtcc-gtggtgat-------ccaacg-atgacccaacggag-ctt----
-----------gctcctt--cgacc
>Isodon_eriocalyx_1 676 bp 
tcgaaacctgcaaagcagaccgagaacacgtt-tctaacgcca-----------------
--------------------------tcccccgccgcggtgcgcgcactcgtgc-cgcgc
tgcgtgcgggc-taacgaacccc-ggcgcggaaagcgccaaggaaaacttaaa-----tt
tagcgtcggtctcgccccgcatcccgttc-gcgggccgtgcggtgcggaacgggcgtcta
t---cgaatgtcataacgactctcggcaacggatatctcggctctcgcatcgatgaagaa
cgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtgaaccatcgagtctttga
acgcaagttgcgcccgaagccattaggccgagggcacgtctgcctgggcatcacgcatcg
cgtcgct-cccc----c----cc--acc-act---ctggcga-------gggggggcgga
tattggcctcccgtgca-----cctcggcgtgcggccggcccaaatgcgatcccccggcg
actcgcgtcgcgacaagtggtggttg-aacatctc---aa--tctcgcgtctcgtcgtgc
--cgccgagccgtcc-gtggtggtc------cgaacg-atgacccaacggag-ctt----
-----------gctcctt--cgacc
>Isodon_eriocalyx_2 676 bp 
tcgaaacctgcaaagcagaccgagaacacgtt-tctaacgcca-----------------
--------------------------tcccccgccgcggtgcgcgcactcgtgc-cgcgc
tgcgtgcgggc-taacgaacccc-ggcgcggaaagcgccaaggaaaacttaaa-----tt
tagcgtcggtctcgccccgcatcccgttc-gcgggccgtgcggtgcggaacgggcgtcta
t---cgaatgtcaaaacgactctcggcaacggatatctcggctctcgcatcgatgaagaa
cgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtgaaccatcgagtctttga
acgcaagttgcgcccgaagccattaggccgagggcacgtctgcctgggcgtcacgcatcg
cgtcgct-cccc----c----cc--acc-act---ctggcgaggggggggggggggcgga
tattggcctcccgtgcg-----cctcgtcgtgcggccggcccaaatgcgatcccccggcg
actcgcgtcgcgataagtggtggttg-aacatctc---aa--tcttgcgtctcgtcgtgc
--cgccgagccgtcc-gtggtgatc------cgaacg-atgacccaacggag-ctt----
-----------gctcctt--cgacc
>Isodon_eriocalyx_3 676 bp 
tcgaaacctgcaaagcagaccgagaacacgtt-tctaacgcca-----------------
--------------------------tcccccgccgcggtgcgcgcactcgtgc-cgcgc
tgcgtgcgggc-taacgaacccc-ggcgcggaaagcgccaaggaaaacttaaa-----tt
tagcgtcggtcccgccccgcatcccgttc-gcgggccgtgcggtgcggaacgggcgtcta
t---cgaatgtcataacgactctcggcaacggatatctcggctctcgcatcgatgaagaa
cgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtgaaccatcgagtctttga
acgcaagttgcgcccgaagccattaggccgagggcacgtctgcctgggcgtcacgcatcg
cgtcgct-cccc----c----cc--acc-act---ctggcga------ggggggggcgga
tattggcctcccgtgcg-----cctcggcgtgcggccggcccaaatgcgatcccccggcg
actcgcgtcgcgacaagtggtggttg-aacatctc---aa--tctcgcgtctcgtcgtgc
--cgccgagccgtcc-gtggtgatc------cgaacg-atgacccaacggag-ctt----
-----------gctcctt--cgacc
>Isodon_eriocalyx_4 676 bp 
tcgaaacctgcaaagcagaccgagaacacgtt-tctaacgcca-----------------
--------------------------tcccccgccgcgg-gcgcgcactcgtgc-cgcgc
tgcgtgcgggc-taacgaacccc-ggcgcggaaagcgccaaggaaaacttaaa-----tt
tagcgtcggt-ccgccccgcatcccgttc-gcgggccgtgcggtgcggaacgggcgtcta
t---cgaatgtcataacgactctcggcaacggatatctcggctctcgcatcgatgaagaa
cgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtgaaccatcgagtctttga
acgcaagttgcgcccgaagccattaggccgagggcacgtctgcctgggcgtcacgcatcg
cgtcgct-cccc----c----cc--acc-act---ctggcga-------gggggggcgga
tattggcctcccgtgc------cctcggcgtgcggccggcccaaatgcgatcccccggcg
actcgcgtcgcgacaagtggtggttg-aacatctc---aa--tctcgcgtctcgtcgtgc
--cgccgagccgtcc-gtggtgatc------cgaacg-atgacccaacggag-ctt----
-----------gctcctt--cgacc
>Isodon_flabelliformis 676 bp 
tcgaaacctgcaaagcagaccgcgaacacgtt-tctaacgcca-----------------
--------------------------tcccccaccgcagcgcgcgcactcgtgc-cgcgc
tgcgtgcgggc-taacgaacccc-ggcgcggaacgcgccaaggaaaacttaaa-----tt
tagcgtcggtcccgccccgcatcccgtta-gcgggccgtgcggtgcggaacgggcgtcta
t---cgaatgtcataacgactctcggcaacggatatctcggctctcgcatcgatgaagaa
cgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtgaaccatcgagtctttga
acgcaagttgcgcccgaagccattaggccgagggcacgtctgcctgggcgtcacgcatcg
cgtcgct-cccc----ccccacc--acc-atg---ctggcga-------gggggggcgga
tattggcctcccgtgcg-----cctcggtgtgcggccggcccaaatgctatccctcggcg
actcgcgtcgcgacaagtggtggttg-aacatctc---aa--tctcgcgtctcgtcgtgc
--tgccgagccgtcc-gtggtgatc------cgaacg-atgacccaacggag-ctt----
-----------gctcctt--cgacc
>Isodon_flavidus 676 bp 
tcgaaacctgcaaagcagaccgcgaacacgtt-tctaacgcca-----------------
--------------------------tcccccgccgcagcgcgcgcactcgtgc-cgcgc
tgcgtgcgggc-taacgaacccc-ggcgcggaacgcgccaaggaaaacttaaa-----tt
tagcgtcggtcccgccccgcatcccgttc-gcgggccgtgcggtgcggaacgggcgtcta
t---cgaatgtcataacgactctcggcaacggatatctcggctctcgcatcgatgaagaa
cgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtgaaccatcgagtctttga
acgcaagttgcgcccgaagccattaggccgagggcacgtctgcctgggcgtcacgcatcg
cgtcgct-cccc----c----cc--acc-act---ttggcga-------gggggggcgga
tattggcctcccgtgca-----cctcggcgtgcggccggcccaaatgcgatcccccggcg
actcgcgtcgcgacaagtggtggttg-aacatctc---aa--tctcgcgtctcgtcgtgc
--cgccgagccgtcc-gcggtgatc------cgaaca-atgacccaacggag-ctt----
-----------gctcctt--cgacc
>Isodon_flexicaulis 676 bp 
tcgaaacctgcaaagcagaccgcgaacacgtt-tctaacgcca-----------------
--------------------------tcccccgccgcagcgcgcgcactcgtgc-cgcgc
ggcgtgcgggc-taacgaacccc-ggcgcggaaagcgccaaggaaaacttaaa-----tt
tagcgtcggtcccgccccgcatcccgttc-gcgggccgtgcggtgcggaacgggcgtcta
t---cgaatgtcataacgactctcggcaacggatatctcggctctcgcatcgatgaagaa
cgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtgaaccatcgagtctttga
acgcaagttgcgcccgaagccattaggccgagggcacgtctgcctgggcgtcacgcatcg
cgtcgct-cccc----c----cc--acc-act---ctggcga-------gggggggcgga
tattggcctcccgtgcg-----cctcggcgtgcggccggcccaaatgcgatcccccggcg
actcgcgtcgcgacaagtggtggttg-aacatctc---aa--tctcgcgtctcgtcgtgc
--cgccgagccgtcc-gtggtgatc------cgaacg-atgacccaacggag-ctt----
-----------gctcctt--cgacc
>Isodon_forrestii 676 bp 
tcgaaacctgcaaagcagaccgcgaacacgtt-tctaacgcca-----------------
--------------------------tcccccgccgcagcgcgcgcactcgtgc-cgcgc
-gcgtgcgggc-taacgaacccc-ggcgcggaacgcgccaaggaaaacttaaa-----tt
tagcgtcggtcccgccccgcatcccgttc-gcgggccgtgcggtgcggaacgggcgtcta
t---cgaatgtcataacgactctcggcaacggatatctcggctctcgcatcgatgaagaa
cgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtgaaccatcgagtctttga
acgcaagttgcgcccgaagccattaggccgagggcacgtctgcctgggcgtcacgcatcg
cgtcgct-cccc----c----cc--acc-act---ctggcga-------gggggggcgga
tattggcctcccgtgcg-----cctcggcgtgcggccggcccaaatgcgatcccccggcg
actcgcgtcgcgacaagtggtggttg-aacatctc---aa--tctcgcgtctcgtcgtgc
--cgccgagccgtcc-gcggtgatc------cgaacg-atgacccaacggag-ctt----
-----------gctcctt--cgacc
>Isodon_gesneroides 676 bp 
tcgaaacctgcaaagcagaccgcgaacacgtt-tctaacgcca-----------------
--------------------------tcccccgccgcagcgcgcgcactcgtgc-cgcgc
ggcgtgcgggc-taacgaacccc-ggcgcggaacgcgccaaggaaaacttaaa-----tt
tagcgtcggtctcgccccgcatcccgttc-gcgggccgtgcggtgcggaacgggcgtcta
t---agaatgtcataacgactctcggcaacggatatctcggctctcgcatcgatgaagaa
cgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtgaaccatcgagtctttga
acgcaagttgcgcccgaagccattaggccgagggcacgtctgcctgggcgtcacgcatcg
cgtcgctccccc----c----cc--acc-act---ctggcga-------gggggggcgga
tattggcctcccgtgcg-----cctcggcgtgcggccggcccaaatgcgatcccccggcg
actcgcgtcgcgacaagtggtggttg-aacatctc---aa--tctcgcgtctcgtcgtgc
--cgccgagccgtcc-gtggtgatc------cgaacg-atgacccaacggag-ctt----
-----------gctcctt--cgacc
>Isodon_glutinosus 676 bp 
tcgaaacctgcaaagcagaccgcgaacaagtt-tctaacgcca-----------------
--------------------------tcccccgccgcagcgcgcgcactcgtgc-cgcgc
-gcgtgcgggc-taacgaacccc-ggcgcggaacgcgccaaggaaaacttaaa-----tt
tagcgtcggtcccgccccgcatcccgttc-gcgggccgtgcggtgcggaacgggcgtcta
t---cgaatgtcataacgactctcggcaacggatatctcggctctcgcatcgatgaagaa
cgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtgaaccatcgagtctttga
acgcaagttgcgcccgaagccattaggccgagggcacgtctgcctgggcgtcacgcatcg
cgtcgct-cccc----c----cc--acc-act---ctggcga------ggggggggcgga
tattggccccccgtgcg-----cctcggcgtgcggccggcccaaatgcgatcccccggcg
attcgcgtcgcgacaagtggtggttg-aacatctc---aa--tctcgcgtctcgtcgtgc
--cgccgagccgtcc-gtggtgatc------cgaacg-atgacccaacggag-ctt----
-----------gctcctt--cgacc
>Isodon_grandifolius_var_atuntz 676 bp 
tcgaaacctgcaaagcagaccgcgaacacgtt-tctaacgcca-----------------
--------------------------tcccccgccgcagcgcgcgcactcgtgc-cgctc
tgcgtgcgggc-taacgaacccc-ggcgcggaaagcgccaaggaaaacttaaa-----tt
tagcgtcggtcccgccccgcatcccgttc-gcgggccgtgcggtgcggaacgggcgtcta
t---cgaatgtcataacgactctcggcaacggatatctcggctctcgcatcgatgaagaa
cgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtgaaccatcgagtctttga
acgcaagttgcgcccgaagccattaggccgagggcacgtctgcctgggcgtcacgcatcg
cgtcgct-cccc----c----cc--acc-act---ctggcga-------gggggggcgga
tattggcctcccgtgcg-----cctcggcgtgcggccggcccaaatgcgatcccccggcg
actcgcgtcgcgacaagtggtggttg-aacatctc---aa--tctcgcgtctcgtcgtgc
--cgccgagccgtcc-gtggtgatc------cgaacg-atgacccaacggag-ctt----
-----------gctcctt--cgacc
>Isodon_hispidus_1 676 bp 
tcgaaacctgcaaagcagaccgcgaacacgtt-aacaacgccg-----------------
------------------------acccccccgccgccgcgcccgcacccgtgc-ggcgc
ggcgtgcgggc-taacgaacccc-ggcgcggcacgcgccaaggaaaacttgaa-----tt
tagcgtcggtccc-cccagcatcccgttc-gcgggccgtgcgg-ggggaacgggcgtcta
t---cgaatgtcgtaacgactctcggcaacggatatctcggctctcgcatcgatgaagaa
cgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtgaaccatcgagtctttga
acgcaagttgcgcccgaagccattaggccgagggcacgtctgcctgggcgtcacgcatcg
cgtcgcc-cccct--ccccgcgc--aag-tcg---ctcgaga--------ggggggcgga
tactggctccccgtgcg-----ccacggcgcgcggccggcccaaatgcgatcccccggcg
tcccgcgtcgcgacaagtggtggttg-aacatctc---aatccctcgcgtcctgtcgtgc
--cgctgggccgtcc-gcagggttc------cgaacg-atgacccaacggag-ctcatcg
-----------gctccct--cgacc
>Isodon_hispidus_2 676 bp 
tcgaaacctgcaaagcagaccgcgaacacgttaaacaacgcca-----------------
------------------------a-ccccccgccgccgcgcgcgcacttgtgc-gacgc
ggcgtgcgggc-taacgaacccc-ggcgcggcacgcgccaaggaaaactgaaa-----tt
tagcgtcggtccccctcagcatcccgttc-gcgggccgtgcgg-ggggaacgggcgtcta
t---cgaatgtcataacgactctcggcaacggatatctcggctctcgcatcgatgaagaa
cgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtgaaccatcgagtctttga
acgcaagttgcgcccgaagccattaggccgagggcacgtctgcctgggcgtcacgcatcg
cgtcgcc-cccct--ccccgcgc--acg-gcg---ctcgcga--------ggggggcgga
tactggctccccgtgcg-----cctcggcgcgcggccggcccaaatgcgatcccccggcg
acccgcgtcgcgacaagtggtggttg-aacatctc---aa--tctcgcgtcctgtcgtgc
--cgctgggtcgtcc-gcagggttc------cgaacg-atgacccaacggag-ctcatct
-----------gctccct--cgacc
>Isodon_irroratus 676 bp 
tcgaaacctgcaaagcagaccgcgaacacgtt-tctaacgcca-----------------
--------------------------tcccccgccgcagcgcgcgcactcgtgc-cgcgc
tgcgtgcgggc-taacgaacccc-ggcgcggaacgcgccaaggaaaacttaaa-----tt
tagcgtcggtcccgccccgcatcccgttc-gcgggccgtgcggtgcggaacgggcgtcta
t---cgaatgtcataacgactctcggcaacggatatctcggctctcgcatcgatgaagaa
cgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtgaaccatcgagtctttga
acgcaagttgcgcccgaagccattaggccgagggcacgtctgcctgggcgtcacgcatcg
cgtcgct-cccc----c----cc--acc-act---ctggcga-------gggggggcgga
tattggcctcccgtgcg-----cctcggcgtgcggccggcccaaatgcgatcccccggcg
actcgcgtcgcgacaagtggtggttg-aacatctc---aa--tctcgcgtctcgtcgtgc
--cgccgagccgtcc-gtggtgatc------cgaacg-atgacccaacggag-ctt----
-----------gctcctt--cgacc
>Isodon_japonicus 676 bp 
tcgaaacctgcaaagcagaccgcgaacacgtt-tctaacgcca-----------------
--------------------------tcccccgccgcagcgcgcgcactcgtgc-cgcgc
ggcgtgcgggc-taacgaacccc-ggcgcggaacgcgccaaggaaaacttaaa-----tt
tagcgtcggtcccgccccgcatcccgttc-gcgggccgtgcggtgcggaacgggcgtcta
t---agaatgtcataacgactctcggcaacggatatctcggctctcgcatcgatgaagaa
cgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtgaaccatcgagtctttga
acgcaagttgcgcccgaagccattaggccgagggcacgtctgcctgggcgtcacgcatcg
cgtcgct-cccc----c----cc--acc-act---ctggcga-------gggggggcgga
tattggcctcccgtgcg-----cctcggcgtgcggccggcccaaatgcgatcccccggcg
actcgcgtcgcgacaagtggtggttg-aacatctc---aa--tctcgcgtctcgtcgtgc
--cgccgagccgtct-gtggtgatc------cgaacg-atgacccaacggag-ctt----
-----------gctcctt--cgacc
>Isodon_japonicus_var_glaucocal 676 bp 
tcgaaacctgcaaagcagaccgcgaacacgtt-tctaacgcca-----------------
--------------------------tcccccgccgcagcgcgcgcactcgtgc-cgcgc
ggcgtgcgggc-taacgaacccc-ggcgcggaacgcgccaaggaaaacttaaa-----tt
tagcgtcggtcccgccccgcatcccgttc-gcgggccgtgcggtgcggaacgggcgtcta
t---agaatgtcataacgactctcggcaacggatatctcggctctcgcatcgatgaagaa
cgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtgaaccatcgagtctttga
acgcaagttgcgcccgaagccattaggccgagggcacgtctgcctgggcgtcacgcatcg
cgtcgct-cccc----c----cc--acc-act---ctggcga-------gggggggcgga
tattggcctcccgtgtg-----cctcggcgtgcggccggcccaaatgcgatcccccggcg
actcgcgtcgcgacaagtggtggttg-aacatctc---aa--tctcgcgtctcgtcgtgc
--cgccgagccgtcc-gtggtgatc------cgaacg-atgacccaacggag-ctt----
-----------gctcctt--cgacc
>Isodon_leucophyllus 676 bp 
tcgaaacctgcaaagcagaccgcgaacacgtt-tctaacgcca-----------------
--------------------------tcccccgccgcagcgcgcgcactcgtgc-cgctc
tgcgtgcgggc-taacgaacccc-ggcgcggaaagcgccaaggaaaacttaaa-----tt
tagcgtcggtcccgccccgcatcccgttc-gcgggccgtgcggtgcggaacgggcgtcta
t---cgaatgtcataacgactctcggcaacggatatctcggctctcgcatcgatgaagaa
cgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtgaaccatcgagtctttga
acgcaagttgcgcccgaagccattaggccgagggcacgtctgcctgggcgtcacgcatcg
cgtcgct-cccc----c----cc--acc-act---ctggcga-------gggggggcgga
tattggcctcccgtgcg-----cctcggcgtgcggccggcccaaatgcgatcccccggcg
actcgcgtcgcgacaagtggtggttg-aacatctc---aa--tctcgcgtctcgtcgtgc
--cgccgagccgtcc-gtggtgatc------cgaacg-atgacccaacggag-ctt----
-----------gctcctt--cgacc
>Isodon_lophanthoides 676 bp 
tcgaaacctgcaaagcagaccgcgaacacgtt-aacaacgccg-----------------
------------------------a-ccccccgccgccgcgcccgcacccgtgc-ggcgc
agcgtgcgggc-taacgaacccc-ggcgcggcacgcgccaaggaaaacttgaa-----tt
tagcgtcggtccc-cccagcatcccgttc-gcggggcgtgcgg-ggggaacgggcgtcta
t---cgaatgtcgtaacgactctcggcaacggatatctcggctctcgcatcgatgaagaa
cgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtgaaccatcgagtctttga
acgcaagttgcgcccgaagccattaggccgagggcacgtctgcctgggcgtcacgcatcg
cgtcgcc-cccct--ccccgcgc--acg-gcg---ctggcga--------ggggggcgga
tactggctccccgtgcg-----ccacggcgcgcggccggcccaaatgcgatcccccggcg
tcccgcgtcgcgacgagtggtggttg-aacatctc---aatctctcgcgtcctgtcgtgc
--cgctgggccgtcc-gcagggtgttccgaacgaacg-atgacccaacggag-ctcatcc
-----------gctccct--cgacc
>Isodon_lophanthoides_var_gerar 676 bp 
tcgaaacctgcaaagcagaccgcgaacacgtt-aacaacgccg-----------------
------------------------acccccccgccgccgcgcccgcacccgtgc-ggcgc
ggcgtgcgggc-taacgaacccc-ggcgcggcacgcgccaaggaaaacttgaa-----tt
tagcgtcggtccc-cccagcatcccgttc-gcgggccgtgcgg-ggggaacgggcgtcta
t---cgaatgtcgtaacgactctcggcaacggatatctcggctctcgcatcgatgaagaa
cgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtgaaccatcgagtctttga
acgcaagttgcgcccgaagccattaggccgagggcacgtctgcctgggcgtcacgcatcg
cgtcgcc-cccct--ccccgcgc--acg-gcg---ctggaga--------ggggggcgga
tactggctccccgtgcg-----ccacggcgcgcggccggcccaaatgcgatcccccggcg
tcccgcgtcgcgacgagtggtggttg-aacatctc---aatctctcgcgtcctgtcgtgc
--cgctgggccgtcc-gcagggttc------cgaacg-atgacccaacggag-ctcatcc
-----------gctccct--cgacc
>Isodon_lophanthoides_var_micra 676 bp 
tcgaaacctgcaaagcagaccgcgaacacgtt-aacaacgccg-----------------
------------------------a-ccccccgccgccgcgcccgcacccgtgc-ggcgc
ggcgtgcgggc-taacgaacccc-ggcgcggcacgcgccaaggaaaactt-aa-----tt
tagcgtcggtccc-cccagcatcccgttc-gcgggccgtgcgg-ggggaacgggcgtcta
t---cgaatgtcgtaacgactctcggcaacggatatctcggctctcgcatcgatgaagaa
cgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtgaaccatcgagtctttga
acgcaagttgcgcccgaagccattaggccgagggcacgtctgcctgggcgtcacgcatcg
cgtcgcc-cccct--ccccgcgc--acg-gcg---ctggcga--------ggggggcgga
tactggctccccgtgcg-----ccacggcgcgcggccggcccaaatgcgatcccccggcg
tcccgcgtcgcgacaagtggtggttg-aacatctc---aatctctcgcgtcctgtcgtgc
--cgctgggccgtcc-gcagggttc------cgaacg-atgacccaacggag-ctcatcg
-----------gctccct--cgacc
>Isodon_loxothyrsus 676 bp 
tcgaaacctgcaaagcagaccgcgaactcgtt-tctaacgcca-----------------
--------------------------tcccccgccgcagcgcgcgcactcgtgc-cgcgc
ggcgtgcgggc-taacgaacccc-ggcgcggaacgcgccaaggaaaacttaaa-----tt
tagcgtcggtcccgccccgcatcccgttc-gcgggccgtgcggtgcggaac-ggcgtcta
t---cgaatgtcataacgactctcggcaacggatatctcggctctcgcatcgatgaagaa
cgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtgaaccatcgagtctttga
acgcaagttgcgcccgaagccattaggccgagggcacgtctgcctgggcgtcacgcatcg
cgtcgct-cccc----c----cc--acc-act---ctggcga-------gggggggcgga
tattggcctcccgtgcg-----cctcggcgtgcggccggcccaaatgcgatcccccggcg
actcgcgtcgcgacaagtggtggttg-aacatctc---aa--tctcgcgtctcgtcgtgc
--cgccgagccgtcc-gtggtgatc------cgaacg-atgacccaacggag-ctt----
-----------gctcctt--cgacc
>Isodon_lungshengensis 676 bp 
tcgaaacctgcaaagcagaccgcgaacacgtt-tctaacgcca-----------------
--------------------------tcccccgccgcagcgcgcgcactcgtgc-cgcgc
tgcgtgcgggc-taacgaacccc-ggcgcggaacgcgccaaggaaaacttaaa-----tt
tagcgtcggtcccgccccgcatcccgttc-gcgggccgtgcggtgcggaacgggcgtcta
t---cgaatgtcgtaacgactctcggcaacggatatctcggctctcgcatcgatgaagaa
cgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtgaaccatcgagtctttga
acgcaagttgcgcccgaagccattaggccgagggcacgtctgcctgggcgtcacgcatcg
cgtcgct-cccc----c----cc--acc-act---ctggcga-------gggggggcgga
tattggcctcccgtgcg-----cctcggcgtgcggccggcccaaatgcgatcccccggcg
actcgcgtcgcgacaagtggtggttg-aacatctc---aa--tctcgcgtctcgtcgtgc
--cgccgagccttcc-gcggtgatc------cgaacg-atgacccaacggag-ctt----
-----------gctcctt--cgacc
>Isodon_megathyrsus_1 676 bp 
tcgaaacctgcaaagcagaccgcgaacacttt-tctaacgcca-----------------
--------------------------tcccccgccgcagcgcgcgcactcgtgc-cgcgc
ggcgtgcgggc-taacgaacccc-ggcgcggaacgcgccaaggaaaacttaaa-----tt
tagcatcggtcccgccccgcatcccgttc-gcgggccgtgcggtgcggaacgggcgtcta
t---cgaatgtcataacgactctcggcaacggatatctcggctctcgcatcgatgaagaa
cgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtgaaccatcgagtctttga
acgcaagttgcgcccgaagccattaggccgagggcacgtctgcctgggcgtcacgcatcg
cgtcgct-cccc----c----ca--ccc-acg---ttggcga--------ggggggcgga
tattggcctcccgtgcg-----cctcggcgtgcggccggcccaaatgcgatcccccggcg
actcgtgtcgcgacaagtggtggttg-aacatctc---aa--tctcgcgtctcgtcgtgc
--cgccgagccgtcc-gtggtgatc------caaacg-atgacccaacggag-ctt----
-----------gctcctt--cgacc
>Isodon_megathyrsus_2 676 bp 
tcgaaacctgcaaagcagaccgcgaacacgtt-tctaacgcca-----------------
--------------------------tcccccgccgcagcgcgcgcactcgtgc-cgcgc
ggcgtgcgggc-taacgaacccc-ggcgcggaacgcgccaaggaaaacttaaa-----tt
tagcatcggtcccgccccgcatcccgttc-gcgggccgtgcggtgcggaacgggcgtcta
t---cgaatgtcataacgactctcggcaacggatatctcggctctcgcatcgatgaagaa
cgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtgaaccatcgagtctttga
acgcaagttgcgcccgaagccattaggccgagggcacgtctgcctgggcgtcacgcatcg
cgtcgct-cccc----c----ca--ccc-acg---ttggcga--------ggggggcgga
tattggcctcccgtgcg-----cctcggcgtgcggccggcccaaatgcgatcccccggcg
actcgtgtcgcgacaagtggtggttg-aacatctc---aa--tctcgcgtctcgtcgtgc
--cgccgagccgtcc-gtggtgatc------caaacg-atgacccaacggag-ctt----
-----------gctcctt--cgacc
>Isodon_melissoides 676 bp 
tcgaattctgcaaagcagaccgcgaactcgtt-tctaacgcca-----------------
--------------------------acccccgccgcagcgcgcgcactcgtgc-cgcgc
-gcgtgcgggc-taacgaacccc-ggcgcggaacgcgccaaggaaaacttaaa-----tt
tagcgtcggtcccgccccgcatcccgttc-gcgggccgtgcggtgcggaacgggcgtcta
t---cgaatgtcataacgactctcggcaacggatatctcggctctcgcatcgatgaagaa
cgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtgaaccatcgagtctttga
acgcaagttgcgcccgaagccattaggccgagggcacgtctgcctgggcgtcacgcatcg
cgtcgct-cccc----c----cc--acc-act---ctggcga-------gggggggcgga
tattggcctcccgtgcg-----cctcggcgtgcggccggcccaaatgcgatcccccggcg
actcgcgtcgcgacaagtggtggttg-aacatctc---aa--tctcgcgtctcgtcgtgc
--cgccgagccgtcc-gtggtgatc------cgaacg-atgacccaacggag-ctt----
-----------gctcctt--cgacc
>Isodon_nervosus 676 bp 
tcgaaacctgcaaagcagaccgcgaacacgtt-tctaacgcca-----------------
--------------------------tcccccgccgcagcgcgcgcactcgtgc-cgcgc
ggcgtgcgggc-taacgaacccc-ggcgcggaacgcgccaaggaaaacttaaa-----tt
tagcgtcggtcccgccccgcatcccgttc-gcgggccgtgcggtgcggaacgggcgtcta
t---cgaatgtcataacgactctcggcaacggatatctcggctctcgcatcgatgaagaa
cgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtgaaccatcgagtctttga
acgcaagttgcgcccgaagccattaggccgagggcacgtctgcctgggcgtcacgcatcg
cgtcgct-cccc----c----cc--acc-act---ctggcga-------gggggggcgga
tattggcctcccgtgcg-----cctcggcgtgcggccggcccaaatgcgatcccccggcg
actcgcgtcgcgacaagtggtggttg-aacatctc---aa--tctcgcgtctcgtcgtgc
--cgccgagccgtcc-gtggtgatc------cgaacg-atgacccaacggagcctt----
-----------gctcctt--cgacc
>Isodon_phyllopodus 676 bp 
tcgaaacctgcaaagcagaccgcgaacacgtt-aacaacgcca-----------------
------------------------a-ccccccgccgccgcgcgcgcactcgtgc-gacgc
ggcgtgcgggc-taacgaacccc-ggcgcggcacgcgccaaggaaaactgaaa-----tt
tagcgtcggtccccctcagcatcccgttc-gcgggccgtgcgg-ggggaacgggcgtcta
t---cgaatgtcataacgactctcggcaacggatatctcggctctcgcatcgatgaagaa
cgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtgaaccatcgagtctttga
acgcaagttgcgcccgaagccattaggccgagggcacgtctgcctgggcgtcacgcatcg
cgtcgcc-cccct--ccccgcgc--acg-gcg---ctcgtga--------ggggggcgga
tactggctccccgtgcg-----cctcggcgcgcggccggcccaaatgcgatcccccggcg
acccgcgtcgcgacaagtggtggttg-aacatctc---aa--tctcgcgtcctgtcgtgc
--cgctgggtcgtcc-gcagggttc------cgaacg-atgacccaacggag-ctcatct
-----------gctccct--cgacc
>Isodon_phyllostachys 676 bp 
tcgaaacctgtaaagcagaccgcgaacacgtt-tctaacgcca-----------------
--------------------------tcccccgccgcagcgcgcgcactcgtgc-cgcgc
ggcgtgtgggc-taacgaacccc-ggcgcggaatgcgccaaggaaaacttaaa-----tt
tagcgtcggtcctgccccgcatcccgttc-gcgggccgtgcggtgcggaacgggcgtcta
t---cgaatgtca-aacgactctcggcaacggatatctcggctctcgcatcgatgaagaa
cgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtgaaccatcgagtctttga
acgcaagttgcgcccgaagccattaggccgagggcacgtctgcctgggcgtcacgcatcg
cgtcgct-cccc----c----cc--acc-act---ctggcga-------gggggtgcgga
tattggcctcccgtgcg-----cctcggcgtgcggccggcccaaatgcgatcccccggcg
actcgcgtcgcgacaagtggtggttg-aacatctc---aa--tctcgcgtctcgtcgtgc
--cgccgagccgtcc-gcggtgatc------cgaacg-atgacccaacggag-ctt----
-----------gctcctt--cgacc
>Isodon_pleiophyllus 676 bp 
tcgaaacctgcaaagtagaccgcgaacatgtt-tctaatgcca-----------------
--------------------------t-ccccgccgcagcgcg-gctctcgtgc-cgcgc
ggcgtgcgggc-taacgaacccc-ggcgcggaacgcgccaaggaaaacttaaa-----tt
tagcgtcggtcccgccccgcatcccgttc-gcgggccgtgcggtgtggaa-gggcgtcta
t---cgaatgtcataacgactctcggcaacggatatctcggctctcgcatcgatgaagaa
cgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtgaaccatcgagtctttga
acgcaagttgcgcccgaagccattaggccgagggcacgtctgcctgggcgtcacgcatcg
cgtcgct-cccc---cc----cc--acc-acg---ctggcga--------ggggggcgga
tattggcctcccgtgcg-----cctcggcgtgcggctggcccaaatgcgatcccccggcg
actcgcgtcgcgacaagtggtggttg-aacatctc---aa--tctcgcgtctcgtcgtgc
----gcgagccgtcc-gtggtgat-------cgaacg-atgacccaacggag-ctt----
-----------gctcctt--cgacc
>Isodon_rosthornii 676 bp 
tcgaaacctgcaaagcagaccgcgaacacgtt-tctaacgcca-----------------
--------------------------tcccccgccgcagcgcgcgcactcgtgc-cgcgc
ggcgtgcgggc-taacgaacccc-ggcgcggaacgcgccaaggaaaacttaaa-----tt
tagcgtcggtcccgccccgcatcccgttc-gcgggccgtgcggtgtggaacgggcgtcta
t---agaatgtcataacgactctcggcaacggatatctcggctctcgcatcgatgaagaa
cgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtgaaccatcgagtctttga
acgcaagttgcgcccgaagccattaggccgagggcacgtctgcctgggcgtcacgcatcg
cgtcgct-cccc----c----cc--accaact---ctggcga--------ggggggcgga
-attggccccccgtgcg-----cctcggcgtgcggccggcccaaatgcgatcccccggcg
actcgcgtcgcgacaagtggtggttg-aacatctc---aa--tctcgcgtctcgtcgtgc
--tgccgagccgtcc-gtggtgatc------cgaacg-atgacccaacggag-ctt----
-----------gctcctt--cgacc
>Isodon_rugosiformis 676 bp 
tcgaaacctgcaaagcagaccgcgaactcgtt-tctaacgcca-----------------
--------------------------tcccccgccgcagcgcgcgcactcgtgc-cgcgc
ggcgtgcgggc-taacgaacccc-ggcgcggaacgcgccaaggaaaacttaaa-----tt
tagcgtcggtcccgccccgcatcccgttc-gcgggccgtgcggtgcggaactggcgtcta
t---cgaatgtcataacgactctcggcaacggatatctcggctctcgcatcgatgaagaa
cgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtgaaccatcgagtctttga
acgcaagttgcgcccgaagccattaggccgagggcacgtctgcctgggcgtcacgcatcg
cgtcgct-cccc----c----cc--acc-act---ctggaga-------gggggggcgga
tattggcctcccgtgcg-----cctcggcgtgcggccggcccaaatgcgatcccccggcg
actcgcgtcgcgacaagtggtggttg-aacatctc---aa--tctcgcgtctcgtcgtgc
--cgccgagccgtcc-gtggtgatc------caaacg-atgacccaacggag-ctt----
-----------gctcctt--cgacc
>Isodon_scoparius 676 bp 
tcgaaacctgcaaagcagaccgcgaacacgtt-tctaacgcca-----------------
--------------------------tcccccgccgcagcgcgcgcactagtgc-cgcgc
ggcgtgcgggc-taacgaacccc-ggcgcggaacgcgccaaggaaaacttaaa-----tt
tagcgtcggtctcgccccgcatcccgttc-gcgggccgtgcggtgcggaacgggcgtcta
t---cgaatgtcataacgactctcggcaacggatatctcggctctcgcatcgatgaagaa
cgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtgaaccatcgagtctttga
acgcaagttgcgcccgaagccattaggccgagggcacgtctgcctgggcgtcacgcatcg
cgtcgct-cccc----c----cc--acc-act---ctggcga-------ggaggggcgga
tattggcctcccgtgcg-----cctcggcgtgcggccggcccaaatgcgatcccccggcg
actcgcgtcgcgacaagtggtggttg-aacatctc---aa--tctcgcgtctcgtcgtgc
--cgccgagccgtcc-gcggtgatc------cgaacg-atgacccaacggag-ctt----
-----------gctcctt--cgacc
>Isodon_sculponeatus 676 bp 
tcgaaacctgcaaagcagaccgcgaacacgtt-tttaacgcca-----------------
--------------------------tcccccgccacagcgcgcgcactcgtgc-cgcgc
tgcgtgcgggc-taacgaacccc-ggcgcggaacgcgccaaggaaaacttaaa-----tt
tagcgtcggtcccgccccgcatcccgttc-gcgggccgtgcggtgcggaacgggcgtcta
t---cgaatgtcataacgactctcggcaacggatatctcggctctcgcatcgatgaagaa
cgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtgaaccatcgagtctttga
acgcaagttgcgcccgaagccattaggccgagggcacgtctgcctgggcgtcacgcatcg
cgtcgct-cccc----c----cc--agc-aca---ctggcga--------ggggggcgga
tattggcctcccgtgct-----cctcggcgtgcggccggcccaaatgcgatcccccggcg
actcgcgtcgcgacaagtggtggttg-aacatctc---aa--tctcgcgtctcgtcgtgc
--tgccgagccgtcc-gtggtgatc------cgaacg-atgacccaacggag-ctt----
-----------gctcctt--cgacc
>Isodon_taliensis 676 bp 
tcgaaacctgcaaagcagaccgcgaacacgtt-tctaacgcca-----------------
--------------------------tcccccgccgcagcgcgtgcactcgtgc-cgcgc
ggcgtgcgggc-taacgaacccc-ggcgcggaacgcgccaaggaaaacttaaa-----tt
tagcgtcggtcccgccccgcatcccgttc-gcgggccgtgcggtgcggaacggacgtcta
t---cgaatgtcataacgactctcggcaacggatatctcggctctcgcatcgatgaagaa
cgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtgaaccatcgagtctttga
acgcaagttgcgcccgaagccattaggccgagggcacgtctgcctgggcgtcacgcatcg
cgtcgct-cccc---------cc--acc-act---ctggcga------ggggggggcgga
tattggcctcccgtgcg-----cctcggcgtgcggccggcccaaatgcgatcccccggcg
actcgcgtcgcgacaagtggtggttg-aacatctc---aa--tctcgcgtctcgtcgtgc
---gccgagccgtcc-gtggtgatc------cgaacg-atgacccaacggagcttt----
-----------gctcctt--cgacc
>Isodon_ternifolius 676 bp 
tcgaaacctgcacagcagaccgcgaacacgtt-tctaaagcca-----------------
--------------------------acccccgccgccgcgcgcgcactcgtgc-gccgc
gatgtgcgggc-taacgaacccc-ggcgcggcacgcgccaaggaaaactaaaa-----tt
tagcgccggtcc--ccccgcaacccgttc-gcgggccgtgcggggcagcacgagcgtcta
t---tgaatgtcataacgactctcggcaacggatatctcggctctcgcatcgatgaagaa
cgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtgaaccatcgagtctttga
acgcaagttgcgcccgaagccattaggccgagggcacgtctgcctgggcgtcacgcatcg
cgtcgcc-cccc---caccgcgc--ttc-ggc---acggccg--------agggggtgga
tattggccccccgtgcg-----cctcggcgtgcggtcggcccaaatacgatcccctgtcg
actcgcgtcgcgacaagtggtggttg-aacatctc---aa--tctcgcatctcgtcgtgg
--caccgagccttcc-gcggtgatc------cgatag-atgacccaacggag-ctg----
---cttatgccgctcctt--cgacc
>Isodon_wikstroemioides 676 bp 
tcgaaacctgcaaagcagaccgcgaacacgtt-tctaacgcca-----------------
--------------------------tcccccgccgcagcgcgcgcactcgtgc-cgctc
tgcgtgcgggc-taacgaacccc-ggcgcggaacgcgccaaggaaaacttaaa-----tt
tagcgtcggtcccgccccgcatcccgttc-gcgggccgtgcggtgcggaacaggcgtcta
t---cgaatgtcataacgactctcggcaacggatatctcggctctcgcatcgatgaagaa
cgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtgaaccatcgagtctttga
acgcaagttgcgcccgaagccattaggccgagggcacgtctgcctgggcgtcacgcatcg
cgtcgct-cccc----c----cc--acc-act---ctggcga-------gggggggcgga
tattggcctcccgtgcg-----cctcggcgtgcggccggcccaaatgcgatcccccggcg
actcgcgtcgcgacaagtggtggttg-aacatctc---aa--tctcgcgtctcgtcgtgc
--cgccgagtcgtcc-gcggtgatc------cgaacg-atgacccaacggag-ctt----
-----------gctcctt--cgacc
>Isodon_xerophilus 676 bp 
tcgaaacctgcaaagcagaccgcgaacacgtt-tctaacgcca-----------------
--------------------------tcccccgccgcagcgcgcgcactcgtgc-cgcgc
ggcgtgcgggc-taacgaacccc-ggcgcggaacgcgccaaggaaaacttaaa-----tt
tagcgtcggtcccgccccgcatcccgttc-gcgggccgtgcggtgcggaacgggcgtcta
t---cgaatgtcataacgactctcggcaacggatatctcggctctcgcatcgatgaagaa
cgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtgaaccatcgagtctttga
acgcaagttgcgcccgaagccattaggccgagggcacgtctgcctgggcgtcacgcatcg
cgtcgct-cccc----c----ca--ccc-acg---ttggcga--------ggggggcgga
tattggcctcccgtgcg-----cctcggcgtgcggccggcccaaatgcgatcccccggcg
actcgtgtcgcgacaagtggtggttg-aacatctc---aa--tctcgcgtctcgtcgtgc
--cgccgagccgtcc-gtggtgatc------cgaacg-atgacccaacggag-ctt----
-----------gctcctt--cgacc
>Isodon_yuennanensis 676 bp 
tcgaaacctgcaaagcagaccgcgaacacgttaaacaacgcca-----------------
------------------------a-tcccccgccgccgcccgtgcacttgtgcggacgc
ggcgtgcgggc-taacgaacccc-ggcgcggcacgcgccaaggaaaactgaaa-----tt
tagcgtcggtccccctcagcatcccgttc-gcgggtcgtgcgg-ggggaacgggcgtcta
t---cgaatgtcataacgactctcggcaacggatatctcggctctcgcatcgatgaagaa
cgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtgaaccatcgagtctttga
acgcaagttgcgcccgaagccattaggccgagggcacgtctgcctgggcgtcacgcatcg
cgtcgcc-cccct--ccccgcgc--acg-gcg---ctcgcga--------ggggggcgga
tactggctccccgtgcg-----cctcggcgcgcggccggcccaaatgcgatcccccggcg
acccgcgtcgcgacaagtggtggttg-aacatctc---aa--tctcgcgtcctgtcgtgc
--cgctgggtcgtcc-gtagggttc------cgaacg-atgacccaa-ggag-ctcatct
-----------gctccct--cgacc
>Lavandula_angustifolia_1 676 bp 
tcg-aacctgcaaggcagaccgcgaacacgtg-tttaactccg---cgggaccgttgtgc
ggcgcgagccc---cacgccgatcccgctcccgtcgttgcacgcgcacccgtgc-gccgc
agcgttcgggcttaactcacccc-ggcgcggaatgcgccaaggaaaac-aaaa-----tg
aagcgtcggccc---tccgcatcccgttc-gcggggcgtgcgg-gggcagcgggcgtcta
t---cgaatgtcataacgactctcggcaacggatatctcggctctcgcatcgatgaagaa
cgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtgaaccatcgagtctttga
acgcaagttgcgcccgaggccattcggctgagggcacgtctgcctgggcgtcacgcatcg
cgtcgcc-ccctcc-acccgcgc--act-gcg---ctcgtag--------agggggcgga
tattggccccccgtgtg-----ctccggcacgcggtcggcccaaatgcgatcccccggcg
actcatgtcgcggccagtggtggttg-aacatatc---aa--tctcgtgtcttgccgcgt
--cgttgagccgtcg-gacgggatc------tcgtta-acgacccaacggtg-tgagcgc
accccgtgcgcgcgcgccctcgacc
>Lavandula_angustifolia_2 676 bp 
tcgaaacctgcaaggcagaccgcgaacacgtg-tttaactccg---cgggaccgttgtgc
ggcgcgagccc---cacgccgatcccgctcccgtcgttgcacgcgcacccgtgc-gccgc
agcgttcgggcttaactcacccc-ggcgcggaatgcgccaaggaaaac-aaaa-----tg
aagcgtcggccc---tccgcatcccgttc-gcggggc-tgcgg-gggcagcgggcgtcta
t---cgaatgtcataacgactctcggcaacggatatctcggctctcgcatcgatgaagaa
cgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtgaaccatcgagtctttga
acgcaagttgcgcccgaggccattcggctgagggcacgtctgcctgggcgtcacgcatcg
cgtcgcc-ccctcc-acccgcgc--act-gcg---ctcgtag--------agggggcgga
tattggccccccgtgtg-----ctccggcacgcggtcggcccaaatgcgatcccccggcg
actcatgtcgcggccagtggtggttg-aacatatc---aa--tctcgtgtcttgccgcgt
--cgttgagccgtcg-gacgtgatc------tcgtta-acgacccaacggtg-tgagcgc
accccgtgcgcgcgcgccctcgacc
>Lavandula_sp 676 bp 
tcgaaacctgcaaggcagaccgcgaacacgtg-tttaactccg-----------------
---------------------------ttcccgccggtgtgcgcgcactcgtgc-gccgc
atcgtgcgggc-taactcacccc-ggcgcggaaagcgccaaggaatac-aaac-----tg
aagcgtcggccc---tccgcatcccgttc-gcgggctgtgcgg-gggtagcgggcgtcta
t---cgaatgtcataacgactctcggcaacggatatctcggctctcgcatcgatgaagaa
cgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtgaaccatcgagtctttga
acgcaagttgcgcccgatgccatccggttgagggcacgtctgcctgggcgtcacgcatcg
cgtcgcc-ccct---ccccgcgctcatt-gtg---caggtgg--------atggggcgga
taatggccccccgtgcg-----ccccggcgtgcggtcggcccaaatacgatcccccggcg
actcatgtcgcggccagtggtggttg-aacatctc---aa--tctctctattcgtcgtgg
--cgttgagccgttc-ggatgcgatc-----acgtattctgacccaacggtg-tgggtgc
actacatgcgctcgcactttcgacc
>Mentha_arvensis 676 bp 
tcgaaacctgcaaagcagaccgcgaactcgta-actaacgccg--cggggcacggcac--
-gggggagaccccctgccgcatcccgtctcctgccg----gcttgctccctcgggggcac
gccgtgcgggc-taacgaacccc-ggcgcggaacgcgccaaggaaaac-caaa-----cg
aagcgtccgccc---ccggcatcccgttc-gcggggcgtgccg-tgggatcgggcgtcta
t---caaatgtcaaaacgactctcggcaacggatatctcggctctcgcatcgatgaagaa
cgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtgaaccatcgagtctttga
acgcaagttgcgcccgaagccattaggccgagggcacgtctgcctgggcgtcacgcatcg
cgtcgcc-ccccac-ccccgcgc--gca-tcg---ccgggca------gttgggggcgga
cactggcctcccgtgcg-----cctcggcgtgcggccggcccaaatgagatccccgggcg
actggcgtcgcgacaagtggtggttg-aacatctc---aa--tctctctcgtggtcgtgc
--cgccgtgtcgtcccgtacgggaa------tcgaaa-acgacccaacggtg-ctaggcg
cgaacagcgtctcacctt--cgacc
>Mentha_sp 676 bp 
tcgaaacctgcaaagcagaccgcgaactcgta-actaacgccg--cggggcacggcac--
-gggggagaccccctgccgcatcccgtctcctgccg----gcttgctccctcgggggcac
gccgtgcgggc-taacgaacccc-ggcgcggaacgcgccaaggaaaac-caaa-----cg
aagcgtccgccc---ccggcatcccgttc-gcggggcgtgccg-tgggatcgggcgtcta
t---caaatgtcaaaacgactctcggcaacggatatctcggctctcgcatcgatgaagaa
cgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtgaaccatcgagtctttga
acgcaagttgcgcccgaagccattaggccgagggcacgtctgcctgggcgtcacgcatcg
cgtcgcc-ccccac-ccccgcgc--gca-tcg---ccgggcg------gttgggggcgga
cactggcctcccgtgcg-----cctcggcgtgcggccggcccaaatgagatccccgggcg
actggcgtcgcgacaagtggtggttg-aacatctc---aa--tctctctcgtggtcgtgc
--cgccgtgtcgtcccgtacgggaa------tcgaaa-acgacccaacggtg-ctaggcg
cgaacagcgtctcacctt--cgacc
>Ocimum_basilicum 676 bp 
tcgagacctgcaaagcagaccgcgaacacgtg-tttaactcat-----------------
-------------------------gaatcccgccgccggccccg------------gtc
ggcgcgcgggc-taacgaacccc-ggcgcggaacgcgccaaggaaaac-tcaaaac--gt
cggcgccggccc---cccccaccccgtcc-gcgggtcgtgcgg-ggggcgcgggcgtcca
tcgacgaatgtcaaaacgactctcggcaacggatatctcggctctcgcatcgatgaagaa
cgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtgaaccatcgagtctttga
acgcaagttgcgcccgaagccatcaggccgagggcacgtctgcctgggcgtcacgcatcg
cgtcgcc-cccccatccccgcgc--aat-gcg---ctcggct------tgggggggcgga
tactggcctcccgtgcg-----ccccgccgcgcggccggcccaaatg-gatcccccggcg
acccgcgtcgcgacaagtggtggttg-aactcatc---aa--tttc----cccgtcgcgc
---cccgggtcgtcc-gcgcggatcccttagtaaaaa--gaacccaacct----------
--------------------cgacc
>Ocimum_gratissimum_var_suave 676 bp 
tcgaaacctgcaaagcagaccgcgaacacgtg-tttaactcat-----------------
---------------------------cccccgccgc------------------cgatc
ggcgtgcgggc-taacgaaccccgggcgcggaaagcgccaaggaaaac-tgta-----cg
tagcgtcggtcc----ccccatcccgttc-gcgggtcgtgcgg-gggatgcggacgtcta
t---cgaat-tcaaaacgactctcggcaacggatatctcggctctcgcatcgatgaagaa
cgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtgaaccatcgagtctttga
acgcaagttgcgcccgaagccattaggccgagggcacgtctgcctgggcgtcacgcatcg
cgtcgcc-cccccttccccgcgc--acc-gcg---ctcggga------cggggggacgga
tattggcctcccgtgcg-----ccccggtgcgcggccggcccaaatgcgatcccccggcg
acccgcgtcgcgacaagtggtggttgaaacatctc---aa--tctcgcgtctcgtcgcgc
--ttccgggtcgtcc-gagcgggct------ccaaaa-ataacccaatggtg-cggccgt
-----tacgccgcgccct--cgacc
>Orthosiphon_aristatus_1 676 bp 
tcgaaacctgcaaagcagaccgcgaacacgtt-tctaactcac-----------------
--------------------------tctcccgccggcgcgggcgcacccgtgc-cttgc
gtcgtgcgggc-taacgaacccc-ggcgcggaatgcgccaaggaaaac-cgaa-----cg
tagcgtcggccc---ccctcgccccgttc-gcgggtcgtgcgg-ggggcgcggacgtcta
t---cgaatgtcaaaacgactctcggcaacggatatctcggctctcgcatcgatgaagaa
cgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtgaaccatcgagtctttga
acgcaagttgcgcccgaagccattaggccgagggcacgtctgcctgggcgtcacgcatcg
cgtcgcc-cccct--ccccgcgc--tct-gcg---ctcggga-------cgggggacgga
tattggcctcccgtgcg-----ccccgtcgtgcggccggcccaaatgcgatcccccggcg
actcgcgtcgcgacaagtggtggttg-aacatctc---aa--tctcgcgtctcgtcgcgc
--cgccgaatcgtcc-gtacgggcat-----cgaaa--ttgacccaaaggcg-tggcccc
-----cgagccacgctct--cgacc
>Orthosiphon_aristatus_2 676 bp 
tcgaaacctgcaaagcagaccgcgaacacgtt-tctaactcac-----------------
---------------------------ctcccgccggcgcgggcgcacccgtgc--ctgc
gtcgtgcgggc-taacgaacccc-ggcgcggaatgcgccaaggaaaac-cgaa-----c-
tagcgtcggccc---cccttgccccgttc-gcgggtcgtgcgg-ggggcgcggacgtcta
t---cgaatgtcaaaacgactctcggcaacggatatctcggctctcgcatcgatgaagaa
cgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtgaaccatcgagtctttga
acgcaagttgcgcccgaagccattaggccgagggcacgtctgcctgggcgtcacgcatcg
cgtcgcc-cccc---tcccgcgc---ct-gcg---ctcggga-------cgggggacgga
tattggcctcccgtg-g-----ccccgtcgtgcggccggcccaaatgcgatcccccggcg
actcgcgtcgcgacaagtggtggttg-aacatctc---aa--tctcgcgtctcgtcgcgc
--cgccgaatcgtcc-gt-cgggcat-----cgaaa--tcgacccaaaggcg-tggcccc
------cgagcccgctct--cgacc
>Orthosiphon_wulfenioides 676 bp 
tcgaaacctgcaaagcagaccgcgaacacgtt-tctaactcac-----------------
--------------------------tctcccgccggcgcgcgcgctcgcgtgc-gtcgc
gtcgtgcgggc-taacgaacccc-ggcgcggaatgcgccaaggaaaac-tgaa-----ag
tagcgccggccc---ccctctccccgttc-gcgggtcgtgcgg-ggggcgcgggcgtcta
t---cgaatgtcaaaacgactctcggcaacggatatctcggctctcgcatcgatgaagaa
cgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtgaaccatcgagtctttga
acgcaagttgcgcccgaagccattaggccgagggcacgtctgcctgggcgtcacgcatcg
cgtcgcc-cccct--ccccgcgc--tcc-gcg---ctcgggg-------tggggggcgga
tattggcctcccgtgcg-----ccccgtcgtgcggccggcccaaatgcgatcccccggcg
actcgcgtcgcgacaagtggtggttg-aacatctc---aa--tctcgcgtctcgtcgcgc
--cgccgaatcgtcc-ggacgggcat-----cgaaca-gtgacccaacggcg-tggcctt
------gagccgcgctct--cgacc
>Perilla_frutescens 676 bp 
tcgaaacctgcaaagcagaccgcgaacacgtg-tttaacatca--tcggacacggcgtgg
gggag-----actcccgtcgtgcaccgctcccgccg--gagtgcgccctcgggc-gtcgc
accgtgcgggc-taacgaacccc-ggcgcggcaagcgccaaggaaaac-aaaa-----tt
tagcgcccgcct---tccgcatcccgttc-gcggggtgtgcgg-ggggaatggacgtcta
t---cgaatgtcataacgactctcggcaacggatatctcggctctcgcatcgatgaagaa
cgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtgaaccatcgagtctttga
acgcaagttgcgcccgaagccattaggccgagggcacgtctgcctgggcgtcacgcatcg
cgtcgcc-cccct--ccccgcgc--tga-gcg---ctcgtga--------ggggggcgga
tattggccccccgtgcg-----ccctggcgtgcggtcggcccaaatgcgatccctcgacg
actcgtgtcgcgactagtggtggttg-aatagctc---aa--tctcgtgtcttgtcgtgc
--taccgcgtcgtcc-gaatgggaat-----cgaaca-acgacccaacggtg-ttcgtgc
gttaccgcaccgcacctt--cgacc
>Plectranthus_strigosus 676 bp 
------------------------------------------------------------
-----------------------------------------------------------c
gccgcgcgggc-taacgaacccc-ggcgcggaaagcgccaaggaaaac-tgaa-----ga
gaaagaggcgcc--gccggcgtct--------------------------------tcta
t---cgaatgtcaaaacgactctcggcaacggatatctcggctctcgcatcgatgaagaa
cgtagcgaaatgcgatacttggtgtgaattgca-aatcccgtgaaccatcgagtctttga
acgcaagttgcgcccgaagccattaggccgagggcacgtctgcctgggcgtcacgcatcg
cgtcgcc-ccccc--gatcgcac--------g---gcgatcg--------agggggcgga
gattggcctcccgtgcg-----ccccggcgcgcggccggcccaaatgcgatcccccggcg
acccgcgtcgcggcgagtggtggttg-aac-tctc---aa--tctcgcgtaccgccgcgc
--ccccgggccgtcc-gagcgggcat-----cgagca-cagacccgaa------------
--------------------cggcg
>Salvia_evansiana 676 bp 
acgaaacctgcaaagcagaccgcgaacacgtg-tttaacacag--tcgggtgcgcggcgt
-ggggtgacccccgtctcgtactcgatcccccgtcg----tcgcgcgtcctcgg-accgc
gtcgttcgggc-taacgaacccc-ggcgcggaatgcgccaaggaaaac-taat-----cg
aagcgtccgccc---cccgtgccccgttc-gcggtgcgtgctg-ggggaccggatgtcta
t---caaatgtcaaaacgactctcggcaacggatatctcggctctcgcatcgatgaagaa
cgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtgaaccatcgagtctttga
acgcaagttgcgcccgaagccattaggccgagggcacgtctgcctgggcgtcacgcatcg
cgtcgcc-ccctct-ccccgcgc--aca-gcg---cggtttg--------cgggggcgga
aactggcctcccgtgcg-----ccccggcgtgcggttggcccaaatgcgatccctcggcg
actcgtatcgcgacaagtggtggttg-aacaactc---ac--tttca-----tgtcgtgc
--ttctgcgtcgttg-gtatgggcat-----ccgtaa-acgacccaacggtg-tcggcgt
cgcacgacgccccacctt--cgacc
>Salvia_miltiorrhiza 676 bp 
tcgaaacctgcaaagcagaccgcgaacacgtg-tttaacaatg--ccgggtgcgtggcgt
gggggcaacccccgtcatgtactcggtcccccgccg----gcgcgcgtcctcgg-gcagt
gtcgtgcgggc-taacgaacccc-ggcgcggaatgcgccaaggaaaac-taat-----cg
aagcgtccgccc---ctcgtgccccgttc-gcggtgcgcgcgg-ggggattggatgtcta
t---caaatgtcaaaacgactctcggcaacggatatctcggctctcgcatcgatgaagaa
cgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtgaaccatcgagtctttga
acgcaagttgcgcccgaagccattaggccgagggcacgtctgcctgggcgtcacgcatcg
cgtcgcc-cccct--ccccgcgc--ata-gcg---tgggctg--------cgggggcgga
aactggcctcccgtgcg-----ccccggcgcgcggctggcccaaatgcgatccctcggcg
actcgtgtcgcgacaagtggtggttg-aacaactc---ac--tttca-----tgtcgtga
--ttctgcgtcgtcg-gtatgggcat-----ccgtaa-acgacccaacggtg-taggcgc
cacacggcgcccaacctt--cgacc
>Siphocranion_macranthum_1 676 bp 
tcgaaacctgcaaagcagaccgcgaacacgtg-tttaacatcg--tcgggcacg------
----------gcctcgtcgtgatccggctctcgccgccgcgtagccatttgtgc-tttgc
gtcgtgcgggc-taacgaacccc-ggcgcggaatgcgccaaggaaaac-ttaa-----tg
aagcgtcggccc--cctcgcaccccgttt-gcggtgcgtgcgg-ggggagcggatgtcta
t---cgaatgtcaaaacgactctcggcaacggatatctcggctctcgcatcgatgaagaa
cgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtgaaccatcgagtctttga
acgcaagttgcgcccgaagccattaggccgagggcacgtctgcctgggcgtcacgcatcg
cgtcgcc-ccctct-cctcgtgccaaac-acg---cttggga------tgggggggcgga
tattggcctcccgtgca-----cctcggtgcgtggttggcccaaatgtgatccctcggcg
actcttgtcacgacctgtggtggttg-aaaatctc---aa--tctcgcttcgtgtcgtgc
--tttcgagtcgtcc-gtaagggctt-----cgaata-acgacccaatggcg-tcggcgc
gatatcgtgctgtgcgctt-cgacc
>Siphocranion_macranthum_2 676 bp 
tcgaaacctgcaaagcagaccgcgaacacgtg-tttaatatcg--tcgggcacg------
----------gcctcgtcgtgatccggctctcgccgccgcgtagcc-tttgtgc-ttcgc
gtcgtgcgggc-taacgaacccc-ggcgcggaatgcgccaaggaaaac-ttaa-----tg
aagcgtcggccc--cctcgcaccccgttt-gcggtgcgtgcgg-ggggagcggatgtcta
t---cgaatgtcaaaacgactctcggcaacggatatctcggctctcgcatcgatgaagaa
cgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtgaaccatcgagtctttga
acgcaagttgcgcccgaagccattaggccgagggcacgtctgcctgggcgtcacgcatcg
cgtcgcc-ccctct-ccccgtgccaaaa-acg---ctcggga-------tggggggtgga
tattggcctcccgtgca-----cctcggtgcgtggttggcccaaatgtgatccctcggcg
actcttgtcacgacctgtggtggttg-aaaatctc---aa--tctcgcttcgtgtcgtgc
--tttcgagtcgtcc-gtaagggatt-----cgaata-acgacccaatggcg-tcggcgc
gatatcgcgctgtgcgctt-cgacc
>Siphocranion_nudipes 676 bp 
tcgtaacctgcaaagcagaccgcgaacacgtg-tttaacaccg--tcgggcacg------
----------gcctcgtcgtgatccggctctcgccgccgcgcagcc-tttgtgc-ttcgc
gtcgtgcgggc-taacgaacccc-ggcgcggaatgcgccaaggaaaac-ttaa-----tg
aagcgtcggccc--cctcgcaccccgttt-gcggtgcgtgcgg-ggggagcggatgtcta
t---cgaatgtcaaaacgactctcggcaacggatatctcggctctcgcatcgatgaagaa
cgtagcgaaatgcgatacttggtgtgaattgcagaatcccgtgaaccatcgagtctttga
acgcaagttgcgcccgaagccattaggccgagggcacgtctgcctgggcgtcacgcatcg
cgtcgcc-ccctct-cctcgtgccaaac-acg---cttggga------tggggggacgga
tattggcctcccgtgca-----ccccggtgcgtggttggcccaaatgcgatccctcgacg
actcttgtcacgacctgtggtggttg-aaaatctc---aa--tctcgcttcgtgtcgtgc
--tttcgagtcgttc-gtaagggctt-----cgaata-acgacccaatggcg-tcggtgc
gatatcgcgctgtgcgctttcgacc
