>Suillaceae_sp__9_ENYO_j_19_DQ351501_1 Suillaceae_sp._9_ENYO_j_19_DQ351501.1 695 bp 
----------------------------------------------------ggaaaggc
gg-ag-agttgtagctggccct-------a-ggca-tgtgcacgctctcttct-gga-ct
ttcgccg-tatgggc-gcggggcga------cccgcgtcttc--atatacctcttcgtgt
agaaagtctttgaatgtt--tttacgatcatcgagtcgtgacttctaggagacgcgattc
tttgagacaaaag-ttattacaactttcagcaacggatctcttggctctcgcatcgatga
agaacgcagcgaatcgcgatatgtaatgtgaa-tgcagatctacagtgaatcatcgaatc
tttgaacgcaccttgcgctcctcggtgttccgaggagcatgcctgtttgagtgtcagtaa
attctcaacccctctcga-tttgcttcgagcgggtgcttggatggtgggggctgccggag
ac-ctggattcg-ttcaggactcgggctcctctgaaatgaattggcttgcggtcga-ctt
tcgactttgcatgacaaggcctttggcgtgataatgatcgccgttcgccgaagtgcacga
cag--aat-ggtcccgtgcctctaatgagtcgacgccttc----tggcg-tcttcc-tat
cgacgtttgacctcaaat
>Suillaceae_sp__ASH17_AY880932_1 Suillaceae_sp._ASH17_AY880932.1 695 bp 
-------------tgcggaggatcattaatg-aaattataatccgg-cga-gggaaaggc
gg-ag-agttgtagctggccct-------a-ggca-tgtgcacgctctcttct-gga-ct
ttcgccg-tatgggc-gcggggcga------cccgcgtcttc--atatacctcttcgtgt
agaaagtctttgaatgtt--tttacgatcatcgagtcgtgacttctaggagacgcgattc
tttgagacaaaag-ttattacaactttcagcaacggatctcttggctctcgcatcgatga
agaacgcagcgaatcgcgatatgtaatgtgaattgcagatctacagtgaatcatcgaatc
tttgaacgcaccttgcgctcctcggtgttccgaggagcatgcctgtttgagtgtcagtaa
attctcaacccctctcga-tttgcttcgagcgggtgcttggatggtgggggctgccggag
ac-ctggattcg-ttcaggactcgggctcctctgaaatgaattggcttgcggtcga-ctt
tcgactttgcatgacaaggcctttggcgtgataatgatcgccgttcgccgaagtgcacga
cag--aat-ggtcccgtgcctctaatgagtcgacgccttc----tggcg-tcttccttat
cgacgtttgacctcaaat
>Suillaceae_sp__Bioassay_DQ351503_1 Suillaceae_sp._Bioassay_DQ351503.1 701 bp 
-----------------------------------------ggcga-ggg-aaaaaggcg
ga-ag-agttgtagctggccct-------a-ggga-tgtgcacgctctcttct-tga-ct
ttcgccg-tatgggs-gcggggcga------cccgcgtcttc--atatacctcttcgtgt
agaaagtctttgaatgtt--tttacgatcatcgagtcgtgacttctaggagacgcgattc
tttgagacaaaag-ttattacaactttcagcaacggatctcttggctctcgcatcgatga
agaacgcagcgaatcgcgatatgtaatgtgaattgcagatctacagtgaatcatcgaatc
tttgaacgcaccttgcgctcctcggtgttccgaggagcatgcctgtttgagtgtcagtaa
attctcaacccctctcga-tttgcttcgagcgggtgcttggatggtgggggctgccggag
ac-ctggattcg-ttcaggactcgggctcctctgaaatgaattggcttgcggtcga-ctt
tcgactttgcatgacaaggcctttggcgtgataatgatcgccgttcgccgaagtgcacga
cag--aat-ggtcccgtkcctctaatgagtcg----------------------------
------------------
>Suillaceae_sp__R3190_EF458012_1 Suillaceae_sp._R3190_EF458012.1 695 bp 
------------------------------------------------------------
------agttgtagctggccct-------agggca-tgtgcacgctttcttct-gga-ct
ttcgccg-tatgggc-gcggggcga------cccgcgtcttc--atatacctcttcgtgt
agaaagtctttgaatgtt--tttacgatcatcgagtcgtgacttctaggagacgcgattc
tttgagacaaaag-ttattacaactttcagcaacggatctcttggctctcgcatcgatga
agaacgcagcgaatcgcgatatgtaatgtgaattgcagatctacagtgaatcatcgaatc
tttgaacgcaccttgcgctcctcggtgttccgaggagcatgcctgtttgagtgtcagtaa
attctcaacccctctcga-tttgcttcgagcgggtgcttggatggtgggggctgccggag
ac-ctggattcg-ttcaggactcgggctcctctgaaatgaattggcttgcggtcga-ctt
tcgactttgcatgacaaggcctttggcgtgataatgatcgccgttcgccgaagtgcacga
cag--aat-ggtcccgtgcctctaatgagtcgacgccttc----tggcg-tcttccttat
cgatgtttgacctcaaat
>Suillaceae_sp__Uncultured_AY587754_1 Suillaceae_sp._Uncultured_AY587754.1 695 bp 
---------------ggaaggatcattaatg-aaattataatccgg-cgaggggaaaggc
gg-agaagttgtagctggcctcc-----aggggca-tgtgcacgctgtcttcc-cgacct
ttcgccg-tatgggc-gcggggcga------cccgcgtcttc--atatacctcttcgtgt
agaaagtctttgaatgtt---atacgatcatcgagtcgcgacttctaggagacgcgattc
tttgagacaaaag-ttattacaactttcagcaacggatctcttggctctcgcatcgatga
agaacgcagcgaatcgcgatatgtaatgtgaattgcagatctacagtgaatcatcgaatc
tttgaacgcaccttgcgctcctcggtgttccgaggagcatgcctgtttgagtgtcagtaa
attctcaacccctctcga-tttgcttcga-cgggtgcttggatgttggaggctgccggag
acactggattcg-tccaggactcgggctcctcttaaatgaatcggctcgcggtcga-ctt
tcgactttgcatgacaaggcctttggcgtgataatgatcgccgttcgccgaagtgcacga
cag--aat-ggtcccgtgcctctaatgcgtcgacgcctctccgggggcg-tcttcctcat
tgacgtttgacctcaaat
>Suillaceae_sp__bioassay_Peay 695 bp 
--------------------------------aaattataatccgg-cga-gggaaaggc
gg-ag-agttgtagctggccct-------a-ggca-tgtgcacgctctcttct-gga-ct
ttcgccg-tatgggc-gcggggcga------cccgcgtcttc--atatacctcttcgtgt
agaaagtctttgaatgtt--tttacgatcatcgagtcgtgacttctaggagacgcgattc
tttgagacaaaag-ttattacaactttcagcaacggatctcttggctctcgcatcgatga
agaacgcagcgaatcgcgatatgtaatgtgaattgcagatctacagtgaatcatcgaatc
tttgaacgcaccttgcgctcctcggtgttccgaggagcatgcctgtttgagtgtcagtaa
attctcaacccctctcga-tttgcttcgagcgggtgcttggatggtgggggctgccggag
ac-ctggattcg-ttcaggactcgggctcctctgaaatgaattggcttgcggtcga-ctt
tcgactttgcatgacaaggcctttggcgtgataatgatcgccgttcgccgaagtgcacga
cag--aat-ggtcccgtgcctctaatgagtcgacgccttc----tggcg-tcttccttat
cgacgtttgacctcaaat
>Suillaceae_sp__ectomycorrhizal_root_tip_AF476994_1 Suillaceae_sp._ectomycorrhizal_root_tip_AF476994.1 695 bp 
-------------------aggacattaatg-aaattataatccgg-cgaggggaaaggc
gg-ag-agttgtagctggcctcc-----aggggca-tgtgcacgctctcttcc-ggacct
ttcgccg-tatgggc-gcggggcga------cccgcgtcttc--atatacctcttcgtgt
agaaagtctttgaatgtt---ttaccatcatcgagtcgcgacttctaggagacgcgattc
tttgagaaaaaag-ttattacaactttcagcaacggatctcttggctctcgcatcgatga
agaacgcagcgaatcgcgatatgtaatgtgaattgcagatctacagtgaatcatcgaatc
tttgaacgcaccttgcgctcctcggtgttccgaggagcatgcctgtttgagtgtcagtaa
attctcaacccctctcga-tttgcttcgagcgggtgcttggatgttgggggctgccggag
acactggattcg-tccaggactcgggctcctcttaaatgaatcggctcgcggtcga-ctt
tcgactttgcatgacaaggcctttggcgtgataatgatcgccgttcgccgaagtgcaaga
cag--aat-ggtcccgtgcctctaatgcgtcgacgcctct--aggggcg-tcttcctcat
tgacgtttgacctcaaat
>Suillaceae_sp__from_Rusca_Bioassay Suillaceae_sp._from_Rusca_Bioassay 695 bp 
----------------------------------------------------ggaaaggc
gg-agaggctgtagctggccccctg---gggggca-tgtgcacgctctcttcc-ggactt
ttcgccg-tatgggc-gcggggcga------cccgcgtcttc--atatacctcttcgtgt
agaaagtctttgaatgtt--atcatcatcatcgagtcgcgacttctaggagacgcgattc
tttgagacaaaag-ttattacaactttcagcaacggatctcttggctctcgcatcgatga
agaacgcagcgaatcgcgatatgtaatgtgaattgcagatctacagtgaatcatcgaatc
tttgaacgcaccttgcgctcctcggtgttccgaggagcatgcctgtttgagtgtcagtta
attctcaacccctctcga-tttgcttcgagagggtgcttggatgttgggggctgccggag
ac-ctggattcg-ttcaggactcgggctcctctgaaatgaatcggctcgcggtcga-ctt
tcgactttgcgcgacaaggcctttggcgtgataatgatcgccgttcgccgaagc------
------------------------------------------------------------
------------------
>Suillus_Glandulosipes_L54087_1 695 bp 
-gtaggtgaacctgcggaaggatcattaatg-aaattacaatccgg-cgaggggaaaggc
gg-ag-agttgtagctggcctcc-----aggggca-cgtgcacgctctcttcc-cgacct
ttcgtcg-tatgggc-gcggggcga------cccgcgtcttc--atgcgcctcttcgtgt
agaaagtctttgaatgtc--atcacgatcatcgagtcgcgacttctaggagacgcgattc
tttgagaaaaaag-ttattacaactttcagcaacggatctcttggctctcgcatcgatga
agaacgcagcgaatcgcgatatgtaatgtgaattgcagatctacagtgaatcatcgaatc
tttgaacgcaccttgcgctcctcggtgttccgaggagcatgcctgtttgagtgtcagtaa
attctcaacccctctcga-tttgtttcgagagggcgcttggatgttggaggctgccggag
acgctggattcg-tccaggactcgggctcctcttaaatgaatcggctagcggtcga-ctt
tcgactttgcatgacaaggcctttggcgtgataatgatcgccgttcgccgaagtgcaaga
cag--aac-ggtcccgcgcctctaatgcgtcgacgccttc--cggggcg-tcttcctcat
cgacgtttgacctcaaat
>Suillus_bellinii_AJ419216_1 698 bp 
-----------------------cattaatg-aaattataatccgg-cgagggaaaggaa
gg-ag-ggttgtagctggccct-------agggca-cgtgcacgctctctttctggactt
ttcgccg-tatgggcagtggggcaa------cccgcgtcttc--atatacctcttcgtgt
agaaagtctttgaacgtt--tttaccatcatcgagtcgcgacttccaggagacgcgattc
tttgagacaaaag-ttattacaactttcagcaacggatctcttggctctcgcatcgatga
agaacgcagcgaatcgcgatatgtaatgtgaattgcagatctacagtgaatcatcgaatc
tttgaacgcaccttgcgctcctcggtgttccgaggagcatgcctgtttgagtgtcagtaa
attctcaacccctctcga-tttgcttcgagcgggtgcttggatggtggaggctgccggag
ac--------ct-tccaggactcgggctcctctgaaatgaatcggcttgcggtcga-ctt
tcgactttgcatgacaaggcctttggcgtgataatgatcgccgttcgccgaagtgcacga
cag--aac-ggtcccgtgcctmtaatgcgtcgacgccttc---gggccg-tcttcctcat
tgacgtttgacctcaaat
>Suillus_brevipes_GQ249389 695 bp 
------gtgacctgcggaaggatcattaatg-aaattataatccgg-cga-gggaaaggc
gg-gg-agttgtagctggccct-------agggca-tgtgcacgctctcttct-gga-ct
ttcgccg-tatgggc-gcggggcga------cccgcgtcttc--atatacctcttcgtgt
agaaagtctttgaatgtt--atcatcatcatcgagtcgcgacttctaggagacgcgattc
tttgagacaaaag-ttattacaactttcagcaacggatctcttggctctcgcatcgatga
agaacgcagcgaatcgcgatatgtaatgtgaattgcagatctacagtgaatcatcgaatc
tttgaacgcaccttgcgctcctcggtgttccgaggagcatgcctgtttgagtgtcagtaa
attctcaacccctctcga-tttgcttcgaaagggtgcttggatgttgggggctgccggag
acactggattcg-tccaggactcgggctcctcttaaatgaatcggcttgcggtcga-ctt
tcgactttgcatgacaaggcctttggcgtgataatgatcgccgttcgccgaagtgcaaga
cag--aac-ggtcccgtgcctctaatgcgtcgacgcctct-cggggccg-tcttcctcat
tgacgtttgacctcaaat
>Suillus_brevipes_L54111_1 698 bp 
-gtaggtgaacctgcggaaggatcattaatg-aaattataatccgg-cga-gggaaaggc
gg-ag-agttgtagctggcccc-------agggca-tgtgcacgctctcttcc-gga-ct
ttcgccg-tatgggc-gcggggcga------cccgcgtcttc--atatacctcttcgtgt
agaaagtctttgaatgtt--attaccatcatcgagtcgcgacttctaggagacgcgattc
tttgagacaaaag-ttattacaactttcagcaacggatctcttggctctcgcatcgatga
agaacgcagcgaatcgcgatatgtaatgtgaattgcagatctacagtgaatcatcgaatc
tttgaacgcaccttgcgctcctcggtgttccgaggagcatgcctgtttgagtgtcagtaa
attctcaacccctctcga-tttgcttcgaaagggcgcttggatgttgggggctgccggag
acactggactcg-tccaggactcgggctcctcttaaatgaatcggcttgcggtcga-ctt
tcgactttgcatgacaaggcctttggcgtgataatgatcgccgttcgccgaagtgcaaga
cag--aac-ggtcccgtgcctctaaygcgtcgacgcctct-cggggccg-tcttcctcat
tgacgtttgacctcaaat
>Suillus_brevipes_TDB1619_GQ249388 Suillus_brevipes_TDB1619_GQ249388 695 bp 
------gtgacctgcggaaggatcattaatg-aaattataatccgg-cga-gggaaaggc
gg-gg-agttgtagctggccct-------agggca-tgtgcacgctctcttct-gga-ct
ttcgccg-tatgggc-gcggggcga------cccgcgtcttc--atatacctcttcgtgt
agaaagtctttgaatgtt--atcatcatcatcgagtcgcgacttctaggagacgcgattc
tttgagacaaaag-ttattacaactttcagcaacggatctcttggctctcgcatcgatga
agaacgcagcgaatcgcgatatgtaatgtgaattgcagatctacagtgaatcatcgaatc
tttgaacgcaccttgcgctcctcggtgttccgaggagcatgcctgtttgagtgtcagtaa
attctcaacccctctcga-tttgcttcgaaagggtgcttggatgttgggggctgccggag
acactggattcg-tccaggactcgggctcctcttaaatgaatcggcttgcggtcga-ctt
tcgactttgcatgacaaggcctttggcgtgataatgatcgccgttcgccgaagtgcaaga
cag--aac-ggtcccgtgcctctaatgcgtcgacgcctct-cggggccg-tcttcctcat
tgacgtttgacctcaaat
>Suillus_brevipes_TRH664_AY880941_1 Suillus_brevipes_TRH664_AY880941.1 698 bp 
-gtaggtgaacctgcggaaggatcattaatg-aaattataatccgg-cga-gggaaaggc
gg-ag-agttgtagctggccct-------agggcaytgtgcacgctctcttcc-gga-ct
ttcgccg-tatgggc-gcggggcga------cccgcgtcttc--atatacctcttcgtgt
agaaagtctttgaatgtt--attaccatcatcgagtcgcgacttctaggagacgcgattc
tttgagacaaaag-ttattacaactttcagcaacggatctcttggctctcgcatcgatga
agaacgcagcgaatcgcgatatgtaatgtgaattgcagatctacagtgaatcatcgaatc
tttgaacgcaccttgcgctcctcggtgttccgaggagcatgcctgtttgagtgtcagtaa
attctcaacccctctcga-tttgcttcgacagggtgcttggatgttgggggctgccggag
acactggattcg-tccaggactcgggctcctcttaaatgaatcggcttgcggtcga-ctt
tcgactttgcatgacaaggcctttggcgtgataatgatcgccgttcgccgaagtgcaaga
cag--aac-ggtcccgtgcctctaatgcgtcgacgcctct-cggggccg-tcttcctcat
tgacgtttgacctcaaat
>Suillus_collinitus_ECM_48_AJ410857_1 Suillus_collinitus_ECM_48_AJ410857.1 695 bp 
------------------agttacattaacg-aaaaagcaatccgg-cga-gggaaaggc
gg-ag-agttgtagctggccct-------aggcaa-cgtgcacgctctcttct-gga-ct
ttcgtcg-tatgggc-gtgggggggcgacccctcgcgtcttc--atatacctcttcgtgt
agaaagtctttgaatgtc--atcatcatcatggagtcgcgacttccaggagacgcgattc
tttgagacaaaag-ttattacaactttcagcaacggatctcttggctctcgcatcgatga
agaacgcagcgaatcgcgatatgtaatgtgaattgcagatctacagtgaatcatcgaatc
tttgaacgcaccttgcgctcctcggtgttccgaggagcatgcctgtttgagcgtcagtaa
attctcaacccctctcgattttttttcgtgcgggtgcttggatggtgggggctgccggag
-acctggatacg-ttcaggactcgggctcctctgaaatgaatcggcttgcggtcgacttt
tcgactttgcatgacaaggcctttggcgtgataatgatcgccg-tcgccgaagtgcacga
cag--aatccgtcccgtgc-----------------------------------------
------------------
>Suillus_collinitus_L54089_1 695 bp 
-gtaggtgaacctgcggaaggatcattaatgaaaaatgcaatccgg-cga-gggaaaggc
gg-ag-agttgtagctggccct-------aggcaa-cgtgcacgctctcttct-gga-ct
ttcgtcg-tatgggc-gtgggggggcgacccctcgcgtcttc--atatacctcttcgtgt
agaaagtctttgaatgtc--atcatcatcatggagtcgcgacttccaggagacgcgattc
tttgagacaaaag-ttattacaactttcagcaacggatctcttggctctcgcatcgatga
agaacgcagcgaatcgcgatatgtaatgtgaattgcagatctacagtgaatcatcgaatc
tttgaacgcaccttgcgctcctcggtgttccgaggagcatgcctgtttgagcgtcagtaa
attctcaacccctctcgattttttttcgtgcgggtgcttggatggtgggggctgccggag
-acctggatacg-ttcaggactcgggctcctctgaaatgaatcggcttgcggtcgacttt
tcgactttgcatgacaaggcctttggcgtgataatgatcgccgttcgccgaagtgcacga
cag--aat-cgtcccgtgcctctaatgcgtcgacgccttc--cggggcg-tcttccttat
cgacgtttgacctcaaat
>Suillus_flavidsus_unite_UDB001214 Suillus_flavidsus_unite_UDB001214 695 bp 
cgtaggtgaacctgcggaaggatcattaatg-aatttataatccgg-cga-gacgaagga
cg-ag-gactgtcgctggccttca--accgaggca-tgtgcacgctctcttct-gga-ct
ttcgccg-tatgggc-gcggggcga------cccgcgtcttc--atatacctcttcgtgt
agaaagtcttcgaatgtt--tttaccatcatcgagtcgcgacttctaggagacgcgattc
tttgagacaaaag-ttatcacaactttcagcaatggatctcttggctctcgcatcgatga
agaacgcagcgaatcgcgatatgtaatgtgaattgcagatctacagtgaatcatcgaatc
tttgaacgcaccttgcgctcctcggtgttccgaggagcatgcctgtttgagcgtcagtaa
attctcaacccctctcga-tttgcttcgagtggg-gcttggatagtgggggctgccggag
acctgaaattcatttcgggactcgggctcctctgaaatgcatcggcttgcggtcga-ctt
tcgactttgcgcgacaaagctttcggcgtgataatgatcgccgttcgctgaagcgcatca
atg--aac-cgtcccgtgcctctaatcagtcgacgccttc---cgggcg-tcttccttat
agacgtttgacctcaaat
>Suillus_flavidsus_unite_UDB001648 Suillus_flavidsus_unite_UDB001648 695 bp 
cgtaggtgaacctgcggaaggatcattaatg-aatttataatccgg-cga-gacgaagga
cg-ag-gactgtcgctggccttca--accgaggca-tgtgcacgctctcttct-gga-ct
ttcgccg-tatgggc-gcggggcga------cccgcgtcttc--atatacctcttcgtgt
agaaagtcttcgaatgtt--tttaccatcatcgagtcgcgacttctaggagacgcgattc
tttgagacaaaag-ttatcacaactttcagcaatggatctcttggctctcgcatcgatga
agaacgcagcgaatcgcgatatgtaatgtgaattgcagatctacagtgaatcatcgaatc
tttgaacgcaccttgcgctcctcggtgttccgaggagcatgcctgtttgagcgtcagtaa
attctcaacccctctcga-tttgcttcgagtggg-gcttggatagtgggggctgccggag
acctgaaattcatttcgggactcgggctcctctgaaatgcatcggcttgcggtcga-ctt
tcgactttgcgcgacaaagctttcggcgtgataatgatcgccgttcgctgaagcgcatca
atg--aac-cgtcccgtgcctctaatcagtcgacgccttc---cgggcg-tcttccttat
agacgtt-----------
>Suillus_flavidsus_unite_UDB001649 Suillus_flavidsus_unite_UDB001649 695 bp 
cgtaggtg-acctgc-ggaggatcattaatg-aatttataatccgg-cga-gacgaagga
cg-ag-gactgtcgctggccttca--accgaggca-tgtgcacgctctcttct-gga-ct
ttcgccg-tatgggc-gcggggcga------cccgcgtcttc--atatacctcttcgtgt
agaaagtcttcgaatgtt--tttaccatcatcgagtcgcgacttctaggagacgcgattc
tttgagacaaaag-ttatcacaactttcagcaatggatctcttggctctcgcatcgatga
agaacgcagcgaatcgcgatatgtaatgtgaattgcagatctacagtgaatcatcgaatc
tttgaacgcaccttgcgctcctcggtgttccgaggagcatgcctgtttgagcgtcagtaa
attctcaacccctctcga-tttgcttcgagtggg-gcttggatagtgggggctgccggag
acctgaaattcatttcgggactcgggctcctctgaaatgcatcggcttgcggtcga-ctt
tcgactttgcgcgacaaagctttcggcgtgataatgatcgccgttcgctgaagcgcatca
atg--aac-cgtcccgtgcctctaatcagtcgacgccttc---cgggcgttcttccttat
agacgtt-gacctcaaat
>Suillus_fluryi_AT313_AJ272407_1 Suillus_fluryi_AT313_AJ272407.1 695 bp 
cgtaggtgaacctgcggaaggatcattaatgaaaaacataatccgg-cga-gggaaaggc
gg-ag-agttgtagctggcct--------aggcaa-cgtgcacgctctcttcc-gga-ct
t---tcg-tatgggc-gtgggggggcgacccctcgcgtcttc--atatacctcttcgtgt
agaaagtcttagaatg-----tcatcatcatggagtcgcgacttccaggagacgcgattc
tttgagacaaaag-ttattacaactttcagcaacggatctcttggctctcgcatcgatga
agaacgcagcgaatcgcgatatgtaatgtgaattgcagatctacagtgaatcatcgaatc
tttgaacgcaccttgcgctcctcggtgttccgaggagcatgcctgtttgagcgtcagtaa
attctcaacccctctcga-tctttttcgagcgggcgcttggatggtgggggctgccggag
-acctggattcg-ttcaggactcgggctcctctgaaatgaatcggcttgcggtcgacttt
tcgactttgcatgacaaggcctttggcgtgataatgatcgccgttcgccgaagtgcacga
cag--aat-cgtcccgtgcctctaatgcgtcgacgccttt--cggggcg-tcttccttat
cgacgtttgacctcaaat
>Suillus_granulatus_AJ272408_1 695 bp 
cgtaggtgaacctgcggaaggatcattaatgaaaaacataatccgg-cga-gggaaaggc
gg-ag-agttgtagctggccc--------aggcaa-cgtgcacgctctcttct-gga-ct
ttcgtcg-tatgggc-gtgggggggcgacccctcgcgtcttc--atatacctcttcgtgt
agaaagtcttagaatgtc--atcatcatcatggagtcgcgacttccaggagacgcgattc
tttgagacaaaag-ttattacaactttcagcaacggatctcttggctctcgcatcgatga
agaacgcagcgaatcgcgatatgtaatgtgaattgcagatctacagtgaatcatcgaatc
tttgaacgcaccttgcgctcctcggtgttccgaggagcatgcctgtttgagcgtcagtaa
attctcaacccctctcga-tctttttcgagcgggcgcttggatggtgggggctgccggag
-acctggattcg-ttcaggactcgggctcctctgaaatgaatcggcttgcggtcgacttt
tcgactttgcatgacaaggcctttggcgtgataatgatcgccgttcgccgaagtgcacga
cag--aat-cgtcccgcgcctctaatgcgtcgacgccttt--cggggcg-tcttccttat
cgacgtttgacctcaaat
>Suillus_granulatus_AT307_AJ272409_1 Suillus_granulatus_AT307_AJ272409.1 695 bp 
--------aacctgcggaaggatcattaatg-aaattacaatccgg-c-a-gggaaaggc
gg-ag-agttgtagctggcccct-----ccgggca-tgtgcacgctctcttcc-gga-ct
ttcgccg-tatgggc-gcggggcga------cccgcgtcttc--atatacctcttcgtgt
agaaagtctttgaatgtc--gaaaccatcatcgagtcgcgacttctaggagacgcgattc
tttgagacaaaag-ttattacaactttcagcaacggatctcttggctctcgcatcgatga
agaacgcagcgaatcgcgatatgtaatgtgaattgcagatctacagtgaatcatcgaatc
tttgaacgcaccttgcgctcctcggtgttccgaggagcatgcctgtttgagtgtcagtaa
attctcaacccctctcga-tttgcttcgagagggcgcttggatggtggaggctgccggag
ac-ctggattcg-ttcaggactcgggctcctctgaaatgaatcggcttgcggtcga-cct
tcgactttgcatgacaaggcctttggcgtgataatgatcgccgttcgccgaagtgcacga
cagaaaac-ggtcccgcgcctctaatgcgtcgacgccttc---cgggcg-tcttcctcat
tgacgtttgacctcaaat
>Suillus_granulatus_Japan_AB284447_1 Suillus_granulatus_Japan_AB284447.1 695 bp 
----------------------------atg-aaattacaatccgg-cga-gggaaaggc
ggcag-agttgtagctggcccct-----ccaggca-tgtgcacgctctcttcc-gga-ct
ttcgtcg-tatgggc-gcggggcga------cccgcgtcttc--atatacctcttcgtgt
agaaagtctttgaatgtcaaaaaatcatcatcgagtcgcgacttctaggagacgcgattc
tttgagacaaaag-ttattacaactttcagcaacggatctcttggctctcgcatcgatga
agaacgcagcgaatcgcgatatgtaatgtgaattgcagatctacagtgaatcatcgaatc
tttgaacgcaccttgcgctcctcggtgttccgaggagcatgcctgtttgagtgtcagtaa
attctcaacccctctcga-tttgcttcgagagggcgcttggatggtggaggctgccggag
aacctggattcg-ttcaggactcgggctcctctgaaatgaatcggcttgcggtcga-cct
tcgactttgcatgacaaggcctttggcgtgataatgatcgccgttcgccgaagtgcacga
cag--aac-ggtcccgcgcctctaacgcgtcgacgccttc----tggcg-tcttcctta-
------------------
>Suillus_granulatus_L54076_1 695 bp 
--------aacctgcggaaggatcattaatg-aaattacaatccgg-cga-gggaaaggc
gg-ag-agttgtagctggcccct-----ccgggca-tgtgcacgctctcttcc-gga-ct
ttcgccg-tatgggc-gcggggcga------cccgcgtcttc--atatacctcttcgtgt
agaaagtctttgaatgtc--gaaaccatcatcgagtcgcgacttctaggagacgcgattc
tttgagacaaaag-ttattacaactttcagcaacggatctcttggctctcgcatcgatga
agaacgcagcgaatcgcgatatgtaatgtgaattgcagatctacagtgaatcatcgaatc
tttgaacgcaccttgcgctcctcggtgttccgaggagcatgcctgtttgagtgtcagtaa
attctcaacccctctcga-tttgcttcgagagggcgcttggatggtggaggctgccggag
ac-ctggattcg-ttcaggactcgggctcctctgaaatgaatcggcttgcggtcgaccct
tcgactttgcatgacaaggcctttggcgtgataatgatcgccgttcgccgaagtgcacga
cagaaaac-ggtcccgcgcctctaatgcgtcgacgccttc---cgggcg-tcttcctcat
tgacgtttgacctcaaat
>Suillus_granulatus_L54121_1 695 bp 
-gtaggtgaacctgcggaaggatcattaatgaaaaacataatctgg-cga-gggaaaggc
gg-ag-agttgtagctggcct--------aggcaa-cgtgcacgctctcttcc-gga-ct
ttcgtcg-tatgggc-gtgggggggcgacccctcgcgtcttc--atatacctcttcgtgt
agaaagtcttagaatgtt--atcatcatcatggagtcgcgacttccaggagacgcgattc
tttgagacaaaag-ttattacaactttcagcaacggatctcttggctctcgcatcgatga
agaacgcagcgaatcgcgatatgtaatgtgaattgcagatctacagtgaatcatcgaatc
tttgaacgcaccttgcgctcctcggtgttccgaggagcatgcctgtttgagcgtcagtaa
attctcaacccctctcga-tctttttcgagcgggcgcttggatggtgggggctgccggag
aacctggattcg-ttcaggactcgggctcctctgaaatgaatcggcttgcggtcgacttt
tcgactttgcacgacaaggcctttggcgtgataatgatcgccgttcgccgaagtgcacga
ccg--aat-cgtcccgtgcctctaatgcgtcgacgccttt--tggggcg-tcttccttat
cgacgtttgacctcaaat
>Suillus_granulatus_NA_L54113_1 698 bp 
-gtaggtgaacctgcggaaggatcattaacg-aattcacgattcgg-cgagggggaaggc
cg-ag-ggttgtagctggcctttttcaaagaggca-cgtgcacgctctcttccctaa-ct
ctcgccg-tatggggcgcggggcga------cccgcgtctttcatmtcacctcttcgtgt
agaaagtctttgaatgtt--tttaccatcatcgagtcgcgacttctaggagacgcgattc
tttgagacaaaagtttattacaactttcagcaatggatctcttggctctcgcatcgatga
agaacgcagcgaatcgcgatatgtaatgtgaattgcagatctacagtgaatcatcgaatc
tttgaacgcaccttgcgctcctcggtgttccgaggagcatgcctgttcgagcgtcagtaa
attctcaacccctctcga-tttgcttcgagagggcgcttggatgctgggggctgccggag
ac-ctggtttcg-tccaggactcgggctctcctgaaatgtatcggcttgcggtcga-cct
tcgactttgcgcgacaaggccttcggcgtgataatgatcgccgttcgccgaagcgcatga
atg--aac-cgtcccgcgcctccaatccgtcgacgctttc----gagcg-tcttcctcat
tgacgtttgacctcgaat
>Suillus_granulatus_S070_AJ272410_1 Suillus_granulatus_S070_AJ272410.1 695 bp 
cgtaggtgaacctgcggaaggatcattaatgaaaaacataatccgg-cga-gggaaaggc
gg-ag-agttgtagctggccc--------aggcaa-cgtgcacgctctcttcc-gga-ct
ttcgtcg-tatgggc-gtgggggggcgacccctcgcgtcttc--atatacctcttcgtgt
agaaagtcttagaatgtc--atcatcatcatggagtcgcgacttccaggagacgcgattc
tttgagacaaaag-ttattacaactttcagcaacggatctcttggctctcgcatcgatga
agaacgcagcgaatcgcgatatgtaatgtgaattgcagatctacagtgaatcatcgaatc
tttgaacgcaccttgcgctcctcggtgttccgaggagcatgcctgtttgagcgtcagtaa
attctcaacccctctcga-tctttttcgagcgggcgcttggatggtgggggctgccggag
-acctggattcg-ttcaggactcgggctcctctgaaatgaatcggcttgcggtcgacttt
tcgactttgcatgacaaggcctttggcgtgataatgatcgccgttcgccgaagtgcacga
cag--aat-cgtcccgtgcctctaatgcgtcgacgccttt--cggggcg-tcttccttat
cgacgtttgacctcaaat
>Suillus_granulatus_UniTe_UDB000650 Suillus_granulatus_UniTe_UDB000650 698 bp 
--------aacctgcggaaggatcattaatg-aaattacaatccgg-cga--gggaaggc
gg-ag-agttgtagctggcccct-----ccgggca-tgtgcacgctctcttcc-gga-ct
ttcgccg--atgggc-gcggggcga------cccgcgtcttc--atatacctcttcgtgt
agaaagtctttgaatgtc--gaaaccatcatcgagtcgcgacttctaggagacgcgattc
tttgagacaaaag-ttattacaa-tttcagcaacggatctcttggctctcgcatcgatga
agaacgcagcgaatcgcgatatgtaatgtgaattgcagatctacagtgaatcatcgaatc
tttgaacgcaccttgcgctcctcggtgttccgaggagcatgcctgtttgagtgtcagtaa
attctcaacccctctcga-tttgcttcgagagggcgcttggatggtggaggctgccggag
ac-ctggattcg-ttcaggactcgggctcctctgaaatgaatcggcttgcggtcga-cct
tcgactttgcatgacaaggcctttggcgtgataatgatcgccgttcgccgaagtgcacga
cagaaaay-ggtcccgcgcctctaatgcgtcgacgccttc---cgggcg-tcttcctcat
tgacgtttgacctcaaat
>Suillus_granulatus_Unite_UDB000666 Suillus_granulatus_Unite_UDB000666 695 bp 
--------aacctgcggaaggatcattaatg-aaattacaatccgg-cga-gggaaaggc
gg-ag-agttgtagctggcccct-----ccgggca-tgtgcacgctctcttcc-gga-ct
ttcgccg-tatgggc-gcggggcga------cccgcgtcttc--atatacctcttcgtgt
agaaagtctttgaatgtc--gaaaccatcatcgagtcgcgacttctaggagacgcgattc
tttgagacaaaag-ttattacaactttcagcaacggatctcttggctctcgcatcgatga
agaacgcagcgaatcgcgatatgtaatgtgaattgcagatctacagtgaatcatcgaatc
tttgaacgcaccttgcgctcctcggtgttccgaggagcatgcctgtttgagtgtcagtaa
attctcaacccctctcga-tttgcttcgagagggcgcttggatggtggaggctgccggag
ac-ctggattcg-ttcaggactcgggctcctctgaaatgaatcggcttgcggtcga-cct
tcgactttgcatgacaaggcctttggcgtgataatgatcgccgttcgccgaagtgcacga
cagaaaactggtcccgcgcctctaatgcgtcgacgccttc---cgggcg-tcttcctcat
tgacgtttgacctcaa--
>Suillus_luteus__AT253_AJ272411_1 Suillus_luteus__AT253_AJ272411.1 695 bp 
cgtaggtgaacctgcggaaggatcattaatg-aaattataatccgg-cgaggggaaaggc
gg-ag-ggttgtagctggcctct-----aggggca-tgtgcacgctctcttcc-ggacct
ttcgccg-tatgggc-gcggggcga------cccgcgtcttc--atatacctcttcgtgt
agaaagtctttgaatgtt---ttaccatcatcgagtcgcgacttctaggagacgcgattc
tttgagaaaaaag-ttatcacaactttcagcaacggatctcttggctctcgcatcgatga
agaacgcagcgaatcgcgatatgtaatgtgaattgcagatctacagtgaatcatcgaatc
tttgaacgcaccttgcgctcctcggtgttccgaggagcatgcctgtttgagtgtcagtaa
attctcaacccctctcga-tttgcttcgagcgggtgcttggatgttgggggctgccggag
acactggactcg-tccaggactcgggctcctcttaaatgaatcggctcgcggtcga-ctt
tcgactttgcatgacaaggcctttggcgtgataatgatcgccgttcgccgaagtgcaaga
cag--aat-ggtcccgtgcctctaatgcgtcgacgcctct--aggggcg-tcttcctcat
tgacgtttgacctcaaat
>Suillus_luteus__S084_AJ272414_1 Suillus_luteus__S084_AJ272414.1 695 bp 
cgtaggtgaacctgcggaaggatcattaatg-aaattataatccgg-cgaggggaaaggc
gg-ag-agttgtagctggcctct-----aggggca-tgtgcacgctctcttcc-ggacct
ttcgccg-tatgggc-gcggggcga------cccgcgtcttc--atatacctcttcgtgt
agaaagtctttgaatgtt---ttaccatcatcgagtcgcgacttctaggagacgcgattc
tttgagaaaaaag-tta-tacaactttcagcaacggatctcttggctctcgcatcgatga
agaacgcagcgaatcgcgatatgtaatgtgaattgcagatctacagtgaatcatcgaatc
tttgaacgcaccttgcgctcctcggtgttccgaggagcatgcctgtttgagtgtcagtaa
attctcaacccctctcga-tttgcttcgagcgggtgcttggatgttgggggctgccggag
acactggactcg-tccaggactcgggctcctcttaaatgaatcggctcgcggtcga-ctt
tcgactttgcatgacaaggcctttggcgtgataatgatcgccgttcgccgaagtgcaaga
cag--aat-ggtcccgtgcctctaatgcgtcgacgcctct--aggggcg-tcttcctcat
tgacgtttgacctcaaat
>Suillus_luteus__S108_AJ272415_1 Suillus_luteus__S108_AJ272415.1 695 bp 
cgtaggtgaacctgcggaaggatcattaatg-aaattataatccgg-cgaggggaaaggc
gg-ag-agttgtagctggcctct-----aggggca-tgtgcacgctctcttcc-ggacct
ttcgccg-tatgggc-gcggggcga------cccgcgtcttc--atacacctcttcgtgt
agaaagtctttgaatgtt---ttaccatcatcgagtcgcgacttctaggagacgcgattc
tttgagaaaaaag-ttattacaactttcagcaacggatctcttggctctcgcatcgatga
agaacgcagcgaatcgcgatatgtaatgtgaattgcagatctacagtgaatcatcgaatc
tttgaacgcaccttgcgctcctcggtgttccgaggagcatgcctgtttgagtgtcagtaa
attctcaacccctctcga-tttgcttcgagcgggtgcttggatgttgggggctgccggag
acactggattcg-tccaggactcgggctcctcttaaatgaatcggctcgcggtcga-ctt
tcgactttgcatgacaaggcctttggcgtgataatgatcgccgttcgccgaagtgcaaga
cag--aat-ggtcccgtgcctctaatgcgtcgacgcctct--aggggcg-tcttcctcat
tgacgtttgacctcaaat
>Suillus_luteus_L54083_1 695 bp 
-gtaggtgaacctgcggaaggatcattaatg-aaattataatccgg-cgaggggaaaggc
gg-ag-agttgtagctggcctcc-----aggggca-tgtgcacgctctcttcc-ggacct
ttcgccg-tatgggc-gcggg--ga------cccgcgtcttc--atatacctcttcgtgt
agaaagtctttgaatgtt---ttaccatcatcgagtcgcgacttctaggagacgcgattc
tttgagaaaaaag-ttattacaactttcagcaacggatctcttggctctcgcatcgatga
agaacgcagcgaatcgcgatatgtaatgtgaattgcagatctacagtgaatcatcgaatc
tttgaacgcaccttgcgctcctcggtgttccgaggagcatgcctgtttgagtgtcagtaa
attctcaacccctctcga-tttgcttcgagcgggtgcttggatgttgggggctgccggag
acactggattcg-tccaggactcgggctcctcttaaatgaatcggctcgcggtcga-ctt
tcgactttgcatgacaaggcctttggcgtgataatgatcgccgttcgccgaagtgcaaga
cag--aat-ggtcccgtgcctctaatgcgtcgacgcctct--aggggcg-tcttcctcat
tgacgtttgacctcaaat
>Suillus_luteus_L54100_1 695 bp 
-gtaggtgaacctgcggaaggatcattaatg-aaattataatccgg-cgaggggaaaggc
gg-ag-agttgtagctggcctcc-----aggggca-tgtgcacgctctcttcc-ggacct
ttcgccg-tatgggc-gcggg--ga------cccgcgtcttc--atatacctcttcgtgt
agaaagtctttgaatgtt---ttaccatcatcgagtcgcgacttctaggagacgcgattc
tttgagaaaaaag-ttattacaactttcagcaacggatctcttggctctcgcatcgatga
agaacgcagcgaatcgcgatatgtaatgtgaattgcagatctacagtgaatcatcgaatc
tttgaacgcaccttgcgctcctcggtgttccgaggagcatgcctgtttgagtgtcagtaa
attctcaacccctctcga-tttgcttcgagcgggtgcttggatgttgggggctgccggag
acactggattcg-tccaggactcgggctcctcttaaatgaatcggctcgcggtcga-ctt
tcgactttgcatgacaaggcctttggcgtgataatgatcgccgttcgccgaagtgcaaga
cag--aat-ggtcccgtgcctctaatgcgtcgacgcctct--aggggcg-tcttcctcat
tgacgtttgacctcaaat
>Suillus_luteus_L54110_1 695 bp 
-gtaggtgaacctgcggaaggatcattaatg-aaattataatccgg-cgaggggaaaggc
gg-ag-agttgtagctggcctct-----aggggca-tgtgcacgctctcttcc-ggacct
ttcgccg-tatgggc-gcggg--ga------cccgcgtcttc--atatacctcttcgtgt
agaaagtctttgaatgtt---ttaccatcatcgagtcgcgacttctaggagacgcgattc
tttgagaaaaaag-ttattacaactttcagcaacggatctcttggctctcgcatcgatga
agaacgcagcgaatcgcgatatgtaatgtgaattgcagatctacagtgaatcatcgaatc
tttgaacgcaccttgcgctcctcggtgttccgaggagcatgcctgtttgagtgtcagtaa
attctcaacccctctcga-tttgcttcgagcgggtgcttggatgttgggggctgccggag
acactggattcg-tccaggactcgggctcctcttaaatgaatcggctcgcggtcga-ctt
tcgactttgcatgacaaggcctttggcgtgataatgatcgccgttcgccgaagtgcaaga
cag--aat-ggtcccgtgcctctaatgcgtcgacgcctct--aggggcg-tcttcctcat
tgacgtttgacctcaaat
>Suillus_luteus_S009_AJ272413_1 695 bp 
cgtaggtgaacctgcggaaggatcattaatg-aaattataatccgg-cgaggggaaaggc
gg-ag-agttgtagctggcctc------aggggca-tgtgcacgctctcttcc-ggacct
ttcgccg-tatgggc-gcggggcga------cccgcgtcttc--atatacctcttcgtgt
agaaagtctttgaatgtt---ttaccatcatcgagtcgcgacttctaggagacgcgattc
tttgagaaaaaag-ttattacaactttcagcaacggatctcttggctctcgcatcgatga
agaacgcagcgaatcgcgatatgtaatgtgaattgcagatctacagtgaatcatcgaatc
tttgaacgcaccttgcgctcctcggtgttccgaggagcatgcctgtttgagtgtcagtaa
attctcaacccctctcga-tttgcttcgagcgggtgcttggatgttgggggctgccggag
acactggattcg-tccaggactcgggctcctcttaaatgaatcggctcgcggtcga-ctt
tcgactttgcatgacaaggcctttggcgtgataatgatcgccgttcgccgaagtgcaaga
cag--aat-ggtcccgtgcctctaatgcgtcgacgcctct--aggggcg-tcttcctcat
tgacgtttgacctcaaat
>Suillus_luteus_S193_AJ272416_1 695 bp 
cgtaggtgaacctgcggaaggatcattaatg-aaattataatccgg-cgaggggaaaggc
gg-ag-agttgtagctggcctct-----aggggca-tgtgcacgctctcttcc-ggacct
ttcgccg-tatgggc-gcggggcga------cccgcgtcttc--atatacctcttcgtgt
agaaagtctttgaatgtt---ttaccatcatcgagtcgcgacttctaggagacgcgattc
tttgagaaaaaag-ttattacaactttcagcaacggatctcttggctctcgcatcgatga
agaacgcagcgaatcgcgatatgtaatgtgaattgcagatctacagtgaatcatcgaatc
tttgaacgcaccttgcgctcctcggtgttccgaggagcatgcctgtttgagtgtcagtaa
attctcaacccctctcga-tttgcttcgagcgggtgcttggatgttgggggctgccggag
acactggactcg-tccaggactcgggctcctcttaaatgaatcggctcgcggtcga-ctt
tcgactttgcatgacaaggcctttggcgtgataatgatcgccgttcgccgaagtgcaaga
cag--aat-ggtcccgtgcctctaatgcgtcgacgcctct--aggggcg-tcttcctcat
tgacgtttgacctcaaat
>Suillus_luteus_Unite_UDB001650 695 bp 
cgtaggtgaacctgcggaaggatcattaatg-aaattataatccgg-cgaggggaaaggc
gg-ag-agttgtagctggcctct-----aggggca-tgtgcacgctctcttcc-ggacct
ttcgccg-tatgggc-gcggggcga------cccgcgtcttc--atatacctcttcgtgt
agaaagtctttgaatgtt---ttaccatcatcgagtcgcgacttctaggagacgcgattc
tttgagaaaaaag-ttattacaactttcagcaacggatctcttggctctcgcatcgatga
agaacgcagcgaatcgcgatatgtaatgtgaattgcagatctacagtgaatcatcgaatc
tttgaacgcaccttgcgctcctcggtgttccgaggagcatgcctgtttgagtgtcagtaa
attctcaacccctctcga-tttgcttcgagcgggtgcttggatgttgggggctgccggag
acactggattcg-tccaggactcgggctcctcttaaatgaatcggctcgcggtcga-ctt
tcgactttgcatgacaaggcctttggcgtgataatgatcgccgttcgccgaagtgcaaga
cag--aat-ggtcccgtgcctctaatgcgtcgacgcctct--aggggcg-tcttcctcat
tgacgtttgacctcaaat
>Suillus_mediterraneensis_AJ410860_1 Suillus_mediterraneensis_AJ410860.1 695 bp 
----------------------------------attataatccgg-cga-gggaaaggc
gggag-ggttgtagctggccttttt----cgggca-tgtgcacgctctcttct-gga-ct
ctcgtcgttatgggc-gcggggcga------cccgcgtctta---------ttcctttgg
aaaaggccaaggtttttt--tttaccatcatcgagtcgcgacttctaggagacgcgattc
tttgagacaaaag-ttattacaactttcagcaacggatctcttggctctcgcatcgatga
agaacgcagcgaatcgcgatatgtaatgtgaattgcagatctacagtgaatcatcgaatc
tttgaacgcaccttgcgctcctcggtgctccgaggagcatgcctgtttgagtgtcagtaa
attctcaacccctctcga-tttgcttcgagcgggtgcttggatggtgggggctgccggaa
cctggattcttg-ttcaggactcgggctcctctgaaatgaattggcttgcggtcga-ctt
tcgactttgcgcgacaaggcctttggcgtgataatgatcgccgttcgccgaaccacgaa-
-----aaa-ccgcccgcgcctttaacgcgtcgatgccttt--------ggcgtttcttat
tgacgtttgacctcaaat
>Suillus_neoalbidipes_AY880940_1 Suillus_neoalbidipes_AY880940.1 701 bp 
-gtaggtgaacctgcggaaggatcattaatg-aaattacaatccgg-cgaggggaaaggc
gg-ag-agttgtagctggcctcc-----aggggca-ygtgcacgctctcttcc-cgacct
ttcgtcg-tatgggc-gcggggcga------cccgcgtcttc--atgcgcctcttcgtgt
agaaagtctttgaatgtc--attacgatcatcgagtcgcgacttctaggagacgcgattc
tttgagaaaaaag-ttattacaactttcagcaacggatctcttggctctcgcatcgatga
agaacgcagcgaatcgcgatatgtaatgtgaattgcagatctacagtgaatcatcgaatc
tttgaacgcaccttgcgctcctcggtgttccgaggagcatgcctgtttgagtgtcagtaa
attctcaacccctctcga-tttgtttcgagagggcgcttggatgttggrggctgccggag
acgctggattcg-tccaggactcgggctcctcttaaatgaatcggctagcggtcga-ctt
tcgactttgcatgacaaggcctttggcgtgataatgatcgccgttcgccgaagtgcaaga
cag--aac-ggtcccgcgcctctaatgcgtcgacgccttc--cggggcg-tcttcctcat
cgacgtttgacctcaaat
>Suillus_neoalbidipes_L54112_1 695 bp 
-gtaggtgaacctgcggaaggatcattaatg-aaattacaatccgg-cgaggggaaaggc
gg-ag-agttgtagctggcctcc-----aggggca-cgtgcacgctctcttcc-cgacct
ttcgtcg-tatgggc-gcggggcga------cccgcgtcttc--atgcacctcttcgtgt
agaaagtctttgaatgtc--atcacgatcatcgagtcgcgacttctaggagacgcgattc
tttgagaaaaaag-ttattacaactttcagcaacggatctcttggctctcgcatcgatga
agaacgcagcgaatcgcgatatgtaatgtgaattgcagatctacagtgaatcatcgaatc
tttgaacgcaccttgcgctcctcggtgttccgaggagcatgcctgtttgagtgtcagt-a
attctcaacccctctcga-tttgtttcgagagggcgcttggatgttgg-ggctgccggag
acgctggattcg-tccaggactcgggctcctcttaaatgaatcggctagcggtcga-ctt
tcgactttgcatgacaaggcctttggcgtgataatgatcgccgttcgccgaagtgcaaga
cag--aac-tgtcccgcgcctctaatgcgtcgacgccttc--cggggcg-tcttcctcat
cgacgtttgacctcaaat
>Suillus_occidentalis_HDT28175_GQ249394 Suillus_occidentalis_HDT28175_GQ249394 695 bp 
------------------------------------------------------------
--------ttgtagctggcctct-----aggggca-tgtgcacgctgtcttcc-ggacct
ttcgccg-tatgggc-gcggggcga------cccgcgtcttc--atatacctcttcgtgt
agaaagtctttgaatgtt---atacgatcatcgagtcgcgacttctaggagacgcgattc
tttgagacaaaag-ttattacaactttcagcaacggatctcttggctctcgcatcgatga
agaacgcagcgaatcgcgatatgtaatgtgaattgcagatctacagtgaatcatcgaatc
tttgaacgcaccttgcgctcctcggtgttccgaggagcatgcctgtttgagtgtcagtaa
attctcaacccccctcga-tttgcttcgagcgggtgcttggatgttggaggctgccggag
acactggattcg-tccaggactcgggctcctct---------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------
>Suillus_occidentalis_STB1418_GQ249397 Suillus_occidentalis_STB1418_GQ249397 695 bp 
-----------------------------------ttataatccgg-cggcaggaaaggc
gg-ag-agttgtagctggcctct-----aggggca-tgtgcacgctgtcttcc-ggacct
ttcgccg-tatgggc-gcggggcga------cccgcgtcttc--atatacctcttcgtgt
agaaagtctttgaatgtt---atacgatcatcgagtcgcgacttctaggagacgcgattc
tttgagacaaaag-ttattacaactttcagcaacggatctcttggctctcgcatcgatga
agaacgcagcgaatcgcgatatgtaatgtgaattgcagatctacagtgaatcatcgaatc
tttgaacgcaccttgcgctcctcggtgttccgaggagcatgcctgtttgagtgtcagtaa
attctcaacc--------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------
>Suillus_occidentalis_STB82_GQ249396 Suillus_occidentalis_STB82_GQ249396 695 bp 
------------------------------------------------------------
----g-agttgtagctggcctct-----aggggca-tgtgcacgctgtcttcc-ggacct
ttcgccg-tatgggc-gcggggcga------cccgcgtcttc--atatacctcttcgtgt
agaaagtctttgaatgtt---atacgatcatcgagtcgcgacttctaggagacgcgattc
tttgagacaaaag-ttattacaactttcagcaacggatctcttggctctcgcatcgatga
agaacgcagcgaatcgcgatatgtaatgtgaattgcagatctacagtgaatcatcgaatc
tttgaacgcaccttgcgctcctcggtgttccgaggagcatgcctgtttgagtgtcagtaa
attctcaacccccctcga-tttgcttcgagcgggtgcttggatgttggaggctgccggag
acactg------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------
>Suillus_occidentalis_STB86_GQ249395 Suillus_occidentalis_STB86_GQ249395 695 bp 
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------tttgaatgtt---atacgatcatcgagtcgcgacttctaggagacgcgattc
tttgagacaaaag-ttattacaactttcagcaacggatctcttggctctcgcatcgatga
agaacgcagcgaatcgcgatatgtaatgtgaattgcagatctacagtgaatcatcgaatc
tttgaacgcaccttgcgctcctcggtgttccgaggagcatgcctgtttgagtgtcagtaa
attctcaacccccctcga-tttgcttcgagcgggtgcttggatgttggaggctgccggag
acactggattcg-tccaggactcgggctcctcttaaatgaat------------------
------------------------------------------------------------
------------------------------------------------------------
------------------
>Suillus_placidus_AB284443_1 695 bp 
----------------------------acg-aattcataattcgg-cga-ggggaaagc
gg-ag-ggttgtagctggccttttt-accgaggca-cgtgcacgctctcttcc-gaa-ct
ctcg-cg-tatgggc-gcggggcga------cccgcgtctttcatcccacctcttcgtgt
agaaagtctttgaatgtt--tttaccatcatcgagtcgcgacttctaggagacgcgattc
tttgagacaaaagtttattacaactttcagcaatggatctcttggctctcgcatcgatga
agaacgcagcgaatcgcgatatgtaatgtgaattgcagatctacagtgaatcatcgaatc
tttgaacgcaccttgcgctcctcggtgttccgaggagcatgcctgtttgagcgtcagtaa
attctcaacccctctcga-tttgcttcgagagggcgcttggatggtgggggctgccggag
ac-ctggattta-tcctggactcgggctctcctgaaatgcatcggcttgcggtcga-ctt
tcgactttgcgcgacaaggccttcggcgtgataatgatcgccgttcgccgaagcgcatga
atg--aac-ggtcccgcgcctctaatccgtcgacgctttc----gagcg-tcttcctca-
------------------
>Suillus_placidus_DQ407265_1 695 bp 
gttggctgaacctgcggaaggatcattaacg-aattcataattcgg-cga-ggggaaagc
gg-ag-ggttgtagctggccttttt-accgaggca-cgtgcacgctctcttcc-gaa-ct
ctcgtcg-tatgggc-gcggggcga------cccgcgtctttcatcccacctcttcgtgt
agaaagtctttgaatgtt--tttaccatcatcgagtcgcgacttctaggagacgcgattc
tttgagacaaaagtttattacaactttcagcaatggatctcttggctctcgcatcgatga
agaacgcagcgaatcgcgatatgtaatgtgaattgcagatctacagtgaatcatcgaatc
tttgaacgcaccttgcgctcctcggtgttccgaggagcatgcctgtttgagcgtcagtaa
attctcaacccctctcga-tttgcttcgagagggcgcttggatggtgggggctgccggag
ac-ctggatttatccctggactcgggctctcctgaaatgcatcggcttgcggtcga-ctt
tcgactttgcgcgacaaggccttcggcgtgataatgatcgccgttcgccgaagcgcatga
atg--aac-ggtcccgcgcctctattccgtcgacgctttc----gaccg-ttttcctcat
ggacgtttgacctcaatt
>Suillus_placidus_Japan_AB284441_1 Suillus_placidus_Japan_AB284441.1 695 bp 
----------------------------acg-aattcataattcgg-cga-ggggaaagc
gg-ag-ggttgtagctggccttttt-accgaggca-cgtgcacgctctcttcc-gaa-ct
ctcgccg-tatgggc-gcggggcga------cccgcgtctttcatcccacctcttcgtgt
agaaagtctttgaatgtt--tttaccatcatcgagtcgcgacttctaggagacgcgattc
tttgagacaaaagtttattacaactttcagcaatggatctcttggctctcgcatcgatga
agaacgcagcgaatcgcgatatgtaatgtgaattgcagatctacagtgaatcatcgaatc
tttgaacgcaccttgcgctcctcggtgttccgaggagcatgcctgtttgagcgtcagtaa
attctcaacccctctcga-tttgcttcgagagggcgcttggatggtgggggctgccggag
ac-ctggattta-tcctggactcgggctctcctgaaatgcatcggcttgcggtcga-ctt
tcgactttgcgcgacaaggccttcggcgtgataatgatcgccgttcgccgaagtgcatga
atg--aac-ggtcccgcgcctctaatccgtcgacgctctc----gagcg-tcttcctca-
------------------
>Suillus_placidus_Nepal_L54118_1 Suillus_placidus_Nepal_L54118.1 695 bp 
-gtaggtgaacctgcggaaggatcattaacg-aattcataattcgg-cga-ggggaaagc
gg-ag-ggttgtagctggccttttt-accgaggca-cgtgcacgctctcttcc-gaa-ct
ctcgtcg-tatgggc-gcggggcga------cccgcgtctttcatcccacctcttcgtgt
agaaagtctttgaatgtt--tttaccatcatcgagtcgcgacttctaggagacgcgattc
tttgagacaaaagtttattacaactttcagcaatggatctcttggctctcgcatcgatga
agaacgcagcgaatcgcgatatgtaatgtgaattgcagatctacagtgaatcatcgaatc
tttgaacgcaccttgcgctcctcggtgttccgaggagcatgcctgtttgagcgtcagtaa
attctcaacccctctcga-tttgcttcgagagggcgcttggatggtgggggctgccggag
ac-ctggatttatccctggactcgggctctcctgaaatgcatcggcttgcggtcga-ctt
tcgactttgcgcgacaaggccttcggcgtgataatgatcgccgttcgccgaagcgcagga
atg--aac-ggtcccgcgcctctaatccgtcgacgctttc----gagcg-tcttcctcat
tgacgtttgacctcaaat
>Suillus_placidus_North_Amer__L54108_1 Suillus_placidus_North_Amer._L54108.1 695 bp 
-gtaggtgaacctgcggaaggat-attaacg-aattcacgattcgg-cgagggggaaggc
cg-ag-ggttgtagctggcctttttcaaagaggca-cgtgcacgctctcttccctaa-ct
ctcgccg-tatgggc-gcgggga--------cccgcgtctttcatatcacctcttcgtgt
agaaagtctttgaatgtt--tttaccatcatcgagtcgcgacttctaggagacgcgattc
tttgagacaaaagtttattacaactttcagcaatggatctcttggctctcgcatcgatga
agaacgcagcgaatcgcgatatgtaatgtgaattgcagatctacagtgaatcatcgaatc
tttgaacgcaccttgcgctcctcggtgttccgaggagcatgcctgttcgagcgtcagtaa
attctcaacccctctcga-tttgcttcgagagggcgcttggatgctgggggctgccggag
ac-ctggtttcg-tccaggactcgggctctcctgaaatgtatcggcttgcggtcga-cct
tcgactttgcgcgacaaggccttcggcgtgataatgatcgccgttcgccgaagcgcatga
atg--aac-cgtcccgcgcctccaatccgtcgacgctttc----gagcg-tcttcctaat
tgacgtttgacctcgaat
>Suillus_pseudobrevipes_Ash_AY880938_1 Suillus_pseudobrevipes_Ash_AY880938.1 695 bp 
-gtaggtgaacctgcggaaggatcattaatg-aaattataatccgg-cgaggggaaaggc
gg-ag-agttgtagctggcctcc-----aggggca-tgtgcacgctgtcttcc-cgacct
ttcgccg-tatgggc-gcggggcga------cccgcgtcttc--atataccccttcgtgt
agaaagtctttgaatgtt---atacgatcatcgagtcgcgacttctaggagacgcgattc
tttgagacaaaag-ttattacaactttcagcaacggatctcttggctctcgcatcgatga
agaacgcagcgaatcgcgatatgtaatgtgaattgcagatctacagtgaatcatcgaatc
tttgaacgcaccttgcgctcctcggtgttccgaggagcatgcctgtttgagtgtcagtaa
attctcaacccctctcga-tttgcttcgagcgggtgcttggatgttggaggctgccggag
acactggattcg-tccaggactcgggctcctcttaaatgaatcggctcgcggtcga-ctt
tcgactttgcatgacaaggcctttggcgtgataatgatcgccgttcgccgaagtgcacga
cag--aat-ggtcccgtgcctctaatgcgtcgacgcctctccgggggcg-tcttcctcat
tgacgttgacctc-----
>Suillus_pseudobrevipes_L54107_1 Suillus_pseudobrevipes_L54107.1 695 bp 
-gtaggtgaacctgcggaaggatcattaatg-aaattataatccgg-cgaggggaaaggc
gg-ag-agttgtagctggcctcc-----aggggca-tgtgcacgctgtcttcc-cgacct
ttcgccg-tatgggc-gcggggcga------cccgcgtcttc--atatacctcttcgtgt
agaaagtctttgaatgtt---atacgatcatcgagtcgcgacttctaggagacgcgattc
tttgagacaaaag-ttattacaactttcagcaacggatctcttggctctcgcatcgatga
agaacgcagcgaatcgcgatatgtaatgtgaattgcagatctacagtgaatcatcgaatc
tttgaacgcaccttgcgctcctcggtgttccgaggagcatgcctgtttgagtgtcagtaa
attctcaacccctctcga-tttgcttcgagcgggtgcttggatgttggaggctgccggag
acactggattcg-tccaggactcgggctcctcttaaatgaatcggctcgcggtcga-ctt
tcgactttgcatgacaaggcctttggcgtgataatgatcgccgttcgccgaagtgcacga
cag--aat-ggtcccgtgcctctaatgcgtcgacgcctctccgggggcg-tcttcctcat
tgacgtttgacctcaaat
>Suillus_punGens_L54094_1 695 bp 
-gtaggtgaacctgcggaaggatcattaatg-aaattataatccgg-cga-gagaaaggc
gg-ag-agctgtagctggccccct----gggggca-tgtgcacgctctcttcc-ggactt
ttcgccg-tatgggc-gcggg--ga------cccgcgtcttc--atatacctcttcgtgt
agaaagtctttgaatgtt--atcatcatcatcgagtcgcgacttctaggagacgcgattc
tttgagacaaaag-ttattacaactttcagcaacggatctcttggctctcgcatcgatga
agaacgcagcgaatcgcgatatgtaatgtgaattgcagatctacagtgaatcatcgaatc
tttgaacgcaccttgcgctcctcggtgttccgaggagcatgcctgtttgagtgtcagtta
attctcaacccctctcga-tttgcttcgagagggtgcttggatgttgggggctgccggag
ac-ctggattcg-tccaggactcgggctcctctgaaatgaatcggctcgcggtcga-ctt
tcgactttgcgcgacaaggcctttggcgtgataatgatcgccgttcgccgaagcgcaaga
cag--aac-ggtcccgtgcctctaatgcgtcgacgccttc--cggggcg-tcttccttat
cgacgtttgacctcaaat
>Suillus_quiescens_GQ249390 695 bp 
-----gtgaacctgcggaaggatcattaatg-aaattataatccgg-cga-gggaaaggc
gg-ag-agttgtagctggccct-------a-ggca-tgtgcacgctctcttct-gga-ct
ttcgccg-tatgggc-gcggggcga------cccgcgtcttc--atatacctcttcgtgt
agaaagtctttgaatgtt--tttacgatcatcgagtcgtgacttctaggagacgcgattc
tttgagacaaaag-ttattacaactttcagcaacggatctcttggctctcgcatcgatga
agaacgcagcgaatcgcgatatgtaatgtgaattgcagatctacagtgaatcatcgaatc
tttgaacgcaccttgcgctcctcggtgttccgaggagcatgcctgtttgagtgtcagtaa
attctcaacccctctcga-tttgcttcgagcgggtgcttggatggtgggggctgccggag
ac-ctggattcg-ttcaggactcgggctcctctgaaatgaattggcttgcggtcga-ctt
tcgactttgcatgacaaggcctttggcgtgataatgatcgccgttcgccgaagtgcacga
cag--aat-ggtcccgtgcctctaatgagtcgacgccttc----tggcg-tcttccttat
cgacgtttgacctcaaat
>Suillus_quiescens_GQ249391 695 bp 
-----gtgaacctgcggaaggatcattaatg-aaattataatccgg-cga-gggaaaggc
gg-ag-agttgtagctggccct-------a-ggca-tgtgcacgctctcttct-gga-ct
ttcgccg-tatgggc-gcggggcga------cccgcgtcttc--atatacctcttcgtgt
agaaagtctttgaatgtt--tttacgatcatcgagtcgtgacttctaggagacgcgattc
tttgagacaaaag-ttattacaactttcagcaacggatctcttggctctcgcatcgatga
agaacgcagcgaatcgcgatatgtaatgtgaattgcagatctacagtgaatcatcgaatc
tttgaacgcaccttgcgctcctcggtgttccgaggagcatgcctgtttgagtgtcagtaa
attctcaacccctctcga-tttgcttcgagcgggtgcttggatggtgggggctgccggag
ac-ctggattcg-ttcaggactcgggctcctctgaaatgaattggcttgcggtcga-ctt
tcgactttgcatgacaaggcctttggcgtgataatgatcgccgttcgccgaagtgcacga
cag--aat-ggtcccgtgcctctaatgagtcgacgccttc----tggcg-tcttccttat
cgacgtttgacctcaaat
>Suillus_quiescens_GQ249393 695 bp 
-----gtgaacctgcggaaggatcattaatg-aaattataatccgg-cga-gggaaaggc
gg-ag-agttgtagctggccct-------a-ggca-tgtgcacgctctcttct-gga-ct
ttcgccg-tatgggc-gcggggcga------cccgcgtcttc--atatacctcttcgtgt
agaaagtctttgaatgtt--tttacgatcatcgagtcgtgacttctaggagacgcgattc
tttgagacaaaag-ttattacaactttcagcaacggatctcttggctctcgcatcgatga
agaacgcagcgaatcgcgatatgtaatgtgaattgcagatctacagtgaatcatcgaatc
tttgaacgcaccttgcgctcctcggtgttccgaggagcatgcctgtttgagtgtcagtaa
attctcaacccctctcga-tttgcttcgagcgggtgcttggatggtgggggctgccggag
ac-ctggattcg-ttcaggactcgggctcctctgaaatgaattggcttgcggtcga-ctt
tcgactttgcatgacaaggcctttggcgtgataatgatcgccgttcgccgaagtgcacga
cag--aat-ggtcccgtgcctctaatgagtcgacgccttc----tggcg-tcttccttat
cgacg-ttgacctcaaat
>Suillus_sp__Uncultured_EF619768_1 Suillus_sp._Uncultured_EF619768.1 695 bp 
-----------------------cattaatg-aaattacaatccgg-cga-gggaaaggc
gg-gg-agttgtagctgcccc--------agggca-tgtgcacgctctcttcc-gga-ct
ttcgccg-tatgggc-gc-gggcga------cccgcgtcttc--atatacctcttcgtgt
agaaagtctttgaatgtt--atcatcatcatcgagtcgcgacttctaggagacgcgattc
tttgaga-aaaag-ttattacaactttcagcaacggatctcttggctctcgcatcgat-a
agaacgcagcgaatcgcgatatgtaatgtgaattgcagatctacagtgaatcatcgaatc
tttgaacgcaccttgcgctcctcggtgttccgaggagcatgcctgtttgagtgtcagtaa
attctcaacccctctcga-tttgcttcgacagggcgcttggatgttgggggctgccggag
acactggattcg-tccaggactcgggctcctcttaaatgaatcggcttgcggtcga-ctt
tcgactttgcgcgacaaggcctttggcgtgataatgatcgccgttcgccgaagtgcaaga
cag--aac-ggtcccgtgcctctaatgcgtcgacgcctct-cggggccg-tcttcctcat
tgacgtttgacctcaaat
>Suillus_volcanalis_HDT12800_holoType_GQ249399 Suillus_volcanalis_HDT12800_holoType_GQ249399 695 bp 
cgtaggtgaacctgcggaaggatcattaatg-aaattataatccgg-cgaggggaaaggc
gg-ag-agttgtagctggcctcc-----aggggca-tgtgcacgctgtcttcc-cgacct
ttcgccg-tatgggc-gcggggcga------cccgcgtcttc--atatacctcttcgtgt
agaaagtctttgaatgtt---atacgatcatcgagtcgcgacttctaggagacgcgattc
tttgagacaaaag-ttattacaactttcagcaacggatctcttggctctcgcatcgatga
agaacgcagcgaatcgcgatatgtaatgtgaattgcagatctacagtgaatcatcgaat-
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------
>Suillus_volcanalis_HDT39873_GQ249398 Suillus_volcanalis_HDT39873_GQ249398 695 bp 
-----------------------------------ttataatccggccgaggggaaaggc
gg-ag-agttgtagctggcctcc-----aggggca-tgtgcacgctgtcttcc-cgacct
ttcgccg-tatgggc-gcggggcga------cccgcgtcttc--atataccccttcgtgt
agaaagtctttgaatgtt---atacgatcatcgagtcgcgacttctaggagacgcgattc
tttgagacaaaag-ttattacaactttcagcaacggatctcttggctctcgcatcgatga
agaacgcagcgaatcgcgatatgtaatgtgaattgcagatctacagtgaatcatcgaatc
tttgaacgcaccttgcgctcctcggtgttccgaggagcatgcctgtttgagtgtcagtaa
attctcaacccctctcga-tttgcttcgagcgggtgcttggatgttggaggctgccggag
acgctggattcg-tccaggactcgggctcctcttaaatgaatcggctcgcggtcga-ctt
tcgactttgcatgacaaggcctttggcgtgataatgatcgccgttcgccgaagtgcacga
cag--aat-ggtcccgtgcctctaatgcgtcgacgcctctccgggggcg-tcttcctcat
tgacgtttgacctcaaat
>Suillus_weaverae_L54091_1 701 bp 
-gtaggtgaacctgcggaaggatcattaatg-aaattataatccgg-cga-gggaaaggc
gg-ag-agttgtagctggcccc-------agggca-tgtgcacgctctcttcc-gga-ct
ttcgccg-tatgggc-gcggggcga------cccgcgtcttc--atatacctcttcgtgt
agaaagtctttgaatgtt--attaccatcatcgagtcgcgacttctaggagacgcgattc
tttgagacaaaag-ttattacaactttcagcaacggatctcttggctct-----------
---------cgaatcgcgatatgtaatgtgaattgcagatctacagtgaatcatcgaatc
tttgaacgcaccttgcgctcctcggtgttccgaggagcatgcctgtttgagtgtcagtaa
attctcaacccctctcga-tttgcttcgawagggygcttggatgttgggggctgccggag
acactggattcg-tccaggactcgggctcctcttaaatgaatcggcttgcggtcga-ctt
tcgactttgcatgacaaggcctttggcgtgataatgatcgccgttcgccgaagtgcaaga
cag--aac-ggtcccgtgcctctaatgcgtcgacgcctct-cggggccg-tcttcctcat
tgacgtttgacctcaaat
>END; 1 bp 
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------n
>nameless_1 1 bp 
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------n
