>Batcheloromyces_eucalypti 700 bp 
------------------------------------------------------------
--------------------------------------------------------tcca
taaggtgaacctgcgaagggatcataacaaaatgagggggta---agccc----------
-gacctcaaacccttt-gtg----tccc--aaccatgttgcctcaggggtaaacaggccc
a-------------gagccggggcccccggtgg---acccc---caactttatatc---t
-ttgcgtctgagca-acggaaaac----caatcaatcaaaactttcaacaacggatctct
tggttctggcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaatt
cagtgaatcatcgaatctttgaacgcatattgcgccctctggcattccggagggcatgcc
tgttcgagcgtcatttcaccactccagc-cccgctggg-tcttgggcg-ctgcgg-----
cctgcccgcgcgcctcaaagtc-tc---cggccgagccg-accgtctc-caagcgttgtg
accataacgggttcgcttccgggacc-aggtccgg-cgccgcgccgtg--aaaacctt--
ccgcaaaaggttaacatcggatcaggtagggata---------------------
>Cladosporium_sphaerospermum 700 bp 
------------------------------------------------------------
------------------------------------------------------------
----------------agggatcattac-aagtga----ccc-ccggctc-cggccgggg
atgttcataacccttt-gtt----gtcc--gactctgttgcctccggggcgaccctgcct
tttc--------acgggcgggggccccgggtgg---acacat--caaaactcttgc---g
-taactttgcagtctgagtaaatttaattaataaattaaaactttcaacaacggatctct
tggttctggcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaatt
cagtgaatcatcgaatctttgaacgcacattgcgccccctggtattccggggggcatgcc
tgttcgagcgtcatttcaccactcaagc-ctcgcttgg-tattgggcg-acgcgg-----
-tccgccgcgcgcctcaaatcg-ac---cggctgggtct-tctgtcccctcagcgttgtg
g----aaactattcgctaaagggtg--ccacggga-ggccacgccgaa--aaacaaaccc
atttctaaggttgacctcggatcaggtagg-------------------------
>Mycosphaerella_ellipsoidea 700 bp 
------------------------------------------------------------
------------------------------------------------------------
------gaacctgcggagggatcattactgagtgagggctca---cgccc----------
-gacctccaacccttt-gtg----aacc--aactctgttgcttcgggggcgaccccgccg
tttc---------ggcgacggcgcccccggagg----tcatc--aaacactgcatc---t
-ttgcgtcggagtc---ttaaagt---aaatttaaacaaaactttcaacaacggatctct
tggttctggcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaatt
cagtgaatcatcgaatctttgaacgcacattgcgccccgtggtattccgcggggcatgcc
tgttcgagcgtcatttcaccactcaagc-ctagcttgg-tattgggcg-tcgcgg-----
---ttccgcgcgccttaaagtc-tc---cggctgagcag-ttcgtctc-taagcgttgtg
g---catatatttcgctgaagagtt--cggacggcttt--tggccgtt--aaatcttt--
---cttaaggttgacctcggatcaggtagggata---------------------
>Mycosphaerella_gracilis_DQ302960 Mycosphaerella_gracilis_DQ302960 700 bp 
------------------------------------------------------------
------------------------------------------------------------
---ggtgaacctgcggagggatcattactgagtgagggctca---cgccc----------
-gacctccaacccttt-gtg----aaca--catcttgttgcttcgggggcgaccctgccg
gc-actacgtcgccg----ggcgcccccggagg----tctcc--aaacactgcatc---t
-ttgcgtcggagtt---t--aaac---a-aattaaacaaaactttcaacaacggatctct
tggttctggcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaatt
cagtgaatcatcgaatctttgaacgcacattgcgccctttggtattccgaagggcatgcc
tgttcgagcgtcatttcaccactcaagc-ctggcttgg-tattgggcg-tcgcgg-----
---ctccgcgcgccttaaagtc-tc---cggctgagcca-ttcgtctc-taagcgttgtg
g-attttctaattcgcttcggagtg--cgggtggc-cg--cggccgtt--aaatcttt--
-attgaaaggttgacctcggatcaggtagg-------------------------
>Mycosphaerella_heimii_AF309606 700 bp 
------------------------------------------------------------
---------------------------------------------------------tcc
gtaggtgaacctgcggagggatcattactgagtgagggcta----ggtcc----------
-gacctccaacccttt-gtg----aacc--aaacttgttgcttcgggggcgaccctgccg
cttg-------ggcggtgcggcgcccccggagg----ccatt--aaacactgcatc---a
-ttgcgtcggagta-----aaagt----aaattaaacaaaactttcaacaacggatctct
tggttccagcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaatt
cagtgaatcatcgaatctttgaacgcacattgcgccctctggtattccggggggcatgcc
tgttcgagcgtcatttcaccactcaagc-ctggcttgg-tattgggcg-tcgcgg-----
---ctccgcgcgccttaaagtcttc---cggctgagctg-tccgtctc-taagcgttgtg
g----caactattcgcttcggaggt--cgggtggc-cg--cggccgtt--aaatcttt--
---cacaaggttgacctcggatcaggtagggata---------------------
>Mycosphaerella_heimii_TH004C 700 bp 
--------------gtgaggccttcggactggcccagggaggtcggcaacgaccacccag
ggccggaaagttggtcaaactcggtcatttagaggaagtaaaagtcgtaacaaggtctcc
gtaggtgaacctgcggagggatcattactgagtgagggctac---ggtcc----------
-gacctccaacccttt-gtg----aacc-aaaacttgttgcttcgggggcgaccctgccg
cttc-------ggcggtgcggcgcccccggagg----ccatt--aaacactgcatc---a
-ttgcgtcggagta-----aaagt----aaattaaacaaaactttcaacaacggatctct
tggttccagcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaatt
cagtgaatcatcgaatctttgaacgcacattgcgccctctggtattccggggggcatgcc
tgttcgagcgtcatttcaccactcaagc-ctggcttgg-tattgggcg-tcgcgg-----
---ctccgcgcgccttaaagtcttc---cggctgagctg-tccgtctc-taagcgttgtg
g----caactattcgcttcggaggt--cgggtggc-cg--cggccgtt--aaatcttt--
---cacaaggttgacctcggatcaggtagggatacccgctgaacttaagcatatc
>Mycosphaerella_heimii_TH004D 700 bp 
gattgaatggctcagtgaggccttcggactggcccagggaggtcggcaacgaccacccag
ggccggaaagttggtcaaactcggtcatttagaggaagtaaaagtcgtaacaaggtctcc
gtaggtgaacctgcggagggatcattactgagtgagggctac---ggtcc----------
-gacctccaacccttt-gtg----aacc---aacttgttgcttcgggggcgaccctgccg
cttc-------ggcggtgcggcgcccccggagg----ccatt--aaacactgcatc---a
-ttgcgtcggagta-----aaagt----aaattaaacaaaactttcaacaacggatctct
tggttccagcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaatt
cagtgaatcatcgaatctttgaacgcacattgcgccctctggtattccggggggcatgcc
tgttcgagcgtcatttcaccactcaagc-ctggcttgg-tattgggcg-tcgcgg-----
---ctccgcgcgccttaaagtcttc---cggctgagctg-tccgtctc-taagcgttgtg
g----caactattcgcttcggaggt--cgggtggc-cg--cggccgtt--aaatcttt--
---cacaaggttgacctcggatcaggtagggatacccgctgaacttaagcatatc
>Mycosphaerella_heimii_TH089 700 bp 
gattgaatggctcagtgaggccttcggactggcccagggaggtcggcaacgaccacccag
ggccggaaagttggtcaaactcggtcatttagaggaagtaaaagtcgtaacaaggtctcc
gtaggtgaacctgcggagggatcattactgagtgagggctac---ggtcc----------
-gacctccaacccttt-gtg----aacc--aaacttgttgcttcgggggcgaccctgccg
cttc-------ggcggtgcggcgcccccggagg----ccatt--aaacactgcatc---a
-ttgcgtcggagta-----aaagt----aaattaaacaaaactttcaacaacggatctct
tggttccagcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaatt
cagtgaatcatcgaatctttgaacgcacattgcgccctctggtattccggggggcatgcc
tgttcgagcgtcatttcaccactcaagc-ctggcttgg-tattgggcg-tcgcgg-----
---ctccgcgcgccttaaagtcttc---cggctgagctg-tccgtctc-taagcgttgtg
g----caactattcgcttcggaggt--cgggtggc-cg--cggccgtt--aaatcttt--
---cacaaggttgacctcggatcaggtagggatacccgctgaacttaagcatatc
>Mycosphaerella_irregulari_TH003 Mycosphaerella_irregulari_TH003 700 bp 
gattgaatggctcagtgaggccttcggactggcccagggaggtcggcaacgaccacccag
ggccggaaagttggtcaaactcggtcatttagaggaagtaaaagtcgtaacaaggtctcc
gtaggtgaacctgcggagggatcattaccgagtgagggcccc--cggccc----------
-gacctccaacccttt-gtg----aactcacatctcgttgcttcgggggcgaccctgccg
ttcg-----cggc-c--gcggcgcccccggggg----atact--taacactgcatc---a
-ttgcgtcggagtct--tttatgtaaatca--tgaacaaaactttcaacaacggatctct
tggttctggcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaatt
cagtgaatcatcgaatctttgaacgcacattgcgccccgtggtattccgcggggcatgcc
tgttcgagcgtcatttcaccactcgagt-ctgactcgg-tattgggcg-ccgcg------
cactgccgcgcgcctcaaagtt-tc---cggctgggcggacccgtccc-cgagcgttgtg
gcatcacagttctcgcctgggagtcg-cgggttgg-cttgcggccgtt--aaacacac--
ccatcaaaggttgacctcggatcaggtagggatacccgctgaacttaagcatatc
>Mycosphaerella_irregulari_TH003_2 Mycosphaerella_irregulari_TH003.2 700 bp 
gattgaatggctcagtgaggccttcggactggcccagggaggtcggcaacgaccacccag
ggccggaaagttggtcaaactcggtcatttagaggaagtaaaagtcgtaacaaggtctcc
gtaggtgaacctgcggagggatcattaccgagtgagggcccc--cggccc----------
-gacctccaacccttt-gtg----aactcacatctcgttgcttcgggggcgaccctgccg
ttcg-----cggc-c--gcggcgcccccggggg----atact--taacactgcatc---a
-ttgcgtcggagtct--tttatgtaaatca--tgaacaaaactttcaacaacggatctct
tggttctggcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaatt
cagtgaatcatcgaatctttgaacgcacattgcgccccgtggtattccgcggggcatgcc
tgttcgagcgtcatttcaccactcgagt-ctgactcgg-tattgggcg-ccgcg------
cactgccgcgcgcctcaaagtt-tc---cggctgggcggacccgtccc-cgagcgttgtg
gcatcacagttctcgcctgggagtcg-cgggttgg-cttgcggccgtt--aaacacac--
ccatcaaaggttgacctcggatcaggtagggatacccgctgaacttaagcatatc
>Mycosphaerella_irregulari_TH003_3 Mycosphaerella_irregulari_TH003.3 700 bp 
gattgaatggctcagtgaggccttcggactggcccagggaggtcggcaacgaccacccag
ggccggaaagttggtcaaactcggtcatttagaggaagtaaaagtcgtaacaaggtctcc
gtaggtgaacctgcggagggatcattaccgagtgagggcccc--cggccc----------
-gacctccaacccttt-gtg----aactcacatctcgttgcttcgggggcgaccctgccg
ttcg-----cggc-c--gcggcgcccccggggg----atact--taacactgcatc---a
-ttgcgtcggagtct--tttatgtaaatca--tgaacaaaactttcaacaacggatctct
tggttctggcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaatt
cagtgaatcatcgaatctttgaacgcacattgcgccccgtggtattccgcggggcatgcc
tgttcgagcgtcatttcaccactcgagt-ctgactcgg-tattgggcg-ccgcg------
cactgccgcgcgcctcaaagtt-tc---cggctgggcggacccgtccc-cgagcgttgtg
gcatcacagttctcgcctgggagtcg-cgggttgg-cttgcggccgtt--aaacacac--
ccatcaaaggttgacctcggatcaggtaggg------------------------
>Mycosphaerella_irregulari_TH004A Mycosphaerella_irregulari_TH004A 700 bp 
gattgaatggctcagtgaggccttcggactggcccagggaggtcggcaacgaccacccag
ggccggaaagttggtcaaactcggtcatttagaggaagtaaaagtcgtaacaaggtctcc
gtaggtgaacctgcggagggatcattaccgagtgagggcccc--cggccc----------
-gacctccaacccttt-gtg----aactcacatctcgttgcttcgggggcgaccctgccg
ttcg-----cggcac--gcggcgcccccggggg----atact--taacactgcatc---a
-ttgcgtcggagtct--tttatgtaaatca--taaacaaaactttcaacaacggatctct
tggttctggcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaatt
cagtgaatcatcgaatctttgaacgcacattgcgccccgtggtattccgcggggcatgcc
tgttcgagcgtcatttcaccactcgagt-ctgactcgg-tattgggcg-tcgcg------
caccgccgcgcgcctcaaagtt-tc---cggctgggcggacccgtccc-cgagcgttgtg
gcatcacagttctcgcctgggagtcg-cgggttgg-cttgcggccgtt--aaacacac--
ccatcaaaggttgacctcggatcaggtagggatacccgctgaacttaagcatatc
>Mycosphaerella_irregulari_TH019 Mycosphaerella_irregulari_TH019 700 bp 
gattgaatggctcagtgaggccttcggactggcccagggaggtcggcaacgaccacccag
ggccggaaagttggtcaaactcggtcatttagaggaagtaaaagtcgtaacaaggtctcc
gtaggtgaacctgcggagggatcattaccgagtgagggcccc--cggccc----------
-gacctccaacccttt-gtg----aatc-acatctcgttgcttcgggggcgaccctgccg
ttcg-----cggcac--gcggcgcccccggggg----atact--caacactgcatc---a
-ttgcgtcggagtc---tttatgtaaatca--taaacaaaactttcaacaacggatctct
tggttctggcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaatt
cagtgaatcatcgaatctttgaacgcacattgcgccccgtggtattccgcggggcatgcc
tgttcgagcgtcatttcaccactcgagt-ctgactcgg-tattgggcg-ccgcg------
caccgccgcgcgcctcaaagtt-tc---cggctgggcggacccgtccc-cgagcgttgtg
gcatcacagttctcgcctgggagtcg-cgggttgg-cttgcggccgtt--aaacaccc--
ccatcaaaggttgacctcggatcaggtagggatacccgctgaacttaagcatatc
>Mycosphaerella_konae 700 bp 
-----------------------tcggactggcccagggaggtcggcaacgaccacccag
ggccggaaagttggtcaaactcggtcatttagaggaagtaaaagtcgtaacaaggtctcc
gtaggtgaacctgcggagggatcattactgagtgagggctac---ggtcc----------
-gacctccaacccttt-gtg----aacc--gaacttgttgcttcgggggcgaccctgccg
cttc-------ggcggtgcggcgcccccggagg----ccatt--aaacactgcatc---a
-ttgcgtcggagta-----aaagt----aaattaaacaaaactttcaacaacggatctct
tggttccagcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaatt
cagtgaatcatcgaatctttgaacgcacattgcgccctctggtattccggggggcatgcc
tgttcgagcgtcatttcaccactcaagc-ctggcttgg-tattgggcg-tcgcgg-----
---ctccgcgcgccttaaagtcttc---cggctgagctg-tccgtctc-taagcgttgtg
g----caactattcgcttcggaggt--cgggtggc-cg--cggccgtt--aaatcttt--
---cacaaggttgacctcggatcaggtagggata---------------------
>Mycosphaerella_marksii_CPC_13273 Mycosphaerella_marksii_CPC_13273 700 bp 
-attgaatggctcagtgaggccttcggactggcccagggaggtcggcaacgaccacccag
ggccggaaagttggtcaaactcggtcatttagaggaagtaaaagtcgtaacaaggtctcc
gtaggtgaacctgcggagggatcattaccgagtgagggtttc---ggccc----------
-gacctccaacccttt-gtg----aatc--aaacctgttgcttcgggggcgaccctgccg
ttcg-----cggc----gcggcgcccccggggg----agacc--aaacactgcgtca--a
tttgtgtcggagta-----cttgt---taa--taaacaaaactttcaacaacggatctct
tggttctggcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaatt
cagtgaatcatcgaatctttgaacgcacattgcgccccgtggtattccgcggggcatgcc
tgttcgagcgtcatttcaccactcgagt-ctgactcgg-tattgggcg-ccgcg------
tttcgatgcgcgccttaaagtt-tc---cggctggaccg-tccgtctc-cgagcgttgtg
gcatc---tgtctcgctagggagtcg-cggagggc-gt--tggccgtt--aaacaccc--
-catcaaaggttgacctcggatcaggtagggatacccgctgaacttaagcatatc
>Mycosphaerella_marksii_CPC_13724 Mycosphaerella_marksii_CPC_13724 700 bp 
------atggctcagtgaggccttcggactggcccagggaggtcggcaacgaccacccag
ggccggaaagttggtcaaactcggtcatttagaggaagtaaaagtcgtaacaaggtctcc
gtaggtgaacctgcggagggatcattaccgagtgagggcttc---ggccc----------
-gacctccaaccctct-gtg----aatc--aaacctgttgcttcgggggcgaccctgccg
ttcg-----cggc----gcggcgcccccggggg----aaatc--aaacactgcgtca--a
tttgtgtcggagta-----cttgt---taa--taaacaaaactttcaacaacggatctct
tggttctggcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaatt
cagtgaatcatcgaatctttgaacgcacattgcgccccgtggtattccgcggggcatgcc
tgttcgagcgtcatttcaccactctagt-ctgactcgg-tattgggcg-tcgcg------
tttcgatgcgcgccttaaagtt-tc---cggctggaccg-tccgtctc-cgagcgttgtg
gcatc---tgtctcgctagggagccg-cggagggc-gt--tggccgtt--aaacaccc--
-catcaaaggttgacctcggatcaggtagggatacccgctgaacttaagcatatc
>Mycosphaerella_marksii_DQ267587 Mycosphaerella_marksii_DQ267587 700 bp 
------------------------------------------------------------
---------------------------------------------------------tcc
gtaggtgaacctgcggagggatcattaccgagtgagggtttc---ggccc----------
-gacctccaacccttt-gtg----aatc--aaacctgttgcttcgggggcgaccctgccg
ttcg-----cggc----gcggcgcccccggggg----aaatc--aaacactgcgtca--a
tttgtgtcggagta-----cttgt---taa--taaacaaaactttcaacaacggatctct
tggttctggcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaatt
cagtgaatcatcgaatctttgaacgcacattgcgccccgtggtattccgcggggcatgcc
tgttcgagcgtcatttcaccactcgagt-ctgactcgg-tattgggcg-tcgcg------
tttcgatgcgcgccttaaagtt-tc---cggctggaccg-tccgtctc-cgagcgttgtg
gcatc---tgtctcgctagggagccg-cggagggc-gt--tggccgtt--aaacaccc--
-catcaaaggttgacctcggatcaggtagggata---------------------
>Mycosphaerella_parkii_AF173311 700 bp 
------------------------------------------------------------
---------------------------------------------------------tcc
gtaggtgaacctgcggagggatcattactgagtgagggtttc-accgccc----------
-gacctccaacccttt-gtg----aacc-acaacttgttgcttcgggggcgaccctgccg
ttcg-----cggc----atcgcgcccccggagg----atact--taaccctgcatc---a
-ttgcgtcggagta---attttat---taa--tacataaaactttcaacaacggatctct
tggttctggcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaatt
cagtgaatcatcgaatctttgaacgcacattgcgccccgtggtattccgcggggcatgcc
tgttcgagcgtcatttcaccactcgagt-ctgactcgg-tattgggcg-tcgcggctt--
--ccgccgcgcgcctcaaagtc-tc---cggctgggcag-cccgtctc-cgagcgttgtg
gcatcacagttctcgctagggagtcg-cggacggc-gt--cggccgtt--aaataccc--
-catcaaaggttgacctcggatcaggtagggata---------------------
>Mycosphaerella_parkii_AY626979 700 bp 
------------------------------------------------------------
------------------------------------------------------------
gtaggtgaacctgcggagggatcattactgagtgagggtttc-accgccc----------
-gacctccaacccttt-gtg----aacc-acaacttgttgcttcgggggcgaccctgccg
ttcg-----cggc----atcgcgcccccggagg----atact--taaccctgcatc---a
-ttgcgtcggagta---attttat---taa--tacataaaactttcaacaacggatctct
tggttctggcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaatt
cagtgaatcatcgaatctttgaacgcacattgcgccccgtggtattccgcggggcatgcc
tgttcgagcgtcatttcaccactcgagt-ctgactcgg-tattgggcg-tcgcggctt--
aaccgccgcgcgcctcaaagtc-tc---cggctgggcag-cccgtctc-cgagcgttgtg
gcatcacagttctcgctagggagtcg-cgggcggc-gt--cggccgtt--aaataccc--
-catcaaaggttgacctcggatcaggtagggatacccgctgaacttaagc-----
>Mycosphaerella_pseudoendophytica_AF173303 Mycosphaerella_pseudoendophytica_AF173303 700 bp 
------------------------------------------------------------
---------------------------------------------------------tcc
gtaggtgaacctgaggagggatcattactgagtgagggctca---cgccc----------
---attctaacccttt-gtg----aactacaactctgttgcttcgggggcgaccccgccg
tctc---------ggcggtggcgctcccggtggccaattatt--aaactctgcatc---t
cctgcgtcggagtc---ttaaaga----aatttaaacaaaactttcaacaacggatctct
tggttctggcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaatt
cagtgaatcatcgaatctttgaacgcacattgcgccccgtggtattccgcggggcatgcc
tgttcgagcgtcatttcaccactcaagc-ctagcttgg-tattgggcg-tcgcgac----
ttcggtcgcgcgccttaaagtc-tc---cggctgagcag-tgtgtctc-cgagcgttgtg
a----tacatattcgctagggatgac-aggtctgt-cg--cggccgtt--aaatcttt--
--ataacaggttgacctcggatcaggtagggata---------------------
>Mycosphaerella_pseudoendophytica_AF468874 Mycosphaerella_pseudoendophytica_AF468874 700 bp 
------------------------------------------------------------
---------------------------------------------------------tcc
cgtagtgaacctgaggagggatcattactgagtgagggctca---cgccc----------
---attctaacccttt-gtg----aactacaactctgttgcttcgggggcgaccccgccg
tctc---------ggcggtggcgctcccggtggccaattatt--aaactctgcatc---t
cttgcgtcggagtc---ttaaaga----aatttaaacaaaactttcaacaacggatctct
tggttctggcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaatt
cagtgaatcatcgaatctttgaacgcacattgcgccccgtggtattccgcggggcatgcc
tgttcgagcgtcatttcaccactcaagc-ctagcttgg-tattgggcg-tcgcgac----
ttcggtcgcgcgccttaaagtc-tc---cggctgagcag-tctgtctc-cgagcgttgtg
a----tacatattcgctagggatgac-aggtctgt-cg--cggccgtt--aaatcttt--
--ataacaggttgacctcggatcaggtagggata---------------------
>Mycosphaerella_pseudomarksii_TH126 Mycosphaerella_pseudomarksii_TH126 700 bp 
gattgaatggctcagtgaggccttcggactggcccagggaggtcggcaacgaccacccag
ggccggaaagttggtcaaactcggtcatttagaggaagtaaaagtcgtaacaaggtctcc
gtaggtgaacctgcggagggatcattaccgagtgagggcctctccggccc----------
-gacctccaacccttt-gtg----aacc--agtcttgttgcttcgggggcgaccctgccg
ttcg-----cggttg--ccggcgcccccggagg----atacg--taacactgcatc---a
-ttgcgtcggagtctagattttgtaaatca--taaacaaaactttcaacaacggatctct
tggttctggcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaatt
cagtgaatcatcgaatctttgaacgcacattgcgccccgtggtattccgcggggcatgcc
tgttcgagcgtcatttcaccactcgagt-ctgactcgg-tattgggcg-tcgcg------
cactgccgcgcgcctcaaagtc-tc---cggctgggcggatccgtccc-cgagcgttgtg
gcattacacttctcgctagggagtcg-cgggttgg-cttgcggccgtt--aaacacac--
ccatcaaaggttgacctcggatcaggtagggatacccgctgaacttaagcatatc
>Mycosphaerella_pseudomarksii_TH126_1 Mycosphaerella_pseudomarksii_TH126.1 700 bp 
gattgaatggctcagtgaggccttcggactggcccagggaggtcggcaacgaccacccag
ggccggaaagttggtcaaactcggtcatttagaggaagtaaaagtcgtaacaaggtctcc
gtaggtgaacctgcggagggatcattaccgagtgagggcctctccggccc----------
-gacctccaacccttt-gtg----aacc--agtcttgttgcttcgggggcgaccctgccg
ttcg-----cggttg--ccggcgcccccggagg----atacg--taacactgcatc---a
-ttgcgtcggagtctagattttgtaaatca--taaacaaaactttcaacaacggatctct
tggttctggcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaatt
cagtgaatcatcgaatctttgaacgcacattgcgccccgtggtattccgcggggcatgcc
tgttcgagcgtcatttcaccactcgagt-ctgactcgg-tattgggcg-tcgcg------
cactgccgcgcgcctcaaagtc-tc---cggctgggcggatccgtccc-cgagcgttgtg
gcattacacttctcgctagggagtcg-cgggttgg-cttgcggccgtt--aaacacac--
ccatcaaaggttgacctcggatcaggtagggatacccgctgaacttaagcatatc
>Mycosphaerella_pseudomarksii_TH126_3 Mycosphaerella_pseudomarksii_TH126.3 700 bp 
gattgaatggctcagtgaggccttcggactggcccagggaggtcggcaacgaccacccag
ggccggaaagttggtcaaactcggtcatttagaggaagtaaaagtcgtaacaaggtctcc
gtaggtgaacctgcggagggatcattaccgagtgagggcctctccggccc----------
-gacctccaacccttt-gtg----aacc--agtcttgttgcttcgggggcgaccctgccg
ttcg-----cggttg--ccggcgcccccggagg----atacg--taacactgcatc---a
-ttgcgtcggagtctagattttgtaaatca--taaacaaaactttcaacaacggatctct
tggttctggcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaatt
cagtgaatcatcgaatctttgaacgcacattgcgccccgtggtattccgcggggcatgcc
tgttcgagcgtcatttcaccactcgagt-ctgactcgg-tattgggcg-tcgcg------
cactgccgcgcgcctcaaagtc-tc---cggctgggcggatccgtccc-cgagcgttgtg
gcattacacttctcgctagggagtcg-cgggttgg-cttgcggccgtt--aaacacac--
ccatcaaaggttgacctcggatcaggtagggatacccgctgaacttaagcatatc
>Mycosphaerella_punctiformis 700 bp 
------------------------------------------------------------
------------------------------------------------------------
----------------agggatcattactgagtgagggcttc--cggccc----------
-gacctccaacccttt-gtg----aaca--catcttgttgcttcgggggcgaccctgccg
ttcg-----------cggcattccccccggagg---tcatca--aaacactgcatt---c
-ttacgtcggagta---aaaagtt-----aatttaataaaactttcaacaacggatctct
tggttctggcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaatt
cagtgaatcatcgaatctttgaacgcacattgcgccccctggtattccggggggcatgcc
tgttcgagcgtcatttcaccactcaagc-ctcgcttgg-tattgggcg-tcgcga-----
gtctctcgcgcgcctcaaagtc-tc---cggctgtgcgg-ttcgtctc-ccagcgttgtg
g---caactatttcgcagtggagtt--cgagtcgt-cg--tggccgtt--aaatcttt--
----caaaggttgacctcggatcagg-----------------------------
>Mycosphaerella_quasiparkii_TH016A Mycosphaerella_quasiparkii_TH016A 700 bp 
gattgaatggctcagtgaggccttcggactggcccagggaggtcggcaacgaccacccag
ggccggaaagttggtcaaactcggtcatttagaggaagtaaaagtcgtaacaaggtctcc
gtaggtgaacctgcggagggatcattactgagtgagggctca---cgccc----------
-gacctccaacccttt-gtg----aacc-aaactttgttgcttcgggggcgaccctgcca
tcga-------gttg----ggcgcccccggagg----tcatc--aaactctgcatc---t
-ttgcgtcggagta---c--aagt---t-aattaaacaaaactttcaacaacggatctct
tggttctggcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaatt
cagtgaatcatcgaatctttgaacgcacattgcgccctttggtattccgaagggcatgcc
tgttcgagcgtcatttcaccactcaagc-ctcgcttgg-tattgggcg-tcgcgg-----
---ttccgcgcgccttaaagtc-tc---cggctgagctg-tccgtctc-taagcgttgtg
a----tacatattcgcttcggagtg--cgggcggt-cg--cggccgtt--aaacttct--
--ttcaaaggttgacctcggatcaggtagggatacccgctgaacttaagcatatc
>Mycosphaerella_quasiparkii_TH016A_2 Mycosphaerella_quasiparkii_TH016A.2 700 bp 
gattgaatggctcagtgaggccttcggactggcccagggaggtcggcaacgaccacccag
ggccggaaagttggtcaaactcggtcatttagaggaagtaaaagtcgtaacaaggtctcc
gtaggtgaacctgcggagggatcattactgagtgagggctca---cgccc----------
-gacctccaacccttt-gtg----aacc-aaactttgttgcttcgggggcgaccctgcca
tcga-------gttg----ggcgcccccggagg----tcatc--aaactctgcatc---t
-ttgcgtcggagta---c--aagt---t-aattaaacaaaactttcaacaacggatctct
tggttctggcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaatt
cagtgaatcatcgaatctttgaacgcacattgcgccctttggtattccgaagggcatgcc
tgttcgagcgtcatttcaccactcaagc-ctcgcttgg-tattgggcg-tcgcgg-----
---ttccgcgcgccttaaagtc-tc---cggctgagctg-tccgtctc-taagcgttgtg
a----tacatattcgcttcggagtg--cgggcggt-cg--cggccgtt--aaacttct--
--ttcaaaggttgacctcggatcaggtagggatacccgctgaacttaagcatatc
>Mycosphaerella_quasiparkii_TH016A_3 Mycosphaerella_quasiparkii_TH016A.3 700 bp 
gattgaatggctcagtgaggccttcggactggcccagggaggtcggcaacgaccacccag
ggccggaaagttggtcaaactcggtcatttagaggaagtaaaagtcgtaacaaggtctcc
gtaggtgaacctgcggagggatcattactgagtgagggctca---cgccc----------
-gacctccaacccttt-gtg----aacc-aaactttgttgcttcgggggcgaccctgcca
tcga-------gttg----ggcgcccccggagg----tcatc--aaactctgcatc---t
-ttgcgtcggagta---c--aagt---t-aattaaacaaaactttcaacaacggatctct
tggttctggcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaatt
cagtgaatcatcgaatctttgaacgcacattgcgccctttggtattccgaagggcatgcc
tgttcgagcgtcatttcaccactcaagc-ctcgcttgg-tattgggcg-tcgcgg-----
---ttccgcgcgccttaaagtc-tc---cggctgagctg-tccgtctc-taagcgttgtg
a----tacatattcgcttcggagtg--cgggcggt-cg--cggccgtt--aaacttct--
--ttcaaaggttgacctcggatcaggtagggatacccgctgaacttaagcatatc
>Mycosphaerella_quasiparkii_TH091A Mycosphaerella_quasiparkii_TH091A 700 bp 
gattgaatggctcagtgaggccttcggactggcccagggaggtcggcaacgaccacccag
ggccggaaagttggtcaaactcggtcatttagaggaagtaaaagtcgtaacaaggtctcc
gtaggtgaacctgcggagggatcattactgagtgagggctca---cgccc----------
-gacctccaacccttt-gtg----aact-aaactttgttgcttcgggggcgaccctgcca
tcga-------gttg----ggcgcccccggagg----tcatc--aaactctgcatc---t
-ttgcgtcggagta---c--aagt---t-aattaaacaaaactttcaacaacggatctct
tggttctggcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaatt
cagtgaatcatcgaatctttgaacgcacattgcgccctttggtattccgaagggcatgcc
tgttcgagcgtcatttcaccactcaagc-ctagcttgg-tattgggcg-tcgcga-----
---ttccgcgcgccttaaagtc-tc---cggctgagctg-tccgtctc-taagcgttgtg
a----tacatattcgcttcggagtg--cgggcggt-cg--cggccgtt--aaacttct--
--ttcaaaggttgacctcggatcaggtagggatacccgctgaacttaagcatatc
>Mycosphaerella_rosigena 700 bp 
------------------------------------------------------------
-gccggaaagttggtcaaactcggtcatttagaggaagtaaaagtcgtaacaaggtctcc
gtaggtgaacctgcggagggatcattaaagagtgagggcccc--cggtcc----------
-gacctccaacccttt-gtg----aact-acaacccgttgcttcgggggcgaccctgccg
ttcg-----cggcg---tcggcgcccccggagg----atcat--taacactgcatc---a
-atgcgtcggagta---aatcagt---taatctgaacaaaactttcaacaacggatctct
tggttctggcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaatt
cagtgaatcatcgaatctttgaacgcacattgcgccccgtggtattccgcggggcatgcc
tgttcgagcgtcatttcaccactcgagt-ctgactcgg-tattgggcg-tcgcg------
cattgccgcgcgccttaaagtc-tc---cggctgggcgg-cccgtctc-cgagcgttgtg
acatcacagtt-tcgctagggagtcg-cgggcggc-gt--tggccgtt--aaataccc--
-catcaaaggttgacctcggatcaggtagggatacccgctgaacttaagcatatc
>Mycosphaerella_thailandica_AY752156_T Mycosphaerella_thailandica_AY752156_T 700 bp 
------------------------------------------------------------
------------------------------------------------------------
------------------ggatcattactgagtgagggcctc-cgggtcc----------
-gacctccaacccttt-gtg----aacc--aatcttgttgcttcgggggcgaccctgccg
cttc-------ggcggtgcggcgcccccggagg----ccatc--aaacactgcatc---a
-ttgcgtcggagta-----aaagt----aaatgaaacaaaactttcaacaacggatctct
tggttccagcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaatt
cagtgaatcatcgaatctttgaacgcacattgcgccctctggtattccggggggcatgcc
tgttcgagcgtcatttcaccactcaagc-ctggcttgg-tattgggcg-tcgcgg-----
---tgccgcgcgccttaaagtcttc---cggctgagctg-tccgtctc-taagcgttgtg
g----caactattcgcttcggaggc--cgggcggc-cg--cggccgtt--aaatcttt--
---cacaaggttgacctcggatcaggtagggata---------------------
>Mycosphaerella_thailandica_EF394848 Mycosphaerella_thailandica_EF394848 700 bp 
-attgaatggctcagtgaggccttcggactggcccagggaggtcggcaacgaccacccag
ggccggaaagttggtcaaactcggtcatttagaggaagtaaaagtcgtaacaaggtctcc
gtaggtgaacctgcggagggatcattactgagtgagggcctc-cgggtcc----------
-gacctccaacccttt-gtg----aacc--aatcttgttgcttcgggggcgaccctgccg
cttc-------ggcggtgcggcgcccccggagg----ccatc--aaacactgcatc---a
-ttgcgtcggagta-----aaagt----aaatgaaacaaaactttcaacaacggatctct
tggttccagcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaatt
cagtgaatcatcgaatctttgaacgcacattgcgccctctggtattccggggggcatgcc
tgttcgagcgtcatttcaccactcaagc-ctggcttgg-tattgggcg-tcgcgg-----
---tgccgcgcgccttaaagtcttc---cggctgagctg-tccgtctc-taagcgttgtg
g----caactattcgcttcggaggc--cgggcggc-cg--cggccgtt--aaatcttt--
---cacaaggttgacctcggatcaggtagggata---------------------
>Mycosphaerella_thailandica_TH004B Mycosphaerella_thailandica_TH004B 700 bp 
-attgaatggctcagtgaggccttcggactggcccagggaggtcggcaacgaccacccag
ggccggaaagttggtcaaactcggtcatttagaggaagtaaaagtcgtaacaaggtctcc
gtaggtgaacctgcggagggatcattactgagtgagggcctc-cgggtcc----------
-gacctccaacccttt-gtg----aacc--aatcttgttgcttcgggggcgaccctgccg
cttc-------ggcggtgcggcgcccccggagg----ccatc--aaacactgcatc---a
-ttgcgtcggagta-----aaagt----aaatgaaacaaaactttcaacaacggatctct
tggttccagcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaatt
cagtgaatcatcgaatctttgaacgcacattgcgccctctggtattccggggggcatgcc
tgttcgagcgtcatttcaccactcaagc-ctggcttgg-tattgggcg-tcgcgg-----
---tgccgcgcgccttaaagtcttc---cggctgagctg-tccgtctc-taagcgttgtg
g----caactattcgcttcggaggc--cgggcggc-cg--cggccgtt--aaatcttt--
---cacaaggttgacctcggatcaggtagggatacccgctgaacttaagcatatc
>Mycosphaerella_thailandica_TH011 Mycosphaerella_thailandica_TH011 700 bp 
gattgaatggctcagtgaggccttcggactggcccagggaggtcggcaacgaccacccag
ggccggaaagttggtcaaactcggtcatttagaggaagtaaaagtcgtaacaaggtctcc
gtaggtgaacctgcggagggatcattactgagtgagggcctc-cgggtcc----------
-gacctccaacccttt-gtg----aacc--aatcttgttgcttcgggggcgaccctgccg
cttc-------ggcggtgcggcgcccccggagg----ccatc--aaacactgcatc---a
-ttgcgtcggagta-----aaagt----aaatgaaacaaaactttcaacaacggatctct
tggttccagcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaatt
cagtgaatcatcgaatctttgaacgcacattgcgccctctggtattccggggggcatgcc
tgttcgagcgtcatttcaccactcaagc-ctggcttgg-tattgggcg-tcgcgg-----
---tgccgcgcgccttaaagtcttc---cggctgagctg-tccgtctc-taagcgttgtg
g----caactattcgcttcggaggc--cgggcggc-cg--cggccgtt--aaatcttt--
---cacaaggttgacctcggatcaggtagggatacccgctgaacttaagcatatc
>Mycosphaerella_thailandica_TH026A Mycosphaerella_thailandica_TH026A 700 bp 
gattgaatggctcagtgaggccttcggactggcccagggaggtcggcaacgaccacccag
ggccggaaagttggtcaaactcggtcatttagaggaagtaaaagtcgtaacaaggtctcc
gtaggtgaacctgcggagggatcattactgagtgagggcctc-cgggtcc----------
-gacctccaacccttt-gtg----aacc--aatcttgttgcttcgggggcgaccctgccg
cttc-------ggcggtgcggcgcccccggagg----ccatc--aaacactgcatc---a
-ttgcgtcggagta-----aaagt----aaatgaaacaaaactttcaacaacggatctct
tggttccagcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaatt
cagtgaatcatcgaatctttgaacgcacattgcgccctctggtattccggggggcatgcc
tgttcgagcgtcatttcaccactcaagc-ctggcttgg-tattgggcg-tcgcgg-----
---tgccgcgcgccttaaagtcttc---cggctgagctg-cccgtctc-taagcgttgtg
g----caactattcgcttcggaggc--cgggcggc-cg--cggccgtt--aaatcttt--
---cacaaggttgacctcggatcaggtagggatacccgctgaacttaagcatatc
>Mycosphaerella_thailandica_TH026B Mycosphaerella_thailandica_TH026B 700 bp 
gattgaatggctcagtgaggccttcggactggcccagggaggtcggcaacgaccacccag
ggccggaaagttggtcaaactcggtcatttagaggaagtaaaagtcgtaacaaggtctcc
gtaggtgaacctgcggagggatcattactgagtgagggcctc-cgggtcc----------
-gacctccaacccttt-gtg----aacc--aatcttgttgcttcgggggcgaccctgccg
cttc-------ggcggtgcggcgcccccggagg----ccatc--aaacactgcatc---a
-ttgcgtcggagta-----aaagt----aaatgaaacaaaactttcaacaacggatctct
tggttccagcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaatt
cagtgaatcatcgaatctttgaacgcacattgcgccctctggtattccggggggcatgcc
tgttcgagcgtcatttcaccactcaagc-ctggcttgg-tattgggcg-tcgcgg-----
---tgccgcgcgccttaaagtcttc---cggctgagctg-tccgtctc-taagcgttgtg
g----caactattcgcttcggaggc--cgggcggc-cg--cggccgtt--aaatcttt--
---cacaaggttgacctcggatcaggtagggatacccgctgaacttaagcatatc
>Mycosphaerella_thailandica_TH091B Mycosphaerella_thailandica_TH091B 700 bp 
gattgaatggctcagtgaggccttcggactggcccagggaggtcggcaacgaccacccag
ggccggaaagttggtcaaactcggtcatttagaggaagtaaaagtcgtaacaaggtctcc
gtaggtgaacctgcggagggatcattactgagtgagggcctc-cgggtcc----------
-gacctccaacccttt-gtg----aacc--aatcttgttgcttcgggggcgaccctgccg
cttc-------ggcggtgcggcgcccccggagg----ccatc--aaacactgcatc---a
-ttgcgtcggagta-----aaagt----aaatgaaacaaaactttcaacaacggatctct
tggttccagcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaatt
cagtgaatcatcgaatctttgaacgcacattgcgccctctggtattccggggggcatgcc
tgttcgagcgtcatttcaccactcaagc-ctggcttgg-tattgggcg-tcgcgg-----
---tgccgcgcgccttaaagtcttc---cggctgagctg-tccgtctc-taagcgttgtg
g----caactattcgcttcggaggc--cgggcggc-cg--cggccgtt--aaatcttt--
---cacaaggttgacctcggatcaggtagggatacccgctgaacttaagcatatc
>Mycosphaerella_tumulosa 700 bp 
------------------------------------------------------------
---------------------------------------------------------tcc
gtaggtgaacctgcggagggatcattactgagtgagggctca---cgccc----------
-gacctccaaccctct-gtg----aacc--aaacttgttgcttcgggggcgaccctgccg
gcaaactcgtcgccg----ggcgcccccggagg----tctcctcaaacactgcatc---t
-ttgcgtcggagtt---t--aaac---aaattaaacaaaaactttcaacaacggatctct
tggttctggcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaatt
cagtgaatcatcgaatctttgaacgcacattgcgccctttggtattccaaagggcatgcc
tgttcgagcgtcatttcaccactcaagc-ctagcttgg-tattgggcg-tcgcgg-----
tctccccgcgcgccttgaatct-tc---cggctgagccg-tccgtctc-taagcgttgtg
g-atttttcaattcgctttggagtg--cgggtggc-tg--cggccgtt--aaatcttt--
cacttaaaggttgacctcggatcaggtagggata---------------------
>Mycosphaerella_vietnamensis_DQ632675 Mycosphaerella_vietnamensis_DQ632675 700 bp 
------------------------------------------------------------
---------------------------------------------------------tcc
gtaggtgaacctgcggagggatcattactgagtgagggtttc-accgccc----------
-gacctccaacccttt-gtg----aacc-acaacttgttgcttcgggggcgaccctgccg
ttcg-----cggc----atcgcgcccccggagg----atact--taaccctgcatc---a
-ttgcgtcggagta---tttttat---taa--taaataaaactttcaacaacggatctct
tggttctggcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaatt
cagtgaatcatcgaatctttgaacgcacattgcgccccgtggtattccgcggggcatgcc
tgttcgagcgtcatttcaccactcgagt-ctgactcgg-tattgggcg-ccgcggttt--
aatcgccgcgcgcctcaaagtc-tc---cggctgggcag-cccgtctc-cgagcgttgtg
gcatcacagttctcgctagggagtcg-cgggcggc-gt--cggccgtt--aaacaccc--
-catcaaaggttgacctcggatcaggtagggata---------------------
>Mycosphaerella_vietnamensis_DQ632678 Mycosphaerella_vietnamensis_DQ632678 700 bp 
------------------------------------------------------------
---------------------------------------------------------tcc
gtaggtgaacctgcggagggatcattactgagtgagggtttc-accgccc----------
-gacctccaacccttt-gtg----aacc-acaacttgttgcttcgggggcgaccctgccg
ttcg-----cggc----atcgcgcccccggagg----atact--taaccctgcatc---a
-ttgcgtcggagta---tttttat---taa--taaataaaactttcaacaacggatctct
tggttctggcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaatt
cagtgaatcatcgaatctttgaacgcacattgcgccccgtggtattccgcggggcatgcc
tgttcgagcgtcatttcaccactcgagt-ctgactcgg-tattgggcg-ccgcggttt--
aatcgccgcgcgcctcaaagtc-tc---cggctgggcag-cccgtctc-cgagcgttgtg
gcatcacagttctcgctagggagtcg-cgggcggc-gt--cggccgtt--aaacaccc--
-catcaaaggttgacctcggatcaggtagggata---------------------
>Mycosphaerella_vietnamensis_TH009B Mycosphaerella_vietnamensis_TH009B 700 bp 
gattgaatggctcagtgaggccttcggactggcccagggaggtcggcaacgaccacccag
ggccggaaagttggtcaaactcggtcatttagaggaagtaaaagtcgtaacaaggtctcc
gtaggtgaacctgcggagggatcattactgagtgagggtttc-accgccc----------
-gacctccaacccttt-gtg----aacc-acaacttgttgcttcgggggcgaccctgccg
ttcg-----cggc----atcgcgcccccggagg----atact--taaccctgcatc---a
-ttgcgtcggagta---tttttat---taa--taaataaaactttcaacaacggatctct
tggttctggcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaatt
cagtgaatcatcgaatctttgaacgcacattgcgccccgtggtattccgcggggcatgcc
tgttcgagcgtcatttcaccactcgagt-ctgactcggttattgggcg-ccgcggttt--
aatcgccgcgcgcctcaaagtc-tc---cggctgggcag-cccgtctc-cgagcgttgtg
gcatcacagttctcgctagggagtcg-cgggcggc-gt--cggccgtt--aaacaccc--
-catcaaaggttgacctcggatcaggtagggatacccgctgaacttaagcatatc
>Mycosphaerella_vietnamensis_TH010B Mycosphaerella_vietnamensis_TH010B 700 bp 
gattgaatggctcagtgaggccttcggactggcccagggaggtcggcaacgaccacccag
ggccggaaagttggtcaaactcggtcatttagaggaagtaaaagtcgtaacaaggtctcc
gtaggtgaacctgcggagggatcattactgagtgagggtttc-accgccc----------
-gacctccaacccttt-gtg----aacc-acaacttgttgcttcgggggcgaccctgccg
ttcg-----cggc----atcgcgcccccggagg----atact--taaccctgcatc---a
-ttgcgtcggagta---tttttat---taa--taaataaaactttcaacaacggatctct
tggttctggcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaatt
cagtgaatcatcgaatctttgaacgcacattgcgccccgtggtattccgcggggcatgcc
tgttcgagcgtcatttcaccactcgagt-ctgactcggttattgggcg-ccgcggttt--
aatcgccgcgcgcctcaaagtc-tc---cggctgggcag-cccgtctc-cgagcgttgtg
gcatcacagttctcgctagggagtcg-cgggcggc-gt--cggccgtt--aaacaccc--
-catcaaaggttgacctcggatcaggtagggatacccgctgaacttaagcatatc
>Mycosphaerella_vietnamensis_TH093 Mycosphaerella_vietnamensis_TH093 700 bp 
gattgaatggctcagtgaggccttcggactggcccagggaggtcggcaacgaccacccag
ggccggaaagttggtcaaactcggtcatttagaggaagtaaaagtcgtaacaaggtctcc
gtaggtgaacctgcggagggatcattactgagtgagggtttc-accgccc----------
-gacctccaacccttt-gtg----aacc-acaacttgttgcttcgggggcgaccctgccg
ttcg-----cggc----atcgcgcccccggagg----atact--taaccctgcatc---a
-ttgcgtcggagta---tttttat---taa--taaataaaactttcaacaacggatctct
tggttctggcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaatt
cagtgaatcatcgaatctttgaacgcacattgcgccccgtggtattccgcggggcatgcc
tgttcgagcgtcatttcaccactcgagt-ctgactcggttattgggcg-ccgcggttt--
aatcgccgcgcgcctcaaagtc-tc---cggctgggcag-cccgtctc-cgagcgttgtg
gcatcacagttctcgctagggagtcg-cgggcggc-gt--cggccgtt--aaacaccc--
-catcaaaggttgacctcggatcaggtagggatacccgctgaacttaagcatatc
>Mycosphaerella_vietnamensis_TH099A Mycosphaerella_vietnamensis_TH099A 700 bp 
gattgaatggctcagtgaggccttcggactggcccagggaggtcggcaacgaccacccag
ggccggaaagttggtcaaactcggtcatttagaggaagtaaaagtcgtaacaaggtctcc
gtaggtgaacctgcggagggatcattactgagtgagggtttc-accgccc----------
-gacctccaacccttt-gtg----aacc-acaacttgttgcttcgggggcgaccctgccg
ttcg-----cggc----atcgcgcccccggagg----atact--taaccctgcatc---a
-ttgcgtcggagta---tttttat---taa--taaataaaactttcaacaacggatctct
tggttctggcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaatt
cagtgaatcatcgaatctttgaacgcacattgcgccccgtggtattccgcggggcatgcc
tgttcgagcgtcatttcaccactcgagt-ctgactcggttattgggcg-ccgcggttt--
aatcgccgcgcgcctcaaagtc-tc---cggctgggcag-cccgtctc-cgagcgttgtg
gcatcacagttctcgctagggagtcg-cgggcggc-gt--cggccgtt--aaacaccc--
-catcaaaggttgacctcggatcaggtagggatacccgctgaacttaagcatatc
>Mycosphaerella_yunnanensis_DQ632686 Mycosphaerella_yunnanensis_DQ632686 700 bp 
------------------------------------------------------------
---------------------------------------------------------tcc
gtaggtgaacctgcggagggatcattactgagtgagggcctc--cggtcc----------
-gacctccaacccttt-gtg----aacc--aacactgttgcttcgggggcgaccctgcct
ttcg----------ggcagtgcgcccccggagg---atatca--aaacgctgcatc---t
-ttgcgtcggagta---tcaat-----caaattgaacaaaactttcaacaacggatctct
tggttctggcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaatt
cagtgaatcatcgaatctttgaacgcacattgcgccccgtggtattccgcggggcatgcc
tgttcgagcgtcatttcaccactcaagc-ctggcttgg-tattgggcg-tcgcga-----
---gtccgcgcgcctcaaagtc-tc---cggctgagctg-tccgtctc-ccagcgttgtg
a----atctcattcgctacggagtct-cgggcagc-cg--cggccgtt--aaacttat--
---ctaaaggttgacctcggatcaggtagggata---------------------
>Mycosphaerella_yunnanensis_DQ632687 Mycosphaerella_yunnanensis_DQ632687 700 bp 
------------------------------------------------------------
---------------------------------------------------------tcc
gtaggtgaacctgcggagggatcattactgagcgagggcctc--cggtcc----------
-gacctcctacccttt-gtg----aacc--aacactgttgcttcgggggcgaccctgcct
ttcg----------ggcagtgcgcccccggagg---gaatca--aaacgctgcatc---t
-ttgcgtcggagta---tcaat-----caaattgaacaaaactttcaacaacggatctct
tggttctggcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaatt
cagtgaatcatcgaatctttgaacgcacattgcgccccgtggtattccgcggggcatgcc
tgttcgagcgtcatttcaccactcaagc-ctggcttgg-tattgggcg-tcgcga-----
---gttcgcgcgcctcaaagtc-tc---cggctgagctg-tccgtctc-ccagcgttgtg
a----atctcattcgctacggagtttacgagcagc-cg--cggccgtt--aaacttat--
---ctaaaggttgacctcggatcaggtagggata---------------------
>Penidiella_eucalypti_TH064 700 bp 
gattgaatggctcagtgaggcgttcggactggcccagggaggtcggcaacgaccacccag
ggccggaaagttcgtcaaacttggtcatttagaggaagtaaaagtcgtaacaaggtctcc
gtaggtgaacctgcggagggatcattaccgagtgagggcccc--cggccc----------
-gacctccaaccccat-gtt----ttcc-aacctctgttgcctcgggggcgacccggccc
c--------------ggccggggccccccgcggacctcaacc--aaaccctgcata---t
-ctgcgtctgagtc---aattgat---aaattcaatcaaaactttcaacaacggatctct
tggttctggcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaatt
cagtgaatcatcgaatctttgaacgcacattgcgcccggtggcattccgccgggcatgcc
tgttcgagcgtcattacaccactccagc-ctggctggg-tattgggcg-tcgcgg-----
ggtccccgcgcgcctcgaagtc-tc---cggccgagccg-tccgtctcataagcgttgtg
a--tctatcaagccgcttgcgagct--cggggggc-cgtcgcgccgtt--aaacgacc--
-atctcaaggttgacctcggatcaggtagggatacccgctgaacttaagcatatc
>Penidiella_eucalypti_TH064_1 700 bp 
gattgaatggctcagtgaggcgttcggactggcccagggaggtcggcaacgaccacccag
ggccggaaagttcgtcaaacttggtcatttagaggaagtaaaagtcgtaacaaggtctcc
gtaggtgaacctgcggagggatcattaccgagtgagggcccc--cggccc----------
-gacctccaaccccat-gtt----ttcc-aacctctgttgcctcgggggcgacccggccc
c--------------ggccggggccccccgcga-cctcaacc--aaaccctgcata---t
-ctgcgtctgagtc---aattgat---aaattcaatcaaaactttcaacaacggatctct
tggttctggcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaatt
cagtgaatcatcgaatctttgaacgcacattgcgcccggtggcattccgccgggcatgcc
tgttcgagcgtcattacaccactccagc-ctggctggg-tattgggcg-tcgcgg-----
ggtccccgcgcgcctcgaagtc-tc---cggccgagccg-tccgtctcataagcgttgtg
a--tctatcaagccgcttgcgagct--cggggggc-cgtcgcgccgtt--aaacgacc--
-atctcaaggttgacctcggatcaggtagggatacccgctgaacttaagcatatc
>Penidiella_eucalypti_TH133 700 bp 
gattgaatggctcagtgaggcgttcggactggcccagggaggtcggcaacgaccacccag
ggccggaaagttcgtcaaacttggtcatttagaggaagtaaaagtcgtaacaaggtctcc
gtaggtgaacctgcggagggatcattaccgagtgagggcccc--cggccc----------
-gacctccaaccccat-gtt----ttcc-aacctctgttgcctcgggggcgacccggccc
c--------------ggccggggccccccgcggacctcaacc--aaaccctgcata---t
-ctgcgtctgagtc---aattgat---aaattcaatcaaaactttcaacaacggatctct
tggttctggcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaatt
cagtgaatcatcgaatctttgaacgcacattgcgcccggtggcattccgccgggcatgcc
tgttcgagcgtcattacaccactccagc-ctggctggg-tattgggcg-tcgcgg-----
ggtccccgcgcgcctcgaagtc-tc---cggccgagccg-tccgtctcataagcgttgtg
a--tctatcaagccgcttgcgagct--cggggggc-cgtcgcgccgtt--aaacgacc--
-atctcaaggttgacctcggatcaggtagggatacccgctgaacttaagcatatc
>Penidiella_kurandae 700 bp 
-----gatggctcagtgaggcctccggactggcccagggaggtcggcaacgaccacccag
ggccggaaagctggtcaaacttggtcatttagaggaagtaaaagtcgtaacaaggtctcc
gtaggtgaacctgcggagggatcattaccgagtgcgggctgc---ggccc----------
-gacctcccaccccgt-gtg-----tcc--ccccccgttgcctcgggggcgacccggccg
ctcg-----------cgccggggcccccggtgg---acccgcc-caactcggttttcggt
gctgcgtctgagtg---acaggtt----taatgaagcaaaactttcaacaacggatctct
tggttccggcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaatt
cagtgaatcatcgaatctttgaacgcacattgcgccccttggcactccgaggggcatgcc
tgttcgagcgtcatttcacccatcaagc-ctggcttgg-cgttgggcg-ccgcgg-----
--cctccgcgcgcctcaaagtt-cccgtcggccgagccg-tccgcccccgtagcgttgtg
g----tttccgttcgctcaccgggggaagggcgg--cg--gcgccgttcaaaaagtct--
-ccacaaagtttgacctcggatcaggcagggatacccgctgaacttaagcatatc
>Penidiella_rigidophora 700 bp 
------------------------------------------------------------
------------------------------------------------------------
----------------agggatcattactgagtgacggccct-cgggctc----------
-gacctccaacccttt-gta----atcc--gaccatgttgcctcgggggcgacccggcct
tcgg----------gcgtcggggcccccggtgg---acccct--caacactgcatc---t
-ttgcgtctgagtt---tgatatt----gaatcaatcaaaactttcaacaacggatctct
tggttctggcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaatt
cagtgaatcatcgaatctttgaacgcacattgcgccccttggtattccggggggcatgcc
tgttcgagcgtcattacacccctccagc-ctcgctggt-tgttgggcg-tccgcggatgc
atagtctgcgcgcctcaatgtc-gc---cggccggaccg-accgtctc-taagcgttgtg
g----taacagttcgcttgcgggca--cgggagggacg--tcgccgtt--aaaccttt--
tcattccaggttgacctcggatcaggtagggatacccgctgaacttaagcatatc
>Penidiella_strumelloidea 700 bp 
------------------------------------------------------------
------------------------------------------------------------
----------------agggatcattactgagtgagggcctc-tgcgccc----------
-gacctcccaaccctt-ctgtcgtctcc--gaccgcgttgcctcgggggatccgccgtc-
---------------cgcggcggcccccggagg---accaca--taactctgcgta---a
ccgtcgtccgagtc---taaacaa---aaattgaaacacaactttcaacaacggatctct
tggctctggcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaatt
ccgtgaatcatcgaatctttgaacgcacattgcgcccctcggtattccggggggcatgcc
tgttcgagcgtcattacacccctcaagctccggcttgg-tcttgggcg-tcgcgg----t
cccccccgcgtgcctcaatgtc-gc---cggctggtgcg-tccgtctc-cgagcgtcgtg
a--cttcattgttcgcttctggaggc-cggacg---cgccgcgccgtc--aacccccc-a
tatctacaggttgacctcggatcaggtagggatacccgctgaacttaagcatatc
>Penidiella_venezuelensis 700 bp 
------------------------------------------------------------
------------------------------------------------------------
----------------agggatcattaccagagtggacc------ggccctcgtggctgg
aacctcccaaccccatgtcg----tttc--gactctgttgcctcgggggcgacccggcct
tcgg----------gcgtcggggcccccggcgg---acccctc-aaactctgcatg---c
tttgcgtctgagta---cagatat----aaatcaatcaaaactttcaacaacggatctct
tggttctggcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaatt
cagtgaatcatcgaatctttgaacgcacattgcgccccctggcattccggggggcatgcc
tgttcgagcgtcattacaccactcaagc-ctggcttgg-tattgggcggccgcggt----
cctccccgcgcgccctaatgtc-tc---cggctgagccg-tccgtctc-taagcgttgtg
gca--caccagttcgcttgcgaggcc-cgggcggttcg--acgccgtt--aaaccccttc
ttctcaaaggttgacctcggatcaggtagggatacccgctgaacttaagcatatc
>Phaeoramularia_calotropidis 700 bp 
------------------------------------------------------------
---------------------------------------------------------tcc
gtaggtgaacctgcggagggatcattactgagtgagggctca---cgccc----------
-gacctccaacccttt-gtg----aacg---aacatgttgcttcgggggcgaccctgcca
ttga-------gccg----ggcgcccccggagg----tcatc--aaactctgcatc---t
-ttgcgtcggagta---c--aagt---taaatcaaacaaaactttcaacaacggatctct
tggttctggcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaatt
cagtgaatcatcgaatctttgaacgcacattgcgccctttggtattccgaagggcatgcc
tgttcgagcgtcatttcaccactcaagc-ctcgcttgg-tattgggcg-tcgcgg-----
---ttccgcgcgccttaaagtc-tc---cggctgagctg-tccgtctc-taagcgttgtg
a----tacatattcgcttcggggcg--cgggcggt-ca--cggccgtt--aaacttcc--
--ttcacaggttgacctcggatcaggtagggata---------------------
>Pseudocercospora_assamensis 700 bp 
------------------------------------------------------------
---------------------------------------------------------tcc
gtaggtgaacctgcggagggatcattactgagtgagggctca---cgccc----------
-gacctccaacccttt-gtg----aacc--aaacttgttgcttcgggggcgaccctgccg
acgacttcgtcgccg----ggcgcccccggagg----tcttct-aaacactgcatc---t
-ttgcgtcggagtt---t--aaac---a-aattaaacaaaactttcaacaacggatctct
tggttctggcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaatt
cagtgaatcatcgaatctttgaacgcacattgcgccctttggtattccgaagggcatgcc
tgttcgagcgtcatttcaccactcaagc-ctggcttgg-tattgggcg-tcgcgg-----
tgtttccgcgcgccttaaagtcttc---cggctgagctg-tccgtctc-taagcgttgtg
g-atttttcaattcgcttcggagtg--cgggcggc-cg--cggccgtt--aaatcttt--
-attcaaaggttgacctcggatcaggtagggata---------------------
>Pseudocercospora_basiramifera 700 bp 
------------------------------------------------------------
---------------------------------------------------------tcc
gtaggtgaacctgcggagggatcattactgagtgagggctca---cgccc----------
-gacctccaacccttt-gtg----aacc--aaacttgttgcttcgggggcgaccctgccg
acgacttggtcgccg----ggcgcccccggagg----tcttct-aaacactgcatc---t
-ttgcgtcggagtt---t--aaac---a-aattaaacaaaactttcaacaacggatctct
tggttctggcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaatt
cagtgaatcatcgaatctttgaacgcacattgcgccctttggtattccgaagggcatgcc
tgttcgagcgtcatttcaccactcaagc-ctggcttgg-tattgggcg-tcgcgg-----
tg-ttccgcgcgccttaaagtcttc---cggctgagctg-tccgtctc-taagcgttgtg
g-atttttcaattcgcttcggagtg--cggatggc-cg--cggccgtt--aaatcttt--
-attcaaaggttgacctcggatcaggtagggata---------------------
>Pseudocercospora_chiangmaiensis_TH094_1 Pseudocercospora_chiangmaiensis_TH094.1 700 bp 
-attgaatggctcagtgaggccttcggactggcccagggaggtcggcaacgaccacccag
ggccggaaagttggtcaaactcggtcatttagaggaagtaaaagtcgtaacaaggtctcc
gtaggtgaacctgcggagggatcattactgagtgagggctca---cgccc----------
-gacctccaacccttt-gtg----aacc--aaacttgttgcttcgggggcgaccctgccg
acgacttcgtcgccg----ggcgcccccggagg----tctcct-aaacactgcatc---t
-ttgcgtcggagtt---t--aaac---a-aattaaacaaaactttcaacaacggatctct
tggttctggcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaatt
cagtgaatcatcgaatctttgaacgcacattgcgccctttggtattccgaagggcatgcc
tgttcgagcgtcatttcaccactcaagc-ctggcttgg-tattgggcg-tcgcgg-----
tgtttccgcgcgccttaaagtcttc---cggctgagctg-tccgtctc-taagcgttgtg
g-atttttcaattcgcttcggagtg--cgggcggc-cg--cggccgtt--aaatcttt--
-attcaaaggttgacctcggatcaggtagggatacccgctgaacttaagcatatc
>Pseudocercospora_chiangmaiensis_TH094_2 Pseudocercospora_chiangmaiensis_TH094.2 700 bp 
-attgaatggctcagtgaggccttcggactggcccagggaggtcggcaacgaccacccag
ggccggaaagttggtcaaactcggtcatttagaggaagtaaaagtcgtaacaaggtctcc
gtaggtgaacctgcggagggatcattactgagtgagggctca---cgccc----------
-gacctccaacccttt-gtg----aacc--aaacttgttgcttcgggggcgaccctgccg
acgacttcgtcgccg----ggcgcccccggagg----tctcct-aaacactgcatc---t
-ttgcgtcggagtt---t--aaac---a-aattaaacaaaactttcaacaacggatctct
tggttctggcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaatt
cagtgaatcatcgaatctttgaacgcacattgcgccctttggtattccgaagggcatgcc
tgttcgagcgtcatttcaccactcaagc-ctggcttgg-tattgggcg-tcgcgg-----
tgtttccgcgcgccttaaagtcttc---cggctgagctg-tccgtctc-taagcgttgtg
g-atttttcaattcgcttcggagtg--cgggcggc-cg--cggccgtt--aaatcttt--
-attcaaaggttgacctcggatcaggtagggatacccgctgaacttaagcatatc
>Pseudocercospora_chiangmaiensis_TH094_3 Pseudocercospora_chiangmaiensis_TH094.3 700 bp 
-attgaatggctcagtgaggccttcggactggcccagggaggtcggcaacgaccacccag
ggccggaaagttggtcaaactcggtcatttagaggaagtaaaagtcgtaacaaggtctcc
gtaggtgaacctgcggagggatcattactgagtgagggctca---cgccc----------
-gacctccaacccttt-gtg----aacc--aaacttgttgcttcgggggcgaccctgccg
acgacttcgtcgccg----ggcgcccccggagg----tctcct-aaacactgcatc---t
-ttgcgtcggagtt---t--aaac---a-aattaaacaaaactttcaacaacggatctct
tggttctggcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaatt
cagtgaatcatcgaatctttgaacgcacattgcgccctttggtattccgaagggcatgcc
tgttcgagcgtcatttcaccactcaagc-ctggcttgg-tattgggcg-tcgcgg-----
tgtttccgcgcgccttaaagtcttc---cggctgagctg-tccgtctc-taagcgttgtg
g-atttttcaattcgcttcggagtg--cgggcggc-cg--cggccgtt--aaatcttt--
-attcaaaggttgacctcggatcaggtagggatacccgctgaacttaagcatatc
>Pseudocercospora_epispermogonia Pseudocercospora_epispermogonia 700 bp 
------------------------------------------------------------
---------------------------------------------------------tcc
gtaggtgaacctgcggagggatcattaccgagtgagggtttc---ggccc----------
-gacctccaacccttt-gtg----aatc--aaacctgttgcttcgggggcgaccctgccg
ttcg-----cggc----gcggcgcccccggggg----aaatc--aaacactgcgtca--a
tttgtgtcggagta-----cttgt---taa--taaacaaaactttcaacaacggatctct
tggttctggcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaatt
cagtgaatcatcgaatctttgaacgcacattgcgccccgtggtattccgcggggcatgcc
tgttcgagcgtcatttcaccactcgagt-ctgactcgg-tattgggcg-tcgcg------
tttcgatgcgcgccttaaagtt-tc---cggctggaccg-tccgtctc-cgagcgttgtg
gcatc---tgtctcgctagggagccg-cggagggc-gt--tggccgtt--aaacaccc--
-catcaaaggttgacctcggatcaggtagggata---------------------
>Pseudocercospora_longispora 700 bp 
------------------------------------------------------------
---------------------------------------------------------tcc
gtaggtgaacctgcggagggatcattaccgagtgagggccca---cgccc----------
-gacctccaacccttt-gtg----aacc--acacctgttgcttcgggggcgaccctgccg
gcgaactcgtcgccg----ggcgcccccggagg----tctcct-aaacactgcatc---t
-ttgcgtcggagtc---cg-aaac---a-aatcgaacaaaactttcaacaacggatctct
tggttctggcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaatt
cagtgaatcatcgaatctttgaacgcacattgcgccctttggtattccgaagggcatgcc
tgttcgagcgtcatttcaccactcaagc-ctagcttgg-tattgggcg-ccgcgg-----
tg-ttccgcgcgccttaaagtctcc---cggctgagccg-tccgtctc-gaagcgttgtg
g-atttttcaattcgcttcggagtg--cgggcggc-cg--cggccgtt--aaatc-----
--ttccaaggttgacctcggatcaggtagggata---------------------
>Pseudocercospora_paraguayensis 700 bp 
------------------------------------------------------------
---------------------------------------------------------tcc
gtaggtgaacctgcggagggatcattactgagtgagggctca---cgccc----------
-gacctccaacccttt-gtg----aacc--aaacttgttgcttcgggggcgaccctgccg
acgactccgtcgccg----ggcgcccccggagg----tcttct-aaacactgcatc---t
-ttgcgtcggagtt---t--aaac---a-aattaaacaaaactttcaacaacggatctct
tggttctggcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaatt
cagtgaatcatcgaatctttgaacgcacattgcgccctttggtattccgaagggcatgcc
tgttcgagcgtcatttcaccactcaagc-ctggcttgg-tattgggcg-tcgcgg-----
tg-ttccgcgcgccttaaagtcttc---cggctgagctg-tccgtctc-taagcgttgtg
g-atttttcaattcgcttcggagtg--cggatggc-cg--cggccgtt--aaatcttt--
-attcaaaggttgacctcggatcaggtagggata---------------------
>Pseudocercospora_pseudoeucalyptorum Pseudocercospora_pseudoeucalyptorum 700 bp 
------------------------------------------------------------
------------------------------------------------------------
----------------agggatcattactgagtgagggctca---cgccc----------
-gacctccaacccttt-gtg----aaca--catcttgttgcttcgggggcgaccctgccg
gc-actacgtcgccg----ggcgcccccggagg----tctcc--aaacactgcatc---t
-ttgcgtcggagtt---t--aaac---a-aattaaacaaaactttcaacaacggatctct
tggttctggcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaatt
cagtgaatcatcgaatctttgaacgcacattgcgccctttggtattccgaagggcatgcc
tgttcgagcgtcatttcaccactcaagc-ctagcttgg-tattgggcg-tcgcgg-----
---ctccgcgcgccttaaagtc-tc---cggctgagcca-ttcgtctc-taagcgttgtg
g-attttctaattcgcttcggagtg--cgggtggc-cg--cggccgtt--aaatcttt--
-attcaaaggttgacctcggatcaggtagg-------------------------
>Pseudocercospora_subulata 700 bp 
------------------------------------------------------------
------------------------------------------------------------
----------------agggatcattactgagtgagggctca---cgccc----------
-gacctccaacccttt-gtg----aaca--catcttgttgcttcgggggcgaccctgccg
gc-actacgtcgccg----ggcgcccccgaagg----tctcc--aaacactgcatc---t
-ttgcgtcggagtt---ta-aaac---a-aattaaacaaaactttcaacaacggatctct
tggttctggcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaatt
cagtgaatcatcgaatctttgaacgcacattgcgccctttggtattccgaagggcatgcc
tgttcgagcgtcatttcaccactcaagc-ctggcttgg-tattgggcg-tcgcgg-----
---ctccgcgcgccttaaagtc-tc---cggctgagcca-ttcgtctc-taagcgttgtg
g-attttctaattcgcttcggagtg--cgggtggc-cg--cggccgtt--aaatcttt--
-attcaaaggttgacctcggatcaggtagggata---------------------
>Readeriella_eucalypti 700 bp 
------------------------------------------------------------
------------------------------------------------------------
----------------agggatcattactgagtgagggcctt-cgggtcc----------
-gacctccaaccccat-gtt----gtcc--gactctgttgcctcgggggcgacccggccg
tacg-----------gccgcgggcccccggtgg---actact--caactctgcatc---t
-tagcgtctgagtt---taattat----aaatcaattaaaactttcaacaacggatctct
tggttctggcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaatt
cagtgaatcatcgaatctttgaacgcacattgcgccccttggtattccgaggggcatgcc
tgttcgagcgtcattacaccaatcaagc-ctggcttgg-tattgggcg-ccgtggttctt
cggagccgcgcgccctaatgtc-ct---cggctgggccg-tccgcctc-gaagcgttgtg
a--taatacagatcgcttgtgggtg--tggacggt-cg-cgcgccgta--aaaccttt--
---tttcaagttgacctcggatcaggtagggata---------------------
>Teratosphaeria_cryptica 700 bp 
------------------------------------------------------------
---------------------------------------------------------tcc
gtaggtgaacctgcgtagggatcattaccgagtgagggcctc-cgggtcc----------
-gacctccaacccttt-gtg----aacg--catcccgttgcgtcggggccgaccctgccg
cc------------gtgccggggcccccggcgg---acccct--caactctgcatc---t
-ttgcgtctgagtg---ataacga----aaatcaatcaaaactttcaacaacggatctct
tggttctggcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaatt
cagtgaatcatcgaatctttgaacgcacattgcgccccctggtattccggagggcatgcc
tgttcgagcgtcattacaccactccagc-ctcgctggg-tattgggcg-tctcgg-----
---ctccgcgcgcctcaatgtc-tc---cggccgagccg-accgtctc-taagcgttgtg
g-cacaactgtttcgcttccgggac--cggtctgg-cgtcgcgccgtc--aaccccct--
ctctcacaggttgacctcggatcaggtagggata---------------------
>Teratosphaeria_nubilosa 700 bp 
------------------------------------------------------------
---------------------------------------------------------tcc
gtaggtgaacctgcggagggatcattactgagtgcgggcgcc---agccc----------
-gacctcctaccccat-gtt----ttcc--caccacgttgcctcgggggcgacccggccc
cc------------gcgccggggccctcgcagg---acccct--caacgctgcatc---t
-gtgcgtcggagta---atacaac----caatcaattaaaactttcaacaacggatctct
tggttctggcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaatt
cagtgaatcatcgaatctttgaacgcacattgcgccctctggtattccggagggcatgcc
tgttcgagcgtcatttcaccactccagc-cccgctggg-tcttgggcg-ccgcgg-----
--cctccgcgcgcctcaatgtc-tc---cggccgagccg-accgtctc-tcagcgttgtg
g-cactactgtttcgctgacggggac-cggtctgg-cggcgcgccgtt--aaaccctt--
tcaccaaaggttgacctcggatcaggtagggata---------------------
>Teratosphaeria_parva_DQ303003 700 bp 
------------------------------------------------------------
------------------------------------------------------------
----------------agggatcattaccgagtgagggcctc-cgggctc----------
-gacctccaaccccattgta----ttccgacctcttgttgcctcgggggcgacccggcct
tcgg----------gcgtcggggcccccggtgg---accatc--aaactctgcatc---t
ttgacgtctgagta----aatatt----gaatcaatcaaaacttttaacaacggatctct
tggttctggcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaatt
cagtgaatcatcgaatctttgaacgcacattgcgccccttggtattccgaggggcatgcc
tgttcgagcgtcatttcaccactcaagc-ctggcttgg-tattgggcg-ccgcgg-----
-tttgccgcgcgcctcaaagtc-tc---cggctgagcca-actgtctc-taagcgttgtg
g--tttaatcatccgcttgtgagat--cgaaggcgacg----gccgtt--aaacttat--
---tcaaaggttgacctcggatcaggtagggata---------------------
>Teratosphaeria_parva_DQ303005 700 bp 
------------------------------------------------------------
------------------------------------------------------------
--------------ggagggatcattaccgagtgagggcctc-cgggctc----------
-gacctccaaccccattgta----ttccgacctcttgttgcctcgggggcgacccggcct
tcgg----------gcgtcggggcccccggtgg---accatc--aaactctgcatc---t
ttgacgtctgagta----aatatt----gaatcaatcaaaacttttaacaacggatctct
tggttctggcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaatt
cagtgaatcatcgaatctttgaacgcacattgcgccccttggtattccgaggggcatgcc
tgttcgagcgtcatttcaccactcaagc-ctggcttgg-tattgggcg-ccgcgg-----
-tttgccgcgcgcctcaaagtc-tc---cggctgagcca-actgtctc-taagcgttgtg
g--tttaatcatccgcttgtgagat--cgaaggcgacg----gccgtt--aaacttat--
---tcaaaggttgacctcggatcaggtagggata---------------------
>Teratosphaeria_sp_ 700 bp 
------------------------------------------------------------
---------------------------------------------------------tcc
gtaggtgaacctgcggagggatcattaccgagtgagggcccc--cggccc----------
-gacctccaaccccat-gtt----ttcc-aacctctgttgcctcgggggcgacccggccc
c--------------ggccggggccccccgcggacctcaacc--aaaccctgcata---t
-ctgcgtctgagtc---aattgat---aaattcaatcaaaactttcaacaacggatctct
tggttctggcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaatt
cagtgaatcatcgaatctttgaacgcacattgcgcccggtggcattccgccgggcatgcc
tgttcgagcgtcattacaccactccagc-ctggctggg-tattgggcg-tcgcgg-----
ggtccccgcgcgcctcgaagtc-tc---cggccgagccg-tccgtctc-taagcgttgtg
a--tctatcaagccgcttgcgagct--cggggggc-cgtcgcgccgtt--aaacgacc--
-atctcaaggttgacctcggatcaggtagggata---------------------
>Teratosphaeria_suberosa_AY725579 Teratosphaeria_suberosa_AY725579 700 bp 
------------------------------------------------------------
---------------------------------------------------------tcc
gtaggtgaacctgcggagggatcattaccgagtgagcgcctc-cgggcgc----------
-gacctccaaccccat-gtt-----tcc--aaccatgttgcctcgggggcgacccggccg
tccg-----------gccgatcgcccccggtgg---acccct--caactctgcatc---t
-ttgcgtcggagtc---taatgat----aaatcaatcaaaactttcaacaacggatctct
tggttctggcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaatt
cagtgaatcatcgaatctttgaacgcacattgcgccccttggtattccgaggggcatgcc
tgttcgagcgtcatttcaccactcaagc-ctcgcttgg-tattgggcg-ccgcgg-----
-tccgccgcgcgccccaatgt--tc---cggctcagccc-aacgtcct-cgagcgatttg
a---ttacaatcccgctagcaggca--cggagggcgcg--acgccgct--aaacaccc--
-catcacaggttgacctcggatcaggta---------------------------
>Teratosphaeria_suberosa_DQ303046 Teratosphaeria_suberosa_DQ303046 700 bp 
------------------------------------------------------------
------------------------------------------------------------
----------------agggatcattaccgagtgagcgcctc-cgggcgc----------
-gacctccaaccccat-gtt----atcc--aaccatgttgcctcgggggcgacccggccg
tccg-----------gccgatcgcccccggtgg---acccct--caactctgcatc---t
-ttgcgtcggagtc---taatgat----aaatcaatcaaaactttcaacaacggatctct
tggttctggcatcgatgaagaacgcagcgaaatgcgataagtaatgtgaattgcagaatt
cagtgaatcatcgaatctttgaacgcacattgcgccccttggtattccgaggggcatgcc
tgttcgagcgtcatttcaccactcaagc-ctcgcttgg-tattgggcg-ccgcgg-----
-tccgccgcgcgccccaatgtc-tc---cggctcagccc-aacgtcctcgaagcgatttg
a---ttacaatcccgctagcaggca--cggagggcgcg--acgccgct--aaacaccc--
-catcacaggttgacctcggatcaggta---------------------------
