>Ighermia_pinifolia 721 bp 
tcgaagcctataaagcagaaagacccgtgaacgtgtaacaacaatagcgcgtcataggga
tcaggcttttcatttgtgacctatggac-cctcgtcgatttgg-catccatggacgcctc
ttcggagcctgccttgggtgtc-agaaaaggcgtaacaaacaaa-gcccggcgcggcatg
tgccaaggaaaactcaaatttcaggcaaggcgtcatgccatgttgccccgttcgcggtgg
-tgtgcatgggatgtggcttctttttaaccacaaacgactctcggcaacggatatctt-g
stcacgcatcgatgaagaacgtagcaaaatgcgatacttggtgtraatt-----------
-----------------------------------------ctcggctgagggcacgtmt
gcctgggcgtcacgcat--cggtcgctccgtcatcttgcctcctcaaaggggtatactgg
ataggagcggatactagtctcccgtgcc-tgatg-gtgcggttggccaaaatagaagtct
ccttcgcaaggacacagggcaagtggtggttgacaaaaccttagtctcgtgttgtgtgtc
ctgagttgtaaagccgaagacctcgtaagtagccctaacgtgttgtctagtgacgacgct
tcgaccgcgaccccaggtcag-----------------------
>Pluchea_purpurascens 712 bp 
tcaaaacctgcatagcagaacgacccgagaacctgtacaaactgtctggtgtcaaagggg
tcaggcttgatgtttgaccgttgtgactgccttgttgatttgcccatccatggtt-cccc
tttggggtctgcgtggtccgtc-agaatcaacacaacaaccaaagccccggcacggcatg
tgccaaggacaact-taacttgaagcaagggcctatgccatgccaccacgttcgcgatgg
ctgtgcatgacatgtggcttctttgtaacca-----------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------attgcgtcgcccccctcatcgtgcttcccttatggggatacacgg
ggtcgggcggatattggtctcccgtttc-cgaagcttacggatgaccaaaataggagtcc
cctt-ggacggacgcacgacaagtggtggttgactaaaccttcgtctcgtgtcgtg----
tttagccgtgaggggaaggcaacacaaaaatcccacagcatgtcgtcttgtgacgatgct
tcgacc--------------------------------------
>Rhodogeron_coronopifolius 712 bp 
ttgaagcctgcatagcaaaacaacctgagaacctgtacaaattgtctggtgtcaca-ggg
tcgggcttgatgttcgacccatgtggccgccttgttgatttgtccatccatggtcacccc
tttggggtcttcgtgggccgtc-ggaatcaacacaacaaccaaacccccggcacggcatg
tgccaaggaaaact-gaacttgaagcaatggcttatgccatgccaccacgttcgcgtcgg
ctgtgcaaggcatgttgcttctttgtaaccacaaacgactctcggcaacggatatctcgg
ctcacgcatcgatgaagaacgtagcaaaatgcgatacttggtgtgaattgcagaatcccg
tgaaccatcgagtttttgaacgcaagttgcgcccgaagccattcggctgagggcacgtct
gcctgggcgtcacatatcgcgtcgcccccctcatcgtgcctccctgat-gggatgtacgg
ggtggggcggatattggtctcccgttc--tgacg-gtgcggatggccaaaataggagtcc
cctt-ggacggacgcacgataagtggtggttgactaaacccttgtttcgtgtcgtgtgtt
ttaatctgtgaggggaaggaaacacaagaaacccccaacgtgtcgtcttgtgacgatgct
ttgaccgcgaccccaggtcaggcgggactacccgctgagtttaa
>Sachsia_Tricephala 712 bp 
tcgaagcctgcatagcagaacgacctgagaacctgtacaaattgtccggtgtcatagggg
tcgggcttgatgtcccacccatgtggctaccttgttgatttgaccatcctcggtcacctg
tttgggctctgccgg----act-gtaatcaacacaacaa--gaagccccggcacggcatg
tgccaaggaaaaca-gaacttgaag-aagggcttatgccatgccaccacgttcgcgtcgg
ctgtgcaaggcatgtggcttctttgtaaccacaaacgactctcggcaacggatatctcgg
ctcacgcatcgatgaagaacgtagcaaaatgcgacacttggtgtgaattgcagaatcccg
tgaaccatcgagtttttgaacgcaagttgcgccagaagccattcggctgagggca-gtct
g-ctgggcgtcacgtatcgcgtcgcccccctcat-gtgcctccctcatggggatgcacgg
ggtggggcggatattggtctcccgttcc-tgaag-gtgcggatggccaaaataggagtcc
cctt---acggacgcacgacaagtggtggttcactaaaccctcgtctcgtgtcgtgtgtt
ttgaaccgtgaagggaaggcaacacaagaaa-ccccaacgtgtcgtcttgtgacgatgct
tcgaccgcgaccccaggtcaggcgg-------------------
>Sachsia_divaricata_1 712 bp 
tcgaagcctgcatagcagaacgacctgagaacctgtacaaatcgtccggtgtcatagggg
tcgggcttgatgttcgacccatgtggctgccttgttgatttgcccatcctcggtcacctc
tttggggtcttccgggactgtc-ggaatcaacacaacaaccaaa-ccccggcacggcatg
tgccaaggaaaact-gaacttgaagcaagggcttattccatgccaccacgttcgcgtcgg
ctgtgcaaggcatatggcttctttgtaaccacaaacgactctcggcaacggatatctcgg
ctcacgcatcgatgaagaacgtagcaaaatgcgatacttggtgtgaattgcagaatcccg
tgaaccatcgagtttttgaacgcaagttgcgcccgaagccattcggctgagggcacgtct
g-cctggcgtcacgtatcgcgtcgcccccctcatcgtgcctccctgatggggatgcacgg
ggtggggcggatattggtctcccgttccttcgag-gtgcggatggccaaaataggagtcc
cctt-ggacggacgcacgacaagtggtggttgactaaaccctcgtctcgtgtcgtgtgtt
ttgaaccgtgaagggaaggcaacacaagaaacccccaacgtgtcgtcttgtgacgatgct
tcgaccgcgaccccaggtcaggcgggact---------------
>Sachsia_divaricata_2 715 bp 
tcgaagcctgcatagcagaacgacctgagaacctgtacaaatcgtccggtgtcatagggg
tcgggcttgatgttcgacccatgtggctgccttgttgatttgcccatcctcggtcacctc
tttggggtcttccgggactgtc-ggaatcaacacaacaaccaag-ccccggcacggcatg
tgccaaggaaaact-gaacttgaagcaagggcttattccatgccaccacgttcgcgtcgg
ctgtgcaaggcatatggcttctttgtaaccacaaacgactctcggcaacggatatctcgg
ctcacgcatcgatgaagaacgtagcaaaatgcgatacttggtgtgaattgcagaatcccg
tgaaccatcgagtttttgaacgcaagttgcgcccgaagccattcggctgagggcacgtct
g-ctgggcgtcacgtatcgcgtcgcccccctcatcgtgcctccctgatggggatgcacgg
ggtggggcggatattggtctcccgttccttcgag-gtgcggatggccaaaatargagtcc
cctt-ggacggacgcacgacaagtggtggttgactaaaccctcgtctcgtgtcgtgtgtt
ttgagccgtgaagggaaggcaacacaagaaacccccaacgtgtcgtcttgtgacgatgct
tcgaccgcgaccccaggtcaggcgg-------------------
>Sachsia_polycephala_BAHAMAS 712 bp 
tcgaagcctgcatagcagaacgacctgagaacctgtacaaatcgtccggtgtcatagggg
tcgggcttgttgtccgacccatgtggctgccttgttgatttgcccatcctcggtcacctc
tttggggtcttccgggactgtctgcaatcaacacaacaa-gaaacccccggcacggcatg
tgccaaggaaaact-gaacttgaag-aagggcttattccatgccaccacgttcgcgtcgg
ctgtgcaaggcatatggcttctttgtaaccacaaacgactctcggcaacggatatctcgg
ctcacgcatcgatgaagaacgtagcaaaatgcgatacttggtgtgaattgcagaatcccg
tgaaccat-gagtttttgaacgcaagttgcg-ccgaagccattcgg-tgagggcacgtct
g-ctgggcgtcacgtatcgcgtcgcccccctcatcgtgccttcctgatggggatgcacgt
tgtggggcggatattggtctcccgttcc-tggag-gtgcggatggccaaaataggagtcc
cctt-ggacggacgcacgacaagtggtggttgactaaaccctcgtctcgtgtcgtgtgtt
ttgaaccgtgaagggaaggcaacacaagaaacccccaacgtgtcgtcttgtgacgatgct
tcgaccgcg-----------------------------------
>Sachsia_polycephala_FLORIDA 712 bp 
tcgaagcctgcatagcagaacga-ctgagaacctgtacaaatcgtccggtgtcatagggg
tcgggcttgatgtccgacccatgtggctgccttgttgatttgcccatcctcggtcacctc
tttggggtcttccgggactgtc-ggaatcaacacaacaaccaaacccccggcacggcatg
tgccaaggaaaact-gaacttgaagcaagggcttattccatgccaccacgttcgcgtcgg
ctgtgcaaggcatatggcttctttgtaaccacaaacgactctcggcaacggatatctcgg
ctcacgcatcgatgaagaacgtagcaaaatgcgatacttggtgtgaattgcagaatcccg
tgaaccatcgagtttttgaacgcaagttgcgcccgaagccattcggctgagggcacgtct
gcctgggcgtcacgtatcgcgtcgcccccctcatcgtgccttcctgatggggatgcacgt
tgtggggcggatattggtctcccgttcc-tggag-gtgcggatggccaaaataggagtcc
cctt-ggacggacgcacgacaagtggtggttgactaaaccctcgtctcgtgtcgtgtgtt
tt-aaccgtgaagggaaggcaacacaagaaacccccaacgtgtcgtcttgtgacgatgct
tcgaccgcacccc-aggtc-------------------------
